### PR TITLE
fix(Core/Movement): Set proper flying animations for creatures with I…

### LINKED ISSUE #7579: Some flight NPCs have bugs
### Current Behaviour

https://youtu.be/bOtG_1fS5yI

NPC `Stormpeak Wyrm` (id 29753) abnormal movement. Unable to fly

### Expected Blizzlike Behaviour

It will fly back and forth

### Source

_No response_

### Steps to reproduce the problem

1. .go 7403.907227 -1207.365234 902.727600 571
2. Watch NPC flying in the sky

### Extra Notes

It may be caused by this commit
https://github.com/azerothcore/azerothcore-wotlk/commit/e35e47c2f72115e50d924cd16042eb2addc3de1f

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5c97632cc358b865008d0b2861317081685a1295

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

### LINKED ISSUE #7584: [Burning Steppes] Rogue Black Drakes clipping through ground when gliding
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1557

Rogue Black Drakes (https://wowgaming.altervista.org/aowow/?npc=14388) fighting with npcs on the Searing Gorge plateau are clipping through ground when flying around. Everytime you take a griffon and fly over you can see them below and if they move around it just looks wierd.

### Expected Blizzlike Behaviour

They should fly around higher so they do not clip through the textures.

### Source

Mobs should not clip through ground.

### Steps to reproduce the problem

1. Teleport to any Rogue Black Drake (entry 14388), GUID 53999 for example
2. Observe them flying around when they are not fighting with the npcs
3. See that they clip through the ground

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC (888549b).
Entry: 14388 with only four spawns.

They are okay, when they just stand still (in air :p):
unknown_2021 08 27-11 59_1

But often clip through the ground or walls when moving/gliding:
unknown_2021 08 27-11 57

### PR DESCRIPTION
**Pull request by UltraNix**
…NHABIT_GROUND.

Fixes #7579

## Issues Addressed:

- Closes #7579
- Closes #7584

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. `.go 7403.907227 -1207.365234 902.727600 571`
2. Watch NPC flying in the sky

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by mpfans — APPROVED** [review]
Tested, work!They are no longer crawling!
image

**Comment by FrancescoBorzi** [comment]
good job @UltraNix and @mpfans

**Comment by Mesielecat** [comment]
Details, this solution causes that the fight with Sindragosa, she to start the fight under the floor. Its happens in Malygoss too and maybe its related with z coordinates of flying creatures

**Comment by UltraNix** [comment]
@Mesielecat Just open new tickets with mobs that have been broken by that commit.

**Pull request merged**
