### PR TITLE
refactor(Core/Trainer): Import TC handling of Trainers

### PR DESCRIPTION
**Pull request by Kitzunu**
Co-Authored-By: Shauren <shauren.trinity@gmail.com>
Co-Authored-By: Ghaster <11392454+Ghaster@users.noreply.github.com>

cp https://github.com/TrinityCore/TrinityCore/commit/bf3ab6d9c4366dae1d34957813e3fbf40ac8532b

## Changes Proposed:
-  Import TC's handling of Trainers
-  All SQL's are directly taken from the latest TDB (TDB 335.21041)

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5420

## Tests Performed:

- 
- 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4885 necessary to finish this in an easy way

**Comment by Winfidonarleyan** [comment]
Time nice prs

**Comment by Kitzunu** [comment]
Nice but a pain in the ass

**Comment by Kitzunu** [comment]
@UltraNix if you are bored some time and want to port from TC, tell me and I can give you access to my fork x)

**Comment by UltraNix** [comment]
@Kitzunu Thanks, but I am not bored :)

**Comment by Kitzunu** [comment]
Was worth a shot xD

**Comment by Winfidonarleyan** [comment]
Maybe need first https://github.com/WarheadCore/WarheadBand/commit/847df113f1e0ed9ead2213704731f6efca7929aa

**Comment by Kitzunu** [comment]
maybe, atm I just dont have time to look at what I need to fix. Most likely next week

**Comment by Kitzunu** [comment]
I will wait for https://github.com/azerothcore/azerothcore-wotlk/issues/5575 before I continue with this

**Comment by Winfidonarleyan** [comment]
1-3 days

**Comment by Kitzunu** [comment]
I am making a new PR so hopefully I can remember what I am doing lol

**Pull request closed without merging**
