### PR TITLE
fix(Events/Midsummer): fix AOE circle bug on Midsummer Torch Catching

### LINKED ISSUE #12392: [Midsummer] Torch Catching incorrect behaviour
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

There are three things wrong with [Torch Catching](https://wowgaming.altervista.org/aowow/?quest=11657) and [More Torch Catching](https://wowgaming.altervista.org/aowow/?quest=11924) (along with Horde counterparts I presume):
1. [Unlit Torches](https://wowgaming.altervista.org/aowow/?item=34833) shouldn't be an "AoE targetable" skill
2. Torches do not cast a circular shadow on the floor
3. Torchs tend to either "hit the ground prematurly", not matching its animation, or just straight up fail randomly (correlation with Master Fire Eater's breath?)

https://www.youtube.com/watch?v=Upxxoyrrk0Q

### Expected Blizzlike Behaviour

1. Torch should be thrown into the air the moment the item is used
2. Torches should cast a shadow in form of black circle directly under the torch's location
3. Torches hitbox should match their animation/texture all the time and they shouldn't explode 2 meters above the ground

### Source

https://www.youtube.com/watch?v=Pjnlfb2_PiE
_Video from 2009_

### Steps to reproduce the problem

1. Take the (More) Torch Catching Quest
2. Throw the torch

### Extra Notes

Anjachan triager notes:
Item - Unlit Torches (ID 34833) - shouldn't give AOE circle on use; while the torch is in the air it should cast a circular shadow on the ground so the player can track it and catch it; also hitbox on catching a torch is pretty tricky

my reproduction of the issue: https://youtu.be/rgVW7TwdURY

prooves of correct behaviour: https://www.youtube.com/watch?v=2-1oZfZlPME

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/6983903a89c556c0ca1239101cffc38098d6b081

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by sudlud**
- using "Unlit Torches" no longer shows an AOE circle
- Throwing the first torch now correctly requires nearby Midsummer Bonfire

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #12392
- Closes chromiecraft/chromiecraft#3667

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Thanks to @heyitsbench, the sniffs gave the hint for the correct spell id

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

.event start 1
.quest add 11923
.go c 245602
use "Unlit torches" - should fail - "Requires Midsummer Bonfire"
walk close to bonfire
use "Unlit torches" to throw torch
observe no AOE circle, torch gets thrown and can be catched to rethrow

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Ready to be reviewed 🙃

**Comment by elthehablo** [comment]
merge conflicts :)

**Review by elthehablo — APPROVED** [review]

**Comment by sudlud** [comment]
> merge conflicts :)

Will update later today

**Comment by sudlud** [comment]
@elthehablo merge conflicts should be fixed now :)

**Pull request merged**
