### PR TITLE
fix(DB): Conditions for quest Replacement Vial

### LINKED ISSUE #6535: Quest "Replacement Phial" is available too early
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/923

##### CURRENT BEHAVIOUR:

After accepting the quest “Back to Uldaman”, Talvash will give the player a phial (a quest item) for later use, in case this phial is lost before completing the next-quest-in-chain “Find the Gems” or the quest after it "Restoring the Necklace", the player could choose to do an extra quest “Replacement Phial” to get another phial so the questline may progress.

Currently the quest “Replacement Phial” is available to the player as soon as accepting “Back to Uldaman”, even if “Talvash's Phial of Scrying” is still in the player’s possession.
WoWScrnShot_061821_022305

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The quest should be available to the player after accepting “Back to Uldaman” and until maybe finishing “Restoring the Necklace”(If the player chooses to abandon it and later regrets and wants to do it), but only when the given phial is lost.

##### SOURCE:

https://classic.wowhead.com/quest=3375/replacement-phial#comments:id=3154153

##### STEPS TO REPRODUCE THE PROBLEM:

1. Quests require a minimal level 37 character, then add the quest [Back to Uldaman(quest=2200)](https://classic.wowhead.com/quest=2200/back-to-uldaman) and [the related phial(item=7667)](https://classic.wowhead.com/item=7667/talvashs-phial-of-scrying) if commands support. Alternatively you can add Shattered Necklace(item=7666) which starts the whole questline.
2. Talk to [Talvash del Kissel(npc=6826)](https://classic.wowhead.com/npc=6826/talvash-del-kissel) in the mystic ward section of Ironforge.
3. Confirm quest [Replacement Phial(quest=3375)](https://classic.wowhead.com/quest=3375/replacement-phial) is available as soon as picking up quest "Back to Uldaman".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker),
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 2a2e54d8c586) :

WoWScrnShot_062421_123332
WoWScrnShot_062421_123602
WoWScrnShot_062421_123614

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99451442-quest-replacement-phial-is-available-too-early?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Added conditions for quest. Item must not be on inventory or bank.

## Issues Addressed:

- Closes #6535
- Closes https://github.com/chromiecraft/chromiecraft/issues/923

## SOURCE:

Comments on
https://classic.wowhead.com/quest=3375/replacement-phial

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Check issue for steps

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
Startup erros, please fix them 👍 
```
Item condition has 0 set for item count in value2 (0), skipped
Item condition has 0 set for item count in value2 (0), skipped
```

**Comment by claudiodfc** [comment]
#### Test case 1

- Player level 37
- Has quest 'Back to Uldaman' and item not in inventory

image


#### Test case 2

- Player level 37
- Doesn't have quest 'Back to Uldaman' and item not in inventory

image

**Comment by claudiodfc** [comment]
@Nefertumm can you review again?

**Comment by Nefertumm** [comment]
Sure, I'm at my cousin's house but I'll ask later for a PC and give your review! I find github phone app disgusting kek

**Review by Nefertumm — APPROVED** [review]
Seems ok now :)

**Review by acidmanifesto — APPROVED** [review]
Just following up. the codefactor test failure has NOTHING to do with this PR and is unrelated to this PR.

**Pull request merged**
