### PR TITLE
fix(DB): Dolanar First Aid Trainer Dialogues

### LINKED ISSUE #10459: First aid trainer Byancie dialogue text
https://github.com/chromiecraft/chromiecraft/issues/2895

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

The first aid trainer in Dolanaar, Byancie, gives the dialogue text about further training no matter what your skill is in first aid.
`The esteemed Doctor Gustaf VanHowzen can train you further. He can be found in Theramore treating the wounded at the barracks.`
https://wowgaming.altervista.org/aowow/?npc=6094

### Expected Blizzlike Behaviour

Byancie's dialogue text should change depending on your level in first aid, like other profession trainers.

### Source

_No response_

### Steps to reproduce the problem

1. Create a new night elf character
2. Walk to Dolanaar and talk to Byancie

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f3774fd9ac8241994396426e6c5f9246ce56400b

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by neifion-00000000**
Dialogues are currently wrong, this PR is "what we know" so far and should be finished later with a wotlk sniff.
related issue #10459

Thanks to Malcrom for his help in understanding the packets.
Also thanks again Malcrom for the skeleton used here, and M'dic for the exact same thing later.

THIS IS WIP but needs sniffs from WOTLK to be accurate.   It is usable in this form, but likely only correct to 1.x/2.x versions of the game.

I believe the WOTLK version will have neither of the 2nd or 3rd dialogues (they exist but are obsolete in game) and possibly a dialogue sending you to OL or maybe even NR for 300/375 but this is pure speculation.

## Changes Proposed:
-  Fixes DB entry for gossip to correct entry.
-  Forms a skeleton conditional list that will need changed to be accurate to wotlk.  While theoretically possible to either just use it, or to create based on historical information available, using it would be TBC-like, and creating on historical information would pollute the db with incorrect entries, as there are correct entries to sniff. 

## Issues Addressed:

- Closes #10459 

## SOURCE:

Sniffs, and videos in bug report. 

## Tests Performed:

- Created a character and set firstaid to various levels testing dialogue changes. 

## How to Test the Changes:

1. .go c 47499 and talk to between each step to view dialoges
2. .setskill 129 1 75
3. .setskill 129 150 150
3. .setskill 129 225 225

## Known Issues and TODO List:

As mentioned above, this needs WOTLK sniffs to be accurate.  There are workable solutions without it, but since the correct values are ultimately sniff-able they would certainly be hacks.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by neifion-00000000** [comment]
for my fans 
image

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
> for my fans 
> image
> 

Fansonly sub when?

**Comment by acidmanifesto** [comment]
Per user's request. Marked as wip.

**Comment by neifion-00000000** [comment]
> > for my fans
> > image
> 
> Fansonly sub when?

catch me on OnlyMaps

**Comment by acidmanifesto** [comment]
this wasnt suppose to be merged pending research. @claudiodfc @temperrr @FrancescoBorzi

**Comment by acidmanifesto** [comment]
@claudiodfc was did you removed the WIP tag and marked it as ready for review and waiting to be tested when it was not at all?

**Pull request merged**
