### PR TITLE
refactor(Core/UnitAI): Update target selector

### PR DESCRIPTION
**Pull request by Maelthyrr**
## Changes Proposed:
-  Allow to exclude tank from the target selectors

## Issues Addressed:

- Step for https://github.com/azerothcore/azerothcore-wotlk/issues/5985

## SOURCE:

Cherry-pick: https://github.com/TrinityCore/TrinityCore/commit/e2a1ccd118d129b96e09ff1a15ed0adb1d4a3897

## Tests Performed:

- In progress

## How to Test the Changes:

1. Check bosses impact by this PR

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Review by Nefertumm — APPROVED** [review]

**Comment by Maelthyrr** [comment]
Tested and work fine.

- [X] Target selector behavior didn't change (test in molten core)
- [X] Exclude the tank from the targetlist work also (test with baron geddon set to false for withTank)

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Target selectors are broken currently. The logic is reversed, if you set **withTank** it will **never** target tanks, you have to set **withTank** to false for them to cast anything on the tanks...

**Comment by Nyeriah** [comment]
.go creature id 9018

image

And notice she never casts Shadowword pain on tanks, despite it being **withTank** being set to true by default.

**Comment by Rdyx** [comment]
It seems `SelectedTargetMethod::MinDistance` and `SelectedTargetMethod::MaxDistance` are reversed too.

Based on Assembly of Iron encounter (ulduar) tactic, once raid has reached phase 2, Steelbreaker (id 32867) should cast Static Disruption (id 63494) on the **furthest** target. Meanwhile, in assembly of iron script, it's using `SelectedTargetMethod::MinDistance` to get the target. This felt counter-intuitive and as expected, changing it to `SelectedTargetMethod::MaxDistance` made Steelbreaker to only cast Static Disruption on the **closest** target to him.

Somehow, the wrong script make the usual encoutner tact works fine, but I guess there's still something wrong there ^^

**Comment by Maelthyrr** [comment]
> It seems `SelectedTargetMethod::MinDistance` and `SelectedTargetMethod::MaxDistance` are reversed too.
> 
> Based on Assembly of Iron encounter (ulduar) tactic, once raid has reached phase 2, Steelbreaker (id 32867) should cast Static Disruption (id 63494) on the **furthest** target. Meanwhile, in assembly of iron script, it's using `SelectedTargetMethod::MinDistance` to get the target. This felt counter-intuitive and as expected, changing it to `SelectedTargetMethod::MaxDistance` made Steelbreaker to only cast Static Disruption on the **closest** target to him.
> 
> Somehow, the wrong script make the usual encoutner tact works fine, but I guess there's still something wrong there ^^
> 
> Target line is L347 in boss_assembly_of_iron.cpp
> 
> ```c++
> if (Unit *pTarget = SelectTarget(SelectTargetMethod::MinDistance, 0, 0, true))
> ```
> 
> How to reproduce:
> 
> * Get 2 accounts in ulduar and start assembly of iron encounter with both of them
> * Kill either Brundir or Molgeim to start phase 2
> * Split apart the 2 characters and wait for Steelbreaker to cast Static Disruption on the furthest target (if `::MinDistance` is set in script. Else, wait for Steelbreaker to cast Static Disruption on the closest target)

I think to know where is the issue. I will look tomorrow.

**Pull request merged**
