### PR TITLE
chore(DB/VerifiedBuild): Creatures 3.2.2

### PR DESCRIPTION
**Pull request by Knindzagxg**
Transfering from SC by @FrancescoBorzi request.

Build update for 3.2.2 creatures.

### CODE REVIEW

**Comment by Geekena** [comment]
tested
no error or problems

**Comment by Helias** [comment]
I can't see any changes here :/

**Comment by FrancescoBorzi** [comment]
@Knindzagxg probably you forgot to add the actual SQL :)

**Comment by Knindzagxg** [comment]
Sorted.
Dunno how the heck it didnt copy xP

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Pull request merged**
