### PR TITLE
feat(Core/Database): Introduce a module db

### PR DESCRIPTION
**Pull request by Kitzunu**
- Introduce acore_module
    - Placeholder database to be used by modules with full core support
    - AutoUpdater is supported
    - Introduce `module_strings`, just like acore_strings, but where modules can store custom strings identified by a custom module identifier

## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes 

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

**NB In order to start the WorldServer you need to add DatabaseInfo in .conf file from .dist file** 

**In order to have AutoUpdater working you need to update Updates.EnableDatabases = 15 in .conf file. This is so that the new DBC and Module databases are included**

If you HAVE edited the config option, you will be presented with the following prompt to auto-create the database and populate it.
image

## Known Issues and TODO List:

- Actually implement module_string in a good way

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Perhaps a good time to try and address https://github.com/azerothcore/azerothcore-wotlk/issues/14766?

**Comment by Kitzunu** [comment]
No cant do that in the scope of this PR. That need Winfis DB rewrite PR I think

**Comment by Kitzunu** [comment]
I really want to store and sort module strings with module name, but I can't understand how to store it in the store

**Comment by Kitzunu** [comment]
Preferably I want to keep it 
```sql
  `module` varchar(12) NOT NULL DEFAULT NULL COMMENT 'Unique module identifier' COLLATE utf8mb4_unicode_ci,
  `entry` int unsigned NOT NULL DEFAULT '0',
  `content_default` text NOT NULL DEFAULT NULL COLLATE utf8mb4_unicode_ci NOT NULL,
  ```
Where the module identifier is stored as a string, this is because it can have a greater uniqueness and less conflict between modules. A module name is always unique, while if we wanted to identify it with an integer two modules could decide to use the same.

Also my plan is that the module identifier for the specified module should be stored in a header file of the module.

**Comment by Kitzunu** [comment]
maybe I pick this up at a later date. I cba and don't have the patience to figure it out atm

**Pull request closed without merging**
