### PR TITLE
fix(Core/Spells): SPELL_AURA_DAMAGE_SHIELD auras should be modified b…

### LINKED ISSUE #4363: [Spell] Thorns does not check for Nature resistance [$10]
### CURRENT BEHAVIOUR:
The damage reflected when being struck while buffed with "Thorns" does not check for resistance. It hits 100%.

### EXPECTED BLIZZLIKE BEHAVIOUR:
Since it is a spell from a certain school and clearly state it deals "Nature Damage" it should be affected by resistance.

### STEPS TO REPRODUCE THE PROBLEM:
`UPDATE acore_world.creature_template SET resistance1=5000, resistance2=5000, resistance3=5000, resistance4=5000, resistance5=5000, resistance6=5000 WHERE entry=299;`

create a druid
.level 79
.learn all my spells
.tele Northshire
Buff thorns. Get hit by a "Diseased Young Wolf". Note how the thorns damage is not affected by the mobs 5000 resistance.

### EXTRA NOTES:
image
image
[Gamepedia](https://wow.gamepedia.com/Thorns) does not mention resistances not applying in either way. Only the school is mentioned.

### AC HASH/COMMIT:
879468506f8e 2021-01-25 20:50:53

### OPERATING SYSTEM:
OS:
Windows 10 pro 64

### MODULES:
none

### OTHER CUSTOMIZATIONS:
No customizations at all

<bountysource-plugin>

---
There is a **[$10 open bounty](https://www.bountysource.com/issues/96197953-spell-thorns-does-not-check-for-nature-resistance?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…y absorbs and resistance.

Fixed #4363.

## Changes Proposed:
-  Added `Unit::CalcAbsorbResist` to `SPELL_AURA_DAMAGE_SHIELD` handler.

## Issues Addressed:
- Closes #4363.

## Tests Performed:

- Tested ingame with druid and Diseased Young Wolf.

## How to Test the Changes:

1. Create a druid
2. `.learn all my class`
3. `.tele Northshire`
4. Apply Thorns on self
5. Get hit by a Diseased Young Wolf and observe combat log.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested
image

**Comment by UltraNix** [comment]
@pklloveyou This is not in Northshire? Did you apply the SQL from #4363?

**Comment by pklloveyou** [comment]
Let me have a try

**Comment by pklloveyou** [comment]
image
 Tested

**Comment by UltraNix** [comment]
It tells nothing - show combat log.

**Comment by pklloveyou** [comment]
image

**Comment by UltraNix** [comment]
Then you tested in the wrong way. Create a night elf druid and follow `How to Test the Changes` section with applying this sql:
`UPDATE acore_world.creature_template SET resistance1=5000, resistance2=5000, resistance3=5000, resistance4=5000, resistance5=5000, resistance6=5000 WHERE entry=299;`

**Comment by UltraNix** [comment]
What is your level? What rank of Thorns used?

**Comment by Sedatyf** [comment]
Hey @UltraNix, I tried to test your PR but it seems the SQL request from the issue doesn't work for me. I looked into the ``creature_template`` table, and there is no resistance1, resistance2, resistance3, ect. columns. So the SQL request doesn't work and I can't test as intended.

I tried something else. I looked into the ``acore_world`` database and I found ``creature_template_resistance``. I added an entry for Young Wolf with id 299 with this following request
```sql
INSERT INTO `acore_world`.`creature_template_resistance` (`CreatureID`, `School`, `Resistance`, `VerifiedBuild`) VALUES ('299', '1', '5000', '12340');
```

I changed every resistance but no luck, nothing worked. Do you have more informations on how to test reproduce the issue? @55Honey you may have more information as well.

**Comment by 55Honey** [comment]
These are the instructions to test it from the linked issue.

UPDATE acore_world.creature_template SET resistance1=5000, resistance2=5000, resistance3=5000, resistance4=5000, resistance5=5000, resistance6=5000 WHERE entry=299;

create a druid
.level 79
.learn all my spells
.tele Northshire
Buff thorns. Get hit by a "Diseased Young Wolf". Note how the thorns damage is not affected by the mobs 5000 resistance.

**Comment by Sedatyf** [comment]
Yeah that's what I'm talking about in my previous comment. I tried to execute this SQL command
```sql
UPDATE acore_world.creature_template SET resistance1=5000, resistance2=5000, resistance3=5000, resistance4=5000, resistance5=5000, resistance6=5000 WHERE entry=299;
```
But there is no resistanceX column in the ``acore_world.creature_template``. I'm trying to import again a fresh DB

**Comment by UltraNix** [comment]
@Sedatyf  Yep - forgot about it. The proper sql:
```
INSERT IGNORE INTO `creature_template_resistance` VALUES
(299,3,5000,0);
```

**Comment by Sedatyf** [comment]
Thank you @UltraNix! So I tested your PR and thorns no longer goes through resistance ✔️ (please see video below)
Nice work!

https://user-images.githubusercontent.com/59012307/115995716-a126e100-a5dc-11eb-9c65-05fdba991e91.mp4

PS: Can you explain me what ``VerifiedBuild`` means? I tried with my own SQL request, it looks like yours but I put ``12340`` and it didn't work
PS2: How do you know what school id is which school resistance?

**Comment by UltraNix** [comment]
3 is nature resistance - got from `SpellSchool` enum in core.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by UltraNix** [comment]
What are waiting for?

**Pull request merged**
