### PR TITLE
fix(DB/Quest): Teron Gorefiend chaining

### PR DESCRIPTION
**Pull request by Kitzunu**
Currently, the chaining for Teron Gorefiend quests is wrong.

Fixed it here https://github.com/TrinityCore/TrinityCore/commit/974ede899c40391d5101cf3dd67ba9dc8adebcc3 so might as well fix it here :P

Tests: Not tested on ACore

Fixes: No open issue

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
> Tests: Not tested on ACore
> 
> Fixes: No open issue

please test your PR before submitting it :)

also, ideally, it would be better (but not strictly necessary) to open an issue that describes the bug and link it the PR

**Comment by Kitzunu** [comment]
Well, for some reason I cannot get my server to work xd

Get stuck at realm screen after trying to connect to world server. (Yes I followed the wiki and tried to get help from ppl in disc :()

As for issue I can thunk of that/include it in the PR report. Was very lazy today, sorry 😃

**Comment by FrancescoBorzi** [comment]
@Kitzunu maybe this can help: https://stackoverflow.com/questions/54732989/stuck-at-retrieving-character-list

**Comment by Kitzunu** [comment]
Ok I will try tomorrow after work. Would be some much nicer for me to test my stuff xd

Btw, if it is for any help, I tested it on TC and it works flawless

**Comment by Si1ker** [comment]
- SQL 👍 
- Quests 👍 
I've took references from RS DB and Wowhead for quests and completing them in the blizzlike order. 🚀

**Pull request merged**
