### PR TITLE
fix(Core): Auth/World conf.dist corrections

### PR DESCRIPTION
**Pull request by poszer**
Auth/World conf.dist corrections

##### CHANGES PROPOSED:

-  Typo, grammar corrections.
-  Rate.Mining.Amount changed to correct config Rate.Talent  (It was set to Rate.Talent for mining amount using default value: 1 which is totally wrong. - Rate.Talent is for talents points per level.)

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1701

##### TESTS PERFORMED:

Yes. Everything is okay, it's just come grammar corrections and typos. Found also one incorrect configuration there (That can be tested):

    Rate.Mining.Amount  <--- Incorrect
        Description: Rate for minimum/maximum times a deposit can be used.
        Default:     1
        Rate.Talent = 1

The correct is :

    Rate.Talent <--- Correct
        Description: Talent point rate.
        Default:     1
        Rate.Talent = 1

Info:
Rate.Talent = 1 is the normal (default) starting at level 10 by giving you 1 talent point for each level, 71 in total. 

Rate.Talent = 2 is the double rate. So if you get level 71 you will receive 142 talents points.

##### HOW TO TEST THE CHANGES:

The only thing which can be tested about this is Rate.Talent configuration (Value: 1 & 2)
1. Set it to 1 and level up to 11(lvl)
2. Check how much talent points you are receiving using configuration Rate.Talent = 1
3. After that set configuration to Rate.Talent = 2
4. Level up again to 11 lvl (You will get double talent points)

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
Only comment-strings have been changed here, no need to test anything.

**Comment by poszer** [comment]
> Only comment-strings have been changed here, no need to test anything.

Okay, thank you

**Comment by Winfidonarleyan** [comment]
Based TC commit https://github.com/TrinityCore/TrinityCore/commit/f9b1e4a03259c39af0d24e63f877455944b8af2e

**Comment by poszer** [comment]
> Based TC commit [TrinityCore/TrinityCore@f9b1e4a](https://github.com/TrinityCore/TrinityCore/commit/f9b1e4a03259c39af0d24e63f877455944b8af2e) maybe?

Nope. While searching for this issue reported about mining chance and configurations, I saw there is some words wrongly written. Also the commit that you shared has too much incorrect words and doesnt use same description at all

**Comment by Winfidonarleyan** [comment]
Okay

**Comment by BarbzYHOOL** [comment]
Thank you @poszer !!

**Pull request merged**
