### PR TITLE
fix(DB): Renn McGill Gossip Option

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix Renn McGill Gossip to provide the player with Repaired Diving Gear

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3015

## SOURCE:

https://www.youtube.com/watch?v=bOG-sDuYhd0

## Tests Performed:

- Talked with NPC, selected gossip option, received Helmet

## How to Test the Changes:

1. .go creature 18595
2. Select gossip option
3. Receive helmet

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by IntelligentQuantum** [comment]
@ZhengPeiRu21 A question without doing a quest should give this to the player?

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21 A question without doing a quest should give this to the player?

I could not find a source to confirm but it makes sense that the player should be on the quest and should need to be missing the item to receive a new one. I have added necessary conditions. Thanks for the suggestion!

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Oops, I didn't saw that you had startup errors! Fix them :)

**Comment by The-GhostRider** [comment]
Related: https://github.com/chromiecraft/chromiecraft/issues/3997

**Pull request merged**
