### PR TITLE
fix(DB/Creature): Add missing gossip option to obtain Yeh'kinya's Scr…

### LINKED ISSUE #6707: Yeh'kinya's resummon item and gossip menu missing
Original Chormiecraft report https://github.com/chromiecraft/chromiecraft/issues/1070

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

When finishing the quest [The God Hakkar](https://classic.wowhead.com/quest=3528/the-god-hakkar) you don't get the option to receive [Yeh'kina's Scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll) .
You should also be able to talk with [Yeh'kinya] to retrieve another scroll (repeatable, but you can carry only one scroll at any time).

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When finishing [The God Hakkar](https://classic.wowhead.com/quest=3528/the-god-hakkar) you should be able to receive [Yeh'kinya's scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll) and you should also be able to talk with [Yeh'kinya](https://classic.wowhead.com/npc=8579/yehkinya) to retrieve another scroll at any time after completing the quest (repeatable, but you can carry only one scroll at any time).
https://wowpedia.fandom.com/wiki/The_God_Hakkar see notes 

##### SOURCE:

[https://classic.wowhead.com/npc=8443/avatar-of-hakkar#comments](https://classic.wowhead.com/npc=8443/avatar-of-hakkar#comments)
[https://classic.wowhead.com/item=10818/yehkinyas-scroll](https://classic.wowhead.com/item=10818/yehkinyas-scroll)
[https://classic.wowhead.com/quest=3528/the-god-hakkar#comments](https://classic.wowhead.com/quest=3528/the-god-hakkar#comments)

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 3528
2. .quest complete 3528
3. .go creature 23270 (Yeh'kinya) and turn in
4. Talk to him again (no option for the scroll)

##### EXTRA NOTES:

Quest chain is quest 3520, 3527, then the 3528 quest above. Completing the entire chain up to that point gives the same results.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99646058-yeh-kinya-s-resummon-item-and-gossip-menu-missing?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…oll. Source: TrinityCore.

Fixes #6707

## Issues Addressed:

- Closes #6707
- Closes https://github.com/chromiecraft/chromiecraft/issues/1070

## Tests Performed:

- Not tested

## How to Test the Changes:

1. `.quest add 3528`
2. `.quest complete 3528`
3. `.go creature 23270` (Yeh'kinya) and turn in
4. Talk to him again - there should be an option to get the new scroll

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
@azerothcore/testers

**Comment by IntelligentQuantum** [comment]
Screenshot_20210913_074023

But when I click, nothing happens

**Review by Kitzunu — APPROVED** [review]

**Comment by UltraNix** [comment]
@IntelligentQuantum Try now.

**Comment by IntelligentQuantum** [comment]
Screenshot_20210913_220206

Works

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum don't forget to update the labels accordingly

**Pull request merged**
