### PR TITLE
fix(DB) Removes Quel'dorei Ghosts/Wraiths text reference to broadcast_text 12690

### LINKED ISSUE #19480: Quel'dorei Ghosts seem to have a broken text line.
### Current Behaviour

Shows an empty emote message.

### Expected Blizzlike Behaviour

Should say the ghost shimmers and becomes intangible.

### Source

[Wowhead comment](https://www.wowhead.com/wotlk/npc=16325#comments:id=213777)

### Steps to reproduce the problem

1. `.go c id 16325`
2. Knock it down to 20% health or so.
3. Observe its message.

### Extra Notes

_No response_

### AC rev. hash/commit

17d61664fd6afa07847c033ea828216bfee6c062

### Operating system

Windows 10 x64

### Custom changes or Modules

[mod-ptr-template](https://github.com/heyitsbench/mod-ptr-template)

### PR DESCRIPTION
**Pull request by kasvati**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #19480 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Notes:

- Inconsistency was caused by gender since only male text was missing, female mobs behaved as expected.
- Removed broadcast_text reference as changes in broadcast_text table are undesirable.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by avarishd** [comment]
Hey, thanks for the PR, but we do not edit broadcast_text, as
"Values from this table come from sniffs (retail data) and should not be changed unless you are absolutelly sure they have been wrongly changed before."
More info here: https://www.azerothcore.org/wiki/broadcast_text

**Comment by kasvati** [comment]
Changed the implementation so there is no change in broadcast_text table. SAI now shouldn't look for incomplete broadcast_text and use creature_text instead.

**Comment by Nyeriah** [comment]
Could I get some counseling on this one? @heyitsbench @Gultask @Kitzunu

**Comment by heyitsbench** [comment]
> Could I get some counseling on this one?

I suspect maybe bad gender assignment in `creature_model_info` is to blame, but would need to check these guys out in a sniff to be sure. BCT only has female text assigned, which is causing problems when the creature rolls display ID 17305 which is assigned male.

**Comment by heyitsbench** [comment]
Checked on Cata Classic, [this is a Blizzlike bug](https://github.com/user-attachments/assets/24186d81-f763-43a7-b058-5df33917eea8).

**Comment by Kitzunu** [comment]
Hot. so the question is, fix or no fix

**Comment by Gultask** [comment]
> Hot. so the question is, fix or no fix

Do it, that's what creature_text was made for, probably.
Add in the comment an explanation as to why it has no broadcast_text ID field

**Comment by sudlud** [comment]
Please add new line at the end of the sql file

**Comment by sudlud** [comment]
the sql check does not like it apparently when the file contains 'broadcast_text'. Can you maybe please update the sql comments so we get the checks passing

**Comment by sudlud** [comment]
thanks for the update, I assume @Gultask was referring to the database `comment` field to add a comment there.

Also is the only change setting `BroadcastTextId` to `0`? In this case I would probably prefer an `UPDATE` statement instead of re-inserting the whole line with just one field changed

**Comment by sudlud** [comment]
thanks for the update

**Review by sudlud — APPROVED** [review]

**Pull request merged**
