### PR TITLE
fix(DB/SAI): Venomspite quests / area

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
This is based on the following TC commits:
https://github.com/TrinityCore/TrinityCore/commit/ec2cee0ab7a7273ff8380bb85437de41c197d684
https://github.com/TrinityCore/TrinityCore/commit/2995e2a93551d17a6ebb79eb0694161e659d4fb3
https://github.com/TrinityCore/TrinityCore/commit/8d5120093d8fefb0f05e7670fb9457419f4c42b2
https://github.com/TrinityCore/TrinityCore/commit/ce062250a2fce8069d35e4b56af4ba5920bfab4f
https://github.com/TrinityCore/TrinityCore/commit/7b1cc6fe7ab664729129286bca591de434b84bd1
I adapted them to AC and added a few tweaks, especially for the quest "Fresh Remounts".

Changes:
- Fix a few quest chain conditions:
  - Show "Let Them Not Rise!" instantly when "Blighted Last Rites" is rewarded
  - "Blighted Last Rites" has to be completed before "Let Them Not Rise!" can be started
  - "Stealing from the Siegesmiths" has to be completed before "A Means to an End" can be started
  - "Materiel Plunder" has to be completed before "Fresh Remounts" can be started
  - "Let Them Not Rise!" has to be completed before "Stealing from the Siegesmiths" can be started
  - "Stealing from the Siegesmiths" has to be completed before "Need to Know" can be started
- Delete one of the two versions of "Deathguard Molder" and add waypoint movement to the other
- Revamp the roleplay event for "Blighted Last Rites"
- Add more Onslaught Warhorses to New Hearthglen (two of them with waypoint movement) and a Transformed Warhorse to Venomspite
- Fix several issues concerning the quest "Fresh Remounts" (e.g. as it was before you could just steal a horse and turn it in 3 times -> quest finished, which is wrong)

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- reset all quests and teleport to Venomspite:
```
.q rem 12206
.q rem 12209
.q rem 12211
.q rem 12214
.q rem 12230
.q rem 12234
.q rem 12240
.go 3234.23 -642.454 165.022 571
```
- just proceed with questing and check the changes mentioned above

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
After testing, no problems found, but, hope someone else to test again

**Comment by Knindzagxg** [comment]
All good mate.

Will check Last Rites on Ret, just to be sure about event once again.

**Comment by Stoabrogga** [comment]
> 
> Will check Last Rites on Ret, just to be sure about event once again.

Ok, please tell me if there's still something missing or wrong.

**Comment by Knindzagxg** [comment]
Checked event all good mate.
On Ret they have few extra things due TW, but nothing that have to be on 3.3.5a.

**Pull request merged**
