### PR TITLE
Fix(DB/EversongWoods): Ranger Jaela RP event

### PR DESCRIPTION
**Pull request by SoglaHash**
4 mobs that attack Jaela and Eversong Rangers are missing.

## Changes Proposed:
- Add new creature_template of Rotlimb Cannibal with flag 256 (not interractible with PC) and hpmodifier 3 (so event lasts arounds 40 seconds)
- Add waypoints 
- Add smart scripts to disable flag 256 and attack rangers
- Add text + emote to Ranger Jaela

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11853

## SOURCE:
event on classic https://www.youtube.com/watch?v=6aVBUGKl5ik

## Tests Performed:

https://user-images.githubusercontent.com/74299960/184496996-5704cfc2-77e1-48bf-9d96-63b6848d391d.mp4

## How to Test the Changes:

Ranger Jaela
```
.go c 55367
```

Leader of the Rotlimb Cannibals
```
.go c 40483
```
1. Observe pathing from spawnpoint towards the rangers. The terrain is not flat so check if there's any "floating" pathing
2. Player should not be attacked while they path towards the rangers
3. Player can attack once the NPCs engage in combat
4. See if the combat lasts 30 seconds or so
5. Respawn time should be 5minutes
6. Check if [Ranger Jaela](https://tbc.wowhead.com/npc=15416/ranger-jaela) yells text + emotes
7. 
## Known Issues and TODO List:

- [ ] Leader sometimes distances from the rest of the mobs but they catch up shortly 
- [ ] I had to guess the spawn point. Not sure how far away they spawn from the rangers
- [ ] AI of the rangers is not like in the reference video. I did not change it in this PR
- [ ] Attack on Tranquillien missing
```
spawnpoint
.go xyz 9132.73 -6992.1 9.97888
```

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Hi, thanks for your PR. Tested and seems work fine:

- [X] Event present without major issues
- [X] Jaela yell when Rotlimb are near
- [X] Rotlimb respawn after 5min

**Comment by Gultask** [comment]
@SoglaHash before you work further on this I'd suggest waiting for sniffs since WotLK Classic just came out, as well as a sniffer for it.

https://user-images.githubusercontent.com/100873791/188526450-facafd77-91ca-49d4-aeb7-9412af6cc121.mp4

In this case, they use the entry 15655 for the Rotlimb Cannibals.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
RP is wrong. Rangers do not shoot. Rangers ran to melee.
Jaela does not cast a fireball.
This is not per sniffs. 
Per sniff team member @malcrom 
This is something he has been working on as well but we are having issues with the reset and chaining of the attacks in the core.

**Comment by acidmanifesto** [comment]
No movement for this pr, This is custom role play and not retail. No follow up from auther since september 2022. WIll mark as abandon.

**Pull request closed without merging**
