### PR TITLE
refactor(Core/Misc): Use steady_timer instead of deadline_timer

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).

Swap deadline_timer to steady_timer as it started to deprecate in boost 1.7 and is completely deprecated in 1.78.

This allows AC to run on Boost 1.78, as well as earlier versions.

## Tests Performed:

This PR has been:

I have started the worldserver.
No extensive tests have been done

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Nah it works with all boost.
Honestly I would just say, check that everything works as normal and saves correctly.

The timers touch
- FreezeDetector
- DB ping
- Ban Expiry check
- Metrics
- Realm 
iirc

**Comment by Exitare** [comment]
I think its working. Compile is fine. Timers in boss fights too. Realm holds up fine too. Metrics look good to me too.

I wanted to check ban expiration by using 
`.ban character`
but i am quite certain that there is an issue with inserting the correct values into the database.
Right now the command will always result in a perm ban because it doesnt translate the ban time correctly to seconds. its always zero, resulting in ban and unbantime being the same. But apparently the core is not cleaning that up either

As far as this PR is concered i tested it and couldnt observe a noticable difference.

**Review by ghost — APPROVED** [review]

**Comment by Grimdhex** [comment]
I will merge it tomorrow. I avoid doing new merge before the CC update.

**Comment by sudlud** [comment]
Please merge master for CI codecheck fix

**Comment by Kitzunu** [comment]
This will fix mac os ci too

**Review by sudlud — APPROVED** [review]

**Pull request merged**
