### PR TITLE
fix(DB/creature_formations): [BRD] The Throneroom will now aid Thaurissan & Moira

### PR DESCRIPTION
**Pull request by syssneck**
Thanks to @Asthalor and @Azcobu!

## Changes Proposed:
-  Aggroing Thaurissan or Moira will now pull the whole Throneroom to aid them

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7725#issuecomment-914437013
- Closes https://github.com/chromiecraft/chromiecraft/issues/1629

## Tests Performed:

- Ran SQL, no errors
- checked in-game, the whole room aids them in battle now
- tested multiple times on Thaurissan & Moira with dmg spells, taunts and body pulls, it always worked.
- Also works on resets and respawns

## How to Test the Changes:

1. `.go c 47217`
2. aggro either Thaurissan or Moira
3. watch all mobs flooding in to help them

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by T1ti** [comment]
I'm interested in how succesful this fix is, because from my past experience,c reature_formations is bugged dogshit when used like this to make aggro groups

**Comment by Asthalor** [comment]
Tested on a new character with a pet and i saw it good.

https://streamable.com/xrl5in

I sent the imp with invisibility and attacked moira, and the whole room came to aid. 
I can do more testing if needed.

**Comment by Helias** [comment]
@syssneck what do you think?

**Comment by syssneck** [comment]
@Helias I tested at least 20 pulls and couldn't make out any strange behavior. I doubt that there is something wrong with the fix, but if there is, we could fix it at a later stage, because at the moment it's totally broken.

**Review by Si1ker — APPROVED** [review]
merge merge merge

**Pull request merged**
