### PR TITLE
fix(DB/Creature): fixed Timber respawn time

### PR DESCRIPTION
**Pull request by gabryatfendor**
Decreased Timber respawn timer from 2 hours to 45 minutes

## Changes Proposed:

This PR proposes changes to:
-  Creature database to correct Timber respawn time

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18433
- Closes https://github.com/chromiecraft/chromiecraft/issues/6219

## SOURCE:

The changes have been validated through:
- https://wowwiki-archive.fandom.com/wiki/Timber
- The WOW Atlas

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.

## How to Test the Changes:

- [X]This pull request can be tested by following the reproduction steps provided in the linked issue

1. Run command .go c id 1132
2. kill the creature
3. wait 45 minutes

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by sudlud — APPROVED** [review]

**Comment by pangolp** [comment]
Update the branch, and remove the constant. It can be used, but since it is an update, in this case I deleted it, but there would be no problems in using it if necessary. Thanks for the contribution, we'll see if it passes the tests.

**Comment by sudlud** [comment]
> Update the branch, and remove the constant. It can be used, but since it is an update, in this case I deleted it, but there would be no problems in using it if necessary. Thanks for the contribution, we'll see if it passes the tests.

You also removed all comments from the sql file.

Why is the constant an issue here? Does it matter really?

**Comment by pangolp** [comment]
> You also removed all comments from the sql file.
> 
> Why is the constant an issue here? Does it matter really?

No, really, the constant and the comments could be left without problems. I just eliminated them, as a matter of custom, really. Since it was a single consultation, it seemed fine to do it, just that. But in reality, it could have been left without problems. At first I used constants and comments a lot within the file. Then, as time went by, and taking into account that sooner or later this was going to be merged with the base content, I started trying to reduce the number of lines, but really, the script was perfect as it was.

**Comment by gabryatfendor** [comment]
I added the comment and the costant because I was following the style guide of azeroth core. I agree that being a single line script maybe it was a bit of an overkill ;-)

**Comment by pangolp** [comment]
> I added the comment and the costant because I was following the style guide of azeroth core. I agree that being a single line script maybe it was a bit of an overkill ;-)

We've all changed the way we write code over time, don't worry. The important thing is the final result.

**Pull request merged**
