### PR TITLE
fix(DB/gameobject): Improve quest Fields of Grief (part2)

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Increase spawn locations from 10->32.
-  Add them to a pool, 20 spawns at once (easy to change this)
- Respawn time lowered from 5->2 minutes

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4701

## Tests Performed:
- Applied SQL ~~, not tested in game~~
- Tested in game

## How to Test the Changes:

- `.quest add 365`
- `.tele sollidenf`
- loot pumpkins, notice respawn is 2 minutes and the spawns are more numerous and in more locations than before

## Known Issues and TODO List:

- This was already discussed in: https://github.com/azerothcore/azerothcore-wotlk/pull/4529 where these suggested changes where found wrong.
- This is not a "purist" change, as it would be more "Classic" than "Vanilla". Opinions regarding this might differ - this is merely a suggestion.
- For what it's worth, this is closer to TC than what we have now.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
updated label as the PR has then been tested by @Zoidwaffle

**Comment by eTzmNcbkrng** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/4701#issuecomment-791753842
>It's hard to say how valid the data is, being potentially poisoned by private servers etc. and so on.

In [part one](https://www.youtube.com/watch?v=Tyc3S-Bl8oU) of this video series, we can see the player's character selection screen and he is playing on a realm called Eonar, which is a valid EU (his accent puts him in EU) realm.
One of the characters is Terminator, a L49 Warrior.
https://worldofwarcraft.com/en-us/character/eu/eonar/terminator - L10 (stat squish) Mechagnome Warrior in full heirlooms,
I was unable to find/read any of the other characters on the Eonar realm.
Also, the video was uploaded in May 2010 while Wrath was still current.

**Comment by pklloveyou** [comment]
Tested

**Comment by Zoidwaffle** [comment]
@eTzmNcbkrng : OK, so the video is probably fine. But how to interpret what happens...

He picks up all the pumpkins in ~2½ minute. There are several pumpkins visible in the field when done, like 5ish and that's not counting the couple that might by the tower. So a 5 minutes respawn and 10 nodes is definitely wrong (what we have before this PR).

So what do you think? Is this PR fine as it is or should the amount of spawns / respawn rate be adjusted?

**Comment by eTzmNcbkrng** [comment]
I think the number of possible nodes is the biggest unknown at this point.  
At 6:04 - 6:06 we see him loot two nodes next to a cart, at 6:29 we can see one of them has already respawned.

I think this means there is a minimum number of nodes always available, and this number is either different to the maximum number of available nodes (in which case a respawn timer is needed) or it is the same as the maximum number of nodes (in which case a respawn timer is not needed).

**Comment by Zoidwaffle** [comment]
I think this is where we use our interpretive freedom - I have lowered the amount of spawns to 15 (down from 20). So there are fewer pumpkins around and they start respawning after 2 minutes. It should give something reminiscent of what could be seen in the video. The respawn timer and amount of spawns can be adjusted, but I think this feels about right.

Is it perfect? Probably not.

Is it better than before? Yes, I believe so.

**Comment by necropola** [comment]
Just updated my local AC and checked. I found 12 Pumpkins (10 in the field), 1 at the tower and 1 at a stable/farm house (probably missed 3). They respawned after 2 minutes. Looks pretty good to me. Well done.

**Pull request merged**
