### PR TITLE
fix(Core/Ahune): Chest and Quest

### PR DESCRIPTION
**Pull request by PkllonG**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .qu ad 11691
2. start ahune
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Whoops.

**Review by Nyeriah — APPROVED** [review]

**Comment by heyitsbench** [comment]
It does look like he's supposed to be killable in the emerged phase. Source: [Wowhead comment](https://www.wowhead.com/npc=25740#comments:id=308725:reply=339349)

**Review by Nyeriah — APPROVED** [review]

**Comment by PkllonG** [comment]
> It does look like he's supposed to be killable in the emerged phase. Source: [Wowhead comment](https://www.wowhead.com/npc=25740#comments:id=308725:reply=339349)

Chests that do not have a reward after being killed.

**Comment by heyitsbench** [comment]
> Chests that do not have a reward after being killed.

Sure, but is there a source for him *not* being killable during emerge?

**Comment by PkllonG** [comment]
> It does look like he's supposed to be killable in the emerged phase. Source: [Wowhead comment](https://www.wowhead.com/npc=25740#comments:id=308725:reply=339349)

Or I can change it
```
            DoCast(SPELL_SUMMON_LOOT_MISSILE);
            DoCast(SPELL_MINION_DESPAWNER);
```

**Comment by heyitsbench** [comment]
The chest spawned fine in my testing with loot inside on current master.

**Comment by heyitsbench** [comment]
I agree with the quest/item additions for sure, but I don't understand the unkillable change, I see no source for it nor do I understand what issue it's targeting.

**Comment by PkllonG** [comment]
> The chest spawned fine in my testing with loot inside on current master.

I'm going to do a test now

**Comment by PkllonG** [comment]
image
no Chests

**Comment by heyitsbench** [comment]
[I am befuddled.](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/febddc20-899b-4527-a115-85cfa2084155)

**Comment by PkllonG** [comment]
> [I am befuddled.](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/febddc20-899b-4527-a115-85cfa2084155)

.die 25740

**Comment by PkllonG** [comment]
[fd0c6a7](https://github.com/azerothcore/azerothcore-wotlk/pull/19106/commits/fd0c6a7662d8cacabd32c257ab54d9a403d37e9d)
Everything works fine now.

**Comment by heyitsbench** [comment]
I cannot reproduce the chest spawning issue no matter what I try. But if moving the loot generation cast from the core to Ahune works, it works. Would eventually like to double check against sniffs which one actually casts the spells, but that can wait.

**Comment by Nyeriah** [comment]
It should probably be a triggered cast. If he's channeling etc. non triggered spells wont be cast

**Comment by PkllonG** [comment]
So, any good ideas?

**Comment by Nyeriah** [comment]
I'll leave it up to bench to decide if he wants to check anything against sniffs before merging this

**Comment by heyitsbench** [comment]
Confirmed Frozen Core is casting the two spells on itself, would something like this work?
```diff
-   DoCast(SPELL_SUMMON_LOOT_MISSILE);
-   DoCast(SPELL_MINION_DESPAWNER);
+   DoCastSelf(SPELL_SUMMON_LOOT_MISSILE, true);
+   DoCastSelf(SPELL_MINION_DESPAWNER, true);

**Comment by PkllonG** [comment]
> Confirmed Frozen Core is casting the two spells on itself, would something like this work?
> 
> ```diff
> -   DoCast(SPELL_SUMMON_LOOT_MISSILE);
> -   DoCast(SPELL_MINION_DESPAWNER);
> +   DoCastSelf(SPELL_SUMMON_LOOT_MISSILE, true);
> +   DoCastSelf(SPELL_MINION_DESPAWNER, true);
> ```

I'll give it a try now

**Comment by PkllonG** [comment]
> Confirmed Frozen Core is casting the two spells on itself, would something like this work?
> 
> ```diff
> -   DoCast(SPELL_SUMMON_LOOT_MISSILE);
> -   DoCast(SPELL_MINION_DESPAWNER);
> +   DoCastSelf(SPELL_SUMMON_LOOT_MISSILE, true);
> +   DoCastSelf(SPELL_MINION_DESPAWNER, true);
> ```

image
It worked fine.

**Comment by PkllonG** [comment]
Windows always gets some weird bugs

**Comment by PkllonG** [comment]
Thank you very much for help

**Comment by heyitsbench** [comment]
> Thank you very much for help

Thank you for the PR! Sorry it was necessary in the first place.

**Pull request merged**
