### PR TITLE
fix(Cmake): using policy 0153 if exist

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Fix make errors in commit - d72a71a4b2ec33f2891c712642adbc63bb201e61

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@FlorianVaissiere @icedcolor can test this pr?

**Comment by aradep** [comment]
Was getting the same error on Debian12. This PR fixed it.  👍

**Comment by WoShiXiaoMaNong** [comment]
also working fine on my mechine( Ubuntu 20.4)
















在 2024-02-26 19:55:58，"Degen" ***@***.***> 写道：

Was getting the same error on Debian12. This PR fixed it.

**Review by elthehablo — APPROVED** [review]

**Review by FlorianVaissiere — CHANGES_REQUESTED** [review]
Good it's working now !
Nice Job ;)

**Pull request merged**
