### PR TITLE
fix(DB/SAI): Re-added Snowblind Follower interaction for quest 14090

### PR DESCRIPTION
**Pull request by Andrei-UPB**
Adds to : https://github.com/azerothcore/azerothcore-wotlk/pull/2354
References taken from https://wowgaming.altervista.org/aowow/?quest=14090 / https://wowgaming.altervista.org/aowow/?quest=14141

##### CHANGES PROPOSED:
-  Stoabrogga's PR #2354 added waypoints and event interaction to npc's in Garm's Rise but broke the functionality of quests 14090 and 14141
- This commit fixes that by re-adding the missing SAI lines

##### TESTS PERFORMED:
- Tested in-game, using the given quest item on a Snowblind Follower rewards credit to the quests as intended.

##### HOW TO TEST THE CHANGES:

1. .go c id 29618
2. .q add 14090
3. and/or .q add 14141
3. Use Weighted Net (item 46885) on a Snowblind Follower
4. Verify if the quest objective updates or not.

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Pushed a new commit with these changes:
- Only add the new entries to the script (if possible please do not overwrite complete scripts, as this is error-prone and ultimately led to my error in the first place).
- Use single quotes instead of double quotes
- Just make entry id 7 not repeatable instead of using timers in order to prevent multiple quest rewards using the same snobold

Already tested this successfully, so can be merged in my opinion. Thanks @Andrei-UPB

**Comment by Andrei-UPB** [comment]
Thanks for the reply.

To be frank, this is my judgement for most if not all of your bullet points:

- If someone using AC updated their script to the one you worked on then noticed the quest being broken and fixed it on their own by adding your improvements on top of the already existing script (instead of replacing it entirely), deleting entries 7,8,9 will just re-write entries 1,2 and 3. That's why I believe it's better to delete all of the entries, and just write everything from scratch, in order to be certain that everyone is on the same page regarding this particular smart script.

I feel that when it comes to a script of this size, complexity wise whether you add 7 lines or 3 or deleting everything in the script or some arbitrary id's which lines might not always contain what we think they do it would be, and rewriting scripts in general, clearing everything is better than just adding on top of because said file might have been worked on previously, in an independent fashion.

- I use double quotes on comments is quite the standard because single quotes require an escape character (usually \) in cases the comment contains a single quote in case of particular words ( don't, won't, can't).

```
"If you're going to use apostrophes, 
       ^

you'll definitely want to use double quotes".
   ^
```
- I didn't know you could make the event non-repeatable, therefore the fix i found was to prevent credit being granted more times by placing an internal cooldown on the event. Blizzard uses to do the same thing with debuffs, that if you're patient enough to let run out, you can "tag" the same creature twice or more for quest completion.


Cheers for the help, today I learnt something, I hope everyone did :)

**Comment by FrancescoBorzi** [comment]
@Andrei-UPB  thanks for your contribution, however, I disagree with this statement:

> If someone using AC updated their script to the one you worked on then noticed the quest being broken and fixed it on their own by adding your improvements on top of the already existing script

AC should be used in the following way:

1) any improvement/changes to the main core (which includes all the blizzlike contents) should be shared with the community via PRs (our AGPL license is quite clear about it)

2) any **custom** additions should be implemented using our [module system](http://www.azerothcore.org/wiki/The-Modular-Structure). Users can create their own custom modules  and they can decide either to share them with the community or keep them private

because of point 1), users should never fix things "on their own". Apart from the license issue, there are several other good reasons not to do it, but that goes beyond the scope of this thread.

**Comment by Stoabrogga** [comment]
@Andrei-UPB 
- Concerning overwriting complete SAI scripts I don't share your opinion:
  - If people use customizations it's their problem, not AC's. As AC contributor you should always base your changes on a fresh DB and clean code base.
  - Overwriting SAI makes it harder to review PRs, because you have to compare the existing script with the new one.
  - As I already told it can cause much trouble by accidentally removing already working parts, like it has happened to me and on several other occasions in the past.

- Concerning single quotes vs double quotes: Please follow the guidlines described here: http://www.azerothcore.org/wiki/Dealing-with-SQL-files
  (single quotes for string values, backticks for field names, no double quotes)

- SAI documentation: http://www.azerothcore.org/wiki/smart_scripts (doesn't harm to take a look at this from time to time, I use it regularly)

**Pull request merged**
