### PR TITLE
fix(DB/SAI): Quest Fel Spirits

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:
-  About visual laser bug reported by @LukasVolgger last year, I was able to fix it.
-  Updated event Aggro to Just_Summoned which is correct for Fel Spirit creature

## Issues Addressed:
**Remembering that it has already been merged with this laser bug.**
- Bug Laser [#2726](https://github.com/azerothcore/azerothcore-wotlk/pull/2726)
- Bug Laser [#2682](https://github.com/azerothcore/azerothcore-wotlk/issues/2682)

## Tests Performed:

- windows 7 64bits.
- Video [here](https://www.youtube.com/watch?v=iJMeyZA7FTA)

## How to Test the Changes:
. quest add 10909

## INFO:

- How it looks in java script and converted to spell_dbc database
spell Create Anchorite Relic

- effect_2 removed and added in SAI
spell id 39183

- another picture of the object
spell summon object

## Target Branch(es):
- [x] Master

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Comment by LautaroJMolina** [comment]
Tested.
The laser is correctly aligned with the crystal, and the fel spirits say their line as soon as they spawn instead of when being aggroed.

**Comment by Eldarix** [comment]
Hi !! this is the visual result that I had after inserting the code, I hope it works! (Tested on Windows 10)

Greetings ;)

WoWScrnShot_042221_080834
WoWScrnShot_042221_080925
WoWScrnShot_042221_081020
WoWScrnShot_042221_081106
WoWScrnShot_042221_081227
WoWScrnShot_042221_081334
WoWScrnShot_042221_081345

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @grimgravy , @LautaroJMolina  and @Eldarix !

**Pull request merged**
