### PR TITLE
fix(Core/GameObjects): Fixed go's rotation and moving actions not updating to client. Port from TC.

### LINKED ISSUE #1043: GObject rotation broken [$100]
EXPECTED BLIZZLIKE BEHAVIOUR:

The GObjects should "rotate", change angles when defined in the DB table gameobject column rotation0, rotation1, rotation2, rotation3

Also, the command for this ingame is weird. It should offer .gobject turn [3 rotations] instead it is only offering the "...same as current character orientation."

STEPS TO REPRODUCE THE PROBLEM:
try any gobject ingame, or spawn fresh one...try to change angle/s. The orientation is working, the rotation is not.

BRANCH(ES):

master
AC HASH/COMMIT:

commit 205e8eb
-> have not updated since
OPERATING SYSTEM:

Win 10 x64, latest update
MODULES:

no
OTHER CUSTOMIZATIONS:

none

I hope my explanation is clear. TC had this issue too, they ported that stuff from mangos...it was some time around y2015 so it is possible it was not included in sunwell. If you find my report invalid, please explain how and if even is this stuff working.

<bountysource-plugin>

---
There is a **[$100 open bounty](https://www.bountysource.com/issues/64129314-gobject-rotation-broken?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #1588: Gob Move command not refreshing Gobject position to players [$20]
**SMALL DESCRIPTION:**
```
.gobject move GUID X Y Z
```
Doesn't refresh gobject position to players in zone.
Players must relog to see changes.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Players should'nt have to relog to see gameobject updated coords.

**STEPS TO REPRODUCE THE PROBLEM:**
1. Add a new gameobject using `.gob add` command
2. Go away from the spawned gameobject
3. Use `.gps` to have other X Y Z position
4. Move the spawned gameobject using `.gob move GUID X Y Z`
5. Observe that the gameobject's position haven't been updated to the client
6. Relog
7. Observe that the gameobject's position have been updated

**EXTRA NOTES:**
You can watch the video that describes the problem : 
https://mega.nz/#!450VECyZ!43iY4JWQzg2ICgdetG26LeS4K3YHT8EZXKQFOCyDAtk

I think the .gob turn command could have the same issue.

**BRANCH(ES):**
master

**AC HASH/COMMIT:**
https://github.com/azerothcore/azerothcore-wotlk/commit/a7b4c909f3f27c729633983b7cee8ad30b058863

##### OPERATING SYSTEM:
Windows10

##### MODULES:
None

##### OTHER CUSTOMIZATIONS:
None

<bountysource-plugin>

---
There is a **[$20 open bounty](https://www.bountysource.com/issues/73006797-gob-move-command-not-refreshing-gobject-position-to-players?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
## Issues Addressed:
- Closes #1043
- Closes #1588.

## Tests Performed:

- Tested ingame in Stormwind with many gameobjects.

**REQUIREMENT: #4885.**

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
m_spawnId Undefined

**Comment by UltraNix** [comment]
Yep, but do not test until #4885 is merged.

**Comment by UltraNix** [comment]
Ready to me merged.

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/developers please check this

**Comment by UltraNix** [comment]
Can be merged?

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> Can be merged?

given that you tested this yourself, yes. Approved.

**Pull request merged**
