### PR TITLE
Fix(DB/Creature): Zul'Gurub boss damage

### PR DESCRIPTION
**Pull request by temperrr**
## Changes Proposed:
-  Reduce damage from ZG bosses as it was way too high. (normal values were all 35 (higher than BWL)

## Issues Addressed:

- None
- 
## SOURCE:

Cmangos, compared with Warcraft logs to assure validity. 

## Tests Performed:

- Tested all bosses and compared damage.

## How to Test the Changes:

1. Go to ZG
2. Kill all the bosses and get hit by them ;)  

## Known Issues and TODO List:

- None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ratkosrb** [comment]
@T1ti Some info about Hakkar here https://github.com/cmangos/issues/issues/2189

The values in the book are with all stacks of the buff (all mini bosses alive).

**Comment by Gultask** [comment]
Also might need to tweak damages of Hazza'rah's Nightmare Illusions (15163) They are supposed to deal massive damage but currently deal very little. Their damage modifier in Keira is 1.

**Comment by temperrr** [comment]
I'll look into that

**Comment by temperrr** [comment]
> Also might need to tweak damages of Hazza'rah's Nightmare Illusions (15163) They are supposed to deal massive damage but currently deal very little. Their damage modifier in Keira is 1.

From cmangos its the same value, where did you find it should do massive damage?

**Comment by ratkosrb** [comment]
In my classic sniff parses, creature 15163 is seen doing damage in the 4785 - 5992 range. This is from combat log, not mind control, so it's not the exact damage range, but it gives you an idea what the damage multiplier should be.

**Comment by Gultask** [comment]
yeah, what ratksrb said. ^^
Their gimmick is that they have like 500-700 HP and are slow to start attacking, but they deal immense amounts of damage since there's also 3 of them at once.
[In this WotLK-era video](https://youtu.be/nN4-ecE0FnE?t=124) they deal 1000+ damage, and around double of the boss' damage

**Comment by temperrr** [comment]
I'll see if I can find a good source for it as I cant start guessing :3

**Pull request merged**
