### PR TITLE
fix(core/quest): improved egg collection

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:
-  Fix condition
-  Fix item collected dragon egg
-  improved PR [#9039](https://github.com/azerothcore/azerothcore-wotlk/issues/9039)
## Issues Addressed:

- Closes 

## Tests Performed:

- was performed windows 7 64bits. Not a single error was found and it is Functional

## How to Test the Changes:

1.add the quest with command:
2.quest add 4735

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Tested with https://github.com/azerothcore/azerothcore-wotlk/pull/12575:

- [X] Can't collect eggs unfreeze
- [X] Can collect eggs freeze
- [X] Can finish the quest

**Comment by acidmanifesto** [comment]
ok... someone able to tell me what the heck this error is suppose to imply?
image

**Comment by Nyeriah** [comment]
Please use the spellcorrections cpp file to make dbc changes

**Review by Nyeriah — CHANGES_REQUESTED** [review]
spellinfocorrections.cpp

**Comment by grimgravy** [comment]
> Please use the spellcorrections cpp file to make dbc changes

why this change?

**Comment by Nyeriah** [comment]
> > Please use the spellcorrections cpp file to make dbc changes
> 
> why this change?

The spell_dbc database table is designed for:
1) server side spells (changing those is fine)
2) custom scripting (pretty much only modules should do this)

We use the CPP file to alter clientside spells because otherwise we incur the risk of overriding fields we don't intend to, and considering how many fields that table has, it is almost impossible to review new inserts 👍

**Comment by acidmanifesto** [comment]
Merge Conflicts

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Thanks for the PR ✌️

**Pull request merged**
