### PR TITLE
fix(DB): Martie Jainrose Missing Gossip

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Add missing gossip for Martie Jainrose (NPC 342)

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Vmangos: https://github.com/vmangos/core/blob/a01720f547f0d042b7989085a1a3558cc6e92a64/sql/old_migrations/20170922181149_world.sql

## Tests Performed:

Capture

## How to Test the Changes:

1. .go creature 6270
2. Gossip is appearing correctly

## Known Issues and TODO List:

Please kindly feel free to change the Gossip Menu ID and NPC Text ID to anything else using variables at top of SQL file! I am just use these now as they are available. My chosen ID do not conflict with any of my other PR.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Thanks for the PR! But I have to say no to this specific way of doing this.

In this PR https://github.com/azerothcore/azerothcore-wotlk/pull/10526 I am implementing `quest_greetings` which will be the proper way to show gossips for creatures with only one option (quests)

Please update this PR accordingly.

**Comment by ZhengPeiRu21** [comment]
> Thanks for the PR! But I have to say no to this specific way of doing this.
> 
> In this PR #10526 I am implementing `quest_greetings` which will be the proper way to show gossips for creatures with only one option (quests)
> 
> Please update this PR accordingly.

Thank you for implement that PR! This workaround is now not necessary. I will fix my PRs to use new table when #10526 is merge.

**Comment by acidmanifesto** [comment]
> > Thanks for the PR! But I have to say no to this specific way of doing this.
> > In this PR #10526 I am implementing `quest_greetings` which will be the proper way to show gossips for creatures with only one option (quests)
> > Please update this PR accordingly.
> 
> Thank you for implement that PR! This workaround is now not necessary. I will fix my PRs to use new table when #10526 is merge.

your past prs are still good and are amazing. just stand by until he gets his pr working and we will hopefully have a better system to use.

**Comment by ZhengPeiRu21** [comment]
Closed in favor of: https://github.com/azerothcore/azerothcore-wotlk/pull/10928

**Pull request closed without merging**
