### PR TITLE
fix(DB): Stitches Event Fix

### LINKED ISSUE #6685: Duskwood, Darkshire - Various Issues With Stitches Event
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1053

Stitches (npc=412) the elite 35 abomination spawn in duskwood as a result of quest Bride of the embalmer (quest=253) doesnt aggro quest giver npc in Darkshire.
Stitches do aggro player and non quest giver gard but quest giver like althea ebonlocke( npc=264) or Calor (npc=663) don't react even when stitches is in front of them

Tester: confirmed. I spawned him (twice actually) and although many of the Night Watch in Darkshire did correctly attack and be attacked by him, some didn't. Watcher Ladimore and Commander Althea Ebonlocke, leader of the Night Watch, both ignored and were ignored by Stitches. Checking the DB shows they both have the CIVILIAN flag set in flags_extra.

WoWScrnShot_070321_114844
WoWScrnShot_070321_114930

Rather more seriously, the event also ended incorrectly. Stitches did a lap of the village centre, and then suddenly ran east, clipping right through a building and then the hills, and moved underground before disappearing.

https://user-images.githubusercontent.com/81782124/124340631-a3697500-dbf5-11eb-9088-2c24526dd888.mp4

These issues are surprising because the Stitches events was looked at in https://github.com/azerothcore/azerothcore-wotlk/pull/4523 and the author did a really thorough job, so not sure if some of these issues mean the changes in that PR have been reverted or otherwise changed in some way.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

-Arriving in darkshire Stitches should aggro all gards in aggro range in town.

Not sure how the event is supposed to end - either with his death or if he despawns after killing all the guards - but he certainly shouldn't be clipping through hills.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .npc add 412
2. See if  they aggro one another

##### EXTRA NOTES:
I'm sure he should aggro in vanilla/TBC, maybe it's his normal behavior in wrath

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99646246-duskwood-darkshire-various-issues-with-stitches-event?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LannyE**
Fixes issue of Stitches running back to its waypoint start
- It appears there were a few changes to Azerothcore that modified elements to this event since it was created.
- It also appears that the Smart Script OOC no repeat seems to repeat anyway under specific circumstances.  Fixed this.
- Updated Watcher Cutford's waypoints to be more resilliant to his feet being under the floor as he runs.
- Updated the event spawned watchers (Corwin and Sarys) from respawning during the event after they have been killed. 
- Issue #6685 talked about Watcher Ladimore and Commander Althea Ebonlocke attacking Stitches.  This was dicussed in length on the original PR but was abandoned due to a few youtube sources (one in source section) and the idea that Blizzard had an issue with killing quest hub NPCs.   Althea is a quest hub NPC and Ladimore is a quest ender thus the civilian flag.  My own memory is that stitches didn't go on a killing spree when he came into town he just hung out in town and killed us all when we tried to leave the Inn.  Eventually he despawned.  Maybe when Wrath Classic comes I can get a better look.
- Also remember this event only lasts for 35 minutes from start to end.  At the 35 minute mark the event ends despawning stitches and any NPCs associated with the event.      

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes #6685

## SOURCE:

https://www.youtube.com/watch?v=xl8WHdd2iwE&ab_channel=LSmash
## Tests Performed:

- Turned in quest and watched the event from beginning to end when stitches despawned
- 

## How to Test the Changes:

-- This is the correct way to test the stitches event. 
1. Go to Darkshire
2. .quest remove 252
3. .quest add 252
4. Turn in quest to Lord Ello Ebonlocke
5. Event should start with Watcher Cutford running in a few seconds later.
6. Wait for Stitches to come to town and defeat the three watchers (20 minute wait) and start random movement in the middle of the town.
7.  Wait for the event to end and stitches despawn (without him running off into the sunset to start whole event over. )
8.  Note: Watcher Keefer will respawn once and fight him and die a second time to him.  The bug happened about 5 seconds after that as he would run back to his starting waypoint and start the event over. 
## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
@LannyE There are any redundance or fix that include with #10939 ?

**Comment by LannyE** [comment]
No, that one dealt with the start event smart action.  That works fine.  This one deals with Stitches running back to start his waypoints again after a while of hanging out in the town before the event stops even though the OOC smart event is set to no repeat.

**Comment by Lynethris** [comment]
Tested and work.

- [X] Event start properly
- [X] No issue find on the Stitches pathway
- [X] No issue find with the global event
- [X] Stitches doesn't kill Watcher Ladimore and Commander Althea Ebonlocke
- [X] When Event is end Stitches despawn

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
