### PR TITLE
DB/Loot: Fix items quests loot party

### PR DESCRIPTION
**Pull request by pangolp**
###### ISSUES ADDRESSED:

Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/1105

##### HOW TO TEST THE CHANGES:
1. Get in group with friend or login with 2 accounts
2. Kill an npc with a partner while in group
3. Try to loot with both characters item.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by poszer** [comment]
> Do not fill in the data because they are all in the issue, it would be to repeat everything again. But if I have to fill it again, I will fill it.



> Do not fill in the data because they are all in the issue, it would be to repeat everything again. But if I have to fill it again, I will fill it.

Nvm, i edited this time. If you didn't notice, Issue template and PR template are different. For example, while opening issue you re writing **STEPS TO REPRODUCE THE PROBLEM**. But while opening PR, you re writing **HOW TO TEST _THE CHANGES_** - That's not same.

**Comment by Maurowin** [comment]
there are quest items that can be picked up by all players, such as, for example, the head of a monster etc... however, all quest items to be picked up like skins or others cannot be picked up by all players on the same beast.

**Comment by Winfidonarleyan** [comment]
I added a new line after first line

**Comment by pangolp** [comment]
Would the arrangement be all right then?

**Comment by Stoabrogga** [comment]
I'd advise against merging this PR. It updates over 3000 item templates without the possibility to revert the changes.

**Comment by pangolp** [comment]
Ok. We'll have to keep looking for another solution then why at least we were bugged with items.  Maybe you didn't.

**Comment by Stoabrogga** [comment]
@pangolp 
We'll find a solution. But this one here is too risky for my taste. If it turns out later that the change has unforeseen side effects you cannot easily revert it.

**Comment by BarbzYHOOL** [comment]
Yes, me too. That seems too straightforward to be the right solution :D. Looks like a custom feature

**Comment by wetbrownsauce** [comment]
I use this as a custom hack-fix on my server, and it has worked perfectly for the past month. However, I do not think it should be merged into the base branch. It is likely NOT the blizzlike way of doing this, as TC does not have the 2048 flag set on hardly anything in DB. I think a core-fix would be more appropriate.  

I have yet to see it affect something that it shouldn't, but just because it works, doesn't mean it is right.

**Comment by FrancescoBorzi** [comment]
I agree with @wetbrownsauce , we could actually keep all those "hackfixes" somewhere. For example a repository?

Anyway, thank you very much @pangolp for contributing, we appreciate.

**Comment by BarbzYHOOL** [comment]
Good idea, I made a repository for this: https://github.com/azerothcore/azerothcore-hackfixes

**Comment by wetbrownsauce** [comment]
Hmmm, yeah maybe a separate repo of work-arounds and hackfixes with ways to reverse them included. Maybe even a wiki page explaining how to use/remove them.  

My bitwise math is a bit shaky so correct me if I'm wrong, but the following query would return every item that _would_ be affected by this PR before it is applied, no?
```
SELECT `entry`, `name` FROM `item_template`
WHERE (`Flags` & 2048 = 2048) AND (`class` = 12) AND (`bonding` = 4);
```

**Comment by wetbrownsauce** [comment]
Also, as a side note for this specific PR, why is `subclass = 0` being checked? All items in the world DB with `class = 12` and `bonding = 4` have `subclass = 0` so it seems useless to include it.

**Comment by Stoabrogga** [comment]
> My bitwise math is a bit shaky so correct me if I'm wrong, but the following query would return every item that _would_ be affected by this PR before it is applied, no?
> 
> ```
> SELECT `entry`, `name` FROM `item_template`
> WHERE (`Flags` & 2048 != 2048) AND (`class` = 12) AND (`bonding` = 4);
> ```
> 
> edit: left out an !

Yes, but what are you trying to accomplish? Dump all entries before applying the update statement?

**Comment by wetbrownsauce** [comment]
Partly. 

I would like to dump all entries of items that would be affected so that I can:
1) easily revert.
2) go through the list and see if anything shouldn't be there.
3) get more practice with bitwise logic

:P

**Comment by BarbzYHOOL** [comment]
post it on the new repo wetbrown or pangolp 

Even a simple text ".md" file could do the job

**Comment by pangolp** [comment]
You're welcome. I'm just trying to collaborate, I'll find some other way to keep doing it. Thank you for taking the time to analyze it.

**Comment by pangolp** [comment]
After many years, I was finally able to create a hook and with it, add a module that does this job.
https://github.com/pangolp/mod-quest-loot-party

**Pull request closed without merging**
