### PR TITLE
fix(DB): Many Missing and Fixed zhCN Translations

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix many or incorrect zhCN locale text
-  Many thanks to @mpfans for providing the data! I only format it into commands and compared it with current database to see what was missing or updated.

## Issues Addressed:

- Closes unreported issue

## Tests Performed:

- SQL file runs without errors, spot checked many text to confirm it is correct zhCN text and not just zhTW in Simplified Chinese

## How to Test the Changes:

1. Apply update
2. Test with zhCN client

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by mpfans** [comment]
A large part of the data here comes from @Remberance .I have verified some data and think it can be merged. If there are other problems, I will submit PR for correction.thank you @ZhengPeiRu21

**Comment by Nyeriah** [comment]
The file seems rather large, we tend to have issues loading large files, it gets stuck when loaded by the auto updater

**Comment by mpfans** [comment]
> The file seems rather large, we tend to have issues loading large files, it gets stuck when loaded by the auto updater, needs testing



> 

There are no errors when I execute SQL statements manually, but I don't know if there will be problems with automatic update

**Comment by Nyeriah** [comment]
> > The file seems rather large, we tend to have issues loading large files, it gets stuck when loaded by the auto updater, needs testing
> 
> > 
> 
> There are no errors when I execute SQL statements manually, but I don't know if there will be problems with automatic update

The problem is that unless users have a high SQL packet treshhold it causes issues, we cannot guarantee everyone has that so we try to use smaller files as otherwise people start having issues.

**Comment by mpfans** [comment]
> > > The file seems rather large, we tend to have issues loading large files, it gets stuck when loaded by the auto updater, needs testing
> > 
> > 
> > > 
> > 
> > 
> > There are no errors when I execute SQL statements manually, but I don't know if there will be problems with automatic update
> 
> The problem is that unless users have a high SQL packet treshhold it causes issues, we cannot guarantee everyone has that so we try to use smaller files as otherwise people start having issues.

You're right. 
CC @ZhengPeiRu21 帮忙分隔下这个PR文件吧,建议用表来分隔,每个表为一个PR提交.谢谢你!

**Comment by Nyeriah** [comment]
I’ll try importing it to see if MySQL errors

**Review by Nyeriah — APPROVED** [review]

**Comment by ZhengPeiRu21** [comment]
> CC @ZhengPeiRu21 帮忙分隔下这个PR文件吧,建议用表来分隔,每个表为一个PR提交.谢谢你!

嗯，虽然这个好像已经merge了但是我下次会先好好分隔。

**Comment by Nyeriah** [comment]
@ZhengPeiRu21 It's fine, tbh, this is difficult, ideally we'd prefer them to be kept together as much as possible, but if files get too large we start having issues. So it's hard to tell. I loaded this one using the autoupdater and it was fine, so I merged it.

**Comment by Nyeriah** [comment]
It turns out that despite working fine for me, it is giving people issues :\

**Comment by mpfans** [comment]
> It turns out that despite working fine for me, it is giving people issues :\

Does this commit need to revert and resubmit the split PR?

**Comment by Kosiak** [comment]
Gives the error when I start worldserver. Closing connection to mysql. I probably could do some tinkering with mysql but we should not use large files like that maybe.

**Pull request merged**
