### PR TITLE
 Core/Pet:  rewrite madness in pet DB communication and etc

### LINKED ISSUE #3679: server is frozen [$150]
logs:
```
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 2450 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 4527 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 4267 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 2450 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6976 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 499 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 499 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): DELETE FROM character_pet WHERE id = 133
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 5219 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 6297 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 5219 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 7175 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 3 queries not executed.
SQL(p): UPDATE character_pet SET slot = 100 WHERE owner = 208 AND slot = 0
 [ERROR]: [1213] Deadlock found when trying to get lock; try restarting transaction
[Warning] Transaction aborted. 4 queries not executed.
```

 version:AzerothCore rev. c32283fab782+ 2020-11-06 18:05:03 +0000 (master branch) (Unix, Release) 
OS:ubuntu 18.04.4

<bountysource-plugin>

---
There is a **[$20 open bounty](https://www.bountysource.com/issues/94338996-server-is-frozen?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Viste**
## Changes Proposed:
-  improve https://github.com/azerothcore/azerothcore-wotlk/pull/2100
-  also this PR includes cool stuff from my favourite jackpoz https://github.com/TrinityCore/TrinityCore/commit/96dc110f4a353871ac74c82ff4b1bcc4c34156f3
## Issues Addressed:
- Closes #3679 

## Tests Performed:
- build

## How to Test the Changes:

Need test stable masters. Read #1914 there is how to

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Viste** [comment]
@mpfans

**Comment by mpfans** [comment]
I will test it and give feedback.
The test may take 1-2 weeks because it is not a common bug

**Comment by Viste** [comment]
> I will test it and give feedback.
> The test may take 1-2 weeks because it is not a common bug

ok no problem

**Comment by mpfans** [comment]
Testing

**Review by Kitzunu — APPROVED** [review]
nice

**Comment by UltraNix** [comment]
As I remember, @mpfans report some crash related to that PR.

**Comment by Viste** [comment]
> As I remember, @mpfans report some crash related to that PR.

yes because logic of this pets a bit fucked from start i make fix in few days

**Review by UltraNix — APPROVED** [review]

**Comment by Viste** [comment]
Спасибо winfi

**Comment by Winfidonarleyan** [comment]
@Viste чё там, будешь делать?

**Comment by FrancescoBorzi** [comment]
@Viste  what's the status of this PR?

**Comment by FrancescoBorzi** [comment]
Closing for inactivity, we can reopen this if the author wants to complete the job.

**Comment by Winfidonarleyan** [comment]
I'll do it.

**Pull request closed without merging**
