### PR TITLE
fix(CMake/MSVC): Cleanup and enable some warnings

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick from commit (https://github.com/TrinityCore/TrinityCore/commit/73b4b1733a49430b2288417d26f96c24a19c8c28)

Co-Authored-By: Shauren <shauren.trinity@gmail.com>

## Changes Proposed:
- Clean up and enable some warnings

## Issues Addressed:

- Closes 

## Tests Performed:

- Builds
- tested with WITH_WARNINGS

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Shauren** [comment]
I generally avoid commenting on this project but... this PR completely misses the main point of my original commit, adding flags that begin with /W3{4 more digits}

**Comment by Winfidonarleyan** [comment]
> I generally avoid commenting on this project but... this PR completely misses the main point of my original commit, adding flags that begin with /W3{4 more digits}

Hi, thanks for answer. I also wanted to say about the this

**Comment by Winfidonarleyan** [comment]
@Kitzunu need https://github.com/TrinityCore/TrinityCore/commit/73b4b1733a49430b2288417d26f96c24a19c8c28

**Comment by Winfidonarleyan** [comment]
@Kitzunu need 
```cmake
# Move some warnings that are enabled for other compilers from level 4 to level 3
target_compile_options(trinity-compile-option-interface
  INTERFACE
    /w34100  # C4100 'identifier' : unreferenced formal parameter
    /w34101  # C4101: 'identifier' : unreferenced local variable
    /w34189  # C4189: 'identifier' : local variable is initialized but not referenced
    /w34389) # C4189: 'equality-operator' : signed/unsigned mismatch
```

**Comment by Kitzunu** [comment]
Damn been a long day. Thank you Shauren, as always!

**Comment by Viste** [comment]
ахахахха Отца спровацировал на комент, шок, мужик ты хоть иногда думай, что зачем и куда.....

**Comment by FrancescoBorzi** [comment]
> I generally avoid commenting on this project

we don't bite :)

**Review by Winfidonarleyan — APPROVED** [review]

**Pull request merged**
