### PR TITLE
CMake: Use source_groups to represent the source tree

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
- Show the source tree inside ide's. Only Windows (e.g. Visual Studio)
- Original PR from TC https://github.com/TrinityCore/TrinityCore/pull/14471 (for more details)
- Fix space in `showoptions.cmake`

##### TESTS PERFORMED:
- [x] Build in Win
- [x] Build in Linux (Travis)

##### HOW TO TEST THE CHANGES:
1. Apply PR
2. Build project in Cmake
3. Look source tree

### Screenshots
- Tree in VS
image

- Showoptions (in Windows)
```cmake
* AzerothCore revision            : 7a3a9a81b4f1+ 2019-01-08 16:19:35 +0000 (group_source branch)

* Install core to                 : C:/Program Files/AzerothCore
* Install configs to              : C:/Program Files/AzerothCore

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (default)
* Build map/vmap tools            : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable extra features           : No
* Enable vmap DisableMgr checks   : Yes (default)
* Enable extra logging functions  : No (default)
* Show source tree                : Yes - "hierarchical"
```
- Showoptions (In Travis/Linux)
```cmake
* AzerothCore revision            : 24adb8bb17f4 2019-01-08 19:23:44 +0000 (HEAD branch)
* AzerothCore buildtype           : Debug

* Install core to                 : /home/travis/build/azerothcore/azerothcore-wotlk/env/dist
* Install libraries to            : /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/lib
* Install configs to              : /home/travis/build/azerothcore/azerothcore-wotlk/env/dist/etc

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (default)
* Build map/vmap tools            : Yes
* Build core w/PCH                : No
* Build scripts w/PCH             : No
* Show all warnings               : Yes
* Use coreside debug              : Yes
* Use unix gperftools             : Yes
* Use GIT revision hash           : Yes (default)
* Enable extra features           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Enable extra logging functions  : Yes
* Show source tree                : No (For UNIX default)
```

### CODE REVIEW

**Comment by Nefertumm** [comment]
Nice, i was about to sugest this. Great!

**Comment by wetbrownsauce** [comment]
Tested on Windows 10, source tree is now there in my VS. Loving this change. 

Image of before and after this PR:
test

**Comment by BarbzYHOOL** [comment]
And what about adding custom modules to the panel?

**Comment by Winfidonarleyan** [comment]
I thought about it, I didn't check.

**Comment by FrancescoBorzi** [comment]
I think this can be merge already, further improvements can be done in a new PR

**Comment by Winfidonarleyan** [comment]
@FrancescoBorzi Yes

**Pull request merged**
