### PR TITLE
fix(Script/Zul'Aman): adjust Zuljin timers

### PR DESCRIPTION
**Pull request by Grimdhex**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20837
- Closes https://github.com/chromiecraft/chromiecraft/issues/7583

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Rorschach91** [comment]
I could be wrong, but I think that blizzard always uses timers that can be multiplied by 5 (5s-10s-15s etc....).

**Comment by Nyeriah** [comment]
No, blizzard timers are erratic

**Comment by Nyeriah** [comment]
Was there any source for this?

**Comment by Rorschach91** [comment]
> No, blizzard timers are erratic

good to know.

**Comment by Rorschach91** [comment]
> Was there any source for this?

Like this [PR](https://github.com/azerothcore/azerothcore-wotlk/pull/20682) the timers were taken from the report.

**Comment by amed80** [comment]
Could the timers be changed even for the first casts and recast ?
Phase 1 :
[Grievous Throw](https://wowgaming.altervista.org/aowow/?spell=43093) : 7-23s (this applies to both first cast and recast)

[Whirlwind](https://wowgaming.altervista.org/aowow/?spell=17207) : 12-29s (this applies to both first cast and recast)


Phase 5:
[Flame Breath](https://wowgaming.altervista.org/aowow/?spell=43215) : First at 16-26s then repeat each 06-25s.

[Flame Whirl](https://wowgaming.altervista.org/aowow/?spell=43213) : always between 12-26s (this applies to both first cast and recast)

**Comment by Grimdhex** [comment]
> Could the timers be changed even for the first casts and recast ?
> 
> Phase 1 :
> 
> [Grievous Throw](https://wowgaming.altervista.org/aowow/?spell=43093) : 7-23s (this applies to both first cast and recast)
> 
> 
> 
> [Whirlwind](https://wowgaming.altervista.org/aowow/?spell=17207) : 12-29s (this applies to both first cast and recast)
> 
> 
> 
> 
> 
> Phase 5:
> 
> [Flame Breath](https://wowgaming.altervista.org/aowow/?spell=43215) : First at 16-26s then repeat each 06-25s.
> 
> 
> 
> [Flame Whirl](https://wowgaming.altervista.org/aowow/?spell=43213) : always between 12-26s (this applies to both first cast and recast)
> 
> 

Not without sources.

**Comment by amed80** [comment]
It's from the videos linked in the report:

those are the exact numbers from the videos:
image

Grievous Throw, Whirlwind and Flame Whirl first cast had similar interval to it's repeat timers

**Review by Rorschach91 — APPROVED** [review]

**Pull request merged**
