### PR TITLE
feat(Tools/MMAPs): Output the time spent in a human readable format 

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/6e34e07c48000e666ec15b26682eb15fb2f5f901
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
Have you tried? 
I will use the following bat when using this PR
```
@echo off
cls

echo ##############################################################

echo.
echo Extracting Cameras and DBC and MAPS...
mapextractor.exe

echo ##############################################################

echo.
echo Extracting VMAPS
vmap4extractor.exe

echo ##############################################################

echo.
echo Building VMAPS
vmap4assembler.exe Buildings vmaps

echo ##############################################################

echo.
echo Building MMAPS
mmaps_generator.exe --threads 8

echo ##############################################################

echo.
echo Press any key to exit
pause NULL

```
After the extraction, the window does not stop there, but disappears

**Comment by IntelligentQuantum** [comment]
> Have you tried? I will use the following bat when using this PR
> 
> ```
> @echo off
> cls
> 
> echo ##############################################################
> 
> echo.
> echo Extracting Cameras and DBC and MAPS...
> mapextractor.exe
> 
> echo ##############################################################
> 
> echo.
> echo Extracting VMAPS
> vmap4extractor.exe
> 
> echo ##############################################################
> 
> echo.
> echo Building VMAPS
> vmap4assembler.exe Buildings vmaps
> 
> echo ##############################################################
> 
> echo.
> echo Building MMAPS
> mmaps_generator.exe --threads 8
> 
> echo ##############################################################
> 
> echo.
> echo Press any key to exit
> pause NULL
> ```
> 
> After the extraction, the window does not stop there, but disappears

It works fine in my private src i will try again thank you

**Comment by IntelligentQuantum** [comment]
@pklloveyou 
Screenshot_20220502_103541

**Comment by pklloveyou** [comment]
I'll try again with win10. Thank you very much

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
