### PR TITLE
fix(DB/SmartScript) Quest - Cleansing the Waters missing RP

### PR DESCRIPTION
**Pull request by M4th3m4tic4l**
## Changes Proposed:
-  Creates Aggonis creature event
```
There should be an animation when Aggonis appears.
There should be a short pause before he can be attacked. During a pause, he says "Fools! You seek to abjure my father's presence? Death awaits you, mortals!"

Smart_Scripts:
Script 0 /*Casts 'Red Lightning' when Aggonis appears*/
Script 1 /*Wait four seconds to speak*/
Script 2 /*When Aggonis appears, set a flag to 2 (not attackable).*/
Script 3 /*Wait seven seconds to remove the non-attackable flag.*/
Script 4 /*When Aggonis appears, set a flag to 256 (Disables combat/assistance with PlayerCharacters (PC)).*/
Script 5 /*Wait seven seconds to remove '256' flag.*/
Script 6 /*When the non-attackable and non-combat with players flag is removed (after seven seconds), Aggonis will start attacking any player within a range of 20.
Script 7 /*If Aggonis kills the player, he disappears after one second.*/

call_timed_actionlist

/*Creates 'call_timed_actionlist' for Aggonis text.*/

Creature_Text
/*creates the missing text*/

Creature_Text_Locale
 /*translates it into Spanish*/
```

## Issues Addressed:

- https://github.com/chromiecraft/chromiecraft/issues/4347
- https://github.com/azerothcore/azerothcore-wotlk/issues/13610

## SOURCE:

https://www.youtube.com/watch?v=K_110B9rjs0
https://www.youtube.com/watch?v=Xlu6gUYSGLk

## Tests Performed:

- 
WoWScrnShot_110522_025550

- 
WoWScrnShot_110522_025555

-
WoWScrnShot_110522_025558

## How to Test the Changes:

1. Insert the sql in your database and then open the game.
.quest add 9427 and then go to the area to summon Aggonis with the item

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
hmm... sql failure. I think we had this issue before with the whole /* */ being used at the end of hte file.
Try adjusting that and see if it passes

**Comment by M4th3m4tic4l** [comment]
ok thanks :)

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
> ok thanks :)

Good job.

**Comment by Gultask** [comment]
The line can be repeated if you `.combatstop`.
And if you enter his hitbox he'll start attacking before you can attack him.

**Comment by M4th3m4tic4l** [comment]
My internet was down. I just read your message @Gultask , and yes, i think i made a lot of mistakes here, but understand one thing, i haven't edited something with smart scripts for a long time, i think since last year, so i'm still rusty XD

Maybe later I'll rewrite it again, but there's no hurry to merge it.

**Comment by M4th3m4tic4l** [comment]
completed

**Comment by Gultask** [comment]
You think you made lots of mistakes?
This is nothing. You should see the horrors I manage to make in SAI :p

Jk. I'll be able to test again this weekend.

**Comment by Gultask** [comment]
Yes. This weekend specifically 🙈 

Tested. Working fine, ty.

**Pull request merged**
