### PR TITLE
fix(Scripts/Temple of AhnQiraj): Qiraji Champion.

### LINKED ISSUE #12933: [AQ40] Qiraji Champion (15252)
### Current Behaviour

Casts Vengeance (25164) when below 25% HP

### Expected Blizzlike Behaviour

Should only cast Vengeance (25164) when all the members of their formation are killed, similarly to Qiraji Gladiator from AQ20. Also does an emote when casting it (%s becomes enraged!)
They are surrounded by Qiraji Mindslayers and/or Qiraji Slayers

Also:

1. Queues Cleave (40504) on aggro and every 0-14.6s afterwards
2. Casts Frightening Shout (19134) on self (AoE) every 20-40s
3. Casts Knock Away (11130) on target every 10-30s

### Source

Retail

### Steps to reproduce the problem

`.go c id 15252`
check if spells are cast
kill their formation members.
see if it casts Vengeance once all are dead.

### Extra Notes

Qiraji Champions and formation spawns are currently unimplemented. This would probably require my PR adding their spawns and formations: https://github.com/azerothcore/azerothcore-wotlk/pull/12862

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/64a891f5ab62f016bc84d85dcbdcb29b7b4f89dc

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12933

**Test it with #12862**

## Issues Addressed:

- Closes #12933

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c id 15252`
check if spells are cast
kill their formation members.
see if it casts Vengeance once all are dead.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Vengeance didn't work for me. Everything else was cast, though.

**Comment by UltraNix** [comment]
@Gultask Tested with your PR?

**Comment by Gultask** [comment]
yup

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Gultask** [comment]
Looks good 👍

**Comment by Nefertumm** [comment]
Build failing

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Comment by UltraNix** [comment]
@acidmanifesto Done.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
