### PR TITLE
fix(Scripts/ZulGurub): Added more missing areatrigger whispers.

### LINKED ISSUE #12224: ZG Areatriggers are wrong part 2
### Current Behaviour

Follow up to https://github.com/azerothcore/azerothcore-wotlk/issues/12187 it was requested I put this in a new issue.

### Expected Blizzlike Behaviour

Entering UD area and Edge of Madness, text event should go off on a delay similar to bridge.

UD area:

image

image

EoM:

image

image

### Source

_No response_

### Steps to reproduce the problem

1. Go to areas, it won't do anything.

### Extra Notes

Need to find the areatriggers for this

### AC rev. hash/commit

79839a4eacd765a3779d182d65e4b8299619453c

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12224

## Issues Addressed:

- Closes #12224

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info [here](#12224)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
Not getting whispered when I reach either areatrigger.

**Comment by UltraNix** [comment]
@temperrr Should be okay now.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
approved in the review but i guess something got merge so now we got a conflict.

**Comment by UltraNix** [comment]
@acidmanifesto Done.

**Comment by Gultask** [comment]
Works 👍

**Pull request merged**
