### PR TITLE
fix(Core): Dropped loot containers acting soul bound after looking inside them

### LINKED ISSUE #6164: Dropped loot containers acting soul bound after looking inside them
Original Chromiecraft report: [https://github.com/chromiecraft/chromiecraft/issues/753](https://github.com/chromiecraft/chromiecraft/issues/753)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Dropped, lootable containers (lockboxes, oozing bags, fishing trunks, etc...) once opened- but not looted act soul bound and can not be traded, mailed, or placed into the bank. without giving an in game error "Already looted" or "Unable to mail soul bound items"

Logging out and back in will fix it temporarily, at least until it's opened again.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should still be tradeable after looking inside. Heavy junkboxes are the only way to get Ravenholdt reputation passed a certain point. Most rogue guides say to leave at least one item in it to keep from losing the box. Then mail them to whatever character is farming the rep. [https://www.wowhead.com/item=16885/heavy-junkbox#comments](https://www.wowhead.com/item=16885/heavy-junkbox#comments) To do this you would need to be able to mail them.

##### SOURCE:

https://www.wowhead.com/item=34109/weather-beaten-journal#comments shows fishing boxes being traded.

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .additem 20768 (oozing bag)
2.  .additem 4634 (iron lockbox) - need to unlock first
3.  .additem 21228 (Mithril bound Trunk)
4. .additem 6645 (Bloated Mudsnapper)
5.  Open to look at items, don't loot
6.  Try to mail, trade, or place the container in your bank.

##### EXTRA NOTES:

Applied to all containers I tried to open

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98815908-dropped-loot-containers-acting-soul-bound-after-looking-inside-them?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dillyns**
## Changes Proposed:
-  Allow the trading of non-soulbound containers that have already been looted.

## Issues Addressed:

- Closes #6164
- Closes chromiecraft/chromiecraft#753

## Tests Performed:

- Looted a https://wowgaming.altervista.org/aowow/?item=21228 without emptying the loot.
- Traded it to another character successfully.
- Other character looted the container and it contained the same loot.

## How to Test the Changes:

1. Add a https://wowgaming.altervista.org/aowow/?item=21228 to the inventory of one character.
2. Look at the loot inside the container without removing it from the container.
3. Trade the container to another character.
4. After the trade, the other character should be able to loot the container and see the same loot as the first character.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by dillyns** [comment]
I am pretty new to working with the core files, so I am unsure if there are any edge cases that making this change would affect.
Trading soulbound containers is still not allowed, so ideally this should only affect containers such a fishing boxes or lockboxes, or other non-soulbound containers.
My only concern is that I don't know why this check was originally included, so if anyone knows if it was supposed to prevent some particular issue that would be some great info

**Comment by UltraNix** [comment]
Those was about some dupe items (you could dupe loot inside the item):
https://github.com/TrinityCore/TrinityCore/commit/15dc23ad45f20e147dcfc01abd94b438cc0318ea
https://github.com/TrinityCore/TrinityCore/commit/15847b2f2f8be359f7d152a9f088c4a4052e9622

I don't know if it's still possible (it was over 10 years ago and many protections has been made to core since that time).

**Comment by UltraNix** [comment]
@dillyns Can you fix the conflicts?

**Comment by FrancescoBorzi** [comment]
ping @dillyns

**Comment by Kitzunu** [comment]
No activity since June 18th on the account. Perhaps someone wants to take over =)

**Comment by UltraNix** [comment]
Superseded by #7826

**Pull request closed without merging**
