### PR TITLE
fix(DB/creature_text): Jin'do the Hexxer's RP - GRATS!

### LINKED ISSUE #11751: [ZG] Bloodlord Mandokir - Jin'do the Hexxer's RP emote cannot be heard/seen from Bloodlord Mandokir's arena
### Current Behaviour

Bloodlord Mandokir, after killing 3 players, levels up and yells "DING!" and Jin'do yells "Hey! Grats, mon!" but it cannot be seen from Mandokir's encounter area.

### Expected Blizzlike Behaviour

After leveling up, players in Mandokir's arena should be able to hear/see in chat Jin'do yelling "Grats!"

### Source

>As far as I've heard by the way, sometimes Bloodlord would shout: "DING!" whenever he killed someone and levelled. And at times, after shouting "DING!", he'd be congratulated by Jin'Do the Hexxer: "GRATS!" ([source](https://www.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=12646))

>When Bloodlord Mandokir yells his: "Ding!" when he levels up by killing 3 players, Jin'do the Hexxer replies with a "Grats!", which is commonly said in guilds when a guildmember levels up. ([source](https://wowwiki-archive.fandom.com/wiki/Jin'do_the_Hexxer#Quotes))

### Steps to reproduce the problem

1. Create 2 or more characters and add them to a group. Make one easily killable.
2. .go xyz -12212 -1959 133 309
3. Kill the Vilebranch Speaker and start the encounter.
4. Make one character go to Jin'do while the other stays with Mandokir.
5. Make Mandokir kill the latter and then revive them until 3 kills
6. Compare the chat logs of both characters.

### Extra Notes

Bloodlord Mandokir (ID: 11382)
Jin'do the Hexxer (ID: 11380)
Level Up! (ID: 24312)

I think there's a mistake in the present quote. All pre-Cata sources claim that Jin'do yells only "Grats!" and not "Hey! Grats, mon!", which is the line he yells in the [Cataclysm ZG 5-man](https://www.wowhead.com/sound=24260/vo-zg2-jindo-mandokir-levels-up-01).

I personally prefer "Hey! Grats, mon!" over just "Grats!" but that's beside the point.
WoWScrnShot_051522_000300
WoWScrnShot_051522_000410

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Si1ker**
Pull Request by [sílker](https://www.chromiecraft.com/en/armory/?character/ChromieCraft/s%C3%ADlker)

## Changes Proposed:
-  Change text range
-  Change text to blizzlike

## Issues Addressed:

- Closes #11751

## SOURCE:

https://wowpedia.fandom.com/wiki/Jin%27do_the_Hexxer#Quotes

## Tests Performed:

- None

## How to Test the Changes:

1. Go ZG
2. ENgage encounter
3. Let Broodlord kill you for him to level up and Jindo should say GRATS! which should be visible to youin chat

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Si1ker** [comment]
PR created following https://www.azerothcore.org/wiki/how-to-create-a-db-pr

Need clarification whether if the file name does not matter anymore or how to get the rev code for the file name, ty.

**Comment by acidmanifesto** [comment]
Use the rev for the file name still. We just dont use the rev line as the first line of the sql anymore.

**Comment by Si1ker** [comment]
> Use the rev for the file name still. We just dont use the rev line as the first line of the sql anymore.

@acidmanifesto how it is being done nowadays? how to get the number after rev_xxxxxxx.sql  ?
(online btw)

**Comment by acidmanifesto** [comment]
> > Use the rev for the file name still. We just dont use the rev line as the first line of the sql anymore.
> 
> @acidmanifesto how it is being done nowadays? how to get the number after rev_xxxxxxx.sql  ?
> (online btw)

https://www.azerothcore.org/pages/rev-generator/

Use the file name only.

**Comment by Si1ker** [comment]
Ok wiki is outdated then, ty

**Comment by Si1ker** [comment]
Tested.

image

Please approve & merge @Nyeriah @temperrr

**Comment by Nyeriah** [comment]
It's a consensus among the AC developers, as well as the TC developers, that broadcast_text shouldn't be changed. I can't merge the PR with changes to broadcast_text, the CI checks won't pass.

I need a second opinion on that @Kitzunu

**Comment by Kitzunu** [comment]
dont change broadcast text unless there's an actual sniff of it. Just set the broadcast text field in creature_text to 0

**Comment by Si1ker** [comment]
> dont change broadcast text unless there's an actual sniff of it. Just set the broadcast text field in creature_text to 0

Didn't think that option, omg! o.o tyty

**Comment by Si1ker** [comment]
Working perfectly 🐱 

image

image

Yep, 1 issue minus for the ZG project,
@Nyeriah / @temperrr  go merge!

**Comment by Si1ker** [comment]
### Source for the second text

1- https://www.youtube.com/watch?v=HuvFjCnor38&t=300s | 5:00
2- https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic) | Look into the "Quotes" section

**Review by Nyeriah — APPROVED** [review]

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
