### PR TITLE
fix(DB/Quest): Ending the Bloodcurse

### LINKED ISSUE #4085: [Quest] Ending the Bloodcurse missing text on gameobject action
##### CURRENT BEHAVIOUR:

The creature only spawns and attack the player.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Atoph the Bloodcursed should yell: _Who dares to defile our beloved ?_

[Proof](https://youtu.be/XyH_d4IGZFo?t=260)

##### STEPS TO REPRODUCE THE PROBLEM:

1. q a 9683
2. go c id 17713 
3. modify swim speed 15 and get to the top of the island ( don't know a specific tele location)
4. right-click on the status and wait for the creature to spawn

##### OTHER CUSTOMIZATIONS: None

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95569549-quest-ending-the-bloodcurse-missing-text-on-gameobject-action?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6331: Quest: Ending the Bloodcurse- possible to destroy the Statue of Queen Azshara multiple times
Original report from Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/848

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

The Statue of Queen Azshara can be destroyed multiple times when doing the quest 'Ending the Bloodcurse'. 
Each occurrence will spawn another Atoph the Bloodcursed.
All Atoph the Bloodcursed will stand idle behind the statue. which is not the correct place for him to spawn.

Screenshot from 2021-06-11 21-40-16 copy

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When Atoph the Bloodcused is spawned, the statue should be in flames, and it should not be possible to click the statue again until he is killed/ despawns. 

##### SOURCE:

https://youtu.be/pWmAazW3ULo?t=159
##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 9683 (Ending the Bloodcurse)
2. .go object 044734
3. R click the statue
4. R click the statue again
5. Notice 2 spawns of Atoph the Bloodcursed behind the statue, and the statue not on fire waiting to be clicked atain

##### EXTRA NOTES:

Related to https://github.com/azerothcore/azerothcore-wotlk/issues/4085

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99233621-quest-ending-the-bloodcurse-possible-to-destroy-the-statue-of-queen-azshara-multiple-times?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Fixed the event for the quest

## Issues Addressed:

- Closes #4085 
- Closes #6331
- Closes https://github.com/chromiecraft/chromiecraft/issues/848

## SOURCE:

https://youtu.be/pWmAazW3ULo?t=159

## Tests Performed:

- Tested in-game on Windows 10

## How to Test the Changes:

**This test should be done with two players**

### Test case 1
1. .quest add 9683
2. .go object 044734
3. Use the statue of queen azshara
4. Player 2 can't use the statue due to NPC being summoned
5. After NPC dies, the fires around the statue despawn and it becomes usable by player 2

### Test case 2
Repeat steps 1-4 above but don't kill the NPC.
Wait for him to despawn after 300 seconds and check for Statue reset

## Known Issues and TODO List:

Complete

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Eldarix** [comment]
Checked, works as expected i think:

WoWScrnShot_062921_145102
WoWScrnShot_062921_145129
WoWScrnShot_062921_145142
WoWScrnShot_062921_145202

But for the Test case 2:

WoWScrnShot_062921_145456
WoWScrnShot_062921_150512

I waited 11 minutes but one of the nagas is still there.

**Comment by claudiodfc** [comment]
Thank-you @Eldarix for the test. I'll push a change for his despawn and this should be good to go 👍🏼

**Comment by claudiodfc** [comment]
@Eldarix If possible, could you try watching if he de-spawns in 1 min when not in combat and 30 seconds after his death?

**Comment by iraizo** [comment]
Test results from https://github.com/azerothcore/azerothcore-wotlk/pull/6477

### Behavior without this pull request:
- NPC stands still.
- NPC despawns 30 seconds after death (being looted, im not sure if theres a difference).
- The statue does not catch fire and is usable by any other player/ the player itself to spawn infinite NPC's.
- NPC does not despawn or takes a considerable large amount of time.

### Behavior with this pull request:
- NPC moves in front of the statue searching for the enemy (player).
- NPC despawns after not being in combat for 60 seconds
- The state catches fire and isnt useable by any other player.

### Tests passed:
- [ ] [Test case 1](https://github.com/azerothcore/azerothcore-wotlk/pull/6477#issue-674552762)
- [ ] [Test case 2](https://github.com/azerothcore/azerothcore-wotlk/pull/6477#issue-674552762)
- [x] [Test case 3](https://github.com/azerothcore/azerothcore-wotlk/pull/6477#issuecomment-870656859)

### Description on failed tests:
- Test case 1 failed because of the statue not [resetting](https://i.imgur.com/W9MuLlS.jpg) even after 13 minutes.
- Test case 2 failed because its dependant on test case 1 (since it wont reset).

**Comment by iraizo** [comment]
revised the test results based on https://github.com/azerothcore/azerothcore-wotlk/pull/6477/commits/086db1720ffdafb8eb123d5f3b11f094f568318e

**Comment by claudiodfc** [comment]
@FrancescoBorzi Ready to be merged

**Comment by FrancescoBorzi** [comment]
good job @claudiodfc and thank you very much @iraizo for your testing feedback, much appreciated!

**Pull request merged**
