### PR TITLE
fix:(DB/Creature): Little Adeline

### PR DESCRIPTION
**Pull request by Kitzunu**
Issue: No open

Currently was missing from the game.

It is a pretty cool npc :D

### CODE REVIEW

**Comment by Remberance** [comment]
yes, i've already text this SQL in my server. it WORKED!

**Comment by Si1ker** [comment]
- No errors found during SQL implementation into DB
- Tested on last rev/hash, working great. 👍

**Comment by BarbzYHOOL** [comment]
thank you testers!

**Comment by BarbzYHOOL** [comment]
@Kitzunu thank you

**Pull request merged**
