### PR TITLE
fix(Core/Spell): Apply AURA_STATE_FAERIE_FIRE to Faerie Fire

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Apply AURA_STATE_FAERIE_FIRE to Faerie Fire to disallow going stealth or invisible

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5215

## Tests Performed:

- Builds
- Tested in-game

## How to Test the Changes:

1. .aura 16498
2. Try to use stealth
3. .add 9172
4. Try and use the potion

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ErnestoGonzalezC** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
@ErnestoGonzalezC thanks for your feedback, but can you please be more descriptive about what you tested?

also, please note:

> REMEMBER: when testing a PR that changes something generic (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but especially check that the PR does not cause any regression (i.e. introducing new bugs).

> For example: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but we should test Y and Z as well.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by ErnestoGonzalezC** [comment]
@FrancescoBorzi Basically I followed @kitzunu instructions. I used the aura (16498) on me and then I tried to use invisible (failed) then I tried to use (Invisibility Potion = 9172) and I can't make myself invisible therefore the PR is effective :)

**Comment by FrancescoBorzi** [comment]
@ErnestoGonzalezC as the PR changes are quite "generic" (i.e. targetting a file that manges many things,  `src/server/game/Spells/SpellInfo.cpp`) and as other spells are involved:

image
 
I would say it's better to also double-check those in cases like this

**Comment by ErnestoGonzalezC** [comment]
@FrancescoBorzi I've been testing this PR for several days and it doesn't seem to cause any kind of bug

**Comment by FrancescoBorzi** [comment]
thanks @ErnestoGonzalezC for your feedback!

**Pull request merged**
