### PR TITLE
fix(DB/locale): Some translations of quests in the Draenei starting area

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
-  Add missing English translations in the Draenei starting zone.
-  There are still some missions missing, but at least there are several, then I will open another PR with more translations.

## Issues Addressed:

- Closes 

## Tests Performed:

- Windows 10

## How to Test the Changes:

1. Create a Draenei character
2. Use a game client in Spanish (esES or esMX)
3. Review at least the first 20 initial missions.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
Change double quotes for single quotes for strings and we're ready to go

**Comment by pangolp** [comment]
> Change double quotes for single quotes for strings and we're ready to go

When he returned from his trip, he reviewed those changes and continued with other pending translations. Pd. We would have to find a way to reload the table where you see the objectives, because all of them reload, but I think that one does not. At least I always had to turn it off and on again to see the changes.

**Comment by Helias** [comment]
what is the status of this PR? WIP?

**Comment by pangolp** [comment]
I will see if I can download the PR here on my local machine, and try to change the quotes so that it can be merged. Then, when I get back, I will continue doing more translations in another PR.

**Comment by pangolp** [comment]
47 queries executed, 47 success, 0 errors, 0 warnings

**Pull request merged**
