### PR TITLE
fix(Scripts/BlackTemple): exclude off tank of the Azzinoth Flame's charge

### PR DESCRIPTION
**Pull request by Grimdhex**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20129
- Closes https://github.com/chromiecraft/chromiecraft/issues/7396#issue-2565901451

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1..tele bt
2. .go creature id 22917
3. going to fase 2 (under 65% hp)
4. place the flames of azzinoth on the warglaives launched by illidan. obviously you need 2 characters to do this.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Rorschach91** [comment]
I could be right to the idea of exclude tanks for the charge mechanics, expecially after reading WoWHead guide, but I continue to think that charge range should be increased. 
Watching some videos i have noted that charge range on tbc classic is not the same on AzerothCore.
For this reason I tested the phase with 45 yard 2 days ago.
In any case I would like to read the opinion of the others.

**Comment by Grimdhex** [comment]
Does 45y works as what you seen on videos ?

**Comment by elthehablo** [comment]
Let's include that in another PR if needed/confirmed

**Review by elthehablo — APPROVED** [review]

**Comment by Rorschach91** [comment]
Lol, I was testing it.

**Comment by elthehablo** [comment]
That's good. However looking at the code it should work and cause no additional issues.

By all means still test it though.

**Pull request merged**
