### PR TITLE
fix(DB/object): Fixed skull piles despawning on quest Speaking with Nezzliok

### PR DESCRIPTION
**Pull request by Asthalor**
## Changes Proposed:
-  Reduced the spawn of the skull piles from 900 seconds to 1 so they wont dissapear

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7199
- Closes https://github.com/chromiecraft/chromiecraft/issues/1324

## Tests Performed:

-Be Horde
-.quest add 585
-.go object 9986
-.gm off
-Pick up the skull.
-The pile only dissapears for a brief moment
-Repeat for objects 10135, and 10030

## How to Test the Changes:

1. Be Horde
2. quest add 585
3. .go object 9986
4.  gm off
5. Pick up the skull.
6. The pile only dissapears for a brief moment
7. Repeat for objects 10135, and 10030

**Test redone with the generic pile of bones inside the quest piles**

https://user-images.githubusercontent.com/87535580/128197230-e79bd5a7-bd20-485e-97d9-cd7fb6f911eb.mp4

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by LukasVolgger** [comment]
Hmmm i'm not happy with both options. As in the video linked to the issue it looks more good. 

Maybe there is something else you can do?

**Comment by Asthalor** [comment]
> Hmmm i'm not happy with both options. As in the video linked to the issue it looks more good.
> 
> Maybe there is something else you can do?

I played with a lot of flags to see if something worked better. Because is a chest it will need to despawn to delete de sparkles and reset the loot, so the 1 second spawn can work , but we can add an item in the same place with the same displayID so it looks like the bones, so when the object is picked it wont appear as so? Just thinking out loud.

**Comment by Kitzunu** [comment]
Is there someone who has a video or something how it works on retail?

**Comment by Asthalor** [comment]
> Is there someone who has a video or something how it works on retail?

There is a wow classic video on the chromiecraft issue. Thats what i took as an example. Here it is:

https://youtu.be/KC7xSHUJTjg?t=55

**Comment by Asthalor** [comment]
Ive added some "hacks" that i think looks good.
By adding 3 piles of bones at the same place and the same size we can camouflage the respawning of the quest pile.
That way we will stop seeing the sprinkles when the item is picked, and at the same time it wont look like its respawning again after picking the item up.

I hope it is better now. Ive been trying to fix it without doing weird things, but i cant see the fix by only changing the 3 pile items.

**Review by LukasVolgger — APPROVED** [review]

**Pull request merged**
