### PR TITLE
fix(DB/Creature): Ragefire Shaman

### PR DESCRIPTION
**Pull request by Kitzunu**
@BarbzYHOOL Reported that the NPC currently is not doing any melee attacks. This PR extends the timers a bit of when the NPC can cast spells so it will be able to melee attack too

test before and after the PR
1. .tele ragefire
2. .npc add tem 11319
3. .npc add tem 11318
4. fight ⚔️

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
it works fine for me, I haven't tested extensively but it seems much better than what it was

**Comment by FrancescoBorzi** [comment]
good job @Kitzunu and thanks @BarbzYHOOL for testing!

**Comment by BarbzYHOOL** [comment]
i removed label because i'd like someone else to test

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL if it's already better than the current version and not introducing new bugs, would be enough already, but ok.

**Comment by BarbzYHOOL** [comment]
the code is taken from TC and changed several small parameters

**Comment by pklloveyou** [comment]
Tested. Very good

**Comment by FrancescoBorzi** [comment]
good job everyone!

**Comment by BarbzYHOOL** [comment]
@pklloveyou have you tested before the PR too?

**Comment by BarbzYHOOL** [comment]
@Kitzunu thank you, merged

**Pull request merged**
