### PR TITLE
fix(DB/Spell): Make Amplify Magic Ranks 4-7 as Positive

### LINKED ISSUE #4565: Mage: Amplify magic bug
##### CURRENT BEHAVIOUR:

- The spell is applied as a debuff.  -> https://wowgaming.altervista.org/aowow/?spell=43017

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- It should be a benefit

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast the spell

##### EXTRA NOTES:

- The spell works correctly until rank 4, since then it becomes a debuff.

##### OPERATING SYSTEM:

- Windows 10

##### MODULES:

- none

##### OTHER CUSTOMIZATIONS:

- none

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/96531483-mage-amplify-magic-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Voxstrasza**
## Changes Proposed:
-  Correctly set Amplify Magic Ranks 4-7 as Positive Buffs

## Issues Addressed:
- Closes #4565

## Tests Performed:
- Ran SQL, tested on mage.  It fixes the issue.

## How to Test the Changes:
- Create a mage and learn all ranks of Amplify Magic (need lvl 77)
- Cast Amplify Magic rank 4, 5, 6 and 7 on yourself and ensure that they are positive buffs.

## Target Branch(es):
- [x] Master

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]
Good use of spell_custom_attr, good job :)

Just for reference; EFF0 and EFF1 are made positive here :)

**Review by Helias — APPROVED** [review]

**Comment by ErnestoGonzalezC** [comment]
Tested, good job. @Voxstrasza

**Comment by ErnestoGonzalezC** [comment]
</img>

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @Voxstrasza and @ErnestoGonzalezC

**Pull request merged**
