### PR TITLE
Missing options in conf file (auth and worldserver)

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
**Changes proposed:**

* Added missing options
* Removed unnecessary options

**Target branch(es):** master.

**Issues addressed:** Closes https://github.com/azerothcore/azerothcore-wotlk/issues/874

**Tests performed:** Tested build, tested in-game

**Known issues and TODO list:**

- Add description **Instance.SharedNormalHeroicId**
- Add description **TeleportTimeoutNear**
- Add description **TeleportTimeoutFar**

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Why no freedualtalentspec??

**Comment by Winfidonarleyan** [comment]
Because, this option is not used anywhere.

**Comment by BarbzYHOOL** [comment]
True I can't find anything about it for mangos or TC either

**Comment by BarbzYHOOL** [comment]
Thank you

**Pull request merged**
