### PR TITLE
feat(DB/locales): import locales from TC

### PR DESCRIPTION
**Pull request by Helias**
I compared the two DBs AC and TC locales and I imported the missing AC locales from TC.
Before the comparison, I imported into my local DB all the opened PRs about locales/translations to avoid to import them twice.

## Tests Performed:
- executed the script twice (second time without the INSERT INTO version)

## How to Test the Changes:
- execute the script twice (second time without the INSERT INTO version)

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
```
How to Test the Changes:
execute the script twice (second time without the INSERT INTO version)
```

@Helias I don't think this test is meaningful at all as you've already done it, if it worked in your machine it does not make much sense to test it again in someone else's. Rather I'd just either make someone with a non-English client test those objects or just merge this as it's a minor change and should not break anything.

**Comment by LukasVolgger** [comment]
@FrancescoBorzi i agree. Just merge it like my PRs.

**Review by Kitzunu — APPROVED** [review]
as long as build is happy I am happy

**Comment by Kitzunu** [comment]
Ty =)

**Pull request merged**
