### PR TITLE
fix(DB/Creature): Several equipment fixes

### PR DESCRIPTION
**Pull request by Kitzunu**
Co-Authored-By: Eridium <6587064+Killyana@users.noreply.github.com>

## Changes Proposed:
-  For once I actually know the original author :D
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
image

**Comment by Mitradis** [comment]
Table `creature` have creature (Entries: 18488, 19149, 0) one or more with equipment_id 3 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 18488, 19149, 0) one or more with equipment_id 4 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 18488, 19149, 0) one or more with equipment_id 3 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 18488, 19149, 0) one or more with equipment_id 4 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 18488, 19149, 0) one or more with equipment_id 3 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 17136, 17137, 0) one or more with equipment_id 1 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 17136, 17137, 0) one or more with equipment_id 1 not found in table `creature_equip_template`, set to no equipment.
Table `creature` have creature (Entries: 17136, 17137, 0) one or more with equipment_id 2 not found in table `creature_equip_template`, set to no equipment.

**Review by Nyeriah — APPROVED** [review]

**Comment by sudlud** [comment]
@Kitzunu
what was the source of these changes? is this based on sniffs? I'm too blind right now to see this info here anywhere.
Thanks!

**Comment by Nyeriah** [comment]
It’s a trinity cherry pick, yes

**Comment by sudlud** [comment]
> It’s a trinity cherry pick, yes 

Alright, thanks got the info!

**Pull request merged**
