### PR TITLE
fix(Core/QuestTracker): do not store quest if quest_id is null

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
Co-Authored-By: Yehonal yehonal.azeroth@gmail.com

## Changes Proposed:
-  do not store quest if quest_id is null in `Player::CompleteQuest`
-  a bunch of types replaced by author

## Issues Addressed:
- Closes none, just a minor code improvement
- could be related to https://github.com/azerothcore/azerothcore-wotlk/issues/4005 but not sure about it

## Tests Performed:
- Not tested

## How to Test the Changes:

- Set `Quests.EnableQuestTracker` to `1` in `worldserver.conf`
- Make sure the `acore_characters.quest_tracker` table is properly filled when completing quests
- Optionally, you can use this old web tool to have a better view: https://github.com/TrinityCore/TC-Quest-Tracker

## Known Issues and TODO List:

None

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
Do we need to add xinef: to the comments?
Imho it makes no sense

**Comment by FrancescoBorzi** [comment]
> Do we need to add xinef: to the comments?
> Imho it makes no sense

I just moved that code block, I'm not adding the comments. They were already there, so better keeping them in order to know that part comes from SunwellCore.

**Review by Helias — APPROVED** [review]

**Comment by pangolp** [comment]
It would seem that everything would work correctly.
I leave some images of the tests carried out.

WoWScrnShot_122920_131349
WoWScrnShot_122920_131413
WoWScrnShot_122920_131421

**Review by pangolp — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@pangolp did you check this?

```
Make sure the acore_characters.quest_tracker table is properly filled when completing quests
```

**Comment by pangolp** [comment]
No, I hadn't checked that, now I'm trying it again.

**Comment by pangolp** [comment]
Now it works wonderfully.

**add:**
add

**complete:**
complete

**abandon:**
abandon

**Pull request merged**
