### PR TITLE
fix(Core/Spells): Charging unit should always reach its target even i…

### LINKED ISSUE #9454: Intercept Affected By Crowd Control Incorrectly
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2449

If an warrior Intercepts a druid that has Nature's grasp  on him, warrior is rooted BEFORE reaching the druid.
This is also happening with frost mage. If Frostbite activate in the moment that warrior press Charge/Intercept warrior freeze in initial place.

Tester: confirmed for Nature's Grasp. Couldn't check Frostbite as the timing is a bit tricky for one person.

The Nature's Grasp problem is even worse than stated. The intercept fails, NG procs, and the warrior is rooted, although the druid target is stunned and debuffed. Once the roots fade, the warr seems to attack (no animation, but a "Miss" above the druid at the 10 second mark), which then procs NG for a second time.

https://user-images.githubusercontent.com/81782124/144391200-5e9ee5e9-44e9-4fda-b837-d9a60b211549.mp4

### Expected Blizzlike Behaviour

If a warrior Intercepts a druid that has Nature's grasp on him, warrior should be rooted AFTER warrior reach the druid.
If Frostbite activate in the moment that warrior press Charge/Intercept warrior MUST freeze AFTER he reach mage.

https://wowgaming.altervista.org/aowow/?spell=20252

### Source

Didn't find any details on direct interactions between Intercept and Nature's Grasp, but don't think the expected behaviour above is controversial, at least for NG. https://wowpedia.fandom.com/wiki/Nature's_Grasp?oldid=2336204 does say "Procs off melee only, does not proc off spells or ranged attacks." 

### Steps to reproduce the problem

1. Your druid target must have Nature's Grasp active on him
2. Use berserk stance and use INTERCEPT
3. Warrior don't reach druid, he's being rooted on initial place
4. Also with mage is harder to reproduce, mage must cast frostbolt on you and when warrior charge/intercept and frostbolt reach warrior and Frostbite is activated warrior remain in the place when frostbite activated instead of reaching the mage.
5. I think second issue will be solved with first one, because seems to be the same mechanics and be a charge/intercept issue

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…f stunned/rooted.

Fixes #9454

## Issues Addressed:

- Closes #9454
- Closes https://github.com/chromiecraft/chromiecraft/issues/2449

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Your druid target must have Nature's Grasp active on him
Use berserk stance and use INTERCEPT
Warrior reaches druid and being rooted on destination place

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by temperrr** [comment]
works as described.

**Comment by creativemonkeyz** [comment]
There is also a problem with charge + hunter's traps like in below video:
https://www.youtube.com/watch?v=bZaElQJySHE&ab_channel=Alex-GeorgianLupoiu
(i have no idea how to do a shorter video in order to capture the problem so i upload it on my yt channel)
Explaining video:
As you can see in the video, hunter put  freezing trap between me and him, and at his position he put Fire trap. As you can see, first time i'm frozen before i reach him BUT then the Fire trap is activated. That means that  mechanically i reach him, but visually i don't. So there is the initial problem: Warrior MUST reach the target and then be affected by something else (freezing trap, frostbite, nature grasp, other charge, etc)

**Comment by UltraNix** [comment]
@creativemonkeyz Do not comment on closed issues. Make a new issue ticket instead.

**Comment by creativemonkeyz** [comment]
Hello,I commented here: fix(Core/Spells): Charging unit should always reach its target even i… by UltraNix · Pull Request #10192 · azerothcore/azerothcore-wotlk (github.com)it's ok? it looks like this is merged with my issue
    Pe marți, 18 ianuarie 2022, 09:50:27 EET, UltraNix ***@***.***> a scris:  
 
 


@creativemonkeyz Do not comment on closed issues. Make a new issue ticket instead.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
