### PR TITLE
fix (core) GOs live add

### PR DESCRIPTION
**Pull request by acidmanifesto**
This fixes gameobjects issue with it being added, not showing on the fly but on restart. Gameobjects now show on the fly when added with gameobject add cmd
image

## Changes Proposed:
-  fix gameobjects not spawning on the fly (live) when added with gm cmds

## Issues Addressed:

- Closes Cant locate the report but alot of mentions in discord

## Tests Performed:

- builds
- performs

## How to Test the Changes:

1. just do a .gobject add 32349
2. observe you now have a working mailbox at your position
3. do sugar booger

## Known Issues and TODO List:

- [x] sugar booger
- [x] wut?

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by porkserver** [comment]
Confirmed working
Screen Shot 2022-03-26 at 9 27 29 PM
Screen Shot 2022-03-26 at 9 27 02 PM

**Comment by acidmanifesto** [comment]
Standby. will see about adding back in the IsGameObjectStaticTransport, they were in there for a reason. will attempt to rewrite it and test.

**Comment by acidmanifesto** [comment]
readded in static transports and redid the if statements. results still shows it working on my end. this is good for merging.

**Comment by acidmanifesto** [comment]
Removing the to be merge label for right now pending further evaulation. This PR may introduce a memory leak. We are attempting to confirm\rewrite this pr at the moment.

**Comment by acidmanifesto** [comment]
Alrighty. we are good to go. Hopefully.

**Comment by acidmanifesto** [comment]
@LannyE locally on my end it shows fine. however i think we need you to do a fetch upstream so the tests can rerun with the appropiately revision. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by SilentCLD** [comment]
@acidmanifesto Are you sure this is correct? I cannot reproduce the bug on master (9e7d1e2a3af7), no break point is hit for `ObjectMgr::AddGOData` and unless intellisense is failing `ObjectMgr::AddGOData` is only called from 2 places in `OutdoorPvP.cpp`.  If anything wouldn't it be a visibility issue (object create packet isn't being sent perhaps)?

**Comment by acidmanifesto** [comment]
> @acidmanifesto Are you sure this is correct? I cannot reproduce the bug on master ([9e7d1e2](https://github.com/azerothcore/azerothcore-wotlk/commit/9e7d1e2a3af7b70c6f2f5ed3d23ea4c9c65c2454)), no break point is hit for `ObjectMgr::AddGOData` when spawning an object via `gobject add 32349` and unless intellisense is failing `ObjectMgr::AddGOData` is only called from 2 places in `OutdoorPvP.cpp`. If anything wouldn't it be a visibility issue (object create packet isn't being sent perhaps)?

the bug is present for several staffers, and users and we even have testers confirmed with feed back this will llive spawn a gameobject with the .gobject add cmd without the need to restart the server for it to replicate with this PR. If you yourself is not having a issue then we will need to figure out what custom changes you have done on your end, because this feature was mentioned not working for well over 6 months and counting currently.

**Comment by SilentCLD** [comment]
> > @acidmanifesto Are you sure this is correct? I cannot reproduce the bug on master ([9e7d1e2](https://github.com/azerothcore/azerothcore-wotlk/commit/9e7d1e2a3af7b70c6f2f5ed3d23ea4c9c65c2454)), no break point is hit for `ObjectMgr::AddGOData` when spawning an object via `gobject add 32349` and unless intellisense is failing `ObjectMgr::AddGOData` is only called from 2 places in `OutdoorPvP.cpp`. If anything wouldn't it be a visibility issue (object create packet isn't being sent perhaps)?
> 
> the bug is present for several staffers, and users and we even have testers confirmed with feed back this will llive spawn a gameobject with the .gobject add cmd without the need to restart the server for it to replicate with this PR. If you yourself is not having a issue then we will need to figure out what custom changes you have done on your end, because this feature was mentioned not working for well over 6 months and counting currently.

Fully stock core running on 9e7d1e2a3af7, even wiped the DB. No issues spawning objects via command, is it something that only happens when the core has been online for some time?
Is this related to the spawning using mod-guildhouse issue in #custom-module in discord? If so i posted a potential fix for that in there.
image

**Comment by acidmanifesto** [comment]
So are you using the guild house module? As i am not currently.

**Comment by SilentCLD** [comment]
> So are you using the guild house module? As i am not currently.

No, it's a stock install, no modules

**Comment by Bogir** [comment]
I've fixed spawns GO by adding `true` value here. Nothing else was neded. GO spawned manually or by core on live server start be visible right after spawn.

изображение

**Comment by porkserver** [comment]
Testing the mailbox as specified worked pre-patch but I could not interact with it until restart in Dalaran. But it did appear.  
With PR it worked as intended on spawn and could use immediately
Testing was done on clean build clean DB

Guildhouse phasing was fixed with Suggestions in discord by Bogir / SilentCLD

**Comment by SilentCLD** [comment]
Again, I have no issues on 9e7d1e2a3af7 with spawning or interacting on any continent.
Adding a breakpoint at ObjectMgr.cpp Line 2284 (`GameObject* go = sObjectMgr->IsGameObjectStaticTransport(data.id) ? new StaticTransport() : new GameObject();`) is never hit for me, even during startup
image

@Bogir true is the default if nothing is provided so not sure how that's making a difference

@porkserver What commit did you test pre-patch on?

**Comment by acidmanifesto** [comment]
> Again, I have no issues on [9e7d1e2](https://github.com/azerothcore/azerothcore-wotlk/commit/9e7d1e2a3af7b70c6f2f5ed3d23ea4c9c65c2454) with spawning or interacting on any continent. Adding a breakpoint at ObjectMgr.cpp Line 2284 (`GameObject* go = sObjectMgr->IsGameObjectStaticTransport(data.id) ? new StaticTransport() : new GameObject();`) is never hit for me, even during startup image
> 
> @Bogir true is the default if nothing is provided so not sure how that's making a difference
> 
> @porkserver What commit did you test pre-patch on?

i guess what i should be asking, is what is your compiling enviroment you are running? is it windows or other?

**Comment by SilentCLD** [comment]
> i guess what i should be asking, is what is your compiling enviroment you are running? is it windows or other?

Windows 10 x64 Professional

**Comment by SilentCLD** [comment]
I also have a core running based on 0ce1c9635bd0e9a0f7a28085f789d10864612f87 (5 day uptime) that works perfectly fine as well. Ubuntu 20.04.3 x64

**Comment by acidmanifesto** [comment]
Closing the PR, until we can get a better understanding at why some people are experiencing the issue and why some people are not. This way we do not risk introducing any other issues since we all pretty much not sure of the root issue.

**Comment by Bogir** [comment]
> > @Bogir true is the default if nothing is provided so not sure how that's making a difference

I also thought so, but noticed `true` here and test it in module. Issue with invisible GO was solved.
https://github.com/azerothcore/azerothcore-wotlk/blob/bd2844bb2d247ad69145fdb12acc6b213a087ac0/src/server/scripts/Commands/cs_gobject.cpp#L144

**Comment by SilentCLD** [comment]
@acidmanifesto wait where did you get gob 32349 from? Did you see someone report that object specifically? It is a Mailbox from Ironforge with the Ironforge faction (55) assigned. Yes a Horde player shouldn't(?) be able to interact with it but works for Alliance

**Comment by acidmanifesto** [comment]
> @acidmanifesto wait where did you get gob 32349 from? Did you see someone report that object specifically? It is a Mailbox from Ironforge with the Ironforge faction (55) assigned. Yes a Horde player shouldn't(?) be able to interact with it but works for Alliance

it was a random mailbox chosen, as far as i am aware, factions are able to access each other's mailboxes and i was able to use it just fine with the PR.

**Comment by SilentCLD** [comment]
With 32349 if I change the faction from 55 (Ironforge) to 714 (Horde generic), the same as the one outside Orgrimmar bank (gob 195562) it works for both factions, maybe the core doesn't fully support this?
I can't say for sure if it is Blizz-like to interact cross faction or not but the core is definitely doing something to stop it.

**Comment by acidmanifesto** [comment]
> With 32349 if I change the faction from 55 (Ironforge) to 714 (Horde generic), the same as the one outside Orgrimmar bank (gob 195562) it works for both factions, maybe the core doesn't fully support this?
> I can't say for sure if it is Blizz-like to interact cross faction or not but the core is definitely doing something to stop it.

I understand where you are coming from but since that would be a possible issue and not anything dealing with this now closed pr it would be best to open up a issue. We decided to close this as the inconsistency of if the problem exsisted that this pr addressed and root cause is not fully understood.

**Pull request closed without merging**
