### PR TITLE
fix (DB\Creature\Instance): Maraudon CTM fix

### PR DESCRIPTION
**Pull request by acidmanifesto**
## Changes Proposed:
-  Fixes 16 creature entires that seem to either not swim or evade when player enters water.

## Issues Addressed:

- Closes chromiecraft/chromiecraft#2768
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10138
## Tests Performed:

- builds
- performs

## How to Test the Changes:

1. Piss things off in Maraudon and run to the water
2. They now swim or move in the water.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Closes https://github.com/chromiecraft/chromiecraft/issues/2763 ?

**Comment by acidmanifesto** [comment]
> Closes [chromiecraft/chromiecraft#2763](https://github.com/chromiecraft/chromiecraft/issues/2763) ?

different area, but i can do a pr for that correction as well

**Comment by Shineslippers** [comment]
https://github.com/chromiecraft/chromiecraft/issues/2768

ID 13282

**Comment by Shineslippers** [comment]
Updated https://github.com/azerothcore/azerothcore-wotlk/issues/10138

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
