### PR TITLE
fix(Scripts/TheEye): make Void Reaver abilities ignore LOS

### PR DESCRIPTION
**Pull request by elthehablo**
with the minimum 18.0f range and maximum 20.0f range there was a small dead zone for arcane orbs. also LOS seems to sometimes be an issue
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/6889

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
Yeah you are correct. I might have a better way to fix this

**Comment by elthehablo** [comment]
The problem was probably that with the original code, if the target is selected correctly, but the spellcast fails for some reason (LOS for instance) nothing else happened. In this way, the spellcast failing should trigger it being cast on a nearby target.

It looks weird tho haha

**Review by Nyeriah — APPROVED** [review]

**Comment by balleny** [comment]
how it should work:

from all targets in Line of Sight: throw bomb on target that is 20+ yards away. if no such target is available, throw bomb on target within 18 yards range.
Dont consider targets out of line of sight at all

see also: https://youtu.be/YlCfJB7RN6U?t=1610

**Comment by balleny** [comment]
this caused more regressions than it solved

https://github.com/chromiecraft/chromiecraft/issues/6949

**Pull request merged**
