### PR TITLE
Core/Account: Add total time played in account

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
-  Add total time played for account

##### ISSUES ADDRESSED: 
- No

##### TESTS PERFORMED:
- [x] Tested in game
- [x] Tested build
- [x] Tested OS Windows

##### HOW TO TEST THE CHANGES:
- Apply test commit
- To stay in the game for a while.
- Quit the game completely
- See the value in the database auth.account - totaltime

##### KNOWN ISSUES AND TODO LIST:
- [x] Test OS Unix

##### Target branch(es):
- Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
This is for a custom feature (for my project) but I think we could add this directly into the core.

1) I have this in my db on linux, so it works.
totaltime: 6777

2) In which unity is it? unix time? seconds?

3) Should we have a configuration option to enable/disable this ? It's a question, feel free to voice your opinion. Without this PR, the total played time is calculated on a per character basis, so if your character is deleted, there is no way to retrieve the total time played since you created your account.

**Comment by Winfidonarleyan** [comment]
> In which unity is it? seconds?

Yes, seconds

> Should we have a configuration option to enable/disable this? 

I think that need not

**Comment by Winfidonarleyan** [comment]
It is strange that the Travis error, I'm fine.

**Comment by Stoabrogga** [comment]
> It is strange that the Travis error, I'm fine.

Travis error:
```
/home/travis/build/azerothcore/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:111:5: fatal error: 
      field 'recruiterId' will be initialized after field 'm_total_time'
      [-Wreorder]
    recruiterId(recruiter),
    ^
```

I think you'll have to put "m_total_time(TotalTime)" directly after "m_expansion(expansion)" in "WorldSession.cpp" to match the order in the header file:
```
m_expansion(expansion),
m_total_time(TotalTime),
```

**Comment by Winfidonarleyan** [comment]
@Stoabrogga It won't help :/

**Comment by BarbzYHOOL** [comment]
Thank you @Winfidonarleyan ;)

And thank you @Stoabrogga for the review!!

**Pull request merged**
