### PR TITLE
fix(DB/Spell): Fixed Syndicate Conjuror continues casting "Bright Campfire" when attacked

### PR DESCRIPTION
**Pull request by Asthalor**
I changed the cast flag of the shadowbolt so if on combat they will stop the casting of the bonefire

## Changes Proposed:
-  Changed the flag from 64 to 1 of the shadow bolt so they will stop the casting of shadowbolt
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6888
- Closes https://github.com/chromiecraft/chromiecraft/issues/1142

## SOURCE:

Some comments of the issue said they casting the bonefire was normal

## Tests Performed:

- .go c id 2590 
- Attack them while they are casting the bonefire

## How to Test the Changes:

1.  .go c id 2590 
2.  Attack them while they are casting the bonefire
3. They should stop casting that and attacking you 

Video test

https://user-images.githubusercontent.com/87535580/126374189-e550602f-3cf0-45d3-a063-f84c573e9ad7.mp4

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]

**Comment by wetbrownsauce** [comment]
Tested.  

Pre-PR: When a conjurer is making a campfire, they will continue to do so even when attacked.  

Post-PR: When a conjurer is making a campfire, they will interrupt the cast and begin using regular attacks (shadowbolt).  

However, if you body-pull (aggro without attacking them), they will still cast the campfire to completion. Their voidwalker will attack as expected.

**Comment by LukasVolgger** [comment]
Thx @wetbrownsauce ! Should they stop casting and attack if they were aggro?

**Comment by Asthalor** [comment]
Good find.
I will have to make them able to use the shadow bolt on melee distance so they can stop the casting of the bonefire and attack as they should

**Comment by syssneck** [comment]
I try to test it myself, but I'm just waiting forever for them to cast the damn Campfire. :'D

**Comment by wetbrownsauce** [comment]
You are correct. I was too high level to reliably aggro them. Tested with a level 31 character and they correctly cancel their campfire cast to begin shadowbolt if attacked or proximity aggro'd

**Pull request merged**
