### PR TITLE
feat(Core/BattlegroundQueue): add limited Battleground.QueueAnnouncer

### LINKED ISSUE #5092: Feature: limited Battleground.QueueAnnouncer
Only show the announcement when X-1 players are queued, where X is the min amount of players required to start the BG.

Suppose that X=4 is the number of players required to join Warsong Gulch.

`Battleground.QueueAnnouncer.Enable = 1` (current)

```
Warsong Gulch 1/4
Warsong Gulch 2/4
Warsong Gulch 3/4
Warsong Gulch 4/4
```

`Battleground.QueueAnnouncer.Enable = 2` (new conf)
```
Warsong Gulch 3/4
```

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Added new config option `Battleground.QueueAnnouncer.Limited.Enable`
```ini
#
#    Battleground.QueueAnnouncer.Limited.Enable
#        Description: Show announce only if left players in queue = 1
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

Battleground.QueueAnnouncer.Limited.Enable = 0
```

## Issues Addressed:
- Closes #5092

## Tests Performed:
-

## How to Test the Changes:
- Check bg queue

## Known Issues and TODO List:
- [ ]

## Target Branch(es):
- [x] Master
 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/developers @pklloveyou please check this

**Comment by ErnestoGonzalezC** [comment]
Tested, works correctly.

**Comment by Ramys** [comment]
Tested..
Works!

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @Winfidonarleyan and thanks @ErnestoGonzalezC and @Ramys for testing this!

**Comment by Ramys** [comment]
I thank you!

**Pull request merged**
