### PR TITLE
Core: Crashfix.

### PR DESCRIPTION
**Pull request by UltraNix**
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@UltraNix feel free to merge it if you tested.

**Review by Nefertumm — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Hmm, nice

**Comment by SanLorenzo59** [comment]
I had reported this crash to @UltraNix this morning on Discord. I have applied this fix to my local server, this crash has not happened any more.

**Comment by Nefertumm** [comment]
Great to hear @SanLorenzo59
@FrancescoBorzi merge this when you can as mac build is broken and I can't merge.

**Pull request merged**
