### PR TITLE
CMake - Made it easier to add your custom scripts

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
**Changes proposed:**

-  Added a sort of tutorial
-  Added cmake examples because this is the second time I add a script made by someone on AC and there were problems

**Target branch(es):** 2.x / master

**Tests performed:** Someone should try to compile in case I broke something

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Hmm I reused my old branch, I don't know if it was wise. And there is a conflict I don't know why.

**Comment by ShinDarth** [comment]
this is not about github but git in general. Try to merge master branch into your branch and you will clearly see all conflicts. if you look on google about solving git merge conflicts I'm sure you'll find a lot of stuff, but please poke us here if you need any help!

**Comment by BarbzYHOOL** [comment]
@ShinDarth I did as you said and now there is an useless merge commit.

**Comment by ShinDarth** [comment]
@BarbzYHOOL merge commits are fine, no problem

**Comment by BarbzYHOOL** [comment]
And reusing the same branch that had been already merged ? I thought it would not pose any problem though

**Comment by ShinDarth** [comment]
ideally the branch should always be updated with latest master (which means pulling & merging master **into** your branch)

**Pull request merged**
