### PR TITLE
fix (Core/Player) Double health regen from spirit

### PR DESCRIPTION
**Pull request by Tereneckla**
## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15952

## SOURCE:

Script is from PaperDollFrame
PaperDollFrame shows Health Regen / second
Health Regen ticks are every 2 seconds

## Tests Performed:

- tested ingame

## How to Test the Changes:

target self
.damage 1000
note down the value restored and the time between ticks
compare to value displayed by hovering over the spirit stat

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Where is this from? How can it be confirmed?

**Comment by Tereneckla** [comment]
As described in the PR:
The paperdoll formula shows Health Regen / second
This formula was copied for the server, but Health Regen ticks happen every 2 seconds

To 100% confirm someone should log into wotlk classic

**Comment by Kitzunu** [comment]
I will rephrase then, what is a paperdoll formula 😅

**Comment by Tereneckla** [comment]
It's the one used by the client to show the transformed value of various stats
For spirit for example
image

As per the comment https://github.com/azerothcore/azerothcore-wotlk/pull/15955/files#diff-baadebd8cd1117ca48225f316a5ab3fd5fd55b20963394d302341147183db067R5135 in the Life Regen formula it is based on that

Currently every tick of life regen is as high as the paperdoll says, but paperdoll is per second and ticks happen every 2 seconds

**Comment by Kitzunu** [comment]
Got it, thanks for explaining

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
