### PR TITLE
[CORE] Group Not remove for Last Player on LFG

### PR DESCRIPTION
**Pull request by Franklampardst**

### CODE REVIEW

**Comment by starrheld** [comment]
What is this?

**Comment by sucofog** [comment]
Lol what is this? xDD

**Comment by Franklampardst** [comment]
lol i really not work with PR

**Comment by Franklampardst** [comment]
i add a script for fix this issue but cant share :| anyone can help me?

**Comment by sucofog** [comment]
@Franklampardst Post it on discord group:
discordapp.com/channels/217589275766685707/217589275766685707

**Comment by starrheld** [comment]
Please whisper on Discord with what you were trying to PR.

**Comment by Franklampardst** [comment]
@sucofog @starrheld looool i cant use with PR you tell me discord :)

**Comment by ShinDarth** [comment]
@Franklampardst I guess you put the branches wrongly:

image

you should select to merge **from** **yourfork/your_feature_branch** -> **to** **master**

please read: 

https://github.com/azerothcore/azerothcore-wotlk/wiki/Contribute#how-to-create-a-pull-request

**Pull request closed without merging**
