### PR TITLE
fix(DB/SAI): Skorn

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Fix various aspects of the Skorn area:
- Winterskorn Woodsman: Use emote 'STATE_WORK_CHOPWOOD' (234) instead of 'STATE_WORK_MINING' (233)
- Various Winterskorn Vrykul: Adjust position, orientation, emotes etc.
- Disable random movement for Winterskorn Rune-Caster (23668) and Winterskorn Oracle (23669) to prevent them from falling down the towers
- Winterskorn Raider (riding on Proto-Drake): Increase flight speed by setting "move_type" to 1 (run) and allow mounted combat
- Winterskorn Shield-Maiden / Warrior / Raider / Berserker: Spar with other Vrykul and restrict talking to the sparring partners
- Quest "Burn Skorn, Burn!": Add fire effect after using the torch
- Winterhoof Brave: Set react state to defensive; cast spell "Loan Spyglass" when selecting the gossip option "Please loan me that spyglass." (only shown if the spyglass is not already in the inventory)
- Westguard Sergeant: Set react state to defensive; cast spell "Loan Spyglass" when selecting the gossip option "Sergeant, loan me your spyglass." (only shown if the spyglass is not already in the inventory)

###### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested in-game

##### HOW TO TEST THE CHANGES:
- preparation Horde:
```
.quest remove 11256
.quest remove 11257
.quest remove 11258
.quest remove 11259
.quest remove 11260
.quest add 11256
```
- preparation Alliance:
```
.quest remove 11248
.quest remove 11245
.quest remove 11246
.quest remove 11247
.quest remove 11249
.quest add 11248
```
- ```.go 2054.65 -4080.44 235.804 571```
- Call Winterhoof Brave / Westguard Sergeant:
  - Loan spyglass
  - Should not attack on his own
- Finish quest "Burn Skorn, Burn!": For each house burnt a fire effect should start shortly after using the torch
- Check the Skorn area:
  - Winterskorn Woodsman: Should use the correct emote for chopping wood; should face trees or tree stumps
  - Vrykul sparring: Should correctly face each other and play attack emotes and use random talk texts
  - There should be no Vrykul with strange states, e.g. random movement with sit state
  - The Winterskorn Raiders mounted on Proto-Drakes should be a little bit faster and attack without dismounting
  - Check the Winterskorn Rune-Casters and Winterskorn Oracles on the towers: They should no longer walk randomly around and fall down the tower

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by comix1988** [comment]
what you have fixed works everything correctly.
Can you try to fix the item "winterhoof emblem" (ID 33340) used to call Winterhoof Brave? The item calls the npc but dosen't dismiss he.
Good jobn @Stoabrogga

**Comment by Stoabrogga** [comment]
> Can you try to fix the item "winterhoof emblem" (ID 33340) used to call Winterhoof Brave? The item calls the npc but dosen't dismiss he.

Done. Could you please try once more, @comix1988 ?

**Comment by comix1988** [comment]
work perfectly.
good job @Stoabrogga

**Comment by Stoabrogga** [comment]
Merged. Thanks for your feedback and testing this PR, @comix1988 . If you find the time, could you please also take a look at #1795 ? It's very easy to test.

**Pull request merged**
