### PR TITLE
refactor(Core/DBCEnums): Reword NYI comment.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:
- Changes `TODO: Needs implementation` to `NYI` in the summon properties group section comments.

## Issues Addressed:

- Closes unreported issue.

## SOURCE:

N/A

## Tests Performed:

- Untested.

## How to Test the Changes:

1. Nothing should be different.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
Im curious. NYI is a English thing. Usually we have it spelled out once on the file it is on with the first round of abbreviation before using initials only in the rest of the files when not universal. 
Example: Not Yet Implemented (NYI)
Then we use NYI thru out the remainder of the individual file.

**Comment by Nyeriah** [comment]
I'm going to say it's probably better worded currently as Mdic suggests

**Comment by Nyeriah** [comment]
Hm I wouldn't touch the //@todo as that's a doxygen tag afaik, @Kitzunu knows better

**Comment by acidmanifesto** [comment]
> I've adjusted a section of 'needs implementing' enums higher in the file, and spelled it out on the first instance of it. If I misunderstood what you meant and it needs further correction, let me know.

Yupe. U did exactly as i suggested.

**Comment by heyitsbench** [comment]
> Hm I wouldn't touch the `//@todo` as that's a doxygen tag afaik, Kitzunu knows better

Might be a question for Kitzunu, but should that be added across the file to unimplemented flags or just on the first instance?

**Comment by Kitzunu** [comment]
I'd use it on all. also use 3 forward slashes and preferably lowercase todo `/// @todo`

**Comment by heyitsbench** [comment]
Done. I gotta stop mistakenly mentioning users though.

**Comment by acidmanifesto** [comment]
i am re-running failed workflow as it had nothing to do with the pr.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
