### PR TITLE
feat(Core/Chat): delete delay for channels

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Delete old pussywizard's delay for channels

## Tests Performed:
- Locally

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
@Winfidonarleyan is thsi ready? or still draft?

**Comment by Kitzunu** [comment]
More crap being deleted. Awesome

**Comment by TheDdraig** [comment]
I see Pussy Wizard is at it again... xD

**Comment by malcrom** [comment]
Noooooooo!!!!!! PussyWizard is a god!!!!!

**Comment by TheDdraig** [comment]
He must be with that confidence, we are all a delay in his presence.

**Comment by malcrom** [comment]
I wish I had his confidence.

**Comment by acidmanifesto** [comment]
Pussy Warlock has now entered the channel.

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan is thsi ready? or still draft?

Yes, ready

**Pull request merged**
