### PR TITLE
fix(DB/Core): "Sons of Hodir" quests / areas

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- Increase the reputation reward for the "Sons of Hodir" quests by 30%, as it was mentioned in the 3.3.0 patch notes:
  https://wow.gamepedia.com/Patch_3.3.0#Reputation
- King Jokkum is now only visible in phase 4 in Dun Niffelem
- Quest "Battling the Elements":
  - Reduce respawn time from 300 to 10 seconds for the Seething Revenants
  - Change faction to "Sons of Hodir" for the Frost Giant Stormheralds (they are trying to cool the anvil) and remove one of them who stands too far away from the anvil
- Quest "In Memoriam": Apply correct phase mask to the Horn Fragments (otherwise the quest cannot be completed)
- Ensure that the quest "A Monument to the Fallen" has to be finished before "Blowing Hodir's Horn" becomes available
- Hide "Hodir's Helm", "Hodir's Spear" and "Hodir's Horn" until their quests have been finished
- Quest "Forging a Head": The Dead Iron Giants will now randomly spawn either 3 Stormforged Ambushers (with correct emote text) or add 2 Fireforged Eyes to the players inventory
- Add the small event playing after the quest "Raising Hodir's Spear" is rewarded
- Add the sparkle effect on Hodir's Helm after the quest "Polishing the Helm" is rewarded
- Fix an error message concerning conditions which are not met in "SendListInventory" (it should be a debug message) which showed when opening Lillehoff's inventory:
  Exalted with "Sons of Hodir":
  ```
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 50335
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 50336
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 50337
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 50338
  ```
  Not exalted:
  ```
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 44133
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 44134
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 44135
  ERROR: SendListInventory: conditions not met for creature entry 32540 item 44136
  ```
- Fix an error message when dismounting Snorri during the quest "Battling the Elements":
  ```
  ERROR: Vehicle GuidLow: 5011460, Entry: 30124 attempts to uninstall, but already has STATUS_UNINSTALLING! Check Uninstall/PassengerBoarded script hooks for errors.
  ```
  The cause of this was a missing condition in "Vehicle::Uninstall" to check if the vehicle is actually a minion (this will also fix similar error messages concerning other vehicles).

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
- tested build on Ubuntu 16.04 / clang 7
- tested successfully in-game

##### HOW TO TEST THE CHANGES:
- Reset all quests and reputation; teleport to Dun Niffelem:
  ```
  .mo re 1119 -42000
  .q rem 12915
  .q rem 12924
  .q rem 12966
  .q rem 12967
  .q rem 13010
  .q rem 13011
  .q rem 12975
  .q rem 12976
  .q rem 12985
  .q rem 12987
  .q rem 13001
  .q rem 13420
  .q rem 13108
  .go 7399.97 -2597.45 814.863 571
  ```
- Complete prerequisite quests:
  ```
  .q a 12915
  .q c 12915
  .q rew 12915
  .q a 12956
  .q c 12956
  .q rew 12956
  .q a 12924
  ```
- Proceed with the quests in Dun Niffelem

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
UPDATE `creature` SET `MovementType` = 1, `spawndist` = 5 WHERE `id` IN (30120, 30387, 30160);

**Comment by pklloveyou** [comment]
因为我的英语读得不太好，所以我立刻完成了所有的任务，没有发现任何问题。

**Comment by Stoabrogga** [comment]
@pklloveyou 
Sorry, but I don't understand your language.

**Comment by pklloveyou** [comment]
@Stoabrogga Tested, nice

**Comment by Knindzagxg** [comment]
Tested, all changes are perfect.

Only thing i'm unable to test on Blizz or find more information is about Fjorn, near anvil.
He's visible during quests towards it, but i'm not sure was he supposed to be visible after as well - At the moment he's not -> I will check more about him, and if anyone have any extra information lemme know.

WoWScrnShot_082419_161203

**Comment by pklloveyou** [comment]
This is wrong, but I do not have such problems, strange.

**Comment by Stoabrogga** [comment]
@Knindzagxg 
Like I told on discord it would be strange that he still lives, as he is killed by the player during the quest "Mending Fences":
https://wow.gamepedia.com/Mending_Fences
https://wow.gamepedia.com/Fjorn

**Comment by Knindzagxg** [comment]
Yeah, all is good. I was wondering why i was able to see him on retail sometimes.
Looks like its when Timewalking is up, sometimes he will appear which is weird.

So yeah, all great mate, really awesome job.
Time to find new thing to work on :D

**Pull request merged**
