### PR TITLE
Swap SPELL_ATTR3_SUPRESS_TARGET_PROCS with SPELL_ATTR2_NO_INITIAL_THREAT

### PR DESCRIPTION
**Pull request by T1ti**
## Changes Proposed:
-  Until about a month ago when the spell flags got updated https://github.com/azerothcore/azerothcore-wotlk/pull/5311 , it was believed that `SPELL_ATTR3_SUPRESS_TARGET_PROCS ` was `SPELL_ATTR3_NO_INITIAL_AGGRO  `and was coded as such. 
-  Replace all implementations of `SPELL_ATTR3_SUPRESS_TARGET_PROCS ` by the new revealed flag `SPELL_ATTR2_NO_INITIAL_THREAT` (which used to be `SPELL_ATTR2_UNK22 ` and wasn't implemented).

Note : no initial threat and aggro could be slightly different behavior... But afaik from my testing it really didn't seem to do much
All it seems to do is ignore threat values definited in spell_threat table ? which is very rarely used
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Spells/Spell.cpp#L5073

Here's an example of the type of spells that used SPELL_ATTR3_SUPRESS_TARGET_PROCS (862 spells)
image
and the type of spells that use SPELL_ATTR2_NO_INITIAL_THREAT (248 spells)
image

## Issues Addressed:

- Closes 

## Tests Performed:

-  None

## How to Test the Changes:

1. Verify that it builds correctly and doesn't cause issues with new/old spells that used the flags

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/developers please check this

**Review by UltraNix — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers we need someone to test this one

**Review by Helias — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers we need someone to test this ingame

**Comment by Nefertumm** [comment]
@azerothcore/testers it would be awesome if someone could test this <3

**Comment by stoudtlr** [comment]
first spell i tested was hunter's mark and it causes the mob to immediately agro the hunter

**Comment by Nefertumm** [comment]
Expected behaviour is not to have aggro right?

**Comment by stoudtlr** [comment]
correct

**Comment by Nefertumm** [comment]
@T1ti can you look at that?

**Comment by T1ti** [comment]
Hunter's mark doesn't have "No initial threat", it had the old "supress atrget procs" flag, and it also has "generates no threat"
The question is, which flag is supposed to do what, that behaviour could come from generates no threat not working properly.

image

**Comment by T1ti** [comment]
I'm pretty sure the no aggroing behavior it should come from "generate no threat".

image

Here's mind soothe, it instead has "generate threat only on miss"

Mind vision also has generate no threat 
image

Some spells like Holy shock do have "supress target procs" so it makes absolutely no sense that this attribute would make it so you don't aggro.

To me it's just that "generate no threat" is not properly implemented

**Comment by T1ti** [comment]
https://github.com/vmangos/core/commits/development/src/game/Spells/Spell.cpp

Look at vmangos september 5 commits for reference

**Comment by Ragelezz** [comment]
Fix merge conflicts please.

**Comment by FrancescoBorzi** [comment]
@T1ti do you plan to finish this?

**Comment by T1ti** [comment]
No this is more intricate than expected as several different flags need to be changed and fixed

**Comment by FrancescoBorzi** [comment]
ok then I'm closing this, it can be of course reopened if needed

**Pull request closed without merging**
