### PR TITLE
fix(DB/gameobject): Adjust Position For Some Copper Veins

### PR DESCRIPTION
**Pull request by Delcidx**
## Changes Proposed:
 Adjust xyz pos for gobject:
- 5027
- 5471
- 5240
- 4661
- 4759
- 5325
- 5454
- 6494

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5354
https://github.com/chromiecraft/chromiecraft/issues/440

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5329

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5274
https://github.com/chromiecraft/chromiecraft/issues/416

## SOURCE:

N/A

## Tests Performed:

- SQL applied
- Tested in game

## How to Test the Changes:

- .go gobject GUID from changes proposed

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Hacki95** [comment]
Why did you close this?

**Comment by Delcidx** [comment]
> Why did you close this?

I was told that you or another contributor will fix the mining nodes using vmangos data.

**Comment by FrancescoBorzi** [comment]
@Delcidx @Hacki95 the bug is still open. Shall we merge this instead?

**Comment by Hacki95** [comment]
Sure

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
