### PR TITLE
fix(Scripts/ZulGurub): Prevent from summoning multiple Edge of Madnes…

### LINKED ISSUE #12327: [ZG] Edge of madness - Can summon multiple bosses
### Current Behaviour

EOM can summon multiple of the same bosses by using "gurubashi-mojo-madness" at the same time

### Expected Blizzlike Behaviour

Should summon only one boss

### Source

Find during a player test on CC PTR

### Steps to reproduce the problem

Difficult to reproduce in local but:
- 2  char use at the same time "gurubashi-mojo-madness" ( .additem 19931 )

### Extra Notes

_No response_

### AC rev. hash/commit

[32ba21d](https://github.com/azerothcore/azerothcore-wotlk/commit/32ba21d02900bc4f236af029c24ac2de27390db5)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…s bosses.

Fixes #12327

## Issues Addressed:

- Closes #12327

## Tests Performed:

- Not tested.

## How to Test the Changes:

2 char use at the same time "gurubashi-mojo-madness" ( .additem 19931 )

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
There is no fire to use the item on,
there is no edge of madness event active when doing .event activelist
activating an event does not make the brazier appear.

**Comment by UltraNix** [comment]
@temperrr This is not related to this PR.

**Comment by temperrr** [comment]
Hmm correct, but wonder why the brazier is gone, it used to be there 1/2 weeks ago :?

**Comment by UltraNix** [comment]
I will look at that event dates.

**Comment by UltraNix** [comment]
@temperrr On my local looks okay. The brazier is there and the active event is Gri'lek.

**Comment by temperrr** [comment]
Ye grilek is wrong xd

**Comment by temperrr** [comment]
AC does something very odd with game events

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
