### PR TITLE
fix(DB/SAI): Improved behavior of Illusion of Jandice Barov (need feedback!)

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Illusion of Jandice Barov should be immune to spells
-  Illusion of Jandice Barov should be scripted
- This has been ported over from [TC](https://github.com/TrinityCore/TrinityCore/commit/e33384d4ddbd4477f8cc5cae6e0679ab914595a5) and all credits go to the original authors

## Issues Addressed:
There is a long description [here](https://github.com/TrinityCore/TrinityCore/issues/26023). The relevant parts should be:

- Jandice Barov mirror images are immune to all damages and can't be killed. https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=11439
- They should only be immune to magic damages, not all damages. Video from Classic : https://youtu.be/s-2GXud7CJI?t=413
- They seem to instantly die on hit even tho even tho wowhead classic reports them as having 3k hp. https://classic.wowhead.com/npc=11439/illusion-of-jandice-barov
- They also seem to wander until they are attacked by a player, or they have a delay until they attack ? On TC they instantly attack the players.

## Tests Performed:
- Applied SQL, and did some testing. It appears to be working as intended for me.

## How to Test the Changes:

- `.go c id 10503`
- Fight Jandice, see if all behaves as intended...

## Known Issues and TODO List:

- [ ] More people need to verify if these changes are an improvement or not
- [ ] PLEASE DO NOT RUBBER-STAMP APPROVE THIS PR BEFORE READING IT THOROUGHLY

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
```
UPDATE `creature_template` SET `speed_walk` = 1, `spell_school_immune_mask` = 126, `AIName`="SmartAI" WHERE `entry` = 11439;
```

**Comment by Zoidwaffle** [comment]
Not saying you are wrong, but where do you get her walk speed change from?

**Comment by Kitzunu** [comment]
Usually those are sniffed values, but as we don't have access to sniffs :shrug:

**Comment by Zoidwaffle** [comment]
I did a bit more of testing on this and it appears working to me. It's super annoying with all the spawns - so bring something with plate armor not relying on magic (and that's working as intended this way).

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Voxstrasza** [comment]
@Zoidwaffle so is this good for merger or do you need more time?

**Comment by Zoidwaffle** [comment]
@Voxstrasza thanks for reminding me, let me test it a final time with all debugging enabled - I hope that will shed some light on the mechanics being triggered correctly or not.

**Comment by Zoidwaffle** [comment]
OK, so I don't think this is working quite as intended...

The change to magic immunity works and they also die on 1 hit. So far so good.

But the spreading out and initial passiveness... It seems not to trigger. So in this case spell 17772 ('Serverside - Spread') and 7131 ('Illusion Passive'), don't seem to do anything.

Some descriptions here: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=11439

Anyone here who knows if those spells are implemented at all? Or a way to see if they are triggered correctly? (I did try running it with -DENABLE_EXTRAS=1 -DENABLE_EXTRA_LOGS=1 but that didn't help).

**Pull request closed without merging**
