### PR TITLE
fix(DB/Fishing): Fix db errors about fishing

### PR DESCRIPTION
**Pull request by poszer**
- 3479 (The Veiled Sea is missing in table skill fishing_base_level which giving us sometimes errors in DB logs).
Based on some informations, since it's near Desolace and This zone is part of Ashenvale which is Level 31-40 zones:, i'm importing there skill 225 too.
- Also importing some loot related to this area

Area missing in fishing base level table

##### CHANGES PROPOSED:

-  Added entry for this area The Veiled Sea
-  Based on some informations, since it's near Desolace and This zone is part of Ashenvale which is Level 31-40 zones:, i'm importing there skill 225 too.
- Also importing some loot related to this area

###### ISSUES ADDRESSED:
 
```sql
2019-05-10 16:33:33 Fishable areaId 3479 are not properly defined in `skill_fishing_base_level`.
```
Related to this report: 
https://github.com/azerothcore/azerothcore-wotlk/issues/1824

Closes 

##### TESTS PERFORMED:

Yes, everything looks fine.

##### HOW TO TEST THE CHANGES:

1. Go at this area, The Veiled Sea and try to fishing. You wont get anymore db errors

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Just wondering if it's better or not to add "SET @ENTRY := 3479;" and replace by this variable.
Or if it's just useless overthinking

**Comment by Pondaveia** [comment]
@BarbzYHOOL For extensive queries it can be a nice plus to avoid extra work. However in small queries I don't think it is a big deal. This is more of a preference than an optimization.

**Comment by Knindzagxg** [comment]
Tested this as well, all good.
Keep forgetin* to post about checks -.-'

**Comment by poszer** [comment]
Thanks @Knindzagxg for testing :+1:

**Comment by pklloveyou** [comment]
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4503";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4416";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "210";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4417";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "3717";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "1176";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "616";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4100";
DELETE FROM `skill_fishing_base_level` WHERE `entry` = "3455";
These areas are missing.
For repairs I am better at collecting data, thank you for your repair, and thank you for your fix.
Because my English is very poor, there are communication barriers, so I can only use translation software, I am sorry.

**Comment by poszer** [comment]
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4503";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4416";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "210";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4417";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "3717";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "1176";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "616";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "4100";
> DELETE FROM `skill_fishing_base_level` WHERE `entry` = "3455";
> These areas are missing.
> For repairs I am better at collecting data, thank you for your repair, and thank you for your fix.
> Because my English is very poor, there are communication barriers, so I can only use translation software, I am sorry.

Np, thank you for report. You want to say these areas also missing (4503, 4416, 210, 4417, 3717, 1176, 616, 4100, 3455) ? @pklloveyou

**Comment by pklloveyou** [comment]
@poszer Yes, thanks again！:)

**Comment by BarbzYHOOL** [comment]
@pklloveyou http://www.azerothcore.org/wiki/Contribute#how-to-create-a-pull-request you should try!!

**Comment by pklloveyou** [comment]
@BarbzYHOOL The content of the webpage translated using Google Chrome cannot be understood at all.：（

**Comment by BarbzYHOOL** [comment]
but lookup google for each command in Chinese, they are the same no?

`git stauts` in chinese = `git status`, no?

**Pull request merged**
