### PR TITLE
fix(DB/Creature) Removes NPCs that shouldn't exist After v. 2.1.0

### PR DESCRIPTION
**Pull request by TheSCREWEDSoftware**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

Removes:
- Terror-Fire Guardian // 22327
- Nightmare Imp // 22202
- Terrordar the Tormentor // 22385
- ~Bladespine Basilisk~ (already doesn't exist, 22187)
- Wrath Reaver // 22196
- Wrath Fiend // 22392
- Fel Rager // 22286
- Trigul // 22174
- Felstorm Corruptor // 22217
- Insidious Familiar // 22218
- Darkflame Infernal // 22289
- Felstrom Overseer // 22221
- Eredar Sotrmbringer // 22283
- Amberpelt Clefthoof // 22287
Total found and removed of `124` rows

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/6317
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20820

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

```sql
SELECT * FROM creature WHERE id1 IN (22202, 22385, 22187, 22196, 22392, 22286, 22174, 22217, 22218, 22289, 22221, 22283, 22287, 22327)
```
- Fly over `Blade's Edge Mountains` area and see the missing creatures now

More specific

> Go to Blade's Edge Mountains zone and fly to Forge Camp Terror
> Fly over the zone, paying attention to the present mobs
> Fly to Forge Camp Wrath
> Fly over the zone, paying attention to the present mobs
> Fly to Crystal Spine
> Fly over the zone, paying attention to the present mobs
> Fly to Bash'ir Landing
> Fly over the zone, paying attention to the present mobs

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
This won't really close the linked issue, as the areas really should have their correct creatures added in addition to the incorrect creatures removed.

**Comment by TheSCREWEDSoftware** [comment]
> This won't really close the linked issue, as the areas really should have their correct creatures added in addition to the incorrect creatures removed.

Which creatures were added if you know just reference?

**Comment by Grimdhex** [comment]
Does this issue was check on classic or retail just to be sure ?

**Comment by TheSCREWEDSoftware** [comment]
Checking classic wouldn't be possilbe as this is a TBC issue. And I didn't check retail. 

I based the removal on the comments of the creatures saying thy got removed.

Check the issue: https://github.com/chromiecraft/chromiecraft/issues/6317 you can see what i mean

**Comment by Grimdhex** [comment]
> Checking classic wouldn't be possilbe as this is a TBC issue. And I didn't check retail.
> 
> I based the removal on the comments of the creatures saying thy got removed.
> 
> Check the issue: [chromiecraft/chromiecraft#6317](https://github.com/chromiecraft/chromiecraft/issues/6317) you can see what i mean

I know. I just said to be sure that npc was removed on cata/retail. when were they removed during TBC, we don't care. It's more a way out for progression module.

**Comment by TheSCREWEDSoftware** [comment]
> > Checking classic wouldn't be possilbe as this is a TBC issue. And I didn't check retail.
> > I based the removal on the comments of the creatures saying thy got removed.
> > Check the issue: [chromiecraft/chromiecraft#6317](https://github.com/chromiecraft/chromiecraft/issues/6317) you can see what i mean
> 
> I know. I just said to be sure that npc was removed on cata/retail. when were they removed during TBC, we don't care. It's more a issue for progression module.

I don't understand. The removal is not because of progression module. This being removed in when BT got released it means AC shouldn't have those npcs.

**Comment by Grimdhex** [comment]
What I'm saying is that you don't need classic TBC to confirm the outcome. There was virtually no change to the TBC content afterwards. So if, for example, the npcs have been deleted on Cata classic, that's enough. 

The only point in knowing when they were removed is just for the progress module so that it can restore them at the appropriate time (but in this case, it's the main AC directory). 

For spells, quest prerequisites, wowhead comments might be enough. But deleting NPCs can be more problematic if it's not true. And we've seen recently that wowhead isn't a good source of information.

Translated with DeepL.com (free version)

**Comment by TheSCREWEDSoftware** [comment]
I can check on retail but having comments saying it got removed (wowhead), having tbc and wotlk tabs (wowhead) with the same information (`The location of this NPC is unknown.` which normaly reflects in them not existing). I'm on the phone so doing more searches it's harder. But example this: https://warcraft.wiki.gg/wiki/Nightmare_Imp_(Blade%27s_Edge_Mountains) says it got removed in that patch different date the comment (earlier than the comment)

**Comment by TheSCREWEDSoftware** [comment]
I will close this PR and look more into it. To see what else got removed if i can gather enough data on it

**Pull request closed without merging**
