### PR TITLE
Renamed TCSoap to ACSoap

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
##### CHANGES PROPOSED:
-  Renamed "TC" SOAP variables into "AC" (SOAP).

##### HOW TO TEST THE CHANGES:
- Use SOAP using some tool like https://github.com/azerothcore/wow-telegram but renaming the  related variables client-side (on wow-telegram).

##### Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Helias** [comment]
Tested with this https://stackoverflow.com/questions/59382665/how-to-run-command-using-soap-to-azerothcore-server-console-using-php/59382666#59382666

Everything works.

**Comment by Viste** [comment]
write it to be notified when mereged

**Comment by FrancescoBorzi** [comment]
@Viste if you need it for some reasons, we can prioritise it

**Comment by Viste** [comment]
@FrancescoBorzi 2530

**Pull request merged**
