### PR TITLE
fix(Core/CharmInfo): Adjust how spells are given to charmed creatures.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:

This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20149

## SOURCE:

The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
@kissingers Please give this PR a test if/when you're able. ❤️

**Comment by kissingers** [comment]
Test OK, but might have some little problem:
By default now will not display normal attack icon.
If change index 3 to 6(total 0-3), the 6 spell will not close the spell 2
image

**Comment by kissingers** [comment]
image

**Comment by heyitsbench** [comment]
I don't understand the expected behavior of your message.

**Comment by kissingers** [comment]
It work, but I think if there is need a mealattack icon at last pision not olny just replace by spell at index 0
and if index not continue, just 0-2 then 6, if can automove 6 near 2?
image

**Comment by heyitsbench** [comment]
I don't believe there is any official instance of a creature having their melee attack in any position other than index 0 (1 on hotbar). If there's evidence to the contrary, then it would need to be investigated, but I've yet to see it myself.

**Comment by kissingers** [comment]
> I don't believe there is any official instance of a creature having their melee attack in any position other than index 0 (1 on hotbar). If there's evidence to the contrary, then it would need to be investigated, but I've yet to see it myself.

I haven't noticed if that's the case either, but I'm assuming there's a melee fight where the priest controls some creature? I try test both fix and not fix.

**Comment by kissingers** [comment]
after fix
image

before fix
image

before fix might have spell idex problem, but the creature can not attack after fix by press keyboard, because the spell 2 depend the next meele attack, and there no meele attack ico(but can use mouse left click to start attack)

**Comment by heyitsbench** [comment]
Cases like that need to have the index manually adjusted.

**Comment by kissingers** [comment]
just re-index all spell, and if index does not exist, skip index it, and add meele attack at end.
or fist add meele attack, then index the spell except does not exist

**Comment by heyitsbench** [comment]
> and add meele attack at end.

But this isn't correct, again, I haven't seen any creature in the game with a melee attack anywhere but index 0. For the creatures that are supposed to have melee attack available, they need to have their indices manually adjusted, as either way their data would be wrong.

**Comment by kissingers** [comment]
> > and add meele attack at end.
> 
> But this isn't correct, again, I haven't seen any creature in the game with a melee attack anywhere but index 0. For the creatures that are supposed to have melee attack available, they need to have their indices manually adjusted, as either way their data would be wrong.

might left the keyboard 1 not add other spell, and add spell index 0 to key beboard 2 , and others flow if exist, and not left blank

**Comment by heyitsbench** [comment]
> how about Blizzlike behaviour?

Blizzlike would have index 0 be clear for any creature they want to have melee attack available for. If they want a spell in index 0 (see all of the manual creature overrides this PR removes), then it always overrides the melee attack in index 0. Again, I have never seen the melee attack in any index other than 0.

**Comment by kissingers** [comment]
> > how about Blizzlike behaviour?
> 
> Blizzlike would have index 0 be clear for any creature they want to have melee attack available for. If they want a spell in index 0 (see all of the manual creature overrides this PR removes), then it always overrides the melee attack in index 0. Again, I have never seen the melee attack in any index other than 0.

So the fix is suite for the bug. how about the blank keyboard? might  Blizzlike database will always not let table index not continue?

**Comment by heyitsbench** [comment]
> [...] how about the blank keyboard? might Blizzlike database will always not let table index not continue?

I don't understand the question.

**Comment by kissingers** [comment]
if index only have 0-2 then skip to 6-7, not have 3-5, will Blizzlike keep the keyboard 4-6 blank?

**Comment by heyitsbench** [comment]
> if index only have 0-2 then skip to 6-7, not have 3-5, will Blizzlike keep the keyboard 4-6 blank?

Yes, can be seen [here](https://www.youtube.com/watch?v=g5Lo1PPLz5k&t=6s) with Death Knight Understudies and [here](https://www.youtube.com/watch?v=fVT3gYZM2AI&t=77s) with Vengeful Spirits.

**Comment by kissingers** [comment]
So it all ok, very thanks again.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
