### PR TITLE
fix(Core/Maps): Fix crash on worldserver shutdown

### PR DESCRIPTION
**Pull request by Nolin7777**
Don't call MapUpdater::deactivate() in ~MapUpdater() destructor because it's called in MapManager::UnloadAll() anyways.
Also unload maps first before deleting it. [TC]

## Changes Proposed:
-  Prevent crash on worldserver shutdown
- https://github.com/WarheadCore/Warhead/commit/fd47c3e06c7988de48166c5626e07dcca72bd930

## Tests Performed:
- Debian 10
- clang 7.0
- gcc 8.3

## How to Test the Changes:
- Shutdown worldserver and watch it crash

## Target Branch(es):
- [x] Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
hi @Nolin7777 , thanks for your contribution. The build is failing, can you fix it?

**Comment by Nolin7777** [comment]
Well, the built was successfull, it looks like it kinda hangs on server startup. ¯\_(ツ)_/¯

**Comment by Mitradis** [comment]
FINALY!

**Comment by FrancescoBorzi** [comment]
> Well, the built was successfull, it looks like it kinda hangs on server startup. ¯_(ツ)_/¯

yes, can you fix it? that ain't good ^^

**Comment by Nolin7777** [comment]
> > Well, the built was successfull, it looks like it kinda hangs on server startup. ¯_(ツ)_/¯
> 
> yes, can you fix it? that ain't good ^^

I cannot reproduce on my current setup. I will install VMs to debug it on those ubuntu OS' soonish

**Comment by Mitradis** [comment]
some one, who have ubuntu, can help his find error reason.

**Comment by Nolin7777** [comment]
It's building and starting up without issues on ubuntu 20.04 and recommented packages using clang or gcc.
Can't reproduce this errors, not even with a different OS...

**Comment by FrancescoBorzi** [comment]
> It's building and starting up without issues on ubuntu 20.04 and recommented packages using clang or gcc.
> Can't reproduce this errors, not even with a different OS...

@Nolin7777 have you tried the **dry run**? that's what the CI does:

```
/apps/ci/ci-worldserver-dry-run.sh
```

**Comment by Mitradis** [comment]
any news?

**Comment by Nolin7777** [comment]
Not yet, will have more time this weekend

**Comment by FrancescoBorzi** [comment]
> Not yet, will have more time this weekend

 @Nolin7777  any news?

**Comment by Mitradis** [comment]
No more needed?

**Comment by Nolin7777** [comment]
I will try something new

**Pull request closed without merging**
