### PR TITLE
feat(Core/Soap): delete ACE inherited

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Delete `ACE_Semaphore` from `ACSoap`

## Issues Addressed:
- Part #3451

## Tests Performed:
- No

## How to Test the Changes:
- Those who know how to use it will understand what to do

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/developers can anyone please help testing SOAP with this?

**Comment by FrancescoBorzi** [comment]
@Helias can you please test this?

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers please someone test this PR by trying to use SOAP with it.

**Comment by Sedatyf** [comment]
I know how to use SOAP Ui, but I don't understand what to test. Do you have any WSDL or something to give me?

**Comment by Winfidonarleyan** [comment]
Give him what he wants

**Comment by Helias** [comment]
I am testing SOAP with this PR, I'll give you some feedback soon

**Comment by Helias** [comment]
Soap works I tested it using [this PHP script](https://stackoverflow.com/questions/59382665/how-to-send-commands-using-soap-to-azerothcore-worldserver-console).
image

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Very good, thanks for testing

**Comment by Sedatyf** [comment]
Thank you @Helias!

**Pull request merged**
