### PR TITLE
Quest Fires Over Skettis: needs to be merged urgently

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
there's a lot of unrelated commits in this PR 👀

**Comment by sudlud** [comment]
as of now this PR does not change anything.

it just reinserts the already existing SAI for `22991` without any changes.

**Comment by sudlud** [comment]
> > as of now this PR does not change anything.
> > 
> > it just reinserts the already existing SAI for `22991` without any changes.
> 
> That's strange, I don't know why it doesn't work on chromiecraft

me neither, works perfectly last time I tested it on my local AC.

**Comment by grimgravy** [comment]
> > > as of now this PR does not change anything.
> > > 
> > > it just reinserts the already existing SAI for `22991` without any changes.
> > 
> > That's strange, I don't know why it doesn't work on chromiecraft
> 
> me neither, works perfectly last time I tested it on my local AC.

This sql is missing from chromiecraft. People complaining that they can't complete the mission

**Comment by sudlud** [comment]
Can you please verify if it works or not on AC? So we know for sure if it's an CC issue

**Comment by grimgravy** [comment]
> Can you please verify if it works or not on AC? So we know for sure if it's an CC issue

I've already done that and the problem is there

**Comment by sudlud** [comment]
Alright I'll try to test it on my local setup again

**Comment by sudlud** [comment]
https://github.com/chromiecraft/chromiecraft/issues/7434#issuecomment-2460657427

Can't reproduce the issue on clean AC.

Also this PR does not propose any changes, so I'll close it for now.

**Comment by Nyeriah** [comment]
CC has all of this SQL

**Comment by Nyeriah** [comment]
PreloadAllNonInstancedMapGrids = 1 was the culprit

**Pull request closed without merging**
