### PR TITLE
fix(DB/Creature): [Burning Steppes] Thauris Balgarr (rare) has no "Shoot" ability

### LINKED ISSUE #6979: [Burning Steppes] Thauris Balgarr (rare) has no "Shoot" ability
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

Original report: [chromiecraft/issues/1218](https://github.com/chromiecraft/chromiecraft/issues/1218)

### Current Behaviour

The npc Thauris Balgarr doesn't use his "Shoot" ability.
WoWScrnShot_071521_170845

### Expected Blizzlike Behaviour

He should use his shooting ability.

### Source

NPC: https://wowgaming.altervista.org/aowow/?npc=8978
His "Shoot" ability: https://wowgaming.altervista.org/aowow/?spell=6660

### Steps to reproduce the problem

Attack in range!

### Extra Notes

Confirmed on local AC (114d55d).
He is indeed not using his "Shoot" ability and just stands at range doing nothing but casting his "Net" and "Dark Iron Land Mine" from time to time. He is a level 57 rare mob and at this moment way too easy to farm for characters with range abilities.
unknown_2021 07 16-13 22

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99970563-burning-steppes-thauris-balgarr-rare-has-no-shoot-ability?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Asthalor**
[Burning Steppes] Thauris Balgarr (rare) has no "Shoot" ability #6979

- Closes #6979
- https://github.com/chromiecraft/chromiecraft/issues/1218

## Issues Addressed:

- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/6979

## SOURCE:

image

## Tests Performed:

-  I attacked him while keeping the distance to see that he shoot me normally while using the net and the mine.

## How to Test the Changes:

1. Use the .go c id  8978, if you cant find it use .npc add temp 8978
2. Keeping the distance attack it
3. He should shoot you, use the net and the mine

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]

**Comment by LukasVolgger** [comment]
Tjx @Asthalor for your contribution! Please adapt the title to fit in the commit standards:
 https://www.conventionalcommits.org/en/v1.0.0/

You can also look in older commits how they are named.

**Comment by syssneck** [comment]
I tested it and it works now! He shoots and still uses his net and the landmines.
Thank you for the fast fix! :)

**Comment by FrancescoBorzi** [comment]
good job @Asthalor and thanks @LukasVolgger / @syssneck  for reviewing / testing

**Comment by FrancescoBorzi** [comment]
@Asthalor just a small note for next time, don't forget to also add the closing CC issue:

```
- Closes https://github.com/chromiecraft/chromiecraft/issues/1218
```

this time I edited your PR already, so no need to bother now

**Pull request merged**
