### PR TITLE
fix(DB/C_T-SAI-GOBJ): NPC: Lady Falther'ess and Scourge Invasion Event

### PR DESCRIPTION
**Pull request by Stifler82**
## Changes Proposed:
- Boss implementation: [Lady Falther'ess](https://wowgaming.altervista.org/aowow/?npc=14686)
- Event implementation: [Scourge Invasion](https://wowgaming.altervista.org/aowow/?event=17) **(Event ID 17)**
## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5786

## Tests Performed:

- Tested in game and working
- Tested on Windows 10 (64)
- **Video Test 1:** [Scourge Invasion Event](https://youtu.be/5D2LnAb0WEM)
- **Video Test 2:**

https://user-images.githubusercontent.com/1884642/117799942-90b46e80-b24a-11eb-8bf5-de07fd059ff1.mp4

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Stifler82** [comment]
> All good me and shin talked about it.
> 
> I believe there is an existing game event for scourge invation in game_event. Could you link the NPC to this event @Stifler82 this way we can get it for the correct event.
> 
> If the gob is supposed to be spawned, I suggest you add conditions for SAI only to execute when event is active. Otherwise add it to event spawn too.
> 
> Good job with the initial work 👍

Hey @Kitzunu, I just finished Fixing `"Event 17"` **Scourge Invasion**

Now I'm tired, but tomorrow I'll make a video and show you the event with all the IDs so you can tell me what needs to be changed if necessary.

**Comment by Stifler82** [comment]
> I can't wait to test this!

@Maurowin 

image

I didn't do this Fix, this Fix is already active on AC.
You all do a lot of BlizzLike super experts and then you have "Bugs" or "Fix-Customs" under your nose and you don't even notice it..
check it also in your server, if you want to do a double check.

https://user-images.githubusercontent.com/1884642/117842752-24e7fb00-b276-11eb-9bed-7d9c3e6eed3a.mp4

**Comment by Maurowin** [comment]
`I didn't make this Fix, this Fix is already active on AC.
You all do a lot of BlizzLike super experts and then you have "Bugs" or "Fix-Customs" under your nose and you don't even notice it..
check it also in your server, if you want to do a double check.`

I don't see the point of this comment if not for provocation. Precisely, I fight against hackfix and custom fix. Yes, I am Mr. Blizzlike and ?

**Comment by Stifler82** [comment]
@Maurowin
I didn't want to be "provocative" if anything "Ironic".
Let's say I use sarcasm to convey deeper truths, if that can serve you as an explanation.

I know, I am often criticized for my way of dealing with others.
But the truth is that in my words there is never malice, rather irony, I like to be witty, and I often use sarcasm to "lighten" heavy concepts.

Sadly, most of the time people interpret this as a hostile attitude of mine, but that is never the case.
If I have to insult someone I do it openly without subtle words or subtleties.

My point earlier was just to explain (via sarcasm) that I find it "ironic" that often people **(not specifically you, I was referring to a general custom that I have often seen done here on Github.)** takes about 0.01 milliseconds to point the finger at a Fix that maybe it's not exactly BlizzLike, and then they don't realize that there are already things that aren't BlizzLike (and maybe they don't even know it and that's fine with them)

We could say, (to quote the Bible, making an analogy): `"How can you say to your brother: «Brother, let me take out the speck that is in your eye», while you yourself do not see the beam that is in your eye? Hypocrite! first remove the beam from your eye and then you will see clearly to remove the speck from your brother's eye."`

But you see, said in this way, with this analogy, the speech becomes boring, tedious and heavy.
Instead expressed with sarcasm, it becomes more fun, and you learn the lesson / concept.

Of course, there is the risk of feeling "slightly" taken for a ride.
But (at least on my side), there is no intention of taking for a ride anyone.

I don't know if I managed to explain my thoughts well, without misunderstandings. my english is unfortunately not perfect, I hope..

In any case, **(in case you felt take for a ride or insulted in some way)**, I'm sorry, that wasn't my intention.

**Comment by Maurowin** [comment]
No worries dude.
I try with the little time I have at my disposal to fight against hackfix and custom fix.

It's true that many non blizzlike fixes have passed. When I have a little more time, I will look at all the fixes that have been merged to open a ticket for rewriting so that it is blizzlike.

After that I'm not 100% blizzlike in the sense that the bugs that were present in 3.3.5 retail, I'm not for keeping them. It doesn't make sense.

**Comment by Stifler82** [comment]
> No worries dude.
> I try with the little time I have at my disposal to fight against hackfix and custom fix.
> 
> It's true that many non blizzlike fixes have passed. When I have a little more time, I will look at all the fixes that have been merged to open a ticket for rewriting so that it is blizzlike.
> 
> After that I'm not 100% blizzlike in the sense that the bugs that were present in 3.3.5 retail, I'm not for keeping them. It doesn't make sense.

@Maurowin 
I'm actually Anti-BlizzLike.
I mean, I agree with the BlizzLike concept in:
- Class-Spell / Talents
- Boss-Spell (for Instance and Dungeon Boss)
- Battlegrounds
- RDF

For everything else, however, I take it as a "Hint" from Blizzard, because it is not written anywhere that Blizzard is the WoW Bible, maybe they invented the game, but in the end we "have it in hand" a product and with this product we can do what we want with it, even improve it where Blizzard has failed or made mistakes.

For example, for me it is a mistake on Blizzard's part to create an event like "Scourge Invasion" where you only have a one-time chance to get certain items or fight certain Bosses.
Instead in my opinion it would be an improvement to do this event as an event that "Start" every certain time, and lasts every certain time.
For example: Start every 2h, 30m and has a duration of 1h, 30m.
So the Players would be more inclined to do Dungeons in those moments, because they are "Special Moments" that only on that occasion can they find those Bosses, but in any case it would be a Daily opportunity that continues over time.

I mean, the game is beautiful, and DEFINITELY, it can be improved upon. So why not do it?

**Comment by Maurowin** [comment]
Blizzard is following the "warcraft story" and I put in quotes because they are adapting the story to the game to try to have something coherent when the expansions come out. 

The problem with events is that they do it 1x for some because it's to open up access to new content.

But with the future feature that AC is planning to develop (EPIC progressiv mode), we will be able to relive all the events even those that have been active 1x. 

After nothing prevent the administrators of a server running under AC to make a progressive server then leave it at the last patch 3.3.5 (ICC, Ulduar etc. ...) and recreate another progressive once arrived at the last patch to migrate all the characters on the first server and reset the 2nd to return to the version for example Vanilla or early WOTLK. And that in a perpetual way a bit like Warmane do.

**Comment by Stifler82** [comment]
> Blizzard is following the "warcraft story" and I put in quotes because they are adapting the story to the game to try to have something coherent when the expansions come out.
> 
> The problem with events is that they do it 1x for some because it's to open up access to new content.
> 
> But with the future feature that AC is planning to develop (EPIC progressiv mode), we will be able to relive all the events even those that have been active 1x.
> 
> After nothing prevent the administrators of a server running under AC to make a progressive server then leave it at the last patch 3.3.5 (ICC, Ulduar etc. ...) and recreate another progressive once arrived at the last patch to migrate all the characters on the first server and reset the 2nd to return to the version for example Vanilla or early WOTLK. And that in a perpetual way a bit like Warmane do.
> 
> And AC's mentality is to be as blizzlike as possible as stated in their README.MD. If not, you should go for a FUN server.

So maybe you misunderstood me, because I have another concept of "Fun-Server"

For me a "Fun-Server" is one of those PvP servers (usually) where you are Instantly at the highest level and only do PvP. (example A.T.)

I'll give you another example:
In the WOTLK expansion it is no longer possible to take the T3 because Naxxramas is no longer that of Classic or TBC and the T3 has been replaced by the T7.

So if you want to do a "Progressive" on WOTLK at the point of T3 what do you do? add T3 to all players? or do you say to them: **"Well guys, no equip for this phase of the game, stick to the dick and do Tarzan"** ?

Instead, a nice idea would be to come up with a "Story" (which has some coherence with the Naxxramas Story)) maybe I don't know, you invent a World's Boss and tell that it's the brother or sister of a Naxxramas Boss who has returned from the past to take revenge (or something like this).

In the end, as you said too, Blizzard does "Story Adaptations" too, so why can't we do it too? why can't we be a "Blizzard 2.0"?

**Comment by Branel** [comment]
I don't mean to jump into a topic I didn't follow as closely as I should but I think more perspectives always help.

The emulation community has always been very divided about 'fun/custom' or 100% blizzlike and everything inbetween. And I say let it rest - this conversation never gets anywhere and even when the developers try their best to be as truthful to the original product as possible, we still end up doing a lot of guess work cause we just dont have enough data of how things actually were, yeah there are videos and forum posts but as long as I have been a part of this community there are some things about the game that I experience nonblizzlike but nobody was able to proove otherwhise so we had to leave it as TrinityCore stock, or patch it up enough that it seems reasonable. 

This might not be the blizzlike thing to do, but it might be the right thing to do, it literally has no significant impact if a event that wont be used is scripted, modules that will enable progression can more easily enable this event for additional content. It's not a custom patch, and it's based on what already exists, no harm, no foul.

**Comment by Nefertumm** [comment]
Status on this?

**Pull request closed without merging**
