### PR TITLE
Fix(DB/Quest): Blueleaf Tubers

### PR DESCRIPTION
**Pull request by wizzymore**
##### CHANGES PROPOSED:

-  Makes item usable ( Crate with Holes ) and the quest now can be completed!

Thanks to @Knindzagxg for the work!

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1604 
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1491

##### TESTS PERFORMED:

[Crate with Holes] can now be used
[Snufflenose Command Stick] makes the little guy search for Tubers

##### HOW TO TEST THE CHANGES:

.go c 14408
.quest add 1221
.go c 20952

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@poszer why still **Waiting to be tested**? You plan to do more tests?

**Comment by poszer** [comment]
> @poszer why still **Waiting to be tested**? You plan to do more tests?

yeah, atleast 1 more confirmation

**Comment by comix1988** [comment]
I tested this quest:

before fix:
https://youtu.be/AYzmyqnvS0Q

after fix:
https://youtu.be/T3jeZOCct9M

now the quest works but I don't know if:
1- it is right that the Snufflenose attacks all mobs
2- it is right to have more Snufflenose at the same time
Schermata da 2019-03-23 13-43-50

**Comment by wizzymore** [comment]
@comix1988 yes it should attack everything he finds in his way as he is set on hostile and is as on blizz. About the multiple snufflenose, yeah that is a bug, but i only wanted to make the quest completable, i don't really know how to work with items to fix the issue so if someone knows how, the help will be appreciated.
Blizzlike: Only one Snufflenose at a time, if he dies you use the item again to summon it but can have only one.

_If i have type mistakes remember i am posting from my phone_

**Comment by poszer** [comment]
This is already tested by @Knindzagxg , @wizzymore, @comix1988  and me. So, i think it can be merged. Since its db change, For any improvements in the future we can easily edit it.

**Comment by Nefertumm** [comment]
Maybe someone can add a condition(db) for the use of this item.

**Comment by Nefertumm** [comment]
Try this:
```sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 17 AND `SourceEntry` = 6918;
INSERT INTO `conditions` VALUES (17, 0, 6918, 0, 0, 29, 0, 4781, 5, 0, 1, 0, 0, '', 'Blueleaf Tubers: Only spawn one Snufflenose Gopher');
```

**Comment by comix1988** [comment]
I tested this sql file and it works perfectly, now I can use the item only when the guardian is dead.
In my opinion you have to check the range of aggro/attack of the Snufflenose, it is too wide.

good job @Nefertumm

**Comment by poszer** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/1633

**Pull request closed without merging**
