### PR TITLE
1

### PR DESCRIPTION
**Pull request by loveshe12**
##### CHANGES PROPOSED:

-  
-  

###### ISSUES ADDRESSED:

Closes 

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

 
 
 
 
 ## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Viste** [comment]
@FrancescoBorzi @BarbzYHOOL @poszer

**Comment by Winfidonarleyan** [comment]
What?

**Comment by FrancescoBorzi** [comment]
what is this?

**Comment by Viste** [comment]
@FrancescoBorzi this need to close, as i can understand he want update hes core but dont know how do it )))

**Comment by BarbzYHOOL** [comment]
yes, viste is right, not the first time it happens :P

**Pull request closed without merging**
