### PR TITLE
fix(DB/creature_template): Fixed Southshore Guards faction

### LINKED ISSUE #7654: Southshore Guards are neutral towards horde
**Originally reported:** https://github.com/chromiecraft/chromiecraft/issues/1591

### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

### Current Behaviour

Southshore Guards (https://wowgaming.altervista.org/aowow/?npc=2386) in Southshore are currently neutral to horde characters.
guards

### Expected Blizzlike Behaviour

Southshore Guards should be hostile towards horde characters.

### Source

https://wotlk.evowow.com/?npc=2386
https://tbc.wowhead.com/npc=2386/southshore-guard#comments
https://wowwiki-archive.fandom.com/wiki/Southshore_Guard
https://wowpedia.fandom.com/wiki/Alliance_Guard_(Hillsbrad_Foothills)

### Steps to reproduce the problem

1. Be horde and Teleport to any NPC entry 2386
2. observe them being neutral

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Efymer**
## Changes Proposed:
-  Set correct faction according to sniffs.

## Issues Addressed:

- Closes #7654 
- Closes https://github.com/chromiecraft/chromiecraft/issues/1591

## SOURCE:

Captura de pantalla 2021-08-31 123413

## Tests Performed:

- Checked ingame with horde character.

## How to Test the Changes:

1. `.go c id 2386` as horde
2. Guards attack you

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by T1ti** [comment]
I remember that there was an open issue and PR about this bug already

**Comment by T1ti** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/4847#issuecomment-803495970

**Comment by Efymer** [comment]
Not sure then if you are telling me that the PR is invalid @T1ti.

About being neutral, I don't think its the case looking at the video https://youtu.be/UOIouyayc7w?t=159

**Comment by syssneck** [comment]
Tested, after this PR the Southshore Guards don't help with the Shadowy Assassins anymore.
Pre-PR (guards aggro on the assassins):
grafik

Post-PR (guards ignore the assassins, only Farmer Kent protects his home):
grafik

I also think there should be an event with the assassins, that is missing here (has nothing to do with this PR, but I will probably look into it).

**Comment by Efymer** [comment]
@syssneck  
I'm unable to see those assasinss in my dev instance, did you do anything to spawn them besides returning this quest? https://tbc.wowhead.com/quest=525/further-mysteries

**Comment by syssneck** [comment]
I didn't do any quest for this. I looked up the Shadowy Assassins, but they don't have any spawns, so some event calls them. They are all around Southshore, and they are in stealth. I just walked around and got aggro from a few. 
According to old comments, this is supposed to be an event that happens all 3-4 h, starting with the "Southshore Crier running into Southshore (form Tarren's Mill direction) and yelling: 'Help me! Help! Assassins in the Hills! To arms! To arms!'" Then there will be some gossip from the guards (and apparently more guards during the event) and the assassins coming into Southshore in stealth and in pairs (https://tbc.wowhead.com/npc=2434/shadowy-assassin#comments).
However, I didn't see any gossip and the assassins are already in Southshore just standing around in stealth.

**Comment by Efymer** [comment]
Okay, thanks for your input @syssneck, after being for a while in the zone I could see some assasins!

Apparently the Shadowy Assasins are summoned by the Crier as we can see here:

Captura

I checked the faction for the Shadowy Assasins and it didn't match with the sniffs and either with the vMaNGOS value, so after correcting it Guards are attacking the Assasins too! 

WoWScrnShot_090121_104856




Feel free to double-check it if you want :)

**Comment by syssneck** [comment]
My bad, the gossip is actually there. Yes, the guards assist now with the assassins. 👍

**Pull request merged**
