### PR TITLE
fix(DB/GameObject): Duplicate nodes in the Barrens

### PR DESCRIPTION
**Pull request by r-o-b-o-t-o**
## Changes Proposed:
-  Fix duplicate Mageroyal nodes in the Barrens :
image
-  Fix duplicate Copper nodes in the Barrens :
image
- Fix duplicate Briarthorn nodes in the Barrens :
image

## Issues Addressed:
No issues for this

## Tests Performed:

Applied SQL diff, tested in-game on Windows 10

## How to Test the Changes:

- `.go o 2318`
- `.go o 5067`
- `.go o 2886`

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by Sedatyf** [comment]
I tested it too and it seems like Mageroyal in Barrens are not duplicate anymore, but it is not spawn. When I do a ``gobj near`` it appears in my logs.
Same behavior for the Briarthorn in Barrens.

Copper Vein is fixed ✔️

**Comment by r-o-b-o-t-o** [comment]
Indeed. That's weird.

I noticed that the mageroyals and briarthorns both had two different ids (1620 and 3727 for mageroyal, 1621 and 3729 for briarthorn). I think this has to do with the barrens quest [[Root Samples]](https://classic.wowhead.com/quest=866/root-samples) (notice how the [3727 id for mageroyal is only located in the Barrens and loots root samples](https://classic.wowhead.com/object=3727/mageroyal#herbalism)), but I don't understand why it stops spawning all of a sudden.

I also noticed that @Helias removed an earthroot spawn that was in the same situation for #5233 (see [these changes](https://github.com/azerothcore/azerothcore-wotlk/pull/5255/files)). Now when I go to the remaining earthroot (`.go o 1908`), I can't see the herb, even though it appears in `.gobj near`, just like my mageroyal and briarthorn nodes... Any ideas anyone?

**Comment by Sedatyf** [comment]
Hey @FrancescoBorzi, can you remove "To Be Merged" and replace it with "Need Help" or something? As @r-o-b-o-t-o mentioned before he has concern about this fix and he thinks there is something deeper to investigate

**Comment by FrancescoBorzi** [comment]
done, thanks guys!

@azerothcore/developers can anyone help here?

**Comment by alchem1ster** [comment]
Mageroyal:
```
(2318,1620,1,0,0,1,1,74.186,-3444,28.167,-1,0,0,-0.25038,0.968148,900,100,1,'',0)
(13696,3727,1,0,0,1,1,74.3646,-3443.92,28.166,-0.506145,0,0,0.25038,-0.968148,900,100,1,'',0)
```
But GUID 2318 is also in the Pool:
```
(2318,801,0,'Mageroyal,Zone 17,Area 17,node 439')
```
The game itself creates objects from the pool according to the distribution chance.
If you want to delete an object, you must also delete it from the pool. 

<hr>

Briarthorn:
```
(2886,1621,1,0,0,1,1,-1789,-3205,89.764,-1,0,0,-0.398749,0.91706,900,100,1,'',0)
(14450,3729,1,0,0,1,1,-1789.54,-3205.13,89.6333,-0.820305,0,0,0.398749,-0.91706,900,100,1,'',0)
```
The same with the Briarthorn. It in the Pool:
```
(2886,803,0,'Briarthorn,Zone 17,Area 385,node 614')
```

**Comment by FrancescoBorzi** [comment]
@r-o-b-o-t-o what's the status of this PR?

**Comment by r-o-b-o-t-o** [comment]
I'll just close this. It's old and half wrong, so we should probably just wait for when/if we replace our nodes with sniffs.

**Pull request closed without merging**
