### PR TITLE
Core/Misc: Guid handling rewrite (more like TC backport)

### PR DESCRIPTION
**Pull request by FALL1N1**
Big WIP...

- [x] https://github.com/TrinityCore/TrinityCore/commit/2fc52b5af62e828e85e1da021b1d7ff0fe7ddd8e
- [x] https://github.com/TrinityCore/TrinityCore/commit/ce67a097bf3c0c3241f4441a808e32639ddbaafb
- [ ] https://github.com/TrinityCore/TrinityCore/commit/a0e50ea35fca61447bf07fc45d93c98234ba59f7
- [ ] https://github.com/TrinityCore/TrinityCore/commit/2a1a2943838d04c6987fcdd68c5e6362798452fe
- [ ] https://github.com/TrinityCore/TrinityCore/commit/d72c4085de0b2ac0ff3bee24a5dae80c0d5dac2c
- [ ] https://github.com/TrinityCore/TrinityCore/commit/56f46e3ce543af8ffdc708eaa4ceecc173a5eb29
- [ ] https://github.com/TrinityCore/TrinityCore/commit/6ce0a3107d06cb5485e09afca42dbef4baa9553b
- [ ] https://github.com/TrinityCore/TrinityCore/commit/a3d8f1d8794150debbed142ef4621a4f680aa1fd
- [ ] https://github.com/TrinityCore/TrinityCore/commit/48deb443f960f0baf10a4cd6893744880651d62e
- [ ] https://github.com/TrinityCore/TrinityCore/commit/5ac62d9ca3bdaf19e32bfa8fb85b87d2a954cc9a
- [ ] https://github.com/TrinityCore/TrinityCore/commit/9b316fe689d06af14d800bcb22992da2e6157225
- [ ] https://github.com/TrinityCore/TrinityCore/commit/6c1a33d62df8a67a913171ad8000d5be1b724ce4
- [ ] https://github.com/TrinityCore/TrinityCore/commit/bee9a3069b51e7e3472096e433730d8d619eda9c
- [ ] https://github.com/TrinityCore/TrinityCore/commit/878073d516c6c30e72c3f818863b2fd65055a657
- [ ] https://github.com/TrinityCore/TrinityCore/commit/9b933b4a291e377d4ae124eb8e3d2ba74b37f34f
- [ ] https://github.com/TrinityCore/TrinityCore/commit/7d1d55124c1e289748d2afefae896c97f710e57b
- [ ] 

... Grand finale
- [ ] https://github.com/TrinityCore/TrinityCore/commit/dcb7082277447c21b11c4a1d59f105fa342c172e

This will be a giant WIP and will take... a while... so any help is appreciated.

Once it's ready I will format it accordingly with the issues it will close.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
nice @FALL1N1 ! if possible, try to break this into smaller PRs (typically smaller PRs are easier to be reviewed/tested)

but I understand that it is not always possible to do so

**Comment by FALL1N1** [comment]
Closing this as I will no longer be working on it, a.k.a it's too early for it.

There is a lot of difference between TC and Sunwell so this is completely incompatiable.
Easiest example is the custom crap in LFG, e.g "class Lfg5Guids"

**Comment by Winfidonarleyan** [comment]
Rofl

**Comment by FALL1N1** [comment]
@Winfidonarleyan anything you want to share/say, or you will be the ordinary pleb as always?

**Pull request closed without merging**
