### PR TITLE
fix(DB/creature) Remove bleed immunity from Twilight Elementalist

### PR DESCRIPTION
**Pull request by BeefSteaker**
## Changes Proposed:
-  Remove bleed immunity from Twilight Elementalist

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11553
- Closes https://github.com/chromiecraft/chromiecraft/issues/3425

## SOURCE:

[Asmongold Classic Stream using Rend and not being immune on Twilight Elementalists.](https://youtu.be/snSTzDUNO-s?t=2962)
https://youtu.be/-887Zu5hqJo?t=4646

## Tests Performed:

- tp to mob on local
- 

## How to Test the Changes:

1. .learn 768
2. .learn 1822
3. .go c 4814

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I'm more in favor of setting their immunity to 0 since the current behaviour is unheard of. They're currently immune to **everything** and that's only seen in Vmangos afaik. In both TC and Cmangos their immune mask is 0.

image
image

**Comment by heyitsbench** [comment]
I'm sorry, why can't this just be sniffed?

**Comment by Gultask** [comment]
I don't remember mechanic_immune being able to be sniffed?

**Comment by Gultask** [comment]
Well we could go and test each mechanic. But that'd take at least 20min for each one and I don't think anyone would bother :P

**Comment by Kitzunu** [comment]
Here you can see which fields are sniffed https://www.azerothcore.org/wiki/sniffing-and-parsing

**Comment by BeefSteaker** [comment]
I only removed stun & bleed as they were confirmed. Would be easy to set to zero if that's more blizzlike

**Comment by Gultask** [comment]
Personally I believe 0 is blizzlike. And it's the value Cmangos/TC uses so there's backing for it.

**Review by temperrr — APPROVED** [review]

**Pull request merged**
