### PR TITLE
fix(DB/SAI): Serpentbloom Snakes no movement.

### PR DESCRIPTION
**Pull request by avarishd**
## Changes Proposed:
- On spawn add random movement

## Issues Addressed:

- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/12500
- Progresses https://github.com/chromiecraft/chromiecraft/issues/3834#issue-1310056500

## Tests Performed:

- tested

## How to Test the Changes:

.q a 962
.go gameobject id 13891
Click and look for the snek

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
In the source video they had very different movement, closer to waypoints instead of random in a radius. This PR would serve for now, but wouldn't really close the issue, could you update it so it does not happen automatically? I use 'Progresses' myself.

**Comment by avarishd** [comment]
> In the source video they had very different movement, closer to waypoints instead of random in a radius. This PR would serve for now, but wouldn't really close the issue, could you update it so it does not happen automatically? I use 'Progresses' myself.

I have the feeling that this WP running was added in 4.1.0's "rework", but I cannot find any videos from before cataclysm.

**Comment by Maelthyrr** [comment]
Tested and work fine. @Gultask do you approve?

**Review by Gultask — APPROVED** [review]

**Comment by Gultask** [comment]
Oh yeah, totally. We can go investigate further later. Until then this is certainly an improvement.

**Pull request merged**
