### PR TITLE
fix(DB/SAI): Rewrite Ring of Blood

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
- Use sniffed data as much as possible

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15190
- Closes https://github.com/chromiecraft/chromiecraft/issues/5095
- Progresses https://github.com/azerothcore/azerothcore-wotlk/issues/13903
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13904
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13907
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13908
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15176
- Closes https://github.com/chromiecraft/chromiecraft/issues/4952

## Tests Performed:

- Tested Ingame
- 

## How to Test the Changes:

1. `.go c id 18471`
2.
3.

## Known Issues and TODO List:

- [x] Mogor
- [x] Immunity flags and combat tweaks

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Done. Ready for review. Also requesting a test to see if it does not break for someone else.

**Comment by avarishd** [comment]
Going by listed issues.
General
- [x] Can't start multiple encounters.
- [x] Boss(es) despawn correctly after not being engaged within 30s. Followed with a mocking line from Gurg. (With a quest fail)
- [x] Gurg yells when %n beats the encounter.
- [x] Correct group/player gets rewarded, even if someone else kills the current boss. (even if tapped)
- [x] Mogor talks according to the current quest progress.
- [ ] unknown interaction: All bosses except twins aggro on spawn to the invoker, no matter how far away you are.
- [ ] Sometimes Gurg quest status isn't being updated until a relog (very, very rare, idk if related to PR or not)

Brokentoe
- [x] has emote
- [x] Immune to CC (tested HoJ && Fear)
- [ ] Hoof Stomp ability can still be avoided by being at max melee range.
(But this can only be done if he is snared, which you no longer can do)

Twins
- [x] Both pull at the same time
- [x] If you kill 1, the other doesn't despawn. (in combat)
- [ ] unknown interaction: You can kill 1, run away and reset and then kill the other one before it despawns. (You get credit)
- [x] You can kill 1, run away, let the other one despawn. -> You get quest failed (when the other one despawns)
- [ ] Immune to poisons
- [x] Casts Sinnister Strike && Eviscerate

Rokdar
no issues listed, worked fine

Skra'gath
- [x] Gains damage reduction against the first element (tested fire/shadow) that hits it.
- [x] Uses Piercing Shadow and is immune to interupts.
- [x] unknown interaction: Uses Dark Shriek, but no matter if the victim is casting or not. (It's a kick that deals damage)
- [x] All threat is removed after Shadow Burst.

Warmaul Champion
- [x] Immune to disarms
- [ ] Charge does happen, but it's very, very rare and it looks like minimum distance is like 15-20y, instead of just few (from https://www.youtube.com/watch?v=dY-KJEcABGY&t=372s)

Mogor
- [x] Starting his quest, roleplaying from him and Gurg works
- [x] Walks into the middle, following his WP and is Immune (friendly) until he reaches his destination.
- [x] Ice totem is very frequent.
- [x] Phase 2 always happens (repeated 5 times)
- [x] Instantly despawns when evaded, instantly respawns after being defeated.

**Comment by Gultask** [comment]
> Sometimes Gurg quest status (personal, other characters see it fine) isn't being updated until a relog (very, very rare, idk if related to PR or not)

If it comes back on a relog, I really have no idea :P 
After Mogor there's a 5s delay before the questgiver flag comes back, otherwise it's all in the Actionlist, if quest credit is given then the flag should be re-added, always

> unknown interaction: Edge case, not always happening -> Bosses (except brokentoe) aggro on spawn to the invoker, no matter how far he is.

This "not always happening" is what worries me, because it's intended behaviour :D 
It happens with .gm on, maybe something else as well? Target is stored by the questgiver and then sent to the bosses, so maybe there should be a bigger delay between the target being sent and the aggro
Aggro is 2.4s after spawn, target should actually be sent immediately on spawn, but it's not possible in SAI, afaik. I know this because they have targets in their talk packets.

> Hoof Stomp ability can still be avoided by being at max melee range.

I think we may have had a similar problem with the dog in MC, unknown to me. That's why it won't close the issue.

> unknown interaction: You can kill 1, run away and reset and then kill the other one before it despawns. (You get credit)

I didn't think about testing this one because it's fairly hard to, but my gut says that this behaviour wouldn't be too far off from blizz standards. The amount of times I've soft-locked instances by testing them too far is kinda crazy. Battle of Mount Hyjal can hard lock if you go too far and hit triggers too early.
The only solution I can think of would be despawn on evade, but that wouldn't be blizzlike, I've already made that compromise with Mogor 😩

> Immune to poisons

I'll have to check videos again but I think it means immunity to CC poisons, otherwise I think the immunity would be to nature spells in general?

>  Charge does happen, but it's very, very rare

I used Cmangos data for this one, with 8-25y min range. The repeat is around 20s so maybe that needs adjusting. I'll see the videos.

**Comment by Gultask** [comment]
Oh yeah and big thanks for such a detailed test! 😄

**Comment by avarishd** [comment]
Regarding to the "immune to poisons", I think https://github.com/azerothcore/azerothcore-wotlk/issues/13904 is wrong, and in the source the rogue has blade twisting talent, it only shows immune when he sinister strikes (and kidney, kek). Also the shaman in the video is blasting so yeah, definitely not immune to poisons/nature, just cc.

**Review by acidmanifesto — APPROVED** [review]

**Comment by Gultask** [comment]
> unknown interaction: You can kill 1, run away and reset and then kill the other one before it despawns. (You get credit)

You actually can in Retail!

> Charge does happen, but it's very, very rare

Videos are kinda inconclusive. Mostly 1-2 charges before he dies, sometimes not happening at all after pull: https://youtu.be/JoBR2BbSTPE?t=606
I'll keep Cmangos for now.

**Pull request merged**
