### PR TITLE
fix(DB/Creature): Feral Defender Damage

### PR DESCRIPTION
**Pull request by merdlin**
Feral Defender Damage damage correction

**TESTS PERFORMED:**
damage without correction is wrong.

**HOW TO TEST THE CHANGES:**
just receive attack from creatures id 34035 and 34171
.npc add temp 34035
.npc add temp 34171

**KNOWN ISSUES AND TODO LIST:**
the damage was totally incorrect.

**Target branch(es):**
[Master](https://github.com/azerothcore/azerothcore-wotlk/commit/fc3fec3deb55cf144d89fc1ae288183e7f5b36ba)

**How to test AzerothCore PRs**
When a PR is ready to be tested, it will be marked as [WAITING TO BE TESTED].

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
I agree values look wrong, but what do you base these changes on?

**Comment by merdlin** [comment]
> I agree values look wrong, but what do you base these changes on?

I studied his damage a lot and got to the point that it really has to increase. the feral was with incorrect damage, as if it were a dummy

**Comment by Kitzunu** [comment]
Yes I know, but why 13 & 25, where did you get those multipliers from? 
Got any data on what damage they should do?

**Comment by merdlin** [comment]
> Sim, eu sei, mas por que 13 e 25, de onde você conseguiu esses multiplicadores?
> Tem algum dado sobre o dano que eles devem causar?

yes there is, i was researching the damage in the trinitycore even in azerothcore, the multiplied ones corrected his damage. I have tested it several times with players!

**Comment by merdlin** [comment]
View https://github.com/TrinityCore/TrinityCoreCustomChanges/commit/77dd751499a92eb06b66eadd00bbc71da07e62be

**Comment by Kitzunu** [comment]
That is not what I am asking...

I am asking if you just took the values from TC or if you did some research, like checking world of warcraft logs / watching old retail videos and doing the maths

**Comment by merdlin** [comment]
> Não é isso que estou perguntando ...
> 
> Estou perguntando se você acabou de pegar os valores do TC ou se fez alguma pesquisa, como verificar os logs do world of warcraft / assistir vídeos antigos de varejo e fazer contas.

I did research, saw videos of the feral to see how the damage is, I asked old players.

**Comment by BarbzYHOOL** [comment]
so how much did he hit before the PR and after the PR? :)

**Comment by merdlin** [comment]
Before PR, npc id: 34035 was 'Damagemodifier = 1', npc id: 34171 was 'Damagemodifier = 1'. now with PR he is right.

**Comment by BarbzYHOOL** [comment]
before PR damage was 900-1200 for normal and 2500-3000 heroic
now it's 15600 max, and 75000 max

isn't it too much????????

**Comment by BarbzYHOOL** [comment]
but i think there is an issue with the feral defender damage, 900-1200 = too low

**Comment by merdlin** [comment]
> mas acho que há um problema com o dano do defensor feroz, 900-1200 = muito baixo

yes i saw it very low so i made the change following even trinitycore corrections.

**Comment by Voxstrasza** [comment]
way too high damage.  the feral defender isn't an NPC that can be tanked, it's a random aggro NPC.  meaning during the fight it'll spawn, a tank will taunt it and then it can jump to a caster or something - not to mention it has an ability that increases its damage by 50%

so I can only assume it was low in the DB because of this mechanic that the NPC does.  see https://wow.gamepedia.com/Feral_Defender for more info

if you raise the damage up, 15600 - 75000, combined with the ability that increases the damage, the mob will start one shotting the entire raid and that's no good

**Comment by Voxstrasza** [comment]
here's a video

https://youtu.be/j21Fa6gpSug

defender spawns about halfway, you can clearly see it doesn't do much damage to who it's attacking

**Comment by Racknar0** [comment]
These are the changes we observe

before PR

image 
image

after PR

image
image

After PR the creatures kill from oneshot this is correct?

MyGS:
image

**Comment by Voxstrasza** [comment]
> After PR the creatures kill from oneshot this is correct?

No it's not correct.  Also, as I've said, there's a scripted mechanic that goes with this NPC, so it's not as cut and dry as spawning the NPC and letting it attack you.  It's scripted to get a buff that increases damage during the Auriaya encounter.

The changes in this PR make this NPC hit too hard.

**Comment by Racknar0** [comment]
Attached a evidence at the current time of the blow in the battle can be seen that the damage is approximately 4763 in 10j
Video age 11 years 
Gear Score Naxxramas

https://youtu.be/QnenxIYOo9s?t=78

**Comment by FrancescoBorzi** [comment]
@merdlin

**Comment by Voxstrasza** [comment]
@merdlin @FrancescoBorzi since this PR is seemingly abandoned and I explained my reasoning why this shouldn't be merged earlier, I'm going to go ahead and close.

Just to reiterate: 

```
way too high damage. the feral defender isn't an NPC that can be "tanked", it's a random aggro NPC. meaning during the fight it'll spawn, a tank will taunt it and then it can jump to a caster or something - not to mention it has an ability that increases its damage by 50%

so I can only assume it was low in the DB because of this mechanic that the NPC does. see https://wow.gamepedia.com/Feral_Defender for more info

if you raise the damage up, 15600 - 75000, combined with the ability that increases the damage, the mob will start one shotting the entire raid and that's no good
```

**Pull request closed without merging**
