### PR TITLE
fix(DB): Tin Veins pooling import from vmangos

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Removed azerothcore's pooling and veins for Tin Veins.
- Imported vmangos pooling.

## Issues Addressed:

None reported

## Tests Performed:

Not tested yet.

## How to Test the Changes:

Wander around these zones and check for Tin nodes. Look for strange behavior with other Copper nodes.
If there's Silver or any other nodes acting weird is because they were part of the Tin pool and will be reworked next.

Duskwood
Westfall
Darkshore
Loch Modan
Wetlands
Arathi
Hillsbrad
Silverpine Forest
Barrens
Thousand Needles
Ashenvale
Desolace
Stonetalon
Redridge

## Known Issues and TODO List:

Silver Veins are gonna be spawned with an 100% rate, which my next PR will fix.
I could either:
1. Ask for a test with both Pull Requests to check for issues
2. Fix both Silver and Tin on the same Pull request.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
```
Pool Id 4700 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4701 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4702 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4703 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4704 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4705 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4706 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4707 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4708 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4709 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4710 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4711 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4712 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4713 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4714 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4715 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4716 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4717 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4718 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4719 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4720 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4721 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4722 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4723 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4724 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4725 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4726 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4727 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4728 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4729 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4730 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4731 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4732 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4733 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4734 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4735 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4736 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4737 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4738 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 4739 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2013 and cannot be safely removed.
Pool Id 11676 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2019 and cannot be safely removed.
Pool Id 11691 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2025 and cannot be safely removed.
Pool Id 11692 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2026 and cannot be safely removed.
Pool Id 11693 has no equal chance pooled entites defined and explicit chance sum is not 100. This broken pool is a child pool of Id 2027 and cannot be safely removed.
```

**Comment by claudiodfc** [comment]
@IntelligentQuantum Thanks for the test! Did you run the query with these last two queries?

``` mysql
UPDATE pool_gameobject SET pool_gameobject.chance = 100 WHERE pool_gameobject.description LIKE 'Spawn Point% - Silver' AND pool_gameobject.chance = 30;
UPDATE pool_gameobject SET pool_gameobject.chance = 100 WHERE pool_gameobject.description LIKE 'Ghostlands Spawn Point%Silver%' AND pool_gameobject.chance = 30;
```

**Comment by claudiodfc** [comment]
Build is failing due to PR #9284 missing. It can still be tested by merging the Copper before the Tin veins. The build will still fail thought.

**Comment by temperrr** [comment]
I would request doing these PRs per zone, if possible, so we can merge them like that.

**Comment by claudiodfc** [comment]
This PR is problematic, I'll make one per zone from now on.

**Pull request closed without merging**
