### PR TITLE
Update MAX_ARENA_SLOT (Fix Arena 1v1 Module)

### PR DESCRIPTION
**Pull request by Rastrian**
## Changes Proposed:
-  Update the current value of the MAX_ARENA_SLOT const

## Issues Addressed:

- https://github.com/azerothcore/mod-1v1-arena/issues/38

## Tests Performed:

- Build without error
- in-game testing with the module

image
image

## How to Test the Changes:

1. Install the azerothcore with this module (and the fixed code).
2. Open 2 clients and test arena module 1v1 queue.
3. Finish the arena.

## Known Issues and TODO List:

- [x] Fix queue.
- [x] Fix crash when arena ends.
- https://github.com/azerothcore/mod-1v1-arena/pull/41

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by benjymansy123** [comment]
May I ask what problems the module has without this change?

**Comment by Rastrian** [comment]
> May I ask what problems the module has without this change?

When the 1v1 arena finish, server crashses
image

as related here: https://github.com/azerothcore/mod-1v1-arena/issues/38

**Review by Viskus — APPROVED** [review]
can confirm this has fixed the outstanding issues.

**Review by acidmanifesto — APPROVED** [review]
defines can be a funny things at times. had something simular with the anticheat module.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
