### PR TITLE
fix(DB/SAI) Colonel Zerran (15385) Enlarge spell mechanics

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
- Removes aura 25462 from creature_addon as it was not blizzlike
- Changes SAI to buff nearby creatures with Enlarge
- Kept initial timer but added repeat from retail sniffs

## Issues Addressed:

- Closes unopened issue

## Tests Performed:

- Tested ingame

## How to Test the Changes:

1. `.go c id 15385`
2. see if he has an aura already applied to him
3. engage Zerran, see if he buffs nearby creatures with Enlarge

## Known Issues and TODO List:

- [ ] It's not perfect but it's better.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Maelthyrr** [comment]
Tested and only Quiraji Warior have an aura (two exactly). Is it right ?

WoWScrnShot_080622_073902

**Comment by Gultask** [comment]
I don't know why it shows up twice but Qiraji Warrior does indeed have aura 18950, it's sniffed.

**Comment by Maelthyrr** [comment]
Yes of course. I just want to say that the others (that fly, sry don't reminder their name), doesn't have aura. Only warrior. Is it fine ?

**Comment by Gultask** [comment]
Oh, yes it's intended. The Swarmguard Needlers don't have an aura :)

**Comment by Nefertumm** [comment]
It shows twice because the spell has 2 different effects, look again the image posted and pay attention to the type, it's the same as 
image

**Pull request merged**
