### PR TITLE
fix(Docker): add cache to dockerignore to speed up local build

### PR DESCRIPTION
**Pull request by Rochet2**
Apparently including cmake cache to the build context will take a long time for consecutive builds and causes docker build to spend a long time at `Sending build context to docker daemon (x %)` step.

## Changes Proposed:
-  add cmake cache to dockerignore so it is not copied to context when starting a docker build as it is not used in the image and causes a huge slowdown (the cache is used through a volume for the actual build, not for the `docker build` command)

## Tests Performed:
- none

## How to Test the Changes:

- without changes use docker to build the core.
- build the core again and see the slowdown caused by the old cmake cache
- add this PR
- build the core again and see that its now faster to start even if the old cmake cache is there

## Known Issues and TODO List:

- This was reported by someone else, so I have not tested this. just making the PR.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @Rochet2 for your contribution!

**Comment by Romain-P** [comment]
Tested and working

**Comment by Kitzunu** [comment]
This is one hella coordinated PR, Opened, Approved and Confirmed in 2 minutes :D

**Review by nethw — APPROVED** [review]
tested and working

**Review by locus313 — APPROVED** [review]

**Pull request merged**
