### PR TITLE
fix(Core/LFG): Add deserter debuff when player leaves after 15min

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
## CHANGES PROPOSED:
- Before that, it would only be added if the player left before 15 min. Now it will also be added if the player leaves at the end of the dungeon and only 1 boss is left to kill. So you're a deserter if you don't do the dungeon entirely. Seems fair to me.
- It also applies the debuff if you picked a specific dungeon, not only a random dungeon!!
- Refactor some variables (deduplicate code)

I make this PR to gather opinions too on this.

While writing this, I looked up wowpedia and found this:

> Leaving a group
> When you join a group you got via the Dungeon Finder you will be on Dungeon Finder cooldown, preventing you from joining another random group for the next 30 minutes (from the time you were matched with a dungeon). There are the following exceptions:
> 
> You got kicked from the group
> The end boss (or whoever gives the reward for joining a LFD group) of the instance has been killed
> Additionally, if you leave or are kicked from a group before one of the bosses is killed, you will receive the Dungeon Deserter debuff, which will prevent you from using the Dungeon or Raid Finder for 30 minutes.

Seems like i'm right

## TESTS PERFORMED:
- It works fine, if a player in a group leaves, it gives the deserter debuff even in non-random dungeons, but i didn't test BEFORE the PR

## HOW TO TEST THE CHANGES:

- Test before the PR please
- After the PR: connect with two accs, group the players, join dungeon finder on a specific dungeon (utgarde keep for example) and enter. Then one player leaves, and he gets the debuff

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by P-Kito** [comment]
https://de.wowhead.com/spell=71041/dungeondeserteur#comments:id=1429884

hmm...

**Comment by BarbzYHOOL** [comment]
> https://de.wowhead.com/spell=71041/dungeondeserteur#comments:id=1429884
> 
> hmm...

?

**Comment by Maurowin** [comment]
If u are kicked u shall dont have deserter debuff

**Comment by BarbzYHOOL** [comment]
> If u are kicked u shall dont have deserter debuff.
> Like said description of debuff :
> You abandoned your group and must wait before using Dungeon Finder or Raid Finder again.

yes, that's like that already, offtopic

**Comment by FrancescoBorzi** [comment]
shall we make this configurable?

**Comment by BarbzYHOOL** [comment]
my opinion is no, it's not custom, it's a fix
i made more tests (with the PR on) related to LFG and I can still say I think this fix is good. Before that, the deserter debuff would not be put on a non-random dungeon, and would also not be put in a random dungeon IF more than 15 min had passed.

**Comment by P-Kito** [comment]
Someone made a ticket back in 2011:

> I made a ticked asking about this issue I had, and his/her answer was; -"I believe that is a problem that we are aware of. There is a 15 minute period at the start of the dungeon where if you leave, you get the 30 minute dungeon deserter debuff and sometimes it is being applied to people that are vote kicked too. Unfortunately this was one of those occasions."
> Then I asked; "Ok, so its not intended to give those who get kicked the debuff then?"
> And s/he answered: "No, it's definitly not intended."


So cases you get Debuff:

Leave before 15 minutes gives the debuff
being kicked DOES NOT give debuff



It was already implemented the right way unfortunately.

**Comment by BarbzYHOOL** [comment]
not

**Comment by BarbzYHOOL** [comment]
Ok so @IntelligentQuantum told me there should be a config option to enable or disable this but I think he meant to disable the PVE deserter debuff entirely, like the BG deserter config option.

Why not, but in a subsequent PR

**Comment by Si1ker** [comment]
I think the change would be good, the debuff should be applicable at any time if the dungeon is still in progress... does not matter if is at the first minute the group has entered the dungeon or 2 hours later...
If [last boss] = IN_PROGRESS
else if [last boss] = not started
-> add aura

want to leave the dungeon without debuff? vote kick every single one until 2 are left (I think is 3 the minimum for not getting debuff)

**Comment by Kitzunu** [comment]
The question is not what is Good, the question is what is blizzlike.

**Comment by BarbzYHOOL** [comment]
> The question is not what is Good, the question is what is blizzlike.

read the PR desc

**Comment by Maurowin** [comment]
> 
> 
> Someone made a ticket back in 2011:
> 
> > I made a ticked asking about this issue I had, and his/her answer was; -"I believe that is a problem that we are aware of. There is a 15 minute period at the start of the dungeon where if you leave, you get the 30 minute dungeon deserter debuff and sometimes it is being applied to people that are vote kicked too. Unfortunately this was one of those occasions."
> > Then I asked; "Ok, so its not intended to give those who get kicked the debuff then?"
> > And s/he answered: "No, it's definitly not intended."
> 
> So cases you get Debuff:
> 
> Leave before 15 minutes gives the debuff
> being kicked DOES NOT give debuff
> 
> It was already implemented the right way unfortunately.

I half agree, to complete:

The debuff applies when:

- You leave the dungeon at any time, except when there are only 3 players left (including you).

The debuff does not apply when:
- When you get kicked.

I remember we used to ask to get kicked to avoid getting the debuff, nowadays it's still the case.

**Pull request closed without merging**
