### PR TITLE
fix(DB/Quest): Add Aqual Quintessence questline steps.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:
-  Adds the questline to acquire the Aqual Quintessence used for dousing fires in Molten Core to Duke Hydraxis with the exception of starting the quest [Poisoned Water](https://www.wowhead.com/wotlk/quest=6804/poisoned-water).

## Issues Addressed:

- Closes unreported issue.

## SOURCE:

Wrath Classic Beta:
- Took a template character to Hydraxis, he offered the [Stormers and Rumblers](https://www.wowhead.com/wotlk/quest=6805/stormers-and-rumblers) quest only. This is what should be the only option for any player unless they're going through a progressive server.
- Took a character from live Burning Crusade Classic that picked up the Poisoned Water quest and Stormers and Rumblers quest, copied them to Wrath Classic Beta, completed the two quests and observed that the next quest in the chain, [Eye of the Emberseer,](https://www.wowhead.com/wotlk/quest=6821/eye-of-the-emberseer) was available to accept.

## Tests Performed:

- Untested.

## How to Test the Changes:

1. Run the in-game commands `.quest add 6804`, `.quest add 6805`, `.quest complete 6804`, `.quest complete 6805`.
2. Go to Duke Hydraxis and continue his quest chain to its final quest, [A Hero's Reward](https://www.wowhead.com/wotlk/quest=7486/a-heros-reward).

## Known Issues and TODO List:

Needs to get tested.
It's unknown how deep the quest chain goes and what parts are still left over from the original chain in Wrath, but given that the UBRS quest is available to pick up in my own testing, as well as the [Wowpedia article](https://wowpedia.fandom.com/wiki/Aqual_Quintessence) pointing out that the quest chain was completable and the achievement was able to be earned, I myself believe this is blizzlike behavior.
This query is taken straight from the [progression system module.](https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_60_1_2/sql/world/progression_60_1_2_MC_poisoned_water.sql) If this is incorrect or needs tweaking, please let me know.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
For the moment the PR will stay in pending precisly because Woltk Classic is in beta. Blizzard will maybe revert this later as in 2009.

**Comment by heyitsbench** [comment]
> Blizzard will maybe revert this later as in 2009.

What part of this did they revert in 2009?

**Comment by Maelthyrr** [comment]
> > Blizzard will maybe revert this later as in 2009.
> 
> What part of this did they revert in 2009?

The beginning quest "Poisoned Water" was no longer available in 3.0.8. (you can find easly informations about see on various wiki and wowhead comments).

**Comment by heyitsbench** [comment]
Yes, this PR explicitly leaves that quest out, as it is in the Wrath beta.

**Comment by Maelthyrr** [comment]
Oh sorry, you have right. I didn't know this.

**Comment by Nyeriah** [comment]
Note for whoever merges this: the progression module queries need to be updated (MC poisoned_water_apply & revert)

**Comment by heyitsbench** [comment]
Finally got around to testing this. A brand new character can get the Silithus mobs quest, but nothing else. Manually adding the Poisoned Water quest lets the player continue through the entire quest chain, same as Vanilla.

Also, created a [PR](https://github.com/azerothcore/mod-progression-system/pull/236) for the progression module.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
