### PR TITLE
fix(DB/Event): Implement L70ETC Concert

### PR DESCRIPTION
**Pull request by Kitzunu**
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/14912

Co-Authored-By: Dr-J <1444120+dr-j@users.noreply.github.com>

## Changes Proposed:
-  Implement L70ETC Concert
-  Implement L70ETC Announcement

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

 Tested 3 years ago 👀 

1. .event start 81 / 82
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
@heyitsbench You saw it live, maybe you're the best one to test this out? 👀

**Comment by acidmanifesto** [comment]
Im not seeing any of the time emotes in this with each of the band members. They have special emotes that sync with the music.

**Comment by heyitsbench** [comment]
Well right off the bat, I can guarantee this isn't blizzlike, as this would line up with what Wowpedia says, which is wrong. That being the occurrence every three hours. As observed on Wrath Classic, this is definitely incorrect. As for the actual scripting, I don't know that I'll be all too good at spotting special effects like that, especially since the performance I saw didn't have them entirely lined up with the song regardless. 🤷‍♀️

**Comment by heyitsbench** [comment]
Alright, so in my observations the duration between ETC concerts seems to be four hours rather than Wowpedia's suggested three, same as Perry Gatner. I attached a recording of the performance to the original issue if anyone else wants to give it a test with a reference, but this is inherently an improvement from what currently (doesn't) exists. I'll try to give it a test when I have some spare time to compare the two, but it already exists in another core, so it can't be that bad. 😛

**Comment by Maelthyrr** [comment]
Is it in WIP or finish ?

**Comment by Kitzunu** [comment]
No time to fix it atm

**Pull request closed without merging**
