### PR TITLE
fix(DB/item_template): Remove Horde-only flag from Pattern: Raptor Hide Harness

### LINKED ISSUE #4854: Pattern: Raptor Hide Harness not learnable by alliance LW
Original report: https://github.com/chromiecraft/chromiecraft/issues/204 by @Hemingway1970
Please check also https://github.com/chromiecraft/chromiecraft/issues/204#issuecomment-799536398 and the suggested change
```
UPDATE item_template SET FlagsExtra=0 WHERE entry=13287;
```

##### ISSUE: FACTION SIDE:
Alliance

##### CONTENT PHASE:
20-29

##### SMALL DESCRIPTION:

The [Pattern Raptor Hide Harness](https://classic.wowhead.com/item=13287/pattern-raptor-hide-harness) is not learnable by alliance LW

Patten is sold by [Tunkk](https://classic.wowhead.com/npc=2819/tunkk)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Pattern should be learnable by any Leatherworker with the proper skill level. 

##### CURRENT BEHAVIOUR:
Recipe is not learnable by alliance LW and gives the error "You will never be able to use this item"

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Obtain pattern on skilled alliance Leatherworker either by in game mail or by AH
Step 2 Attempt to learn pattern
Step 3 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97181943-pattern-raptor-hide-harness-not-learnable-by-alliance-lw?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by necropola**
## Changes Proposed:
- Allow [Pattern: Raptor Hide Harness](https://wotlkdb.com/?item=13287) to be learned by Alliance character when transfered via trade, mail or AH   

## Issues Addressed:
- Closes #4854
- Closes https://github.com/chromiecraft/chromiecraft/issues/204

## Tests Performed:
- cmake, make on Linux without errors
- db_assembler.sh without errors
- checked DB using mysql command prompt
- learned pattern on Alliance character 

## How to Test the Changes:
- Get Alliance character to LW skill >= 165 
- Run .additem 13287
- Learn the pattern

## Target Branch(es):
- [x] Master
 
## How to Test AzerothCore PRs
 When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @necropola

**Comment by claudiodfc** [comment]
@pklloveyou are you in the discord chat?

**Comment by FrancescoBorzi** [comment]
@claudiodfc he is not, unfortunately Discord cannot be easily accessed from China :(

**Pull request merged**
