### PR TITLE
BREAKING CHANGE(Deps/Boost): Set 1.74 as minimum version

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
- Update minimum version to 1.74 to be able to proceed with C++20 build

## Tests Performed:

- Tested on windows, build can proceed and does not break on Boost being broken

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
I will test if 1.74 works to fix CI... Hopefully =)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/wiki/pull/591

**Comment by FrancescoBorzi** [comment]
https://www.conventionalcommits.org/

if it's `BREAKING CHANGE` it ain't `chore` :)

**Comment by Kitzunu** [comment]
True

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by necropola** [comment]
This is (currently) for windows only?
Debian stable (buster) has 1.67.
I'll need `buster-backports` which has 1.74 to meet this new requirement on debian stable.

I find thid recent trend of constantly changingbuild requirements extremely annoying.
Did the user experience become any better through any of those updates?

**Comment by FrancescoBorzi** [comment]
@necropola 

> Update minimum version to 1.74 to be able to proceed with C++20 build

this is required to proceed to C++20.

Also, we are requiring a minimum version that is already 1 year old (see https://www.boost.org/users/history/ ). There is no reason to use an even older version.

> This again breaks building on debian stable. which has 1.67.

Version 1.67 has been released **3 years ago**. Despite what we require and do not require, it's not recommended to use such old software unless there is a strong reason for it. Ideally, people should always keep their dependencies up to date with the latest stable versions of the software, in order to not have bugs that have already been fixed in a more recent version.

**Comment by FrancescoBorzi** [comment]
I'm reverting this change (see https://github.com/azerothcore/azerothcore-wotlk/pull/6975 ) as this is causing too many problems, including failing the Docker build on master and I don't want to deal with this now.

Please note this can stay this way forever, in future we will need to require a newer Boost version. It's just for now it's ok to keep it like this.

Also the next Debian version should fix this problem: https://packages.debian.org/bullseye/libboost-dev

**Comment by necropola** [comment]
Offical announcement of the **Bullseye full freeze on 2021-07-17**: https://lists.debian.org/debian-devel-announce/2021/06/msg00000.html
Which makes it quite likely that we are only 2-3 weeks away from release. :tada:

**Pull request merged**
