### PR TITLE
fix(DB/SAI): Quest "Territorial Trespass"

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- Set Veranus active in order to ensure that she starts and follows her path even when no player is near anymore or the player is too far away.
- Spawn Small Proto-Drake Eggs when using the quest item.
- Let Veranus land on her nest before Thorim mounts her.

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- preparation:
```
.quest remove 13051
.quest add 13051
.go 7094.71 -916.112 1067.29 571
```
- just proceed with the quest

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
nice,Success

**Comment by pklloveyou** [comment]
.qu r 10923
.qu ad 10923
.go c 76742

DELETE FROM `smart_scripts` WHERE `entryorguid` IN (22441);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES 
(22441, 0, 0, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Thrym - On Respawn - Set Active On'),
(22441, 0, 1, 2, 38, 0, 100, 0, 1, 1, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Data Set - Set Active'),
(22441, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 69, 1, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, -3398.96, 4466.33, -11.18, 0, 'Teribus the Cursed - On Data Set - Move To Position'),
(22441, 0, 3, 4, 34, 0, 100, 0, 8, 1, 0, 0, 0, 5, 293, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - Movement Inform - Play Emote'),
(22441, 0, 4, 5, 61, 0, 100, 0, 0, 0, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Data Set - Set Active off'),
(22441, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 0, 22, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Data Set - Set Event Phase'),
(22441, 0, 6, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Data Set - Set Home Position'),
(22441, 0, 7, 8, 60, 1, 100, 1, 2000, 2000, 0, 0, 0, 19, 768, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Update - Remove Unit Flags'),
(22441, 0, 8, 0, 61, 0, 100, 1, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, 0, 21, 70, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Update - Attack Start'),
(22441, 0, 9, 0, 7, 0, 100, 0, 0, 0, 0, 0, 0, 101, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Teribus the Cursed - On Data Set - Set Home Position');

**Comment by Stoabrogga** [comment]
@pklloveyou 
Could you please tell me why you are posting those SQL statements?

**Comment by pklloveyou** [comment]
@Stoabrogga Fix quest 10923

**Comment by Knindzagxg** [comment]
Tested, all good.

**Comment by Stoabrogga** [comment]
@pklloveyou @Knindzagxg 
Thanks for testing this. Concerning the quest "Evil Draws Near": I will take a look at this later.

**Comment by Stoabrogga** [comment]
@pklloveyou 

> 
> Fix quest 10923
> The Dragon sometimes too far will not appear

I tested this multiple times and the dragon came down every time. If there really is a problem concerning this quest please open an issue with a description on how to reproduce the error.

**Pull request merged**
