### PR TITLE
I close issue 119

### PR DESCRIPTION
**Pull request by cooler-SAI**
**Changes proposed:**

-  Fixed SAI
-  
-  

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc)

**Known issues and TODO list:**

- [ ] 
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by cooler-SAI** [comment]
Is it right now? I apologise - have some problems in real life.

**Comment by Dokman** [comment]
@cooler-SAI thanks to understood it, hahahaha, always with a happy face in the world, hahahaha

**Comment by talamortis** [comment]
please update ur git, as it not showing the correct information %N should be numbers

**Comment by ShinDarth** [comment]
@Yehonal  what is happening here ?

**Comment by cooler-SAI** [comment]
@talamortis  I have last version from GitExtensions

**Comment by cooler-SAI** [comment]
ok, Git updated and all good now)) you can apply

**Comment by ShinDarth** [comment]
@cooler-SAI please remove the old wrong file

@talamortis  can you test this? just to double check

**Comment by cooler-SAI** [comment]
@ShinDarth , done

**Comment by talamortis** [comment]
tested and working :) gj 👍

**Comment by ShinDarth** [comment]
@cooler-SAI @talamortis thanks a lot, merged

**Pull request merged**
