### PR TITLE
Add GMSummonPlayer Config Option

### PR DESCRIPTION
**Pull request by StygianTheBest**
**Changes proposed:** 
-  Give the GM the option of being able to summon players into instances.
-  The option is configured worldserver.conf.dist
- The option defaults to FALSE

**Target branch(es):** 1.x/2.x etc.
9d2395e1d379e539bd6da0138cb425532c848cb6

**Issues addressed:** Closes #
https://github.com/azerothcore/azerothcore-wotlk/issues/581

**Tests performed:** (Does it build, tested in-game, etc)
GTG

### CODE REVIEW

**Comment by Inifield** [comment]
Fix all intentation

**Comment by StygianTheBest** [comment]
@Inifield The indentation is perfect in Visual Studio, so I'm not sure why it's showing up like this.

**Comment by Inifield** [comment]
You need to setup your VS to 4 spaces its in the options

**Comment by StygianTheBest** [comment]
I changed to "insert spaces" so hopefully this sorts it out.

**Comment by Yehonal** [comment]
Please merge updates from master branch, we need to run a travis build to check about warnings.

**Pull request merged**
