### PR TITLE
fix(CMake): Deprecation warning

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## CHANGES PROPOSED:
-  Fix deprecation warning
-  Properly set minimum version (see https://cliutils.gitlab.io/modern-cmake/chapters/basics.html#minimum-version)

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1261

## TESTS PERFORMED:

Manual tested locally:
- macOS Catalina: `CMake version: 3.17.3`
- macOS Catalina: `CMake version: 3.18.4`

Tested automatically in CI:
- Ubuntu 20.04: `CMake version: 3.17.0`
- Ubuntu 18.04: `CMake version: 3.17.0`
- Docker: `CMake version: 3.16.3`
- Windows: `CMake version: 3.18.4`
- macOS Catalina: `CMake version: 3.18.4`

## HOW TO TEST THE CHANGES:

- Run CMake again
- Rebuild
- Make sure the build was successful

## KNOWN ISSUES AND TODO LIST:

- [x] Tested on macOS
- [x] Tested on Linux*
- [x] Tested on Windows

* I think it's enough to test Linux in the CI as the process is the same as you would normally do locally, also we run the dry run on Linux. While on Windows I'd still prefer if someone else tests it manually. 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers can anyone please give this a try?

**Comment by pangolp** [comment]
What should be done concretely? I don't understand what should be tested or how to do it.

**Comment by FrancescoBorzi** [comment]
> What should be done concretely? I don't understand what should be tested or how to do it.

just follow the generic steps to checkout a PR here: https://www.azerothcore.org/wiki/How-to-test-a-PR

then follow the specific instructions to test **this** PR that I posted above:

>Run CMake again
>Rebuild
>Make sure the build was successful

**Comment by pangolp** [comment]
I have already tried other pull requests. But what I don't understand, is that it would be necessary to try. Specifically, there was a warning while using CMAKE, or later in the compilation... that's what I meant. As I had not been completely clear, I wanted to ask you.

**Comment by FrancescoBorzi** [comment]
> I have already tried other pull requests. But what I don't understand, is that it would be necessary to try. Specifically, there was a warning while using CMAKE, or later in the compilation... that's what I meant. As I had not been completely clear, I wanted to ask you.

Just make sure using the version of this PR you are still able to correctly setup AzerothCore (so run cmake and compile without any new problems). That's it!

**Comment by LukasVolgger** [comment]
Tested, everything builds fine.

**Review by Si1ker — APPROVED** [review]
looks good

**Comment by FrancescoBorzi** [comment]
thanks @LukasVolgger and @Si1ker for test/review!

**Comment by Winfidonarleyan** [comment]
```Cmake
CMake version: 3.19.1
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
The CXX compiler identification is MSVC 19.28.29334.0
The C compiler identification is MSVC 19.28.29334.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
Loading module: modules/mod-transmog
Loading module: modules/mod-player-can-get-exp
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++17 support
Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
cotire 1.8.0 loaded.
Found MySQL library: C:/Program Files/MariaDB 10.5/lib/libmariadb.lib
Found MySQL headers: C:/Program Files/MariaDB 10.5/include/mysql
Found git binary : C:/Program Files/Git/cmd/git.exe

* AzerothCore revision            : 78dde1d423fb 2020-11-30 16:21:31 -0600 (fix-cmake-deprecation-warning-1261 branch)

* Install core to                 : C:/Program Files (x86)/AzerothCore
* Install configs to              : C:/Program Files (x86)/AzerothCore

* Build world/auth                : Yes (default)
* Build with scripts              : Yes (default)
* Build map/vmap tools            : No  (default)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable extra features           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Enable extra logging functions  : No (default)
* Show source tree                : Yes - "hierarchical"

Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
CXX target ace cotired without unity build.
Looking for open
Looking for open - found
Looking for _strtod_l
Looking for _strtod_l - found
Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib  
CXX target common cotired without unity build.
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD
Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
CXX target game cotired without unity build.
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
CXX RC target authserver cotired without unity build.
Running cmake hook: AFTER_AUTHSERVER_CMAKE
No hooks registered for AFTER_AUTHSERVER_CMAKE
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
SCRIPT PREPARATIONS
  -> Prepared: Spells
  -> Prepared: Commands
  -> Prepared: World
  -> Prepared: Outdoor PVP Zones
  -> Prepared: Eastern Kingdoms
  -> Prepared: Kalimdor
  -> Prepared: Outland
  -> Prepared: Northrend
  -> Prepared: Events
  -> Prepared: Pet
SCRIPT PREPARATION COMPLETE

CXX target scripts cotired without unity build.
CXX RC target worldserver cotired without unity build.
Running cmake hook: AFTER_WORLDSERVER_CMAKE
No hooks registered for AFTER_WORLDSERVER_CMAKE
Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done
Generating done
```

**Review by Helias — APPROVED** [review]

**Pull request merged**
