### PR TITLE
Core/Social: cleaunup, fix crash when friend or ignore get 0 guid and also double friend list

### PR DESCRIPTION
**Pull request by Viste**
## CHANGES PROPOSED:
-  cleanup
-  fix crash when friend or ignore get 0 guid( https://paste2.org/3dUy2Ud8 )
-  fix floating problem with double friend list

## ISSUES ADDRESSED:
don't find

## TESTS PERFORMED:
- build and run successful for 1 moth on wowka.su

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Viste** [comment]
@FrancescoBorzi done

**Comment by Viste** [comment]
@Winfidonarleyan мог бы вместо лайка ревью кинуть :D засланец!

**Review by Kitzunu — COMMENTED** [review]
To me it looks cosistent, but cant approve since I know too little about it.
Good job!👍

**Comment by Winfidonarleyan** [comment]
Ну ладно ладно, так и быть

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @Viste 

For @azerothcore/testers 

### How to test the changes

- Play with the Friend system (add/remove friends to your friend list), try login and logout between these actions too, make sure everything is fine

**Review by Helias — APPROVED** [review]

**Comment by peti446** [comment]
Test Results (Bold show errors encountered) tested on windows only:

- No crash encountered on start or during test
- Server runs > 20 mins with no crash
- While both characters are connected adding/removing friends o works fine, they show correctly level zone...
- Adding or removing a disconnected character it woks fine.  **However if the disconnected friend enters the game it will not show as online**
- **When reloggin with one of the character the friend list of the character reloged will be empty and adding the friend again will show "Is already in you friends" and will appear as disconnected and with an "Unknown" status with no way of adding or remove it** 
- Ignoring friend works fine, **on reloggin same as above happens list is cleared and ignore will not work (can send wispers)**
- Restarting server does not fix any of the presented issues

Pictures of errors:
image
image

**Comment by FrancescoBorzi** [comment]
Thank you very much @peti446 for testing this.

@Viste can you please check the issues reported by @peti446 and solve them? Let us know when this is ready for testing again.

**Comment by Viste** [comment]
hmm

**Pull request closed without merging**
