### PR TITLE
chore(unit-object-accessor): add findConnectedPlayer to object accessor

### PR DESCRIPTION
**Pull request by Helias**
## CHANGES PROPOSED:
-  add function **findConnectedPlayer** to **ObjectAccessor**
-  ~add function **Whisper** to **Unit**. this allows creature to send a message to a player~

## ISSUES ADDRESSED:
- I am adding this to support a new module that I will publish soon

## TESTS PERFORMED:
- I tested in-game with my module

## HOW TO TEST THE CHANGES:
To test them in a proper way for now you could just use a custom script that uses the two functions.

Anyway, these functions do not break anything because they are not used anywhere (I am just adding them in the core), so merging this PR will not break anything.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
I wonder how Clang 10 passes lol

**Comment by Helias** [comment]
I forgot to say that I got these functions from TrinityCore so they should be ok and already tested in past.
I will fix the build in the next days.

**Comment by Helias** [comment]
Thank you @Shard-MW I see.
But about finding players I think that findConnectedPlayer is not so bad compared to your solution, what do you think?
does it is not more compact and immediate to use?

**Comment by Helias** [comment]
I removed the whisper and leave the findconnectedplayer

**Comment by Helias** [comment]
The [module tic tac toe](https://github.com/azerothcore/mod-tic-tac-toe) require this PR to work, different users tested it.
This function is ported from TrinityCore and it's one-line simple function.
The function is not called anywhere it only can be helpful to some code migration from TC or implementing new features.

After this considerations I put this PR as **To Be Merged.**

**Comment by P-Kito** [comment]
Great merge from TC. I can use it for mythic+ aswell.

**Comment by Helias** [comment]
This PR merged now make AzerothCore full compatible with https://github.com/azerothcore/mod-tic-tac-toe

**Pull request merged**
