### PR TITLE
fix(DB): Befouled Water Elemental CTM

### LINKED ISSUE #10144: Water Elementals in Mystral Lake are evading
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2771

[Befouled Water Elementals](https://wowgaming.altervista.org/aowow/?npc=3917) will sometimes evade you, if you are swimming/under water. But if you aggro them while standing on a ground, they behave normally. 
I've thought that only those not moving in the lake are bugged, but the evading bug will sometimes trigger the others too. 

Tester:

The issue is confirmed and reproducible on local AC. There are several issues I discovered during triaging.

* The author is refering to this NPC `.go creature 32397`. Same issue for NPC `.go creature 32398`. These NPCs evade when attacking from inside the water. This issue does random appear. NPCs that can be pulled before sometimes random evade when attacking them again.
* There were also elementals on land that evaded when being attack from inside the water. For example `.go creature 32419`.
* It seems that you can bug elementals when chaning the terrain during the fight.

https://user-images.githubusercontent.com/62797536/149119944-0458a095-bba3-4883-857e-6c263439e812.mp4

* The named issues also affect the NPCs [Tideress](https://wowgaming.altervista.org/aowow/?npc=12759) and [Eck'alom (Rare)](https://wowgaming.altervista.org/aowow/?npc=10642).

### Expected Blizzlike Behaviour

Original report:
The NPC should swim towards you or attack you normally - not affected by the character being in the water or not.

Tester:
Changing the terrain (water, land) where you are fighting should not reset the NPCs.

### Source

_No response_

### Steps to reproduce the problem

Original report:
1. Swim in the water.
2. Attack non-patroling elemental (in the water) or sometimes attack even an unsuspicious one.
3. The NPC will behave like you are not there, as long as you are swimming in the water.

Tester:
* `.go creature 32397`
* Pull elementals
* Change terrain during fight

### Extra Notes

Videos: 
https://youtu.be/1cT4J-9DoJs
https://youtu.be/MPbBnZzr6VQ

Screenshots:
Snímek obrazovky 2022-01-12 091336
Snímek obrazovky 2022-01-12 091439
Snímek obrazovky 2022-01-12 091528
Snímek obrazovky 2022-01-12 091222

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c1ebda66bae939e7151fc9f43176dd897e8c01b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Befouled Water Elemental set to Swim and Run.

## Issues Addressed:

- Closes #10144 

## Tests Performed:

- Not Tested

## How to Test the Changes:

1. .go c id 3917
2. Pull out of water and in water

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by temperrr** [comment]
tested;

He does come in out of water, however,
he stays on the bottom of the water, and does not come to melee me

image

**Comment by acidmanifesto** [comment]
Hover locks him to the ground.

**Comment by claudiodfc** [comment]
I thought hover was because they didn't have legs, my bad 😄

**Comment by acidmanifesto** [comment]
not needed due to https://github.com/azerothcore/azerothcore-wotlk/pull/10147
but apply thing would not harm anything either.
I will leave that up for other staffers or pr maker to decide

**Pull request merged**
