### PR TITLE
fix(DB/Tanaris): [Rescue OOX-17/TN!] completes for all party members now

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

Store target list and target list as `target_type` seem to not work correctly in some cases. I would suggest changing to `target_type` 16 for all of these. The reason this might've not been chosen the first time around is to perhaps prevent griefing, when you throw someone out of the party? But this is highly debatable to be an issue and would be a minor issue imo.  This `target_type` (16), to me, seems like the best solution.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17129
- Closes https://github.com/chromiecraft/chromiecraft/issues/4913

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

Do this on multiple characters (up to 5)
1. `.additem 8623`
2. `.list creature 7784`
3. `.go creature <homingchickenGUID>`
4. turn in the quest from the item on all characters but don't accept escort yet
5. when all first quests are turned in on all characters, accept escort
6. complete escort and witness that everybody gets the credit

## Known Issues and TODO List:

- [ ] fix waypoints with sniffs, as the chicken clips through a hill in the beginning
- [ ] fix other escorts in azeroth with the same issues

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Does it work? Doesn't make sense to me since UPDATE_OOC doesn't have an invoker. Maybe it's calling for the last invoker stored, which would be the party, but still, I'd imagine it'd be overwritten by something. Usually Store Targetlist worked for me.

Oh well, if it works it works.

**Comment by elthehablo** [comment]
It worked for me. More testing welcome ofc

**Comment by Gultask** [comment]
I'll do one myself if I can remember, or if you're interested, one thing that caught my eye is On Death -> Fail Quest.
Invoker should be the killer, but it's an escort quest so the killer won't be players.

**Comment by elthehablo** [comment]
> I'll do one myself if I can remember, or if you're interested, one thing that caught my eye is On Death -> Fail Quest. Invoker should be the killer, but it's an escort quest so the killer won't be players.

Best to keep that as 12 then and re-add the store data

**Comment by elthehablo** [comment]
I don't really find it an elegant way tbh. I wish there was a better way

**Comment by Kitzunu** [comment]
stastus

**Comment by Nyeriah** [comment]
statusd

**Comment by Kitzunu** [comment]
Status

**Comment by Nyeriah** [comment]
Status

**Comment by YungElf** [comment]
Tested.

Tested on 2 characters, accepted Escort quest within a second or so of each other, got chicken to safety and both received credit for the quest. As stated by elthehablo, waypoints need to be sniffed as the chicken clips in the beginning of the quest. Also unsure if this is incorrect, but the quest is NOT shareable in its current state. 
Regardless, this PR fixes the issue listed. 

Thanks!

**Comment by MikaMauger** [comment]
There are a lot of escort quests which won't complete for all party members. There was a [fix for this in TrinityCore](https://github.com/TrinityCore/TrinityCore/issues/24706), and they chose to implement it using this trick (target_type=16).

**Pull request closed without merging**
