### PR TITLE
fix(DB/Creature): Brann Bronzebeard respawn

### PR DESCRIPTION
**Pull request by poszer**
Brann Bronzebeard respawn

##### CHANGES PROPOSED:

-  Updated 'spawntimesecs' to 20s
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1974

##### TESTS PERFORMED:

Yes on Win. Everything good for me.
Current issue was : 
- Brann Bronzebeard using script "brann_bronzebeard". The creature is spawned in Halls of Stone by DB, and it' using GUID: 126801. At this moment the respawn time is set to 3600 which is 1hour (And it's incorrect) bcoz this creature starting quest (event) and on every wipe/dead he should be respawned atleast in 20 , so people can abandon quest, and take it from him again to repeat Event.
This update should fix this issue.

##### HOW TO TEST THE CHANGES:

1. Go in Halls of Stone
2. Find the creature Brann Bronzebeard take quest from him
3. Activate Event by clicking on Gossip menu from him
4. Let him to die, also wipe with your group
5. He should be respawned when you release corpse and enter inside.

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

 
 
 
 
 ## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by ArashGorge** [comment]
i already requested pull for this problem here:https://github.com/azerothcore/azerothcore-wotlk/pull/2063
Does have problem ? Or u just wanna and fix it by DB query

**Comment by poszer** [comment]
> i already requested pull for this problem here:#2063
> Does have problem ? Or u just wanna and fix it by DB query

Hey @ArashGorge . Didn't saw anything referenced to this issue, since you didn't mention anything about this. Also, what i saw, we have this creature spawned by DB, not by script, and it's normally to lower his timer by query.
I already explained everything in description about issue , just read it. 
P,S. This will not cause any problems, the respawn timer is reduced for creature and it looks fine.

**Comment by Stoabrogga** [comment]
@poszer 
Are you sure that this issue still exists after PR #2063 was merged? The following part of the code should respawn Brann, so your PR is not necessary anymore in my opinion:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Ulduar/HallsOfStone/brann_bronzebeard.cpp#L590-L595

**Comment by poszer** [comment]
> @poszer
> Are you sure that this issue still exists after PR #2063 was merged? The following part of the code should respawn Brann, so your PR is not necessary anymore in my opinion:
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Ulduar/HallsOfStone/brann_bronzebeard.cpp#L590-L595

Dunno, i didn't saw that there is fix for this issue opened, since its not referenced. That's why i'm opening this one. Also I don't have that PR merged, and i can't say it's working or no. I can said just with this commit, i don't have anymore that problem since it was set before to respawn in 1 hour

**Comment by Stoabrogga** [comment]
@poszer 
Then please verify if the issue is gone already without your PR. We should not merge unnecessary PRs.

**Comment by poszer** [comment]
> @poszer
> Then please verify if the issue is gone already without your PR. We should not merge unnecessary PRs.

I don't know if the issue is gone without PR. I don't have that PR merged, bcoz it's not referenced anywhere as the fix, as the related commit to this issue.
I'm just opening PR with intent to solve this issue, bcoz i didn't know if it's fixed? Since the Creature is DB spawned, and we have creature Guid there in creature table which is 126801, isn't normally to put correct amount in row "spawntimesecs" or no? If not, close this PR

**Comment by Stoabrogga** [comment]
PR #2063 is already merged:
bad8390dee2fba50a711a26e6537fbdbb0d8863d
So this issue should already be fixed. I will close this PR and also issue #1974 as this seems to have been forgotten.

**Pull request closed without merging**
