### PR TITLE
fix(DB/Translation/FR) : Deputy Willem greetings gossip text

### PR DESCRIPTION
**Pull request by Elmsroth**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc) : TRANSLATION

## Issues Addressed:
- English text is appearing in french client in first human quest given by deputy iIllem in Northshire : 
image

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

The text come from a quite good translation. It is always better to have this for players experience instead of English/French mix.
I have tried to log into Wotlk live server on classic Wotlk but the Deputy Willem does not display this gossip greetings anymore (he only gives the quest and then never allow you to talk with him). Testd with a lvl 1 charater and a lvl 60 character

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.
Capture d'écran 2024-02-20 222127

## How to Test the Changes:
- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Test the first quest given by deputy willem on a French client after applying update

## Known Issues and TODO List:
- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Thanks for the PR!

Regarding your comment on the DELETE - query:
even if the entry does not exist before this PR, it ensures that the sql patch file can be executed repeatedly without any errors 🙂

**Comment by Elmsroth** [comment]
Thanks for your feedback @sudlud .
Yes I thought it was related to allow multiple executions with same results.
Do you think it can be merged ?

**Comment by heyitsbench** [comment]
```
Bien le bonjour, $c. Je devrais être à la recherche des gens de Hurlevent, mais bon nombre de gardes de Hurlevent combattent sur d'autres terres. Me voilà donc nommé adjoint et proposant des primes alors que je devrais être de patrouille...
```
Text taken from Wrath Classic build 52237.

**Comment by Elmsroth** [comment]
@heyitsbench How did you find that ?
I logged in wrath clssic  yesterday and he did not displays that when playing.

**Comment by Elmsroth** [comment]
Hum I think it could be fixed and perhaps not so difficult to do ? in handleGossipMenu perhaps.

**Comment by Elmsroth** [comment]
Thanks to @heyitsbench.I have updated the text.

**Comment by Elmsroth** [comment]
@sudlud or @heyitsbench Do you think it could be merged since the last update ?

**Comment by sudlud** [comment]
Imo most of the comments in the sql file are unnecessary, but that's not really an issue.

Did you check if maybe there's a broadcast text available for this?

**Review by elthehablo — APPROVED** [review]

**Pull request merged**
