### PR TITLE
 [Quest] smart_script 11223

### PR DESCRIPTION
**Pull request by pangolp**
##### CHANGES PROPOSED:

-  Add smart_script
-  Remove c++ script

###### ISSUES ADDRESSED:

Closes 

##### TESTS PERFORMED:

Test on Windows.

##### HOW TO TEST THE CHANGES:

To test the changes, it is enough to take the mission.
.quest add 11223

##### KNOWN ISSUES AND TODO LIST:
None in particular, just change the c++ script to an SQL script

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@pangolp thanks for your contribution!

**Comment by pangolp** [comment]
I didn't know that every time I had to upload an array I had to create a branch, but what happens with the previous array, do I get them automatically when I use the fetch command?

**Comment by pangolp** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/1334

**Comment by BarbzYHOOL** [comment]
@pangolp "ISSUES ADDRESSED: No" in the PR, it should have been 

```
ISSUES ADDRESSED: #1334
```

:P

**Pull request closed without merging**
