### PR TITLE
Scripts/Karazhan: Cleanup in opera event

### PR DESCRIPTION
**Pull request by Viste**
Once upon a time, some smart guy decided to climb this script and fuckup all encounter i get thing back where they should be
##### CHANGES PROPOSED:
-  analyzed the script, did the right thing.
###### ISSUES ADDRESSED:
should closes : #631 
##### Target branch(es): master

### CODE REVIEW

**Comment by disclosurez** [comment]
will test ty

**Comment by Viste** [comment]
close due to inactive testers

**Comment by FrancescoBorzi** [comment]
@Viste it does not make sense at all to close it "because of inactive testing".

Opening this and hoping people will test it soon.

**Comment by Viste** [comment]
@FrancescoBorzi some guys report the bug i look on it and do the PR, they dont care about it so i close it. If inn next 2 days nothing changes i close it again and delete branch with changes. If i see my work is not needed i dont want support this when you change some in main or when someone wakes up and test it next month.

**Comment by poszer** [comment]
> @FrancescoBorzi some guys report the bug i look on it and do the PR, they dont care about it so i close it. If inn next 2 days nothing changes i close it again and delete branch with changes. If i see my work is not needed i dont want support this when you change some in main or when someone wakes up and test it next month.

I aggre

**Comment by FrancescoBorzi** [comment]
@Viste @poszer how can closing the PR and deleting it help?

**Comment by Viste** [comment]
maybe people who can fix things self start think. in any case i dont care about your inefficient testing system, which does not guarantee that the broken changes will not get into the master.
The only thing it really does is push people away.

**Comment by FrancescoBorzi** [comment]
our testing system might be not efficient but it still better than not doing testing at all... especially in a program like this that does not have any automation testing at all

**Comment by Viste** [comment]
its not a contributors trouble, its maintainers trouble.
If you need contribs and devs you have to give them the conditions, not the stupid rules that just push people away.

**Comment by FrancescoBorzi** [comment]
@Viste so what are you suggesting?

**Comment by Viste** [comment]
@FrancescoBorzi you need automated test )

**Comment by FrancescoBorzi** [comment]
@Viste of course that would help, feel free to open PR and add some :)

**Comment by Viste** [comment]
@FrancescoBorzi i'm not interested in this, only in improve code base

**Comment by BarbzYHOOL** [comment]
alt_text

**Comment by degenesis** [comment]
Tested and working on 512559b.

WoWScrnShot_080419_225139

**Comment by Viste** [comment]
@pklloveyou sorry but i dont understand chines but as i see in your case dint work.
@degenesis Just on master or with PR, do you leave karazhan and can enter to it again?

**Comment by degenesis** [comment]
@Viste Oh I didn't fully understand the issue. Yes I can zone the raid out of Karazhan and zone back in.

**Comment by Viste** [comment]
@degenesis thx. and i still don't get you test just master branch without PR, or PR.

**Comment by degenesis** [comment]
Master branch with PR.

**Comment by Viste** [comment]
@degenesis big thanks!

**Comment by Viste** [comment]
@BarbzYHOOL nie try but read what i say in my big post, automated test its not a contribs trouble, yes someone can do it if want, but in general this may be done my repository maintainers.
i'm not maintainer of this repository, i just help people with bugs and move good things from other project.

**Comment by pklloveyou** [comment]
A very successful job.

**Pull request merged**
