### PR TITLE
fix (db): Remove unused script

### PR DESCRIPTION
**Pull request by acidmanifesto**
image

## Changes Proposed:
-  Removes unused Script Name

## Issues Addressed:

- Closes 

## Tests Performed:

- Ran on Database World
- Observered no Red

## How to Test the Changes:

1. run on database
2. observe no red

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
I don't have that issue in c59f6be0575f8aedc63c75f08ef3115b4c0be663

**Comment by acidmanifesto** [comment]
> I don't have that issue in c59f6be0575f8aedc63c75f08ef3115b4c0be663

I updated today, first time in a week and i got the issue  never touched any cthun scripts

**Comment by acidmanifesto** [comment]
> I don't have that issue in [c59f6be](https://github.com/azerothcore/azerothcore-wotlk/commit/c59f6be0575f8aedc63c75f08ef3115b4c0be663)

Are you sure you are not getting it?
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/3242618786/jobs/5316147700
image

Something is not right and thats the workflow showing that.

**Comment by Nyeriah** [comment]
This is the workflow from **this** PR….
That deletes the script that is in the database and working fine as is

**Comment by acidmanifesto** [comment]
> This is the workflow from **this** PR…. That deletes the script that is in the database and working fine as is

is it? jesus. talk about a bad compiler day then for me? reran it all fresh and made new branches. was still hitting it on my end.
I guess i will close it then and see what gets reported later.

**Pull request closed without merging**
