### PR TITLE
fix(DB/Creature): Delete creature, wrong spawn

### PR DESCRIPTION
**Pull request by poszer**
Creatures is wrongly spawned there

##### CHANGES PROPOSED:

-  Delete one creature from Borean T. Creature is wrongly spawned there causing issue entering in combat with other creature (CreatureTextMgr: Could not find TextGroup 1 for Creature(Bone Warrior) GuidLow 97670 Entry 26126. Ignoring.
-  

###### ISSUES ADDRESSED:
 There is issue about it, but i won't close it, since there is more creatures with some db problems.
Related to this : https://github.com/azerothcore/azerothcore-wotlk/issues/1062

Closes 

##### TESTS PERFORMED:

Yes, now is fine, also no more db errors about that text.

##### HOW TO TEST THE CHANGES:

Just go creature 97670 , and take a look around. If you find another creature like that (fighting others) congratz :rofl: 
Including one image : 
https://image.prntscr.com/image/L3TIt80USk2j7R8pc69Miw.png
Red is where is he spawned atm.
Green is, where are others creatures like him. 

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@poszer 
Could you please also remove these 2 creatures? They also seem to not belong into this area:
- GUID 101638, ID 25660 (Festering Ghoul)
- GUID 101626, ID 25660 (Festering Ghoul)

**Comment by poszer** [comment]
> @poszer
> Could you please also remove these 2 creatures? They also seem to not belong into this area:
> 
> * GUID 101638, ID 25660 (Festering Ghoul)
> * GUID 101626, ID 25660 (Festering Ghoul)

Sure, thank you

**Comment by Stoabrogga** [comment]
Ok, tested it once more but cannot reproduce the original issue mentioned in #1062. There are no errors in the log, the Bone Warrior just says "Die mortal". This PR is good, though, because the creatures don't belong into this area, but it has nothing to do with the log errors.

Btw, @poszer and @Pondaveia: Please stop labelling PRs as "To Be Merged" before they are tested. Even if it seems that the PRs are trivial, it makes sense to let at least one other person look at it.

**Comment by poszer** [comment]
> Ok, tested it once more but cannot reproduce the original issue mentioned in #1062. There are no errors in the log, the Bone Warrior just says "Die mortal". This PR is good, though, because the creatures don't belong into this area, but it has nothing to do with the log errors.
> 
> Btw, @poszer and @Pondaveia: Please stop labelling PRs as "To Be Merged" before they are tested. Even if it seems that the PRs are trivial, it makes sense to let at least one other person look at it.

You should leave that creature to enter in combat with other creature near him, the little one npc.
You can see in this image the red line, ignore text : 
If he enter in combat with him, you will get next db error.

CreatureTextMgr: Could not find TextGroup 1 for Creature(Bone Warrior) GuidLow 97670 Entry 26126. Ignoring.

https://image.prntscr.com/image/OIg025f1QuyLcYemRSt5Iw.png

**Comment by Stoabrogga** [comment]
@poszer 
Ok, now I saw the error in the log, too. As can be seen on the screenshot below the Bone Warrior says "Die mortal!", do you know where this comes from or how it is triggered? I don't see any references in the SAI or otherwise in the DB or the code, only an entry in the creature_text table for 26126.
WoWScrnShot_051019_074734

**Comment by poszer** [comment]
> e, only an entry in the creature_text table for 2612

Same. I can't find any references how it's triggered :laughing:

**Comment by Stoabrogga** [comment]
Ok, found the source of the talk text: It was a wrong target type for the "say" action of the creature "Defendo-tank 66D". I corrected this in PR #1819 .

**Comment by poszer** [comment]
> o-tank 66D". I c

Okaay, good

**Pull request merged**
