### PR TITLE
fix(Scripts/ZulGurub): Gah'zranka's Slam should reset threat.

### LINKED ISSUE #11567: [ZG] Gahz'ranka - Gahz'ranka Slam threat wipe mechanic
### Current Behaviour

When Gahz'ranka uses Gahz'ranka Slam (ID: 24326) the threat of the affected players remains unchanged.

### Expected Blizzlike Behaviour

When Gahz'ranka Slam is used, all threat of the players affected by the ability is wiped.

If everyone is affected by Slam, there should be no effect to the threat.

### Source

>Abilities
>- Knocks all melee-range units high into the sky, temporarily removing them from the hate list
>- Creates a geyser under a random secondary target, knocking back everyone near
([source](https://classic.wowhead.com/npc=15114/gahzranka#comments:id=2801785))

>This boss is weak you can tank him into the water (but it's annoying when he throws you in the air to take the aggro back ) ([source](https://classic.wowhead.com/npc=15114/gahzranka#comments:id=2918127))

https://youtu.be/BNsf4SbHFo4?t=334 shows the threat wipe in WotLK

https://youtu.be/BNsf4SbHFo4?t=307 shows that when everyone is hit by Slam, threat does not change.

https://youtu.be/T4NaB7KU0jQ?t=40 shows it perfectly in WoW Classic, and there are also Slams happening around 1:40 (Slam is cast immediately after Massive Geyser) and 2:35
At 0:30 a Massive Geyser and the following Water affects the tank, but they **do not** lose threat from it.

### Steps to reproduce the problem

1. Find a way to monitor threat
2. `.additem 19975 5`
3. `.additem 19974`
4. `.go xyz -11695 -1770 13 309` Teleports to Pagle's Pointe
5. Engage Gahz'ranka

### Extra Notes

After reviewing the video sources I decided to reopen the issue.
https://youtu.be/BNsf4SbHFo4?t=307 shows the threat not being wiped, that is because both players were thrown in the air by Slam
https://youtu.be/BNsf4SbHFo4?t=334 shows that when one player is affected, and the other is not, the threat of the player thrown is wiped

Wowpedia and some guides erroneously claim that Massive Geyser / Water ID: 22422 is what wipes threat, but that is not true, and there is a lot of video evidence from WoW Classic showing that, even if the tank is hit by Water from the Massive Geyser, they do not get their threat reduced.

Edit: From looking at a couple of videos I'd say the timer is 20s for the first and 20-36s for the following ones

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11567

## Issues Addressed:

- Closes #11567

## Tests Performed:

- Not tested.

## How to Test the Changes:

Find a way to monitor threat
`.additem 19975 5`
`.additem 19974`
`.go xyz -11695 -1770 13 309` Teleports to Pagle's Pointe
Engage Gahz'ranka

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Working great!

**Comment by mpfans** [comment]
@Nyeriah Please merge it

**Comment by Nyeriah** [comment]
@mpfans Please don’t ping me like this.

It’s fine to ping me over PRs that are critical and PRs that are in the queue for too long for whatever reasons, but pinging me on every single PR merely 13 hours after they’ve been added to the queue is absurd. Half of that time I was sleeping.

**Comment by mpfans** [comment]
> @mpfans Please don’t ping me like this.
> 
> It’s fine to ping me over PRs that are critical and PRs that are in the queue for too long for whatever reasons, but pinging me on every single PR merely 13 hours after they’ve been added to the queue is absurd. Half of that time I was sleeping.

ok... I'm sorry. I'll notice that later

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Missing include

/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/EasternKingdoms/ZulGurub/boss_gahzranka.cpp:111:37: fatal error: base class has incomplete type
class spell_gahzranka_slam : public SpellScript
                             ~~~~~~~^~~~~~~~~~~
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Scripting/ScriptMgr.h:67:7: note: forward declaration of 'SpellScript'
class SpellScript;
      ^

**Comment by UltraNix** [comment]
@Nyeriah Should be okay now.

**Pull request merged**
