### PR TITLE
 docs(README.md): normalized captions

### PR DESCRIPTION
**Pull request by abebeos**
trivial

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]
Looks better than before to me!

**Comment by BarbzYHOOL** [comment]
being the author of the readme, i prefer the original way but i guess it'll appeal to more people if not in uppercase

**Comment by abebeos** [comment]
> it'll appeal to more people if not in uppercase

The are standards/quasi-standards, which you should not ignore.

Here a simple doc re capitals:

https://www.skillsyouneed.com/write/capital-letters.html

**Comment by BarbzYHOOL** [comment]
I had capitalized titles only, your link is not talking about it

But I agree it's not common so it's fine

**Comment by abebeos** [comment]
> I had capitalized titles only, your link is not talking about it

It does

>>Rule 2:
>>Titles
>>
>>In titles, capitalise only the important words, not minor words such as ‘and’ and ‘but’.

You used FULLCAPS, which is nearly never ok, see

>> Rule 6:
>> Overusing Capitals is Rude
>>
>> WRITING ENTIRELY IN BLOCK CAPITALS IS SHOUTING, and it’s rude.

https://www.skillsyouneed.com/write/capital-letters.html

Those are very basic general rules, and it doesn't matter much if we agree or not.

**Pull request merged**
