### PR TITLE
fix(Scripts/Temple of AhnQiraj): Vekniss Stinger.

### LINKED ISSUE #12929: [AQ40] Vekniss Stinger (15235) are not casting anything
### Current Behaviour

They cast no spells

### Expected Blizzlike Behaviour

1. They should cast Stinger Charge immediately on pull and every 6s after.
2. They should cast 26081 on targets **without** aura 26078, and 26082 on targets **with** aura 26078.
3. They should **always** prioritize targets afflicted by aura 26078. If no targets have aura 26078, it charges one person randomly from their threat table.

### Source

Retail

### Steps to reproduce the problem

1. `.go c id 15235` with 2 or 3 characters if the range condition has been added
2. `.aura 26078` on one character, see if Vekniss Stinger always charges that character
3. drop the aura, see if it chargers random characters

### Extra Notes

I've not been able to confirm but there are written sources claiming they prioritize charging players >5y away from them first. Choosing players <5y away if none else are available.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a347e3fca86f61d1095511b885be7ad5b5391f41

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12929

## Issues Addressed:

- Closes #12929

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c id 15235` with 2 or 3 characters if the range condition has been added
`.aura 26078` on one character, see if Vekniss Stinger always charges that character
drop the aura, see if it chargers random characters

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
@UltraNix Tested with two chars, I got the first on the pull but after any new charges.

**Comment by UltraNix** [comment]
@Maelthyrr Within 20y distance?

**Comment by Gultask** [comment]
Tested as well.

- [X] Changes spell correctly when the target has Vekniss Catalyst.
- [ ] Does not charge tank after the first cast, even if they are the only target available.
- [ ] Does not always prioritize players with the Vekniss Catalyst aura.

https://user-images.githubusercontent.com/100873791/188326858-282fe89c-cb63-473e-a979-8ab7d0b5fd21.mp4

**Comment by UltraNix** [comment]
@Maelthyrr @Gultask Should be okay now.

**Comment by Gultask** [comment]
Looks great on my end 👍

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
