### PR TITLE
fix(DB): Various names & title fixes in locales

### PR DESCRIPTION
**Pull request by Endeffect-AT**
Merged PRs #2480 and #2481 as @FrancescoBorzi suggested.

##### CHANGES PROPOSED:

-  Added missing titles for weapon masters
-  Added missing titles for auctioneers & removed duplicate titles in names
-  Added missing description for items

- Fixed name & title for npc 13476 Zen'Balai to Balai Lok'Wein - The creature entry 13476 got the name & title from patch 4.0.3a - fixed as to be wotlk Balai Lok'Wein. 
References taken from https://wow.gamepedia.com/Zen%27Balai

##### ISSUES ADDRESSED:
- Closes

##### TESTS PERFORMED:
- imported and checked the tables

##### HOW TO TEST THE CHANGES:

import sql file and check the tables
##### KNOWN ISSUES AND TODO LIST:

- [x] Fixed deDE locales 
- [x] Fixed esES locales 
- [x] Fixed esMX locales 
- [x] Fixed frFR locales 
- [ ] <del>Fixed koKR locales
- [ ] <del> Fixed ruRU locales 
- [ ] <del>Fixed zhCN locales
- [ ] <del>Fixed zhTW locales
##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Endeffect-AT check my comment in Discord :)

**Comment by Viste** [comment]
i add some ruRU locales in past and also Heartwell do it, and ruRU must be ok fully

**Comment by Endeffect-AT** [comment]
So you added them in past on your server or here? I don't understand what you mean

**Comment by Viste** [comment]
I don't have a server, that's not why I'm here. Next, think for yourself.

**Comment by Endeffect-AT** [comment]
Okay, my english is not the best but i think you misunderstood my last last post. Anyway, if no one want my help in a learning project, i quit and study for myself

**Comment by FrancescoBorzi** [comment]
@Endeffect-AT yes your help is much appreciated

**Comment by Viste** [comment]
@Endeffect-AT https://github.com/azerothcore/azerothcore-wotlk/pull/407 for be clear 
and some other PRs/Commits
sorry if i look rude or somthing, eng is not my native language too

**Comment by Endeffect-AT** [comment]
@Viste 
Don't worry, everything's okay :+1:

**Comment by Endeffect-AT** [comment]
@BarbzYHOOL 

Can be merged as discussed with you 😄

**Comment by BarbzYHOOL** [comment]
since it's language related, it makes testing even more annoying, right?

if not, tell us how to test ingame plz (in the PR description)
which NPC or item to check?

else i'll try to import the sql and compare in the table when I can, don't worry it will be merged :)

**Comment by Endeffect-AT** [comment]
Annoying, not necessarily when it comes to no great structural changes. Here only the table creature_template is compared and adjusted with creature_template_locale for the missing titles. Same as the item_template ...
The only major change is the NPC where the references in the link above are to be found and even if you stand in front of the NPC realize that something can not be right.
If the code has been approved and the references are verified, no further tests are required.

**Comment by Stoabrogga** [comment]
Pushed a commit replacing the delete/insert statements with updates like you did on the other entries. Deleting and inserting the entries is not necessary here.

**Comment by Endeffect-AT** [comment]
I tried it several times with a update statement but got a syntax error so i used the del/ins. That made me already crazy xD
Thx for fixing it!

**Comment by Stoabrogga** [comment]
I compared the updates and they seem to just fill the empty "title" column, looks ok. But I think the names of the auctioneers have to be changed as they contain the title in their names. For example ID 16627 has the name "Auktionator Ithillan" for locale "deDE" and would then be "Auktionator Ithillan" with title "Auktionator", which would look strange. The actual creature template does not contain the title in the name, it's just "Ithillan".

**Comment by Endeffect-AT** [comment]
At first I believed too. For all vanilla auctioneers the title is included in the name - without additional title. For Silbermond and the Exodar I could not find a clear reference, which is why I primarily want to complete only the missing title. 
A live p-server has the spelling as you mean https://db.rising-gods.de/?npcs&filter=cr=18;crs=1;crv=0. 

Now the question is what is right: D

**Comment by Endeffect-AT** [comment]
That's why i didn't touch the creature_template itself

**Comment by Stoabrogga** [comment]
In my opinion we should just remove the updates for the auctioneers from this PR. Yes, the names may be a bit different from the English version, but it looks much worse if the title is suddenly contained twice for the other languages.

**Comment by Endeffect-AT** [comment]
I agree with you that it is better to have a consistent line for the titles. In that case, I would rather tend to the version of Rising Gods https://db.rising-gods.de/?npcs&filter=cr=18;crs=1;crv=0, as this is a WotLK P server for more than 10 years and these are most Blizzlike act like many others.

**Comment by Endeffect-AT** [comment]
Also i wanna say that the same happens with the weaponmasters. As they got "weaponmaster" in name & title at the same time it's correct!

**Comment by Stoabrogga** [comment]
No, the weapon masters don't have their title in the name, just checked a fresh AC DB.

**Comment by Endeffect-AT** [comment]
Forget my previous comment, had a miscalculation... You're right! I just saw on Discord that someone has done the translation done for frFR. 

I would suggest the following: We add the titles for the auctioneers as already changed and remove the "titles" in the name itself. I can do that for ALL locales without great translation effort ...

**Comment by Stoabrogga** [comment]
That's ok with me, we should just avoid having duplicate titles, because this looks ugly when the player interacts with the NPCs.

**Comment by Endeffect-AT** [comment]
Alright, work on it soon :thumbsup

**Comment by Endeffect-AT** [comment]
Just fixed for deDE, esES, esMX & frFR. 
I thought about it again and think that it is better not to touch the other locales if there is no complete fix available. So we fixed everything where we know 100% that it is correct

**Comment by Stoabrogga** [comment]
Checked the updated rows and everything looks good to me. I think this can be merged.

**Pull request merged**
