### PR TITLE
fix(DB/Creature): Tender Strider Meat chance increase /  icon for Refurbished Steam Tank

### PR DESCRIPTION
**Pull request by Voxstrasza**
## Changes Proposed:
-  Increase drop chance of 'Tender Strider Meat' for quest Kyle's Gone Missing! (ID: 11129) to 50% based on videos that show that this quest is completed with one or two kills of a mob - currently on AC it's a 10% droprate which is considerable for a low level entry quest
-  Remove 'Get In' Icon on Refurbished Steam Tank

## Issues Addressed:
- It was closed, but #3239 mentions the low drop chance of Kyle's Gone Missing! quest item
- Refurbished Steam Tank, an NPC with SAI in Stormwind, was an NPC implemented in WotLK pre-patch - it used to fight the Scourge during the Scourge Invasion Event, but now it simply spawns, drives around and breaks down.  You were never able to 'get in' to this vehicle, as it was just an NPC that drove around and smashed some undead baddies. ([based on Wowhead comments for this npc](https://www.wowhead.com/npc=29144/refurbished-steam-tank#comments))

## How to Test the Changes:
1. Apply SQL, clear your cache and restart the server - create an alliance character for the steam tank, a horde character for the quest
2. .tele stormwindharbor and find the Steam Tank, hover your mouse over it to ensure it doesn't show a get in icon
3. .tele mulgore, .level 10 and .quest add 11129, go kill the specified mobs to ensure the drop chance was increased

## Target Branches
Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Kitzu said to separate the PR in two, that's understandable but since it's a tiny second fix, then imo it can be all in one. We can show some leniency and mercy :D

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @pklloveyou can anyone please test this?

**Comment by pangolp** [comment]
Indeed, without applying the fix. I killed about 10 npc, and they didn't drop the item.

WoWScrnShot_020221_224620

**7 queries executed, 7 success, 0 errors, 0 warnings**

Once the fix has been applied. Indeed, practically all the npc will drop the item.

WoWScrnShot_020221_225112

**Review by pangolp — APPROVED** [review]

**Review by Kitzunu — CHANGES_REQUESTED** [review]
Make it one delete and one insert for it all :)

**Comment by pangolp** [comment]
```sql
DELETE FROM `creature_loot_template` WHERE `Item`=33009 AND `Entry` IN (2956, 2957, 3068);

INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(2956, 33009, 0, 50, 1, 1, 0, 1, 1, NULL),
(2957, 33009, 0, 50, 1, 1, 0, 1, 1, NULL),
(3068, 33009, 0, 50, 1, 1, 0, 1, 1, NULL);

UPDATE `creature_template` SET `IconName` = NULL, `VehicleId` = 0 WHERE `entry`=29144;
```
@Voxstrasza

**Review by Kitzunu — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/504a788c63265a85ac730ce5dd6c5a067f25ee67

**Pull request merged**
