### PR TITLE
fix(CI): disable mac PCH to allow more caching

### PR DESCRIPTION
**Pull request by Rochet2**
## Changes Proposed:
-  Disable PCH in mac CI to allow ccache to cache more files
-  Decrease mac CI  ccache max size to 1G since that fits a bit more than one build

## Issues Addressed:
- It **seems to me** that regardless of the fixed cache saving the mac builds are taking ~45 minutes even on `master` branch as seen here: 
image

- With the proposed changes the time is hopefully closer to 20 minute mark as seen here: 
image

## Tests Performed:

- 
- 

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by locus313 — APPROVED** [review]

**Comment by Footman** [comment]
Hey thanks for pull request. Did you probably get it running on M1 Chip mac?

**Comment by Footman** [comment]
Hey thanks for pull request. Did you probably get it running on M1 Chip mac?

**Comment by locus313** [comment]
> Hey thanks for pull request. Did you probably get it running on M1 Chip mac?
Far as I know github actions does not currently support mac M1 chip runners yet. There is probably also some other work we need to do to support ARM. Think I saw an issue opened about it.

**Comment by FrancescoBorzi** [comment]
good job!

**Pull request merged**
