### PR TITLE
[Naxxramas] Gothik the harvester minions

### LINKED ISSUE #424: [NPC][WOTLK] Gothik the Harvester encounter minions(They are not scripted).
**Description**: So,on Gothik's encounter,minions don't use any spells at all. Both on the living side, and on the undead side

**Current behaviour**: Descripted higher.

**Expected behaviour**: All minions on Gothik encounter must use their spells,like Shadow Mark from Death Knight on living side,and Arcane Explosion from Spectral Trainee on undead side.

**Steps to reproduce the problem**:

1.  Pull Gothik(start encounter)
2.  Wait around 1:30 to pack different NPCs
3.  You'll see,they don't use any spells.

**Branch(es)**: master

**AC hash/commit**:  e0d951c

**Operating system**:  WIndows 8.1 with all current system updates.

**Modules**: No, i don't

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/43014780-npc-wotlk-gothik-the-harvester-encounter-minions-they-are-not-scripted?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pondaveia**
**Changes proposed:**

Added spells to npcs on living and dead side:
-  Trainees
-  Knights
-  Riders

**Target branch(es):** Master

**Issues addressed:** Closes #424 

**Tests performed:** Builds but needs to be tested.

**Known issues and TODO list:**

- [x]  Tested by me

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Sdyess** [comment]
Is there a reason this can't be done in smart scripts?

**Comment by pondaveia** [comment]
Well their script is counting the waves. Unless you want to find a solution for what is already working I don't see a reason to change this.

**Comment by Sdyess** [comment]
Yes but all this did was add spells to the npcs. Something that smartscripts are easily capable of doing and suited for.

**Comment by pondaveia** [comment]
You can't have both core and SAI on npc.

**Comment by alexkulya** [comment]
You can try SmartAI::UpdateAI(diff);

But I can be wrong.

**Comment by pondaveia** [comment]
I'll take a look after my first PR

**Comment by talamortis** [comment]
Tested and working as intended but why not use smartAi? @Yehonal ill leave this one for you go make the decision.

**Comment by Sdyess** [comment]
Currently as the script stands, it relies on tracking the deaths of the minions, which is harder with smartai. But I’m also pretty sure you can store all the summons and track their deaths as well, and just script the minions in smartai

**Comment by BarbzYHOOL** [comment]
Yes, probably can be done in SAI but it's really not for someone who never dealt with SAI.

Better to have it done this way than not

**Comment by Motorheadx** [comment]
tested and working fine

**Comment by talamortis** [comment]
Since @Yehonal  has not replied about this ill merge till a better solution is done/SAI is complete.

**Pull request merged**
