### PR TITLE
fix(Scripts/Pets): Force of Nature's Treants should inherit haste fro…

### LINKED ISSUE #13531: Force of nature's Treants not scaling with haste rating
https://github.com/chromiecraft/chromiecraft/issues/4288
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Treants spawned by the balance druid talent Force of Nature (https://wowgaming.altervista.org/aowow/?spell=33831) are currently not benefitting from the druid's haste rating. 

### Expected Blizzlike Behaviour

It should work similarly to unholy deathknight's summon gargoyle (https://wowgaming.altervista.org/aowow/?spell=49206) as in "it should snapshot with the player current haste stat when summoned".

So you could use stuff like Haste Potion ( https://wowgaming.altervista.org/aowow/?item=22838 ) or even MCP ( https://wowgaming.altervista.org/aowow/?item=9449 ) before casting Treant so they fully benefit from haste. 

### Source

**Wowhead comment from back in the day :** 

https://www.wowhead.com/wotlk/spell=/force-of-nature#comments : 

image
image

**Youtube video (for WOTLK retail but according to the previously mentionned wowhead comments, that's how it worked at the time anyway) :** 

https://www.youtube.com/watch?v=fzcP1dz_oB4 *

Small disclaimer about this video : Beside the clickbait title, he mention a bug in the video. The bug he mention isn't treant scaling with haste, but the fact that you can abuse spec-swap going to use treants in feral spec.

### Steps to reproduce the problem

1. Create a druid
2. .learn 33831
3. .level 59
4. .setskill 160 300 300
5. .additem 22838 & 9449
6. Use MCP ( https://wowgaming.altervista.org/aowow/?item=9449 ) + Haste potion ( https://wowgaming.altervista.org/aowow/?item=22838 ) in order to have massive haste, making the difference more noticeable. 
7. You'll see no difference between 0 haste and 900 haste rating.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…m owner.

Fixes #13531

 

## Issues Addressed:

- Closes #13531
- Closes https://github.com/chromiecraft/chromiecraft/issues/4288

## Tests Performed:

- Not tested.

## How to Test the Changes:

Create a druid
`.learn 33831`
`.level 59`
`.setskill 160 300 300`
`.additem 22838 & 9449`
Use MCP ( https://wowgaming.altervista.org/aowow/?item=9449 ) + Haste potion ( https://wowgaming.altervista.org/aowow/?item=22838 ) in order to have massive haste, making the difference more noticeable.
See the difference between 0 haste and 900 haste rating.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I couldn't see any difference. I made a macro to apply the 900 haste bonus to myself but when I compared damage dealt it was pretty much the same, with auras being slightly lower. No observable difference in pet attack speed, either.

.aura 13494
.aura 28507

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Santaria94** [comment]
I looked at the report and it seems to me that additional proofs are needed for it, since this is still a pretty serious change in the class ability.

1. Both wowhead comments don't look like serious testing. In the first comment, the difference in the number of hits is only 4, which may be caused by other factors. In the second comment, we are generally talking about the total damage dealt, the difference in which could be caused by the number of critical hits or misses.

There is also a comment that does not report scaling with haste
>By 166824 (6,773 – 3·11·33) on 2008/10/16 (Patch 3.0.2)		
Treants 3.0
-Damage scaled up noticeably (They crit for almost 1000 on the target dummies with +700 SP. Crit a gnome warlock for 1.5k with 1.2k spell power).
-They get a pet bar! =O (No more unwanted aggro of other mobs!)
-With Blizzard FINALLY letting you see mob health, you can see that each treant has around 2.5k health. (400 current Stamina. Seems health scales up with Stam. 700 Stam hits them around 3.5k-ish)
-Brambles adds 15% extra damage, not to mention the 15% chance to daze the target (50% reduced movement speed). Assuming that the Treants attack every two seconds, that means every two seconds, the enemy has an (approximate) 38-39% chance of getting dazed.
And that's it really. Small amount of changes, but they make a huge difference.
TREANT STATS
Stats: 2.1k Spellpower, 1.6k Stamina, No haste. The trees seem to take your spell critical chance. Buffed with IMotW. 3/3 Brambles.
edit: this is pre-3.3. I'll get it updated sometime.

2. The statement in the video is not supported by a practical example and confirmation that this is indeed the case. There is also an interesting commentary on the video that raises doubts about what was said in it.
>Clazzo
i was told on the druid disc the treents dont snapshot the haste from pummeler only nature spell power?

**Comment by Nefertumm** [comment]
Probably some kind of sniff or further testing on official servers would do it.

**Comment by UltraNix** [comment]
@BeefSteaker

**Comment by Gultask** [comment]
WotLK Classic PTR has potions of haste at vendors, probably. But the sniffer isn't up to date last I saw.

**Comment by heyitsbench** [comment]
> WotLK Classic PTR has potions of haste at vendors, probably. But the sniffer isn't up to date last I saw.

Would you not be able to discern it from combat logs?

**Comment by Gultask** [comment]
Maybe. But it's several creatures and it's haste-based. Maybe even a video could clarify it, given enough haste.

**Comment by UltraNix** [comment]
Sniffer is not needed. Just observe damage and speed.

**Comment by UltraNix** [comment]
@Gultask

**Comment by heyitsbench** [comment]
[Tested on the Wrath Classic PTR](https://www.youtube.com/watch?v=ILnef2Hzf-U). I could not see a difference. Combat log and Details! Damage Meter (Overall data) are visible during the test.

**Comment by UltraNix** [comment]
So the report is invalid.
Closing.

**Pull request closed without merging**
