### PR TITLE
chore: Rename Worldserver & Authserver config variables

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
##### CHANGES PROPOSED:
- Give proper name to that debug option

##### TESTS PERFORMED:
- NO TESTS DONE (but i had to make the PR while I had it in mind else it would be forgotten forever :P)

##### HOW TO TEST THE CHANGES:
Compile and set cmake option `CONF_DIR` to a specific path

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stoabrogga** [comment]
I think this PR can be closed together with #2424 as new names already have been introduced with commit e22d78e.

**Comment by BarbzYHOOL** [comment]
my names were better

**Comment by Stoabrogga** [comment]
I like "ACORE" better.

**Comment by Helias** [comment]
guys, for me is the same, it's just a convetion

**Pull request closed without merging**
