### PR TITLE
fix(Script/Command): Build

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  fix build

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by 55Honey — APPROVED** [review]

**Comment by Kitzunu** [comment]
Hmm I dont understand why the codestyle is failing... It doesn't have these blank lines anywhere in the file :shrug:

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can you help please?

**Comment by Raelorasz** [comment]
> 
> 
> Hmm I dont understand why the codestyle is failing... It doesn't have these blank lines anywhere in the file 🤷

I think it's those two blank lines on line 202-203

**Comment by Kitzunu** [comment]
how did I miss that

**Comment by Winfidonarleyan** [comment]
Plz add include "#include "MySQLThreading.h"`

**Pull request merged**
