### PR TITLE
fix(DB/ElwynnForest): allow Defias Cutpurse to use their Backstab ability

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
- add 2 castflag to allow them to use their backstab ability which usually costs 60 energy, which they don't have

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16433

## SOURCE:

Ability is in db. Mob cannot cast it because of energy requirements 

## Tests Performed:

- tested ingame. works
- 

## How to Test the Changes:

1. Go to Elwynn Forest towards the north where the Defias Cutpurse camps are
2. Turn your back
3. Should get backstabbed

## Known Issues and TODO List:

It could technically be possible they use a different backstab version. But that would require sniffing. According to wowhead they do seem to use a backstab that uses energy.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
There is an event BEHIND_TARGET which would work better for Backstab

**Comment by elthehablo** [comment]
> There is an event BEHIND_TARGET which would work better for Backstab

Yeah. Didn't know that existed, but that is more elegant than firing the spell and just having failing conditions most of the time

**Comment by elthehablo** [comment]
Unfortunately this event doesn't seem to make them trigger the cast. I will revert it back for now. As the condition is within the spell to be behind the target, and this is not circumvented by any castFlag, this works. It is not elegant, but it does work.

**Comment by Vyperhand** [comment]
> Unfortunately this event doesn't seem to make them trigger the cast. I will revert it back for now. As the condition is within the spell to be behind the target, and this is not circumvented by any castFlag, this works. It is not elegant, but it does work.

Idea/brainstorming:  Is there a known working rogue NPC elsewhere with backstab that code could be cannibalized from to optimize it and make it consistent with similar mobs?

**Comment by Gultask** [comment]
> Idea/brainstorming: Is there a known working rogue NPC elsewhere with backstab that code could be cannibalized from to optimize it and make it consistent with similar mobs?

Yeah we can query from BEHIND_TARGET event. Dunno why this one didn't work

**Comment by Gultask** [comment]
@elthehablo missing file extension

**Comment by elthehablo** [comment]
> @elthehablo missing file extension

Lmao yeah. Wtf was I on

**Comment by heyitsbench** [comment]
> Lmao yeah. Wtf was I on

Clearly not .SQL. 🙂

**Comment by elthehablo** [comment]
> > Lmao yeah. Wtf was I on
> 
> Clearly not .SQL. 🙂

image

**Comment by Gultask** [comment]
Actually, no, there is an issue with this. Triggered flags don't take range into question. So this will make them cast from infinite range. This is likely the wrong spell ID.

**Comment by elthehablo** [comment]
Could you investigate please?

**Comment by heyitsbench** [comment]
Would it be possible to find a video of this spell being cast by this NPC? Tried to get a sniff of it on Classic but they would not cast it no matter what I did.

**Comment by elthehablo** [comment]
Very likely then that this ability may not exist? It should be cast quite regularly if you face your back towards them

**Comment by Vyperhand** [comment]
> Would it be possible to find a video of this spell being cast by this NPC? Tried to get a sniff of it on Classic but they would not cast it no matter what I did.

Can't find a video yet, but one of the top comments on wowhead references it.
https://www.wowhead.com/wotlk/npc=94/defias-cutpurse#comments

**Comment by elthehablo** [comment]
> > Would it be possible to find a video of this spell being cast by this NPC? Tried to get a sniff of it on Classic but they would not cast it no matter what I did.
> 
> Can't find a video yet, but one of the top comments on wowhead references it. https://www.wowhead.com/wotlk/npc=94/defias-cutpurse#comments
> 
> with the age of that comment, this could be one of the things that didn't get re-solved in Classic, perhaps? Or otherwise perhaps a victim of the starting zone nerfs?
> 
> might check vanilla classic to see if the behavior is any different for a sniff.

Please do. But yeah could be a vanilla thing that didn't get added to classic.

**Comment by heyitsbench** [comment]
Checked on the Classic Era PTR, the backstab ID is correct (53) and happens very often and very easily. Still does not happen on Wrath Classic however, I suspect removed with starting zone nerfs.

**Comment by elthehablo** [comment]
I vote keep it. Merge merge merge. Zugzug.

**Comment by Vyperhand** [comment]
> Checked on the Classic Era PTR, the backstab ID is correct (53) and happens very often and very easily. Still does not happen on Wrath Classic however, I suspect removed with starting zone nerfs.

That sounds pretty darn deliberate to me, if it's present in vanilla classic and gone by wrath classic.  I can't imagine they un-solved it moving classic forward.

**Comment by ZhengPeiRu21** [comment]
Based on Bench's comparison with Classic, I agree that this skill probably was removed as part of the starting zone nerfs, similar to the Defias Pillager's fireball spell being changed to a weaker one, so not having it is correct WotLK behavior. (Although it could be something else, like an unintentional bug by Blizzard at the time or just making it much less common.)

If you don't mind, though, I will include your fix in Individual Progression as part of "un-nerfing" the Vanilla world.

**Comment by elthehablo** [comment]
> Based on Bench's comparison with Classic, I agree that this skill probably was removed as part of the starting zone nerfs, similar to the Defias Pillager's fireball spell being changed to a weaker one, so not having it is correct WotLK behavior. (Although it could be something else, like an unintentional bug by Blizzard at the time or just making it much less common.)
> 
> If you don't mind, though, I will include your fix in Individual Progression as part of "un-nerfing" the Vanilla world.

By all means!

**Comment by elthehablo** [comment]
Closing this PR then as well as the issue.

**Pull request closed without merging**
