### PR TITLE
refactor(Core/AI): Some more refactoring prep for Comat Threat system…

### PR DESCRIPTION
**Pull request by Kitzunu**
… rewrite.  CreatureAI::EnterCombat is now called CreatureAI::JustEngagedWith. There's  also two new methods on UnitAI, though they're never invoked right now.

* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/6113b9dec2e0081c36c36c2974a28ed0693bc601)

Co-Authored-By: Treeston <14020072+Treeston@users.noreply.github.com>

## Changes Proposed:
-  CreatureAI::EnterCombat is now called CreatureAI::JustEngagedWith. There's  also two new methods on UnitAI, though they're never invoked right now.
-  

## Issues Addressed:

- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/5985 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
*dogygen*? 👯

**Comment by Kitzunu** [comment]
*Angry Doxygen noises*

**Comment by pklloveyou** [comment]
Why do we always imitate TC？

**Comment by Kitzunu** [comment]
Because the system they have is better than ours.

Why invent something new, when it already exists.

**Comment by Kitzunu** [comment]
Eluna shit https://github.com/azerothcore/mod-eluna/pull/97

**Comment by acidmanifesto** [comment]
> Eluna shit [azerothcore/mod-eluna#97](https://github.com/azerothcore/mod-eluna/pull/97)

L-UwU-A *

**Pull request merged**
