### PR TITLE
fix(DB/creature_template): Vanilla Creature Speed corrections (Credit VMangos)

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Correct walk and run speeds from Vmangos sniffs
-  Some based on display ID, some based on creature ID
- Co-authored by: [ratkosrb](https://github.com/vmangos/core/commits?author=ratkosrb)

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Vmangos: https://github.com/vmangos/core/commit/3ae76673e15409e8d0e6f5b635eaf761aa9ef193

## Tests Performed:

- Spot checked fixes, looks correct and matches other NPC with same model

## How to Test the Changes:

1. Go to any NPC affected by change, observe movement speed

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ZhengPeiRu21** [comment]
I used modelid1 as equivalent to Vmangos creature_display_info_addon because AzerothCore does not have an equivalent table to pair movement speed with model id that I know. Please let me know if there is better way to map this.

**Comment by acidmanifesto** [comment]
@ZhengPeiRu21 I dropped the PR link into the staff room for discussion. Hopefully some feedback is provided

**Comment by acidmanifesto** [comment]
At the moment, where it stands. We need to know if these values were changed at any point from vanilla to wotlk. Are you able to provide any supporting references for this change? Although i am 100% confident it is correct for vanilla, we are uncertain if there was any adjustments when wotlk was retail.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
At the moment, where it stands. We need to know if these values were changed at any point from vanilla to wotlk. Are you able to provide any supporting references for this change? Although i am 100% confident it is correct for vanilla, we are uncertain if there was any adjustments when wotlk was retail.

**Comment by ZhengPeiRu21** [comment]
> At the moment, where it stands. We need to know if these values were changed at any point from vanilla to wotlk. Are you able to provide any supporting references for this change? Although i am 100% confident it is correct for vanilla, we are uncertain if there was any adjustments when wotlk was retail.

Sorry, like I am respond on the other related PR, I only have VMangos as a source for this, though I would be surprising that Blizzard would change them from Vanilla. Like the other PR, perhaps we can leave this as an useful reference for WotLK sniff data, or if it is not helpful then please feel free to close it.

**Comment by ZhengPeiRu21** [comment]
With WotLK classic now available to cross-check, we should be able to investigate and confirm that these values are correct.

**Comment by acidmanifesto** [comment]
> With WotLK classic now available to cross-check, we should be able to investigate and confirm that these values are correct.

Performing comparison now

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Comparison with several available resources and individuals message with in other core sniff teams, it is determined creatures from vanilla wow speeds were not changed and stayed presisted thru out the expansions.

**Comment by acidmanifesto** [comment]
Thank you for your PR

**Pull request merged**
