### PR TITLE
fix(DB/spell): Adjust Intercept and Charge attrs

### LINKED ISSUE #6400: Warrior - Intercept damage & stun can be dodged
Original report: https://github.com/chromiecraft/chromiecraft/issues/864

Can confirm, if the target dodges the caster still charges towards it, but no damage is done and the target doesn't get stunned. Tested dodge only but I assume parrying and blocking works the same way. Same applies to the Charge spell.

 intercept getting dodged/parried and target doesn't get stunned anymore

#### WHAT CLIENT DO YOU PLAY ON?

- [x] enUS

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:
 https://wotlk.evowow.com/spell=20252

intercept sometimes gets dodged/parried in pvp. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

intercept should not be dodged/parried or blocked by players or mobs, because it is **NOT** a melee attack.

##### STEPS TO REPRODUCE THE PROBLEM:

1. intercept an enemy player multiple times, sometimes they will dodge/parry as shown in the screenshot

##### EXTRA NOTES:

I haven't noticed dodges on charge yet, but will update it if I do
Screenshot_21
Screenshot_5

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99325156-warrior-intercept-damage-stun-can-be-dodged?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anguaive**
Intercept and Charge stun and damage effects were dodgeable.

The attributes of Intercept (damage & stun) (id: 20253) and Charge
(stun) (id: 7922) have been adjusted to include a flag that makes
these effects impossible to dodge, parry and block.

## Changes Proposed:
- add SPELL_ATTR0_IMPOSSIBLE_DODGE_PARRY_BLOCK flag to the aforementioned spells
(it's called IMPOSSIBLE_DODGE_PARRY_BLOCK in the docs (https://wowdev.wiki/Spell.dbc/Attributes) and NO_ACTIVE_DEFENSE internally)

## Issues Addressed:

- Closes #6400
- Closes chromiecraft/chromiecraft#864

## SOURCE:

Refer to chromiecraft/chromiecraft#864

## Tests Performed:

- Sql applies cleanly
- Tested in-game. Testing one of three cases (dodge/parry/block) should be sufficient because they're all covered by the flag (look for `SPELL_ATTR0_NO_ACTIVE_DEFENSE` in `Unit.cpp` if you want to make sure)

## How to Test the Changes:

I'm sure there's a less cumbersome way of testing this. I used the following steps:
1. Buff the Greater Agility elixir to grant 2000 (+1) agility. Use the included statement: https://pastebin.com/zQt9Y334
2. Create a level 40-ish character, drink elixir which will increase dodge to 80-ish %
3. Create a level 40-ish character of the opposite faction, `.learn` Charge, Bloodrage, Intercept (100, 2687, 20252)
4. Set pvp on on both characters
5. Intercept the high dodge character a couple times, make sure the yellow damage never gets dodged and the target gets stunned
6. Charge the high dodge character a couple times, make sure the target always get stunned

Use Bloodrage to generate rage for Intercept, use `.cheat cooldown` to save time, use a `.gm on .gm off` macro to get out of combat inbetween Charge casts.

Note that after getting stunned three times in quick succession, targets gain stun immunity for a short period. This means that Intercepted targets do not get stunned (but they still take damage), and Charged targets will be "Immune" to the stun.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Goatform** [comment]
Why SQL when you can do it in C++ ? It's far easier to maintain it.

**Comment by Kitzunu** [comment]
What ancient tool do you use to get the name SPELL_ATTR0_IMPOSSIBLE_DODGE_PARRY_BLOCK instead of SPELL_ATTR0_NO_ACTIVE_DEFENSE o.o

**Comment by laasker** [comment]
Adding SPELL_ATTR0_IMPOSSIBLE_DODGE_PARRY_BLOCK on charge and intercept may cause a bug that makes the stun ignore deterrence i think

**Comment by anguaive** [comment]
@Goatform I thought about it. 

1. Making two separate (INSERT and UPDATE) statements for the DBC entry and the changes you're applying to it is equally as readable/maintainable as the equivalent ApplySpellFix solution IMHO. Only downside is the ugly INSERT, which you only have to include it if there's no existing entry for the spell yet, but if you do the updates as a separate statement then you don't have to touch it ever again. 
2. Spells are treated as data and data belongs in a database

@Kitzunu it's from https://wowdev.wiki/DB/Spell#3.3.5.12340, but if you can point me to more up-to-date docs, feel free to do so :P

@laasker Thanks for the heads up, I will look into it

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Goatform** [comment]
I don't see how it's maintainable when you have +10 columns that a person might not know what they are about since they are hard to track etc.

Yes, you made it more readable but it is still ugly af in my opinion. Why make things hard when you can write simple 3 lines of code to make it work or something like that... Still, it's up to AC devs to decide what to do but if you ask me it is just not the way to do it.

**Comment by FrancescoBorzi** [comment]
@Goatform check the new Keira3 release with the spell-dbc editor:

image

**Comment by ErnestoGonzalezC** [comment]
> Adding SPELL_ATTR0_IMPOSSIBLE_DODGE_PARRY_BLOCK on charge and intercept may cause a bug that makes the stun ignore deterrence i think

You're right, I don't know why your comment was ignored.

**Comment by Kitzunu** [comment]
@FrancescoBorzi

**Comment by FrancescoBorzi** [comment]
sorry I did not understand that it was a bug caused by this PR. So we need to either revert the faulty part or fix the issue

**Pull request merged**
