### PR TITLE
fix(Scripts/BlackwingLair): Razorgore The Untamed misc improvements.

### LINKED ISSUE #10151: [BWL] Razorgore issues
CURRENT BEHAVIOUR:

Using orb without aggroing boss :"target is not in line of sight" and in combat, nothing happening 
Yells from boss it self when you destroy eggs doesn't appear
Adds do not despawn once you finish / restart fight
Channeled beam must be sorted, since there is not timer (U can keep boss forever)
You dont get debuff when u stop casting channel
Exit btn doesn't work as well
Boss doesnt enter phase 2

EXPECTED BLIZZLIKE BEHAVIOUR:

Orb should have no los issues
Boss should yell when eyes break
adds should despawn when fight wipes, and flee when all eggs are destroyed
Channeled beam should have a 90s casttime
debuff should be appleid after, for 60 seconds
Being able to stop the channel (possibly?)
enter gate should close (?)
when all eggs are destroyed, boss should enter phase 2

SOURCE:

https://classic.wowhead.com/guides/razorgore-the-untamed-blackwing-lair-strategy

STEPS TO REPRODUCE THE PROBLEM:
Go to bwl first boss

NOTES

https://github.com/azerothcore/azerothcore-wotlk/issues/5054

AC HASH/COMMIT:
0c35369
OPERATING SYSTEM:
Windows 11
MODULES:
mod-progression-system
CUSTOMIZATIONS:

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #10151

 

## Issues Addressed:

- Closes #10151

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/10151)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by temperrr** [comment]
I will test this on the PTR with a full group, please stand by.

**Comment by temperrr** [comment]
Tested with a raid group, we got the following input:

When wipe on razorgore, razorgore should not fight the adds, but it should reset, this also causes the mini boss + adds at orb to not respawn sometimes.
Warlocks and Taskmaskers should not spawn during razorgore fight
You can sleep razorgore with his sleep ability
He managed to bug out during phase 1, acting as if he was in phase 2 already ( still some eggs not broken, mc still worked, no adds spawning)
When phase 2 starts, mind control should be automatically stopped.

**Comment by UltraNix** [comment]
@temperrr Updated.

**Comment by temperrr** [comment]
Just curious, can´t really read the code, but what is the maximum number of enemies spawned during this encounter?

Guides talk about a maximum of 52, 12 dragonkin, they all should go for the mind controller. They should keep spawning till either group is dead, or all eggs are destroyed and he goes in p2. I can´t find that in the code, but I may miss this.

**Comment by UltraNix** [comment]
@temperrr 15 eggs destroyed.

**Comment by acidmanifesto** [comment]
image

**Comment by Kitzunu** [comment]
Conflict

**Comment by UltraNix** [comment]
@Kitzunu Done.

**Pull request merged**
