### PR TITLE
fix(DB/SAI): Fixes starting waypoint movement during "I Sense a Distu…

### LINKED ISSUE #11857: [quest] `I Sense a Disturbance` quest bug
### Current Behaviour

get `I Sense a Disturbance` quest(quest id 12665) ,talk `Har'koa`(creature id 28401 ),`Har'koa's Kitten` won't run with players

### Expected Blizzlike Behaviour

`Har'koa's Kitten` will run with players

### Source

https://www.youtube.com/watch?v=SO_IcD9bWeI

### Steps to reproduce the problem

1. `.quest 12665`
2. `.go c id 28401`
3. talk ``Har'koa`

### Extra Notes

_No response_

### AC rev. hash/commit

324112ff4fcb52416dea7444c9c80a7781b57ebf

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…rbance" quest.

Fixes #11857

## Issues Addressed:

- Closes #11857

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.quest 12665`
`.go c 118591`
talk ``Har'koa`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
@UltraNix  When the task was completed, `har'koa's kitten 'didn't send the player back to' har'koa '

**Comment by mpfans** [comment]
https://www.youtube.com/watch?v=SO_IcD9bWeI

**Comment by UltraNix** [comment]
@mpfans Check again.

**Comment by mpfans** [comment]
work now ... tyvm

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
