### PR TITLE
fix(Core): Missing updates for creatures; disable Travis modules check

### LINKED ISSUE #2390: [World] Bugged creature movement/engaging in combat
##### SMALL DESCRIPTION:

When mobs are engaging in combat, NPC or NPCs getting stuck and you can't normally fight them.
Can't properly describe it, so i made a video.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC movement and combat engaging should work properly

##### CURRENT BEHAVIOUR:

[Video link](https://youtu.be/JqUSK9Sg33g)

##### STEPS TO REPRODUCE THE PROBLEM:

1. Watch the [video](https://youtu.be/JqUSK9Sg33g) :)

P.S. I CAN'T REPRODUCE THIS BUG at 100% of the times, and mostly where it happens is an Outland, so, maybe this bug is related to MMaps or VMaps

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

d9986c0

##### OPERATING SYSTEM:

Win 10 LTSC 1903

##### MODULES:

AutoBalance

##### OTHER CUSTOMIZATIONS:

No.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/82716227-world-bugged-creature-movement-engaging-in-combat?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2399: Core/Pet - Player pets have stopped following them a few times
**Description:**

Players' pet is buggy

**Current Behavior:**

After some testing I found that the pet's of players of all classes at certain times stop moving as follows in the video below:

https://www.youtube.com/watch?v=XBJ0_tDMyV0&feature=youtu.be

But this bug does not happen every time, I tested on a server with clean database and did not reproduce the problem.

I tested it on a live server and the error happens.

**Expected Behavior:** Pet's Must Follow Players

**Steps to reproduce the problem:** Player pets must follow them

of the mission
Branch (s): Master

Hash / CA Confirmation: https://github.com/azerothcore/azerothcore-wotlk/commit/8a3a7295a40de873ba5c59d50ace5fb4b9f429ea

Operating System: Windows Server 2008 R2

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83079772-core-pet-player-pets-have-stopped-following-them-a-few-times?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
This PR fixes a problem introduced with PR #2304. Sadly I had a logic error in there: Cells visited only for large creatures were also marked as visited for all creatures, which is wrong because it prevents updates for those creatures. With this PR cells are marked as visited for large and normal creatures separately which ensures that each creature is updated.

Sadly I did not see this error in the first place as it only shows while playing with multiple players.

This PR will also temporarily disable the Travis modules check in order to allow correct Travis runs once more. This will be reverted after PR #2454 has been merged and the modules have been fixed.

##### ISSUES ADDRESSED:
- Closes #2390
- Closes #2399

##### TESTS PERFORMED:
- Tested build on Ubuntu 16.04 x64 / cmake 3.15.5 / clang 7.1.0 / MySQL 5.7
- Tested successfully in-game

##### HOW TO TEST THE CHANGES:
Without this PR:
- Create 2 hunters on separate accounts, put their pets in "defensive" mode
- `.go 7343.97 -896.434 915.94 571`
- Attack one of the rhinos there with the pet of the first hunter
- Attack the same rhino with the pet of the second hunter
- Run away with the second hunter, constantly attacking the rhino with the pet, so it keeps following
- One of the pets will stop getting updates, which means it "hangs" or "lags", unresponsive to the player's commands

With this PR the pets should just behave normally.

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by solidmaxtor** [comment]
Test all is good now, pet/npc not have more problems. Great job!

**Comment by BarbzYHOOL** [comment]
@markvetwow did you test the PR or do you approve the code (as a developer) ?

**Comment by markvetwow** [comment]
@BarbzYHOOL I'm testing this PR for 3 days now, didn't encountered any issues with NPCs in open world. Yet. :)

**Comment by BarbzYHOOL** [comment]
@markvetwow ok nice !! next time if you test a PR, please, put a small comment, "approving" is usually for developers (who don't test the PR ingame :P)

**Comment by diluh** [comment]
Testing and everything is working fine!

**Comment by Stoabrogga** [comment]
Someone mentioned on Discord that the DK quest "Death Comes From On High" does not work anymore with this PR applied. I have to look into this tomorrow.

**Comment by Stoabrogga** [comment]
I think I know what could cause a problem with this quest, will test tomorrow and then update the PR.

**Comment by smansesdottk** [comment]
> Someone mentioned on Discord that the DK quest "Death Comes From On High" does not work anymore with this PR applied. I have to look into this tomorrow.

I confirm this, player report cannot complete that quest anymore

**Comment by Stoabrogga** [comment]
Pushed another commit. Large WorldType objects also have to be updated, not just GridType objects. Sorry for not seeing this. The quest is now working, tested it on my own server.

**Comment by smansesdottk** [comment]
After testing, the PR works as expected

**Comment by Maxximus1** [comment]
Tested for 48 hours without problems, PR works correctly

**Comment by Stoabrogga** [comment]
Merged as this is fixing a rather critical bug. I also included a change to the Travis configuration file in order to disable the modules check which is causing all Travis runs for the core repository to fail. This has to be reverted later.

Thanks all for testing this :+1:

**Pull request merged**
