### PR TITLE
chore(DB/Quest): Fix typo in quest reward offer text for ID 9145

### PR DESCRIPTION
**Pull request by v-mstrs**
## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16685

## SOURCE:

https://www.wowhead.com/wotlk/quest=9145/help-ranger-valanna + grammar
## Tests Performed:

-  Tested, works

## How to Test the Changes:

1. Horde char
2. .npc add 9145
3. .go xyz 7932.62 -7573.54 145.5 530

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Review by Gultask — CHANGES_REQUESTED** [review]
needs sniff

**Comment by v-mstrs** [comment]
https://youtu.be/a4a7GDPVTJw?t=155

**Comment by Gultask** [comment]
```
QuestGiverCreatureID: 16219
QuestID: 9145
[0] QuestFlags: 8
[1] QuestFlags: 0
[2] QuestFlags: 0
SuggestedPartyMembers: 0
EmotesCount: 1
Type: 1
Delay: 0
AutoLaunched: True
Unused: False
(QuestRewards) ChoiceItemCount: 0
(QuestRewards) ItemCount: 0
(QuestRewards) [0] ID: 0
(QuestRewards) [0] Quantity: 0
(QuestRewards) [1] ID: 0
(QuestRewards) [1] Quantity: 0
(QuestRewards) [2] ID: 0
(QuestRewards) [2] Quantity: 0
(QuestRewards) [3] ID: 0
(QuestRewards) [3] Quantity: 0
(QuestRewards) RewardMoney: 0
(QuestRewards) XP: 800
(QuestRewards) ArtifactXP: 0
(QuestRewards) ArtifactCategoryID: 0
(QuestRewards) Honor: 0
(QuestRewards) Title: 0
(QuestRewards) FactionFlags: 0
(QuestRewards) [0] FactionID: 0
(QuestRewards) [0] FactionValue: 0
(QuestRewards) [0] FactionOverride: 0
(QuestRewards) [0] FactionCapIn: 7
(QuestRewards) [1] FactionID: 0
(QuestRewards) [1] FactionValue: 0
(QuestRewards) [1] FactionOverride: 0
(QuestRewards) [1] FactionCapIn: 7
(QuestRewards) [2] FactionID: 0
(QuestRewards) [2] FactionValue: 0
(QuestRewards) [2] FactionOverride: 0
(QuestRewards) [2] FactionCapIn: 7
(QuestRewards) [3] FactionID: 0
(QuestRewards) [3] FactionValue: 0
(QuestRewards) [3] FactionOverride: 0
(QuestRewards) [3] FactionCapIn: 7
(QuestRewards) [4] FactionID: 0
(QuestRewards) [4] FactionValue: 0
(QuestRewards) [4] FactionOverride: 0
(QuestRewards) [4] FactionCapIn: 7
(QuestRewards) [0] SpellCompletionDisplayID: 0
(QuestRewards) [1] SpellCompletionDisplayID: 0
(QuestRewards) [2] SpellCompletionDisplayID: 0
(QuestRewards) SpellCompletionID: 0
(QuestRewards) [0] CurrencyID: 0
(QuestRewards) [0] CurrencyQty: 0
(QuestRewards) [1] CurrencyID: 0
(QuestRewards) [1] CurrencyQty: 0
(QuestRewards) [2] CurrencyID: 0
(QuestRewards) [2] CurrencyQty: 0
(QuestRewards) [3] CurrencyID: 0
(QuestRewards) [3] CurrencyQty: 0
(QuestRewards) SkillLineID: 0
(QuestRewards) NumSkillUps: 0
(QuestRewards) TreasurePickerID: 0
(QuestRewards) (ItemChoiceData) [0] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [0] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [0] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [0] Quantity: 0
(QuestRewards) (ItemChoiceData) [1] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [1] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [1] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [1] Quantity: 0
(QuestRewards) (ItemChoiceData) [2] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [2] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [2] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [2] Quantity: 0
(QuestRewards) (ItemChoiceData) [3] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [3] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [3] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [3] Quantity: 0
(QuestRewards) (ItemChoiceData) [4] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [4] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [4] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [4] Quantity: 0
(QuestRewards) (ItemChoiceData) [5] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [5] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [5] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [5] Quantity: 0
(QuestRewards) IsBoostSpell: False
QuestPackageID: 0
PortraitGiver: 0
PortraitGiverMount: 0
PortraitGiverModelSceneID: 0
PortraitTurnIn: 0
QuestGiverCreatureID: 16219
QuestTitle: Help Ranger Valanna!
RewardText: Good to hear that Lethvalin made it to safety, and that he was smart enough to ask you for help instead of just waiting there.$B$BI hope that Ranger Salissa made it safely to Farstrider Enclave.
PortraitGiverText: 
PortraitGiverName: 
PortraitTurnInText: 
PortraitTurnInName: 
```

**Comment by Gultask** [comment]
So it was only a comma, then?

**Review by Gultask — APPROVED** [review]

**Pull request merged**
