### PR TITLE
fix(Core/Command): cheat explore

### PR DESCRIPTION
**Pull request by Kitzunu**
## CHANGES PROPOSED:
-  move from cs_misc to cs_cheat
- fix removing flag
- fix usability when targeting a player

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1524

## TESTS PERFORMED:
- Builds
- Tested in-game

## HOW TO TEST THE CHANGES:

1. .cheat explore 1

## KNOWN ISSUES AND TODO LIST:

- [x] `.cheat explore 0` does not remove the explored
- [x] The command does not change flag on the targeted player

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
Okay, so I have tested this script and it works for everything it should.

You can:
- Change flag 1/0 on you
- Change flag 1/0 on target
- Error if trying to cast on npc
- Removing flag works properly

THE CODE IS NOT PRETTY! I know, but this was my first EVER C++ that I made myself with some help from Kito in Discord. Feedback is accepted :D

**Comment by h0lysp4nk** [comment]
@Kitzunu 

Looks good to me :)

**Comment by Kitzunu** [comment]
Ty everyone

**Comment by BarbzYHOOL** [comment]
nice work

**Pull request merged**
