### PR TITLE
fix(app/db_assembler): Allow recursion with bash

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
## CHANGES PROPOSED:
- Add bash 4.x+ recursion (this bash is available for years so it should be NP, also it makes use of the recursion Yehonal wrote in the bash script, no need to use `find` command for that)

## ISSUES ADDRESSED:
- Closes 

- Before that commit, the recursion with "**" stopped after the first directory

## TESTS PERFORMED:
- works fine :)

## HOW TO TEST THE CHANGES:

Seriously no need to test, I just made it to fix the issue right now, but just in case:

- Go in `data/sql/custom/db_world`
- Make a directory and its subdir like `test/test2` and put sql files inside
- Try to merge them with the db_assembler.sh (use the option 4 for custom SQL files)

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
@Yehonal i don't understand the travis error

**Comment by Yehonal** [comment]
Nice job!

about the error, uhm, have you tested it locally?

**Comment by Helias** [comment]
> wtf now it says the check have been passed

I restarted the failed build, so now it passed.

**Comment by BarbzYHOOL** [comment]
> > wtf now it says the check have been passed
> 
> I restarted the failed build, so now it passed.

I knew someone did it sneakily xD

Ok so we need to remember that sometimes, travis fucks up! He's just a human after all

**Comment by BarbzYHOOL** [comment]
TODO: might want to exclude some dirs called "WIP" "TODO" "OBSOLETE" or stuff like that

**Pull request merged**
