### PR TITLE
fix(Core): increase visibility distance of large game objects

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Based on this TC commit: https://github.com/TrinityCore/TrinityCore/commit/d1c3ee957962897a8b323e8ca40302fc5ff8c932

I only took over code parts concerning the visibility distance of large game objects as the visibility calculation of AC seems to be quite different from TC.
- large game objects will be handled like active objects:
 visibility distance is set to MAX_VISIBILITY_DISTANCE (250.0f)
- the logic concerning Wintergrasp visibility calculation is not touched
- I tried to keep the code changes to a minimum

It looks much better to see large game objects from far away in my opinion, e.g. the demon portals in Hellfire Peninsula:
before:
WoWScrnShot_043019_103403
after:
WoWScrnShot_043019_103700

###### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested build (Ubuntu 16.04, Clang 7) and in-game

##### HOW TO TEST THE CHANGES:
- GAMEOBJECT_TYPE_BUTTON (1):
 ```.go object 27370``` (Night Elf Moon Crystal)
- GAMEOBJECT_TYPE_QUESTGIVER (2):
 ```.go object 59875``` (Elder Atkanok)
- GAMEOBJECT_TYPE_GENERIC (5):
 ```.go object 24222``` (Gateway Murketh)
- GAMEOBJECT_TYPE_TRAP (6):
 ```.go object 57161``` (Kvaldir Inferno)
- GAMEOBJECT_TYPE_SPELL_FOCUS (8):
 ```.go object 62204``` (Ymirheim Peak Skulls)
- GAMEOBJECT_TYPE_GOOBER (10):
 ```.go object 25256``` (Portal Grimh)
- GAMEOBJECT_TYPE_SPELLCASTER (22):
 ```.gobject add temp 192819``` (Defender's Portal)
- GAMEOBJECT_TYPE_CAPTURE_POINT (29):
 ```.gobject add temp 184380``` (Visual Banner (Horde))

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Ok, thanks, I'll label this PR as waiting to be tested then.

**Comment by poszer** [comment]
| OS: Windows| Description |
| --- | --- |
| Build | Build: 5 succeeded, 0 failed, 9 up-to-date, 2 skipped  |
| Tested in game | Players are able to see large game objects from far away |

Some images:
Screenshot_7
Screenshot_6
beforeVISIBLE
afterDISTANCE

For me, looks great. Better than before, and ready for merge. Thank you @Stoabrogga

**Comment by Stoabrogga** [comment]
Great, thanks for testing this @poszer !

**Comment by Stoabrogga** [comment]
Merged. Thanks for looking into this @Pondaveia & @poszer !

**Pull request merged**
