### PR TITLE
fix(DB/Gameobjects): Fixed rotations of some plaques in Royal Gallery…

### LINKED ISSUE #7675: Missing plaques in the Royal Gallery of Stormind Keep
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1597

In the Royal Gallery of Stormwind Keep each statue of the Alliance Heroes should have its own plaque to click and read. But only 2 of them are available and one of them is rotated and facing backwards. I know this is the most minor bug you can find but it is a bug nonetheless.

Testers note:
The current config can be seen here
image
It seems that the plaques exist, but are in the wrong position/rotation. The GUIDs can be seen in the above image.

### Expected Blizzlike Behaviour

Each statue should have its own usable (readable) plaque and facing correctly.

Testers note:
As seen in [wowpedia](https://wowpedia.fandom.com/wiki/Royal_Gallery?oldid=869948&file=Royal_Gallery.jpg) there should be atleast 3 plagues, they should also be flat. 
image

Additional information curtesy of @VFaleiro
I think only 3 statues are labeled
[Lady Mara Fordragon](https://wowpedia.fandom.com/wiki/Lady_Mara_Fordragon?direction=prev&oldid=2776151)
`unlabeled statues identical to those of Archmage Khadgar and Ranger Captain Alleria Windrunner are also present`
Also, the description of Mara Fordragon's statue is also there.

By the way, I've found the following objects on Wowhead
[Mara's plaque](https://tbc.wowhead.com/object=177202)
[Daelin's plaque](https://tbc.wowhead.com/object=177201)
[Llane's plaque](https://tbc.wowhead.com/object=177200)

### Source

_No response_

### Steps to reproduce the problem
 - .go xyz -8407.997 481.78 123.76 (Can't get it to tele to the room)
 - Move to trophy room

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d20f315bd5370761f226460964ae506a97f372c0

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
… in Stormwind City.

Fixes #7675

## Issues Addressed:

- Closes #7675
- Closes https://github.com/chromiecraft/chromiecraft/issues/1597

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. `.go xyz -8407.997 481.78 123.76` (Can't get it to tele to the room)
2. Move to trophy room

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Asthalor** [comment]
Tested, the Lady Mara and the King llane are perfect, but i couldnt find the one on the right. That one is https://tbc.wowhead.com/object=177201/grand-admiral-daelin-proudmoore

image

**Comment by UltraNix** [comment]
@Asthalor Check now.

**Comment by Asthalor** [comment]
Tested. All good now! 

image

**Comment by FrancescoBorzi** [comment]
> Tested. All good now!

thanks for testing this, don't forget to remove [Waiting to be tested] and apply [To Be Merged]

**Pull request merged**
