### PR TITLE
fix(DB/ZulGurub): Remove taunt immunity from Mar'li

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Remove extra_flags from Mar'li

## Issues Addressed:

- Closes -

## Tests Performed:

- SQL Ran, should work...

## How to Test the Changes:

1. Go to Mar'li and try to taunt, you should be able to taunt her.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Gultask** [comment]
I don't know about Mar'li but Gri'lek should be immune to Taunt, I think.

**Comment by Nefertumm** [comment]
There, lets only change Mar'li for now

**Comment by Gultask** [comment]
Works. I'll see what I can find of Gri'lek. If he's immune only during Avatar I'll open another issue.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
