### PR TITLE
refactor(Core/Misc): replace ace network to boost asio

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
# TODO
- [x] Correct CI
- [x] Test with 1-5 players
- [ ] Test with 10+ players
- [ ] Test with 50+ players
- [x] https://github.com/azerothcore/mod-ah-bot/pull/37

## Changes Proposed:
- Replace `ace` network to `boost::asio`

## Issues Addressed:
- Part #3451 

## Tests Performed:
-
image

## How to Test the Changes:
- Need test all core with players (don't need to test anything in particular, you need to test the basic actions of the players)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
nice

**Comment by Kitzunu** [comment]
I believe this will close https://github.com/azerothcore/azerothcore-wotlk/issues/2735 too?

**Comment by Winfidonarleyan** [comment]
> I believe this will close #2735 too?

Maybe, need test

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers someone please test this

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan the build is failing

**Comment by Winfidonarleyan** [comment]
Update to f1727b79d251ec28775796a45cfb669b1c346b66
image

**Comment by Winfidonarleyan** [comment]
Okay, can test without module `mod-ah-bot`

**Comment by Kitzunu** [comment]
@azerothcore/testers

**Comment by Sedatyf** [comment]
Tested with 3 different players and 5 accounts:
- We learned fly path and took fly ✔️ 
- We rolled on stuff ✔️ 
- We dueled ✔️ 
- We did some dungeons ✔️ 
- We split our party in two and we did two dungeons simultaneously ✔️ 
- We tagged in RDF ✔️ and we had our satchel ✔️ 
- We learned our spells ✔️ 
- We did some auctions (we auctioned items, someone else bought it and received payment) ✔️ 
- We did a guild and we were able to do all guild bank actions (withdraw money, items, deposit money, items, ect) ✔️ 
- We did a raid and no errors came up but we could rand on every loot even if we couldn't equip them (we were in group loot) so I don't know if it's related or not but I don't think so ❓ 
- We sent each others mail ✔️ 
- We took zeppelin ✔️ 
- We tagged in Warsong Gulch ✔️ 

We played like one hour and server didn't crash

**Comment by Azcobu** [comment]
Just had a go at testing this and didn't run into any issues at all. Tried to do a range of typical player activities - open world questing, a dungeon, a raid, and things like learning/unlearning professions, weapon and class skills, adding/removing glyphs/gems/enchants on gear, summoning/desummoning pets and mounts, resetting talents and adding dual spec, training pets, and some light gathering, crafting and fishing. All fine, no error messages in server log (beyond those I caused myself by messing with skills.)

**Comment by Sedatyf** [comment]
Thanks @Azcobu for those tests !

**Comment by FrancescoBorzi** [comment]
excellent job @Sedatyf and @Azcobu 

> Okay, can test without module `mod-ah-bot`

@Winfidonarleyan please prepare PRs to fix modules as well

**Comment by FrancescoBorzi** [comment]
@pklloveyou @mpfans @Footman @disclosurez  any chance you can test this with players?

**Comment by Winfidonarleyan** [comment]
Added https://github.com/azerothcore/mod-ah-bot/pull/37

**Comment by FrancescoBorzi** [comment]
I think we are ready to merge this

**Comment by FrancescoBorzi** [comment]
@mpfans will test this next week with players

**Comment by FrancescoBorzi** [comment]
@pklloveyou any chance you can also test this with players?

**Comment by Kitzunu** [comment]
Conflicts

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan conflicts are easy to solve here. You need to apply the changes to `PlayerQuest.cpp` instead of `Player.cpp`

**Comment by Winfidonarleyan** [comment]
Ready

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by mpfans** [comment]
- [ ]  Test with 900+ players

**Comment by FrancescoBorzi** [comment]
> * [x]   Test with 900+ players
>   And several wintergrass battles,120VS120.
>   I think this PR can be merged

many thanks @mpfans ! very precious feedback

**Comment by Kitzunu** [comment]
Good works

**Pull request merged**
