### PR TITLE
refactor(Core/Creature): Reworked creature aggro radius calculation

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/980047763a685217e712f58b8713d48523d90ccb)

* Formulas are taken from WoW Wiki

Co-Authored-By: Ovah <18347559+Ovahlord@users.noreply.github.com>

## Changes Proposed:
-  Rework creature aggro radius calculations with formulas from WoW Wiki

## Tests Performed:

- builds

## How to Test the Changes:

1. Check general aggro radius of creatures above and below your level

for example
> The aggro radius for creatures with equal level as the player is 20 yards.

> WoW Wiki: the minimum radius seems to be 5 yards, while the maximum range is 45 yards

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by T1ti** [comment]
Does this override the new creature detection_range parameter we recently added in creature_template ?

**Comment by Kitzunu** [comment]
This fixes the general aggro radius calculations to be as blizzlike as we know.

I don't know where detection_range is used, but none of the removed code has any correlation with it

**Comment by T1ti** [comment]
Looks like another issue then if it's not used

**Comment by Kitzunu** [comment]
Do you know where detection_range is used? Because it wasn't in the previous code either for Creature::GetAttackDistance()

**Comment by Kitzunu** [comment]
Ah it is used in Creature::GetAggroRange()

**Comment by Kitzunu** [comment]
what is the use-case of detection_range

**Comment by Kitzunu** [comment]
I just found GetAggroRange and GetAttackDistance used very weirdly in AC. I need to investigate it. Because right now they are both a hot mess.

But what I want to know to make my life a tad bit easier is.

is detection_range a random guessed value, or is it a sniffed value?
Because in DB atm we have 1, 10, 18, 20.

**Comment by Kitzunu** [comment]
Ok so I have confirmed it is not sniffed, and on wowwiki it states 20yd.

So right know detection_range just looks like something made up to me with values someone took from the air

**Comment by T1ti** [comment]
> Ok so I have confirmed it is not sniffed, and on wowwiki it states 20yd.
> 
> So right know detection_range just looks like something made up to me with values someone took from the air

https://github.com/azerothcore/azerothcore-wotlk/issues/5455

wow wiki is wrong, the range isn't **_always_**  20, exceptions are rare but they exist

**Comment by Kitzunu** [comment]
Okay so basically a guessed value.

But now I know what I can work with.

**Comment by Kitzunu** [comment]
I really can't be bothered to look into this

**Pull request closed without merging**
