### PR TITLE
fix(DB/gameobject): GameObject Coordinate Fixes

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Update gameObject coordinates to data from WotLK Classic pre-patch sniffs
-  Co-authored by @CraftedRO

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13081

## SOURCE:

See original issue

## Tests Performed:

- See original issue

## How to Test the Changes:

1. See original issue

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Not quite correct 😛 
image

Also not all queries were needed:
`/* Affected rows: 1.922  Found rows: 0  Warnings: 0  Duration for 2.208 queries: 00:09:34.7 */`

**Comment by ZhengPeiRu21** [comment]
The signs from the original example look correct, but it seems some are wrong as Gultask showed. Thank you for testing so that we did not merge with bad data. ^_^ These will probably need individually checked through sniffs; I'm not sure if it is more good to leave this PR open as a reference to check or just close and we can fix individual objects as they are sniffed.

**Comment by CraftedRO** [comment]
If this is that signpost then on TC looks fine after import , probably AC does have even worst orientation values that TC:

Before:
WoWScrnShot_110422_135426


After :
WoWScrnShot_110422_141709

WoWScrnShot_110422_140502

**Comment by acidmanifesto** [comment]
Status?

**Comment by Maelthyrr** [comment]
As we need to improve our GO System and fix coordinates issues before, I will close this PR. Feel free to reopen it when everything will be fine.

**Pull request closed without merging**
