### PR TITLE
fix(Core/Movement) : Improved confused movement generator.

### LINKED ISSUE #5442: Broken vmaps?
## CURRENT BEHAVIOUR:

- During the tests that I carry out of the powers to make corrections I have noticed that there are several powers that make the characters sink to the ground, I guess this is a bug in the vmaps.
PD: I have tried with data extracted from my client and the official azerothcore.

## EXPECTED BLIZZLIKE BEHAVIOUR:

- The collision should work fine.

## STEPS TO REPRODUCE THE PROBLEM:

1. Watch the video.

https://user-images.githubusercontent.com/80600689/115984082-084f8180-a55a-11eb-9380-d7b4eb2f9939.mp4

https://user-images.githubusercontent.com/80600689/115984091-1f8e6f00-a55a-11eb-9892-cf8bb30e56c3.mp4

## AC HASH/COMMIT:
 765660b

## OPERATING SYSTEM:

- Windows 10 and Ubuntu 20.04

## MODULES:

- None.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98101623-broken-vmaps?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #5442.
Fixed https://github.com/chromiecraft/chromiecraft/issues/271

## Changes Proposed:
-  Improved confused movement generator by building path generator to specific destination.

## Issues Addressed:
- Closes #5442

## Tests Performed:

- Not tested ingame.

## How to Test the Changes:

More info #5442.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Yehonal — APPROVED** [review]

**Comment by Helias** [comment]
This PR has high priority, @sedatyf, if you can please test this :pray:

**Comment by Sedatyf** [comment]
No problem I'll test it when I can. Is this only for arena or should I check somewhere else?

**Comment by ErnestoGonzalezC** [comment]
Tested. Works correctly the only thing missing is the review of my friend @Sedatyf 😄

**Comment by Kitzunu** [comment]
Thanks

**Comment by Sedatyf** [comment]
If you tested it, there is no point to test it myself. Furthermore @Kitzunu merged it, so good job @UltraNix and @ErnestoGonzalezC  😄

**Pull request merged**
