### PR TITLE
fix(Scripts/BlackTemple): Fix Zerevor not casting Dampen Magic OOC

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19729
- Closes https://github.com/chromiecraft/chromiecraft/issues/7305

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by amed80** [comment]
Missing the recast each ~1mn during combat and the first one during combat can be earlier than 1mn depend on how long Dampen Magic was used before starting the fight.

**Comment by Nyeriah** [comment]
Addressed, check if I missed anything please.

**Comment by amed80** [comment]
For some reason (in combat) the time between each Dampen Magic is longer than 1mn (around 1mn and 30sec and sometimes go past 2mn)
If he have the Dampen Magic before the fight starts and it has less than 4mn , he doesn't instantly recast it.
Even if there is 30sec left on the buff before starting the fight , he doesn't rebuff himself with it , stealing the buff will give a short buff then it will fades away before Zerevor recast Dampen Magic again

**Comment by Nyeriah** [comment]
> If he have the Dampen Magic before the fight starts and it has less than 4mn , he doesn't instantly recast it.

> If you start the fight with Zeveros and 1mn already have passed from the previous cast of the buff , then Zeveros will immediately cast the buff again as soon the fight starts which can be seen in the second source from [TBC classic](https://youtu.be/MAjuy89WIbY) as there was ~3mn left on the buff and Zeveros buffed himself again with it as the fight started.

So he shouldt refresh it ?

**Comment by amed80** [comment]
If the buff has less than 4mn on it , he should instantly refresh it when the fight starts

**Comment by Nyeriah** [comment]
Script adjusted to comply with the above requests.

**Comment by amed80** [comment]
The recast of DM still not fully working correctly :
- If you start the fight with stealing the buff , Zerevor will cast his buff again : 
1- as soon he enter combat , If the buff has been up for more than 1mn out of combat (this is correct)
2- After 1mn from entering combat if the buff was casted under 1mn before the fight (he shouldn't wait 1mn during combat to cast his buff again)

- For some reason if you steal the buff in between 30-60? seconds from it when was casted , this will stops Zerevor from using the buff for the rest of the fight?

PS:
> 1- as soon he enter combat , If the buff has been up for more than 1mn out of combat (this is correct)

For the first DM that is casted , Zerevor will ignore this behavior as if you steal the buff as soon he cast it , he will cast it again instantly ignoring the 1mn timer , this is probably not a big problem as it's hard for normal players to reach him under 1mn from his first DM cast out of combat.

**Comment by Nyeriah** [comment]
> I guess , he have 2 checks one if he have the buff or not and the other how long was it the last time he used the buff , if first check is true and the second one get past +60sec , he recast the buff

I am having issues understanding what I am supposed to do here.

**Comment by amed80** [comment]
> > I guess , he have 2 checks one if he have the buff or not and the other how long was it the last time he used the buff , if first check is true and the second one get past +60sec , he recast the buff
> 
> I am having issues understanding what I am supposed to do here.

Zerevor should always check if he have the buff on him or not , if no then he will check when was the last time it was casted if it's past 1mn , he will reuse DM

This behavior i believe to be the same for both out of combat or in combat.

The only difference is as soon the fight start Zerevor seems to ignore his first check if he has the buff or not and only check if it was casted in the last 60sec (including the time out of combat) if it get past 60s than he will use it then after the first one , he goes back to normal checking if he has the buff if not then how long was it the last time he casted DM.

**Comment by Nyeriah** [comment]
The way this is scripted currently:

Zerevor will cast his buff:

**On pull**
- If the buff has 4 or less than 4 minutes duration.
- If he does not have the buff.

**During combat**
- Once the debuff is removed, it fires a 1 minute lock that prevents him from recasting it.
- He will recast it as soon as the timer is up.
- If the debuff expires on its own, without being dispelled or stolen, it will be recast considering that the spell duration is 5 minutes and the lock is only 1 minute, so in logical terms the lock will never prevent the debuff from being refreshed if it was removed by expire.

**Out of combat**
- Debuff is reapplied once it expires.

**Comment by amed80** [comment]
> **During combat**
> 
> *Once the debuff is removed, it fires a 1 minute lock that prevents him from recasting it.

The 1 minute lock should start from when the last time he casted DM and not from when it was removed , this seems to cause a delay of when he cast his first DM during combat , as if he cast the buff out of combat , you wait as an example 20s then you steal it which also gonna start the fight , Zerevor should recast DM again after 40s from when the fight start (60s from his last cast)

Also as i mentioned about , if you don't steal the buff instantly when he cast it (waiting 30-60s) , he will not cast DM again for the rest of the fight.

**Comment by Nyeriah** [comment]
> The 1 minute lock should start from when the last time he casted DM and not from when it was removed

I meant to say, Zerevor casts his debuff -> When it expires -> And consequently triggers the lock (the lock triggers after the cast).

I am sorry for the confusion. It is scripted exactly as you described, please check the code.

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
