### PR TITLE
fix(DB/creature): Starting zones

### LINKED ISSUE #3724: [BUG] Minor bug (bad positioning npc first quest)
##### CURRENT BEHAVIOUR:

NPCs who give the first quete are badly positioned

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Human : https://youtu.be/nvPSKTsvObk?t=115
elfes : https://youtu.be/0YhY4g-JEj4?t=131

I didn't found other rerail video for other races.

##### STEPS TO REPRODUCE THE PROBLEM:

1. create char 
2. see npc first quest positioning
3. 

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/94495407-bug-minor-bug-bad-positioning-npc-first-quest?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Si1ker**
This change will update the guid position for human and night-elf initial NPCs

Reference - Human: https://www.youtube.com/watch?v=nvPSKTsvObk
Reference - Night elf: https://www.youtube.com/watch?v=0YhY4g-JEj4

## CHANGES PROPOSED:
- Update guide position for Deputy Willem and Ilthalaine
- Update guide position for Ilthalaine
- Adjust orientation

## ISSUES ADDRESSED:
- Closes #3724 

## TESTS PERFORMED:
- Applied SQL query
- Tested in-game (win x64)

### Before PR:
image

image

### After PR:
image

image

### Before the PR:
.go c id 823 -> check pos
.go c id 2079 -> check pos

### After the PR:
Apply SQL query and repeat as above

## KNOWN ISSUES AND TODO LIST:

- N/A

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by BarbzYHOOL** [comment]
interesting

**Review by BarbzYHOOL — APPROVED** [review]

**Comment by Mitradis** [comment]
same problem with dwarven\gnome start position and starting npc.

**Comment by Mitradis** [comment]
@Si1ker same problem with dwarven\gnome start position and starting npc.

**Comment by Mitradis** [comment]
@Si1ker @BarbzYHOOL same problem with dwarven\gnome start position and starting npc.

**Comment by Si1ker** [comment]
@Mitradis Post a new issue with references.
Locking this threat.

**Pull request merged**
