### PR TITLE
fix(DB/Gossip_Menu_Option_Locale): fix german umlauts

### PR DESCRIPTION
**Pull request by V-Cyberpunk**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18773

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

image

## How to Test the Changes:

1. e.g. go to learning dual spec.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Missing new line at end of file

**Comment by sudlud** [comment]
Thanks for the PR!

Do you want to check if other _locale tables might also be affected maybe?
So we could fix them in another PR if necessary

**Comment by V-Cyberpunk** [comment]
i will look into that :)

**Comment by V-Cyberpunk** [comment]
other locales are fine!

**Comment by V-Cyberpunk** [comment]
how is the "ready to be review" label be added? or is that automatic?

**Comment by sudlud** [comment]
Thanks for the fix :)

**Review by sudlud — APPROVED** [review]

**Comment by sudlud** [comment]
i actually dumped the DB table before and after PR and looked at the diff and couldn't see any unintended or incorrect changes.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by pangolp** [comment]
Asked out of ignorance, but shouldn't we have to specify the language here in the query? Couldn't this affect another language?

**Comment by pangolp** [comment]
Sorry, there was already an image inside the body of the pull request. He hadn't seen her. If you could upload one with the bug, that would be great, although it wouldn't be necessary either. It is simply because in my case, I do not have a client to be able to do the tests in that language.

**Comment by pangolp** [comment]
Before

image

After

image

I did the tests with this script. If you need help, I can make a commit on that topic. In case you can't. But since the title says German, I think it would be interesting to add this modification, to specify the language.

```sql
UPDATE `gossip_menu_option_locale` SET `OptionText`=REPLACE(`OptionText`,'Ã¤','ä') WHERE `Locale`='deDE';
UPDATE `gossip_menu_option_locale` SET `OptionText`=REPLACE(`OptionText`,'Ã¼','ü') WHERE `Locale`='deDE';
UPDATE `gossip_menu_option_locale` SET `OptionText`=REPLACE(`OptionText`,'Ã¶','ö') WHERE `Locale`='deDE';
UPDATE `gossip_menu_option_locale` SET `BoxText`=REPLACE(`BoxText`,'Ã¤','ä') WHERE `Locale`='deDE';
UPDATE `gossip_menu_option_locale` SET `BoxText`=REPLACE(`BoxText`,'Ã¼','ü') WHERE `Locale`='deDE';
UPDATE `gossip_menu_option_locale` SET `BoxText`=REPLACE(`BoxText`,'Ã¶','ö') WHERE `Locale`='deDE';
```

**Comment by pangolp** [comment]
@sudlud Should we add the language in the query or not? What do you think about this topic?

**Comment by sudlud** [comment]
I agree with @pangolp that adding that additional "safety net" could not hurt.

**Comment by pangolp** [comment]
Let's wait if he passes the tests...

**Review by pangolp — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
