### PR TITLE
fix(scripts/zone_shadowmoon_valley): Enraged Spirits' abilities

### LINKED ISSUE #16229: [TBC Shadowmoon Valley]: Enraged Earth Spirit do not spawn Enraged Earth Shards on death
Originally reported on CC at: https://github.com/chromiecraft/chromiecraft/issues/5588
By: Paradigmxd

### What client do you play on?

enUS

### Faction

Both

### Content Phase:

70

### Current Behaviour

Has no scripted Shatter ability

### Expected Blizzlike Behaviour

Upon death -it shatters - just like Elemental Earths in Netherstorms..

### Source

https://www.wowhead.com/wotlk/npc=21050/enraged-earth-spirit#abilities

### Steps to reproduce the problem

Teleport to NPC ID 21050 
Kill it and see if it shatters

### Extra Notes

Todo:
- [ ] find a way to be able to do the totem quest without using npc_enraged_spirit as a creature script so that SAI can be used to cast spells
- [x] implement death mechanic of Enraged Earth Spirit (I have a fix ready for this*) AKA summoning the Enraged Earth Shards
- [ ] implement other missing abilities of the enraged spirits (which require the first task to be completed first to work)

```sql
--
UPDATE `creature_template` SET `AIName` = 'SmartAI', `ScriptName` = '' WHERE `entry` = 21050;

DELETE FROM `smart_scripts` WHERE `entryorguid` = 21050 AND `source_type` = 0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(21050, 0, 0, 0, 6, 0, 100, 1, 0, 0, 0, 0, 0, 11, 38365, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Enraged Earth Spirit - On Death - Cast \'Summon Enraged Earth Shard\' (No Repeat)');
```
### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8224a90a99cc40ff9a7a9a3ab4d7aecc40aacd3d

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-BreakingNewsOverride](https://github.com/AnchyDev/BreakingNewsOverride)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-event-scripts](https://github.com/55Honey/Acore_eventScripts)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Partially port https://github.com/TrinityCore/TrinityCore/commit/cc894288b77299e9e73f322869f16c2791435104

Co-authored-by: Malleus <Malleus@users.noreply.github.com>

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5588
- Closes #16229

## Tests Performed:

- Tested

image

image

image

image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Why can't we make it in SAI?

**Comment by Si1ker** [comment]
> Why can't we make it in SAI?

@Gultask Close this and make it in SAI then.

As far as I remember (at least in old AC) if anybody can publish a fix to resolve an issue, good.. if after the issue is resolved anyone wishes to improve it or refactor it, good as well.

**Comment by Gultask** [comment]
I'm just asking because we usually use SAI unless it:

1. Is a boss
2. Can't be handled with SAI alone

So I was just curious.

**Comment by elthehablo** [comment]
The adds were already scripted in SAI. But those are overwritten because of the quest script. We could do SAI but then we need to script the quest in SAI too

**Comment by Si1ker** [comment]
Feel free to close.

**Comment by elthehablo** [comment]
Personally I'd say merge. Maybe add something somewhere that indicates we still want to transform this all to SAI. But honestly I am not touching that myself

**Comment by heyitsbench** [comment]
> Personally I'd say merge. Maybe add something somewhere that indicates we still want to transform this all to SAI. But honestly I am not touching that myself

It's pretty much a given that anything that *can* be done with SAI should eventually be done in SAI (except bosses). There's no need to add a note of any sort IMO to point that out. But I am also in the camp of C++ script being better than open issue.

**Review by Kitzunu — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
this marked as [Waiting to be tested] but it has been tested by the author being a known contributor and testing material has been provided, it is not a delicate change, so no need for further testing.

**Comment by Nyeriah** [comment]
This hasn’t been merged because the commit message doesn’t hold proper TrinityCore credits

**Comment by FrancescoBorzi** [comment]
> This hasn’t been merged because the commit message doesn’t hold proper TrinityCore credits —author=“” or at least co-author

@Si1ker please fix

**Comment by Si1ker** [comment]
what about now? first time using —author lul

**Comment by Si1ker** [comment]
> > what about now? first time using —author lul (also editor reset xd)
> 
> no it's not that, it is about writing it in the PR description :)
> 
> ```
> Co-authored-by: author-name <name@xxx.com>
> ```

idk the ID+user @ no-reply, so now?

**Comment by Si1ker** [comment]
update labels pls, ty.

**Pull request merged**
