### PR TITLE
feat(Cmake/Build): correct support std::filesystem

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Title
- Improve #5417

## SOURCE:
- https://en.cppreference.com/w/cpp/filesystem

## Tests Performed:
- No

## How to Test the Changes:
- Build tools with clang version less `9.0`
- Build tools with gcc version less `9.1`

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nolin7777** [comment]
Great, I will close mine.

**Comment by Winfidonarleyan** [comment]
> Great, I will close mine.

Try test this

**Comment by FrancescoBorzi** [comment]
@Nolin7777 can you please test this?

**Comment by Nolin7777** [comment]
> @Nolin7777 can you please test this?

Will do

**Comment by Nolin7777** [comment]
No, not working for me.
Debian 10.9
Clang 7.0.1
CMake 3.20.1

**Pull request closed without merging**
