### PR TITLE
fix(DB/Kalimdor): limit Warchief's Blessing to level 63 and below and Horde only

### PR DESCRIPTION
**Pull request by sogladev**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

https://wowpedia.fandom.com/wiki/Patch_2.1.0  
image  list omits WCB

wowhead https://www.wowhead.com/tbc/guide/raid-consumables-flasks-elixirs-potions-wow-burning-crusade-classic
image

can no longer apply to Alliance
https://wowpedia.fandom.com/wiki/Warchief%27s_Blessing

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

Go to Thrall
```
.quest remove  4974
.quest add 4974
.quest  complete  4974
```

Crossroads
```
.tele crossroads
```

- must be 63 or lower
- Horde only

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Rip Alliance players.

**Comment by Kitzunu** [comment]
The question is... Was this changed in classic or was it like this in 335

**Comment by sogladev** [comment]
I found no source for the level requirement of Warchief's Blessing in patch notes. Maybe it was not included in the 2.1 nerfs to worldbuffs. Songflower is not in there either. Blizzard probably overlooked them at the time. I'll remove the level requirement

**Review by Kitzunu — APPROVED** [review]

**Comment by godnesso** [comment]
I looked into Wowhead comments and found sources that suggest WCB was not received when buff went out.
How did you miss this?

https://www.wowhead.com/wotlk/spell=15366/songflower-serenade#comments
wcb
wcb1


Same for Songflower, but this time it is spelled out:
https://www.wowhead.com/wotlk/spell=16609/warchiefs-blessing#comments
songflower

The buffs definitely were not possible to receive above level 63 and Blizz forgot to include them in patch notes. Please fix, thank you

**Comment by sogladev** [comment]
> The buffs definitely were not possible to receive above level 63 and Blizz forgot to include them in patch notes. Please fix, thank you

Thanks for investigating this. I vaguely remember that reputation requirement that's included in the comment Where in classic, undead lvl20 MC cappers were considered bad as they likely are only neutral with Orgrimmar at that level and therefore failing to give the buff

**Pull request merged**
