### PR TITLE
Fix (db/creature) spire frostwyrm creature no longer duplicates in icc

### PR DESCRIPTION
**Pull request by Dr-Arayashiki**
## Changes Proposed:
-  remove the duplicate of the Spire Frostwyrm creature that just sits in the sky doing nothing in the ICC, right before the Gun Ship

## Issues Addressed:

- Closes 

## SOURCE:

image

## Tests Performed:

- 
- 

## How to Test the Changes:

1. go to the entrance just before the Gun Ship
2. look up and the dragon won't be there anymore
3. now only one dragon will come down and the copy will no longer idle on top

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Scenery wyrms are named Frostwyrm (Scenery) or something. Those were the wyrms sunwell used before I rewrote the script a couple of nights ago. They were likely custom

**Comment by heyitsbench** [comment]
> Scenery wyrms are named Frostwyrm (Scenery) or something. Those were the wyrms sunwell used before I rewrote the script a couple of nights ago. They were likely custom

Maybe, I still don't really agree with PRs with no source for changes.

**Comment by Nyeriah** [comment]
Scenery wyrms are named **Frostwyrm (Scenery)** or something. They’re of a different entry. Those were the wyrms sunwell used before I rewrote the script a couple of nights ago. They were likely custom

**Comment by Dr-Arayashiki** [comment]
> Please provide a source for the change. While I agree that chances are the wyrm shouldn't just be sitting up there, he may supposed to be circling the area or just watching the encounter for scenery.

the dragons that are flying there cannot be selected as an object of attack, only this one descends and can be attacked ^^

**Comment by Nyeriah** [comment]
@heyitsbench i appreciate your concerns and I do share the same sentiment about it but I’ve asked them to open this PR myself after having worked on those mobs. There are no such mobs flying in that area, but you’re welcome to test it on retail as well and provide sources to counter my claim

**Comment by heyitsbench** [comment]
> heyitsbench i appreciate your concerns and I do share the same sentiment about it but I’ve asked them to open this PR myself after having worked on those mobs. There are no such mobs flying in that area, but you’re welcome to test it on retail as well and provide sources to counter my claim

I just prefer that templates be filled out properly, even a source of "Assumption based on name of offending creature and surrounding scenery creatures" would satisfy me. A source of an AC screenshot doesn't scream blizzlike to me.

**Comment by Nyeriah** [comment]
image

Nothing there as can be seen, and we already got the scenery drakes working

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
