### PR TITLE
fix(Core/Spells): Taunt always set proper target while channelling sp…

### LINKED ISSUE #13841: [Slave Pens] Quagmirran should turn towards the taunter during acid spray
### Current Behaviour

[Quagmirran](https://wowgaming.altervista.org/aowow/?npc=17942)'s [Acid Spray](https://wowgaming.altervista.org/aowow/?spell=38153) will target the taunter after being taunted, but his body will still point towards the old target

### Expected Blizzlike Behaviour

When [Quagmirran](https://wowgaming.altervista.org/aowow/?npc=17942) is taunted during [Acid Spray](https://wowgaming.altervista.org/aowow/?spell=38153), his body should point towards the taunter

### Source

tbc classic:
https://youtu.be/N4k1Malqmi0?t=1438

### Steps to reproduce the problem

with multiple partymembers:
.go 80260
wait for him to cast acid spray
taunt it during acid spray when it doesn't aim for the taunter

### Extra Notes

https://wowgaming.altervista.org/aowow/?npc=17942
https://www.wowhead.com/wotlk/npc=17942/quagmirran
https://wowgaming.altervista.org/aowow/?spell=38153

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2ad56371130ab7e9a96f2a92b167a6eeb895e44f

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…ells.

Fixes #13841

## Issues Addressed:

- Closes #13841

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Login with multiple partymembers:
`.go cr 80260`
wait for him to cast acid spray
taunt it during acid spray when it doesn't aim for the taunter

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Sneften** [comment]
Tested
Acid spray changes direction but not the visual of Quagmirran.

Will test Rotface when I have more time and fin a source of  expected behaviour.

**Comment by UltraNix** [comment]
@Sneften Shopuld be okay now.

**Comment by Maelthyrr** [comment]
Hi, tested.  The spell effect is fixed, but Nyeriah has the right. it doesn't work with rotface.

**Comment by UltraNix** [comment]
@Maelthyrr Could you re-test Rotface?

**Review by Kitzunu — APPROVED** [review]

**Comment by Nyeriah** [comment]
I see this got merged...
...but to my knowledge, going from @GastonCK report... it still broke Rotface

**Pull request merged**
