### PR TITLE
feat(CORE/Petname): DK Petname generation locale

### PR DESCRIPTION
**Pull request by Valdifer**
When a DK calls a ghoul its getting the English name, now can get locale names if they are inserted in DB

Valdifer

## Changes Proposed:
-  DK Ghouls generate name by locale

## Issues Addressed:

- Closes 

## Tests Performed:

- Tested ingame, and build without errors
- 
image

## How to Test the Changes:

1. create a DK
2. get the Ghoul permanent Perk
3. spawn the ghoul

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
You filled the VerifiedBuild values with 12340, may I ask the source for those?

**Comment by Valdifer** [comment]
> You filled the VerifiedBuild values with 12340, may I ask the source for those?

The source? sure, i just copied from other locales SQL because i don't know if is that version or if that field should be there :/

**Comment by heyitsbench** [comment]
I'm mostly asking where the names are coming from, as the VerifiedBuild column are supposed to be the client build that the values are collected from.
Because the `pet_name_generation` table has no VerifiedBuild column, there's probably no reason to include it in your created table.

**Comment by Valdifer** [comment]
> I'm mostly asking where the names are coming from, as the VerifiedBuild column are supposed to be the client build that the values are collected from. Because the `pet_name_generation` table has no VerifiedBuild column, there's probably no reason to include it in your created table.

I see, the table is based in pet_name_generation but when i saw some DB table locales i saw the verified build, so if it is not necesary i can remove it and test it again

**Comment by heyitsbench** [comment]
> I see, the table is based in pet_name_generation but when i saw some DB table locales i saw the verified build, so i thought that should be there but if it is not necesary i can remove it and test it again

In my opinion that column isn't necessary. but where are the names you're filling the table with coming from? Are they translations by hand, grabbed from Wowhead, or somewhere else?

**Comment by Valdifer** [comment]
> > I see, the table is based in pet_name_generation but when i saw some DB table locales i saw the verified build, so i thought that should be there but if it is not necesary i can remove it and test it again
> 
> In my opinion that column isn't necessary. but where are the names you're filling the table with coming from? Are they translations by hand, grabbed from Wowhead, or somewhere else?

These names are translation by hands and names that i remember when i played LK 14 years ago

**Comment by Kitzunu** [comment]
This is not supposed to be determined by locale but by the server settings.

**Comment by heyitsbench** [comment]
Don't know if this is something specific to the PTR or just a general Classic change, but names of ghouls do appear to depend on [client locale](https://user-images.githubusercontent.com/38561765/205511209-9c6e6006-a7cc-4c97-a1fd-bf99ff7a4860.png) on the Classic PTR.

**Comment by Valdifer** [comment]
I remember when i played LK in 2008, if you were with other client language version the ghouls were named by your Locale, the thing i dont remember right now is if the client was english version and the other was spanish (For example) the english client was seeing english name or spanish

**Comment by Valdifer** [comment]
> Don't know if this is something specific to the PTR or just a general Classic change, but names of ghouls do appear to depend on [client locale](https://user-images.githubusercontent.com/38561765/205511209-9c6e6006-a7cc-4c97-a1fd-bf99ff7a4860.png) on the Classic PTR.
> 
> EDIT: Name that shows up on PTR is dependent on locale of the [summoner](https://user-images.githubusercontent.com/38561765/205949663-cb56dd0a-3626-4b2d-b979-29f02692b354.png). Somewhat unsurprising, the name of the ghoul stays localized even if the client changes locale after summoning.

hmm and what happen when you summoned the pet in DE locale, you change locale back to EN, kill the pet and resummon?
Right now in AC when you kill the ghoul you get a new one with a new name

**Comment by acidmanifesto** [comment]
> > Don't know if this is something specific to the PTR or just a general Classic change, but names of ghouls do appear to depend on [client locale](https://user-images.githubusercontent.com/38561765/205511209-9c6e6006-a7cc-4c97-a1fd-bf99ff7a4860.png) on the Classic PTR.
> > 
> > EDIT: Name that shows up on PTR is dependent on locale of the [summoner](https://user-images.githubusercontent.com/38561765/205949663-cb56dd0a-3626-4b2d-b979-29f02692b354.png). Somewhat unsurprising, the name of the ghoul stays localized even if the client changes locale after summoning.
> 
> hmm and what happen when you summoned the pet in DE locale, you change locale back to EN, kill the pet and resummon?
> Right now in AC when you kill the ghoul you get a new one with a new name

Undead pets and demon summon companions never keep their names. The lore is everytime you call/summon them, you will not summon the same exact one. The only exception is the hunter's tamed pets which requires a [certificate of ownership](https://www.wowhead.com/wotlk/item=43850/certificate-of-ownership) item to rename

**Comment by Nyeriah** [comment]
Hm. My demons always kept their names

**Comment by Valdifer** [comment]
> Hm. My demons always kept their names

Same, it happens to me too that

**Comment by acidmanifesto** [comment]
> Hm. My demons always kept their names 

Unless somethink boinked on retail, the demons never keep their names. It changes on every resummon. The wow lore states that the only way to truely control a demon is to know their true name. Which is why the rename never stays.

**Comment by Nyeriah** [comment]
Through vanilla, tbc, wrath, wod, legion and bfa I can confirm that demons don’t change name on resummon

**Comment by heyitsbench** [comment]
> hmm and what happen when you summoned the pet in DE locale, you change locale back to EN, kill the pet and resummon? Right now in AC when you kill the ghoul you get a new one with a new name

Ghoul was summoned with the name Larvennager, switched to enUS, stayed Larvennager, dismissed+resummoned, new name was Hammermonger.

For the record, ghoul names do *not* stay the same between summons on the PTR regardless of any locale shenanigans.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
Could someone with a Spanish client give this one a go? So we can get it merged 👍

**Comment by heyitsbench** [comment]
Tested with esES/enUS. When I first created a minion on esES, the name was Rootsomething, an English name, but after dismissing that ghoul, every ghoul after had a Spanish name. Every ghoul I summoned with an enUS client had an English name. Seems to have been a one off issue due to maybe cached locale for my account, otherwise seems to be working as it should. 👍

**Comment by Nyeriah** [comment]
Thank you very much for testing 👍

**Comment by heyitsbench** [comment]
Will point out though that it has a few issues, such as not matching up to the [SQL standards](https://www.azerothcore.org/wiki/sql-standards) regarding table/column names and no brackets around some if statements.

**Comment by Kitzunu** [comment]
Yea, we noticed that right as Nyeriah merged too. Thanks for pointing it out tho. Will be corrected ASAP

**Pull request merged**
