### PR TITLE
chore(DB/quest_offer_reward): Update capitalization of name/class

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  $C -> $c
-  $n -> $N

## Tests Performed:
- Ran SQL

## How to Test the Changes:

Not needed

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
> Test performed: Ran SQL

I think a test in-game is needed for such a big change (even if it's a simple change)

**Comment by Kitzunu** [comment]
Well, nothing has changed.

I just pulled the already existing tables and changed the capitalization. 

Anyhow how to test:
Test the ID of all 3690 quests :D

**Comment by FrancescoBorzi** [comment]
> Well, nothing has really changed.
> 
> I just pulled the already existing tables and changed the capitalization.
> 
> Anyhow how to test:
> Test the ID of all 3690 quests :D

just checking a couple of them would be enough

**Comment by pklloveyou** [comment]
Tested

**Review by Voxstrasza — APPROVED** [review]

**Pull request merged**
