### PR TITLE
refactor(Core): remove ACE types

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## CHANGES PROPOSED:
-  Remove ACE types

## ISSUES ADDRESSED:
- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3451

## TESTS PERFORMED:
- Builds

## HOW TO TEST THE CHANGES:
- If all builds pass, no tests needed

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]

**Comment by Mitradis** [comment]
unused or its parf of https://github.com/azerothcore/azerothcore-wotlk/pull/3744 ?

**Comment by FrancescoBorzi** [comment]
> unused or its part of #3744 ? i cant create pull request for PRs like this (3744 too) to my forked repo.

not sure what you really meant but: apparently these imports were unused, otherwise the build would have failed

**Comment by Mitradis** [comment]
@FrancescoBorzi 
https://i5.imageban.ru/out/2020/11/23/a6b997c52d088fea94582a61cf755d9d.png
https://i6.imageban.ru/out/2020/11/23/506f3f278a53aaf3a3e3746046db7115.png

**Comment by FrancescoBorzi** [comment]
sorry @Mitradis I still don't get what you mean. Do you need something?

**Pull request merged**
