### PR TITLE
Quest abandon finish fix

### PR DESCRIPTION
**Pull request by poszer**
Updating previous PR [#1241 ](https://github.com/azerothcore/azerothcore-wotlk/pull/1241)

##### CHANGES PROPOSED:

-  Adding @talamortis suggestion
-  

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
I don't think much testing is needed here, @poszer if you already tested this then feel free to merge

**Comment by BarbzYHOOL** [comment]
the tag was more for "need feebback" like if it's missing stuff or if it's correct I guess

**Comment by talamortis** [comment]
Can merge for me thanks for doing the change :)

**Comment by BarbzYHOOL** [comment]
there were other 9999 in the previous PR though and this one wasn't tested

**Comment by BarbzYHOOL** [comment]
ok then I put 3 notes on the previous PR where the files were visible

**Comment by BarbzYHOOL** [comment]
guys check it out https://github.com/azerothcore/azerothcore-wotlk/pull/1241

**Comment by talamortis** [comment]
@poszer are you able to edit the other '9999' please :)

**Comment by poszer** [comment]
> @poszer are you able to edit the other '9999' please :)

Yeah, sure

**Comment by FrancescoBorzi** [comment]
@poszer  please squash commits when merging the PR

**Pull request merged**
