### PR TITLE
Ashbringer event inside Scarlet Monastery instance

### PR DESCRIPTION
**Pull request by Gargarensis**
**Changes proposed:**

-  Fix Ashbringer event in Scarlet Monastery
-  Fix interaction of Fairbanks with the Ashbringer

**Known issues and TODO list:**

- [Some NPC will continue with their pathing after performing the bow emote ] 
- [Not sure about the Mograine spawn name (but it should be sniffed correctcly anyway) ]

### CODE REVIEW

**Comment by Yehonal** [comment]
could someone test this PR please?

**Comment by Rushor** [comment]
where do you got this code from?

**Comment by Rushor** [comment]
source for this: https://github.com/TrinityCore/TrinityCore/issues/12666

**Comment by Gargarensis** [comment]
Yes, i took something from there and i made some modification, also i've written Fairbanks, starting from an old resource of xinef

**Comment by Rushor** [comment]
better move the gossip_options to db instead hardcoded in core

**Comment by ShinDarth** [comment]
I agree

**Pull request merged**
