### PR TITLE
feat(Docker): Container healthchecks

### PR DESCRIPTION
**Pull request by h0lysp4nk**
Improvement(Docker): Container healthchecks

## CHANGES PROPOSED:
-  Added healthchecks to the worldserver, authserver and database containers
-  Added package `net-tools` to the worldserver, authserver and database containers for healthchecks.

## ISSUES ADDRESSED:
- Doesn't address any issues.

## TESTS PERFORMED:
- Forcefully closed the process inside the container
- Ran `docker-compose config` to ensure the sytnax is correct.

## HOW TO TEST THE CHANGES:

- Build AzerothCore in Docker
- Start the server
- Cause the process for the worldserver, authserver or database to stop. e.g: use the in-built stop command.

## KNOWN ISSUES AND TODO LIST:

- None

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by h0lysp4nk** [comment]
Before:
```
➜  azerothcore-wotlk git:(pr-dockerhealthchecks) docker-compose ps
               Name                             Command                  State                     Ports
----------------------------------------------------------------------------------------------------------------------
azerothcore-wotlk_ac-authserver_1    /azeroth-server/bin/authserver   Up   0.0.0.0:3724->3724/tcp
azerothcore-wotlk_ac-database_1      docker-entrypoint.sh mysqld      Up   0.0.0.0:3306->3306/tcp, 33060/tcp
azerothcore-wotlk_ac-worldserver_1   /azeroth-server/bin/worlds ...   Up   0.0.0.0:8085->8085/tcp
```

After:
```
➜  azerothcore-wotlk git:(pr-dockerhealthchecks) docker-compose ps
               Name                             Command                  State                     Ports
----------------------------------------------------------------------------------------------------------------------
azerothcore-wotlk_ac-authserver_1    /azeroth-server/bin/authserver   Up (healthy)   0.0.0.0:3724->3724/tcp
azerothcore-wotlk_ac-database_1      docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3306->3306/tcp, 33060/tcp
azerothcore-wotlk_ac-worldserver_1   /azeroth-server/bin/worlds ...   Up (healthy)   0.0.0.0:8085->8085/tcp
```

When there's an issue:
```
➜  azerothcore-wotlk git:(pr-dockerhealthchecks) docker-compose ps
               Name                             Command                  State                     Ports
----------------------------------------------------------------------------------------------------------------------
azerothcore-wotlk_ac-authserver_1    /azeroth-server/bin/authserver   Up (unhealthy)  0.0.0.0:3724->3724/tcp
azerothcore-wotlk_ac-database_1      docker-entrypoint.sh mysqld      Up (healthy)   0.0.0.0:3306->3306/tcp, 33060/tcp
azerothcore-wotlk_ac-worldserver_1   /azeroth-server/bin/worlds ...   Up (healthy)   0.0.0.0:8085->8085/tcp
```

**Comment by merdlin** [comment]
thanks, it works.

**Comment by FrancescoBorzi** [comment]
thanks @merdlin for testing this :)

**Comment by Kitzunu** [comment]
@h0lysp4nk please fix the merge conflict

**Pull request merged**
