### PR TITLE
fix(DB/Scripts): Npc Tonk Control Console

### PR DESCRIPTION
**Pull request by grimgravy**
## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9514

## Tests Performed:

- Tested in game

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Sneften** [comment]
Tested PR, did not work ❌ 
Nothing happens when I click the _Tonk Control Console_.
Tested with different lvl ranges and different reputation lvl with DF.

**Comment by grimgravy** [comment]
> Tested PR, did not work x Nothing happens when I click the _Tonk Control Console_. Tested with different lvl ranges and different reputation lvl with DF.

please test change

**Comment by Sneften** [comment]
Tested changes, Tonk is summoned ✔️ 
**How its working now** 
If you are in party, members will get controll over a tonk if you are nearby when a member is pressing the console.
If not in party and another player press the console only that player will get to control a tonk.
When tonk is canceled, console is unclickable and then despawns after 4min and then spawns again after 30sec.

**Comment by FrancescoBorzi** [comment]
good job @grimgravy and thank you very much @Sneften for testing this PR!

**Pull request merged**
