### PR TITLE
Core/Items: Items with charges should not remove on item unequip its …

### LINKED ISSUE #5716: Multiple Pendant Buffs Persist Incorrectly After Relog and Removal
**CURRENT BEHAVIOUR:**

Original reports:
- https://github.com/chromiecraft/chromiecraft/issues/548
- https://github.com/chromiecraft/chromiecraft/issues/547
- https://github.com/chromiecraft/chromiecraft/issues/350
- https://github.com/chromiecraft/chromiecraft/issues/349

There are at least 4 identified pendants that have 10 charges and give 30 minute buffs of various kinds in the game:

- Citrine Pendant of Golden Healing - https://wotlkdb.com/?item=20967 - aura is https://wotlkdb.com/?spell=25608
- Aquamarine Pendant of the Warrior - https://wotlkdb.com/?item=21755 - aura is https://wotlkdb.com/?spell=26562
- Amulet of the Moon - https://wotlkdb.com/?item=20830 - aura is https://wotlkdb.com/?spell=25207
- Pendant of the Agate Shield - https://wotlkdb.com/?item=20950 - aura is https://wotlkdb.com/?item=20950

The problem is that the buff auras for all of these are not removed if you relog with it active and then remove the necklace from your necklace slot. This allows stacking of all 4 if you want, which is pretty significant at lvl 39:

All four buffs active with none of the necks equipped:
WoWScrnShot_050821_150848

Also note other issues with these pendants - notably https://github.com/azerothcore/azerothcore-wotlk/issues/5637

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The buff aura should only be active while you are wearing the necklace and should be removed at any point a player does not have necklace equipped.

note from @gurveleg:
Its not the problem that the buff is staying after relogging - that part works as it should, you have the pendant equiped and buff active so the aura is saved, the problem is buff not being removed after removing the pendant if you relogged with the buff active and pendant equipped. The aura should only work as long as you are wearing the pendant - doesn't matter if you relogged or not while having the buff. It doesn't persist through death either so that part works as it should.

**SOURCE:**

"If you buff yourself with this and then remove the pendant, the buff disappears immediately." (https://tbc.wowhead.com/item=20950/pendant-of-the-agate-shield#comments:id=232231)

"Is this like a magic buff, where it remains for 30mins. even when the necklace is removed and replaced with another necklace?"
"No, this item must be worn for the duration of the buff or the entire group loses it.  Re-equipping the item will not bring the buff back, and you must wait for the cooldown before you may use it again." (https://tbc.wowhead.com/item=21755/aquamarine-pendant-of-the-warrior#comments:id=3337702:reply=1468645)

"1) Does the buff remain if you swap in another necklace? or does it go away if you aren't wearing the item anymore?"
1) no. yes." - "https://tbc.wowhead.com/item=20950/pendant-of-the-agate-shield#comments:id=3360805:reply=1475152")

It's only fair to note disagreement from @Stifler82:
"But the comment you reported is a report from (Patch 2.3.3) So maybe in WOTLK the spell might have changed.
In addition, the item has 10 charges, after which it is not possible to use it more times. So I assume it was done on purpose to avoid "losing" the charge used. The charge is not lost because when you "Log-out" the Server "Registers" the aura you have, in fact if you remove the item before logging out the charge is lost.."

I believe the above is inaccurate. We know the buffs were removed when the necklace was removed in 2.3. That is therefore the default position for how the game behaved. If it is conjectured that "maybe in WOTLK the spell might have changed" then it is necessary to find some record of that change. Otherwise we are merely guessing. I have not been able to find any such record in the patch notes. Therefore, we can only conclude that there was no change, and that the behaviour in 3.3.5 was the same as is described above. 

@gurveleg argues from a game design perspective:
"Okay, I watched a few retail WotlK raiding videos (firsts kills and what not) and I have not seen anyone using Pendant of the Agate Shield buff. Were it to work like it is now (buff staying when you remove Pendant from Necklace slot if you reloged before) every raid would have 1 person with that for free +10 stamina because it stacks with other stamina buffs - they would use buff, relog, and then equip their epic lvl 80 necklace and kept on giving the raid 10 stamina buff from pendant. Tanks were minmaxing with JC because it gave 3 more stamina than other professions, or even farming some https://wowgaming.altervista.org/aowow/?item=23985 for that 5 stamina, yet no one ever uses this. It isnt mentioned in any comments or any of the raid buff guides either.

So it is safe to assume that the buff not being removed at any point when person is not wearing Pendant of the Agate Shield is a bug."

**STEPS TO REPRODUCE THE PROBLEM:**

1. Equip one of the necklaces and use its buff
2. Relog
3. Swap the necklace for something else
4. See the buff stay
5. Repeat for all four if you want.

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
ev. 3c763786a0bd 2021-05-07 21:53:46 +0000

**OPERATING SYSTEM:**

Linux Mint 20.1

**MODULES:**

N/A.

**CUSTOMIZATIONS:**

N/A.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98327436-multiple-pendant-buffs-persist-incorrectly-after-relog-and-removal?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…auras activated by use.

Fixed #5716

## Changes Proposed:
-  Corrected condition about removing auras activated on item use.

## Issues Addressed:

- Closes #5716
- Closes https://github.com/chromiecraft/chromiecraft/issues/548
- Closes https://github.com/chromiecraft/chromiecraft/issues/547
- Closes https://github.com/chromiecraft/chromiecraft/issues/350
- Closes https://github.com/chromiecraft/chromiecraft/issues/349

## Tests Performed:

- Tested ingame with aboved items.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by robbie018** [comment]
Not completely fixed.

Before fix: The buffs stays 30 min, doesn't matter if you remove the amulet or log out. The buff always stays.
After fix: The buff is removed if you remove the amulet. But if you equipe the amulet, use the buff and log out. The buff will stay, also if you equipe an other amulet and use that buff.

https://user-images.githubusercontent.com/65018032/126547212-f4013eeb-f058-4ac7-a5c9-23ff27eceff6.mp4

**Comment by UltraNix** [comment]
@robbie018 Test again.

**Comment by robbie018** [comment]
@UltraNix 
Sorry it took so long to test a second time.

<h1>First fix</h1>
Before fix: The buffs stays 30 min, doesn't matter if you remove the amulet or log out. The buff always stays.
After fix: The buff is removed if you remove the amulet. But if you equipe the amulet, use the buff and log out. The buff will stay, also if you equipe an other amulet and use that buff.
<br /><br />

<h1>Second fix</h1>
Before second fix: Problem was when you log out you could unequipe the amulet but keep the buff.
After second fix: The buff wil always be removed when you unequipe the amulet. Also when you log out and back in you have the buff but when you unequipe the amulet the buff will also be removed. Also when you right click a different amulet to equipe the old amulet will be unequiped and the buff will be removed.
<br /><br />

<h2>Conclusion:</h2>
Works perfect with the 4 amulets!
<br /><br />

<h2>POE</h2>

https://user-images.githubusercontent.com/65018032/126810832-a8956c8a-ce5e-4fbe-a56f-7ba8ce5b1496.mp4

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @UltraNix and thank you very much @robbie018 for testing this!

**Pull request merged**
