### PR TITLE
fix(Core/AuctionHouse): Implemented sorting. Based on @r00ty-tc work.

### LINKED ISSUE #8728: Auction House Sorts By Page, Not Globally
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1636

In any search of the AH that produces more than 1 page of results, sorting by current bid will apply page-by-page, not across pages. More expensive items than those on page 1 will display on later pages when sorting in descending order of current bid, and vice versa when sorting by ascending order of current bid.

Tester: The basic issue is trivially confirmed:

Page 1, sort by lowest current bid, lowest shown is 1 silver.
WoWScrnShot_102521_211851

But on page 2 are items that are 5 copper:
WoWScrnShot_102521_211901

Same for highest bid. Page 1:

WoWScrnShot_102521_211912

But on page 2:
WoWScrnShot_102521_211914

This was discussed at some length by Trinity: https://github.com/TrinityCore/TrinityCore/issues/15648 but despite an outstanding bounty, no fix was ever made.

### Expected Blizzlike Behaviour

Sorting by current bid would show all items, no matter how many pages of them there are, in descending/ascending order of bid.

### Source

At 3:37 and 3:48 in this Wrath-era video, you can see the person in this video clicking on the next page of an AH search (sorting by rarity, as you can see from the yellow arrow beside rarity) and the rarity is continuous page-on-page. https://www.youtube.com/watch?v=s6cG0m5Zl8g

At 5:02 the person clicks next page, and although he is sorting by rarity, it is a crafting item with no rarity, and the price is continuous page-on-page (since he is not sorting by bid, the items are continuous by buyout): https://www.youtube.com/watch?v=VEKLzUsqrio

### Steps to reproduce the problem

Search the AH for something which returns results of more than 1 page (armor -> mail -> hands, for instance)
Sort by unit price.
Compare 1st page results with later page results.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #8728

## Issues Addressed:

- Closes #8728
- Closes https://github.com/chromiecraft/chromiecraft/issues/1636

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/8728)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
Now.

**Comment by syssneck** [comment]
Tested. It unfortunately still doesn't work correctly for me

Example (sorted by lowest bid):
Page 1:
Page 1 lowest bid

Page 2:
page 2 lowest bid

Why are these auctions not displayed on page 1? The current bid is lower than the bid of some auctions on page 1.

**Comment by UltraNix** [comment]
Yes - buyout in this case is prior to start bid.

**Comment by syssneck** [comment]
Okay, but if that is the case, why is that bag so high up then? (I didn't bid on any item, so it should sort by buyout price, right?):
Page 1 lowest bid

**Comment by UltraNix** [comment]
Because all items above have the same start bid.

**Review by Nefertumm — APPROVED** [review]

**Comment by temperrr** [comment]
So this is working as intended then UltraNix? If so, can be labeled to be merged.

**Comment by UltraNix** [comment]
Yes.

**Comment by Kitzunu** [comment]
codestyle

**Comment by UltraNix** [comment]
@Kitzunu ??

**Comment by Kitzunu** [comment]
Build was failing on it

**Comment by LannyE** [comment]
This could be just me as I haven't had the time to help and keep up with this project like I used to but I do try to compile weekly.  I am getting compile errors this week.  
image

I did a textcrawl to find the GetPlayerNameByGUID text throughout the whole project and only found it in the AuctionHouse.cpp not the ObjectMgr.cpp
image

Was there ObjectMgr changes that was supposed to be included in this commit?

**Comment by Nyeriah** [comment]
@LannyE the commit that removed that function was ready to be merged but this commit got merged before we got to that point, so it fell out of sync and needed to be updated

**Comment by LannyE** [comment]
Thank you.  That fixed it.  Everything compiles nicely now.

**Pull request merged**
