### PR TITLE
fix(Scripts/Ulduar): Fixed "I Could Say That This Cache Was Rare" ach…

### LINKED ISSUE #10910: [Ulduar]Hodir achievement  bug
### Current Behaviour

Kill hodir in three minutes and you cannot achieve the following achievements
`I Could Say That This Cache Was Rare (10 player)` (achievement 3182)
`I Could Say That This Cache Was Rare (10 player)` (achievement 3184)

### Expected Blizzlike Behaviour

Kill hodir in three minutes and you can achieve the following achievements
`I Could Say That This Cache Was Rare (10 player)` (achievement 3182)
`I Could Say That This Cache Was Rare (10 player)` (achievement 3184)

### Source

_No response_

### Steps to reproduce the problem

1. go c id 32845 
2. Fight it
3. Kill it in 10 seconds
4.look your achievement 

### Extra Notes

_No response_

### AC rev. hash/commit

d4b3e8f201bfd303b980c68ea1fb67af5f3e6003

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…ievement.

Fixes #10910

## Issues Addressed:

- Closes #10910

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c id 32845`
Fight it
Kill it in 10 seconds
look your achievement

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by Nefertumm** [comment]
@UltraNix conflicts

**Comment by mpfans** [comment]
> @UltraNix conflicts

This is the PR I want to test right away

**Comment by Nefertumm** [comment]
Nevermind, the merge conflict was easy. I fixed it.
@mpfans you can test it now :)

**Comment by mpfans** [comment]
tested,word .

**Comment by mpfans** [comment]
tested,word .

**Review by Nefertumm — APPROVED** [review]

**Review by Winfidonarleyan — APPROVED** [review]

**Pull request merged**
