### PR TITLE
fix(DB): Lower Blackrock Spire creature import

### LINKED ISSUE #9806: Incorrect NPCs placement in LBRS Wyrmthalak room
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2623

Chromatic Dragon mobs are spawned on the bridge leading to and in Wyrmthalak's boss room in LBRS.

Tester:

The issue is confirmed. Involved NPCs

https://wowgaming.altervista.org/aowow/?npc=9197
https://wowgaming.altervista.org/aowow/?npc=9216
https://wowgaming.altervista.org/aowow/?npc=9583
https://wowgaming.altervista.org/aowow/?npc=9693
https://wowgaming.altervista.org/aowow/?npc=9240
https://wowgaming.altervista.org/aowow/?npc=9268

WoWScrnShot_122021_162338

### Expected Blizzlike Behaviour

No chromatic dragon mobs should be located in LBRS, as they are only appearing in the Rend Blackhand encounter in UBRS.
There should be a selection of troll, orc and ogre mobs from previous parts of the dungeon.

In addition, there is a single mob patrolling between Wyrmthalak and the room entrance, walking up and down the ramp.

### Source

Classic TBC, all mob locations are as shown on screenshot:
Viewing bridge leading to Wyrmthalak, only 2 mobs guarding (Smolderthorn Berserker and Spirestone Warlord)
proof1

There is a single mob patrolling from Wyrmthalak, down the ramp all the way to where the guards stand and then moving back (Smolderthorn Berserker)
proof2

Entering room (Spirestone Warlord, Bloodaxe Veteran, Smolderthorn Berserker, Bloodaxe Evoker)
proof3

Further up the ramp (Spirestone Battle Mage, Smolderthorn Shadow Priest, Bloodaxe Veteran)
proof4

Even further up the ramp, before Wyrmthalak (Spirestone Warlord, Smolderthorn Berserker, Bloodaxe Veteran, Bloodaxe Evoker)
proof5

https://youtu.be/JB__PqlsgkE?t=4402

### Steps to reproduce the problem

.go ga 87971

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/24f4e08708c27b38ed46cb2333a53dfb4c484bc6

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Imported NPCs from VMangos
- Removed Chromatic NPCs
- Added Creature Formations
- Patroling Smoldering Berseker

## Issues Addressed:

- Closes #9806
- Closes https://github.com/chromiecraft/chromiecraft/issues/2623

## SOURCE:

Wow Classic

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. .go c id 9568
2. Check for Creature formations
3. Check for Patroling NPC
4. No chromatic NPCs

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
Can you elaborate on what Removed Chromatic NPCs means?

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Just really need to know what you ment by remove chromatic npcs so i can make a sound assessment of hte pr.

**Comment by claudiodfc** [comment]
There's in Low BlackRock spire Chromatic Whelps and Chromatic Dragonspawn incorrectly placed in Overlord Wyrmthalak's chamber, as displayed on the issue reported.

I removed them since they aren't meant to be there.

Instead, I imported from Vmangos the correct placement for the NPCs and changed them to be like classic since they missed two berserkers.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
> There's in Low BlackRock spire Chromatic Whelps and Chromatic Dragonspawn incorrectly placed in Overlord Wyrmthalak's chamber, as displayed on the issue reported.
> 
> I removed them since they aren't meant to be there.
> 
> Instead, I imported from Vmangos the correct placement for the NPCs and changed them to be like classic since they missed two berserkers.

Gotcha. This PR has my approval.

**Comment by yuzifc** [comment]
Tested, no chromatic NPCs, Patroling NPC and Creature formations as it should be. 👌

https://user-images.githubusercontent.com/70452524/148706782-b274f253-2e49-436d-8e22-7632e9be51ca.mp4

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
We had some changes with the creature table. Can you adjust you sql.

**Comment by claudiodfc** [comment]
There we go @acidmanifesto

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
