### PR TITLE
fix(DB/smart_scripts): Play small event on noble brew part 2 completion

### PR DESCRIPTION
**Pull request by vtihomirov**
## Changes Proposed:
-  Added a SAI query for `Lord Baurles K. Wishock`.
- On quest completion of `A Noble Brew` it will now play a small event.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5222
- Closes https://github.com/chromiecraft/chromiecraft/issues/379

## SOURCE:

https://youtu.be/di1GyozfIU8?t=151

## Tests Performed:

- Tested without the changes: no event is playing on `A Noble Brew` turn in.
- Tested in game on linux/docker setup from windows client.
- Tested with the changes: an event is now playing like in the source video.

## How to Test the Changes:

1. `.quest add 335`
2. `.additem 2779`
3. `.additem 2784`
4. `.go xyz -8980.497070 1025.567139 101.404068 0` and turn in the quest.
5. Accept the next quest or use `.quest add 336`
6. `.go xyz -8559.486328 371.781189 108.385941 0`
7. Observe if an event is playing on quest turn in and if its according to the source video.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by vtihomirov** [comment]
Test result:

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Stifler82 — CHANGES_REQUESTED** [review]
@vtihomirov

I would like to suggest these changes.
Your Fix is good, but some "Details" are missing.
In this my Fix, I have accelerated the NPC's Despawn Time and Respawn Time, to ensure that the next player who has to complete the quest has the NPC "Available" quickly.

```
UPDATE `creature` SET `spawntimesecs` = 15 WHERE `guid` = 79749;

UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 1439;

DELETE FROM `smart_scripts` WHERE (`source_type` = 0 AND `entryorguid` = 1439);
INSERT INTO `smart_scripts` VALUES
(1439, 0, 0, 0, 20, 0, 100, 0, 336, 0, 0, 0, 0, 80, 143900, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - On Quest \'A Noble Brew\' Finished - Run Script'),
(1439, 0, 1, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 41, 5000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - On Just Died - Despawn In 5000 ms'),
(1439, 0, 2, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - On Respawn - Set Emote State 0');

DELETE FROM `smart_scripts` WHERE (`source_type` = 9 AND `entryorguid` = 143900);
INSERT INTO `smart_scripts` VALUES
(143900, 9, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 5, 7, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - Actionlist - Play Emote 7'),
(143900, 9, 1, 0, 0, 0, 100, 0, 3000, 3000, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - Actionlist - Say Line 0'),
(143900, 9, 2, 0, 0, 0, 100, 0, 4000, 4000, 0, 0, 0, 17, 64, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - Actionlist - Set Emote State 64'),
(143900, 9, 3, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - Actionlist - Say Line 1'),
(143900, 9, 4, 0, 0, 0, 100, 0, 5000, 5000, 0, 0, 0, 11, 2596, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Lord Baurles K. Wishock - Actionlist - Cast \'Touch of the Black Claw\'');
```

**Comment by Stifler82** [comment]
@vtihomirov 
This is my Fix
**Video Test:** [A Noble Brew 2/2](https://youtu.be/epvrRHCPkik)

**Comment by vtihomirov** [comment]
@Stifler82 I'm happy to make the adjustments given that there is a source/proof of the changes requested. Please provide a source for the despawn and respawn adjustments required.

**Comment by Stifler82** [comment]
> @Stifler82 I'm happy to make the adjustments given that there is a source/proof of the changes requested. Please provide a source for the despawn and respawn adjustments required.

There are no sources.
My "source" is just a little common sense.
Because if another Player has to do the quest, he will be forced to wait 3 minutes, to complete the quest too, and this doesn't make much sense, since the SAI of this NPC only works "An animation" for a quest..

**Comment by vtihomirov** [comment]
@Stifler82 I agree that changing the respawn and despawn will improve the quality of life for the players, but to me common sense is not the best practice for making it a blizz-like experience e.g. we don't want to make the server easy for players, but 
we want it as close to blizz-like emulation as possible.
I'm sorry but I won't adjust the PR without source of proof. I'm ok to close it if you wish to push your changes.

**Comment by Stifler82** [comment]
> @Stifler82 I agree that changing the respawn and despawn will improve the quality of life for the players, but to me common sense is not the best practice for making it a blizz-like experience e.g. we don't want to make the server easy for players, but
> we want it as close to blizz-like emulation as possible.
> I'm sorry but I won't adjust the PR without source of proof. I'm ok to close it if you wish to push your changes.

@vtihomirov 
Do as you see fit, I just gave you a suggestion.

**Pull request merged**
