### PR TITLE
Core/Vehicle: delay position update in Vehicles, this may be deleted

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
-  Port from TC https://github.com/TrinityCore/TrinityCore/commit/3532173ee340573be937b4c5799c155fa2cc906c

##### TESTS PERFORMED:
- [x] Test in game
- [x] Test in build

##### HOW TO TEST THE CHANGES:
- See https://github.com/TrinityCore/TrinityCore/issues/17634

## How to test AzerothCore PRs 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:
http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Before the test, and after the test, are not found problems

**Comment by FrancescoBorzi** [comment]
good job @Winfidonarleyan 

thanks a lot @pklloveyou !!! you are our testing star!

**Comment by pklloveyou** [comment]
> Before the test, and after the test, are not found problems
Translation error

No issues were found before and after the merge

**Comment by FrancescoBorzi** [comment]
yes, no worries, we got it! :)

**Comment by pklloveyou** [comment]
Okay.

**Comment by Yehonal** [comment]
This PR can be merged

**Comment by Stoabrogga** [comment]
I just tested **without** this PR by going through the steps mentioned here:
https://github.com/TrinityCore/TrinityCore/issues/17634
There was no crash, so why do we need this fix if it does not fix anything?

**Comment by Winfidonarleyan** [comment]
That's a need to ask @Yehonal.

**Comment by Viste** [comment]
@Stoabrogga sunwell have a bit different vehicles system(its only based on TC)

**Comment by Stoabrogga** [comment]
Hmm, ok, so if I understand this correctly: Although we don't suffer the crash it's better to update the passenger's position outside of the the loop which calculates the position?

**Comment by Yehonal** [comment]
RelocatePassengers is a "redundant" method because when you call it the UpdatePosition of Unit is called and it calls again the RelocatePassengers.

So if you don't store the calculation of passenger position before Update it could be some wrong behaviour and in some rare case it can cause a crash.

**Comment by Stoabrogga** [comment]
Ok, now I understand. Thanks for explaining this.

**Pull request merged**
