### PR TITLE
DB/SAI: Fix Arakkoa Egg

### LINKED ISSUE #1209: Arakkoa Eggs in Blades Edge follow the player and attack them
##### EXPECTED BLIZZLIKE BEHAVIOUR:
[Arakkoa Eggs](https://wowgaming.altervista.org/aowow/?npc=20214) should not move around or attack.

##### CURRENT BEHAVIOUR:
[Arakkoa Eggs](https://wowgaming.altervista.org/aowow/?npc=20214) move around and attack the player.

##### STEPS TO REPRODUCE THE PROBLEM:
1.  .gm off
2.  `.go creature 71892`  or  `.go xyz 3224 5295 177 530`
3.  Egg begins attacking player, move around to see it chase you

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
0e16853157cff17dcd59aac490fbd5db3da0b727

##### OPERATING SYSTEM:
Windows 10

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- Prevent the Arakkoa Egg (template ID 20214) from following the player
- Arakkoa Egg will now cast Arakkoa Egg Debuff (ID 35788) if the player is within 6 yards range

I changed the SAI proposed by @wetbrownsauce in #1209 slightly.

##### ISSUES ADDRESSED:
Closes #1209 

##### TESTS PERFORMED:
tested in-game

##### HOW TO TEST THE CHANGES:
see #1209 

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@wetbrownsauce 
I think I found a better script combination. Could you please test once more?

**Comment by wetbrownsauce** [comment]
Tested the new change. Looks good.

Only issue that can sometimes happen is if you dance in and out of combat with the egg you can create periods of delay between the cloud casts but I don't see much of a workaround for that, plus they have 500 hp so what are the odds someone is going to sit there dancing in and out of combat with it lmao

**Comment by Stoabrogga** [comment]
@wetbrownsauce @poszer 
Thanks for testing this and for your feedback. So this should be finally ready to be merged.

**Comment by Maurowin** [comment]
work fine for me

**Comment by BarbzYHOOL** [comment]
Thank you for confirmation @Maurowin !

**Pull request merged**
