### PR TITLE
[WIP] Cpp modernization

### LINKED ISSUE #3451: Remove ACE dependence [$300]
# TASK
- [x] `ASSERT` - #4950
- [x] `Configuration` - #4608
- [x] `Method_Request` - #3459
- [x] `Stack_Trace` #6574
- [x] `Task` #5454
- [x] `Guard_T` - #4821
- [x] `Event_Handler` (signal) - #4877
- [x] `Based` #6574
- [x] `TSS_T` #5454
- [x] `INET_Addr` #6574
- [x] `Reactor` #5679
- [x] `Acceptor` #6574
- [x] `Future` #5611
- [x] `Queue` #5611
- [x] `Basic_Types`
- [x] `Semaphore`  - #4951
- [x] `AutoPtr` - #3454
- [x] `OS_NS_time` - #3455
- [x] `Atomic_Op` - 4a9476b
- `Thread` (there is a separate issue for this with a 150$ bounty: https://github.com/azerothcore/azerothcore-wotlk/issues/99)

**The list will be replenished**

# Steps
- [x] 1. Update `acelite`, set lib to `STATIC` and disable incorrect fix `std::auto_ptr` #3450
- [x] 2. Rework `Config` #3453 
- [x] 3. Delete `AutoPtr` #3454
- [x] 4. Replace `Ace Atomic` 4a9476b
- [x] 5. Replace `Ace Time` #3455
- [x] 6. Replace `ACE_Method_Request` #3459
- [x] 7. Replace `ACE_Configuration` #4608
- [x] 8. Replace `ACE_Thread_Mutex` | `ACE_GUARD` #4821
- [x] 9. Replace `ACE_Event_Handler` #4877
- [x] 10. Replace `ACE_ASSERT` #4950
- [x] 11. Delete `ACE_Semaphore` #4951
- [x] 12. Delete `ACE_TSS` #5454
- [x] 13. Delete `Future` and `Queue` #5611
- [ ] 14. `The end` #6980 and #5679

<bountysource-plugin>

---
There is a **[$300 open bounty](https://www.bountysource.com/issues/92874324-remove-ace-dependence?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by namreeb**
## CHANGES PROPOSED:
-  ACE dependency removed
-  New use of modern C++ threading and async features
-  Boost.Asio dependency introduced

## ISSUES ADDRESSED:
- Closes #3451 #99 

## TESTS PERFORMED:
-  Build works on Windows
-

## KNOWN ISSUES AND TODO LIST:

- [ ] ASIO support
- [ ] Remove ACE
- [ ] CI update

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Mitradis** [comment]
@namreeb need fix merge conflicts

**Comment by abebeos** [comment]
@FrancescoBorzi , are there enough tests to risk such a one-chunk large change? How is the runtime-behavior tested?

**Comment by FrancescoBorzi** [comment]
@abebeos these changes are heavily inspired by the same work done on TrinityCore and CMaNGOS. The author of this PR is the same person who did the job at CMaNGOs.

And of course, we will carefully test this PR before merging it to our master branch. Any help will be welcome.

**Comment by abebeos** [comment]
It is not always a matter of confidence, but of process. Simple, mechanical changes are better send in as separate PR's (as they need minimum review and can be merged quickly).

How is the run-time behaviour tested? Do you have an automated system, or is this done manually by testers?

(as a sidenote: the bounty https://www.bountysource.com/issues/92874324-remove-ace-dependence does not mention ongoing work, possibly this should be updated).

**Comment by FrancescoBorzi** [comment]
@abebeos yes mostly will be manual testing as there are no automated tests in WoW emulation. We are in the process of introducing unit testing here but it's still the beginning, so we can't count on them either.

**Comment by FrancescoBorzi** [comment]
@abebeos I've noticed that you started a solution on Bountysource for this work. Please keep in mind that @namreeb started this first work so he has the right to complete it and claim the bounty. 

You can, of course, step in case he will renounce.

**Comment by abebeos** [comment]
> @abebeos I've noticed that you started a solution on Bountysource for this work. Please keep in mind that @namreeb started this first work already,

Bountysource does not show anyone has started the bounty (which contains usually an estimated delivery date), but even if..

> so he has the right to complete it and claim the bounty.

Anyone has the right, that's how bounties work. Otherwise, just agree to pay someone exclusively for some work (and state it in the bounty).

> You can, of course, step in case he will renounce.

Strictly speaking, he has renounced already.

The question is: do you want to get things done, or do you want to wait for individuals to disappear without notice, not knowing when they come back?

In any way, please clarify your bounty-process, see #3866

**Comment by namreeb** [comment]
> > @abebeos I've noticed that you started a solution on Bountysource for this work. Please keep in mind that @namreeb started this first work already,
> 
> Bountysource does not show anyone has started the bounty (which contains usually an estimated delivery date), but even if..
> 
> > so he has the right to complete it and claim the bounty.
> 
> Anyone has the right, that's how bounties work. Otherwise, just agree to pay someone exclusively for some work (and state it in the bounty).
> 
> > You can, of course, step in case he will renounce.
> 
> Strictly speaking, he has renounced already.
> 
> The question is: do you want to get things done, or do you want to wait for individuals to disappear without notice, not knowing when they come back?
> 
> In any way, please clarify your bounty-process, see #3866

Tell you what, you go ahead.  I don't have time or interest to argue with people.  I was asked to do this.  Good luck!

**Comment by abebeos** [comment]
> Tell you what, you go ahead. I don't have time or interest to argue with people. I was asked to do this. Good luck!

???

Hey @namreeb , I don't argue with you, I hate arguing, but more than this I hate silence.

Here I "argue" re project-processes in general, and was mainly talking to @FrancescoBorzi;

Your contribution history shows activity then weeks break, then again activity, then weeks break, so naturally, i expected that you entered a "weeks break" phase.

In any way, how is the completion grade of your work, can you tell?

And possibly what caused the build-failure within 0a714d8, you managed to fix this?

**Comment by Kitzunu** [comment]
Closing as Winfi is doing this in other PRs

**Pull request closed without merging**
