### PR TITLE
fix(DB/Spells): Hallows End candies should not give Well Fed buff.

### LINKED ISSUE #13595: [Hallow's End] Candy Bars and Lollipops give well fed buff while they are being eaten
https://github.com/chromiecraft/chromiecraft/issues/4313
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

Both of these halloween candies give well fed buff for stamina and spirit (25% of your level), while you are eating them. When you stop eating, the buff goes away. Replaces proper well fed buffs like clamlette magnifique.

### Expected Blizzlike Behaviour

They should only restore 3% of your health and don't give a well fed buff.

### Source

not mentioned in tooltips
https://wotlkdb.com/?item=20390
https://wotlkdb.com/?item=20388

not on list of well fed foods
https://wowpedia.fandom.com/wiki/Well_Fed?oldid=2129966

not mentioned in comments
https://www.wowhead.com/wotlk/item=20390/candy-bar#comments
https://www.wowhead.com/wotlk/item=20388/lollipop#comments

### Steps to reproduce the problem

.additem 20390
.additem 20388

also try .additem 33004 to show it knocks off buff

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #13595

## Issues Addressed:

- Closes #13595
- Closes https://github.com/chromiecraft/chromiecraft/issues/4313

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.additem 20390`
`.additem 20388`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
Tested on local - everything works okay.

**Comment by Nefertumm** [comment]
I have the exact same issue Beef described.

**Comment by UltraNix** [comment]
@Nefertumm So can I test it? On my local everything works okay.

**Comment by UltraNix** [comment]
@Nefertumm @BeefSteaker

**Comment by BeefSteaker** [comment]
>  So how can I test it? On my local everything works okay.

I just ran the SQL on a fresh install. Can't think of any reason my setup would be different

**Comment by UltraNix** [comment]
So I'm closing this one as it does not work.

**Comment by avarishd** [comment]
The PR was correct 😀 Just the wrong column name

**Pull request closed without merging**
