### PR TITLE
feat(DB/translations): import quest_template, quest_request_items and quest_offer_reward from TC

### PR DESCRIPTION
**Pull request by Helias**
**import quest_template, quest_request_items and quest_offer_reward from TC**

I imported 1k text quest_template_locale of zhTW (chinese text) @mpfans
Several texts for esMX, esES @Si1ker, @pangolp 

No `deDE` texts found, this means that we have a lot of `deDE` texts @LukasVolgger  :+1: .
About 60 `ruRU` texts @Winfidonarleyan.

## Tests Performed:
- executed the script twice (without the insert into of revision for the second time)

## How to Test the Changes:
- execute the SQL script twice

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]
tbf I would expect these to be correct out of the bat =)

**Comment by Helias** [comment]
Me too :+1:

**Comment by mpfans** [comment]
Who can I contact? I can provide all Chinese localization (zhCN)

**Review by LukasVolgger — APPROVED** [review]

**Comment by LukasVolgger** [comment]
> Who can I contact? I can provide all Chinese localization (zhCN)

@mpfans You can share it here or in our discord channel https://discord.gg/jznfFWQr

**Comment by mpfans** [comment]
tyvm @LukasVolgger     [ac-zhCN.zip](https://github.com/azerothcore/azerothcore-wotlk/files/5745946/ac-zhCN.zip)

only a few of them have not been translated

**Comment by LukasVolgger** [comment]
Testes SQL script - everything fine!

/* Datei "rev_1609102998767361464.sql" ausgeführt, mit 13 Abfragen und 13.401 betroffenen Zeilen */
/* 1 Datei(en) verarbeitet, in 00:00:01.3 */

@mpfans thx for the files! Where you got those? @Helias, please have a look at this as you are the data specialist here <3

**Comment by Helias** [comment]
Thank @mpfans  and @LukasVolgger, I will take care of these new data :wink:

**Comment by Helias** [comment]
What about put "To Be Merged"?

**Comment by LukasVolgger** [comment]
For me it's okay, or if you wan't we can wait for the pending reviews.

**Review by Si1ker — APPROVED** [review]
good for Spanish.

**Pull request merged**
