### PR TITLE
fix(Spells/SpellInfoCorrections) PVP in area 52

### PR DESCRIPTION
**Pull request by pangolp**
Co-authored-by: Jelle Meeus <jellemeeus@hotmail.com>

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17186
- Closes https://github.com/chromiecraft/chromiecraft/issues/5120

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. .`tele area52` with 2 opposite faction player
2. Fight inside Area 52
3. The guards will start hitting you if you put up a fight.

https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/a38a081a-b080-432a-add6-4312123e19d6

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pvp100com** [comment]
I tested this PR, when I attack hostile players, the guards will immediately attack me. after I am killed by the guards and resurrected, they still attack me. I remain unable to attack these guards.

I'm not sure if this meets expectations. thank you.

**Comment by pangolp** [comment]
> I tested this PR, when I attack hostile players, the guards will immediately attack me. after I am killed by the guards and resurrected, they still attack me. I remain unable to attack these guards.
> 
> I'm not sure if this meets expectations. thank you.

According to the videos we were watching, no player can attack the guards. The guards are there to prevent pvp from being done in the area. So we assume that's what should happen, but if anyone has more information, we'll check it out.

**Comment by pvp100com** [comment]
After being killed by guards, you will still be marked as hostile by them and they will continue to attack. and waiting for a few minutes, the guards will return to a friendly state. If that's as expected, It worked really well.

**Comment by pangolp** [comment]
> After being killed by guards, you will still be marked as hostile by them and they will continue to attack. and waiting for a few minutes, the guards will return to a friendly state. If that's as expected, It worked really well.

Thanks for the tests. Could you try the other gobbin areas, such as `Booty Bay` and `Tanaris`? Just in case, those mechanics have not been broken, although that should not happen.

**Comment by pvp100com** [comment]
After testing, it was found that the “Faction” of guards in Tanaris is “475”. Therefore, when I attack hostile players, the guards will retaliate against me. In contrast to this PR (Faction = 1857 and 1806), when I die and respawn, the guards will no longer continue to attack me and will treat me as friendly.

If possible, I think the effect of this PR should be consistent with Tanaris. thank you.

**Comment by pangolp** [comment]
> After testing, it was found that the “Faction” of guards in Tanaris is “475”. Therefore, when I attack hostile players, the guards will retaliate against me. In contrast to this PR (Faction = 1857 and 1806), when I die and respawn, the guards will no longer continue to attack me and will treat me as friendly.
> 
> If possible, I think the effect of this PR should be consistent with Tanaris. thank you.

It is difficult to achieve this effect, because the problem is that the area 52 faction is friendly by default. On the other hand, in Tanaris, she is not friendly. The problem is in the DBC. We have to eliminate the default behavior. I don't know if we can achieve the same effect as in Tanaris, however, I would fix the problem, and then if anything, I would improve it. But today it doesn't even work. I would like to add it, and then improve it in another pull request.

Thanks for the tests.

**Comment by pangolp** [comment]
Anyway, there's no rush to merge it. We can wait, find out a little more, and see if we can achieve the same effect as in Tanaris. Although it will depend on the evidence we have in this regard. I really don't know how it works on the official servers.

**Comment by pvp100com** [comment]
Ratchet guard (637) and Booty Bay guard (121) are the same as Tanaris. For your reference, thank you.

**Comment by jellemeeus** [comment]
The goblin guards at K3 Storm Peaks suffer from the same issue. I can't think of any other goblin guards

K3 Bruiser, faction 1812

tp to K3
```
.go xyz 6124 -1023 409.1 571 4.67
```

**Comment by pangolp** [comment]
And then they say that I don't like giving credits, but this time, I think I got out of hand.

**Comment by pangolp** [comment]
This is a disaster, nothing is understood, I better close this and create it again.

**Pull request closed without merging**
