### PR TITLE
fix(DB/SAI) Serpentshrine Sporebat now use correct charge

### PR DESCRIPTION
**Pull request by v-mstrs**
## Changes Proposed:
-  Serpentshrine Sporebat now use correct charge

## Issues Addressed:

-  

## SOURCE:

https://www.wowhead.com/wotlk/npc=21246/serpentshrine-sporebat#abilities;mode:n25
## Tests Performed:

- Tested, works

## How to Test the Changes:

1. .npc add 21246

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
IDs line up with other Sporebat spells but all other cores use 22120
I'll wait until a sniff.

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers @azerothcore/testers can anyone please check this?

**Comment by elthehablo** [comment]
> @azerothcore/developers @azerothcore/testers can anyone please check this?

Looks like the right ID as discussed in https://github.com/azerothcore/azerothcore-wotlk/pull/16985. Should be good to merge then the PR mentioned here can adjust the timers and the spore burst maybe?

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
superseded by https://github.com/azerothcore/azerothcore-wotlk/pull/16985

**Pull request closed without merging**
