### PR TITLE
FIX [Target is in line of sight through the Texture] [$20]

### LINKED ISSUE #281: Target is in line of sight through the Texture [$40]
**Description**: If someone casts any spell, the texture is ignored, allowing you to attack or being attack, out of sight of the target. This happens in PvE and PvP.

**Current behaviour**: If a player is hidden behind a mountain without having a visual on the target, it can be hit without any problems through the texture.

**Expected behaviour**: Target is not in line of sight, so it wouldn't be possible to cast any spell.

**Steps to reproduce the problem**:

1. Take two characters and bring them on any map.
2. Hide a character under a hill or a mountain, and the other character above, without it being possible to see the hidden target.
3. You have to cast any spell to the target over the mountain, or vice versa.

These two images should help you understand the problem:

1. http://tinypic.com/view.php?pic=24v4bb9&s=9#.WFJPhqnrxwE
2. http://tinypic.com/view.php?pic=2a4wfh5&s=9#.WFJPQ6nrxwF

In these images we understand that none of the characters should be attacked because it is out of the target view.

When he was tested: it was tested on 14.12.2016 with the presence of a staff member to confirm the obvious problem.

**AC hash/commit**:  9d0c8dc71bb867218a949644b72592b452a7e62b

**Operating system**:  Windows 10 64bit

[Bountysource](https://www.bountysource.com/issues/40153074-target-is-in-line-of-sight-through-the-texture?utm_source=40153074&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### PR DESCRIPTION
**Pull request by sucofog**
**Changes proposed:**

* Rewrite VMaps and MMaps - fixes issue with invisible walls causing LoS errors and wrong pathing in some places.
* Updated MMaps to official TC (up-to-date)
* Update area storage - from TC.
* Implement map out of bound info.
* Fix creatures that should block incoming AoE spells.
* Closes #281 (Needs testing RE-Extracting Vmaps/Maps/MMaps/DBC's)

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:** Closes #281 

**Tests performed:** Builds fine, TEST REQUIRED.

**Known issues and TODO list:**

- Target is in line of sight through the Texture.

### CODE REVIEW

**Comment by sucofog** [comment]
Tested commits:

* https://github.com/azerothcore/azerothcore-wotlk/pull/405/commits/954154c2a7a013c3f442f3b0d4dc9c96d12b5862

* https://github.com/azerothcore/azerothcore-wotlk/pull/405/commits/f478c45c3ecda7291952c80830cb7ac601d913b5

**Bug LOS Persists, totally broken LoS through textures.**

Pending to test:

* https://github.com/azerothcore/azerothcore-wotlk/pull/405/commits/7d78d7adc84940c84b3e3f3a01b493c9af51ecd2

**Comment by Irome** [comment]
Any news about this?

**Comment by sucofog** [comment]
I'm little busy nowadays @Irome i'll will continue asap

**Comment by JunkyBulgaria** [comment]
atleast give credits to the proper author of the code

**Comment by sucofog** [comment]
What are you talking about @JunkyBulgaria  ?

Credits are in the commit, it's ported from SC, check commit:

image

If this is a fix by TC it's not specified at the original commit where this comes from, that is @Maczuga 

Cheers buddy!

**Comment by ShinDarth** [comment]
any news about this one?

**Comment by Inifield** [comment]
It's not enough, LoS problem still there and you'll crash/weird behavior from npc

**Comment by Yehonal** [comment]
Closing because issue has been flagged as invalid. Thanks for contribution

**Pull request closed without merging**
