### PR TITLE
Fix new bugs created by new Pathfinding System + Refactor some Code

### LINKED ISSUE #4247: Eye of the Storm Emissary constantly falling in Darnassus
##### CURRENT BEHAVIOUR:
One EotS Emissary in Darnassus is constantly falling while pathing in Darnassus while the partner paths normally.  Pathing coords issue?

https://i.imgur.com/zgeZHua.jpg
https://i.imgur.com/Aic7Lu7.jpg
https://i.imgur.com/eHrPurE.jpg (has npc info in it)

##### EXPECTED BLIZZLIKE BEHAVIOUR:
NPC is supposed to path normally like the counterpart seen in the SS.

##### STEPS TO REPRODUCE THE PROBLEM:
1. .tele darnassus
2. look for EotS emissary pathing near entrance
3. wait for them to path towards the entrance, the one on the right (if behind) will constantly fall

##### AC HASH/COMMIT:

7cf097eab2fc

##### OPERATING SYSTEM:
Win10

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95823990-eye-of-the-storm-emissary-constantly-falling-in-darnassus?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Footman**
## Changes Proposed:
- fix issue with creatures spawning under map (for example Violett Hold portal guards)
- fix issue with hunter trap placement in some areas like dalaran, probably some other objects and in general refactor summon code used by spell
- fix issue with mob moving back too far or too close to the player making it hard to control boss in raids like ICC

## Issues Addressed:
- Closes  #4247 #4203

## Tests Performed:
- Compiled
- Tested locally in different instanced and with different NPCs

## Target Branch(es):
- [x] pathfinding-refactor

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Footman** [comment]
Fixxed two more issues:
1. Crash for some teleporting spells when map grid in target location is not loaded
2. Mage Blink not working in arena

**Comment by Footman** [comment]
Refactored more code for spell target position finding

**Comment by Helias** [comment]
I am reverting the NPC repositioning and a lot of functions related to it to not keep on master a lot of issues caused by it.
Can I merge this PR into this https://github.com/azerothcore/azerothcore-wotlk/pull/4220 to make all of these improvements at once and test them at once?

**Comment by Footman** [comment]
> I am reverting the NPC repositioning and a lot of functions related to it to not keep on master a lot of issues caused by it.
> Can I merge this PR into this #4220 to make all of these improvements at once and test them at once?

this pull request is based on @Yehonal branch and is fixing all issues. So basically dont need to revert master after this

**Comment by Helias** [comment]
Ok, anyway I think that we can already merge this to import your fixes in his branch

**Comment by Helias** [comment]
please @Footman fix the build

**Comment by Footman** [comment]
> please @Footman fix the build

what do you mean? it has no issues

**Comment by Helias** [comment]
@Footman tell me when this PR is finished, than I will merge it into the Yehonal PR ;-)

**Comment by Footman** [comment]
> @Footman tell me when this PR is finished, than I will merge it into the Yehonal PR ;-)

it is finished

**Comment by Helias** [comment]
ok @Footman, merged

**Comment by FrancescoBorzi** [comment]
thanks for your contribution @Footman

**Pull request merged**
