### PR TITLE
fix(DB/Creature): Removed permanent root from Nergeld.

### LINKED ISSUE #12218: [quest] `The Sum is Greater than the Parts` bug
### Current Behaviour

Boarding `Nergeld` does not refresh the monster

https://youtu.be/9tAtaPlEgRw

### Expected Blizzlike Behaviour

Boarding `Nergeld` will refresh the monster

https://www.youtube.com/watch?v=PKr2j4T38xI

### Source

_No response_

### Steps to reproduce the problem

1. additem 42772
2. .go c id 30403
3. mounted on the `Nergeld`

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12218

## Issues Addressed:

- Closes #12218

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.additem 42772`
`.go c id 30403`
mount on the Nergeld

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
tested , not work,

https://www.youtube.com/watch?v=9tAtaPlEgRw

It's still the same as this video

**Comment by UltraNix** [comment]
@mpfans Tested on my local and works okay now.

**Comment by mpfans** [comment]
need @azerothcore/testers

**Comment by mpfans** [comment]
I retested and found that 'nergeld' could move, but no monsters appeared Please watch this video, `nergeld` can't be moved
https://youtu.be/PKr2j4T38xI?t=52

After testing, the constant mount 'nergeld' and dismount 'nergeld' can refresh the monster
test video:
https://youtu.be/VDyqmzt4YxI

**Comment by Maelthyrr** [comment]
It's just a misunderstood with your issue. @UltraNix Nergeld should stay "rooted". The issue with this quest is that no monsters appear corectly when it's mounted. As you can see on videos, they spawn by waves.

**Comment by mpfans** [comment]
> It's just a misunderstood with your issue. @UltraNix Nergeld should stay "rooted". The issue with this quest is that no monsters appear corectly when it's mounted. As you can see on videos, they spawn by waves.

You're right

**Comment by UltraNix** [comment]
@Maelthyrr @mpfans Test now.

**Comment by mpfans** [comment]
tested and work

**Review by acidmanifesto — APPROVED** [review]

**Comment by mpfans** [comment]
please detele this  `UPDATE `creature_template` SET `unit_flags`=`unit_flags`|4 WHERE `entry`=30403;`

Because the current database is correct, there is no need to +4   @UltraNix

**Comment by mpfans** [comment]
> please detele this `` UPDATE `creature_template` SET `unit_flags`=`unit_flags`|4 WHERE `entry`=30403; ``
> 
> Because the current database is correct, there is no need to +4 @UltraNix

Your previous commitment was not to merge into the master branch, so you don't need to do +4 operations @UltraNix

**Comment by UltraNix** [comment]
It's only bitwise operation, so no worry about it.

**Comment by mpfans** [comment]
> It's only bitwise operation, so no worry about it.

I know, but there's no need to add this line update at all

**Comment by UltraNix** [comment]
@mpfans Removed.

**Comment by mpfans** [comment]
> @mpfans Removed.

tyvm....

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
