### PR TITLE
fix(Script/Nexus): Anomalus rift spawning/ empowering timings and Rift Shield cancellation

### PR DESCRIPTION
**Pull request by peti446**
## CHANGES PROPOSED:
-  Changed the range of charge rifts so it will only charge nearby rifts
- Added smart script to rifts so that when they are destroyed they notify the boss, to cancel the shield.
-  Changed script so that more rifts can be spawned and he shields himself correctly after 51% hp. Will shield once and then spawn a normal rifts, repeat afterwards.
Reference: https://www.youtube.com/watch?v=Flydqb6fuGM

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3274

## TESTS PERFORMED:
- Fight against Anomalus in HC and Normal, checked time between spawns of rifts and rift shields.

## HOW TO TEST THE CHANGES:

1. Set dung to normal or hc
2.  .go c 126599
3. Start boss and check that more than one rift spawns
4. Damage boss to bring him below 51%
5. Check boss now starts to shield himself every so often.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Kitzunu** [comment]
Before we merge this I want to know exactly what is changed in the DBC from the original

**Comment by FrancescoBorzi** [comment]
@Kitzunu please discuss with @peti446

**Comment by peti446** [comment]
@Kitzunu The only change done to the spell is the radius (column EffectRadiusIndex_1) to 45 (value 11 in the specific column) instead of maximum radius, to avoid it targeting wrong rifts. Everything else has not been changed.

**Comment by Kitzunu** [comment]
as long as it doesnt mess with anything I'm happy :D

**Comment by Kitzunu** [comment]
Thank you for the PR!

**Pull request merged**
