### PR TITLE
feat(Core/Items): Implemented elemental weapon damage. Source: Trinit…

### LINKED ISSUE #12165: Feature: Elemental weapon damage
### Describe your feature request or suggestion in detail

**Suggestion:** When a weapon has a dmg_type1 other than 0, the damage dealt by it on autoattack will be that school of damage.

Currently on AzerothCore when you set a weapon to deal purely spell damage, it still deals physical damage on hit. Weapons dealing all spell damage isn't exactly blizzlike, but it works on vanilla cores so it should be possible to implement as a custom feature.

### Describe a possible solution to your feature or suggestion in detail

_No response_

### Additional context

image
image
image

### PR DESCRIPTION
**Pull request by UltraNix**
…yCore.

Closes #12165

## Issues Addressed:

- Closes #12165

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/12165)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
```
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Entities/Unit/Unit.cpp:1452:54: fatal error: unused parameter 'damage' [-Wunused-parameter]
void Unit::CalculateMeleeDamage(Unit* victim, uint32 damage, CalcDamageInfo* damageInfo, WeaponAttackType attackType, const bool sittingVictim)
```
from checks

**Comment by Gultask** [comment]
Tested with custom melee weapons with fixed elemental damage.
Please give me any more ideas of what to test, this is everything I came up with so far:

Only arcane damage is affected by resistances, while other types of damage **have no partial resists nor full resists**.
Wands and melee elemental damage bypasses immunities such as elementals. Even for arcane damage.

Melee weapon damage is increased by Ossirian Crystal debuff (Fire Weakness, Frost Weakness, etc)
Wand damage is not affected by Ossirian Crystal debuff

Melee weapon damage is increased and decreased by Chromaggus Elemental Shield.
Wand damage is not affected by Chromaggus Elemental Shield.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Comment by UltraNix** [comment]
@Gultask I need all items you used during the tests.

**Comment by Gultask** [comment]
Wands:
Excavation Rod: `.additem 5246`
Moonbeam Wand: `.additem 5818`
Gravestone Scepter: `.additem 7001`
Spellcrafter Wand: `.additem 6677`
Freezing Shard: `.additem 10572`

Melee Weapons:
```
DELETE FROM `item_template` WHERE `entry` BETWEEN 60001 AND 60006;
INSERT INTO `item_template` (`entry`, `class`, `subclass`, `SoundOverrideSubclass`, `name`, `displayid`, `Quality`, `Flags`, `FlagsExtra`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `RequiredSkill`, `RequiredSkillRank`, `requiredspell`, `requiredhonorrank`, `RequiredCityRank`, `RequiredReputationFaction`, `RequiredReputationRank`, `maxcount`, `stackable`, `ContainerSlots`, `StatsCount`, `stat_type1`, `stat_value1`, `stat_type2`, `stat_value2`, `stat_type3`, `stat_value3`, `stat_type4`, `stat_value4`, `stat_type5`, `stat_value5`, `stat_type6`, `stat_value6`, `stat_type7`, `stat_value7`, `stat_type8`, `stat_value8`, `stat_type9`, `stat_value9`, `stat_type10`, `stat_value10`, `ScalingStatDistribution`, `ScalingStatValue`, `dmg_min1`, `dmg_max1`, `dmg_type1`, `dmg_min2`, `dmg_max2`, `dmg_type2`, `armor`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `delay`, `ammo_type`, `RangedModRange`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `spellppmRate_1`, `spellcooldown_1`, `spellcategory_1`, `spellcategorycooldown_1`, `spellid_2`, `spelltrigger_2`, `spellcharges_2`, `spellppmRate_2`, `spellcooldown_2`, `spellcategory_2`, `spellcategorycooldown_2`, `spellid_3`, `spelltrigger_3`, `spellcharges_3`, `spellppmRate_3`, `spellcooldown_3`, `spellcategory_3`, `spellcategorycooldown_3`, `spellid_4`, `spelltrigger_4`, `spellcharges_4`, `spellppmRate_4`, `spellcooldown_4`, `spellcategory_4`, `spellcategorycooldown_4`, `spellid_5`, `spelltrigger_5`, `spellcharges_5`, `spellppmRate_5`, `spellcooldown_5`, `spellcategory_5`, `spellcategorycooldown_5`, `bonding`, `description`, `PageText`, `LanguageID`, `PageMaterial`, `startquest`, `lockid`, `Material`, `sheath`, `RandomProperty`, `RandomSuffix`, `block`, `itemset`, `MaxDurability`, `area`, `Map`, `BagFamily`, `TotemCategory`, `socketColor_1`, `socketContent_1`, `socketColor_2`, `socketContent_2`, `socketColor_3`, `socketContent_3`, `socketBonus`, `GemProperties`, `RequiredDisenchantSkill`, `ArmorDamageModifier`, `duration`, `ItemLimitCategory`, `HolidayId`, `ScriptName`, `DisenchantID`, `FoodType`, `minMoneyLoot`, `maxMoneyLoot`, `flagsCustom`, `VerifiedBuild`) VALUES
(60006, 2, 7, -1, 'Teebu\'s Holy Longsword', 19997, 4, 0, 0, 1, 364684, 72936, 13, -1, -1, 65, 60, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1000, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2, '', 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 0, '', 65, 0, 0, 0, 0, 12340),
(60005, 2, 7, -1, 'Teebu\'s Arcane Longsword', 19997, 4, 0, 0, 1, 364684, 72936, 13, -1, -1, 65, 60, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1000, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2, '', 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 0, '', 65, 0, 0, 0, 0, 12340),
(60004, 2, 7, -1, 'Teebu\'s Shadowy Longsword', 19997, 4, 0, 0, 1, 364684, 72936, 13, -1, -1, 65, 60, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1000, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2, '', 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 0, '', 65, 0, 0, 0, 0, 12340),
(60003, 2, 7, -1, 'Teebu\'s Nature Longsword', 19997, 4, 0, 0, 1, 364684, 72936, 13, -1, -1, 65, 60, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1000, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2, '', 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 0, '', 65, 0, 0, 0, 0, 12340),
(60002, 2, 7, -1, 'Teebu\'s Chilling Longsword', 19997, 4, 0, 0, 1, 364684, 72936, 13, -1, -1, 65, 60, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1000, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2, '', 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 0, '', 65, 0, 0, 0, 0, 12340),
(60001, 2, 7, -1, 'Teebu\'s Warming Longsword', 19997, 4, 0, 0, 1, 364684, 72936, 13, -1, -1, 65, 60, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 1000, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1, 2, '', 0, 0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 105, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 225, 0, 0, 0, 0, '', 65, 0, 0, 0, 0, 12340);

```
and `.additem 60001` `.additem 60002` `.additem 60003` `.additem 60004` `.additem 60005` `.additem 60006`

**Comment by UltraNix** [comment]
`Only arcane damage is affected by resistances, while other types of damage have no partial resists nor full resists.`
obraz_2022-09-25_100337464

Tested with fire wand and fire weapon with `58740` aura on dummy.

`Wands and melee elemental damage bypasses immunities such as elementals. Even for arcane damage.` What do you mean by`immunities `?  Absorption auras like `53911` works okay.
obraz_2022-09-25_100746620

Remember that spells like `Divine Shield` works only with spells (includin wands), not melee. `Blessing of Protection` works only with phsycial melee.

`Melee weapon damage is increased by Ossirian Crystal debuff (Fire Weakness, Frost Weakness, etc)`
`Melee weapon damage is increased and decreased by Chromaggus Elemental Shield.`
It should be increased, because like you posted in 1. sentence, all elemental damage is modified by school resistances and auras.

`Wand damage is not affected by Ossirian Crystal debuff`
`Wand damage is not affected by Chromaggus Elemental Shield.`
Fixed.

@Gultask Please, retest it.

**Comment by Gultask** [comment]
Oh, yes, I posted that to show the differences between melee and wands, I  should've worded it better 😛 

For the partial resistances, I tested it with creatures that have entries in the creature_template_resistances table, such as Ossirian, that has 1000 resistances to every school.
Tested again:
image

For the immunities I tested elementals such as Burning Exile (`.go c id 2760`)
Tested again:
image

**Comment by Gultask** [comment]
Oh yes, I forgot about re-testing Ossirian and Chromaggus' weaknesses. They work fine now with wands.

**Comment by UltraNix** [comment]
`For the partial resistances, I tested it with creatures that have entries in the creature_template_resistances table, such as Ossirian, that has 1000 resistances to every school.` 
I see Ossirian has only 1000 resistance to arcane.

**Comment by UltraNix** [comment]
@Gultask 
`For the partial resistances, I tested it with creatures that have entries in the creature_template_resistances table, such as Ossirian, that has 1000 resistances to every school.`
I see Ossirian has 1000 resistance only to arcane.

**Comment by UltraNix** [comment]
`For the immunities I tested elementals such as Burning Exile (.go c id 2760)`
It's `SPELL` school immunity, not melee.

**Comment by Gultask** [comment]
I messed up Ossirian in another PR. I'm sorry 🤦

**Comment by UltraNix** [comment]
@Gultask So everything is okay now?

**Comment by Gultask** [comment]
I'll try again ASAP

**Comment by Gultask** [comment]
This is WotLK Classic. Wands are affected by spell immunities.

image

**Comment by Gultask** [comment]
Yes, my mistake. The resistances look fine, sorry about that.
Only the immunities left, I think.

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Gultask** [comment]
- [X] Immunities on wands work.
- [ ] Immunities on melee register as a 'miss' and not 'immune', but in this case I don't know the correct behaviour.
- [X] Resistances on wands work.
- [X] Resistances on melee work.
- [X] Ossirian's weaknesses work.
- [X] Chromaggus' weaknesses work.
- [ ] Frost attacks on Viscidus with wands or melee do not count towards the hit counter, but I believe that's for another PR?

**Comment by UltraNix** [comment]
`Immunities on melee register as a 'miss' and not 'immune', but in this case I don't know the correct behaviour.` It's blizzlike in this case.
`Frost attacks on Viscidus with wands or melee do not count towards the hit counter, but I believe that's for another PR?` Out of scope of this PR.

**Comment by Gultask** [comment]
Then I think it's all good. Or at least I don't know what else to test 👍

**Comment by UltraNix** [comment]
@Gultask Melee immunity should be okay now.

**Comment by Gultask** [comment]
Spell, melee and wand immunities still work ok 👍

**Comment by UltraNix** [comment]
@Gultask Viscidus should be okay as well :)

**Comment by Gultask** [comment]
😮 
Tested latest commit.
Wand work now with Viscidus but not melee, but to be honest I don't see how that could be a problem xd
Spells still work as intended with Viscidus.
Thanks!

**Comment by UltraNix** [comment]
@Gultask Big kudos to you for testing this :)

**Comment by Gultask** [comment]
Thanks for making the PR ^^

**Comment by Gultask** [comment]
Merge conflicts due to QAston

**Review by Nefertumm — APPROVED** [review]

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
