### PR TITLE
fix(DB/SAI): Change target type in Someone Else's Hard Work Pays Off …

### PR DESCRIPTION
**Pull request by Nyeriah**
…credit script

## Changes Proposed:
-  Change target from nearest player to invoker party, needs test
-  

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4566
- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
If this is ready to be tested, please include testing steps.

**Comment by Nyeriah** [comment]
Testing steps are included in the report. Nothing out of ordinary other than doing the quest, plain and simple

**Comment by heyitsbench** [comment]
Tested. Not mentioned in the report, but there seem to be quite a few issues with the RP, relating to timings/lines said at wrong times. Did not get credit for the quest with this PR.

**Comment by Nyeriah** [comment]
Thanks for testing 👍

**Pull request closed without merging**
