### PR TITLE
fix(Core/Guild): disable invite if players diff factions

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
-  Disable invite if players diff factions

## Issues Addressed:
- Closes https://github.com/azerothcore/mod-cfbg/issues/19

## Tests Performed:
- No

## How to Test the Changes:
- https://github.com/azerothcore/mod-cfbg/issues/19
```
GIVEN THAT the Crossfaction-guild option is DISABLED
and I am an Ally character
AND I join BG
AND I'm playing as Horde player inside the BG
THEN during the BG, I can't join any Ally guild (wrong)
AND I can join Horde guilds (wrong)
```

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can't you test this yourself? testing is part of the job, otherwise you have to split the bounty with the tester :)

**Comment by Sedatyf** [comment]
> > Tests Performed: No
> 
> @Winfidonarleyan can't you test this yourself? testing is part of the job, otherwise you have to split the bounty with the tester :)

I can test it but I won't take any money from the bounty. @Winfidonarleyan worked for it, so it's him/her 😄

**Comment by Winfidonarleyan** [comment]
Tested
image

**Comment by Sedatyf** [comment]
> Tested
> image

Nice! Lemme know if you want me to test it @FrancescoBorzi

**Comment by Winfidonarleyan** [comment]
> > Tested
> > image
> 
> Nice! Lemme know if you want me to test it @FrancescoBorzi

If can - go

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
it's ok, thanks guys!

**Pull request merged**
