### PR TITLE
fix(DB/Gameobject): Sniffed Values for 'Fire' spawns

### PR DESCRIPTION
**Pull request by sudlud**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [x] Sniffs (remember to share them with the open source community!)

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
How can I test this pull request?
What should be the change I should see?

**Comment by sudlud** [comment]
> How can I test this pull request?
> 
> What should be the change I should see?

What I'm doing in these kind of PRs is "merging" the existing spawns in DB with the spawns in my sniffed data.

Anything that already existed before PR and only gets updated is in the first section "updated spawns" in the sql file.

Anything that was in the sniffs but didn't exist gets added to the DB and is in the second section "new spawns" in the sql file.

So for testing I myself usually visit all new spawns in game and check if "they make sense" and are not related to any event / should be spawned by script instead etc.

For the updated spawns I actually look at the sql diff before PR vs. after PR and only visit the locations in game which coordinates actually got changed.

All in all anything I'm doing here is definitely based on sniffs 🙂

**Comment by sudlud** [comment]
Is there any issue with this PR or can it be merged maybe

**Comment by pangolp** [comment]
Is this a sniff? I really don't have a way to test it at this moment. But if at least one person tests it, he estimates that they could merge.

**Pull request merged**
