### PR TITLE
chore(git): Add a commit template & introduce new guidelines

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
##### CHANGES PROPOSED:

Introduce new guidelines for commit titles and descriptions:
- More useful and unique commit titles
- Useful descriptions
- Maybe the use of automated changelogs in the future (see link)

https://www.conventionalcommits.org/en/v1.0.0-beta.2/

##### TESTS PERFORMED:

Yeah, that works fine.

##### HOW TO TEST THE CHANGES:

- Merge the PR and run the new script in `apps/git_tools/setup_git_commit_template.sh`
- Create a new file `touch testaa`
- Git add the file `git add testaa`
- Git commit `git commit`

See the commit message. It probably works in all the GUI too.

##### KNOWN ISSUES AND TODO LIST:

- [ ] Need to update the wiki to include this in the build process `Run this script with git bash (or just bash) apps/git_tools/setup_git_commit_template.sh`
- [ ] Need to warn OLD users (and notably contributors) to run this script as soon as this PR is accepted :(

If we wanted to set a common .gitconfig to all contributors, we could instead put everything in a .gitconfig and then force read it with this `git config --local include.path ../.gitconfig ` but I only added the git commit template atm so I didn't do that

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL checked, liked, tested, works.

Feel free to merge

**Comment by BarbzYHOOL** [comment]
Ah ok I thought it had already been merged because you adopted the naming convention :P

Ok, as soon as I edit the wiki and warn people I'll merge this

Also we'll just ask people to run the git config command when they make a PR that is not using this naming convention and we can fix when merging the PR

so all should be fine

**Comment by FrancescoBorzi** [comment]
yes please, also because since I tested this I cannot do `git commit` without `-m` because it will fail not finding your script ^_^

**Comment by BarbzYHOOL** [comment]
oh yeah i had this issue, lol

if you want to remove it for now, just type `git config -e` and remove the line about it :D

**Comment by BarbzYHOOL** [comment]
Or I just misunderstood what you meant :P

**Comment by Pondaveia** [comment]
@BarbzYHOOL When will you merge this bad boy?

**Comment by Deku** [comment]
Since there are no more objections, I will merge this.

**Pull request merged**
