### PR TITLE
refactor(Core/BG): improvements to the queue system

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## CHANGES PROPOSED:
-  Apply CLang tidy improvements

## TESTS PERFORMED:
- Build run, etc...
- Tested queuing BG in game

## HOW TO TEST THE CHANGES:

- Try to make BG starts in all possible combination (e.g. all cases described here: https://github.com/azerothcore/azerothcore-wotlk/pull/3082)

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Yehonal** [comment]
can you please give the writing access to your PR branch?

**Comment by Yehonal** [comment]
Lol, the improving for code quality is failing on Quality review

**Comment by FrancescoBorzi** [comment]
> Error getting analysis status for this pull request.

I can't see what's wrong

**Comment by Kitzunu** [comment]
Codacy/PR Quality Review — **Codacy was unable to analyse your pull request.**

The error is just that Codacy didn't run :)

**Comment by diluh** [comment]
Tested along with that other PR #3082 worked very good!

- Prevent new Battlegrounds to start if there are already other Battlegrounds that have free slots

**Comment by FrancescoBorzi** [comment]
@Kitzunu this is not really "high" priority, however due to its nature, this PR is likely to easily get merge conflicts. That's why I flagged this as "high priority" and I'd like to merge it soon-ish

**Pull request merged**
