### PR TITLE
fix(Core/Spell): rogue's poisons logic check

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
Co-Authored-By: Yehonal yehonal.azeroth@gmail.com

## CHANGES PROPOSED:

-  Fix logic in an `if` block where a condition was always returning true

image

## TESTS PERFORMED:

- Build, runs

## HOW TO TEST THE CHANGES:

- Use a Rogue character and play with Poisons. Make sure they are still correctly applied in all cases (hit, crit, etc..)
- Play a little bit with spells and hitting in general, make sure nothing is broken by this change.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@pklloveyou can you please give this a try?

**Comment by pklloveyou** [comment]
OK

**Comment by pklloveyou** [comment]
image
I don't know if it's correct. You can see the quick acting poison's critical hit and hit from the picture

**Comment by FrancescoBorzi** [comment]
@pklloveyou thanks!

**Comment by FrancescoBorzi** [comment]
Merging soon as other PRs depend on this one.

**Comment by merdlin** [comment]
How was it before PR?

**Comment by FrancescoBorzi** [comment]
@merdlin there was a bad condition inside an `if` which was logically wrong as it always resolved to `true`.

However, this does not necessarily mean that there was a bug before. Maybe that condition didn't impact at all the game, or maybe this PR fixed some corner cases.

**Pull request merged**
