### PR TITLE
fix(Core/CreatureAI): revert NPC repositioning and path system (temporarily)

### PR DESCRIPTION
**Pull request by Helias**
This feature will be added again here https://github.com/azerothcore/azerothcore-wotlk/pull/4220

## Changes Proposed:
reverted  https://github.com/azerothcore/azerothcore-wotlk/commit/b2761626fec1d454acb58f08c0e0e3d8c9b83e47 and https://github.com/azerothcore/azerothcore-wotlk/commit/aeab8d8bc613eae1f0c44c9dd59b39feb793f444

## Issues Addressed:
- all the issues caused by this

## Tests Performed:
- didn't test, just revert

## How to Test the Changes:
This removed some feature and restore the old behavior of the NPCs, so it should not create new bugs

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by mpfans** [comment]
I'm already testing this PR, because after I update these two commits, the server will crash

**Comment by pklloveyou** [comment]
Qishi can leave “MoveBackwards” behind, it won't let the server crash

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by mpfans** [comment]
tested ，server won't crash

**Comment by Helias** [comment]
These issues should not be present on master anymore after this PR

https://github.com/azerothcore/azerothcore-wotlk/issues/4268
@JamesGent 

https://github.com/azerothcore/azerothcore-wotlk/issues/4205
https://github.com/azerothcore/azerothcore-wotlk/issues/4252
@nicoaravena

https://github.com/azerothcore/azerothcore-wotlk/issues/4203
@Hacaw 

https://github.com/azerothcore/azerothcore-wotlk/issues/4247
@Voxstrasza 

not sure about https://github.com/azerothcore/azerothcore-wotlk/issues/4262 @footman

Please test again now on master and confirm or close the related issues.
Naturally, we will need to test these kinds of issues again in this new PR https://github.com/azerothcore/azerothcore-wotlk/pull/4220

**Comment by Footman** [comment]
#4262 was already in master before

**Comment by nicoaravena** [comment]
> 
> 
> These issues should not be present on master anymore after this PR
> 
> #4268
> @JamesGent
> 
> #4205
> #4252
> @nicoaravena
> 
> #4203
> @Hacaw
> 
> #4247
> @Voxstrasza
> 
> not sure about #4262 @Footman
> 
> Please test again now on master and confirm or close the related issues.
> Naturally, we will need to test these kinds of issues again in this new PR #4220

#4205 This still happens.
#4252 it appears that this is not happening anymore.

**Comment by Voxstrasza** [comment]
#4262 is an issue that won't be solved easily tbh - not even TC has it right

**Pull request merged**
