### PR TITLE
fix(db/creature_template): Remove creature 138

### PR DESCRIPTION
**Pull request by neifion-00000000**
## Changes Proposed:
-  Removes creature 138
-  Just look at this thing, what's it doing?  be gone.
 https://wowgaming.altervista.org/aowow/?npc=138

## SOURCE:

This doesn't exist anywhere, nor should it.  If you can prove me wrong I'd be very interested to see it.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Gultask — APPROVED** [review]

**Comment by Nyeriah** [comment]
If it's a custom/private server leftover it's okay to delete it but if it's a sniffed remain/QA creature it shouldn't be deleted

**Comment by neifion-00000000** [comment]
to be clear I'm not advocating for removing any mobs that show up in any legit databases  or can be pinged from the blizzard servers, just ones that aren't and don't (like this case)

I have passed up dozens of those oddities before finding that guy

**Comment by Gultask** [comment]
```
ServerToClient: SMSG_QUERY_CREATURE_RESPONSE (0x2914) Length: 5 ConnIdx: 1 Time: 08/18/2022 09:48:02.477 Number: 1953
Entry: 138
no response
```

**Comment by heyitsbench** [comment]
> no response

There's likely many things that would return no response that still belong in the DB.

**Comment by neifion-00000000** [comment]
> > no response
> 
> There's likely many things that would return no response that still belong in the DB.

this was from the brute force packet, which is how the creature_template was populated

while it doesn't 100% confirm it wasn't in wotlk originally from a logical standpoint (it not being in classic doesn't mean it wasn't in wotlk), but it does from a contextual standpoint because all of the other misc entries do exist (only this mob and other confirmed custom mobs are missing, so the chances of it not being the same are slim).

**Pull request merged**
