### PR TITLE
fix(db/SAI): Missing esES/esMX locales

### PR DESCRIPTION
**Pull request by Valdifer**
Some quests had missing creatures name, rewards, creatures texts and they were shown in english

wowhead.com/wotlk/es/quest=12919 for example (There is more quests inside)

Valdifer

## Changes Proposed:
-  Update/Add some missing esES/esMX locales

## Issues Addressed:

- Closes 

## SOURCE:

Wowhead

## Tests Performed:

- Does it build without errors? Yes
- Did you test in-game? Yes
- What did you test? WG quests, Dalaran quests, Headless Horseman quest, Violet Hold key Item, WG Announcers

## How to Test the Changes:

1. Execute updates
2. Open the game
3. .additem 42482
4. .event start 12
5. .quest add 11404
6. .quest add 11405
7. .quest add 13222
8. .quest add 13223
9. .quest add 13177
10. .quest add 13179
11. .quest add 13181
12. .quest add 13183
13. .quest add 13158
14. .quest add 13159
15. .quest add 24585
16. .quest add 13178
17. .quest add 13180
18. .quest add 13159

## Known Issues and TODO List:

- [Complete the rest of ES locales doing them in big packs separated by tables]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
What is the source on this, just Wowhead?

**Comment by Valdifer** [comment]
> What is the source on this, just Wowhead?

Yes, all those translations are copied from wowhead, if they didn't had a translation i made it by myself, but i think in this SQL all of them are copied from wowhead yes, let me edit and put it there

**Comment by LukasVolgger** [comment]
Hi and thx for your contributions. I requested changes on your other PR https://github.com/azerothcore/azerothcore-wotlk/pull/13718 which are also necessary for this one.

**Review by LukasVolgger — CHANGES_REQUESTED** [review]
- DELETE before INSERT
- Add backticks around all column names
- Use `locale` IN ('esES', 'esMX')

**Comment by Valdifer** [comment]
> * DELETE before INSERT
> * Add backticks around all column names
> * Use `locale` IN ('esES', 'esMX')

Done, if there is something more wrong i will change it

thx for review my PR :_D

**Comment by LukasVolgger** [comment]
Script looks good, thanks!  Please test it yourself and post at least a few screenshots here :)

**Review by LukasVolgger — APPROVED** [review]

**Comment by Valdifer** [comment]
> Script looks good, thanks! Please test it yourself and post at least a few screenshots here :)

image
image
image
image

Some of them

Greetings!

**Comment by LukasVolgger** [comment]
Good work, thx!

**Comment by Nefertumm** [comment]
Thank you for your contribution!

**Pull request merged**
