### PR TITLE
Script/Spells: fixed dk pets stats calculation

### PR DESCRIPTION
**Pull request by sanctum32**
## CHANGES PROPOSED:
-  Fixed incorrect stats calculation for gargoygles (haste, stamina, ap)

## TESTS PERFORMED:
- Builds (MSVC, GCC, Clang)
- Tested ingame

## HOW TO TEST THE CHANGES:
For haste - mostly try to apply any haste auras on owner
For stamina and AP - same as haste, try to apply stamina/AP based auras

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
So I tried to reproduce the issue on my 5months old core WITHOUT this PR.

I made a DK, I applied a +132 stamina buff, I summoned the Gargoyle and the Risen ghoul and they both got an upgrade in HP.

So there seems to be 0 issue to fix. If it's not broken, do not fix it.

However, second test I've made in Icecrown Citadel, I entered and got the +30% hp buff but my summoned pets didn't get any hp buff (and they don't receive the ICC buff either). But maybe they only scale from Stamina and not from raw HP

**Comment by FrancescoBorzi** [comment]
not sure about the bug being solved here, but the PR definitely gives some code style improvements so we need it

**Comment by pklloveyou** [comment]
Can anyone test it? I'm not very good at DK

**Comment by Helias** [comment]
@sanctum32 why did you close this?

**Comment by sanctum32** [comment]
well, i'm going to redo this as actual code cleanup on another PR

**Pull request closed without merging**
