### PR TITLE
fix(DB/spell_proc_event): Add Blade of Wizardry ICD

### PR DESCRIPTION
**Pull request by Samsequel**
## Changes Proposed:
-  add icd

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16747

## Tests Performed:

- not tested

## How to Test the Changes:

.add 31336
Cast spells

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Gultask — APPROVED** [review]

**Comment by Gultask** [comment]
I think spell_proc_event might be reloadable if you wanna give it a quick try

**Comment by Samsequel** [comment]
tested

**Comment by elthehablo** [comment]
Crying and shaking... it finally happened

**Comment by elthehablo** [comment]
In all seriousness. Are we sure 50s is accurate. Who tested this?

**Comment by Gultask** [comment]
image

**Pull request merged**
