### PR TITLE
fix(Core/Spells): Restore sending SMSG_CAST_FAILED for spells in SPEL…

### PR DESCRIPTION
**Pull request by avarishd**
…L_STATE_PREPARING state (cast bar in progress)

https://github.com/TrinityCore/TrinityCore/commit/844efbfca84580f7b2bd700f40209515f2aaa959

Correction for https://github.com/azerothcore/azerothcore-wotlk/pull/19082 & https://github.com/azerothcore/azerothcore-wotlk/pull/19101

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/60459dd7-e1db-420b-ac7c-c95abc8c460e

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

start/cancel casts/channels
Check if casts/channels are properly being interrupted (by manually canceling or interrupting with a spell) and if the animations/cast bar is being updated accordingly.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Bench test :D

**Comment by Kitzunu** [comment]
Does thsi fix https://github.com/azerothcore/azerothcore-wotlk/issues/12884 ?

**Comment by avarishd** [comment]
Channels not giving gcd update was fixed by https://github.com/azerothcore/azerothcore-wotlk/pull/19082 & https://github.com/azerothcore/azerothcore-wotlk/pull/19101

**Comment by Kitzunu** [comment]
ok close the issue

**Review by Nyeriah — APPROVED** [review]

**Comment by avarishd** [comment]
I'm scared of this PR...

**Comment by Nyeriah** [comment]
Ye, we all are

**Pull request merged**
