### PR TITLE
fix(Core/Mail): Mailhandler cleanup

### PR DESCRIPTION
**Pull request by Viste**
## CHANGES PROPOSED:
-  prevent possible money dupe in mailhandler
-  Fix max packet size client crash in mailbox listing (thx Warlockbugs and cmangos)

## TESTS PERFORMED:
- build only
## HOW TO TEST THE CHANGES:
 - test open send mails in game and etc
 - try to owerflow client mail buffer

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
I tested these and none of them were wrong.
1.Send mail.
2.Send gold coins.
3.Send the maximum amount of gold coins.
4.Send items.
5.Send maximum number of items (12).
6.Mail sent by the auction house.

**Comment by pklloveyou** [comment]
And 7.Return mail.

**Comment by pklloveyou** [comment]
And 8.Delete mails.

**Comment by pklloveyou** [comment]
And 9.Buy items on the auction house(176).

**Comment by pklloveyou** [comment]
9.Mail sent by the system

**Comment by pklloveyou** [comment]
11.Mail sent by the system

**Comment by pklloveyou** [comment]
image

**Comment by Viste** [comment]
> image

it's not understandable, but it's very interesting.

**Comment by pklloveyou** [comment]
12.Return the email sent by GM。
It should have all been tested.If there is still please add it.

**Comment by pklloveyou** [comment]
This is when you meet the requirements of the level, the system sends you the“learning to fly riding”mail

**Comment by BarbzYHOOL** [comment]
@Viste thank you for that fix

and thank you @pklloveyou for deep testing!!

**Pull request merged**
