### PR TITLE
refactor(Player): Update some methods to UpperCamelCase

### PR DESCRIPTION
**Pull request by Kitzunu**
* GetClass
* GetLevel
* GetRace
* GetSelectedPlayer

## Changes Proposed:
-  Time to start following https://www.azerothcore.org/wiki/cpp-code-standards#naming-of-variables-and-functions a bit

## Tests Performed:

- Builds

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
UpperCamelCase = PascalCase

**Comment by Kitzunu** [comment]
in cpp code standards it says UpperCamelCase, so should not be confusing

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Helias** [comment]
merge conflcits

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6599

**Comment by pklloveyou** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
TODO: prepare PR to fix modules before merging this

**Comment by FrancescoBorzi** [comment]
> TODO: prepare PR to fix modules before merging this

@Kitzunu can you please take care of it? So we can merge this PR. Also, there are merge conflicts.

**Comment by iraizo** [comment]
By the way, this can be done to the whole project by using clang-tidy and going over it with [readability-identifier-naming](https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/mod-anticheat/pull/37
https://github.com/ElunaLuaEngine/Eluna/pull/373
https://github.com/azerothcore/mod-autobalance/pull/88

**Comment by FrancescoBorzi** [comment]
@Kitzunu what's the status of this?

**Comment by Kitzunu** [comment]
Status: I got no personal life and anything not fun to do is put on a wait list until I work less

**Comment by Kitzunu** [comment]
too much conflicts

**Pull request closed without merging**
