### PR TITLE
fix(CORE/commands): Realign columns for command ".pdump"

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
## CHANGES PROPOSED:
Columns were not longer aligned and sometimes it worked, sometimes it didn't want to save a character or load a character. Now it works fine.

Thanks @Rochet2 for identifying the column count issue

## TESTS PERFORMED:
- Tested ingame and in the console, works perfectly fine for both subcommands

## HOW TO TEST THE CHANGES:

Before and after PR:
1. `.pdump write pdump_test.txt character_name` without PR it failed for me on SOME characters (saying the character had been deleted)
1. `.pdump load pdump_test.txt account_id`

## KNOWN ISSUES AND TODO LIST:

- The code is prehistoric, in theory it should be reworked and also make use of "named queries" (with column names instead of column count) to avoid this issue again.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by skxawng-cu** [comment]
I don't test the PR but I can confirm the bug that say (the character had been deleted) when you try to dump.

**Comment by JokerBayern** [comment]
The command works properly ;)

**Comment by BarbzYHOOL** [comment]
@JokerBayern thank you!! you had same issue as us so it's good to merge

**Comment by FrancescoBorzi** [comment]
well done, this is a good example of something that we could easily catch if we only had unit tests....

**Pull request merged**
