### PR TITLE
fix(Core/Unit): Set AI notification when setting/removing contested PvP flags.

### PR DESCRIPTION
**Pull request by Chero**
## Changes Proposed:
-  Set AI notification when player's contested PvP flag changes, so nearby stational guards will attack correctly.

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/524

## Tests Performed:

- Build & Implementation

## How to Test the Changes:
1) Login 1 Horde and 1 Alliance character

2) Go to Booty Bay or another neutral city. Find a stationary guard
**OR**
.tele barrens
.npc add 4624

3) Attack the other player without moving

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Hacki95** [comment]
Does this also fix the issue which is named in the first comment here: https://github.com/chromiecraft/chromiecraft/issues/311 ?

**Comment by Chero** [comment]
> Does this also fix the issue which is named in the first comment here: [chromiecraft/chromiecraft#311](https://github.com/chromiecraft/chromiecraft/issues/311) ?

I'm afraid not, but I can imagine a similar fix, calling this on creature spawn. Just-spawned creatures, however, have supposed to have a slight delay between spawn and reaction time (about 5 sec or so)

**Comment by Hacki95** [comment]
> 
> 
> > Does this also fix the issue which is named in the first comment here: [chromiecraft/chromiecraft#311](https://github.com/chromiecraft/chromiecraft/issues/311) ?
> 
> No, if there is such an issue, this will not fix that. This fix is only regarding the contested PvP flag toggle.
> 
>     1. I can imagine a similar fix, calling this on creature spawn. Just-spawned creatures, however, have supposed to have a slight delay between spawn and reaction time (about 5 sec or so).
> 
>     2. As for player resurrection,  UpdateObjectVisibility() is already called there, so in this case, there might be a limitation regarding positioning or something like that. In such cases, a positional condition in visibility updates should be disregarded
> 
> 
> There are various places, where AI & visibility notifications should be triggered (i.e. AI change, resurrection, teleport, movement, etc..) including the contested PvP flag toggle which was completely missing. And there is no oneliner fix for all of them unless you want your CPU usage to skyrocket.

Thanks for the information! Do you think you might be able to make a PR for this bug too?

**Comment by pklloveyou** [comment]
How to test

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
