### PR TITLE
fix(DB/Creature): Atal'ai Priest unattackable

### PR DESCRIPTION
**Pull request by Tyrelis**
##### SMALL DESCRIPTION:
Atal'ai Priest creature in the entrance to Sunken Temple is not able to be attacked and does not attack players.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
This creature should be hostile and attack players in range

##### CURRENT BEHAVIOUR:
Creature does not attack players and is not able to be attacked, even with aoe attacks.
https://user-images.githubusercontent.com/65240021/82106834-8754fc80-96f1-11ea-9923-1b87d0f6438a.jpg

##### STEPS TO FIX THE PROBLEM:

1. apply sql and restart server
2. Go to the entrance of Sunken Temple
3. Notice the Atal'ai Priest creature is attackable.

##### EXTRA NOTES:
Fixes: #3041
Credits: Kitzuna, Tyrelis, r0m1ntik94

##### BRANCH(ES):

master

##### AC HASH/COMMIT:
AzerothCore rev. f301d81 2020-05-12 06:08:54 +0000 (master branch) (Unix, Release)

##### OPERATING SYSTEM:
Ubuntu 18.04

##### MODULES:
AHbot
Autobalance

##### OTHER CUSTOMIZATIONS:
None

### CODE REVIEW

**Comment by Geekena** [comment]
priest attacking me
damage and spells are ok aswell

**Comment by Kitzunu** [comment]
I got 2 notations
1. Ideally you would not override flags but remove/add them (How to properly do that can be found on the wiki)
2. There is a reason to why the NPC had the flag 256 in the first place.
Check his SAI, it has an SAI to remove that specific flag out of combat
smart_scripts
---
```sql
SELECT * FROM `smart_scripts` WHERE `entryorguid` = 5269 AND `id` = 2
```
| entryorguid | source_type | id | link | event_type | event_phase_mask | event_chance | event_flags | event_param1 | event_param2 | event_param3 | event_param4 | event_param5 | action_type | action_param1 | action_param2 | action_param3 | action_param4 | action_param5 | action_param6 | target_type | target_param1 | target_param2 | target_param3 | target_param4 | target_x | target_y | target_z | target_o | comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | 
| 5269 | 0 | 2 | 0 | 1 | 0 | 100 | 0 | 5000 | 5000 | 5000 | 5000 | 0 | 19 | 256 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | Atal'ai Priest - Out of Combat - Remove Unit Flags | 

3. This SAI has a condition to it
conditions
---
```sql
SELECT * FROM conditions WHERE sourceentry = 5269
```
| SourceTypeOrReferenceId | SourceGroup | SourceEntry | SourceId | ElseGroup | ConditionTypeOrReference | ConditionTarget | ConditionValue1 | ConditionValue2 | ConditionValue3 | NegativeCondition | ErrorType | ErrorTextId | ScriptName | Comment | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | 
| 22 | 3 | 5269 | 0 | 0 | 13 | 1 | 11 | 6 | 0 | 0 | 0 | 0 |  | Run action if GetData(11) == 6 | 


256 - UNIT_FLAG_IMMUNE_TO_PC

So this fix is not valid without figuring out why this SAI & condition exists, perhaps there is some kind of event that should happen.
https://www.azerothcore.org/wiki/conditions

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/fecba9f287002a33d4f72d7c3e6041c9175f4b83/src/server/scripts/EasternKingdoms/SunkenTemple/sunken_temple.h#L11
https://github.com/azerothcore/azerothcore-wotlk/blob/fecba9f287002a33d4f72d7c3e6041c9175f4b83/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp#L90
https://github.com/azerothcore/azerothcore-wotlk/blob/fecba9f287002a33d4f72d7c3e6041c9175f4b83/src/server/scripts/EasternKingdoms/SunkenTemple/instance_sunken_temple.cpp#L125

If I were to guess you'd find your answer around these lines.

**Comment by Kitzunu** [comment]
So I did some research.

There are 6 Defenders that needs to be killed in order to unlock your way to Jammal'an the Prophet
Which makes `Run action if GetData(11) == 6` make sense since
DATA_DEFENDER_KILLED        = 11
and 6 = the amount of defenders

Now we just need to figure out the actual issue to why you cannot attack the NPC. Is it intended? or are they only supposed to be attackable after you have killed all 6 defenders

**Comment by Knindzagxg** [comment]
Priests are just regular NPC's, they are not required for any Event in Dungeon.
Guardians and other mini bosses are linked with each other to unlock few major boss fights.

While i was testing, all events were working without problems.

**Comment by Tyrelis** [comment]
> Priests are just regular NPC's, they are not required for any Event in Dungeon.
> Guardians and other mini bosses are linked with each other to unlock few major boss fights.
> 
> While i was testing, all events were working without problems.

I can make the changes but yes here right there just regular npc's.

**Comment by Kitzunu** [comment]
except for the 1 NPC that is stood before the last boss

**Comment by Tyrelis** [comment]
Like this https://prnt.sc/sifobq

**Comment by Kitzunu** [comment]
? there is no Data Type 32

**Comment by Kitzunu** [comment]
The condition and SAI is good, all you need to do is make it point to the GUID instead of the Entry

**Comment by Tyrelis** [comment]
@Geekena Needs additional testing

**Comment by felwyn** [comment]
Fix is working @FrancescoBorzi

**Pull request merged**
