### PR TITLE
fix(DB/Creature): Added patrolling and fixes to Spiteflayer

### PR DESCRIPTION
**Pull request by Asthalor**
Changed the spawns, movement speed and added patrolling

## Changes Proposed:
-  Reduced speed of movement
-  Removed some spawns
- Added to the remaining spawns patrolling logic to mimic the source

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7105
- Closes https://github.com/chromiecraft/chromiecraft/issues/1281

## SOURCE:

https://tbc.wowhead.com/npc=8299/spiteflayer#comments

## Tests Performed:

- .go c 38089 or .go c 134366
- Observe if he moves more slowly and if he patrols

Video test of a small timestamp

https://user-images.githubusercontent.com/87535580/126907567-3cc7d7e9-98f6-4c56-a38b-2e9ba0dd2f46.mp4

## How to Test the Changes:

1. .go c 38089 or .go c 134366
2. Observe if he moves more slowly and if he patrols

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — COMMENTED** [review]
Thx for that! Why are you deleting so many spawns? Were they wrong?

**Comment by Asthalor** [comment]
> Thx for that! Why are you deleting so many spawns? Were they wrong?

Oh, not at all.
But since the source only had it moving around a small area i thought that having two spawns with the patrolling would be enough for it to wander in all those places. But i can try and add some kind of patrolling to all of them if its better

**Comment by LukasVolgger** [comment]
I'm just wondering why would there be so many spawns of this creature if there is no reason for it? We should clarify this before deleting something

**Comment by Asthalor** [comment]
> I'm just wondering why would there be so many spawns of this creature if there is no reason for it? We should clarify this before deleting something

Good for me!
Having 17 patrols for this one is not hard, just a bit of time consuming.

**Comment by LukasVolgger** [comment]
@FrancescoBorzi @Kitzunu what do you think about?

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi, @Kitzunu what do you think about?

I'm not sure if the spawns should be only 2

**Comment by Asthalor** [comment]
> > @FrancescoBorzi, @Kitzunu what do you think about?
> 
> I'm not sure if the spawns should be only 2

No problem then. I will add some patrolling to all of them, should not take too long!

**Comment by Asthalor** [comment]
I think this PR is now fixed. Had some errors in the SQL that should now be fixed.

**Review by LukasVolgger — APPROVED** [review]

**Pull request merged**
