### PR TITLE
fix(Scripts/Raids): Fixed setting `UNIT_FLAG_NON_ATTACKABLE` flag to …

### LINKED ISSUE #8980: [Dungeon/TOC]Boss can not killed
### Current Behaviour

At end of the 1st wave encounter,one of three champion npc boss keep attacking players with 1 hp.and then the Black Knight on Hawk float on air can not be attacked . the dungeon is totally can not play

### Expected Blizzlike Behaviour

champion npc boss won't attack player after be "killed" with 1 hp left. and Black Knight boss should be  attackable.

### Source

_No response_

### Steps to reproduce the problem

1. go to dungeon TOC
2. start combat
3. "Kill" all challenger npc include the 3 champion
4. watch the champion

### Extra Notes

_No response_

### AC rev. hash/commit

d80f7d467d47+

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…some Trial of the Champions bosses.

Fixes #8980

## Issues Addressed:

- Closes #8980

## Tests Performed:

- Not tested.

## How to Test the Changes:

go to dungeon TOC
start combat
"Kill" all challenger npc include the 3 champion
watch the champion

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by adink1** [comment]
This doesn't seem to work,The strange thing is that it is normal to be defeated by tribal players, as long as one of the bosses is pulled to the corner, the plot can be triggered. But the alliance players could not continue.

**Comment by betayi** [comment]
the last champion(npc_mokra or other) in first counter be defeated still fight with player in status unattackable flag

**Comment by UltraNix** [comment]
@betayi @adink1 I cannot reproduce these bugs. Please, record it.

**Comment by UltraNix** [comment]
@betayi @adink1 ??

**Comment by fullofstarschen** [comment]
I tried this patch，just like adink1 said，the Alliance players could not continue.

**Comment by UltraNix** [comment]
@fullofstarschen Can you provide some screenshots or (better option) a clip?

**Comment by fullofstarschen** [comment]
I recorded a video, but the capacity exceeds 10M, which can only be uploaded to the baidu network disk. Please visit
:    https://pan.baidu.com/s/1PaA1CnOPR6et07FZTh0xJw?pwd=ntcq        (code: ntcq )

**Comment by UltraNix** [comment]
@fullofstarschen Please, test it again with the newest changes.

**Comment by fullofstarschen** [comment]
I just tried the new patch,it's not perfect but it works,great job!
Issues remains: 
1，Horde players,in the first stage，grand champions will attack players on sight before the three knights be defeated,while Alliance players check it okay.
2,  Alliance players,in the first stage,the battle is over while I just defeated 2 of 3 grand champions and the chest appears.

I didn't find any issue in stage 2 and 3, Thank you!

**Comment by UltraNix** [comment]
@fullofstarschen Please - one more try.

**Comment by fullofstarschen** [comment]
I tried the latest patch,grand champions will not attack Horde players now,it works.But this time I won the battle by defeated 1 of 3 grand champions as a Horde player,I think this is an acceptable issue,it doesn't matter.Thank you!

**Comment by UltraNix** [comment]
@fullofstarschen I can't reproduce the last - please record the video.

**Comment by fullofstarschen** [comment]
I recorded a video as an Alliance player，You can visit      https://v.youku.com/v_show/id_XNTg1MDQxNTg1Ng==.html

**Comment by fullofstarschen** [comment]
I think I shouldn't use .damage code,so I record a new one,but this time,just like what [betayi](https://github.com/betayi) said,please visit:  https://v.youku.com/v_show/id_XNTg0OTkwMTIyMA==.html

**Comment by UltraNix** [comment]
@fullofstarschen Sadly I cannot reproduce it. Are able to bug this out every single time?

**Comment by fullofstarschen** [comment]
One particular detail to note is that if I use “.damage” code to defeat the grand champions,even I use the code for 3 times on the same champion I would win the battle and all the grand champions run away;If I use spell to defeat all of them,one of them will be like what betayi had said,“the last champion(npc_mokra or other) in first counter be defeated still fight with player in status unattackable flag”，just like my latest video.

**Comment by fullofstarschen** [comment]
Anyway,there won't be any more chest that keeping respawn,i will take this patch.

**Comment by UltraNix** [comment]
@fullofstarschen Please, test again (the bug with command `.damage`) and the `npc_mokra`

**Comment by fullofstarschen** [comment]
I tried the latest patch,now use .damage code on same champion will not win the battle,but players don't use .damage code,I said that because I  have a guess that there is a counter ,when used .damage code, the counter works, and when the counter increases to 3, all the champions escape; However, the normal spell attack leaves the champions with 1HP left, the champion's state change to NON_ATTACKABLE , but the counter does not  increase, so one  of the champions will stay to fight with the player.

**Comment by UltraNix** [comment]
@fullofstarschen As I said - I cannot reproduce that bug. It happens only with Mokra?

**Comment by fullofstarschen** [comment]
I tried the latest patch,now use .damage code on same champion will not win the battle,but players don't use .damage code,I said that because I  had a guess that there is a counter,when I used .damage code, the counter works, and when the counter increases to 3, all the champions escape; However, spell attack leaves the champions with 1HP left, the champion's state change to NON_ATTACKABLE , but the counter does not  increase, so one  of the champions will stay to fight with the player.

**Comment by UltraNix** [comment]
No. You are wrong about the counter.

**Comment by fullofstarschen** [comment]
Not a specific champion,but every battle has one of them left NON_ATTACKABLE with 1 hp.

**Comment by fullofstarschen** [comment]
A champion NON_ATTACKABLE can be accepted. Now players will try to pull the last champion to the corner and try to get out of the battle（eg ACE）. The dungeon can be completed, and all the players can accept this little trouble.

**Comment by UltraNix** [comment]
Sorry - I have no idead how to reproduce that bug. I can't fix it.

**Comment by UltraNix** [comment]
@fullofstarschen 
`UPDATE `creature_template` SET `unit_flags`=0 WHERE `ScriptName`='boss_grand_champion';`
Can you apply this SQL and test it again?

**Comment by fullofstarschen** [comment]
Unit_flags updated but doesn't work,maybe I do something mistake？It doesn't matter,one champion fighting and NON_ATTACKABLE but the door is open,so players can escape and reenter，while a mage or a rogue pull the champion to a corner and fade away.

**Comment by UltraNix** [comment]
@fullofstarschen You are testing on the newest version? Can you record the video again?

**Comment by fullofstarschen** [comment]
Yes,the newest one,and please visit  https://v.youku.com/v_show/id_XNTg1MjQyOTU0OA==.html

**Comment by UltraNix** [comment]
Thrust hits 700k???

**Comment by fullofstarschen** [comment]
.damage 70000

**Comment by UltraNix** [comment]
So it's still a command, not a spell.

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Nyeriah** [comment]
Merge conflicts

**Comment by UltraNix** [comment]
@Nyeriah Done.

**Pull request merged**
