### PR TITLE
fix(Scripts/Lich-King): tirion now attacks LK with Ashbringer

### PR DESCRIPTION
**Pull request by Dr-Arayashiki**
## Changes Proposed:
- Tirion was throwing punches at LK before
- Tirion now wields Ashbringer and attacks LK with it

## Issues Addressed:

- Closes 

## SOURCE:

I suppose he has to wield an Ashbringer and hit the LK, before he just threw punches and wasn't equipped with the weapon
## Tests Performed:

- reach the end of the LK and watch the cutscene
- Tirion now wields the Ashbringer and hits LK with it

## How to Test the Changes:

1. Reach the end of the LK and watch the cutscene
2. Tirion now wields the Ashbringer and hits LK with it
3. After the events are over he is still with Ashbringer

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Dr-Arayashiki** [comment]
@Kitzunu
@Gultask 
It's cool?
no magic numbers 😄

**Comment by Dr-Arayashiki** [comment]
@Kitzunu 
@Gultask 
@Nyeriah 
It's cool?
no magic numbers 😄

**Comment by heyitsbench** [comment]
> ## SOURCE:

Glad to see my concerns are being addressed.

**Comment by Dr-Arayashiki** [comment]
> > ## SOURCE:
> 
> Glad to see my concerns are being addressed.
I share the same concern with you, but as I said, it's pretty obvious what the NPC should do.
https://youtu.be/Ocq4byvypZM?t=542
if you have a different source that might refute what i put there please post

**Comment by Dr-Arayashiki** [comment]
> > ## SOURCE:
> 
> Glad to see my concerns are being addressed.

I share the same concern with you, but as I said, it's pretty obvious what the NPC should do.
https://youtu.be/Ocq4byvypZM?t=542
if you have a different source that might refute what i put there please post

**Comment by heyitsbench** [comment]
> I share the same concern with you, but as I said, it's pretty obvious what the NPC should do.

You stated no such thing in the text for this PR. Had you said it was an assumption, that would still be fine with me, but as I said on your previous PR, a screenshot taken from AC (or anything *not* from Blizzard servers in my humble opinion) does not a source make, though I'm sure it would be more than good enough for the maintainers of this project.

**Comment by Dr-Arayashiki** [comment]
> > I share the same concern with you, but as I said, it's pretty obvious what the NPC should do.
> 
> You stated no such thing in the text for this PR. Had you said it was an assumption, that would still be fine with me, but as I said on your previous PR, a screenshot taken from AC (or anything _not_ from Blizzard servers in my humble opinion) does not a source make, though I'm sure it would be more than good enough for the maintainers of this project.

although, probably even you know what the npc does, I believe this kind of comment about very obvious things is unnecessary 👍 
now it should be fine for you

**Comment by heyitsbench** [comment]
> although, probably even you know what the npc does, I believe this kind of comment about very obvious things is unnecessary 👍 now it should be fine for you

It doesn't matter that I know the expected behavior. In my opinion the purpose of the template is to make the changes feasible to understand for anyone. The changes made, the tests done, and what the changes are based off of should all be properly included in a PR's description and understandable to anyone who may not know these mechanics. I know I may be alone in that opinion across the entire space of contributors to this project, but this is a hill I am willing to die on.

I do insist that you continue to attach proper sources for your PRs in the future.

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/15823

**Pull request closed without merging**
