### PR TITLE
fix(DB/Spell): Judgement of wisdom/light procs

### PR DESCRIPTION
**Pull request by GMKyle**
thx also to @Yehonal
##### CHANGES PROPOSED:

-  Fix JOW (http://wotlk.cavernoftime.com/spell=20186) and JOL (http://wotlk.cavernoftime.com/spell=20185), they should give mana or heal also to spell attackers. Right know they only procs with physicals attacks.

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/698

##### TESTS PERFORMED:
Build without errors and tested in-game. (Win10 and Debian 9 servers).

##### HOW TO TEST THE CHANGES:

 - cast JOL and JOW on any mob
 - attack the mob casting spells (physical attacks works to)

##### Target branch(es):

Master

### CODE REVIEW

**Comment by shuradumau** [comment]
apply the corrections, in my updated version this error does not happen, everything works correctly.

**Comment by BarbzYHOOL** [comment]
@GMKyle why "thx also to @Yehonal" ?

And thank you @GMKyle for the fix

Thank you for testing @shuradumau @Selyria please, keep testing guys!

**Comment by FrancescoBorzi** [comment]
> @GMKyle why "thx also to @Yehonal" ?

I guess because of prior Yehonal's investigations on this bug

**Comment by BarbzYHOOL** [comment]
ah yes

**Comment by Yehonal** [comment]
> @GMKyle why "thx also to @Yehonal" ?
> 
> And thank you @GMKyle for the fix
> 
> Thank you for testing @shuradumau @Selyria please, keep testing guys!

https://github.com/azerothcore/azerothcore-wotlk/issues/698#issuecomment-338507767

**Pull request merged**
