### PR TITLE
fix(Core/Unit): Remove delay for Conflagrate aura state

### PR DESCRIPTION
**Pull request by Alethrion**
## Changes Proposed:
This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3112
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2801
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1571
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/832
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/298
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11641
- Closes https://github.com/chromiecraft/chromiecraft/issues/4136
- Closes https://github.com/chromiecraft/chromiecraft/issues/1136
- Closes https://github.com/chromiecraft/chromiecraft/issues/4319

## SOURCE:
The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
  - Matches Wrath Classic
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
  - https://youtu.be/KUizH_eVcuA?t=209
  - https://youtu.be/gM_cpfa3EJE?t=55
- [X] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
  - https://github.com/TrinityCore/TrinityCore/commit/e27c385b48fce359a168d602dabae8c55fa85563

## Tests Performed:
This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [X] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Create warlock with Destruction spec
2. Cast immolate
3. Cast conflagrate

## Known Issues and TODO List:

- [ ] Needs testing for Stealth case (Hunter pet ability "Sting" and Faerie Fire)
- [ ] Needs testing for multiple warlocks (Conflagrate edgecase where it you may/may not be able to conflagrate off other warlocks immolate)
  - https://github.com/TrinityCore/TrinityCore/issues/19790

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by BeefSteaker** [comment]
All the issues this closes are marked as invalid. Is this a blizzlike fix?

**Comment by Kitzunu** [comment]
Wrong. They are all closed as fixed. I dont know about cc, dont care. But most if not everything from Ariel- is definetly trust worthy

**Comment by heyitsbench** [comment]
> Is this a blizzlike fix?

From what I've seen of every source mentioned as to why the behavior is as it is on current AC, it seems to moreso be trying to emulate the spell batching or latency of the era or a combination. I would much sooner believe that the sources just had high ping and aura states were highly subject to that and not that there's some hidden travel time as a few have claimed to support the current behavior in the past.

**Comment by Alethrion** [comment]
The currently AC mentioned "fix" adds a delay to conflagrates activation. The initial issue seen in the sources mentioned has nothing to do with conflagrate, but instead is related to spell batching on immolate. See: https://youtu.be/KUizH_eVcuA?t=209

This fix removes the conflagrate delay.

Somewhat tangentially I would also contest that immolate should have an invisable cast time. See: https://youtu.be/gM_cpfa3EJE?t=55

**Review by Nyeriah — APPROVED** [review]

**Comment by heyitsbench** [comment]
Gave this a small test, seems to work as expected. 👍

> Needs testing for multiple warlocks

Tested this against Classic, and the PR does not match the behavior there. This PR will only light up conflagrate if the target has an immolate up casted from the player. On Classic, conflagrate will light up regardless of the caster of immolate, but when attempting to cast when the target does not have an immolate casted from the player, it will give the "invalid target" error. Aside from the visual issue, the conflagrates do seem to consume the appropriate immolate.

**Comment by Alethrion** [comment]
As of right now the PR is an improvement on current behavior, though fized conflagrates' behavior is not visually blizzlike it is mechanically blizzlike and I wont personally be fixing the less intuitive visual indication that is blizzlike.

To my knowledge it still needs testing for faerie fire and hunter pets' sting. It would also be nice to know whether fire and brimstone and other dps modifying abilities apply when two warlocks are used (Even if the wrong warlock has the talent(s)), but it's worth noting that it is unlikely to be any worse then current AC.

**Pull request merged**
