### PR TITLE
Revert "fix(DB/gossip_menu): Add vendor option to Innkeeper Shaussiy"

### PR DESCRIPTION
**Pull request by Azcobu**
Reverts azerothcore/azerothcore-wotlk#8078 as per https://github.com/azerothcore/azerothcore-wotlk/pull/8078#issuecomment-944929149

### CODE REVIEW

**Comment by Nyeriah** [comment]
Something seems wrong, it shows no files were created

**Comment by Azcobu** [comment]
I was wondering about that, but haven't ever reverted anything before so wasn't sure what was going on. This was made by just hitting 'Revert' on the other issue, is there more that needs to be done?

**Comment by Nyeriah** [comment]
> I was wondering about that, but haven't ever reverted anything before so wasn't sure what was going on. This was made by just hitting 'Revert' on the other issue, is there more that needs to be done?

Yep, to revert database changes generally we need to reverse what we've done, that button only works for c++ changes. I can help you with that if you'd like

**Comment by Azcobu** [comment]
Thanks, I'll see how it goes. Will close this PR then.

**Comment by Azcobu** [comment]
This is turning out to be trickier than I thought. If I just delete the gossip menu option I originally added (```DELETE FROM `gossip_menu_option` WHERE `MenuID` = 347 AND `OptionID` = 3;```), leaving behind the gossip menu option to set the hearthstone, the gossip disappears altogether. Now, when you interact with her, you just get an immediate 'set hearthstone?' prompt with no gossip at all:

WoWScrnShot_101721_145212

But this isn't correct, as your screenshot from Classic shows - it should show some gossip text with an option there to set the hearth. There's a remaining gossip_menu_option still set for setting the hearthstone in gossip (her gossip menu ID is 347), but it's not shown. There's a flag in the creature_template `type_flags` field called FORCE_GOSSIP and even that doesn't make her display the hearthstone gossip option. Also tried changing her flags, as she has 2/Questgiver and 7/Vendor set - tried removing those, leaving just 0/Gossip and 16/Innkeeper set, but that didn't help. So I'm a bt puzzled about how to make her display the gossip menu option she has remaining. Any thoughts?

On a side note, she may also need Trick or Treat mechanics added - maybe that's why she has the questgiver flag.

**Pull request closed without merging**
