### PR TITLE
fix(Core/MailHandler): Fix display of item enchantments in mailbox

### PR DESCRIPTION
**Pull request by r0m1ntik**
Thanks for [@Eureka26](https://github.com/Eureka26) for extra notes

## Changes Proposed:
-  Fixed visual for item enchantments in mailbox

## Issues Addressed:
- Closes [4831](https://github.com/azerothcore/azerothcore-wotlk/issues/4831)

## Tests Performed:
- Tested in game
Снимок экрана 2021-03-15 в 22 16 37

## How to Test the Changes:

1) Send an already enchanted item to the player by mail
2) Will display

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Comment by Eureka26** [comment]
hi ! thanks for pull,  but you should put GetEnchantmentDuration
above GetEnchantmentCharges otherwise  items with  ench durations will show "charges"
like in this image  https://i.imgur.com/KrlUf0H.jpg

**Review by Eureka26 — CHANGES_REQUESTED** [review]
hi ! thanks for pull,  but you also should put GetEnchantmentDuration
above GetEnchantmentCharges otherwise  items with  ench durations will show  "charges" instead of duration, like in this screenshot <a href="https://imgur.com/KrlUf0H"></a>

**Comment by pklloveyou** [comment]
you are right

**Comment by r0m1ntik** [comment]
> hi thanks for pull, but you also should put GetEnchantmentDuration above GetEnchantmentCharges otherwise items with ench durations will show "charges" instead of duration, like in this screenshot [](https://imgur.com/KrlUf0H)

```c++
for (uint8 i = 0; i < MAX_ENCHANTMENT_SLOT; ++i)
{
    ssEnchants << GetEnchantmentId(EnchantmentSlot(i)) << ' ';
    ssEnchants << GetEnchantmentDuration(EnchantmentSlot(i)) << ' ';
    ssEnchants << GetEnchantmentCharges(EnchantmentSlot(i)) << ' ';
}
```

**Review by Eureka26 — APPROVED** [review]
now it's fine <3 thanks you

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Kitzunu** [comment]
ty

**Comment by Kitzunu** [comment]
ty

**Comment by Stifler82** [comment]
pls @Kitzunu  or @r0m1ntik  add this https://github.com/chromiecraft/chromiecraft/issues/46 to "Close"

**Comment by Kitzunu** [comment]
Need to be manually closed as it is after the PR was merged

**Pull request merged**
