### PR TITLE
feat(Scripts/Command): Implemented new command: bags clear.

### LINKED ISSUE #8365: Feature: GM clear inventory command
### Describe your feature request or suggestion in detail

When testing, I often find myself in a situation, where I have full bags and I don't want to delete every item one by one. Especially, when the items are blue or above, and I have to type "delete" each time.
I'm sorry, if there already is such a command or solution for it. If not, it would be nice, to have something like this implemented.

Implement a GM feature to clear the (own) inventory to get bag space.
For example, there could be multiple instances of that command:

`.clear inv hard` = Deletes all items from the inventory (maybe not hearthstone)
`.clear inv med` = Only deletes items with Uncommon quality or below and keeps quest items
`.clear inv soft` = Only deletes gray and white items and keeps quest items

### Describe a possible solution to your feature or suggestion in detail

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Closes #8365

## Changes Proposed:
-  Added new command: `.bags clear <itemQuality>`, eg. `.bags clear rare`
Possible qualities:
```
ITEM_QUALITY_POOR                  = 0,                 //GREY
ITEM_QUALITY_NORMAL                = 1,                 //WHITE
ITEM_QUALITY_UNCOMMON              = 2,                 //GREEN
ITEM_QUALITY_RARE                  = 3,                 //BLUE
ITEM_QUALITY_EPIC                  = 4,                 //PURPLE
ITEM_QUALITY_LEGENDARY             = 5,                 //ORANGE
ITEM_QUALITY_ARTIFACT              = 6,                 //LIGHT YELLOW
ITEM_QUALITY_HEIRLOOM              = 7
```

## Issues Addressed:

- Closes #8365

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Have some items in your bags
2. Use that command and look at your bags.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
works fine for me.

@UltraNix can you add please handler->PSendSysMessage("");

i dont know, items deleted successfully or 20x rare item deleted from character X

**Comment by UltraNix** [comment]
@Kitzunu If you want delete only one item, just remove it from bag.

**Comment by Kitzunu** [comment]
that is not what I said.

>  [bool "Clear all qualities including and lower than 'item quality"]

**Comment by UltraNix** [comment]
`.bags clear epic` removes EPIC + RARE + UNCOMMON + NORMAL + POOR

**Comment by UltraNix** [comment]
@IntelligentQuantum Done.

**Comment by UltraNix** [comment]
@jamadaha 
`.bags clear heirloom` Use `bags clear all` as it hase the same - will remove all items (heirloom is the highest item quality).

`Target other player | Not working it clears own bag. I don't know whether this is intended` This command is only for gms and not for clearing someone elses' bags.

**Comment by jamadaha** [comment]
@UltraNix Alright, justed wanted to know whether it was intended. I have updated my commented. However, should it remove the hearthstone?

**Comment by UltraNix** [comment]
You can buy it from innkeeper whenever you like. Moreover, I think GMs do not need hearthstone anyway.

**Comment by Shineslippers** [comment]
When you're using upper case in last word of command `.bags clear` it return syntax error

**Pull request merged**
