### PR TITLE
Core/Crypto: Transitional Cryptography update for OpenSSL 1.1

### PR DESCRIPTION
**Pull request by Viste**
Support for both OpenSSL 1.0 LTS and OpenSSL 1.1 versions.

Close issue #827 
Build testes workd fine on ubuntu desktop 18/04
Need Windows test(dont have it)
Port of CMaNGOS commit: cmangos/mangos-wotlk@e1b0048

Sorry for not use pull template do request from git kraken

### CODE REVIEW

**Comment by Viste** [comment]
default

**Comment by HamedMohsenavi** [comment]
screenshot-2018-05-0308-07-42

Arch Linux 64Bit

**Comment by ShinDarth** [comment]
@HamedMohsenavi is everything working for you?

**Comment by HamedMohsenavi** [comment]
Yes, it is

**Comment by ShinDarth** [comment]
@Viste thanks for your PR and @HamedMohsenavi thanks for testing it

**Pull request merged**
