### PR TITLE
fix(Core/Pet): Logic in which spells are allowed to be cast during co…

### PR DESCRIPTION
**Pull request by Kitzunu**
…mabt

## Changes Proposed:
-  Don't allow permanent spells to be cast during combat as a pet

## How to Test the Changes:

**RERUN CMAKE**

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
tested https://github.com/azerothcore/azerothcore-wotlk/issues/6085#issuecomment-850298688

**Comment by pklloveyou** [comment]
Do need to merge here?

**Comment by FrancescoBorzi** [comment]
@Kitzunu has this PR been tested ?

**Comment by Kitzunu** [comment]
No I will look at this PR when I get time, totally forgot about it lol

**Comment by FrancescoBorzi** [comment]
@Kitzunu what's the status of this PR?

**Pull request closed without merging**
