### PR TITLE
Core/Gossip: Replacing old macros with new

### LINKED ISSUE #1605: AddGossipItemFor() function fails on build in Linux
##### SMALL DESCRIPTION:

```cpp
void AddGossipItemFor(Player* player, uint32 gossipMenuID, uint32 gossipMenuItemID, uint32 sender, uint32 action);
```
Using this function on linux builds the file correctly with no error but it can't build worldserver, it fails there.

What the function does is:
```cpp
player->PlayerTalkClass->GetGossipMenu().AddMenuItem(gossipMenuID, gossipMenuItemID, sender, action);
```
If you want to create a gossip item from the DB and use directly the PlayerTalkClass the build works!

The only problem is when calling the function AddGossipItemFor()

##### EXPECTED BLIZZLIKE BEHAVIOUR:

---

##### CURRENT BEHAVIOUR:

Crashes the server on linux

##### STEPS TO REPRODUCE THE PROBLEM:

1. Follow this commit: https://github.com/azerothcore/azerothcore-wotlk/pull/1600/commits/61ecd4e6d88b7c7ed73ac1d76ec8a9d5d9212da5
2. Try to build core on linux.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/64d8bb1984870d1ac268a3476773de254578841c

##### OPERATING SYSTEM:

Linux Ubuntu 18.10

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/71770384-addgossipitemfor-function-fails-on-build-in-linux?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
**PR based TC commit** https://github.com/TrinityCore/TrinityCore/commit/d55426f5b4e431e6d398b1e2dbbd25f7387328f2

##### CHANGES PROPOSED:
**Support new macros for all scripts in core**
- `player->ADD_GOSSIP_ITEM(whatever)` -> `AddGossipItemFor(player, whatever)`
- `player->ADD_GOSSIP_ITEM_DB(whatever)` -> `AddGossipItemFor(player, whatever)`
- `player->ADD_GOSSIP_ITEM_EXTENDED(whatever)` -> `AddGossipItemFor(player, whatever)`
- `player->CLOSE_GOSSIP_MENU()` -> `CloseGossipMenuFor(player)`
- `player->SEND_GOSSIP_MENU(textid, creature->GetGUID())` -> `SendGossipMenuFor(player, textid, creature->GetGUID())`
- ~~Delete gossip preprocessor macros, and replaces them with the new-and-shiny gossip functions.~~

##### ISSUES ADDRESSED: 
- Close #1605 

##### TESTS PERFORMED:
- [x] Build in Windows

##### HOW TO TEST THE CHANGES:
1. Apply PR
2. Use npc or go gossip in game
3. You should not see any changes

##### KNOWN ISSUES AND TODO LIST:
- [x] Test build Linux
- [ ] Test in game

#### P.S. ... (todo)

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
```
/home/travis/build/azerothcore/azerothcore-wotlk/src/server/scripts/World/npcs_special.cpp:184:10: fatal error: 
      'OnQuestReward' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
    bool OnQuestReward(Player* player, Creature* creature, Quest const* ...
```

@Winfidonarleyan I guess you should add `override` on method at line `184`

**Comment by Winfidonarleyan** [comment]
@FrancescoBorzi Yes, right

**Comment by Trystanosaurus** [comment]
I've given this a bit of a test (I was hoping it would help with https://github.com/azerothcore/azerothcore-wotlk/issues/726 but no luck). 

In normal play there did seem to be no difference (so working). I also tried Vaelastraz in BWL and went through Karazhan and as far as I could see it was all working the same as before the patch.

In Kharazhan I got the big bad wolf opera event and talking to the granny starts on the third page of her gossip "What phat lewtz you have." but that's the same without this PR.

**Comment by BarbzYHOOL** [comment]
then it seems to be working as intended

**Comment by Winfidonarleyan** [comment]
This PR does not correct errors. Please read `CHANGES PROPOSED:`

> Delete gossip preprocessor macros and replaces them with the new-and-shiny gossip functions.
> Now support `Uses gossip item info from DB`

**Comment by brussens** [comment]
Decided yesterday to prepare a pull request with localizations for some gossip, but found that strings are not translated. This pull request is very important.

**Comment by brussens** [comment]
```mysql
INSERT INTO `gossip_menu_option_locale` (`MenuID`, `OptionID`, `Locale`, `OptionText`, `BoxText`) VALUES (11013, 3, 'ruRU', 'Перенестись на Черепной вал.', NULL);
```

This line should translate into Russian one of the gissip options, but the translation is not performed.

**Comment by FrancescoBorzi** [comment]
@brussens have you tested this?

@Winfidonarleyan can you please solve the conflicts?

**Comment by brussens** [comment]
@FrancescoBorzi Tonight, I'm gonna get to the computer and test it.

**Comment by FrancescoBorzi** [comment]
Ideally the conflict and code review should go first but feel free to start looking into this, and then we need to test it properly once it's ready to be merged

**Comment by brussens** [comment]
I looked at the results of the travis, but I still don't understand why the error is in `src/server/scripts/EasternKingdoms/zone_eastern_plaguelands.cpp`, but actually in the travis log the error is in `src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp`.

**Comment by brussens** [comment]
Tried to compile, got mistakes.

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(405): error C2059: syntax error: <<

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(416): error C2059: syntax error: public

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(417): error C2143: syntax error: no ";" before "{"

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(417): error C2447: {: no function header (the formal list of the old type may be used)

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(460): error C2059: syntax error: >>

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(462): error C2143: syntax error: no ";" before "{"

1. src\server\scripts\EasternKingdoms\zone_eastern_plaguelands.cpp(462): error C2447: {: no function header (the formal list of the old type may be used)

**Comment by brussens** [comment]
Tested by Win10x64 VS15.
Gossips are displayed as before.

**Comment by talamortis** [comment]
please fix travis 

> /home/travis/build/azerothcore/azerothcore-wotlk/src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp:851:17: fatal error: 
>       'GetAI' overrides a member function but is not marked 'override'

**Comment by Winfidonarleyan** [comment]
Need mark `override` in all project :/

**Comment by Winfidonarleyan** [comment]
And so, there is an important announcement, then PR, all modules which use the gossip won't work, you will need to remake them for the new macros.

**Comment by FrancescoBorzi** [comment]
> Maybe need time to leave old macros to developers of the modules and adaptation to the new macros?

@Winfidonarleyan  is there a way to make it backwards-compatible? For example instead of removing the old methods, make the old methods calling the new ones.

**Comment by wizzymore** [comment]
So, not taking in count the override stuff and others. Does it build on linux? Because before i failed on build at [worldserver]

**Comment by Winfidonarleyan** [comment]
@wizzymore Yes, good work in all OS. I will try to finish PR today

**Comment by wizzymore** [comment]
If you need help, pm me on discord

**Comment by Winfidonarleyan** [comment]
@wizzymore It will be necessary to test PR when I correct all errors

**Comment by wizzymore** [comment]
Add this as an issue: https://github.com/azerothcore/azerothcore-wotlk/issues/1605 , created it before i saw this PR and knowing it fixes build on linux

**Comment by Nefertumm** [comment]
Status?

**Comment by Winfidonarleyan** [comment]
I'm done, wow, really? Go test :D

**Comment by wizzymore** [comment]
Tested it, everything works fine!

Added the commits from this PR https://github.com/azerothcore/azerothcore-wotlk/pull/1600
before replacing macros:
worldserver gave build errors.
after replacing macros:
everything builds an run as intended.

Great work @Winfidonarleyan !

**Comment by Winfidonarleyan** [comment]
@wizzymore Thanks a lot for test

**Comment by Deku** [comment]
Since this is a breaking change, should be considered a version increment to AzerothCore v2.1

Also, does this work? => https://en.cppreference.com/w/cpp/language/attributes/deprecated

**Comment by Winfidonarleyan** [comment]
@Deku, good idea, I will try to test

**Comment by FrancescoBorzi** [comment]
@Deku about the versioning, it doesn't work like that:

- we released 2.0.0 and create a branch `2.x` where we put there important security fixes (if any) and release new 2.x if needed
- the current `master` is always pointing to the next big release, now would be `3.0.0` (under development): https://github.com/azerothcore/azerothcore-wotlk/blob/master/acore.json

For example, in past we release 1.0.0 and started working on 2.0.0, but meanwhile we had to release an important security fix for 1.x so there is 1.0.4: https://github.com/azerothcore/azerothcore-wotlk/releases/tag/v1.0.4

More info at: http://www.azerothcore.org/wiki/Project-Versioning

Sorry if this is a bit generic and not strictly related with the PR, but I think is important to keep this always in mind.

**Comment by Winfidonarleyan** [comment]
@Deku, need to create new PR for `deprecated`.
For Visual studio need `compile with: /W3` https://docs.microsoft.com/en-us/cpp/cpp/deprecated-cpp?view=vs-2017
For other compilers i don't know if it's necessary

If there are no objections, I think can merge PR

**Comment by Deku** [comment]
@FrancescoBorzi From the same link you mention: 

> MINOR version when you add functionality in a backwards-compatible manner

This is a breaking change that SHOULD be added in a backwards-compatible manner (adding the deprecated flag), so an increase in the minor version is applyable. And I consider this a change that should be marked in the release history since it changes the scenario for mod devs before the next major release.

**Pull request merged**
