### PR TITLE
fix(DB/Zone):improved Hinterlands II

### PR DESCRIPTION
**Pull request by Knindzagxg**
Zone now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

### CODE REVIEW

**Comment by aradep** [comment]
Tested, all working except Savage Owlbeast(2929) doesn't cast any spells.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg

**Comment by Knindzagxg** [comment]
Updated @aradep 

Please, re-test.

**Comment by aradep** [comment]
Works 👍

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
