### PR TITLE
fix(DB/SAI): Zergling vs Grunty

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- let the Zergling fight against Grunty (50% win chance)
- add Zergling aura (will trigger attack emote every 20 seconds)

###### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- First player: ```.additem 13582 (Zergling Leash)```
- Second player: ```.additem 46802 (Heavy Murloc Egg)```
- learn and summon both pets

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by poszer** [comment]
Could you check your code. Codacy didn't pass it

**Comment by Stoabrogga** [comment]
There's nothing wrong with the code, Codacy is reporting some strange errors here:
codacy

**Comment by poszer** [comment]
> There's nothing wrong with the code, Codacy is reporting some strange errors here:
> codacy

Yeah, i saw in your other PR same errors reporting from Codacy, but actually it's wrong report.

**Comment by Stoabrogga** [comment]
I changed a comment in the file in order to start Codacy once more. Perhaps it works now.

**Comment by Stoabrogga** [comment]
Ok, this time it did work. I did note that the first failed Codacy run is associated with talamortis:
https://app.codacy.com/app/talamortis/azerothcore-wotlk/pullRequest?prid=3756112

The second one, which was successful, is associated with shin:
https://app.codacy.com/app/FrancescoBorzi/azerothcore-wotlk/pullRequest?prid=3756078

I'll create an issue for this behaviour.

**Comment by Knindzagxg** [comment]
Luv this one :P

All good mate, tested ingame.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg thanks for testing. Feel free to apply the `To be merged` label after you test.

**Pull request merged**
