### PR TITLE
feat(DB/Locales): add missing esES & esMX quest locales [PART 2] (Port from TC) 

### PR DESCRIPTION
**Pull request by ErnestoGonzalezC**
## Changes Proposed:
-  Add Missing Spanish locales.

## Tests Performed:

- Tested on windows 10 and ubuntu 20.

## How to Test the Changes:

- To test these changes you must have the client in EsMX or EsES
- ``.quest add quest_id`` verify that the texts are correctly translated and logically that the description is not empty.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]
approving with trust

**Comment by Delcidx** [comment]
already imported this in https://github.com/azerothcore/azerothcore-wotlk/pull/5160

**Comment by ErnestoGonzalezC** [comment]
> already imported this in #5160


If you have already done so, why do some of the missions proposed here still have no translation?

**Comment by Delcidx** [comment]
> > already imported this in #5160
> 
> If you have already done so, why do some of the missions proposed here still have no translation?

I saw your pr and compared with mine, just to let you know. If i missed a quest then my bad, but i have these translations.

**Comment by ErnestoGonzalezC** [comment]
> > > already imported this in #5160
> > 
> > 
> > If you have already done so, why do some of the missions proposed here still have no translation?
> 
> I saw your pr and compared with mine, just to let you know. If i missed a quest then my bad, but i have these translations.

So what do you suggest to do?

**Comment by Delcidx** [comment]
> > > > already imported this in #5160
> > > 
> > > 
> > > If you have already done so, why do some of the missions proposed here still have no translation?
> > 
> > 
> > I saw your pr and compared with mine, just to let you know. If i missed a quest then my bad, but i have these translations.
> 
> So what do you suggest to do?

If what you say is true then i will check all translations again, and see which ones are still missing. Maybe, importing all the translations in one pr was a mistake.

**Pull request merged**
