### PR TITLE
fix(DB): ore node now spawns above ground

### LINKED ISSUE #5942: Tin Vein unreachable in Hillsbrad Foothills
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Vein shows on mini map bright yellow, but not visible and is stuck underground. However, not in the mine

image

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Hi Hacki

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go object 75523 This will put you in the wall of the mine below, but the vein will not show on your mini map down there.
2. .go creature 15564 will put you close to it up top

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40ed3a575ba4ba3eff9d218d018de6a20b6e29db

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98576155-tin-vein-unreachable-in-hillsbrad-foothills?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jamadaha**
## Changes Proposed:
-  Prevents the ore node (GUID 75523) in Hillsbrad Foothills from spawning in the ground, by it now spawning on a nearby hill

## Issues Addressed:

- Closes #5942

## SOURCE:

image

## Tests Performed:

- SQL commands change a single row
- Verified in game as seen in source

## How to Test the Changes:

1. .go object 75523

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by jamadaha** [comment]
This is my first pull request for this project, so I hope it was done correctly.

**Comment by Azcobu** [comment]
Congrats on the first PR, hope it's the first of many.

One thing you might find useful in future is that UPDATE lets you chain columns to update. So instead of 3 lines, you only need 1 by doing something like this:
```
UPDATE `table` SET field1 = value1, field2 = value2 ..., fieldN = valueN WHERE [conditions]
```
This helps keep the update as small as possible.

**Review by LukasVolgger — CHANGES_REQUESTED** [review]
As Azcobu requestet: You can write the UPDATE in one single line: ``SET `position_x` = -781.1, `position_y` = 185.2, `position_z` = 59.6``

**Review by LukasVolgger — APPROVED** [review]
Good Job!

**Comment by Azcobu** [comment]
If I can make another suggestion, the DB shows this node is one of 4 in the exact same place. GUIDs 75314 (ID 1731, copper), 75315 (ID 1732, tin), and 73516 (ID 1733, silver) also share the original coordinates and thus the original problem. I would suggest moving the other 3 nodes to match your fix for node 75523.

**Comment by jamadaha** [comment]
@Azcobu Should these then have the same position as a 75315 or different?

**Comment by Azcobu** [comment]
I suggested moving the other 3 nodes because I thought all four nodes sharing those coordinates would be members of the same node pool, but that turns out to be wrong. 75523 is a member of pool 2016, which is a group of 6 tin nodes. The other 3 nodes (75314/5/6) are a mini pool of their own, pool 4788. So if you moved the other 3 to the same coordinates as 75523, they could still spawn at the same time and produce a incorrect double node. So eventually they should be moved to separate and distinct coordinates.

However, moving those other 3 could be a separate PR if you wanted.

**Comment by Eldarix** [comment]
Don't know why, but after applying the query i can't see the node:

WoWScrnShot_071421_094658

**Comment by jamadaha** [comment]
That might be because it is in a pool with 5 other nodes, while the limit for the pool is 3?

**Comment by Eldarix** [comment]
@jamadaha I see, so it's correct then right? Within that limit you mention, I understand that the ones that fit comes out randomly throughout the server resets ?

thanks again !!

**Comment by jamadaha** [comment]
@Eldarix I think it's correct. I found it in the correct location in the PR. And after it didn't spawn for you, I found it on a clean AC after applying the commit.

**Comment by Eldarix** [comment]
@jamadaha nice in that case :D

take care mate and good luck

**Comment by FrancescoBorzi** [comment]
good job @jamadaha and thanks @Azcobu @Eldarix @LukasVolgger for helping!

**Pull request merged**
