### PR TITLE
Removed item DBC loading and use item_template table instead

### PR DESCRIPTION
**Pull request by Kaev**
**Changes proposed:**
-  Removed all Item.dbc related things
-  Load informations from item_template instead
-  Added all items which are used for NPCs only which were only in Item.dbc

**Target branch(es):** master

**Issues addressed:** Part of #584

### CODE REVIEW

**Comment by talamortis** [comment]
this done already?

**Comment by Kaev** [comment]
Yes, this one is done already. I'll always write WIP if my PRs still need some work done.

**Comment by talamortis** [comment]
@Kaev  tested and working fine, great work! and good contribution well done you can merge if you wish

**Comment by Kaev** [comment]
Either we will merge them one by one until it's finished or we wait until i finished all DBC related stuff and merge them all in one when they got tested

**Comment by Yehonal** [comment]
Amazing job! DBC freedom is great :D

**Comment by ShinDarth** [comment]
excellent

**Pull request merged**
