### PR TITLE
DB/Quest: Ogre Head On A Stick = Party

### PR DESCRIPTION
**Pull request by poszer**
-Simple to fix, but it was hard to find the fix

Co-Authored-By: WiZZy <bilucristian25@gmail.com>

Quest Ogre Head On A Stick = Party 

##### CHANGES PROPOSED:

-  Changed Faction 
-  

###### ISSUES ADDRESSED:

The issue was, as player you're not able to finish it. Actually not able to use quest item on that object. Just with .gm on it was posible.
Closes 

##### TESTS PERFORMED:

Tested in game, the players are able to finish it now. 
@wizzymore also tested it, everything fine :smiley: 

##### HOW TO TEST THE CHANGES:

1. .go gobject 4521
2. .quest add 3825 (You should be able to use quest that item on that object)

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Knindzagxg** [comment]
Tested few mins ago, everything is  good now.

**Comment by comix1988** [comment]
@poszer 
tested on the master branch and I had no difficulty completing it

https://youtu.be/b5NmWv21Azo

**Comment by FrancescoBorzi** [comment]
@poszer good job. I added the missing new line at the end of file to avoid issues when combining SQL files.

@Knindzagxg @comix1988 good job with testing!

**Comment by comix1988** [comment]
@FrancescoBorzi wait...i tested it on a master branch and it worked however also without fix

**Comment by FrancescoBorzi** [comment]
@comix1988 oh... sorry, my bad. I misread :)

**Comment by comix1988** [comment]
tested the quest with the sql file and it works correctly but I found no differences

**Comment by poszer** [comment]
> tested the quest with the sql file and it works correctly but I found no differences

The old faction was set to 84 which is Quilboar, Razormane. Changing it to 35, the players are able to finish quest, and use req quest item on that object.

**Comment by comix1988** [comment]
I tested again on the master branch without sql file and the quest could not be completed only for horde players.
Now with the fix it works for both factions.

**Comment by FrancescoBorzi** [comment]
so is this good to go ?

**Comment by poszer** [comment]
> so is this good to go ?

Yes, it is :smile:  We already tested it last night @wizzymore , @Knindzagxg  and me :smiley:

**Pull request merged**
