### PR TITLE
feat(Game/AI): convert `SelectAggroTarget` to enum class

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Cherrypick https://github.com/TrinityCore/TrinityCore/commit/418c3b1fd50664aad035bd975a65281e82ba2dea  

## Issues Addressed:
- Part #5985

### CODE REVIEW

**Comment by Kitzunu** [comment]
image
fuck you <3

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
I don't think this needs to be tested if CI pass. Just changing enum

**Comment by Nyeriah** [comment]
Considering the amount of files this changes, it's probably better to merge it sooner than later

**Comment by pklloveyou** [comment]
image
?_?

**Comment by pklloveyou** [comment]
image
?_?

**Comment by pklloveyou** [comment]
NEAREST = MaxDistance ?
FARTHEST = MinDistance ?

**Pull request merged**
