### PR TITLE
fix(DB/gameobject_template): fixed text for some plaques

### PR DESCRIPTION
**Pull request by gabryatfendor**
Fixed text and formatting for plaques in final room of Scarlet Monastery Armory

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10007

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. go c 89097
2. Check all the plaques in the room

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
At least one of these entries (didn't check more than one) has a VerifiedBuild value. In the future, make sure to set values in that column to `0` if you're making changes without sniffs to back them up.

Once I get a chance, I will try to verify the replacement text with a sniff.

**Comment by gabryatfendor** [comment]
@heyitsbench ok, just to understand: in this case the text was already there, I just added some newline to format it correctly: I need sniff also for this basic kind of changes (this issue did not have a "need sniff" label, that's why I'm asking)? And I suppose the verifiedBuild = 0 is valid for any change I make at the DB without sniff?

**Comment by heyitsbench** [comment]
> I need sniff also for this basic kind of changes

We prefer sniffs to back up changes to anything that can be sniffed regardless of the size of the change.

> this issue did not have a "need sniff" label, that's why I'm asking

The issue was opened before the `Needs Sniff` label was starting to get applied when it should have been iirc. Good looking out though, I do appreciate that. 😄

> And I suppose the verifiedBuild = 0 is valid for any change I make at the DB without sniff?

Yes, the VerifiedBuild value is supposed to refer to the game client build that the content was sniffed/collected from, so 0 denotes that it wasn't collected from the game itself.

**Comment by gabryatfendor** [comment]
Thanks a lot for the informations, I will try to setup the sniffer/parser then so I can learn to do that :-)

**Comment by gabryatfendor** [comment]
@heyitsbench ok, I have the related sniffs from Classic WOTLK. I have to upload them through the form before proceeding? What is the usual path to follow?

**Pull request closed without merging**
