### PR TITLE
fix(DB): Add missing script for The Binding quest

### PR DESCRIPTION
**Pull request by Raelorasz**
## Changes Proposed:
-  Add missing script for The Binding quest (ID 1795)
-  The NPCs will behave roughly as shown in the source video. After the green summoning circle is spawned the player has two minutes to summon and defeat the Summoned Felhunter. Otherwise, Strahad Farsan will despawn the circles and return to its original position

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6137

## SOURCE:

https://youtu.be/EOt6uVMi5F4?t=367

## Tests Performed:

- Tested in-game. Windows 10 - enUS client.

https://user-images.githubusercontent.com/82320853/120514601-c5d95a00-c3cd-11eb-9a3f-8868a8a21df8.mp4

https://user-images.githubusercontent.com/82320853/120514614-c83bb400-c3cd-11eb-99f8-5dadf99d1547.mp4

## How to Test the Changes:

1. Be a Horde Warlock, at least level 30
2. `.q a 1805` -> `.q complete 1805`
3. `.go c id 6251`
3. Accept the quest and play through it

## Known Issues and TODO List:

The spells chosen for the event were kind of a shot in the dark. I'm pretty sure the one casted by the acolytes is the correct one but I'm not so sure about what Strahad casts. Still, pretty similar.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
Thank you very much @Raelorasz for all the hard work you've been doing lately.

Unfortunately there are some startup errors with this PR, can you please check them?

```
The DBErrors.log file contains startup errors:

SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 0, expected 1.
SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 1, expected 2.
SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 2, expected 3.
SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 3, expected 4.
SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 4, expected 5.
SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 5, expected 6.
SmartWaypointMgr::LoadFromDB: Path entry 6251, unexpected point id 6, expected 7.
```

**Comment by Eldarix** [comment]
Checked, no issues so far in the query addition, but something is failing to me:

Screenshot 2021-06-03 050719

Before the modification some errors with the quest appears:

WoWScrnShot_060321_050033
WoWScrnShot_060321_050059

The acolytes do nothing, and you can't complete the quest after defeating the demon:

WoWScrnShot_060321_050145
WoWScrnShot_060321_050156
WoWScrnShot_060321_050234

And after the query addition the issue with the quest display seems solved, but can't progress to the demon summoning:

WoWScrnShot_060321_050541
WoWScrnShot_060321_050604

**Comment by Raelorasz** [comment]
Hey @Eldarix, thanks for testing the PR! I think the quest is not showing up because your character, in the last screenshot, is level 1; you need to be at least level 30 for the quest.

**Comment by Eldarix** [comment]
Lol !! I've made so many new characters in such a short time, that I totally forgot to level up to that last one, checking it again!

**Comment by Eldarix** [comment]
Completed without issues, all working nicelly and the acolytes animations as well:

WoWScrnShot_060321_115144
WoWScrnShot_060321_115201
WoWScrnShot_060321_115211
WoWScrnShot_060321_115217
WoWScrnShot_060321_115312

Just a little side note, don't know why but the first felhunter quest still appears after completion:

WoWScrnShot_060321_115329

**Pull request merged**
