### PR TITLE
fix(DB/Warden): Export 6 warden checks from TC that were corrupted on…

### PR DESCRIPTION
**Pull request by UltraNix**
… AC.

Updates #4827.

## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes 

## Tests Performed:
-
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by UltraNix** [comment]
Merge before #4827

**Comment by FrancescoBorzi** [comment]
@UltraNix test performed?

**Comment by UltraNix** [comment]
Yes - no more crashes.

**Comment by pklloveyou** [comment]
Tested

**Comment by Hacki95** [comment]
Why didnt you just add this to the other PR if its needed for it?

**Comment by FrancescoBorzi** [comment]
> Why didnt you just add this to the other PR if its needed for it?

because separate PRs are easier to be reviewed, tested and merged separately

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Hacki95** [comment]
> 
> 
> > Why didnt you just add this to the other PR if its needed for it?
> 
> because separate PRs are easier to be reviewed, tested and merged separately

I get that! I just wondered because if this PR is needed for the other to work and its just a bit of SQL then on the other hand this makes it way more complicated to test.

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
