### PR TITLE
fix(Core/Dungeon) Blackrock Depths - Ambassador Flamelash

### LINKED ISSUE #1771: BRD Ambassador Flamelash is not working as he should
##### SMALL DESCRIPTION:
Ambassador Flamelash is not working as he should. I have added a video link to this page
https://youtu.be/GR_CQ-eC6ns?t=1200

##### EXPECTED BLIZZLIKE BEHAVIOUR:
He should scream a sentence at the beginning of the fight: Ambassador Flamelash yells: Your reign of terror ends now! Face your doom mortals!

At the beginning of the fight, the seven runes should burn on his platform and burning spirits should appear (after about 3 seconds), which run to the ambassador Flame Strike and approach him at 1 meter. These then work burning ghost, die and give Ambassador Flame Strike a Buff, which is stackable up to 50 times. Ambassador Flame Strike gets bigger per stack and does 30 more damage for 180 seconds up to a maximum of 1,500.
Ambassador Flame Strike should also have an aura called Fire Strike (not visible to the player), which should cause an additional 185 is 215 fire damage per strike.

##### CURRENT BEHAVIOUR:
you attack the boss and he spawns the adds in his environment but not on the runes there are only 4 Burning Spirit instead of 7 and they don't buff him who they are in his environment.

##### STEPS TO REPRODUCE THE PROBLEM:
.go creature 47778 and fight

##### BRANCH(ES):

AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
mod-transmog
mod_world_chat

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/73333561-brd-ambassador-flamelash-is-not-working-as-he-should?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

- Burning spirits spawn at the correct places
- When they get close to the boss they die, thus buffing the boss with a stackable buff
- When encounter begins the runes start burning
- Burning Spirits chase the boss around the room
- Changed timers to eventmap

###### ISSUES ADDRESSED:

Closes #1771 

##### TESTS PERFORMED:

Compiled and tested locally on Windows 10

##### HOW TO TEST THE CHANGES:

.go creature 47778 and fight

##### KNOWN ISSUES AND TODO LIST:

- [x] Finish scripting the event

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Seebaby** [comment]
Error

i get an error when compiling

**Comment by Pondaveia** [comment]
@Seebaby That's strange, It passed on Travis... Can you check if you have this [import](https://github.com/azerothcore/azerothcore-wotlk/pull/1803/files#diff-cd73a05110eb91ff516d4f2c9064c9b2R9) ? Try to fetch again this PR maybe

**Comment by Seebaby** [comment]
> @Seebaby Das ist seltsam, es hat Travis weitergegeben ... Kannst du überprüfen, ob du diesen [Import](https://github.com/azerothcore/azerothcore-wotlk/pull/1803/files#diff-cd73a05110eb91ff516d4f2c9064c9b2R9) hast ? Versuchen Sie, diese PR vielleicht noch einmal zu holen

Everything good was probably bissel late yesterday so I didn't say anything 

I'll test it all out then.

**Comment by Seebaby** [comment]
> @Seebaby That's strange, It passed on Travis... Can you check if you have this [import](https://github.com/azerothcore/azerothcore-wotlk/pull/1803/files#diff-cd73a05110eb91ff516d4f2c9064c9b2R9) ? Try to fetch again this PR maybe

Everything good was probably bissel late yesterday so I didn't say anything 

I'll test it all out then.

**Comment by Pondaveia** [comment]
Just re-tested. Looks good to me. Let me know on discord if you have any issues

**Comment by Seebaby** [comment]
Looks pretty good already better than before

I found 4 errors 

No. 1 of the Fire Blast ID 15573 makes about 700 damage normal 185 to 215 Fire damage.

No. 2 Fire Blast ID 15573 drift sometimes with a swerve up to 5 times see screenshot a tank level 55 would be onehit and dead.

Flammenlag


No. 3 if the fire elementalists go to the boss and an AOE gives him damage they may not buff the boss and must attack the mage or so that makes grade aoe damage to the fire elementalists.

No. 4 If I killed all the fire elementaries that started running towards the boss without them killing themselves, there won't be any more.

**Comment by Pondaveia** [comment]
Thanks man, will take care of them. Not sure what is causing bug n° 2 yet.

**Comment by Pondaveia** [comment]
@Seebaby new changes, will you check them when you have time again please? Thanks in advance.

**Comment by Seebaby** [comment]
but very much

**Comment by Seebaby** [comment]
> @Seebaby new changes, will you check them when you have time again please? Thanks in advance.

but very much

**Comment by Pondaveia** [comment]
Sometimes i hate you @Seebaby but thanks for the test report 👍

**Comment by Seebaby** [comment]
I can imagine that well but perfect is just perfect and since I love 3.3.5a so much I hope that AC will be the best server sometime.  Is it already in my eyes there much more goes than with TC.  I liked Trinitycore earlier but there are too many mistakes made to me.  Here is more heart blood and love in it.

**Comment by Seebaby** [comment]
So I checked everything again now and it looks great the elementary stop at Aggro and the boss is no longer bufft.

So I would say super work

**Comment by Pondaveia** [comment]
FML sorry @Seebaby I made a stupid mistake. I just made them spawn when they died... I need a different aproach to this let me think.

**Comment by Seebaby** [comment]
> FML sorry @Seebaby I made a stupid mistake. I just made them spawn when they died... I need a different aproach to this let me think.

That's why I like to test it. 

What's good is the elementary go on aggro and no longer buff the boss.

Now they should just die and not spawn in addition to the 4 new ones.

**Comment by Pondaveia** [comment]
Hopefully I got it right this time 🙏 😂

**Comment by Seebaby** [comment]
> Hopefully I got it right this time 🙏 😂

mass spawn Fix check

Elementary run boss after fix check

Last problem 

If I put a fire elementary in the middle of the boss, nobody buffs the boss anymore.

Video https://youtu.be/_yh8ixSD92U

**Comment by Pondaveia** [comment]
Pretty sure I'm done @Seebaby

**Comment by Pondaveia** [comment]
Good job with testing, you're a beast

**Comment by poszer** [comment]
Thanks @Pondaveia and @Seebaby for testings. Great job

**Pull request merged**
