### PR TITLE
fix(scripts/Naxxramas): Improve Four Horsemen

### LINKED ISSUE #14203: (scripts): Divine Intervention can "cheat" Four Horsemen
### Current Behaviour

When the encounter begins and all 4 horsemen go to their corners, if a player is with [Divine Intervention](https://www.wowhead.com/wotlk/spell=19753/divine-intervention) in the middle of Lady Blaumeux and Sir Zeliek, both bosses won't do anything, while the raid is just dealing with Thane Korth'azz and Baron Rivendare.

Context - Tactic: The cheese is to [Divine Intervention](https://www.wowhead.com/wotlk/spell=19753/divine-intervention) a healer (or lowest dps) in between the 2 bosses in the back, and of course rez the dead DI'er. As long as you can kill the first 2 bosses under the DI timer (3mins) the cheese is easy. If you get to 6+ stacks on the first 2 bosses it can also be a little sketchy.

### Expected Blizzlike Behaviour

DI is supposed to drop all aggro.

That's the reason why you DI a healer when a wipe is a sure thing to happen, so you can recover faster (less downtime) as the boss will reset.

An additional check should be implemented in here:

[boss_four_horsemen.cpp - line # 365](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/Naxxramas/boss_four_horsemen.cpp#L365)
```cpp
            if ((me->GetEntry() == NPC_LADY_BLAUMEUX || me->GetEntry() == NPC_SIR_ZELIEK))
            {
                if (Unit* target = SelectTarget(SelectTargetMethod::MaxDistance, 0, 45.0f, true))
                {
                    me->CastSpell(target, RAID_MODE(TABLE_SPELL_PRIMARY_10[horsemanId], TABLE_SPELL_PRIMARY_25[horsemanId]), false);
                }
            }
```

### Source

Spell mechanic - if it were blizzlike - all guides would include it.

### Steps to reproduce the problem

Create 2 characters

1. Go into Naxxramas - The Horsemen's Assembly room
2. Place one of them on tp of the eye teleporter which is between Lady Blaumeux and Sir Zeliek's final positions.
3. Use Divine Intervention on that char
4. Use your second character to pull/attack any boss from the front position fo the room and start the event
5. Now watch how Lady Blaumeux and Sir Zeliek won't attack the DI player but also won't execute EVENT_PUNISH properly.

### Extra Notes

_No response_

### AC rev. hash/commit

d2940a0

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Si1ker**
At first, I just wanted to remove the possibility to cheat the encounter but then I saw a chance for improvements and a few bugs to be resolved.

- Damage adjusted based on the source.

## Issues Addressed:

- Closes #14203 

## SOURCE:

https://wowwiki-archive.fandom.com/wiki/Four_Horsemen

## The following scenarios have been tested during the last 3 days:

- Pull bosses with a target affected by Divine Intervention ✔ (they will ignore it and reset if is the only one left)
- Check if both caster bosses cast by distance ✔
- Check primary spell vs punish by distance and target availability ✔ (bug done when AC changed TargetSelectors)
- Try to cheat with pre-DI and post-DI on target killed by bosses ✔
- Check target selection at full room's distance ✔
- Check script events and attacks in a per-boss schema ✔
- Remove target as a valid target during boss casting ✔ (they used drop script and freeze, now they don't)
- Check half-threat wipe based in original wotlk wiki✔
- Check mark stacks dmg ratio as per original wotlk wiki ✔
... but most importantly: cheat is over.
image

## How to Test the Changes:

1. Go into Naxx
2. Engage Four horsemen encounter
3. Test anything you want to

## Known Issues and TODO List:

- None that I'm aware of, no errors server-side (noticeable by players) or in the console.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by Si1ker** [comment]
acidmanifesto approved these changes on Jan 22 😴💤

**Comment by acidmanifesto** [comment]
> acidmanifesto approved these changes on Jan 22 😴💤

I seldom merge anything anymore due to me somehow getting blamed for something half the time due to a merge i do regardless if my review was in it or not. I keep to reviews only mainly these days and only merge in exceedingly rare circumstances. I don't get blamed for stuff if i don't merge. Keeping it simple.

**Comment by Maelthyrr** [comment]
And you PR is always in waiting to be tested by someone. I'm sorry, but we have a shortage of testers. I will look to test this soonly but the woltk content is not the main priority compare to TBC fixes.

**Comment by avarishd** [comment]
I will test later (don't quote me on that).

**Comment by avarishd** [comment]
- [x] Pulled with DI target, instantly evaded
- [x] Both cast on the closest player
- [x] Both cast normal spells (to the one without DI) even if a target with a DI is between (closer).
- [x] Target updates pre and post DI.
- [x] Entire room is covered by the target selection
BUG (probably core): If you go outside of server visibility range, the spells don't hit you, even in an instance, when they should.
<details>

https://user-images.githubusercontent.com/46330494/221854998-2dd0a556-b091-43c9-b524-2f7ae7f82322.mp4

</details>

- [x] They finish their initial cast even if a valid target becomes invalid or valid mid cast.
- [ ] Threat is cut in half on every stack application, except the first one (as it does no damage, and the threat modification is applied on damage, in code). I'm not sure about the exact behaviour, but there isn't anything about having to have already applied stack(s) in order to cut threat.
- [x] Mark damage on 5 stacks is 12,500

**Comment by Si1ker** [comment]
@avarishd ty for the testing.

- Even though the threat reduction mechanic is written in the guide, the videos don't show it so it's removed. ✅
(wotlk 2008 > wotlk classic > wotlk guides)

- About the visual range, nothing I can do about it, it is configured at the server config level I think.
Bosses use CastAOE and there is no limit for the range at the spell level. ✅
image



Note: I thought using [DoCastSpellOnPlayers](https://github.com/azerothcore/azerothcore-wotlk/blob/a9fac92c8048f3c144d742cbb01130fefe840308/src/server/game/Instances/InstanceScript.h#L220) but wouldn't make the bosses cast the spell which would be an awful behavior (player-side)

**Comment by Si1ker** [comment]
> ```sql
> UPDATE `creature_addon` SET `visibilityDistanceType` = 3 WHERE `guid` IN (130964, 130961, 130962, 130963);
> ```
> 
> They had visibilityDistanceType of 1 (100y), 3 is 200y. Fixes the issue.

Good to know, added it into a new file.

[ Ready for merge - tested/approved ]

**Comment by Mitradis** [comment]
conflicts

**Pull request merged**
