### PR TITLE
feat(CI): limit workflow concurrency

### PR DESCRIPTION
**Pull request by locus313**
## Changes Proposed:
-  enabled the new workflow concurrency feature https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
hey @locus313 , what does this do in practice? I did not get it from the description. Can you give some examples please?

**Comment by locus313** [comment]
@FrancescoBorzi sure.
Let's say someone opens a pr then pushes additional fixes right after. What this will do is cancel the jobs for the initial run and only run the jobs from the most recent push. 

In affect it should keep the build pipeline from queuing a bunch of jobs due to some pr's getting lots of pushes.

**Comment by Kitzunu** [comment]
Very nice

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@locus313 can we only limit this in PRs and not on `master`? I noticed builds are now automatically cancelled on `master`. when a new commit is merged, but that's not ideal

**Comment by locus313** [comment]
@FrancescoBorzi I will check on this. There is a job level option, but let me see if there might be a way to do it without doing it at the job level.

**Pull request merged**
