### PR TITLE
fix(Core/Spells): Spellmods should not drop charges if not consumed b…

### LINKED ISSUE #13343: Mortal Strike & Slam critical hits consume a charge of Recklessness and Juggernaut
https://github.com/chromiecraft/chromiecraft/issues/4141

### What client do you play on?

enGB

### Faction

Both

### Content Phase:

60

### Current Behaviour

Currently when you use Recklessness, and then charge a unit to gain Juggernaut, your Mortal Strike or Slam if _crit_, will consume 1 stack of Recklessness _and_ the Juggernaut buff. 

### Expected Blizzlike Behaviour

If you have Recklessness up, then charge a unit to gain Juggernaut, the next Mortal Strike or Slam _crit_ should only consume the Juggernaut buff. 

### Source

https://youtu.be/Vc0O1-hAwvM?t=25

### Steps to reproduce the problem

1. `.learn 12294`
2. `.aura 1719`
3. `.aura 65156`
4. Achieve a critical hit, see if only Juggernaut is consumed

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…y spells.

Fixes #13343

## Issues Addressed:

- Closes #13343
- Closes https://github.com/chromiecraft/chromiecraft/issues/4141

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.learn 12294`
`.aura 1719`
`.aura 65156`
Achieve a critical hit, see if only Juggernaut is consumed

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Comment by mpfans** [comment]
@Gultask  Please confirm

**Comment by UltraNix** [comment]
@acidmanifesto Done.
@azerothcore/testers Please, test it.

**Review by acidmanifesto — APPROVED** [review]

**Comment by Samsequel** [comment]
Tested: It first uses the Juggernaut 25% chance to crit (so attack can be a normal hit), and after it uses the recklessness 100% chance to crit. is this intended behaviour? @UltraNix

**Comment by UltraNix** [comment]
Yep - Juggernaut has higher prio according to dbc.

**Comment by Samsequel** [comment]
Tested some other talents and it seems to be behaving as expected :)

**Pull request merged**
