### PR TITLE
fix(Core/Spells): Fingers of Frost should always proc alongside with …

### LINKED ISSUE #11339: [Mage][Talent] Fingers of Frost and Frostbite should have the same proc roll.
### Current Behaviour 

- FoF and Frostbite talent shouldn't have separate chances to proc, they be on the same "roll".

### Expected Blizzlike Behaviour 

- Fingers and Frostbite should be on the same roll, meaning when one procs the other should as well if both talents are fully maxed out (15% / 15%). Although they behave like this it doesn't mean both talents are fully linked , as Frostbite can actually proc by itself if procced by an ability that deals no damage like [Ice armor](https://wowgaming.altervista.org/aowow/?spell=43008) snare. Not exactly sure how they'd behave if they're not maxed but I'd assume it's something like FoF had a 15% chance and Frostbite 5%, Frostbite would have a 5/15 or @ 33% chance if a FoF proc were to occur. To note that Frostbite still procs on spell hit and not on cast like Fingers but a fingers proc will pretty guarantee that freeze on the target. Can be seen [here](https://youtu.be/otdlbEUUkPE?t=136) if you slow the video down to 0.25.

### Source 

https://www.mmo-champion.com/threads/641024-FrostBite-Fingers-of-Frost-question

>Yes, the proc chances are indeed related, in such a way that you can't proc Frostbite on a frost damage spell without also proccing FoF. However, you can proc FoF without proccing Frostbite if the target is immune to the Frostbite effect. In addition, you can proc Frostbite without proccing FoF if the Frostbite proc is caused by a non-damage spell such as Ice Armor.

>[From what I've gathered Frostbite and Fingers of Frost have the same proc roll and if fully speced into both they will always proc together, ok got that](https://www.wowhead.com/forums/topic/frostbite-and-fingers-of-frost-92604)

>[It will also always proc along with Fingers of Frost if both are fully talented.](https://wowwiki-archive.fandom.com/wiki/Frostbite_(mage_talent))

### Steps to reproduce the problem 

1. Go to a dummy with both Frostbite and Fingers of Frost specced with the same amount of points

2. With enough Frostbolt casts you'll see several instances of Frostbite debuff and Fingers of Frost buff proccing independently from each other

### Extra Notes

Originally Reported: https://github.com/chromiecraft/chromiecraft/issues/3123

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/ccc9bb6679c232353939812760bedbd0f30b62cf

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
…Frostbite.

Fixes #11339

 

## Issues Addressed:

- Closes #11339
- Closes https://github.com/chromiecraft/chromiecraft/issues/3123

## Tests Performed:

- Not tested.

## How to Test the Changes:

Go to a dummy with both Frostbite and Fingers of Frost specced with the same amount of points.
With enough Frostbolt casts you'll see several instances of Frostbite debuff and Fingers of Frost buff always proccing together.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Doesn't work. Even with both fully talented I can still proc them independently.
Tested with 13006 and without. Had the same problems.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Need break for previous case
image

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Gultask** [comment]
Seems to work now 👍

**Review by IntelligentQuantum — APPROVED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
