### PR TITLE
fix(DB/SAI): Quest "What Is Going On?"

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Add the missing event played during the quest "What Is Going On?" from Commander Gor'shak in Blackrock Depths.

This is based on the following TC commit:
https://github.com/TrinityCore/TrinityCore/commit/a48ca214ed40f2ffde1fd13d50b0e464a209c5da

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- preparation:
```
.q rem 3981
.q a 3981
.ad 11140
.go 378.227 -198.917 -69.9568 230
```
- just proceed with the quest chain

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested, no problem.

**Comment by Knindzagxg** [comment]
All good mate, works like charm.

PS. Did u save all issues i mentioned sometime, or shall i try to dig them again and open them as issues :P ?

**Comment by Stoabrogga** [comment]
> 
> PS. Did u save all issues i mentioned sometime, or shall i try to dig them again and open them as issues :P ?

I think all of the issues you mentioned on discord will be fixed by already existing PRs, so no need to open AC issues for them. But it would be great if you could open issues in the future as it is easier to track them here than in the discord chat history 😉

**Comment by Knindzagxg** [comment]
Will do mate :P

**Pull request merged**
