### PR TITLE
fix(Core/Spells): Added `SPELL_AURA_MOD_ABILITY_IGNORE_TARGET_RESIST`…

### LINKED ISSUE #9742: Warlock's Chaos Bolt doesn't pierces through all absorption effects and could be resisted by higher level targets
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2609

Warlock level 60 Destruction talented ability Chaos Bolt https://wowgaming.altervista.org/aowow?spell=50796 is being resisted, when it should not.
Chaos Bolt resisted (2)

Tester:

Some issues is exist. [Chaos Bolt](https://wowgaming.altervista.org/aowow/?spell=50796)

1. Absorbing auras is affecting Chaos Bolt
2. High level targets resisting part of Chaos Bolt damage even if have 0 resistance
 
WoWScrnShot_121721_182653

### Expected Blizzlike Behaviour

1. Absorbing auras like Mana Shield, Anti-Magic Shell, Power Word: Shield and etc. should not affect Chaos Bolt
2. Not sure is this issue. Maybe it's some kind of damage reduction by higher level targets. Anyway description of spell saying `Chaos Bolt cannot be resisted`. If target have same level as user of Chaos Bolt i can't get `resisted` or `partially resisted` combat log lines

### Source

Spell description
> Chaos Bolt cannot be resisted, and pierces through all absorption effects.

Wowwiki [Chaos Bolt](https://wowwiki-archive.fandom.com/wiki/Chaos_Bolt?oldid=2299174#Tips_and_tactics)

https://youtu.be/RFR4cNYzB6A?t=34
This includes a copy of the blue post issued by "ghostcrawler" greg street former Lead Systems Designer at the time.

### Steps to reproduce the problem

.aura 48066 on target
.cast 50796

make targer 20+ levels higher
.cast 50796

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d87d0a2ae892286a44a85cc230fa66d44479d4bd

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
… to Chaos Bolt Passive

Fixes #9742

## Issues Addressed:

- Closes #9742
- Closes https://github.com/chromiecraft/chromiecraft/issues/2609

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

make targer 20+ levels higher
.cast 50796

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by tkn963** [comment]
Tested so many on creatures 20-60 levels above me and there were no issues. Works as it should. 👍

**Review by Nefertumm — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Merge Conflicts.

**Comment by acidmanifesto** [comment]
Merge Conflicts

**Comment by UltraNix** [comment]
@temperrr Done.

**Comment by UltraNix** [comment]
@acidmanifesto Can be merged.

**Pull request merged**
