### PR TITLE
feat(Core/MMAPs): Reduce chances of breaking tile connections 

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/e615e2ddefd2c18b6dec8e08fb3d17580b64ea99
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
image

🤔

**Comment by IntelligentQuantum** [comment]
> image
> 
> thinking

i know, I added this to my source and I have no problem with it.

**Comment by acidmanifesto** [comment]
> > image
> > thinking
> 
> i know, I added this to my source and I have no problem with it.

With this PR:
pot holes are reduced with less ignore z-axis hits with the anticheat module using a prior formula for detection.
At the time a detection wasnt available and the only way to know about pot holes and game play issue was to look thru pathing in recast demo.

**Comment by acidmanifesto** [comment]
Marked it as to be merged later and labeled with mmaps tags. Need to ensure if there are anymore map prs to be merged we do it all at once with apprioate testing before we up uploading and updating mapes in short periods of time.

**Review by acidmanifesto — APPROVED** [review]

**Comment by Kitzunu** [comment]
Imo we merge. It doesnt update any map versions so it is fine.

**Pull request merged**
