### PR TITLE
fix(Core/Spells): Limit Polymorph and Seduction duration to 8 sec in …

### LINKED ISSUE #14386: Polymorph and Seduction duration in PvP
Original issue: https://github.com/chromiecraft/chromiecraft/issues/4258

### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

60

### Current Behaviour

Polymorph lasting 10 seconds in pvp - tested in arathi basin, on my local server

### Expected Blizzlike Behaviour

It should last 8 seconds

### Source

https://wowwiki-archive.fandom.com/wiki/Diminishing_returns

https://www.wowhead.com/guide/diminishing-returns-in-pvp-6024

### Steps to reproduce the problem

1. Join a battleground
2. Have an enemy Mage use Polymorph on you
3. Check duration

### Extra Notes

Seduction's Succubus has the same behaviour

### AC rev. hash/commit

3b5ceb43636a 2022-12-25

### Operating system

Ubuntu 20.04 - Windows 10 x64

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…PvP.

Fixes #14386

## Issues Addressed:

- Closes #14386
- Closes https://github.com/chromiecraft/chromiecraft/issues/4258

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Join a battleground
Have an enemy Mage use Polymorph on you
Check duration

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by balleny** [comment]
if you open the history of the article and go back before cata release date (before december 2010), it is stated that poly and seduction are 10 seconds.
https://wowwiki-archive.fandom.com/wiki/Diminishing_returns?oldid=2366039

**Comment by balleny** [comment]
can also be seen here
https://youtu.be/EzJt1m5VEXA?t=58

**Comment by avarishd** [comment]
wotlk recycled (+ any old video from original wrath)
https://youtu.be/dezxgcLq-8k?t=115
image

**Comment by Nyeriah** [comment]
Okay… looks like it

**Comment by Nyeriah** [comment]
I’m sorry about this @UltraNix

**Pull request closed without merging**
