### PR TITLE
fix:Dungeon Queue - Not working(#856)

### LINKED ISSUE #856: Dungeon Queue - Not working
**Description**: Was checking old issues and found towards this one - https://github.com/azerothcore/azerothcore-wotlk/issues/468

For some reason it's not fixed, people still have to leave group and remake it after completing dungeons.

**Current behaviour**: Unable to requeue again.

**Expected behaviour**: People should be able to queue again, after last boss is killed.

**Steps to reproduce the problem**: Not sure.

**Hash**: 7696bd3
**Operating system**:  Linux, Debian 9

**Modules**:  Premium, Congrats on level.

**Other Customizations**: No.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58169495-dungeon-queue-not-working?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by AyaseCore**
**Changes proposed:**
Once LFG is finished, it is forbidden to queue again.
Now I've removed this restriction.

**Target branch(es):**  master

**Issues addressed:** Closes #856

**Tests performed:** i test in game.Normal work.

**Known issues and TODO list:**
I don't know why pussywizard wanted to disable it.
There may be other problems.
So need to test it.
- [x] Test various conditions to enter LFG.

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Knindzagxg** [comment]
It's live now on my server, so players can test it even more.
Will provide more info as soon as possible.

**Comment by AyaseCore** [comment]
In fact, I have forgotten the details of LFG. In the LFG group, only leaders can continue to queue, or can any member start to queue? I asked in 856, but no one answered me.

**Comment by Deku** [comment]
@AyaseCore only the leader can re-queue either to find a new member or to do another dungeon run

**Comment by Knindzagxg** [comment]
Still testing, will have more info tonight hopefully.

**Comment by Knindzagxg** [comment]
So far everything's great.
I would suggest people to apply this fix.

Players on my server had no issues at all.

**Comment by Knindzagxg** [comment]
Its been over a week while players using fix - Everything works great.
I would put this as official fix.

**Comment by BarbzYHOOL** [comment]
Thanks a lot to @AyaseCore. Also thank you for feedback @Knindzagxg and review @Viste

**Pull request merged**
