### PR TITLE
fix(Scripts/Player): Updating Heirloom Weapons damage

### LINKED ISSUE #18083: Heirloom Weapons are Dealing more damage than they should
### Current Behaviour

I first noticed issue when I hit lvl 80 and crafted a Titansteel Destroyer to replace my Bloodied Arcanite Reaper. This was standard behavior in retail as when you hit 80 the BOAs stop being useful. However...Upon equipping the Destroyer my damage on the character screen and testing on the boss dummy dropped by about half? (exact percent is hard to determine looking at random white numbers but it would be 'around' 50%). I was concerned some mods (like the solo dungeon mod) might be causing an issue even though I was no longer in a dungeon so I spun up a fresh install of azerothcore and proceeded testing. Below are my results:

Setup:
- I set my account to permission level 3 which I believe is the highest.
- I created a paladin (all my testing has been on paladin).
- I leveled the paladin to 80 and set all weapon skills to 400 (max)
- I create some BoAs the majority of testing I did with the Bloodied Arcanite Reaper.
- I created a Bryntroll, the Bone Arbiter (ilvl 264).
- With no buffs or other gear (other than the weapons) I proceeded to bash the boss target in Silvermoon City.

The character screen damage was similar between the 2 (sorry I don't remember the exact figures but they were 'close'). The white damage on the dummy seemed to average slightly higher on the Bone Arbiter.

I did also notice in other testing that this is not limited to the Bloodied Arcanite Reaper. I also used a Venerable Dal'Rend's Sacred Charge which was also considerably overperforming.

I did do an initial dive into the DB but I got stuck when I realized that the scaling tables in the world DB were blank.

### Expected Blizzlike Behaviour

BOA weapons should not perform better than ilvl 200 lvl 80 weapons. Historically they slightly underperformed the first lvl 80 purples you can get at lvl 80

### Source

_No response_

### Steps to reproduce the problem

From above:

Setup:
- I set my account to permission level 3 which I believe is the highest.
- I created a paladin (all my testing has been on paladin).
- I leveled the paladin to 80 and set all weapon skills to 400 (max)
- I create some BoAs the majority of testing I did with the Bloodied Arcanite Reaper.
- I created a Bryntroll, the Bone Arbiter (ilvl 264).
- With no buffs or other gear (other than the weapons) I proceeded to bash the boss target in Silvermoon City.

I did not create another titansteel destroyer for my fresh test but if you also wanted to use that it should slightly outperform the bloodied arcanite reaper.

### Extra Notes

This 'feels' like a scaling issue with at least 2 of the BoA weapons. Thinking back to when I was leveling...When I switched from a blue weapon to the reaper (around lvl 30) I immediately noticed an improvement. Thinking back that should have been a signal there was an issue as I was killing mobs very quickly.

### AC rev. hash/commit

AzerothCore rev. b6cb8a572c69 2023-11-16 01:00:30 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Debian 12

### Custom changes or Modules

Was running the following mods when noticed:

AH bot mod
Solocraft mod
SoloLFG mod
Transmog mod

I did the majority of testing off a fresh install (from backup) without any mods

### PR DESCRIPTION
**Pull request by Knindzagxg**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).

## Issues Addressed:

- Closes #18083

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue

- You can follow steps from report by Dracko

    I set my account to permission level 3 which I believe is the highest.
    I created a paladin (all my testing has been on paladin).
    I leveled the paladin to 80 and set all weapon skills to 400 (max)
    I create some BoAs the majority of testing I did with the Bloodied Arcanite Reaper.
    I created a Bryntroll, the Bone Arbiter (ilvl 264).
    With no buffs or other gear (other than the weapons) I proceeded to bash the boss target in Silvermoon City.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
What's the source on these numbers?

**Comment by FrancescoBorzi** [comment]
also I'm wondering if it could make sense to create a conf for these values, so users can easily customise them

**Comment by Nyeriah** [comment]
Maybe make a conf then and keep the original values as default, can't accept it as it is granted the values are correct

**Comment by Kitzunu** [comment]
Closing as abandoned as no response from the author for 2 months

**Comment by Knindzagxg** [comment]
Re-opening this @Kitzunu 
Values we have currently in the core are wrong.

Tested multiple times, and simple Heirloom 2h Axe beats 25man drop from Naxx.

Please, do not close till u check / test and verify cause some of those issues must be fixed as soon as possible.

PS. Im not always active on the web, but can poke me on Discord anytime so i can check things on git.

**Comment by Kitzunu** [comment]
They are taken from the client. So something else must modify them because the values are correct

**Comment by Knindzagxg** [comment]
Not sure what else could change it since i wasnt able to find.
With those values during tests damage was fine.

If anyone else have any idea where we could find / change it lemme know.
Also idea about adding it to config is not bad at all.

**Comment by amed80** [comment]
https://github.com/TrinityCore/TrinityCore/blob/73a879449a302baf8a984c7614843f5e88f48c1c/src/server/game/Entities/Player/Player.cpp#L7621
could this help ? 
that's from this commit i believe https://github.com/TrinityCore/TrinityCore/commit/f1986c6aafdf2457902a7a4cc7acc903cbbdc7bb

**Comment by Knindzagxg** [comment]
Uhm not sure tbh.
Will try and see.

**Comment by sudlud** [comment]
@Nyeriah can this be closed in favor of #20357 ?

**Comment by Nyeriah** [comment]
Yes this is not correct unfortunately

**Pull request closed without merging**
