### PR TITLE
fix(Core/SpellMgr): Essence of Wintergrasp

### LINKED ISSUE #4109: 'Essence of Wintergrasp' buff error
1. change worldserver.conf
Wintergrasp.Enable = 1 to Wintergrasp.Enable = 0
2. restart worldserver 
3. A party to a Alliance or Horde , still get 'Essence of Wintergrasp' buff

AzerothCore revision : 96c7d42+ 2020-12-24 02:48:51 +0000 (master branch)
OS:ubuntu 18.04

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95629452-essence-of-wintergrasp-buff-error?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by aradep**
## Changes Proposed:
Prevents players from getting the Essence of Wintergrasp buff while Wintergrasp is disabled in worldserver.conf

## Issues Addressed:
- Closes #4109 

## How to Test the Changes:
Set `Wintergrasp.Enable=1`
Restart server, check if horde or alliance players get Essence of Wintergrasp in Dalaran.

Set `Wintergrasp.Enable=0`
Restart server, check if horde or alliance players get Essence of Wintergrasp in Dalaran.

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@mpfans can you please test this one?

**Comment by mpfans** [comment]
Set Wintergrasp.Enable=0

horde no buff

alliance  no buff


and then Set Wintergrasp.Enable=1  restart server

horde capture wintergrasp,horde have buff


alliance  no buff


Confirmed it's fixed

**Comment by pklloveyou** [comment]
Tested

**Comment by Kitzunu** [comment]
Thanks!

**Pull request merged**
