### PR TITLE
refactor(Scripts/ZulAman): Nalorakk refactored

### PR DESCRIPTION
**Pull request by elthehablo**
Simplified the gauntlet quite a bit. Also used some information from sniffs, like some extra text.

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes unreported issue 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by kissingers** [comment]
Good, but I find there  are some door object miss in database, such as the 4 boss, player can come form back door.
Also many of the patrolling creature, if find players would run off to bang on the drums. Now only one drumming action in SAI, which bang the air and then fight with the player but not run alway.

**Comment by elthehablo** [comment]
> Good, but I find there are some door object miss in database, such as the 4 boss, player can come form back door. Also many of the patrolling creature, if find players would run off to bang on the drums. Now only one drumming action in SAI, which bang the air and then fight with the player but not run alway.

Our team will likely be working on this somewhere in the next couple of months. Make sure to report the issues if they haven't already been reported.

Anyway, this is probably out of the scope of this PR.

**Comment by elthehablo** [comment]
Review pls

**Review by Nyeriah — APPROVED** [review]

**Comment by kissingers** [comment]
after this PR, sometimes the boss will not work. 
If it work, it will say something, if it not work, it will say nothing and not walk.
I test 10 times only 3 times ok.
even if I clear all world database and test again, it still same as before
image

**Comment by kissingers** [comment]
If I near the boss , change to GM mode, then logout game. wait the instance free from the memory(I set to 2 min so veryfast), then logon, remove the gm Status near the boss ,It always work ok.

So might the distance with the play judge might have problem?

**Comment by kissingers** [comment]
also miss the Instance DONE ,so will something problem with the bags and doors after the boss

image

**Comment by kissingers** [comment]
And there are some delay now way. if kill the creature much fast, the boss still wait for finishing the now Status.
And before if kill creature and go to  the near boss very fast, the boss will very fast turn to next position and to next Status.

**Comment by kissingers** [comment]
I konw what the problem why sometimes the boss will not move when the player near it. becasue  the para unit8 _phase never initialization and direct used in here, so sometimes it will not 0, might any of 0-255, so the boss will never move.

        if (who->IsPlayer() && _phase < PHASE_START_COMBAT && _active)

so might need change the define

private:
    uint8 _phase = 0; 

or at any place init it.

**Pull request merged**
