### PR TITLE
fix(Core/SpellEffects): Make Shadowmeld drop combat

### PR DESCRIPTION
**Pull request by Kitzunu**
## CHANGES PROPOSED:
-  Make Shadowmeld drop combat in open world
-  

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3266

## TESTS PERFORMED:
- Builds
- Tested in-game

## HOW TO TEST THE CHANGES:

1. Aggro a mob
2. Use Shadowmeld (`.cast 58984`)
3. See that you lost combat and aggro
4. Use 2 characters and go into an instance and start a boss fight
5. Use Shadowmeld (`.cast 58984`)
6. See that you do not lose combat

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
@r0m1ntik94

**Comment by r0m1ntik94** [comment]
Capture d’écran 2020-08-09 à 20 11 11

**Comment by Kitzunu** [comment]
good, test in open world too :)

**Comment by r0m1ntik94** [comment]
work:)

**Comment by HeartWell** [comment]
Isn't this a hack?

**Comment by Kitzunu** [comment]
Why?
The first `if` checks if the player is in an encounter, and will thereby not drop combat, which I don't touch either.
since the `else` don't check for anything specific it is clearly for open world and thereby the CombatStop(false) makes 0 sense

**Comment by FrancescoBorzi** [comment]
@HeartWell welcome back!

**Comment by HeartWell** [comment]
@Kitzunu sorry for my English. I'll try to explain. In the description of the spell it is written that there is a probability that you will not be noticed, and not 100% option to leave the battle. I think it all depends on the distance and level of the mob.

[https://youtu.be/oxWeBE_cbyI](Test)

**Comment by Kitzunu** [comment]
To me, this is the only way that makes sense atm.
because if you are stealth, higher-level enemies can still see you.

**Comment by HeartWell** [comment]
Ops sorry it's my fail. i dont close PR. I cloase only me PR.

**Comment by P-Kito** [comment]
How does this behave against Raidbosses?
When you use it while fighting an encounter you could Shadowmeld and Ressurrect?

**Comment by Kitzunu** [comment]
No.

**Pull request merged**
