### PR TITLE
fix(DB/Dungeon): The Nexus

### PR DESCRIPTION
**Pull request by Kitzunu**
Continue of https://github.com/azerothcore/azerothcore-wotlk/pull/2877 because I fucked up my Fork :D

## CHANGES PROPOSED:
- Add money loot to all bosses that were missing. (These values do not have a reliable source. I used old videos and the already entered money values in DB to calculate something that looks okay)
- Berinand's Research respawn time changed to 2 sec
- Respawn Crazed Mana-Wyrm and fix weird hover state
- Respawn Azure Skyrazor and fix weird hover state
- Chaotic Rift rework SAI to be blizzlike.
- Respawn Crazed Mana-Wraith

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2874
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2913

## TESTS PERFORMED:
- Ran SQL
- Tested in-game. Works!

## HOW TO TEST THE CHANGES:

- Check the linked issue

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
closes https://github.com/azerothcore/azerothcore-wotlk/issues/2913

Crystalline Frayer will now be untargetable while in their Seed Pod

**Comment by Kitzunu** [comment]
@Maurowin Ready for test <3
Don't forget you need to build this time

**Comment by Kitzunu** [comment]
@Maurowin feel free to test https://github.com/azerothcore/azerothcore-wotlk/pull/2871in the progress too.

**Comment by merdlin** [comment]
Your fixes are excellent, it works.

**Pull request merged**
