### PR TITLE
fix(DB/gameobject): Fixes quest In Memoriam

### PR DESCRIPTION
**Pull request by wizzymore**
##### CHANGES PROPOSED:
-  Change the faction of Horn Fragment

##### ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2138

##### TESTS PERFORMED:
.go go 268627
.sum Normal_Player ( Non GM )

##### HOW TO TEST THE CHANGES:

.go go 268627
.sum Normal_Player ( Non GM )
##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Did you test this using the latest commit and a fresh DB? This should already have been fixed in PR #2231. Only the phase of the object was wrong (as you proceed through the "Sons of Hodir" quest chain the area "Thunderfall" is phased).

**Comment by Stoabrogga** [comment]
As a side note: The faction of a game object does not affect it's visibility, it only affects damage calculation through spells. Visibility is controlled via phase mask of the game object.

**Comment by Stoabrogga** [comment]
Ok, tested on commit 6ebd64e5c3c082d34fa0376857552ed494ad0bfa with a fresh DB and the quest is working fine, so this PR is not needed.

**Comment by wizzymore** [comment]
Indeed this was fixed, the way i tested was wrong.

Good job @Stoabrogga with that PR!

I will close this.

**Pull request closed without merging**
