### PR TITLE
fix(DB/Creature): Remove Skeletal Executioner from Silverpine Forest

### PR DESCRIPTION
**Pull request by Raelorasz**
## Changes Proposed:
-  Remove high level Skeletal Executioner from Silverpine Forest

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5237
- Closes https://github.com/chromiecraft/chromiecraft/issues/400

## SOURCE:

- https://wowpedia.fandom.com/wiki/Skeletal_Executioner

## Tests Performed:

- Tested in-game 

## How to Test the Changes:

.go 840 60 40 [The Dawning Isles]

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
thanks ;-)

**Comment by pklloveyou** [comment]
tested

**Comment by FrancescoBorzi** [comment]
this PR cannot be merged yet, it causes a startup DB error:

> 2021-04-11 14:56:57 Creature (GUID: 52542) does not exist but has a record in `creature_addon`

@Raelorasz can you please have a look at it?

**Comment by Raelorasz** [comment]
> 
> 
> this PR cannot be merged yet, it causes a startup DB error:
> 
> > 2021-04-11 14:56:57 Creature (GUID: 52542) does not exist but has a record in `creature_addon`
> 
> @Raelorasz can you please have a look at it?

@FrancescoBorzi It should work fine now.

**Pull request merged**
