### PR TITLE
fix(db/Quest Template) Change QuestType in quest 13070

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
-  I was checking if the quest, had any condition that made it not to be taken, after being abandoned and I had no problems. Then, I noticed that the QuestType was set to 0, and I tried setting it to 2, which resulted in being able to take it and leave it as many times as necessary.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14791

## Tests Performed:

- Windows 10
- In-game

## How to Test the Changes:

1. `.go c id 28179`
2. `.quest add 13070` or complete the missions until you reach that
3. Abandon it and you will not be able to retake it.
4. Then apply the SQL and try again.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by heyitsbench** [comment]
Lines up with sniffs. 👍

**Comment by acidmanifesto** [comment]
> Lines up with sniffs. 👍

Love them lines.

**Comment by mpfans** [comment]
tested and work!

**Comment by pangolp** [comment]
The truth is that I did not get the information from any sniff, I simply found that value, which caught my attention and I decided to try it to see if it works, but better if it is corroborated by a sniff. Thanks for the confirmation and for the test.

**Comment by Nyeriah** [comment]
Thanks for the PR

**Comment by pangolp** [comment]
> Thanks for the PR

You're welcome.

**Pull request merged**
