### PR TITLE
fix(Scripts/BlackMorass): Improved Opening the Dark portal encounter.

### LINKED ISSUE #14852: [Opening the Dark Portal] Missing DPS check mechanic
### Current Behaviour

Rifts only spawn after the last one was destroyed.

### Expected Blizzlike Behaviour

If not killed quickly enough, another rift is spawned.

## From my research:

1. There is a timer for when another rift spawns.
2. If there is one spot open for a rift to spawn, then there's a 2-minute timer for when another rift can spawn.
3. If there are no spots left open no rifts can spawn.
4. As soon a spot opens, the 2-minute timer starts.
5. If there are no rifts up, then another spawns instantly.
6. If you're in the 13th rift or higher, the rift time limit is lowered to 1:30.
7. In Normal Mode, Boss Rifts have a 2.5-minute time limit until the next one spawns
8. In Heroic Mode, Boss Rifts have a 5-minute time limit until the next one spawns
9. Yes, 2 bosses can be up at one time

When the boss dies, I've still not found a conclusion to it. It seems that either it starts a 30s timer for the next portal OR the timer that was counting down as soon as the boss rift spawned, whichever is lowest.
I.e. If the group in Normal Mode takes 2:15 to kill a boss, the next rift opens in 15s.
Looking at the DBM code hasn't revealed much to me :(

### Source

Retail

### Steps to reproduce the problem

`.go c id 15608`

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/c3dd1b7a5ca0a9945d609213fdd3c4a19e0106e2

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #14852

## Issues Addressed:

- Closes #14852

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go c id 15608`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@Gultask Please - test it.

**Comment by Maelthyrr** [comment]
Tested and based on the report:
- [X] If the players are not fast, another rift can spawn
- [X] Timers look good
- [ ] After some waves, if you kill quickly a rift, there is no other spawns instantly.

**Comment by UltraNix** [comment]
@Maelthyrr 
`After some waves, if you kill quickly a rift, there is no other spawns instantly.`
Have you waited at least 2 min?

**Comment by Maelthyrr** [comment]
> 



> @Maelthyrr `After some waves, if you kill quickly a rift, there is no other spawns instantly.` Have you waited at least 2 min?
> 
> ```
> If there are no spots left open no rifts can spawn.
> As soon a spot opens, the 2-minute timer starts.
> ```

I just had a doubt about understanding. So, everything is good

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by UltraNix** [comment]
@IntelligentQuantum Done.

**Comment by Gultask** [comment]
more conflicts

**Comment by UltraNix** [comment]
@Gultask Done.

**Pull request merged**
