### PR TITLE
fix(DB/DustwallowMarsh): allow Apprentice Morlann to talk whilst looking for reagents next to Tabetha's shack

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16341
- Closes https://github.com/chromiecraft/chromiecraft/issues/5653

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

the actions were already present. I only connected the right things in `waypoint_scripts`. It looks accurate. Text was also already present in `broadcast_text`

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. `.list creature 23600`
2. `.go creature <apprenticemorlannguid>`
3. marvel at how he found his tongue again

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
CC issue.

**Comment by elthehablo** [comment]
> CC issue.

Was not linked iirc?

**Comment by elthehablo** [comment]
Oh in extra notes reeee

**Comment by elthehablo** [comment]
Why would you put it in there... Bench???

**Comment by heyitsbench** [comment]
> Why would you put it in there... Bench???

I always put it in there because that's where it goes.

**Comment by elthehablo** [comment]
I will push my latest commit adding the wps in SAI. Currently the movement is very wonky. It seems he wants to move to the next wp before getting the pause instruction so it looks weird.

**Comment by Gultask** [comment]
That's why I separate the waypoints :p 
We should also focus on fixing the delay not working properly

If I was you I'd wait for a sniff on their interactions

**Comment by elthehablo** [comment]
> That's why I separate the waypoints :p 
> We should also focus on fixing the delay not working properly
> 
> If I was you I'd wait for a sniff on their interactions

Yuppp good shout I will leave this open till Bench sniffs this

**Comment by neifion-00000000** [comment]
@elthehablo @heyitsbench I'm babysitting this one so lmk if you need me to get this sniff if this is still going to be worked on

**Pull request closed without merging**
