### PR TITLE
fix(DB/SmartAI): Gelkis Rumbler & Gelkis Earthcaller

### PR DESCRIPTION
**Pull request by BeefSteaker**
## Changes Proposed:
-  Removes Rock Shell ability

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11486

## SOURCE:

https://user-images.githubusercontent.com/11332559/200976702-7e7f8cbd-bf88-4520-86cd-a354e7209a88.mp4

## Tests Performed:

- tested on local 
- 

## How to Test the Changes:

1. .go c id 4661
2. enter combat and see if they cast rock shell
3. .go c id 4651
4.  kill Gelkis Rumbler
5.  die ( target self and .damage 1000000 )

## Known Issues and TODO List:

- [ ] doesnt work with feign death and vanish, prehaps due to flag "[Cannot be used in combat](https://www.wowhead.com/tbc/spells?filter=33;2;0)"
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
I'm pretty sure the subname would be automatically created by the core. Instead of having the creature itself be statically called "Gelkis Earthcaller's Minion", it would be created as a minion of Gelkis Earthcaller, and given a tag on summon to fit that. Wowhead NPC pages typically include the static subnames on the page itself, such as [Aliocha Segard](https://www.wowhead.com/wotlk/npc=30431/veteran-crusader-aliocha-segard).

**Comment by Nyeriah** [comment]
> I'm pretty sure the subname would be automatically created by the core. Instead of having the creature itself be statically called "Gelkis Earthcaller's Minion", it would be created as a minion of Gelkis Earthcaller, and given a tag on summon to fit that. Wowhead NPC pages typically include the static subnames on the page itself, such as [Aliocha Segard](https://www.wowhead.com/wotlk/npc=30431/veteran-crusader-aliocha-segard).

This correct

the creature summon method could be wrong 
Eg manually spawn instead of proper spawn by spell

**Comment by BeefSteaker** [comment]
ok, ive removed that part.

**Review by temperrr — APPROVED** [review]

**Comment by Kitzunu** [comment]
Appreciated

**Pull request merged**
