### PR TITLE
fix(Scripts/Temple of AhnQiraj): Twins Emperor entrance door should b…

### LINKED ISSUE #13395: [AQ40] Twin emperors door open without killing Huhuran
original issue https://github.com/chromiecraft/chromiecraft/issues/4174
### Current Behaviour

Twin emperors door is open without killing Huhuran, allowing you to skip this boss

image

### Expected Blizzlike Behaviour

Princess Huhuran shouldnt be skipable (mandatory boss!). Gate to Twins should be closed or C'Thun not accessible if Huhuran is still alive.

### Source

https://classic.wowhead.com/guides/temple-ahnqiraj-aq40-overview-classic-wow

image
https://classic.wowhead.com/npc=15509/princess-huhuran

Princess Huhuran wouldnt be listed everywhere as a mandatory boss if they were skippable

### Steps to reproduce the problem

.tele aq40
.go xyz -8912 1358 -95

### Extra Notes

Princess Huhuran is a major gear check for aq40 as it requires Nature resistance gear. it being skippable eliminates a significant challenge of the raid, and allows access to c'thun/ouro loot earlier than might be expected

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
…e opened once Huhuran is defeated.

Fixes #13395

## Issues Addressed:

- Closes #13395
- Closes https://github.com/chromiecraft/chromiecraft/issues/4174

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.tele aq40`
`.go xyz -8912 1358 -95`
Door should be closed if Princess Huhuran is alive

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Wait - it shouldn't, it's always open on retail

**Comment by UltraNix** [comment]
#13395
"Expected Blizzlike Behaviour
Princess Huhuran shouldnt be skipable (mandatory boss!). Gate to Twins should be closed or C'Thun not accessible if Huhuran is still alive."
C'mon guys...

**Comment by Gultask** [comment]
We talked about it in the comments and even added the Not Confirmed label to it, we were just waiting to get a new better source for it.

Changing it to C'Thun won't do anything because you need to kill Twins to access C'Thun anyway.

**Comment by Nyeriah** [comment]
Thanks for the PR but closing as it is intended behavior

**Pull request closed without merging**
