### PR TITLE
feat(Core/Hook): A few new hooks

### PR DESCRIPTION
**Pull request by Stoabrogga**
## CHANGES PROPOSED:
I tried to introduce a few generic hooks which can help getting rid of the [patch file](https://github.com/azerothcore/mod-ah-bot/blob/6198ee2f30747b7dd66a517f8dd1537ed31272e1/ahbot.patch) of the [AuctionHouseBot module](https://github.com/azerothcore/mod-ah-bot):

**AuctionHouseScript**
- OnBeforeAuctionHouseMgrSendAuctionWonMail
- OnBeforeAuctionHouseMgrSendAuctionSalePendingMail
- OnBeforeAuctionHouseMgrSendAuctionSuccessfulMail
- OnBeforeAuctionHouseMgrSendAuctionExpiredMail
- OnBeforeAuctionHouseMgrSendAuctionOutbiddedMail
- OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail
- OnBeforeAuctionHouseMgrUpdate

**MailScript** (new ScriptObject!)
- OnBeforeMailDraftSendMailTo

## ISSUES ADDRESSED:
none

## TESTS PERFORMED:
- tested build on Ubuntu 16.04 / clang 7
- tested using a modified version of mod-ah-bot

## HOW TO TEST THE CHANGES:
see https://github.com/azerothcore/mod-ah-bot/pull/15

## KNOWN ISSUES AND TODO LIST:
none

## Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
The change works fine for mod-ahbot and thank you very much stoabrogga for this as you don't even use mod-ahbot! (i commented here https://github.com/azerothcore/mod-ah-bot/pull/15 )

**Comment by FrancescoBorzi** [comment]
so @BarbzYHOOL is this ready to be merged?

**Comment by BarbzYHOOL** [comment]
in my **humble** opinion, yes

**Comment by Yehonal** [comment]
Nice, clear, and you mastered the Hook naming <3 but, if I can suggest you a small improvement:

        bool sendNotification = true;
        bool updateAchievementCriteria = true;
        bool sendMail = true;

These variables are a sort of "default" parameters of a function...so would be nice to use them as "real default parameters" 😄 

https://en.cppreference.com/w/cpp/language/default_arguments

In this ways

1. you don't have to change the callers
2. you can use those 2 methods you've changed in other context changing the behaviour of the function itself, without even use the hook. For example a module could manually run that function and disable the mail (maybe it will never happen but it's nice to have)
3. those variables become more useful in general :) 

Please, let me know what you think

**Comment by Stoabrogga** [comment]
@Yehonal 
You mean something like this?
```cpp
void SendAuctionSuccessfulMail(AuctionEntry* auction, SQLTransaction& trans, bool sendNotification = true, bool updateAchievementCriteria = true, bool sendMail = true);

void SendAuctionExpiredMail(AuctionEntry* auction, SQLTransaction& trans, bool sendNotification = true, bool sendMail = true);

void SendAuctionOutbiddedMail(AuctionEntry* auction, uint32 newPrice, Player* newBidder, SQLTransaction& trans, bool sendNotification = true, bool sendMail = true);

void SendMailTo(SQLTransaction& trans, MailReceiver const& receiver, MailSender const& sender, MailCheckMask checked, uint32 deliver_delay, uint32 custom_expiration, bool deleteMailItemsFromDB = false, bool sendMail = true);
```

**Comment by Yehonal** [comment]
> @Yehonal
> You mean something like this?
> 
> ```c++
> void SendAuctionSuccessfulMail(AuctionEntry* auction, SQLTransaction& trans, bool sendNotification = true, bool updateAchievementCriteria = true, bool sendMail = true);
> 
> void SendAuctionExpiredMail(AuctionEntry* auction, SQLTransaction& trans, bool sendNotification = true, bool sendMail = true);
> 
> void SendAuctionOutbiddedMail(AuctionEntry* auction, uint32 newPrice, Player* newBidder, SQLTransaction& trans, bool sendNotification = true, bool sendMail = true);
> 
> void SendMailTo(SQLTransaction& trans, MailReceiver const& receiver, MailSender const& sender, MailCheckMask checked, uint32 deliver_delay, uint32 custom_expiration, bool deleteMailItemsFromDB = false, bool sendMail = true);
> ```

Exactly

**Comment by BarbzYHOOL** [comment]
Thank you @Yehonal ! Can we merge it now? (because it will allow us to merge the PR in another module)

**Comment by Stoabrogga** [comment]
@Yehonal 
Thanks for all your feedback. I applied the changes and also added 3 more hooks in order to have one for each auction house mail:
- OnBeforeAuctionHouseMgrSendAuctionWonMail
- OnBeforeAuctionHouseMgrSendAuctionSalePendingMail
- OnBeforeAuctionHouseMgrSendAuctionCancelledToBidderMail

Could you please take another look at these?

**Pull request merged**
