### PR TITLE
fix(DB/Quest): "Gaining Acceptance" Reputation limit

### PR DESCRIPTION
**Pull request by iraizo**
## Changes Proposed:
-  Change `Req.MaxRepValue` to 6000 instead of 0

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7552
- closes https://github.com/chromiecraft/chromiecraft/issues/1503

## Tests Performed:

- None

## How to Test the Changes:

Look at https://github.com/azerothcore/azerothcore-wotlk/issues/7552

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by baranzadeoglu** [comment]
> @iraizo We need 3000 rep for neutral to friendly and another 6000 rep for friendly to honored, so the max rep value should be 9000 here! I didn't know, and just found this out myself. Please change the value to 9000 otherwise the quest will no longer be available halfway through friendly.

I believe the right max value should be 8375. Here is why.

There is basically 2 quests. From friendly to honored these two are the only way of gaining rep (apart from quests).
One is gaining acceptance, requires 4 residue, rewards 25 rep.
other one is gaining even more acceptance, requires 100 residue, rewards 625 rep.
Now latter already cuts out at max rep 9000 but if you cut the former at 9000 rep as well one can get up to 8975 rep with the first, then turn in the second for 9600 total rep whereas residue turn-ins should have been out of the picture at 9000 rep marker.

**Comment by syssneck** [comment]
@baranzadeoglu That works as intended. The quest only checks, what your reputation is at the moment you "take" the quest and not with the reputation gained after completing the quest. Of course, you could do that and, in fact, the whole point of the quests is, to get to honored (and beyond). The only reason for the "Gaining Even More Acceptance" quest is, to make it less tedious.
Also, from honored to revered you need another 12000 reputation and 600 is very little compared to that. That was only the easy part of the rep grind for the Thorium Brotherhood, the hard part starts from honored on.

The max. value of 8375 renders the problem, that players could get into the situation of not having enough rep to be honored (<9000) but can't do the quests anymore, because their rep might be over 8375 (for example you have 8000 rep and do one of the "Gaining Even More Acceptance" quest = 8625)

There are people in the comments, from patch 3.1.0 & 3.1.3, who did the exact same thing you described back in the day: https://www.wowhead.com/quest=7737/gaining-even-more-acceptance#comments

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by syssneck** [comment]
@FrancescoBorzi it is all good and can be merged. I'm not sure, if I should set the "to be merged" label without any reviewer approving the changes, so that is why I waited with it. I don't want to skip any steps, but I'm feeling confident enough, to review easy SQL changes myself.

**Comment by FrancescoBorzi** [comment]
> I'm not sure, if I should set the "to be merged" label without any reviewer approving the changes, so that is why I waited with it

yes, you can apply [To Be Merged] as soon as the PR has been tested. The code review approval is also required so GitHub won't let people merge without it ;)

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
