### PR TITLE
feat(conditions): prevent adding bad contitions + align enums with TC

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
This improves the way we handle table `conditions`. You can find its TC reference here: https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130002/conditions#conditions-

------
### Field `SourceTypeOrReferenceId`

- When `SourceTypeOrReferenceId` that are not supported on 3.3.5a are used, show the following error:

> "ConditionSourceType XX in `condition` table is not supported on 3.3.5a, ignoring."

Current source types that are not supported in 3.3.5a: `25`, `26`, `27`.

------

###  Field `ConditionTypeOrReference`

- `CONDITION_QUEST_SATISFY_EXCLUSIVE` has been moved from `50` to `101`

- `CONDITION_HAS_AURA_TYPE` has been moved from `51` to `102`

- When `ConditionTypeOrReference` that are not supported on 3.3.5a are used, show the following error:

> SourceEntry YY in `condition` table has a ConditionType that is not supported on 3.3.5a (XX), ignoring.

Current condition types that are not supported in 3.3.5a: `41`, `48`, `49`.

- When `ConditionTypeOrReference` that are not yet supported on AzerothCore are used, show the following error: 

> "SourceEntry YY in `condition` table has a ConditionType that is not yet supported on AzerothCore (XX), ignoring."

Current not supported in AzerothCore condition types: `42`, `43`, `44`, `45`, `46`

------

###### ISSUES ADDRESSED:

Updates: https://github.com/azerothcore/azerothcore-wotlk/issues/1372 

##### TESTS PERFORMED:

Build, runs

##### HOW TO TEST THE CHANGES:

- Make sure the errors described above are currently displayed
- Make sure the 2 moved condition types are not broken

##### Target branch(es):

Master

### CODE REVIEW

**Comment by wetbrownsauce** [comment]
Tested. 

#### Test Cases:
- [Sandfury Shadowcaster](https://wowgaming.altervista.org/aowow/?npc=5648#abilities) in Zul'Farrak use `ConditionTypeOrReference` 51 to check if a player is mounted first before deciding whether or not to run `smart_scripts` 5648, `id` 0 (which dismounts the player on aggro). 

- [Ormus the Penitent](https://wowgaming.altervista.org/aowow/?npc=38316#starts) in ICC uses `ConditionTypeOrReference` 50 to determine which Ashen Verdict rep ring to give the player if they select that they lost their ring. 

- Inserted records into `conditions` that use `ConditionTypeOrReference` 41, 48, 49, 42, 43, 44, 45, 46.

- Inserted records into `conditions` that use `SourceOrReferenceId` 25, 26, 27.

#### Results:
- [Sandfury Shadowcaster](https://wowgaming.altervista.org/aowow/?npc=5648#abilities) correctly cast dismounting blast only if the player is mounted. `ConditionTypeOrReference` 51 still works. 

- [Ormus the Penitent](https://wowgaming.altervista.org/aowow/?npc=38316#starts) correctly provides the right Ashen Verdict rep ring to the player if they select that they lost theirs. `ConditionTypeOrReference` 50 still works. 

- Results of faulty inserts:
```
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not supported on 3.3.5a (41), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not yet supported on AzerothCore (42), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not yet supported on AzerothCore (43), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not yet supported on AzerothCore (44), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not yet supported on AzerothCore (45), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not yet supported on AzerothCore (46), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not supported on 3.3.5a (48), ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not supported on 3.3.5a (49), ignoring.
2019-01-29 14:52:12 ConditionSourceType 25 in `condition` table is not supported on 3.3.5a, ignoring.
2019-01-29 14:52:12 ConditionSourceType 26 in `condition` table is not supported on 3.3.5a, ignoring.
2019-01-29 14:52:12 ConditionSourceType 27 in `condition` table is not supported on 3.3.5a, ignoring.
2019-01-29 14:52:12 SourceEntry 66741 in `condition` table has a ConditionType that is not yet supported on AzerothCore (47), ignoring.
```

Note, `ConditionTypeOrReference` 47 is in your code as not supported on AC, but you did not mention it in the PR description. If this is correct behavior and you just missed it when writing to PR description, then ignore this message lol.

**Comment by FrancescoBorzi** [comment]
@wetbrownsauce  Thanks a lot for your feedback. As usual, very good testing work.

About the number `47` you're right, I just forgot to add it in the description. I have only one question:

>  51 still works.
>  50 still works.

I assume that you  verified that those `ConditionTypeOrReference` still works even after the PR, which actually moves them to new IDs (101 and 102) and you did **not** inserted them as "50" and "51" **after** the PR.

Is my assumption correct?

**Comment by wetbrownsauce** [comment]
@FrancescoBorzi For types 50 & 51, I did not insert any data, I used the existing ones (now 101 and 102 with this PR). I wasn't clear, my bad. I will update my reply to reflect that they work with the new values.

**Comment by FrancescoBorzi** [comment]
perfect, thank you very much, that was what I thought but just wanted to double check.

Merging this!

**Pull request merged**
