### PR TITLE
fix(DB/Quest): Disabled quest A little luck (6606)

### PR DESCRIPTION
**Pull request by Asthalor**
As the last sources ive found seems to prove that thgis quest was removed at some point (on classic wow is not showing, and in some wotlk addons seems to agree on that) ive changed the scope of this issue.

## Changes Proposed:
-  As the sources indicates that the quest was removed at some point on classic this quest should be disabled.

## Issues Addressed:

- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/9334
- Closes https://github.com/chromiecraft/chromiecraft/issues/2399

## SOURCE:

https://user-images.githubusercontent.com/87535580/145009847-3c56a5e3-7112-4a72-b375-8745991b15ea.png

## Tests Performed:

- .go c id 11755 and see if the quest A Little Luck (6606) is there.
- Apply fix
- Check now. The quest should not be there

## How to Test the Changes:

1.  .go c id 11755 and see if the quest A Little Luck (6606) is there.
2. Apply fix
3. Check now. The quest should not be there

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by baranzadeoglu** [comment]
Fix is incorrect.

https://tbc.wowhead.com/quest=969/luck-be-with-you

Quest "A Little Luck" is not a prerequisite for  "luck be with you". Namely, you should be able to take "luck be with you" without taking "A little luck".

**Comment by Asthalor** [comment]
I do not understant then the expected behaviour the issue wanted to fix.
On the issue the text said :

**Expected Blizzlike Behaviour**
A Little Luck is pre-quest for Luck Be With You

**Comment by baranzadeoglu** [comment]
> I do not understant then the expected behaviour the issue wanted to fix. On the issue the text said :
> 
> **Expected Blizzlike Behaviour** A Little Luck is pre-quest for Luck Be With You

Let me explain. There are bunch of quests in the game that are meant to direct players. I call them **go to this place** quests. They are basically meant to direct players to right zones / npcs. Such as you are level 50 now, so there are npcs in every major city that direct you to silithus. But these quests are not prerequisites. In other words, without any such quest, I player can wander into the zone and start the quest without actually doing **go to silithus** quest.

**Comment by Asthalor** [comment]
The issue https://github.com/azerothcore/azerothcore-wotlk/issues/9334 had a wrong Expected behaviour.
As i understand on the Chromiecraft issue is that after completing the quest  "Cache of Mau'ari" the quest "A little luck "should not be available. I will change the title and try to fix it soon.

**Comment by Asthalor** [comment]
Ive been trying to find a condition to make a quest unavailable, but to no avail. Ive found that on classic the quest A little luck (6606) is not showing and was probably removed from the game.
image

Matches with the info on this issue: https://github.com/Questie/Questie/issues/1338
This issue would be fixed by removing that quest.

**Comment by Asthalor** [comment]
Ive updated the scope of the issue as i have found more information about this quest.

**Comment by acidmanifesto** [comment]
@Asthalor 

Quest Starts at npc Harlo Wigglesworth
The Quest Ends at npc Witch Doctor Mau'ari
It is a level 60 quest (Requires level 60 character)

Quest was officially removed in 4.0.3a Cata.

This quest was valid and working from classic to wotlk.

What is the scope of this PR putting it as disabled?

**Comment by Asthalor** [comment]
Thanks acid for the tip.
The sources ive founded all had a lvl 55 character so that was probably the case here.
Then we can close this PR as the quest is working as intended.

**Pull request closed without merging**
