### PR TITLE
Fix(Core/Crypt): Updated cmake macro for OpenSSL

### PR DESCRIPTION
**Pull request by stoudtlr**
Author:    github.com/Shauren <shauren.trinity@gmail.com>

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).
-  [X] CMake macros

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18281

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [X] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
- This is a copy of the latest FindOpenSSL.cmake file from TrinityCore commit ID [94aed68](https://github.com/TrinityCore/TrinityCore/commit/94aed6896873179b284b8b1911590ed9587466d6). Original author of that commit is tagged.  

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.
Tested with OpenSSL version 1.1.1w, 3.1.2, 3.1.5, and 3.2.1.  All compile and build on Windows without error. Confirmed SSL version in-game.
Screenshot 2024-02-07 085515
Screenshot 2024-02-07 002306
Screenshot 2024-02-07 074709

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [X] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Verify my testing by building with various OpenSSL versions
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
Thanks for the input. Could you check that please? Thank you. I'm sure I detect a tabulation.

```
Codestyle check script:

  Checking RegEx: '\t'
src/cmake/macros/FindOpenSSL.cmake:261:	set(_OPENSSL_MSI_INSTALL_GUIDS "A1EEC576-43B9-4E75-9E02-03DA542D2A38" "31D2408A-9CAE-4988-9EC3-F40FDE7D6AE5")
```

**Comment by stoudtlr** [comment]
@pangolp formatting fixed and additional test done with OpenSSL version 3.0.13 since that was another version discussed in discord as not working before.
Screenshot 2024-02-07 103053
Screenshot 2024-02-07 103613

**Comment by pangolp** [comment]
> formatting fixed and additional test done with OpenSSL version 3.0.13 since that was another version discussed in discord as not working before.

Excellent. Great contribution, unfortunately, I am still using version 1.1.x so I have to update first and then perform the tests. Generally I don't see these topics, but I'm sure that when someone with more experience sees them, they ask for changes or approve them. Thanks for the input. I will report on him.

**Comment by pangolp** [comment]
I have carried out the tests with OpenSSL 1.1
(Because I haven't updated yet)
And the pull request does not affect said version.
I have to update the library and try it with 3.
But you have already uploaded images with the results.
I think it's okay.

```
CMake version: 3.28.2
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++20 standard
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.38.33135.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Enable NOMINMAX
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Found git binary : D:/Program Files/Git/cmd/git.exe

* AzerothCore revision            : 43b6c59345b5 2024-02-09 13:37:08 -0300 (pr-18284 branch)

* Install core to                 : C:/Program Files/AzerothCore
* Install configs to              : C:/Program Files/AzerothCore

* Build applications              : Yes (all)
* Build tools                     : No
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : Yes - "hierarchical"

Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD

* Apps build list (all):
  |
  +- apps
  |   +- authserver
  |   +- worldserver
  |

Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
* Script configuration (static):
  |
  +- worldserver
  |   +- Commands
  |   +- Custom
  |   +- EasternKingdoms
  |   +- Events
  |   +- Kalimdor
  |   +- Northrend
  |   +- OutdoorPvP
  |   +- Outland
  |   +- Pet
  |   +- Spells
  |   +- World
  |

* Modules configuration (static):
  |
  +- worldserver
  |   +- mod-aoe-loot
  |   +- mod-solo-lfg
  |

* Modules config list:
  |
  +- mod-aoe-loot
  |  * mod_aoe_loot.conf.dist
  +- mod-solo-lfg
  |  * SoloLfg.conf.dist

Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done (1.8s)
Generating done (2.9s)
```

```
Compilación iniciada a las 13:38...
1>------ Operación Compilar iniciada: Proyecto: ZERO_CHECK, configuración: RelWithDebInfo x64 ------
2>------ Operación Compilar iniciada: Proyecto: revision.h, configuración: RelWithDebInfo x64 ------
3>------ Operación Compilar iniciada: Proyecto: common, configuración: RelWithDebInfo x64 ------
3>GitRevision.cpp
3>common.vcxproj -> W:\wotlk\azeroth-server\src\common\RelWithDebInfo\common.lib
4>------ Operación Compilar iniciada: Proyecto: authserver, configuración: RelWithDebInfo x64 ------
5>------ Operación Compilar iniciada: Proyecto: worldserver, configuración: RelWithDebInfo x64 ------
4>   Creando biblioteca W:/wotlk/azeroth-server/src/server/apps/RelWithDebInfo/authserver.lib y objeto W:/wotlk/azeroth-server/src/server/apps/RelWithDebInfo/authserver.exp
4>authserver.vcxproj -> W:\wotlk\azeroth-server\bin\RelWithDebInfo\authserver.exe
5>   Creando biblioteca W:/wotlk/azeroth-server/src/server/apps/RelWithDebInfo/worldserver.lib y objeto W:/wotlk/azeroth-server/src/server/apps/RelWithDebInfo/worldserver.exp
5>worldserver.vcxproj -> W:\wotlk\azeroth-server\bin\RelWithDebInfo\worldserver.exe
6>------ Operación Compilar omitida: Proyecto: INSTALL, configuración: RelWithDebInfo x64 ------
6>Proyecto no seleccionado para compilarse para esta configuración de solución 
========== Compilación: 5 correcto, 0 erróneo, 14 actualizado, 1 omitido ==========
========== Compilar completado a las 13:38 y tardó 28,829 segundos ==========
```

The tests were carried out on Windows 10.

**Review by pangolp — APPROVED** [review]

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
