### PR TITLE
fix(Scripts/Command): Command `gm visible on` should not mark you wit…

### LINKED ISSUE #9495: [GM commands] Toggling between visible off and on keeps the player invisible to npcs
### Current Behaviour

Using `.gm visible off` will turn you invisible to the NPC. This is okay.
If you were to use `.gm visible on` after being invisible, you can no longer be attacked by npcs.

https://user-images.githubusercontent.com/22718174/144696892-1877005c-1e14-479a-b98f-4b2e3c81585e.mp4

### Expected Blizzlike Behaviour

Because I am now visible, hostile npcs should be hostile.

### Source

_No response_

### Steps to reproduce the problem

`.gm visible off`
`.gm visible on`

That's it.

### Extra Notes

_No response_

### AC rev. hash/commit

~~AzerothCore rev. 5877261bb703 2021-12-03 11:47:15 +0000 (pr-9124 branch) (Unix, Debug, Static)~~
AzerothCore rev. 5df73f668052 2021-12-03 21:35:07 +0000 (master branch) (Unix, Debug, Static)

### Operating system

Unix

### Custom changes or Modules

On ChromieCraft PTR 1.

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
…h <GM> tag.

Fixes #9495

## Issues Addressed:

- Closes #9495 

## Tests Performed:

- Not tested.

## How to Test the Changes:

Go fight with some hostile mob
`.gm visible off`
`.gm visible on`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Under the impression this was set that way to clear off dirty threat tables. Worth checking if nothing awry happens if you toggle visible off while in combat.

**Comment by UltraNix** [comment]
@Nyeriah Should be okay now.

**Comment by Maelthyrr** [comment]
Tested and work fine IG. Thanks :)

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@UltraNix please fetch upstream. We are getting that jammy failure crap again with one of the workflow.

**Comment by UltraNix** [comment]
@acidmanifesto Done.

**Pull request merged**
