### PR TITLE
fix(CMake): Fix for linux error builds

### PR DESCRIPTION
**Pull request by wizzymore**
There is a problem on Linux where the new policy crashes the build.

##### CHANGES PROPOSED:
-  Change back to OLD policy until this gets fixed

##### ISSUES ADDRESSED:
- Closes

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
Codacity again...

**Comment by wizzymore** [comment]
> Codacity again...

Now it is fixed, i think there is something personal between Codacy towards me.
So much hatred in the air

**Comment by FrancescoBorzi** [comment]
setting it as to be merged unless @Winfidonarleyan or anyone else can fix master without reverting that change

**Comment by Winfidonarleyan** [comment]
#2305

**Comment by FrancescoBorzi** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/2307

**Pull request closed without merging**
