### PR TITLE
fix(DB/creature_template): Adjust movement speed of all vanilla creatures from sniffs up until Naxxramas

### PR DESCRIPTION
**Pull request by T1ti**
Co-Authored-By:  Efymer <79163132+Efymer@users.noreply.github.com>

## Changes Proposed:
mass update creatures movement speeds from reliable Classic sniffs data up until Naxxramas(not included because it got reworked in wrath)
The sniff data uses the filter "no aura" on the creature to make sure the data is reliable and no spell is affecting the creature's speed.

-  Remaking the PR https://github.com/azerothcore/azerothcore-wotlk/pull/6502 since he gave up

## Issues Addressed:

- Closes 

## SOURCE:

vMaNGOS classic sniffs.

## Tests Performed:

- scrolled through it and checked if I saw any weird data, if so manually checked some of it
- 

## How to Test the Changes:

1.Test as many creatures as you can.
2.Check that the values make sense.

## Known Issues and TODO List:

- [ ] 
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
I added `Co-Authored-By:  Efymer <79163132+Efymer@users.noreply.github.com>` hope it is correct.

**Comment by T1ti** [comment]
Ok, I did a massive rework  of the PR and changed it to ALL speed data sniffed from classic that didn't match AC

**I have been extremly careful with the data though, me efymer worked on this, we had set up special filter like "creature has no aura", to only have the most pure and reliable data**

_To be even more safe and only have reliable data, I decded to not include anything past ID 15973, which is where the Naxxramas stuff starts, and since blizz reworked that for lvl 80, I prefer to not touch it._

The PR now includes over 1500 speed and walk movement speed updates from Classic sniffs !
Need massive testing guys !

**Comment by Efymer** [comment]
Let's see if we can get some attention here 🙏
I closed my previous PR as I thought it would be easier to fix it case by case, but hey, if there's people willing to help here it would be amazing ^^

btw we used https://azerothcore-speedchecker.web.app to get the data 🚀

**Comment by Helias** [comment]
these queries are really a lot, I don't think that a manual test is needed, I was wondering if these data are related to classic but we have some proofs that they are compliant to wotlk or not

**Comment by T1ti** [comment]
I don't think manual testing each of them is needed either lol but AC always wants some testing
basically just test some of them in game, especially the odd ones, see if they make sense and it should be enough

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers please check this

**Comment by temperrr** [comment]
tested:
I randomly selected big changes from the commit. I then search the entry in kiera3 and found the spawn points. I think looked if it felt alright and not out of place.

What I did -> with pr
[x]Entry 603 (.go creature 6940) -> |They walk normally 
[x]Entry 763 (.go creature 42112) -> | All mobs seem to be moving normally
[x]Entry 768 (.go creature 38704) -> | The shadow panther moves quite quickly, though not unexpected for a cat.
[x]Entry 1507 (.go creature 29810) -> | they run quite slow, but its consistent with other starting zones.
[x]Entry 1667 (.go creature 44986) -> | Same as above.
[x]Entry 1776 (.go creature 34160) -> is friendly to both alliance and horde, so could not really test this speed, though it appears to be quite quick.
[x]Entry 1813 (.go creature 47871) -> quite slow walk speed when wandering, which is expected for creatures like this.
[x]Entry 1942 (.go creature 17888) -> seems good.
[]Entry 13256 (.npc add 13256) (its the ice lord for horde for AV) -> movementspeed is way too high in my opinion. (both walk and run; see https://www.youtube.com/watch?v=--whOlqFB9s)
[]Entry 8516 (.go creature 87171) -> | escort quest: he should walk with 1.0 speed, he goes too quickly (see https://www.youtube.com/watch?v=w1FWROsT69g)
[x]Entry 10643 (.go creature 51884) -> Looks good
[]Entry 10981 ( went into alterac valley bg) _> run speed seems way too High
[]entry 10990 (went into alterac valely bg) -> run speed seems way too High
[]Entry 11352 (.go creature 51395) -> Unsure, seems to be running pretty quickly, but I cant find any evidence of this being wrong.
[]Entry 11981 (.go creature 85783) -> they move way too quickly.

There is more to test, still, but I gave it my shot.
As of now, I find quite a few not looking correctly, so I am unsure how we should proceed.

**Comment by T1ti** [comment]
> []Entry 8516 (.go creature 87171) -> | escort quest: he should walk with 1.0 speed, he goes too quickly (see https://www.youtube.com/watch?v=w1FWROsT69g)

Looks blizzlike : https://youtu.be/ihsU49eGFMk?t=545

**Comment by T1ti** [comment]
Flamegor and ebonroc are compeltely bugged for me, i can't aggro them, does it happen for anyone else ?

frostwolf : no video evidence but in comments people say it is the fastest pet in the game, so seems legit that it is very fast 
image
edit : https://youtu.be/FIzOJox8C9o?t=592 video proof that they are super fast

Can't find video for the rams but fi the wolves are correct, so are the rams imo

**Comment by T1ti** [comment]
Also how the heck do you enter AV solo ? The teleports commands don't work for me

**Comment by Kitzunu** [comment]
.debug bg

queue for AV

**Comment by T1ti** [comment]
for lokhamar i'm ivnestiagting, the first obvious bug is that he is WAYYY too small, and it might be what makes him look like he's running super fast.

**Comment by T1ti** [comment]
I really don't know what's up with Lokholar but in Wrath databases he ahs this new display info 31723 as the primary one 

image
image

which is obviously way too small, even in retail he is still very big 
image

This is from vanilla classic cache files : The only display he has there is 13256 
image

**Comment by temperrr** [comment]
OK so I trust your sources more than. Overal it seems to be working as intended then?

**Comment by temperrr** [comment]
> Flamegor and ebonroc are completely bugged for me, i can't aggro them, does it happen for anyone else ? Though their regular wander movement looks fine
> 
> frostwolf : no video evidence but in comments people say it is the fastest pet in the game, so seems legit that it is very fast
> image
> edit : https://youtu.be/FIzOJox8C9o?t=592 video proof that they are super fast
> 
> Can't find video for the rams but if the wolves are correct, so are the rams imo

Also are pretty buggy over at my side when going inside the dungeon indeed.

**Comment by T1ti** [comment]
Nvm about lokholar, the video you sent is from retail.. (AV 15 th anniversary)
This is on classic : https://youtu.be/kvVtj_TdCN0?t=127

**Comment by temperrr** [comment]
Darn that level squish from retail got the better of me.

**Comment by T1ti** [comment]
His speed looks normal imo...
https://i.gyazo.com/7dca0ccc8c76171ad2bbad2c2dc9f322.mp4

**Comment by T1ti** [comment]
So all the issues you report look blizzlike ?

**Comment by temperrr** [comment]
> So all the issues you report look blizzlike ?

Yes, thanks for bringing counter evidence and showing me wrong. I have to check better for where the videos are from,  I don't know what made me not see all that.  I will edit my post accordingly.

**Comment by T1ti** [comment]
Tip : you can see if a vannilla/BC video is from classic or a private server by looking at the UI 
image
 Classic has this new voice chat icon
It also has a clock udner the minimap which vanilla didn't have 
image

**Comment by T1ti** [comment]
what's up ?

**Comment by FrancescoBorzi** [comment]
@T1ti @temperrr @Efymer what's the status of this PR? needs further testing or it's ready?

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> From what I tested the changes worked, but I didn't test all creatures.

no need to test all creatures one by one, let's trust @T1ti 's work here. If some creatures should have wrong data, it can easily be improved later.

**Pull request merged**
