### PR TITLE
fix(Core/Commands): Explore cheat

### PR DESCRIPTION
**Pull request by poszer**
Remove from cs_misc.cpp and add to cs_cheat.cpp

##### CHANGES PROPOSED:

-  Adding Explore cheat command correctly to cs_cheat
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1524

##### TESTS PERFORMED:

Yes, for me build without errors, Os: Win. Tested in game, working with values 0 & 1 on self
cheatcommandexplore
Doesn't work on target player.

##### HOW TO TEST THE CHANGES:

1. Log in game, use command .cheat explore 1 / .cheat explore 0

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by comix1988** [comment]
.cheat explore or .explorecheat change something?

anyway .... it happens like when it was implemented long ago ....
prova

**Comment by poszer** [comment]
> .cheat explore or .explorecheat change something?
> 
> anyway .... it happens like when it was implemented long ago ....
> prova
> 
> https://www.youtube.com/watch?v=6CeVeRiZntQ&feature=youtu.be (my old video, look @0:30)

Hmm, i think i know what is problem. Will check later. Thanks for testing anyway

**Comment by poszer** [comment]
> > .cheat explore or .explorecheat change something?
> > anyway .... it happens like when it was implemented long ago ....
> > prova
> > https://www.youtube.com/watch?v=6CeVeRiZntQ&feature=youtu.be (my old video, look @0:30)
> 
> Hmm, i think i know what is problem. Will check later. Thanks for testing anyway

Are you sure that command doesn't work on player ? Bcoz, when i try on self, and also targeting other player, command .cheat explore 1 work in both cases @comix1988

**Comment by BarbzYHOOL** [comment]
Why you write this in description:

>    Log in game, use command .explorecheat 1 / .explorecheat 0


if it's .cheat explore (and i prefer .cheat explore, cleaner)

Btw also NEED to add the wiki entry for this. (Hmm I just checked the wiki page and there is nothing lol http://www.azerothcore.org/wiki/command)

**Comment by comix1988** [comment]
@poszer I created a non-GM account in dual-box to test it and even if the message appears in chat, the map is not revealed

**Comment by poszer** [comment]
> Why you write this in description:
> 
> > Log in game, use command .explorecheat 1 / .explorecheat 0
> 
> if it's .cheat explore (and i prefer .cheat explore, cleaner)
> 
> Btw also NEED to add the wiki entry for this. (Hmm I just checked the wiki page and there is nothing lol http://www.azerothcore.org/wiki/command)

Bcoz, someone added this to cs_misc as explorecheat. Removing it from there, and adding in cs_cheat where it belong

**Pull request closed without merging**
