### PR TITLE
fix(Scripts/Hunter): Bestial Wrath shoul not be castable on dead pets.

### LINKED ISSUE #8452: Bestial Wrath Castable on Dead Pet/Snapshots Duration on Mounting or Pet Dismissal
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2068

If your pet dies/is killed, and you cast Bestial Wrath, the CD is used and instantly removes the beast within because your pet isn't alive. It should NOT be useable unless the pet is active AND alive. Also, during the duration of Bestial Wrath, the duration snapshots while the hunter is mounted or if the pet is dismissed. This should not happen.

Tester: confirmed.

Cast on dead pet, showing BW on cooldown:

WoWScrnShot_101321_003133

Snapshotting of duration from both pet dismissal and mounting:

https://user-images.githubusercontent.com/81782124/136978879-ccfbd867-68f4-41c9-adc7-22c7ee3ed75e.mp4

Some discussion on TC here: https://github.com/TrinityCore/TrinityCore/issues/18249

### Expected Blizzlike Behaviour

Bestial Wrath should only be usable if the Hunter's Pet is active AND alive. The duration of the skill should also continue to countdown whether the hunter mounts up or dismisses the pet as well.

### Source

Note that I couldn't find a source specifically saying BW shouldn't work on dead pets, but I don't think that's very controversial. On TC's discussion someone said 'the core should report "your pet is dead" or "you don't have a pet" if the pet is dismissed' although of course that's not a primary source.

https://wowwiki-archive.fandom.com/wiki/Bestial_Wrath?oldid=2333466
https://tbc.wowhead.com/spell=19574/bestial-wrath#comments

### Steps to reproduce the problem

Make a hunter with "Bestial Wrath" and "The Beast Within" talents.
Kill off the pet.
Attempt to use Bestial Wrath and watch the skill go into CD as if it was used with no duration.

### Extra Notes

As another note, on this server when casting Bestial Wrath, you can apparently snapshot the buff on the hunter by casting the skill and instantly mounting. If someone was to wait until the CD was up again and remain mounted, they could potentially have an 18.5 second Beastial Wrath buff. On every server I played on including retail, the skill is snapshot on the pet, but the duration continues to count down while mounted or not of if pet is active or not. As another note, you can cast Bestial Wrath, and dismiss the pet, later recalling it for the remainder of what was active of the skill's duration. This is also incorrect.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b2f08934bcc60491f8fa8971f98837b2d48a489e

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Bestial Wrath should expire while pet is offline.

## Issues Addressed:

- Closes #8452
- Closes https://github.com/chromiecraft/chromiecraft/issues/2068

## Tests Performed:

- Not tested.

## How to Test the Changes:

Make a hunter with "Bestial Wrath" and "The Beast Within" talents.
Kill off the pet.
Attempt to use Bestial Wrath and watch the skill go into CD as if it was used with no duration.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by IntelligentQuantum** [comment]
@UltraNix Mount part doesnt work

**Comment by UltraNix** [comment]
@IntelligentQuantum Tested and worked okay.

**Comment by UltraNix** [comment]
@IntelligentQuantum ??

**Comment by temperrr** [comment]
tested!

**Comment by acidmanifesto** [comment]
merge conflicts

**Comment by UltraNix** [comment]
Fixed

**Pull request merged**
