### PR TITLE
fix(DB/Creature): Fix Spellmaw not wandering/patrolling

### PR DESCRIPTION
**Pull request by Asthalor**
Changed the spawn point to one with more sense and added patrolling around

Closes AzerothCore issue#6278

## Changes Proposed:
-  I changed the spawn point because he was in the edge of a cliff, and on videos he is on ground patrolling
-  Added movement to the spawnpoint

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6278
- Closes https://github.com/chromiecraft/chromiecraft/issues/817

## SOURCE:

https://classic.wowhead.com/npc=10662/spellmaw

Video from WoW Classic (retail version): https://youtu.be/lO60l6tdTps . At the timestamp 39:04, you can see the player hovering his mouse over Spellmaw, and Spellmaw appears to be patrolling.

## Tests Performed:

- .go c id 10662
-  Observe if he patrolls around

TEST VIDEO

https://streamable.com/jyd7sf

## How to Test the Changes:

1.  .go c id 10662
2. Observe if he patrolls around

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — CHANGES_REQUESTED** [review]
Please just update the queries which you are fixing instead of deleting and insert the whole entries

**Comment by Asthalor** [comment]
Improved the SQL query

**Review by LukasVolgger — APPROVED** [review]
Thx! So you have a more compact code and we can see what you are changing even without testing

**Comment by Asthalor** [comment]
Yes, that was  a very good idea. Im copying and pasting the keira3 code without much thinking. I will try to be a bit more cautious from now on :P

Thanks @LukasVolgger

**Comment by LukasVolgger** [comment]
No need to worry, everything is fine and we appreciate your work very much! :)

**Comment by syssneck** [comment]
I'm not sure, but I think he should be patrolling. People found him in a lot of different places: [wowhead tbc](https://tbc.wowhead.com/npc=10662/spellmaw#comments). 
I test it and he is now wandering around.  I would go for the merge, as it is already much better than before. What are your thoughts on it? Ty!

**Comment by LukasVolgger** [comment]
Thx @syssneck ! Maybe we could have a look what TC have done with it. If we find nothing better than this solution, every better behaviour than before is good and appreciated :)

**Pull request merged**
