### PR TITLE
 Fix(Core/Player): fix periodic eating and drinking emotes

### PR DESCRIPTION
**Pull request by Viste**
##### CHANGES PROPOSED:
-  Fixes drinking and eating periodic emotes. Blizzlike timings, blizzlike first timer. So ye. This is fixed. Mangos did it wrong, we did it right. Sniffs confirm it.
-  you may now feel like on retail when pointlessly drinking or eating stuff
##### Target branch(es): Master
thx to Ovahlord

### CODE REVIEW

**Comment by comix1988** [comment]
I don't understand what this fix changes @Viste

**Comment by Viste** [comment]
@comix1988 this make emotes of eat and drink blizzlike, Now the interval between the character bringing food or water to himself is the right one.

**Comment by comix1988** [comment]
so it's just a visual change?

thanks for the explanation

**Comment by Viste** [comment]
yes

**Comment by sucofog** [comment]
It seems right, and tested, but the thing is on retail, the character brings food and drink back to himself after each timing, is it happening only to me?

**Comment by Viste** [comment]
according to @poszer comment "After ( With this commit ) ; Visual is shown, The player sit drinking / eating which is correct totally."
yes its only you @sucofog

**Comment by NixAJ** [comment]
Just adding a comment here.

I tried to start a discussion on the discord about this and promised Shin to start an issue on here, which I will in time.

https://github.com/TrinityCore/TrinityCore/pull/22380
This pull requests has some interesting information commented by xvwyh detailing information sniffed from the alpha. While alpha data shouldn't be taken as confirmed, there are a lot of evidence that point towards blizzard having 5 second internal unit timer acting as a heartbeat for trigger a multitude of different processes including but not limited to eating / drinking emotes, Spline syncing and certain Aura procs.

It might be incorrect to simply implement a timer specific for eating / drinking emotes, and potentially we should look into implementing a timer that handles the appropriate things?

**Comment by pklloveyou** [comment]
Not working
Did I miss the update?

**Comment by pklloveyou** [comment]
TIM截图20190323232825
There you go！！！！！！！

**Comment by Viste** [comment]
@pklloveyou i retested now and all works fine

**Pull request merged**
