### PR TITLE
DB/SAI: Bog Giant and Underbog Lord uses Growth only in Heroic mode.

### LINKED ISSUE #13978: [The Underbog] NPC - Bog Giant and Underbog Lord uses Growth in Normal mode
### Current Behaviour

Bog Giant and Underbog Lord uses Growth in Normal mode
https://www.wowhead.com/spell=40318/growth

### Expected Blizzlike Behaviour

Should only be used on Heroic Mod.

Normal mode:
https://youtu.be/EYmGCbnIb4c?t=416 - 6:57
https://youtu.be/_LRpztnnao8?t=432 - 7:14

https://youtu.be/_LRpztnnao8?t=1739 - 29:03

Heroic mode:
https://youtu.be/bVSlQKWLRAo?t=189 - 3:13

### Source

https://www.wowhead.com/npc=17723/bog-giant
https://www.wowhead.com/npc=17734/underbog-lord

Normal mode:
https://youtu.be/EYmGCbnIb4c?t=416 - 6:57
https://youtu.be/_LRpztnnao8?t=432 - 7:14

https://youtu.be/_LRpztnnao8?t=1739 - 29:03

Heroic mode:
https://youtu.be/bVSlQKWLRAo?t=189 - 3:13

### Steps to reproduce the problem

.go cr 138337

.tele underbog
.go xyz 280.749817 -169.079193 36.874214

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/55957fbb6e24f2fb6df57c92b829ad42498afee0

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #13978

## Issues Addressed:

- Closes #13978

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go cr 138337`

`.tele underbog`
`.go xyz 280.749817 -169.079193 36.874214`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by BeefSteaker — CHANGES_REQUESTED** [review]
I believe you want to set `event_flags`=4 for heroic only
image

**Comment by UltraNix** [comment]
@BeefSteaker Should be okay now.

**Comment by Sneften** [comment]
Tested ✔️ 
Growth is only cast in Heroic mode by both Giants and Lords.

**Review by BeefSteaker — APPROVED** [review]
tested, Works as expected

**Review by Gultask — APPROVED** [review]

**Pull request merged**
