### PR TITLE
fix(DB/Creature): Ferra Boss now has its correct loot

### PR DESCRIPTION
**Pull request by Dr-Arayashiki**
## Changes Proposed:
-  add missing loot to npc 14308 (Ferra)

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15780

## SOURCE:

https://www.wowhead.com/wotlk/npc=14308/ferra
## Tests Performed:

- tested in game

## How to Test the Changes:

1. open the database
2. I added the missing loot to the boss
3. add npc 14308 and see

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Couple things: 1) you still have the Grunda mount fix SQL in your branch. 2) You should be attaching the issues to close in your issue.

**Comment by Dr-Arayashiki** [comment]
> Couple things: 1) you still have the Grunda mount fix SQL in your branch. 2) You should be attaching the issues to close in your issue.

I'm still being beaten to move here in git rsrs

**Comment by Dr-Arayashiki** [comment]
> Couple things: 1) you still have the Grunda mount fix SQL in your branch. 2) You should be attaching the issues to close in your issue.

now it worked ok

**Comment by neifion-00000000** [comment]
from what I can gather (these tables are not easy to work off) gear is ~5.25%, bags are ~0.125%, gems are ~1.5% with bias toward aquamarines, the lockbox is ~1%, and the leather is a bad report/skinning loot

The gear should come off a reference table, though which will need to be figured out (one with similar loot as shown tho).   There are two open PRs for this same mob as well, but neither of them are in good enough shape to ship at the moment, I'll be copy/pasting this into both tho.

**Comment by Dr-Arayashiki** [comment]
> from what I can gather (these tables are not easy to work off) gear is ~5.25%, bags are ~0.125%, gems are ~1.5% with bias toward aquamarines, the lockbox is ~1%, and the leather is a bad report/skinning loot
> 
> The gear should come off a reference table, though which will need to be figured out (one with similar loot as shown tho). There are two open PRs for this same mob as well, but neither of them are in good enough shape to ship at the moment, I'll be copy/pasting this into both tho.

yes, but before that only two items were falling, I wanted to at least supply a little of what was missing, I thought it would at least solve part of the problem ^^

**Comment by neifion-00000000** [comment]
yeah but there is a correct way to do this and this isn't it.  Among other things this will now likely drop multiple greens at a time (instead of a green occasionally) and drops leather.  The green loot needs to come off a reference table, the leather needs removed, and the rates need adjusted downwards a lot.

**Comment by Dr-Arayashiki** [comment]
> yeah but there is a correct way to do this and this isn't it. Among other things this will now likely drop multiple greens at a time (instead of a green occasionally) and drops leather. The green loot needs to come off a reference table, the leather needs removed entirely as it's skinning data, and the rates need adjusted downwards a lot (the rates I posted would be acceptable/close).

I see, I'll try to work on the loot reference and put the drop rates shown in wowhead :)

**Comment by Gultask** [comment]
@Dr-Arayashiki 
I'd suggest that you first need to study a bit about references and the loot system AC has: https://www.azerothcore.org/wiki/loot_template

There are many issues with this approach, not to mention that loot issues are notoriously hard to deal with.

**Comment by Gultask** [comment]
Using the method you've shown here would lead to massive bloating of the loot tables. That's why we use references.

For example:
We have 100 NPCs dropping the same 100 items. That's 10000 rows. But if we use references instead it'll be only 201, since the reference will hold the 100 items, and each NPC will only require 1 row to link it to the reference.

Another thing are the chances.

In your current PR, one kill could result in several green drops. In fact, the chance of **not** dropping any loot is close to 1-4% and, consequently, the chance of seeing at least 1 green item is >90%, which is... improbable.

**Comment by Gultask** [comment]
I'd recommend looking at loot tables that already exist. Have you used https://github.com/azerothcore/Keira3 ? It's pretty easy to navigate. And I highly recommend to a beginner.

**Pull request closed without merging**
