### PR TITLE
fix(Core/Items): BoP stackable items can be traded among raid members.

### LINKED ISSUE #12400: [ZG] Tokens should be tradable for 2h in a group
https://github.com/chromiecraft/chromiecraft/issues/3784

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

ZG tokens are not tradable for 2h.

### Expected Blizzlike Behaviour

ZG tokens should be tradable for 2h like items from other raids.

### Source

Proof 1 - https://us.battle.net/support/en/article/49504
Proof 2 - https://i.ibb.co/6Pxy32L/Tooltip1.jpg
Proof 3 -  ad GDKP ZG all items were usually traded at the end of dungeon: https://i.ibb.co/zX21QF1/Tooltip2.jpg

### Steps to reproduce the problem

1. make a group of 2 or more people. `.tele group ZG`
2. Kill any boss, loot the Primal Hakkari Token.
3. Have a look to ZG token tooltip.

### Extra Notes

IDs are: 19716, 19717, 19718, 19719, 19720, 19721, 19722, 19723, 19724

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft Live - AzerothCore rev. 02fa20b6380b+ 2022-07-13 20:54:01 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12400

## Issues Addressed:

- Closes #12400
- Closes https://github.com/chromiecraft/chromiecraft/issues/3784
- Closes https://github.com/chromiecraft/chromiecraft/issues/3801

## Tests Performed:

- Not tested.

## How to Test the Changes:

make a group of 2 or more people. .tele group ZG
Kill any boss, loot the Primal Hakkari Token.
Have a look to ZG token tooltip.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
When an item is added to an existing stack, which rule prevails? Will the old stack be tradeable or will the new itens be impossible to trade?

**Comment by mpfans** [comment]
@Gultask please test it

**Comment by Gultask** [comment]
Tested.

- I can trade quest items after accepting the quest. Such as Head of Ossirian the Unscarred, so many people can take the quest at once. Obviously I can't turn in the quest if it requires the item, but I don't know if the full behaviour is correct or not, or if problems may arise from this.
- If I take 2 of the same item, the trade window refreshes, but if I split the stack, then one item keeps being tradeable while the other loses the ability to do so. See image, they were part of the same stack.

image

**Comment by UltraNix** [comment]
@Gultask Try again.

**Comment by Gultask** [comment]
If I split the stack, restack them and split it again, the timer of one of the items is refreshed to 2 hours.

**Comment by UltraNix** [comment]
@Gultask Interesting thing. So it looks like these items should not stack and then this PR is not needed :P

**Comment by Nyeriah** [comment]
Wrong, they shouldn`t be tradeable, the stack removal thing was... wow classic?

**Comment by Gultask** [comment]
From what I researched just now it seems that trading raid items was introduced in wotlk and later in Classic for QoL changes...

**Comment by UltraNix** [comment]
Trading items was introduced in Wotlk, but it includes itemsfrom previous expansion raids.

**Comment by UltraNix** [comment]
@Nyeriah So this PR is not needed?

**Comment by Nyeriah** [comment]
Sorry, I got lost after the last researches. I'm not sure how it should work, but it seems to me stackable items shouldnt be tradeable because of the overlaping rules mentioned earlier, so something seems off

**Comment by UltraNix** [comment]
Okay. I thinks the best solution here is just to set these items as single-stack

**Comment by UltraNix** [comment]
Updated.

**Comment by Gultask** [comment]
Sorry for the delay. I tested this before and tried again now. It works, and if you have a full inventory before the query is applied, the previously stacked items disappear from your bags and are returned through Customer Support mail automatically.

But it probably isn't blizzlike in WotLK retail. In Shadowlands the items still stack.

**Comment by temperrr** [comment]
I am not sure this is the correct approach. I think its better to put it in mod-progression instead.

**Comment by UltraNix** [comment]
For me it's best option and should be included in core, not in module. But not my decision though.

**Comment by Gultask** [comment]
I didn't know that AQ40 also had stackable loot. Here are the IDs:

20926, 20927, 20928, 20929, 20930, 20931, 20932, 20933

```
--
UPDATE `item_template` SET `stackable`=1 WHERE `entry` IN (19716,19717,19718,19719,19720,19721,19722,19723,19724,20888,20884,20889,20885,20890,20886,20926,20927,20928,20929,20930,20931,20932,20933);

```

**Comment by UltraNix** [comment]
@Gultask Thanks

**Comment by UltraNix** [comment]
@FrancescoBorzi What we do with this PR?

**Comment by UltraNix** [comment]
@Nyeriah @FrancescoBorzi @IntelligentQuantum

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by UltraNix** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/12415#issuecomment-1200102944

**Comment by Gultask** [comment]
Long story short this will make it the same as WoW Classic but will be different from 'true' Vanilla since these items are still stackable even today in SL.
Not blizz-like but it's a very nice QoL improvement.

**Comment by acidmanifesto** [comment]
Reading over the comments i am a bit conflicted with the disposition of this pr. Do we merge, or not merge? last comment was sept 2022 stating its a nice QOL. Do we move forward with this or not?

**Comment by Gultask** [comment]
I believe no as it is a custom implementation, even if QoL

**Comment by heyitsbench** [comment]
> I believe no as it is a custom implementation, even if QoL

Would it be impossible to implement as a config option?

**Comment by Gultask** [comment]
The core implementation had many problems, which makes sense since it didn't even exist, actually, and the items were what was changed for Classic.

Can the .sql be made to be applied as a config file?

**Comment by Nyeriah** [comment]
> > I believe no as it is a custom implementation, even if QoL
> 
> Would it be impossible to implement as a config option? EDIT: Might be completely misunderstanding the PR, disregard me. 🤷

Not a possibility. SQLs can’t be set as configs

**Comment by Nyeriah** [comment]
Considering this is a Classic change the PR should be closed as we shouldn’t merge classic content into the main branch. Perhaps this could be moved to the progression module instead.

**Comment by acidmanifesto** [comment]
> > I believe no as it is a custom implementation, even if QoL
> 
> Would it be impossible to implement as a config option?
> EDIT: Might be completely misunderstanding the PR, disregard me. 🤷

The closest i ever gotten to sql change via config was matching with client version to database auth version. Long story. Was completely useless. Had to have the sql string mstch the conf. Really was not worth the outcome or the effort to even get it like that.

**Comment by Maelthyrr** [comment]
As most people are more in favour of a transfer to mod-progress, I close this PR in favour of : https://github.com/azerothcore/mod-progression-system/pull/316/files

**Pull request closed without merging**
