### PR TITLE
fix(DB/Creature): King Magni Bronzebeard combat script

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Import the SAI for King Magni Bronzebeard combat from TC

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2905

## Tests Performed:
- None

## How to Test the Changes:

1. .go c id 2784
2. fight him

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Voxstrasza** [comment]
> fight him

wow how about a lil more info bud

works ok, still missing thunderclap, charge, self heal and summon guards (according to the wowwiki page from pre-4.0) but can't seem to find those abilities

**Comment by Kitzunu** [comment]
dood, it is 5am I dont even know what is up and down atm xD

**Comment by Kitzunu** [comment]
I did do the luxery and giving a tp command at least x)

**Comment by Kitzunu** [comment]
I can't find the other spells either, but to me this is good enough of an improvement so that he at least fights back.

**Comment by Kitzunu** [comment]
@Voxstrasza 
image

**Comment by Voxstrasza** [comment]
> 
> 
> @Voxstrasza
> image

interesting.  I think I found the ability he uses to summon guards.  Not sure about his Self Heal ability (from videos it seems to be a lay on hands effect) and charge

Summon Guard - Spell ID 72972.  Summons 1x Dark Iron Guard with Ironforge flags.

**Comment by Kitzunu** [comment]
I am going to hear with a friend if he can provide sniffed info about it

**Comment by Kitzunu** [comment]
The weird in the comments of WoWHead is that they don't mention any summon or heal https://www.wowhead.com/npc=2784/king-magni-bronzebeard#comments

**Comment by Voxstrasza** [comment]
> 
> 
> The weird in the comments of WoWHead is that they don't mention any summon or heal https://www.wowhead.com/npc=2784/king-magni-bronzebeard#comments

the classic wowhead version of the page does, with comments from 2006/2007 mentioning the summon and heal.  weird

**Comment by Kitzunu** [comment]
wowhead do be trippin

**Comment by Voxstrasza** [comment]
> Complete overwiew on King Magni's abilities.
> 
> Dps: He hits for 1000+- with a dual wielding attack.
> Stormbolt: He throws a Stormbolt at the target on the top of his hate list, doing around 1400 dmg and stuns for 6 seconds.
> Thunder Clap: His Thunder Clap deals around 1000 damage and slows movement and attack speed by 50% for 15 seconds, can be dispelled.
> Knock Away: Knocks all nearby enemies up into the air and away, dealing around 2000 damage to them.
> Avatar: Increases his normal attack damage by 100% and gives him immunity to magic for a short period.
> 

hm.  I don't know what to believe anymore lol

**Comment by Kitzunu** [comment]
Gonna wait and see for my friend =)

**Comment by Kitzunu** [comment]
@Voxstrasza I think this is good enough as an improvement, don't think we will find the other spell IDs if they even exist.

So if you approve this then it is good to be merged =)

**Comment by Voxstrasza** [comment]
> 
> 
> @Voxstrasza I think this is good enough as an improvement, don't think we will find the other spell IDs if they even exist.
> 
> So if you approve this then it is good to be merged =)

yea I'm good with it

**Comment by FrancescoBorzi** [comment]
@Voxstrasza check your email

**Review by Voxstrasza — APPROVED** [review]

**Comment by pklloveyou** [comment]
It's better to have something than nothing, Tested

**Pull request merged**
