### PR TITLE
Core/Player: fix achievements activation

### LINKED ISSUE #1422: Core: Instant 80 achievements issues
##### SMALL DESCRIPTION:

If you set the start level in the config to 80, you won't be able to see achievements until you earn some of them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

You should be able to see your level achievements immediately after create a new character because you already unlocked it (level 10).

##### STEPS TO REPRODUCE THE PROBLEM:

1. Change the start level to 80 (gmlevel and normal level, it's the same)
2. Open the worldserver
3. Enter to the game and see you can't access to the achievements.

##### EXTRA NOTES:

It works on trinity.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/37d9ef012608a1ddaa839f7e6b63e22fcd821d90

##### OPERATING SYSTEM:

Windows 10, ubuntu (not sure about the version)

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

None

### PR DESCRIPTION
**Pull request by GitVerge**
**CHANGES PROPOSED:**

- Check achievements on player creation.

Fixes client not allowing to open achievements list if start level is superior or equal to 10.

Closes #1422

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@GitVerge welcome and thanks for your contribution :)

Waiting for feedback/testing

**Comment by comix1988** [comment]
@GitVerge 
I tested this PR and now the achievements of the levels are added.
suggestion:
I would put a block on the results of the "realm first" because when logging a gm they are added to it

**Comment by GitVerge** [comment]
@comix1988 yes I noticed, I'll commit tonight or tmrw

**Comment by Nefertumm** [comment]
Tested, gms can obtain the achievement but it will still available for players.

**Comment by FrancescoBorzi** [comment]
well done @GitVerge , @comix1988 and @Nefertumm

**Comment by BarbzYHOOL** [comment]
awesome

**Pull request merged**
