### PR TITLE
Core: Crashfix.

### LINKED ISSUE #6797: new crash log
### Current Behaviour

logs

https://gist.github.com/mpfans/25c45261780818ad8961d6fab2b05efd

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. 019884c7d479+ 2021-07-06 19:00:29 +0800 (pr-6378 branch) (Unix, RELWITHDEBINFO, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using ACE version: 6.4.5
Using Boost version: 1.71.0
Using MySQL version: 80025
Using CMake version: 3.16.3
Compiled on: Linux 
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/data/maps. Total size: 252191207 bytes
vmaps directory located in /home/data/vmaps. Total size: 658638902 bytes
mmaps directory located in /home/data/mmaps. Total size: 2196401108 bytes
Using World DB: ACDB 335.3
Using World DB Revision: 2021_07_06_00
Using Character DB Revision: 2021_07_06_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99760788-new-crash-log?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6808: New server crash
```
Thread 16 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7feef07ff700 (LWP 17996)]
0x0000000001402c22 in Acore::Assert (file=0x14f317c "/root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Object/Object.h", line=941, function=0x14f3fe8 "GetMap", debugInfo=..., message=0x14f3fef "m_currMap") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:64
64	        Crash(formattedMessage.c_str());
#0  0x0000000001402c22 in Acore::Assert (file=0x14f317c "/root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Object/Object.h", line=941, function=0x14f3fe8 "GetMap", debugInfo=..., message=0x14f3fef "m_currMap") at /root/env/chromiecraft/azerothcore-wotlk/src/common/Debugging/Errors.cpp:64
#1  0x0000000000d760a5 in WorldObject::GetMap (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Entities/Object/Object.h:941
#2  ObjectAccessor::GetPlayer (u=..., guid=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Globals/ObjectAccessor.cpp:220
#3  0x0000000000f03bcb in WorldSession::HandlePetActionHelper (this=0x7fee574f9100, pet=0x7fee4e23d000, guid1=..., spellid=<optimized out>, flag=<optimized out>, guid2=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/PetHandler.cpp:556
#4  0x0000000000f02f25 in WorldSession::HandlePetAction (this=<optimized out>, recvData=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/PetHandler.cpp:450
#5  0x000000000102cd7c in WorldSession::Update (this=0x7fee574f9100, diff=10, updater=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:347
#6  0x00000000012252f1 in World::UpdateSessions (this=0x7fef48e52000, diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/World/World.cpp:2696
#7  0x00000000012226d6 in World::Update (this=0x7fef48e52000, diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/World/World.cpp:2234
#8  0x0000000000459231 in WorldRunnable::run (this=<optimized out>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/worldserver/WorldThread/WorldRunnable.cpp:48
#9  0x00007fef4b8aad84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fef4b9c4609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007fef4b598293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/f16fe3f8dc5e6fd0af8848714fab2195cb1182c1

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99787371-new-server-crash?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
## Changes Proposed:
-  Mark `CMSG_PET_ACTION` as `PROCESS_THREADSAFE` and move to map context.

## Issues Addressed:

- Closes #6797.
- Closes #6808.

## Tests Performed:

- Not tested.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
@FrancescoBorzi  I'm testing this PR

**Comment by mpfans** [comment]
It's been running for 16 hours without a crash

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> It's been running for 16 hours without a crash

same for me, tested with players. No new issues with Pets reported either.

LGTM

**Comment by mpfans** [comment]
> > It's been running for 16 hours without a crash
> 
> same for me, tested with players. No new issues with Pets reported either.
> 
> LGTM

It's been running for 55 hours without a crash

**Pull request merged**
