### PR TITLE
fix(DB): Many Quest Emote Fixes from TrinityCore

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Many Quest Emotes updates recently added to TrinityCore thanks to many efforts from ZenoX92.
- I included only the changes that were not in AzerothCore yet
-  Please kindly note that in addition to emote updates, there are a few small related fixes included as they were in original TC PRs. Like the emote fixes, I included these if they were not already in AzerothCore. This include quest ordering fixes, conditions, and one NPC fix (remove innkeeper script incorrectly assigned to a not innkeeper NPC.) There are not many of these; they can be excluded if we are want to test them separately. All were accepted into TrinityCore.
- 
Co-authored-by: ZenoX92 <carlos.morales@insmet.cu>
[ZenoX92](https://github.com/TrinityCore/TrinityCore/commits?author=ZenoX92)

## Issues Addressed:

- Closes unreported issue

## SOURCE:

All values are from the following TrinityCore commits:
https://github.com/TrinityCore/TrinityCore/commit/345e067855b19985a387b59f851f6a6a3907aa1e
https://github.com/TrinityCore/TrinityCore/commit/09559d51de34c2c2e7caa61e05526081a8b88dc6
https://github.com/TrinityCore/TrinityCore/commit/0ccccd6919d627feb6acc7cf0580f62f5d08494c
https://github.com/TrinityCore/TrinityCore/commit/cba2a77c883ce4a740548f7f5e0e578f4221c0c1
https://github.com/TrinityCore/TrinityCore/commit/666e84607c3e42772f6187a0194f8b015db8907d
https://github.com/TrinityCore/TrinityCore/commit/8c0d55bc124f7d5f36211e1ef606cf7a9980bbc7
https://github.com/TrinityCore/TrinityCore/commit/5b7e1afa49b7dcea6d0525587045319c741e1011
https://github.com/TrinityCore/TrinityCore/commit/74a49db483e12bab6866f82c1189d04627dbdba0
https://github.com/TrinityCore/TrinityCore/commit/5ae5cc78804088cf8b8e1bbe5cbdd0ce4fc17b42
https://github.com/TrinityCore/TrinityCore/commit/b8c92d17e69f8462a0c467e1b319073882661e45
https://github.com/TrinityCore/TrinityCore/commit/8d7b612b68d0aba0e68ebeadd843ff45120d6f09
https://github.com/TrinityCore/TrinityCore/commit/4010c0e116478c55159e0237e7de893e21fbb451
https://github.com/TrinityCore/TrinityCore/commit/31abf99b6fdc958d5364166a850aa933de6e17aa
https://github.com/TrinityCore/TrinityCore/commit/f04707718e3d8931e4bbbbff48d8fe9d83dc0ac4
https://github.com/TrinityCore/TrinityCore/commit/0c93909e13ff913cc9972eb620b686f4af54794b
https://github.com/TrinityCore/TrinityCore/commit/df2097ab27db762b11c6f7e62db4a8e1ac22ebb6
https://github.com/TrinityCore/TrinityCore/commit/87162ba4579d10cf9fc5765cb5b39dcaf12461aa
https://github.com/TrinityCore/TrinityCore/commit/94e21d2814bbae0dc015abcfb49a11374d8fbd0d
https://github.com/TrinityCore/TrinityCore/commit/73a004c4c772c03305c83e3ef5ef992d83d6658e
https://github.com/TrinityCore/TrinityCore/commit/e1120ca23363966b260c340006ef11cd0e461b2d
https://github.com/TrinityCore/TrinityCore/commit/d45b66b9e10967e0187b616a3b9d8e35f0ca5834
https://github.com/TrinityCore/TrinityCore/commit/b6b3b3bb6effe2138f4dd21d6894a4c02b335d70
https://github.com/TrinityCore/TrinityCore/commit/6e7eca8c3bd0d7bec2358d6f66ba6061aceab428
https://github.com/TrinityCore/TrinityCore/commit/7545b5f8c1037a6e393e13631fda0cebc61b3b88
https://github.com/TrinityCore/TrinityCore/commit/44ae5c34a7810e422289e007d4bcfe85004bbdfc
https://github.com/TrinityCore/TrinityCore/commit/82d150e3e1509e28053107e1012decc51ccae54a

## Tests Performed:

- Automated validation of values was done through Python testing scripts
- Others were spot checked and seem correct

## How to Test the Changes:

1. Accept and complete any of the quests mentioned in the PR
2. See the new emotes

## Known Issues and TODO List:

I was originally submit each one of these individually but decide it might be better to do all in one PR. Please let me know if you would prefer to see these in individual PR instead.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
```
ERROR 1064 (42000) at line 10134: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `quest_details` (`ID`, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `Emot' at line 385
```

**Comment by ZhengPeiRu21** [comment]
> ```
> ERROR 1064 (42000) at line 10134: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `quest_details` (`ID`, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `Emot' at line 385
> ```

Fixed, sorry. This was from copy and paste error; I'm surprised HeidiSQL did not catch it when I did final check that all run with no error!

**Comment by acidmanifesto** [comment]
oof... i tried to correct whatever the error may of been on error 3121 or near it and still get the error. so i dunno.

**Comment by ZhengPeiRu21** [comment]
Thank you for let me know of the issues. I just test again in HeidiSQL and it seem to run correct:

```
/* Affected rows: 2,548  Found rows: 0  Warnings: 0  Duration for 2,718 queries: 0.251 sec. */
```

It may be HeidiSQL has more lenient than whatever is perform SQL check. I will continue to investigate the issue and update this PR. Thank you for taking time to try a fix!

**Comment by ZhengPeiRu21** [comment]
Thank you for your patience. I believe to have fixed all necessary issues with the PR.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
