### PR TITLE
Fix NPC enters into EvadeMode, he loses all his Auras.

### LINKED ISSUE #6348: Creatures EvadeMode lose auras
**CURRENT BEHAVIOUR:**

If an NPC enters into EvadeMode, he loses all his Auras.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
NPCs never lose his already active auras.
https://youtu.be/KFVNX0Ynrw8

**SOURCE:**
4532ef4c7a9dda1e5b4ade7e6a94f13d76e7851b

**STEPS TO REPRODUCE THE PROBLEM:**

1.  .go c 90286
2.  aggro NPC
3.  Switch NPCs to evade mode (.gm on or Or run out of range)

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 

**OPERATING SYSTEM:**
Ubuntu 20.04

**MODULES:**
no

**CUSTOMIZATIONS:**
no

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99233606-creatures-evademode-lose-auras?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Krejza9**
## Changes Proposed:
-  NPCs never lose his already active auras if enter to EvadeMode (go back home).

## Issues Addressed:

- Closes #6348

## Tests Performed:

- can be tested in the game

## How to Test the Changes:

1. .go c 90286
2. aggro NPC
3. Switch NPCs to evade mode (run out of his aggro range)
4. He must not lose his Frost Armor

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
Good one 🥇 👍🏼

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
I'm sorry but this PR was merged too fast, my mistake was assuming it was properly tested but it was not. Needs revert.

**Comment by Krejza9** [comment]
No need for a revert, just modify the scripts for bosses that use positive auras. This has already been discussed.

**Comment by Si1ker** [comment]
> No need for a revert, just modify the scripts for bosses that use positive auras. This has already been discussed.

@Krejza9 Glad, you are here, please let me know when you open a PR containing those modifications!
It will be our please to review and test the PR, just to make sure everything is working based on your changes, thanks in advance!

**Comment by Krejza9** [comment]
I just got back from vacation.
I'll prepare an edit for the bosses I know. It would be nice if someone would list all the bosses that use positive auras.
I don't have all the bosses in my head.

**Comment by Si1ker** [comment]
Keep in mind, not only positive auras, also every single boss that has a enrage timer (all berserk spell types) are covered on that and count as positive aura/spell.

**Comment by Krejza9** [comment]
this is going to be a hell of a challenge to track down everything :(

**Comment by Si1ker** [comment]
Yep, that's why we cannot remain with broken bosses until that PR/changes are in good state.
You have plenty of time if now or in the future want to submit the same changes + the required changes to all the mentioned bosses, to make it work. Thanks for your understanding.

**Comment by Krejza9** [comment]
The funny thing is that this breaks NPCs again :-D, but I understand your point.
Unfortunately it's a bug I didn't see coming. I didn't realize that bosses don't have aura removal by default on evade.

**Comment by FrancescoBorzi** [comment]
> > No need for a revert, just modify the scripts for bosses that use positive auras. This has already been discussed.
> 
> @Krejza9 Glad, you are here, please let me know when you open a PR containing those mentioned modifications + the reverted changes!
> It will be our pleasure to review and test the PR when you submit it, just to make sure everything is working based on your changes, thanks in advance! For now, the changes will be reverted.

I agree with this, we can't afford to keep `master` branch broken so please @Krejza9  open a new PR containing the old changes + the needed fix as Silker suggested

**Pull request merged**
