### PR TITLE
fix(DB/Item): Deep Thunder ppm adjustment

### PR DESCRIPTION
**Pull request by Maria-sequel**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17048
- Closes https://github.com/chromiecraft/chromiecraft/issues/6052

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.) @heyitsbench 
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
[Stormherald](https://wowgaming.altervista.org/aowow/?item=28442) likely uses the same PPM.

**Comment by Maria-sequel** [comment]
> [Stormherald](https://wowgaming.altervista.org/aowow/?item=28442) likely uses the same PPM.

cant work with "likely"

**Review by Gultask — APPROVED** [review]

**Comment by Bijjoo** [comment]
https://www.wowdb.com/items/28441-deep-thunder says 1 procs per minute , The CC database currently has a ppm=1 value, so it procs as intended. Period.

**Comment by heyitsbench** [comment]
> https://www.wowdb.com/items/28441-deep-thunder says 1 procs per minute , The CC database currently has a ppm=1 value, so it procs as intended. Period.

WoWDB is a database site for retail. Testing on Wrath Classic indicated it was not one proc per minute.

**Comment by Bijjoo** [comment]
Wrath Classic isnt blizzlike  as it used to be back in days 2007-2008. It run completely different core and client.

**Comment by heyitsbench** [comment]
> Wrath Classic isnt blizzlike as it used to be back in days 2007-2008. It run completely different core and client.

Then find a real source.

**Comment by elthehablo** [comment]
Ye sorry but make a new issue with good sources and then people'd be happy to change it back

**Comment by Bijjoo** [comment]
Procs for things like weapons and trinkets have always been at 1 ppm, a value lower than that makes these things nonsense.

**Comment by heyitsbench** [comment]
Feel free to provide a source in your issue report.

**Comment by Bijjoo** [comment]
Look here https://www.wowhead.com/tbc/spell=34510/stun  you can see 

Effect | Apply Aura: Stun    Value: 1          PVP Multiplier: 1
for Stormherald and Deep Thunder relative stun.

**Comment by heyitsbench** [comment]
> Effect | Apply Aura: Stun Value: 1 PVP Multiplier: 1 for Stormherald and Deep Thunder relative stun.

https://www.wowhead.com/wotlk/spell=34510#comments:id=141664

**Comment by Bijjoo** [comment]
When it comes to aura proc rate, it means ppm, not percentage.

**Comment by elthehablo** [comment]
WoWhead is quite an unreliable source

**Comment by heyitsbench** [comment]
> When it comes to aura proc rate, it means ppm, not percentage.

My point is that those '1' values have nothing to do with the proc rate.

**Comment by Bijjoo** [comment]
Look at this , it says ppm https://www.wowdb.com/items/28441-deep-thunder

**Comment by heyitsbench** [comment]
> Look at this , it says ppm [WoWDB]

Again, that's for retail.

**Comment by heyitsbench** [comment]
> Not entirely different at all, this is a logical continuation of how it was in the original state.

Spell for the Wrath Deep Thunder stun proc: [34510](https://www.wowhead.com/wotlk/spell=34510)
Spell for the retail Deep Thunder stun proc: [265278](https://www.wowhead.com/spell=265278)
Entirely different spell IDs.

And you mean to tell me you trust a community Dragonflight database sight regarding this item rather than Wrath Classic?

**Comment by Bijjoo** [comment]
You can see from multiple sources that proc rate is 1 ppm (https://www.wowdb.com/items/28441-deep-thunder) or even [1+Haste] ppm (https://www.wowhead.com/spell=265278/deep-thunder) , but no source says about 1%.

**Comment by Kitzunu** [comment]
The spell you are linking is from current retail, Dragonflight. It has nothing to do with wrath what so ever

**Comment by heyitsbench** [comment]
> You can see from multiple sources that proc rate is 1 ppm [...] or even [1+Haste] ppm [...], but no source says about 1%.

Both of those are retail sources.

**Comment by Bijjoo** [comment]
Its logical continuation of original state. All proc based weapons, meta gems and trinkets are working the  way based on procs per minute. On the other hand, there is not a single source indicating 1% proc rate.

**Comment by heyitsbench** [comment]
> On the other hand, there is not a single source indicating 1% proc rate.

There is Wrath Classic testing. Which I, and I would hope many others, believe more than a few people saying "it's supposed to be 1 ppm".

**Comment by Bijjoo** [comment]
This is a highly dubious test run on a legion based Wrath Classic client by some youtuber a few years ago, done inappropriately under improper conditions. It cannot be sufficient proof of anything.

**Comment by heyitsbench** [comment]
> This is a highly dubious test run on a legion based Wrath Classic client

Why do you trust Dragonflight and not Wrath Classic?

> by some youtuber a few years ago, done inappropriately under improper conditions.

It was tested by me not even a week ago in as optimal conditions as could be.

> It cannot be sufficient proof of anything.

Sufficient enough to be merged.

If you happen to find an actually trustworthy source besides to just take your word for it, again, feel free to open an issue report with that source included. Otherwise I'm not going to try to argue this issue any longer.

**Comment by Bijjoo** [comment]
Legion based Wrath Classic client does not match in any way original 3.3.5 WoTLK client that run by Chromiecraft and therefore cannot be reliable proof of anything. On other hand there are plenty of sources indicating for 1 ppm proc rate, even if in the form of a logical continuation of what has come down to our days.

**Comment by Kitzunu** [comment]
A legion based client does not matter. Things on wrath classic are not tuned to legeion rates or whahever just because the base structure of the client happens to be from legion. So using it as an argument is not right.

Yes, they have tuned fixed and alterned some things in classic compared to 335 15 years ago, but unless you come up with any actual source of proof to the behaviour 15 years ago, then wrath classic is the best we got to imitate WotLK

**Comment by Bijjoo** [comment]
wrath classic is the best we got to imitate WotLK - completely wrong. A small example - how the arena points calculating system works on Chromiecraft and how it works on Wrath Classic-completely different way. And no one argues with this, but everyone accepts the existing state. So Chromiecraft has its own point of view, often more correct than Wrath Classic.

**Comment by heyitsbench** [comment]
> wrath classic is the best we got to imitate WotLK - completely wrong. A small example - how the arena points calculating system works on Chromiecraft and how it works on Wrath Classic-completely different way. And no one argues with this, but everyone accepts the existing state. So Chromiecraft has its own point of view, often more correct than Wrath Classic.

Chromiecraft is not AzerothCore.

**Comment by Bijjoo** [comment]
Among other things, based on common sense , making some item 0.25 ppm is completely nonsence , for real , 1 proc in 4 minutes? Given that often the duration of the battle in the arena is a matter of few seconds.

**Pull request merged**
