### PR TITLE
fix(DB/gameobject): Compendium of the Fallen should be lootable by all

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Lower respawn rate from 24h to 2s

## Issues Addressed:
- Impossible to finish the quest [Compendium of the Fallen](https://classic.wowhead.com/quest=1049/compendium-of-the-fallen) as a group (quest inside Scarlet Monastery for Horde)

## Tests Performed:
- Applied SQL
- Restarted server

## How to Test the Changes:

`.tele scarletm`
Enter the Library, get to the final hallway at the opposite end of the end boss
`.q a 1049`
Loot the book
Without the patch, wait 24 hours for it to respawn...
With the patch, others can loot it almost instantly afterwards

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Helias** [comment]
Why only 2 seconds?

**Comment by Zoidwaffle** [comment]
Hm, seems like I was a bit too fast with the 2s.

I just recalled it as a fast respawn, but of course, it's been a while...

https://classicdb.ch/?quest=1049 <-- A comment saying around 5 mins, another 1 min, a third 30-35s.

Very interestingly, this was a closed issue: https://github.com/azerothcore/azerothcore-wotlk/issues/902 (at that time it seems like 3s was accepted).

So 2s might be too low, but 24h is definitely too much!

So I suggest either keeping the 2s or increasing it to 30-60s.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> Hm, seems like I was a bit too fast with the 2s.
> 
> I just recalled it as a fast respawn, but of course, it's been a while...
> 
> https://classicdb.ch/?quest=1049 <-- A comment saying around 5 mins, another 1 min, a third 30-35s.
> 
> Very interestingly, this was a closed issue: #902 (at that time it seems like 3s was accepted).
> 
> So 2s might be too low, but 24h is definitely too much!
> 
> So I suggest either keeping the 2s or increasing it to 30-60s.

I'm fine with 2s as it's supposed to be looted by all members of the party. If someone has stronge evidence against it, we can always change it later.

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
