### PR TITLE
chore(.clang-format): Delete

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  I honestly don't know if this is the best approach. But I am really sick of not being able to use Visual Studio without wanting to rip my hair out. This was a good idea, but it does not follow a single rule we have.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Personally I agree, most of the time it just does edits that I gotta undo right away, and some times they unfortunatelly end up slipping

**Review by Nyeriah — APPROVED** [review]

**Comment by Kitzunu** [comment]
I'll give it until Monday, after that I add To Be Merge label

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/discussions/9970 ?

**Comment by Kitzunu** [comment]
Thats something else

**Comment by iraizo** [comment]
Ah yes, without even reminding the one who created this of any issue at all lets just delete this, not notify anybody of this issue, not do something about it yourself.

At this point I'm leaving this project as it seems that contributing to this community at all is not worth my time at all, this is not about a single file being removed but about this multiple times happening not just to me. So I'd ask @55Honey / @FrancescoBorzi to remove me off every contributor role / server / organization.

**Comment by Kitzunu** [comment]
The issues of the line breaks being off has been known, you even commented it here https://github.com/azerothcore/azerothcore-wotlk/pull/6848#issuecomment-877842933

**Comment by iraizo** [comment]
> The issues of the line breaks being off has been known, you even commented it here [#6848 (comment)](https://github.com/azerothcore/azerothcore-wotlk/pull/6848#issuecomment-877842933)

Which a fix has been introduced and reviewed. please stop argueing with me over this.

**Comment by 55Honey** [comment]
> So I'd ask 55Honey / FrancescoBorzi to remove me off every contributor role / server / organization.

@iraizo 
As per your request, i've removed you from the CC organization and your contributor roles on CC discord. Since i still consider you a valuable contributor, i've added you the "Friend of Chromie" rank on discord.

Please take my advice that nobody is perfect and everybody makes mistakes once in a while. It's not useful to fight over who is responsible for them. Instead we should learn from our or anyones elses mistakes and improve by not repeating them.

**Pull request merged**
