### PR TITLE
fix(DB/creature): Fix Deputy Feldon hostility against horde players

### PR DESCRIPTION
**Pull request by Hacaw**
## Changes Proposed:
-  Update flag

## Issues Addressed:
- Closes : https://github.com/azerothcore/azerothcore-wotlk/issues/6775

## SOURCE:
https://wotlkdb.com/?npc=1070

## Tests Performed:
- Create horde character -> `.go c 6713` -> you should be attacked right away 
- Create alliance character -> `.go c 6713` -> `.character level 11` -> `.q add 244` and complete it and take next one (the guard itself is also a quest-giver for alliance players)

## How to Test the Changes:
- Create horde character -> `.go c 6713` -> you should be attacked right away 
- Create alliance character -> `.go c 6713` -> `.character level 11` -> `.q add 244` and complete it and take next one (the guard itself is also a quest-giver for alliance players)

## Known Issues and TODO List:
- none

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Hacaw** [comment]
@necropola and @anguaive I got inspired by your contributions on: https://github.com/azerothcore/azerothcore-wotlk/pull/6579/files and https://github.com/azerothcore/azerothcore-wotlk/pull/6319.
Do you think my fix is ok or are there any better solutions ?

**Review by necropola — COMMENTED** [review]
Why would you want to change this?
- He is a quest  giver
- https://wowpedia.fandom.com/wiki/Quest_giver?oldid=2341345
> Questgiving NPCs will not usually attack monsters or the opposing faction unless they have been attacked first 
- Hence he is curently flagged as `CIVILIAN (flags_extra = 2)`
- TC-3.3.5 additionally has flagged him `NO_XP (flags_extra = 2 + 64 = 66)`
- What does setting the highest bit `(flags_extra = 32768)` do?

**Comment by Hacaw** [comment]
> Why would you want to change this?
> 
> * He is a quest  giver
> * https://wowpedia.fandom.com/wiki/Quest_giver?oldid=2341345
> 
> > Questgiving NPCs will not usually attack monsters or the opposing faction unless they have been attacked first
> 
> * Hence he is curently flagged as `CIVILIAN (flags_extra = 2)`
> * TC-3.3.5 additionally has flagged him `NO_XP (flags_extra = 2 + 64 = 66)`
> * What does setting the highest bit `(flags_extra = 32768)` do?


32768 means is a guard.
image

Based on the https://wowpedia.fandom.com/wiki/Quest_giver?oldid=2341345 looks like https://github.com/azerothcore/azerothcore-wotlk/issues/6775 is not a bug, is just a normal behavior.

**Comment by necropola** [comment]
> 32768 means is a guard and it was reported that this guard should attack the player like the other normal guards.

Of course. I'm an idot. 32768 is bit 15 and not the highest bit.

> Based on the https://wowpedia.fandom.com/wiki/Quest_giver?oldid=2341345 looks like #6775 is not a bug, is just a normal behavior.
> I should have validated the issue first with the wowpedia sources.

Yeah, better not make quest givers attack the other faction. We already have some people engaging/killing quest NPCs intentionally. Don't need to add accidental kills.

**Pull request closed without merging**
