### PR TITLE
fix(DB/Creature): Moontouched Owlbeast (7453)

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  Corrects spell_template
-  Adds SmartAI

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12342
- Closes https://github.com/chromiecraft/chromiecraft/issues/3741

## SOURCE:

Vmangos

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. `.go c id 7453`
2. engage, see if it casts Rejuvenation on pull and Moonfire occasionally.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by Maelthyrr** [comment]
Tested and work fine.

<details>

WoWScrnShot_071322_223236

</details>

**Comment by Nyeriah** [comment]
hey thanks for the PR, I just just see one issue here: the creature_template spell, those are mind controlled abilities but it`s not granted that the abilities a creature use are available once mind controlled, it is not always the case

**Comment by Gultask** [comment]
Thanks for the feedback! ^^

IIRC the template had 2 spells with different IDs from what were supposed to be used in the SmartAI so I just changed their IDs.
But I can check it in the Classic PTR real quick tomorrow and report back.

**Comment by Gultask** [comment]
It's present in TBCC as well

image

**Pull request merged**
