### PR TITLE
DB: Fixes Issue #1435 [QUEST] hunting for ectoplasm

### PR DESCRIPTION
**Pull request by CookieMonsterDev**
DB: Fixes Issue #1435 [QUEST] hunting for ectoplasm

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1435

##### TESTS PERFORMED:

Tested all creatures loots **without** Ectoplasmic Distiller spawned.
Tested all creatures loots **with** Ectoplasmic Distiller.
Tested on Windows.
Works as intended now.

##### HOW TO TEST THE CHANGES:

Simply follow the steps from https://github.com/azerothcore/azerothcore-wotlk/issues/1435

> 1- .quest add 8924
2- .go creature 43138 kill and loot without positioning "Ectoplasmic Distiller"
3- .go creature 41777 kill and loot without positioning "Ectoplasmic Distiller"
4- .go creature 91892 kill some of these npc and loot without positioning "Ectoplasmic Distiller"

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
Good job @CookieMonsterDev 

waiting to be tested.

**Comment by poszer** [comment]
Tested, it's okay now. But someone should write that to test this issue, you have to .add 9061  [Goblin Rocket Fuel] since it's required to use that item Ectoplasmic Distiller

**Comment by FrancescoBorzi** [comment]
good job @CookieMonsterDev and @poszer

**Comment by CookieMonsterDev** [comment]
Thank you! Yeah my bet I forgot to add it, sorry about that

**Comment by comix1988** [comment]
I confirm, now it's okay

**Pull request merged**
