### PR TITLE
Fix mage quest "Investigate the Alchemist Shop"

### PR DESCRIPTION
**Pull request by Motorheadx**
**Changes proposed:**

-  
-  
-  

**Target branch(es):master

**Issues addressed:** Closes # https://github.com/azerothcore/azerothcore-wotlk/issues/846

**Tests performed:** (tested in-game, etc)

- [ ] 
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Tested by @stoabrogga (who opened the issue)
I suppose we can merge

**Comment by Stoabrogga** [comment]
The first change to "Spell.cpp" is not necessary, works also without it.

The main problem of spell 9082 seems to be that it does not find valid targets. The spell only works after changing EffectImplicitTargetA[0] to TARGET_UNIT_NEARBY_ENTRY. The original value is TARGET_DEST_NEARBY_ENTRY, but I don't understand what these values mean.

**Comment by BarbzYHOOL** [comment]
Motorheadx, join our discord :P

**Comment by BarbzYHOOL** [comment]
https://discord.gg/PaqQRkd

**Comment by Stoabrogga** [comment]
I think I found the cause of this problem: Cast items with target type "nearby destination" are not handled correctly in Spell.cpp. I fixed this in PR https://github.com/azerothcore/azerothcore-wotlk/pull/854.

**Comment by BarbzYHOOL** [comment]
Hmm I'm not sure if the PR is needed because of another PR from @Stoabrogga . Can you confirm Stoa?

**Comment by Stoabrogga** [comment]
If PR https://github.com/azerothcore/azerothcore-wotlk/pull/854 will be merged it is not necessary to merge this PR anymore.

**Comment by pondaveia** [comment]
#854 will fix alot of bugs like this one so I'll be closing until other wise we find it needed to come back here.

**Pull request closed without merging**
