### PR TITLE
fix(DBSAI) Quest Fel Spirits

### PR DESCRIPTION
**Pull request by grimgravy**
## CHANGES PROPOSED:
-  added Despawn time in 5 minutes.
-  added Say Line.

## ISSUES ADDRESSED:
- Closes [#2682](https://github.com/azerothcore/azerothcore-wotlk/issues/2682)

## TESTS PERFORMED:
-  windows 7 64bits.
-  works perfectly in the game.
## Target branch(es):
- [x] Test

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Volgger** [comment]
Despawn time works fine - Gobject disappears after 5 minutes. 

What about the laser: 

WoWScrnShot_030120_001252

Is it even possible to fix this bug with sql? I looked around in the SAI and found nothing helpful to fix this...

**Comment by Maurowin** [comment]
@FrancescoBorzi, The laser are not fixed yet, like screenshot of Volgger. Don't merge it right now.

**Comment by Volgger** [comment]
Don't worry, i don't forgot about the laser. I'm still looking for a solution and i think it's core based.

The PR does what it should, fix the despawn time and the added the say line.

For everything else it needs a core dev because this just partially closes the issue.

**Comment by grimgravy** [comment]
The laser spreads within a range of 30 meters [Anchorite Contrition] (https://www.wowhead.com/spell=39184/anchorite-contrition)

**Comment by Helias** [comment]
If this is not complete but at least it improves the functionalities of this Quest and work, I think that we can merge it

**Pull request merged**
