### PR TITLE
fix(DB/SAI): Loramus Thalipedes quests/gossip

### LINKED ISSUE #2439: Quest "Azsharite" Felhound works not correctly
##### SMALL DESCRIPTION:

The Felhound which you get when accepting the Quest 'Azsharite' does nothing after you target him and type emote /roar.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

If you target the felhound and type the emote /roar it should do the emote 'Felhound Tracker searches for a source of arcane energy.' and go around to the next Azsharite in the near. After he found it, the Felhound should do the second emote 'Felhound Tracker growls.'

Look this Video: https://youtu.be/xZ595B7iENg

##### CURRENT BEHAVIOUR:

Nothing happens when typing the /roar emote in the chat ingame while selected the Felhound. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 3602
2. .go 2660.236572 -5852.825684 94.152527 1
3. Release the Felhound with the item 10831
4. Target the Felhound and type the emote /roar in chat

##### EXTRA NOTES:

Seems to be similar to Isse #2415 
You can complete the quest without the felhound by finding the Azsharite yourself. 

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

- Max Skill on levelup

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83809859-quest-azsharite-felhound-works-not-correctly?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- Loramus Thalipedes (quests "The Demon Hunter" and "Loramus"): Add SAI and gossip menus as replacement for the CreatureScript "npc_loramus_thalipedes" and also correct the gossip options.
- Felhound Tracker Kit (quest "Azsharite"): Ensure that it always contains "Fel Orb" and "Fel Tracker Owner's Manual", no other items
- Azsharite Formation (quest "Azsharite"): Ensure that only formations which have a humanoid form can contain a "Crystallized Note"
- Felhound Tracker (quest "Azsharite"): Disable combat with players / NPCs; Add SAI in order to track down the Azsharite Formations

##### ISSUES ADDRESSED:
Closes #2439

##### TESTS PERFORMED:
- tested build on Ubuntu 16.04 / clang 7
- tested successfully in-game

##### HOW TO TEST THE CHANGES:
**Quests "The Demon Hunter" & "Loramus":**
- preparation:
```
.q rem 2744
.q rem 3141
.q a 2744
.go c id 7783
```
- Talk to Loramus and proceed through the quests "The Demon Hunter" & "Loramus"; the gossip options should now be correct.

**Quest "Azsharite":**
- preparation:
```
.q rem 3511
.q a 3511
.q c 3511
.go c id 7783
```
- proceed with the quest chain; after accepting the quest "Azsharite" Loramus should say how to use the Felhound Tracker.
- proceed with the quest "Azsharite": If you `/roar` at the Felhound Tracker it should track down the Azsharite Formations or just growl if no Azsharite Formation is near.

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Endeffect-AT** [comment]
Not working to me on win 10 pro 64 bit. Compiled without errors and imported the sql script but the felhound still does nothing if i target him and do the remote:

WoWScrnShot_123019_220416

Tried several times with restart and cache deleted.

**Comment by Stoabrogga** [comment]
Hmm, don't know, tested this myself a few hours all across the quest area in Azshara and it did work every time. You really have to ensure that GM mode is off, if it is on it won't work.

**Comment by Endeffect-AT** [comment]
Yes, i'm sure that gm mode was off. I will test it again in the next days and try it with no gm level on testing acc. Maybe that will help

**Comment by Stoabrogga** [comment]
I'll also try out a new installation of the server and test again, just to ensure that I did not accidentally break something while implementing this fix.

**Comment by Stoabrogga** [comment]
Ok, tested on a new server (commit 561b9ba) and a fresh DB, then applied the changes of this PR. Still works well for me, I recorded a video:
[azsharite.zip](https://github.com/azerothcore/azerothcore-wotlk/files/4011440/azsharite.zip)

**Comment by Endeffect-AT** [comment]
looks really good!  i hope it just was a misbehabe of my machine that it won't work.  test it soon again :)

**Comment by Endeffect-AT** [comment]
Tested again with several accounts and no gm level:

WoWScrnShot_010120_193030

Now the Felhound just growls after each /roar emote but still don't looks for azsharite. Checked the logs, everything is fine.

**Comment by Stoabrogga** [comment]
Hmm, on which AC commit did you test the fix? Where there any errors while importing the SQL script? Do you have any other modules / customizations installed? Sorry to ask all those questions, but I don't know how to analyze this further because it works on my server.

**Comment by Endeffect-AT** [comment]
Tested again with a fresh db, no mods or other customisations on AC commit  rev. 0a24c3bac9a5 2019-12-29 12:15:24 +0100 and it's still the same. After the /roar emote the Felhound just growls. 

Build on win 10 pro 64 bit without errors. 

**Logs:**
[CMakeOutput.log](https://github.com/azerothcore/azerothcore-wotlk/files/4016303/CMakeOutput.log)
[Server.log](https://github.com/azerothcore/azerothcore-wotlk/files/4016297/Server.log)

--> No error logs

2020-01-02 15_52_32-Run SQL Script

Seems that someone else should test it, I have no idea what else to try :(

**Comment by Stoabrogga** [comment]
0a24c3b is the commit of this PR, I meant the commit of your master branch. In order to test PRs you should first have an updated AC master branch, then switch to an alternate local branch and pull the PR changes. Here's an example:

- clone AC: `git clone https://github.com/azerothcore/azerothcore-wotlk.git azerothcore`
  (if you've already done this, ensure that you're on the master branch and that it has been updated to the latest commit)
- create a new local branch named "pr-2535": `git checkout -b pr-2535`
- pull the PR changes: `git pull origin pull/2535/head` (this will create a new commit for your local PR test branch)
- from here you can compile the core and create a fresh DB

This is basically also explained here: http://www.azerothcore.org/wiki/How-to-test-a-PR

**Comment by Endeffect-AT** [comment]
Always pull to latest commit before i test PRs so this is my master branch commit 
0f590d0

**Comment by Stoabrogga** [comment]
Ok, one final idea: Could you please try this with an English client? Honestly, I don't know why this should make any difference, but I sadly have no other ideas why it doesn't work for you :cry:

**Comment by Endeffect-AT** [comment]
Now i tested this with enUS client and it's still the same :(

**Comment by Stoabrogga** [comment]
I think I've found the problem: One of the timers was too low. Could you perhaps give this another try?

**Comment by Endeffect-AT** [comment]
Of course, there is a long weekend ahead to test \(  ^-^)/

**Comment by Stoabrogga** [comment]
Yeah, sorry for all this trouble and thanks for your help 👍

**Comment by Endeffect-AT** [comment]
No reason to apologize i'm glad to help :)

**Comment by Endeffect-AT** [comment]
Now it worked @Stoabrogga :)

WoWScrnShot_010320_204253

But i had to change the values of your last commit like that:

UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 8668;

DELETE FROM `smart_scripts` WHERE (`entryorguid` = 8668) AND (`source_type` = 0) AND (`id` IN (2));
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(8668, 0, 2, 0, 61, 0, 100, 0, 0, 0, 0, 0, 0, 67, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Felhound Tracker - Linked - Create Timed Event 1');


It sets the timed event with id 2 to 0:

image

How is the time calculated at this value? If it's in seconds i have to around 50 minutes? (InitialMin 3000 / 60 sec = 50 hours?)

**Comment by Stoabrogga** [comment]
Sorry, but this is not a solution. The timer should ensure that the Felhound Tracker does not get stuck in phase 3 if he doesn't find an Azsharite Formation. So now if you use it without an Azsharite Formation near it will not work anymore. The timer is specified in milliseconds, you could try 4000 instead. I still don't understand why the SAI works on my server but not on yours.

**Comment by Endeffect-AT** [comment]
I'm sure that it not solve the problem but maybe help you to find the cause if it

**Comment by Stoabrogga** [comment]
Sadly, as long as I cannot reproduce this behaviour it's very hard to analyze. Nevertheless, I will continue working on this later, currently don't have the time and already spent more than enough hours on a summoned creature no one uses because the sparkle effect on the crystals suffices to find them.

**Comment by Endeffect-AT** [comment]
I will try to find out if I have the time and maybe even test it on ubuntu if it is because of it.  It's not a waste of time, it's a step closer to Blizzlike.  I also spent a few hours testing it 😅

**Comment by Stoabrogga** [comment]
Ok, perhaps one last try. I pushed a new commit removing the timer and changing the phases.

**Comment by Endeffect-AT** [comment]
Thank you very much, now it works as expected! 

I also tested the radius and the felhound is always looking for azsharite when it's 90m away. If no azsharite is in range the felhound growls one time. 
After looting, the same can be repeated until the quest is finished. 

Good work! 👍 

WoWScrnShot_010420_184444

**Comment by Stoabrogga** [comment]
Great, thanks for testing and providing your feedback. I'm glad that this is finally working.

**Comment by Endeffect-AT** [comment]
No problem, big thanks to you! :)

**Pull request merged**
