### PR TITLE
fix(DB): some vanilla instance rare creatures and add missing ones

### PR DESCRIPTION
**Pull request by T1ti**
## Changes Proposed:
Currently a lot of rares in vanilla  dungeons are always spawned, or never spawned.
I made a list of the issues : 
image

## Issues Addressed:
- Fix rares spawning all the time in dungeon :  I added a chance to despawn in SAI to the creatures that didn't have one yet, this is already how instance rares were implemented. I chose 85% to despawn for all, the others ranged from 75% to 90%.

- Fix rares that were never spawned : I copied the missing spawn data and waypoints from [Vmangos ](https://github.com/vmangos/core)which is usualy very reliable and a lot of it is sniffed.

- Added some missing spells and mechanics to some creatures : 
-Added [spell reflect](https://www.wowhead.com/npc=8923/panzor-the-invincible#abilities;mode:normal) to Panzor the invincible. It's an hidden permanant aura that gives him 20% chance to reflect all spells 
-Added [Curse of the tribes](https://www.wowhead.com/npc=11688/cursed-centaur#abilities) to Cursed Centaur. He should cast a curse that reduces physical damage after ~15 seconds initially, and then every ~30 seconds.

## Tests Performed:
I teleported and verified all npcs are correctly spawn and their waypoints is working.
 I didn't extensively test the creatures

## How to Test the Changes:
`.tele creature xxx` to any creature guid added or modified in this PR.
**Here's a bunch of GUIDs to test :** 
**1st group** : 45843, 44422, 43519, 43523, 43521, 203506, 137970, 10899, _47774(+his pet dog),_
**2nd group** : 300627, 56961, 300376, 300742, 300768, 160358, 160355, 300452
- **1st group** : Creatures that got added a despawwn chance, verify if they despawn correctly but  still have a chance to spawn by resetting multiple times. Note that in GM mode you will just see them as dead, without gm mode you shouldn't see them at all. _(85% chance to despawn)_
- **2nd group** : For the newly added creatures, verify if they are correctly spawned and if they work/behave correctly.

## Known Issues and TODO List:
- Some creatures are not scripted at all and missing spells. (waiting for vmangos updates, they are also missing some spells)
-Tsu'Zee is missing the backstab ability
-Veyzhak the canibal is missing two spells : rend and enrage.
-Zekkis is not scripted from SAI
- I haven't added the chance to despawn for the newly spawned rares yet, this is purely for testing purposes. Once they are tested we can give them the despawn chance.
- Cursed centaur's speed is too fast. Should be fixed by a bulk update https://github.com/azerothcore/azerothcore-wotlk/issues/4524
- Ghok Bashguud spawns on top of a raider, not sure how to do it with the current system but on vmangos they are pooled together and the rare sapwn chance is part of the pool in vmangos 
image
update : the spawn location was wrong anyways, waiting for a vmangos update

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
This is really awesome - I have noticed the lack of rare spawns. So great job!

If you want to, you can write the SQL a bit shorter.
```
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 1, -698.351, 559.918, -282.06, 6.01478, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 2, -736.867, 569.914, -291.06, 4.36542, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 3, -743.754, 581.403, -291.06, 2.05638, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 4, -734.431, 619.357, -300.06, 1.31614, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 5, -726.929, 649.513, -309.06, 1.34361, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 6, -717.134, 687.832, -318.06, 1.26506, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 7, -705.253, 694.829, -318.06, 0.471789, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 8, -717.059, 687.506, -318.06, 4.36151, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 9, -726.776, 650.171, -309.06, 4.389, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 10, -734.225, 619.203, -300.06, 1.31416, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 11, -743.649, 581.74, -291.06, 4.92503, 0);
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES (3000376, 12, -736.919, 569.825, -291.06, 5.79487, 0);
```

becomes:

```
INSERT INTO `waypoint_data` (`id`, `point`, `position_x`, `position_y`, `position_z`, `orientation`, `delay`) VALUES 
(3000376, 1, -698.351, 559.918, -282.06, 6.01478, 0),
(3000376, 2, -736.867, 569.914, -291.06, 4.36542, 0),
(3000376, 3, -743.754, 581.403, -291.06, 2.05638, 0),
(3000376, 4, -734.431, 619.357, -300.06, 1.31614, 0),
(3000376, 5, -726.929, 649.513, -309.06, 1.34361, 0),
(3000376, 6, -717.134, 687.832, -318.06, 1.26506, 0),
(3000376, 7, -705.253, 694.829, -318.06, 0.471789, 0),
(3000376, 8, -717.059, 687.506, -318.06, 4.36151, 0),
(3000376, 9, -726.776, 650.171, -309.06, 4.389, 0),
(3000376, 10, -734.225, 619.203, -300.06, 1.31416, 0),
(3000376, 11, -743.649, 581.74, -291.06, 4.92503, 0),
(3000376, 12, -736.919, 569.825, -291.06, 5.79487, 0);
```

**Comment by T1ti** [comment]
update: vmangos just spawned Trigore the Lasher

**Comment by T1ti** [comment]
ready for testing, a few rares are still missing some spells everything else should be ready

**Comment by pklloveyou** [comment]
It's better to have something than nothing

**Comment by FrancescoBorzi** [comment]
@pklloveyou have you tested this? is it ready to be merged for you?

**Comment by pklloveyou** [comment]
Can be merged

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @T1ti and thanks @pklloveyou for testing this

**Pull request merged**
