### PR TITLE
fix(Scripts/BRD): Fixed movement of Burning Spirits during Ambassador…

### LINKED ISSUE #6964: (BRD/Dungeon) Ambassador Flamelash encounter
### Current Behaviour

Burning Spirits doesn't chase Ambassador Flamelash during the encounter, they just stay in their initial summon point.

### Expected Blizzlike Behaviour

Burning Spirits must chase the boss, if they are succeed, boss will grant [Burning Spirit] buff.

### Source

https://www.youtube.com/watch?v=VC039Lty50E

### Steps to reproduce the problem

1. `.go c ambassador_flamelash`
2. Pull the boss

### Extra Notes

_No response_

### AC rev. hash/commit

05bbf4a8589c

### Operating system

Arch Linux 5.12

### Custom changes or Modules

mod-account-achievements
mod-autobalance
mod-buff-command
mod-solo-lfg
mod-transmog

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99970995-brd-dungeon-ambassador-flamelash-encounter?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
… Flamelash encounter.

Fixes #6964

## Issues Addressed:

- Closes #6964

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. `.go c ambassador_flamelash`
2. Pull the boss

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@syssneck Test it again.

**Comment by syssneck** [comment]
Yepp, works now! 👍

**Comment by Helias** [comment]
build fails for unused variable

**Comment by FrancescoBorzi** [comment]
@UltraNix 

```
src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockDepths/boss_ambassador_flamelash.cpp:28:14: fatal error: unused variable 'NPC_AMBASSADOR_FLAMELASHER' [-Wunused-const-variable]
const uint32 NPC_AMBASSADOR_FLAMELASHER = 9156;
             ^
1 error generated.
```

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
