### PR TITLE
DB/Core: Fix hover height and some flying animations of vanity pets

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Fix the hover height for some of the flying vanity pets (they fly nearly on the ground). Also fix the animation while following the player for the moths, the "Gryphon Hatchling" and the "Wind Rider Cub".

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
Tested build, tested in-game

##### HOW TO TEST THE CHANGES:
Summon the following vanity pets, especially the moths, the "Gryphon Hatchling" and the "Wind Rider Cub":
Azure Whelpling
Blue Dragonhawk Hatchling
Blue Moth
Cockatiel
Crimson Whelpling
Dark Whelpling
Emerald Whelpling
Firefly
Frosty
Golden Dragonhawk Hatchling
Great Horned Owl
Green Wing Macaw
Gryphon Hatchling
Hawk Owl
Hyacinth Macaw
Mana Wyrmling
Miniwing
Nether Ray Fry
Netherwhelp
Onyxian Whelpling
Phoenix Hatchling
Red Dragonhawk Hatchling
Red Moth
Senegal
Silver Dragonhawk Hatchling
Sprite Darter Hatchling
Tickbird Hatchling
Tiny Sporebat
Tirisfal Batling
Vampiric Batling
White Moth
White Tickbird Hatchling
Willy
Wind Rider Cub
Yellow Moth

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by wetbrownsauce** [comment]
Tested. 

Works well. All fly at a more appropriate height instead of on the ground. They also properly fly with the player when on flying mount. 

I don't know if this is that important, but the gryphon and wyvern pets don't fly properly if you use .gm fly, but they work fine with flying mounts.

**Comment by Stoabrogga** [comment]
Thanks for testing, @wetbrownsauce .

> I don't know if this is that important, but the gryphon and wyvern pets don't fly properly if you use .gm fly, but they work fine with flying mounts.

This is normal behaviour, as the custom AI only reacts if the player is mounted, which is not the case for GMs flying around.

**Comment by wetbrownsauce** [comment]
Yeah I figured. Looks good!

**Comment by BarbzYHOOL** [comment]
@Stoabrogga thank you for the fixes!!

@wetbrownsauce thx for testing!

**Pull request merged**
