### PR TITLE
fix(DB/Creature): Emeraldon Mobs Missing Patrol Patterns

### LINKED ISSUE #6218: Ashenvale - Emeraldon Mobs Missing Patrol Patterns
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [x] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/771

Emeraldon Mobs (https://wowgaming.altervista.org/aowow/?search=emeraldon) In Ashenvale are stationary and do not patrol around.

emeraldon

Groups and the mob GUIDS:

GUID 33226, 33210, 33241
GUID 33228, 33243, 33229
GUID 33209, 33240, 33208
GUID 33227, 33242, 33211
GUID 33231, 33245, 33230
GUID 33214, 33215, 33246
GUID 33213, 33244, 33212

Tester: confirmed, the whole place is littered with packs of very lazy dragons.

WoWScrnShot_060421_235533

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Emeraldon Mobs should patrol around short distance in groups of 3.

##### SOURCE:

https://classic.wowhead.com/npc=12474/emeraldon-boughguard#comments

https://www.youtube.com/watch?v=Hu6qzkwXyrw

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to npc GUID  32381 and proceed into Bough Shadow (Northeastwern corner of Ashenvale) (or port directly to provided Mob GUID but you will likely die)
2. Observe the groups stationary, not patroling around

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/40cf7b46d221e562a20264316d660318af213690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98988606-ashenvale-emeraldon-mobs-missing-patrol-patterns?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by dillyns**
## Changes Proposed:
-  Add formations for the 7 packs of Emeraldon mobs and set them to wander.
-  Took the wander distance from other similar dragonkin npcs from the other world boss areas.

## Issues Addressed:

- Closes #6218
- Closes chromiecraft/chromiecraft#771

## Tests Performed:

- See next section.

## How to Test the Changes:

DB TEST
1. Run this query to observe the changes:
```
SET @GROUP1_LEADER = 33210;
SET @GROUP1_LEFT = 33226;
SET @GROUP1_RIGHT = 33241;

SET @GROUP2_LEADER = 33243;
SET @GROUP2_LEFT = 33229;
SET @GROUP2_RIGHT = 33228;

SET @GROUP3_LEADER = 33240;
SET @GROUP3_LEFT = 33209;
SET @GROUP3_RIGHT = 33208;

SET @GROUP4_LEADER = 33242;
SET @GROUP4_LEFT = 33211;
SET @GROUP4_RIGHT = 33227;

SET @GROUP5_LEADER = 33245;
SET @GROUP5_LEFT = 33230;
SET @GROUP5_RIGHT = 33231;

SET @GROUP6_LEADER = 33246;
SET @GROUP6_LEFT = 33214;
SET @GROUP6_RIGHT = 33215;

SET @GROUP7_LEADER = 33244;
SET @GROUP7_LEFT = 33212;
SET @GROUP7_RIGHT = 33213;
SELECT * FROM `creature` WHERE `guid` IN (@GROUP1_LEADER, @GROUP2_LEADER, @GROUP3_LEADER, @GROUP4_LEADER, @GROUP5_LEADER, @GROUP6_LEADER, @GROUP7_LEADER);
SELECT * FROM `creature_formations` WHERE `memberGUID` IN (
@GROUP1_LEADER, @GROUP2_LEADER, @GROUP3_LEADER, @GROUP4_LEADER, @GROUP5_LEADER, @GROUP6_LEADER, @GROUP7_LEADER,
@GROUP1_LEFT, @GROUP2_LEFT, @GROUP3_LEFT, @GROUP4_LEFT, @GROUP5_LEFT, @GROUP6_LEFT, @GROUP7_LEFT,
@GROUP1_RIGHT, @GROUP2_RIGHT, @GROUP3_RIGHT, @GROUP4_RIGHT, @GROUP5_RIGHT, @GROUP6_RIGHT, @GROUP7_RIGHT
);
```
2. The first query returns the results of the 7 formation leaders. Their MovementType should be set to 1, and their wander_distance should be set to 15.
3. The second query returns the npc formations. There should be 7 groups of 3 grouping by the leaderGUID. 
Each group should have 1 entry where the leaderGUID and memberGUID is the same (this is the leader). All the other columns for the leader should be 0.
The other 2 entries in the group should have a groupAI set to 2. One entry will have an angle of 300 and the other will have an angle of 60

IN-GAME TEST
1. Move to one of the npcs in the area (ex. ```go creature 33210```)
2. Observe the npcs in the area. There should be 7 groups of 3 npcs each. Each group should wander together, staying together as a 3-npc unit rather than wandering separatly.

## Known Issues and TODO List:

- [Other world dragon npcs need to be looked at. Can guarantee that at least Feralas npcs need to be fixed.]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@dillyns thanks for contributing and sorry for my late review, the code looks good, can you please provide evidence of testing? some screenshots or a video would work, otherwise we have to wait that some other contributor checks this

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Eldarix** [comment]
Tested, looks pretty good so far.

Before the applying of the query they're indeed standing still:

WoWScrnShot_060921_182744
WoWScrnShot_060921_182851

And after the apply they're wandering correctly:

WoWScrnShot_060921_183154
WoWScrnShot_060921_183208
WoWScrnShot_060921_183230

I think the fix works perfectly, great work !!

WoWScrnShot_060921_183357
WoWScrnShot_060921_183410

**Comment by tkn963** [comment]
Tested each groups of creatures before and after the change and it works as it should. 👍 

Would it be a good idea not to have `acore_world`.`table_name` in the information queries? It stunned me for a second as I have several different world databases so using the queries without editing them selects data from the wrong one and it should just select from the one you're running the query against. I might be wrong on this

**Comment by Sedatyf** [comment]
> Tested each group of creatures before and after the change and it works as it should. 👍
> 
> Would it be a good idea not to have `acore_world`.`table_name` in the information queries? It stunned me for a second as I have several different world databases so using the queries without editing them selects data from the wrong one and it should just select from the one you're running the query against. I might be wrong on this

That's a question for @FrancescoBorzi ☝🏼

**Comment by FrancescoBorzi** [comment]
> Tested each group of creatures before and after the change and it works as it should. 👍
> 
> Would it be a good idea not to have `acore_world`.`table_name` in the information queries? It stunned me for a second as I have several different world databases so using the queries without editing them selects data from the wrong one and it should just select from the one you're running the query against. I might be wrong on this

yes, I definitely agree. I did not notice that. But in the PR changes there are no such things, only in the PR description. I'll edit that ;)

**Pull request merged**
