### PR TITLE
Show default options, missing in config files

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
#### Made a mistake, created new pull request. Old (https://github.com/azerothcore/azerothcore-wotlk/pull/906)

**Changes proposed:**

* Update code in Log.cpp (To avoid errors when opening authserver.exe)
* If the required settings are not found when the configuration file is opened, a notification is displayed and the value that was set by default

**Target branch(es):** master.

**Issues addressed:** No issue

**Tests performed:** Tested build, tested in-game (Windows 10 / VS 2017)

**How to test the changes:**
* Comment out the option not related to category Log (.conf and .conf.dist)
**Example** MaxPingTime

image

**Known issues and TODO list:**

- Notifications are working, if everything is in order with the options category Log

### CODE REVIEW

**Comment by Deku** [comment]
Just need someone to confirm this is operational in Linux and we can merge.

**Comment by Winfidonarleyan** [comment]
I'll do it today

**Comment by Winfidonarleyan** [comment]
**Testing in:** Linux 14.04
### Testing if all options exist in conf.dist and .conf
* **Authserver:** 
image
* **Worldserver:**
image

### Testing if missing option (e.g. MaxPingTime)
* **Authserver:**
image
* **Worldserver:**
image

**Comment by Deku** [comment]
Nice! Great work @Winfidonarleyan, we really appreciate it

**Comment by Winfidonarleyan** [comment]
Thanks, always ready to help

**Comment by ShinDarth** [comment]
nice job!

**Comment by BarbzYHOOL** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/992

**Pull request merged**
