### PR TITLE
fix(DB): Grimbooze Thunderbrew Missing Gossip

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Add missing gossip for Grimbooze Thunderbrew (NPC 239)

## Issues Addressed:

- Closes unreported issue

## SOURCE:

https://wowpedia.fandom.com/wiki/Grimbooze_Thunderbrew

## Tests Performed:

Capture

## How to Test the Changes:

1. .go creature 62840
2. No longer is placeholder gossip

## Known Issues and TODO List:

Please kindly feel free to change the Gossip Menu ID and NPC Text ID to anything else using variables at top of SQL file! I am just use these now as they are available. My chosen ID do not conflict with any of my other PR.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
Gossip ids and gossips are sniffed. Do we have a verified database from where this matches up or a sniff to reference the id and text?

**Comment by ZhengPeiRu21** [comment]
> 



> Gossip ids and gossips are sniffed. Do we have a verified database from where this matches up or a sniff to reference the id and text?

I only know that this is the same as the Wiki and Vmangos, but that is my only sources. I do think it is better than the placeholder greeting! Please feel free for waiting to merge until a sniffer can verify.

**Comment by acidmanifesto** [comment]
Well vmangos is a acceptible source. Can u see if the gossip matches up with that?

**Comment by ZhengPeiRu21** [comment]
> Well vmangos is a acceptible source. Can u see if the gossip matches up with that?

Yes, here is this gossip in Vmangos migration:
https://github.com/vmangos/core/blob/a01720f547f0d042b7989085a1a3558cc6e92a64/sql/old_migrations/20190608093343_world.sql

And in current local Vmangos DB to see it has not changed since migration:
Capture

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
