### PR TITLE
fix(DB/Dungeons): Caverns of Time: Old Hilsbrad should be available u…

### LINKED ISSUE #13837: [TBC] CoT Dungeons accessible without Pre-Quest through RDF
https://github.com/chromiecraft/chromiecraft/issues/4466
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

61-64

### Current Behaviour

The dungeon [Old Hillsbrad](https://www.wowhead.com/tbc/zone=2367/old-hillsbrad-foothills) and Escape from Durnholde are accessible through the RDF tool without previous completion of [quest: Caverns of Time](https://www.wowhead.com/tbc/quest=10277/the-caverns-of-time)

### Expected Blizzlike Behaviour

CoT dungones shouldnt be accessible through RDF without completion of said quest, enforcing the same requirements as is for walk-ins
Same, I would expect the 2nd dungeon, Black Morass, to require the Durnhold quest chain (https://www.wowhead.com/tbc/quest=10284/escape-from-durnholde) to be completed also for RDF, not only for walk-ins

### Source
image
https://www.wowhead.com/wotlk/zone=2367/old-hillsbrad-foothills#comments:id=984954

image
https://www.wowhead.com/wotlk/quest=10284/escape-from-durnholde#comments:id=1003615

### Steps to reproduce the problem

.level 64
queue RDF

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/8e0b6aca1a472e456184f2f91f5761944d2817b7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…pon "Caverns of Time" completion.

Fixes #13837

## Issues Addressed:

- Closes #13837
- Closes https://github.com/chromiecraft/chromiecraft/issues/4466

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.level 64`
See if CoT: Old Hilsbrad is enabled  in RDF tool.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Gultask** [comment]
Is there supposed to be an error message when trying to enter without completing the quest? I don't see an error message.
Otherwise it works.

**Comment by Nyeriah** [comment]
I had the same issue with Onyxia. The table seems broken, it doesn't display custom text. However, it should technically work correctly with the quest requirement.

**Comment by UltraNix** [comment]
@Gultask @Nyeriah It's not covered by this PR.

**Comment by Gultask** [comment]
Cmangos uses these texts instead:
'You must complete the quest "The Caverns of Time" before entering Old Hillsbrad Foothills'
'You must complete the quest "The Caverns of Time" and be level 70 before entering the Heroic difficulty of Old Hillsbrad Foothills'

**Pull request merged**
