### PR TITLE
fix(Spells/Scripts): Gnomish Poultryizer

### PR DESCRIPTION
**Pull request by avarishd**
## Changes Proposed:
- Fix 30504(malfunction) not being broken on damage
- Use correct backfire spell (30506) TARGET_UNIT_CASTER

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5051

## SOURCE:

https://wowpedia.fandom.com/wiki/Gnomish_Poultryizer
https://www.wowhead.com/wotlk/item=23835/gnomish-poultryizer#comments

https://www.wowhead.com/wotlk/spell=30501/poultryized chicken, -66% dmg
https://www.wowhead.com/wotlk/spell=30504/poultryized malfunction, big chiken, +100% dmg
https://www.wowhead.com/wotlk/spell=30506/poultryized backfire, chicken, not broken on damage

## Tests Performed:

- tested

## How to Test the Changes:

Use 2 characters
.additem 23835
.learn 202
.setskill 202 450
.learn 20219

There should be 2 successful casts on the target, one is the small chicken and the other (20%) big chicken.
Both of them should be canceled by any damage taken.

Backfire should be applied to the caster and shouldn't be removed by damage taken.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kofmy** [comment]
degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates

**Review by Nefertumm — APPROVED** [review]
Seems okay.

**Comment by Nefertumm** [comment]
One question though, where the 80% chance come from?

**Comment by avarishd** [comment]
The backfire one was there prior to the PR, as for the malfunction, I'm using the same percentage as backfire (can't really find source even if I wanted to).
Maybe it should be lower to 5% like Goblin Bomb?

https://github.com/azerothcore/azerothcore-wotlk/blob/dacd4b7159b2284adc7831190326abd9350206b9/src/server/scripts/Spells/spell_item.cpp#L3561

https://wowpedia.fandom.com/wiki/Patch_2.1.0

>The [Poultryizer](https://wowpedia.fandom.com/wiki/Poultryizer) has a smaller chance of getting malfunction effects and is now a superior quality item.

**Comment by Nefertumm** [comment]
Fine for me, we can tune it up later.

**Review by Helias — APPROVED** [review]

**Comment by GastonCK** [comment]
I don't know whether this PR adresses only the effect cancellation or both the cancellation and the damage modifier so I tested both things.

Normal damage received (combatlog)
WoWScrnShot_081023_135502


Small chicken's damage doesn't seem to be 66% reduced to me, it looks the same.
WoWScrnShot_081023_135519


Small chicken properly canceled by damage.
WoWScrnShot_081023_141201


Big chicken's damage properly increased by 100%
WoWScrnShot_081023_140243


Big chicken properly canceled by damage
WoWScrnShot_081023_142132


Backfire is not canceled by damage taken, which is correct.
WoWScrnShot_081023_135633


Normal Damage done to target (combatlog
WoWScrnShot_081023_143026


Backfire's damage properly reduced by 66%
WoWScrnShot_081023_143140

**Comment by Nyeriah** [comment]
Ty for test

**Pull request merged**
