### PR TITLE
fix(Core/Gossip): Fix gossip menu for locale clients

### LINKED ISSUE #7209: Overlapping entries in guards gossip menu (locale Client)
### Current Behaviour

When a guard is asked for directions, some overlapping entries without text are displayed in the gossip menu:

grafik

### Expected Blizzlike Behaviour

Entries should not overlapp:

grafik

### Source

_No response_

### Steps to reproduce the problem

1. Go to any city and ask any guard

### Extra Notes

Client: deDE

### AC rev. hash/commit

AzerothCore rev. 498e01e7fcb4+ 2021-07-29 12:18:36 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1j  16 Feb 2021 (library: OpenSSL 1.1.1j  16 Feb 2021)
Using Boost version: 1.74.0
Using MySQL version: 100510
Using CMake version: 3.18.4
Compiled on: Linux 5.11.0-25-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/gameserver/azeroth-server/Data/maps. Total size: 252191207 bytes
vmaps directory located in /home/gameserver/azeroth-server/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in /home/gameserver/azeroth-server/Data/mmaps. Total size: 2196365052 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS deDE
Using World DB: ACDB 335.4-dev
Using World DB Revision: 2021_07_29_04
Using Character DB Revision: 2021_07_21_00
Using Auth DB Revision: 2021_06_17_00

### Operating system

Ubuntu 21.04 x64

### Custom changes or Modules

mod-ah-bot
mod-autobalance
mod-new-character-perks
mod-pocket-portal (https://github.com/milestorme/mod-pocket-portal)
mod-solo-lfg (https://github.com/milestorme/mod-solo-lfg)

Custom changes for mod-solo-lfg:
/src/server/game/DungeonFinding/LFGMgr.cpp
/src/server/game/DungeonFinding/LFGMgr.h
/src/server/game/DungeonFinding/LFGQueue.cpp

### LINKED ISSUE #15119: gossip_menu_option_locale not work
### Current Behaviour

Even There are corresponding records in  gossip_menu_option_locale
some of main city guards gossip menu still english. I check DB wiki,these locale text come from table "broadcast_text_locale" but not gossip_menu_option_locale.
WoWScrnShot_021923_164333
无标题

### Expected Blizzlike Behaviour

npc's gossip menu text should reading the text from gossip_menu_option_locale,but now it come from broadcast_text_locale

### Source

_No response_

### Steps to reproduce the problem

if you change the text in gossip_menu_option_loacale , npc gossip menu will not change 

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. eb36cbb42c08

### Operating system

docker ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by wzw1990**
## Changes Proposed:
-  Fix menu not localized properly when OptionBroadcastTextID=0
-  Fix menu not localized properly when broadcast_text_locale was missing locale text
-  Using gossip_menu_option texts by default

## Issues Addressed:

- Closes #15119 
- Closes #7209
## Tests Performed:

- Tested in-game with zhCN client and enUS client
- Change before: 
WechatIMG1333
- Change after:
WechatIMG1541

## How to Test the Changes:

1. Login to the game except for enUS client, I'm using zhCN.
2. Find a guardian, such as a Silvermoon City Guardian
3. Talk to them
4. Menu should be correctly localized

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by wzw1990** [comment]
> I think this is like the 10th time this is switched back and forth lol

The best code is always the next time lol

**Comment by pangolp** [comment]
I will see if I can test with the client in Spanish.
But it is true, that some gossip, in spite of being translated in the DB, were not being correctly displayed.

**Comment by wzw1990** [comment]
I think there are two cases where localization will fail under the [current code](https://github.com/azerothcore/azerothcore-wotlk/blob/c676a828376877e63da77fc1adc81ac2aa3daab0/src/server/game/Entities/Player/PlayerGossip.cpp#LL186C21-L186C34)

**Case 1**: OptionBroadcastTextID in gossip_menu_option has no value, so itr->second.OptionText will be used, and the condition of strOptionText.empty() is not true, and the localization logic will fail
**Case 2**: OptionBroadcastTextID in gossip_menu_option has a value but there is no corresponding client language in broadcast_text_locale, causing ObjectMgr::GetLocaleString() to return nullptr and display a blank menu

The problem I'm having is case 1, #8396 seems to be case 2

**Comment by pangolp** [comment]
> I think there are two cases where localization will fail under the [current code](https://github.com/azerothcore/azerothcore-wotlk/blob/c676a828376877e63da77fc1adc81ac2aa3daab0/src/server/game/Entities/Player/PlayerGossip.cpp#LL186C21-L186C34)
> 
> **Case 1**: OptionBroadcastTextID in gossip_menu_option has no value, so itr->second.OptionText will be used, and the condition of strOptionText.empty() is not true, and the localization logic will fail **Case 2**: OptionBroadcastTextID in gossip_menu_option has a value but there is no corresponding client language in broadcast_text_locale, causing ObjectMgr::GetLocaleString() to return nullptr and display a blank menu
> 
> The problem I'm having is case 1, #8396 seems to be case 2

Isn't a double validation or a default value possible in case I don't have the translation?

**Comment by wzw1990** [comment]
> Isn't a double validation or a default value possible in case I don't have the translation?

I think a new function with default value might need to be added
If broadcast_text has a value but broadcast_text_locale is missing then the default language value is returned, which is better than a null value and reminds us that we should fix it in the database
**Pseudocode:**
```
GetLocaleStringOrDefaultLocale(const std::vector<std::string>& data, int loc_idx, std::string& value) {
  GetLocaleString(data, loc_idx, value);
  if (value.isEmpty()) {
    GetLocaleString(data, DEFAULT_LOCALE, value);
  }
}

optionBroadcastText = GetBroadcastText(optionBroadcastTextID)
boxBroadcastText = GetBroadcastText(BoxBroadcastTextID)
if optionBroadcastText {
    GetLocaleStringOrDefaultLocale(getGender() == GENDER_MALE ? optionBroadcastText->MaleText : optionBroadcastText->FemaleText, locale, strOptionText);
} else {
  // fallback to gossip_menu_option and gossip_menu_option_locale
}
if boxBroadcastText {
    GetLocaleStringOrDefaultLocale(getGender() == GENDER_MALE ? boxBroadcastText->MaleText : boxBroadcastText->FemaleText, locale, strBoxText);
} else {
  // fallback to gossip_menu_option and gossip_menu_option_locale
}
```

**Comment by wzw1990** [comment]
Finally use the default value to solve this problem, ready to be reviewed @yehonal-bot

**Comment by FrancescoBorzi** [comment]
@Kitzunu @pangolp what's the status of this PR?

**Comment by Nyeriah** [comment]
This breaks localization for some clients while fixing it for others so in the end you’re still left with broken localization. This has been switched back and forth a couple of times

**Comment by pangolp** [comment]
> @Kitzunu @pangolp what's the status of this PR?

The truth is that I have not tried it. If you want later when I arrive I can do it.

**Comment by pangolp** [comment]
Today during the day, I download the branch and upload the results with the esES client. I was traveling, so I can't do it before. A thousand apologies. Later I will upload the results and screenshots / videos.

**Comment by pangolp** [comment]
I have just tested with the Spanish client.
These are the results.

With the latest version of the emulator, they look like this.
WoWScrnShot_071223_024033

Then, download and compile the branch.
And it looks like this.
WoWScrnShot_071223_024555

At first glance, there appear to be no changes.
But then, checking in the database.
I found, that we don't have all the translations.
So the code works fine.
We only need to add the spanish translations.
But that is the subjec
result
t of another pull request.

**Review by pangolp — APPROVED** [review]

**Comment by wzw1990** [comment]
> Did you try Russian? Iirc the issue was that the Russian would work while the French would not, vice versa

I just tested the Russian client (obviously I don't understand Russian)
SilvermoonGuardian(Russian)

Nothing has changed because there is no translation in gossip_menu_option_locale
微信截图_20230712185405

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Thanks for testing

**Pull request merged**
