### PR TITLE
fix(Core/Units): Clear any movement on charm - vol. 2.

### LINKED ISSUE #11880: [BWL] Razorgore becomes uncontrollable and "teleports" to the orb/player when using the Orb of Domination to control him
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour
When in an encounter with Razorgore the Untamed inside Blackwing Lair, the person trying to control Razorgore would sometimes be unable to take control of him, as he would just move towards the Orb/ Controlling player location and after that be controllable. In the process, other players are unable to see Razorgore move from the moment the Orb was clicked to control him until the moment he reaches the player/orb location, making it seem like he teleported.
### POV of the players not controlling Razorgore:

[Razorgore teleport video 1](https://streamable.com/08g66n)

[Razorgore teleport video 2](https://streamable.com/jm0e11)
[
Razorgore teleport video 3](https://streamable.com/pv9tow)
### POV of the person using the Orb of Domination:

[Razorgore unable to be controlled until he comes back 1](https://streamable.com/b5an67)

[Razorgore unable to be controlled 2](https://streamable.com/x2q74m)

[Razorgore uncontrolled 3](https://streamable.com/pv9tow)

### Expected Blizzlike Behaviour

Razorgore should be controlled immediately once the Orb is clicked, without him going back to the Orb / controlling player location.
Players should not be able to see him as if he teleported to the Orb location.

### Source

Should be self evident as this has not happened before.

### Steps to reproduce the problem
    1. Enter Blackwing Lair.
    2. Engage Razorgore the Untamed.
    3. Try to use Orb of Domination and see him run back towards you before he is able to be controlled.
    4. See other players see him teleport to your location in the process.

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3549

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11880

## Issues Addressed:

- Closes #11880
- Closes https://github.com/chromiecraft/chromiecraft/issues/3549

## Tests Performed:

- Not tested.

## How to Test the Changes:

1. Enter Blackwing Lair.
2. Engage Razorgore the Untamed.
3. Try to use Orb of Domination

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
hi, update all your PR branches with master

**Comment by Gultask** [comment]
Tested. I didn't see a teleport with another character but I still couldn't control him until he reached my character, just like in the videos provided.

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Gultask** [comment]
Working great now 👍

**Comment by mpfans** [comment]
@Nyeriah Please merge it

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
