### PR TITLE
feat(DB/Spawns): port from TC spawns and event associations

### PR DESCRIPTION
**Pull request by Helias**
## Changes Proposed:
-  Ported from TC the related spawns and event associations of NPC Goblin Commoner, and several NPCs involved in the following **events**:
12, 24, 7, 1, 26, 51, 50, 9

About event 9 check if the following NPCs give the related quests

**NPCs questgivers ID**  (check them!):
19148, 18927, 19178, 19177, 19176, 19175, 19169, 19171, 19172, 19173, 20102, 20102

**Quests**
13484, 13484, 13483, 13483, 13483, 13483, 13483, 13484, 13484, 13484, 13484, 13483

related commits
https://github.com/TrinityCore/TrinityCore/commit/1399e705ebbe1429f8549eb41de6e70b823a7b22
https://github.com/TrinityCore/TrinityCore/commit/e6a7818a9a12b085c8ea07cfb8b3c6d1d700a112

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4330
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4335

## Tests Performed:
- tested in-game activating and deactivating the event

## How to Test the Changes:
- `.event stop X`
- `.event start X`
- check the NPCs in the related cities (Booty Bay, stormwind etc. )
- check if all the quest givers work properly
- check if the NPCs should stand in all event without any issue
- `.event stop X`

About event 9 check if the following NPCs give the related quests (see the IDs above).
Check also if the NPCs (like goblin commoner) change the equipe when you stop and start a new event.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
I believe they are supposed to be spawned during Hallow's End (ID 12 if I remember correctly)

**Comment by Helias** [comment]
Looking our DB we have 100 goblin spawned most of them at the same position of others, in TC there are 45 spawns.
There is something wrong, I am investigating and probably I will do a clean and a porting from TC.

**Comment by Kitzunu** [comment]
Yea, less data is better and if it works as it should on TC then I am happy

**Comment by Helias** [comment]
Ported from TC the related spawns and event associations of NPC Goblin Commoner 20102.

image

**Comment by Kitzunu** [comment]
just check so the GUID's are available

**Comment by Helias** [comment]
PR updated, I ported the two TC commit into this PR.

I tested the Stranglethorn Vale zone using
.event start [some events]
and also .event stop and start again (and/or started multiple events at the same time).

I tried some events on Stormwind and they seem to work, but, I need your help to make deeper test.

**Comment by Helias** [comment]
ok, I verified all the guids, there should not be any conflicts and I fixed the startup errors, now we need to **test a lot**.

**Comment by LannyE** [comment]
I tested in the following locations:
Stormwind, Ironforge, Darnassus, Exodar, Silvermoon, Orgrimmar, Thunder Bluff, Undercity, Ratchet, Gadgetzan, Shattrath City, Dalaran, and Booty Bay.

The following issues were found:
- There are no Tauren Commoners
- There are no Gnome Commoners
- Nobelgarden is missing but the commoners do spawn but without the rabbit ears model.

**Comment by LannyE** [comment]
Also I noticed the weekly battleground NPCs are missing from all cities.    
WoWScrnShot_022521_234524

**Comment by Stifler82** [comment]
Good Job @Helias 👍

**Comment by Helias** [comment]
I need to make some checks so

**Comment by Kitzunu** [comment]
status?

**Pull request closed without merging**
