### PR TITLE
Add foreign key to delete the characters if the account is deleted

### PR DESCRIPTION
**Pull request by mornil**
## Changes Proposed:
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:
- Closes 

https://github.com/azerothcore/azerothcore-wotlk/issues/19194

## Tests Performed:
- [ ] Tested in-game by the author.

## How to Test the Changes:

1. Create an account.
2. Login and create a character. Logout
3. Delete the account in the database -> the character is also removed

## Known Issues and TODO List:

     Do not remove the instructions below about testing, they will help users to test your PR -->
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Correct. It should be handled with the account- and character delete commands

**Comment by mornil** [comment]
Should not those tables at least have foreign key contraints? The issue is if you want to delete 1000:s of account.

**Comment by Nyeriah** [comment]
My understanding is that would be a nightmare to manage and it requires further study of what could go wrong during run time, e.g items being moved from character to bank, especially guild bank, so on, so forth.

**Comment by Nyeriah** [comment]
Closing as per the above, I am sorry

**Pull request closed without merging**
