### PR TITLE
fix(DB/Creatures): add Intervene spell to Bonechewer Shield Disciple

### PR DESCRIPTION
**Pull request by Grimdhex**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19861
- Closes https://github.com/chromiecraft/chromiecraft/issues/7332#issue-2503084607

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. type .tele bt
2. find bonechewer shield disciple on the way to Gurtogg Bloodboil.
3. pull and it, and with another charcter move away (8-25y) bonechewer from the rest of the group.
4. wait to intervene

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Grimdhex** [comment]
I put this PR as draft because I need more infos about the behavior (timers and if the target is specific or random. For the random, the SAI is put to closest friendly target).

**Comment by kissingers** [comment]
tested, still will not move
image

might need change in smartAI
image

**Comment by Grimdhex** [comment]
> tested, still will not move image
> 
> might need change in smartAI, or change the creature flags image
> 
> will the Scritp AI and Smart AI both run for creature?

wrong PR ?

**Comment by kissingers** [comment]
sorry I misstake the message, this for the before pr 
https://github.com/azerothcore/azerothcore-wotlk/pull/19948

**Comment by Rorschach91** [comment]
This ability probably works like the warrior's spell. 
It has 30 seconds cooldown and It only works if one or multiple allies are more than 8 and less than 25 yard away from Bonechewer Shield Disciple.
By the other thing, I don't know if It is randomic, but I think that Bonechewer Shield Disciple gives priority to the ally with less HP.

The problem regarding this ability is that I wasn't able to find a gameplay fight when the mob use Intervene. Usually the players keep the pack united. 
Another problem is that I cannot enter in instances on Cata Classic PTR.

**Pull request closed without merging**
