### PR TITLE
fix(DB/Gameobject): Fix Silithyst Geyser click invalid

### LINKED ISSUE #18034: [Quest]Scouring the Desert- Can't get the silithid aura from silithid mounds
### Current Behaviour

Originally reported https://github.com/chromiecraft/chromiecraft/issues/6457.
Trying to get the silithid from a mound does not give the aura/buff. So quest can't be turned in. https://wowgaming.altervista.org/aowow/?quest=9419

### Expected Blizzlike Behaviour

Clicking on a silithyst geyser should give an aura to the character.

### Source

https://wowgaming.altervista.org/aowow/?quest=9419
https://www.youtube.com/watch?v=i30NuEzK2xk

### Steps to reproduce the problem

1. Enable PVP (/pvp)
2. Go to Silithus/General Kirika (.go c 43204)
3. Accept quest Scouring the Desert (.quest add 9422)
4. Find a Silithyst Geyser (.gob add temp 181598)
5. Right-click it - no aura is applied. Manually apply correct aura: .aura 29519.
6. Turn Silithyst by going to X:-7589, Y:757, Z:-15 - this completes the quest which can be turned in

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/123bf37ee7e6763d9d7f4b778cfe8453577bce6c

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by disgrace2013**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #18034 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Thanks for the update 🙂 

I'm not sure if you accidentally closed & reopened the PR - you can also edit the PR title without closing the PR first.

**Comment by disgrace2013** [comment]
> Thanks for the update 🙂
> 
> I'm not sure if you accidentally closed & reopened the PR - you can also edit the PR title without closing the PR first. (Just fyi)

Sorry,this is my first PR,I'm not  familiar with it.

**Comment by sudlud** [comment]
Thanks again for your contribution!

This PR most likely fixes the linked issue, but to me it looks like the issue was actually caused by a different underlying issue.

There already existed a mechanism to handle the aura buffing of the player, which seems to be broken right now.
This PR would add a second mechanism in parallel while not touching the broken existing mechanism.

I've tried to track down the existing mechanism and made a suggestion of a fix in https://github.com/azerothcore/azerothcore-wotlk/issues/18034#issuecomment-1937765304

Maybe you want to look into that and update your PR to fix the existing mechanism? 🙂

I'd like to hear your thoughts on this

**Comment by disgrace2013** [comment]
> Thanks again for your contribution!
> 
> This PR most likely fixes the linked issue, but to me it looks like the issue was actually caused by a different underlying issue.
> 
> There already existed a mechanism to handle the aura buffing of the player, which seems to be broken right now. This PR would add a second mechanism in parallel while not touching the broken existing mechanism.
> 
> I've tried to track down the existing mechanism and made a suggestion of a fix in [#18034 (comment)](https://github.com/azerothcore/azerothcore-wotlk/issues/18034#issuecomment-1937765304)
> 
> Maybe you want to look into that and update your PR to fix the existing mechanism? 🙂
> 
> I'd like to hear your thoughts on this

I get it, but it's hard for me, so I'll close this PR.I also feel like it doesn't solve the problem fundamentally.

**Comment by sudlud** [comment]
Please don't take this as negative feedback, I didn't mean to discourage you.

I just tried to give my thoughts on this - also no need to close the PR, it's also very possible that my opinion on this was wrong and also I'm not a maintainer.

**Comment by sudlud** [comment]
@disgrace2013 
You wanna give this another try and provide a new PR with the fix that was proposed in the linked issue? 🙂

I'm confident that you can do it.

**Pull request closed without merging**
