### PR TITLE
feat(DB/acore_string) Spanish translations of `acore_string`

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
-  Update acore_string texts in Spanish.

## Issues Addressed:

- Closes

## Tests Performed:

- Windows 10

## How to Test the Changes:

1. Apply SQL
2. Test different server commands and texts

## Screenshots

WoWScrnShot_062221_034241

WoWScrnShot_062221_034436

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by pangolp** [comment]
Approximately 22 translations were left out, out of the 1,199 that were missing. And I had to apply the SQL directly in the client window, because it wouldn't let me import it, due to the special characters I think. And I'm not sure if any changes should be made to the table.

**Comment by pangolp** [comment]
We'd better make smaller changes to it, because it seems to me that it generates errors if not.

**Comment by pangolp** [comment]
Do not approve this PR, because I think it brings problems.

**Comment by FrancescoBorzi** [comment]
> Do not approve this PR, because I think it brings problems.

ok, please let us know once this is ready to be reviewed again

**Comment by pangolp** [comment]
> > Do not approve this PR, because I think it brings problems.
> 
> ok, please let us know once this is ready to be reviewed again

I will have to divide it into about 10 PRS, of about 100 translations each, and test them. Then I'll put them all together in a single file again. Or we can go through them a little at a time.

**Comment by pangolp** [comment]
I will have to close the PR and open another one.

**Pull request closed without merging**
