### PR TITLE
fix(Scripts/Icecrown): ICC Lich King is now killable after 10% health.

### PR DESCRIPTION
**Pull request by devovh**
## Changes Proposed:
-  The problem is that the boss will fall under the texture after killing him and you have to exit and re-enter the instances to pick up the loot, I will try to fix it.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10821

## Tests Performed:

- Tested
- Windows x64

## How to Test the Changes:

1. Enter Instance Icecrown Citadel
2. Bring the Boss to 10% HP, which is the last stage where you just have to kill him.
3. If the boss falls under the texture, leave the instance and re-enter.
4. Move to Lich King and Open Loot.

## Known Issues and TODO List:

- [x] The Lich King is now Killable.
- [ ] Re-instance to Open Loot - fix it.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kisskam** [comment]
Fixed the damage issue when he is at 10% health or less, but now when he kills LK he falls off the platform making it impossible to grab the items he drops.

[https://www.youtube.com/watch?v=Yz9rCrAk_H8](url)

* I do not speak English. I use a translator tool to be able to communicate on the platform. I apologize if what I say is not very understandable.

**Comment by pangolp** [comment]
With the emulator updated, I downloaded the changes from this pull request, and the truth is that I don't get any difference. In my case, the boss is at 9% of life, and once the npc `Terenas Menethil` appears and revives us, the boss becomes unpunished. The only way to kill him is by using the `.die` command, because it is not even a question of damage, since I have tried to use the `.damage` command with different values and I cannot finish the fight. I thought I saw a person say that it had something to do with the type of movement, but the truth is that I could not reproduce, not even what is seen in the video.

**Comment by Ramys** [comment]
I just tested it, and it really doesn't die at 10% health.
Confirmed!

**Comment by pangolp** [comment]
The problem is that the script itself has not changed much, except for those lines proposed in this pull request. But applying them does not really solve the problem either. I am trying several things today, but obviously I don't have enough knowledge to fix this problem. We will have to wait for someone else to come along who knows a little more about the subject.

**Comment by Ramys** [comment]
Video :. https://files.fm/f/36a59upw8
@pangolp

**Comment by pangolp** [comment]
Thanks to @Nefertumm help, we were able to find a solution. It would be interesting if you can test it please. Now I create the pull request, and link it to this one.

**Comment by pangolp** [comment]
@devovh I am going to copy the title.

**Comment by Nefertumm** [comment]
The issue is fixed on e139ed1c0bbd342b300083e1ffbfdb883cb1b009

**Pull request closed without merging**
