### PR TITLE
refactor(Core/Scripting): Unify the gossip scripting API

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  Unify the gossip API, easier to use, easier to manage, less redundancy and also more TC compatibility
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Good

**Comment by Nyeriah** [comment]
230 left to go.

I definitely underestimated the amount of hardcoded gossips we had.

**Comment by FrancescoBorzi** [comment]
@Nyeriah what's the status of this? is it possible to merge what has been done so far and complete the work later?

**Comment by Nyeriah** [comment]
> @Nyeriah what's the status of this? is it possible to merge what has been done so far and complete the work later?

Unfortunately that's not possible. Right now I'm stuck in a situation where it's too late to give up on it and at the same time there's more pressing matters than this, so I don't have the time to invest into it. I'll try to finish it until the next weekend so we get rid of it.

**Comment by Nyeriah** [comment]
Actually, I'll just drop this, it's a bad idea to try implementing it while we have so many useless hardcoded gossips, it might lead to adverse effects. It's a shame but it's for the best I suppose

**Pull request closed without merging**
