### PR TITLE
fix(Core/Pets): Player summon's will not trigger unnecessary combat

### PR DESCRIPTION
**Pull request by arenacraftwow**
A branch of code was using `IsPet()` where I think the author meant `IsSummon()`. Anyhow this created the issue linked below. 

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2838

## TESTS PERFORMED:
- Tested locally, fixed the issue. Nothing appears to be broken.

## HOW TO TEST THE CHANGES:

- Follow issue instructions and just see if the problems persists. 
- Should probably test other pet related stuff, see if nothing is broken etc.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Si1ker** [comment]
@arenacraftwow  It didn't fix it.

Demon controlled by warlock will trigger combat.

### Before PR
2020-04-04 10_06_42-Window


### After PR
after

**Comment by arenacraftwow** [comment]
@Si1ker nice catch. I've retested and you are correct. However it still works with 
- water ele
- sfiend
:thinking:
So this fix i'd say is good enough for PVP  but for clarity should probably find what's different about captured deamons. Gonna look into this further later, meanwhile if anyone has an idea to what try out just go ahead.

**Comment by Si1ker** [comment]
@arenacraftwow Sure, what you mean with sfiend ? 🤔 💭

**Comment by arenacraftwow** [comment]
@Si1ker Shadowfiend, priest pet

**Comment by arenacraftwow** [comment]
Changed the check to `IsGuardian()` instead of `IsSummon()` seems to include the same class of pets as `IsSummon` but also the warlock controlled demons.

**Comment by gengarshadowball** [comment]
imagem
imagem


Enslaved demon does not trigger combat
Summoned succubus does trigger combat

I suggest adding IsSummon isGuardian to the same check

**Comment by FrancescoBorzi** [comment]
@arenacraftwow why closing this?

**Comment by arenacraftwow** [comment]
@FrancescoBorzi Seems like it auto closed because I deleted the remote branch (since I was doing some cleaning)

**Comment by laasker** [comment]
> imagem
> imagem
> 
> Enslaved demon does not trigger combat
> Summoned succubus does trigger combat
> 
> I suggest adding IsSummon isGuardian to the same check

How do i do that? I tried changing to:
if (GetTypeId() == TYPEID_UNIT && !IsSummon() && !IsGuardian())
But some pets get weird, like Dk Unholy Ebon Gargoyle doesnt attack targets unless the Gargoyle itself gets attacked, also shaman enhancement Wolves movement speed gets weird i think

**Pull request closed without merging**
