### PR TITLE
fix(DB/Gameobject): Missing in DB (Giving conflicts on quest)

### PR DESCRIPTION
**Pull request by poszer**
Adding missing gameobject

##### CHANGES PROPOSED:

-  Adding missing gameobject_template in DB. Entry 184981 (Poodad Trap)
-  Required for Quest https://wotlk.evowow.com/?quest=10629

###### ISSUES ADDRESSED:

The problem is that we missing creature in gameobject_template related to this quest. So, since this quest work like, yor pet have to summon gameobject after you kill creature there, and you loot them, until you loot quest item. On the first try you are able to loot it (Your pet will create it), if the quest item isn't droped, and you are trying to kill second mob, than your Pet spawn gameobject, but you are unable to loot it. Actually you are unable to click on it.
Related to this report: https://github.com/azerothcore/azerothcore-wotlk/issues/1824

```sql
2019-05-08 13:20:11 Gameobject (GUID: 2140565 Entry: 184981) not created: non-existing entry in `gameobject_template`. Map: 530 (X: 174.656204 Y: 2941.460449 Z: 24.702682)
2019-05-09 15:49:48 Gameobject (GUID: 2136466 Entry: 184981) not created: non-existing entry in `gameobject_template`. Map: 530 (X: 463.308716 Y: 2914.412109 Z: 41.515911)
2019-05-09 15:51:14 Gameobject (GUID: 2136492 Entry: 184981) not created: non-existing entry in `gameobject_template`. Map: 530 (X: 503.835632 Y: 2955.605225 Z: 32.195271)
2019-05-11 15:36:32 Gameobject (GUID: 2144716 Entry: 184981) not created: non-existing entry in `gameobject_template`. Map: 530 (X: 500.778961 Y: 2955.333740 Z: 32.511833)
2019-05-11 15:37:32 Gameobject (GUID: 2144810 Entry: 184981) not created: non-existing entry in `gameobject_template`. Map: 530 (X: 473.075165 Y: 2987.416260 Z: 23.230686)
```

Closes 

##### TESTS PERFORMED:

Yes, everything work perfect now and no more DB errors

##### HOW TO TEST THE CHANGES:

First test this without this commit:
1. Get this quest [Shizz Work](https://wotlk.evowow.com/?quest=10629)
2. Than .go c 58690
3. Use quest item, and summon your pet.
4. Than go at this creature and kill it .go c 58056
5. Your pet will spawn Gameobject (If you don't loot required object) try to kill another one.
6. Your pet will spawn another Gameobject (But you are unable to loot it) - Also check now your DB log, you will have some errors bcoz creature can't create it. 
7. Now when you see problem, apply commit ,and test with it. 

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Meltie2013** [comment]
I remember giving a fix for this months ago. Not sure why it wasn't added then. https://github.com/azerothcore/azerothcore-wotlk/issues/1016

**Comment by poszer** [comment]
> I remember giving a fix for this months ago. Not sure why it wasn't added then. #1016

Dunno. As you can see, none from that issue conversation didn't open PR with your fix included. That's the posible reason. Thank you anyway

**Comment by BarbzYHOOL** [comment]
Well Poszer, you closed the issue saying no errors anymore. Mistake?

**Comment by poszer** [comment]
> Well Poszer, you closed the issue saying no errors anymore. Mistake?

Yes, issue is closed, since i didn't saw any reports about this in my log. Also, the issue is reported in 2018, ''fix included'' is also marked in 2018. which means that none of people there didn't tested this, even though this guy wrote the right solution which tell too much. 
Something I want to say is that someone is very lascivious to do anything. And in this case, it was hardly possible to reproduce this issue. Simply, it means: Whoever explores it, he solves it

**Comment by Meltie2013** [comment]
Pfft, c & p fix.

**Comment by Log-nx** [comment]
Closing to claim others input, could have just verified Melts fix worked didn't have to make a whole new post.

#Devlogic

**Comment by poszer** [comment]
> Closing to claim others input, could have just verified Melts fix worked didn't have to make a whole new post.
> 
> #Devlogic

Everyone are able to open PR, right?

**Comment by poszer** [comment]
> Pfft, c & p fix.

P.S What is here C/p fix ? Did you explain anything about your post year ago? Nope.
Is this your fix? It's not. It's easy to compare trinity database with our one, almost same structure.
Btw. to explain you better, you think it's hard to get what's wrong here, so you want to say something? 
Watch now the DB error :
Gameobject (GUID: 2140565 Entry: 184981) not created: non-existing entry in `gameobject_template`

What first you gona do about this ? 
Check : https://wotlk.evowow.com/?object=184981
If it exist, we don't have entry in our db. 
Than compare our db with TC, and check there. 
If it exist on TC:
Export, import -> Check, working ? -> Yes -> Post PR.

**Comment by BarbzYHOOL** [comment]
Everyone can make mistakes, I clean the comments from people who talk and do nothing. Thank you for your numerous PRs Poszer

**Comment by Knindzagxg** [comment]
Tested again, all good.

**Comment by BarbzYHOOL** [comment]
@Knindzagxg thank you friend!

@poszer your commits are perfect, I don't even change one line :P

**Pull request merged**
