### PR TITLE
fix(DB/gameobject): Quest 'Soaked Pages' GO respawn time

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## Changes Proposed:
-  Fix [Soaked Pages] GO respawn time

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4060

## Tests Performed:
- Tested in game

## Target Branch(es):
- [x] Master

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]

**Comment by Yehonal** [comment]
Please, set the secs to 2 and check my last comment within the issue, probably you would add more changes to this PR

P.S. ChromieCraft is very helpful to spot these forgotten issues 👍

**Comment by FrancescoBorzi** [comment]
@Yehonal done

**Comment by wizzymore** [comment]
Confirm it is working fine now.

**Comment by FrancescoBorzi** [comment]
thanks @wizzymore for your feedback!

**Pull request merged**
