### PR TITLE
fix(Core/Movement): Improved pet's follow movement.

### LINKED ISSUE #9254: Pets ignore ground's collision on climbing up
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2355

when running up hills in barrens, the hunter pet clips the ground and runs underneath the world 
hunter pet under world

Tester:

The issue is confirmed. Pets ignore ground's collision on climbing up.
1. Running in places where player can not climbing
2. In places where player can climbig they still moving under textures
3. If under hill a cave pet could even drop down to it and agro someone

https://user-images.githubusercontent.com/85256266/142668954-5d6138cd-77aa-401c-b569-7806011845fe.mp4

### Expected Blizzlike Behaviour

Pets should stay above the ground

### Source

_No response_

### Steps to reproduce the problem

.go c 14097
.pet create
climb up

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/00dc369cb627d728c520cd597b31e9edf2c75eed

### Operating system

Ubuntu 20.04
Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #9254

## Issues Addressed:

- Closes #9254
- Closes https://github.com/chromiecraft/chromiecraft/issues/2355

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/9254), [here](https://github.com/chromiecraft/chromiecraft/issues/2562) and [here](https://github.com/azerothcore/azerothcore-wotlk/issues/9290)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested
image
image

**Comment by pklloveyou** [comment]
wait a minute

**Comment by pklloveyou** [comment]
image
It floats in the air during transportation

**Comment by UltraNix** [comment]
And without this PR?

**Comment by pklloveyou** [comment]
There is no such phenomenon before pr

**Comment by pklloveyou** [comment]
image

**Comment by UltraNix** [comment]
Can you tested without PR?

**Comment by pklloveyou** [comment]
This is before primage

**Comment by pklloveyou** [comment]
image

**Comment by UltraNix** [comment]
Okay.

**Comment by pklloveyou** [comment]
I have an idea

**Comment by pklloveyou** [comment]
image

**Comment by UltraNix** [comment]
No. Too expensive.

**Comment by pklloveyou** [comment]
Yes, I just tried

**Comment by UltraNix** [comment]
@pklloveyou Just tested on the newest rev with new maps/vmaps/mmaps and see no problems on transports. Please, retest it.

**Comment by pklloveyou** [comment]
pull/10963 Is this one?

**Comment by UltraNix** [comment]
I just pulled the newest rev, with not additional PRs. Andt hen extracted new maps, vmaps and mmaps.

**Comment by pklloveyou** [comment]
image
Is that the same with you?

**Comment by UltraNix** [comment]
Yes.

**Comment by pklloveyou** [comment]
ok TESTED

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
