### PR TITLE
fix(DB/Creature) Add CTM to 4 flying creatures

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  ~~Adds creature_template_movement entries to Gahz'ranka (15114) and Zulian Crocolisk (15043) from ZG.~~
-  Adds CTM to Outlands flying creatures 15242, 18707, 224411 so that they won't fall to the ground.
-  Adds CTM to Hinterlands creature 8276 so that they fly properly.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12183
- Closes https://github.com/chromiecraft/chromiecraft/issues/3662
- Closes part of https://github.com/azerothcore/azerothcore-wotlk/issues/11814 as it still needs sniffs for the waypoints.

## Tests Performed:

- Tested ingame
- 

## How to Test the Changes:

1. `.go c id 15242`, `.go c id 18707`, `.go c id 22441` `.go c id 8276`
2.  See if all creatures fly properly and don't fall to the ground. Note: Teribus still needs waypoints, so he'll be static.
3. ~~`.additem 19975 5` `.additem 19974` `.go xyz -11695 -1770 13 309`~~
4. ~~Use lure to summon Gahz'ranka if needed. Crocolisks are nearby. I don't really know how you'd test these two since we don't have the water Evade issues much anymore.~~

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I only noticed that 8276 didn't have a CTM after seeing that issue. I updated this PR to include it so there won't be too many PRs open. If that's not the preferred method of creating PRs please let me know.

**Comment by Maelthyrr** [comment]
Work but ghaz'ranka got ugly movements whe you are near the land. For me, it's better without the flag swim (even he should have it). Test without and said me what do you think.

**Comment by Gultask** [comment]
I double-checked the behavious with and without CTM and to be honest I don't see any difference, which is what I was expecting. I just added Gahz'ranka there because I noticed that it lacked a CTM entry along with the crocolisks. If anyone thinks it's not needed I can remove Gahz'ranka from the query/file no problem. The ID is 15114.

Without CTM

https://user-images.githubusercontent.com/100873791/175818549-94a830fd-592b-48ec-8c93-a3b75b4c0cad.mp4

With CTM

https://user-images.githubusercontent.com/100873791/175818553-ea5b4052-de14-48c2-b6f2-6ba9da3e3ecf.mp4

**Comment by acidmanifesto** [comment]
what happens if you add 32768 (canswim) to the unitflag ontop of the current ctm adjustment? @Gultask

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
add 32768 to the unitflags and cahnge swim ctm to 0 and tell me if the results are better

**Comment by Gultask** [comment]
I'll try that but I'll only have access to my local on friday. Thanks for the suggestion!

**Comment by Gultask** [comment]
Ok. Now I've tried the 32768 flag with and without CTM and I couldn't see any change to the movement/pathing. There is still that weird behaviour as seen in the first video at 30s in happens, where Ol' Ranka will move all the way that specific position to be able to swim along the surface of the water. Otherwise it only stays at the bottom.

If you want me to I can record it easily. I've already got a character saved at Pagle's Pointe.

**Comment by Maelthyrr** [comment]
I will  do a record this night of what I've find. Sorry actually, there are a lot of PR, and I'm busy with my work during the week ^^

**Comment by Gultask** [comment]
No need to be sorry ^^

But I'm curious to see if you get  different results, because it might be the case. The most striking part of the pathing is the one seen in these videos, where Gahz'ranka will go all the way back to that cliff to be able to swim along the surface, which is present in all cases.

`.additem 19975 5` `.additem 19974` `.go xyz -11695 -1770 13 309` `.save`

<details>
 <summary>No CTM No Unitflags</summary>


https://user-images.githubusercontent.com/100873791/176830554-7a2c602a-6289-42f8-a299-f1d4328e91e2.mp4


</details>

<details>
 <summary>No CTM With Unitflag</summary>


https://user-images.githubusercontent.com/100873791/176830595-befbb404-c1af-445a-b1cb-1463af72ba9e.mp4


</details>

<details>
 <summary>With CTM No Unitflag</summary>


https://user-images.githubusercontent.com/100873791/176830628-fed8d1e6-3cde-4de2-b47f-272570f5103f.mp4


</details>

<details>
 <summary>With CTM With Unitflag</summary>


https://user-images.githubusercontent.com/100873791/176830678-9786e644-e05e-46d0-95be-e8b1edc75d6d.mp4


</details>

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Gultask is this PR considered a current improvement and completed compared to what is currently active on Azerothcore?

**Comment by Gultask** [comment]
For Gahz'ranka and the Zulian Crocolisk? No. I don't think it changes anything. For those I just set the ground and swim to 1.
For the others yes, because they currently don't fly.

Should I remove both Gahz'ranka and the Crocolisk from the PR?

**Comment by acidmanifesto** [comment]
I recommend removing only those that are a improvement.

**Comment by Gultask** [comment]
Done 👍 
Query runs fine for me.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
