### PR TITLE
fix(DB/Item): Make Araj's Phylactery Shard lootable by all

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  make it lootable by all

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4403

## Tests Performed:
- None

## How to Test the Changes:

Do https://classic.wowhead.com/quest=211/alas-andorhal in a group
Loot the item

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
This doesn't change anything - the item in question already has `Flags: 2048`.

**Comment by Kitzunu** [comment]
Then it should be lootable by all already

**Comment by Kitzunu** [comment]
2048 | 0x0800 | Item is party loot and can be looted by all
-- | -- | --

**Comment by Zoidwaffle** [comment]
The issue isn't that the shard can't be looted by anyone in the party - the issue is that the chest that contains the shard, goes away after the first one loots it. If that makes sense.

I can't recall other quests like this, except the other one also involving Araj here... I can't find the way the chest spawns - if it's some spell triggered by the death of Araj or something - so it can get fixed there? Araj himself drops completely ordinary expected loot and his "corpse" doesn't despawn as expected from a dead elite creature.

**Comment by Kitzunu** [comment]
Ah ok, now I get you

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
Summoned by this spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=18661

**Comment by Zoidwaffle** [comment]
OK, so... It seems like it is triggered by a spell:

```
> SELECT * FROM `smart_scripts` WHERE `entryorguid`=1852 AND `id`=3\G
*************************** 1. row ***************************
     entryorguid: 1852
              id: 3
      event_type: 6
    event_chance: 100
     event_flags: 1
     action_type: 11
   action_param1: 18661
   action_param2: 7
     target_type: 1
         comment: Araj the Summoner - On Just Died - Cast 'Araj's Phylactery' (No Repeat)
```

I removed everything being "0" in the output above.

**Comment by Kitzunu** [comment]
@Zoidwaffle just for testing, change action_param2 to 6

**Comment by Zoidwaffle** [comment]
`UPDATE smart_scripts SET event_param2=6 WHERE entryorguid=1852 AND id=3;`

No difference.

But it's pretty weird - if you do have the shard in your inventory already (and you have the quest), the "chest" shows you can loot it... but it has 0 content (as expected, since you already has the quest item), but the chest still despawns afterwards.

**Comment by Kitzunu** [comment]
Okay last thing that I could think of is 
```sql
UPDATE `gameobject_template` SET `Data15` = 1 WHERE `entry` = 177241;
```
After this I am out of suggestions :shrug:

**Comment by Zoidwaffle** [comment]
No difference.

Thanks for the effort :+1:

**Pull request closed without merging**
