### PR TITLE
fix(Scripts/Temple of AhnQiraj): Fixed Sartura's aggro reset mechanic.

### LINKED ISSUE #13072: [AQ40] Battleguard Sartura - Boss and adds should reset aggro while Whirlwind aura is up.
### Current Behaviour

Aggro reset happens on a timer separate from Whirlwind.

### Expected Blizzlike Behaviour

The boss should:

- Reset aggro at the same time when Whirlwind (26083) is cast.
- Reset aggro every 1.2-7.5s while whirlwinding (7.5 taken from mangos. Exact max timer is unknown to me)
- Reset aggro after Whirlwind fades.

Adds follow the same behaviour with their own Whirlwind (26038)

### Source

Retail and https://youtu.be/JHOGWVd7OjQ

### Steps to reproduce the problem

1. `.go c id 15516`
2. engage the boss and monitor aggro changes

### Extra Notes

In retail, the boss also adds 100000 threat to a random player whenever she resets aggro, but that behaviour is not seen in WotLK videos.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d5f839a4be933f944c0df46c233066e37966c263

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #13072

## Issues Addressed:

- Closes #13072

## Tests Performed:

- Not tested. 

## How to Test the Changes:

.go c id 15516 with at least 2 chars
engage the boss and monitor aggro changes

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by Gultask** [comment]
Here you can see some examples of how she resets aggro while Whirlwinding: https://youtu.be/sF-osaK31DE?t=57

**Comment by UltraNix** [comment]
It's classic. I watched many videos from wotlk era and every single was something different :P

**Comment by Gultask** [comment]
hehe. True

Here you can just barely see a threat meter in the top of the screen. I'll see if I can find some more and update this comment.
https://youtu.be/kwlCOViQimA?t=101

**Comment by UltraNix** [comment]
For me it's not a "classic threat reset", but it's a fixate mechanic.

**Comment by Gultask** [comment]
The shaman video has pets helping the player, so they count: https://youtu.be/JHCn4qvQ8p4?t=55
There it's not adding any threat, only removing it.

**Comment by UltraNix** [comment]
https://www.youtube.com/watch?v=jZvGaODEidI
https://www.youtube.com/watch?v=uZCT_T5tQ68
These are not era videos, but definetely not classic videos. You can clearly see threat there.

**Comment by Gultask** [comment]
I don't understand, then. In WotLK footage there's clearly threat being wiped. Was it a later change or possibly an issue with the KTM addon?

Well since it's not immune to threat then mechanically a gaze vs threat wipe wouldn't make much of a difference, strategically-speaking.

**Comment by UltraNix** [comment]
Yep. I will leave it as it is now - gaze mechanic.

**Comment by Gultask** [comment]
Using 2 characters I always saw the same behaviour:

It would *always* switch its target on the start of Whirlwind.
It would never change targets for the duration of the Whirlwind.

Using 3 characters:

It can target either 'DPS' at the start of Whirlwind
It can switch targets during Whirlwind.

So the main tank is being ignored.

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Gultask** [comment]
Seems to work for me 👍

**Comment by Nefertumm** [comment]
fixed conflicts but now whirlwind variable doesn't exist

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
