### PR TITLE
fix(DB/SAI): Ring of Blood creature despawn

### LINKED ISSUE #1890: [Quest] The Ring of Blood
**_Problem_**

- _Once you start any quest, NPC's appear as supposed._
- _But, if you decide to abandon quest and take it again, new set will be spawned, and this can be used as much as you wanna which can, at the end, crash server due to number of them._
- _**Problem is with every quest that you can take in Arena.**_

**_Expetations_**

- _Once player leave combat or arena it self, NPC's should despawn._
- _If quest is abandoned, NPC's should despawn as well._

**_How to_**

- _Create character and level up your self to 80._
- _Modify your health cause NPC's hit hard._
- _.tele Nagrand (Move to Arena)_
- _Talk with Gurgthock and start quest._
- _Abandon once they spawn and take quest again._

**_Commit: Up to date / Latest._**

WoWScrnShot_052619_175336

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74666373-quest-the-ring-of-blood?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Despawn the creatures which are summoned during the "Ring of Blood" quest chain if they are 10 seconds out of combat.

###### ISSUES ADDRESSED:
Closes #1890 https://github.com/azerothcore/azerothcore-wotlk/issues/1856

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- preparation:
```
.quest remove 9962
.quest remove 9967
.quest remove 9970
.quest remove 9972
.quest remove 9973
.quest remove 9977
.go -727.81 7929.77 58.001 530
```
- play through the quest chain
- try to not fight at all or flee from combat, the creatures should despawn after being out of combat for 10 seconds

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Selyria** [comment]
Do you get it somehow hin that Mogor after you killed in the first time has to get up again. Currently he remains dead after the first time kill

**Comment by Stoabrogga** [comment]
@Selyria 
He will respawn as all Elite NPCs do: 5 minutes until his corpse vanishes, another 5 minutes until he respawns.

**Comment by Selyria** [comment]
> @Selyria
> He will respawn as all Elite NPCs do: 5 minutes until his corpse vanishes, another 5 minutes until he respawns.

No, I meant maybe you could fix his bug.

The boss Mogor dies but he is a shaman and can revive himself once. 

Man must kill him onm offi 2 times because he can resurrect himself see video.

**Comment by Stoabrogga** [comment]
@Selyria 
Ok, thanks for pointing this out and sorry for the misunderstanding. I can look into this, but will create a new PR to keep it separated from the issue addressed in this PR.

**Pull request merged**
