### PR TITLE
fix(Docker): Git version resolution in docker build

### PR DESCRIPTION
**Pull request by michaeldelago**
## Changes Proposed:
- Add lines to `apps/docker/Dockerfile` so that the docker build can properly get version information from git

## Issues Addressed:

- The `ac-dev-server` doesn't properly pull the git versioning information during the build step
    - This is due to the `var` directory being in a separate mount as well as ownership for the `/azerothcore` directory
    - This is easily resolved with an extra env var and `RUN` step in `apps/docker/Dockerfile`

## SOURCE:

- Issue reported in discord in the #docker-support 

## Tests Performed:

- The easiest way is to check the `var/build/obj/revision.h` file after executing `./acore.sh compiler configure`

## How to Test the Changes:

1. Checkout master (`git checkout master`)
2. View the revision.h file that gets created by master:

```console
docker compose -f docker-compose.yml run --build ac-dev-server \
  bash -c "./acore.sh compiler clean;
           ./acore.sh compiler configure;
           cat var/build/obj/revision.h"
```

3. You'll see that the `_HASH` and `_BRANCH` are the default/unknown values
4. go to this branch (`git checkout cmake-git-version`)
5. Run the same command as step 2, and check the output
6. You'll see that the `_HASH` and `_BRANCH` are properly set

## Known Issues and TODO List:
- none that I know of

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
did you test it @michaeldelago ? if so we can merge

**Comment by michaeldelago** [comment]
Oops, sorry I forgot to test/missed the reminder.

Should have this by this weekend

**Comment by michaeldelago** [comment]
Confirmed that this builds and the proper git version is set in the logs:

```console
WORLD: World Initialized In 0 Minutes 10 Seconds
AzerothCore rev. f1b8e5a91c44+ 2023-08-12 11:14:32 -0400 (cmake-git-version branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
```

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Thank you

**Pull request merged**
