### PR TITLE
fix(DB/Instances): Dark Keeper Portrait should summon only one boss.

### LINKED ISSUE #9255: BRD's Dark Keeper Portrait allow to summon several NPCs
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2232

Dark Keeper Pelver spawns double.
Screenshot from 2021-11-01 21-16-12

Tester:

The issue is confirmed. Clicking on [Dark Keeper Portrait](https://wowgaming.altervista.org/aowow/?object=164819) `43130 (Entry: 164819)` multiple times allow you to summon several keepers at the same time.

WoWScrnShot_112021_000352

https://user-images.githubusercontent.com/85256266/142693090-3e5053fd-a277-4d03-8836-b6c58d2fffee.mp4

### Expected Blizzlike Behaviour

Should be summoned only one NPC

### Source

X

### Steps to reproduce the problem

.go ga 43130
click, click, click
check out name plate several times

### Extra Notes

If several players will do it - it will create even more NPCs. Need also anti several players fix.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #9255

## Issues Addressed:

- Closes #9255
- Closes https://github.com/chromiecraft/chromiecraft/issues/2232

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.go ga 43130
click, click, click
check out name plate several times

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by temperrr** [comment]
I can't replicate the issue without the PR?

**Comment by UltraNix** [comment]
@temperrr You must click (and spam it) very fast (without PR)

**Comment by temperrr** [comment]
> @temperrr You must click (and spam it) very fast (without PR)

I see, I can't do that with my hands nor have a spam clicker installed. Maybe someone else can do it ;p

**Comment by Voxstrasza** [comment]
Video of my test: https://youtu.be/DuTFzh_OrrM

Off camera, I used an auto hotkey script to spam click the name plate - no double spawn of any NPC.

**Pull request merged**
