### PR TITLE
feat(Battlegrounds): make it compatible with custom arena type

### PR DESCRIPTION
**Pull request by Helias**
## Changes Proposed:

This PR proposes changes to:
-  make different checks ONLY for standard arena type

## Issues Addressed:
- incompatibility with [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)

## Tests Performed:
This PR has been:
- [ ] Tested in-game by the author ONLY using the module (so far)

## How to Test the Changes:

- test the standard arenas

## Known Issues and TODO List:
- [ ] we should make more tests with standard arenas

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by laasker** [comment]
The changes in BattlegroundQueue.cpp causes BG queues to not work

**Comment by Helias** [comment]
> The changes in BattlegroundQueue.cpp causes BG queues to not work

please, check now if this has been solved with the last commit

**Comment by laasker** [comment]
I tested pretty quickly but yea it works, now BG queues pops, normal 2v2/3v3/5v5 queue pops and Solo 3v3 (module) queue pops only when there are 6 people on the queue.

Also can you take a look at my last comment in https://github.com/azerothcore/mod-arena-3v3-solo-queue/issues/8 ?

**Comment by 29Hido** [comment]
Just tested it, seems like this changes are breaking https://github.com/azerothcore/mod-1v1-arena

**Comment by pangolp** [comment]
We cannot take the 1vs1 arena module as a reference, because we had to do many things to that module that shouldn't be there, due to other changes in the emulator. If these changes cause errors in the 1v1 arena module, then a pull request is opened within the module. But that doesn't mean we're going to stop making these changes, which may be important for other modules.

**Review by Nyeriah — APPROVED** [review]

**Comment by Helias** [comment]
I've merged it because I've tested it a lot

**Pull request merged**
