### PR TITLE
Core/SmartScripts: Use BroadCastText instead of trinity_string

### PR DESCRIPTION
**Pull request by HoustonCore**
## CHANGES PROPOSED:
-  Use BroadCastText instead of trinity_string in SMART_ACTION_FLEE_FOR_ASSIST and SMART_ACTION_CALL_FOR_HELP

## TESTS PERFORMED:
- Build and test

## HOW TO TEST THE CHANGES:

- Go to Strange Vilage
- Go to fight Mobs, when he has low hp, he run and speak in chat help me(text in you locale) .

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
Why?

**Comment by HoustonCore** [comment]
> Why?

Because there is no translation of acore_string for all languages. And this is the best option.

**Comment by Kitzunu** [comment]
So we add translation?

**Comment by HoustonCore** [comment]
> So we add translation?

It is already in the broadcast_text_locale table))

**Comment by Kitzunu** [comment]
ah

**Review by Kitzunu — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@HoustonCore thanks for your contribution, can you please add instructions to your PR about how to test it?

For example, I guess in this case it's a matter of trying to trigger some `CALL_FOR_HELP` and `FLEE_FOR_ASSIST`

**Comment by HoustonCore** [comment]
> @HoustonCore thanks for your contribution, can you please add instructions to your PR about how to test it?
> 
> For example, I guess in this case it's a matter of trying to trigger some `CALL_FOR_HELP` and `FLEE_FOR_ASSIST`

I get it, I'll add a description for testing a little later, I'm at work)

**Comment by HoustonCore** [comment]
@FrancescoBorzi done.

**Comment by Racknar0** [comment]
Where is Strange Vilage?

**Comment by LukasVolgger** [comment]
Can't test because of conflicts

**Comment by Kitzunu** [comment]
Youll have tp remake the pr since the fork was deleted

**Comment by HoustonCore** [comment]
If you want open new PR.

**Comment by LukasVolgger** [comment]
Sadly, i'm not a core dev... Too bad, would be nice to have

**Pull request closed without merging**
