### PR TITLE
fix(Core/Spells): Properly handle SPELLMOD_COOLDOWN for spell categor…

### LINKED ISSUE #8155: Spell Cooldown Modifier did not work after
### Current Behaviour

apply https://github.com/azerothcore/azerothcore-wotlk/pull/7878

After this commit,Talent Spell Modifier and Glyph did not work!
Just like Improved Judgements(spell id :25957)
cast `Judgement of Light` and then cast `Judgement of Wisdom` should be 8s but now still 10s
Please check again

### Expected Blizzlike Behaviour

Cooldown modifier should work

### Source

_No response_

### Steps to reproduce the problem

1.cast `Judgement of Light` (20271) 
2.wait for the cooldown before casting `Judgement of Wisdom`(53408)
3.you must wait 2 seconds to cast successfully

### Extra Notes

https://github.com/azerothcore/azerothcore-wotlk/issues/7877

### AC rev. hash/commit

26f1aaa0c888bb052f06d68d43d23a785ee6b39c

### Operating system

ubuntu 20.04

### Custom changes or Modules

none

### PR DESCRIPTION
**Pull request by ghost**
…y cooldowns.

Fixes #8155

## Issues Addressed:

- Closes #8155

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. cast Judgement of Light (20271)
2.wait for the cooldown before casting Judgement of Wisdom(53408)
3.you can cast it immediately 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
tested.. work.

**Review by mpfans — APPROVED** [review]
work

**Review by bgcfb — APPROVED** [review]

**Comment by bgcfb** [comment]
tested and work.

**Review by Kitzunu — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks a lot @mpfans and @bgcfb for testing this

**Pull request merged**
