### PR TITLE
fix(Core/GameEvents): Attempt to fix holiday game events endind to ea…

### LINKED ISSUE #6345: Darkmoon Faire - Incorrect Finishing Date
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/858

On June 11h daily server restart at 5:30 server time, the DMF left Elwynn Forest when it was supposed to be in town until June 12th, 23:59.
I asked about it on discord but since no one answered, I did not know if it was worth a report.

Tester's notes: Messed about with my server clock and confirmed that the DMF will run until midnight 10th/11th of June, disappearing on the first server restart after that. Also set the clock back to just before the DMF is supposed to start on Sunday 6/6 at 12:01 AM , and found that it was starting at the correct time. 

Screenshot showing calendar claiming it is active, while the actual DMF site is empty. Current server date when this was taken was 11/6.
WoWScrnShot_061421_141451

Checking game_event table:
```
SELECT * from game_event WHERE evententry = 4;
```
```
+------------+---------------------+---------------------+-----------+--------+---------+--------------+--------------------------------+-------------+----------+
| eventEntry | start_time          | end_time            | occurence | length | holiday | holidayStage | description                    | world_event | announce |
+------------+---------------------+---------------------+-----------+--------+---------+--------------+--------------------------------+-------------+----------+
|          4 | 2014-09-07 08:31:00 | 2030-12-31 15:30:00 |    131040 |  10079 |     374 |            2 | Darkmoon Faire (Elwynn Forest) |           0 |        2 |
+------------+---------------------+---------------------+-----------+--------+---------+--------------+--------------------------------+-------------+----------+
```
Occurrence is minutes between event starts - 131040 minutes = 91 days.
Length is 10079 = 7 days less 1 minute.
Holiday is client side holiday ID - linked to holidays.dbc.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Accordng to Wowpedia, the DMF starts at 12:01 a.m. on the Sunday before the 1st Monday of each month and runs for a week. Thus it should end at 11:59 PM on Saturday the 12th.

Darkmoon Faire should be present according to the ingame calendar.

##### SOURCE:

https://wowpedia.fandom.com/wiki/Darkmoon_Faire_(Classic)?oldid=2411748

##### STEPS TO REPRODUCE THE PROBLEM:

1. Change server clock to some time after 12:01 AM on the 11th and before 11:59 PM on the 12th, when the DMF should be going, and start the server. Then visit Goldshire in Elwynn Forest (the DMF is a bit south of it) and note it's not there.

##### EXTRA NOTES:

Also note that TC are having the same problem: https://github.com/TrinityCore/TrinityCore/issues/25550

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/d0a52896283a9bfed36ca897f0c2ebe870a25800

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99233609-darkmoon-faire-incorrect-finishing-date?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…rly. Author:  sirikfoll

Fixes #6345

## Changes Proposed:
-  Ported from https://github.com/TrinityCore/TrinityCore/issues/25550#issuecomment-881110808
-  

## Issues Addressed:

- Closes #6345
- Closes https://github.com/chromiecraft/chromiecraft/issues/858

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Change server clock to some time after 12:01 AM on the 11th and before 11:59 PM on the 12th, when the DMF should be going, and start the server. Then visit Goldshire in Elwynn Forest (the DMF is a bit south of it) and note it's not there.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
The duration of the event was extended, but it was extended too much. After the end time of the event, the event continued

**Comment by FrancescoBorzi** [comment]
> The duration of the event was extended, but it was extended too much. After the end time of the event, the event continued

so does this require further changes?

**Comment by pklloveyou** [comment]
The end time is too long

**Comment by FrancescoBorzi** [comment]
@UltraNix what's the status of this PR?

**Comment by UltraNix** [comment]
Inactive at the moment.

**Pull request closed without merging**
