### PR TITLE
fix(scripts/TempleOfAhnQiraj): Improve Sartura

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Rewrite [Battleguard Sartura](https://classic.wowhead.com/npc=15516/battleguard-sartura) and her 3 [Sartura's Royal Guard](https://classic.wowhead.com/npc=15984/sarturas-royal-guard)

## Comments:
- It's not my cleanest work but here you go, mechanics/timers/spells/adds/resets - all completed.
- I used SpellHit on both scripts only because `spell_linked_spell` makes the boss and her 3 adds to also get the debuff even without being hit by the source spell.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Tested and I don't find big issue related to this PR.

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Overall is okay, for temp threat drop mechanic you could use Creature::ModifyThreatPercentTemp, which was implemented a time ago by Nyeriah

**Comment by Si1ker** [comment]
> Overall is okay, for the temp threat drop mechanic you could use Creature::ModifyThreatPercentTemp, which was implemented a time ago by Nyeriah

try to use it and you'll see why I didn't

**Comment by Nefertumm** [comment]
??

**Comment by Si1ker** [comment]
> ?? Chill out.

😕 ❓  idk what u mean tbh..
there's an error, that's it.

**Comment by Si1ker** [comment]
🤔

**Comment by acidmanifesto** [comment]
> 🤔

**Comment by Nefertumm** [comment]
Could you update your branch? It seems like something odd is happening with GitHub, showing things that it shouldn't, let's see if that works.

**Comment by Si1ker** [comment]
@Nefertumm done.

**Pull request merged**
