### PR TITLE
refactor(Core/TempleOfAhnQiraj): Bug trio

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Codestyle.
-  Change the way to get each boss object
-  Don't let bosses dying auto attack.
-  Remove player damage req whenever they heal.
-  Do their final spell after actually dying and not before.
-  Trying to fix an odd case of they dying with all of them dropping loot and not doing their final spell.
-  Fix timers according to sniffs

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4087

## Tests Performed:

- Not tested.

## How to Test the Changes:

1. Engage bug trio, only one of them should drop loot, the dying creature should not auto attack.

### CODE REVIEW

**Comment by Nefertumm** [comment]
I'm going to rewrite the death part to see if I can find a better solution

**Comment by Gultask** [comment]
I thought it would be better to comment here instead of opening another issue. Some issues were raised about the Thrash timers. So I thought it'd be good to review the timers in their entirety.

In my experience, first cast timers do not differ much from the repeat timers.

**Lord Kri:**

**Cleave (40504)**
Queued every 7s, 18s

**Toxic Volley (25812)**
Cast every 8s, 17s

**Thrash (3391)**
Cast every 7s, 16s

**Vem:**

**Knockdown (19128)**
50% 10s, 13s
50% 13s, 23s

**Berserker Charge (26561)**
15s, 27s

**Knock Away (18670)**
10s, 24s

**Princess Yauj:**

**Ravage (3242)**
50% 10.9s
40% 12.1s
10% 14.5s
If cast fails requeues in 1.2s

**Greater Heal (25807)**
Cooldown of 12.1s

**Fear (26580)**
First cast at 12.1s
Other casts at 20.6s

**Comment by Gultask** [comment]
While any of the Trio are eating, they can turn to face the player, which shouldn't be the case.
Also, they can still hit players while eating: https://github.com/chromiecraft/chromiecraft/issues/4088

I got this error sometimes but I don't know how to reproduce it.
`DoResetThreat called for creature that either cannot have threat list or has empty threat list (me entry = 15511)`

Other than that I can't reproduce getting loot to drop for every one of them anymore. Will fix: https://github.com/chromiecraft/chromiecraft/issues/4087

**Comment by Nefertumm** [comment]
Test again please

**Comment by Gultask** [comment]
Build Failed

image
image
image
image

**Comment by Nefertumm** [comment]
my branch is bugged... Superseded by https://github.com/azerothcore/azerothcore-wotlk/pull/13141

**Pull request closed without merging**
