### PR TITLE
feat(Core/Players): Enabled resurrecting players from opposite factio…

### LINKED ISSUE #8600: Can't resurrect opposite faction when already released
### Current Behaviour

You can't resurrect a player from the opposite faction, if he/she already clicked on "release spirit". It works fine for the same faction. This is a known bug on Chromiecraft, but I couldn't find a bug report for it on AC.
I tested it on the latest master branch, and the issue still persists.
I'm not sure if that is only an issue with the dungeon finder, but I believe it's a general issue.

### Expected Blizzlike Behaviour

We should be able to resurrect each other in a crossfaction group.

### Source

_No response_

### Steps to reproduce the problem

1. be in a group with the opposite faction
2. try to resurrect a player from the opposing faction after he already released.
3. See that you can't

### Extra Notes

_No response_

### AC rev. hash/commit

67ebf7b0923caa986ff4b154

### Operating system

Win 10 x64

### Custom changes or Modules

All crossfaction options enabled in the worldserver config.

### PR DESCRIPTION
**Pull request by UltraNix**
…n in crossfactioned raids.

Fixes #8600

## Issues Addressed:

- Closes #8600
- Closes https://github.com/chromiecraft/chromiecraft/issues/1206

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

be in a group with the opposite faction
try to resurrect a player from the opposing faction after he already released.
See that you can resurrect

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Maelthyrr** [comment]
I'm unable to reproduce this.

Test done:
- 2 char (on human, one blood elf)
- one char die (.die)
- try to  use res paladin spell (before and after release)

WoWScrnShot_061222_173300

WoWScrnShot_061222_173441

**Comment by Gultask** [comment]
I had the same result, selecting the portrait and casting the ress spells don't work, neither does clicking the ress spells and hovering over the body, as it won't 'highlight' the corpse and the mouse won't change to the blue icon indicating that the body is a valid target.

**Comment by UltraNix** [comment]
1. Must be in the same party
2. Must be hostile
3. `CONFIG_ALLOW_TWO_SIDE_INTERACTION_GROUP` is set to 1

**Comment by temperrr** [comment]
image
We are in a group
image

**Comment by UltraNix** [comment]
@temperrr @Gultask Should be okay.

**Comment by acidmanifesto** [comment]
@azerothcore/testers this needs to be tested.

**Comment by Gultask** [comment]
It works but there are some bizarre texture glitches when one dies while both are in a group.

WoWScrnShot_061822_110621
 
WoWScrnShot_061822_110744

When both are not in a group, then the insignia icon shows up when hovering over their bodies, which I don't think should be the case? Clicking it does nothing
Sorry for the phone image:
image

**Comment by UltraNix** [comment]
About the the insignia - it's okay.
About glitches - yeah. It's impossible to do it in other way- otherwise client crashes.

**Comment by acidmanifesto** [comment]
> About glitches - yeah. It's impossible to do it in other way- otherwise client crashes.
Can concur and validate that, this was a internal discussion the other day.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
