### PR TITLE
fix(Core/Spells): Fixed LoS problems with hunter traps.

### LINKED ISSUE #12332: Hunter traps have trigger issues
### Current Behaviour

The trigger of the hunter trap is not normal, sometimes it can trigger, sometimes it can't trigger

### Expected Blizzlike Behaviour

Hunter Trap can be triggered by monsters in any situation

### Source

[https://youtu.be/DPM1iHSu_oo](url) 
Here is the demo video

### Steps to reproduce the problem

Find monsters and place more traps, sometimes the traps will not trigger

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. ff3e53ec0e95 2022-07-09 01:36:37 +0800 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 80029
Using CMake version: 3.22.1
Compiled on: Windows 10.0.19043
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in data/maps. Total size: 291014951 bytes
vmaps directory located in data/vmaps. Total size: 658130721 bytes
mmaps directory located in data/mmaps. Total size: 2320900676 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-autobalance
- mod-cfbg
- mod-eluna
- mod-npc-buffer
- mod-npc-free-professions
- mod-solo-lfg
- mod-transmog

### Operating system

windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
## Issues Addressed:

- Closes #12332
- Closes https://github.com/chromiecraft/chromiecraft/issues/3749

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](#12332)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Tested and it works 👍

**Comment by WORISX** [comment]
Tested and working perfectly.

**Comment by q67732897** [comment]
THX 👍👍👍

**Review by acidmanifesto — APPROVED** [review]
5th times the charm right? Let see how long this last before it regresses again.

**Comment by mpfans** [comment]
Please merge this PR first

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
