### PR TITLE
Core/Instances: Finally fix instance_reset

### LINKED ISSUE #966: Either Heroic instances aren't resetting when they should, or the calendar is not displaying reset dates correctly
**Description**: As an example, this morning I had several Heroic 5-man instance locks scheduled to expire, according to my calendar, at 4:59 AM. I logged in at 6 AM only to find that the reset time had extended to (time of log in). This happens every time I log in and out or restart the server -- the time just keeps extending infinitely. The only way I can reset my Heroic instance locks is to use the GM command.

I have been digging around in the source quite a bit, and if I clear the tables myself it does seem to clear the instance locks, however the `instance_reset` table continuously resets itself -- not sure if that behavior is intended but it seems like in the current scenario, instance locks will just keep expiring forever.

I am a professional software engineer (but not a professional QA! lol), so if you would like to point me in the direction of where I might be able to fix this I would be willing to give it a go in my free time.

**Current behaviour**: When logging in, Heroic instance locks seem to extend to the time at which I logged in. They never actually expire. This happens regardless of whether the server is down or up when the instance locks should be expiring. If they do expire, it's not displayed on the calendar.

**Expected behaviour**: When Heroic instance locks reach their time of expiry, those instances should expire.

**Steps to reproduce the problem**:

1. Get yourself locked to a Heroic instance
2. Wait until the time displayed on your calendar (or cheat and set your server's time to some time after that value)
3. Log in to the game
4. Heroic instance expiry times have updated to the time at which you just logged in (for example, this morning for me they had all updated to 6:01 AM, although I have been testing this and playing around with it for several days now).

**Branch(es)**: master

**AC hash/commit**:  Still happening in c15444a18e9ddd6b297acbbbff2e51d1782a96d7

**Operating system**:  Windows 10

**Modules**:  Only azerothcore/mod-vas-autobalance

**Other Customizations**: None

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60508298-either-heroic-instances-aren-t-resetting-when-they-should-or-the-calendar-is-not-displaying-reset-dates-correctly?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Nefertumm**
##### CHANGES PROPOSED:

-  Change the if condition.
-  

###### ISSUES ADDRESSED:

Hopefully Closes #966

##### TESTS PERFORMED:

Compiled, debugged and it worked. 

##### HOW TO TEST THE CHANGES:

Just play with instances.

##### KNOWN ISSUES AND TODO LIST:

- [ A lot of test. ]

##### Target branch(es):

Master

### CODE REVIEW

**Comment by poszer** [comment]
Something isn't fine here. I tryed this PR, and now i'm not able to login in game ( Stucked on Retrieving Character list )
**========== Build: 2 succeeded, 0 failed, 13 up-to-date**
https://image.prntscr.com/image/FOLvP5CRR3O5kv4k9c7XVw.png
And in worldserver it says that i'm online 
https://image.prntscr.com/image/R0tA_j3BSBaM95iVQldt4A.png

**Comment by FrancescoBorzi** [comment]
good job @poszer for spotting this, moving to WIP since it cannot be further tested atm

**Comment by Nefertumm** [comment]
I'll take another look to see what i can find.

**Comment by Nefertumm** [comment]
Try again when you can.

**Comment by poszer** [comment]
Tested, working. Was locked to instance for 3 days ( Checked today, the character doesn't have any locks to instance ). 
The calendar showing the correct time also

**Comment by FrancescoBorzi** [comment]
good job @Nefertumm and @poszer

**Pull request merged**
