### PR TITLE
feat(Core/SmartAI): Implement a few more stuff

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).
- Implement SMART_ACTION_SET_ORIENTATION_TARGET so that it's possible to set a creature's orientation from another source, simplifying scripts and not needing to use SET_DATA
- Implement Smart CastFlag SMARTCAST_TARGET_POWER_MANA to only cast a spell if target has mana
- Refactors a few things
- Modify SMART_EVENT_RANGE to use Initial and Repeat timers, using new parameter field
- Modify SMART_EVENT_IS_BEHIND_TARGET to use Initial and Repeat timers, using new parameter field
- Add aura parameter to HOSTILE_RANDOM target types to better select for targets without an aura
- Increased the delay timer for when spells overlap, so when it happens it has a more blizzlike delay rather than taking top priority. The same is made for CALL_FOR_ASSIST

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4955

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
GOATED title

**Comment by fangshun2004** [comment]
Can I increase the mob to move when casting? For example, when releasing a spell that requires guidance, it is possible to move towards the target

**Comment by Gultask** [comment]
I don't understand the question or the situation specified?
Do you mean like combat movement? Like how casters often stay at a distance when casting spells?

**Comment by fangshun2004** [comment]
> I don't understand the question or the situation specified? Do you mean like combat movement? 

It's about allowing creatures to move and cast spells. And keep the boot strip uninterrupted

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
