### PR TITLE
fix(DB/creature): Adjust Shadowforge Surveyor z-position

### PR DESCRIPTION
**Pull request by Azcobu**
## Changes Proposed:
Bumps Shadowforge Surveyor GUID 7714's z-position up a bit so he doesn't get stuck in the rock object, and instead stands on top of it. I didn't want to change the x/y coords becauses Wowhead shows a Surveyor at that spot. 

Also tested pathing to/from the top of the rock, and he can run off it to attack if needed, and warrs/bears can charge to him, so pathing shouldn't be an issue.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9549
- Closes https://github.com/chromiecraft/chromiecraft/issues/2491

## SOURCE:

Wowhead [Shadowforge Surveyor](https://classic.wowhead.com/npc=4844/shadowforge-surveyor)

## Tests Performed:

- Ran SQL, no errors/warnings, 1 row changed as expected.
- Checked in-game:

WoWScrnShot_120821_001636

## How to Test the Changes:

1. .go c 7714

## Known Issues and TODO List:

N/A.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Is this simular to the lich king issue we have in the dk zone? I did find another way around it without bumping up the z axis. Is this npc stationary the whole time?

**Comment by Azcobu** [comment]
I'm at work so can't go check the LK, but it sounds similar. This NPC is moving around, however it's just the standard random wandering, not a patrol or anything. If you have a way to fix this without messing with coords that does sound preferable though - should I close this PR?

**Comment by acidmanifesto** [comment]
> I'm at work so can't go check the LK, but it sounds similar. This NPC is moving around, however it's just the standard random wandering, not a patrol or anything. If you have a way to fix this without messing with coords that does sound preferable though - should I close this pr open until we have a absolute confirm solution. Ill check it later today.

**Comment by Kitzunu** [comment]
Stop creating branches on the repository.
Make your own fork and make the branches there, to avoid spamming the github bot in discord.

**Comment by Nyeriah** [comment]
@acidmanifesto any news?

**Comment by acidmanifesto** [comment]
> @acidmanifesto any news?

Well the inhabittype removal pr does fix the issue. But right now we are just spot checking and spot fixing a few npcs right now

**Comment by claudiodfc** [comment]
So is this close-able or merge?

**Comment by claudiodfc** [comment]
@FrancescoBorzi Can this be closed?

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi Can this be closed?

I haven't followed this myself. What do you say @Azcobu @Nyeriah @acidmanifesto ?

**Comment by Nyeriah** [comment]
It appears to me that this will be fixed in the upcomming inhabit type PR without requiring DB data changes, so in my honest opinion this request could be closed

**Comment by acidmanifesto** [comment]
Currently this npc is not handled in the inhabit removal pr but adjustments can be made after i do some research on a couple of things.

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/9272

**Pull request closed without merging**
