### PR TITLE
fix(DB/Gameobject): Pumpkin wrong placement

### PR DESCRIPTION
**Pull request by poszer**
Delete wrong spawned gobject

##### CHANGES PROPOSED:

-  Delete
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2056 https://github.com/azerothcore/azerothcore-wotlk/issues/542

##### TESTS PERFORMED:

Wrongly spawned gameobject, doesn't need tot be there.

##### HOW TO TEST THE CHANGES:

1. .go gob 78033

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Instead of just deleting it, why not add it to the appropriate event (Hallow's End)? There are also 3 other GUIDs missing of the same type:
```sql
DELETE FROM `game_event_gameobject` WHERE `guid` IN (78033,78106,78117);
INSERT INTO `game_event_gameobject` (`eventEntry`, `guid`)
VALUES
(12,78033),
(12,78106),
(12,78117);
```

**Comment by poszer** [comment]
> Instead of just deleting it, why not add it to the appropriate event (Hallow's End)? There are also 3 other GUIDs missing of the same type:
> 
> ```sql
> DELETE FROM `game_event_gameobject` WHERE `guid` IN (78033,78106,78117);
> INSERT INTO `game_event_gameobject` (`eventEntry`, `guid`)
> VALUES
> (12,78033),
> (12,78106),
> (12,78117);
> ```

Yeah better solution. Updated , thank you

**Comment by Knindzagxg** [comment]
Checked ingame, all good.

**Comment by Stoabrogga** [comment]
Added a few more Hallow's End game objects that I identified (hanging ghosts, various pumpkins).

**Comment by spinzaku** [comment]
Thank you for this fix

**Pull request merged**
