### PR TITLE
Fix(core/Creature) initialize AI before calling OnCreatureCreate

### PR DESCRIPTION
**Pull request by patou01**
## Changes Proposed:
-  Move OnCreatureCreate call to the end of the AddToWorld(), so that a user gets a creature that is initialized beforehand.
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9088

## SOURCE:

TC has the same (discovered after trying) https://github.com/TrinityCore/TrinityCore/blob/04909bada85d4770a58a5b2b6f2180f5aacb1b81/src/server/game/Entities/Creature/Creature.cpp#L274
Since the code base has diverged, we still need to check that we're not affecting anything else

## Tests Performed:

- Tested on The beast, he seemed to work. Using a win10 x64 build relwithdebinfo.
- 

## How to Test the Changes:

1. First test is to verify it fixes the issue (steps taken from the issue report)
.additem 12709 - skining dagger
.setskill 173 400 - dagger skill if needed
.setskill 393 400 - skinning
.go c id 10430
.cast 10768

2. Try to find where it could fail. I have no clue there, to me this is logical that it's called at the end (similar to the eluna call)
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
> @Nyeriah did you test? :P

Doesn't really need testing

**Comment by acidmanifesto** [comment]
> @Nyeriah did you test? :P

Great job. 👍

**Comment by patou01** [comment]
Would still makes sense, just so we're sure it's not a fluke on my side.

**Comment by Nyeriah** [comment]
> Would still makes sense, just so we're sure it's not a fluke on my side.

This is just a script hook that calls the instance script methods, we are just moving the code from one place to another, so nothing really unexpected can come out of this.

Furthermore, as you mentioned, it's the same logic used by TrinityCore.

Moreover, it's the same logic used by Eluna, that also calls the AddedToWorld() hook after AI has been initialized.

This is a crash fix so getting this merged as soon as possible is in all of our best interests.

**Pull request merged**
