### PR TITLE
fix(Core/Loot): Gold should always be lootable, even if it's the only loot

### LINKED ISSUE #4839: Loot/Skinning issue, Black Dragon Whelps Lev 17
Originally reported https://github.com/chromiecraft/chromiecraft/issues/199

##### ISSUE: FACTION SIDE:

Alliance
Horde

##### CONTENT PHASE:

1-19

##### SMALL DESCRIPTION:

NPC: Black Dragon Whelp https://wowgaming.altervista.org/aowow/?npc=441

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Dead lev 17 whelp should be lootable to enable skinning.

##### CURRENT BEHAVIOUR:

Dead whelp only has skinning action enabled, which is not possible with loot on the body.

##### STEPS TO REPRODUCE THE PROBLEM:

Step 1 Kill whelp
Step 2 Attempt to loot
Step 3 Only skinning action shown.  Unable to loot.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97181949-loot-skinning-issue-black-dragon-whelps-lev-17?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by AbraKabastard**
## Changes Proposed:
-  Add a gold check into HasItemForAll, which stops it reporting false in Player::IsAllowedToLoot

## Issues Addressed:
- Closes #4839

## Tests Performed:
- Kill the drakes a lot and loot
-

## Known Issues and TODO List:

- [ ] Try it in a group situation
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by AbraKabastard** [comment]
This also fixes all skinning related issues on ChromieCraft as I've tested the respective mobs (Moonrage worgen.. IDs: 1769, 1924 ... cave yeti id: 2248, 2249)

**Comment by T1ti** [comment]
I've also noticed this issue several times

**Comment by Stifler82** [comment]
I'll test your PR, and I'll let you know if it works..

**Comment by Stifler82** [comment]
Great PR! for me can be merged.
**Note:** `Watch my video entirely, because a secondary problem has arisen, (it's at the end of the video), but the problem is not related to the CODE of This PR, it is an additional problem.`

**Video Test:** [Loot: Gold should always be lootable](https://youtu.be/zoeELIPXOt4)

**Comment by T1ti** [comment]
> @FrancescoBorzi @AbraKabastard
> 
> Great PR! for me can be merged.
> **Note:** `Watch my video entirely, because a secondary problem has arisen, (it's at the end of the video), but the problem is not related to the CODE of This PR, it is an additional problem.`
> 
> **Video Test:** [Loot: Gold should always be lootable](https://youtu.be/zoeELIPXOt4)

so if you start clicking very quickly you can skip the skill requirement to skin ? 
Need to test without this PR

**Comment by Stifler82** [comment]
> so if you start clicking very quickly you can skip the skill requirement to skin ?
> Need to test without this PR

@T1ti 
already done, I can confirm that I had already noticed this problem (which happens only in that specific NPC), it was there even before this PR.

**Comment by Stifler82** [comment]
@T1ti 
in addition, if you go to see the modification he made, you will notice that he has just entered a little code to force the loot of the golds.
the changes he made don't affect the skinning mechanics!

**Review by Stifler82 — APPROVED** [review]
For me it's ok.

**Comment by Stifler82** [comment]
> > so if you start clicking very quickly you can skip the skill requirement to skin ?
> > Need to test without this PR
> 
> @T1ti
> already done, I can confirm that I had already noticed this problem (which happens only in that specific NPC), it was there even before this PR.

@T1ti 
Not even to do it on purpose, here is the proof that gave that problem even before.
**Video Test:** [Loot Skinning issu](https://www.youtube.com/watch?v=b6GM0hZtFf8)

and here is also the link of the report where I commented with this video.
https://github.com/chromiecraft/chromiecraft/issues/199#issuecomment-798832734

**Comment by AbraKabastard** [comment]
I can see by your videos and my own tests that if the whelp spawns as level 17, you can skin it at 70, if it spawns at level 18 you can skin it at 80. I never skinned in retail or any private server so I have no clue if this is correct behavior or not

**Comment by Stifler82** [comment]
> ‎Posso vedere dai tuoi video e dai miei test che se il whelp si genera come livello 17, puoi scuoiarlo a 70, se si genera al livello 18 puoi scuoiarlo a 80. Non ho mai scuoiato al dettaglio o qualsiasi server privato, quindi non ho idea se questo sia un comportamento corretto o meno‎

@AbraKabastard 
Are you saying that it is the paradox of a game rule?
wedged by the quirk of the level.

**Comment by Stifler82** [comment]
@AbraKabastard 
in any case your PR is an improve.

**Comment by AbraKabastard** [comment]
> Are you saying that it is the paradox of a game rule?
> wedged by the quirk of the level.

Yes. From WoWPedia
```
Skinning skill required is:

    1 for level 1-10 mobs.
    (10 times mob level) minus 100 for level 11-20 mobs.
    5 times level for level 21-73 mobs.
    Wrath of the Lich King - Requires 5-point skill increases per mob level up to 73. Requires 10-point skill increases from 74-80.
```
17 * 10 = 170
170 - 100 = 70
18 * 10 = 180
180 -100 = 80

Thanks for your review and the discussion :) I learn something new

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @AbraKabastard , just one small note from me: always add brackets, even in 1-liner if/else/for blocks. This helps to prevent mistakes. No need to update this PR as I've already done it for you.

thanks @Stifler82 for testing this and for the accurate feedback. Nice team work!

**Comment by Stifler82** [comment]
**Related to:** https://github.com/chromiecraft/chromiecraft/issues/199

**Pull request merged**
