### PR TITLE
fix(Scripts/TirisfalGlades): script Calvin Montague in SAI so we can remove the tirisfal glades cpp script file

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

N.A.

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
N.A.

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

N.A.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by fangshun2004** [comment]
The spell id should use 7737
When the task is completed (I see what appears to be less than 30% HP). When you return to the home spot, you will make an emoji (EMOTE_ONESHOT_RUDE) .  Failed mission (player dies or leaves the battle, returns to home, keeps faction 14 attackable) for 3 minutes, restores the invulnerable state and faction

**Comment by fangshun2004** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/18087
It's a sniffing script and my attempt to move to smartscript failed. I don't know what to do with smrtscript, how to deal with mobs that are below 30 HP back to the home point. Or return to the home point after leaving the fight, if you use phase and when you enter avoidance mode, the phase will be reset

**Comment by elthehablo** [comment]
> https://github.com/azerothcore/azerothcore-wotlk/pull/18087
> It's a sniffing script and my attempt to move to smartscript failed. I don't know what to do with smrtscript, how to deal with mobs that are below 30 HP back to the home point. Or return to the home point after leaving the fight, if you use phase and when you enter avoidance mode, the phase will be reset
> 

I completely missed that. I am sorry. Can I add you as a co-author in a future commit and keep it in SAI?

**Comment by fangshun2004** [comment]
Absolutely. I can provide complete sniffing data if needed

**Comment by elthehablo** [comment]
> #18087 It's a sniffing script and my attempt to move to smartscript failed. I don't know what to do with smrtscript, how to deal with mobs that are below 30 HP back to the home point. Or return to the home point after leaving the fight, if you use phase and when you enter avoidance mode, the phase will be reset

image

image

I hate scripting SAI, but tbh it's very nice to be able to not have a specific script for these simple quests clogging up the scripts folders. SAI is very versatile

**Comment by fangshun2004** [comment]
SmartScript doesn't know how to tell if it's due to health being reduced below 30% back to the spawn point. Or by leaving the fight or dying of the player to return to the spawn point I tried to deal with it with SMART_ACTION_SET_EVENT_PHASE. But when out of combat, it seems that the SMART_EVENT_PHASE will also be reset. SMART_EVENT_REACHED_HOME with SMART_EVENT_PHASE does not work

If someone can do it, I can Xi how to do it

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
