### PR TITLE
fix(DB/Creature): Captain Greenskin formation

### LINKED ISSUE #3055: deadmines captain greenskin creatures
deadmines captain greenskin creatures

##### SMALL DESCRIPTION:

there are 2 defias pirates at the top of the ship in deadmines that are not patrolling correctly

##### EXPECTED BLIZZLIKE BEHAVIOUR:

the 2 defias creatures at the top of the ship are supposed to be patrolling with captain greenskin around the boat.  Note captain greenskin is correct, but the additional creatures are not

##### CURRENT BEHAVIOUR:

the 2 defias creatures are just standing on the ship without patrolling

##### STEPS TO REPRODUCE THE PROBLEM:

1. go to the deadmines
2. go to the top of the ship right before the last boss (van cleef)
3. see the 2 defias creatures not patrolling
WoWScrnShot_052020_115958

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

f2892764cd38

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

AhBot
Autobalance

##### OTHER CUSTOMIZATIONS:

none

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91484564-deadmines-captain-greenskin-creatures?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by wackinwallaby**
## CHANGES PROPOSED:
-  Added Captain greenskin to creature_formations as a leader
-  Added the 2 pirates that should be following him to the formation as well

## ISSUES ADDRESSED:
- Closes #3055

## TESTS PERFORMED:
-Updated my world database on Linux and the creatures follow captain greenskin now.
-

## HOW TO TEST THE CHANGES:

- `.go cr 79333`
- the 2 pirates start following greenskin after a few seconds.

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by merdlin** [comment]
Hello, I will start the test. I will give you feedback soon.

**Comment by Winfidonarleyan** [comment]
`fix(DB/CreatureFormations): captain greenskin followers` maybe use this title?

**Comment by wackinwallaby** [comment]
How do I edit the file for the PR to remove the quotes?  Sorry this is the first one I have ever done😁

**Comment by Kitzunu** [comment]
You just need to edit the file within your fork and your branch

**Comment by wackinwallaby** [comment]
Quotes removed from integers.  Let me know if anything else should be different.  Thanks!

**Comment by Kitzunu** [comment]
Looks good, ty

**Comment by merdlin** [comment]
It looks good to me.

**Comment by BarbzYHOOL** [comment]
thank you guys and most notably @wackinwallaby 
btw to edit the file directly in github, you need to click on "view file" in the diff then edit it

**Pull request merged**
