### PR TITLE
fix(Core/Command): `additem` doesn't work when name contains apostrophe

### LINKED ISSUE #3646: .additem [item's] doesn't work with single quote in name
##### CURRENT BEHAVIOUR:

```
.additem [Ymirjar Physician's Robe]
.add [Sovereign's Belt]
.add [Sovereign\'s Belt]
```

None of these work but they should (without the need to escape with `\` if possible)
Item names without `'` work fine.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .additem [Ymirjar Physician's Robe]
2. .add [Sovereign's Belt]
3. 

##### AC HASH/COMMIT:

cfdbf00a
old commit but found no issue/pr related to this and i'm sure it has not been noticed before

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/94005999-additem-item-s-doesn-t-work-with-single-quote-in-name?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by placemolle**
Fix  #3646

Happens because the code escapes those characters in the name, but we don't need to do that because we use prepared statements.

## CHANGES PROPOSED:
-  Remove item name's escaping

## ISSUES ADDRESSED:
- Closes  #3646

## TESTS PERFORMED:
- In-game on a Windows server

## HOW TO TEST THE CHANGES:

1.  `.additem [Ymirjar Physician's Robe]`
2. You now have the item, wheras before you would get an error message like `Could not find 'Ymirjar Physician's Robe'`

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Thanks for the PR!

So, the change is that: `                WorldDatabase.EscapeString(itemName);` ?
but this is probably there to prevent bad things to happen like a sql injection, no?

PS: I can't easily read the diff on github, dunno why, if some other staff member can explain why, it's very annoying (seems related to codacy)

**Comment by placemolle** [comment]
Yes I just removed  `WorldDatabase.EscapeString(itemName);`. We don't have to worry about SQL injection because we use prepared statements to insert the item's name into the query.

**Comment by placemolle** [comment]
Tests are failing but it seems to be an unrelated issure.
In the error details:
```
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/focal/InRelease  402  Payment Required [IP: 54.193.34.251 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu focal InRelease' is no longer signed.
```

**Comment by FrancescoBorzi** [comment]
I've restarted the build, let's see

**Comment by placemolle** [comment]
CodeFactor is failing because of "Complex Code", I don't think my commit did that.

**Comment by FrancescoBorzi** [comment]
> CodeFactor is failing because of "Complex Code", I don't think my commit did that.

you are correct, just ignore that. The other failures were solved, so it's good to go.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Racknar0** [comment]
Tested!

Before PR
 
image

After PR

image

**Comment by BarbzYHOOL** [comment]
> Yes I just removed `WorldDatabase.EscapeString(itemName);`. We don't have to worry about SQL injection because we use prepared statements to insert the item's name into the query.

Ok

@Racknar0 ty for testing
@placemolle ty for the PR, gonna be merged (are you on our discord?)

**Pull request merged**
