### PR TITLE
fix(Core/AI): improve npc_escortAI

### PR DESCRIPTION
**Pull request by Kitzunu**
cp from tc

## Changes Proposed:
- NPC should not go into combat if it has REACT_PASSIVE
- NPC should not go into combat if the place is inaccessible
- NPC should not go into combat if AI cannot attack
- NPC should not go into combat if it is in EVADE mode
- NPC should not go into combat if the enemy is in EVADE mode
- Update DEFAULT_MAX_PLAYER_DISTANCE to 100 instead of 50 to allow players to be further away from the NPC (ref https://github.com/azerothcore/azerothcore-wotlk/issues/4860)

## Tests Performed:
- Build

## How to Test the Changes:

Edit by Shin: check a couple of creatures that use npc_escortAI

For example:

1. Get a creature that uses npc_escortAI
2. check the conditions above, creature should not aggro when they are true
3. Check that the NPC only despawns if you are >100 yards away

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by 55Honey — COMMENTED** [review]
Looks good to me.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Kitzunu have you tested this in game? I see only "build" in "Test performed". A check in game is required for such generic C++ change.

**Comment by Kitzunu** [comment]
I have not as I am limited on time, but anyone can easily test it.

But the conditions are pretty logical, for example it should obviously not attack if it is passive

**Comment by T1ti** [comment]
Kinda unrelated but it's been proved in sniffs that on Classic, escort NPCs change their faction to "Escortee" (faction id 40) I wonder if using the correct faction would fix some issues with escorts

**Comment by Kitzunu** [comment]
Testing this would probably require the tester to change code to some script or NPC to make these conditions true.

This is why I don't think it is necessary and instead just look at the logic.
Should an escort NPC be able to attack while in passive state? No. if (me->HasReactState(REACT_PASSIVE))
Should an escort NPC be able to attack a target it cannot get to? No. if (!who->isInAccessiblePlaceFor(me))
Should an escort NPC be able to attack if it cannot attack "who"? No. if (!CanAIAttack(who))
Should an escort NPC be able to attack if it is in evade mode? No. if (me->IsInEvadeMode())
Should an escort NPC be able to attack an enemy that is in evade mode? No. if (who->GetTypeId() == TYPEID_UNIT && who->ToCreature()->IsInEvadeMode())

**Comment by FrancescoBorzi** [comment]
> Testing this would probably require the tester to change code to some script or NPC to make these conditions true.

not necessarily. Once again: when testing, we should first make sure that there is no regression. So testing a couple of escort quests is what we want.

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
