### PR TITLE
fix(Core/Unit): fix Dual Wield for more creatures, CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK, creature disarm damage

### PR DESCRIPTION
**Pull request by sogladev**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

dual wield:
current dual wield logic relies on `Unit::haveOffhandWeapon()` which requires  `m_canDualWield` to be set. New dual wield logic for creatures is based on cmangos' implementation. player DW remains unchanged. I did not remove `Unit::haveOffhandWeapon()` as it is still used on some scripts

creatures can now dual wield if: has non-disarmed weapon in offhand OR `m_canDualWield` is set. `m_canDualWield` is set by `SetCanDualWield` through script or `SPELL_EFFECT_DUAL_WIELD`, `CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK`

 https://github.com/azerothcore/azerothcore-wotlk/blob/bb0d292e1c2bb5619fbc3105e7cd919b45268748/src/server/game/Entities/Unit/Unit.cpp#L527  

changes:
1. dual wielding mobs can hit with their off-hand without relying on `m_canDualWield` being set
1. implement `CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK` which allows special cases to attack with non-weapon offhand. ex. allows 20929 Wrath Lord to dual wield main hand sword and offhand fist
1. disarmed mobs no longer do near zero damage, instead damage is reduced by ~50%
1. implement helper function  `Unit::GetVirtualItemId` for `SetUInt32Value(UNIT_VIRTUAL_ITEM_SLOT_ID...` to use [helper function based on tc](https://github.com/TrinityCore/TrinityCore/commit/d611925dc7ab2b3f19c5ee9e0f75b8dfb6de1291), omitted refactoring
1. shapeshift check for can useweapon, small part of using data from `SpellShapeshiftForm.dbc` present in cmangos

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20001

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

1. disarm damage https://wowwiki-archive.fandom.com/wiki/Disarm_effect, [original commit in cmangos](https://github.com/cmangos/mangos-wotlk/commit/8ebc4836269ddf4665daf7a6f336fb0060f797df)
2. creatures with `CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK` from cmangos-db  `ExtraFlags & 0x00800000`, trinitytc lists 2 creatures Ymirjar Battle-Maiden `flags_extra & 0x00000800`

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

special case dual wield 20929 Wrath Lord with `CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK`
 should attack with main hand and off hand fist
```
.npc add temp 20929
```

generic case dual wield 22143 Gordunni Back-Breaker
```
.npc add temp 22143
```

disarm MH
```
.cast 8379
```

disarm MH and OH with dismantle 
```
.cast 51722 
```

1. dual-wield animation, damage and disarmed damage
2. special case animation

## Known Issues and TODO List:

- [ ] refactor, use helper `Unit::GetVirtualItemId`
- [ ] remove `Unit::haveOffhandWeapon()`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Rorschach91** [comment]
I tested the pr and seems that it works.
However some script files has been modified during these days by other merged fixes.

I don't know if can be useful but this is the fix with files updated to the last AC version.
[fix Dual Wield (updated 09-25-24).zip](https://github.com/user-attachments/files/17130164/fix.Dual.Wield.updated.09-25-24.zip)

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
I've updated the wiki and keira3 about the flag extra reference

**Comment by Nyeriah** [comment]
This PR has caused this issue: https://github.com/azerothcore/azerothcore-wotlk/issues/20045

**Comment by Rorschach91** [comment]
Could it be the problem?

Immagine 2024-09-26 005849

**Comment by sogladev** [comment]
I maybe should have renamed this flag `CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK` as it can cause some confusion with the current name and description 

To clarify, by default, any creature with a usable off-hand weapon (not disarmed) will automatically dual wield and use both their main hand and off-hand for attacks.

`CREATURE_FLAG_EXTRA_USE_OFFHAND_ATTACK` exists to force the dual wield behavior, even if the creature does not have a valid off-hand weapon. It is meant for special cases where creatures need to attack with their off-hand regardless of having a usable weapon.

To illustrate, [Wrath Lord](https://www.wowhead.com/tbc/npc=20929/wrath-lord#screenshots:id=12811), which has a main-hand sword but no off-hand weapon,  will only attack using his sword. With this flag, Wrath Lord will correctly use its unarmed off-hand, forcing it to dual wield

Maybe a rename is appropriate to `CREATURE_EXTRA_FLAG_DUAL_WIELD_FORCED` with description "creature will forcibly use offhand attacks even without a weapon"

**Pull request merged**
