### PR TITLE
fix(Core/Spells): Removed Focused/Brutal on map change.

### LINKED ISSUE #6195: Focused Assault Debuff Persisting After WSG Ends
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/738

The Focused Assault debuff https://wowgaming.altervista.org/aowow/?spell=46392 stays after the WSG battleground ends in certain circumstances.

<a href="https://ibb.co/6rT8t31">CCbug</a>

Tester's notes: Confirmed. This issue was originally raised in https://github.com/azerothcore/azerothcore-wotlk/issues/5157, where it was fixed in most cases. However, there do seem to be rare edge cases where it persists. To get it to break in this case involved two druids, CFBG, and bear form - see reproduction steps for details. Somewhat unexpectedly, it's the druid who was not faction changed that was affected.

WoWScrnShot_060221_220852

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Focused Assault should not remain on your character after the battleground ends. I can't find any evidence about this issue specifically, but patch notes at the bottom of this page: https://wowpedia.fandom.com/wiki/Warsong_Gulch state that the timer for the debuff should reset when both flags are returned to their bases, which I assume happens when a battleground ends. Also it just doesn't make sense for it to remain when you don't have the flag anymore.

##### STEPS TO REPRODUCE THE PROBLEM:

1. join WSG with two druids of the same faction
2. CFBG will assign one to the opposite faction
3. Go bear and carry flag until you get debuffed with Focused Assault (or use .aura 46392 on BOTH characters)
4. wait until battleground ends
5. observe the debuff still being there. Weirdly, the affected druid in my case was the non faction-changed one.

As a note, this took days to reproduce, and I'm not confident it's distilled down to exactly the elements that are causing it to fail. It's a combination of CFBG, bear form, and maybe other buffs. But for anyone trying to reproduce this, don't try once, fail, and declare that it's not happening. Like I said, this took days.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98898409-focused-assault-debuff-persisting-after-wsg-ends?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #9724: (Spell) Focused Assault buff not being removed after WSG.
### Current Behaviour

Try to carry flag for >5 mins in WSG and get debuff Focused Assault, either win or lose the BG, and notice the buff is still applied. 
Issue is first reported once and only onced on CC https://github.com/chromiecraft/chromiecraft/issues/738 and  https://github.com/chromiecraft/chromiecraft/issues/1732

### Expected Blizzlike Behaviour

When WSG is completed, Focused Assault should be removed from the player.

### Source

_No response_

### Steps to reproduce the problem

Try to carry flag for >5 mins in WSG and get debuff Focused Assault
Win/Lose that BG while having debuff
Check if debuff persists on character upon leaving BG or entering new BG

also mentioned in the comments of the first issue:
image

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/086b20edbcc76bb6b80ef4fe2845d1f4e4087bd9

### Operating system

Windows 10 x64 Pro

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #6195
Fixes #9724

## Issues Addressed:

- Closes #9724
- Closes #6195
- Closes https://github.com/chromiecraft/chromiecraft/issues/738
- Closes https://github.com/chromiecraft/chromiecraft/issues/1732

## Tests Performed:

- Not tested

## How to Test the Changes:

It's nearly impossible to reproduce.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by acidmanifesto** [comment]
Merge Conflicts

**Comment by UltraNix** [comment]
Fixed.

**Comment by Nyeriah** [comment]
Conflicts 🤷‍♂️

**Pull request merged**
