### PR TITLE
fix(Core/Spells): Cooldowns:

### LINKED ISSUE #5263: Unable to Auto Attack after drinking Health Potion [$20 awarded]
Under some circumstances Health Potions cause a player to be unable to Auto Attack.

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance (not tested)
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

If a player exits WoW while under the effects of a Troll's Blood Potion (multiple tested, all affected), using a Health Potion (multiple tested, all affected) after logging back in causes Auto Attack to not work.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Using a Health Potion, under any circumstances should not permanently disable a player's melee abilities.

##### STEPS TO REPRODUCE THE PROBLEM:

Setup: Add Troll's Blood Elixirs and Health Potions to inventory
```
.additem 3382 5
.additem 3388 5
.additem 3826 5
.additem 858 10
.additem 3928 10
.additem 22829 10
.additem 33447 10
```

Use one of the Troll's Blood Elixirs:
`/use Weak Troll's Blood Elixir`
`/use Strong Troll's Blood Elixir`
`/use Major Troll's Blood Elixir`

Exit game
`/exit`

Delete Cache folder: *optional*

Log into game

Now attempt to use one of the Health Potions (any will do)
`/use Lesser Healing Potion`
`/use Superior Healing Potion`
`/use Super Healing Potion`
`/use Runic Healing Potion`

If you use a potion out of combat you will notice the icon dulls (edit: ElvUI dulls icon, default UI has glowing border) as though it's been clicked but you will get no HP restored, and the cooldown will not start. Engaging a NPC in combat at this point, you will see that Auto Attack does not work.

Now `/exit` game, relaunch and attack another NPC, you will see it works fine.
While still in combat, use another Health Potion. Again, any will do.
You will again not get the effects of the potion, nor start the CD, but also, Auto Attack continue to work, but your weapons disappear.

##### EXTRA NOTES:

I found that if I engaged a NPC with the Warrior's Charge ability, Auto Attack functioned as normal, while this bug continued to affect Auto Attack on NPCs that were not engaged with Charge.

Instead of Troll's Blood Elixirs, I tried a few other items that also grant a HP5 buff.
 - Poached Sunscale Salmon
 - Book of Survival
 - Rune of Duty

Of the 3 items I tested, only Poached Sunscale Salmon actually gives a removable aura but none of them caused any issues with drinking a Health Potion.

Merely Logging out and Logging in does not clear the bugged state of a player, `/exit` is required to invoke and to clear this bug.

related: https://github.com/chromiecraft/chromiecraft/issues/386

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/ee1918a3e9bc355fbd6f8d58d77760fb61fdbff7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
The **[$20 bounty](https://www.bountysource.com/issues/97795972-unable-to-auto-attack-after-drinking-health-potion?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Reworked spell category cooldowns.
Implemented category cooldowns for pets.
Properly shows pet spell cooldowns in player's UI.
Corrected pet spell cooldowns with infinity duration.
Do not add/remove infinity spell cooldown on aura apply/remove if casted by item.
Fixes #5263.

## Issues Addressed:

- Closes #5263
- Closes https://github.com/chromiecraft/chromiecraft/issues/386
- Closes https://github.com/chromiecraft/chromiecraft/issues/1350

## Tests Performed:

- Tested ingame with many spells and pets.

## How to Test the Changes:

```
Properly shows pet spell cooldowns in player's UI.
Corrected pet spell cooldowns with infinity duration.
```
1. Login on warlock and summon imp
2. Cast "PhaseShift"
3. Logout
4. Login
5. See that "PhaseShift" is still on inifity duration (it's active).
6. Remove aura by clicking on pet bar
7. You should see cooldown counting.

**For all other problems described here - see #5263**

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers @azerothcore/testers please check this one

**Review by iraizo — APPROVED** [review]
I had to manually alter the tables because the auto updater of world_db does not do that, or the rev_ is wrong, but maybe thats just me. The PR itself seems to be working, after logging in its still active and if i click it its on cooldown.

**Comment by iraizo** [comment]
@FrancescoBorzi

**Comment by FrancescoBorzi** [comment]
@UltraNix build fails

**Comment by UltraNix** [comment]
Reated PR: https://github.com/azerothcore/mod-duel-reset/pull/20

**Comment by bgcfb** [comment]
After this commit,Talent Spell Modifier did not work!
Just like Improved Judgements(spell id :25957)
Judgements should be 8s but now still 10s
Please check again

**Comment by bgcfb** [comment]
> Make an issue.

Okay I am newbie here ,is it right?

**Pull request merged**
