### PR TITLE
fix(DB/Creature): Ormus the Penitent

### PR DESCRIPTION
**Pull request by Kitzunu**
* closes https://github.com/azerothcore/azerothcore-wotlk/issues/16801

## Changes Proposed:
-  From all the sources I can gather Ormus the Penitent should not offer a way to get the ring back if it is discarded.
-  

## Issues Addressed:

- Closes 

## SOURCE:

* https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/64078529
    *  > You can switch the ring, but there isn't an option to restore it if it's deleted.
    * > You can use the Item Recovery thing on Battle.net. It tracks stuff you vendor/destroy.
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
The text **does** exist in broadcast_text, ID 38227
ID 38226 is also used by the same NPC

**Comment by Gultask** [comment]
image

**Comment by Kitzunu** [comment]
Sure, but could it have been left over from cataclysm? Or earlier versions? Because I can't find any claim for it ever existing

**Comment by Gultask** [comment]
These rings might still exist. It's best to check in Retail if recovery is possible through this method.
I never trust comments anymore :(

**Comment by Kitzunu** [comment]
I can check retail

**Comment by heyitsbench** [comment]
> Sure, but could it have been left over from cataclysm? Or earlier versions?

Doesn't mean a whole heck of a lot, but its ID is before other Wrath texts. (~40,400 for example seems to be from the Zalazane's fall event)

**Comment by Kitzunu** [comment]
I stand corrected.

If the ring has been deleted the option shows and you can recover your ring.
In today's retail it is however free to recover it

**Pull request closed without merging**
