### PR TITLE
UBRS - incorrect unannotated fallthroughs

### PR DESCRIPTION
**Pull request by patou01**
## Changes Proposed:
-  add a bunch of break statements
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Thanks for those

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Just one question though: why do we even need those unused cases?

**Comment by patou01** [comment]
> 
> 
> Just one question though: why do we even need those unused cases?

They're one of those "we have the same structure and we make it noob friendly" thing that people have been using, probably because few people dare "add code".

**Comment by Nyeriah** [comment]
> > Just one question though: why do we even need those unused cases?
> 
> They're one of those "we have the same structure and we make it noob friendly" thing that people have been using, probably because few people dare "add code".

Looks like ancient code to me, it's not the case anywhere else anymore, feel free to remove them if you want to

**Comment by patou01** [comment]
Done, just have a quick check that I didn't remove one that might have been right just by luck.

**Pull request merged**
