### PR TITLE
Fix(core/arena) crash

### PR DESCRIPTION
**Pull request by pklloveyou**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
-

## How to Test the Changes:

The crash  is as follows:
1. Two teams use arena to queue.
2. Team A enters arena.
3. Team B disbands (deletes) the team
4. Server crashes after arena starts

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
Do we have a issue or a crash log for this crash fix? Or a way to replicate the crash?

**Comment by pklloveyou** [comment]
@acidmanifesto 
It crashed on my server
The crash  is as follows:
1. Two teams use auena to queue.
2. Team A enters arena.
3. Team B disbands (deletes) the team
4. Server crashes after arena starts

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@azerothcore/testers Can we confirm the crashing and then see if this resolves the crash as desribed here https://github.com/azerothcore/azerothcore-wotlk/pull/13196#issuecomment-1264525766

**Comment by atlasapplications** [comment]
On master branch I have not been able to recreate this crash. I went to Nagrand, created two sets of a 2v2 arena team, and I had them both go in a queue. I had team A enter the arena and I then attempted to disband team B's team and the message "Arena teams are currently locked" popped up over and over when I tried different ways to disband the team.

Was there another way you were able to reproduce the crash?

**Comment by pklloveyou** [comment]
Quit the queue and then disband the team

**Comment by atlasapplications** [comment]
How do you quit the queue once the dialog for entering the arena has appeared? To my knowledge, once the queue selects the teams you can't leave the queue. In my case, the leave queue button is grayed out and only enter battle is selectable.

**Comment by Sneften** [comment]
**I tried to recreate the crash on my local without success.**

- Joind 2v2 queue with two teams
- Enterd with team A
- Left the team with a member in team B and the leader type /teamdisband 2v2 to delete team B.
- No crash

**Comment by Maelthyrr** [comment]
I will close this PR. Unable to reproduce the crash source and no crash log.

**Pull request closed without merging**
