### PR TITLE
fix(DB/Events): Apothecary Hummel should be linked to event

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Add Apothecary Hummel to game_event_creature, I missed it on my last PR.

## Issues Addressed:

- Closes none

## Tests Performed:

- Not tested

## How to Test the Changes:

1. .tele sfk
2. Check if the apothecary is there, it should not.
3. .event start 8
4. Enter the instance again, it should be there.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
this?

Screenshot_20220223_095209

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Nefertumm** [comment]
I don't know if they are supposed to be there. I would have to find more info about it, but the boss definitely should not be there if the event is not active :P

**Comment by temperrr** [comment]
Those objects should be gone too :)

**Comment by Lynethris** [comment]
PR not work : 

- [X] Apothecary Hummel is not here when the event is not active
- [] When the event start, Apothecary Hummel spawn

**Comment by Lynethris** [comment]
PR not work : 

- [X] Apothecary Hummel is not here when the event is not active
- [] When the event start, Apothecary Hummel spawn

**Comment by Nefertumm** [comment]
> PR not work : 
> 
> - [X] Apothecary Hummel is not here when the event is not active
> - [ ] When the event start, Apothecary Hummel spawn
> 
> WoWScrnShot_030922_205354
> 

Did you delete the save from the instance after you started the event?

**Comment by Lynethris** [comment]
> > PR not work :
> > 
> > * [x]  Apothecary Hummel is not here when the event is not active
> > * [ ]  When the event start, Apothecary Hummel spawn
> > 
> > WoWScrnShot_030922_205354
> 
> Did you delete the save from the instance after you started the event?

My bad, I forget. It's work fine with a reset instance.

**Comment by LukasVolgger** [comment]
Thx!

**Pull request merged**
