### PR TITLE
fix(LICENSE): GPLv2 or later

### PR DESCRIPTION
**Pull request by Kitzunu**
This is an attempt to fix the licensing issue that has been present on AzerothCore.
If there are any references to AGPL or the Affero GPL left in the repository that is not intentional and the GPLv2 is the license to be used.

For more information about the case you can check up on https://github.com/azerothcore/azerothcore-wotlk/issues/11863

If there are any other issues with this PR, or if this PR does not fix the issue of AGPL being applied wrongly please let me know so we can correct it.

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11863

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
#first

**Comment by ZhengPeiRu21** [comment]
This is maybe good opportunity to change this line, which incorrectly say that changing the banner message is against the terms of the license. It can still have threat, but is not against license terms technically, so is will be more scary when correct. Haha.

The line is here:
https://github.com/azerothcore/azerothcore-wotlk/blob/76d57065e266f2642035291fac13982d18751761/src/server/worldserver/worldserver.conf.dist#L1240

**Comment by ihm-tswow** [comment]
Friends, you cannot undo a license just like that (even if it was incompatible!). 

If this only affects the files that was changed in the recent PR ~6 months ago, you might get away with it if you ask _every contributor to those files since then_. If this is intended to completely remove the AGPL from azerothcore, you'd need permission from every contributor to the AGPL modules since 2016. The alternative is to drop any AGPL-infected code, which you won't likely ever be able to do.

There is no completely pain-free way out of something like this, but if you just want to be on the good end of other cores, I think we're just happy you don't leave clauses keeping us hostage from editing our own files.

If you want any advice with this, you can reach out here or on discord. While I'm not a lawyer, I'm probably the person that's discussed this topic the longest in this scene to date, so I have a decent grasp on GPL conventions and how other projects use it.

**Comment by Nyeriah** [comment]
> Friends, you cannot undo a license just like that (even if it was incompatible!).
> 
> If this only affects the files that was changed in the recent PR ~6 months ago, you might get away with it if you ask _every contributor to those files since then_. If this is intended to completely remove the AGPL from azerothcore, you'd need permission from every contributor to the AGPL modules since 2016. The alternative is to drop any AGPL-infected commits, which you won't likely ever be able to do.
> 
> There is no completely pain-free way out of something like this, but if you just want to be on the good end of other cores, I think we're just happy you don't leave clauses keeping us hostage from editing our own files.
> 
> If you want any advice with this, you can reach out here or on discord. While I'm not a lawyer, I'm probably the person that's discussed this topic the longest in this scene to date, so I have a decent grasp on GPL conventions and how other projects use it.


> Friends, you cannot undo a license just like that (even if it was incompatible!).
> 
> If this only affects the files that was changed in the recent PR ~6 months ago, you might get away with it if you ask _every contributor to those files since then_. If this is intended to completely remove the AGPL from azerothcore, you'd need permission from every contributor to the AGPL modules since 2016. The alternative is to drop any AGPL-infected commits, which you won't likely ever be able to do.
> 
> There is no completely pain-free way out of something like this, but if you just want to be on the good end of other cores, I think we're just happy you don't leave clauses keeping us hostage from editing our own files.
> 
> If you want any advice with this, you can reach out here or on discord. While I'm not a lawyer, I'm probably the person that's discussed this topic the longest in this scene to date, so I have a decent grasp on GPL conventions and how other projects use it.

I'm not sure what you're proposing. I understand the implications of this, I don't see other feasible way to achieve it.

**Comment by Kitzunu** [comment]
I will leave this as-is.

Personally, I do not have the time to go through every commit or every file to see if or what was licensed correctly or not. I also do not really care about the license to the extent that I will research it anymore, but did this as I and others came to understand that the licensing issue that came before I ever contributed here was wrong. Perhaps we just leave this here and hope all contributors approve this change, which is also unlikely.

We are all out for the same thing, fair open sourcing and mutual respect amongst the wow emulation community.

If you know the way to correct it the right way, feel free to open a PR.

**Comment by Kitzunu** [comment]
we can't just relicense everything. That would also break a lot of things.

**Pull request closed without merging**
