### PR TITLE
fix(Core/Spell): Restricted Flight Area

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Bug originated due to changes in CheckLocation()
-  Remove duplicate code

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5013#issuecomment-808317120

## Tests Performed:

- Builds
- Tested in-game

## How to Test the Changes:

1. Test so flying works as expected in all maps (Classic, TBC, WotLK)
2. Fly over dalaran, see that you get the debuff no fly zone

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Footman

**Comment by pklloveyou** [comment]
image
So?

**Comment by Footman** [comment]
I am on it. Testing on live to see if there some other issues connected to it.

**Comment by Kitzunu** [comment]
good =)

**Comment by FrancescoBorzi** [comment]
according to @Footman we can merge this because he has been testing it

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
