### PR TITLE
Restore chek in disables table for bg and random bg

### LINKED ISSUE #306: Disable battleground random
**Description**:

**Current behaviour**: Tell us what happens
When you disable some BG from the database, it still works in random BG mode.
**Expected behaviour**: Tell us what should happen instead
Should be disabled also in BG random
**Steps to reproduce the problem**:
Example:
Run the following query in the database "world"
```
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('3', '1', '0', '', '', '');
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('3', '30', '0', '', '', '');
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('2', '628', '0', '', '', '');
INSERT INTO `world`.`disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) VALUES ('2', '30', '0', '', '', '');
```

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/858955b68c70b98e0c05b737cad5ee7310033308

**Modules**:  Are you using modules? if yes, list them
NO
**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

no

### PR DESCRIPTION
**Pull request by Viste**
**Changes proposed:**

-  Restore chek for disables table for battelgraunds

**Target branch(es):** 1.x/2.x etc. master

**Issues addressed:** Closes #306 

**Tests performed:** (Does it build, tested in-game, etc)
no test can't test now
**Known issues and TODO list:**
- [ need test] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Viste** [comment]
why travis unhappy in linux builds fine

**Comment by falzard** [comment]
I'll test it but to be sure, it's about the bug: "Disables Random BG doesn't work" right?

**Comment by falzard** [comment]
Tested it. So now if you disable random BG it says "this battleground is disabled" and it works. **But if you DO NOT disable random BG in the database and you enable any or all BGs, the random BG feature doesn't work and you stay in queue forever.

**Comment by falzard** [comment]
Ok, normally it works completely fine after 15 tests and mistakes from my side. (I forgot to .debug bg during one test)

**Comment by Inifield** [comment]
This won't work, you're missing more code related to disable

**Comment by Viste** [comment]
@Inifield mmm where for random bg queue no need any more cheks in my opinion

**Comment by falzard** [comment]
no it works

**Comment by Inifield** [comment]
Are you sure ? it says currently not supported have you tested all possible scenario ?

**Comment by Viste** [comment]
@Inifield i think pussywizard is wrong in this case

**Comment by Viste** [comment]
i tested it now whith .debug bg and when no bg in disables table all time random bg put me on alterac first, then i add alterac to disables and .reload disables then reg random bg and bg put me to Standard of Ancients then i put to disables it to(so Alterac and SA in disables) and reload table again reg random bg and he puts me to warsong, i'm re reg 20 times to bg and no SA and Alterac only isel of conquest warsong arathi basin and Eye

**Comment by falzard** [comment]
Don't test with "reload disables".

I personally tested this thing during 20 min, I don't know why I did it...

**Comment by Viste** [comment]
@falzard reload don't work for disables and i don't know why (

**Pull request merged**
