### PR TITLE
feat(DB/Translations): import translation text from @mpfans

### PR DESCRIPTION
**Pull request by Helias**
Imported several quest texts

## Tests Performed:
- executed in the DB twice

## How to Test the Changes:
- just executed in the DB **twice**

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
That's a lot

**Comment by Helias** [comment]
It's only a little part, I still need to import several ones

**Comment by Helias** [comment]
Imported all, they were less than what I think.
it's hard to review this, I checked if these texts have been already imported on a clean AC.

**Review by Kitzunu — APPROVED** [review]
Approving as I can run it twice in the DB

**Pull request merged**
