### PR TITLE
fix(DB/creature): Beaten Corpse faction and flags

### LINKED ISSUE #6318: [Barrens] Beaten Corpse wrong faction
Can confirm on local AC server (42019c0)

Original report: https://github.com/chromiecraft/chromiecraft/issues/841

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Mankrik's wife name tag "Beaten Corpse" is in grey instead of green.
Current behaviour on ChromieCraft:
WoWScrnShot_061121_121732
Expected behaviour, recorded on retail Classic Wow: https://youtu.be/g-1A-JD2UMQ?t=23971
image

##### EXPECTED BLIZZLIKE BEHAVIOUR:

"Beaten Corpse" should be in green.

##### SOURCE:

Expected behaviour, recorded on retail Classic Wow: https://youtu.be/g-1A-JD2UMQ?t=23971

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Mankrik's wife, in the Barrens, coords 49.3 ; 50.4 (or ".go creature 19221")

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by anguaive**
Beaten Corpse (id: 10668) was assigned the wrong faction and flags
which made its nameplate appear grey instead of green for Horde players

According to https://classic.wowhead.com/npc=10668/beaten-corpse, the
creature should appear friendly to Horde players and hostile towards
Alliance players.

## Changes Proposed:
- Modify faction and dynamic flags of creature id 10668

## Issues Addressed:

- Closes #6318
- Closes https://github.com/chromiecraft/chromiecraft/issues/841

## SOURCE:

https://classic.wowhead.com/npc=10668/beaten-corpse
https://youtu.be/g-1A-JD2UMQ?t=23971

## Tests Performed:

- Tested in-game. Dialogue options still work and the "Lost in Battle" quest is still completable. Creature can't be damaged.

## How to Test the Changes:

1. `go c 19221`
2. confirm that creature appears friendly towards Horde players and hostile towards Alliance players
3. confirm that the creature can't be damaged

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by T1ti** [comment]
based on sniffs the correct faction should be 83

**Comment by T1ti** [comment]
since on vmangos it is working correctly with faction 83, we should probably investigate why it's not working properly on AC with the correct faction instead.

**Comment by anguaive** [comment]
Its faction was 83 initially ("Leatherworking - Elemental" according to Faction.dbc). 29 is "Beast - Wolf". Either I'm doing something wrong or the names assigned to the factions in the dbc are complete bogus. I went to The Crossroads and the horde guards there were of faction 29 so that's why I chose that.

**Comment by T1ti** [comment]
> Its faction was 83 initially ("Leatherworking - Elemental" according to Faction.dbc). 29 is "Beast - Wolf". Either I'm doing something wrong or the names assigned to the factions in the dbc are complete bogus. I went to The Crossroads and the horde guards there were of faction 29 so that's why I chose that.

that's not how factions work, the ID is faction_template.dbc 
image

2nd column link to faction.dbc id (66)
which is (horde generic) 
image

**Comment by T1ti** [comment]
it's a bug related to the fake death state flag which makes it appear neutral as other npcs with this faction behave correctly

when u remove the dynamic flag it's properly green 
image

**Comment by anguaive** [comment]
@T1ti Thank you very much, I'll look into this today.

**Comment by T1ti** [comment]
Some dead npcs on Classic TBC are also grey so looks like that dyn flag is working properlyimage

I found the issue, this is beaten corpse on classic : 
image
U can see that it has 100% health, so it doesn't have the dead dynamic flag. That dynamic flag will make the npc have 0% health

That's the whole reason, just remove that flag from beaten corpse and issue is fixed

**Comment by anguaive** [comment]
WoWScrnShot_061521_213324

**Comment by T1ti** [comment]
yep

**Pull request merged**
