### PR TITLE
fix(Core/Quests: Fixed displaying correct quest marks for autocomplet…

### LINKED ISSUE #11237: While turning in quests the NPC's prioritize the wrong marker
Original CC Issue: https://github.com/chromiecraft/chromiecraft/issues/2989

### Current Behaviour

Wrong quest giver status (Icon Markers above head) priorty are given out of priority and order.

### Expected Blizzlike Behaviour

Per CC Report:
I'm pretty sure NPC's should always show the turn in quest marker above their head (?) if there's a quest to be delivered even if it can deliver a new quest (!).

Also, the turn in quest marker should appear in the minimap.

### Source

_No response_

### Steps to reproduce the problem

For this particular example:

Don't do the quest "The First and the Last".
Complete the quest "A Gift for The King of Stormwind".
Turn in "A Gift..."

### Extra Notes

_No response_

### AC rev. hash/commit

[e8e8c34](https://github.com/azerothcore/azerothcore-wotlk/commit/e8e8c345906220d2c3dda2066b9baf14172b9897)

### Operating system

Windows 11 x64 Pro

### Custom changes or Modules

- anticheat module

### PR DESCRIPTION
**Pull request by UltraNix**
…e/repeatable/daily completed quests.

Fixes #11237

## Issues Addressed:

- Closes #11237
- Closes https://github.com/chromiecraft/chromiecraft/issues/2989

## Tests Performed:

- Not tested.

## How to Test the Changes:

Start "Love is in the Air event` (`.event start 8`)
Don't do the quest "The First and the Last".
Complete the quest "A Gift for The King of Stormwind".
Turn in "A Gift..."

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
Remove the wrong mark, but but there should not be a question mark ? Because there are no mark now.

WoWScrnShot_041122_231917

**Comment by mpfans** [comment]
> 

You need to log out and log in again to see the correct sign

At present, this bug exists in all tasks, but it cannot be reproduced

**Comment by pklloveyou** [comment]
Sometimes it doesn't show https://github.com/azerothcore/azerothcore-wotlk/pull/9962 something to do with it

**Comment by Lynethris** [comment]
> > 
> 
> You need to log out and log in again to see the correct sign
> 
> At present, this bug exists in all quests, but it cannot be reproduced

You have right. So all is good.

**Review by IntelligentQuantum — APPROVED** [review]

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
