### PR TITLE
fix(DB/creature_template): Improve The Nexus

### PR DESCRIPTION
**Pull request by Knindzagxg**
Changes:

Min, Max & Modifier Damage for whole Dungeon.

How to test:
Apply SQL
Restart Server and delete your Cache.
Make sure to add very very basic gear towards Dungeon ilevel.

Before you start checking damage:
.mod hp 50000
.learn 1908 (Uber heal over time)

If there is any issue with damage and if you get instantly killed, lemme know.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Geekena** [comment]
damage and spell are ok
no problem found
boss have skulls now too

**Comment by Voxstrasza** [comment]
Why did you change the bosses to skulls?  That's not blizzlike at all.

**Comment by Si1ker** [comment]
https://www.youtube.com/watch?v=27iSseyrPbE&ab_channel=WoWAholics101
1:15 - frist boss
3:18 - second boss
4:32 - third boss
6:12 - last boss

They have more level but no skull.

**Comment by Voxstrasza** [comment]
> 
> 
> https://www.youtube.com/watch?v=27iSseyrPbE&ab_channel=WoWAholics101
> 1:15 - first boss
> 3:18 - second boss
> 4:32 - third boss
> 6:12 - last boss
> 
> They have more level (82) but no skull.

5 man bosses in WotLK will always be level 82 elites

How many more got pushed through and incorrectly have a skull now?

**Comment by Knindzagxg** [comment]
Thats something blizz never fixed even they wanted.
If you check wowhead every boss is marked with skull flag - That doesnt change level, only visual.
Its something we had chat once we started sorting classic and TBC dungeons before few months and decided to add visual skull.

**Comment by Knindzagxg** [comment]
Cheers for tests Geekena btw.

**Comment by Voxstrasza** [comment]
> Thats something blizz never fixed even they wanted.
> If you check wowhead every boss is marked with skull flag - That doesnt change level, only visual.
> Its something we had chat once we started sorting classic and TBC dungeons before few months and decided to add visual skull.

It’s still not Blizzlike. Even on Retail now, 5 man bosses don’t have skulls.

**Comment by Meltie2013** [comment]
@Knindzagxg Do you have sniff data to confirm the changes?

**Comment by Racknar0** [comment]
Tested with 3k of GS which is the usual to initiate heroics and no creature has abnormal damage

image

**Review by Si1ker — APPROVED** [review]

**Comment by Knindzagxg** [comment]
Do not Merge this one yet.

Everything is prepared, but need to see are we going with 1x Modifier or higher.
Any news @BarbzYHOOL ?

**Pull request merged**
