### PR TITLE
fix(DB/SAI): Head of Nefarian (A&H)

### PR DESCRIPTION
**Pull request by poszer**
- Fix

Updating previous PR

##### CHANGES PROPOSED:

-  Update
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1728

##### TESTS PERFORMED:

Yep, it's okay.

##### HOW TO TEST THE CHANGES:
 Read closing issue

##### KNOWN ISSUES AND TODO LIST:

- [x] Horde version (TODO)

- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by poszer** [comment]
Quest done in  **16:44** ( The gob spawned ) 


**17:41**


Will see result in 18:44 :rofl:

**Comment by Pondaveia** [comment]
Codestyle: Double to single quotes. Then I'll aprove and you can merge :)

**Comment by poszer** [comment]
Do not merge this. Need to test one more time the horde version. Also for code style, they re auto generated from SAI Editor like always, when I get some free time, I'll edit it.  @pondaveia

**Comment by gtao725** [comment]
Horde side's head does not despawn after 2 hours, Alliance side is ok, just tested the PR

**Comment by poszer** [comment]
> Horde side's head does not despawn after 2 hours, Alliance side is ok, just tested the PR

Yep, will fix this

**Comment by poszer** [comment]
Tested by @Knindzagxg and me. The quests are fine now. 
P.S Thanks for help @Knindzagxg  :heart:

**Comment by Stoabrogga** [comment]
This is not yet ready to be merged, there are still errors. I will sort this out together with @poszer.

**Comment by poszer** [comment]
@gtao725 When you are able, test please :smiley:

**Comment by gtao725** [comment]
@poszer just tested for 2 hrs and confirmed: BOTH Alliance & Horde side work PERFECT now!

**Comment by poszer** [comment]
> @poszer just tested for 2 hrs and confirmed: BOTH Alliance & Horde side work PERFECT now! Time to MERGE!!

Awesome! Thank you @gtao725

**Pull request merged**
