### PR TITLE
fix(DB/CreatureLoot) Felhunter (417)

### PR DESCRIPTION
**Pull request by nolt**
## Changes Proposed:
-  Deletes drop from Felhunter

## Issues Addressed:

- Partially Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10214

## SOURCE:

https://tbc.wowhead.com/item=18519/pattern-shifting-cloak

## Tests Performed:

-  sql applied, test drop

## How to Test the Changes:

1. Spawn Felhunter (entry 417), kill it, pattern will not drop

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by nolt** [comment]
PR is not ready yet.

**Review by acidmanifesto — APPROVED** [review]
its funny, because entry 417 is the Warlock's summon Felhunter. Which would of made it impossible to drop at all unless looting from a player's pet is possible. I concur with the changes.

**Comment by nolt** [comment]
@acidmanifesto 
if that so, I delete all loot from it cuz now it has 12 items that can be dropped :o

**Comment by acidmanifesto** [comment]
> @acidmanifesto if that so, I delete all loot from it cuz now it has 12 items that can be dropped :o

even better. usually when it comes to loot audit, we will audit either just the loot item itself or the npc\gameobject\item itself.
in this case i suggest making it a npc loot audit so we can keep it less chaotic and simple.

**Comment by acidmanifesto** [comment]
image
@nolt looks like the dry run caught something. can u correct it?

**Comment by acidmanifesto** [comment]
I recommend adding the line to the sql
```UPDATE `creature_template` SET `lootid`='0' WHERE  `entry`=417;```

**Pull request merged**
