### PR TITLE
refactor(Core): Make more use of helpers.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:

This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).

## Issues Addressed:

- Closes unreported issue.

## Known Issues and TODO List:

- [ ] Various comments around the repository use different forms of apostrophes, either (') or (`). Would like to replace all instances with a certain form, but which?

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Here I am trying to hijack your PR to push changes to the codestyle ci, but you won't let me :cry:

Anyways, push this
```diff
diff --git a/apps/codestyle/codestyle.py b/apps/codestyle/codestyle.py
index 50c5fe3dd5..797594d29d 100644
--- a/apps/codestyle/codestyle.py
+++ b/apps/codestyle/codestyle.py
@@ -105,14 +105,14 @@ def get_typeid_check(file: io, file_path: str) -> None:
     check_failed = False
     # Parse all the file
     for line_number, line in enumerate(file, start = 1):
-        if 'GetTypeId() == TYPEID_PLAYER' in line:
-            print(f"Please use IsPlayer() instead GetTypeId(): {file_path} at line {line_number}")
+        if 'GetTypeId() == TYPEID_PLAYER' in line or 'GetTypeId() != TYPEID_PLAYER' in line:
+            print(f"Please use IsPlayer() instead of GetTypeId(): {file_path} at line {line_number}")
             check_failed = True
         if 'GetTypeId() == TYPEID_ITEM' in line:
-            print(f"Please use IsItem() instead GetTypeId(): {file_path} at line {line_number}")
+            print(f"Please use IsItem() instead of GetTypeId(): {file_path} at line {line_number}")
             check_failed = True
         if 'GetTypeId() == TYPEID_DYNOBJECT' in line:
-            print(f"Please use IsDynamicObject() instead GetTypeId(): {file_path} at line {line_number}")
+            print(f"Please use IsDynamicObject() instead of GetTypeId(): {file_path} at line {line_number}")
             check_failed = True
     # Handle the script error and update the result output
     if check_failed:
```

**Comment by Grimdhex** [comment]
Be careful, your last commit is completely wrong. A player is also a unit, a child of Unit class precisely.  If you check TC: IsUnit() return TYPEID_UNIT or TYPEID_PLAYER. 

For Creature, it's more complicated because I'm not sure that there aren't other classes that are derived from Unit class without being a Creature class. It's why I wasn't added to my first PR.

**Comment by PkllonG** [comment]
> Be careful, your last commit is completely wrong. A player is also a unit, a child of Unit class precisely. If you check TC: IsUnit() return TYPEID_UNIT or TYPEID_PLAYER.
> 
> For Creature, it's more complicated because I'm not sure that there aren't other classes that are derived from Unit class without being a Creature class. It's why I wasn't added to my first PR.

That's true

**Comment by heyitsbench** [comment]
> Be careful, your last commit is completely wrong.

Maybe renaming to `IsUnitType()` would be a better usage? Or should I just revert that commit entirely?

**Comment by Grimdhex** [comment]
This doesn't change the logic much, since the player is by definition a UnitType. But I thought wrong, I've just checked. There are only two child classes of Unit: Player and Creature. So we can follow the TC logic: If only TYPEID_UNIT -> IsCreature() and IsUnit() is for: TYPEID_UNIT || TYPEID_PLAYER

@PkllonG it's not an issue because it's not use by same classes. TC have also IsCreature() for ObjectGuid class.

**Comment by PkllonG** [comment]
> This doesn't change the logic much, since the player is by definition a UnitType. But I thought wrong, I've just checked and there are only two child classes of Unit: Player and Creature. So we can follow the TC logic: If only TYPEID_UNIT -> IsCreature() and IsUnit() is for: TYPEID_UNIT || TYPEID_PLAYER usage.
> 
> @PkllonG it's not an issue because it's not use by same classes. TC have also IsCreature() for ObjectGuid class.

image
What do you think of that?

**Comment by heyitsbench** [comment]
So, in summation, requested changes are to rename the existing function to `IsCreature()` and make a new `IsUnit()` function returning `IsCreature()/IsPlayer()`?

**Comment by PkllonG** [comment]
`TYPEID_UNIT` use `IsCreature()`

**Comment by PkllonG** [comment]
`TYPEID_UNIT` use `IsCreature()`

**Comment by PkllonG** [comment]
image
 use `IsUnit()`

**Comment by PkllonG** [comment]
> image use `IsUnit()`

It is recommended to implement it with a new PR

**Comment by heyitsbench** [comment]
Updated. 👍

**Comment by Nyeriah** [comment]
[****](https://github.com/TrinityCore/TrinityCore/tree/3.3.5/src/server/game/Entities/Object#L191)

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
hmm merge conflicts

**Comment by heyitsbench** [comment]
> hmm merge conflicts

Hopefully resolved cleanly.

**Pull request merged**
