### PR TITLE
Fix parry aura spells

### PR DESCRIPTION
**Pull request by TheHighlord**
###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1522

##### TESTS PERFORMED:
Tested and working.

##### HOW TO TEST THE CHANGES:
Test Hunter Deterrence spell in melee combat.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by comix1988** [comment]
I tested this hunter spell and both on the master branch and with this fix the % of parry does not change, it remains at 89.04%.
parry

**Comment by Nefertumm** [comment]
But what about deterrence? Is it parrying?

**Comment by TheHighlord** [comment]
The truth is I made a lot of change in the core until the spell modified my parry correctly and I tought it's the only problem. I will check this again tomorrow.

**Comment by TheHighlord** [comment]
idk

Yeah it is working.

**Comment by comix1988** [comment]
I think the problem during the test of the issue was because I wasn't using the .max skill command, even before the fix.
however now it works, for me it's ok.

@TheHighlord good job^^

**Comment by TheHighlord** [comment]
@comix1988 Thanks !

I just realised that ```target->ToPlayer()->UpdateParryPercentage();``` can be deleted because ```SetCanParry()``` also calls ```UpdateParryPercentage()```.

**Comment by comix1988** [comment]
need to test again?

**Comment by TheHighlord** [comment]
> need to test again?

No, it is not neccesary.

**Comment by Nefertumm** [comment]
Thanks @TheHighlord for the fix, thanks @comix1988 for testing. 
Please, go grab those $5 https://github.com/azerothcore/azerothcore-wotlk/issues/1522

**Comment by TheHighlord** [comment]
@Nefertumm it's me who posted that bounty xD

**Comment by BarbzYHOOL** [comment]
@TheHighlord you create the bounty, you fix it and you earn the money thus making money from nothing

did you find a loop in the system to make infinite money? this is genius

**Comment by TheHighlord** [comment]
@BarbzYHOOL Nope. I did not know the fix for this issue, so I payed for that bounty.

**Comment by FrancescoBorzi** [comment]
@barbz Bountysource takes a small percentage of the bounty. So actually doing like this you don't earn any additional money but loose a little bit of it actually :)

**Comment by BarbzYHOOL** [comment]
i was joking -_-

**Comment by Viste** [comment]
this must be reverted!

**Pull request merged**
