### PR TITLE
Bash: Fix incorrect apply sql files at import

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
-  Added option `--default-character-set=utf8`
-  Fix incorrect apply not English text

##### ISSUES ADDRESSED:
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1250

##### TESTS PERFORMED: 
- `import-all: Assemble & Import all` in Windows

##### HOW TO TEST THE CHANGES:
**Need full clean DB!**
1. Apply PR
2. Use `db_assembler`
3. Choose `5 - import-all: Assemble & Import all`
4. Check DB table e.g. `locales_broadcast_text`
5. First data should be as follows
image

##### KNOWN ISSUES AND TODO LIST:
- [x] in Windows
- [ ] in Linux

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
I think this is for the correct reading of the file

**Comment by BarbzYHOOL** [comment]
but stoabrogga is right, there seems to be an issue that can bite us back in the future

**Comment by BarbzYHOOL** [comment]
setting specified in file is not applied
maybe other settings won't be applied

**Comment by FrancescoBorzi** [comment]
Not sure. We need to do some search about it

**Comment by BarbzYHOOL** [comment]
then this can be merged meanwhile so the other PR can be merged too (they are related)

but if we change something, let's not forget this "hackfix" :D

**Pull request merged**
