### PR TITLE
fix(DB/Spell): Desert BG 30min

### PR DESCRIPTION
**Pull request by Stifler82**
## Changes Proposed:
-  as requested by Shin, I increased the BG Desert by 30min

## Issues Addressed:
- Closes 

## Tests Performed:
- Tested in game and working
- Tested on Windows 10 (64)
WoWScrnShot_022421_020833

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stifler82** [comment]
@FrancescoBorzi 
@Helias

**Comment by Kitzunu** [comment]
Proof?

**Comment by Mitradis** [comment]
for what?

**Comment by Zoidwaffle** [comment]
This sounds like something you should be able to modify in worldserver.conf - or just run it as a custom SQL patch (assuming the current value is "blizz-like").

**Comment by FrancescoBorzi** [comment]
sorry, there is a misunderstanding here. I did request this change but not for AC, this is supposed to go on ChromieCraft only.

**Comment by Stifler82** [comment]
**This is what I think about:** [your sterile controversy](https://youtu.be/2bIi-RwcBf4)

@Kitzunu 
@Mitradis 
@Zoidwaffle

**Comment by BarbzYHOOL** [comment]
as a config option, it could be interesting though

**Comment by FrancescoBorzi** [comment]
Anyway... there is no need to attack a contributor just because of a mistake. Especially since he already tagged me and Helias so we would have handled this without any drama.

Stifler is new here and he has already been contributing a lot, this already shows something. Any constructive comment is always welcome but be respectful.

**Comment by Kitzunu** [comment]
Like that video was anything better.

**Comment by Stifler82** [comment]
> Like that video was anything better.

I have nothing against you @Kitzunu or against @Zoidwaffle.
But try to put yourself in my shoes: I went to bed late, and I was so tired that I could shoot a scene from "The Walking Dead", then I wake up, (mostly, resurrected), and I find myself against the farmers with the pitchforks that inveigh against me, for something that among other things was not my initiative, but (they commissioned it) to me.
How would you react in my shoes?

So, for me there is no problem if you do the checks here, indeed! THANK YOU FOR EVERYTHING YOU DO.
But, don't be "Kitzunu-BOT" you noticed that I tagged Shin and his brother, wait, before doing "Actions" right? and then after their comment you will realize how to act, it make sense to me, doesn't it?

**Pull request closed without merging**
