### PR TITLE
fix(Scripts/ZulGurub): Added dance emote on Jindo's evade.

### LINKED ISSUE #12275: [ZG] Jin'do the Hexxer - Boss shouldn't reset so quickly
### Current Behaviour

Boss resets immediately upon breaking combat.

### Expected Blizzlike Behaviour

Boss should emote a dance for a couple of seconds before returning to his original position and resetting. This is due to Brain Wash Totem working even when the player runs solo.

Everything besides the boss should reset first. Totems and Shades should disappear, but the boss stays for a couple of seconds before returning.

I believe it's 5 seconds between the first "reset" that starts the emote and the hard "reset" that properly resets the boss.

### Source

https://youtu.be/rTFP5VYf3zw?t=126 A full reset happening. The "soft resets" happen throughout the video.

### Steps to reproduce the problem

1. `.go c 49655` solo.
2. Engage the boss, see if resets are occurring immediately

### Extra Notes

Low-prio due to being mainly a solo problem.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/16f2983307aeeb39bd263e3e923c93c16488444f

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12275

## Issues Addressed:

- Closes #12275

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c 49655` solo.
Engage the boss, see if resets are occurring immediately

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
@UltraNix didn't work. The boss stay block in dance emote and don't reset.

**Comment by UltraNix** [comment]
@Maelthyrr Should be okay now.

**Comment by Maelthyrr** [comment]
Work fine now. Thanks :)

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nefertumm** [comment]
Merged with https://github.com/azerothcore/azerothcore-wotlk/pull/12233

**Pull request closed without merging**
