### PR TITLE
fix(DB/Zone):improved Dun Morogh

### PR DESCRIPTION
**Pull request by Knindzagxg**
Zone now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

### CODE REVIEW

**Comment by aradep** [comment]
Tested, everything works but the ranges for Juvenile Snow Leopard(1199), Young Black Bear(1128), and Snow Leopard(1201) seem a bit low, most of the time SAI doesn't have a chance to trigger.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg

**Comment by Knindzagxg** [comment]
Yeah, thats on purpose @aradep 
Most times they don't even cast on Retail, but you notice "daze" sometimes only when people pull multiple NPCs.
Otherwise, players would be dazed 24/7 in low level zones xP

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> Yeah, thats on purpose @aradep
> Most times they don't even cast on Retail, but you notice "daze" sometimes only when people pull multiple NPCs.
> Otherwise, players would be dazed 24/7 in low level zones xP

sounds reasonable to me. Unless @aradep has something against, for me it's good to be merged

**Review by Si1ker — APPROVED** [review]

**Comment by aradep** [comment]
@Knindzagxg should these creatures actually be "casting" daze? there is already a chance-on-hit daze effect that all mobs have. https://wow.gamepedia.com/Daze

**Comment by Knindzagxg** [comment]
Yeah for some reason they have daze spell that proc super super rarely.
Regular daze is hit from behind and its core based, but there is also this one xP

**Pull request merged**
