### PR TITLE
fix(DB/creature_template): Trial of the Champions Gossip Menu

### LINKED ISSUE #10333: FIX for: Trial of the Champions missing gossip entry
### Current Behaviour

NPC: 35004 has a missing gossip_menu_id which should be setted to:  10614... due to this he had no talking menu.

### Expected Blizzlike Behaviour

The NPC should be clickable and interactable.

just do: UPDATE creature_template SET gossip_menu_id="10614", npcflag="1" WHERE (entry="35004");

this is sniffed data which i was using on another server of mine.

### Source

_No response_

### Steps to reproduce the problem

1. type: .go cr 200038
2. take a lance hop up the mount and speak to the npc.
3. you will notice that the dialogue options are not there!

### Extra Notes

_No response_

### AC rev. hash/commit

22ec66566c26 2022-01-23 17:56:41 -0300 (master branch)

### Operating system

Host: Windows Server 2019 | Client: Windows 10 x64

### Custom changes or Modules
added his gossip_menu_id as well as his npcflag:

UPDATE creature_template SET gossip_menu_id="10614", npcflag="1" WHERE (entry="35004");

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix Trial of the Champions Gossip Menu for Horde and Alliance so event can be started

## Issues Addressed:

- Closes #10333 

## SOURCE:

Thank you @ PsYchoNauTek for original Horde fix. I also added fix for Alliance.

## Tests Performed:

NPC can gossip for Alliance:
Capture

NPC can gossip for Horde:
Capture2

NPC can start event:
Capture3

## How to Test the Changes:

1. .go creature 200038
2. NPC can interact and start event

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by 235832289** [comment]
some this error,After the battle is failed, it will not be reset

**Comment by acidmanifesto** [comment]
is this one also able to be verified thru vmangos as well?  @ZhengPeiRu21

**Comment by acidmanifesto** [comment]
if you can reference this with another verified database or a sniff please let us know before approval.

**Comment by ZhengPeiRu21** [comment]
> is this one also able to be verified thru vmangos as well? @ZhengPeiRu21

This is WotLK content, so it is not in Vmangos. These IDs and gossips were already in the database and were just not correctly assigned to these NPCs.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
