### PR TITLE
fix (Core/Raid/Boss Script): Naxxramas boss loatheb kill event

### PR DESCRIPTION
**Pull request by GMKyle**
###### ISSUES ADDRESSED:
When boss loatheb it's killed in Naxxramas, players remains  trapped, and instance event is still running.

Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/2053

##### TESTS PERFORMED:
 Build without errors and tested in-game. (Win10 and Debian 9 servers).

##### HOW TO TEST THE CHANGES:
- Enter instance/raid Naxxramas 
- Kill boss loatheb
- Door should open and also teleport portal  be active as intended 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Selyria have you tested this?

**Comment by solidmaxtor** [comment]
Tested, work fine now.... this issue is mark for "Priority - Low" I hate them for that  HA HA

**Comment by spinzaku** [comment]
Confirmed working

**Comment by poszer** [comment]
Thanks @GMKyle for PR, @Selyria , @solidmaxtor, @spinzaku   for testing :+1:

**Comment by Selyria** [comment]
> @Selyria have you tested this?

yes i have this tested

**Pull request merged**
