### PR TITLE
fix(Core/ZulGurub): Mandokir charge and chained spirits

### LINKED ISSUE #11746: [ZG] Bloodlord Mandokir - Chained Spirits not resurrecting dead players
### Current Behaviour

~~The Chained Spirits have no AI.~~ fixed by #11854

 - Chained Spirits are chosen seemingly randomly to resurrect a player.
 - Missing resurrection timer between Revives.

### Expected Blizzlike Behaviour

When a player dies, the **closest** Chained Spirit immediately goes to their body and casts Revive (ID: 24341) on them, then the Chained Spirit disappears until combat ends and the boss resets. They do not respawn mid-fight.

There is a ~~1:30~~ 100s timer before the player is allowed to accept the revive, and the "Accept" button is grayed out while the timer is ongoing.
Edit: I think the word cooldown works better here. Sorry for not explaining it correctly.
There cannot be 2 consecutive revives within 100 seconds of each other.

### Source

https://youtu.be/PdvZirl8vls?t=85
https://youtu.be/PdvZirl8vls?t=118 and 7 seconds after that timestamp

Timer:
https://youtu.be/BCfUnfSpDmM?t=315
https://youtu.be/BCfUnfSpDmM?t=416

### Steps to reproduce the problem

1. Create 2 or more characters and add them to a group. Make one easily killable.
2. `.go xyz -12212 -1959 133 309`
3. Kill the Vilebranch Speaker and start the encounter.
4. Let one character die and see that the Chained Spirits do not do anything.

### Extra Notes

Chained Spirit (ID: 15117)
Revive (ID: 24341)

It seems to be a Blizz-like bug in TBC that if a priest with Spirit of Redemption talent dies, then the Chained Spirit does not resurrect them. Proof:
https://www.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=317157
I also had a video showcasing the bug but I lost the link to it, sorry.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #11749: [ZG] Bloodlord Mandokir - Charge, Shout & Threat Wipe
### Current Behaviour

~~Charge is not followed by Intimidating Shout.~~
~~This mechanic does not wipe the tank's threat.~~
Both fixed by #11854

 - The Boss charges a random player.

 - Boss can cast mid-charge (see video in extra notes).

 - Sometimes will not Shout after a Charge (I've also seen him do a Charge -> Whirlwind -> Shout, when the Shout should come immediately after the Charge)

 - Shout is placing 2 auras on the player 19134 and 29544

### Expected Blizzlike Behaviour

The Boss first charges the target farthest away from him for the first charge, and the switches target if possible (probably to the second furthest target). Possibly inconsistent, but comments seem to confirm.

Edit: If there is no other player (like in a solo situation) then he will charge the same player.

After charging, the Boss casts Intimidating Shout and wipes the threat from his main target.

### Source

https://user-images.githubusercontent.com/100873791/168453800-d790aa87-2ca3-4047-95b9-26ec4aa94e5a.mp4

[From Wowhead comments](https://tbc.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=2826633):
>After the boss has charge that person, which is always the one furtest away from him

[From Wowpedia Talk Page](https://wowpedia.fandom.com/wiki/Talk:Bloodlord_Mandokir_(Classic)):
>Does the paladin dummy tactic work still? Mandokir seems to charge the raid at random now.

>Our pally "dummy" or punt pally was getting the initial charge but after one charge, Mandokir would charge a second raider in the group area.

https://youtu.be/-SDNeAQOHJY?t=41 notice that he charges the player farthest away from him, singled out from the rest of the raid. This can be seen in several videos.

Threat Wipe:

>This fight is about managing aggro, when it comes down to it. Seperate from the way he watches people, he'll occasionally charge random people. This charge reduces his aggro on the MT, so the situation we often had was that he'd charge, then make a beeline straight to a mage or a hunter and one-shot them. ([source](https://tbc.wowhead.com/npc=11382/bloodlord-mandokir#comments:id=2826602))

>The main issue in fighting this boss is getting the aggro back on the MT as quickly as possible after he charges. He seems to charge randomly, but in actuality, he charges anyone who is singled out away from the group and DPSing. Thusly, the easiest way to control him is to deliberately give him someone to single out, while the rest of the group huddles. Hunters work well, as they can Feign Death to aid in the MT's recovery of Mandokir. After Mandokir charges, he will move on the next highest aggro, which is not the MT since he partially dumps the threat associated with the highest aggro producer prior to the charge. ([source](https://wowpedia.fandom.com/wiki/Bloodlord_Mandokir_(Classic)?oldid=2287881#Controlling_Mandokir))

https://youtu.be/-SDNeAQOHJY?t=41 
https://youtu.be/yQIhi37rlXM?t=69
https://youtu.be/mEURNWfXusk?t=109
https://youtu.be/AGg9eJXz_vA?t=119
https://youtu.be/qTO85ph8MnM?t=41
https://youtu.be/qTO85ph8MnM?t=70
https://youtu.be/-X5w9olgqAg?t=55

### Steps to reproduce the problem

1. Create at least 2 characters and put them in a group.
2. `.go xyz -12212 -1959 133 309`
3. Kill the Vilebranch Speaker and start the encounter.
4. Place one target closer to Mandokir and the other far from him.

### Extra Notes

https://user-images.githubusercontent.com/100873791/170794452-bbccb694-73a9-4ade-af0e-51ce10a1478c.mp4

Bloodlord Mandokir (ID: 11382)
Charge (ID: 24408)
Intimidating Shout (ID: 19134)

From what I've observed, he seems to charge every 30-40s

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/5474b00a3d4f75245068535c26fa44c70f7ca6b4

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Chained spirits should revive the nearest player instead of random. Also added a check to not select the same spirit for 2 players.
-  Mandokir should charge the farthest target possible.
-  Removed double debuff for Frightening Shout.
-  Added a check to not cast spells during charge.

## Issues Addressed:

- Closes #11746
- Closes #11749
- Closes https://github.com/chromiecraft/chromiecraft/issues/3626

## Tests Performed:

- Tested in-game.

## How to Test the Changes:

1. Engage Mandokir with more than 2 players.
2. Let Mandokir or Ohgan kill players
3. See the nearest spirits revive the killed players.

## Known Issues and TODO List:

- [ ] Issues were not so clear, so I don't know if there is anything to be left or if I successfully addressed all the issues.

### CODE REVIEW

**Comment by Si1ker** [comment]
idk why I still care to make blizzlike stuff if people just gonna do/say whatever they want anyway.
image
image

**Comment by Gultask** [comment]
From Wowhead comments:

>After the boss has charge that person, which is always the one furtest away from him

From Wowpedia Talk Page:

>Does the paladin dummy tactic work still? Mandokir seems to charge the raid at random now.

>Our pally "dummy" or punt pally was getting the initial charge but after one charge, Mandokir would charge a second raider in the group area.

https://youtu.be/-SDNeAQOHJY?t=41 notice that he charges the player farthest away from him, singled out from the rest of the raid. This can be seen in several videos.

**Comment by Gultask** [comment]
This comment here is about the merged commit, not this PR.

About the charging bug. It affects both Threatening Gaze charge and the Threat Wipe charge. I'm thinking it's a deeper more generic issue:

1. He can cast during a charge
2. If I move, he will charge an empty space, and the character will slide a bit as shown in the video.

Movement does not trigger the Threatening Gaze charge anymore. This video is from an earlier commit, but the other parts are still bugged.

https://user-images.githubusercontent.com/100873791/170794452-bbccb694-73a9-4ade-af0e-51ce10a1478c.mp4

Also, somewhat unrelated but auto-attacks are not triggering the Threatening Gaze charge. I've added this to the original issues, but also mentioned here in case you miss it.

Threat Wipe is working fine from my end :)

**Comment by Nefertumm** [comment]
I changed threatening gaze, so it should be better now and triggered by auto attacks. I found that issue with charge and threatening gaze charge. He could cast whirlwind during charge, I added a check to avoid that. About player being able to move during charge, I don't know about that, I might ask for a sniff on that, since I don't know if it should root the player before charging or what...

**Comment by Gultask** [comment]
Hahahaha. Guess what, the charge thing is blizzlike: https://youtu.be/28EhZvGtf0s?t=28
Watch at 0.5x speed

**Comment by Nefertumm** [comment]
Lol, nice catch.

**Comment by Gultask** [comment]
Played around with the PR a bit.

 - [ ] I think the Threat Wipe charge is actually targeting the closest raider, instead of the farthest. That's what happened to me, at least.
 - [ ] DoT ticks are triggering Threatening Gaze's charge. Tested with Shadow Word: Pain rank 1. I've applied the DoT before the Threatening Gaze being cast, of course.

To-do list:

 - [ ] Boss cannot move or attack while casting Threatening Gaze.
 - [ ] No 100s cooldown between revives.
 - [ ] Guillotine is triggered at the start of the charge instead of the end of the charge.
 - [ ] Overpower doesn't work.

Also something. Playing around with the boss' movements and the terrain tells me that the teleport might be nice to be implemented, if possible.
In retail, the boss teleports the main threat holder if they're in an unreachable spot, and can even teleport *himself* to the player, although that mechanic is rarer and I've not worked out the conditions for it.
It's seen in [this video](https://youtu.be/yQIhi37rlXM?t=55), when the hunter overtakes their pet's threat and becomes the main target, the boss TPs them. Both behaviours can be [seen here](https://youtu.be/PLHmWYmHieg?t=22), with the TP-to-player mechanic seen at around 1:00. Another video [shows how instantaneous it can be](https://youtu.be/xVEUGYgf5u8?t=60).
Link to the TP issue: https://github.com/azerothcore/azerothcore-wotlk/issues/11750

May be interesting to note that the second video mentions that the strat of getting the boss stuck up there "might take 1 or 2 tries". My gut says that the boss keeps track if the player has already been TP'd, and if they have, he'll TP himself to the player instead of TP'ing the player again... Another theory could be that it's just chance-based.

**Comment by Nefertumm** [comment]
@Gultask there, the charge should be good now

**Comment by Gultask** [comment]
- [ ] If you LoS the farthest player, he will never Charge, but will Shout and wipe threat.
 - [ ] He can Shout mid-charge, I think. Because when he arrives at the target they won't be feared depending on distance. I had 3 characters standing in a line, and I'm pretty sure the one in the middle got feared but the farthest one didn't.

Also, forget the speculation I had about Charge being more selective. [This video](https://www.youtube.com/watch?v=fLb6KZLHeVE) shows that my idea doesn't hold water (he will always charge the caster, i.e. the farthest one)

**Comment by Nefertumm** [comment]
@Gultask sorry, now it should be good...

**Comment by Gultask** [comment]
No, no, don't be sorry. I'm here to help as much I can ^^
I'll take a look as well.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
