### PR TITLE
Core/Misc: Introduce a new task scheduler and move EventMap into its own source file

### PR DESCRIPTION
**Pull request by Viste**
This is a combination of #2240  and #2238 
## CHANGES PROPOSED:
-  Use std::function as callback (methods, lamdas & std::bind).
-  Uses std::chrono::duration as duration type (Milliseconds, Seconds...) with c++11 user defined literals we could just write "11s" for example (MSVS 2015, gcc & clang).
- Provides a lot of overloads for easier usage:
  - Static durations or random durations between min and max.
  - Named (with group ids - group id 0 is possible) or anonymous tasks.
  - Asynchronous tasks.
- Is adapted to the current needs of scripting:
  - Repeat tasks through the TaskContext
  - Schedule new tasks from the context.
  - Provides access to the times repeat counter of a task,
    this will help to schedule multi step events (dialogs for example).

See https://gist.github.com/Naios/6d143538abdc3d32fd2b for usage examples.

Big thanks to @Naios

 - also move scheduled map scripts counter methods into MapManage
-  Move EventMap into its own source file.
-  Move implementation details to .cpp.
- Add std::chrono::duration overloads to EventMap makes possible to write:
```c++
events.ScheduleEvent(1, Seconds(10));
// ... or ...
events.ScheduleEvent(2, Minutes(1) + Seconds(20));
// ... or with C++14 support:
events.ScheduleEvent(2, 45s);
```
## TESTS PERFORMED:
- Build
## HOW TO TEST THE CHANGES: 
 - this useless tests not my problem :)) 
## Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Viste** [comment]
scheduler part tested in #2238

**Comment by Viste** [comment]
No one wants a useless innovation. Those who want to write scripts easier can find I think.

**Comment by FrancescoBorzi** [comment]
what's the status of this? ready to be tested? if yes, what should be checked?

**Comment by Viste** [comment]
> what's the status of this? ready to be tested? if yes, what should be checked?
its ready from feb 9 but only 1% of people can test this lol because need write own script
also
> scheduler part tested in #2238

**Comment by FrancescoBorzi** [comment]
> You just need to check the existing scripts (all dungeons, part of the spells, npc) that everything is OK.

for this 99% of people can do it )

**Comment by Viste** [comment]
sad story but as always all needs only quests

**Comment by BarbzYHOOL** [comment]
no one knows what it's for (you included) so no one cares

also it requires some C++ devs to review this, not a simple quest tester

**Comment by Viste** [comment]
> no one knows what it's for (you included) so no one cares

CHANGES PROPOSED read it and you understand

**Pull request closed without merging**
