### PR TITLE
Ragnaros hammer orientation

### LINKED ISSUE #595: [RAID] MC Ragnaros' hammer falls facing the wrong direction.
**Description**: The hammer is falling so the side of the hammer is not visible to the player after Raganros is killed. Having farmed this countless times in retail, and claimed the Eye of Sulfuras myself, I know this is wrong.

**Expected behavior:** 
When the hammer falls, it should land in the lava with the side facing the players giving a full view of the epic hammer from the fight start position. This is the same direction Ragnaros is facing when the fight starts. A bit hard to describe, but if you go check the image you'll see what I mean. 

Right: https://www.flickr.com/photos/erocsid/4021735116/in/album-72157622608658698/
Wrong: https://imgur.com/a/Xi2t8

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/48908411-raid-mc-ragnaros-hammer-falls-facing-the-wrong-direction?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

- Fixed Ragnaros hammer when he dies
- Removed useless comments

###### ISSUES ADDRESSED:

Closes #595

##### TESTS PERFORMED:

- Compiles
- Tested
- Works

##### HOW TO TEST THE CHANGES:

- tele Molten Core
- Kill all bosses
- Fight Majordomo Executus but don't kill him
- Check Ragnaros
- Kill
- Confirm hammer orientation

##### Target branch(es):

Master

https://imgur.com/a/aodK4ha

### CODE REVIEW

**Comment by comix1988** [comment]
@Pondaveia I tested this PR but I find no difference. the hammer both before and after the fix is ​​oriented in the same direction.
before
before

after
Schermata da 2019-04-06 11-08-13

**Comment by Pondaveia** [comment]
Strange, I can't make this happen... without these changes the hammer will indeed face the player as reported.

**Comment by comix1988** [comment]
@Pondaveia 
gurada this my viedeo: the position of the hammer reported by me and the one reported in the issue are the same.
https://youtu.be/RfAS1z7Mnp4

I drew the right hammer position in this screenshot
hammer

**Comment by Pondaveia** [comment]
Ok noted, will see what I can do about it

**Comment by Pondaveia** [comment]
@comix1988 can you try this again?

**Comment by comix1988** [comment]
now work perfectly.
matrtello


good job @Pondaveia

**Comment by poszer** [comment]
Thank you @Pondaveia for this fix, and @comix1988 for testings :+1:

**Comment by BarbzYHOOL** [comment]
lol that will make the game better for sure!

**Pull request merged**
