### PR TITLE
fix(Scripts/Instances): Fixed some problems with getting proper unit'…

### LINKED ISSUE #5054: BWL Broken
## CURRENT BEHAVIOUR:

Broken bwl.
All access to creature instance(boss) like:
`instance->GetCreature(DATA_RAZORGORE_THE_UNTAMED)`
return nothing

## EXPECTED BLIZZLIKE BEHAVIOUR:

fixed bwl boss / instance

## STEPS TO REPRODUCE THE PROBLEM:

1. Build from #3673 
2. go into bwl the razorgore orb doesn't cast mc
3. razorgore can't reach p2 can't stop casting mc aura and so on.

## EXTRA NOTES:

#3673 Introduce bugs.
I give some details here.
https://github.com/azerothcore/azerothcore-wotlk/commit/6ef73413131e58dddd45524d51b57015b0ca3b7b#commitcomment-48848790

Globally the bwl fix removed bosses guid because trinity does that, but they introduced code that replace the old way for finding boss creature instance.
You have 2 options to fix it:
- Introduce TC InstanceScript code then we could update all instances script.
- Reintroduce the removed guid

## CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97508257-bwl-broken?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #10156: [BWL] Chromaggus doesn't come out of his cage after pulling the lever.
CURRENT BEHAVIOUR:

Chromaggus stays in his cage after pulling the lever.

EXPECTED BLIZZLIKE BEHAVIOUR:

After the lever gets pulled, he should come out and attack the players in the room.

SOURCE:

https://classic.wowhead.com/guides/broodlord-lashlayer-blackwing-lair-strategy

STEPS TO REPRODUCE THE PROBLEM:

Go to chromaggus, bwl.

NOTES

https://classic.wowhead.com/guides/chromaggus-blackwing-lair-strategy

AC HASH/COMMIT:
0c35369
OPERATING SYSTEM:
Windows 11
MODULES:
mod-progression-system
CUSTOMIZATIONS:

### PR DESCRIPTION
**Pull request by UltraNix**
…s GUID in BlackwingLair raid.

Fixes #5054
Fixes #10156

## Issues Addressed:

- Closes #5054
- Closes #10156

## Tests Performed:

- Not tested.

## How to Test the Changes:

Go to chromaggus, bwl. and start the event.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
Did you do anything about Razorgore fight? Why is  5054 linked? :)

**Comment by temperrr** [comment]
Also not noticing anything different with the lever on chromaggus, still ahve to click on the gate to get him out

**Comment by UltraNix** [comment]
#5054 is not strictly about Razorgore, but the instance scripting itself.

**Comment by UltraNix** [comment]
Should be okay now.

**Comment by temperrr** [comment]
Tested,

Doggy comes out when pulling the lever, the gate opens on itself.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
