### PR TITLE
fix (Core/Gossip): gossipMenuLocale doesn't work

### PR DESCRIPTION
**Pull request by AlvinZhu**
## Changes Proposed:
-  fix gossipMenuLocale
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1. login with zhCN Clients.
2. .go xyz  -6032.287 -2497.3784 309.93246 2.69
3. See if the NPC(ID 3836)'s  gossip Menu is Chinese.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/74db38ea14be21d27af6cec56f84687d7b9f3aef

**Comment by AlvinZhu** [comment]
> [74db38e](https://github.com/azerothcore/azerothcore-wotlk/commit/74db38ea14be21d27af6cec56f84687d7b9f3aef)

Yes, I tried to fix the issue caused by this commit.
in this commit, if the text were found, English is always used, regardless of whether the default language is English or not.

**Comment by Kitzunu** [comment]
Yea sure I get that, but this is basically reverting thst commit, which will cause the issue that allegedly fixed to regress. Can you double check that please

**Comment by AlvinZhu** [comment]
> Yea sure I get that, but this is basically reverting thst commit, which will cause the issue that allegedly fixed to regress. Can you double check that please

I see, according to PR（#8396）'s purpose, he wants to force gossip_menu_option_locale to be ignored to motivate people to improve broadcast_text_locale.
But after more than one year, the fix for broadcast_text_locale is not finished. I don't think this is a good idea.
I will close my PR.

**Review by 0356738481 — COMMENTED** [review]
Hh

**Pull request closed without merging**
