### PR TITLE
Improove check setted variables

### PR DESCRIPTION
**Pull request by Bogir**
## Changes Proposed:
-  Improve check settled variables and remove duplicate or unnecessary strings 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Bogir thanks for your contribution, however the build fails with:

```
[ 97%] Built target scripts
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/World/World.cpp:848:112: fatal error: comparison of integers of different signs: 'int32' (aka 'int') and 'uint32' (aka 'unsigned int') [-Wsign-compare]
    if (int32(m_int_configs[CONFIG_START_HONOR_POINTS]) < 0 || int32(m_int_configs[CONFIG_START_HONOR_POINTS]) > m_int_configs[CONFIG_MAX_HONOR_POINTS])
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:2834: src/server/game/CMakeFiles/game.dir/World/World.cpp.o] Error 1
```

can you please fix?

**Comment by Bogir** [comment]
> can you please fix?

MSVC can't find any errors.
What must I do?

изображение

**Comment by FrancescoBorzi** [comment]
@Bogir check the errors here on GitHub: 

image

click on "Details"

**Comment by Bogir** [comment]
> click on "Details"

Thanks! I'll try to fix it =)

**Comment by Bogir** [comment]
done

**Comment by FrancescoBorzi** [comment]
@Bogir the build is still failing :(

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Bogir** [comment]
> @Bogir the build is still failing :(

What must I do to repeat your fails? :)

**Comment by FrancescoBorzi** [comment]
@Bogir strange, it looks like fine now

**Pull request merged**
