### PR TITLE
fix(Core): Crashfix.

### LINKED ISSUE #11281: RealmCrash when team cancel skirmish arena and get into queue of rated arenas
### Current Behaviour

We've disabled all arena system, because by doing this steps the entire realm crash.

By joining skirmish, leaving queue and joining rated arenas is crashing the realm.

### Expected Blizzlike Behaviour

-

### Source

_No response_

### Steps to reproduce the problem

1. Make a arena team
2. Invite your team mate into your party
3. Join queue of skirmish arena
4. Cancel queue and inmediatly join rated arenas queue.

### Extra Notes

_No response_

### AC rev. hash/commit

446546f

### Operating system

Debian 10 x64

### Custom changes or Modules

Anticheat
Chat transmitter
Duel reset
Transmog
World chat

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11281

## Issues Addressed:

- Closes #11281

## Tests Performed:

- Not tested.

## How to Test the Changes:

Make a arena team
Invite your team mate into your party
Join queue of skirmish arena
Cancel queue and inmediatly join rated arenas queue.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@nestormourino @r0m1ntik @Kitzunu Please, test it.

**Comment by UltraNix** [comment]
@mpfans Test it.

**Comment by mpfans** [comment]
testing

**Comment by nestormourino** [comment]
As I tested, the crash still happening. Sorry but I don't have access to crashlog.

**Comment by UltraNix** [comment]
@mpfans Without it, I can't even say if it it related to this topic.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
