### PR TITLE
Core/Scripts: Karazhan rework

### LINKED ISSUE #779: Core/Script: Karazhan Chess Event [$250]
**Description**:The karazhan chess event does not work

**Current behaviour**: 
If you try to enter and talk to the king of your faction, the event does not start

**Expected behaviour**: Speaking to the king of his own faction, the event should start correctly allowing each player in the raid to take possession of a piece on the board to properly perform the fight.(post a video demonstration of how it should work) https://www.youtube.com/watch?v=b496Mc9A4U0

**Steps to reproduce the problem**:
1. enter karazhan
2. try to start the event by talking to the king of his own faction

**AC hash/commit**: 29f4a1e

**Operating system**: Linux

[Bountysource](https://www.bountysource.com/issues/54545022-bug-chess-event?utm_source=54545022&utm_medium=shield&utm_campaign=ISSUE_BADGE)

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/54545022-core-script-karazhan-chess-event?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Viste**
##### CHANGES PROPOSED:
-  Rewrite instance scripts, there is no reason for karazhan to be broken in 2019
-  For now done:
- [x] Maiden of Virtue
- [ ] Terestian Illhoof
- [ ] Chess Event
- [ ] The Curator
- [ ] Nightbane
- [x] Bells

##### KNOWN ISSUES AND TODO LIST:
- [x] depends #2179 
- [ ] depends #2238
- [ ] depends #2240
##### Target branch(es):master

### CODE REVIEW

**Comment by pklloveyou** [comment]
Look forward to this RP

**Comment by Viste** [comment]
@pklloveyou ??

**Comment by pklloveyou** [comment]
There are a lot of problems with this instance, so I look forward to this RP, you can fix them.

**Comment by Viste** [comment]
@pklloveyou i think this PR will be fineshed only in september

**Comment by Viste** [comment]
no sense in this anymore

**Pull request closed without merging**
