### PR TITLE
fix(DB/SAI): Missings spells for few creatures in Blade's Edge Mountains

### PR DESCRIPTION
**Pull request by Grimdhex**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19594 and https://github.com/chromiecraft/chromiecraft/issues/5408#issue-1666880763

## SOURCE:

The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .go creature 19993 and check that the creature cast knockdown
2. .go creature 22160 and check that the creature cast knockdown
3. .go creature 19995 and check that the creature cast Cleave

## Known Issues and TODO List:

- [X] Comparing to the "confirmed" issue, I wasn't able to get : Fire Nova Totem with Bladespire Shaman / Bloodmaul Buzz with Bloodmaul Mauler on live servers (retail and cata) --> Edit: WoWhead sources so I think that my check on live servers can confirm that these creatures doesn't cast mentioned spells.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Grimdhex** [comment]
@Rorschach91 how have you done your checks before to confirm issues ? Because I'm unable to get : Fire Nova Totem with Bladespire Shaman / Bloodmaul Buzz with Bloodmaul Mauler on live servers (retail and cata)

**Comment by Rorschach91** [comment]
I used WowHead Wotlk classic as reference.

**Comment by Grimdhex** [comment]
> I used WowHead Wotlk classic as reference.

Ok, unfortunately WoWhead is not very reliable. Here, I can confirm with a check on live server than Bladespire Shaman doesn't cast Fire Nova Totem and Bloodmaul Mauler doesn't cast Bloodmaul Buzz.

**Comment by Rorschach91** [comment]
....Wow. So I can't trust wowhead either.
I get it. I reactivate my blizzard account. 
I shall not make the same mistake another time. 
Thank you for the warning.

**Comment by alecsci** [comment]
Tested
1. Bloodmaul Taskmaster - Cast Knockdown ✅ 
2. Bloodmaul Mauler - Cast Knockdown ✅ 
3. Bladespire Brute - Does not cast Cleave ❌ 

Is there a condition that must be met for the 3. ?

**Comment by Grimdhex** [comment]
> Hi @Grimdhex I tested:
> 
> 1. Bloodmaul Taskmaster - Cast Knockdown ✅
> 2. Bloodmaul Mauler - Cast Knockdown ✅
> 3. Bladespire Brute - Does not cast Cleave ❌
> 
> Is there a condition that must be met for the 3. ?

Hmmm... They are no conditions for Cleaves, but everything looks fine. I've check another creature that use the same spell and there are no differences. I suspect a conflict with "Timed actionlists". I will look deeper.

**Comment by alecsci** [comment]
@Grimdhex yes, good observation.
Bladespire Brute has timed actions, and between those the Cleave is not mentioned compared to 
Bladespire Brute - Script - Cast Bloodmaul Intoxication which is a spell also used by this NPC.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
