### PR TITLE
fix(DB/Creature): Add data for creature template models.

### PR DESCRIPTION
**Pull request by heyitsbench**
This PR is being opened primarily just to show that work is being done on this and also to garner feedback if anyone wants to comment/suggest something.

## Changes Proposed:

This PR proposes changes to:
-  [X] Database.

## Issues Addressed:

- Closes probably a few issues. Pretty cool.

## SOURCE:

The changes have been validated through:
- [X] Sniffs

## Tests Performed:

This PR:
- [X] Has not been tested.
- [X] This pull request will require further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request will requires further testing.
1. Look at every creature.
2. Every.
3. Single.
4. One.

## Known Issues and TODO List:

Currently going through by VerifiedBuild number. Still need to do builds 9767, 11159, and of course 12340. End goal is to have any creatures with an entry that do not exist in current sniffed data be set to 0, any `difficulty_entry` creatures based off a creature that does have sniffed data will have a value of 1 (just to distinguish them), and any creatures that will be based off sniffed data (either display ID, scale, probability, or a combination) but have some change due to a Classic change will have a value of 12340.

- [ ] Finish the above.
- [ ] Remove the additional queries that I have just to keep progress.
- [ ] Make a proper delete query to make sure no custom entries would be removed.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Just want to remind you that you need the delete queries :D

**Comment by heyitsbench** [comment]
> Just want to remind you that you need the delete queries :D

Didn't read the todo list, rookie mistake.

**Comment by Kitzunu** [comment]
yikes

**Comment by heyitsbench** [comment]
Closing this for now, gonna split it up into smaller chunks since doing all 40k entries and keeping track of it all is...yikes.

**Pull request closed without merging**
