### PR TITLE
fix(DB/Spells): Moonkin Form - remove TBC leftover from mana restore …

### LINKED ISSUE #8851: [Druid/Spell]Moonkin Form have half chance proc mana restore when not equip two hands weapon
### Current Behaviour

RT

### Expected Blizzlike Behaviour

chance should be same

### Source

_No response_

### Steps to reproduce the problem

1.Use a Druid and Cast Moonkin Form
2.Equip double hand weapon
3.Combat with Heroic Training Dummy
4.See mana restore proc

5.Equip one hand or main hand weapon and offhand
6.Combat with Heroic Training Dummy
7.See mana restore proc

### Extra Notes

_No response_

### AC rev. hash/commit

a25eae3

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…passive aura.

Fixes #8851

## Changes Proposed:
-  https://wowpedia.fandom.com/wiki/Moonkin_Form?oldid=2395546
`Patch 3.0.2 (2008-10-14): No longer increases your attack power or causes you to regenerate mana off melee attacks, but now has a chance to cause you to instantly regenerate 2% of your total mana every time you critically hit with a spell.`

## Issues Addressed:

- Closes #8851

## Tests Performed:

- Not tested.

## How to Test the Changes:

https://github.com/azerothcore/azerothcore-wotlk/issues/8851#issuecomment-973117000

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by claudiodfc** [comment]
## Tests executed:
- Learned Moonkin using talents.
- Cheats for power, casttime and cooldown.
- Wrath, Starfire, Insect Swarm, Moonfire and Hurricane critical hits restored 2% of the player's total mana.
- Meele hits from one-handed and two-handed weapons didn't proc Moonkin form's mana replenishment.

**Comment by Nefertumm** [comment]
> ## Tests executed:
> * Learned Moonkin using talents.
> * Cheats for power, casttime and cooldown.
> * Wrath, Starfire, Insect Swarm, Moonfire and Hurricane critical hits restored 2% of the player's total mana.
> * Meele hits from one-handed and two-handed weapons didn't proc Moonkin form's mana replenishment.

Thank you for the test, did you test with one-handed and two-handed weapons for spells too right?

**Comment by claudiodfc** [comment]
> 

You mean casting spells with one or two handed weapons?

**Comment by bgcfb** [comment]
> 

It is wrong way to test if you cheat cooldown
I tested and not work

**Comment by claudiodfc** [comment]
> @claudiodfc It is wrong way to test if you cheat cooldown pls test follow #8851 I tested and not work

why is it a wrong way to test with cheat cooldown, when it only removes the global cooldown?

Also if you swap from a weapon without crit to one with crit, such as an off hand + one handed vs Two handed weapon, It's only normal that the chance of mana restore increases. Since the test didn't even specify specific stats or gear, I don't see the point of this bug report.

Also It's only normal that you get increased mana depending on gear with more or less intellect, since that's what 2% total mana means.

Anyways, meele weapon swings aren't restoring mana, if they ever did, I didn't bother to test on master to confirm this.

If you want a real test, send me the exact gear you're using to execute the test so that we can compare the numbers.

I never got any 9k mana with spells or weapon swings, so depending on the servers that you're playing, they might have other bugs that are inducing the problem you just reported.

**Comment by bgcfb** [comment]
pls look at #8851 before you test it

**Comment by claudiodfc** [comment]
Thanks for ignoring all my points as if I didn't read. My test is done, I don't care about this anymore.

**Pull request merged**
