### PR TITLE
feat(Deps/Ace): remove ace library. Part 2

### LINKED ISSUE #3451: Remove ACE dependence [$300]
# TASK
- [x] `ASSERT` - #4950
- [x] `Configuration` - #4608
- [x] `Method_Request` - #3459
- [x] `Stack_Trace` #6574
- [x] `Task` #5454
- [x] `Guard_T` - #4821
- [x] `Event_Handler` (signal) - #4877
- [x] `Based` #6574
- [x] `TSS_T` #5454
- [x] `INET_Addr` #6574
- [x] `Reactor` #5679
- [x] `Acceptor` #6574
- [x] `Future` #5611
- [x] `Queue` #5611
- [x] `Basic_Types`
- [x] `Semaphore`  - #4951
- [x] `AutoPtr` - #3454
- [x] `OS_NS_time` - #3455
- [x] `Atomic_Op` - 4a9476b
- `Thread` (there is a separate issue for this with a 150$ bounty: https://github.com/azerothcore/azerothcore-wotlk/issues/99)

**The list will be replenished**

# Steps
- [x] 1. Update `acelite`, set lib to `STATIC` and disable incorrect fix `std::auto_ptr` #3450
- [x] 2. Rework `Config` #3453 
- [x] 3. Delete `AutoPtr` #3454
- [x] 4. Replace `Ace Atomic` 4a9476b
- [x] 5. Replace `Ace Time` #3455
- [x] 6. Replace `ACE_Method_Request` #3459
- [x] 7. Replace `ACE_Configuration` #4608
- [x] 8. Replace `ACE_Thread_Mutex` | `ACE_GUARD` #4821
- [x] 9. Replace `ACE_Event_Handler` #4877
- [x] 10. Replace `ACE_ASSERT` #4950
- [x] 11. Delete `ACE_Semaphore` #4951
- [x] 12. Delete `ACE_TSS` #5454
- [x] 13. Delete `Future` and `Queue` #5611
- [ ] 14. `The end` #6980 and #5679

<bountysource-plugin>

---
There is a **[$300 open bounty](https://www.bountysource.com/issues/92874324-remove-ace-dependence?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
-  Just remove `deps/acelite`

## Issues Addressed:
- Closes #3451

## Known Issues and TODO List:
- [x] #5676
- [x] #5653 
- [x] #5640 
- [x] #5638 
- [x] #5626 
- [x] #5617 
- [x] #5454 
- [x] #4951 
- [x] #6980

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan I think it's better to split this huge PR in 2 parts:

- all the changes to our source files in `src/`
- the actual removal of the `deps/acelite` directory

Also please fix the headers license stuff

**Comment by Winfidonarleyan** [comment]
Wair #6980

**Comment by Winfidonarleyan** [comment]
Bye

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Kitzunu** [comment]
👏

**Pull request merged**
