### PR TITLE
fix(DB/SAI): acore_string missing locale_zhCN

### PR DESCRIPTION
**Pull request by XiaoSeee**
Added Chinese translation for the convenience of Chinese players like me

## Changes Proposed:
-  acore_string add locale_zhCN

## Issues Addressed:
- acore_string missing locale_zhCN

## SOURCE:
The source is uncertain. I have integrated a lot of translations provided on local forums, and I feel fine.

## Tests Performed:
- I test it on Windows

## How to Test the Changes:
- 

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by cjl3230** [comment]
When I enter pinfo [charsname], the server crashes. Because the format of the acore_string entry 749 locale_zhCN field is wrong (I use the Chinese client).

**Comment by XiaoSeee** [comment]
翻译格式有问题，不知道是后来改了字符串，还是当时就错了。可以暂时把zhCN里面的内容清空，后面在提个PR修改吧。

**Comment by cjl3230** [comment]
@XiaoSeee 好的,今天用pinfo的时候 发现服务端异常了,原来azerothcore还有chinese ^ ^

**Comment by LukasVolgger** [comment]
> 翻译格式有问题，不知道是后来改了字符串，还是当时就错了。可以暂时把zhCN里面的内容清空，后面在提个PR修改吧。

Hello @XiaoSeee , can you please translate it for us so everybody can read it?

**Comment by XiaoSeee** [comment]
> > 翻译格式有问题，不知道是后来改了字符串，还是当时就错了。可以暂时把zhCN里面的内容清空，后面在提个PR修改吧。
> 
> Hello @XiaoSeee , can you please translate it for us so everybody can read it?

There is a translation problem with format, only affects zhCN. I will create RP later

**Pull request merged**
