### PR TITLE
(fix/GObjects) Chair selectable though occupied Part 1

### PR DESCRIPTION
**Pull request by ghost**
## Changes Proposed:
-  This is the first part of fixing chairs being able to sit down though an NPC is already sitting on that specific chair.

## How to Test the Changes:

This is the first part of (I guess?) many to follow (just as the guards emotes/abilities)

1.  .tel Valiance Keep
2. Go to Officer Blythe
3. You shouldnt be able to select his chair because he is sitting on it already

## Known Issues and TODO List:

- just a guess but I guess ( lol ) that there are many many more chairs which are permanently occupied by NPCs but still selectable...

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Banehammer have you tested it in game? can you provide some screenshots/videos about your results?

**Comment by stoudtlr** [comment]
confirmed. no matter where you put your cursor you no longer get the gear icon that lets you select the chair to sit down.  only able to select Officer Blythe.
image

**Comment by FrancescoBorzi** [comment]
@Banehammer what's the status of this PR?

**Comment by Nefertumm** [comment]
It seems he deleted his account :(

**Pull request closed without merging**
