### PR TITLE
fix(Core): Crash fix for attacks

### LINKED ISSUE #6145: CRASH C0000005 ACCESS_VIOLATION
**CURRENT BEHAVIOUR:**

[7f90f41ba6e3+_worldserver.exe_[31-5_13-2-19].txt](https://github.com/azerothcore/azerothcore-wotlk/files/6567894/7f90f41ba6e3%2B_worldserver.exe_.31-5_13-2-19.txt)

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Not crash? attack quilboar as normal

**SOURCE:**
whenever I attack the quilboars in durotar, and other random spots

**STEPS TO REPRODUCE THE PROBLEM:**
whenever I attack the quilboars in durotar, and other random spots

**OPERATING SYSTEM:**
Windows 10

Commit 7f90f41ba6e3

**MODULES:**
AHbot
Anticheat
CFBG
Eluna lua
transmog
Weapon visual
weekend XP

**CUSTOMIZATIONS:**
Classless system Astoriacore

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98815923-crash-c0000005-access_violation?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Another check to prevent crashing

## Issues Addressed:

- Closes #6145

## Tests Performed:

- Didn't test yet but maybe someone can test before me

## How to Test the Changes:

1. Meele attack NPCs or try reproducing the issue

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
@AndrewQ91 can you test this please?

**Comment by Viste** [comment]
you are idiot???

**Comment by lineagedr** [comment]
This ```if (cleanDamage != nullptr)``` // Here we check if cleanDamage is not null
And This
```if (cleanDamage)``` // Here we also check if cleanDamage is not nullptr

is the same. In both statements we're checking if cleanDamage is pointing to a valid object.

So this commit is doing nothing.

**Comment by Viste** [comment]
https://media.tenor.co/videos/16483b809ddf9aa9bcb14e9a834621bc/mp4

**Comment by Viste** [comment]
> This `if (cleanDamage != nullptr)` // Here we check if cleanDamage is not nullptr
> And This
> `if (cleanDamage)` // Here we also check if cleanDamage is not nullptr
> 
> They're both the same. In both statements we're checking if cleanDamage is pointing to a valid object.
> 
> So this commit is doing nothing.

Just leave it...

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6145#issuecomment-864565363

**Comment by claudiodfc** [comment]
> This `if (cleanDamage != nullptr)` // Here we check if cleanDamage is not nullptr
> And This
> `if (cleanDamage)` // Here we also check if cleanDamage is not nullptr
> 
> They're both the same. In both statements we're checking if cleanDamage is pointing to a valid object.
> 
> So this commit is doing nothing.

But if you compare a nullptr to a 0 you're also getting an exception right?

**Comment by claudiodfc** [comment]
My fix is checking for both the literal, integer and nullptr:
This is the reason people replaced NULL with nullptr, because pointers aren't literals.

https://stackoverflow.com/questions/20509734/null-vs-nullptr-why-was-it-replaced

**Comment by lineagedr** [comment]
> > This `if (cleanDamage != nullptr)` // Here we check if cleanDamage is not nullptr
> > And This
> > `if (cleanDamage)` // Here we also check if cleanDamage is not nullptr
> > They're both the same. In both statements we're checking if cleanDamage is pointing to a valid object.
> > So this commit is doing nothing.
> 
> But if you compare a nullptr to a 0 you're also getting an exception right?

They're the same. Nullptr was created to avoid confusion between integers 0 and NULL but regardless of using nullptr, 0, NULL the result will be the same.

**Comment by claudiodfc** [comment]
then what do you suggest @lineagedr

**Comment by lineagedr** [comment]
@claudiodfc Well, it's simple. Just take a close look at his Unit.cpp. 
https://gist.github.com/AndrewQ91/e7006e4b3fc9be3727fe407ca48eaca7 Line: 808 :)

**Pull request closed without merging**
