### PR TITLE
feat(Core/Player)Add quest failure sound when inventory is full or quest failed

### LINKED ISSUE #20193: Failure sound when inventory is full
### Current Behaviour

When we validate a quest and our inventory is full, the sound "failure" is not played.

### Expected Blizzlike Behaviour

When you validate a quest that cannot be validated because of a full inventory, a failure sound is played.

### Source

Blizzard server

### Steps to reproduce the problem

1. validate a quest that gives an object with a full inventory

### Extra Notes

_No response_

### AC rev. hash/commit

[e72d0f6](https://github.com/azerothcore/azerothcore-wotlk/commit/e72d0f6dc502424580a1cdfcccecced1838cd927)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Exitare**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:
- Closes #20193

## SOURCE:

The changes have been validated through:
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)

[Sound](https://www.wowhead.com/sound=847/igquestfailed)

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Fill up your inventory with items
2. .quest add 1060
3. Hear the sound of failure

## Known Issues and TODO List:

- [ ] While it does work, i dont know whether this is the correct way of playing the sound. 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Grimdhex — APPROVED** [review]

**Comment by TheSCREWEDSoftware** [comment]
@Grimdhex @Exitare sorry for the ping, is there a way to know if this PR change isn't playing for every player?

**Comment by Exitare** [comment]
No it should not play for all players. I’ll investigate. Sorry if that caused any unintentional side effects. :/

**Comment by TheSCREWEDSoftware** [comment]
I just wanted to make sure! and dont have to be sorry for anything, we are all humans mistakes happen and this one is an annoyance sound.

**Comment by Takenbacon** [comment]
`PlayDirectSound` takes a target argument, if it uses the default argument of nullptr (which it does), it sends it out to everyone in range.

Changing the code to: `PlayDirectSound(QUEST_SOUND_FAILURE, this);` should fix it

**Comment by Exitare** [comment]
i am already on it :) 
Thank you for providing feedback!

**Pull request merged**
