### PR TITLE
fix(CORE): Boss threat pulse

### LINKED ISSUE #13554: [AQ40] Princess Huhuran does not aggro whole raid
https://github.com/chromiecraft/chromiecraft/issues/4303
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Princess Huhuran does not cause the whole raid to enter combat when agroed

### Expected Blizzlike Behaviour

All raid members should be put into combat after a short delay

### Source

image
https://www.bluetracker.gg/wow/topic/eu-en/116562109-how-do-aggro-and-threat-work-in-wow/

### Steps to reproduce the problem

with 2+ characters
.tele aq40 (Both)

.go c id 15509
aggro

### Extra Notes

potentially related [4299](https://github.com/chromiecraft/chromiecraft/issues/4299) [4301](https://github.com/chromiecraft/chromiecraft/issues/4301) [4303](https://github.com/chromiecraft/chromiecraft/issues/4303) [4305](https://github.com/chromiecraft/chromiecraft/issues/4305)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #13555: [AQ40] Twin Emperors do not aggro whole raid
https://github.com/chromiecraft/chromiecraft/issues/4305
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Twin Emperors do not cause the whole raid to enter combat when agroed

### Expected Blizzlike Behaviour

All raid members should be put into combat after a short delay

### Source

image
https://www.bluetracker.gg/wow/topic/eu-en/116562109-how-do-aggro-and-threat-work-in-wow/

### Steps to reproduce the problem

with 2+ characters
.tele aq40 (Both)

.go c id 15275
aggro

### Extra Notes

potentially related [4299](https://github.com/chromiecraft/chromiecraft/issues/4299) [4301](https://github.com/chromiecraft/chromiecraft/issues/4301) [4303](https://github.com/chromiecraft/chromiecraft/issues/4303) [4305](https://github.com/chromiecraft/chromiecraft/issues/4305)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #13556: [AQ40] Sartura does not aggro whole raid
https://github.com/chromiecraft/chromiecraft/issues/4301
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Sartura does not cause the whole raid to enter combat when agroed

### Expected Blizzlike Behaviour

All raid members should be put into combat after a short delay

### Source

image
https://www.bluetracker.gg/wow/topic/eu-en/116562109-how-do-aggro-and-threat-work-in-wow/

### Steps to reproduce the problem

with 2+ characters
.tele aq40 (Both)

.go c id 15516
aggro

### Extra Notes

potentially related [4299](https://github.com/chromiecraft/chromiecraft/issues/4299) [4301](https://github.com/chromiecraft/chromiecraft/issues/4301) [4303](https://github.com/chromiecraft/chromiecraft/issues/4303) [4305](https://github.com/chromiecraft/chromiecraft/issues/4305)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #13557: [AQ40] Bug Trio does not aggro whole raid
https://github.com/chromiecraft/chromiecraft/issues/4299
### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Bug Trio do not cause the whole raid to enter combat when agroed

### Expected Blizzlike Behaviour

All raid members should be put into combat after a short delay

### Source

image
https://www.bluetracker.gg/wow/topic/eu-en/116562109-how-do-aggro-and-threat-work-in-wow/

### Steps to reproduce the problem

with 2+ characters
.tele aq40 (Both)

.go c id 15544
aggro

### Extra Notes

potentially related [4299](https://github.com/chromiecraft/chromiecraft/issues/4299) [4301](https://github.com/chromiecraft/chromiecraft/issues/4301) [4303](https://github.com/chromiecraft/chromiecraft/issues/4303) [4305](https://github.com/chromiecraft/chromiecraft/issues/4305)

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:

The event on combat start allows bosses in raids to check for players who aren't in combat with the boss but are in the raid and adds them to the encounter threat list.

The pulse will happen every 2s (two seconds).

## Issues Addressed:

- Closes #13554 
- Closes #13557 
- Closes #13556 
- Closes #13555

## SOURCE:

The source of the change is included on each issue.

## Tests Performed:

Not tested yet.

### Test 1 - Raid setting
with 2+ characters on raid group
.tele aq40 (Both)
.go c id 15275
aggro

### Test 2 - World creatures
With 2+ characters in group, attacking monsters should only put the attacker in combat

## Known Issues and TODO List:

- [ ] Tests must be completed.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
How is this going to interact with spells such as Vanish, Invisibility and Feign Death?

**Comment by claudiodfc** [comment]
That's a good question. I'm not sure how that should be treated. Suggestions?

**Comment by Gultask** [comment]
This is all that I could find.

>When they changed the instance raid boss mechanics, it only works now if you are the last one alive in most cases. An engaged raid boss has a constant pulse that engages combat, this was added to prevent people from OOC rezzing, which was pretty big during the MC rush. So, while the boss will immediately deaggro you, if there is anyone else alive in the raid, you will be thrown back into combat in a matter of seconds. ([source](https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/43761762))

>But when the leader does call a wipe, try to get somewhere safe and feign, it can often save your armor bill and a run from the graveyard.  If you are an Engineer with an army knife or jumper cables you may even be able to rez your companions after you get out of combat. ([No mention of that mechanic, but it honestly reads like a cheap article](https://wowwhimsy.wordpress.com/tag/feign-death/))

>if you are feigned and everybody else dies the boss will leave combat and reset.  
>>Heroic bosses yes. Raid bosses no. Many of the comments were in reference to raids. Unless of course they broke it at some point between wotlk and cata.
>>>If you're the last one alive, it will drop combat and reset the boss, even in raids. It depends on when the combat pulses go out if you try it before everyone else is dead--if you Feign and a pulse goes out before the boss resets, you get put back in combat.  ([source](https://www.mmo-champion.com/threads/826829-Feign-Death-Vanish-Invisibility?p=10021430&viewfull=1#post10021430))

>Some classes have abilities that remove them from combat instantly. However, if they are [dotted](https://wowpedia.fandom.com/wiki/Damage_over_Time) they will usually be brought back into combat the next time they take damage. Note that these abilities no longer remove you from combat during Boss Fights (only at the end of wipes if you time it correctly). ([source](https://wowpedia.fandom.com/wiki/Combat))

**Comment by claudiodfc** [comment]
So all in all, this PR accomplishes most of the behaviors.
The following abilities will end combat and drop aggro if you're the last one alive but, you will be flagged `in combat` if an encounter is still happening:
- [x] Shadowmeld
- [x] Vanish
- [x] Stealth
- [x] Feign Death
- [x] Invisibility
- [ ] Divine Intervention (I'm not sure how are bosses supposed to react to this spell)

**Comment by Maelthyrr** [comment]
The main issue with this PR is that not really fix the problem. We shouldn't need to check every 2sec if a player is missing. The combat system is just uggly and we need to port the Treeston system but it's a big work. For me it's more a hack fix that we will add a certain cpu charge with lot off players.

**Comment by heyitsbench** [comment]
> For me, it's more a hack fix and it will add a certain CPU charge for servers with a lot of players.

And what of the blue post source? I can understand your want to use a system that doesn't require this pulse, but calling this a hackfix isn't necessarily true, assuming the blue post was honest.

**Comment by Maelthyrr** [comment]
> > For me, it's more a hack fix and it will add a certain CPU charge for servers with a lot of players.
> 
> And what of the blue post source? I can understand your want to use a system that doesn't require this pulse, but calling this a hackfix isn't necessarily true, assuming the blue post was honest.
> 
> I could see maybe adding a config option for this threat pulse to alleviate CPU power as an interim solution, especially since it very well may be blizzlike.

My mistake. I just read the source of the report. I didn't think that was possibly a real system use by blizzard.

**Comment by Maelthyrr** [comment]
@claudiodfc Hi, I've talked with some other senior devs about your PR to move forward. The main issue is the usage of event maps is not appropriate for general creature levels. I don't have the technical reasons but if you want I've found a similar PR done on TC if you want to compare to replace the events map.

https://github.com/TrinityCore/TrinityCore/commit/d57193df444b719757ae1da4a5f19e204074f6ae

In any case, thanks for your contribution and sorry for my last message,  and for the absence of answers since one month.

**Pull request closed without merging**
