### PR TITLE
Core/Collision: Fix typo in VMap BIH generation.

### LINKED ISSUE #5768: Blink in Multiple Cave Systems Clipping to Roof
**CURRENT BEHAVIOUR:**

Originally reported: @karakter222 on Discord.

Mage blink is currently clipping through the walls of at least two identified cave systems and onto the roof. The areas accessed this way are unfinished, untextured, and definitely not meant to be seen by players. 

The two cave systems are Stonesplinter cave in Loch Modan, and Coldridge cave in Dun Morogh. Others that share this model may also be affected.

https://user-images.githubusercontent.com/81782124/117684543-40aabd00-b1f4-11eb-9050-befdfc11407e.mp4

(Note that the faster run speed was turned off later in case it was affecting Blink somehow, and it made no difference.)

https://user-images.githubusercontent.com/81782124/117687544-0db5f880-b1f7-11eb-9cfa-4ab96d26dfca.mp4

Shot from @karakter222 from within Chromie:
karak-blink1

**EXPECTED BLIZZLIKE BEHAVIOUR:**

Blink should not teleport you through walls.

**SOURCE:**

I don't think this claim is controversial.

**STEPS TO REPRODUCE THE PROBLEM:**

1. To access Stonesplinter, .go c 9264. That will port you to a random mob halfway through the cave.
2. Run around spamming Blink. Stoneplinter is much the easier of the two caves to get this to work in.

For Coldridge - .go c 1502 will take you to the boss. Coldridge is harder to glitch, but karakter got it to work from here:
karak-blink2

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
rev. 0079034d7300 2021-05-10 00:58:22 -0600

**OPERATING SYSTEM:**

Linux Mint 20.1

**MODULES:**

N/A.

**CUSTOMIZATIONS:**

N/A.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98393276-blink-in-multiple-cave-systems-clipping-to-roof?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #5768.

## Changes Proposed:
-  Fixed a typo. More info: https://github.com/TrinityCore/TrinityCore/pull/18297

**Re-extracting VMAPS is required.
Re-extracting MMAPS is required.**

## Issues Addressed:

- Closes #5768

## Tests Performed:

- Tested ingame with given locations.

## How to Test the Changes:

More info: #5768.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Krejza9** [comment]
@UltraNix Wouldn't it be better to upgrade version number for vmaps a mmaps ? 
currently VMAP_4.5

**Comment by pklloveyou** [comment]
Tested

**Comment by pklloveyou** [comment]
@Krejza9 It's not a big change, is it necessary?

**Comment by UltraNix** [comment]
@Krejza9 You are right.

**Comment by Krejza9** [comment]
@pklloveyou If it requires recompilation of maps, I think so, even if it should be something like 4.5b

**Comment by pklloveyou** [comment]
But it's still like that. Have you tested it?

**Comment by Krejza9** [comment]
@UltraNix  That was fast :-D

**Comment by FrancescoBorzi** [comment]
TODO: re-extract client files after merging this I guess

**Comment by FrancescoBorzi** [comment]
cc @Helias @Yehonal

**Review by Helias — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
@UltraNix uploaded the new data here: https://github.com/wowgaming/client-data/releases/tag/v11

I'll merge this PR soon

**Comment by Krejza9** [comment]
We must update wiki to.

**Comment by Yehonal** [comment]
@UltraNix @Helias please remeber to update the bash script too.

**Review by Yehonal — CHANGES_REQUESTED** [review]
The bash installer must point to the new data zip

**Comment by Helias** [comment]
I updated the installer bash script and here the PR of the wiki https://github.com/azerothcore/wiki/pull/617
;-)

**Review by Yehonal — APPROVED** [review]

**Comment by LukasVolgger** [comment]
It's already reviewed - can it be merged??

**Comment by Krejza9** [comment]
> It's already reviewed - can it be merged?

It already has status set To be Merged. Waiting for devs.

**Comment by FrancescoBorzi** [comment]
have map files been updated?

**Comment by Kitzunu** [comment]
https://github.com/wowgaming/client-data/releases/tag/v11

**Pull request merged**
