### PR TITLE
Core/Scripts: Some Loatheb mods.

### PR DESCRIPTION
**Pull request by FALL1N1**
Changes:
- Move from BossAI to ScriptedAI
- All left spores will now despawn upon boss death.
- Fixed Necrotic Aura's timer.
- New method of spawning spores, we don't have to share them with deathbloom as it has different timer.
- Boss now evades if pulled outside the combat area.

### CODE REVIEW

**Comment by FALL1N1** [comment]
bad travis, need the full compile error so i can fix it, (i don't have local build and i don't have the time to do it)

**Comment by FALL1N1** [comment]
will fix build later, ignore this pr for now

**Comment by a4501150** [comment]
I have a noob question. BOSSAI is inheriting from ScriptedAI, and suppose to be used for boss fight.. why we switch it to ScriptedAI?..

**Comment by FALL1N1** [comment]
@a4501150  because of 'CheckEvadeIfOutOfCombatArea', it is missing from BossAI

**Comment by FrancescoBorzi** [comment]
Looking for @FALL1N1  or someone else to completed the work that has been previously started here.

**Comment by Selectah** [comment]
Well you can also include something like this

```
        bool IsInRoom()
        {
            if (me->GetExactDist(2909.0f, -3997.4f, 274.187f) > 50.0f)
            {
                EnterEvadeMode();
                return false;
            }

            return true;
        }
```

and on UpdateAI

```
            if (!IsInRoom())
                return;
```

So you still can leave Loatheb's BossAI which is anyay better.

**Comment by FALL1N1** [comment]
#1712

**Pull request closed without merging**
