### PR TITLE
refactor(Core/ScriptedAI): few improvements with threat methods

### PR DESCRIPTION
**Pull request by Maelthyrr**
## Changes Proposed:
- Now DoResetThreat will reset the threat for a specific unit
- To reset the threat list, now we have DoResetThreatList (old DoResetThreat)
- Add a DoAddThreat method to ScriptedAI

## Issues Addressed:

- Closes 

## SOURCE:

Inspired by https://github.com/TrinityCore/TrinityCore/pull/19966/files

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
we got a fail with the progressive module. who is the maintainer of that one? I really dont want to mark a review on this since it is based on it failing on another module.

**Comment by Maelthyrr** [comment]
> we got a fail with the progressive module. who is the maintainer of that one? I really dont want to mark a review on this since it is based on it failing on another module. image

Ah... I will update modules again. Normally, it's should be the last time.

**Comment by pklloveyou** [comment]
Good on my server

**Comment by acidmanifesto** [comment]
@Maelthyrr is this final for hte PR or is it a WIP stil?

**Comment by Maelthyrr** [comment]
> @Maelthyrr is this final for hte PR or is it a WIP stil?

Can be merge

**Comment by acidmanifesto** [comment]
> > @Maelthyrr is this final for hte PR or is it a WIP stil?
> 
> Can be merge

i dont mind merging but we got a workflow going red for the mod-progression-system. Is still a issue?

**Comment by Maelthyrr** [comment]
Yes, I've link the fix above

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Maelthyrr can you fetch a upstream on this pr so we can see what the workflow shows? we had a sorta off day with some workflow fixits yesterday and i want to make sure this and the core isnt going bork.

**Comment by Maelthyrr** [comment]
> @Maelthyrr can you fetch a upstream on this pr so we can see what the workflow shows? we had a sorta off day with some workflow fixits yesterday and i want to make sure this and the core isnt going bork. I want to try to get this merged today.

done

**Comment by Kitzunu** [comment]
@Maelthyrr do you have a pr to fix the module build once this is merged?

**Comment by Kitzunu** [comment]
ah yes

**Comment by Kitzunu** [comment]
ty

**Pull request merged**
