### PR TITLE
chore. Add hook OnSetArenaMinPlayersPerTeam

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author. (I'm still doing tests)

## How to Test the Changes:

1. The idea of the change is to be able to add the minimum number of players so that the arena begins. It is intended for the `mod-arena-3v3-solo-queue` module but other modules may also use it at some point if they need it.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Elmsroth** [comment]
Nice feature @pangolp <3

**Comment by pangolp** [comment]
> Nice feature @pangolp <3

We have to test, if it does not affect the current scoring system. Because I created it for the [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue) module thinking that it could be used, but I don't know if I really need it. However, since we have `OnSetArenaMaxPlayersPerTeam`, it doesn't hurt that we also have `OnSetArenaMinPlayersPerTeam`. But you have to make sure that this modification does not affect the default behavior of the arenas.

**Comment by sudlud** [comment]
I think this PR needs an update now to comply with the latest updates to the scripitng system.

similar to how it is done in #18760.

**Comment by pangolp** [comment]
> I think this PR needs an update now to comply with the latest updates to the scripting system.
> 
> similar to how it is done in #18760.

Possibly, in the event of a merger, changes would have to be made. The issue is to know if it is really worth to merge it, because this hook was created for the 3v3 module, but I think that in the end it does not need it. If the module does not require it, and there is no other module that uses it, most likely, it will end up closing this pull request.

**Pull request closed without merging**
