### PR TITLE
fix(DB/Graveyard): Add Horde graveyards in Darkshore

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
~~- Move the Horde GY in Darkshare into Darkshore (Twilight Vale)~~
~~- Notice that I remove the Horde specific GY reference and share it between Horde and Alliance (it's already used by both factions if you die in zone 141 as Horde or 148 as Alliance)~~
- Latest commit: Notice that I remove the Horde specific GY reference and share the 2 GY's there between Horde and Alliance

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4304

## Tests Performed:
- You need to be a Horde character
- .tele darkshore
- .die
- Release spirit, notice you are far away in Ashenvale
- Apply the fix, now you remain in the Darkshore zone when you release your spirit
- Depending on if you die in the Northern or Southern part of the map, you end up at different GY's.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by nicoaravena** [comment]
They are 2 spirit healers in darkshore https://classic.wowhead.com/npc=6491/spirit-healer

If I die new the top one, I will respawn at the bottom as ghost. It should be able to respawn near both when apply.
imagen

**Comment by Zoidwaffle** [comment]
I also found the 2 spirit healers but I have no idea if they are both supposed to be used by both factions are not.

If they are indeed shared between factions, I can make a fix for that as well... I should have time to make a commit to the PR addressing this later today I hope.

**Comment by FrancescoBorzi** [comment]
> I also found the 2 spirit healers but I have no idea if they are both supposed to be used by both factions are not.
> 
> If they are indeed shared between factions, I can make a fix for that as well... I should have time to make a commit to the PR addressing this later today I hope.

I see, I'd say while we are not still sure about the other GY, we can still merge this one because it improves the game already

**Comment by Zoidwaffle** [comment]
Hm, I'm not sure how the GY's are differentiated in the same zone.

All of Darkshore seems to be zone 148.

But there are 2 GY's for Alliance there (this is before the fix btw).
```
> select * from graveyard_zone WHERE `GhostZone`=148;
+-----+-----------+---------+-----------------------------------------+
| ID  | GhostZone | Faction | Comment                                 |
+-----+-----------+---------+-----------------------------------------+
|  35 |       148 |     469 | Darkshore, New Auberdine GY - Darkshore |
| 469 |       148 |     469 | Darkshore, Twilight Vale GY             |
| 512 |       148 |      67 | Ashenvale, Kargathia GY                 |
+-----+-----------+---------+-----------------------------------------+
```

So depending on where in the zone you die, you end at different GY's as Alliance. As Horde you are send far away (which obviously seems wrong).

I do think the current fix is an improvement - but I would like to understand where the logic is that sends a dead player in the same zone to different GY's.

**Comment by Zoidwaffle** [comment]
OK, I managed to find some sort of proof...

[Horde GY is North of Auberdine](https://2wowdoctors.wordpress.com/2008/03/18/the-more-than-complete-guide-on-how-to-get-a-ravager-pet-as-a-horde-hunter/)

See step 15. in the guide above.

So it true, the Horde should indeed also be able to use the Northern GY.

But I don't know how to fix that (yet).

**Comment by Zoidwaffle** [comment]
OK, so at the risk of talking to myself (sorry for the spam!)...

If both GY's are shared anyway, then the new fix should work.

I quickly tested it myself - where I did end up at the Northern or Southern GY depending on where I died.

**Comment by FrancescoBorzi** [comment]
thanks @Zoidwaffle !

@nicoaravena could you please test this as well?

**Comment by nicoaravena** [comment]
Works good now. Good job.

imagen
imagen

**Pull request merged**
