### PR TITLE
Feat(Core/Item): Item Signature proper way to add it

### PR DESCRIPTION
**Pull request by Viste**
##### CHANGES PROPOSED:
-  Many items are getting incorrectly signed.
- Items that should have signatures are profession crafted items that do not stack.

Disclaimer; this is mostly guesswork based on foggy memory and it's hard to find supporting evidence other than a feeling that it's incorrect for stacked items to have signatures, I swear it wasn't like that on retail.

What I could find
https://www.youtube.com/watch?v=leCvyUCqTcI
at 1:03 he hovers over a Bolt of Frostweave (item class 7, subclass 5, stacks to 20) without signature
https://www.youtube.com/watch?v=pgckZnEeq7w
at 2:52 he hovers over a Box of Bombs (item class 7, subclass 2, stacks to 1) with signature

### CODE REVIEW

**Comment by Viste** [comment]
As i see its no need by anyone so i close it

**Comment by FrancescoBorzi** [comment]
@Viste stop closing your PRs, we need them.

**Comment by poszer** [comment]
Tested in game. 
**Before, without this commit :** 
The signatures was wrong, i'll add two images here :

**Eternal Shadow - Created by Player and it has correct Signature here:**
Screenshot_1

**Crystallized Shadow - It's looted, it has wrong signature, including Player name there:**
Screenshot_2

**After, with this commit :**

**Eternal Shadow - Created by Player and it has correct Signature here:**
Screenshot_3

**Crystallized Shadow - It's looted, it doesn't have anymore signature, which is correct:**
Screenshot_4

Good job @Viste

**Comment by BarbzYHOOL** [comment]
nice

**Comment by FrancescoBorzi** [comment]
Good job @Viste and @poszer

**Pull request merged**
