### PR TITLE
karazhan Update

### LINKED ISSUE #173: Karazhan The opera house Script Bug
**Description**:
The scene can't trigger
http://www.wowhead.com/npc=16812/barnes
**Current behaviour**: Tell us what happens

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:
1. Click on the NPC after didn't open the option.

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

**AC hash/commit**:  

**Operating system**:  
WIN7/X64
**Modules**:  Are you using modules? if yes, list them

**Other Customizations**: Are you use core/db patches or other customizations? If yes please specify them here.

##

### PR DESCRIPTION
**Pull request by talamortis**
**Changes proposed:**

Fixed Moroes Vanish and to set data for Opera event
Opera Event will now function correctly
Barnes will now check the Data of both opera event and also boss state of moroes
Doors will now correctly work even NPC wants to trigger 

**Target branch(es):** Master 

**Issues addressed:** Closes #173 #172 

**Tests performed:** (Does it build, tested in-game, etc)
tested and working as intended.

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by ShinDarth** [comment]
@talamortis please check all those empty lines addition/removals

**Comment by Saben65** [comment]
Might be worth it to fix the Big Bad Wolf dialogue event while you are cleaning up kara in this commit?

For reference: https://github.com/velinath/TrinityCore/issues/2#issuecomment-223747493

**Comment by talamortis** [comment]
Closing this PR going to do a load of fixes in this instance and submit them all at once as i found a few more bugs

**Comment by mayaren888** [comment]
@talamortis  Your update still does not resolve the Moroes skill bug problem

**Comment by talamortis** [comment]
@mayaren888 skill bugg?

**Pull request closed without merging**
