### PR TITLE
fix(DB/gameobject_queststarter): Added queststarter records for GameObject 142122

### PR DESCRIPTION
**Pull request by manuel-velascodev**
I added the records so that these quests can be initiated from both wanted posters.

GameObject
https://www.wowhead.com/wotlk/object=142122/wanted-poster

Quests:
https://www.wowhead.com/wotlk/quest=2781/wanted-caliph-scorpidsting https://www.wowhead.com/wotlk/quest=2875/wanted-andre-firebeard

added_queststart

### CODE REVIEW

**Comment by manuel-velascodev** [comment]
This is my first time contributing, it's a minimal change but I hope I did it right.

**Comment by sudlud** [comment]
Thanks for the PR!

Can you please add the missing ticks according to AC sql standard:

https://www.azerothcore.org/wiki/sql-standards

**Comment by manuel-velascodev** [comment]
> Thanks for the PR!
> 
> Can you please add the missing backticks according to AC sql standard:
> 
> https://www.azerothcore.org/wiki/sql-standards

Thank you for the comment; I have already made the changes in a new commit.

**Review by sudlud — APPROVED** [review]

**Comment by sudlud** [comment]
thanks for the update.

I'd like to ask you to keep the PR template and fill in the requested information there for future PRs instead of deleting it.

**Pull request merged**
