### PR TITLE
Ambassador Kelemar Waypoint

### PR DESCRIPTION
**Pull request by talamortis**
**Changes proposed:**

- Ambassador Kelemar Waypoint

**Target branch(es):** 1.x/

**Issues addressed:** Closes 

**Tests performed:** (Does it build, tested in-game, etc)
Tested and works.

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

Ambassador Kelemar has no waypoint he stays outside AH in silvermoon with the Horde Embassy, This is the waypoint fix to be more blizzlike.

### CODE REVIEW

**Comment by DantestyleXD** [comment]
This was a good work, only some mistake like first 4 waypoints useless and no members's spaws near the leader.

I improved your fix for a better execution, try it and modify your ;)
You can find it attach
[2016_08_19_01.zip](https://github.com/azerothcore/azerothcore-wotlk/files/426292/2016_08_19_01.zip)

**Comment by talamortis** [comment]
i think its the spawn of the mobs as they run to the 1st way point.

**Comment by DantestyleXD** [comment]
If you leave mobs near the AH and not near the leader, they reach him through the builds of Silvermoon.

**Comment by ShinDarth** [comment]
@talamortis  can you please correct it with @DantestyleXD  suggestion?

also please move it under the new folder [data/sql/updates/pending_db_world](https://github.com/azerothcore/azerothcore-wotlk/tree/master/data/sql/updates/pending_db_world)

**Comment by talamortis** [comment]
Yeah i will change soon as i can get my server working as im still stuggling and getting the error

**Comment by ShinDarth** [comment]
@talamortis  ok no problem, I will help you when I have a bit time

**Pull request closed without merging**
