### PR TITLE
fix(Core/Players): Fixed setting player's zone id to unknown value.

### LINKED ISSUE #10945: wrong dismount
### Current Behaviour

Mount a flying mount. After passing through this area, the mount will be released

.go xyz 6966.457520 -1050.787476 1005.334900

### Expected Blizzlike Behaviour

This position should not disarm the mount

### Source

_No response_

### Steps to reproduce the problem

1.mount a flying mount
2. .go xyz 6966.457520 -1050.787476 1005.334900
3.you will automatically release the mount

### Extra Notes

_No response_

### AC rev. hash/commit

acd3ed8759477e6059b31f88377a790f3a0d8133

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #10945

## Issues Addressed:

- Closes #10945

## Tests Performed:

- Not tested.

## How to Test the Changes:

1.mount a flying mount
2. .go xyz 6966.457520 -1050.787476 1005.334900

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by mpfans** [comment]
tested,work now ,but `.go xyz 6965.391602 -1063.848999 863.463440` unable to summon flying mount, need further fix.

**Comment by UltraNix** [comment]
@mpfans Try again.

**Comment by UltraNix** [comment]
@mpfans Try now.

**Comment by mpfans** [comment]
work now! tyvm

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
