### PR TITLE
fix(DB/pool): Remove redundant Meshlok creature pool

### LINKED ISSUE #6745: Maraudon Purple - Meshlok The Harvester, Low Spawn Chance
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1098

So i and many others tried to farm this rare spawn myself 10 runs of purple crystals and a few others 30 runs and 50 runs but he doesn't seem to pop up. maybe an incorrect spawn rate?

Tester: Went and checked on his spawn and he was up, so he does appear:
WoWScrnShot_070521_200826

But that's on a freshly started server. Checking the DB shows he has a respawn timer of 1 day, and on top of that, when he spawns he runs a script that has an 85% chance of immediately despawning himself. And as @anguaive points out, that's not even taking pooling into account (see https://github.com/azerothcore/azerothcore-wotlk/issues/6658.) So it does seem as if the respawn timer/despawn chance means he's much too rare compared to retail. A 1 day respawn * 15% chance of staying spawned means he's appearing about once a week.

His GUID is 203506.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

I understand he's a rare spawn and he won't spawn every single time but watching countless youtube videos in the specified location and checking pristine waters, Purple crystals and even Orange crystals none of them will trigger Meshlok to show up. maybe a broken spawn cycle, According to wowhead it should be a 50% spawn chance but it seems like 0% and even so its so very low compared to the blizzard spawn rate.

Tester: only definite quote I could find was from TBC WH: "From my experience, he does appear to spawn about 50% of the time." - https://tbc.wowhead.com/npc=12237/meshlok-the-harvester#comments:id=2808527

##### SOURCE:

https://tbc.wowhead.com/npc=12237/meshlok-the-harvester#comments:id=2808527

##### STEPS TO REPRODUCE THE PROBLEM:

1. .go c 203506

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99776024-maraudon-purple-meshlok-the-harvester-low-spawn-chance?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anguaive**
Pool id 1211 is redundant and it needlessly reduces the spawn chance of Meshlok.
Rare creature spawn chance should be handled exclusively by SAI

Courtesy of @T1ti 

## Changes Proposed:
-  remove pool 1211

## Issues Addressed:

- Closes #6745
- Closes https://github.com/chromiecraft/chromiecraft/issues/1098

## Tests Performed:

- sql applies cleanly. Not tested in-game

## How to Test the Changes:

1. make sure sql applies cleanly
2. make sure worldserver doesn't throw warnings and stuff at you

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]
Sql looks good, test is needed.

**Comment by anguaive** [comment]
I'll test this as soon as I get back home (unless someone else tests it until then)

**Comment by anguaive** [comment]
I did some further testing and all seems well. Worldserver runs without warnings. 

I started 30 instances of Maraudon (making sure to reset all instances inbetween) and Meshlok spawned in 3 times. In the remaining 27 tries I only found the corpse, which means he spawned and then got culled by the SAI (which is correct). His despawn chance is 85% so I got a bit unlucky with the spawns. Prior to the patch, he sometimes would not spawn at all because of the pooling.

 I used 2 macros; one that takes me to the Maraudon portal (`.go o 5417`) and one that teleports me straight to Meshlok (.go c 203506), so it only took a few minutes.

**Comment by FrancescoBorzi** [comment]
good job @T1ti @anguaive and thanks @LukasVolgger for reviewing this!

**Pull request merged**
