### PR TITLE
fix(DB/Creature): Add some immunities to C'thun adds

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4839

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@Gultask please check the immunity masks, to ensure we need all of them. I added a few considering there were none, but skipped dubious ones, like stun.

**Comment by Gultask** [comment]
image

**Comment by Nyeriah** [comment]
Yeah that's what I read and why I skipped that one

**Comment by Gultask** [comment]
Checking Vmangos then.
I wish these could be sniffed 😩

**Comment by Gultask** [comment]
Confused, Fear, Sleep, Freeze for all
Confused, Fear, Sleep, Freeze, Bleed for Flesh Tentacle

not too sure about that last one.

**Review by Gultask — APPROVED** [review]

**Pull request merged**
