### PR TITLE
fix(DB/Creature): Delete some creatures in Dragonblight

### PR DESCRIPTION
**Pull request by poszer**
[Blighted Elk](https://wotlk.evowow.com/?npc=26616) & [Rabid Grizzly](https://wotlk.evowow.com/?npc=26643) Stucked, wrong spawn.

##### CHANGES PROPOSED:

- Posible wrongly spawned
- Creatures are stucked, without movement.
- Too many of them are at this place which is wrong.

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1112

##### TESTS PERFORMED:

It's just DB change/deleting creatures. Everything looks better and correct now.
wrongspawn

##### HOW TO TEST THE CHANGES:

Doesn't need test, but if someone want:
Use .go creature #guid Command - With provided ''guids'' in sql file.

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@poszer 
I see you removed 40 creatures. How did you choose which ones to remove? Random?

**Comment by Pondaveia** [comment]
I think he chose based on the ones that didn't have movement or were on top of other creatures. It's pretty hard to pick GUIDs without a sniff tbh

**Comment by poszer** [comment]
> @poszer
> I see you removed 40 creatures. How did you choose which ones to remove? Random?

Easy, Checking them one by one. NPC info on not correct creatures, getting it, saving all in db query and run :laughing: Anyway, all of them are stucked, doesn't move, doesn't do nothing. Like you can see on image i shared, they re overwriting each. And on my live server it's reported that play who's levling in this zone, traveling from borean to dragonblight are not able to go through that area bcoz a ubnormal count of these mobs. Also i give a try, picking some quests in that area. Players who's level 70+ are not able to deal with all of that creatures, which will aggro on you. Checked on blizz, checked on tc, there should be around 15 - 16 how i spot. Also little more these Elks than bears. @Stoabrogga

**Comment by Stoabrogga** [comment]
Yeah, I remember questing there and got killed instantly. Btw, I see there are 4 other creatures without movement which are not covered by your SQL statement:
- GUID 52318, ID 26616
- GUID 119440, ID 26616
- GUID 119499, ID 26616
- GUID 97934, ID 26643

Could you perhaps also take a look at these?

**Comment by poszer** [comment]
> * 52318

Hmmm, yes you re right. Some of them are in other location spawned. I checked just the one like on image :smiley: 
Will add them too now, just checked they re wrong too

**Comment by Stoabrogga** [comment]
Tested this PR, looks better now, not so crowded anymmore 👍

**Comment by BarbzYHOOL** [comment]
Good work @poszer 

Thank you @Pondaveia and @Stoabrogga !

**Pull request merged**
