### PR TITLE
fix(DB/Sai): Crash

### PR DESCRIPTION
**Pull request by Kitzunu**
* Fixes https://github.com/azerothcore/azerothcore-wotlk/issues/3028

## CHANGES PROPOSED:
-  Remove faulty SAI

Gameobjects should not be allowed to be in combat with zone

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3028

## HOW TO TEST THE CHANGES:

This was tested and confirmed in https://github.com/azerothcore/azerothcore-wotlk/issues/3028#issuecomment-654536304

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Kitzunu good that this solves the crash. However the core should be robust enough to not crash even when there are invalid SAI in the DB. The core should rather just give an error instead (and the SAI of course should be removed from the DB too, as you did).

**Comment by Kitzunu** [comment]
Indeed, that is in my todo but this is the only case so it is more important to do this first imo

**Comment by FrancescoBorzi** [comment]
@Kitzunu totally agree. Maybe it's worth opening a ticket for that too? so we don't forget

**Comment by Kitzunu** [comment]
Got friends over atm but screenshotted so I will remember

**Pull request merged**
