### PR TITLE
fix(Core/Spells) Explosive Shot 

### PR DESCRIPTION
**Pull request by v-mstrs**
## Changes Proposed:
-  Excludes Explosive Shot 
## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16480
- Closes https://github.com/chromiecraft/chromiecraft/issues/5787

## SOURCE:

WOTLK Classic
## Tests Performed:

- Works

## How to Test the Changes:

1. .learn 60052
2. .learn 60053
3. .cast 56453
4. can stack ( any rank )

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Fix it in spell_group_stack_rules instead.

**Comment by avarishd** [comment]
This was not present in original wrath, also mentioned on recycled's repo https://github.com/JamminL/wotlk-classic-bugs/issues.

**Comment by v-mstrs** [comment]
Screenshot of a comment on wowhead.

**Review by Kitzunu — CHANGES_REQUESTED** [review]
Fix it in spell_group_stack_rules instead.

**Comment by v-mstrs** [comment]
> Fix it in spell_group_stack_rules instead.

can't get it working

**Pull request closed without merging**
