### PR TITLE
fix(Scripts/Icecrown): ICC Lich king does not evade 10% of health

### PR DESCRIPTION
**Pull request by pangolp**
## Credits

- Although I am writing the pull request, the ideas and authorship belong to Mr. @Nefertumm. I only made the tests.

## Changes Proposed:
-  Currently, in the last phase of the lich king boss, when it reaches 10%, after the terenas king revives you, the npc constantly regenerates his health, which makes him never finish the fight.

## Issues Addressed:

- https://github.com/azerothcore/azerothcore-wotlk/issues/10821

## Tests Performed:

- The tests were performed on a Windows 10 operating system. Although I was alone in the raid, it would be interesting if someone can test it, with other people. (but I don't think it will change too much)

## How to Test the Changes:

1. Go to the citadel: `.tele IcecrownCitadelRaid`
2. Eliminate the previous bosses beforehand
3. Perform the fight and you will be able to finish it normally.

## Screenshot

WoWScrnShot_032622_003808

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10882

**Comment by Ramys** [comment]
I will recompile and test.

**Comment by pangolp** [comment]
> I will recompile and test.

Thank you.

**Comment by Ligthsx** [comment]
**Tested** on the date 03/26/2022
Effectively the boss "LICH KING" upon reaching HP 10% of life, can no longer be damaged with spells or meles hits.
Screenshot_28
Screenshot_30

**Comment by Bogir** [comment]
Bug on last phase? Or I did something wrong?
On PHASE_OUTRO every hit to Leech King takes only -1 HP from him.
(don't pay attention to the russian text, only action)

https://youtu.be/jldD9hcG4gI

**Comment by pangolp** [comment]
> **Tested** on the date 03/26/2022 Effectively the boss "LICH KING" upon reaching HP 10% of life, can no longer be damaged with spells or meles hits. Screenshot_28 Screenshot_30

Indeed, you have failed to apply the change. Because if you apply the flag at least, the one in the SQL, the boss, dies, but falls out of the world. Now if you combine that, with the C++ code, then if the problem is solved. I made a video that talks about it.

https://www.youtube.com/watch?v=YvBxlGr8Bsc

**Comment by Bogir** [comment]
Can I link it here? It  seems some issue

https://github.com/azerothcore/azerothcore-wotlk/issues/11168

**Comment by pangolp** [comment]
> Can I link it here? It seems some issue
> 
> #11168

Yes, it is the same error.

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
@Bogir for that issue, try removing [this](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L819) line

**Comment by Bogir** [comment]
I've tested with fix suggested in this PR.  Leech get full damage now.

**Comment by Ramys** [comment]
Now it works perfectly..
Thanks..
@pangolp

**Comment by pangolp** [comment]
> Now it works perfectly.. Thanks.. @pangolp

Thanks, although the code is not really mine. I tried other methods, but I couldn't find a solution. The code was suggested to me by Nefertum. I'm glad that it will solve the problem.

**Comment by Ramys** [comment]
> > Now it works perfectly.. Thanks.. @pangolp
> 
> Thanks, although the code is not really mine. I tried other methods, but I couldn't find a solution. The code was suggested to me by Nefertum. I'm glad that it will solve the problem.

I just realized something, I tested all the modes, both N and H.
and the only mode that works is 10N.
10H, 25N and 25H does not work.
Life keeps not downloading.
https://ibb.co/qDrMbkJ

**Comment by Nefertumm** [comment]
Ah, indeed.

**Comment by Nefertumm** [comment]
Try now.

**Comment by Ramys** [comment]
> Try now.

Adjusted.
Thank you all..
I think you can add this correction to the core.

**Comment by fullofstarschen** [comment]
> @Bogir for that issue, try removing [this](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Northrend/IcecrownCitadel/boss_the_lich_king.cpp#L819) line

So should I remove that line or not？

**Comment by Ramys** [comment]
no need, because the fix is ​​what is in the pull.

**Comment by fullofstarschen** [comment]
> no need, because the fix is ​​what is in the pull.

thx.

**Pull request merged**
