### PR TITLE
fix(Core/MMAPs): Fix small steps being considered as NAV_AREA_GROUND_STEEP 

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/3ac1992afbeb1cd7669b300b8ee4131d39f35595
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Remember to re-extract maps whoever merges this

**Comment by Nefertumm** [comment]
As we are updating mmaps soon, I'm merging this.

**Comment by mpfans** [comment]
mmaps needs to be re extracted

**Comment by LannyE** [comment]
I updated my server this morning and get this error on startup which crashes the server:
`VMap file './data/vmaps/000.vmtree' couldn't be loaded
This is because the version of the VMap file and the version of this module are different, please re-extract the maps with the tools compiled with this module.`
I assume this is the mmaps update you all are referring to that will fix this, correct?  Just making sure I am not having a different issue.

**Comment by LannyE** [comment]
That is what I thought but have been spoiled by you all putting them up to download.  I will do the extract to fix it.  Thank you.

**Comment by hongweiOst** [comment]
**> Version DB world:     ACDB 335.7-dev
Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
Using DataDir /data/azerothcore-server-new/data/
WORLD: VMap support included. LineOfSight:true, getHeight:true, indoorCheck:true PetLOS:true
VMap file '/data/azerothcore-server-new/data/vmaps/000.vmtree' couldn't be loaded
This is because the version of the VMap file and the version of this module are different, please re-extract the maps with the tools compiled with this module.**

Map file  '/data/azerothcore-server-new/data/vmaps/000.vmtree'
The maps extracted with 13930 and 12340 cannot be repaired successfully

Map file '/data/azerothcore-server-new/data/maps/0004331.map' --- This file was fixed using the map extracted by 12340

**Comment by hongweiOst** [comment]
[AC Data v14](https://github.com/wowgaming/client-data/releases/tag/v14)
about 000.vmtree
I didn't find the V15 version

**Comment by hongweiOst** [comment]
> > I updated my server this morning and get this error on startup which crashes the server: `VMap file './data/vmaps/000.vmtree' couldn't be loaded This is because the version of the VMap file and the version of this module are different, please re-extract the maps with the tools compiled with this module.` I assume this is the mmaps update you all are referring to that will fix this, correct? Just making sure I am not having a different issue.
> 
> you need select tools when compiling,and reextracted mmaps or waiting this update V15 https://github.com/wowgaming/client-data/releases/

When will version 15 fix this problem

**Pull request merged**
