### PR TITLE
fix(DB): failure due to missing semicolumn

### PR DESCRIPTION
**Pull request by FrancescoBorzi**

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]
oops !

**Comment by Kitzunu** [comment]
How does that even pass checks

**Comment by FrancescoBorzi** [comment]
> How does that even pass checks

Good question. It does because one query without `;` is valid, multiple queries aren't.

**Comment by FrancescoBorzi** [comment]
@locus313 maybe we can improve the `.github/workflows/check_pending_sql.yml` workflow and add this check

**Comment by locus313** [comment]
@FrancescoBorzi just submitted a pr to add the check: 
https://github.com/azerothcore/azerothcore-wotlk/pull/3749

**Pull request merged**
