### PR TITLE
Creature type flags

### LINKED ISSUE #1984: Creature type flags should be defined/updated
The `enum CreatureTypeFlags` located in `SharedDefines.h` should be checked and updated (renamed) accordingly to what they are actually doing. Especially the ones marked as "UNKNOWN".

Then the wiki should be updated too.

This commit can be a good starting point:

https://github.com/TrinityCore/TrinityCore/commit/fb0881398a106806fad48abe9ffd600e0caf175d

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/75740411-creature-type-flags-should-be-defined-updated?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mik1893**
Closes #1984
add a missing condition in Spell:SelectImplicitTrajTargets when creature has flag CREATURE_TYPE_FLAG_CAN_COLLIDE_WITH_MISSILES

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Changes are ok (just made a small adjustment to the if statement), but sadly I have no idea how to test the condition concerning creature flag CREATURE_TYPE_FLAG_CAN_COLLIDE_WITH_MISSILES.

**Comment by degenesis** [comment]
CREATURE_TYPE_FLAG_CAN_COLLIDE_WITH_MISSILES.

probably creatures that can be shot with vehicle missiles, like Flame Leviathan.

**Comment by Stoabrogga** [comment]
@mik1893 
Why are you merging this without further testing? Also if merging PRs please use the naming conventions mentioned here:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.git_commit_template.txt

**Comment by mik1893** [comment]
sorry. i didn't know it would actually merge into master, i thought i was merging into my own fork master. Never seen this feature before :|

**Comment by FrancescoBorzi** [comment]
@mik1893 no worries, just revert :)

**Comment by pklloveyou** [comment]
How to test it?

**Comment by BarbzYHOOL** [comment]
@mik1893 if you see some colorful tags or request reviews, then it's AzerothCore repo :P

How to test it as pklloveyou said?

And now it has been merged we can revert and remerge eventually, dunno. If one commit has not the right name it's not that big of a deal but since the PR is of medium size, it would be better.

So what do?

**Comment by Stoabrogga** [comment]
As I see this the only thing which has to be tested is the change to Spell.cpp about the condition with creature flag CREATURE_TYPE_FLAG_CAN_COLLIDE_WITH_MISSILES. The other changes concern only names, not logic.

**Comment by pklloveyou** [comment]
No problems found

**Pull request merged**
