### PR TITLE
fix(Core/Spells): Kill credits given via spells should always be awar…

### LINKED ISSUE #10784: Pets not Providing kill credit to player on creature kills.
### Current Behaviour

Pretty much the title says it all, while triaging I was able to replicate consistency with when pets get the final kill of a creature, the kill credit is not registered to the player, this will also make smart ai scripts not fire off as well.

https://github.com/chromiecraft/chromiecraft/issues/3078
https://github.com/chromiecraft/chromiecraft/issues/3077

Video include by original issue maker:
https://user-images.githubusercontent.com/91145640/154377801-1a4b31a8-5ef9-49f2-899c-24e4457e4eba.mp4

### Expected Blizzlike Behaviour

Pets should provide kill credit to player. 
Pets should also fire off associated smart scripts dealing with kill credits.

### Source

Retail Class, TBC, SL

### Steps to reproduce the problem

1. take any quest that involves kill objectives
2. Have your pet kill the creature with the final blow
3. observer no credit or progress given to player

### Extra Notes

_No response_

### AC rev. hash/commit

[00caec](https://github.com/azerothcore/azerothcore-wotlk/commit/400caec7099addf7329396800341c0f9070da734)

### Operating system

Ubuntu 20.04

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
…ded to players.

Fixes #10784

## Issues Addressed:

- Closes #10784
- Closes https://github.com/chromiecraft/chromiecraft/issues/3078
- Closes https://github.com/chromiecraft/chromiecraft/issues/3077

## Tests Performed:

- Not tested.

## How to Test the Changes:

Accept the quest "The Grimtotem Power" https://wowgaming.altervista.org/aowow/?quest=11169
If your pet last hits an NPC you get progress.

Accept the quest "What's Haunting Witch Hill?" https://wowgaming.altervista.org/aowow/?quest=11180
If your pet last hits an NPC you get progress.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@pangolp Test specifically these 2 mention in the PR.

**Comment by pangolp** [comment]
Maybe I'm wrong, but I think the problem is in the smart_scripts target.

target

**Comment by UltraNix** [comment]
@pangolp Please, test it again.

**Comment by temperrr** [comment]
Tested with warlock pet:

Both quests give progression if pet kills them

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
