### PR TITLE
DB/Quest: Lazy Peons SAI

### PR DESCRIPTION
**Pull request by poszer**
Moved from Core Script to SAI

##### CHANGES PROPOSED:

-  Quest: Lazy Peons: Moved from core to SAI
-  Lazy Peon will now play work sounds
-  Lazy Peon will now display the axe-swing emote
-  Lazy Peon will now kneel in front of the pile, and start cutting in front of the tree
-  Lazy Peon will now use better positions and orientations for the wood pile and the trees
-  Lazy Peon will fall asleep after 80 seconds of working
-  Lazy Peon will now activate itself every 120 000 till 150 000 milliseconds

###### ISSUES ADDRESSED:

Closes 

##### TESTS PERFORMED:

Builded without errors, tested in game, all creature are fine, also quest can be normally, Ps: It's better than before :smiley: 
Video included:
https://youtu.be/uSbagD3NcP4

##### HOW TO TEST THE CHANGES:

1. Go to Durotar
2. .quest add 5441
3. Go there, and start to do quest / finish

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

Ported from TC with some changes.

### CODE REVIEW

**Comment by DrArkaneX** [comment]
Works for me on build:
AzerothCore rev. 4ba0932885fb+ 2019-01-22 23:07:46 +0000 (master branch) (Unix, Release) (worldserver-daemon) ready...

**Comment by FrancescoBorzi** [comment]
good job @poszer and thanks a lot @DrArkaneX for testing this!

**Comment by Stoabrogga** [comment]
@poszer 
Could you please add a link to the appropriate TC commit in the PR description?

**Comment by Phatcat** [comment]
It's ported from https://github.com/TrinityCore/TrinityCore/pull/18702 which is based on https://github.com/cmangos/mangos-classic/pull/220

**Comment by FrancescoBorzi** [comment]
Thanks @phatcat

**Comment by BarbzYHOOL** [comment]
thank you @poszer and thank you @DrArkaneX for testing! I hope you can test more of our PRs (it's very helpful)!

**Comment by DrArkaneX** [comment]
Everything seems to work, however on worldserver start, i get this in the SmartScripts startup: https://pastebin.com/e7hzkjPu

Other than that, seems fine.

**Comment by Stoabrogga** [comment]
The action "SMART_ACTION_RANDOM_SOUND" (ID 115) is currently not supported by AC. I'll look into this, shouldn't be too complicated to implement.

**Comment by Stoabrogga** [comment]
See PR #1356

**Pull request merged**
