### PR TITLE
fix(DB/SAI): Nathanos Blightcaller Combat Script

### LINKED ISSUE #9324: Various issues with Nathanos Blightcaller
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [X] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2390

Nathanos Blightcaller is missing all of his spells

Tester:

The issue is confirmed. [Nathanos Blightcaller](https://wowgaming.altervista.org/aowow/?npc=11878) has blank `creature_template_spell`. He is using only Shoot and Multi-Shot. Also doesn't have any speeches.

WoWScrnShot_112521_011443

### Expected Blizzlike Behaviour

Tbh skillset is not clear. Nathanos Blightcaller probably missing
1. [Psychic Scream](https://wowgaming.altervista.org/aowow/?spell=13704)
2. [Shadow Shot](https://wowgaming.altervista.org/aowow/?spell=18649#used-by-npc)
3. [Backhand](https://wowgaming.altervista.org/aowow/?spell=6253)
4. Skeletons summon
5. TC fix to speeches below

### Source

https://tbc.wowhead.com/npc=11878/nathanos-blightcaller#abilities
> [Reanna] 23.12.2006 (Обновление 2.0.1)Тема: "more like newbcaller"
Beat Blightcaller today with a 5-man group.  That "don't heal" rule of yours is crap, he'll spawn skeletons whenever he damn well feels like it.

https://youtu.be/db_xKqU5sTQ?t=90
https://youtu.be/nMbtkZWwkzs?t=8

### Steps to reproduce the problem

.go c id 11878

### Extra Notes

```sql
-- Nathanos Blightcaller
DELETE FROM `smart_scripts` WHERE `entryorguid`=11878 AND `source_type`=0 AND `id` IN (4, 5);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(11878,0,4,0,4,0,100,0,0,0,0,0,1,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Nathanos Blightcaller - On Aggro - Say Line 0"),
(11878,0,5,0,5,0,100,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Nathanos Blightcaller - On Killed Unit - Say Line 1");

DELETE FROM `creature_text` WHERE `CreatureID`=11878;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(11878,0,0,"Prepare for a severe beating.",12,0,100,0,0,0,7229,0,"Nathanos Blightcaller"),
(11878,0,1,"I shall wear your entrails as a necklace.",12,0,100,0,0,0,7230,0,"Nathanos Blightcaller"),
(11878,0,2,"I can smell your fear, $r.",12,0,100,0,0,0,7231,0,"Nathanos Blightcaller"),
(11878,0,3,"If you run now, you may live.",12,0,100,0,0,0,7232,0,"Nathanos Blightcaller"),
(11878,0,4,"How dare you!",12,0,100,0,0,0,7233,0,"Nathanos Blightcaller"),
(11878,1,0,"Pathetic.",12,0,100,0,0,0,7234,0,"Nathanos Blightcaller"),
(11878,1,1,"The reckoning is upon you, weakling!",12,0,100,0,0,0,7235,0,"Nathanos Blightcaller"),
(11878,1,2,"Disappointing.",12,0,100,0,0,0,7236,0,"Nathanos Blightcaller"),
(11878,1,3,"Is that the best you can do?",12,0,100,0,0,0,7237,0,"Nathanos Blightcaller"),
(11878,1,4,"You weren't worth the energy expenditure. <Nathanos spits.>",12,0,100,0,0,0,7238,0,"Nathanos Blightcaller"),
(11878,1,5,"Next time, bring friends.",12,0,100,0,0,0,7239,0,"Nathanos Blightcaller");
```

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Voxstrasza**
## Changes Proposed:
-  Nathanos Blightcaller will now use Psychic Scream, Backhand, Shadowshot and summon his skeletons in addition to auto shot and multi-shot
-  He will also use his proper voice lines when being aggroed or when he kills someone

## Issues Addressed:

- Closes #9324
- Closes chromiecraft/chromiecraft#2390

## Tests Performed:

1. He will fear on his timer
2. He will backhand his target
3. He'll use Shadow Shot at range
4. He'll summon his skeletons on a timer
5. Skeletons will execute their separate combat script regardless of range of player

https://youtu.be/i9hS8dK2-Xg

## How to Test the Changes:
.go c id 11878

### CODE REVIEW

**Comment by Shineslippers** [comment]
Well this TC fix not so good. When you're staying on max distance `Corrupted Soul of Blightcaller` doen't attack you. They just despawn.

https://user-images.githubusercontent.com/85256266/144758156-eeb34f83-fd2d-444a-841f-0470926a8a0c.mp4

.

**Comment by Voxstrasza** [comment]
i will tweak it

**Comment by Voxstrasza** [comment]
@Shineslippers I have made it so the skeletons will initiate combat script to players within 30 yards, which is a few yards greater than max range

**Comment by Voxstrasza** [comment]
@Shineslippers 
Changes made:

Nathanos will use 'Summon Conquered Soul' spell instead of just summoning them individually - this creates the 'woosh' sound when summoning as heard in official blizzard server videos.

The conquered souls will force despawn after 1 minute of no combat

The conquered souls will start their attack upon summon to a huge range

video: https://youtu.be/i9hS8dK2-Xg

@Nyeriah please review code

**Comment by Shineslippers** [comment]
Wooosh. Much much better. Tested:

- [X] Fear on his timer
- [X] Backhand his target
- [X] Shadow Shot at range
- [X] Summon his skeletons on a timer
- [X] Skeletons will execute their separate combat script regardless of range of player


https://user-images.githubusercontent.com/85256266/145282772-539fb331-2465-4f95-a3f1-bcbd1b0a10f8.mp4

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
