### PR TITLE
fix(DB): Fix variable in 2022_10_07_06.sql

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix a typo in a committed SQL file causing undefined behavior

## Issues Addressed:

- Closes unreported issue

## Tests Performed:

- SQL now works as intended

## How to Test the Changes:

1. Ensure SQL only deletes intended objects

## Known Issues and TODO List:

- A further PR is needed to restore all data deleted by the incorrect SQL. However, we are unable to determine exactly what data could have been deleted. We may just need to reimport the whole gameobject table prior to this commit.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ZhengPeiRu21** [comment]
I have updated this PR to also repopulate the gameobject table to the state it should be in as of 2022_10_17_02 if the SQL is correct.

**Comment by Yehonal** [comment]
Can you link the broken commit, please? 

Also, is it really necessary to put a 3mb SQL file as an update? can't we just restore the wrong values?

**Comment by heyitsbench** [comment]
> Can you link the broken commit, please?

https://github.com/azerothcore/azerothcore-wotlk/commit/e30f0ada163b712161d64ae4519d2a5f8edfbf5a

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
cant merge with the error, please update branch

**Comment by ZhengPeiRu21** [comment]
Branch has been update.

**Pull request merged**
