### PR TITLE
fix(DB/HellfirePeninsula): remove very strange resistance from Kaliri Swooper, Matriarch and the Hatchlings

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16368
- Closes https://github.com/chromiecraft/chromiecraft/issues/5639

## SOURCE:

The video shows that this resistance that it is rn (see AC issue) just cannot be right. The arcane shot we see [here](https://www.youtube.com/watch?v=8LrraqpLa1M&t=150s) would likely be totally resisted.

checking thanks to @heyitsbench 

## Tests Performed:

- not tested in game
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [x] <s>set verified build to 0</s>delete entries
- [x] this is very likely not needed, but to be absolutely sure we would need sniffs

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Is there a reason to keep these entries around if they're gonna be zeroed anyway?

**Comment by elthehablo** [comment]
> Is there a reason to keep these entries around if they're gonna be zeroed anyway?

Fine either way by me. @staff?

**Comment by heyitsbench** [comment]
Also, since it wasn't checked in the linked issue, here's the beast lore for the [Male](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/b80b4644-231b-49f8-804f-87d19fc09316) and [Female](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/4dca7135-b9b3-4382-9824-e4f8e18315ec) Kaliri Hatchlings.

**Comment by Gultask** [comment]
Most creatures don't have entries there. If they'll be zeroed might as well delete

**Comment by elthehablo** [comment]
> Most creatures don't have entries there. If they'll be zeroed might as well delete

I will do that then

**Review by Gultask — APPROVED** [review]

**Pull request merged**
