### PR TITLE
feat(Cmake): add support old policy 0153

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
Fix cmake warning
```
CMake Warning (dev) at src/cmake/macros/FindMySQL.cmake:113 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  CMakeLists.txt:103 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/cmake/macros/FindMySQL.cmake:122 (exec_program):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  CMakeLists.txt:103 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
> Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found

After this

**Comment by justinknierim** [comment]
Ubuntu 22.04
```
-- CMake version: 3.22.1
CMake Error at CMakeLists.txt:20 (cmake_policy):
  Policy "CMP0153" is not known to this version of CMake.
<snip>
-- Looking for strtod_l
-- Looking for strtod_l - not found
<snip>
-- Running cmake hook: AFTER_SRC_LOAD
-- No hooks registered for AFTER_SRC_LOAD
-- Configuring incomplete, errors occurred!
See also "/home/ac/azerothcore/build/CMakeFiles/CMakeOutput.log".
See also "/home/ac/azerothcore/build/CMakeFiles/CMakeError.log".
```

**Comment by Nyeriah** [comment]
@Winfidonarleyan please take a look ty

**Comment by Winfidonarleyan** [comment]
Today fix, sorry

**Comment by WoShiXiaoMaNong** [comment]
cmake issue as below.  and build success after remove "cmake_policy(SET CMP0153 OLD)"


=============Error log ================

Run Build Command(s):/usr/bin/make cmTC_46a2a/fast && /usr/bin/make -f CMakeFiles/cmTC_46a2a.dir/build.make CMakeFiles/cmTC_46a2a.dir/build
make[1]: Entering directory “/home/zhongming/wow/azerothcore/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_46a2a.dir/CheckFunctionExists.c.o
/usr/bin/clang   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_46a2a.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_46a2a
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_46a2a.dir/link.txt --verbose=1
/usr/bin/clang  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_46a2a.dir/CheckFunctionExists.c.o  -o cmTC_46a2a  -lpthreads
/usr/bin/ld:  cannot find -lpthreads
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [CMakeFiles/cmTC_46a2a.dir/build.make:87：cmTC_46a2a] Error 1
make[1]: Leaving directory“/home/zhongming/wow/azerothcore/build/CMakeFiles/CMakeTmp”
make: *** [Makefile:121：cmTC_46a2a/fast] Error 2

**Pull request merged**
