### PR TITLE
feat(Core/SmartScripts): SMART_ACTION_SELF_CAST

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

TC

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
image

**Review by acidmanifesto — APPROVED** [review]

**Comment by pklloveyou** [comment]
I only tested one quest and found error...
QuestID 11652

**Comment by Nyeriah** [comment]
Best way of reporting a bug is opening an issue about it with detailed information so it can be fixed.

**Comment by pklloveyou** [comment]
My mistake, I didn't close GM....

**Comment by pklloveyou** [comment]
@Nyeriah 
Can you help create a PR?
This will fix quest 11627
```sql
DELETE FROM `smart_scripts` WHERE `entryorguid`=25418 AND `source_type`=0;
DELETE FROM `smart_scripts` WHERE `entryorguid`=25416 AND `source_type`=0;
INSERT INTO `smart_scripts` VALUES (25416, 0, 0, 1, 4, 0, 100, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - On Aggro - Say Line 0');
INSERT INTO `smart_scripts` VALUES (25416, 0, 1, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 42, 0, 5, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - On Respawn - Set Invincibility Hp 5%');
INSERT INTO `smart_scripts` VALUES (25416, 0, 2, 0, 0, 0, 100, 1, 5000, 5000, 5000, 5000, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - In Combat - Say Line 2');
INSERT INTO `smart_scripts` VALUES (25416, 0, 3, 4, 0, 0, 100, 1, 10000, 10000, 10000, 10000, 0, 1, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - In Combat - Say Line 3');
INSERT INTO `smart_scripts` VALUES (25416, 0, 4, 5, 61, 0, 100, 1, 0, 0, 0, 0, 0, 134, 45599, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - Between 0-5% Health - Invoker Cast &apos;Boiling Point: Simmer Kill Credit&apos; (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25416, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - Between 0-5% Health - Say Line 1 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25416, 0, 6, 7, 61, 0, 100, 512, 0, 0, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - Between 0-5% Health - Set Faction 35 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25416, 0, 7, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - Between 0-5% Health - Evade (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25416, 0, 8, 0, 1, 0, 100, 512, 120000, 120000, 120000, 120000, 0, 2, 1983, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Simmer - Out of Combat - Set Faction 1983 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 0, 0, 0, 0, 100, 0, 5300, 5300, 9900, 9900, 0, 11, 50206, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - In Combat - Cast &apos;Scalding Steam&apos; (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 1, 0, 4, 0, 100, 512, 0, 0, 0, 0, 0, 42, 0, 5, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - On Aggro - Set Invincibility Hp 5% (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 2, 0, 0, 0, 100, 1, 5000, 5000, 5000, 5000, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - In Combat - Say Line 0 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 3, 4, 0, 0, 100, 1, 10000, 10000, 10000, 10000, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - In Combat - Say Line 1 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 4, 5, 61, 0, 100, 1, 0, 0, 0, 0, 0, 134, 45598, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - Between 0-5% Health - Invoker Cast &apos;Boiling Point: Churn Kill Credit&apos; (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 5, 6, 61, 0, 100, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - Between 0-5% Health - Say Line 2 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 6, 7, 61, 0, 100, 512, 0, 0, 0, 0, 0, 2, 35, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - Between 0-5% Health - Set Faction 35 (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 7, 0, 61, 0, 100, 512, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - Between 0-5% Health - Evade (No Repeat)');
INSERT INTO `smart_scripts` VALUES (25418, 0, 8, 0, 1, 0, 100, 512, 120000, 120000, 120000, 120000, 0, 2, 1984, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Churn - Out of Combat - Set Faction 1984 (No Repeat)');
```

**Pull request merged**
