### PR TITLE
fix(Core): Player stats logic 

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Removed check that gave Druids Ranged Attack power.
- Removed Check that gave Ranged attack power based off Strength since no points in Strength give Ranged Attack Power.
- Fixed Warlocks, Mages and Priests attack power scaling from Strength.

## Issues Addressed:

- Closes not reported Issue.

## SOURCE:

https://wowpedia.fandom.com/wiki/Attack_power

## Tests Performed:

- Checked Warlock, mage and priest attack power gains

## How to Test the Changes:

1. Check Warlock, Mage or Priest Attack Power. It should be `(Strength x 2) - 20`

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by tkn963** [comment]
Tested 👍

**Comment by pklloveyou** [comment]
Tested

**Comment by temperrr** [comment]
Thanks for the tests :)

**Comment by temperrr** [comment]
You appear to be using a shadowlands source

https://wowpedia.fandom.com/wiki/Attack_power?oldid=2362723

**Pull request closed without merging**
