### PR TITLE
fix(Scripts/UpperBlackrockSpire): Missing Seal of Ascension event

### PR DESCRIPTION
**Pull request by SoglaHash**
Using seal of ascension during the arena event  does not start event

Seal of ascension does not give chromatic protection buffs

## Changes Proposed:
-  Add missing event 
- Add chromatic protection proc

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9069

## SOURCE:

https://youtu.be/E3i998lGwYM?t=34 

## Tests Performed:

- Matched recordings of the event with the source video to get timing correct

## How to Test the Changes:

See "Expected Blizzlike Behaviour" details in issue https://github.com/azerothcore/azerothcore-wotlk/issues/9069

2 clients may be useful, 1 that starts the event with the ring and 1 with GM mode on to observe.

Start arena event 

.go c 137967
start Gyth and Rend event
.cheat cooldown
.additem 12344

Observe Vael event matches https://youtu.be/E3i998lGwYM?t=34

Ring can only be used once per encounter.

Ring cannot be used outside Rend event and only once per attempt. 

Gyth breaths should buff player wearing ring with chromatic protection buffs

## Known Issues and TODO List:

- [ ] 5s after Vaelastrasz spawns, he should attack. I've had issues where does not move or attack.
When Nefarius shouts "Enough! Playtime is over!", Vael should attack

https://user-images.githubusercontent.com/74299960/187093430-0ddca089-45fe-4319-bd8d-1cbc529e9fa9.mp4

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by SoglaHash** [comment]
Please label as WIP. I need to improve the transition from Red to Vael similar to how some `ScriptedAI` call `me->SetEntry`

**Comment by heyitsbench** [comment]
You can mark the PR as a draft yourself if you'd like.

**Comment by Gultask** [comment]
- [X] Event proceeds smoothly.
- [X] 2 characters cannot use the Seal of Ascension at the same time.

Nice work. It looks very good.

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
There are merge conflicts, please fix them!

**Comment by SoglaHash** [comment]
Fixed conflicts in `src/server/scripts/EasternKingdoms/BlackrockMountain/BlackrockSpire/instance_blackrock_spire.cpp` due to https://github.com/azerothcore/azerothcore-wotlk/pull/12920

Build failing seems unrelated :(

**Comment by Nefertumm** [comment]
Indeed, don't mind the build errors, is not related at all.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
