### PR TITLE
fix (core): Cast sub-expression to wider-type

### PR DESCRIPTION
**Pull request by acidmanifesto**
sub-expression may overflow before being added to a wider type.
Possible fix for a segmentation fault being reported in the chat.

## Changes Proposed:
-  Cast sub-expression to wider-type

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1. 
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by ZhengPeiRu21 — APPROVED** [review]
I think I have seen uint64 used for time_t associated values more than long long, so that is maybe more consistent to cast to that instead, but this also will work, so is not very important!

**Comment by Maelthyrr** [comment]
How test ?

**Comment by acidmanifesto** [comment]
Not crash when instance resetting a raid instance or dungeon diff higher then normal

**Comment by Maelthyrr** [comment]
Tested with ICC 50 times, no issue, no crash.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by acidmanifesto** [comment]
thanks for the test and reviews. @Maelthyrr @IntelligentQuantum @ZhengPeiRu21

**Pull request merged**
