### PR TITLE
Core/Players: get character_queststatus from trinitycore thx to Shauren

### PR DESCRIPTION
**Pull request by Viste**
CHANGES PROPOSED: compare structure of character_queststatus to trinitycore
Closes: #1125
Target branch(es): master

### CODE REVIEW

**Comment by Nefertumm** [comment]
Thanks Viste!! Just a little detail: Don't change the base db, delete those changes and keep the pending sql.

**Comment by wetbrownsauce** [comment]
Began testing. Builds with no errors and updates to database apply with seemingly no issue. 

Quest 4763 (The Blackwood Corrupted) uses RequiredItemCount6, tested the quest and it works as normal.

Quest 13476 and 13478 (For Great Honor and Concerted Efforts) both use all 6 RequiredItemCount fields. Tested and they successfully check off as marks are collected, and those changes are reflected in the character_queststatus db table.  

Screenshots of test with descriptions:
[Imgur Album](https://imgur.com/a/mocsslz)


I'm going to test regular questing by leveling a character for a while to make sure everything else still works fine if you want to hold merging until then. :)

Future tests:

- [ ] Ensure that characters already on the above quests will retain them and work properly when PR is merged
- [ ] Ensure all other regular quests function properly
- [ ] Ensure existing quests in players logs are still there and functioning properly

**Comment by wetbrownsauce** [comment]
Alright tested. I have no complaints with this PR. Everything seems to work properly

**Comment by BarbzYHOOL** [comment]
Thank you @Viste for porting quickly!

Thank you @wetbrownsauce for testing in details!

**Comment by FrancescoBorzi** [comment]
good job @Viste @wetbrownsauce ! :+1:

**Comment by BarbzYHOOL** [comment]
I forgot but we need to update the wiki too, for the db structure

**Pull request merged**
