### PR TITLE
fix(DB/SAI): A large number of SAI are lost

### PR DESCRIPTION
**Pull request by PkllonG**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19174

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by avarishd** [comment]
Woops.

**Comment by Nyeriah** [comment]
We will need a squash to address this skipping the commit that deleted stuff, this alone won’t help

**Comment by heyitsbench** [comment]
> We will need a squash to address this skipping the commit that deleted stuff, this alone won’t help

Is that necessary? Anyone that updates past this commit will not have the issue as long as they didn't update to the deletion commit, and updated DBs don't run squashed base queries afaik.

**Comment by Nyeriah** [comment]
> > We will need a squash to address this skipping the commit that deleted stuff, this alone won’t help
> 
> Is that necessary? Anyone that updates past this commit will not have the issue as long as they didn't update to the deletion commit, and updated DBs don't run squashed base queries afaik.

I would need to commit the deleted queries otherwise, and that would add a lot of pollution. With the squash people can just rebuild the db

**Comment by heyitsbench** [comment]
But people can already rebuild the DB as it now stands as of fa51584878897081ce499eaf8439965b6f213dbb, no?

**Comment by sudlud** [comment]
Dropping world DB and restarting server should help for anyone that had executed the faulty sql file. As it is now corrected

**Comment by heyitsbench** [comment]
I do agree with a squash being warranted due to the large amount of updates being required currently, but I don't think this situation makes a squash required, since I don't really see what it changes from a user perspective. I also would like more time to finish the model probability data PR before the squash. 😛

**Comment by Gultask** [comment]
This also happened with TrinityCore a long time ago lol. A bad OR statement deleted the entire smart_scripts table.

I think this should reset the DB
[message(1).txt](https://github.com/user-attachments/files/15994345/message.1.txt)

**Comment by Kitzunu** [comment]
Correct Squash will not "help" in this situation. But I have promised a squash during my vacation time.
I just have to go on vacation first :D

**Comment by FrancescoBorzi** [comment]
1) Go back to the commit preceding the faulty commit
2) Extract all values that were accidentally deleted
3) Re-insert them in a new PR to fix all existing live servers that have already updated their AC version
-- this already puts us in a stable state --
4) Squash the updates and release a new DB to avoid having the big SQL file from step 3) in the updates

**Pull request merged**
