### PR TITLE
Disables the "all flight paths unlocked" after changefaction.

### PR DESCRIPTION
**Pull request by febaut**
## Changes Proposed:
-  CharacterHandler.cpp has a weird conditional structure that unlocks all the flight paths for a player after a faction change. It even does have a comment `//this doesn't seem to be 100% blizzlike... but it can't really be helped.`. However, I'm not sure about the Blizzlike behaviour. After some research, some private servers forums says that it unlocks all the paths wheter or not you had them before. There's no info as far as I saw about how it works blizzzlike. 

- This pull request disables the unlocking.  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10315

## SOURCE:

This is the only info I managed to find but is not totally useful 

https://us.battle.net/support/en/article/178364

## Tests Performed:

-  I checked Trinity Core's sourcer and it has something similar. The result is the same: unlocking all the paths.

## How to Test the Changes:

1. Comment the conditional structre as this PR suggests
2. Create a new char and do .level 30 (The condition requires lvl 7+ but there are some other things one may want to avoid, like money conditions)
3. .char changefaction 
4. Visit a Flight master

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
Tested @Nyeriah review please

**Comment by Nyeriah** [comment]
Hey,

Thanks for the PR, but I don't think this is something we want as default. Having them unlock every fly path is a problem but having without any fly path at all is even more of a problem.

**Comment by febaut** [comment]
Yep, thought so. I think the current code aims to unlock some of them based on player's level, but turns out unlocking all.

**Comment by acidmanifesto** [comment]
Superceeded by https://github.com/azerothcore/azerothcore-wotlk/pull/9729

**Pull request closed without merging**
