### PR TITLE
fix(DB): Remove immunity to bleed effects on Boss

### LINKED ISSUE #9704: Garr, Baron Geddon, and Ragnaros are immune to bleeds
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2557

Currently when testing in the PTR, the elemental bosses in Molten Core are immune to bleeds. This includes [Garr](https://wotlkdb.com/?npc=12057), [Baron Geddon](https://wotlkdb.com/?npc=12056), and [Ragnaros](https://wotlkdb.com/?npc=11502). 

Tester:

The issue is confirmed. [Garr](https://wowgaming.altervista.org/aowow/?npc=12057), [Baron Geddon](https://wowgaming.altervista.org/aowow/?npc=12057) and [Ragnaros](https://wowgaming.altervista.org/aowow/?npc=11502) are immune to bleeds. 

### Expected Blizzlike Behaviour

All NPCs marked under the classification of Boss should supersede their elemental tag, and are able to bleed.  

### Source

https://www.warcraftmovies.com/movieview.php?id=130065

This video is from 2009-11-04, which is during wotlk and did not change later with patch 3.3.5 (2010-6-22). It shows a feral druid casting the spell [Lacerate ](https://wotlkdb.com/?spell=48568) which deals damage, and applies a bleed. While the debuff icons are hard to see on the boss, it is clear in the combat scrolling text that Lacerate is dealing bleed tick damage. This would prove that bosses in MC did in fact bleed during wotlk, even though they are considered vanilla content. 

https://www.warcraftmovies.com/movieview.php?id=143455

Further backed by a video from 2010 here of a warrior rending

https://youtu.be/5aysuiNKgXw?t=52
https://youtu.be/X-Xr4t21Pek?t=181

### Steps to reproduce the problem

check out `mechanic_I_M` in sql

### Extra Notes

I cannot confirm yet if every NPC in a raid zone has the same rules, or if the 3.3.5 client removed bleed immune altogether on all mobs. I will say however that wotlk bosses were also not immune to bleeds, yet were elemental/mech. This included bosses : Algalon the Observer, XT-002 Deconstructor, and Mimiron. This further adds evidence that the wotlk client made steps to remove bleed immunities to certain NPC types. 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
Creatures affected:
- Ragnaros
- Baron Geddon
- Garr

## Issues Addressed:

- Closes #9704 

## Tests Performed:

- Not tested.

## How to Test the Changes:

1. .go c id 11502 12057 12056
2. .lookup spell Rake
3. .cast #SpellID
4. Confirm non bleed immunity

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Voxstrasza** [comment]
I made the same changes on my local before this PR and it allowed bleeds to be applied to these bosses

**Review by Nefertumm — APPROVED** [review]

**Review by Nefertumm — CHANGES_REQUESTED** [review]
Wait, sorry. Use bitwise operators to assign the immune mask please :D
https://www.azerothcore.org/wiki/sql-standards#flags-amp-bits

**Comment by claudiodfc** [comment]
@Nefertumm how's that? :)

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Excellent!

**Pull request merged**
