### PR TITLE
fix(Scripts/Paladin): ensure Judgements of the Just procs Seal of Vengeance/Corruption

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

I can see how this PR can spark some debate, and perhaps it should. I do invite people to read the sources, as well as the original bug report. As a lot of planning went into this from the reporter's side.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16537
- Closes https://github.com/chromiecraft/chromiecraft/issues/5673

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

https://wowpedia.fandom.com/wiki/Patch_3.2.0
Judgments are attacks, patch 3.2:
"Judgments: All paladin judgements are now properly considered as melee attacks that cannot be dodged, blocked or parried."

Again patch 3.2, about SoC/SoCor:
"These seals have been redesigned. Only auto-attacks and Ability paladin hammeroftherighteous [Hammer of the Righteous] can place the debuff on the paladin's current target(s). However, while the seal is active, each melee swing or ability (excluding judgements) that lands on the target will deal a percentage of weapon damage as Holy damage to the target. This damage maxes out at 33% weapon damage with 5 applications of the debuff and scales upward evenly based on how many applications of the debuff are active. This Holy damage deals double-damage critical strikes. In addition, the damage-over-time debuff is now considered a melee attack for the purposes of determining its chance to hit, miss, be dodged or parried."

additional note by me: Reading the above, you can see that an effort was made to remove seal of vengeance or corruption procs on regular judgements. However, as you can also read, it does proc on any other ability. This means, that together with the judgements of the just proc, the seal should most likely proc again, even though it wouldn't proc on judgement alone. For further sources regarding judgements specifically proccing on judgements of the just, check the linked issues.

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. don't learn judgements of the just
2. stand near a target dummy but not in melee range
3. apply seal of vengeance
4. cast judgement
5. see that no seal of vengeance stack has been applied
6. learn judgements of the just (prot talent) (any rank)
7. cast judgement again
8. see that a vengeance stack is applied

## Known Issues and TODO List:

none afaik

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@heyitsbench @Kitzunu @Nefertumm @neifion-00000000 

Have you guys got any info about this? Some hidden mechanic thing? Pending confirmation so it can be merged

**Comment by TimekillerTK** [comment]
Tested. Works exactly as described, following the outlined steps:
```
    1. don't learn judgements of the just
    2. stand near a target dummy but not in melee range
    3. apply seal of vengeance
    4. cast judgement
    5. see that no seal of vengeance stack has been applied
    6. learn judgements of the just (prot talent) (any rank)
    7. cast judgement again
    8. see that a vengeance stack is applied
```

See combat log & talent tree in screenshots, you can see that BC/HV application changes based on `Judgement of the Just` taken as a talent or not.

## Before
On `master` branch.

* `Holy Vengeance` / `Blood Corruption` is not applied on Judgement without `Judgements of the Just`
* `Holy Vengeance` / `Blood Corruption` **is still not applied** on Judgement with `Judgements of the Just`
 
before17470


## After
On `pr-17470`, works exactly as described following outlined steps.

* `Holy Vengeance` / `Blood Corruption` is not applied on Judgement without `Judgements of the Just`
* `Holy Vengeance` / `Blood Corruption` **is now applied** on Judgement with `Judgements of the Just`

after17470horde

after17470alliance

after17470srvinfo



In case anyone wants the exact GM commands I used for testing:
```
## Horde
.character level 80
.learn all my spells
.tele orgrimmar
.go xyz 2114.70 -4665.39 45.70
.setskill 55 400


#Alliance
.character level 80
.learn all my spells
.tele ironforge
.go xyz -4937.18 -1146.84 501.57
.setskill 160 400
```

**Comment by elthehablo** [comment]
Thanks for testing bud. Now we just need checks on wotlk classic to see if behaviour is similar

**Comment by heyitsbench** [comment]
Tested on Classic PTR, the seals did proc with judgements of the wise but not without.

**Comment by elthehablo** [comment]
Judgements of the just you mean I hope? Thanks for testing

**Comment by heyitsbench** [comment]
> Judgements of the just you mean I hope?

Yes, my mistake.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
