### PR TITLE
Fix(Core/Unit): improved handling attribute IGNORE_HIT_RESULT and some parts of immune system

### PR DESCRIPTION
**Pull request by Viste**
**CHANGES PROPOSED**:
- improved handling attribute _IGNORE_HIT_RESULT_
- implement handling attributes  UNAFFECTED_BY_SCHOOL_IMMUNE and UNAFFECTED_BY_AURA_SCHOOL_IMMUNE
- Now counts as a hostile dispel (triggers on-dispel effects: Grobbulus injection etc)
- Can dispel non-deathpersist spells despite ATTR0_UNAFFECTED_BY_INVULNERABILITY (despite the name, this only means they can be applied while immune, not that the aura cannot be removed by immunity), if they do not have SPELL_ATTR1_UNAFFECTED_BY_SCHOOL_IMMUNE (debuffs like recently bandaged etc have this)

**ISSUES ADDRESSED**: must help with #1522 mayby with some others
**Target branch(es)**: Master

### CODE REVIEW

**Comment by GitVerge** [comment]
maybe we need a label for TC ports

**Comment by GitVerge** [comment]
maybe we need a label for TC ports

**Comment by Viste** [comment]
Test will be hard, need check all spells with imnune and parry/block chanses and etc

**Comment by TheHighlord** [comment]
Seems it didn't solve the detterence parry bug.

**Comment by Viste** [comment]
@TheHighlord how do you test it, sreenshoot or etc some more info plz for i can do research fro a right way. blind reserch is hard and long

**Comment by TheHighlord** [comment]
@Viste Well I just added your commit to my core and tested the spell ingame. There is nothing more I can do.

**Comment by GitVerge** [comment]
This could help spells avoidance (probably fix warrior's overpower - deterrence) and immunity spells interactions in some boss encounters. But as @TheHighlord already tested, I don't see which part of the code will fix melee auto attacks parry.

**Comment by Viste** [comment]
@GitVerge https://github.com/azerothcore/azerothcore-wotlk/pull/1575/files#diff-4522eeffcbc961602e86620011a2d579R2527

**Comment by GitVerge** [comment]
> @GitVerge https://github.com/azerothcore/azerothcore-wotlk/pull/1575/files#diff-4522eeffcbc961602e86620011a2d579R2527

that function is for spells (which include melee spells also), but not auto attacks

**Comment by Viste** [comment]
sorry missunderstanding )

**Comment by Viste** [comment]
usles

**Pull request closed without merging**
