### PR TITLE
feat(Metrics): real time statistic visualization

### PR DESCRIPTION
**Pull request by Kitzunu**
* Cherry-pick TrinityCore/TrinityCore@3ae1016

Co-Authored-By: Duarte Duarte <dnpd.dd@gmail.com>

https://github.com/TrinityCore/TrinityCore/commits/3.3.5/contrib/grafana

Requires network threading rework with MPSCQueue

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
It won't work, need replace socket for work this

**Comment by Kitzunu** [comment]
Yea I know, I have just tried to work around it but can't find a way to

**Comment by Kitzunu** [comment]
Maybe we can use realm id instead of name

**Comment by Winfidonarleyan** [comment]
Need my pr

**Comment by Kitzunu** [comment]
Won't be finishing this anytime soon, and if I do, it would be in a new pr

**Pull request closed without merging**
