### PR TITLE
Should Update Create_Mysql.sql

### PR DESCRIPTION
**Pull request by betayi**
Install as  Classsic Setup,Execute with Create_Mysql.sql as Guild Manual,
Will Failed While DB_accemble.sh working on update,
cause this : 
utf8mb4_0900_ai_ci

## Changes Proposed:
-  Correct Homepage Install Guild's Mistake 
-  

## Issues Addressed:

- Closes 

## SOURCE:

CREATE DATABASE `acore_world` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;

CREATE DATABASE `acore_characters` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;

CREATE DATABASE `acore_auth` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8mb4_general_ci;

## Tests Performed:

- 
- 

## How to Test the Changes:

1.CLassic Setup Step To Step 4: Database Install 
2.Follow the guild : excute create_mysql.sql as linked :
Creating and Populating the Database in MySQL with automated script
Creating the Databases and User
First of all you need to create the acore user using the script below.

https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/create/create_mysql.sql

You can perform this with a MySQL client or with the MySQL command-line interface (CLI).

You would need to use one MySQL root account with your MySQL client or with MySQL CLI before starting core to run one of those files (use MySQL root only to import one of those files, never run core as root or administrator).
3.then Importing the Database:
Open $srcpath\apps\db_assambler
Run db_assambler.sh bash apps/db_assembler/db_assembler.sh
Select import-all: Assemble & Import all

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by iraizo** [comment]
doesent `wow_server` automatically populate the database itself?

**Comment by betayi** [comment]
> doesent `world_server` automatically populate the database itself?

it looks a new feature that not mentioned with install guild ?

**Comment by iraizo** [comment]
> it looks a new feature that not mentioned with install guild ?

Yeah its not yet implemented within the wiki.

**Comment by betayi** [comment]
> > it looks a new feature that not mentioned with install guild ?
> 
> Yeah its not yet implemented within the wiki.

Woo,Sounds Good!  hope  wiki update the guild asap  ：）

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
this is good.

utf8mb4_0900_ai_ci is the default collation from MySQL 8.0.1

Source: https://www.monolune.com/what-is-the-utf8mb4_0900_ai_ci-collation/#:~:text=utf8mb4_0900_ai_ci%20as%20the%20default%20collation%20in%20MySQL%208.0.1%20and%20later

**Comment by FrancescoBorzi** [comment]
are we sure about this? isn't this non-existing in MariaDB? can anyone confirm?

**Comment by iraizo** [comment]
> are we sure about this? isn't this non-existing in MariaDB? can anyone confirm?

Yeah this should not be merged since it would break MariaDB

</img>

**Comment by Zanthed** [comment]
This does indeed break MariaDB as MariaDB does not support `utf8mb4_0900_ai_ci`.

Please see the official list of supported charsets and collations: https://mariadb.com/kb/en/supported-character-sets-and-collations/
It does not have `utf8mb4_0900_ai_ci`.

MariaDB and MySQL are fundamentally the same, with differences. MySQL has a more strict and proprietary licensing model with more features, hence this charset and collation. MariaDB has a different licensing model, minimal proprietary features, and built with high performance low latency in mind.

Sources of this breaking MariaDB databases:
- https://mariadb.com/kb/en/migrate-from-mysql-8-to-mariadb-10324-howto/
- https://dba.stackexchange.com/questions/248904/mysql-to-mariadb-unknown-collation-utf8mb4-0900-ai-ci
- https://github.com/drud/ddev/issues/1902#issuecomment-627942845

**Comment by Kitzunu** [comment]
Fick Maria qq

**Comment by betayi** [comment]
make another guide of diffrent database install, just like linux|windows|macos  ?

**Comment by iraizo** [comment]
> make another guide of diffrent database install, just like linux|windows|macos ?

Or just not use the collation

**Pull request closed without merging**
