### PR TITLE
fix(Core/Scripting): Fix healing reduction abilities not applying cor…

### PR DESCRIPTION
**Pull request by Nyeriah**
…rectly

## Changes Proposed:
-  Flip the boolean so it calculates things properly
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10357

## Tests Performed:

- Tested ingame
- 

## How to Test the Changes:

1. aura Mortal strike
2. heal
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Tested with a rogue with wound poison VII and a priest.
Before the poison: 
image

After the poison:
image

**Comment by Nyeriah** [comment]
image

w/o mortal strike

image

**Comment by Nyeriah** [comment]
image
image

Not sure what happened but seems to be working for me

**Comment by Nyeriah** [comment]
@Nefertumm could you please test it again?

**Comment by Nefertumm** [comment]
image
image

Working like a charm now!

**Pull request merged**
