### PR TITLE
fix(LICENSE): restore & apply GPLv2

### PR DESCRIPTION
**Pull request by Helias**
I am applying all files to GPLv2 to respect the old files license MaNGOS and TC.

We were thinking to use AGPLv3, but we can't for maintainability reasons and rules.

Between applying GPLv2 and AGPLv3 together (as before but not maintainable or easy accidentally to violate ) OR only AGPLv3 (against licenses) we are restoring the GPLv2 to respect and be compliant at least with MaNGOS and TC that we truly respect.

We discussed in #staff in the Discord Server, we do not want to violate anything, we would like to put order and maintainable rules here.

Not related but useful to mention: for the rest of the repositories, I am personally more for applying AGPLv3 when it is possible improving and spread the open-source.

**EDIT:** I would like to say thank you to anyone that goes deep into this and want to keep the community compliant and safe regarding rules and licenses.

original PR https://github.com/azerothcore/azerothcore-wotlk/pull/11873 (thanks @Kitzunu)

Progress https://github.com/azerothcore/azerothcore-wotlk/issues/11863

### CODE REVIEW

**Comment by ihm-tswow** [comment]
Hey again guys, I am currently in the process of writing a long ass document detailing **exactly** how you can solve this without going nuclear on your own contributors like this. It will most likely be done tomorrow!

**Comment by Helias** [comment]
Hi @ihm-tswow, I appreciate the effort that you are putting on this, I hope your solution will be better than this, but keep in mind that it should be a doable and maintainable solution.

**Comment by ihm-tswow** [comment]
It's not complicated or unmaintainable at all, I promise. It's simply leaving a special header that defaults the file to GPLv2-or-later, but makes explicit mentions of the time period through which some patches in the document were released as AGPL.

**Comment by Nyeriah** [comment]
> It's not complicated or unmaintainable at all, I promise. It's simply leaving a special header that defaults the file to GPLv2-or-later, but makes explicit mentions of the time period through which some patches in the document were released as AGPL.

Hey,

Wouldn't that still leave us with untouchable chunks of code that nobody would be able to cherry-pick without spreading AGPL to their source? I understand it keeps the commit integrity, but who's going to keep track of what exactly lines are GPL and which are AGPL? It's a good idea for docummentation but does it actually work in practice?

**Comment by ihm-tswow** [comment]
> 
> Hey,
> 
> Wouldn't that still leave us with untouchable chunks of code that nobody would be able to cherry-pick without spreading AGPL to their source? I understand it keeps the commit integrity, but who's going to keep track of what exact lines are GPL and which are AGPL? It's a good idea for docummentation but does it actually work in practice? I don't think files can be licensed that way, it would be far too unfeasiable to keep track of the changes...
> 
> I don't think two licenses could be used for the same file, so it'd still be a void solution

Correct, it would, but so would this, because the code in this repository isn't yours to change like that, and no matter what you re-label it as, that code is still AGPL, you'd just hide the issue away. I will make my case for why I think it's both in your contributors and everyone elses interests that you be as transparent about this as possible 🙂

I wanted to write it so that **any** contributors can understand what is going on, so it's taking some time, but for that reason it'll also try to cover **everything**, from the start to how this licensing stuff works and what it really means to submit patches, down to what the exact options exist for your core from here on forward, what the consequences are for each, and a little about how other projects have handled issues like this in the past.

At the end of the day, yes, you will end up with parts of this core that is internally inconsistent and licensed in ways that is technically impossible, but this is a problem you've had since the very beginning with the way you incorrectly labeled your own GPLv2-or-later files as GPLv2, which was changed one year ago. 

What's worse, **every** core has stolen and incorrectly labeled code in it like this that **nobody** knows who it truly belongs to anymore. This is not about making the **perfect** decision, but the **best** decision that we can, so please stay for my full comment until you make any final decisions on this!

**Comment by Nyeriah** [comment]
Sure, we’re still discussing the best way to handle this.

However, could we avoid using those terms? Open source and stealing aren’t things that go well together and it has never been our goal to do so.

**Comment by ihm-tswow** [comment]
Hi again friends,

With the amount of unclarity surrounding these issues, I have decided to contact the FSF directly with your original issue of replacing license headers. Even if you still decide you want to somehow revert this, I feel like we should at least operate with clarity on what our licenses actually says, and I recommend that you put this on hold until I've heard from them.

For this reason, I will delay my full response to this until I have received an answer from them. You may contact me in the meantime if you need anything.

**Comment by ihm-tswow** [comment]
Document is ready: https://github.com/ihm-tswow/azerothcore-open-letter

**Comment by Helias** [comment]
> Document is ready: https://github.com/ihm-tswow/azerothcore-open-letter

Great job, I read all the summary text so far, you summarized everything making concrete examples.
In short, if I understood correctly, we can put "GPLv2-or-later" and keep the AGPL in new files?
In this way we will respect MaNGOS/TC and we can introduce AGPL for the new files.

Is it correct?

**Comment by Winfidonarleyan** [comment]
sorry for conflict

**Comment by ihm-tswow** [comment]
> > Document is ready: https://github.com/ihm-tswow/azerothcore-open-letter
> 
> Great job, I read all the summary text so far, you summarized everything making concrete examples. In short, if I understood correctly, we can put "GPLv2-or-later" and keep the AGPL in new files? In this way we will respect MaNGOS/TC and we can introduce AGPL for the new files.
> 
> Is it correct?

Correct, exactly what options you have and what they lead to is detailed here specifically: <https://github.com/ihm-tswow/azerothcore-open-letter#my-proposal-stage-3-decimation>

which itself leads to this: https://github.com/ihm-tswow/azerothcore-open-letter#solution-3s3-only-make-promises-that-you-can-keep

**Comment by Helias** [comment]
I would say, let's put all "GPLv2 or later" as it is in this PR and release under AGPLv3 only the new files created by the AC community from scratch as I wrote here https://github.com/azerothcore/azerothcore-wotlk/pull/11887/commits/9a72a1c2f49baa461a138f1ef6a5a0da3106d232

Any objections? possible legal issues?

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
I'd just like to register that I'm strictly against having mixed up licenses. I understand there's no way around the broken files that got mixed, but having the new files follow AGPL3 seems like an unecessary headache. 

Moreover, it still disallows any code that wasn't released under AGPL3 from being picked into or picked out of those files.

It just feels like we are, again, consciently driving towards more trouble in the future. Really makes me question myself why.

The same way maintainers of other projects disallow cherry-picks from us due to messed up licenses, we should probably no longer accept cherry-picks unless they're AGPL3 originated, regardless of the author's consent, to prevent mixing up licenses in those files as well. I wonder who's going to policy that...

**Comment by acidmanifesto** [comment]
What is the status of this PR? Is it abandon?

**Comment by Helias** [comment]
I need to restore the AGPL text for the file created from scratch, I am not finding the time in this period

**Comment by acidmanifesto** [comment]
conflicts. needs fetch upstream, and further discussion. this pr was from mid 2022.
Labeling as wip and conflicts

**Comment by Helias** [comment]
I am really sorry, hope to work with this soon

**Comment by heyitsbench** [comment]
Any updates on this?

**Comment by Helias** [comment]
unfortunately not, I am not finding the time to work on it 😔

**Comment by Helias** [comment]
I've just solved the merge conflicts with master, this PR should set in all files the license GPLv2 except in 32 files that have been created from scratch from the AC community.
There are more files that have been created from the AC community that for now are based on GPLv2, I do not know how to get the full list of files that we wrote entirely from scratch.

We could merge this PR to start this "license fix" and later we could update some files originally created from AC to AGPLv3 or just set the new files under the AGPLv3 license.

What do you think?

**Comment by heyitsbench** [comment]
I'm obviously no project maintainer or anything, but I do think this is an important issue and that some steps should be taken to resolve it sooner rather than later. Though if merging this as is wouldn't entirely solve the issue, I do recommend removing/editing the 'Closes [issue number]' in the PR description.

**Comment by Nyeriah** [comment]
There’s a legal impasse as 1) they can’t simply be changed back 2) we can’t have mixed licenses. Therefore, this wouldn’t solve anything and we’re unable to move on with this.

**Comment by heyitsbench** [comment]
So what now?

**Comment by Nyeriah** [comment]
We could do another wrong and try to rectify the wrongful changes to the license or leave thing as they are. 

Honestly, one of the reasons why I’ve supported this and actively pushed for a resolution to this before was to allow better cooperation with other projects and work out past grievances, but given the latest events I can’t say neither of those goals still hold ground and thus I personally fail to see this is a priority at this point in time. It’s still an illegal move and it likely won’t help our work relations at all (as it seems nobody even cares about this anyway)

**Review by Kitzunu — APPROVED** [review]
If there are no other comments about this within the week, I merge this as-is

**Comment by FrancescoBorzi** [comment]
> If there are no other comments about this within the week, I merge this as-is

we first need to discuss this internally and come to an agreement and make a proper announcement about this.

So I'm parking this for now in order to avoid confusion. I want to stress: I am NOT saying that I'm against this, just that I don't want to rush it because this is quite an important topic.

**Comment by pangolp** [comment]
I don't know if they are going to merge this pull request, but I leave the merge conflict solved. Greetings.

[Conflict.txt](https://github.com/azerothcore/azerothcore-wotlk/files/12249788/Conflict.txt)

**Comment by CraftedRO** [comment]
> I don't know if they are going to merge this pull request, but I leave the merge conflict solved. Greetings.

Of course they won't because they have no honnor.

**Comment by Nyeriah** [comment]
It’s probably best to educate yourself into the subject better before coming here to incite drama.

Nothing is as easy as it seems. 

I believe all the information regarding this subject has been provided. I suggest consulting a lawyer for further inquiry.

Seeing as this discussion has been exhausted, I’ll lock this comment section to avoid further drama.

**Pull request closed without merging**
