### PR TITLE
fix(Scripts/ZulGurub): Shade of Jin'do's invisibility aura should not…

### LINKED ISSUE #11557: [ZG] Jin´do the Hexxer -  Shade of Jin'do can be targetted and attacked without debuff
### Current Behaviour

Shade of Jin'do spawns and can be targetted and killed by anyone

### Expected Blizzlike Behaviour

Only players with delusions of jindo (https://wowgaming.altervista.org/aowow/?spell=24306) should be able to target and kill the shades.

### Source

https://wowwiki-archive.fandom.com/wiki/Jin%27do_the_Hexxer?oldid=2417056

### Steps to reproduce the problem

1. Go to ZG  - Jin'do with 2 chars
2. Wait for shades
3. kill shades without debuff

### Extra Notes

_No response_

### AC rev. hash/commit

59e45c251eb53abb0ed4b37a57254cbdf415e69a
### Operating system

Manjaro x64

### Custom changes or Modules

mod-eluna
mod-progression-system

### PR DESCRIPTION
**Pull request by UltraNix**
… be removed on attack.

Fixes #11557

## Issues Addressed:

- Closes #11557

## Tests Performed:

- Not tested

## How to Test the Changes:

Go to ZG - Jin'do with 2 chars
Wait for shades
Shades should be visible only to players with debuf

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
@temperrr please test it

**Comment by temperrr** [comment]
Tested,

No work.

You are phased from seeing them, but using AOE will still hurt them.

**Comment by UltraNix** [comment]
@temperrr What AOE?

**Comment by temperrr** [comment]
Consecration for instance

**Comment by UltraNix** [comment]
@temperrr AoE spells ignore stealth auras, just like in this case.

**Comment by temperrr** [comment]
Yes but afaik you should not be able to hit them unless you have the debuff on you

**Comment by temperrr** [comment]
afbeelding

**Comment by UltraNix** [comment]
Okay.

**Comment by UltraNix** [comment]
@temperrr Should be okay now.

**Comment by Maelthyrr** [comment]
Tested and everything seems to work fine.

- [X] Shade are only visible and targetable if you get the debuff
- [X] AoE doesn't hit shade

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
