### PR TITLE
fix(DB/Spells): Missing bonus data for paladin judgements

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Re-add missing spell_bonus_data (not ideal but until we fix this shit out)

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13331
- Closes https://github.com/chromiecraft/chromiecraft/issues/4159

## Tests Performed:

- Tested in-game.

## How to Test the Changes:

1. See the issue.
2.
3.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Gultask** [comment]
Works 👍

**Comment by ZhengPeiRu21** [comment]
It looks like I missed a number of spells in https://github.com/azerothcore/azerothcore-wotlk/pull/13104, including this one. Sorry about that! There are more that are missing in addition to Judgement - I will open a PR to correct.

**Comment by ZhengPeiRu21** [comment]
Fixed PR is here: https://github.com/azerothcore/azerothcore-wotlk/pull/13333.

**Comment by Nefertumm** [comment]
Superseded by https://github.com/azerothcore/azerothcore-wotlk/pull/13333.

**Pull request closed without merging**
