### PR TITLE
fix(DB/Creature) Underground Orgrimmar Grunt

### PR DESCRIPTION
**Pull request by warkuss**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16343

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Thanks for the PR!

Can you please rename the file so it has the file extension `.sql`?

**Comment by sudlud** [comment]
thanks for the update, the creature has an entry in `creature_addon` that also has to be deleted

**Comment by elthehablo** [comment]
Do we know the creature can be deleted or rather does it have to be somewhere else? I mean it's fine to delete it for now tbh, but it's likely supposed to be somewhere else but we can just let future sniffs handle that or something

**Comment by elthehablo** [comment]
Yeah that is what I meant

**Comment by pangolp** [comment]
When you are going to add a SQL file, always run the script found inside the folder, which will generate a file and inside it, you can put the fix that you may add. I took the opportunity to replace the file and add the missing `creature_addon`. I hope it helps you and welcome to the ship.

**Comment by heyitsbench** [comment]
> always run the script found inside the folder, which will generate a file and inside it, you can put the fix that you may add.

This has not been necessary for a long time.

**Comment by pangolp** [comment]
I prefer to continue using it, just in case 2 identical files are generated, although I doubt that will happen, but it will much less happen if we use the script.

**Comment by heyitsbench** [comment]
> but it will much less happen if we use the script.

It will never happen with or without the script, as uniqueness is ensured from the SQL query import commits. For example: https://github.com/azerothcore/azerothcore-wotlk/commit/0da6b17f7ba80876be28996e096e86b036808863

**Comment by pangolp** [comment]
Excellent. Thanks for the information.

**Review by sudlud — APPROVED** [review]

**Review by pangolp — APPROVED** [review]

**Pull request merged**
