### PR TITLE
fix(Core/PlayerQuest): make timed quests failable

### LINKED ISSUE #6991: [Barrens][Quest] No Fail Condition For "Apothecary Zamah" After Logging Out For The Duration Of The Countdown
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1217

The fail condition for Apothecary Zamah (https://wowgaming.altervista.org/aowow/?quest=853) doesn't trigger if you log out during the whole countdown and then log in when the timer has reached zero (0), allowing you to complete the quest even if the timer has reached zero (0).

### Expected Blizzlike Behaviour

The fail condition must **always** trigger when the timer has reached zero, regardless if you logged out during the whole countdown.

### Source

Basic timed quest mechanics.

### Steps to reproduce the problem

1. Accept the quest "Apothecary Zamah" (https://wowgaming.altervista.org/aowow/?quest=853).
2. Stay logged out for the duration of the countdown (45 minutes).
3. Log in again.
4. Notice that the fail condition did not trigger and you can still complete the quest even when the timer is zero.

### Extra Notes

I reproduced this problem 3 times just to make sure.

WoWScrnShot_071621_022443

Another user had also experienced this issue months ago:
https://github.com/chromiecraft/chromiecraft/issues/57
It was marked **invalid** because the triager misunderstood the problem since the bug reporter explained it very poorly. 
The triager only logged out for a few seconds. Note that you need to stay logged out for the duration of the countdown (45 minutes).

Tested on: c17ce009d

### PR DESCRIPTION
**Pull request by sudlud**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

Timed quest 853 always has questState "QUEST_STATUS_COMPLETE" so it would never be able to fail within `FailQuest()`

## Issues Addressed:

- Closes #6991
- Closes https://github.com/chromiecraft/chromiecraft/issues/1217

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

```sql
-- reduce quest timeout to 60 seconds
UPDATE `quest_template` SET `TimeAllowed` = 60 WHERE (`ID` = 853);
```

.quest add 853
logout for at least 1 minute
login

before PR
observe quest not failed and no timer showing

after PR
observe quest beeing failed correctly

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Have you checked if this allows for already complete quests to fail after the timer expires? E.g the warrior level 15 quest

**Comment by sudlud** [comment]
> Have you checked if this allows for already complete quests to fail after the timer expires? E.g the human warrior level 15 quest
> 
> It has been the case before

I can re-check later, but the quest I tested is also "complete" right from the beginning while the timer runs and was therefore unable to fail.

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Sad... no free timed quests kek

**Comment by sudlud** [comment]
> Have you checked if this allows for already complete quests to fail after the timer expires? E.g the human warrior level 15 quest It has been the case before

Quest 853 is "completed" right from the beginning and fails correctly when the time runs up.

**Pull request merged**
