### PR TITLE
fix(Core/Player) Stop small durability loss from still occuring when DurabilityLoss options in worldserver.conf are set to 0

### PR DESCRIPTION
**Pull request by hallgaeuer**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

A small durability loss on e.g. death still occurs even when all the "DurabilityLoss" options in worldserver.conf are set to 0.
This happens because the calculation for the actual durability points lost always "rounds up" to 1 point at the minimum.

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

No source, because this is a non-blizzlike server configuration.

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Set all "DurabilityLoss" options in worldserver.conf to 0 and restart your server
2. Get killed by an enemy of your choice (don't use the .die command, which doesn't seem to incur durablity losses?)
3. Observe that no durability is lost on equipped items

I have also verified that durability is still correctly lost if configured so in worldserver.conf.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Would it not be preferable to have the if statement on L4664 check for a case of zero percent?
```cpp
if (pDurabilityLoss && pDurabilityLoss < 1)
```

**Comment by hallgaeuer** [comment]
> Would it not be preferable to have the if statement on L4664 check for a case of zero percent?
> 
> ```c++
> if (pDurabilityLoss && pDurabilityLoss < 1)
> ```

I think that could cause side effects. `pDurabilityLoss` is an int value of the actual durability points lost. 
The condition seems to ensure that there's always at least one point lost, even when the configured percentage lost is very small. 

With your proposed change small durability loss percentages wouldn't lose any durability points anymore I think. 
Which is why I still prefer the early return if the percentage is actually 0.

At least that's my understanding of it. Feel free to correct me if I'm wrong :)

**Comment by Nefertumm** [comment]
I don't like this, using comparision operators between double type (float, etc) is bad.

**Comment by hallgaeuer** [comment]
It's not always "bad". In fact it depends on the use case. Comparing floating points to zero in this way is fine, if the value is not the result of some calculation (which it isn't in this case, it's just a config). 
A quick google seach "c++ comparing float to zero" do reveal plenty of results saying it's fine.
But you're welcome to propose another way.

**Comment by Nefertumm** [comment]
Ah, then it's fine. I thought this was indeed a result of some calculation, that's why I said that. If that's just the config value, then we're good.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
