### PR TITLE
fix(SQL): Remove wrong comment

### PR DESCRIPTION
**Pull request by Kitzunu**

### CODE REVIEW

**Review by malcrom — APPROVED** [review]

**Comment by Nyeriah** [comment]
I think this doesn't work like this unfortunatelly, we need to check if the following files applied successfully even though this one failed, and if they did, it' probably better we don't touch this since then it'll reapply to this revision. Not entirely sure though

**Comment by Kitzunu** [comment]
I guess what we could do is nuke the file

**Comment by Kitzunu** [comment]
💥

**Comment by Nyeriah** [comment]
why was this merged? did we test if it doesn't break the database revision?

**Pull request merged**
