### PR TITLE
fix(Scripts/VoA) Vault of Archavon:

### LINKED ISSUE #2823: Vault of Archavon Bosses - Incorrect Scripts/Visuals/etc [$15]
##### SMALL DESCRIPTION:
Emalon the Storm Watcher:  Adds do not respawn when they explode, but do respawn when killed via damage.  Video: https://youtu.be/OWqc-ayUNis

**FIXED BY #2868**  --  Toravon the Ice Watcher:  On 25-man, only one Frozen Orb spawns, and Whiteout is tied to the Frozen Orb death.  Ex: Kill a Frozen Orb, and Whiteout will be cast.  When multiple Frozen Orbs are killed, multiple Whiteout's will be casted on the raid.  Additionally, the visual for Whiteout is missing.  Video: https://youtu.be/R15BH1zM84M

Koralon the Flame Watcher:  When he casts Burning Breath, he faces one direction.  Video: https://youtu.be/Bdz3eYpeLJI

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Emalon the Storm Watcher:  Adds should respawn, regardless how they die - whether it is because they explode or because they are killed.

Toravon the Ice Watcher:  On 25-man difficulty, three Frozen Orbs should spawn.  The first Whiteout should be cast **24 seconds** after the initial pull, and then every **38 seconds** after that, and it should accompany a visual effect.  Retail video: https://youtu.be/VMsP_8F6BvQ

Koralon the Flame Watcher:  Burning Breath is an AoE ability, and Koralon should spin in place when he channels this.  Retail video: https://www.youtube.com/watch?v=Vgrw5_zPoOE

##### CURRENT BEHAVIOUR:
Emalon the Storm Watcher:  Currently, when adds explode, they will not respawn.  They will respawn if they are killed via damage.

Toravon the Ice Watcher:  Only one Frozen Orb spawns on 25-man difficulty.  Whiteout does not have a visual when it is used, and it is tied to a Frozen Orb dying.

Koralon the Flame Watcher:  When he uses Burning Breath, he faces a random direction and remains facing that way for the entire duration.

##### STEPS TO REPRODUCE THE PROBLEM:
1.   Enter Vault of Archavon on 25 man difficulty
2.   Pull Emalon the Storm Watcher
3.   Wait until he overcharges a Tempest Minion, and wait until it has 10 stacks of the debuff.  It will explode and not spawn again, leaving you with 3.  Kill the other 3, and the 3 will respawn.  There should be 4 throughout the entire encounter.
4.   Pull Koralon the Flame Watcher
5.  Wait until Burning Breath, notice he faces one direction.
6.  Pull Toravon the Ice Watcher.
7.  Wait until Frozen Orbs spawn, and kill them.  Toravon will then cast Whiteout multiple times, depending on how many Frozen Orbs you kill.  There will be no visual effect.

##### EXTRA NOTES:
N/A

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
1411336dcbbc

##### OPERATING SYSTEM:
Win 10

##### MODULES:
N/A

##### OTHER CUSTOMIZATIONS:
Modified health on bosses

<bountysource-plugin>

---
There is a **[$15 open bounty](https://www.bountysource.com/issues/90840546-vault-of-archavon-bosses-incorrect-scripts-visuals-etc?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Emalon: Tempest Minions should kill self instead of despawning in order to trigger `SummonedCreatureDies` in Emalon's script
Koralon: Clears out UNIT_FIELD_CHANNEL_OBJECT, so Koralon can spin in during Burning Breath.
Fixed #2823.

## Changes Proposed:
-  As for UNIT_FIELD_CHANNEL_OBJECT clearing - just like during Mimiron's Spinning, there should be a trigger that runs/float around the room and Koralon should target it via Burning Breath (rotate is done automatically thanks to clientside attribute SPELL_ATTR1_CHANNEL_TRACK_TARGET). Needs sniffs to track this trigger.
-  

## Issues Addressed:
- Closes #2823.

## Tests Performed:
-
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@UltraNix test performed? How to test the changes? please fill out those

thanks for your contribution

**Comment by UltraNix** [comment]
Yes, tested. Both works.
How to test - it's explained in addressed issue.

**Comment by pklloveyou** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
thanks @pklloveyou 

@UltraNix the build is failing

**Comment by UltraNix** [comment]
I see, but I don't know why.  Fails on "Configure OS".

**Comment by FrancescoBorzi** [comment]
> I see, but I don't know why. Fails on "Configure OS".

ah, it happens sometimes, not something on our side. I've just restarted the build, let's see if it passes this time.

**Review by Si1ker — APPROVED** [review]

**Comment by Si1ker** [comment]
Keepers are ok and koralon...

Koralon SPINNING !!! <3

Tested and next to merge !! 🎉 

image

**Pull request merged**
