### PR TITLE
feat(Core/BG): revamp Battleground.QueueAnnouncer.Limit

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## Changes Proposed:
-  Revamped the `Battleground.QueueAnnouncer.Limit.*` configuration
-  Instead of only being able to enable/disable it, added a `MinLevel` so it allows to enable only for that level and higher levels
- When limited, it announces only if one more player is needed to start the BG
-  At 80 it only limits RBG, at lower level only limits Warsong Gulch.

The config values are the following (let me know if something is not clear enough):

```
#
#    Battleground.QueueAnnouncer.Limit.MinLevel
#        Description: Limit the QueueAnnouncer starting from a certain level.
#                     When limited, it announces only if there are at least MinPlayers queued (see below)
#                     At 80 it only limits RBG, at lower level only limits Warsong Gulch.
#        Default:     0 - (Disabled, no limits)
#                     10 - (Enabled for all, because BGs start at 10)
#                     20 - (Enabled for 20 and higher)
#                     80 - (Enabled only for 80)

Battleground.QueueAnnouncer.Limit.MinLevel = 0

#
#    Battleground.QueueAnnouncer.Limit.MinPlayers
#        Description: When the Battleground.QueueAnnouncer.Limit.MinLevel limit is enabled (not 0)
#                     only show when at least MinPlayers are queued.
#        Default:     3 - (Show only when 3 or more players are queued)

Battleground.QueueAnnouncer.Limit.MinPlayers = 3

```

Basically:

```
- I want to limit the Queue announce messages
- I want to limit them only for Warsong Gulch (if level is < than 80) and RBG (at 80)
- I want to limit only starting from a certain level (e.g. if I set it to 30, I'm NOT limiting 10-19 and 20-29 but only 30-39 and higher)
- The limit is basically: show the announce only when there are AT LEAST Battleground.QueueAnnouncer.Limit.MinPlayers queued players
```

## Tests Performed:

- see comments below

## How to Test the Changes:

- Set `Battleground.QueueAnnouncer.SpamProtection.Delay = 1`
- Install https://github.com/azerothcore/mod-cfbg and set `CFBG.EvenTeams.Enabled = 1`
- Checkout https://github.com/azerothcore/mod-cfbg/pull/55 in the CFBG module (`cd modules/mod-cfbg; git checkout revamp-bg-queue-limit`)
- Play with the new configurations `Battleground.QueueAnnouncer.Limit.MinLevel` and `Battleground.QueueAnnouncer.Limit.MinPlayers` and make sure they work fine

- I hope the description and test instructions are clear enough, if not please let me know. Otherwise I'm going to assume it's clear for you how this is supposed to work and how to test it.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@sedatyf when you have some time, could you please test this?

**Comment by Sedatyf** [comment]
Yeah sure. I'll test some PR tonight, I'll see if I find time for it 😄

**Comment by Sedatyf** [comment]
It's weird, I have errors on building this PR. Here what I did:
- Downloaded https://github.com/azerothcore/mod-cfbg as a zip
- Extracted it in my ``module`` folder
- Changed ``CFBG.EvenTeams.Enabled`` from ``0`` to ``1``
- Made a new branch from Master
- Pulled this PR
- Deleted my ``build`` folder
- Launched CMake
- Launched fresh build
Finally Visual gave me this:
image
I'm on a Windows 10 server

**Comment by FrancescoBorzi** [comment]
@Sedatyf my bad, you need this as well in the CFBG: https://github.com/azerothcore/mod-cfbg/pull/55

**Comment by Sedatyf** [comment]
Nevermind, I'm just thinking outloud.
I added 
```conf
#    Battleground.QueueAnnouncer.Limit.MinLevel
#        Description: Limit the QueueAnnouncer starting from a certain level.
#                     When limited, it announces only if one more player is needed to start the BG.
#                     At 80 it only limits RBG, at lower level only limits Warsong Gulch.
#        Default:     0 - (Disabled, no limits)
#                     10 - (Enabled for all, because BGs start at 10)
#                     20 - (Enabled for 20 and higher)
#                     80 - (Enabled only for 80)

Battleground.QueueAnnouncer.Limit.MinLevel = 0

#
#    Battleground.QueueAnnouncer.Limit.MinPlayers
#        Description: When the Battleground.QueueAnnouncer.Limit.MinLevel limit is enabled (not 0)
#                     only show when at least MinPlayers are queued.
#        Default:     3 - (Show only when 3 or more players are queued)
```
in my ``worldserver.conf``

**Comment by Sedatyf** [comment]
So for those tests.
When ``Battleground.QueueAnnouncer.Limit.MinLevel`` is at ``80``:
- There was no announce when I tagged in RBG at level 80
- There was an announce when I tagged in WG/Arathi/etc. (everything, except RBG) at level 80
- There was no announce when I tagged as a character under 80

When ``Battleground.QueueAnnouncer.Limit.MinLevel`` is at ``10``:
- There was an announce when I tagged in RBG at level 80
- There was an announce when I tagged in WG/Arathi/etc. (everything, except RBG) at level 80
- There was no announce when I tagged at level 15

When ``Battleground.QueueAnnouncer.Limit.MinPlayers`` is at ``3``:
- There was an announce when I tagged with only character

I don't know if I did those tests correctly to be honest, so here is my process in order to see if I am the cause of this or if it's code:
- In my ``CFBG.conf`` in ``azerothcore(worldserver)/configs/modules/`` I have the following values:

```CFBG.Enable = 1
CFBG.BalancedTeams = 1
CFBG.Include.Avg.Ilvl.Enable = 0
CFBG.Players.Count.In.Group = 3
CFBG.EvenTeams.Enabled = 1
CFBG.EvenTeams.MaxPlayersThreshold = 5
```

- In ``worldserver.conf`` in ``azerothcore(worldserver)/configs/`` I changed those values:
   - ``Battleground.QueueAnnouncer.Limit.MinLevel``
   - ``Battleground.QueueAnnouncer.Limit.MinPlayers``

When I made changes in ``worldserver.conf``, I killed Worldserver with CTRL+C, saved my file, and launched it again

**Comment by FrancescoBorzi** [comment]
> If a 10-19 character queues in Warsong Gulch, whereas Battleground.QueueAnnouncer.Limit.MinLevel is set to 30, there is no announcements, which is not correct ❌

There was indeed a (silly) mistake in the `MinLevel` logic which I've just fixed and pushed the changes both to the main core repo and the CFBG module repo. So both of them should be updated.

I've performed some tests locally and it seems to work fine now, I also did other generic tests to this system and I couldn't see any issue. However I want to wait for @Sedatyf final approval before merging this :)

**Review by Helias — APPROVED** [review]

**Comment by Sedatyf** [comment]
Tested it on stream with @FrancescoBorzi and everything is working as intended! Congrats 🥳

**Pull request merged**
