### PR TITLE
fix(Core/Guild): Crash during money deposit / withdrawal

### PR DESCRIPTION
**Pull request by Shard-MW**
Tests performed on MySQL. 
Maybe we need to try it on MariaDB too ?

##### ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2504

##### TESTS PERFORMED:
- Made a deposit of various gold amount : 100g, 1000g, 210000g
- Made a withdraw of various gold amount : 100g, 1000g, 210000g
- Checked if logs are well written in ac_characters.log_money

##### HOW TO TEST THE CHANGES:
- Join/Create a guild
- Try to deposit/withdraw
- Check if the amount logged is correct

##### Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by wowpide** [comment]
Will test ASAP , good job 👍

**Comment by wowpide** [comment]
confirmed no crash after applying fix, well done

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan or @Viste can you please try this on MariaDB ?

**Comment by pangolp** [comment]
I share the record with you, but I don't know if it's the result you were getting. I tried it in Windows 10 with Mysql 5.7
<a href="https://subefotos.com/ver/?3874fe2da197037371c4c79e1d68a451o.png" target="_blank"></a>

**Comment by Nefertumm** [comment]
It would be great if we can merge this due it's a critical issue.

**Pull request merged**
