### PR TITLE
fix(DB/Creature): Knight-Lieutenant T'Maire Sydes

### PR DESCRIPTION
**Pull request by Kitzunu**
This is originally from TC, but I cannot find the original commit so I cannot reference.

## CHANGES PROPOSED:
-  Replace Knight-Lieutenant Moonstrike to T'Maire Sydes
(proof: https://wowwiki.fandom.com/wiki/Knight-Lieutenant_Moonstrike `Wrath-Logo-Small Patch 3.3.3 (2010-03-23): Replaced by Knight-Lieutenant T'Maire Sydes
`)

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
-
-

## HOW TO TEST THE CHANGES:

1. .go c 133917

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by merdlin** [comment]
Tested, this PR works. but I have a doub. there were no vendor's items?

**Comment by Helias** [comment]
I am not sure about this PR, this NPC depends on the ARENA SEASONS, the Furious Gladiaot'rs is not available in the vendor.
Probably this vendor is activated about some `event` of the season. I don't think that it is bugged, should be a too much important bug.

**Comment by Kitzunu** [comment]
Well since this branch runs on 3.3.5 Knight-Lieutenant Moonstrike should clearly not be in the game

**Comment by merdlin** [comment]
Tested, this PR works.

**Comment by Knindzagxg** [comment]
This NPC will work if you select Season 5 in world config.
In other words, depending on config setup, different NPC's will be spawn in Area 51, Stormwind, Orgrimmar and Dalaran.

**Comment by Knindzagxg** [comment]
It's nice to keep him up in DB, cause a lot of servers choose to go progressive, Arena and Raid wise.

**Pull request closed without merging**
