### PR TITLE
refactor(Core): apply clang-tidy modernize-use-default-member-init

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-use-default-member-init`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-default-member-init.html

### How to test the changes

This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:

- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game and play around a bit
- All good so far? Then this should be good to go

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-use-nullptr`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html

### How to test the changes

This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:

- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game
- All good so far? Then this should be good to go

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by JamesGent** [comment]
E325: ATTENTION
Found a swap file by the name "C:/azerothcore-wotlk/.git/.MERGE_MSG.swp"
          owned by: james   dated: Fri Nov 13 17:55:18 2020
         file name: /c/azerothcore-wotlk/.git/MERGE_MSG
          modified: YES
         user name: james   host name: Grasswalker
        process ID: 1777
While opening file "C:/azerothcore-wotlk/.git/MERGE_MSG"
             dated: Wed Dec 02 14:33:46 2020
      NEWER than swap file!

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r C:/azerothcore-wotlk/.git/MERGE_MSG"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "C:/azerothcore-wotlk/.git/.MERGE_MSG.swp"
    to avoid this message.

Swap file "C:/azerothcore-wotlk/.git/.MERGE_MSG.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort:

**Comment by FrancescoBorzi** [comment]
@JamesGent mmmh not sure what's happening, apparently something wrong with your `.git` files. Can you try to re-clone the repository and try again from a clean setup?

**Comment by nicoaravena** [comment]
Results from testing:

- Compilation with `-DTOOLS=1` work fine (no time for testing extraction maps sorry)
imagen

- Start server is ok.
imagen

- Playing around without any problems.
imagen

**Comment by FrancescoBorzi** [comment]
thank you @nicoaravena !

**Review by Helias — APPROVED** [review]

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
