### PR TITLE
fix(CI): Only run macos build if ubuntu build is successful

### PR DESCRIPTION
**Pull request by locus313**
## Changes Proposed:
-  make macos build dependent on ubuntu build success. (Since macos build's take the longest, we shouldn't run them if there is already a failure on the ubuntu build)

## Issues Addressed:
- Closes none

## Tests Performed:
failure test:
image

successful test:
image

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
Actually, this makes the checks even slower now, as one of the MacOS builds are "Required" and need to wait for first Ubuntu and then MacOS build before we can merge, etc D:

**Comment by locus313** [comment]
true it does make the individual build take a little longer, but it seems to be helping with having the overall builds queued for 8+hours.

**Comment by Kitzunu** [comment]
pog

**Comment by FrancescoBorzi** [comment]
I think this is better and will save us useless macOS builds

**Pull request merged**
