### PR TITLE
fix(Core/Dungeon) BRD - The seven minibosses re-order

### LINKED ISSUE #1772: BRD The seven minibosses don't work properly
###### SMALL DESCRIPTION:
The seven minibosses don't work properly miniboss doomrel should be the last to start the attack and also stop the event. and the chest spawns wrong too.

Loot Chest fix for Position

REPLACE INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `ScriptName`, `VerifiedBuild`) VALUES (67872, 169243, 230, 0, 0, 1, 1, 1266.18, -285.451, -78.2193, 3.93, 0, 0, 0.909298, 0.416147, -300, 100, 1, '', 0);

Offi Video https://youtu.be/GR_CQ-eC6ns?t=1380

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The order of the event is wrong.

Events start Boss Doomrel ID 9039

1 attacker is Anger'rel ID 9035
2 attacker is Seeth'rel ID 9038
3 Attacker is Dope'rel ID 9040
4 Attacker is Gloom'rel ID 9037
5 attacker is Vile'rel ID 9036
6 attacker is Hate'rel ID 9034
7 attacker is Doom'rel after his death spawnt the chest and the doors go back to ID 9039

the chest spawnt next to the door see video

##### CURRENT BEHAVIOUR:
1 attacker is Doom'rel ID 9039
2 Attacker is Dope'rel ID 9040
3 attacker is Hate'rel ID 9034
4 Attacker is Vile'rel ID 9036
5 attacker is Seeth'rel ID 9038
6 attacker is Gloom'rel ID 9037
7 attacker is Anger'rel D 9035

##### STEPS TO REPRODUCE THE PROBLEM:
.go creature 91020 and start the event.

##### BRANCH(ES):
AzerothCore rev. 22d4cae+ 2019-04-22 13:36:54 +0200 (master branch) (Win64, Release)

##### OPERATING SYSTEM:
Windows 10

##### MODULES:
mod transmog
mod_world_chat

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/73335232-brd-the-seven-minibosses-don-t-work-properly?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

- Swapped timers to EventMap
- 1st attacker is Anger'rel
- 2nd attacker is Seeth'rel
- 3rd Attacker is Dope'rel
- 4th Attacker is Gloom'rel
- 5th attacker is Vile'rel
- 6th attacker is Hate'rel
- 7th attacker is Doom'rel

###### ISSUES ADDRESSED:

Closes #1772 

##### TESTS PERFORMED:

No testes performed.

##### HOW TO TEST THE CHANGES:

Events start Boss Doomrel ID 9039

Either one of the two choices:
1. Look on the database for the GUID on creature with entry 9039 and then do
.go c \<guid\>
2. Do the entire dungeon

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Seebaby** [comment]
Does not work 

The event is started at DOOMREL but he is also the first to attack.
If you kill him comes the 2 boss SEETHREL then comes the booty chest and the doors open.

**Comment by Pondaveia** [comment]
@comix1988 can you retest? If this doesn't start on Anger'rel I already know the reason. I can't test right now I'm just coding from work :) Thanks in advance

**Comment by Seebaby** [comment]
So it looks so far quite good except for the Anger'rel not as the first comes it starts with number 2 Seeth'rel but then has the right sequence.

Anger'rel seems as if he was skipped

**Comment by Pondaveia** [comment]
it was skipped indeed because before the fight starts, a counter is increased before the first boss fight, which means that instead of starting on boss 0 (Anger'rel) it starts on boss 1 (Seeth'rel).  In programming 0 is a real number I'm sorry if this confuses you but, you are right! First boss is being skipped.
It should be fine now @Seebaby 😄 Thanks for the help.

**Comment by Seebaby** [comment]
Everything looks good only that you can still address the Start Boss Doom'rel after the event has started and click on the gossip you should perhaps change everything else perfect now

**Comment by Pondaveia** [comment]
@Seebaby wanna give it another shot again?

**Comment by Seebaby** [comment]
> @Seebaby will es noch einmal schießen?

Sure, I'm always here to test it out.

**Comment by Pondaveia** [comment]
Don't bother, that last commit wont fix it. I was coding from phone let me get home first

**Comment by Seebaby** [comment]
> Don't bother, that last commit wont fix it. I was coding from phone let me get home first

All right.

**Comment by Pondaveia** [comment]
@Seebaby Done :)

**Comment by poszer** [comment]
Thanks @Pondaveia for this fix, and @Seebaby for testings :+1:

**Comment by BarbzYHOOL** [comment]
awesome guys

@Seebaby are you in our discord?

**Pull request merged**
