### PR TITLE
fix(DB/SAI): Missing Creature Twilight Corruptor

### PR DESCRIPTION
**Pull request by Endeffect-AT**
NPC id 15625 missing in creature table to complete quest 8735

## CHANGES PROPOSED:
-  Add creature 15625 with new guid 3110362 

Creature was added in patch 1.9.0 and should be there in 3.3.5a since it was never removed. 
Source: https://wowwiki.fandom.com/wiki/Twilight_Corrupter

Source of position found online: 
unnamed
Post from 2009: https://twilight-sucks.livejournal.com/486659.html

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Imported sql with HeidiSQL on win 10 pro x64
- Checked successfully ingame

## HOW TO TEST THE CHANGES:

1. Import sql file
2. Check creature ingame 

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Nice thank you, but does the creature have a script too?

**Comment by Endeffect-AT** [comment]
@BarbzYHOOL 
Unfortunately I can not answer you, but I lack the knowledge about smart scripts.

**Comment by BarbzYHOOL** [comment]
Check the related entry in creature_template, look up at the bottom columns "AIName" if it's SmartAI then check the related entry in smart_scripts

Then can test it ingame xD

**Comment by Endeffect-AT** [comment]
If i understand correctly it's a C++ script
image

**Comment by gengarshadowball** [comment]
Yea, that's a core script

**Comment by Stoabrogga** [comment]
It's this CreatureScript:
https://github.com/azerothcore/azerothcore-wotlk/blob/832bccd9fa8ae5f3dd20eaeed244e74cd700f2de/src/server/scripts/EasternKingdoms/zone_duskwood.cpp#L38

**Comment by Endeffect-AT** [comment]
Do I understand correctly that this code has to spawn the creature when the player is on this quest? So it didn't appear all the time?

https://github.com/azerothcore/azerothcore-wotlk/blob/832bccd9fa8ae5f3dd20eaeed244e74cd700f2de/src/server/scripts/EasternKingdoms/zone_duskwood.cpp#L142-L164

**Comment by Stoabrogga** [comment]
Yes, seems to be the case. Probably adding it directly to the creature table is wrong in this case.

**Comment by Endeffect-AT** [comment]
Okay so the script just doesn't work in that case :sweat_smile: 
I'm not a core dev so didn't looked on any script because I can only read the code a little as a layperson

**Comment by Stoabrogga** [comment]
So he does not spawn if you're on the quest "The Nightmare's Corruption"?

**Comment by Endeffect-AT** [comment]
Correct. As I have described above, the quest cannot be completet because the creature does not spawn.

**Comment by Stoabrogga** [comment]
Hmm, the script is assigned to area 4017 in "[areatrigger_scripts](http://www.azerothcore.org/wiki/areatrigger_scripts)"
| entry | ScriptName        |
|-------|-------------------|
|  4017 | at_twilight_grove |

But there doesn't seem to be an area 4017 in 3.3.5:
http://www.azerothcore.org/wiki/AreaTable

Perhaps it is just using the wrong area ID as "Twilight Grove" has the ID 856.

**Comment by Stoabrogga** [comment]
Sorry, I used the wrong area table... 4017 is a reference to this:
http://www.azerothcore.org/wiki/DBC-AreaTrigger

**Comment by Endeffect-AT** [comment]
Is there any way to see creatures like that which are summoned by a script in creature table? If i look at the creature table i couldn't find the ID 15625 and that's why I assumed that the entry is completely missing. 

It would be very helpful for people like me which has not much knowledge about c++.

**Comment by Stoabrogga** [comment]
No, because it is summoned. Summoned creatures are (obviously) not part of the creature table. What you could do is search the source code for the creature ID 15625, you'll then find this:
https://github.com/azerothcore/azerothcore-wotlk/blob/832bccd9fa8ae5f3dd20eaeed244e74cd700f2de/src/server/scripts/EasternKingdoms/zone_duskwood.cpp#L21

I do this regularly when looking for specific spell, creature, gameobject IDs etc. which I assume are used in core scripts.

**Comment by Endeffect-AT** [comment]
Learned something again, thank you @Stoabrogga! 

To solve the problem now should I close the PR and open an isse?

**Comment by Stoabrogga** [comment]
You're welcome. If you don't know why the areatrigger script is not running, then yes, close this PR and open an issue. What you could test if you have the time: Teleport to the area 4017 and check if it is the correct position for the Twilight Grove:
`.go -10636.200195 -391.307007 101.877998 0`

Sadly, I currently don't have the time to test this.

**Comment by Stoabrogga** [comment]
The script works correctly. You need quest 8735 **without** the quest item and have to run down the way into the grove in order to trigger it because areatrigger 4017 is just a small part of that way. It won't work if you teleport into the grove, but players cannot do this anyway.

**Comment by Endeffect-AT** [comment]
That was my mistake, I did not assume an area trigger. It works as expected!

**Pull request closed without merging**
