### PR TITLE
fix(Core/Loot): Always interrupt any spell casting while looting corpse.

### LINKED ISSUE #8860: [Core] Looting while mounting up
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/2224

After finishing the casting of the mounting spell, you may loot before getting the mounted up buff (any mount really).

In this video, I show looting while casting, looting after casting and looting while mounted up.
I had auto-loot on but it also does work without auto-loot.

https://user-images.githubusercontent.com/22718174/139591606-f0983958-6514-4b8c-afdd-a891ebfdab31.mp4

Tester: Confirmed
image

### Expected Blizzlike Behaviour

I should get dismounted or my mounting be cancelled.

### Source

_No response_

### Steps to reproduce the problem

Start casting your mount.
Loot as soon as the casting has finished.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #8860

## Issues Addressed:

- Closes #8860
- Closes https://github.com/chromiecraft/chromiecraft/issues/2224

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Start casting your mount.
2. Loot as soon as the casting has finished.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@jamadaha Please, test it.

**Review by Nefertumm — APPROVED** [review]

**Comment by acidmanifesto** [comment]
This confuses me honestly. And it isnt the PR that confuses me, but why are we doing a check after the designated outcome?
We dont give a store item then do a money check, we do the money check before the store item is given.
This PR honestly looks like it corrects a very vague and often over looked oversight.
My opinion, this PR makes sense to send the loot after ALL the checks, not inbetween.
image

**Comment by UltraNix** [comment]
@acidmanifesto I don't understand you at all :)

**Comment by acidmanifesto** [comment]
> @acidmanifesto I don't understand you at all :)

I am saying, the load order adjustment you are PR makes more sense as it does the send loot after all the checks, not inbetween the checks.

**Comment by UltraNix** [comment]
In this particular case - yes.

**Comment by claudiodfc** [comment]
### Test result: ✔
- Dismounts after loot.

**Pull request merged**
