### PR TITLE
DB: Shattered sun marksman SAI

### LINKED ISSUE #696: Shattered Sun Marksman Quel'Danas
sun marksman server Server Version

**Description**: There are Shattered Sun Marksman in Quel'Thalas that are using the wrong animation for the bow and missing their correct equipment.
**Current behaviour**: Doesn't have the correct equipment id/gear and is shooting like the npc is using a gun, but in-fact is using a bow.
**Expected behaviour**: Supposed to have the correct equipment id/gear and should be shooting with bow animation. Here is a link to wowhead. http://www.wowhead.com/npc=24938/shattered-sun-marksman

**Steps to reproduce the problem**:

1. Login
2. Goto Quel'Thalas `.go creature 24938`
3. Find Shattered Sun Marksman and look at their animation/gear

**Branch(es)**: Master(es)

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/d0af1c812bf4ea15204cad37b39ff27ff6bae339

**Operating system**:  Windows 10

**Modules**:  Solorcraft, npcenchanter, transmog, congratsonlevel, moneyforkills, randomenchants

**Other Customizations**: Added in cata->mop->wod models, items etc. With patches for it.

sun marksman Retail Version

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/50596622-shattered-sun-marksman-quel-danas?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

- On reset make the NPC sheath his/her bow out

###### ISSUES ADDRESSED:

Closes #696 

##### TESTS PERFORMED:

Tested in-game

##### Target branch(es):

Master

### CODE REVIEW

**Comment by d3tr0l** [comment]
I am very sorry to say that, but this did not fix the issue and it made it even worse. At least for me. Can anyone else confirm?

**Comment by BarbzYHOOL** [comment]
@d3tr0l , you need to test before and after, read what the issue is about and not talk about UNRELATED issues.

Maybe there is an issue with their AI but the fix is about their equipment and I tested and it seems quite good.

**Comment by alexkulya** [comment]
@d3tr0l
Edit Smart function for the GUID of the creatures.
(-65702, -65695, -65694, -65698, -65699, -65697, -65696, -65700).

The current SpellID: 45223 has a crossbow animation and a random position to hit - >
replace with SpellID: 42580 (Solution, but maybe not Blizzlike).

P.S.
Attention. Google translate was used.

**Comment by BarbzYHOOL** [comment]
@alexkulya Can you provide a SQL query for easy testing? (even though it's not related to this PR or issue)

**Comment by alexkulya** [comment]
<pre>UPDATE `smart_scripts` SET `action_param1` = 42580 WHERE `entryorguid` IN (-65694, -65695, -65696, -65697, -65698, -65699, -65700, -65702) AND `source_type` = 0;</pre>

**Comment by BarbzYHOOL** [comment]
@alexkulya that's not a bad fix/change but I don't know, is it normal that they aim at nothing?

**Comment by alexkulya** [comment]
For example (-65700):
<pre>UPDATE `smart_scripts` SET `target_type` = 10, `target_param1` = 62842, `target_param2` = 25192 WHERE `entryorguid` = -65700 AND `source_type` = 0;</pre>

**Comment by Knindzagxg** [comment]
Can confirm what d3 said - It's not fixed.
Instead crossbow, there's still bow (That's easy fix, anyone can change equipment ID)
Direction where they shoot is even worse after update cause they shoot on bridge it selfsometimes (Before they used to shoot behind, but that's nothing special tbh)

2 videos bellow:

Before - https://www.youtube.com/watch?v=xYcwZ4S-A-k&feature=youtu.be

After - https://www.youtube.com/watch?v=LIXPQyokE5k&feature=youtu.be

**Comment by FrancescoBorzi** [comment]
Looking for @Pondaveia   or someone else to complete the work that has been previously started here.

**Comment by Pondaveia** [comment]
I'm not available at the moment to fix it. If someone can do this meanwhile you're free to do so. Very busy.

**Comment by Pondaveia** [comment]
Needs to be tested but this should fix it for now. I can't find the blue arrow spell resembling Blizzlike behaviour.
I'll gladly swap it as soon as someone gets a sniff on it.

**Comment by Nefertumm** [comment]
Thank you @Pondaveia. Can you change " to ' for strings in the sql?

**Comment by BarbzYHOOL** [comment]
> Thank you @Pondaveia. Can you change " to ' for strings in the sql in order to merge this?

Why? `""` allows people to use `'` without writing `\'`. For example `"Barbz's dog"`

Please, don't tell me that's because they do this on TC :D or because "we always did that"

**Comment by Nefertumm** [comment]
I'm not gonna bother to answer to you. 👍

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL 

because of:

1) consistency
2) double quotes in SQL might not work in all DB servers 

because of 2) some IDEs even consider as syntax error when you use double quotes in SQL

**Comment by BarbzYHOOL** [comment]
> because of:
> 
>     1. consistency

Hmm 

> double quotes in SQL might not work in all DB servers

Any info related to this?

**Comment by FrancescoBorzi** [comment]
there are plenty on the web, for example:

> using double quotes for string delimiters isn't standard SQL, so it's good practice to use single quotes

https://stackoverflow.com/questions/881194/how-do-i-escape-special-characters-in-mysql

**Comment by BarbzYHOOL** [comment]
> there are plenty on the web, for example:
> 
> > using double quotes for string delimiters isn't standard SQL, so it's good practice to use single quotes
> 
> https://stackoverflow.com/questions/881194/how-do-i-escape-special-characters-in-mysql

hmm okay even though this guy's quote made me smile

> Another handy benefit of using single-quotes is that the literal double-quote characters within your string don't need to be escaped: 

Note that the answer is 10 years old though

**Pull request merged**
