### PR TITLE
feat(Core/Locale): implement separated manager for game locale from ObjectMgr

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Move all localizations code to `GameLocale`
- Add a new system for localizing modules
- Add support locale for `autobroadcast`
- Add support locale for `commands.help`
- Implement separated manager for `autobroadcast` - #7420
- Add localization for all game `races` and `classes` (now using in command `.pinfo`)
- Sync naming `npc_text` and fix delay fields naming (https://github.com/TrinityCore/TrinityCore/commit/c574972cb2d000caacd155ddd32af425bed259ee)
- Sync `broadcast_text` naming (https://github.com/TrinityCore/TrinityCore/commit/6c85964065dc2b2d397904d79755eacc43a8ab0d)
- Add support `fmt` style for all functions using db table `acore_string`

## Issues Addressed:
- https://github.com/azerothcore/mod-npc-talent-template/pull/32#issuecomment-827184388

# Tests Performed:
- `autobroadcast_locale`
image
image

- `mod-player-info-at-login` with module locale system
image

- `commands_help_locale`
image

- `.pinfo` with localize races and classes
image

## How to Test the Changes:
- Add new module - https://github.com/WarheadCore/mod-player-info-at-login
- Check info at login
- Try test default localization
image

## Known Issues and TODO List:
- [x] #6893
- [x] #6243
- [x] Add example
- [ ] Add documentation
- [ ] https://github.com/azerothcore/Eluna/pull/10
- [ ] https://github.com/azerothcore/mod-transmog/pull/57
- [x] StringFormat
- [x] `acore_string` 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
what's the status of this PR?

**Comment by Winfidonarleyan** [comment]
> what's the status of this PR?

Need correct buikd for linux

**Comment by MysterioPRM** [comment]
Tested
image

Compiled with this modules:
image


Not work  with this modules:
image

**Comment by Winfidonarleyan** [comment]
> Tested image
> 
> Compiled with this modules: image
> 
> Not work with this modules: image

Thanks for test

**Comment by Winfidonarleyan** [comment]
- [x] mod-trasmog
image

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan status?

**Comment by Tony931023** [comment]
[Winfidonarleyan](https://github.com/Winfidonarleyan) How is the state of this PR, can you test it to see if it works? It would be very useful for the translations of the modules

**Comment by Winfidonarleyan** [comment]
Perhaps later

**Comment by acidmanifesto** [comment]
What is the current status of this? Is it abandoned?

**Comment by Winfidonarleyan** [comment]
> What is the current status of this? Is it abandoned?

Yes

**Pull request closed without merging**
