### PR TITLE
fix(Core/Object): Fix small error in Position::IsWithinBox

### PR DESCRIPTION
**Pull request by Kitzunu**
Co-Authored-By: Meltie2013 <Meltie2013@users.noreply.github.com>

Imported from https://github.com/Meltie2013/azerothcore-wotlk/commit/550fede1671613a844545f8810b986a31892fe5d

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4048

## Tests Performed:
- https://github.com/azerothcore/azerothcore-wotlk/issues/4048#issuecomment-751297797

## How to Test the Changes:

- check issue

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]

**Comment by BarbzYHOOL** [comment]
ty kitzu, silker and meltie

**Comment by FrancescoBorzi** [comment]
@bronzato @morpheux  I see you guys reverting this. Did you have any issues with it?

cc @Kitzunu @Yehonal

**Comment by Kitzunu** [comment]
"Revert "Revert"" so it is back in play

**Comment by morpheux** [comment]
All good after ktzu and silker fix.

**Comment by FrancescoBorzi** [comment]
thanks @morpheux for letting us know

**Pull request merged**
