### PR TITLE
fix(Core/Player): Learn runeforging & lockpicking

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/b1ac631f68d122558c25c4da7eedef75b4c2b7b6)

Co-Authored-By: r00ty-tc <173349+r00ty-tc@users.noreply.github.com>

## Changes Proposed:
- Learn skill runeforging when the spell is learned
- Do same for lockpicking to avoid issues (half of the lockpicking stuff was already imported, missing this stuff see https://github.com/TrinityCore/TrinityCore/commit/dcba0106d64bd598e70cc65be8e28f6ee279dcfd)

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6611
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6604

## Tests Performed:

image
image

## How to Test the Changes:

1. Do the DK questline
2. When you finish the quest to get runeforging, see that you learn the Spell and the Skill "Runeforging"
1. Have a rogue at lvl 16
2. Learn lockpicking at trainer

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Sedatyf** [comment]
Here what I did:
- ``.quest add 12619``
- ``.additem 38631``
- Turned quest and learned Runeforging ✔️ 
- I could open Runeforge book (please see video below)
Then I did a level 16 rogue and learned lockpicking without any problem ✔️ 

Everything work for me!


https://user-images.githubusercontent.com/59012307/123549346-edbba380-d768-11eb-9ce6-c30ae44dec6c.mp4

image

**Comment by Kitzunu** [comment]
thanks for testing

**Comment by Winfidonarleyan** [comment]
One of the fastest PR

**Comment by Kitzunu** [comment]
If I break something, I do my best to fix it asap :D

**Pull request merged**
