### PR TITLE
fix(DB/SAI): Lava Spawn SmartAI

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  Removed duplicated entries in smart_scripts
-  Ported script from Mangos.

## Issues Addressed:

- Closes unopened issue

## SOURCE:

Vmangos & Cmangos

## Tests Performed:

- Tested ingame.
- 

## How to Test the Changes:

1. .npc add temp 12265
2. See if it casts Fireball
3. See if it splits into 2 other Lava Spawns, emotes and despawns the original.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
tested and fixed the problems. Cmangos has the split timer at 30s, Vmangos has it at 10s

**Comment by temperrr** [comment]
Doesnt despawn the original one.

**Comment by Gultask** [comment]
I wonder what we're doing different, because it's working on my end :C 

https://user-images.githubusercontent.com/100873791/191737819-6d3b9461-c9c4-4a4a-bbda-bc6f2ce8c9f4.mp4

**Comment by temperrr** [comment]
> I wonder what we're doing different, because it's working on my end :C
> spawn.mp4

maybe the new spawn from firelord is at the same time as the old one and I got confused?

**Comment by Gultask** [comment]
Could be, but I think it's unlikely that it would respawn in the same place, but thanks for checking!

**Comment by temperrr** [comment]
tested again with raid markers and yea I must have been confused,

**Comment by Gultask** [comment]
Needs to be scripted in cpp for safety measures in case too many spawn.

https://github.com/azerothcore/azerothcore-wotlk/issues/13107

**Pull request closed without merging**
