### PR TITLE
DB/SAI: fix tortured skeletons in Shadow Labyrinth

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Some of the tortured skeletons in Shadow Labyrinth are moving around while lying on the ground. They are also not standing up when attacking. The following TC commit fixes part of this (skeletons standing up):
https://github.com/TrinityCore/TrinityCore/issues/14367

I added another statement to prevent the movement of the lying skeletons.

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested build and in-game

##### HOW TO TEST THE CHANGES:
- check the skeletons:
 .go creature 67091
 .go creature 67096
 .go creature 67133
- attack the skeletons

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
> the lying skeletons.

Never trust a skeleton

**Comment by Xgap** [comment]
working but there are errors
dberror log:
`Table `creature` have creature (GUID: 67091 Entry: 18797) with `MovementType`=1 (random movement) but with `spawndist`=0, replace by idle movement type (0).`
`Table `creature` have creature (GUID: 67096 Entry: 18797) with `MovementType`=1 (random movement) but with `spawndist`=0, replace by idle movement type (0).`
`Table `creature` have creature (GUID: 67097 Entry: 18797) with `MovementType`=1 (random movement) but with `spawndist`=0, replace by idle movement type (0).`
`Table `creature` have creature (GUID: 67098 Entry: 18797) with `MovementType`=1 (random movement) but with `spawndist`=0, replace by idle movement type (0).`
`Table `creature` have creature (GUID: 67099 Entry: 18797) with `MovementType`=1 (random movement) but with `spawndist`=0, replace by idle movement type (0).`
`Table `creature` have creature (GUID: 67133 Entry: 18797) with `MovementType`=1 (random movement) but with `spawndist`=0, replace by idle movement type (0).`

**Comment by Xgap** [comment]
thanks dude.  no error. 👍

**Comment by BarbzYHOOL** [comment]
@Stoabrogga thank you bro!

@Xgap thank you for testing, very helpful, you could join us on the discord too :)

**Pull request merged**
