### PR TITLE
fix(DB/creature_model_info): Turn 'Guard Untula' as female

### PR DESCRIPTION
**Pull request by Si1ker**
## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5684

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/20a4c95ffb5a9b018010e7879e2ac17dd8a464a3

Co-authored-by: Wyreth <Wyreth@users.noreply.github.com>

## Tests Performed:

image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by GastonCK** [comment]
Tested
Before
WoWScrnShot_062923_112409

After
WoWScrnShot_062923_112545

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @Si1ker and @GastonCK

**Comment by Gultask** [comment]
I have no idea if this data needs to be sniffed or not, sorry.

**Comment by Nyeriah** [comment]
This comes from a trinitycore cherry pick but hasn’t been merged because the commit doesn’t have proper author tags

**Comment by FrancescoBorzi** [comment]
> This comes from a trinitycore cherry pick but hasn’t been merged because the commit doesn’t have proper author tags

good point, @Si1ker can you please fix this?

**Comment by Si1ker** [comment]
> > This comes from a trinitycore cherry pick but hasn’t been merged because the commit doesn’t have proper author tags
> 
> good point, @Si1ker can you please fix this?

edit

**Comment by Gultask** [comment]
Also I was also waiting for that on your Crag Stalker PR :3

**Comment by Si1ker** [comment]
> Also I was also waiting for that on your Crag Stalker PR :3

@Gultask closed due to improvement - check #16574

**Comment by Si1ker** [comment]
update labels pls, ty.

**Comment by Si1ker** [comment]
update labels pls, ty.

second reminder.

**Pull request merged**
