### PR TITLE
fix(Core/Spell): AuraInterruptFlags AURA_INTERRUPT_TELEPORTED not used

### PR DESCRIPTION
**Pull request by TheLegendaryKingdom**
When you use a spell with AuraInterruptFlags SPELL_AURA_INTERRUPT_TELEPORTED and
it applies an aura, this aura is actually NOT removed from the player when he is
teleported.

Ported from TheLegendaryKingdom/LegacyOfAzeroth: https://github.com/TheLegendaryKingdom/LegacyOfAzeroth/commit/8d79ed8110e86f8137ea010ebd9fecd3920821cc

Original author : [Ayahuasca](https://github.com/ayahuasca-ruderalis) (for [TLK](https://github.com/TheLegendaryKingdom))

## Changes Proposed:
-  Remove all auras wich interrupt flags include AURA_INTERRUPT_TELEPORTED when player is teleported

## Issues Addressed:

- Closes NONE

## SOURCE:

https://github.com/TheLegendaryKingdom/LegacyOfAzeroth/commit/8d79ed8110e86f8137ea010ebd9fecd3920821cc
## Tests Performed:

- Built correctly
- Tested with a custom "flying form like" spell flagged AURA_INTERRUPT_TELEPORTED:
-         used the spell, applied aura
-         teleported using .tele <location name>
-         the aura was removed from the character

## How to Test the Changes:

1. Cast a spell that applies an aura and has flag AURA_INTERRUPT_TELEPORTED ([spell 42146](https://wowhead.com/spell=42146) makes your character slowly walk forward and unstoppable)
2. Teleport yourself (e.g. use `.tele <location name>` gm command)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
Acording to TrinityCore master branch, it's ENTER_WORLD flag and should be removed on add to world.

**Comment by TheLegendaryKingdom** [comment]
> Acording to TrinityCore master branch, it's ENTER_WORLD flag and should be removed on add to world.

Maybe this changed over expansion ? Isn't TC master their SL branch ?
If the aura is removed on world entering, wont it only be done upon character logging into the world instead ?
The flag name "teleported" works there, so why would its name/meaning be different (question) ? (:

**Comment by UltraNix** [comment]
@TheLegendaryKingdom `EnterWorld` is done every time you enter the map. So there are two cases: on login and on teleport from other map(not teleport on the same map). There is a different flag for leaving the world.
TC mater is indeed on Shadowolands, but this enum is valid for wotlk.

**Comment by TheLegendaryKingdom** [comment]
@UltraNix I see better. I noticed that it was also removed at login.
So, I guess the line I wrote is:
1°) not necessary
2°) in a counter-productive way, inefficiently influencing the core

More, thinking of the game design, I come to the conclusion it might even NOT be necessary to handle this at all.
I explain what I wanted to do before making this edit to the core:

I created a flying form, that I want to be castable everywhere, but only applying fhe tly aura if the player is technically allowed to fly (I'm not talking about skills lika riding or north flight ability, I mean zone/map/area side). I added in HandleAuraAllowFlight() a switch on the spellid to test if the player's location is flyable and to avoid situation where the player is either summoned or teleported (or everything that calls Player::TeleportTo()). 

See these two commits    [SPELL](https://github.com/TheLegendaryKingdom/LegacyOfAzeroth/commit/8c830f979c6287c5366453141116efa386d2d2d9)    [PR Source](https://github.com/TheLegendaryKingdom/LegacyOfAzeroth/commit/8d79ed8110e86f8137ea010ebd9fecd3920821cc)
It works to achieve what I wanted, but I know it's a hacky move and might be highly deprecated. The issue I fixed is if I cast the flying form spell in Outland it applies the flying aura, and if I teleport to Quel'danas (which is non-flying zone and same map as outland) the aura remains and my character can fly around the isle and above Sunwell which is glitchy. So with the second commit it made it more secure in game.

Maybe there is no way the player can get in a such situation where he is teleported and keeps the aura ?
How can I make it properly to be able to have one spell usable in the two cases (flight allowed/forbidden) ? And to be sure the player will not keep this aura (or this spell active) in a no-flight zone ?

**Comment by TheLegendaryKingdom** [comment]
[Visual demonstration](https://youtu.be/a6NSToPT9rs) (more explicit ?)

**Comment by UltraNix** [comment]
Why closed? Just rename the flag and move from `Player::Teleport` to `Unit::AddToWorld`

**Comment by TheLegendaryKingdom** [comment]
I'll make some test as I guess the correct CHANGE_MAP flag is already correctly handled. With it set to my spell thé aura gets removed when I log the character to the game. I'll make another PR if really needed.

**Comment by TheLegendaryKingdom** [comment]
@UltraNix After a bit of testinvestigation, I figured out the following:
1°) SPELL_AURA_INTERRUPT_FLAG_CHANGE_MAP is correctly handled
2°) SPELL_AURA_INTERRUPT_FLAG_TELEPORT is another flag and should imo be treated in TeleportTo()

How did I come to this:
1°) Created two clones of one of my spells which is a morph + invincibility aura and has no interrupt flag
2°) Added the interrupt flag CHANGE_MAP to one of the two clones
3°) Added the interrupt flag TELEPORT to the other one
IN GAME:
4°) Applied aura with CHANGE_MAP and went through the dark portal : Aura was removed (expected behaviour)
5°) Applied aura with CHANGE_MAP and logout then log back in : aura was removed (expected behaviour)
6°) Applied aura with TELEPORT and went through the dark portal : aura was still applied (unexpected behaviour)
7°) Logged out, then back in : aura still applied (expected behaviour)

So I'll come back with a new PR, just exactly the one which I deleted the branch (dumb me)

**Comment by TheLegendaryKingdom** [comment]
I tested an edit and it actually works as inteded. I'll create an issue then a PR for the situation to be more clear (with two videos to show it).

**Comment by TheLegendaryKingdom** [comment]
[Issue](https://github.com/azerothcore/azerothcore-wotlk/issues/9542) | [PR](https://github.com/azerothcore/azerothcore-wotlk/pull/9543)

**Pull request closed without merging**
