### PR TITLE
chore(core): remove malformed whitespaces

### PR DESCRIPTION
**Pull request by Kitzunu**
I hate this. Why did I decide to do this Q.Q

malformed whitespaces in CPP files from Codefactor https://www.codefactor.io/repository/github/azerothcore/azerothcore-wotlk/issues?category=Style&groupId=838&lang=5&page=75

### CODE REVIEW

**Comment by Kitzunu** [comment]
image
Hand made.... if only I had a script for this D:

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> image
> Hand made.... if only I had a script for this D:

obama-medal

**Comment by Kitzunu** [comment]
gonna check the warnings

**Comment by Viste** [comment]
> image
> Hand made.... if only I had a script for this D:

https://github.com/Winfidonarleyan/KargatumConsole

**Pull request merged**
