### PR TITLE
(fix/Quest) Redemption Incorrext Broadcast Text

### PR DESCRIPTION
**Pull request by ghost**
## Changes Proposed:
-  Fixes the Broadtext Order of Tirion Fordring.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8553
- Closes https://github.com/chromiecraft/chromiecraft/issues/2106

## SOURCE:

Same as seen in https://github.com/azerothcore/azerothcore-wotlk/issues/8553

## Tests Performed:

- Already tested and it is going as usual now. Thought I am not sure if it is meant to see the "Incomplete Quest Marker" when you start the dialog with him. Any confirmations?!

## How to Test the Changes:

TP to GUID 53837, Entry 1855
Start quest 5742, Redemption
Interact with Tirion to open the chat panes in question

Many thanks to @Azcobu for his/her exceptionally good issue report (just to mention it)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Banehammer** [comment]
Just dont ask me why I forgot like 80% of all the commit....

**Comment by Nyeriah** [comment]
Hey, thanks for your contribution but if the text order is wrong then the scripts need to be updated to match the broadcast_text values, not the other way around. The data from that table comes from retail, it contains all texts used in-game until a given point and should not be touched

**Comment by Banehammer** [comment]
> Hey, thanks for your contribution but if the text order is wrong then the scripts need to be updated to match the broadcast_text values, not the other way around. The data from that table comes from retail, it contains all texts used in-game until a given point and should not be touched
> 
> Skärmbild 2021-10-16 172640

Ah wait okay. I thought so. let me retry.

**Comment by Kitzunu** [comment]
I dont think you should edit broadcast text. They are all sniffed

**Comment by Nyeriah** [comment]
```sql
UPDATE `gossip_menu` SET `TextID `= 4493 WHERE `MenuID` = 3681 AND `TextID` = 4495;
UPDATE `gossip_menu` SET `TextID` = 4495 WHERE `MenuID` = 3683 AND `TextID` = 4493;
```

The broadcast text is fine, the above will fix the wrong order. Could you please test it and see if it solves the issue you tried to address?

Skärmbild 2021-10-20 110602
Skärmbild 2021-10-20 110617
Skärmbild 2021-10-20 110636

**Comment by Nyeriah** [comment]
Cool! Thanks for checking it out! You can include it in your PR if you want to.

And yeah, sorry about that backtick, kinda got messed up while formating it. I fixed it now.

**Pull request merged**
