### PR TITLE
fix(DB/creature_template): Fix Creatures Level

### PR DESCRIPTION
**Pull request by Kosiak**
## Changes Proposed:
-  Fix Crown Hoodlum(38006) and Crown Duster(37984) level.

## Issues Addressed:

- Closes[ [Love is in the Air / Dustwallow Marsh] Crown Hoodlum are level 1. #3070](https://github.com/chromiecraft/chromiecraft/issues/3070)

## Tests Performed:

- Started event [Love is in the Air], added both quests [Crushing the Crown](https://wowgaming.altervista.org/aowow/?quest=24648) and [Crushing the Crown](https://wowgaming.altervista.org/aowow/?quest=24647), gone to creatures and they are both right level and not level 1.

## How to Test the Changes:

1. Add quests ( .q add 24647, .q add 24647)
2. Start event (.event start 8)
3. Go to creatures Duster(.go creature 244621) and Hoodlum(.go creature 244616)
4. Duster should be Level 25-26, Hoodlum 33-34

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Remove name from where statement. Does nothing.

Ty for the pr tho

**Comment by LukasVolgger** [comment]
Src of Duster lvl: https://wowwiki-archive.fandom.com/wiki/Crown_Duster

**Comment by porkserver** [comment]
Tested on clean build with fresh databases
AC> AzerothCore rev. 5aed28707759 2022-03-15 15:30:02 -0500 (pr-11009 branch) (Unix, RelWithDebInfo, Static)

Added quests ( .q add 24647, .q add 24647)
Started event (.event start 8)
All NPC in question still lvl 1

Screen Shot 2022-03-15 at 5 00 59 PM
Screen Shot 2022-03-15 at 4 57 57 PM
Screen Shot 2022-03-15 at 4 57 33 PM

**Comment by porkserver** [comment]
AC> AzerothCore rev. 5aed28707759 2022-03-15 15:30:02 -0500 (pr-11009 branch) (Unix, RelWithDebInfo, Static)

Tests Performed:
Started event [Love is in the Air], added both quests [Crushing the Crown](https://wowgaming.altervista.org/aowow/?quest=24648) and [Crushing the Crown](https://wowgaming.altervista.org/aowow/?quest=24647), gone to creatures and they are both right level and not level 1.

All NPC's the proper level!
Screen Shot 2022-03-15 at 5 17 35 PM
Screen Shot 2022-03-15 at 5 16 44 PM
Screen Shot 2022-03-15 at 5 00 59 PM

**Pull request merged**
