### PR TITLE
fix(DB/Squash): MariaDB Imports

### PR DESCRIPTION
**Pull request by noisiver**
## Changes Proposed:
-  Replace the collate so it will actually import using both MySQL and MariaDB

I wasn't sure which collate to use or if I should just remove it altogether so I just used one that other cores use. Do let me know if I should change it or remove it and I'll do it. At least it'll import right now.

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
It didn't have collate before

**Comment by noisiver** [comment]
> It didn't have collate before

But it did. Well, with the squash that happened 12 hours ago added it. Should I remove it?

**Comment by Nyeriah** [comment]
> > It didn't have collate before
> 
> But it did. Well, the squash that happened 12 hours ago added it. Should I remove it?

Yes, that's what I meant, it didn't have collate before yesterdary. MariaDB doesn't like collate.

**Comment by noisiver** [comment]
Thanks a ton for clearing that up for me. I wasn't sure about collates when it comes to MariaDB. Either way I removed it and I tested both MySQL and MariaDB and it works perfectly but obviously someone has to test it to make sure it does work for them too. Like you. 💯

**Comment by Nyeriah** [comment]
I don't use MariaDB so that wouldn't be me but either way this is fine as it is.

**Comment by Lovo97** [comment]
I get an error when importing the databases in mysql

**Comment by noisiver** [comment]
> 

It would help to see the actual error. I did try this using both MySQL 8.0 and MariaDB 10.6 with no issues.

**Comment by Kitzunu** [comment]
> > > It didn't have collate before
> > 
> > 
> > But it did. Well, the squash that happened 12 hours ago added it. Should I remove it?
> 
> Yes, that's what I meant, it didn't have collate before yesterdary. MariaDB doesn't like collate.

It does likw general_ci iirc

But this should be fine

**Comment by Gultask** [comment]
Apologies. I'll keep this in mind if I do another squash in the future.

**Comment by Kitzunu** [comment]
I forgot about it too, dw

**Pull request merged**
