### PR TITLE
fix(Script/Instance) [Deadmines] Smite Slam

### LINKED ISSUE #4945: Deadmines - Mr.Smite
##### CURRENT BEHAVIOUR:
-Mr. Smite always uses his stun (Smite Slam)
-Mr Smite will aggro other nearby creatures when pulled by aggroing the blackguards image

##### EXPECTED BLIZZLIKE BEHAVIOUR:
-He should only use his stun(Smite Slam) in hammer stance (below 33%) https://classic.wowhead.com/guides/deadmines-classic-dungeon#mr-smite. _At 33%, Smite will stun the group once again and run towards the chest. This time, he will pull out his famous 2-handed mace, granting him the  Smite Slam_
-Only Mr Smite should aggro when the blackguards are pulled.  https://youtu.be/j01MfraN6b0?t=2279 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  .go c id 646 and test

##### AC HASH/COMMIT:
b8c2c2311d08b2b6332ce013ecc69d4ce7e33500

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97335617-deadmines-mr-smite?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Branel**
## Changes Proposed:
- Moves Smite Slam to be more chronological
- Resolves the issue of him constantly casting by setting a 33% health condition for the spell
- Adds the proper cooldown (6 sec)
- Removes Smite Slam from the creature_template_spell (prevents him from constantly casting it)

## Issues Addressed:
- Closes #4945

## SOURCE:

See original report.

## Tests Performed:

I tested the encounter by myself `.go c id 646` , got him to 33% and checked combatlog.

## How to Test the Changes:

Please see the wiki on how to test PR.
Enter the instance by `.go c id 646`. 
Get him to 33% hp and check combatlog (he might miss the spell, takes up to 6 seconds for him to cast because of first cooldown)

## Known Issues and TODO List:

He should not be able to miss the spell (according to wowhead) 
The mobpack around him will get pulled no matter what, there is a greater issue that causes it and there is already a seperate bugtracker about it. I am interested in solving in but I am not proficient enough at this time.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

Note: My first C++ PR, please have a good look.

### CODE REVIEW

**Comment by Sedatyf** [comment]
Hey there @Branel 
I just tested your PR, and it seems it doesn't work like you wanted. As you may see on the video, Smite stunned me at 66% with a 9s long stun, and then he stunned me again at 33% with that same duration.

https://user-images.githubusercontent.com/59012307/115454288-ea63e300-a220-11eb-8ed5-1b09e353d6d5.mp4

Furthermore, I saw when he's under 33%, he tends to spam Smite Slam a bit too much. Please see video below with my "What happened to me" chat open

https://user-images.githubusercontent.com/59012307/115454757-6d853900-a221-11eb-86bc-6bd27949b4d4.mp4

**Comment by Branel** [comment]
hahaha that 2nd video definitily is not how it is supposed to be, something must have gone terribly wrong.
I had rewritten my solution to make it fit with the rest of the script and something must have gotten lost in the translation so to say. 
Thanks for testing I will try to resolve this soon,

**Comment by Sedatyf** [comment]
Feel free to poke me when you're done and I'll test it again

**Comment by Sedatyf** [comment]
Another note, I think the report issue about stun is wrong. He gave us this link : https://classic.wowhead.com/guides/deadmines-classic-dungeon#mr-smite

And it says the following :
image

So Mr.Smite should stun at 66% and 33%.

**Comment by Branel** [comment]
You are confusing the stuns, the stuns at 66% and 33% are the10 seconds stun you had in your first video, Smite Stomp. The one I am trying to fix which is supposed to be at 33% is in the last paragraph that you just posted that references Smite Slam.

**Comment by Sedatyf** [comment]
Yeah sorry, I read the issue wrong, I deleted my comment about it 😓

**Comment by Branel** [comment]
No worries! :D

**Comment by FrancescoBorzi** [comment]
excellent team work guys, keep it up!

**Comment by Si1ker** [comment]
@Sedatyf  about your first video, that's blizzlike behavior, no error in there.
He will stun for that long time at 66% and 33%

image
source: https://classic.wowhead.com/guides/deadmines-classic-dungeon#mr-smite

**Comment by Sedatyf** [comment]
> @Sedatyf about your first video, that's blizzlike behavior, no error in there.
> He will stun for that long time at 66% and 33%
> 
> image
> source: https://classic.wowhead.com/guides/deadmines-classic-dungeon#mr-smite

Yeah indeed. After reading the wowhead page and the issue again, I saw that I misunderstood what they both said (that's why I deleted one comment and forgot to edit my first one) 😓

**Comment by Branel** [comment]
I have now removed the Spell from his spell_template -  which seems to have been one of the reasons he was constantly casting Smite Slam. 

I also corrected the timings of the Smite Slam, it should now more correctly be casted every ~6 seconds.

I believe its ready for a 2nd testing at this stage @Sedatyf

**Comment by Sedatyf** [comment]
Alright! Thank you for the side note about the DB. I'll try those changes as soon as I get time 👍🏼

**Comment by Sedatyf** [comment]
Sorry @Branel I kinda forgot to test your PR again. I'm doing it right now, I'll keep you updated

**Comment by Sedatyf** [comment]
Here a video of my latest test to check if Mr. Smite doesn't spam Smite Slam anymore. And it is workind as intended. 
If you check timestamp from video, you can see that it cast it every 6 sec approximatively ✔️ 

https://user-images.githubusercontent.com/59012307/116063080-d424af80-a684-11eb-8a75-b346794d398e.mp4

@Si1ker or @FrancescoBorzi we just need a review here and remove the wip tag as well 👍🏼

**Comment by Branel** [comment]
Thank you for taking your time to test.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @Branel and @Sedatyf !

**Comment by FrancescoBorzi** [comment]
@Branel the build is failing:

```
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/EasternKingdoms/Deadmines/boss_mr_smite.cpp: In member function ‘virtual void boss_mr_smite::boss_mr_smiteAI::UpdateAI(uint32)’:
src/server/scripts/CMakeFiles/scripts.dir/build.make:2539: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/Deadmines/boss_mr_smite.cpp.o' failed
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/EasternKingdoms/Deadmines/boss_mr_smite.cpp:92:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
                     if (me->HealthBelowPct(34) && !health34)
                     ^~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
```

please fix it so we can merge the PR

**Pull request merged**
