### PR TITLE
fix(docker/scripts) add quotes to pwd in docker build scripts

### PR DESCRIPTION
**Pull request by locus313**
## CHANGES PROPOSED:
-  add quotes to pwd in docker build scripts, This fixes the docker build from failing when you have a space in your directory path

before pr:
image

after pr:
image

## ISSUES ADDRESSED:
- Closes none

## TESTS PERFORMED:
- create test directory with a space in it
- clone the repo to the directory
- try running the docker build scripts `./bin/acore-docker-build` and `./bin/acore-docker-build-no-scripts` (only tested on Centos7)
- verified that the build completed with no errors

## HOW TO TEST THE CHANGES:

- create test directory with a space in it and cd into it
- clone the repo to the directory
- follow the  pr testing directions to download the changes https://www.azerothcore.org/wiki/How-to-test-a-PR
- try running the docker build scripts `./bin/acore-docker-build` and `./bin/acore-docker-build-no-scripts` (only tested on Centos7)
- verify that the build completed with no errors

## KNOWN ISSUES AND TODO LIST:

- [x] test on windows
- [x] test on macos

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers can anyone test this on Windows?

**Comment by FrancescoBorzi** [comment]
@locus313 tested on macOS, it works fine ✅ 

- tested `/bin/acore-docker-build`
- tested `/bin/acore-docker-build-no-scripts`

both scripts succeeded with no errors

**Comment by locus313** [comment]
Tested on windows. Looks to be working fine as well:
before pr:
image

after pr:
image

**Comment by JamesGent** [comment]
Tested on Windows 10 Pro (19042) and it worked.

Previously would error out if a space was present.

**Pull request merged**
