### PR TITLE
fix(Core/Units): Clear emote state on attack rather than on combat st…

### LINKED ISSUE #6281: Core/Scripts: Mimiron's Spinning Up + Mine Issues [$30]
**CURRENT BEHAVIOUR:**

Full video here
https://youtu.be/450PUVQn-2M

**EXPECTED BLIZZLIKE BEHAVIOUR:**

The mine should be released in an arc.
Spinning should work correctly, Issues appears on P2 and P4.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. .gm on
2. .go c 137630
3. start encounter

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
361fd86416c5267dacc33701196afc7ce95140dd

**OPERATING SYSTEM:**

win10

**MODULES:**

mod-ah-bot
mod-anticheat
mod-cfbg
mod-eluna-lua-engine
mod-individual-xp
mod-transmog

**CUSTOMIZATIONS:**

<bountysource-plugin>

---
There is a **[$30 open bounty](https://www.bountysource.com/issues/99055303-core-scripts-mimiron-s-spinning-up-mine-issues?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ghost**
…art.

Fixes #6281

## Issues Addressed:

- Closes #6281

## Tests Performed:

- Not tested.

## How to Test the Changes:

1. .gm on
2. .go c 137630
3. start encounter and wait for p2.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
I re-ran the actions. Idk why it exploded with OpenSSL

**Comment by temperrr** [comment]
Tested. 

Before PR spinning up did move around
With PR Spinning up slowly moves around the room.

**Comment by UltraNix** [comment]
@bgcfb Just tested in P2 and P4 - all looks good. Test it again.

**Comment by UltraNix** [comment]
#8259 is about something different.

**Comment by UltraNix** [comment]
@bgcfb Test it now.

**Pull request merged**
