### PR TITLE
fix(DB/Creature) Bellygrub not wandering

### LINKED ISSUE #6275: Bellygrub not wandering
Original report from Chromiecraft [https://github.com/chromiecraft/chromiecraft/issues/814](https://github.com/chromiecraft/chromiecraft/issues/814)

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bellygrub in Redridge Mountains (guid 10105) does not wander like the other goretusk creatures in the area.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

He should be wandering like in this video: https://www.youtube.com/watch?v=KKlibkOYRm0

##### STEPS TO REPRODUCE THE PROBLEM:

1. ```go creature 10105```
2. Observe that Bellygrub is not wandering

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99055309-bellygrub-not-wandering?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Zenslash**
## Changes Proposed:
-  Bellygrub now wandering

## Issues Addressed:
- Closes #6275

## SOURCE:
He should be wandering like in this video: https://www.youtube.com/watch?v=KKlibkOYRm0

## Tests Performed:
- Tested on local server

## How to Test the Changes:
1. ```go creature 10105```
2. Observe

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]

**Comment by Eldarix** [comment]
Checked (AC HASH/COMMIT: 53ab534) it works:

WoWScrnShot_062821_081644
WoWScrnShot_062821_081654

**Comment by LukasVolgger** [comment]
Thx @Zenslash for the contribution and @Eldarix for testing!

**Comment by T1ti** [comment]
Your video is from a private server fyi

**Comment by Zenslash** [comment]
> Your video is from a private server fyi

https://www.youtube.com/watch?v=MC71IT71_Gk (14:27)
@T1ti  In this video, he also wandering. I guess this video is from classic wow

**Pull request merged**
