### PR TITLE
AOE Mass Loot Implementation

### PR DESCRIPTION
**Pull request by acidmanifesto**
This is a implementation of a QOL Feature that is enabled and disabled thru conf.
It allows mass looting within a distance of 30 when NOT in a group.

Discord name is MDic#0865

## Changes Proposed:
Implements QOL feature from Higher expansion:
Works only when player is NOT in a group.
Area of Effect (MOP Looting\Mass Looting) up to distance of 30.
Mails excess loot from looting when there is no more player inventory to player.
Conf enabled\disable.

## Issues Addressed:

- QOL Wishes

## SOURCE:
Based on my previous PR\MERGE with Trinitycore Custom Branch for 335
https://github.com/TrinityCore/TrinityCoreCustomChanges/pull/60

Based on my previous PR with Trinitycore Custom Branch for 434
https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/pull/293

## Tests Performed:

Tested on TC 335 and TC CPP 434
Tested with inside and outside of instances.
Tested with skinning although sometimes you will have to skin twice the same creature.
Mechanicall Skinning Works without issues.
When Looting it will Loot ALL Indiscriminately with in the radius of 30 with dead creatures.

Client limitation Warning:
Client can only handle 50 messages. Excess Loot is sent one item per a message. If you exceed 50 messages in your inbox, simply retrieve and clear out your messages and relog and the queue will push forward with the other items.

## How to Test the Changes:

1. Best Test is to gather up alot of trash mobs of various entries and kill and loot them.
2. ICC is the best place to test, 
3. Kill and Loot enemies.

## Known Issues and TODO List:

- Isolate and identify the conditions and why exactly, does it take two skinning attempts at rare times to skin a skinnable mob.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Ty for PR, cool feature =)

**Comment by acidmanifesto** [comment]
> I'm fine with the conf tbh.

Azerothcore members\users pretty much blew up my reddit inbox when i posted it online. I had zero ideas a custom script would go somewhat viral.

**Comment by Nyeriah** [comment]
For the mail retrieval part, it seems my commit was never cherry-picked: https://github.com/TrinityCore/TrinityCore/commit/9f606f74a3e10a275d59765312679eda9e58af99

**Comment by Tony931023** [comment]
@acidmanifesto When did this end, it would be a perfect implementation that was in AC

**Comment by acidmanifesto** [comment]
> @acidmanifesto When did this end, it would be a perfect implementation that was in AC

This was a insane early sttempt to port to azerothcore.
Helpers were implmented in the core currently.

Right now the place of it being maintained is here
https://github.com/acidmanifesto/azerothcore-wotlk-custom/wiki

**Comment by Tony931023** [comment]
Thanks, I'll try it, I still think that this is something that the community will like a lot

**Comment by acidmanifesto** [comment]
> Thanks, I'll try it, I still think that this is something that the community will like a lot

It was a group dm i was in. They do not want it in the core, they do not want it as a conf. They want it as a module, which getting the hooks for it has not been working out. So it is currently staying as a core edit in my custom branch.

**Pull request closed without merging**
