### PR TITLE
refactor(Core/Instance): make SetBossState void

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Make it void instead of returning an std::string, it makes no sense and there are no uses for that currently on the core.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13409

## Tests Performed:

- Build on windows.

## How to Test the Changes:

1. Compile.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Maelthyrr** [comment]
@Nefertumm Seems that break gcc compile.

**Comment by Nefertumm** [comment]
?????

**Comment by Kitzunu** [comment]
Why ?, no response after the comment. This breaks GCC

**Comment by acidmanifesto** [comment]
Applying run-build label to ensure we have no issues.

**Comment by Maelthyrr** [comment]
Tested in AQ40/20, Nax, and ICC and no crash, no compile errors, no worldserver errors

**Pull request merged**
