### PR TITLE
Core/Locale: fix Locales for gossip menu option

### LINKED ISSUE #456: [Locales]locales_gossip_menu_option
The script on locales_gossip_menu_options if anyone needs it!
https://github.com/Devalenok/azerothcore-wotlk/commit/a95aa88b1ad46279cf4380e152ce20c8f21d98c0
cdd185162a4f

### PR DESCRIPTION
**Pull request by Viste**
**Changes proposed:**

- Restore locale for gossip menu option

**Target branch(es):** master

**Issues addressed:** Closes #456

**Tests performed:** build

**Known issues and TODO list:** no

### CODE REVIEW

**Comment by Viste** [comment]
@ShinDarth thx for close invalid PR i redone it.

**Comment by ShinDarth** [comment]
codestyle looks good, waiting for testers

**Comment by Viste** [comment]
anyone?

**Comment by cooler-SAI** [comment]
all works good! can be merged

**Comment by talamortis** [comment]
Thank you for testing @cooler-SAI and thank you @Viste for your input 👍

**Comment by HeartWell** [comment]
Ах ты партизан)

**Comment by Viste** [comment]
нет я не такой :dancer:

**Pull request merged**
