### PR TITLE
Neferian head in SW spawn time adjusted to 2 hours from 21 seconds (my first PR)

### PR DESCRIPTION
**Pull request by Falstring**
Timer updated to 2 hours from 21 seconds.

CHANGES PROPOSED:
Updated object timer to 2 hours.

ISSUES ADDRESSED:
Issue is reported in: #1702

TESTS PERFORMED:
Database. Does not produce warnings nor errors.

HOW TO TEST THE CHANGES:
use an Alliance character and then .additem 19003
start the quest from the item
follow the quest through
head should remain for 2 hours
-->

KNOWN ISSUES AND TODO LIST:
[ ]
[ ]
Target branch(es):
Master

### CODE REVIEW

**Comment by Pondaveia** [comment]
You deleted the file with the changes, maybe revert commit?

**Comment by Falstring** [comment]
> You deleted the file with the changes, maybe revert commit?

I did not delete the files with changes. The one with changes is the new one I created.

**Comment by Pondaveia** [comment]
If you check the changes you can see 0 lines added, also the last commit says deleted file revision

**Comment by Falstring** [comment]
> If you check the changes you can see 0 lines added, also the last commit says deleted file revision

It's because I had to make a copy of the file.

It does not come over when you fork it apparently.

**Pull request closed without merging**
