### PR TITLE
fix(Scripts/AzjolNerub): Fixed Hadronox being killed by mobs.

### LINKED ISSUE #14120: (scripts/AzjolNerub): Hadronox dissapears if no players around
### Current Behaviour

I've been getting reports from players in Azjol-Nerub where Hadronox is not in the instance.

When I checked with a gm account, Hadronox is dead in its initial position.
image

After several tests to check what's going wrong, it seems if no player (player or gm) is in the zone (Hadronox Lair) for the first 8-10 minutes that the dungeon group takes (as average) to clean the first boss gauntlet event (before the spider web that block the access to Hadronox Lair), Hadronox disappears/dies.

### Expected Blizzlike Behaviour

Hadronox should be there

### Source

Logic

### Steps to reproduce the problem

This is a tricky part.

1. Go into Azjol-nerub, clear the entrance WITHOUT triggering the gauntlet event of the first boss.
2. Wait for 10-12min , that's what 5man groups takes to clear the entrance.
image

3. Clear the entrance and go into Hadronox Lair, boss won't be there.
image

If I use ".gm on" I can see hadronox dead:
image

### Extra Notes

_No response_

### AC rev. hash/commit

d2940a0

### Operating system

Ubuntu

### Custom changes or Modules

transmog
dual-reset
battleground-reward
individual-xp
weekend-xp

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #14120

## Issues Addressed:

- Closes #14120

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](#14120)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Si1ker** [comment]
Thanks @UltraNix ✨
### Tested & working

Before PR, adds were applying to many debuffs and the boss was not initiated to cast its poison witch heals a % of its health and prevents its dead in the first place. Now HP cannot go lower.

image

### No issues found
image

**Comment by mpfans** [comment]
The commit needs to be merged immediately

**Comment by Si1ker** [comment]
It's curious how a PR from 13 hours ago to add content was merged 5 hours ago, but this one to fix content and bring back an unavailable boss atm doesn't.

**Comment by heyitsbench** [comment]
> It's curious how a PR from 13 hours ago to add content was merged 5 hours ago, but this one to fix content and bring back an unavailable boss atm doesn't.

Because that PR doesn't impact basically anything and only adds static gobjects and creatures to a one-time event.

**Comment by Nyeriah** [comment]
I can’t approve this because it’s done without research and to my knowledge it’s not how it’s supposed to work. The poison volley should be enough to keep the boss alive through the tunnel, so this is a hack fix. 

I’ll second @heyitsbench on the question above

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Fetch the upstream pplease. DB failure on workflow was resolved the other day. Fetch the upstream so we can get a clear view of the work flow results.

**Comment by noisiver** [comment]
> > @mpfans That's why it has "Priority-High" label.
> 
> Because of this bug, this dungeon lacks a BOSS

You can still progress to the final boss and complete the dungeon. You do lose some loot but it doesn't break the entire dungeon.

**Comment by mpfans** [comment]
The status of this PR?

**Comment by Maelthyrr** [comment]
> I can’t approve this because it’s done without research and to my knowledge it’s not how it’s supposed to work. The poison volley should be enough to keep the boss alive through the tunnel, so this is a hack fix.
> 
> If some other developer or maintainer thinks this can get a pass they’re of course free to do so
> 
> I’ll second @heyitsbench on the answer to the question above

Test done on retail and the boss have a sparing system but it's not 5% but 1 hp. Maybe different % on woltk classic but impossible to check without a full test group.

WoWScrnShot_012123_195855

**Comment by Gultask** [comment]
Invincibility at 1HP is a common mechanic present in most encounters where things like these can go wrong.
It's easier to notice in Retail as bosses can be killed in 1 hit. Quite a few stay at 1hp until they are "allowed" to die.

**Review by Nyeriah — APPROVED** [review]

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by jayendo** [comment]
I added this to test since I was experiencing something similar. It fixed the boss "not showing"/"disappearing". However, I noticed even though it seems to work correctly this time; when Hardronox first comes into sight at the tunnel he is attacking one of his own. Albeit, I can actually attack him, finish this boss, and move on. Which is extremely important to me.

**Comment by Maelthyrr** [comment]
> I added this to test since I was experiencing something similar. It fixed the boss "not showing"/"disappearing". However, I noticed even though it seems to work correctly this time; when Hardronox first comes into sight at the tunnel he is attacking one of his own. Albeit, I can actually attack him (he will attack back), finish this boss, and move on. Which is extremely important to us.

It's a normal behavior. Same thing on retail and classic.

**Comment by jayendo** [comment]
> > I added this to test since I was experiencing something similar. It fixed the boss "not showing"/"disappearing". However, I noticed even though it seems to work correctly this time; when Hardronox first comes into sight at the tunnel he is attacking one of his own. Albeit, I can actually attack him (he will attack back), finish this boss, and move on. Which is extremely important to us.
> 
> Hadronox does not have "one of his own". Hadronox is alive (feral) and mobs around are (Anub'ar) undead.
> 
> ( They're enemies xd )

Thanks for both of your inputs. You can tell I am new to the WoW content. I am learning as I also develop our first server revision. Got into the game 2 years ago (3.3.5).

**Review by Kitzunu — APPROVED** [review]

**Comment by Nyeriah** [comment]
`run-build` label is killing this PR, the CI has some actions stuck, I have removed the label now so please update your branch so it fires again and we can hopefully merge it this time

**Pull request merged**
