### PR TITLE
fix(DB/gameobject_template): unlink trap 181604 from gameobject 181605

### PR DESCRIPTION
**Pull request by sudlud**
- fix for midsummer ribbon pole dance beam beeing connected to ribbon pole bottom instead of top (issue #12145)
- ribbon pole beam (spell 29712) by condition always targets NPC 17066 "Ribbon Pole Debug Target"
- all Ribbon Poles (181605) already have NPC 17066 placed on top for this purpose
- 181604 "TEST Ribbon Pole TRAP" triggers spell 29708, which spawns an additional NPC 17066 at the ribbon pole bottom everytime the ribbon pole is beeing clicked / activated
- (these additional NPCs also do NOT despawn on Event end)
- the closest NPC 17066 is then at the bottom pole and becomes target of ribbon pole beam spell (29712)
- therefore unlink trap 181604 to not spawn any unwanted NPCs anymore and get beam correctly targetting the ribbon pole top

## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Progress #12145

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

.event start 1
.tele orgrimmar
.go xyz 1937 -4326 22
click on ribbon pole
observe beam connecting to the top

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Those fields are sniffed, this is a hack I am affraid

**Comment by sudlud** [comment]
Well right now the trap spawns unwanted NPCs at the pole bottom, just tried to find a solution for this issue.

**Comment by sudlud** [comment]
What better way is there to prevent the trap from casting the spell that spawns the unwanted NPCs?

Or should a script for the spell take care of despawning the NPCs.

**Comment by Nyeriah** [comment]
The issue is likely not the npc but something else, those fields can't be wrong

**Comment by sudlud** [comment]
Alright then I've just wasted quite some time to track this issue down to this point. I'm open to suggestions for a different solution / approach.

**Comment by sudlud** [comment]
The trap has a negative verifiedbuild, so sniffed but modified? Also are conditions sniffed as they have no verifiedbuild?

**Pull request closed without merging**
