### PR TITLE
fix(Scripts/BlackwingLair): Do not spawn more than 52 Razorgore's add…

### LINKED ISSUE #11238: [BWL] Razorgore no adds limit during P2
### Current Behaviour

Actually, adds spawn until that all eggs are  destroyed. 

### Expected Blizzlike Behaviour

Normaly, there are a limit of 52 adds (40 orcs, and 12  dragonkin).

### Source

https://classic.wowhead.com/guides/razorgore-the-untamed-blackwing-lair-strategy

https://wowwiki-archive.fandom.com/wiki/Razorgore_the_Untamed

### Steps to reproduce the problem

Go to P2, wait and count the adds number.

### Extra Notes

_No response_

### AC rev. hash/commit

[e8e8c34](https://github.com/azerothcore/azerothcore-wotlk/commit/e8e8c345906220d2c3dda2066b9baf14172b9897)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…s (12 dragonkins and 40 orcs).

## Issues Addressed:

- Closes #11238

## Tests Performed:

- Not tested.

## How to Test the Changes:

Go to P2, wait and count the adds number.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
Tested and work

- [X] Adds limit of 52
- [X] Spawn 40 orcs and 12 dragonkids

**Comment by Lynethris** [comment]
I have misunderstand the system. Sorry

**Comment by UltraNix** [comment]
@temperrr Done. Please, test it.

**Comment by Lynethris** [comment]
@UltraNix Doesn't work. When the limit is reached, no more adds spawn even if we kill adds alives.

**Comment by UltraNix** [comment]
@Lynethris You tried with the newest changes?

**Comment by Lynethris** [comment]
> @Lynethris You tried with the newest changes?

Yes.

**Comment by UltraNix** [comment]
@Lynethris Fixed.

**Comment by Lynethris** [comment]
It's work.

- [X] Limit is reached when there are 52 adds alive
- [X] They can't be more than 40 orcs and 12 dragonkids
- [X] When the limit is reached, and then you kill some adds, the respawn restart (until you reach the limit again)
- [X] Don't break other fixes/game mechanics (reset, timer waves, P2/P3....)

**Comment by temperrr** [comment]
Sometimes adds spawn during P2 now

**Comment by UltraNix** [comment]
Fixed.

**Comment by Lynethris** [comment]
> Fixed.

Doesn't work. When adds are killed just after that all eggs are destroyed, they continue to spawn.

**Comment by UltraNix** [comment]
@Lynethris Now ;)

**Comment by Lynethris** [comment]
It's good now. Thanks ;)

I have also checked again other points. All is fine, so this PR can be merge.

**Pull request merged**
