### PR TITLE
 Core/Quest: implement Quest Tracker

### LINKED ISSUE #1176: Implement Quest Tracker
This is also part of: https://github.com/azerothcore/azerothcore-wotlk/issues/1118

---

This is a feature I've previously implemented for TC: https://github.com/TrinityCore/TrinityCore/commit/e806fc8a02dbde324dd9654b0165a7cac5ae7086

It can be used with: https://github.com/FrancescoBorzi/TC-Quest-Tracker

It would be nice to have it in AzerothCore too.

### PR DESCRIPTION
**Pull request by Viste**
##### CHANGES PROPOSED:
This is a way to easily track bugged quest. The tracks will be stored in the new quest_tracker table:
* `id` -> quest id
* `character_guid` -> character guid
* `quest_accept_time` -> datetime of accepting
* `quest_complete_time` -> datetime of when quest was marked as "(Completed)" [could be NULL]
* `quest_abandon_time` -> datetime of when quest has been abandoned by player [could be NULL]
* `completed_by_gm` -> if the quest has been completed by a GM this value will be 1, it will be 0 otherwise
* `core_hash` -> core hash when player accepted the quest
* `core_revision`-> core revision when player accepted the quest

possible cases:
* both `quest_complete_time` and `quest_abandon_time` **are NULL** -> means player doesn't do the quest yet
* `quest_complete_time` **is NULL** and `quest_abandon_time` **isn't NULL** -> means player abandoned the quest before completing it, then the quest could be bugged
* both `quest_complete_time` and `quest_abandon_time` **aren't NULL** -> means player completed the quest, but he abandoned it before delivering: there could be a bug in deliver process (e.g. the NPC is missing)
* `quest_complete_time` **isn't NULL** and `quest_abandon_time` **is NULL** -> means player succesfully finished the quest. No bug here, unless a GM completed that quest for him (in that case, `completed_by_gm` is set to **1**).

##### HOW TO TEST THE CHANGES:
Enable in the conf
```
Quests.EnableQuestTracker = 1
```

Try to use it in game (take quests as players, abandon some of them, complete with gm some of them, complete normally some of them, etc...) and see what happens in the table (i.e. if the table is filled with the right data).

##### Target branch(es):Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi what are the test instructions?

**Comment by FrancescoBorzi** [comment]
just enable the feature and try to use it in game (take quests as players, abandon some of them, complete with gm some of them, complete normally some of them, etc...) and see what happens in the table (i.e. if the table is filled with the right data). I think the original description is enough for testers but feel free to ask me if you have more questions

**Comment by wetbrownsauce** [comment]
Tested. All cases listed work as expected.

**Comment by Viste** [comment]
@wetbrownsauce thank you!

**Comment by BarbzYHOOL** [comment]
@Viste @wetbrownsauce thank you very much !! really

**Pull request merged**
