### PR TITLE
feat(CI): Travis check modules

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- Extend Travis compilation check by including some of the most popular modules.
- Change the absolute paths of the CI scripts to use environment variable "TRAVIS_BUILD_DIR". This way it is also possible to run Travis on forks.

###### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
see Travis runs

##### HOW TO TEST THE CHANGES:
see Travis runs

##### KNOWN ISSUES AND TODO LIST:
All modules included here have to make sure that they don't throw any Travis errors. In order to check this they have to activate Travis and include (or update) this file in their repository:
https://github.com/azerothcore/skeleton-module/blob/master/.travis.yml
I already did this for beastmaster, transmog and VAS autobalance.

TODO list:
- [x] [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [x] [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [x] [mod-npc-beastmaster](https://github.com/azerothcore/mod-npc-beastmaster)
- [x] [mod-premium](https://github.com/azerothcore/mod-premium)
- [x] [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [x] [mod-vas-autobalance](https://github.com/azerothcore/mod-vas-autobalance)

I will remove the comments in "apps/ci/ci-install-modules.sh" after each of the modules passes the Travis check.

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
As all included modules (even Eluna) now pass the Travis check I think this is ready to be merged. Still need someone reviewing this, though.

**Comment by Winfidonarleyan** [comment]
Maybe merge?

**Comment by Stoabrogga** [comment]
Ok, merged. Thanks for reviewing this @Winfidonarleyan @FrancescoBorzi

**Comment by BarbzYHOOL** [comment]
awesome

**Pull request merged**
