### PR TITLE
fix(DB/Creature): Galak Windchaser drops mid-high level items

### PR DESCRIPTION
**Pull request by podmepodme**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16290

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by elthehablo — CHANGES_REQUESTED** [review]
Please stick to the AzerothCore sql conventions.

The join might work in this case, but it is not directly clear what entries are being deleted and updated.

So with that said, please stick to generic inserts, deletes and updates at least for loot related db changes

**Comment by podmepodme** [comment]
Unless I m reading it wrong, we should keep queries compact.
https://www.azerothcore.org/wiki/sql-standards#compact-queries

**Comment by elthehablo** [comment]
Although that is true in most cases, this mostly goes for simple inserts/deletes/updates and keeping those as short as possible.

One possible issue with this PR is that from the code you can't really see exactly what items are deleted, with deletes it is clear exactly what items are removed which is useful to maintain some level of version control and building a nice history.

**Comment by pangolp** [comment]
> Unless I m reading it wrong, we should keep queries compact. https://www.azerothcore.org/wiki/sql-standards#compact-queries

It is good to have compact queries, but so that the testers can test many times and the people watching understand the changes you are providing, we can write the query in another way. At the end of the day, after a while, when a release is made, all the updates are passed to the code base, however, it is good to keep the code clean, making sure to make as many queries as possible, but I am sure that It can be written in another way, that is more understandable at first glance. Also, after testing, I have to revert the code until the pull request is approved.

**Comment by elthehablo** [comment]
If the original author does not want to fix this I will push some changes myself and get this merged. I will just convert the entries taken from the joins into inserts m

**Comment by elthehablo** [comment]
Yes insert into values and then some neat lines

**Comment by pangolp** [comment]
What status is this pull request in? The author has changed the SQL.
And from what I see, it removes 4 items from a creature's loot.
I don't know if we need a sniff for this, or if we can merge it...

**Comment by sudlud** [comment]
Thanks for the PR!

Closing this as obsolete now with #18796 / 65942555b51c0200fdf962bc968ec9002686417a

**Pull request closed without merging**
