### PR TITLE
fix(DB/Creature): Kregg Keelhaul

### PR DESCRIPTION
**Pull request by razers211**
Scope :
      - fix(DB/SAI): Missing spells to NPC Kregg Keelhaul

  Descrption :  Kregg Keelhaul didn't use his spells on attacking targets (missing spells)

  - Closes AzerothCore issue #6955

## Changes Proposed:
-  Adding Kregg Keelhaul's SAI script with all it's missing spells
-  

## Issues Addressed:

- issue #6955

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
hey @razers211 thanks for this PR! have you tested this in game? as @Kitzunu pointed earlier, it would be nice if you can fill up the PR template so we know details such as whether it has been tested and how to test it ;)

**Comment by Kitzunu** [comment]
Please fix these errors =)

```
SmartAIMgr: Entry -51834 SourceType 0 Event 0 Action 11 uses non-existent Spell entry 83622, skipped.
SmartAIMgr: Entry -51834 SourceType 0 Event 1 Action 11 uses non-existent Spell entry 83643, skipped.
SmartAIMgr: Entry -51834 SourceType 0 Event 2 Action 11 uses non-existent Spell entry 83645, skipped.
```

**Review by LukasVolgger — APPROVED** [review]

**Comment by LukasVolgger** [comment]
Oh, although the code looks good please solve the errors

**Comment by razers211** [comment]
well these errors are poping out because these spells aren't even implemented yet apparently

**Comment by Kitzunu** [comment]
These are all Cataclysm Abilities, so invalid.

He should use 40504, 11976

Source
https://wowpedia.fandom.com/wiki/Kregg_Keelhaul?oldid=2464589 (From wotlk era)
https://tbc.wowhead.com/npc=8203/kregg-keelhaul#abilities

**Comment by Kitzunu** [comment]
Also I do not see the reason to make the SAI for the specific GUID, you can make it on the creature Entry instead

**Comment by FrancescoBorzi** [comment]
what is the status of this?

**Comment by Nefertumm** [comment]
Again, what's the status on this?

**Comment by FrancescoBorzi** [comment]
@Ragelezz what's the status of this PR?

**Comment by Ragelezz** [comment]
This can be closed since I created another PR, this one is not created by me so I don't have acces to edit this.

**Comment by FrancescoBorzi** [comment]
> This can be closed since I created another PR, this one is not created by me so I don't have acces to edit this.

ok, then please close it and other similar ones if any, so we don't have PRs opened that aren't going anywhere :)

**Pull request closed without merging**
