### PR TITLE
fix(DB/smart_scripts): Adjust SAI for Dabyrie Laborer

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Remove thrash ability
-  Add Pierce Armor

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/328

## SOURCE:

https://www.wowhead.com/spell=6016/pierce-armor
Dabyrie Laborer appears as an NPC who uses the ability "Pierce armor"

The ability thrash assigned to this NPC make him hits 7 times at once
image

## Tests Performed:

- Tested in-game

## How to Test the Changes:

.go c id 2582

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Delcidx** [comment]
Tested
test

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Si1ker** [comment]
The bug was introduced in https://github.com/azerothcore/azerothcore-wotlk/pull/4794
(no source provided when adding the ability)

**Comment by Si1ker** [comment]
The bug was introduced in https://github.com/azerothcore/azerothcore-wotlk/pull/4794
(no source provided when adding the ability)

cc @Stifler82

**Comment by Stifler82** [comment]
> The bug was introduced in #4794
> (no source provided when adding the ability)
> 
> cc @Stifler82

No, @Si1ker you're wrong, I didn't add that Spell to those mobs, I redid the SAI to those Mobs, **which's different so..**

Because I didn't add that Spell to those Mobs, **I just "Told"** to Mobs to use that Spell **ONLY when the target is from behind.** that's all..

So, The bug **WASN'T** introduced in #4794


https://www.wowhead.com/npc=2582/dabyrie-laborer#abilities **(WoW LIVE) NOT TBC OR CLASSIC**
`Dabyrie Laborer appears as an NPC who uses the ability "Pierce armor"`

Instead to me, it appears that you introduce wrong links as proof of your thesis.

**[Link Classic]:** [Dabyrie Laborer - Abilities](https://classic.wowhead.com/npc=2582/dabyrie-laborer#abilities)

**[Link TBC]:** [Dabyrie Laborer - Abilities](https://tbc.wowhead.com/npc=2582/dabyrie-laborer#abilities)

So instead, be careful to not introduce YOU some bugs.

That anyway, **(speaking to you and me)**, I'm pretty convinced **(NOW)** that even what Wowhead says in Classic and TBC is bullshit about these Mobs using these spells.
I am pretty convinced that Ability Section for those Mobs is rather some kind of metaphor that Blizzard uses to say that they have no skills/Ability other than to do "Daze"

**Pull request merged**
