### PR TITLE
fix(DB/SAI): Quest "Jack Likes His Drink"

### PR DESCRIPTION
**Pull request by sluggor**
Repair gossip menus for "Jack Likes His Drink" quest

##### CHANGES PROPOSED:

-  Update smart_scripts table for Olga and Jack to reflect proper gossip menus
-  Update character_template for Jack to point to correct gossip menu

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1854

##### TESTS PERFORMED:

Applied changes to database then ran through entire quest. Debt item was properly acquired and quest was able to be completed successfully.

##### HOW TO TEST THE CHANGES:

Go to pirate encampment in Howling Fjord and acquire quest "Jack Likes His Drink". Talk to Olga and give her a gold piece to deliver a spiked drink to Jack. Jack will go down and you should be able to click on him to collect the quest item needed. Turn in.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by poszer** [comment]
Hmm, the options are correct. But there is one more thing to fix  (The creature doesn't return to home path - Olga (Stopped at the half way), also the script isn't reseted. So if there is another player with this quest, he can't do it until server restart)

**Comment by sluggor** [comment]
OK, I'll take another look at her smart_script entries.

**Comment by sluggor** [comment]
Although Olga starts at -91.8194, -3532.71, 7.7126, her waypoint data had one point about halfway to Jack, and one right in front of him. I don't know if the code is supposed to use her creature table entry data as an implied waypoint or not, but she wasn't making it all the way back because there was no waypoint matching her starting point.

I added the extra waypoint and she walked all the way back, but did not turn back to her starting position, so that's what the extra smart_script entry is for.

By the way, it looks like no matter where Olga is, she'll still work for the quest, but Just must be spawned for her gossip menu to be active.

**Comment by wizzymore** [comment]
Idk about this quest or who tf Olga is but, is it blizzlike for her to walk again to her position or she can be respawned or, the moving npc shouldn't be phased?

**Comment by sluggor** [comment]
Blizzard version: Olga stands in the back of the bar. You bribe her to spike a drink for a patron. She delivers the drink to the patron, who passes out. You loot the patron's body for a quest item, then Olga walks back to her original position, ready to do it again for the next adventurer once the patron respawns.

There were a few database bugs and omissions that were causing the quest to fail at various points. It should all be worked out now.

**Comment by BarbzYHOOL** [comment]
Ok, nice. Are you on our discord tho?

**Comment by sluggor** [comment]
Tested it out on my local DB and it works great, thanks for the updates.

**Comment by Stoabrogga** [comment]
@sluggor 
Seems like something went wrong copying the changes. I corrected this, should be ok now.

**Comment by deadmanevil** [comment]
now if the routes are good to me also I found error but if now if it enters without problem and olga if it already makes its way as it should thanks

**Comment by poszer** [comment]
Thanks guys :+1:

**Pull request merged**
