### PR TITLE
DB/Quest Ulag the Cleaver

### PR DESCRIPTION
**Pull request by poszer**
[Quest Ulag the Cleaver](https://vanilla-twinhead.twinstar.cz/?quest=1819)

##### CHANGES PROPOSED:

-  Move Ulag the Cleaver to SAI
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1222

##### TESTS PERFORMED:

Tested in game with update. It's okay ( Players can now click on that ''Mausoleum Trigger'' and the doors are opening. The NPC "Ulag the cleaver" coming outside on Horse and attacking player) which is correct.

##### HOW TO TEST THE CHANGES:

1. .quest add 1819
2. .go xyz 2372.087646 363.687805 38.098766 0
3. Click on item in front of you '' Mausoleum Trigger ''
4. Take a look on the doors. 
5. They should opening and the '' Ulag the cleaver '' will come on horse attacking you.

##### KNOWN ISSUES AND TODO LIST:

- [x] Waypoint of the NPC is correct now
- [x] SAI is correct now

##### Target branch(es):

Master

Thanks @grimgravy

### CODE REVIEW

**Comment by grimgravy** [comment]
Do not forget to remove the [script ](https://github.com/azerothcore/azerothcore-wotlk/blob/2f5653c24fe0ca031c61cd1d3db6b7b400d6518d/src/server/scripts/EasternKingdoms/zone_tirisfal_glades.cpp#L147)

**Comment by Stoabrogga** [comment]
@poszer 
I think you can change the movement yourself. This should be the correct line:
https://github.com/azerothcore/azerothcore-wotlk/blob/cfef52d19049e61c4a6c39471b8c356dac097bf2/data/sql/updates/pending_db_world/rev_1546933586341240000.sql#L25

```2371.5554, 358.37, 38.092,0```

These values describe position x,y,z and orientation, just use another position and orientation here.

**Comment by Stoabrogga** [comment]
Tested it and the quest looks good, but was the seal always visible? I played a lot WotLK, and Forsaken are my favorites, but I don't recognize the seal on the crypt. Also found two old videos were the seal is not visible:
https://www.youtube.com/watch?v=U_5Et5tHdSg&t=395
https://www.youtube.com/watch?v=7gFnNU3wZdc&t=9

Sadly, I never played a Forsaken warrior, so cannot tell how the quest originally did work.

**Comment by poszer** [comment]
> pt. Also found two old videos were th

Hmm, i saw that videos too. There are more versions, on one effect is always visible, on other one it's visible just when used item ( So, i don't know how it is correct, for example on this video is just like on our update, check it please [Ulag the Cleaver : Vanilla Quest](https://www.youtube.com/watch?v=TssjgNMJuPk)

**Comment by Stoabrogga** [comment]
Oh, and another important note: You are deleting GUID 1532 from the gameobject table. This object was linked with template ID 2066 'Bonfire Damage'. I am not comfortable with deleting old entries, in my opinion it would be better to use a new GUID here.

**Comment by Stoabrogga** [comment]
@poszer 
Could you please use GUID 195629 instead of 1532? 195629 is definitely not used as it was removed in PR #845 (was a duplicate mail box in Undercity). This would avoid deleting existing entries.

As for the seal: I think it is ok if the seal is always visible, even if it's not blizzlike. Actually I find it rather interesting, because it shows that something is caged there and the crypt is special.

**Comment by poszer** [comment]
> @poszer
> Could you please use GUID 195629 instead of 1532? 195629 is definitely not used as it was removed in PR #845 (was a duplicate mail box in Undercity). This would avoid deleting existing entries.
> 
> As for the seal: I think it is ok if the seal is always visible, even if it's not blizzlike. Actually I find it rather interesting, because it shows that something is caged there and the crypt is special.

Sure, i'll do it. Thanks

**Comment by FrancescoBorzi** [comment]
good job @poszer and @Stoabrogga

**Comment by FrancescoBorzi** [comment]
@poszer I've updated your branch with master and restarted the build. Now it should pass

**Comment by grimgravy** [comment]
> @poszer
> Could you please use GUID 195629 instead of 1532? 195629 is definitely not used as it was removed in PR #845 (was a duplicate mail box in Undercity). This would avoid deleting existing entries.
> 
> As for the seal: I think it is ok if the seal is always visible, even if it's not blizzlike. Actually I find it rather interesting, because it shows that something is caged there and the crypt is special.

Doubt  [WoWHead](https://www.wowhead.com/quest=1819/ulag-the-cleaver#screenshots)

**Pull request merged**
