### PR TITLE
fix(Core\Spells):The Green Tower passive aura duration

### PR DESCRIPTION
**Pull request by Ragelezz**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/5682
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5649
- Closes https://github.com/chromiecraft/chromiecraft/issues/531

## Tests Performed:

- .aura 18097 and after .list aura, observe it has a duration of 30s, passive auras from items which gives a benefit (like procs or so) should be unlimted
- 

## How to Test the Changes:

1. .aura 18097 and after .list aura, observe Duration to -1, unlimited
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Ragelezz** [comment]
@T1ti

**Comment by Ragelezz** [comment]
@azerothcore/testers

**Comment by Nyeriah** [comment]
> Shouldn't u fix how the cores handles the data rather than modifying the data ?

Hey, do you have any suggestion on how we could address this one?

**Comment by jamadaha** [comment]
**Tested**
Bot tested the outlined method before and after, and this PR does indeed change it to -1 / unlimited.
After:
image
**Seems to work**

**Comment by Helias** [comment]
Probably, @T1ti means that there is a way to edit that data, the DurationIndex, through the SQL table `spell_dbc`, you could do it even Keira3 too if I remember correctly

**Comment by Ragelezz** [comment]
So how we should do it exactly ?

**Comment by Helias** [comment]
read in detail this https://www.azerothcore.org/wiki/spell_dbc
installing node-dbc-reader (https://github.com/wowgaming/node-dbc-reader) you could create the spell_dbc rows that you need and later you can edit them using Keira3

**Comment by T1ti** [comment]
> Probably, @T1ti means that there is a way to edit that data, the DurationIndex, through the SQL table `spell_dbc`, you could do it even Keira3 too if I remember correctly.
> 
> EDIT: you can, but you need to first populate the row of `18097` in spell_dbc with the original data (if it is not already present) and later you can use Keira3 to use the UPDATE sql query and edit the DurationIndex to -1.
> 
> I know, it can seem complicated but it's more long than complicated, you can use the DB to make this fix following this guide and using Keira3 https://www.azerothcore.org/wiki/spell_dbc
> 
> I am fine to keep this in the core, but I would like to move all the spells edit to the DB in the future if we can

No I meant that I doubt we need to modify the data, and that if AC needs it to be set to unlimited instead of the blizzlike data (the cactual duration), it's probably because AC doesn't handle the spell data correctly.

**Comment by claudiodfc** [comment]
I agree that this shouldn't be merged. If we keep adding band-aids to problems like these, one day when we have to remove the band-aids the infection will be out of proportions.
Fixing how the spell is handled and not hack fixing should be the way to go.

**Pull request closed without merging**
