### PR TITLE
fix(Scripts/ZulGurub): Venoxis - Holy wrath and Holy nova event

### PR DESCRIPTION
**Pull request by Maelthyrr**
## Changes Proposed:
-  The mechanic of holy nova was inverted with holy wrath. It's fixed now.
-  Adjust timers (provide from various videos)

## Issues Addressed:

None

## SOURCE:

https://youtu.be/3zbw-BvYPOc?t=39

https://wowpedia.fandom.com/wiki/High_Priest_Venoxis_(Classic)

Info: as nobody put a cac near the boss in P1, the timer of holy wrath is impossible to get without intensive test on retail. Guides and some youtuber said "often".
## Tests Performed:

Tested

## How to Test the Changes:

1. Engage Venoxis with 3 char
2. 2 char are far from the boss -> He should never cast Holy wrath
3. 2 char go near the boss -> He should cast Holy wrath

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
He didn't cast Holy Wrath for me, regardless if I had 2 characters near him.

Does that condition still apply in WotLK? In [this video](https://youtu.be/agtu7nDp8FM?t=57) he casts it at a pet, but it might work differently in that case. I'll try to look for more stuff when I have the chance.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Gultask let me know of what you come up.
@azerothcore/testers we will need a test on this as well.

**Comment by Gultask** [comment]
Condition shouldn't be enforced in WotLK: https://youtu.be/7dNMoocaGsY?t=35 (set video to a slower speed) :)

He should probably only cast it at his primary target.

**Comment by acidmanifesto** [comment]
@Maelthyrr is there any we need to adjust after feed back from Gultask?

**Comment by Maelthyrr** [comment]
> @Maelthyrr is there any we need to adjust after feed back from Gultask?

I'm not available before tomorrow night. But feel free to push changes if needed.

**Comment by Gultask** [comment]
The timers need to be adjusted and the condition needs to be removed, I guess.

If I remember to I can take a couple of samples of timers from some footage. I did a bunch of that before, it doesn't take too long :)

**Comment by Gultask** [comment]
I've gathered some samples from:
https://www.youtube.com/watch?v=bfrUV9T0_NI
https://www.youtube.com/watch?v=GGM8U_beCQI
https://www.youtube.com/watch?v=cmtJVaWBmBw (footage doesn't show the boss for a while so not many timers gathered here)
https://www.youtube.com/watch?v=erlaYrOfVGg (WotLK - no significant variation between vanilla)
https://www.youtube.com/watch?v=d2pBPV_fFvU (WotLK)

Also, can confirm that the conditions for Holy Wrath/Nova are not present in retail.

Holy Fire: [10, 10, 12, 12, 13, 15, 16, 17, 18, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 36, 40] avg of 19
Holy Wrath: [8, 12, 13, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 19, 20, 22, 22, 23, 26] avg of 17
Holy Nova: [7, 9, 10, 12, 12, 12, 13, 14, 14, 14, 14, 15, 15, 15, 16, 16, 16, 18, 19, 19, 19, 20, 20, 22, 23, 25, 26, 26, 27] avg of 17
removing the 2 outliers from Holy Fire gives an average of 16,3

It's important to note that Holy Fire can delay both Nova and Wrath because of its 3.5s cast time.
My reasoning, only taking samples into account, is: find the minimum, remove ridiculous outliers like 7s, take the average and make an arithmetic average calc to get the maximum.
Holy Fire: 10-24s
Holy Wrath: 12-22s
Holy Nova: 10-24s

This is just a suggestion, of course, I'm just providing some data and my thoughts. I'll leave it up to you :)

[From Vmangos](https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/stranglethorn_vale/zulgurub/boss_venoxis.cpp):
Holy Fire first at 10s, others at 8-12s
Holy Wrath: first at 30s, others at 15-25s
Holy Nova: first at 7.5s, others at 14-16s

The samples I gathered for the first cast have the timers being:
Holy Fire: [10, 10, 18, 21, 19, 36]
Holy Wrath: [15, 8, 17, 26, 16, 23]
Holy Nova: [10, 20, 14, 7, 23, 19, 25]
Always starting the count when combat starts.
I've not included some videos up there because I had only gotten 1 sample out of them before Phase 2 started.

**Comment by Maelthyrr** [comment]
> 

Thanks so much for your researches. I'm agree with your propose about timers. I will update the PR.

**Comment by Maelthyrr** [comment]
> I've gathered some samples from: https://www.youtube.com/watch?v=bfrUV9T0_NI https://www.youtube.com/watch?v=GGM8U_beCQI https://www.youtube.com/watch?v=cmtJVaWBmBw (footage doesn't show the boss for a while so not many timers gathered here) https://www.youtube.com/watch?v=erlaYrOfVGg (WotLK - no significant variation between vanilla) https://www.youtube.com/watch?v=d2pBPV_fFvU (WotLK)
> 
> Also, can confirm that the conditions for Holy Wrath/Nova were not present in retail.
> 
> Holy Fire: [10, 10, 12, 12, 13, 15, 16, 17, 18, 18, 18, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22, 36, 40] avg of 19 Holy Wrath: [8, 12, 13, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 19, 20, 22, 22, 23, 26] avg of 17 Holy Nova: [7, 9, 10, 12, 12, 12, 13, 14, 14, 14, 14, 15, 15, 15, 16, 16, 16, 18, 19, 19, 19, 20, 20, 22, 23, 25, 26, 26, 27] avg of 17 removing the 2 outliers from Holy Fire gives an average of 16,3
> 
> It's important to note that Holy Fire can delay both Nova and Wrath because of its 3.5s cast time. My reasoning, only taking samples into account, is: find the minimum, remove ridiculous outliers like 7s, take the average and make an arithmetic average calc to get the maximum. Holy Fire: 10-24s Holy Wrath: 12-22s Holy Nova: 10-24s
> 
> This is just a suggestion, of course, I'm just providing some data and my thoughts. I'll leave it up to you :)
> 
> [****From Vmangos****](https://github.com/vmangos/core/blob/development/src/scripts/eastern_kingdoms/stranglethorn_vale/zulgurub/boss_venoxis.cpp): Holy Fire first at 10s, others at 8-12s Holy Wrath: first at 30s, others at 15-25s Holy Nova: first at 7.5s, others at 14-16s
> 
> The samples I gathered for the first cast have the timers being: Holy Fire: [10, 10, 18, 21, 19, 36] Holy Wrath: [15, 8, 17, 26, 16, 23] Holy Nova: [10, 20, 14, 7, 23, 19, 25] Always starting the count when combat starts. I've not included some videos up there because I had only gotten 1 sample out of them before Phase 2 started.

Thanks so much for your researches. I'm agree with your propose about timers. I will update the PR.

**Comment by Gultask** [comment]
Holy Wrath takes a bit long to start up. Might want to modify that first timer. It's currently 60s.
Otherwise it's all good.

**Comment by Maelthyrr** [comment]
Done, Totaly forgot to change the first cast.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
