### PR TITLE
fix(DB/Core): quest chain leading to "Battle for the Undercity"

### LINKED ISSUE #1541: Quest issues before "Battle for the Undercity"
##### SMALL DESCRIPTION:

Before do quest "Battle for the Undercity" start, Alliance and Horde is missing follow quest and portal to th Undercity

You can see these on my test Video: https://youtu.be/uNpvKjCvonw
##### EXPECTED BLIZZLIKE BEHAVIOUR:

For Alliance: After the quest "The Killing Time"(13371) starts, there should be appear a portal to outside the Undersity sewer gate.

For Horde: It should have a follow quest "A Life Without Regretafter"(13266) and a portal when the "Herald of War"(13257) was done.

##### CURRENT BEHAVIOUR:

Alliance: 
1. When the quest "The Killing Time"(13371) starts, there is no portal to the Undercity.
2. I can't see the relevant NPC in specific place (the GM character can see them after re-login, the normal character can't see them)

Horde: 
1. After the quest "Herald of War"(13257) starts, Perhaps missing a portal to Orgrimmar.
2. When quest "Herald of War"(13257) is completed，No follow-up quest and missing a portal to the Undercity

##### STEPS TO REPRODUCE THE PROBLEM:

1. For Alliance:  .add quest 13370 and start the quest.
2. For Horde: .add quest 13257 and start it.
3. Or you can see the video: https://youtu.be/uNpvKjCvonw

##### EXTRA NOTES:

None
##### BRANCH(ES):

master

##### AC HASH/COMMIT:

9643ccd

##### OPERATING SYSTEM:

Ubuntu 16.04 64

##### MODULES:

None

##### OTHER CUSTOMIZATIONS:

None

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70759621-quest-issues-before-battle-for-the-undercity?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- add all necessary portals for the Horde and Alliance quest chain
- add Horde version of the phased Orgrimmar
- add event for "Herald of War", based on the already existing Alliance version with a few tweaks
- add a few tweaks to the event for "Fate, Up Against Your Will" (Alliance)
- add Runthak speaking to the Orc commoners (based on https://github.com/ElunaLuaEngine/ElunaTrinityWotlk/commit/3002839bfec1c69e00a191d82e569b647cd4fdb8)
- randomize the Forsaken refugees (some sleeping, some sitting around)
- add a 5th parameter to SAI events "SMART_EVENT_OOC_LOS" and "SMART_EVENT_IC_LOS" in order to allow a reaction to players only; this is based on these TC commits:
 https://github.com/TrinityCore/TrinityCore/commit/5ad38c31b0ed633555f281318684e57ea5d6dd73
 https://github.com/TrinityCore/TrinityCore/commit/f555a67bf850e1a9659c89551d7bb69cc812f161

###### ISSUES ADDRESSED:
Closes #1541 

##### TESTS PERFORMED:
tested in-game; tested build on Ubuntu 16.04

##### HOW TO TEST THE CHANGES:
Horde:
- ```.quest remove 13242```
- ```.quest remove 13257```
- ```.quest remove 13266```
- ```.quest remove 13267```
- ```.quest add 13242```
- ```.additem 43615```
- play through the complete quest chain

Alliance:
- ```.quest remove 13347```
- ```.quest remove 13369```
- ```.quest remove 13370```
- ```.quest remove 13371```
- ```.quest remove 13377```
- ```.quest add 13347```
- ```.additem 44474```
- play through the complete quest chain

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by ide1234000** [comment]
These quest chain looks perfect. Nice work!

**Comment by Nefertumm** [comment]
@ide1234000 did you tested the pr?

**Comment by ide1234000** [comment]
> @ide1234000 did you tested the pr?

Yes, it works well, I didn't find any problem.

**Comment by FrancescoBorzi** [comment]
good job @Stoabrogga and @ide1234000

**Pull request merged**
