### PR TITLE
feat(Core): Allow negative resistance values

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Many items in WoW history have negative element resistance, such as https://www.wowhead.com/wotlk/item=9509/petrolspill-leggings, but the current implementation uses unsigned int so negative values aren't support.
-  Changes to support negative values.

## Issues Addressed:

- Closes unreported issue

## Tests Performed:

- Tested in game, item tooltip successfully shows negative resistance value and resistance drops when item is equipped

## How to Test the Changes:

1. Add negative resist value to any item
2. Test in game

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I'm not sure how to test this one.
First it didn't allow me to modify the resistance values to negative so I changed the column properties to signed int. After that I modified the item but the changes didn't appear in the item tooltip nor the character screen.

**Comment by ZhengPeiRu21** [comment]
> I'm not sure how to test this one. First it didn't allow me to modify the resistance values to negative so I changed the column properties to signed int. After that I modified the item but the changes didn't appear in the item tooltip nor the character screen.

This SQL should work to make the item changes. Please make sure to clear your cache after running it:

```
-- Alter AzerothCore table to support Vanilla negative resistance values
ALTER TABLE item_template MODIFY fire_res SMALLINT;
ALTER TABLE item_template MODIFY holy_res SMALLINT;
ALTER TABLE item_template MODIFY nature_res SMALLINT;
ALTER TABLE item_template MODIFY frost_res SMALLINT;
ALTER TABLE item_template MODIFY shadow_res SMALLINT;
ALTER TABLE item_template MODIFY arcane_res SMALLINT;

/*  Petrolspill Leggings  */
UPDATE `item_template` SET `fire_res` = -10 WHERE entry=9509;
```

Also note that resistance cannot go below 0, so you will also need to wear another item that increases your resistance if you are want to see it decrease.

**Comment by Gultask** [comment]
Oh, thanks! Of course, it was the cache ^^
I also didn't know that it couldn't go below zero.
It's working 👍

**Comment by Nefertumm** [comment]
Wouldn't this need an sql change as well?

**Comment by ZhengPeiRu21** [comment]
I've updated this PR to include the needed SQL.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
