### PR TITLE
DB/Creature: Troll Roof Stalkers

### PR DESCRIPTION
**Pull request by poszer**
Missing creatures

##### CHANGES PROPOSED:

-  Added missing creatures : Troll Roof Stalkers
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1413

##### TESTS PERFORMED:

SQl imported without errors, Tested in game, the creatures are on the roofs of Orgrimmar.
Video : https://youtu.be/45fswt3G4cM

##### HOW TO TEST THE CHANGES:

1.  .go creature 200150
2. .go creature 200151
3. .go creature 200152

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Haha I knew about them, just thought they got removed during wotlk.

Nice, easy to test

**Comment by comix1988** [comment]
i tested this PR and the 3 pg walk normally on the roofs of the buildings, they are enemies for the alliance and friends for the horde but when they attack a player they remain in stealth (i don't know if this a bug)

schermata da 2019-02-06 00-29-13

**Comment by poszer** [comment]
> i tested this PR and the 3 pg walk normally on the roofs of the buildings, they are enemies for the alliance and friends for the horde but when attack a player they remain in stealth (i don't know if this a bug)
> 
> schermata da 2019-02-06 00-29-13

Try to attack them. Damage should break stealth

**Comment by comix1988** [comment]
I attacked them and the stealth break. Everything works properly.

**Comment by poszer** [comment]
> I attacked them and the stealth break. Everything works properly.

Nice, thank you for testings @comix1988 
Btw, If you aren't on our discord channel, join please

**Comment by BarbzYHOOL** [comment]
@comix1988 thank you for testing!!!

@poszer ty for PR as usual!

**Pull request merged**
