### PR TITLE
fix(DB/creature) first aid trainer

### PR DESCRIPTION
**Pull request by mpfans**
## Changes Proposed:
-   `Hellfire Peninsula`  first aid trainer can learn skills

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11979

## Tests Performed:

- tested ingame
Before fix
image

After fix
image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
`Creature (Entry: 18991) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
Creature (Entry: 18990) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
`

I don't know what their original gossip menu ID is. Who can help me?

**Comment by Maelthyrr** [comment]
> ```
> Creature (Entry: 18991) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
> Creature (Entry: 18990) has npcflag UNIT_NPC_FLAG_GOSSIP (1), but gossip menu is unassigned.
> ```
> 
> 
> image
> 
> 
> I don't know what their original gossip menu ID is. Who can help me?
> 
> 

Maybe ask in sniff channel to get the right text. And why this, I think that you can find the ID.

**Comment by Maelthyrr** [comment]
Tested and work fine.

<details>
WoWScrnShot_061122_212402
</details>

**Comment by acidmanifesto** [comment]
@mpfans i want to help and get this pr thru. can you try to see if you can get the same results without errors with:
first undo your current db pr with:
```
UPDATE `creature_template` SET `npcflag` = 208 WHERE `entry` IN (18990,18991) And `npcflag` = 209; 
```
then run this instead:
```
UPDATE `creature_template` SET `type_flags`=`type_flags`|0x08000000 WHERE `entry` IN (18990,18991);
```

**Comment by mpfans** [comment]
> 

not work

**Comment by acidmanifesto** [comment]
> > 
> 
> not work

Gotcha. I will look into it in full tomorrow

**Comment by acidmanifesto** [comment]
@mpfans a pr was merged that should make your pr pass. can you please fetch the upstream of your PR so the test can re-run?

**Comment by mpfans** [comment]
completed

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR.

**Comment by LannyE** [comment]
I updated my wowemu this morning and got these errors:
image

The last time I updated was June 22.  The third entry n the error list from the graphic is from this PR: #12125.  It changed the npcflag for the walker.   I noticed that these errors popped up in testing of this PR and in reading this conversation I guess a PR was supposed to fix it.  Did the PR not get merged?

**Comment by Nyeriah** [comment]
It's not an error, it's a warning, and needs to be ignored

**Comment by mpfans** [comment]
> I updated my wowemu this morning and got these errors: image
> 
> The last time I updated was June 22. The third entry n the error list from the graphic is from this PR: #12125. It changed the npcflag for the walker. I noticed that these errors popped up in testing of this PR and in reading this conversation I guess a PR was supposed to fix it. Did the PR not get merged?

apply this commit  https://github.com/azerothcore/azerothcore-wotlk/commit/37c1ce5e36c9749bc9a063f0621bb1f02e47a6f1

**Comment by mpfans** [comment]
update your core to newest

**Comment by LannyE** [comment]
That commit was applied:
image

If it is a warning than I will ignore it.  It just shows red in the console so I took it as an error.

**Comment by acidmanifesto** [comment]
> That commit was applied: image
> 
> If it is a warning than I will ignore it. It just shows red in the console so I took it as an error.

if that is what you have applied then you may of specificed different logging settings in the world conf. on my end with current revision, i am not getting red on the console.

**Comment by LannyE** [comment]
After what you told me in another thread that you are not getting any errors. I did another pull and build and the errors went away.  I also rebuilt my world config file.  Thanks all for helping me through this brain dead moment.

**Pull request merged**
