### PR TITLE
Gurubashi arena fix

### PR DESCRIPTION
**Pull request by talamortis**

### CODE REVIEW

**Comment by ShinDarth** [comment]
Hi, can you use UPDATE or DELETE/INSERT instead of REPLACE?

also read https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files

thank you!

**Comment by talamortis** [comment]
Sure, I shall edit it now.

**Comment by DevRival** [comment]
And where the ending .sql file?

**Comment by DantestyleXD** [comment]
Attached your file with some adjust, please watch my adjust.
Unfortunately it doesn't work because there is a core script on the NPC that bypass SmartAI.

By the way, it's a great work.
[16_08_14_01.zip](https://github.com/azerothcore/azerothcore-wotlk/files/426030/16_08_14_01.zip)

**Pull request closed without merging**
