### PR TITLE
fix(Core/Mails): Do not load expired mails from database.

### PR DESCRIPTION
**Pull request by UltraNix**
## Tests Performed:

- Not tested.

## How to Test the Changes:

Get 140 AH mails

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Why dont we delete expired mails?

**Comment by Nyeriah** [comment]
> Why dont we delete expired mails?

We do, every 6 hours from what I understand. However, if you have a gazillion AH mails it is not fast enough and you'll find yourself stuck with too many pending sale mails.

**Comment by Kitzunu** [comment]
Then we can just delete them on load instead of skipping them? Or will that be too big of a load for the DB to handle everytine?

**Comment by UltraNix** [comment]
@Kitzunu We can't, because sometimes expired mails must be returned to sender.

**Comment by Kitzunu** [comment]
Ah, fair point, and I guess that happens every 6 hrs then

**Comment by UltraNix** [comment]
Yes.

**Review by Kitzunu — APPROVED** [review]

**Comment by temperrr** [comment]
Tested:

After buying 140 items (or selling 140 items) I get the message when inbox is full. After clearing the inbox I can instantly sent mail again to these characters.

However, this is now spamming console after logging in on the char that sold all the items on AH, and I dont think we want this spam in wordconsole, if ever?

image

**Comment by UltraNix** [comment]
@temperrr Done.

**Pull request merged**
