### PR TITLE
Scripts/Item: Fixed Gnomish Death Ray.

### LINKED ISSUE #5648: Current Gnomish Death Ray Behaviour Not Blizz-Like
#### WHAT CLIENT DO YOU PLAY ON?
enUS

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/528

Gnomish Death Ray is not working properly, it doesnt take your health, it hits for a fixed amount of damage, and sometimes it deals no damage and then you get the dot as if you were casting the ray.

Damage log of multiple casts in a duel. The physical damage taken is from backfires.
WoWScrnShot_050521_221819

When it does backfire, you get a debuff/dot that says you are charging the GDR. The debuff should vary in damage, and should be applied on every shot, not just backfires. Not doing damage to the target on a backfire is correct, however.
WoWScrnShot_050521_224130

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. The GDR charging process should do physical damage to the caster every time it is used. The user damage is not set, but varies.
2. The damage should also vary significantly, not be the same value all the time. Wowpedia says "The damage ranges from 700-3000 on normal and is significantly higher when it crits." (https://wowpedia.fandom.com/wiki/Gnomish_Death_Ray?oldid=2348758)

As soon as you casted it, it should take some of your hp and then hit the enemy.
https://www.youtube.com/watch?v=ngTRw2w1onY&ab_channel=J%C3%B8rnEvenrud
https://www.youtube.com/watch?v=nROztXtjCZY&ab_channel=FarvaGeddon

##### STEPS TO REPRODUCE THE PROBLEM:

1. Cast Gnomish Death Ray multiple times on a character.

##### EXTRA NOTES:
 https://wowgaming.altervista.org/aowow/?item=10645

Trinity has some notes that might be handy: https://github.com/TrinityCore/TrinityCore/issues/4087

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/91081f4ad8fed98d7bdc9c0ae13d05c86032df9f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98292740-current-gnomish-death-ray-behaviour-not-blizz-like?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #5648

## Changes Proposed:
-  Corrected the item script.

## Issues Addressed:

- Closes #5648
- Closes https://github.com/chromiecraft/chromiecraft/issues/528
- 
## Tests Performed:

- Tested ingame.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
image
Why do I still have fixed damage after merging

**Comment by UltraNix** [comment]
What spell?

**Comment by pklloveyou** [comment]
13279

**Comment by UltraNix** [comment]
This one is casted to your victim.

**Comment by pklloveyou** [comment]
@UltraNix Select the target character and click on the item to cast the spell.

**Comment by pklloveyou** [comment]
But it's still like that. Have you tested it?

**Comment by UltraNix** [comment]
@pklloveyou Try now.

**Comment by pklloveyou** [comment]
I'm extracting the VMap MMAP map

**Comment by UltraNix** [comment]
> But it's still like that. Have you tested it?

Yes. On my local it works as intended.

**Comment by pklloveyou** [comment]
image
Tested

**Comment by FrancescoBorzi** [comment]
@pklloveyou works as intended?

**Comment by pklloveyou** [comment]
Absorb and cause damage

**Pull request merged**
