### PR TITLE
fix(DB/Creature) Tarindrella movement type

### PR DESCRIPTION
**Pull request by Maelthyrr**
## Changes Proposed:
-  Set movement type to 1 (random type)

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11801

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Create night elf character
2. Find Tarindrella NPC in Shadowglen
3. Check her behavior

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Not working. Does a radius need to be set?

**Comment by Maelthyrr** [comment]
> Not working. Does a radius need to be set in wander_distance/spawn?
> 
> edit: I've just begun testing PRs yesterday, so it could very well be a problem on my end.

Possibly. I start with DB ^^. I will look this later.

**Comment by Nefertumm** [comment]
Indeed, you have to update the creature table with a wander distance in order to work :)

**Comment by Gultask** [comment]
@Maelthyrr Someone submitted a sniff in the issue in the AC repo: https://github.com/azerothcore/azerothcore-wotlk/issues/11801#issuecomment-1134101259
wander_distance is 7

**Comment by Maelthyrr** [comment]
You have right. @Gultask it's should work now.

**Comment by Gultask** [comment]
Tested and working 👍

**Comment by Kitzunu** [comment]
Why are we not just updating the field if the creature already exists?

**Comment by Maelthyrr** [comment]
I just used Keira. And It's generate changes by delete/insert. But I can look to just update thé creature.

**Review by Nefertumm — APPROVED** [review]

**Comment by heyitsbench** [comment]
Looks like this was also supposed to close https://github.com/chromiecraft/chromiecraft/issues/3515.

**Pull request merged**
