### PR TITLE
feat(Core/Logging): Changed format of packet log file from .bin to .pkt

### LINKED ISSUE #5930: Error on the consol server
**CURRENT BEHAVIOUR:**

AC>> Config: Missing name PacketLogFile in config, add "PacketLogFile = "

**EXPECTED BLIZZLIKE BEHAVIOUR:**

It seems that "PacketLogFile = " is missing in the conf file

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Run the server
2. create/connect char
3. Wait few minutes
4. see on the consol

**EXTRA NOTES:**

**AC HASH/COMMIT:**
 
b2ab5dba79c1

**OPERATING SYSTEM:**

Ubuntu 20.04

**MODULES:**

**CUSTOMIZATIONS:**

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98542571-error-on-the-consol-server?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- https://github.com/WarheadCore/Warhead/commit/42decaa360c31c7ed2e35c92837910daa7a3dbd8
- https://github.com/WarheadCore/Warhead/commit/57cf08f86ec389a32c73c174c231a8b1ceed1371

## Issues Addressed:
- Closes #5930

## Tests Performed:
-

## How to Test the Changes:
-

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
build fails

**Comment by pangolp** [comment]
I just tested the PR with the latest version of the emulator and apparently, the message disappeared.

worldserver

gitlog

**Review by pangolp — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
> I just tested the PR with the latest version of the emulator and apparently, the message disappeared.
> 
> worldserver
> 
> gitlog

Thanks for testing

**Comment by pangolp** [comment]
You are welcome.

**Pull request merged**
