### PR TITLE
fix(Core/AI): correct Permit level for trigger flagged creatures

### LINKED ISSUE #12498: SmartAI CPP update case some problem
### Current Behaviour

Many problems occurred after the change of the SmartAI module, including the second step of the Nagrand Arena mission, the blue twins could not be completed. Karazhan's Void Dragon, after opening the red, green and blue doors, can not see the door to the boss line, etc.
I think this might cased by "Commits on Jul 18, 2022"  6ac7dfa
https://github.com/azerothcore/azerothcore-wotlk/commits?author=IntelligentQuantum

### Expected Blizzlike Behaviour

When the source code was not synchronized 10 days ago, it was normal, but after synchronizing master 3 days ago, these problems appeared.

### Source

_No response_

### Steps to reproduce the problem

1 Nagland arena to pick up the task, the second step after playing the blue twin brothers task can not be completed
2 Karazhan Void Dragon, after the door open, can't see the line connection line to the boss.  But the player blocked the middle, the effect is present after try blocking.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 2d4e93dc3e2d+ 2022-07-22 21:20:14 -0400 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100515
Using CMake version: 3.18.4
Compiled on: Linux 5.15.35-3-pve
Worldserver listening connections on port 54345
Realmlist (Realm Id: 1) configured in port 54345
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /root/wow/bin/maps. Total size: 291014339 bytes
vmaps directory located in /root/wow/bin/vmaps. Total size: 658130553 bytes
mmaps directory located in /root/wow/bin/mmaps. Total size: 2320900760 bytes
Using zhCN DBC Locale as default. All available DBC locales: zhCN 
Using World DB: ACDB 335.7-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0

### Operating system

debian 11

### Custom changes or Modules

_No response_

### LINKED ISSUE #12604: Void Specter Dragon of Karazhan
### Current Behaviour

Void Gate Stage
In the room entrance to the left, right, and directly opposite each have a void door point, whenever you enter the stage, the three points will each refresh a different color void door, and after 10 seconds from the three doors at the same time issued three corresponding color light shot to the BOSS, now the problem is that the three light no actual display effect, not visible to the naked eye.

### Expected Blizzlike Behaviour

After the appearance of the void door, should appear from the door at the same time, red, green and blue light shot to the void dragon.

### Source

_No response_

### Steps to reproduce the problem

Open the team mode into Karazhan, directly with the Void Dragon battle until the appearance of three void doors can see the problem of not showing light. (red line green line blue line)

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. bad616c68a66+ 2022-07-27 12:47:50 +0000 (master branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1l  24 Aug 2021 (library: OpenSSL 1.1.1l  24 Aug 2021)
Using Boost version: 1.74.0
Using MySQL version: 50737
Using CMake version: 3.22.4

### Operating system

Windows 7 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by pklloveyou**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes #12604
- Closes #12498

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
@kissingers @zxnhrdz

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Trinity counter part: https://github.com/TrinityCore/TrinityCore/commit/1de89579c75f7b5d5028b162334fa496832a093c

**Comment by kissingers** [comment]
update to  a4c809f13c818d1d7e078ed49cd67afbebebd900

The Karazhan's Void Dragon which creature ID 15689 still no line to boss (now the problem is can't see the line, but if stay between boss and the door, the line effect will have)

I can sure flow update case the problem. before this update, there is no problem, after this update problem appear.  and any flow updates till today still not be fixed. 
https://github.com/azerothcore/azerothcore-wotlk/pull/11779 cc52712

The pic show no line between the boss and door, but have door effect to player.

**Comment by pklloveyou** [comment]
@kissingers It's not about where you update, it's about trying this pr

**Comment by pklloveyou** [comment]
Thank you for your reply

**Comment by zxnhrdz** [comment]
@pklloveyou
Update PassiveAI.cpp　068a476
Thanks a lot, the problem is solved!
QQ图片20220805005534

**Comment by pklloveyou** [comment]
Thank you for your reply

**Pull request merged**
