### PR TITLE
fix (core/logging): fixed wrong decription of error during server startup

### PR DESCRIPTION
**Pull request by Bogir**
The Logger was pointing to the wrong table. Text is missed not in `broadcast_text_locale`, but in `broadcast_text`.

## How to Test the Changes:

What we have now:
1. add new record with some ID to broadcast_text_locale table
2. start server and see error.
3. add record to broadcast_text with same ID - error will dissapear

After applying the fix :
изображение

### CODE REVIEW

**Comment by acidmanifesto** [comment]
@Nyeriah Im not seeing this error on a clean database as of 5 minutes ago, is this a issue being mentioned else where by chance?

**Comment by Kitzunu** [comment]
I dont have this issue either. Probably a missing file.

**Comment by acidmanifesto** [comment]
@Kitzunu Actually I missunderstood the pr explaination. His PR deals with a better explaination IF a error was to occur.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
I will approve the changes for now but will wait for additional feed back incase i misunderstood what i am seeing the changes.

**Comment by Nyeriah** [comment]
Yes
>add new record with some ID to broadcast_text_locale table
start server and see error.
add record to broadcast_text with same ID - error will dissapear

You gotta force the error to show up to test it, it might be okay

**Comment by acidmanifesto** [comment]
image
I believe the suggested changes are valid incase a error was to ever happen on a future pr, we will see it on the dry run with a better description.

**Comment by Bogir** [comment]
Yes, this logger handles the error appears if developer adds some new localized text but forgot to add it to general table.
In clean base it must not never happens

Now I'm trying to apply customisations to clean core/db and facing with such errors. So, I found another loggers which not correctly points on the reason of error.
Maybe I'll fix them too

**Comment by acidmanifesto** [comment]
Just following up, the failure with  ubuntu-20.04-clang-with-modules test has nothing to do with this PR but another module that is being worked on unrelated to this pr.
image

**Review by Winfidonarleyan — APPROVED** [review]

**Pull request merged**
