### PR TITLE
fix(Scripts/Brewfest): Some tweaks to Dark Iron Attack event.

### LINKED ISSUE #7871: [Brewfest] Issues with Brewfest Revelers
### Current Behaviour

Brewfest Revelers Entry 24484  (https://wowgaming.altervista.org/aowow/?npc=24484) of horde or ally race are all set to friendly for Horde characters and neutral for alliance characters.

revelerally
revelerhorde
aaa
bbb

Doing /drink emote on Brewfest revelers does not award buff called Brewfest Toast.

Also, it seems that Brewfest Revelers are mising the RP scripts, they are all just standing still (with expcetion of two who are dancing).

https://user-images.githubusercontent.com/80769357/133233629-8786d041-c735-48da-8526-d29ea8bfc6ca.mp4

You can see that they don't have mugs, they don't cheer/drink

### Expected Blizzlike Behaviour

Brewfest Revelers of horde races should be friendly towards horde characters and neutral towards allaince characters.
Brewfest Revelers of alliance races should be firendly to alliance characters and neutral towards horde chartacters.

When doing a /drink emote on a brewfest reveler, you should get a 30 min 15 stamina buff called Brewfest Toast (https://wowgaming.altervista.org/aowow/?spell=41586)

Brewfest Revelers should have scripted RP, should talk/cheer/drink as shown in screenshots and videos linked in sources.

### Source

https://wowpedia.fandom.com/wiki/Brewfest_Reveler
https://tbc.wowhead.com/spell=41586/brewfest-toast#comments

https://youtu.be/nggjFT4GTTE?t=40 - video from 2009, shows alliance char in horde brewfest area, when hoovering over brewfest revelers there a sword appears

https://youtu.be/vmNIIGo5EzM?t=201 - video from 2010 brefest, you can see the revelers in Dun Morogh friendly towards alliance character

https://tbc.wowhead.com/npc=24484/brewfest-reveler#screenshots

### Steps to reproduce the problem

1. .event start 24
2. Go to Brewfest locations infront of Orgrimmar or Ironforge
3. Observe the revelers as ally and horde char at both locations

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 26aee27f600d

### Operating system

Windows 7 x64

### Custom changes or Modules

_No response_

### LINKED ISSUE #7872: [Brewfest] Dark Iron attack not working properly
### Current Behaviour

When the Dark Iron attack starts, the Brewfest Revelers do not flee the area.
The Dark Iron Guzzlers (https://wowgaming.altervista.org/aowow/?npc=23709) move too fast and are glitchy, starting to glide after drink animation.

https://user-images.githubusercontent.com/80769357/133238727-71d3cb07-545a-4b0b-a465-653870d86100.mp4

https://user-images.githubusercontent.com/80769357/133238747-9de2ece2-85ba-4d6d-935a-d448c97264ad.mp4

Haven't check Horde side yet.

### Expected Blizzlike Behaviour

Brewfest revelers should flee the area of the attack before the Dark Iron attack starts.
Dark Iron Dwarves should move slower and should not glitch to gliding after doing drink animation.

### Source

https://youtu.be/vmNIIGo5EzM?t=653

https://youtu.be/QSwCSD9t_BI?t=28

https://tbc.wowhead.com/npc=23709/dark-iron-guzzler#comments
https://wowpedia.fandom.com/wiki/Dark_Iron_Guzzler
https://wowwiki-archive.fandom.com/wiki/Dark_Iron_Guzzler

### Steps to reproduce the problem

1. .event start 24
2. observe the Dark Iron attack (happens every hour at half hour time, like 5.30, 6.30 etc)

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 26aee27f600d

### Operating system

Windows 7 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #7872

## Issues Addressed:

- Closes #7871
- Closes #7872

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. `.event start 24`
2. observe the Dark Iron attack (happens every hour at half hour time, like 5.30, 6.30 etc)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
Without pr: Dwarves were super fast and overal glitchy
With pr: 

- [x] dwarves are correct speed. The mugs on floor are working. (aoe wirlwind damage to the dwarfs. 
- [ ] Server crashes when event fails or when event is succesful. No logs in server.txt. (worldserver crashes, authserver stays up). If there is any information I could obtain elsewhere please say.

**Comment by UltraNix** [comment]
@temperrr Send crashlogs.

**Comment by temperrr** [comment]
[Uploading 4074d0e93d1f_worldserver.exe_[22-9_18-31-53].txt…](
[4074d0e93d1f_worldserver.exe_[22-9_18-35-1].txt](https://github.com/azerothcore/azerothcore-wotlk/files/7212709/4074d0e93d1f_worldserver.exe_.22-9_18-35-1.txt)
)

**Comment by UltraNix** [comment]
The lines in these crashlogs do not match the real lines. Do you have your own script/code in this file?

**Comment by UltraNix** [comment]
I cannot reproduce it and I don't know what might be the cause. Can somebody else check if it is crashing?

**Comment by temperrr** [comment]
Tested;

- [x] event starts every half hour
- [x] Revelers run away
- [x] Revelers respawn when event ends. 
- [x]  dwarves are correct speed. 
- [x]  no errors in worldserver
- [x] no crash when event fails (ironforge)
- [ ] crash when event is succesful and clicking the cog. It should give the quest  https://tbc.wowhead.com/quest=12020/this-one-time-when-i-was-drunk (a) / https://tbc.wowhead.com/quest=12192/this-one-time-when-i-was-drunk (h
[fdbe9a31ee4c_worldserver.exe_[23-9_8-35-1].txt](https://github.com/azerothcore/azerothcore-wotlk/files/7215363/fdbe9a31ee4c_worldserver.exe_.23-9_8-35-1.txt)
)

**Comment by UltraNix** [comment]
@temperrr If you don't click on that cog, the server crashes anyway?

**Comment by temperrr** [comment]
Also crashes after a few seconds when not clicking the cogwheel.

**Comment by UltraNix** [comment]
@temperrr Can you try again?

**Comment by temperrr** [comment]
- [x] No crash at the end now in ironforge and got quest and handed it in. 
- [x] Event in orgrimmar works  too. same notes as above
- [x] Failing event does not give cog and quest. (correct!)

**Review by Helias — APPROVED** [review]

**Pull request merged**
