### PR TITLE
fix(Core/Spells): Ignite and Revitalize should not prelong combat.

### LINKED ISSUE #13330: Triggered Spells put you into combat
original issue https://github.com/chromiecraft/chromiecraft/issues/3905. confirmed on ptr
### Current Behaviour

Triggered spells, like Mage Ignite put both sides into combat when they trigger
This leads to a very long combat timer when a mage has living bomb on a target and it crits

### Expected Blizzlike Behaviour

Triggered Spells have no influence on the combat timer

### Source

https://youtu.be/qavkjivhSkQ?t=696

Here you see the mage leaving combat with a crit of living bomb causing ignite to trigger 1 second ago

Proof that he has the living bomb glyph (ignite on the new target that had a previous casted living bomb on):
https://youtu.be/qavkjivhSkQ?t=436

### Steps to reproduce the problem

    Get 2 characters, 1 of them mage
    On the mage learn ignite and living bomb
    .add 18970 2
    .add 45737
    Equip those rings
    Learn the Glyph
    Duel
    Cast Living Bomb
    Look at the combat status

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=44457
https://wowgaming.altervista.org/aowow/?spell=12848

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Custom changes or Modules

[mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
    [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
    [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
    [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
    [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
    [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
    [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
    [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
    [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
    [mod-eluna](https://github.com/azerothcore/mod-eluna)
    [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
    [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
    [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
    [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
    [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
    [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
    [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
    [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
    [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
    [mod-transmog](https://github.com/azerothcore/mod-transmog)
    [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
    [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
    [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
    [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
    [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
    [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
    [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
    [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
    [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
    [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #13330

## Issues Addressed:

- Closes #13330
- Closes https://github.com/chromiecraft/chromiecraft/issues/3905
- Closes https://github.com/chromiecraft/chromiecraft/issues/4072

## Tests Performed:

- Not tested.

## How to Test the Changes:

Ignite:
Get 2 characters, 1 of them mage
On the mage learn ignite and living bomb
.add 18970 2
.add 45737
Equip those rings
Learn the Glyph
Duel
Cast Living Bomb
Look at the combat status

Revitalize:
For the combat:
Same talents
Needs 3 chars
Cast Rejuv on friendly char and then attack hostile char with that one
Wait for the Revitalize proc and see if combat is prelong

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I didn't see any difference with Living Bomb + Ignite.

**Comment by UltraNix** [comment]
https://user-images.githubusercontent.com/80540499/202844299-d2845d13-7c2a-42df-b791-78c3716bc39e.mp4
Works okay.

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
All the affected spells like deep wounds and so also works as before? :D

**Comment by UltraNix** [comment]
@Nefertumm Not affected by this PR.

**Comment by Gultask** [comment]
Living Bomb with Ignite:

https://user-images.githubusercontent.com/100873791/203186539-91fef281-6dcb-411c-92c2-cce0747a5bdb.mp4

Tried Deep Wounds. Had a freeze/crash:
https://gist.github.com/Gultask/4cc4ef682984599afd001933639b1b96

I'll try to reproduce again

**Comment by UltraNix** [comment]
Tested Living Bomb: the combat lasts 5 sec after the initial cast - it's okay.
Deep Wounds not affected by this PR, as stated above.

**Pull request merged**
