### PR TITLE
fix(Core/Deps): fix build

### PR DESCRIPTION
**Pull request by mik1893**
fix build for VS 2015 onwards

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@mik1893 now the travis build fails:

https://travis-ci.org/azerothcore/azerothcore-wotlk/jobs/571501234

**Comment by milestorme** [comment]
`wotlk/deps/recastnavigation/Detour/Include/DetourCommon.h:22:
656/home/travis/build/azerothcore/azerothcore-wotlk/deps/recastnavigation/Detour/Include/DetourMath.h:22:46: fatal error: use of undeclared identifier 'isfinite'; did you mean 'std::isfinite'?
657inline bool dtMathIsfinite(float x) { return isfinite(x); }
658                                             ^~~~~~~~
659                                             std::isfinite`

**Comment by pklloveyou** [comment]
nice
VS2019 success (win10x64）

**Comment by FrancescoBorzi** [comment]
well done @mik1893 and thanks @pklloveyou for reporting the bug and testing the PR

if travis passes it can be merged

**Comment by pklloveyou** [comment]
Extract map again?

**Comment by FrancescoBorzi** [comment]
@pklloveyou no need

**Pull request merged**
