### PR TITLE
fix(Core): Bag/Fishing pole equip

### PR DESCRIPTION
**Pull request by poszer**
Fix bag issue and fishing pole on spaw if the bag is full

##### CHANGES PROPOSED:

-  Fix bug When your bags are full and you equip a fishing pole, from 2x one handed weapon, it equip the fishing pole, than 1 weapon goes into bag and the other goes into the mailbox from "customer support".
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/152

##### TESTS PERFORMED:

Builded without errors. Yes, tested in game, everything looks fine now, without problem.
Including some pictures, and video as proof:
Screenshot_3
Screenshot_4
Screenshot_5

[Video here-Recorded with low quality(Reduce time upload lol)](https://youtu.be/EDHgbiHjLA4)

##### HOW TO TEST THE CHANGES:

**First try without this commit, to reproduce issue :**
1. Create character which can equip 2 one hand weapons (Ex. Rogue)
2. Equip two one handed weapons (In Main hand & off hand)
3. Learn fishing
4. Get Fishing Pole in your bag
5. Place some random items in your bag, to leave it without empty slot
6. Than Equip fishing pole 
7. Result is --> You will get your 1 one hand item in bag, and other one in mail, and also your fishing pole will be equiped >>> Incorrect

**Now try with this commit, same steps** :+1: 

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Viste** [comment]
Need test titan grip(fury warr) :)

**Comment by poszer** [comment]
> Need test titan grip(fury warr) :)

 It allows a warrior to wield a two-handed weapon in one hand and increases maximum health by 15%. Dual-wielding is only allowed for Axes, Maces, Swords and Polearms. So i don't know on what you mean ?

**Comment by Viste** [comment]
try to equip 2 fishing poles )

**Comment by poszer** [comment]
> @poszer try to equip 2 fishing poles )

fishing pole

**Comment by Viste** [comment]
this is wrong behaviour ) you can equip only 1 fishing pole even if you warrior

**Comment by poszer** [comment]
> this is wrong behaviour ) you can equip only 1 fishing pole even if you warrior

I think this is correct way, since we have this issue with every class who can equip 2 weapons. For the warrior, my suggestion will be to implement code/check for it, and give restriction to equip 2 fishing poles. As now, it allow equip 2 fishing poles just if you have one equiped fishing pole and off hand slot free. But if the warrior have weapon equiped weapons, and equip one fishing pole in main hand, and than try to equip another fishing pole in off hand which is currently used by another weapon / He can't.

**Comment by Knindzagxg** [comment]
Bug is gone for now, atleast reported one.
As said, 2h issue remain still.

**Comment by wizzymore** [comment]
> It allows a warrior to wield a two-handed weapon in one hand and increases maximum health by 15%. Dual-wielding is only allowed for Axes, Maces, Swords and Polearms. So i don't know on what you mean ?



> > this is wrong behaviour ) you can equip only 1 fishing pole even if you warrior
> 
> I think this is correct way, since we have this issue with every class who can equip 2 weapons. For the warrior, my suggestion will be to implement code/check for it, and give restriction to equip 2 fishing poles. As now, it allow equip 2 fishing poles just if you have one equiped fishing pole and off hand slot free. But if the warrior have weapon equiped weapons, and equip one fishing pole in main hand, and than try to equip another fishing pole in off hand which is currently used by another weapon / He can't.

It is not normal to have 2 fishing poles, as you said in the first Quote, only Axes, Maces, Swords and Polearms

**Comment by poszer** [comment]
> > It allows a warrior to wield a two-handed weapon in one hand and increases maximum health by 15%. Dual-wielding is only allowed for Axes, Maces, Swords and Polearms. So i don't know on what you mean ?
> 
> > > this is wrong behaviour ) you can equip only 1 fishing pole even if you warrior
> > 
> > 
> > I think this is correct way, since we have this issue with every class who can equip 2 weapons. For the warrior, my suggestion will be to implement code/check for it, and give restriction to equip 2 fishing poles. As now, it allow equip 2 fishing poles just if you have one equiped fishing pole and off hand slot free. But if the warrior have weapon equiped weapons, and equip one fishing pole in main hand, and than try to equip another fishing pole in off hand which is currently used by another weapon / He can't.
> 
> It is not normal to have 2 fishing poles, as you said in the first Quote, only Axes, Maces, Swords and Polearms

Yeah, it's okay now. With the lats commit, they can equip just one fishing pole

**Comment by deadmanevil** [comment]
if it was tremendous bugs for the warrior since they could have two and now that's not so good that is already solved also already tried in my source with the correction and is all right for the moment

**Comment by poszer** [comment]
> if it was tremendous bugs for the warrior since they could have two and now that's not so good that is already solved also already tried in my source with the correction and is all right for the moment

I don't believe you anything dude. I already meet you, and your testing '' writing us that everything is correct '' but when i checked, you lie. Just to become contributor or ? 
Also for this, first i don't understand you. Second i'm sure you didn't test this, since i follow git log on discord bcoz of your comments, You did test for XX Pr's in less than 4 minutes. How actually? Once i give you help about core, i saw that your machine is too slow, how the fc* you are compiling now in minute? Let me guess, you lie again ofc :-1:

**Comment by deadmanevil** [comment]
I think you're bad friend the test is done on the basis of linux tell me that it is faster to compile linux or windows now also tell me you ask me help tell me when you have done tell me a test where you have done

**Comment by deadmanevil** [comment]
not to be good you say it friend and then say you have asked for help because I have nothing

**Comment by FrancescoBorzi** [comment]
@deadmanevil please provide screenshots and/or videos about your tests.

**Comment by Viste** [comment]
@deadmanevil compile speed mostly base on CPU power not the OS lol 
VS and Clang/GCC show almost same results on same CPU.

**Comment by Viste** [comment]
Btw nothing to test here code is very simple to understand what is going on... 
and now all is OK! CAN BE MEREGED!

**Comment by BarbzYHOOL** [comment]
I agree with Mr. Nice

**Comment by deadmanevil** [comment]
> @deadmanevil please provide screenshots and/or videos about your tests.


yes friend I know you from trinity core

**Pull request merged**
