### PR TITLE
fix (Core/Pathfinding): Remove unnecesary LiquidData Z check

### PR DESCRIPTION
**Pull request by WORISX**
Remove an unnecessary LiquidData status check that was correcting Z position on ending points inside water, check added probably for SunwellCore before the Movement Rewritte done last year on AzerothCore, this fixes global pathfinding problems on all Movement Generators including all pathfinding problems that make creatures and players go through textures in case the pathpoints are exclusively underwater.

## Changes Proposed:
-  Remove unnecessary LiquidData status Z checks.
-  Just pass directly the pointCount

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10119 (should be marked as priority high/critical, but no one marked as, pretty gamebreaking)

## Tests Performed:

- Tested and working on latest master, no more charge, waypoints and any kind of movements through underwater terrain 
(https://github.com/azerothcore/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4)
image

## How to Test the Changes:

1. Charge creatures between a underwater hill: creature <----> player (fixed)
2. Attack creatures between a underwater hill or terrain. (fixed)
3. Do stuff and interaction with creatures and player spells on water on ground (fixed)
4. Waypoints on underwater terrain (fixed)
5. Chase on underwater terrain (fixed)
6. RandomMovement generator clipping through underwater terrain (fixed)
6.  And more not known issues related, etc etc

## Known Issues and TODO List:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10119

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
i do look forward to the changes.
image

**Review by acidmanifesto — APPROVED** [review]
approved since u must of made the changes while i reviewing.

**Comment by acidmanifesto** [comment]
@Nyeriah can you or your team see if this changes will have any adverse regression or side effect?

**Comment by acidmanifesto** [comment]
Slightly updated the PR Title to match naming scheme for azerothcore.

**Comment by acidmanifesto** [comment]
So a video review that solved a issue i been noticing since before my inhabittype removal pr that still presisted after that pr.
For context. the Orcas in borean tundra (NW) had a issue with path finding or sorts and never pursued the player when combat engaged if you went lower or higher then them. This PR fixes that issues 100% as evidence of my video right provide.
https://youtu.be/FINuZ4g9dVc
However, since movement generator is sort of a world formula like thing where changing one thing on it would possible effect the movement of many other npcs, we will wait until our movement generator person @Yehonal has time to review it. As i may be a developer and staffer, anything dealing with the movement generators is out of league and out of my experience.
So just hang tight until the main person can check it out and provide his assessment as he is pretty slim on time at the moment, i however will request him to review this pr as well as the final say on the matter.

**Comment by WORISX** [comment]
> So a video review that solved a issue i been noticing since before my inhabittype removal pr that still presisted after that pr. For context. the Orcas in borean tundra (NW) had a issue with path finding or sorts and never pursued the player when combat engaged if you went lower or higher then them. This PR fixes that issues 100% as evidence of my video right provide. https://youtu.be/FINuZ4g9dVc However, since movement generator is sort of a world formula like thing where changing one thing on it would possible effect the movement of many other npcs, we will wait until our movement generator person @Yehonal has time to review it. As i may be a developer and staffer, anything dealing with the movement generators is out of league and out of my experience. So just hang tight until the main person can check it out and provide his assessment as he is pretty slim on time at the moment, i however will request him to review this pr as well as the final say on the matter.

It would be great that you point which out which issues are getting solved/fixed by my update, in this case the orcas issue that i think it was already reported.

**Comment by acidmanifesto** [comment]
> 

as much as i agree, there could be a slew of issues that could be fixed but to reaudit all of them to be particular to this pr would be a bit more time consuming then what i have available. however, we do try out best to follow up on issues as time goes on. wish you the best on this pr as i am pretty satisfied with it so far, but we will have to wait for the main guy on the matter.

**Comment by WORISX** [comment]
> > 
> 
> as much as i agree, there could be a slew of issues that could be fixed but to reaudit all of them to be particular to this pr would be a bit more time consuming then what i have available. however, we do try out best to follow up on issues as time goes on. wish you the best on this pr as i am pretty satisfied with it so far, but we will have to wait for the main guy on the matter.

Can you contact me by discord? Have some issues to tell you regarding your InhabitType removal
Cevallos#0246

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10276 Can you put him here?

**Comment by pklloveyou** [comment]
They are stuck on the water.
image

**Comment by pklloveyou** [comment]
Test failed 。The path is wrong
image

**Comment by pklloveyou** [comment]
but It fixed this
image

**Comment by WORISX** [comment]
> Test failed 。The path is wrong image

Not related to this PR, this only aims to fix described issue.

**Comment by pklloveyou** [comment]
@WORISX  But before PR, there is no such error

**Comment by pklloveyou** [comment]
I think we should merge it, The mistake of not being able to chase on the water should be another PR to fix it

**Review by acidmanifesto — APPROVED** [review]
Not entirely certain why my review was request again as i already approved. Lets not do another review request from me in the advent it does get approved by the other person, i may be unavailable to approve it for it to be merged when and if that happens.

**Comment by Kitzunu** [comment]
We can't wait and stall PR's for a review from an inactive man, tbh.

I am with pklloveyou. Push it, see the changes in action. If it gets worse we can just restore the old code.

maybe @Winfidonarleyan has anything to say about it. But otherwise I think we merge it as nobody is familiar enough with the movement system.

**Review by Kitzunu — APPROVED** [review]

**Comment by pklloveyou** [comment]
Only by merging it can we carry out the next work, otherwise this error will be ignored all the time.

**Comment by pklloveyou** [comment]
I think the next job is the error in the picture I sent above. I hope someone can test it after merging. The method is as follows:
```
1.
.go c  2187
Let the creature attack you

2.
.go -14738 396 -1.635787
```

**Pull request merged**
