### PR TITLE
feat(Core/Soap): Allow external usage

### PR DESCRIPTION
**Pull request by th3lolipop**
This will enable SOAP for Docker and External Usage.

## CHANGES PROPOSED:

-  SOAP enabling for external usage

## ISSUES ADDRESSED:
- Request

## TESTS PERFORMED:

I tested on my server and its works !!

OS : Ubuntu 18.04 
Tools: Docker

## HOW TO TEST THE CHANGES:

You will need to make some changes in your worldserver.conf 

```
#
#    SOAP.Enable
#        Description: Enable soap service
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

SOAP.Enabled = 1

#
#    SOAP.IP
#        Description: Bind SOAP service to IP/hostname
#        Default:     "127.0.0.1" - (Bind to localhost)

SOAP.IP = "0.0.0.0"

#
#    SOAP.Port
#        Description: TCP port to reach the SOAP service.
#        Default:     7878

SOAP.Port = 7878

```

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
As this is just about exposing a new port, there is no way this can break the current functionality. Plus you tested it locally and works for you.

I'd say no further test is needed and we can already merge it.

**Comment by th3lolipop** [comment]
> As this is just about exposing a new port, there is no way this can break the current functionality. Plus you tested it locally and works for you.
> 
> I'd say no further test is needed and we can already merge it.

Thanks @FrancescoBorzi

**Comment by Kitzunu** [comment]
For me that has never used Soap, what possibilities would this open up to be able to do with Soap?

**Comment by th3lolipop** [comment]
> For me that has never used Soap, what possibilities would this open up to be able to do with Soap?

If we allowed the SOAP for external usage , we can access **World Server** via the SOAP protocol.

### My Use Case
I need to access world server from website. 
3 Tier Setup ( Web , Auth/World, Database )

### Possibilities 
If we expose SOAP port for Worldwide ( 0.0.0.0 ) , that can be unexpected security risk !!
We may need to setup OS level firewall or Network level firewall.

**Comment by Kitzunu** [comment]
Verry cool :)

**Comment by Kitzunu** [comment]
Ty for the PR!

**Pull request merged**
