### PR TITLE
fix(DB/Text): creature_text cleanup

### PR DESCRIPTION
**Pull request by wdraenor**
## Changes Proposed:
-  Deletes 2 unnecessary rows of text that aren't used anywhere in the game, and was removed in patch 3.2.2 
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://wowpedia.fandom.com/wiki/Celebrating_Good_Times

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Is there a source that with 3.2.2 those that still had the head could no longer see this RP event? If there isn't, I disagree with this change wholeheartedly.

**Comment by wdraenor** [comment]
> Is there a source that with 3.2.2 those that still had the head could no longer see this RP event? If there isn't, I disagree with this change wholeheartedly.

I'm not sure of a source for that, I was able to add the prerequisite quest "Victory for the Alliance" to myself in-game with the head of Onyxia but I wasn't able to turn in the quest, using GM commands to give myself the "Celebrating Good Times" quest also wouldn't let me turn in the quest to Major Mattingly, so you're never able to see this text in-game.

**Comment by heyitsbench** [comment]
> I was able to add the prerequisite quest "Victory for the Alliance" to myself in-game with the head of Onyxia (given to me by GM commands) but I wasn't able to turn in the quest, using GM commands to give myself the "Celebrating Good Times" quest also wouldn't let me turn in the quest to Major Mattingly, so you're never able to see this text in-game.

To be honest, I would sooner call *that* the issue here.
 
> The prerequisite quest "Victory for the Alliance" was also removed in patch 3.2.2 [Wowpedia link]

I wouldn't trust a site like Wowpedia for that sort of thing, they tend to say the quest is removed just if it's inaccessible to new players. The quest technically still exists even in retail today.

I am of the opinion that these quests and their turn-ins should still exist in 3.3.5 if a player from an older patch happened to hold onto the items/quests, as Blizz does have a [bit of a track record with that sort of thing](https://github.com/azerothcore/azerothcore-wotlk/pull/12707). It's obviously not a great source given the circumstances, but the quests and their RP do still exist on Wrath Classic today despite the revised Ony raid also being released. Of course as you've noticed, there is no source proving or disproving this, and I would prefer the quests be corrected to have working turn-ins with base AC, but in the absence of evidence, I definitely don't think stripping out what used to exist is a good idea.

**Comment by wdraenor** [comment]
I see what you mean, you've raised some valid arguments which makes me think this is not a good change, so I will be closing this.

**Pull request closed without merging**
