### PR TITLE
fix(DB/Gameobject): Remove duplicate mining node.

### PR DESCRIPTION
**Pull request by ErnestoGonzalezC**
## Changes Proposed:
-  Remove duplicate mining node

## Issues Addressed:
- Closes 

- https://github.com/azerothcore/azerothcore-wotlk/issues/5513

## Tests Performed:

- ``.go o 35547``
- Verify that there is no duplicate node

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by Si1ker** [comment]
@ErnestoGonzalezC Don't delete content, if is already in the DB is for a reason, move it.

Any duplicate is seen as "duplicate" just because they are together, so the right fix is to move them away so we eliminate the "duplicate" behaviour (unless is a unique NPC/Gobject)

So please move them instead of deleting them. Take this note also for future references in case you encounter any duplicate.

**Comment by T1ti** [comment]
They weren't duplicate, they had a different ID
image
One is tein vein, the other is silver.

They just need to be pooled so they don't spawn at the same time

**Comment by FrancescoBorzi** [comment]
I agree, I've overlooked this one earlier

**Pull request closed without merging**
