### PR TITLE
fix(DB/BladesEdgeMountains): several SAI fixes for the mobs in the upper forge camps

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/6314
- Progress https://github.com/chromiecraft/chromiecraft/issues/6312
- Closes https://github.com/chromiecraft/chromiecraft/issues/6311
- Closes unreported issue where the spawned elite mobs didn't have a yell

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Timers and spells used from CManGOS creature_scripts cherry picks and yells from [here](https://wowpedia.fandom.com/wiki/Braxxus) after querying broadcast text for matches

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. go to the forge camp plateaus
2. summon the big guys with apexis shards and wait for Braxxus to appear to see his panic is no longer that frequent
3. see that the other mobs from the issues have some abilities added

## Known Issues and TODO List:

- [ ] check for fear on Fear Fiend (duh... they should have it) in wotlk classic sniffs, as it was not in CManGOS either.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Are you able to find the author from mangos for proper credits?

**Comment by elthehablo** [comment]
> Are you able to find the author from mangos for proper credits?

Don't think so. Gonna be hard to find db related commits I'd say. Can try to take a look

**Comment by Kitzunu** [comment]
oh okay thought you took it from a commit

**Comment by elthehablo** [comment]
> oh okay thought you took it from a commit

Yeah don't really know what to put as a source when I just grab it from a different project's db. Guess it's a cherry pick, just not a commit cherry pick

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
