### PR TITLE
fix(DB): Missing Ironforge Guard on Mountain

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Add missing Ironforge Guard on top of Mountain
-  Values from Vmangos
- Thank you Bench for notice this small fun details ^_^

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4027
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12943

## SOURCE:

Vmangos

## Tests Performed:

- Tested in game, guard is present and walks on mountain

## How to Test the Changes:

1. .go creature 190247
2. Check position and pathing is okay

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
https://youtu.be/e7MCOm1OxEs
This is what the path looks like in the Wrath pre-patch.

**Comment by Gultask** [comment]
Climbs the mountain like a Skyrim horse 👍 

Very slight clipping at one point but it's totally due to the awkward angles. Seems to be similar to Bench's video in the spots that he appears.

**Comment by heyitsbench** [comment]
> Seems to be similar to Bench's video in the spots that he appears.

Does the delay at the peak line up with the video? 30000 feels very long at a glance.

**Comment by Gultask** [comment]
Ah, you're right. In the video it appears more like a 1-2s pause instead. I only looked at the path.

**Comment by ZhengPeiRu21** [comment]
I have updated to reduce the wait time at the peak to 3 seconds, which seems closer to the video. If we are prefer then we can wait to merge until we have a sniff of waypoints to confirm all is exactly correct.

**Comment by heyitsbench** [comment]
> If we are prefer then we can wait to merge until we have a sniff of waypoints to confirm all is exactly correct.

I've already got a sniff of the guard's pathing. Once WPP fixes its delay parsing, we can correct the value to be exact, but as of right now, I'd say 3000 is good.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
