### PR TITLE
fix(core/cooking): improve position basic campfire

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

now basic campfire is summoned at the correct distance of 3 meters
https://www.wowhead.com/wotlk/spell=818/basic-campfire
## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. learn cooking
2. use basic campfire

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
What's to say this isn't a Classic change?

**Comment by grimgravy** [comment]
I didn't know it was a classic change. Has this already been done in Script?

**Comment by heyitsbench** [comment]
My questions are what was wrong with this spell before, how does this PR resolve it, and how do we know it was incorrect?

**Comment by grimgravy** [comment]
the basic bonfire is invoked practically at the character's feet, that's what's incorrect

**Comment by elthehablo** [comment]
The PR makes sense to me. But I do wonder what happens if you stand before a wall. I am unfamiliar with the specific target type

**Comment by grimgravy** [comment]
// notice that it doesn't work with radius
// front left, doesn't use radius
TARGET_DEST_CASTER_SUMMON

**Comment by grimgravy** [comment]
> Tested. [Current AC master](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/e64b44ba-86de-4001-b687-d5c5f197a5f5), [This PR](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/1dfcf1fd-602a-4a02-b1a8-678c47c1645d), [Wrath Classic PTR](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/a30d3096-1822-492b-8d59-65fb29a8fdaf).
> 
> While yes, it does seem this is much closer to the distance it should be, it's been rotated from the front-left of the caster to directly in front.
> 
> > But I do wonder what happens if you stand before a wall.
> 
> It finds the closest available point along the path it expects afaik. In this case, it'd place the fire directly at the caster's feet.

The difference between the images is the direction of the invocation. Scripted creation would probably be better

**Review by Kitzunu — CHANGES_REQUESTED** [review]
Please fix the remarks above. TARGET_DEST_CASTER_FRONT is not the way to go

**Comment by Kitzunu** [comment]
Closed as no response

**Pull request closed without merging**
