### PR TITLE
fix(Scripts/Spells): Death Knight Army of the Dead auras

### PR DESCRIPTION
**Pull request by sogladev**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

1. update spell dbc + script `67561 - Serverside - Pet Scaling - Master Spell 06 - Spell Hit, Expertise, Spell Penetration <---`
2. add script `49040 - Army of the Dead Passive <---`
3. refactor names `Death Knight Pet Scaling 01` and 02

copied some spelldbc values from DK Scaling 1

scaling script based on spell_sha_feral_spirit_scaling and spell_pet_hit_expertise_scalling

DBC Info:
ID - 49040 Army of the Dead Passive
not sure lines +-"Frost Presence" do 
```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 99 (SPELL_AURA_MOD_ATTACK_POWER), value = 0, misc = 1 (1), miscB = 0, periodic = 0
SpellClassMask = 00008000 00000000 00000000
	+ 48263 - Frost Presence
	- 61261 - Frost Presence
```

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3217
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18217

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

wowsims scaling stamina 20% AP 6.5%
https://github.com/wowsims/wotlk/blob/870a2e1c040d5f7368561753f55d0662a236e57e/sim/deathknight/ghoul_pet.go#L213

### ravenous dead talent

comment 5 originally from thottbot
> "they don't benefit from the ravenous dead talent" https://www.mmo-champion.com/threads/701170-Army-of-Dead-s-actual-damage

no benefit from "Glyph of the Ghoul" https://wowgaming.altervista.org/aowow/?spell=58721

no scaling spell modifies stamina or strength. health/damage is scaled with bonus health and bonus damage from ap

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

ingame: expertise 1.50% 51 rating, 3.35% hit 110 rating, +100 spell penetration, 15571 hp

DK_auras

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ] hit and spellhit from 61697 (`ID - 61697 Death Knight Pet Scaling 03`) is 0. It is used by other DK pets. Gargoyle gets hit by an incorrect hunter aura. AOTD gets spellhit by 67561 - Serverside - Pet Scaling - Master Spell 06 - Spell Hit. It should? receive double spellhit with fixed 61697
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Any idea what's up with Periodic Taunt (43264)?

**Comment by sogladev** [comment]
> Any idea what's up with Periodic Taunt (43264)?

From DBC

```
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 23 (SPELL_AURA_PERIODIC_TRIGGER_SPELL), value = 1, misc = 0 (0), miscB = 0, periodic = 1000
   Trigger spell (43263) Ghoul Taunt. Chance = 101
   Description: Taunts and causes additional high threat to all enemies within $a1 yards.
```

It's an aura applied by `creature_template_addon` to Army of the Dead Ghoul (24207).

Should probably delete the entry and move it to script

**Comment by heyitsbench** [comment]
To clarify, my concern mostly stems from not seeing that aura on an army ghoul in a sniff.

**Comment by sogladev** [comment]
> To clarify, my concern mostly stems from not seeing that aura on an army ghoul in a sniff.

From what I know, in 335 this taunt effect is always active. In [5.x a glyph](https://wowpedia.fandom.com/wiki/Glyph_of_Army_of_the_Dead) was added to disable this taunt. My guess is that not every ghoul needs to have this aura active. 

Maybe every x ghoul has this aura applied?

**Comment by sudlud** [comment]
what's the state of this PR?

**Comment by sogladev** [comment]
missing info 43264 Periodic Taunt, it's not supposed to be always active?

Could use an opinion, should it be removed from creature_template_addon and added conditionally somewhere

https://github.com/azerothcore/azerothcore-wotlk/blob/529e9140323edeef916bd6a1b6c97e13aa38db08/src/server/game/Entities/Pet/Pet.cpp#L1369

logic here, rand %, every n. Maybe it's only applied if the ghoul enters combat?

**Comment by Grimdhex** [comment]
My suggestion is simple. update your PR to be merged and we will another issue to investigate if we should let or not 43264 Periodic Taunt.

**Review by Grimdhex — APPROVED** [review]

**Pull request merged**
