### PR TITLE
warlock pet base damage and stat fix

### PR DESCRIPTION
**Pull request by PolarCookie**
Stock trinity / sunwell issue, the base damage and stats on warlock pets are wrong.
See TrinityCore/TrinityCore#19409 for details

### CODE REVIEW

**Comment by HeartWell** [comment]
You add  table min_dmg, max_dmg in creature_template, and update min_dmg, max_dmg for pet_levelstats wtf?

**Comment by PolarCookie** [comment]
yep, treating damage the same as base stats, armor, hp and mana, all being level determined values. The current functions calculating damage are horribly wrong for all pets, especially in the 60-80 level range.
I originally tried changing the damage functions to use interpolation and pow(), but this table solution is much closer to retail values.

**Comment by HeartWell** [comment]
Oh, i stupid. Good PR. Wait who any testing this.

**Comment by ShinDarth** [comment]
please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files#how-to-create-an-sql-update-file

thanks for your contribution

**Comment by ShinDarth** [comment]
@HeartWell did you test it?

**Comment by HeartWell** [comment]
Oh sorry, yes i test and good work)

**Comment by ShinDarth** [comment]
ok you can merge, thanks!

**Comment by Yehonal** [comment]
@HeartWell @ShinDarth please remember to run the db_pendings script when a PR includes sql files

otherwise people will have errors on startup

**Comment by ShinDarth** [comment]
yes I always do it :)

**Pull request merged**
