### PR TITLE
fix(DB/gameobject, pool): overhaul Durotar chests

### PR DESCRIPTION
**Pull request by neifion-00000000**
## Changes Proposed:
-  Removes and overhauls Durotar chests

## SOURCE:

Sniffed data
## Tests Performed:

- Checked to see if pooling worked, seems fine 

## How to Test the Changes:

1.  .go ga 47713 and up all the way threw the chests, 1 should spawn per pool as noted in the SQL

## Known Issues and TODO List:

- I somehow lost a chest (I swear it's sniffed but sniffs were being weird around the time I did this, months ago, according to the creation date of the image I made for it in Janurary-Feb) but I'm not going back for it \_o_/

Speaking of images, have the whole thing, Ore coming soon (TM)
Durotar Ore

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
DB Errors

**Comment by neifion-00000000** [comment]
100/5 != 25 whoops, fixed

**Comment by neifion-00000000** [comment]
> > 100/5 != 25 whoops, fixed
> 
> is this PR good to go?

yeah no other typos I could see and definitely and no critical ones <_<

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
