### PR TITLE
fix(DB/Creature): Root Ironhand Guardian

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  adds CTM
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13758
- Closes https://github.com/chromiecraft/chromiecraft/issues/3865

## Tests Performed:

- Tested a bit but I couldn't reproduce it in the first place 🤷 
- 

## How to Test the Changes:

1. .learn 688
2. `.go c id 9938` Go straight to the gates to last boss room. Then kite the boss to the gates at the start
3. Repeat until golem starts attacking imp

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Keep in mind that they may not follow pets anymore but they may still combat bug then. Does the immune_to_npc unitflag not work?

**Comment by Gultask** [comment]
Oh good point. I tried Immune to PC & NPC first but that made the damage from their Flamethrower spell do no damage. I'll try it properly once I get back home.

**Review by temperrr — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Status?

**Comment by Gultask** [comment]
Couldn't reproduce to test, either before or after the fix. But it does happen occasionally in Live server.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
