### PR TITLE
fix(Core/Creature): Implement INHABIT_ROOT

### PR DESCRIPTION
**Pull request by Kitzunu**
https://github.com/TrinityCore/TrinityCore/commit/f78ab9aba45e3b4189a71bb68de6d5b13f45bbca
That this never was implemented, wtf

## Changes Proposed:
-  Implement INHABIT_ROOT  

## Tests Performed:
- Builds
- Tested in-game

## How to Test the Changes:

1. use a new caster char with stave, level one
2. .mod hp 999999999
3. .go c id 30273
4. Hit, Miss and walk away. The NPC should not follow you.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Comment by Si1ker** [comment]
and I confirm the bug was there...  🤣   ( I'm running away.. )

image

**Comment by pklloveyou** [comment]
image

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @Kitzunu , can you please update Keira3 as well?

https://github.com/azerothcore/Keira3/issues/1027

**Comment by Rushor** [comment]
on tc we have creature_template_movement for all that, maybe that should ported aswell

**Comment by Kitzunu** [comment]
Yep I know, that is a project for another day.

Btw @Rushor I am back on the server O.O

**Pull request merged**
