### PR TITLE
fix(Core/Spell): "Taming the Beast" hunter quests, part 2

### PR DESCRIPTION
**Pull request by Stoabrogga**
Co-authored-by: Mitradis <mitradis@gmail.com>

##### CHANGES PROPOSED:
After dismissing the creatures during quest "Taming the Beast" they should vanish instead of playing the death animation.

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
see #2243

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Mitradis** [comment]
it works fine.
https://ibb.co/kmX0Lyv
https://ibb.co/X3Nfs6w
https://ibb.co/V9cjrhF
https://ibb.co/x6PS3LX
https://ibb.co/Z2WBLtK
https://ibb.co/RNMVHtD
https://ibb.co/Mcdsq51
https://ibb.co/Qvd8mtD
https://ibb.co/D1zv0DK
https://ibb.co/wh7zSgb
https://ibb.co/5rQ2DHd
https://ibb.co/VxSYJrT
https://ibb.co/HqBnv7n
https://ibb.co/9pRFHm1
https://ibb.co/YjvHh1Z
https://ibb.co/zQKGHYw
https://ibb.co/MVR0zq6
https://ibb.co/K6f5wnN
https://ibb.co/LdyS303
https://ibb.co/HzKNNCw
https://ibb.co/0Y4PwbK
https://ibb.co/1T3jp2b
https://ibb.co/KhC0sCN
https://ibb.co/H7bdvdf
https://ibb.co/W6cGStB
https://ibb.co/QYqCzs0
https://ibb.co/NZBfHXq
https://ibb.co/b67wJWH
https://ibb.co/SxGxXqp
https://ibb.co/mXPcH3B
BE i I tested yesterday

**Comment by Stoabrogga** [comment]
Great, thanks!

**Comment by wowmane** [comment]
Worked.

**Comment by Stoabrogga** [comment]
Merged as it should have been part of PR #2243 and is just a minor change.

**Pull request merged**
