### PR TITLE
Fix -Update src/server/game/Movement/Spline/MoveSpline.cpp

### LINKED ISSUE #1063: Assertion Failed Movespline.cpp
**Description:**
Dunno why, For the first time I see this error/crash.  (Movespline.cpp Assertion Failed)
I'll include crash log.

**Current behaviour:** Tell us what happens
The server just crashed after 8 days.

**Reference**
Screenshot of error: https://prnt.sc/l9tggt
Crash Log: [1d5407a9d929+_worldserver.exe_[24-10_4-27-3].txt ](https://gist.github.com/poszer/b2520777cb3e887a11105f90c3ec3056)

**Branch(es):** 0.x / 1.x / master (Specify the branch(es) affected by this issue)
Master

**Operating system:**
Win Server 2012 R2 x64

**Modules:** Are you using modules? if yes, list them
Transmog, BossAnnouncer, DuelReset, Buffer, BeastMaster.

### PR DESCRIPTION
**Pull request by poszer**
CHANGES PROPOSED:
Fix Assertion Failed Movespline.cpp
ISSUES ADDRESSED:
Closes #1063  https://github.com/azerothcore/azerothcore-wotlk/issues/552

TESTS PERFORMED:
HOW TO TEST THE CHANGES:
Tested in game, for 7 days without error

Operating system:
Win Server 2012 R2 x64

KNOWN ISSUES AND TODO LIST:
Target branch(es):
Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
The idea came from @grimgravy

**Comment by grimgravy** [comment]
thanks for the support @BarbzYHOOL

**Comment by poszer** [comment]
> 
> 
> thanks for the support @BarbzYHOOL

Ok, have to try another way. The problem has appear again -.-

**Comment by BarbzYHOOL** [comment]
ok, however knindza said he had an issue with velocity error in the console, this looks related

**Comment by grimgravy** [comment]
try this option "CHECK(velocity > 0.f);"

**Comment by BarbzYHOOL** [comment]
This is the hackfix from https://github.com/azerothcore/azerothcore-wotlk/issues/552

**Comment by Knindzagxg** [comment]
I don't have it since we made reverse.

**Comment by FrancescoBorzi** [comment]
what is the status of this?

**Comment by poszer** [comment]
With these (fixes) my server is running more than months without this spline crash errors. So i can confirm, atleast on Win OS, that this has solved anoying issue which was crashing server every day 🤣 Better to leave it open, and wait until someone apply these commits, and confirm it

**Comment by FrancescoBorzi** [comment]
@wetbrownsauce :1st_place_medal:

**Comment by wetbrownsauce** [comment]
I'm not entirely sure how I could confirm this aside from adding it to my server and waiting to see. I've never had the related crash happen so even if it works I wouldn't see a difference :/ 

Regardless, I'll merge it into my server.

**Comment by BarbzYHOOL** [comment]
Yes, I think we can let it open and if someone complains about this issue, refer to this PR and wait for his input

**Comment by FrancescoBorzi** [comment]
@wetbrownsauce I guess that would be enough, since @poszer has already being testing it for a while.

Good job guys.

**Comment by FrancescoBorzi** [comment]
@xgap have you tested this?

**Comment by Xgap** [comment]
> @Xgap have you tested this?

yeap

**Comment by BarbzYHOOL** [comment]
@Xgap and you had that bug previously??

**Comment by BarbzYHOOL** [comment]
no he didn't xD

**Comment by Xgap** [comment]
I was getting the same error. I haven't received an error since I edited.

**Comment by poszer** [comment]
> I was getting the same error. I haven't received an error since I edited. (win server os)

Good than, thanks

**Comment by Nefertumm** [comment]
Due it was already tested and marked as functional, i'm merging. Thank you all for the work!

**Pull request merged**
