### PR TITLE
fix(DB/lang): TBC Heroic Dungeon Keys German Description

### PR DESCRIPTION
**Pull request by LukasVolgger**
Change the keys description ''Heroisch'' which which incorrectly had two single quotes instead of just one.

2020-03-25 22_14_35-World of Warcraft
to
2020-03-25 22_15_38-World of Warcraft

## CHANGES PROPOSED:
-  Update item description for deDE Client

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Imported SQL script on Win 10 pro x64 with Heidi SQL v11
- Tested succesfully ingame 

## HOW TO TEST THE CHANGES:

To test changes ingame you need deDE client. It is sufficient to just test the SQL.

- Import SQL file and check that no error occurs
- Can be merged after approval

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Si1ker** [comment]
Imported and reviewed in deDE client, ready 🚀  !

**Comment by LukasVolgger** [comment]
Thx @Si1ker !

**Comment by Remberance** [comment]
```sql
INSERT INTO `item_template_locale` VALUES (9299,'zhCN','瑟玛普拉格的保险箱密码','',18019),(2719,'zhCN','小小的黄铜钥匙','',18019), (3930,'zhCN','玛雷的钥匙','',18019), (21691,'zhCN','沾满软泥的护手','',18019), (13704,'zhCN','骷髅钥匙','',18019), (30623,'zhCN','水库钥匙','允许你进入英雄难度的盘牙水库地下城。',18019), (30622,'zhCN','焰铸钥匙','允许你进入英雄难度的地狱火堡垒地下城。',18019), (30635,'zhCN','时光之钥','允许你进入英雄难度的时光之穴地下城。',18019), (30633,'zhCN','暗影迷宫钥匙','允许你进入英雄难度的奥金顿地下城。',18019), (30637,'zhCN','焰铸钥匙','允许你进入英雄难度的地狱火堡垒地下城。',18019), (45796,'zhCN','天文台钥匙','',18019), (44582,'zhCN','聚焦之虹钥匙','',18019), (44581,'zhCN','英雄：聚焦之虹钥匙','',18019), (42482,'zhCN','紫罗兰监狱钥匙','',18019), (31704,'zhCN','风暴钥匙','一种水晶钥匙，似乎被光束缚在一起。',18019), (30634,'zhCN','扭曲锻造钥匙','允许你进入英雄难度的风暴要塞地下城。',18019), (24490,'zhCN','麦迪文的钥匙','',18019), (21762,'zhCN','大型圣甲虫箱的钥匙','',18019), (21761,'zhCN','圣甲虫箱的钥匙','',18019), (18268,'zhCN','戈多克内门钥匙','',18019), (18266,'zhCN','戈多克庭院钥匙','',18019), (11000,'zhCN','暗炉钥匙','通往黑石深渊的钥匙……',18019), (5396,'zhCN','通往灼热峡谷的大门钥匙','',18019);
```
this is some simplified Chinese key's description.

**Comment by LukasVolgger** [comment]
@Remberance 
these are completely different items than they have to do with this PR. I have looked at the entries and so far there is no locale zhCN in our DB.

If you wan't me to import some locales just give me the source and i'll take a look at it. 

Btw if we `INSERT` in our DB don't forget to `DELETE` the records in first point so we can re-run the script.

**Pull request merged**
