### PR TITLE
fix(Core/Creature): Set PvP flag for some creatures

### PR DESCRIPTION
**Pull request by lineagedr**
## Changes Proposed:
-  Properly setpvp for these creatures.
-  

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4261

## Tests Performed:
- https://i.imgur.com/4a46MYJ_d.webp?maxwidth=760&fidelity=grand
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by lineagedr** [comment]
@Kitzunu Out of the 6 creatures only 1 is from the azuremyst isle.

**Comment by Voxstrasza** [comment]
I can't test this right now because I'm at work (lol NA) but I will say to anyone that tests this before me, please make sure that when you heal them for the quest the quest completes properly and the NPCs reset properly.  Also test the Draenei/Blood Elf priest quest for their respective NPCs.

**Comment by Voxstrasza** [comment]
ok, got it tested, compiled etc - here are my test results for all starter zone NPCs that require to be healed and/or buffed by the player:

**Draenei Survivor** (NPC ID 16483)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Rescue the Survivors (ID 9283) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?: **Yes**
Does the NPC reset after quest completion?: **Yes**
Notes:  None, this is fine!

**Tavara** (NPC ID 17551)
Is the NPC PvP flagged (green portrait)?: **No**
Can quest Help Tavara (ID 9586) be completed?: **No**
Can opposite faction players attack and kill this NPC?: **Yes**
Does the NPC reset after quest completion?: **Unknown**
Notes:  This NPC spawns with 100% HP despite being the objective of a "heal this person!" quest - needs to be fixed, maybe separate issue

**Eversong Rangers** (NPC ID 15938)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Cleansing the Scar (ID 9489) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?: **Yes**
Does the NPC reset after quest completion?: **Unknown**
Notes:  I don't think these NPCs are scripted (separate issue), I believe they're supposed to be in-combat with scourge mobs in this area - will do some investigating.

**Sentinel Shaya** (NPC ID 12429)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Garments of the Moon (ID 5621) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?:  **Yes**
Does the NPC reset after quest completion?:  **Yes**
Notes:  Must use Lesser Heal (Rank 2) and Power Word: Fortitude Rank 1 (in that order) or it won't work properly.  Quest text specifically outlines that order though, so not an issue.

**Guard Thomas** (NPC ID 12423)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Garments of the Light (ID 5624) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?:  **Yes**
Does the NPC reset after quest completion?: **Yes**
Notes:  Must use Lesser Heal (Rank 2) and Power Word: Fortitude Rank 1 (in that order) or it won't work properly.  Quest text specifically outlines that order though, so not an issue.

**Mountaineer Dolf** (NPC ID 12427)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Garments of the Light (ID 5625) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?:  **Yes**
Does the NPC reset after quest completion?: **Yes**
Notes:  Must use Lesser Heal (Rank 2) and Power Word: Fortitude Rank 1 (in that order) or it won't work properly.  Quest text specifically outlines that order though, so not an issue.

**Grunt Kor'ja** (NPC ID 12430)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Garments of Spirituality (ID 5648) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?:  **Yes**
Does the NPC reset after quest completion?: **Yes**
Notes:  Must use Lesser Heal (Rank 2) and Power Word: Fortitude Rank 1 (in that order) or it won't work properly.  Quest text specifically outlines that order though, so not an issue.

**Deathguard Kel** (NPC ID 12428)
Is the NPC PvP flagged (green portrait)?: **Yes**
Can quest Garments of Darkness (ID 5650) be completed?: **Yes**
Can opposite faction players attack and kill this NPC?:  **Yes**
Does the NPC reset after quest completion?: **Yes**
Notes:  Must use Lesser Heal (Rank 2) and Power Word: Fortitude Rank 1 (in that order) or it won't work properly.  Quest text specifically outlines that order though, so not an issue.

This PR fixes most of the issues.  I have a stupid idea that might work for Tavara, I'll post it once I'm complete to add it to your PR @lineagedr

**Comment by lineagedr** [comment]
@Voxstrasza Tavara and the rangers are scripted with SAI. 

Tavara quest works you just have to use:

```sql
59544; -- Gift of the Naaru - Priest
2050; -- Lesser Heal R1
2052; -- Lesser Heal R2
139; -- Renew R1 (they don't have R2 yet)
```

Anyway setting her faction to 1639 will fix her.

tavara

**Comment by Voxstrasza** [comment]
That fixed it, although we should figure a way to bring her health to 70-80% and have her reset once the quest is complete.  Not sure if this will help you, but DalaranWoW had a fix that did this:

```
UPDATE `creature` SET `curhealth` = 81 WHERE `guid` = 63161; 
-- Tavara SAI
SET @ENTRY := 17551;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,53,0,100,1,9,200000,10000,10000,80,@ENTRY*100+00,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Received Heal Between 9-200000 - Run Script (No Repeat)"),
(@ENTRY,0,1,0,53,0,100,1,9,200000,10000,10000,80,@ENTRY*100+01,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Received Heal Between 9-200000 - Run Script (No Repeat)"),
(@ENTRY,0,2,0,53,0,100,1,9,200000,10000,10000,80,@ENTRY*100+01,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Received Heal Between 9-200000 - Run Script (No Repeat)");

-- Actionlist SAI
SET @ENTRY := 1755100;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,48,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Set Active On"),
(@ENTRY,9,1,0,0,0,100,0,0,0,0,0,91,8,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Remove Flag Standstate Kneel"),
(@ENTRY,9,2,0,0,0,100,0,0,0,0,0,64,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Tavara - On Script - Store Targetlist"),
(@ENTRY,9,3,0,0,0,100,0,3500,3500,0,0,66,0,0,0,0,0,0,12,0,0,0,0,0,0,0,"Tavara - On Script - Set Orientation <unsupported target type>"),
(@ENTRY,9,4,0,0,0,100,0,100,100,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Say Line 0"),
(@ENTRY,9,5,0,0,0,100,0,3000,3000,0,0,33,17551,0,0,0,0,0,12,0,0,0,0,0,0,0,"Tavara - On Script - Quest Credit ''"),
(@ENTRY,9,6,0,0,0,100,0,3000,3000,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Evade"),
(@ENTRY,9,7,0,0,0,100,0,0,0,0,0,48,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Set Active Off");

-- Actionlist SAI
SET @ENTRY := 1755101;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,48,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Set Active On"),
(@ENTRY,9,1,0,0,0,100,0,10000,10000,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Evade"),
(@ENTRY,9,2,0,0,0,100,0,0,0,0,0,48,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Tavara - On Script - Set Active Off");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceEntry`=17551;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(22, 1, 17551, 0, 0, 9, 0, 9586, 0, 0, 0, 0, 0, '', 'Player with quest 9586'),
(22, 2, 17551, 0, 0, 14, 0, 9586, 0, 0, 0, 0, 0, '', 'Player without quest 9586'),
(22, 3, 17551, 0, 0, 28, 0, 9586, 0, 0, 0, 0, 0, '', 'Player with completed quest 9586');

-- Add texts
DELETE FROM `creature_text` WHERE `entry` = 17551; 
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(17551,0,0,'%s thank $n.',16,0,100,2,0,0,0,0,'');
```

**Comment by lineagedr** [comment]
@Voxstrasza Seems like a separate issue.

**Comment by Voxstrasza** [comment]
> 
> 
> @Voxstrasza Seems like a separate issue.

Fair.  PR all good then!

**Pull request merged**
