### PR TITLE
fix(Core/BG) Moved AddObject AV doors after their spawn, closes #2453

### LINKED ISSUE #2453: BG Alterac Valley (low lvl) bosses die.
Bosses from both side die every second and respawn (loop). On Alterac Valley before 80lvl version.
And additional: no main gate if clear game cache and go on Alterac Valley.

##### STEPS TO REPRODUCE THE PROBLEM:
1. creat character, ".level 50" and ".debug bg" go Alterac Valley.
2. go to bosses room.

modules:
Eluna-master.zip
mod-1v1-arena-master.zip
mod-ah-bot-master.zip
mod-autobalance-master.zip
mod-duel-reset-master.zip
mod-eluna-lua-engine-master.zip
mod-instance-reset-master.zip
mod-npc-talent-template-master.zip
mod-random-enchants-master.zip
mod-transmog-master.zip

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83966439-bg-alterac-valley-low-lvl-bosses-die?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Helias**
##### CHANGES PROPOSED:
-  Moved AddObject AV doors after their spawn.
- Added the spawn of the object in `StartingEventCloseDoors()` function

##### ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2453

##### TESTS PERFORMED:
**Before PR:**
if I join AV for the first time and I can't see the gate, if I open another client with a second account and join AV (same faction) I can see the gate and I can see that the first player can pass through the gate because he can't see them.

**After PR:**
The problem don't persist, I can see the gate at the first join.

##### HOW TO TEST THE CHANGES:
- start your worldserver
- delete Cache, open Wow.exe
- join AV, check if you can see the gate

**Before the PR:** you will not see the gate, but the gate is spawned, if you use another account you will see it.
**After the PR:** you will see the gate at the first join.

##### Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Mitradis** [comment]
work for me

**Comment by Mitradis** [comment]
once work, after shutdown and clear cache not work

**Comment by Mitradis** [comment]
yes it is work)

**Comment by Helias** [comment]
I think that it's partially work, I'm testing it several times, unfortunately I got the bug again.

**Comment by Helias** [comment]
Try now @Mitradis.

Anyway to put this PR "To Be Merged" I want that at least another one (or maybe 2?) test this PR, it's a bit hard to test.

**Comment by Mitradis** [comment]
work, i am 3 times full restart server with clear game cache and unpack clear database.

**Comment by LichKing255** [comment]
Working.

**Pull request merged**
