### PR TITLE
fix(Core/Script) - Black Temple - Gurtogg Bloodboil - Bewildering Strike mechanics doesnt work as it should

### PR DESCRIPTION
**Pull request by Carriola-wotlk**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/20059
- Closes https://github.com/chromiecraft/chromiecraft/issues/7384#issue-2553196527

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Rorschach91** [comment]
I tested the PR and it works.
@Nyeriah could you check the script, please?

**Comment by Nyeriah** [comment]
The script looks fine although I'm not sure if it is correct, as in, I am not sure if there is actually a threat drop or he just ignores confused targets as most creatures should do (but currently don't). If we can't get that confirmation then I will merge it

**Comment by Rorschach91** [comment]
As I saw, with this script the boss works as it should. 
If the boss use Bewildering Strike It stop to attack the main tank and it attacks the second in aggro.
When Bewildering Strike effect vanish, if the second in threat has become the first, the boss continues to attack the new first in threat, otherwise it return to attack the previous target.

From a mechanics PoV this script allows the boss to do what it should do. 
I've nothing more to say, sorry.

**Comment by heyitsbench** [comment]
Threat drop mechanics have been tricky in the past, being sure of the way it's supposed to work doesn't hurt.

**Comment by Rorschach91** [comment]
> Threat drop mechanics have been tricky in the past, being sure of the way it's supposed to work doesn't hurt.

I agree.

**Comment by Carriola-wotlk** [comment]
Okay, I watched a video and the blizzlike behavior doesn't reset the tank's threat, but ignores him for the duration of the disorient. I'll try to adjust the code a bit (even though the final behavior is the same)

**Comment by Rorschach91** [comment]
Tested again. It works.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
