### PR TITLE
fix(DB/Loot): fix gold drops of ethereal mobs in Bash'ir Landing

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
-  change mingold to 448
-  change maxgold to 2520

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15850

## SOURCE:

- research drive link: https://docs.google.com/spreadsheets/d/11Wz9RS0uYH0EgtwnwHcztyzy_zZz-A0F2KYaDYSwx9U/edit?usp=sharing

## Tests Performed:

- 
- 

## How to Test the Changes:

1. `.tele bashirlanding`
2. kill mobs
3. test whether loot is closer to tbc classic/wotlk classic values now

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
cc @Gultask @neifion-00000000

**Comment by Gultask** [comment]
Seems to line up with sniffs

**Comment by Gultask** [comment]
image

**Comment by elthehablo** [comment]
> image

Cool. Yeah it is quite possible that there are still outliers. But this was as much as I could do without a retail account. I will add the ones from your table to mine tho

**Pull request merged**
