### PR TITLE
fix(Core/SmartScripts): Fixed SMART_TARGET_CREATURE_GUID and SMART_TA…

### LINKED ISSUE #5780: Quest#1249 "Missing Diplomat" failure causes NPC Mikhail to lock up
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [x] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Upon failure of quest [1249,](https://wowgaming.altervista.org/aowow/?quest=1249) NPC 9432 Mikhail will no longer interact with any player until server reset. Even if the failed quest is abandoned. He is both a quest ending point for quest 1248, and quest giver for quest 1249.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

From my understanding, failed quests should be able to be abandoned and reaccepted once the event has reset. The NPC should still be able to have quests turned in, and offer the event quest once the event has been reset.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .quest add 1248
2. .go creature 9432
3. Turn in and accept the chain quest (1249)
4. Fail it miserably
5. Abandon the quest and try to reaccept 
6. Repeat steps 1 and 2 on another character and attempt step 3

##### EXTRA NOTES:

Original report from Chromiecraft 
[https://github.com/chromiecraft/chromiecraft/issues/599](https://github.com/chromiecraft/chromiecraft/issues/599)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98393267-quest-1249-missing-diplomat-failure-causes-npc-mikhail-to-lock-up?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…RGET_GAMEOBJECT_GUID with `getFromHashMap` parameter.

Fixed #5780

## Changes Proposed:
-  After ObjectGuid port, parameter `getFromHashMap` is useless now. Corrected code.

## Issues Addressed:

- Closes #5780

## Tests Performed:

- Not tested.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
build fails :(

```
[ 25%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_account.cpp.o
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/AI/SmartScripts/SmartScript.cpp: In member function ‘ObjectList* SmartScript::GetTargets(const SmartScriptHolder&, Unit*)’:
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/AI/SmartScripts/SmartScript.cpp:3642:29: error: redeclaration of ‘GameObject* target’
 3642 |                 GameObject* target = FindGameObjectNear(scriptTrigger ? scriptTrigger : GetBaseObject(), e.target.goGUID.dbGuid);
      |                             ^~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:300: src/server/game/CMakeFiles/game.dir/AI/SmartScripts/SmartScript.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by UltraNix** [comment]
Fixed

**Comment by anguaive** [comment]
Works, tested the `Missing Diplomat` and `The Scarlet Oracle, Demetria` scripts in-game.

**Comment by anguaive** [comment]
May I propose renaming `FindCreatureNear` and `FindGameObjectNear` to `FindCreature` and `FindGameObject`, respectively? They don't actually check for visibility since f4c2264 (I assume they're not supposed to anymore).

**Pull request merged**
