### PR TITLE
fix(Maps/MeshExtractor): build on windows

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
* Add missing includes

* Remove duplicate struct from utils

* Remove faulty ASSERT and use already defined.

* Comment out code that has no counterpart

- I mean it cant break it anymore than it already is as wait() and activate() doesn't exist. So this just fixes the build, I don't know if it works.

But presumably it's working the same as it did before.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3329

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by Kitzunu** [comment]
The status of this is "what should activate() and wait() do?", they don't exist

**Comment by Viste** [comment]
> The status of this is "what should activate() and wait() do?", they don't exist

for what you need this meshext?

**Comment by patou01** [comment]
My guess based on a quick look at the [history](https://github.com/azerothcore/azerothcore-wotlk/commits/master/src/tools/mesh_extractor/ContinentBuilder.cpp) is that it's a call to a removed mother class.
If you look at the [first commit](https://github.com/azerothcore/azerothcore-wotlk/blob/e8e94a0a663be0a1cefe704d8c6860a526b2d7e9/src/tools/mesh_extractor/ContinentBuilder.cpp), you can see `class BuilderThread : public ACE_Task_Base`
Up until this [commit ](https://github.com/azerothcore/azerothcore-wotlk/blob/b9d14372fd1139423d9be8d2952f2249f93c8d83/src/tools/mesh_extractor/ContinentBuilder.cpp )by Francesco it's there.
And then with a [refactor to remove ACE](https://github.com/azerothcore/azerothcore-wotlk/blob/4dd9b92759ad7e2a7e8e4ffce83cb4d90b8afa0c/src/tools/mesh_extractor/ContinentBuilder.cpp): `class BuilderThread`.

If I checkout the commit before "remove ACE from tools" I find:
image
image

Apologies for the white background, haven't fixed np++ yet.
Content of the 2 functions is here in case you don't want to checkout the old commit: https://pastebin.com/4c79hfbQ 



Does this help in any way?

**Comment by Kitzunu** [comment]
Ah yea, ACE is removed

**Comment by Kitzunu** [comment]
@Winfidonarleyan could you take a look?

**Comment by Viste** [comment]
i still don't understand what you want to extract with this mesh extractor

**Comment by Winfidonarleyan** [comment]
> i still don't understand what you want to extract with this mesh extractor

Agree

**Pull request closed without merging**
