### PR TITLE
tools improvement

### LINKED ISSUE #923: NPCs falling through the ground
**Description**:
Sometimes NPCs fall through the ground while attacking.

**Current behaviour**:
When attacking NPCs which are moving over a hill, they sometimes fall through the ground and attack you from below.

**Expected behaviour**:
The NPCs should just run/walk normally above the ground.

**Steps to reproduce the problem**:
Example:
Teleport to the following location:
`.go xyz -3067.45 -4308.53 0.300854 1`
Attack the Defias Rummager on the other side of the small hill and pull him on top of the hill. He will fall through the ground.

I don't know if it is related, but sometimes NPCs with waypoint or random movement "float" or "hop" to their destination when running up or down a hill.

**Branch(es)**: master

**AC hash/commit**: https://github.com/azerothcore/azerothcore-wotlk/commit/8481eec5beac5a2e65052f95a6ff6aa22c5db981

**Operating system**: Ubuntu 16.04

**Modules**:
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster
https://github.com/azerothcore/mod-vas-autobalance

**Other Customizations**: none

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59528933-npcs-falling-through-the-ground?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
**Changes proposed:**
Taken over the essential changes from the following Trinitycore commits:
Improve vmaps:
https://github.com/TrinityCore/TrinityCore/commit/c35793941b3aae9b54dce92389aa528d40050754
https://github.com/TrinityCore/TrinityCore/commit/89d641f1e68d11359a2398ff51d3d6eee1470ae8

Improve mmaps:
https://github.com/TrinityCore/TrinityCore/commit/f8fd0b7a2c0a9acd084f011c614d529e49397479
https://github.com/TrinityCore/TrinityCore/commit/7ef22e43057080926685eb45f0fce3f2f3d58c61

**Target branch(es):**
master

**Issues addressed:**
Closes #923 

**Tests performed:**
tested build and a few tests in-game

**How to test the changes:**
Look for NPCs with pathing issues (falling through the ground, floating or hopping to it's destination etc.). The issue #923 contains one such example. After using the newly extracted data those issues should not occur anymore.

**Known issues and TODO list:**

### CODE REVIEW

**Comment by Nefertumm** [comment]
Probably this will fix #862 too

**Comment by Nefertumm** [comment]
This would need to re-extract all the mmaps and vmaps.

**Comment by FALL1N1** [comment]
better split the commits, one for lib updates e.g recast and detour then another for the extractor updates
you also forgot to bump the mmap/vmap magic

**Comment by Stoabrogga** [comment]
I took over only the logic and the recastnavigation update. Is the mmap/vmap magic of any importance? I thought it is just some kind of version tracking TC does.

**Comment by BarbzYHOOL** [comment]
"better split the commits, one for lib updates e.g recast and detour then another for the extractor updates"

But we squash the commits when there are too many. Or you mean multiple PRs?

**Comment by FALL1N1** [comment]
multiple PR's so if something breaks you don't have to revert entire 'encyclopedia' of code

**Comment by Stoabrogga** [comment]
Well, it isn't that much. TC changed just a little bit of logic in the vmaps and mmaps generation and updated the recastnavigation for better height calculation. Also, I don't see which other commits I am missing, could you please point out those commits? Where was the mmap structure changed?

By the way, I already use the newly extraced data on my test system, until now without issues (but did only a short test on different areas). I will continue testing the next days.

**Comment by ShinDarth** [comment]
good job!

**Comment by FALL1N1** [comment]
ignore my comments about missing commits, i don't see the liquid/collision commits merged with the so-called 'map rewrite' so it should work just fine

**Comment by BarbzYHOOL** [comment]
The magic number is a good idea because when someone will open an issue, we can probably easily identify that he has old mmaps. (as fall1n said in discord)

If someone wants to upload the mmaps to make testing easier :D (testers are lazy)

**Comment by Stoabrogga** [comment]
I increased the version numbers.

**Comment by dunjeon** [comment]
Good work!

**Comment by BarbzYHOOL** [comment]
Have you tested @dunjeon ? we need some feedback !

**Comment by dunjeon** [comment]
@BarbzYHOOL The PR compiled with zero errors.  The tools extracted and generated all files as intended.  I tested in STV with a pet and I didn't have any issues with the pet falling underground or npc creatures falling and attacking from underground.  it seems to be working as intended.

**Comment by BarbzYHOOL** [comment]
ok nice, will wait a bit before merging though

**Comment by dunjeon** [comment]
I spent a few hours using .mmap path in various zones and dungeons. The edge detection is much better.

**Comment by Middel** [comment]
can confirm this fixes alot of falling through the ground issues. this should be pushed honestly.
as alot of reports are due to NPC Pathing and falling through ground. and this really does fix the majority of it.

**Comment by BarbzYHOOL** [comment]
@talamortis @ShinDarth  what do you think? let's merge?

**Comment by talamortis** [comment]
since this has been tested. Will merge! thanks @Stoabrogga

**Comment by devfrom** [comment]
problem in Wintergrasp because of this https://www.youtube.com/watch?v=1a4E5go2o3M&feature=youtu.be

**Pull request merged**
