### PR TITLE
fix(Core/Battlegrounds): Fixed battleground queue announcer.

### LINKED ISSUE #11214: BG Queue announcer stopped reporting when players joins the queue
### Current Behaviour

When player joins the queue, it does not show that they joined the queue. It will only announce when bg starts.

### Expected Blizzlike Behaviour

It should announce it (Like AV 51-60 3/30)

### Source

_No response_

### Steps to reproduce the problem

Set bg announcer on Battleground.QueueAnnouncer.Enable = 0  Battleground.QueueAnnouncer.Limit.MinPlayers = 1

join bg 
doesnt show in chat

### Extra Notes

_No response_

### AC rev. hash/commit

89ba502bfc09ae5e8d217d7beb9494c5673c1af4

### Operating system

 Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11214

## Issues Addressed:

- Closes #11214

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Set bg announcer on `Battleground.QueueAnnouncer.Enable` = 1 `Battleground.QueueAnnouncer.Limit.MinPlayers` = 1
join bg
See the chat (or wait 30 sec if you have `Battleground.QueueAnnouncer.Timed` set to 1

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
If "Battleground.QueueAnnouncer.Timed" is set to 1, worldserver crash.

Screenshot 2022-04-12 144615

Logs: https://gist.github.com/Lynethris/7a0705adc5c0df931bc0a29c9ecd632c

**Comment by UltraNix** [comment]
@Lynethris Should be okay now.

**Comment by Lynethris** [comment]
@UltraNix Crash fix but the bg queu announcer doesn't work. I got only an announcer when BG start.

**Comment by UltraNix** [comment]
I tested that and it worked. If you have set timer, then you must wait.

**Comment by UltraNix** [comment]
Tell me more how are you testing this (your level, battleground type, configs).

**Comment by Lynethris** [comment]
My bad, I don't know how but after a second test all work. I have redone some others tests and all is fine.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
