### PR TITLE
Fix(Core/Quest): For The Horde! 

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Added RP and buff.
-  Implemented two methods to cast a certain spell to all players in a map, zones or areas.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1690

## SOURCE:

Positions from VMangos.

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. .q a 4974
2. .q c 4974
3. Turn in the quest.
4. Place other chars on Razor Hill, Crossroads and Camp Taurajo.
5. You should see the yell and get the buff.

## Known Issues and TODO List:

- [ ] There is a missing Herald of Thrall for Durotar zone (so you can see the yell), but I couldn't find it.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by dualcorex** [comment]
Tested this using three Horde characters located in Orgrimmar, Razor Hill, Crossroads and Camp Taurajo. 

[x] Buff was seen all these zones.
[  ] Thrall's /yell announcement was seen in all these zones. NOTE: I did NOT see the /yell announcement in Razor Hill (tested twice). Was only seen in Orgrimmar, Crossroads & Camp Taurajo 
[x] Buff was NOT seen in the Horde starting zones or on Alliance.

**Comment by Nefertumm** [comment]
> Tested this using Horde characters located in Orgrimmar, Razor Hill, Crossroads and Camp Taurajo. 
> 
> [x] Buff was seen all these zones.
> [  ] Thrall's /yell announcement was seen in all these zones. NOTE: I did NOT see the /yell announcement in Razor Hill (tested twice). Was only seen in Orgrimmar, Crossroads & Camp Taurajo 
> [x] Buff was NOT seen in the Horde starting zones or on Alliance.

Thank you for testing! Yes, I commented it on known issues. I didn't have the correct coordinates to spawn the herald in Durotar, so that's the only thing missing.

**Comment by Nefertumm** [comment]
Do not merge before https://github.com/azerothcore/azerothcore-wotlk/pull/10371

**Comment by dualcorex** [comment]
I tested this a second time but included 10330 and 10371. The result was the same as before. Tested with four characters placed in Orgrimmar, Razor Hill, Crossroads & Camp Taurajo.

[x] Buff was seen all these zones.
[ ] Thrall's /yell announcement was seen in all these zones. NOTE: I did NOT see the /yell announcement in Razor Hill. I only saw it  in Orgrimmar, Crossroads & Camp Taurajo
[x] Buff was NOT seen in the Horde starting zones or on Alliance.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
