### PR TITLE
fix(CORE/Events): Hallows end,  hardcoded strings replaced.

### PR DESCRIPTION
**Pull request by febaut**
### Changes Proposed

The event of Hallows end (hallows_end.cpp) had hardcoded strings. Were replaced according to broadcast_text.

### Issues Addressed:
Closes:  https://github.com/azerothcore/azerothcore-wotlk/issues/8632

### CODE REVIEW

**Comment by Kitzunu** [comment]
Add the entries in creature_text and reference to that instead

**Comment by febaut** [comment]
Is that necessary? I saw some examples and they call from broadcast_text. Also, if I'm not wrong, broadcast table has priority.

**Comment by Kitzunu** [comment]
Yea, you reference broadcast_text in creature_text. Better doing it that way so that everything is done the same.

**Comment by febaut** [comment]
I've double checked and creature_text does have the texts for Headless Horseman already.

`SELECT * FROM creature_text WHERE CreatureID = 23682`

On the other hand, Say and Yell, they both refer to Talk function which uses broadcast text so no way to refer directly creature_text.

**Review by acidmanifesto — APPROVED** [review]

**Comment by temperrr** [comment]
I can't get the headless horseman to spawn in rdf with .event start 12 and joining the headless horseman queue.... :/ (with this pr or without.)

**Comment by Nyeriah** [comment]
The changes requested by Kitzunu were not addressed. Waiting feedback from the author @febaut

**Pull request closed without merging**
