### PR TITLE
fix(Scripts/PlayerScript): PlayerScript Error

### PR DESCRIPTION
**Pull request by PkllonG**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by sudlud — APPROVED** [review]

**Comment by pvp100com** [comment]
It works, No errors have been detected.

**Comment by pangolp** [comment]
I haven't really tried these changes.
But I see 2 people say it works.
Therefore, I am going to give it my approval so that it can be merged.

**Review by pangolp — APPROVED** [review]
Thanks.

**Comment by pangolp** [comment]
This is a personal opinion and you may not agree with me, but it would be interesting if we could, when creating a pull request, respond at least and give a general idea of what the problem is. Because this can be used in the future by someone who has a similar problem, and by sharing the fix and having a description of the change that is made, the person who receives it can have a general idea of what they want to do. With the change.

**Comment by sudlud** [comment]
> This is a personal opinion and you may not agree with me, but it would be interesting if we could, when creating a pull request, respond at least and give a general idea of what the problem is. Because this can be used in the future by someone who has a similar problem, and by sharing the fix and having a description of the change that is made, the person who receives it can have a general idea of what they want to do. With the change.

I also did not test the changes.

This PR foxes an oversight when the script mechanism was updated.

As you can see, the "execute hook" call should was executing the wrong hooks before.
The function name did not match the executed hook.

So just from looking at the lines of code this was wrong and the PR fixed it.

**Comment by sudlud** [comment]
@pangolp 
image

**Comment by pangolp** [comment]
At first glance, reviewing the code, it is understood that it was a possibly typing error and it is good that it be fixed. I thought you tried it. Perhaps, as you say, it does not require proof, because it is more logical, because the name itself indicates it... what do we do then? Shall we merge it?

**Comment by sudlud** [comment]
> At first glance, reviewing the code, it is understood that it was a possibly typing error and it is good that it be fixed. I thought you tried it. Perhaps, as you say, it does not require proof, because it is more logical, because the name itself indicates it... what do we do then? Shall we merge it?

Sure, I don't see any reason why this should not be merged.

**Comment by pangolp** [comment]
> Sure, I don't see any reason why this should not be merged.

Done

**Pull request merged**
