### PR TITLE
fix(Core/ObjectMgr): Avoid Global Storage issue

### LINKED ISSUE #3151: [Global Storage] - Arena teams and Guild membership bugged
##### SMALL DESCRIPTION:
Some players are getting this weird bug were they can't see their own arena team and even guild. The game lets them join again to the arena team but with 0 progression, and for the non bugged members of the arena team, the bugged one who rejoined shows duplicated, one with the correct ammount of arenas played, and the other with 0 progression.

For now we've been dealing with this by restarting the server. On server restart the bugged players gets their team and guild access back, but this is far from an optimal solution.

I've only noticed than all the players with this bug get mentioned on the server log, whith something like this:

`2020-06-22 14:36:48 Player Xxxxxx  [GUID: 123456] was not found in the global storage, but it was found in the database.

2020-06-22 14:36:49 Player Xxxxxx  [GUID: 123456] was not found in the global storage, but it was found in the database.`

The lines before are never followed by "Player %s [GUID: %u] added to the global storage.", which I think may be a clue for this bug. It's like for some reason the player information is getting lost on this "global storage", and when trying to reload the info from database, it gets loaded but missing the arena and guild of the player.

I'm sorry for not being able to reproduce the issue. If anyone knows how global storage works, or what could disrupt this system, I'll be glad to start some testing to give more info, but for now this is all I have.

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
34077115a5de7d640517caf8136f8648f8f195e3

##### OPERATING SYSTEM:
Ubuntu 18.04

##### MODULES:
mod-anticheat-master
mod-boss-announcer
mod-eluna-lua-engine-master
mod-emblem-transfer
mod-premium
mod-reward-played-time-master
mod-transmog-master

##### OTHER CUSTOMIZATIONS:
I've lowered conflarate delay to 0 on https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Unit/Unit.cpp#L3928

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91920270-global-storage-arena-teams-and-guild-membership-bugged?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by CosmeF**
## CHANGES PROPOSED:
-  Add a condition for normalizePlayerName to not search for existing names with a blank space " " in the end of the string.
-  Prevents global storage to go nuts and overwrite player info with missing information, as detailed on issue #3151

## ISSUES ADDRESSED:
- Closes  #3151

## TESTS PERFORMED:
- Tested on Ubuntu 18.04 and Debian 10.

## HOW TO TEST THE CHANGES:
- Without this PR, create a character with guild and arena team. With other character, send a mail to the first character, but on the receiver's name, add the condition mentioned above (I don't want to explicitly say the process). The mail won't be sent, but try and see what happens on world console, and then relogin the first character. This will cause issue #3151.
- With this PR, this won't happen. The mail won't be sent, and that's it.

## KNOWN ISSUES AND TODO LIST:

- I've checked for other characters besides the space " ", but nothing happens with those. The condition of "not founding" the character on global storage but finding it on the database should, however, bring the right information, with no bugs or missing parts. 

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
nice catch @CosmeF

**Comment by Shadofiend** [comment]
Worked.

**Comment by BarbzYHOOL** [comment]
@CosmeF can you tell me how to reproduce this issue? maybe on discord? i don't get what you meant here

**Comment by BarbzYHOOL** [comment]
Alright i reproduced the issue fine :D

**Pull request merged**
