### PR TITLE
Switch to C++14 to solve compilation issues

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
##### CHANGES PROPOSED:

Switching from C++11 to C++17 has caused some compilation issues for some users. Until such issues are solved, it's better to use C++14 

###### ISSUES ADDRESSED:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1593
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1568

##### TESTS PERFORMED:

https://github.com/azerothcore/azerothcore-wotlk/issues/1593#issuecomment-475008813

##### HOW TO TEST THE CHANGES:

Try to build this and run. Check if everything looks fine.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by wizzymore** [comment]
It builds fine with clang 7. The only reason that travis is not getting the error is that Xenial, the dist used by travis comes with clang 3.8.
For more information: https://pkgs.org/download/clang

**Comment by FrancescoBorzi** [comment]
that issue was fixed thanks to @FallingSnow

I'm waiting him to test this PR again too and we can merge it

**Comment by FallingSnow** [comment]
We are good to go. Compiled successfully.

**Comment by FrancescoBorzi** [comment]
thank you @wizzymore and @FallingSnow for your help

**Pull request merged**
