### PR TITLE
fix(Core/Movement) Smoother movement of hunter pets when following players

### LINKED ISSUE #16763: Hunter pets don't move smooth when following
### Current Behaviour

Hunter pets don't move smoothly when following the player after learning the Boar's Speed talent
[Prove Video](https://youtu.be/ijqUeb_r_Js)

### Expected Blizzlike Behaviour

It should be smooth. I don't have an account to verify right now, so if anyone is willing to help I'd greatly appreciate it!

### Source

_No response_

### Steps to reproduce the problem

1. Create a blood elf hunter
2. .level 79
3. Selected a Springpaw Cub then using .pet create
4. Pets learn Boar's Speed talent

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 3a3dc6446bad 2023-07-12 08:04:39 -0300 (master branch) (Win64, Debug, Static)
Using SSL version: OpenSSL 1.1.1g  21 Apr 2020 (library: OpenSSL 1.1.1g  21 Apr 2020)
Using Boost version: 1.81.0
Using MySQL version: 80021
Using CMake version: 3.26.3
Compiled on: Windows
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in E:/workspace/azerothcore-wotlk/build/bin/Debug/maps. Total size: 291014951 bytes
vmaps directory located in E:/workspace/azerothcore-wotlk/build/bin/Debug/vmaps. Total size: 658130721 bytes
mmaps directory located in E:/workspace/azerothcore-wotlk/build/bin/Debug/mmaps. Total size: 2192910844 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS frFR deDE esES esMX ruRU
Using World DB: ACDB 335.10-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
No modules enabled

### Operating system

Windows 11 x64

### Custom changes or Modules

None

### PR DESCRIPTION
**Pull request by wzw1990**
## Changes Proposed:
-  Smoother movement of hunter pets when following players

## Issues Addressed:

- Closes #16763 

## Tests Performed:

- Tested in game
- [Prove Video](https://youtu.be/y7PXED3LNlo)

## How to Test the Changes:

1. Create a blood elf hunter
2. .level 79
3. Selected a Springpaw Cub then using .pet create
4. Pets learn Boar's Speed talent
5. Walking around.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]
It seems okay, but what's the behaviour when you're mounted?

**Comment by wzw1990** [comment]
> It seems okay, but what's the behaviour when you're mounted?

When mounted, the hunter's pet disappears.

**Comment by Samsequel** [comment]
*testing in progress*

**Comment by wzw1990** [comment]
Thanks for the testing @Samsequel 
I'll try to fix these as soon as I can

**Comment by wzw1990** [comment]
Sorry for taking so long to reply.
I can't reproduce the problems with 3 and 4, could you please record a video?
[my record](https://youtu.be/VU5eQdq2IsM)

**Comment by Samsequel** [comment]
@wzw1990 

I tested it with the boar pet from night elves zone

**Comment by wzw1990** [comment]
@Samsequel 
Here are my [test results](https://youtu.be/CuvqVYNkUOc) with boar pet and night elves, it looks ok

**Comment by Samsequel** [comment]
seems fine indeed, no objections...

**Pull request merged**
