### PR TITLE
fix(Core/Spells): Berserk now removes the Tiger Fury buff.

### PR DESCRIPTION
**Pull request by ErnestoGonzalezC**
## Changes Proposed:
-  Berserk now removes the Tiger Fury buff.

## Tests Performed:

- Compile without errors on windows 10 and ubuntu 20

## How to Test the Changes:

- Log in with a Druid, cast ``Tiger Fury``, and then cast ``Berserk``. Note that ``Berserk`` now removes the ``Tiger Fury buff``.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Sedatyf** [comment]
I did some digging on that matter. And I think ``[Berserk]`` shouldn't remove ``[Tiger's Fury]``
``[Berserk]`` description says you can't cast ``[Tiger's Fury]`` while ``[Berserk]`` is active. But I saw people using ``[Berserk]`` while ``[Tiger's Fury]`` active for a short DPS burst
image

**Comment by ErnestoGonzalezC** [comment]
@Sedatyf Please check this https://www.warmane.com/bugtracker/report/56417

**Comment by ErnestoGonzalezC** [comment]
https://youtu.be/rtAq6yL2E1g?t=1m50s

https://youtu.be/MrG1Befdu0o at 00:12 and 3:24

**Comment by Sedatyf** [comment]
> https://youtu.be/MrG1Befdu0o at 00:12 and 3:24

Oh you're right. It's interesting but okay. My bad buddy! I'll test it as soon as I got time

**Comment by ErnestoGonzalezC** [comment]
> > https://youtu.be/MrG1Befdu0o at 00:12 and 3:24
> 
> Oh you're right. It's interesting but okay. My bad buddy! I'll test it as soon as I got time


This time I was able to do some research haha, but thank you very much your help is always welcome :)

**Comment by Sedatyf** [comment]
So it was easy and quick to test 😄 Tiger's Fury is removed when Berserk is active ✔️ 
Good job @ErnestoGonzalezC 👍🏼 

https://user-images.githubusercontent.com/59012307/116213193-d995fe80-a745-11eb-9b45-54eb2287f557.mp4

Just need a reviewer here @FrancescoBorzi

**Review by Helias — APPROVED** [review]

**Pull request merged**
