### PR TITLE
Allow Opcode Handlers be overridden by Modules

### PR DESCRIPTION
**Pull request by DavuKnight**
## Changes Proposed:
-  Remove the restriction from allowing opcode handlers to be overridden

## Issues Addressed:
-  Opcode handlers can't currently be overridden by a module. With this change a Module can completely override how an Opcode is handled. 

- Currently working on a system to offload processing out of the WorldServer thread. This can be done by making the Opcodes that are less sensitive to response time work Async using a message hub but cant do it without overriding Opcode handlers. 

## Tests Performed:
tests performed -->
- Built Ran Played for a bit

## How to Test the Changes:
Internal Code change to allow for something currently restricted

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by DavuKnight** [comment]
Messed up the PR Need to make another

**Comment by DavuKnight** [comment]
Looks like this came in from Trinity Core in https://github.com/azerothcore/azerothcore-wotlk/pull/5617
Might not have ever been something we wanted to restrict.

**Comment by acidmanifesto** [comment]
Op codes were not ment to be overriden outside of the world core.

**Comment by DavuKnight** [comment]
@acidmanifesto Thats basically the question . Why not? What is it that preventing Opcode override is achieving?

**Comment by DavuKnight** [comment]
IE:
`function(deleteCharsInPlace IN_FILE startcut endcut)
	file (READ ${IN_FILE} LINES)
	string(SUBSTRING "${LINES}" 0 ${startcut} Pre)
	string(SUBSTRING "${LINES}" ${endcut} -1 Post)
	string(APPEND fileData "${Pre}" "${Post}")
	message(STATUS "${fileData}")
	file(WRITE ${IN_FILE} "${fileData}")
endfunction()

SET(OpCodesFile "${CMAKE_CURRENT_SOURCE_DIR}/../src/server/game/Server/Protocol/Opcodes.cpp") 
SET(OpCodesFileHash "b973fd5b8cf81ff46de9cdcad416a3e4c3a7e9d718a1632ae7aafcf3ac1409f1")

if (EXISTS ${OpCodesFile})
    message(STATUS "Found :" ${OpCodesFile})
endif()

message(CHECK_START "Validating ${OpCodesFile}")
File(SHA256 "${OpCodesFile}" OpCodeHash)
message(STATUS "${OpCodesFile} is        ${OpCodeHash}")
message(STATUS "${OpCodesFile} should be ${OpCodesFileHash}")

set(CMAKE_DISABLE_SOURCE_CHANGES OFF)
if(${OpCodeHash} STREQUAL  ${OpCodesFileHash})
	message(CHECK_PASS "OpCodes.cpp is Valid for Module")
	deleteCharsInPlace(${OpCodesFile} 2746 2964)
	deleteCharsInPlace(${OpCodesFile} 3307 3525)
else()
	message(CHECK_FAIL "OpCodes.cpp is Invalid or has already been updated")
endif()
set(CMAKE_DISABLE_SOURCE_CHANGES ON)`
Just Fragile as hell

**Comment by acidmanifesto** [comment]
> IE:
> 
> ```
> function(deleteCharsInPlace IN_FILE startcut endcut)
> 	file (READ ${IN_FILE} LINES)
> 	string(SUBSTRING "${LINES}" 0 ${startcut} Pre)
> 	string(SUBSTRING "${LINES}" ${endcut} -1 Post)
> 	string(APPEND fileData "${Pre}" "${Post}")
> 	message(STATUS "${fileData}")
> 	file(WRITE ${IN_FILE} "${fileData}")
> endfunction()
> 
> SET(OpCodesFile "${CMAKE_CURRENT_SOURCE_DIR}/../src/server/game/Server/Protocol/Opcodes.cpp") 
> SET(OpCodesFileHash "b973fd5b8cf81ff46de9cdcad416a3e4c3a7e9d718a1632ae7aafcf3ac1409f1")
> 
> if (EXISTS ${OpCodesFile})
>     message(STATUS "Found :" ${OpCodesFile})
> endif()
> 
> message(CHECK_START "Validating ${OpCodesFile}")
> File(SHA256 "${OpCodesFile}" OpCodeHash)
> message(STATUS "${OpCodesFile} is        ${OpCodeHash}")
> message(STATUS "${OpCodesFile} should be ${OpCodesFileHash}")
> 
> set(CMAKE_DISABLE_SOURCE_CHANGES OFF)
> if(${OpCodeHash} STREQUAL  ${OpCodesFileHash})
> 	message(CHECK_PASS "OpCodes.cpp is Valid for Module")
> 	deleteCharsInPlace(${OpCodesFile} 2746 2964)
> 	deleteCharsInPlace(${OpCodesFile} 3307 3525)
> else()
> 	message(CHECK_FAIL "OpCodes.cpp is Invalid or has already been updated")
> endif()
> set(CMAKE_DISABLE_SOURCE_CHANGES ON)
> ```
> 
> Just Fragile as hell

with op codes, depending on which ones, is already client specific with packets assigned to them, wrong packet, wrong opcode, wrong combination will result in a client side crash\disconnect or server crash pretty much which is the quick summary of it.
There are some op-codes intentionally nulled out that are still recognized and could still be used that is no longer actually used within the expansions so some can be repurposed if you decide to reverse engineer the client to find them and label them out.

But in wow emu case, Opcodes are also called byte codes which is intended for a software interpreter (client side\server side).

**Comment by DavuKnight** [comment]
So we make overriding OpCodes difficult because they can cause a client crash if not coded correctly? 
Guess I can see it but then it only takes one dev to create a CMake Script that exposes it and then anyone else can Mod away at it. Not sure security by obfuscation is going to work for long.

**Pull request closed without merging**
