### PR TITLE
fix(DB/CreatureSAI/GameObjectSAI): Quest Call of Water 5/6

### PR DESCRIPTION
**Pull request by Stifler82**
## Changes Proposed:
Fix Quest: [Call of Water 5/6](https://wowgaming.altervista.org/aowow/?quest=9508)
-  NPCs spawns coordinates changed [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) and 2 [Water Spirit](https://wowgaming.altervista.org/aowow/?npc=6748)
-  Added SAI to Creature [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) and [Water Spirit](https://wowgaming.altervista.org/aowow/?npc=6748)
- Added SAI to GameObject [Barrel of Filth](https://wowgaming.altervista.org/aowow/?object=181699)
- GameObject spawn coordinates changed [Barrel of Filth](https://wowgaming.altervista.org/aowow/?object=181699)
- Added Text for SAI to Creature [Tel'athion the Impure](https://wowgaming.altervista.org/aowow/?npc=17359) and [Water Spirit](https://wowgaming.altervista.org/aowow/?npc=6748)

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/197
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4830

## Tests Performed:
- Tested in game and working
- Tested on Windows 10 (64)
- **Video Test:** [Call of Water 5/6](https://youtu.be/O33OyHjRzjQ)

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
sorry @Stifler82 but I had to change this query:

```sql
UPDATE `creature_template` SET `faction` = 1655, `AIName` = 'SmartAI', `mindmg` = 18, `maxdmg` = 28, `attackpower` = 51, `type_flags` = 0, `resistance1` = 10, `resistance2` = 60, `resistance3` = 50, `resistance4` = 60, `resistance5` = 10, `resistance6` = 10 WHERE (`entry` = 6748);
```

to this:

```sql
UPDATE `creature_template` SET `faction` = 1655, `AIName` = 'SmartAI', `type_flags` = 0, `resistance1` = 10, `resistance2` = 60, `resistance3` = 50, `resistance4` = 60, `resistance5` = 10, `resistance6` = 10 WHERE (`entry` = 6748);
```

so basically removing the following:

```sql
`mindmg` = 18, `maxdmg` = 28, `attackpower` = 51,
```

(I did this here https://github.com/azerothcore/azerothcore-wotlk/pull/4925 )

the reason is: the table structure is changed and those fields are no longer there.

**Comment by Mindary-Warlock** [comment]
There is still the Problem, that the spawning Waterelementals are not help killing Tel'athion... whereby it is nearly impossible to kill Tel'athion on your own if youre not at least a level 29+ Dreanei because of the high amount of damage Tel'athion is making.  So i would say its very important to fix this quest as intendet.

:-)

**Comment by FrancescoBorzi** [comment]
> There is still the Problem, that the spawning Waterelementals are not help killing Tel'athion... whereby it is nearly impossible to kill Tel'athion on your own if youre not at least a level 29+ Dreanei because of the high amount of damage Tel'athion is making. So i would say its very important to fix this quest as intendet.
> 
> :-)

@Mindary-Warlock please open a new issue

**Pull request merged**
