### PR TITLE
fix(Core/Movement): Improved fleeing movement generator.

### LINKED ISSUE #11850: Movement (moving in fear across the bridge)
### Current Behaviour

When using fear(any) on the bridge, we block movement and in the arena, fear brings to the very edge, which leads to the player falling to the bottom.

videos: https://streamable.com/pm2nnl
            https://streamable.com/dad2i0

### Expected Blizzlike Behaviour

should generate a valid place to move, and the arena should not go all the way to the edge.

### Source

_No response_

### Steps to reproduce the problem

1. Climb any bridge
2. Use fear

### Extra Notes

_No response_

### AC rev. hash/commit

[#305a26](https://github.com/azerothcore/azerothcore-wotlk/commit/305a2689e965346dc7c12a87650fab08696b0a10)

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11850

## Issues Addressed:

- Closes #11850

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Climb any bridge
Use fear

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@r0m1ntik Please, test it.

**Comment by r0m1ntik** [comment]
@UltraNix sometimes bugs in the same conditions, but of course it got better. If the player is standing in the corner, then he stays there.

**Comment by UltraNix** [comment]
@r0m1ntik Please, can you make some video of this "corner" problem. I think we'll never achieve a perfect solution on this.

**Comment by r0m1ntik** [comment]
@UltraNix
https://streamable.com/j6heuh
https://streamable.com/7adju0

**Comment by UltraNix** [comment]
@r0m1ntik Where is that bridge?

**Comment by UltraNix** [comment]
@r0m1ntik Should be now okay.

**Comment by r0m1ntik** [comment]
@UltraNix tested, now work fine ! Thanks <3

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
