### PR TITLE
fix(Core/RealmList) Fix display of realm population

### PR DESCRIPTION
**Pull request by Meltie2013**
## Changes Proposed:
-  Fix realm population not reflecting real levels of players on given realm
-  Fix realms displaying `Medium` levels when there are 2 or more realms when `population` remains `0`
-  Fixed 2 realm flags that were displaying incorrectly when used

**Without Changes**
image

**With Changes**
image
This last images reflects the values updates to the `population` field in the `realmlist` database.

**Notice**
Make sure you have a set max population when testing this, since the flags are dependent on max realm population and total connected players.

## Tests Performed:

- Builds without errors
- View images above (keep in mind, the flags `New` and `New Players` are flipped in the image.
  This been fixed with current PR.

## How to Test the Changes:

1. Make 2 realms (can be a realm that is not used)
2. Log into an account
3. You can either log into the world or sit on the realmlist screen
4. Wait for the server to update the population or change `population` field to any value between `0` and `1`
5. Watch the population levels change according to the values given per realm

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
I did some research about this and I've found something:

>Each realm has a population listed on the server selection screen. Each realm is characterized as having Recommended, Low, Medium, High, and Full population. **Recommended servers are what Blizzard thinks will give a new player the best experience, while the rest are categorized based on how many players are currently logged into the realm.** These servers change throughout the day, so you may want to decide on a server at the time you would normally play, so that you'll know how full it is normally. You cannot create a character on a Full server unless you already have characters there. Some High population servers have wait queues during peak hours. This means you cannot sign in at all to them until other people have completely logged off of that server.

Apparently the "recommended" flag should be static and not change depending on the amount of players logged in.

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers can anyone please look into this?

**Comment by Meltie2013** [comment]
Closing this PR out and looking at a different methods like IPC.

**Comment by Maurowin** [comment]
Let me know when you want another tests like the last time.

**Pull request closed without merging**
