### PR TITLE
fix(DB/SmartScript) Quest - Gurok the Usurper RP event

### PR DESCRIPTION
**Pull request by M4th3m4tic4l**
## Changes Proposed:
-  Add animation with skulls, pause before spawn and missing text to the event.

## Issues Addressed:

- https://github.com/chromiecraft/chromiecraft/issues/4439
- https://github.com/azerothcore/azerothcore-wotlk/issues/13745

## Tests Performed:

- 
WoWScrnShot_012623_231840

- 
WoWScrnShot_012623_231845

- 
WoWScrnShot_012623_231849

## How to Test the Changes:

1.Add the statements to your world database
2. .tele Nagrand
.go xyz -875.142761 8687.954102 251.572418
.quest add 9853
.additem 24502 7

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — COMMENTED** [review]
Do we have a reference via retail video\sniff\or other core source such as tc\mangos to confirm this is how it need to be played out?

**Comment by M4th3m4tic4l** [comment]
As I told you in the other pr, I relied on videos mainly, and from that I recreated the event:
https://youtu.be/rMxB5tVa9j8?t=733
https://youtu.be/H4MZHJrC64k?t=24

I set it up so that the skulls would disappear at the same time as the creature's corpse, approximately 3 minutes, also, there were missing texts in the DB that I added

**Comment by Maelthyrr** [comment]
Hi, tested and work but we can't always finish the quest because the head loot is missing on earthen brand.

**Comment by M4th3m4tic4l** [comment]
I don't know what you are referring to specifically, the Gurok head loot is in the database.
Loot

Now, I don't know if I misread, but correct me in any case.

**Comment by Maelthyrr** [comment]
I'm wrong. After a recheck with a clean DB, the head drop. So everything is fine, thanks for your PR!

**Comment by Gultask** [comment]
Will need a sniff for the proper locations. Also not really sure on the Visibility part.
Could be that a trigger creature or gob could be used for spawns instead.

**Comment by FrancescoBorzi** [comment]
what's the status of this PR? I haven't looked at it in details but if it's not good and not going to be reworked, I'd rather close it.

**Comment by Kitzunu** [comment]
Closing as stale.

**Pull request closed without merging**
