### PR TITLE
fix(DB/Spell): remove NPC curse

### PR DESCRIPTION
**Pull request by Helias**
I don't know if my fix is an hackfix or not, please have a look.

## Changes Proposed:
-  remove all auras before updating entry, this will refresh the aura of the NPC

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4476
- Closes https://github.com/chromiecraft/chromiecraft/issues/52

## Tests Performed:
- tested in-game

## How to Test the Changes:
```
.q add 6124
.go cr id 12298
use the item of the quest to heal the deer
it should not have the curse anymore
```

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
I'm wondering if this could potentially break other quests

**Comment by FALL1N1** [comment]
This spell is used for 2 quests  6124 and 6129 so it won't break anything in my opinion and can be merged right away.

**Comment by r0m1ntik** [comment]
Yes, I also think like previous posts

**Comment by Kitzunu** [comment]
You could do this as well

```sql
DELETE FROM `spell_linked_spell` WHERE `trigger_spell` = 19512;
INSERT INTO `spell_linked_spell` (`spell_trigger`, `spell_effect`, `type`, `Commen`) VALUES
(19512, -19502, 1, 'Apply Salve - Sickly Critter Aura removed');
```

**Comment by pklloveyou** [comment]
Tested

**Review by Voxstrasza — APPROVED** [review]

**Pull request merged**
