### PR TITLE
fix(DB/Gameobject): Rebuild all Kalimdor gathering nodes using sniffed data

### PR DESCRIPTION
**Pull request by Gultask**
Continuation of: https://github.com/azerothcore/azerothcore-wotlk/pull/18898

I want to take another look before merging, tho

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17410
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10382
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11551
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7206
- Closes https://github.com/chromiecraft/chromiecraft/issues/1267
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9308
- Closes https://github.com/chromiecraft/chromiecraft/issues/2380
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10218
- Closes https://github.com/chromiecraft/chromiecraft/issues/2805
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11268
- Closes https://github.com/chromiecraft/chromiecraft/issues/3192
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7432
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17147
- Closes https://github.com/chromiecraft/chromiecraft/issues/5970
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11306
- Closes https://github.com/chromiecraft/chromiecraft/issues/3270
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6264
- Closes https://github.com/chromiecraft/chromiecraft/issues/966
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6099
- Closes https://github.com/chromiecraft/chromiecraft/issues/723
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6092
- Closes https://github.com/chromiecraft/chromiecraft/issues/717
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6070
- Closes https://github.com/chromiecraft/chromiecraft/issues/712
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6068
- Closes https://github.com/chromiecraft/chromiecraft/issues/711
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5912
- Closes https://github.com/chromiecraft/chromiecraft/issues/634
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5884
- Closes https://github.com/chromiecraft/chromiecraft/issues/589
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5849
- Closes https://github.com/chromiecraft/chromiecraft/issues/642
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5619
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5424
- Closes https://github.com/chromiecraft/chromiecraft/issues/450
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4518

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [X] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
🔥🔥🔥

**Comment by heyitsbench** [comment]
That's a lot more linked issues than the EK one. 😆

**Comment by Gultask** [comment]
> That's a lot more linked issues than the EK one. 😆

Cause EK one only progressed some more general issues rather than fix it altogether :P

Oh, and sorry. It's done, it can be merged, I was just worried about the amount spawned in a couple of distinct zones, but we can easily alter that later on the major pools.

**Comment by sudlud** [comment]
You wanna merge master again to get CI passing? :)

**Comment by Kitzunu** [comment]
No need, CI passed once we can just merge it. Nothing here can break the build so it is fine

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
