### PR TITLE
fix(Core/Player): Use SkillLineAbility.dbc to determine player initia…

### PR DESCRIPTION
**Pull request by Kitzunu**
…l spells - skill assignment done in a new table `playercreateinfo_skills`

* Cherry-pick https://github.com/TrinityCore/TrinityCore/commit/2a3546ca36468b81d673bdb27315006144af3165

* Cherry-Pick https://github.com/TrinityCore/TrinityCore/commit/d28b66bca88de621fd00495e4edc7e4d9d01e7eb

* Cherry-Pick https://github.com/TrinityCore/TrinityCore/commit/193408f3351b8ce1fb17dc87e11fe2e18b46ec41

Co-Authored-By: Shauren <shauren.trinity@gmail.com>
Co-Authored-By: Rothend <67004168+Rothend@users.noreply.github.com>
Co-Authored-By: claudiodfc <claudio.daniel.f.c@gmail.com>

## Changes Proposed:
-  Use SkillLineAbility.dbc to determine player initial spells
-  skill assignment done in a new table `playercreateinfo_skills`
- properly scale current value of hidden skills with player level

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1659
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6036
- Closes https://github.com/chromiecraft/chromiecraft/issues/693

## Tests Performed:

- Builds
- Tested in-game

### Case 1

1. Create a new character
2. See that you get all skills that you should.
3. See that you get all spells that you should.

### Case 2

1. Test that you can learn talents

### Case 3

1. Test "Blood Fury" and see that the Tooltip is updated when you level up

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Ready for review.

Tested by both me and @claudiodfc and everything works as it should =)

**Review by Winfidonarleyan — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
very huge works, congrats!

**Comment by pklloveyou** [comment]
https://github.com/TrinityCore/TrinityCore/commit/08fdac340c8af7d7426870d3ec51ab88c5dd77db

**Comment by WillzDevs** [comment]
#6527

**Comment by Yehonal** [comment]
Please, can you provide a changelog next time? https://www.azerothcore.org/wiki/how-to-use-changelog

**Comment by FrancescoBorzi** [comment]
> Tested by both me and @claudiodfc and everything works as it should =)

this PR introduced a critical bug that basically caused all your max skills to increase with your level (even the ones that weren't supposed to, like professions) and was quite hard to debug and fix.

Please next time be more careful when testing such huge core changes and try to check all possible affected cases, but I know it's sometimes hard to remember testing everything.

This PR has been opened on the 23rd May and merged only 7 days ago, it would have been nice if other people could help testing this.

**Comment by claudiodfc** [comment]
My bad Shin, I should have done a better job testing this indeed. I'll be more careful next time.

**Comment by FrancescoBorzi** [comment]
> My bad Shin, I should have done a better job testing this indeed. I'll be more careful next time.

no worries, at least you tried testing it and for that I'm grateful! :) I wish many other users would help with testing as well...

**Comment by necropola** [comment]
> Tested by both me and @claudiodfc and everything works as it should =)
Is this the entire log of what/how was tested or rather what was identified as "needs to be tested"?

@FrancescoBorzi I agree that we need more people to test PRs (like this), but the root cause here lies in the section `### How to test the Changes:`. A change like this requires a comprehensive test plan provided by the original author which not only lists areas/cases addressed by the change but also areas/cases maybe affected by change.

Going through such a test plan would have produced a lot more log than just a line stating "everything is working as expected" and maybe it would have even spotted a bug or two.

**Comment by Yehonal** [comment]
> > Tested by both me and @claudiodfc and everything works as it should =)
> 
> Is this the entire log of what/how was tested or rather what was identified as "needs to be tested"?
> 
> @FrancescoBorzi I agree that we need more people to test PRs (like this), but the root cause here lies in the section `### How to test the Changes:`. A change like this requires a comprehensive test plan provided by the original author which not only lists areas/cases which are addressed by the change but also areas/cases which may be affected by the change.
> 
> Going through such a test plan would have produced a lot more log than just a line stating "everything is working as expected" and maybe it would have even spotted a bug or two.

indeed

**Comment by claudiodfc** [comment]
The problem isn't just not having a test case, but the cherry pick itself. We thought we had explored the only areas it affected and we thought it was pretty good to go. We implemented a big issue on the way but we only realised it was an issue when players played with the commit.
If we were developing the core without copying code that we don't understand, which is what they do on TC, we wouldn't be having this conversation. However, I do understand that it is very hard to improve without knowing where to improve which is a barrier that I face daily. If we talked more in the discord about core changes and how to change, if there was more communication between contributors, this would be a much pleasant experience.

**Pull request merged**
