### PR TITLE
refactor(Core/Command): tele to teleport

### PR DESCRIPTION
**Pull request by Kitzunu**
## CHANGES PROPOSED:
-  rename tele to teleport, this has no effect on the command.

## ISSUES ADDRESSED:
- Closes nada 

## TESTS PERFORMED:
- builds
- works in-game

## HOW TO TEST THE CHANGES:

1. use the command

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
looks fine to an amateur like me

and also useful

TODO: rename the fuckin table too

**Comment by FrancescoBorzi** [comment]
it still works with `.tele` too, right?

**Comment by Kitzunu** [comment]
Ofc ^^

**Comment by merdlin** [comment]
thanks, this will help many people who are not very knowledgeable about the commands.

**Comment by Kitzunu** [comment]
@merdlin did you test it?

**Comment by merdlin** [comment]
> @merdlin você testou?

Yes

**Comment by P-Kito** [comment]
Time for aliases :P

**Pull request merged**
