### PR TITLE
Fix(Script/scholo): Improvements for Kirtonos

### PR DESCRIPTION
**Pull request by patou01**
## Changes Proposed:
- Removed most SAI from brazier, it now only sets the instance data
- Event starts at the end of the gameobject use, not at the start. ie he spawns when the brazier is lit
- Gate and brazier control is moved from kirtonos.cpp to scholomance.cpp
- Retry is now possible after a wipe, granted one has enough blood.
- Kirtonos doesn't swim in the air in humanoid form anymore

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8397
- closes https://github.com/azerothcore/azerothcore-wotlk/issues/8386
- closes https://github.com/azerothcore/azerothcore-wotlk/issues/8852 
- closes https://github.com/chromiecraft/chromiecraft/issues/2221
- closes https://github.com/chromiecraft/chromiecraft/issues/2041

## Tests Performed:

- tested on my own machine. https://drive.google.com/file/d/1h2Sc_UCuLoGhe9s-WOogzoRG_WeluJnq/view?usp=sharing
- tested fail event (enabling GM mode), door opens and brazier reset
- tested 2 players clicking at the same time, only one spawns and the last clicker gets "invalid target" upon completion, which afaik is blizzlike
- tested killing the boss, door opens brazier doesn't reset

## How to Test the Changes:

1. Go to scholo at kirtonos spawn, use blood of innocent (.add 13523)
2. Test the event in usual ways: wipe, boss kill, etc (note that if the boss is killed and you respawn him, the event probably wont work anymore)
3. Test what happens if you get thrown out the window too, should just cause a reset but good to be sure.

## Known Issues and TODO List:

- [ ] Might have broken the "load after crash" feature.
- [ ] I broke the flying path slightly towards the end where he lands I believe, but it's still good enough.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by patou01** [comment]
I think this PR is fully ready now... Only remaining issue that I'm aware of about Kirtonos is that the path kinda sucks, but I think that's a core issue on pathing and not on the boss itself. https://drive.google.com/file/d/1hlkrFheGlin4BPSZBFVWHNBDtLxpaNQ3/view?usp=sharing

**Comment by patou01** [comment]
@azerothcore/testers if anyone could have a look that the event happens correctly?
Should be checked that:
- all 3 issues are fixed
- no obvious bug between summon and end of fight.

**Review by Nyeriah — APPROVED** [review]

**Comment by Synful-Syn** [comment]
Also closes these two original reports.
https://github.com/chromiecraft/chromiecraft/issues/2041
https://github.com/chromiecraft/chromiecraft/issues/2221

**Comment by Helias** [comment]
@patou01 merge conflicts, please fix them to allow the test :wink:

**Comment by patou01** [comment]
@Helias , done

**Comment by patou01** [comment]
@azerothcore/testers , since I believe the boss is currently 100% broken unless someone fixed it behind our back, might be worth to have a look at it.

**Comment by temperrr** [comment]
Tested:

- [x] No errors
- [x] He flies outside for a bit, then flies inside to the staircase
- [x] He uses abilities, kicks you back, goes in and out of bat form.
- [ ] When he kicks you out the window, you get a loading screen and go back to where you entered RDF (is this correct?)
- [x] Can only summon once
- [x] Can summon again if you wipe

**Comment by patou01** [comment]
In vanilla and TBC, you'd get ported out if  you fell out the window. I assume that's the same for rdf. I'll do some checks during the rest of the week and add the label if I find it.

**Comment by patou01** [comment]
> Tank him at the top of the stairs. He has a knockback attack and if he sends you out the window, you will zone out of the instance.  

From https://wowwiki-archive.fandom.com/wiki/Kirtonos_the_Herald . As far as I'm aware zoning out will put you back to where you entered, so RDF joining location in this case. I don't see anything that says it changed between introduction and removal.

**Pull request merged**
