### PR TITLE
fix(Core/Movement): Fixed adding wrong flag on root.

### LINKED ISSUE #5891: Quest Buge [The Drakkensryd]
## CURRENT BEHAVIOUR:
[The Drakkensryd]
When I ride a dragon, I attack the npc
They do not eat damage
It only works on one of them. When they go around a few times, the dragons disappear and become bugs

## EXPECTED BLIZZLIKE BEHAVIOUR:
https://www.wowhead.com/quest=12886/the-drakkensryd

## SOURCE:
WoWScrnShot_051621_170831

## STEPS TO REPRODUCE THE PROBLEM:
.go cre 97128
.q add 12886

Hit the item and ride the dragon
And attack
You see, he does not attack

## AC HASH/COMMIT:
rev. 7fa1cb1+ 2021-04-29 15:07:03 +0200

## OPERATING SYSTEM:
Windows Server 2019 Standard

## MODULES:
mod-transmog
mod-cfbg
mod-duel-reset
mod-anticheat
mod-mall-teleport
mod-dynamic-xp

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98542800-quest-buge-the-drakkensryd?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #5891

## Issues Addressed:

- Closes #5891

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/5891)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by zqgmzq** [comment]
@UltraNix, thank u
i will test it now

**Comment by temperrr** [comment]
Tested

without pr
- [ ] You can jump to a drake, but cant hit the rider (it says Too far away)

with pr:

- [ ] You can jump to a drake, but you cant hit the rider (it says too far away)

**Comment by UltraNix** [comment]
@temperrr Test again.

**Comment by tkn963** [comment]
I tested it. The first dragon I landed on worked perfectly fine. The second one told me I was facing the wrong way. The third one worked fine, the fourth one had the same facing the wrong way issue and so did the fifth one. It seems kind of random.

Spell casting always work luckily so I could easily kill one and try another.

**Comment by tkn963** [comment]
And because I had to say it, now it's saying "Target needs to be in front of you" when I try to cast spells..

**Comment by UltraNix** [comment]
@tkn963 Try again.

**Comment by tkn963** [comment]
Tested on more than 20 creatures with no issues what so ever. I tested both melee and spell casts and never had any issues.

Of course testing so many gets confusing since most of them will be dead by the time you get there, heh.

The only note I could give is that killing them sometimes just makes them untargettable and they face away from you instead of falling off. I don't remember if that was a random chance to happen or not though. But you can complete the quest with ease.

**Comment by zqgmzq** [comment]
tested, quest is ok now

**Comment by Footman** [comment]
for me its still same. out of range

**Comment by zqgmzq** [comment]
> for me its still same. out of range

clean cache

**Comment by Footman** [comment]
> > for me its still same. out of range
> 
> clean cache

ok yes works for me now

**Comment by Heitortadeu** [comment]
Go merge!

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
