### PR TITLE
Core/Locales: Add support for localization

### LINKED ISSUE #207: locales_ translations in database dont work properly with core? esES Client
**Description**: Locales translations don't work properly (for me)

**Current behaviour**: I have a database of the same exact estructure than the one using with azerothcore-wotlk, i translated everything as it is in the other database i use with an old Trinitycore compilation,, but in this case with azerothcore-wotlk.. quests dont detect the translations on locales_ tables on world database,, items dont translate, npc texts dont translate,, they still remain in english, i used locales 6 as in my old database that worked properly, this is maybe a think i should set-up in worldserver.conf file? I did something wrong?
Its problem of the core not reconizing the locales?
Should i help with a fix to this?

**Expected behaviour**: Using translation locales_ system should translate for clients texts to language according to his client, in my case esES.

**Operating system**:  Windows 10 Pro

**Modules**:  Should i use any module to solve this? Don't really know...

**Other Customizations**: Clean compile, everything works fine except for translations to Spanish.

If you can explain me detaile

If you need screenshots i can attach them.
Thanks and sorry for my english.
Keep this great work.
##

### PR DESCRIPTION
**Pull request by Blumfield**
**Changes proposed:**

-  Implement support for localization
-  
-  

**Target branch(es):** 1.x/2.x etc.

Master

**Issues addressed:** Closes #207 #197 

**Tests performed:** (Does it build, tested in-game, etc)

Compiled without problem(althought tons of sql errors that needs to be corrected) THIS WAS NOT TESTED INGAME ! USE AT YOUR OWN RISK !

**Known issues and TODO list:**

- [ ] Lots of errors when booting the core
- [ ] 

Please read ! I couldn't upload the SQL file because they were too large, you can find them here https://mega.nz/#fm/2hNTnJjB they are 5 SQL in total (it's stull upload as I post this so be patient !)

report feedback with as much details as possible thanks !

### CODE REVIEW

**Comment by ShinDarth** [comment]
@cooler-SAI @HeartWell @sucofog please check this and give your feedback, thanks

**Comment by sucofog** [comment]
I'm on it, thanks @Blumfield :D thanks @ShinDarth @cooler-SAI

**Comment by cooler-SAI** [comment]
will test it soon

**Comment by HeartWell** [comment]
Very good, just one piece of advice. Divide all examples like me, it will help you understand where that well.

<a target="_blank" href="http://radikal.ru/fp/rj2ai5bx4mtj7"></a>

**Comment by sucofog** [comment]
SQL still did not upload? :P

**Comment by sucofog** [comment]
Tested, compiled fine, big errors due to soundID's, Gossips, etc.

DB Errors  🗡 : 

image

http://pastebin.com/TW2UEiFW

image

**Comment by HeartWell** [comment]
Miss sql for db.

**Comment by sucofog** [comment]
It also did NOT:

- No translated items locales
- No translated quest locales
- No translated creatures locales
- No translated commands locales
- No translated achievement reward locales

IT did translated:

- Most Gossips locales
- Most NPC Page Texts locales

Still testing more.

**Comment by cooler-SAI** [comment]
try use sql files for locales from this repo
https://bitbucket.org/pak3935/sunwellcore/src/323de62159685b97317d3706ced08bc617936add/sql/world%20updates/?at=master

**Comment by HeartWell** [comment]
These sql just take with TC. Entry does not match, and you get a lot of database errors.

**Comment by cooler-SAI** [comment]
@HeartWell , I know that you have already Sunwell core with locales, way be you can help here? share your skills

**Comment by sucofog** [comment]
I did @cooler-SAI , this screenshots are errors from the SQL's of https://bitbucket.org/pak3935/sunwellcore/src/323de62159685b97317d3706ced08bc617936add/sql/world%20updates/?at=master

@Blumfield gave me the link to SQL, anyways with the correct SQL's (existent ones of pak3935) these errors are becouse scripts/core does not match with UPDATED database, i think its not a problem of the SQL, its of the core.

Correct me if i'm mistaken @HeartWell @Blumfield

**Comment by sucofog** [comment]
@HeartWell You have a better solución and not share? Why? 😕😮

**Comment by HeartWell** [comment]
I can not share, but happy to help.

**Comment by Blumfield** [comment]
@sucofog I'm well aware it doesn't translate everything, there is so much more to backport from TC and it's time consuming, the SQLs have to be redone by someone too.

I do not understand you @HeartWell, you say you wish to help but refuse to share the code for some reason, if you did share the code we would be fixing something more important right now ! it annoys me to know someone has it working but won't make a PR for it.... make me wonder if I should bother sharing my work...

**Comment by sucofog** [comment]
@Blumfield Its a very nice work, you know a lot better what you doing, dont take my bad, just pointing hehe, and yes, i wonder why HeartWell does not share locales, i dont really understand, locales are done in Trinitycore, it's not a secret new script or function, if i knew more programming i would be colaborating more but im newb at this, learning from guys like you.

**Comment by ShinDarth** [comment]
I would remind that this project is released under GPL/AGPL so all the code should be shared (unless part of external modules)...

**Comment by HeartWell** [comment]
I have the right not to share code, the GPL/AGPL uses azeroth, and I don't use it.

**Comment by sucofog** [comment]
Then if developers or people here make a fix and you take it to a non GPL/AGPL project like yours, whats that?
Anyways SunwellCore converted to GPL/AGPL, you got now a non GPL/AGPL project that comes from TrinityCore/Mangos that its a GPL/AGPL code.
I mean.. i don't get the point, you don't want to share code  becouse you have the right.. well wtf lol.

**Comment by HeartWell** [comment]
SunwellCore was not free code and even now, as it was in private development. I do not use SunwellCore in the same way as you, you have only a fork he him.

**Comment by HeartWell** [comment]
And if you go on sunwell.pl where was given to the core of the surprised, because he ceased to be open-source.

**Comment by cooler-SAI** [comment]
I see 2 way here, @HeartWell : 
1) you can make new commits, based on azerothcore source and make PR for us ( you will be a good guy)
2) if you don't wanna make new commits for azerothcore, but you have well worked locales and don't wanna share your commits from private repo ( repo, whoes use GPL TrinityCore ), so, please don't say people about your achievments, shut up and use your NON GPL source in silence. we don't wanna read here how you are TBE BEST ASS CHIELD CODER. Thanks anyway

**Comment by sucofog** [comment]
@cooler-SAI Don't be so rude man, if he does not want to share code we cannot say more, its his choice.

**Comment by HeartWell** [comment]
@cooler-SAI чувак мне насрать на твоё мнение, можешь запихать его в свой жирный зад. О великий разработчик пытающийся в конфиге переключить мир на русский язык)

**Comment by sucofog** [comment]
@HeartWell It's okay man it's your choice but at least, you should help so we get locales.. you don't want to share code, its ok then but you're a contributor of this project for something, don't insult and help, i don't know any shit programming compared to all of you, but if someone asks for spanish translations of all core or i see some good code that could be implemented to azeroth to make this work better than its now, i will, you should do same....

**Comment by sucofog** [comment]
The moral of this is that if you don't want to share code, at least help us to get it working, we don't steal nothing, we ask for it.

**Comment by cooler-SAI** [comment]
@HeartWell , kiss my Ass)))))) долбаёб ты)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

**Comment by cooler-SAI** [comment]
@sucofog , leave him alone, he is asshole

**Comment by HeartWell** [comment]
@cooler-SAI или правь конфиги жирненький ты наш) Мозгов только на это хватит)

**Comment by cooler-SAI** [comment]
@HeartWell , иди нахуй,,школота задротская)  очкарик-девственник)пиши там коды,,..распиздатый ты наш)

**Comment by HeartWell** [comment]
@cooler-SAI больше запятых) не агрись толстый) ПМС пройдёт у тебя это временно)

**Comment by ShinDarth** [comment]
All MaNGOS/TrinityCore based project are GPL and the license cannot be changed into private.

However, I'm glad that @HeartWell  is here to help even if for some reasons he is not allowed to share part of his code.

I don't understand russian, please use english and discuss about this PR, not about other issues.

**Comment by sucofog** [comment]
That's it @ShinDarth

**Comment by cooler-SAI** [comment]
@HeartWell школьничег, смотри лучше порнушку и дай дядям тут дела делать важные) иди погуляй лучше) синдром распиздатости не лечится? - ну да......случай запущенный)

**Comment by Blumfield** [comment]
Wait for @HeartWell  PR, closing this one

**Pull request closed without merging**
