### PR TITLE
fix(CORE): fix arm compile on macOS

### PR DESCRIPTION
**Pull request by motivewc**
## Changes Proposed:
-  Use ARM friendly replacements for AVX instructions, fixes argon2 compile.

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3720

## Tests Performed:
- Built from source on macOS Ventura 13.2 on ARM Mac

## How to Test the Changes:
1. Build it on an M1 Mac 
2. ??
3. Profit

## Known Issues and TODO List:
No known issues, I have tested in-game.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by motivewc** [comment]
Original Error:
```
[  2%] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourNode.cpp.o
[  2%] Building CXX object deps/recastnavigation/Recast/CMakeFiles/Recast.dir/Source/Recast.cpp.o
[  2%] Building CXX object deps/fmt/CMakeFiles/fmt.dir/src/format.cc.o
In file included from /Users/motivewc/Development/azerothcore-wotlk/deps/argon2/argon2/opt.c:26:
In file included from /Users/motivewc/Development/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:23:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/emmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
In file included from /Users/motivewc/Development/azerothcore-wotlk/deps/argon2/argon2/opt.c:26:
In file included from /Users/motivewc/Development/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/emmintrin.h:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/xmmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
In file included from /Users/motivewc/Development/azerothcore-wotlk/deps/argon2/argon2/opt.c:26:
In file included from /Users/motivewc/Development/azerothcore-wotlk/deps/argon2/argon2/blake2/blamka-round-opt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/emmintrin.h:17:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/xmmintrin.h:17:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/mmintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"
#error "This header is only meant to be used on x86 and x64 architecture"
 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/mmintrin.h:54:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size


```

**Comment by Kitzunu** [comment]
This breaks Windows build.

**Comment by eyeofstorm** [comment]
__x86_64__ not defined at windows platform.

**Comment by acidmanifesto** [comment]
Status?

**Comment by acidmanifesto** [comment]
PR abandoned

**Pull request closed without merging**
