### PR TITLE
fix(DB/Creature): ICC Saurfang correct model

### PR DESCRIPTION
**Pull request by r0m1ntik94**
## CHANGES PROPOSED:
- PARTIALLY fix issue #3246 

## TESTS PERFORMED:
- Tested on Ubuntu 18.04

## HOW TO TEST THE CHANGES:
Apply SQL and restart server

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Thank you!

however it's a bit misleading as it fixes only a part of the issue, not the entire issue

**Comment by Voxstrasza** [comment]
> 
> 
> Thank you!
> 
> however it's a bit misleading as it fixes only a part of the issue, not the entire issue
> 
> Unless I didn't understand

You are correct as I said in the other thread; this corrects the model but does not despawn the NPCs after the event

**Comment by FrancescoBorzi** [comment]
still good to be merged IMHO

good job @r0m1ntik94 !

**Comment by pklloveyou** [comment]
Why not?
```sql
UPDATE `creature` SET `modelid` = 30583 WHERE `id` = 32315;
```

**Pull request merged**
