### PR TITLE
fix(DB/Creature): Dustbelcher NPC MovementType 2.0

### PR DESCRIPTION
**Pull request by ArthurXL2G**
- Errors generated in the worldserver console were: 
`WaypointMovementGenerator::LoadPath: creature Dustbelcher Wyrmhunter (GUID Full: 0xf130000a9c0016b7 Type: Creature Entry: 2716  Low: 5815) doesn't have waypoint path id: 0`

- #16499
 There is still a small omission:

1. `Dustbelcher Wyrmhunter` id1=2716
2. id1=2907, it's `Dustbelcher Mystic`
3. `Dustbelcher Wyrmhunter` with two guid 6973 and 6975

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Addresses an issue found in #16499
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17618

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.the database import and run

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Does this close any open issue?

**Comment by icemansparks** [comment]
> Does this close any open issue?

As far as i can see it should address my issue reported in #17618

**Comment by ArthurXL2G** [comment]
> > Does this close any open issue?
> 
> As far as i can see it should address my issue reported in #17618

Yep

**Comment by Kitzunu** [comment]
When you fix something that should close an issue, you must add `Closes #issueNumber` either in the commit description or Issues Addressed in the PR template.

It will ensure the issue gets closed when the PR is merged. I have fixed it for this one

image

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Thank you for the PR

**Pull request merged**
