### PR TITLE
Core/Player: Fix all apply item mods for scale

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
Co-authored-by: Yehonal <yehonal.azeroth@gmail.com>

##### CHANGES PROPOSED:
-  

##### TESTS PERFORMED:
- [x] Test in-game
- [x] Test in build

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
I have merged it, how to test

**Comment by Yehonal** [comment]
You should just test that when you equip/unequip an item, all bonuses and stats are removed and applied correctly

**Comment by pklloveyou** [comment]
Okay.

**Comment by pklloveyou** [comment]
Tested, pictured，

**Comment by FrancescoBorzi** [comment]
excellent @pklloveyou

**Comment by Stoabrogga** [comment]
Could someone please tell me what is fixed here so I can first reproduce the error without this PR? @Winfidonarleyan It would be great if you could add more information to your PRs so it is easier to understand what the error is and how it is fixed.

**Comment by Winfidonarleyan** [comment]
That's a need to ask @Yehonal.

**Comment by Yehonal** [comment]
> Could someone please tell me what is fixed here so I can first reproduce the error without this PR? @Winfidonarleyan It would be great if you could add more information to your PRs so it is easier to understand what the error is and how it is fixed.

It's not a "fix" but an improvement
I'm working on a module that is able to scale up and down your equip (any kind of item) such as an heirloom, but _ApplyAllLevelScaleItemMods only applies bonuses and not all mods (that contains bonuses). This because there are no real case in game where items must scale mods (enchantments, sockets etc.) but only bonuses.

Reapply mods doesn't break anything but it's a more complete way to handle an item scaling

**Comment by pklloveyou** [comment]
If the function in the game can be divided into multiple exe program like "for example, the authentication server and the server as the world", the separation of a function in the game " such as auction houses, banks and so on.。"Blizzard should do this, a crash does not affect other functions, do not know the translation can not understand, because too much.

**Comment by Stoabrogga** [comment]
@Yehonal 
Ok, understood. Thanks for the explanation.

**Pull request merged**
