### PR TITLE
fix(DB/Spell): Deep Freeze

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
- Deep Freeze will now stun targets properly
- Deep Freeze will now only deal damage to targets immune to stun

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6616

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. Learn Deep Freeze from talent
2. Freeze an enemy, presumably with Frost Nove
3. Cast Deep Freeze
4. Repeat with an enemy immune to stun

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
Deep freeze should only deal damage to targets that are permanently immune to coma,There should be no damage in PVP!

After testing, it still does damage to players

**Comment by Kitzunu** [comment]
How did you test? So I can test that too

**Comment by Kitzunu** [comment]
According to https://www.elitepvpers.com/forum/wow-guides-templates/503791-frost-mage-pvp-begginers-guide.html deepfreeze can be used in pvp

**Comment by mpfans** [comment]
> How did you test? So I can test that too

A Rogue duels with a mage ,when mage  have `Fingers of Frost` (spell id 44544),rogue use item(id 5634) ,mage cast `Deep freeze` ,can cause damage

**Comment by mpfans** [comment]
> According to https://www.elitepvpers.com/forum/wow-guides-templates/503791-frost-mage-pvp-begginers-guide.html deepfreeze can be used in pvp
I checked a lot of documents, because it's Chinese, I won't put it here,blizzard in the 3.0 test server , it does cause PVP damage. But the actual line did not damage!
Then blizzard in version 3.3,add `Deals 1469 to 1741 damage to targets permanently immune to stuns.`

https://wowwiki-archive.fandom.com/wiki/Patch_3.3.0
December 8, 2009

`Frost
[Deep Freeze]: This spell now deals a large amount of damage to targets permanently immune to stuns. In addition, when this ability deals damage it will no longer consume two charges of Fingers of Frost for those mages with the Shatter talent.`

**Comment by SKingOWN** [comment]
I test it in PvE with a non inmune normal creature it work fine (No damage), with a Dungeon Boss (inmune) it make a lot of damage, about 10k-15k.
Note: the inmunity check is fine, the amount of damage that make is other problem added in https://github.com/azerothcore/azerothcore-wotlk/pull/6015

**Comment by mpfans** [comment]
We all know that players can't be immune to coma forever, only boss and vehicle(example:wintergrasp's demolisher) can

**Review by SKingOWN — APPROVED** [review]
I test the inmunity check ingame and works fine.

**Comment by mpfans** [comment]
> I test the inmunity check ingame and works fine.

I agree, but there are bugs I mentioned

**Comment by pklloveyou** [comment]
Tested

**Comment by Kitzunu** [comment]
It at least fixes the issues with mobs.

We have to investigste further about pvp. So the purpose of this PR is done and gtg.

**Comment by Kitzunu** [comment]
@FrancescoBorzi you need to review before removing label lol

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi you need to review before removing label lol

yeah I did, just forgot to actually push the button :)

**Comment by Voorh** [comment]
> It at least fixes the issues with mobs.
> 
> We have to investigste further about pvp. So the purpose of this PR is done and gtg.

related to PvP is perfect!! only problem at the moment is the high damage on Boss, it's pretty high.

**Comment by mpfans** [comment]
> > It at least fixes the issues with mobs.
> > We have to investigste further about pvp. So the purpose of this PR is done and gtg.
> 
> related to PvP is perfect!! only problem at the moment is the high damage on Boss, it's pretty high.

Boss's damage is normal. Because it will enjoy the bonus of spell strength. PVP does no damage!

**Comment by Voorh** [comment]
> > > It at least fixes the issues with mobs.
> > > We have to investigste further about pvp. So the purpose of this PR is done and gtg.
> > 
> > 
> > related to PvP is perfect!! only problem at the moment is the high damage on Boss, it's pretty high.
> 
> Boss's damage is normal. Because it will enjoy the bonus of spell strength. PVP does no damage!

Exactly, PvP is normal, Pve too, but it is doing a lot of damage to the bosses

**Pull request merged**
