### PR TITLE
fix(docker): grabled cjk characters in docker

### LINKED ISSUE #1891: A TOO BIG BUG：服务端提供的DBC有问题，中国和台湾的客户端显示任何物品和NPC全部乱码！
A TOO BIG BUG：服务端提供的DBC有问题，中国和台湾的客户端显示任何物品和NPC全部乱码！

Google Translate：There is a problem with the DBC provided by the server. The clients in China and Taiwan show that all items and NPCs are garbled!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74666872-a-too-big-bug-dbc-npc?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by leopku**
fixed #1891. grabled cjk characters in docker

##### CHANGES PROPOSED:
-  fixed #1891. grabled cjk characters in docker

##### ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1891

##### TESTS PERFORMED:
-
-

##### HOW TO TEST THE CHANGES:
 - Install an instance with Docker following http://www.azerothcore.org/wiki/Install-with-Docker
 - Check characters
    - Connect to database with `utf8_general_cli`, check cjk characters
    - Log into game using Chinese game client, check name of NPC or equip

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@pklloveyou can you please have a look here?

**Comment by pklloveyou** [comment]
I have it working fine. no problems.，

**Comment by FrancescoBorzi** [comment]
good job @leopku @pklloveyou

**Comment by leopku** [comment]
> good job

My pleasure.

**Pull request merged**
