### PR TITLE
fix(Core): Quest Question marks

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Imported logic from Trinitycore with a few tweeks for Azerothcore

## Issues Addressed:

- Closes part of #7897 
- Closes part of #8151
- Closes https://github.com/chromiecraft/chromiecraft/issues/2535

## SOURCE:

Several quests that are repeatable should have a Blue Question mark. This can be seen in loads of videos on classic wow.
Imported from and adapted https://github.com/TrinityCore/TrinityCore/pull/23338

## Tests Performed:

- Tested on Windows 10

## How to Test the Changes:

1. Follow instructions on #7897 and see that the Dwarf has a blue question mark
2. Follow instructions on https://github.com/chromiecraft/chromiecraft/issues/2535 and check for the blue question mark
3. Follow the instructions on the issue fixed by the Trinitycore PR.
4. .go c id 25580 (Learn fishing on any capital first and check for the blue "!")
5. .go c id 20735 : Should have lvl 80 for this weekly and a yellow exclamation mark.

## Known Issues and TODO List:

- [x] daily must have blue "!" -- 11665
- [x]  weekly must have yellow "!" -- 24583

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
@azerothcore/testers I need feedback on this pull request

**Comment by tkn963** [comment]
I'm testing this as we speak, but I'm having some issues. The warsong report works fine, but I'm currently on https://github.com/azerothcore/azerothcore-wotlk/issues/7897 and the unguarded barrel you have to click after distracting the guard doesn't switch with the guarded barrel but they overlap which caused confusion for me. The barrel also has a yellow ! above it. The guard himself has a blue ? though. I'm currently on the Onu issue.

**Comment by tkn963** [comment]
I'm running the quest in Kharanos again just to make sure I wasn't confused, but yeah the barrel has a yellow ? on top of it at all times and they're both there (guarded and unguarded) - I'm sure this is why it's "part of". Like I said however, the guard has the proper blue ? above his head.

**Comment by tkn963** [comment]
The npc named Onu, after accepting "The Master's Glaive" from him, has no mark above his head at all. He also offers the quest "Onu is Meditating" after completing all quests he offer (up to and including "Mathystra Relics".

**Comment by tkn963** [comment]
Also after accepting the master's glaive from Onu, the quest offered (without any mark above his head) is a yellow ! to get a new item.

The fishing NPC (step 4) has a blue ! above his head as intended.
The weekly quest (step 5) has a yellow ! above his head as intended.

**Comment by tkn963** [comment]
I see what the problem is with Onu. The quest can be red, yellow, green or gray and it still counts as low-level for me. That's why it doesn't show up as a mark above his head. Regardless, the quest is available after completing the quests he gives.

**Comment by claudiodfc** [comment]
@tkn963 thank you very much for the test cases. About Kharanos, yes the script still has to be changed as this only partially fixes the quest. 

About Onu, I have another PR #9817 that should fix this issue, which is just conditions for his quests. Can you try testing both PRs at the same time? Thank-you very much once again.

**Comment by tkn963** [comment]
> @tkn963 thank you very much for the test cases. About Kharanos, yes the script still has to be changed as this only partially fixes the quest.
> 
> About Onu, I have another PR #9817 that should fix this issue, which is just conditions for his quests. Can you try testing both PRs at the same time? Thank-you very much once again.

Absolutely, I'll get right on it. I have to compile the source again though since I reset it thinking the other PR wasn't just a SQL update. As soon as it's done, I'll get to it.

**Comment by tkn963** [comment]
With both of these PRs, the Onu quest works like a dream. 👍

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
