### PR TITLE
Move spline fix (hopefully)

### LINKED ISSUE #309: Worldserver.exe is running, suddenly crashes
**Crashe files download**: http://www.filedropper.com/crashes

**Description**: Worldserver.exe is running, suddenly crashes.

**Current behaviour**: Suddenly crashes.

**Expected behaviour**: Suddenly crashes.

**Steps to reproduce the problem**: Suddenly crashes.

**Branch(es)**: master

**AC hash/commit**:  Update at https://github.com/azerothcore/azerothcore-wotlk/commit/bd9b4e84b6b075ff3f526050511e290d02ff5ce1

**Operating system**:  Windows Server 2008 64bit

**Modules**:  Customize transmog

**Other Customizations**: Use AC official

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)
c

### PR DESCRIPTION
**Pull request by talamortis**
**Changes proposed:**

-  Stop crash from Movespline 
-  
-  

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:** Closes #309 

**Tests performed:** (Does it build, tested in-game, etc)

tested and builded ok, just needs further testing.

**Known issues and TODO list:**

- [ ] 
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Inifield** [comment]
That won't fix it

**Comment by talamortis** [comment]
worth a try though :)

**Comment by rre-za** [comment]
when exactly this crash happen ?

**Comment by talamortis** [comment]
probly about a week after the server has started 👍

**Comment by rre-za** [comment]
i meant , how to re-produce the crash ?

**Comment by sucofog** [comment]
If it's random it's very difficult to reproduce lol, did you tried this @talamortis ?

**Comment by talamortis** [comment]
my server is not on long enough to test so no I did not

**Pull request closed without merging**
