### PR TITLE
Core/Hooks: Add new Player hooks

### PR DESCRIPTION
**Pull request by brussens**
##### CHANGES PROPOSED:

- Fix hook OnReputationChange
- Add hook OnReputationRankChange
- Add hook OnLearnSpell
- Add hook OnForgotSpell

##### TESTS PERFORMED:
Test in game

##### HOW TO TEST THE CHANGES:
1. Create the custom PlayerScript shown below
1. Enter in world
1. Learn spell and see in console
1. Unlearn spell and see in console
1. Change any faction reputation on val < 1000 and see in console
1. Change any faction reputation on val > 3000 and see in console

```cpp
class MyPlayer : public PlayerScript
{
public:
    MyPlayer() : PlayerScript("MyPlayer") { }

    void OnReputationChange(Player* player, uint32 factionID, int32& standing, bool incremental)
    {
        sLog->outError("The reputation of the %u faction %u changed.", factionID);
    }

    void OnReputationRankChange(Player* player, uint32 factionID, ReputationRank newRank, ReputationRank oldRank, bool increased)
    {

        if (increased)
            sLog->outError("The reputation RANK of the %u faction is enhanced", factionID);
        else
            sLog->outError("The reputation RANK of the %u faction has fallen", factionID);
    }

    void OnLearnSpell(Player* player, uint32 spellID)
    {
        sLog->outError("Player learned spell %u", spellID);
    }

    void OnForgotSpell(Player* player, uint32 spellID)
    {
        sLog->outError("Player forgotten spell %u", spellID);
    }
};
```

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
good job @brussens

**Comment by brussens** [comment]
@FrancescoBorzi Thanks)

**Comment by brussens** [comment]
@poszer Thanks)

**Comment by BarbzYHOOL** [comment]
nice

**Pull request merged**
