### PR TITLE
close https://github.com/azerothcore/azerothcore-wotlk/issues/119

### PR DESCRIPTION
**Pull request by cooler-SAI**
**Changes proposed:**

-  
-  
-  

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc)

**Known issues and TODO list:**

- [ ] 
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Yehonal** [comment]
This file is not valid for our procedure. You need to follow our wiki to
create pending sql, just 2 steps

Thank you

Il 05/Ott/2016 23:47, "Ander" <notifications@github.com> ha scritto:

**Comment by cooler-SAI** [comment]
what's a problem with 1 little sql file fix? It's not a BIG proble, add this to oyur repo - why I must read this big manuals how copy-paste a little fix? fuck this shit, forget.... I close it.

**Comment by Yehonal** [comment]
Big manual?

as i said there are just few step:

1. go into data/sql/updates and choose the pending folder of the database that you have to create the sql file.

2. run the create_sql.sh script with your bash console ( git bash on windows, the terminal on unix / osx )

3. now you'll have a file called rev_[a_long_number].sql , you can open it and add your queries

4. commit and push. If you are not a dev now you've to create the PR.

it requires just 2 minutes to read & learn. It's an educational project. We are not your slave that must take your dirty things and convert it to keep it clean with this project standards. Various people before you did it without any problems:

https://github.com/azerothcore/azerothcore-wotlk/commit/3356a712c3e0d8346ab76bca5ccf57406c0b8216

@talamortis can confirm.

**Comment by Dokman** [comment]
@Yehonal @cooler-SAI Please just Keep calm and listen to mozart.
Relax all your asses is bad for your ass to keep in fury

**Comment by Dokman** [comment]
@cooler-SAI Please keep calm a do right things, here we are to develop freely and because we want, so please keep the things of the other people, because if your respect them, they will respect you

**Pull request closed without merging**
