### PR TITLE
fix(DB/Quest): Lessons Anew

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Fix horde and alliance text on compeltion

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5799

## Tests Performed:

- none 

## How to Test the Changes:

1. Not needed, but turn in the quest. (Delete cache)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Branel** [comment]
I get the alliance text while being a tauren druid, and the same on a night elf, horde text does not show.

**Comment by Kitzunu** [comment]
Can you check which Quest ID you get?

6126 horde
6121 ally

**Comment by Branel** [comment]
My bad. Will edit once I test again.

**Comment by Branel** [comment]
Tested and it works, just got the ID wrong the first time.

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
