### PR TITLE
fix(Core/Movement: Creatures should not cast while moving.

### LINKED ISSUE #8843: NPCs can cast atleast aoe spells while flee
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/1831

Defias Evoker (https://wowgaming.altervista.org/aowow?npc=1729) was able to cast Flamestrike(https://wowgaming.altervista.org/aowow?spell=11829) whilst fleeing. This happened multiple times in the dungeon.

clip: https://medal.tv/clips/65788661/d13379GyEvLL

Tester:

The issue is confirmed. NCPs can cast atleast aoe spells while flee. Tested blizzard and flamestrike.

https://user-images.githubusercontent.com/85256266/139557373-19555a3b-4f84-4292-9943-a650b6e61f14.mp4

https://user-images.githubusercontent.com/85256266/139557367-a5f64fec-a682-4066-907e-39bfb4aa606b.mp4

### Expected Blizzlike Behaviour

I guess noone can cast while moving,

### Source

X

### Steps to reproduce the problem

choose any npc with aoe and flee
look when he is casting aoe
get him to flee 1 second before aoe

.do c id 16977 - Arch Mage Xintor
agro 
.damage 5000 while is casting fireball.
look to npc 

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #8843

## Issues Addressed:

- Closes #8843
- Closes https://github.com/chromiecraft/chromiecraft/issues/1831

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/8843)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FlamePrince** [comment]
Just tested this, and I found the following:

- Flamestrike and Fireball cancalled 100% of the time upon fleeing. Tested other casters in the deadmines to ensure there were no follow up issues.

- Blizzard cancels roughly 90% of the time. Using GM's dmg, I was able to slowly reduce HP and it seemed that when the creature initiates fleeing **just** as (or a second before) the cast, the blizzard continues. It missed every time, and did not cast for the full duration.

- Unsure if it is related, but Arch Mage Xintor (16977) will not cast whatsoever after depeleting his mana. As soon as his mana bottoms out, he will continue to melee even if his mana is full or the player is at distance.

https://imgur.com/a/FCbESok

**Comment by FlamePrince** [comment]
Just tested this, and I found the following:

- Flamestrike and Fireball cancelled 100% of the time upon fleeing. Tested other casters in the deadmines to ensure there were no follow up issues.

- Blizzard does not always cancel. See video for info.

- Unsure if it is related, but Arch Mage Xintor (16977) will not cast whatsoever after depeleting his mana. As soon as his mana bottoms out, he will continue to melee even if his mana is full or the player is at distance.

https://imgur.com/a/FCbESok

**Comment by UltraNix** [comment]
`Unsure if it is related, but Arch Mage Xintor (16977) will not cast whatsoever after depleting his mana. As soon as his mana bottoms out, he will continue to melee even if his mana is full or the player is at distance.`
It's not related to this PR.

**Comment by UltraNix** [comment]
@FlamePrince Try now.

**Comment by FlamePrince** [comment]
> @FlamePrince Try now.

Testing, will update soon.

**Comment by FlamePrince** [comment]
> @FlamePrince Try now.

If you interrupt Xintor casting fireball, there is a chance he will cast blizzard on himself instead of fleeing.

https://imgur.com/a/pwA6ofE

**Comment by UltraNix** [comment]
@FlamePrince This is okay - this is how his script works.

**Comment by FlamePrince** [comment]
> @FlamePrince This is okay - this is how his script works. But no longer moves when casting.

Got it! I'd like to go regression testing on an escort quest to make sure the changes to NPC behaviour don't affect that, but otherwise everything looked great. I've since unloaded this PR but I'll get it done by tonight if no one else does.

**Pull request merged**
