### PR TITLE
DB - Deadmines - Add missing waypathes to some patrols

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Thanks to @Cillez from Renegade-WOW

**Changes proposed:**

-  Add missing waypathes for some patrols (But the query to activate the waypath is not included as of now.)

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:**
https://github.com/azerothcore/azerothcore-wotlk/issues/820

But there might be more mobs to fix in the instance

**Tests performed:** (Does it build, tested in-game, etc)
None myself.
Need to init the waypath with `.wp load xxxx`

**Known issues and TODO list:**

- [x] Test ingame these creatures with ".go creature xxxx" where xxxx is the guid from
```2018-03-29 12:53:36 ERROR: WaypointMovementGenerator::LoadPath: creature Defias Overseer (Entry: 634 GUID: 2175191) doesn't have waypoint path id: 0
2018-03-29 12:53:36 ERROR: WaypointMovementGenerator::LoadPath: creature Defias Overseer (Entry: 634 GUID: 2175222) doesn't have waypoint path id: 0
2018-03-29 12:53:42 ERROR: WaypointMovementGenerator::LoadPath: creature Defias Taskmaster (Entry: 4417 GUID: 2175263) doesn't have waypoint path id: 0
2018-03-29 12:53:42 ERROR: WaypointMovementGenerator::LoadPath: creature Defias Overseer (Entry: 634 GUID: 2175357) doesn't have waypoint path id: 0
```
- [ ] In the original issues, there are 6 creature GUIDs missing waypath
- [ ] Find other bugged patrols
- [ ] Export the query after `.wp load xxxx` (so the patrol starts at server reboot automatically)

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Motorheadx** [comment]
tested and it works fine

**Comment by Knindzagxg** [comment]
Tested.

Working pretty good now.

**Comment by BarbzYHOOL** [comment]
It doesn't require to ".wp load xxxx" ?? if it does please someone export the related SQL :D 

And can someone just quickly run through the instance and check the patrols ? then look at the console and see if some errors are popping

**Comment by Motorheadx** [comment]
Need to use .wp load, there are other patrols that do not go not only on the track at the boss

**Comment by BarbzYHOOL** [comment]
Ok then we need to complete these tasks first

**Comment by Cillez** [comment]
You can use this: 
`REPLACE INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES (634, 793730, 0, 0, 0, 0, NULL);`
This will make them patrol automatically without doing .wp load. 
Not sure if Azerothcore prefer the sql query to be 
`UPDATE `creature_template_addon` SET `path_id` = 793730 WHERE (entry = 634);`
Since there already is a row in creature_template_addon for entry 634
Tested locally, works.

**Comment by BarbzYHOOL** [comment]
The update should do it, I'll update the file.

But it's only targeting the patrol leader, what if he dies and the whole group of players wipes. Then they come back and the remaining mob doesn't patrol anymore?

Is it the right way to do it?

**Comment by Cillez** [comment]
Thinking about it, if there are other npc in the dungeon with entry 634, they will all be assigned that path id, so maybe not the best way to do it after all. Updated post with this information to warn people-

**Comment by Motorheadx** [comment]
there are other this id patrols , for this we need additional ways

**Comment by BarbzYHOOL** [comment]
Ok, we just need to replace the GUID of the creatures in this:

```
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(2018497,	51460,	0,	0,	0,	0,	NULL),
(2018497,	51460,	0,	0,	0,	0,	NULL);
```

But there are probably more patrols not working in the deadmines

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL what is the status of this? still WIP or needs something else (e.g. testing) ?

**Comment by BarbzYHOOL** [comment]
Ok Cillez disappeared so I guess I have to fix this :(

also travis modified the PR and I don't know why/how o_0

**Comment by Pondaveia** [comment]
@BarbzYHOOL Kill this one man, this PR is so old 😛

**Comment by poszer** [comment]
Closing this, new pr ready for testings https://github.com/azerothcore/azerothcore-wotlk/pull/1808

**Pull request closed without merging**
