### PR TITLE
feat(Core/Entities): Enabled loading basic stats for players, pets an…

### LINKED ISSUE #12386: Feature: 32 bit stats for players and pets (currently 16 bit) [$100]
### Describe your feature request or suggestion in detail

Hello

DISCLAIMER: I didn't test each class and each pet so i can't say for sure that this applies to all stats but probably it does.

So as title says currently all stats (except damage but that's not really a stat) are 16 bit so for example if player gets more than 65535 crit it overflows and reset to 0. I'm not sure if AC is supposed to be blizzlike focused or universal because if blizzlike then this change has no meaning no benefit and only causes slightly more RAM usage and that would influence decision if this will be accepted. However that impact is probably negligible.

I'm not exactly sure how to do it but i think it just requires to go through code and change type of variables related to stats to int 32 and then test ingame that it works for all player and pet stats.

This will be placed as bounty. Thank you.

### Describe a possible solution to your feature or suggestion in detail

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…d items from database as 32 bit integers.

Closes #12386

## Issues Addressed:

- Closes #12386

## Tests Performed:

- Tested ingame.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@MellianStudios Please, test it.

**Comment by benjymansy123** [comment]
Does this not require a client side change to display properly?

**Comment by UltraNix** [comment]
@benjymansy123 No. Just remove your Cache folder.

**Comment by MellianStudios** [comment]
@UltraNix

hello thank you for your effort so far

I did in-game testing. Testing was done by creating bunch of items which had stat values at breakpoints small int, unsigned small int and over unsigned small it specifically 32767, 65535 and 50000000 i checked players stats and some pet stats. It was not 100% tested so far especially pets because it require quite a lot of time to test all possibilities.

For anybody interested in this issue if you want to replicate it and test it this PR so far doesnt include alter of table item_template for columns stat_value1 - stat_value_10 and armor which are also small int and in order to allow creation of items with higher stats it needs to be changed. We could discuss whether is it in scope of this issue and should be included or not.

image
image

**Comment by UltraNix** [comment]
This table says nothing to me and it's confusing to me. I don't know if the problem described by you in the issue ticket is resolved or not by this PR.

**Comment by MellianStudios** [comment]
No it is not resolved

Table shows original limits and limits after applying your changes
Let's take haste as example originally when u got over 32767 haste it reset to 0 meaning it was small int with ur PR there is still same limit
Another example would be armor that is slightly more complicated. Originally armor had limit on items small int as any other item stat but the total amount player could have was limited either to int32 ur uint32 i'm not sure. Now after i changed it in DB column it is possible to create items with up to unsigned small it (65535) to be fair here i don't know if it's limited by server or client.

If it's still not clear let me know i will try to explain more

**Comment by UltraNix** [comment]
But stats like haste etc is not covered by this PR. You meant basis stats loaded from DB and this is resolved.

**Comment by MellianStudios** [comment]
I don't want to be mean but where did i say "basic" ? Even in issue description I'm using crit as example. I admin I could probably be more specific but I didn't expect such confusion

**Comment by UltraNix** [comment]
`Another example - armor that is slightly more complicated. Originally armor had limit on items small int as any other item stat`
No - now items have 32 bit integer values.

**Comment by UltraNix** [comment]
Stats like haste, parry, dodge, etc are floats, so by default are 32 bits.

**Comment by MellianStudios** [comment]
here you can see item with slightly less than uint16 armor
image

this is item with over uint16 (50M) as you can see it doesn't work
image

here are working examples with strength
image
image

and here are issues with for example crit
image
image
image

**Comment by UltraNix** [comment]
Yep - armor/resistance from items were still small int. Gonna change that.

**Comment by UltraNix** [comment]
About crit, hit haste etc:
WoWScrnShot_071722_142324
WoWScrnShot_071722_142326
WoWScrnShot_071722_142327
It works okay.

**Comment by MellianStudios** [comment]
how did you achieve it ?

**Comment by UltraNix** [comment]
Just modying in core. As you can see client correctly display 32 bits.

**Comment by UltraNix** [comment]
Hmm, I think I see where the problem is.

**Comment by MellianStudios** [comment]
no i mean in game you got item with those stats right ? i don't quite understand why it wouldn't work for me

**Comment by UltraNix** [comment]
@MellianStudios Plase, update with latest changes and test again. Should be okay now.

**Comment by MellianStudios** [comment]
I'm testing it and it seems working now but i will do some more testing later especially for pets just to be sure.

Meanwhile I would like to ask you because i don't really have opinion nor knowledge to answer it. Do you think this should also contain alter of item_template for stat_value1....stat_value10 and armor ?

**Comment by UltraNix** [comment]
Yes, it should.

**Comment by MellianStudios** [comment]
Then stat_value1 - stat_value10 are not yet in this PR

So far in testing I found small issue - attack power - when i get 50M strenght i get 50M power but when i get 50M attack power my dmg is increased but the value is reset to 0 so there is still small int limit somewhere

image
image

**Comment by UltraNix** [comment]
`Then stat_value1 - stat_value10 are not yet in this PR` They are already 32 bits. Just corrected their loading from DB.

**Comment by MellianStudios** [comment]
i meant DB columns those are small int and you didn't change it yet here
https://raw.githubusercontent.com/azerothcore/azerothcore-wotlk/master/data/sql/base/db_world/item_template.sql
`stat_type1` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value1` SMALLINT NOT NULL DEFAULT 0,
  `stat_type2` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value2` SMALLINT NOT NULL DEFAULT 0,
  `stat_type3` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value3` SMALLINT NOT NULL DEFAULT 0,
  `stat_type4` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value4` SMALLINT NOT NULL DEFAULT 0,
  `stat_type5` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value5` SMALLINT NOT NULL DEFAULT 0,
  `stat_type6` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value6` SMALLINT NOT NULL DEFAULT 0,
  `stat_type7` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value7` SMALLINT NOT NULL DEFAULT 0,
  `stat_type8` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value8` SMALLINT NOT NULL DEFAULT 0,
  `stat_type9` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value9` SMALLINT NOT NULL DEFAULT 0,
  `stat_type10` TINYINT unsigned NOT NULL DEFAULT 0,
  `stat_value10` SMALLINT NOT NULL DEFAULT 0,

**Comment by UltraNix** [comment]
It looks like:
```
stat_type1tinyint unsigned NOT NULL
stat_value1int NOT NULL
stat_type2tinyint unsigned NOT NULL
stat_value2int NOT NULL
stat_type3tinyint unsigned NOT NULL
stat_value3int NOT NULL
stat_type4tinyint unsigned NOT NULL
stat_value4int NOT NULL
stat_type5tinyint unsigned NOT NULL
stat_value5int NOT NULL
stat_type6tinyint unsigned NOT NULL
stat_value6int NOT NULL
stat_type7tinyint unsigned NOT NULL
stat_value7int NOT NULL
stat_type8tinyint unsigned NOT NULL
stat_value8int NOT NULL
stat_type9tinyint unsigned NOT NULL
stat_value9int NOT NULL
stat_type10tinyint unsigned NOT NULL
stat_value10int NOT NULL
```

**Comment by UltraNix** [comment]
@MellianStudios Done.

**Comment by MellianStudios** [comment]
thank you

I'm yet to verify few other pet related things but i can say that stats are working except power. Power for pets has same issue as player power it resets after 32767.

So as of now pet power and player power comming from attack power stat on items are int16

**Comment by UltraNix** [comment]
@MellianStudios By power, you mean mana/focus/energy?

**Comment by UltraNix** [comment]
Attack power for pets and for players (including from items) should be okay.

**Comment by MellianStudios** [comment]
Few messages ago i sent 2 screenshots of power (attack power) working from strength but not from attack power stat

**Comment by UltraNix** [comment]
So tell me how you increased ap for items.

**Comment by MellianStudios** [comment]
For pets i just equipped myself with items with 1M of each stats and checked what stats pet got out of that i notice power is pretty weird but its maybe only my lack of knowledge on how its calculated bcs when i got 1M of each stat i would expect my pet to have more than something like 15k power however i kept equipping items until power of pets reset to 0 after 32767

For players i just created item with attack power (stat id 38)

**Comment by UltraNix** [comment]
@MellianStudios Just tested - attack power mods (so attack power came from items or auras) is limited to 16 bits by client. Nothing I can do about it.

**Comment by MellianStudios** [comment]
does it apply to pet power too ?

**Comment by UltraNix** [comment]
Yep.

**Comment by MellianStudios** [comment]
Sadge

well thank you for your work i will deal with power myself

**Review by MellianStudios — APPROVED** [review]

**Review by MellianStudios — APPROVED** [review]

**Comment by Nyeriah** [comment]
image

Something went awry

**Comment by UltraNix** [comment]
@Nyeriah Weird - that column is in the table.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Do i need to explain the context or do you see it?

**Comment by Nyeriah** [comment]
Yeah, you renamed `nature_res` to `int`, there's a typo there

**Comment by UltraNix** [comment]
Oh I see now :)

**Comment by acidmanifesto** [comment]
Because this is linked to a bounty issue, we will need to ensure it is fully and independently tested first by other members of the community before i carelessly hit approve on a review. We had a number of past incidences of bounties being paid out to people for fixes that never worked, what made it painful is that we do not find out about it til many months later. I would like to ensure that does not happen again out of the respect of the user who created the bounty and for the azerothcore community.

**Comment by UltraNix** [comment]
@acidmanifesto The author of bounty already tested it. That was him that suggest that changes.

**Comment by acidmanifesto** [comment]
> @acidmanifesto The author of bounty already tested it. That was him that suggest that changes.

It was tested when the workflow was green a few days ago and few commits ago, not after with it going red for a few other reasons over the course of a few additional commits. Also we do not have the bounty information listed or linked in the issue. We need to ensure everything is covered.

**Comment by UltraNix** [comment]
`It was tested when the workflow was green a few days ago and few commits ago, not after with it going red for a few other reasons over the course of a few additional commits.`
Not true. It was tested after every single commit as you can see the conversation. The workflow has nothing to do testing this by @MellianStudios

**Comment by MellianStudios** [comment]
I tested it when it was red i fixed nature_res column for myself at that time and then i completely forget about it so I didnt say it before approving this PR :(

I have to say i didnt test each and every class and pet with all possible combinations on the other hand it depends how in depth you want tests to be because as we know you can never test every case

**Comment by acidmanifesto** [comment]
> I tested it when it was red i fixed nature_res column for myself at that time and then i completely forget about it so I didnt say it before approving this PR :(
> 
> I have to say i didnt test each and every class and pet with all possible combinations on the other hand it depends how in depth you want tests to be because as we know you can never test every case

If it is good and in line with your specifications then that will be fine. We just need to be a bit tighter with bounty posts because of issues i listed earlier. It has nothing to do with the author or you posting the bounty. Also I had to ping the git maintainers to ensure the bountysource bounty is propperly linked. if we merge and closed this issue and pr, i need to make sure the author of the PR is propperly credited for the bounty.

**Comment by MellianStudios** [comment]
Time of merge of this PR doesnt have any effect on my usage of it and as i said in feature request i dont even need it to be in AC core so its up to maintainers and contributors to deal with it. In bigger picture of AC and its users i would recommend to wait for further testing from other people just to verify i didnt miss anything. I dont need it to be merged now and most of people using AC are probably blizzlike servers which this feature has to value for so extra care is better in my opinion

**Comment by acidmanifesto** [comment]
> Time of merge of this PR doesnt have any effect on my usage of it and as i said in feature request i dont even need it to be in AC core so its up to maintainers and contributors to deal with it. In bigger picture of AC and its users i would recommend to wait for further testing from other people just to verify i didnt miss anything. I dont need it to be merged now and most of people using AC are probably blizzlike servers which this feature has no value for so extra care is better in my opinion
> 
> It may slow down payment but those money are effectively already yours @UltraNix

I got word that we are good on the issue and the bounty source. So i will go ahead and green light the review for merging.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Will merge if and when the workflow is all green.

**Comment by acidmanifesto** [comment]
- [x] Workflow is green.
- [x] PR independently tested from the PR Maker.
- [x] Bounty Poster states the requirements are met in. 
- [x] Bounty is linked to the issue and recognized and labeled.
- [x] Review is approved.

Thanks for the PR

**Pull request merged**
