### PR TITLE
fix(DB/SmartAI): Convert smartai stealth detection buff to Aura

### PR DESCRIPTION
**Pull request by BeefSteaker**
## Changes Proposed:
-  Instead of casting on respawn of similar, stealth detection 18950 is added via aura to creatures and their spawn addon
-  some Smartai shuffled around so that ID's are still sequential

## Issues Addressed:

- No issue, ive just been advised this is the better way to do it

## SOURCE:

https://github.com/azerothcore/azerothcore-wotlk/pull/13826#issuecomment-1313938911

## Tests Performed:

- teleported to mobs on local
- 

## How to Test the Changes:

1. go c 
(  3502, 4624, 9460, 11190, 12160, 14378, 15184, 16504, 16580, 16590, 16591, 16599, 17493, 17558, 17727, 17958, 18103, 19048, 19355, 19425, 19426, 19432, 19562, 19836, 22134, 24043, 25507, 27162, 30737 )
3. .list aura
4. SELECT \`entryorguid\` FROM \`smart_scripts\` WHERE \`action_param1\`=18950

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Maelthyrr** [comment]
All check and everything is fine. Aura is present. DB also check.

**Comment by heyitsbench** [comment]
Do we know that these affected creatures *don't* cast on respawn?

**Comment by Maelthyrr** [comment]
From what I have seen no. I recheck with few creatures and no cast on respawn.

**Comment by heyitsbench** [comment]
> From what I have seen no. I recheck with few creatures and no cast on respawn.

I more so mean is it blizzlike for these creatures not to cast on respawn.

**Comment by Maelthyrr** [comment]
@Gultask will probably answer better than me on this subject ^^

**Comment by Gultask** [comment]
Aura 18950 is not cast on respawn, no. It's not cast at all in sniffs, no SPELL_START or SPELL_GO, just an aura update after the object is created.
This behaviour of using SAI instead of addons is very present on AC and kinda pollutes the DB, imo.

**Pull request merged**
