### PR TITLE
fix(DB): Elwynn Forest ported from Trinitycore.

### PR DESCRIPTION
**Pull request by MathematicalWTF**
## Changes Proposed:
-  Ported: https://github.com/TrinityCore/TrinityCore/issues/18772

## Issues Addressed:

https://github.com/azerothcore/azerothcore-wotlk/issues/5654

## Tests Performed:

- I adapted several statements to AC and then ran them on the database to confirm errors.
- I saw the changes in the game.

## How to Test the Changes:

1. Run the sql on your database, then, go to the game and verify:
-- Mark (Little Boy Playing in Goldshire) -- BACKPORTED FROM UDB 4.3.4
-- Joshua (Little Boy Playing in Goldshire) -- BACKPORTED FROM UDB 4.3.4
-- Eastvale Peasant Carrying Wood (Closer) - Has Wood In Hand (Model 89 wood?) -- BACKPORTED FROM UDB 4.3.4
-- Guard Pathing From Stormwind to Goldshire
-- Catpurse Pathing Just Outside Northshire -- BACKPORTED FROM UDB 4.3.4
-- Catpurse Pathing at Bandit Hideout -- BACKPORTED FROM UDB 4.3.4
-- Stormwind Guard Pathing from Goldshire to East Bridge -- BACKPORTED FROM UDB 4.3.4
-- Kobold Miner Pathing in Fargodeep Mine -- BACKPORTED FROM UDB 4.3.4
-- Bandit Pathing at Brackwell Pumpkin Patch -- BACKPORTED FROM UDB 4.3.4
-- Eastvale Peasant Carrying Wood (Far One) - Does Not Have Wood In Hand -- BACKPORTED FROM UDB 4.3.4
-- Servant of Azora Pathing in Circle in Tower of Azora -- BACKPORTED FROM UDB 4.3.4
-- Murloc and Murloc Steamrunner Pathing Around Crystal Lake -- BACKPORTED FROM UDB 4.3.4
-- Eastvale Lumberjack in Eastvale Lumbermill -- Backported From UDB 4.3.4
-- Eastvale Peasant Carrying Wood (2 on Other Side) - Closer One -- BACKPORTED FROM UDB 4.3.4
-- Eastvale Peasant Carrying Wood (Lone One Near Road) - Does Not Have Wood In Hand -- BACKPORTED FROM UDB 4.3.4
-- Fix Spawn Locations For Some NPC
-- General Fix NPC Respawn Times - Existing Times Are Too Short For Almost All NPC

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by MathematicalWTF** [comment]
While waypoints are fixed here. The animations, sounds of the peasants and texts of the supervisor are not. @Krejza9

I tried various methods, but the little I could do was to have the peasants say:
"what ( is it )"
"More work"
"Ready to work!"
"Noone else available?"
"I guess I can"
"If you want..."
The sound of these npc's was very loud, so much so that all over Eastvale you could hear it, without needing to be with the supervisor.

Also, I added the effect of felling wood to the peasants, but unfortunately the emote never stopped, so I decided to eliminate it.

I also didn't make the supervisor say any text.

So, what I did was to port the coordinates + several changes from TC.

The changes I just mentioned I saved for the future, for the moment I am not going to add them.

**Comment by Krejza9** [comment]
> 
> 
> While waypoints are fixed here. Animations, peasant sounds and supervisor texts are not. @Krejza9
> 
> I tried various methods, but the little I could do was to have the peasants say:
> "what ( is it )"
> "More work"
> "Ready to work!"
> "Noone else available?"
> "I guess I can"
> "If you want..."
> The sound of these npc's was very loud, so much so that all over Eastvale you could hear it, without needing to be with the supervisor.
> 
> Also, I added the effect of wood chopping to the peasants, but unfortunately the emote never stopped, so I decided to eliminate it.
> 
> I also didn't make the supervisor say any text.
> 
> The changes I just mentioned I saved for the future, for the moment I am not going to add them.
> 
> So, what I did was to port the coordinates + several changes from TC.

I'll see what possibilities we have in ScriptedAI, maybe I'll find something

**Comment by T1ti** [comment]
Does UDP 4.3 means is from cataclysm ?

**Comment by Kitzunu** [comment]
https://github.com/UDB-434/Database
But I trust the changes as I have worked with Rushor before and he knows what he is doing. So if it is taken from UDB 4.3.4 there was either no information/sniffs found for 3.3.5 or has been verified somehow

**Comment by Krejza9** [comment]
The problem is that for example in Eastvale Logging Camp there are badly seeded WPs (they collide with each other, so there is a chance that several peasants will suddenly take the wood) + wander dittance on some creatures.
It needs to be reworked to ScriptedAI

**Comment by FrancescoBorzi** [comment]
wow.... UDB and @X-Savior , quite some history there.

**Comment by Nefertumm** [comment]
Any news on this?

**Comment by FrancescoBorzi** [comment]
what's the status of this PR?

**Comment by FrancescoBorzi** [comment]
@MathematicalWTF feel free to reopen this when you want to complete it. Closing for now.

**Pull request closed without merging**
