### PR TITLE
Core/Misc: Adding localization DBC.

### PR DESCRIPTION
**Pull request by DevRival**
- When you compile no errors , the game works well. 
- Proven in the Russian client.

### CODE REVIEW

**Comment by ShinDarth** [comment]
https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/World/World.cpp#L1951

**Comment by DevRival** [comment]
And?

**Comment by ShinDarth** [comment]
@DevRival I guess just wait @Yehonal to merge this, the project has just been created and no one else has the merge permissions :+1:

**Comment by Yehonal** [comment]
we're doing some re-organization to this project structure and starting to create a versioning system with roadmap etc.

We will include this feature directly in new version as soon as available. Please don't close it.

**Comment by DevRival** [comment]
Okey :+1:

**Comment by DevRival** [comment]
I also have a complete localization of the entire game world, if you need my help will be happy to help.

**Comment by ShinDarth** [comment]
@DevRival can you submit it via PR?

**Comment by DevRival** [comment]
Ops...

**Comment by DevRival** [comment]
@ShinDarth maybe later.

**Comment by ShinDarth** [comment]
@DevRival it's nice that you imported all those arena config stuff, but can't you open a separate PR for separate things?

**Comment by ShinDarth** [comment]
@DevRival  any news?

**Comment by DevRival** [comment]
@ShinDarth  no news.

**Comment by Draztal** [comment]
Thank you

**Pull request closed without merging**
