### PR TITLE
fix(scripts/TempleOfAhnQiraj): Ouro initial engagement

### LINKED ISSUE #13684: [AQ40] Ouro can have no targets even if attacked
### Current Behaviour

If pulled at max range or Ouro can't find another target, it will not cast spells or Submerge

### Expected Blizzlike Behaviour

Ouro will always target another player

### Source

_No response_

### Steps to reproduce the problem

1. `.gm on`
2. `.go xyz -9144.474609 2126.168701 -64.607368 531 3.682328`
3. `.gm off`
4. see if Ouro has a target. Does not submerge, does not cast spells

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/4391

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/93622ccb481e3484b90971f3450b4e3c9c902c9d

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Si1ker**
## Issues Addressed:

- Closes #13684
- Closes https://github.com/chromiecraft/chromiecraft/issues/4391

## Tests Performed:

- Tested

image

image

image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
This reverts my PR and consequently Ouro will no longer switch to melee targets once his victim is out of range

**Comment by Si1ker** [comment]
> This reverts my PR and consequently Ouro will no longer switch to melee targets once his victim is out of range

You mean, your PR (that created this issue) should have never been merged in the first place?

**Comment by Nyeriah** [comment]
I’ll address it once I’m available, thanks for the help and support

**Comment by Si1ker** [comment]
image

**Pull request closed without merging**
