### PR TITLE
fix(DB): Ashenvale Hunt german quest texts

### PR DESCRIPTION
**Pull request by Volgger**
Updated quest texts 2, 23 and 24 to patch stand 3.3.5a for deDE client. 

**Research source:**

NPCs
https://wowwiki.fandom.com/wiki/Senani_Thunderheart
https://wowwiki.fandom.com/wiki/Captain_Tarkan

Quest 2:
https://wow.gamepedia.com/Sharptalon%27s_Claw_(old)

Quest 23
https://wow.gamepedia.com/Ursangous%27s_Paw_(quest)

Quest 24 
https://wow.gamepedia.com/Shadumbra%27s_Head_(old)

## CHANGES PROPOSED:
-  Update quest texts for deDE locales

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Imported sql
- Tested succesfully ingame
- Text checked

## HOW TO TEST THE CHANGES:

- Import sql and check that no error occurs

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Volgger** [comment]
I just renamed the commit message and hate typing errors

**Comment by Si1ker** [comment]
Nice work done here Volgger, I got a german client to run the testing. it is not my language but very simple to test.

Test: In-game, Quest #2, #23, #24 texts compared with the texts in SQL changes listed in this PR, no errors received, texts are accurate and working as expected. Looks good on the last rev 👍

**Comment by Volgger** [comment]
Thx for testing @Si1ker and your feedback!

**Comment by BarbzYHOOL** [comment]
ty, merged

**Pull request merged**
