### PR TITLE
fix(DB): Missing Gnomeregan Pathing and Formations

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Adds missing pathing and formation to Gnomeregan
-  All values from Vmangos

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Vmangos
## Tests Performed:

- Tested in game, checked paths and formation, works as intended

## How to Test the Changes:

1. .go creature to any affected GUID
2. Check that pathing and formation looks correct

## Known Issues and TODO List:

- ~~The Leprous Assistant formation does not look quite correct during movement. I do not know if this is due to Vmangos using the values differently or if Vmangos just has wrong data here. If you know how to correct the data, please let me know!~~ This has been fixed.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
The Mobile Alert System creatures don't move for some reason. SAI has them disabling combat movement on reset, I don't know if that makes a difference.

Other than that I see no problems 👍

**Comment by ZhengPeiRu21** [comment]
> The Mobile Alert System creatures don't move for some reason. SAI has them disabling combat movement on reset, I don't know if that makes a difference.
> 
> Other than that I see no problems 👍

This is maybe a SmartAI bug. If someone is able to check correct behavior, I will correct this as well. Thank you for testing!

**Comment by Nefertumm** [comment]
Status?

**Comment by ZhengPeiRu21** [comment]
I am still hope that someone is able to confirm correct retail behavior for Mobile Alert System. Their pathing is added with this PR but they currently have Smart AI to disable movement, so either the pathing sniff is wrong or the AI is wrong.

**Comment by acidmanifesto** [comment]
> I am still hope that someone is able to confirm correct retail behavior for Mobile Alert System. Their pathing is added with this PR but they currently have Smart AI to disable movement, so either the pathing sniff is wrong or the AI is wrong.

the smart ai is the issue. we have this problem with a few other things. will approve this pr for now since the pathing is sniffed.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
> I am still hope that someone is able to confirm correct retail behavior for Mobile Alert System. Their pathing is added with this PR but they currently have Smart AI to disable movement, so either the pathing sniff is wrong or the AI is wrong.

feel free to remove the wip tag when you deem it necessary

**Comment by Maelthyrr** [comment]
As waypoint_data are correct, I will pass in "to be merged" and we will open a new issue for the SAI. Thanks for the PR.

**Pull request merged**
