### PR TITLE
DB restructuring - world - achievement_reward

### PR DESCRIPTION
**Pull request by wizzymore**
##### CHANGES PROPOSED:

-  Create TrinityCore like table structure for achievement_reward
-  Read the achievemnts from the table with the new structure

###### ISSUES ADDRESSED:

https://github.com/azerothcore/azerothcore-wotlk/issues/1177 

##### TESTS PERFORMED:

Tested on Linux Ubuntu 18.10 with no build errors.

##### HOW TO TEST THE CHANGES:

- Make sure achievement rewards still work as intended.

##### KNOWN ISSUES AND TODO LIST:

- [ Keep up-to-date to TrinityCore if there are new changes]

##### Target branch(es):

Master

### CODE REVIEW

**Comment by wizzymore** [comment]
If accepted, i will create a PR for wiki aswell

**Comment by FrancescoBorzi** [comment]
@wizzymore good job! I modified the instructions for testers a bit (also in the other PR of yours), because what we need to make sure with testing is that we are not breaking any game functionality. Are you on Discord? What's your nickname?

**Comment by poszer** [comment]
Tested on windows. The build is done without errors :
========== Build: 3 succeeded, 0 failed, 12 up-to-date, 1 skipped ==========
In game tested: Achievement rewards works as intended 
Good job @wizzymore :+1:

**Comment by FrancescoBorzi** [comment]
excellent @wizzymore and @poszer

**Pull request merged**
