### PR TITLE
fix(DB/Spell): Flurry Shaman Talent

### PR DESCRIPTION
**Pull request by Stifler82**
## Changes Proposed:
- Fixed the percentages of all [Flurry Shaman's Ranks](https://wowgaming.altervista.org/aowow/?spells=-2.7.373&filter=na=Flurry;cl=7;sc=0)
- Fixed Proc's Flags of all [Flurry Shaman's Ranks](https://wowgaming.altervista.org/aowow/?spells=-2.7.373&filter=na=Flurry;cl=7;sc=0)
- Fixed Client **(Visual percentages)** via this Patch: [patch-5.zip](https://github.com/azerothcore/azerothcore-wotlk/files/6253146/patch-5.zip)

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5115
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4723

## Tests Performed:

- Tested in game and working
- Tested on Windows 10 (64)
- **Video Test:** [Flurry Shaman Talent](https://youtu.be/xS1becJssrY)

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Stifler82** [comment]
@FrancescoBorzi @Helias

**Review by Helias — APPROVED** [review]

**Comment by D3thw0lf** [comment]
The linked client patch is **not** working with other languages (e.g. deDE)

You should mention this ^^

**Comment by Stifler82** [comment]
> The linked client patch is **not** working with other languages (e.g. deDE)
> 
> You should mention this ^^

No I shouldn't, because the **RECOMMENDED Client** to play **(because it is the one with the least Bug Client Side)** is the enUS one.

For example I am Italian, but I haven't done the ITA patch, **because the WOTLK 3.3.5a expansion is English.**
As well as the **GLOBAL** language.
So, no, I shouldn't ^^

**Comment by FrancescoBorzi** [comment]
> The linked client patch is **not** working with other languages (e.g. deDE)
> 
> You should mention this ^^

the client patch is just for the visual fix, the actual server-side behaviour is what matters here. We don't support client modifications so consider that patch from Stifler an extra bonus :)

**Pull request merged**
