### PR TITLE
fix(DB/object): Pool copper veins on Azuremyst Isle

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
- Make a pool with a copper veins on Azuremyst Isle, 20 spawns at once (39 spawn points)
- Lower respawn rates to fit in with the pool

## Issues Addressed:
- Nicer control of veins this way

## Tests Performed:
- You can teleport yourself around to check for veins, I have done so and my head nearly imploded from boredom

## How to Test the Changes:

```
.go xyz -3198.77 -12358.7 18.8168 530 -- 5290 Azuremyst Isle, Copper Vein, spawn 1
.go xyz -3205.95 -12416.9 3.10401 530 -- 5291 Azuremyst Isle, Copper Vein, spawn 2
.go xyz -3127.35 -12482.8 2.25965 530 -- 5292 Azuremyst Isle, Copper Vein, spawn 3
.go xyz -3356.8 -12177.6 41.1204 530 -- 5293 Azuremyst Isle, Copper Vein, spawn 4
.go xyz -3875.6 -12775 25.1323 530 -- 5294 Azuremyst Isle, Copper Vein, spawn 5
.go xyz -3961.57 -12711.4 82.02 530 -- 5295 Azuremyst Isle, Copper Vein, spawn 6
.go xyz -4295.92 -12735.8 21.8414 530 -- 5296 Azuremyst Isle, Copper Vein, spawn 7
.go xyz -4302 -12927.6 9.3698 530 -- 5297 Azuremyst Isle, Copper Vein, spawn 8
.go xyz -4778.81 -11573.7 -2.75845 530 -- 5298 Azuremyst Isle, Copper Vein, spawn 9
.go xyz -4774.76 -11635.7 -36.7166 530 -- 5299 Azuremyst Isle, Copper Vein, spawn 10
.go xyz -4702.54 -11540.2 -24.777 530 -- 5300 Azuremyst Isle, Copper Vein, spawn 11
.go xyz -4773.14 -11467.5 24.643 530 -- 5301 Azuremyst Isle, Copper Vein, spawn 12
.go xyz -5045.83 -11072.7 29.4929 530 -- 5302 Azuremyst Isle, Copper Vein, spawn 13
.go xyz -5167.42 -11033.6 24.5044 530 -- 5303 Azuremyst Isle, Copper Vein, spawn 14
.go xyz -5118.29 -10943.1 16.0907 530 -- 5304 Azuremyst Isle, Copper Vein, spawn 15
.go xyz -4874.49 -11278.6 2.6214 530 -- 5305 Azuremyst Isle, Copper Vein, spawn 16
.go xyz -4890.08 -11146.4 7.22636 530 -- 5306 Azuremyst Isle, Copper Vein, spawn 17
.go xyz -4977.74 -11441.8 -36.9993 530 -- 5307 Azuremyst Isle, Copper Vein, spawn 18
.go xyz -4816.09 -11605.3 -42.3396 530 -- 5308 Azuremyst Isle, Copper Vein, spawn 19
.go xyz -5083.06 -11658.3 -12.9082 530 -- 5309 Azuremyst Isle, Copper Vein, spawn 20
.go xyz -4961.75 -11727.3 12.8604 530 -- 5310 Azuremyst Isle, Copper Vein, spawn 21
.go xyz -4890.44 -12042.3 22.4669 530 -- 5311 Azuremyst Isle, Copper Vein, spawn 22
.go xyz -4323.69 -12851.5 11.673 530 -- 5312 Azuremyst Isle, Copper Vein, spawn 23
.go xyz -4178.29 -12910.6 6.36836 530 -- 5313 Azuremyst Isle, Copper Vein, spawn 24
.go xyz -4066.04 -12693.8 14.8971 530 -- 30444 Azuremyst Isle, Copper Vein, spawn 25
.go xyz -4565.29 -12030.2 42.5364 530 -- 30478 Azuremyst Isle, Copper Vein, spawn 26
.go xyz -5085.58 -11970 -2.40896 530 -- 30486 Azuremyst Isle, Copper Vein, spawn 27
.go xyz -4809.11 -11667.8 -40.5956 530 -- 30498 Azuremyst Isle, Copper Vein, spawn 28
.go xyz -3887.91 -12696.9 94.0337 530 -- 30507 Azuremyst Isle, Copper Vein, spawn 29
.go xyz -4408.13 -11518.2 14.1106 530 -- 30512 Azuremyst Isle, Copper Vein, spawn 30
.go xyz -4666.33 -11535.9 22.4012 530 -- 30514 Azuremyst Isle, Copper Vein, spawn 31
.go xyz -3149.38 -12393.9 12.1434 530 -- 30531 Azuremyst Isle, Copper Vein, spawn 32
.go xyz -3496.12 -11577 14.9949 530 -- 39948 Azuremyst Isle, Copper Vein, spawn 33
.go xyz -3703.19 -11466.1 303.665 530 -- 39949 Azuremyst Isle, Copper Vein, spawn 34
.go xyz -3823.74 -12579.4 2.17238 530 -- 39950 Azuremyst Isle, Copper Vein, spawn 35
.go xyz -3584.34 -11828.8 11.2678 530 -- 120291 Azuremyst Isle, Copper Vein, spawn 36
.go xyz -2997.91 -12274.1 17.2133 530 -- 120340 Azuremyst Isle, Copper Vein, spawn 37
.go xyz -3208.36 -12254.1 57.0038 530 -- 120362 Azuremyst Isle, Copper Vein, spawn 38
.go xyz -4095.92 -11588.5 19.9823 530 -- 120791 Azuremyst Isle, Copper Vein, spawn 39
```

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
I will fix the errors tomorrow, I didn't see errors when testing it locally...

**Comment by Zoidwaffle** [comment]
It should be fine for testing now.

**Review by Stifler82 — CHANGES_REQUESTED** [review]
i wrote a bullshit  🤣

**Review by Stifler82 — APPROVED** [review]
Tested, works perfect, excellent spawn points.

WoWScrnShot_022321_183304

**Comment by Stifler82** [comment]
@FrancescoBorzi 
@Helias

**Review by Helias — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Pull request merged**
