### PR TITLE
fix(DB/Creature): Deadmines Pathing for 23 creatures

### PR DESCRIPTION
**Pull request by poszer**
Deadmines Pathing for 23 creatures inside

##### CHANGES PROPOSED:

-  Fix Pathing for 23 creatures inside instance
-  ERROR: WaypointMovementGenerator

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/820

##### TESTS PERFORMED:

Yes, all creatures now correctly patrols

##### HOW TO TEST THE CHANGES:

1. Go in Deadmines and check creatures inside, also check worldserver for DB errors

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Seebaby have you tested this PR ?

I'm just asking because sometimes it is not clear if the feedback is about code review or actual testing

**Comment by poszer** [comment]
> This looks good all move

Did you test this?

**Comment by Seebaby** [comment]
Yes i have tested

**Comment by poszer** [comment]
> Yes i have tested

And, did this PR fix issue with creatures movements inside Deadmines? Do you have any errors reported in DB log?

**Comment by Seebaby** [comment]
> > Ja, ich habe es getestet
> 
> Und hat diese PR das Problem mit Kreaturenbewegungen in Deadmines behoben? Haben Sie Fehler im DB-Protokoll gemeldet?

So I have no errors in the deadmines in the log

**Comment by poszer** [comment]
> > > Ja, ich habe es getestet
> > 
> > 
> > Und hat diese PR das Problem mit Kreaturenbewegungen in Deadmines behoben? Haben Sie Fehler im DB-Protokoll gemeldet?
> 
> So I have no errors in the deadmines in the log

Okay, thanks for infos

**Comment by poszer** [comment]
Related to this report also : https://github.com/azerothcore/azerothcore-wotlk/issues/1824

**Pull request merged**
