### PR TITLE
fix(DB/Karazhan): implement Threat Drop mechanic on Mana Feeders

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
- mana feeders should now drop threat every 2 second on all targets, then apply threat to a random target on threat list. this does not work the same way it does on retail, therefore it is a hack fix.
-  now use hate to zero aura obtained from sniff that doesn't seem to work

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16269
- Closes https://github.com/chromiecraft/chromiecraft/issues/5609

## SOURCE:

- see issue
- used sniffs from Neifion to more accurately determine timers and actual spellIDs being used

## Tests Performed:

- tested ingame with 2 characters. seems to work but would preferably need testing with a full group to see if it works properly (multi-boxing?)
- 

## How to Test the Changes:

1. go to menagerie and kara with multiple chars
2. engage the Mana Feeders
3.

## Known Issues and TODO List:

- [ ] proper timing for threat drop mechanic - needs sniffing
- [ ] figure out whether threat is added to a random target on top of the threat drop - also needs sniffing

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
> Gotta check sniffs for threat drop auras here (“hate to zero”)

I will add commits if someone does

**Comment by elthehablo** [comment]
> Gotta check sniffs for threat drop auras here (“hate to zero”)

image
 
image

**Comment by elthehablo** [comment]
Seems to be always cast together with Astral Bite if I am not mistaken.

**Comment by elthehablo** [comment]
lol I think I need someone who is better at reading sniffs to read those hieroglyphics and explain them to me in monkey terms

**Comment by elthehablo** [comment]
Gonna take another look at this tomorrow

**Comment by elthehablo** [comment]
Does anyone have any idea how "hate to zero" is supposed to work? The only ones in the db that seem to make use of it as well are the Splintered Skeletons near The Ravenian in Scholomance.

**Comment by Nyeriah** [comment]
They are periodic auras that reset threat whenever their periodic effect fires. Is there anything specific you'd like to know about it?

**Comment by FrancescoBorzi** [comment]
status of this?

**Comment by elthehablo** [comment]
Ideally someone who can decipher the sniffs better than I can should try to figure this out

**Comment by Nyeriah** [comment]
This is on hold until we start working on Karazhan in the upcoming weeks

**Comment by FrancescoBorzi** [comment]
> This is on hold until we start working on Karazhan in the upcoming weeks

good to know, updated the labels

**Comment by Kitzunu** [comment]
Status

**Comment by elthehablo** [comment]
> Status

I personally have not looked into the sniffs for this creature. Partially because my skills and tools in reading sniffs are limited

**Comment by Kitzunu** [comment]
@elthehablo bug Bench. He'll love it

**Comment by avarishd** [comment]
we technically don't even need SAI, add Astral Bite and Hate to Zero to template_addon

"Hate to zero" is just -100% threat (and to "Hate to half" is -50%)
https://github.com/cmangos/mangos-wotlk/commit/8f79da87e7d75a49910078796a150de4428681c7
(assigned scripts to the spell Ids are still valid to date in wotlk mangos db)

**Comment by Kitzunu** [comment]
status?

**Pull request closed without merging**
