### PR TITLE
feat(Core/Grids): Allow arbitrary containers in grid searchers that support push_back

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/8775f8b28a5ad4403371577787131ff81f14332b

I Need it for smartscripts
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by acidmanifesto** [comment]
keep in mind i done this already and we had to revert as there was a issue with alot of spells not working, can not remember one of the names in particular, but it was pretty much any spell that is casted on the player and gave them a aura stopped working. It had to be reverted from the master.

**Comment by acidmanifesto** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/8841

**Comment by IntelligentQuantum** [comment]
@acidmanifesto I did not bring all the parts so I do not think there is a problem. 

btw tnx i will test that video posted from winfi

**Comment by acidmanifesto** [comment]
> @acidmanifesto I did not bring all the parts so I do not think there is a problem.
> 
> btw tnx i will test that video posted from winfi

I really do hope it works on your PR! GOOD LUCK!

**Comment by IntelligentQuantum** [comment]
I tested that video posted from winfi and it works fine.

**Comment by acidmanifesto** [comment]
> I tested that video posted from winfi and it works fine.

Awesome!

**Comment by Nyeriah** [comment]
@azerothcore/testers please test this one, try to cast spells/apply auras

**Comment by temperrr** [comment]
Only regression tested;

Tried various spells as a shaman, hunter, warlock and paladin, they all seem to work as expected

**Comment by IntelligentQuantum** [comment]
@Nyeriah we can merge this ? i need it for https://github.com/azerothcore/azerothcore-wotlk/pull/10094 and more..

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
