### PR TITLE
fix(DB/SAI): Add Gnomish Battle Chicken combat SAI

### PR DESCRIPTION
**Pull request by Voxstrasza**
## Changes Proposed:
-  Battle Chicken casts Battle Squawk w/ 25% chance in combat on self
-  Battle Chicken casts Chicken Fury w/ 50% chance in combat on self

## Issues Addressed:
#9408

## Tests Performed:
Untested

## How to Test the Changes:
1. Use trinket Gnomish Battle Chicken
2. Attack mob with Chicken out
3. Wait for procs.
4. Invite some friends to see if they get the Haste buff.

## Known Issues and TODO List:

I pulled 25% and 50% out of my ass.  There is no concrete information on the proc rates - but the Haste proc has historically procced less than the Enrage proc.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Voxstrasza** [comment]
@Nyeriah I didn't test - did anyone confirm testing to you?

**Comment by Kitzunu** [comment]
90% of the time sai dont need to be tested as long as the comments are good

**Comment by Nyeriah** [comment]
I checked the database and saw they had no scripts at all whatsoever. As for the queries themselves, as Kitzunu said, there's usually no reason to expect any adverse effects from SAI - it just does what the numbers tell it to do

**Comment by Nyeriah** [comment]
There's only one thing here I would change: that spell already has TARGET_UNIT_CASTER_AREA_PARTY as target type, so setting it to be cast on the invoker's party is not necessary, the amount of targets is also not necessary. It works fine with self as target, since it's an aoe spell, the spell target selectors will take care of the rest.

**Comment by Voxstrasza** [comment]
> There's only one thing here I would change: that spell Squawk already has TARGET_UNIT_CASTER_AREA_PARTY as target type, so setting it to be cast on the invoker's party is not necessary, the amount of targets is also not necessary. It works fine with self as target, since it's an aoe spell, the spell target selectors will take care of the rest.

i'll edit it, thanks for the feedback

**Comment by Eronox** [comment]
If I'm not mistaken, I believe the event type should probably be `UPDATE_IC` (id: 0) instead of `AGGRO` (id: 4), because otherwise the spells may only be cast on aggro with the given chance instead of during combat

**Comment by KaneoHunter** [comment]
https://www.youtube.com/watch?v=TSywF4MrPBQ

I wanted to make note of this recent revelation, we might want to account for this behaviour?

**Pull request merged**
