### PR TITLE
fix(DB/Creature): Reduced casts of healing from Gordunni Shamans

### PR DESCRIPTION
**Pull request by Asthalor**
They had 2 events that triggered a heal.
One checked a friendly unit, and the other himself. Because he could heal him with both i deleted the one that checked friend and leave the one with the self healing.
## Changes Proposed:
-  Removed the  event 14 - Friendly Health

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7572
- Closes https://github.com/chromiecraft/chromiecraft/issues/1548

## SOURCE:

None

## Tests Performed:

- .go c id 5236 
- Attack him and check the timers, they should heal themselfs once every 14 to 21 seconds when below 40% hp

Video

https://streamable.com/htcjt5

## How to Test the Changes:

1. .go c id 5236 
2. Attack him and check the timers, they should heal themselfs once every 14 to 21 seconds when below 40% hp

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Asthalor** [comment]
I had some messing with master branch that should not mess with this pr. :P

**Comment by syssneck** [comment]
Okay, but supposedly you pull multiple mobs, then the shamans can't heal their friends anymore. Is this a good way to deal with the issue? This might be an overarching issue with the event itself in SmartAI: `14 - FRIENDLY_HEALTH`.

**Comment by Si1ker** [comment]
image


Against

[TrinityCore - Gordunni Shaman SAI](https://github.com/TrinityCore/TrinityCore/blob/f759809d9d4364bc1d988e4390d3d5a33d5469e9/sql/old/6.x/world/02_2015_11_08/2015_07_20_01_world.sql#L159)


😿

**Comment by Asthalor** [comment]
Yeah. maybe that was a bigger change that needed. The thing is that the code shared by  Si1ker is exactly the same as we have, so if we pick it by the source it means that this issue is expected.

image

The other option was to remove the self healing, given that the smartAI option 'Gordunni Shaman - Between 0-40% Health - Cast \'Healing Wave\'' heals himself, and the option 'Gordunni Shaman - Friendly At 450 Health - Cast \'Healing Wave\'' can target him.

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by Asthalor** [comment]
We dont know if the issue here is blizzlike or not. The event 4 Frienly NPC within 40m is at 450HP trigger the heal, but it trigger the heal on himself too. I tought of deleteing the event 5, which is the self healing so he only have 1 healing, but its only my opinion and not anything related to blizzlike, so we need more data.

**Comment by Si1ker** [comment]
I just came from the video posted in the chromiecraft issue, there are other mobs with healing spells around Azeroth that have the same behavior. He is using a shaman character that can interrupt spell casting as well as other classes have "fear, kicks, mind freeze, stuns, any other kind of spells that could interrupt casting". Example on Shamans:
image


Those spells that cut spell casting are in WoW not only meant to be used in PvP, also in PvE scenarios like this one.

All sources point to the same place: "this is blizzlike behavior, not a bug, use your spells bruh."

**Comment by Asthalor** [comment]
Then i will close this PR as its intended.

**Pull request closed without merging**
