### PR TITLE
fix(Core): const at the end of set function.

### PR DESCRIPTION
**Pull request by Baggins800**
Remove `const` at the end of SetGridId(), this `const` implies the member value cannot change, the compiler may drop the const but it is not guaranteed.
Edit: fix typo

### CODE REVIEW

**Comment by Helias** [comment]
Thanks for the contribution.

Is there a way to test that this function still work correctly?

please, explain step by step how to test the functionality of this function (in-game)/

**Comment by Baggins800** [comment]
The simple test I performed was with basic implementation in a `main.cpp`,
```
#include <iostream>
#include <cstdint>
typedef uint32_t uint32;
using namespace std;
class SetMemberTest {
 public:
  void SetGridId(const uint32 & id) { i_gridId = id; }
  //void SetGridId(const uint32 id) const { i_gridId = id; } // this does not compile for me
  void print_member() {
    cout << i_gridId << endl;
  }

 private:
  uint32 i_gridId;
};

int main () {
  SetMemberTest t;
  t.SetGridId(5);
  t.print_member();
  
  return 0;
}
```
followed by, `clang++ main.cpp && ./a.out`, which yielded the result `5`, as expected.
The previous function `void SetGridId(const uint32 id) const { i_gridId = id; }`  causes the program not to compile. You can reproduce the above code an see if you have a different result?

**Comment by FrancescoBorzi** [comment]
@Baggins800 there are conflicts

**Comment by Baggins800** [comment]
> @Baggins800 there are conflicts

it seems the function was removed, the merge is not longer required.

**Pull request closed without merging**
