### PR TITLE
Revert "fix(Core/Config): Set default corpse decay for normal creatures to 5 …"

### PR DESCRIPTION
**Pull request by Gultask**
Reverts azerothcore/azerothcore-wotlk#14039

Causing corpses to despawn instantly: https://github.com/azerothcore/azerothcore-wotlk/issues/14325

### CODE REVIEW

**Comment by heyitsbench** [comment]
For the record, only the `Rate.Corpse.Decay.Looted` section should be reverted. Still not blizzlike, but more blizzlike with the `Corpse.Decay.NORMAL` set to 300.

**Comment by Gultask** [comment]
We're testing it with different values and it still causes the issue, unfortunately.

**Comment by heyitsbench** [comment]
> We're testing it with different values and it still causes the issue, unfortunately.

[Then your testing is wrong.](https://user-images.githubusercontent.com/38561765/210276277-1e1ecb19-a90e-4efa-aad7-33aa8084bcae.png)

**Comment by Samsequel** [comment]
Tested it, and it instantly despawned after looting

**Comment by Samsequel** [comment]
Revert fixed the issue

**Comment by Samsequel** [comment]
image

**Review by Samsequel — APPROVED** [review]

**Comment by heyitsbench** [comment]
Again, reverting just `Rate.Corpse.Decay.Looted` fixes the issue, you don't need to revert `Corpse.Decay.NORMAL` as well.

**Comment by Gultask** [comment]
Me and Sam have no further knowledge of the issue. And we can't keep this PR and just expect people to know to change the config on their own servers.

UltraNix or yourself can open a PR to correct it later.

**Pull request merged**
