### PR TITLE
feat(Deps/Fmt): update to 8.1.1. Fix build with c++20

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Update to https://github.com/fmtlib/fmt/releases/tag/8.1.1
- Fix build for c++20

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@Kitzunu

**Comment by Kitzunu** [comment]
Is there a way we can support both versions for a while? Cuz this introduces new functions from c++20, or push these changes to my PR and we can hold and release this when we merge that

**Comment by Winfidonarleyan** [comment]
@Kitzunu Done

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
awesome winfi!

**Pull request merged**
