### PR TITLE
fix(Scripts): Brazier of Dancing Flames should dance when spawned

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix Brazier of Dancing Flames to begin dancing when spawn

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3666

## Tests Performed:

- Tested in-game, also tested that emotes as still work

## How to Test the Changes:

1. .additem 34686
2. Use item, test that flames dance

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@azerothcore/testers

**Comment by Maelthyrr** [comment]
@ZhengPeiRu21 I'm sorry but when I use  the item, nothing happens. I've check, I'm on the good branch.

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21 I'm sorry but when I use the item, nothing happens. I've check, I'm on the good branch.

I am just test again, and tt is work for me locally. Do you mean that using the item has no effect at all, and NPC does not spawn at all? Or that NPC is just not dance on spawn? I do not see how my changes could have caused NPC to not spawn at all....

Is anyone else see this same behavior?

**Comment by Synful-Syn** [comment]
Related to https://github.com/azerothcore/azerothcore-wotlk/issues/10327

**Comment by Maelthyrr** [comment]
Oh... I'm stupid... I misunderstood the fix.... Sorry. So yes, it's work  fine. When Gob spawn, the flame npc dance.

It is this animation with the player that I did not see : https://youtu.be/aYdwWVihq0I?t=9

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
