### PR TITLE
feat(Core/Scripting): Implement OnSpellHealingBonusTakenNegativeModif…

### PR DESCRIPTION
**Pull request by Nyeriah**
…iers hook

## Changes Proposed:
-  Allows excluding certain healing spells from negative percentage modifiers
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- Tested in-game
- 

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Thats one hell of a name.

Btw isnt Caster Target SpellInfo a better order? Just seems more logical to me

**Comment by Nyeriah** [comment]
> Thats one hell of a name.
> 
> Btw isnt Caster Target SpellInfo a better order? Just seems more logical to me

Doesn't sound more logical to me because the hook is called by the target and not the caster (target = this), but I guess it depends on how you look at it

**Comment by Kitzunu** [comment]
I guess true, I didnt really look at it as i was on my phone.

I am just trying to recall if we ever order target before caster in any other hook?

**Review by Nefertumm — APPROVED** [review]

**Comment by Nyeriah** [comment]
> I guess true, I didnt really look at it as i was on my phone.
> 
> I am just trying to recall if we ever order target before caster in any other hook?

I don't really remember Kitzunu

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
