### PR TITLE
fix(Scripts/SSC): do reset threat list for p3 in the right place

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/6680

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

logic

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

untested

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Known Issues and TODO List:

N.A.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by balleny** [comment]
did you verify that the demon form does not inherit any previous active threatlist by moving the reset into the melee forms codesection only?

**Comment by elthehablo** [comment]
> did you verify that the demon form does not inherit any previous active threatlist by moving the reset into the melee forms codesection only?

No. As stated I didn't test. Didn't have time. It will be on the PTR this afternoon so I will check

**Comment by elthehablo** [comment]
> did you verify that the demon form does not inherit any previous active threatlist by moving the reset into the melee forms codesection only?

But I don't think this is an issue as the demon form is summoned and therefore spawns with an empty threatlist.

**Comment by balleny** [comment]
i would expect so, too. but, we have seen some funky stuff from small, untested changes recently

**Comment by elthehablo** [comment]
I tested for my sanity. But it's clear from the code that that won't happen here

**Pull request merged**
