### PR TITLE
fix(DB) Tamed Sporebats have drops and Giant Plains Creeper spider should not be skinnable

### PR DESCRIPTION
**Pull request by M4th3m4tic4l**
## Changes Proposed:
-  Removes copper and ragveil drop from Tamed Sporebats
-  Removes the possibility of skinning Giant Plains Creeper

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14596
- Closes https://github.com/chromiecraft/chromiecraft/issues/4777
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14580
- Closes https://github.com/chromiecraft/chromiecraft/issues/4714

## Tests Performed:

- 
WoWScrnShot_012923_180303

- 
WoWScrnShot_012923_180201

## How to Test the Changes:

1. Insert the changes in your world database
2. .go c id 2565 for Giant Plains Creeper
3. .tele feralfenvillage for Tamed Sporebats

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
Note that the emulator returned these 2 errors.
- Table 'creature_loot_template' Entry 18201 does not exist but it is used by Creature 18201
- Table 'skinning_loot_template' Entry 2565 isn't creature skinning id and not referenced from loot, and thus useless.

**Comment by M4th3m4tic4l** [comment]
> Note that the emulator returned these 2 errors.
> 
> * Table 'creature_loot_template' Entry 18201 does not exist but it is used by Creature 18201
> * Table 'skinning_loot_template' Entry 2565 isn't creature skinning id and not referenced from loot, and thus useless.
> 
> One of them, I think, is fixed with this.
> 
> ```sql
> UPDATE `creature_template` SET `mingold`=0, `maxgold`=0, `lootid`=0 WHERE `entry`=18201;
> ```
> 
> The other one, I don't know.

Thanks Walter

**Comment by M4th3m4tic4l** [comment]
the same error is still displayed

**Comment by pangolp** [comment]
> the same error is still displayed

No, it is not the same error. Now the error is different.
You updated the script, but you removed the DELETE.
And then, I think you are still missing delete the other record.
Try this, see if it works.

```sql
DELETE FROM `creature_loot_template` WHERE `entry`=18201;
UPDATE `creature_template` SET `mingold`=0, `maxgold`=0, `lootid`=0 WHERE `entry`=18201;

DELETE FROM `skinning_loot_template` WHERE `Entry`=2565 AND `Item`=4234;
UPDATE `creature_template` SET `skinloot`=0 WHERE `entry`=2565;
```

**Comment by M4th3m4tic4l** [comment]
> > the same error is still displayed
> 
> No, it is not the same error. Now the error is different. You updated the script, but you removed the DELETE. And then, I think you are still missing delete the other record. Try this, see if it works.
> 
> ```sql
> DELETE FROM `creature_loot_template` WHERE `entry`=18201 AND `Item`=22787;
> UPDATE `creature_template` SET `mingold`=0, `maxgold`=0, `lootid`=0 WHERE `entry`=18201;
> 
> DELETE FROM `skinning_loot_template` WHERE `Entry`=2565 AND `Item`=4234;
> UPDATE `creature_template` SET `skinloot`=0 WHERE `entry`=2565;
> ```
> 
> If you delete the `creature_template` reference, the emulator prevents you from leaving unused information. Not only you have to do the update, but, in any case, you also have to delete the information that is no longer used. I don't know where you got that information from, but, well, the point is that you have to update, but you also have to delete the information.

The information is extracted from the Issues mentioned above, but thank you for explaining that point, although I was already sensing that it might go that way.

**Comment by Nyeriah** [comment]
Next time please keep 1 issue per PR unless they're strictly related. Thanks!

**Comment by pangolp** [comment]
Why don't you create 2 PRs, separating the topics? Because if you had to revert any of them, the other one is not lost, instead, that way, when you revert it, you lose both of them. Divide it in 2 better and create 2 different PR's.

**Comment by M4th3m4tic4l** [comment]
> Why don't you create 2 PRs, separating the topics? Because if you had to revert any of them, the other one is not lost, instead, that way, when you revert it, you lose both of them. Divide it in 2 better and create 2 different PR's.

Personally, I do not consider it necessary, especially considering these minuscule changes.

**Comment by pangolp** [comment]
> Okay, I'll keep that in mind

Excellent. Better this way.

**Comment by Maelthyrr** [comment]
Tested and work fine.

**Review by Gultask — APPROVED** [review]

**Pull request merged**
