### PR TITLE
fix(DB/Creature): Greatmother Hawkwind faction

### LINKED ISSUE #9547: Greatmother Hawkwind has incorrect faction
### What client do you play on?

enUS

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2495

When you go talk to Greatmother Hawkwind for her quest, she's missing Thunder Bluff on her tooltip. Only displaying level and name.

Tester:

The issue is confirmed. [Greatmother Hawkwind](https://wowgaming.altervista.org/aowow/?npc=2991) has faction `ID35`. That is not `Thunder Bluff`

| name | faction | 
| --- | ---: | 
| Greatmother Hawkwind | 35 | 

### Expected Blizzlike Behaviour

Greatmother Hawkwind should be part of `Thunder Bluff` faction
Безымянный

### Source

Wowhead [Greatmother Hawkwind](https://www.wowhead.com/npc=2991/greatmother-hawkwind#outfit)
> Faction: Thunder Bluff

Wowpedia [Greatmother Hawkwind](https://wowpedia.fandom.com/wiki/Greatmother_Hawkwind)
> Affiliation(s) | Thunder Bluff

https://youtu.be/Yv0cPuseynQ

### Steps to reproduce the problem

```sql
SELECT ct.name, ct.faction
FROM `creature_template` ct
WHERE entry = 2991
```

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Voxstrasza**
## Changes Proposed:
-  Update Greatmother Hawkwind faction to Thunder Bluff

## Issues Addressed:
- Closes #9547

## How to Test the Changes:
.go c 26610

### CODE REVIEW

**Comment by Nefertumm** [comment]
From sniff?

**Comment by Voxstrasza** [comment]
This NPC was removed in 4.0.3 so unless anyone has any legacy sniff data or a way to verify faction 104 to be the correct one then no.

The other NPCs in Camp Narache/tauren starting area use faction 104

**Comment by Nefertumm** [comment]
I can ask from a sniff to verify. I'll let you know 👍

**Comment by acidmanifesto** [comment]
Sniff that i will upload when i get back from dropping the kids from school.
This is the text parse which gives more info. Shows her entry as 2991, and her faction as 81 Thunderbuff, not 35 as az core and tc core has, and not 104 as this pr suggest. So we are all wrong.

ClientToServer: CMSG_QUEST_GIVER_HELLO (0x3496) Length: 13 ConnIdx: 1 Time: 12/08/2021 07:00:27.250 Number: 674
QuestGiver GUID: Full: 0x204CB0002002EBC000000A00002AE607 Creature/0 R4908/S10 Map: 1 Entry: 2991 Low: 2811399

ServerToClient: SMSG_QUEST_GIVER_QUEST_DETAILS (0x2A92) Length: 1058 ConnIdx: 0 Time: 12/08/2021 07:00:27.547 Number: 675
QuestGiverGUID: Full: 0x204CB0002002EBC000000A00002AE607 Creature/0 R4908/S10 Map: 1 Entry: 2991 Low: 2811399
InformUnit: Full: 0x0
QuestID: 753
QuestPackageID: 0
PortraitGiver: 0
PortraitGiverMount: 0
PortraitGiverModelSceneID: 0
PortraitTurnIn: 0
[0] QuestFlags: 0
[1] QuestFlags: 0
SuggestedPartyMembers: 0
LearnSpellsCount: 0
DescEmotesCount: 4
ObjectivesCount: 1
QuestStartItemID: 0
QuestSessionBonus: 0
[0] Type: 1
[0] Delay: 0
[1] Type: 1
[1] Delay: 0
[2] Type: 0
[2] Delay: 0
[3] Type: 0
[3] Delay: 0
[0] ObjectiveID: 381223
[0] ObjectID: 4755
[0] Amount: 1
[0] Type: 1
AutoLaunched: True
Unused: False
StartCheat: False
DisplayPopup: False
(QuestRewards) ChoiceItemCount: 0
(QuestRewards) ItemCount: 0
(QuestRewards) [0] ID: 0
(QuestRewards) [0] Quantity: 0
(QuestRewards) [1] ID: 0
(QuestRewards) [1] Quantity: 0
(QuestRewards) [2] ID: 0
(QuestRewards) [2] Quantity: 0
(QuestRewards) [3] ID: 0
(QuestRewards) [3] Quantity: 0
(QuestRewards) RewardMoney: 40
(QuestRewards) XP: 250
(QuestRewards) ArtifactXP: 0
(QuestRewards) ArtifactCategoryID: 0
(QuestRewards) Honor: 0
(QuestRewards) Title: 0
(QuestRewards) FactionFlags: 1
**(QuestRewards) [0] FactionID: 81**
(QuestRewards) [0] FactionValue: 5
(QuestRewards) [0] FactionOverride: 0
(QuestRewards) [0] FactionCapIn: 7
(QuestRewards) [1] FactionID: 0
(QuestRewards) [1] FactionValue: 0
(QuestRewards) [1] FactionOverride: 0
(QuestRewards) [1] FactionCapIn: 7
(QuestRewards) [2] FactionID: 0
(QuestRewards) [2] FactionValue: 0
(QuestRewards) [2] FactionOverride: 0
(QuestRewards) [2] FactionCapIn: 7
(QuestRewards) [3] FactionID: 0
(QuestRewards) [3] FactionValue: 0
(QuestRewards) [3] FactionOverride: 0
(QuestRewards) [3] FactionCapIn: 7
(QuestRewards) [4] FactionID: 0
(QuestRewards) [4] FactionValue: 0
(QuestRewards) [4] FactionOverride: 0
(QuestRewards) [4] FactionCapIn: 7
(QuestRewards) [0] SpellCompletionDisplayID: 0
(QuestRewards) [1] SpellCompletionDisplayID: 0
(QuestRewards) [2] SpellCompletionDisplayID: 0
(QuestRewards) SpellCompletionID: 0
(QuestRewards) [0] CurrencyID: 0
(QuestRewards) [0] CurrencyQty: 0
(QuestRewards) [1] CurrencyID: 0
(QuestRewards) [1] CurrencyQty: 0
(QuestRewards) [2] CurrencyID: 0
(QuestRewards) [2] CurrencyQty: 0
(QuestRewards) [3] CurrencyID: 0
(QuestRewards) [3] CurrencyQty: 0
(QuestRewards) SkillLineID: 0
(QuestRewards) NumSkillUps: 0
(QuestRewards) TreasurePickerID: 0
(QuestRewards) (ItemChoiceData) [0] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [0] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [0] RandomPropertiesSeed: 0
(QuestRewards) (ItemChoiceData) [0] RandomPropertiesID: 0
(QuestRewards) (ItemChoiceData) [0] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [0] Quantity: 0
(QuestRewards) (ItemChoiceData) [1] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [1] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [1] RandomPropertiesSeed: 0
(QuestRewards) (ItemChoiceData) [1] RandomPropertiesID: 0
(QuestRewards) (ItemChoiceData) [1] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [1] Quantity: 0
(QuestRewards) (ItemChoiceData) [2] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [2] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [2] RandomPropertiesSeed: 0
(QuestRewards) (ItemChoiceData) [2] RandomPropertiesID: 0
(QuestRewards) (ItemChoiceData) [2] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [2] Quantity: 0
(QuestRewards) (ItemChoiceData) [3] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [3] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [3] RandomPropertiesSeed: 0
(QuestRewards) (ItemChoiceData) [3] RandomPropertiesID: 0
(QuestRewards) (ItemChoiceData) [3] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [3] Quantity: 0
(QuestRewards) (ItemChoiceData) [4] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [4] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [4] RandomPropertiesSeed: 0
(QuestRewards) (ItemChoiceData) [4] RandomPropertiesID: 0
(QuestRewards) (ItemChoiceData) [4] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [4] Quantity: 0
(QuestRewards) (ItemChoiceData) [5] LootItemType: 0 (Item)
(QuestRewards) (ItemChoiceData) [5] ItemID: 0 (0)
(QuestRewards) (ItemChoiceData) [5] RandomPropertiesSeed: 0
(QuestRewards) (ItemChoiceData) [5] RandomPropertiesID: 0
(QuestRewards) (ItemChoiceData) [5] HasItemBonus: False
(QuestRewards) (ItemChoiceData) [5] Quantity: 0
(QuestRewards) IsBoostSpell: False
QuestTitle: A Humble Task
DescriptionText: I have traveled many paths through life and these old legs lack the vigor they once had. I can still perform my duties to the tribe. Sometimes it just takes an old woman a little longer to do the task.$b$bBut you look like an eager $c. Let's put some of that youthful vitality to the test. Take a water pitcher from the well and bring it to my son, the Chief, in Camp Narache.$b$bRemember that even the most humble task can gain the recognition of elders.
LogDescription: Take a Water Pitcher from the water well.$b$bReturn the pitcher to Chief Hawkwind in Camp Narache which is northwest from the water well.
PortraitGiverText: 
PortraitGiverName: 
PortraitTurnInText: 
PortraitTurnInName:

**Review by acidmanifesto — APPROVED** [review]
~~sniff shows 81 (thunderbuff). but changing it to 81 makes her hostile even towards tauren players. can u tell me where 104 came from?~~
Ok. so misunderstanding on my side. this is correct. faction points to faction template in the faction template db2 file. this PR is 100% correct and verified by both me, wow vanilla dev brotalnia and tc dev shauren.

**Comment by acidmanifesto** [comment]
@Voxstrasza Thank you for your PR

**Pull request merged**
