### PR TITLE
fix(Core): fix a few issues with "Battle for the Undercity"

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
- collect the GUIDs of the spawned guards "Warsong Battleguard" for the Horde and "Stormwind Elite" for the Alliance in a vector in order to despawn them after the event resets (otherwise they would just stay there, which is kind of strange when you start the event again)
- adjust the angle Sylvanas uses to follow Thrall a little bit so that she doesn't stand directly in front of him all the time (looks strange when he's talking to Wrynn for example)
- include a point movement to the target destination before Sylvanas leaps to the platform (otherwise she would run back to her starting position after finishing the leap)
- clear the sit animation of Thrall after the event resets (otherwise he would always trying to sit when the event starts again)
- ensure that Sylvanas is mounted again on her undead horse after the event resets

###### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested build on Ubuntu 16.04 using clang 7; tested in-game

##### HOW TO TEST THE CHANGES:
**Horde version**
- preparation:
 ```
.quest remove 13266
.quest remove 13267
.quest add 13266
.go 1955.33 242.527 41.5081 0
```
- proceed with the quest
- after finishing the event, do not finish the quest "Battle for the Undercity", instead teleport to the position mentioned above, logout and wait a few minutes for the event to reset
- after login Thrall and Sylvanas should be outside once more (Sylvanas mounted on the undead horse); when looking inside Undercity the Warsong Battleguards should have vanished

**Alliance version**
- preparation:
```
.quest remove 13371
.quest remove 13377
.quest add 13371
.go 1774.72 770.518 55.3043 0
```
- proceed with the quest
- after finishing the event, do not finish the quest "Battle for the Undercity", instead teleport to the position mentioned above, logout and wait a few minutes for the event to reset
- after login Wrynn and Jaina should be outside once more; when looking inside Undercity the Stormwind Elite soldiers should have vanished

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by comix1988** [comment]
in the next few days I will be testing this PR @Stoabrogga

**Comment by Stoabrogga** [comment]
@comix1988 
Sure, take your time. Thanks for looking into this :+1:

**Comment by comix1988** [comment]
I tested these fixes for both alliance and horde.
In both factions the event resets after a few minutes from completion, the npcs all return to their place and the guards disappear.

good job @Stoabrogga

**Comment by Stoabrogga** [comment]
@comix1988 
Great, thanks for testing this :+1:

**Pull request merged**
