### PR TITLE
fix(DB/Creature): Fixed Mist Howler

### PR DESCRIPTION
**Pull request by Asthalor**
## Changes Proposed:
-  Added 2 new spawns
-  Changed some coords of the original 2 spawns according to sniffs
- Added roaming to all of them, added to the same pool so only 1 can be spawned and changed the spawn time to 10h.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7750

## Tests Performed:

- .go c 32884, 51885, 945802 and 945803 and check the coords
- See if he moves

## How to Test the Changes:

1. .go c 32884, 51885, 945802 and 945803 and check the coords
2. See if he moves

Test

Spawn 1
howl spawn 1

Spawn 2
howl spawn 2

Spawn 3
howl spawn 3

Spawn 4
howl spawn 4

I reloaded between pictures, so we can see 2, but trust me there can be only one at the same time :P

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by syssneck** [comment]
Works and only spawns in one place at a time, but I'm really wondering about the `wander_distance` here. One spawn has a `wander_distance` of only 1,9 and the other spawn of 32,7? 
It's probably correct, because it's from the sniff data, but I just wanted to point this out.

**Review by Helias — APPROVED** [review]

**Comment by Asthalor** [comment]
> Works and only spawns in one place at a time, but I'm really wondering about the `wander_distance` here. One spawn has a `wander_distance` of only 1,9 and the other spawn of 32,7?
> It's probably correct, because it's from the sniff data, but I just wanted to point this out.

Yeah, i was sceptical at first, but by having the sniff data it seemed wrong to put 5 or 10 as we usually do. If people see that he moves wrong or too little we can always increase it.

**Comment by syssneck** [comment]
I kind of agree with @Efymer. Let's use the sniff data as a helpful tool, but not blindly trust it.

**Comment by Asthalor** [comment]
Fine by me, i will round them up

**Pull request merged**
