### PR TITLE
fix(DB/GameObject-Spawn): Solid Chests respawn time in Azshara

### PR DESCRIPTION
**Pull request by Otanikotani**
Fix Respawn times for several Solid Chests located in Azshara.

_Please also see comments, pooling is added as well_

## Changes Proposed:
-  `spawntimesecs` increased from 180 to 7200 for chests with guids `48362, 48363,48364, 48365, 48366, 48367, 48368, 48369, 48370, 48371`

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4836

## Tests Performed:
- Rebuilt (docker), linux host. 
- Tested locally, verified that spawn time is not 180 anymore. Screenshot:
Screenshot from 2021-03-13 16-18-39

## How to Test the Changes:
 - Teleport to any of `48362, 48363,48364, 48365, 48366, 48367, 48368, 48369, 48370, 48371` objects (use `.go gobject #object_guid`) 
 - Loot the chest.
 - Verify that the chest does not respawn in 3 minutes as it was before

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
This is just a suggestion - but add them all to a pool, then make 1-2 spawn at once, with a respawn time of maybe 10-15 minutes?

Then only 1 (or 2) will ever be present at once and once looted, a random one will pop into existence 10-15 minutes later.

With 2 hours respawn you can visit them all and loot them every 2 hours if no other players are there.

**Comment by Otanikotani** [comment]
@Zoidwaffle I think it is a good suggestion, I think I can do that as well, if needed

**Comment by JamesGent** [comment]
Tested and working.

**Comment by Otanikotani** [comment]
@Zoidwaffle Do you want pooling in the same PR or should I create a separate one? This is my first PR to this repository, do not really know the rules :)

**Comment by Otanikotani** [comment]
Added pooling. 
- No more than 2 chests spawn simultaneously
- Respawn time is 10 minutes. 

Tested by:
- Teleport around all spots and verify there are two chests. 
- Loot one of them
- Wait for the spawn time. 
- Teleport around all spots and verify there are two chests again.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
welcome @Otanikotani to AzerothCore and thanks for your first contribution!

also thanks @Zoidwaffle and @JamesGent for reviewing/testing this.

**Comment by Zoidwaffle** [comment]
@Otanikotani : looks good!

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
