### PR TITLE
fix(DB/Zone):improved Netherstom

### PR DESCRIPTION
**Pull request by Knindzagxg**
## Changes Proposed:
- Missing SAI creature updates.
- Improvements to existing if possible.

## Tests Performed:
- Applied SQL without problems.
- Tested Forgelords due Data / Out of combat casts.

## How to Test:
- Apply SQL(s).
- Restart Server (You can .reload creature_template for each creature as well, but will take time)
- Go to zone (Check PR name) and check creatures around - You can also spawn (.npc add) each by command.

## Source for Changes:
- [Wowhead](https://wowhead.com) Database and or comments.
- [WotlkDB](https://wotlkdb.com/) Multi checking trough Private DB's.
- [WowWiki](https://wowwiki-archive.fandom.com/wiki/Portal:Main) Can be useful for extra informations.
- [WowPedia](https://wow.gamepedia.com/Wowpedia) Cross checking trough comments if possible.
- [Retail](https://worldofwarcraft.com/en-gb/) In-game checking if previous don't have any required informations.

## Target Branch:
- [x] Master

## Operating System:
- Linux (Debian 10)

## How to Test AzerothCore PR's
When a PR is ready to be tested, it will be marked as **[Waiting to be tested]**.
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:
http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
First of all, it's better to have AI than none.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg @pklloveyou please specify whether you have tested these changes in game, so we can merged them

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
I simply tested it on each NPC to see if they would cause errors to the server

**Comment by claudiodfc** [comment]
This test is useless, SAI doesn't crash the server.

**Comment by Helias** [comment]
@azerothcore/testers please have a look

**Review by Helias — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
excellent feedback @Sedatyf , please @Knindzagxg have a look at those ❌

**Comment by Knindzagxg** [comment]
Awesome, thanks a lot mate xD

I will check those in next few minutes and update.

**Comment by Knindzagxg** [comment]
* Ethereum Nexus-Stalker updated. Will buff it self out of combat and rest of spells are mostly on proc -> Tested in-game and working pretty good. 
WoWScrnShot_050821_105520

**Comment by Knindzagxg** [comment]
* Shimmerwing Moth -> Fixed typo, good catch xD

**Comment by Knindzagxg** [comment]
* Nether Beast -> It should cast this one it's already up, so it can be stunned if damaged by Fire 
```Causes the target to be stunned when it takes fire damage. 1 charge. Last 8 sec.```

Other one is proc spell from first ID -> https://www.wowhead.com/spell=33731/judgment-of-the-flame

**Comment by Knindzagxg** [comment]
* Wrath Lord -> Removed Dual Wield, dunno why i even add tbh. Prolly was mistake xP
* Mana Beast -> They do have low health but they also have Mana Burn. Maybe sometimes there is a lot of them and Blizz decided to give them something. Updated it to cast between 20-80% hp (Once) so maybe they do some now xP

**Comment by Sedatyf** [comment]
Hey @Knindzagxg 
I tested your last changes. Everything looks good except for the Nether Beast. They don't cast spells on aggro (and I didn't understand what you meant in your comment 😓). Furthermore, they are walking very slowly. I don't know if it's was like that on retail, but it seems wrong to be honest.

**Comment by Knindzagxg** [comment]
Finally sorted that one.
For some reason there was issue with casting on it self -> Now it's working trough Aura.
Whole idea is to get that on it self, so fire spells can stun target.
Tested and its woooooorking xD

WoWScrnShot_051121_200617
WoWScrnShot_051121_200622

**Review by Hacki95 — APPROVED** [review]

**Comment by Sedatyf** [comment]
I tested it too and everything works as intended. Good job @Knindzagxg!

**Pull request merged**
