### PR TITLE
fix(DB): Stranglethorn Fishing Extravaganca Event NPC's & Gameobject 

### LINKED ISSUE #2404: Game Event "Stranglethorn Fishing Vale Competition" Event NPC  "Riggle Bassbait" Missing
##### SMALL DESCRIPTION:

During the stranglethorn fishing extravaganza event every sunday from 02:00 pm 04:00 pm the NPC which is needed to complete the fishing contest is not spawning. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The NPC "Riggle Bassbait" ID 15077 should spawn during the event every sunday at 02:00 pm and disappear at 04:00 pm server time.  

See:

https://classic.wowhead.com/npc=15077/riggle-bassbait

https://wowwiki.fandom.com/wiki/Riggle_Bassbait

Position of NPC should be:

https://www.gamingcfg.com/img/6338/Riggle-Bassbait.jpg
http://www.vanion.eu/uploads/media/article/0001/22/thumb_21672_article_big.jpeg

##### CURRENT BEHAVIOUR:

The game_event ID 15 the fishing pools spawn correctly, but he NPC ID 15077 does not appear during the given time. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele booty bay
2. Start the event using the command .event start 15
3. See the Screenshots above, the NPCs and Gobject is not spawned. 

##### BRANCH(ES):

AzerothCore rev. c69b05fb1c7c 2019-11-03 20:42:34 +0100 (pr-2381 branch)

##### AC HASH/COMMIT:

c69b05fb1c7c

##### OPERATING SYSTEM:

Windows 10 Pro 64 Bit

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83192332-game-event-stranglethorn-fishing-vale-competition-event-npc-riggle-bassbait-missing?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Endeffect-AT**
The Event NPC's Riggle Bassbait (id 15077), Jang (id 15078) & Fishbot
5000 (id 15079) were missing and had wrong coordinates so that the event
could not be completed. Now the NPC's & gamobject spawn during the game event id 15.

Position of the NPCs manually determined by screenshots, no unique source available!

##### CHANGES PROPOSED:

- Added new entry 164445 in gameobject table for 'soapbox' id 180403 with coordinates
- Added gamobject entry in game_event_gameobject
- Updatet coordinates for NPC 15077. 15078 & 15079 to be blizzlike as possible
- Insert NPC's entry in game_event_crteature 

##### ISSUES ADDRESSED:
- Closes #2404 

##### TESTS PERFORMED:
- Imported on Win 10 Pro 64 bit with HeidiSQL without errors
- Tested  .event start 15 (The NPC`s and the gameobject spawns as expected)

##### HOW TO TEST THE CHANGES:

**Don't merge before succesfully approved the following tests:**

- .event start 15 
- Check blizzlike behaviour for the NPC's and gameobjects position (No gps data found, so i had to manually re build the coordinates from screenshots online)
- check the event without the command upcoming sunday at 2 pm if it starts as axpected
- complete the event and check if all quests are working

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Endeffect-AT** [comment]
Sure, i change it tomorrow 👍🏻

**Comment by Endeffect-AT** [comment]
@Stoabrogga 

So ok? General question, are comments allowed?

**Comment by Stoabrogga** [comment]
Looks good now, thanks. You can add any comments to the SQL file that you want.

**Comment by Endeffect-AT** [comment]
So, tested ingame and works really fine 👍 The 3 NPC's spawn as expected such as the NPC Text from Riggle. All 3 Quests are working such as the win of the competition. 

Only thing what seems to be not correct is the dropping of one of the three rare fishes for the Fishbot 5000. Sometimes when the fishing is succesfull, no fish drops. Not like no fish has biten, just nothing happens. Someone recognized the samne or i just had not enough luck?

**Comment by Endeffect-AT** [comment]
Okay, checked the fishing_loot_template and the three rare fishes with item id 19803, 19805 & 19806 are completely missing. Will fix it!

**Comment by Maxximus1** [comment]
I've mounted the PR in the database, 
I activate event number 15.
The npc now appear.

**Comment by Endeffect-AT** [comment]
@Maxximus1 

Thx for testing! If you wanna do me a favor, pls test it like that again:

1. Shutdown your server
2. Change your PC Date & Time manually to a sunday at 1:55 pm or something
3. Start & Login and wait till the event starts like normal (The Creature Text from Riggle should appear)
4. If you logged in with a Character which has a fishing Skill over 225, the third Quest from the NPC Jang should also appear
5. Finish the Event such as the Quests

**Comment by Knindzagxg** [comment]
Sometimes, dunno why event does not even start when its time for it.
It was an old issue, and i think i never actually reported.

When it comes to this one, NPC's are perfect now, just need to keep eye on event it self.

**Comment by Endeffect-AT** [comment]
Hmmm okay, for me it worked every time i tried it. Every sunday 2 pm the NPC's are spawning as they should. Also if i simulated the date and server time on local host it worked fine.

Can you give us a bit more info how exactly you tested it?

**Comment by Knindzagxg** [comment]
Try to run server 7 days without restart and then test.

For some reason, it wasn't working for me after one week, there was no announce about event, there was no pools as well.

Same happened few times for Kaluk in Northrend.

**Comment by Endeffect-AT** [comment]
@Knindzagxg 
Ty, i will test it like that too.

**Comment by Stoabrogga** [comment]
In order to simplify testing you could reduce the time interval for the event from 7 to 2 days, the mechanic itself should stay the same:
```sql
UPDATE `game_event` SET `occurence` = 2880 WHERE `eventEntry` IN (14,15,62);
```
Sorry, I'd love to further help here, but currently just don't have the time.

**Comment by Endeffect-AT** [comment]
Thx for the tipp! :)

**Comment by Endeffect-AT** [comment]
I have now observed the activities of the events for 3 days with an occurrence of 1440 (daily). Both events start and end as it should be. I have never had any problems with other events that they did not match the calendar. 
Nevertheless, keep an eye on the events if some have the problem ...

In my opinion, the fix should be merged when 2 people have at least confirmed the correct npc's (which is also the goal of the PR).

**Comment by FrancescoBorzi** [comment]
good job @Endeffect-AT  and @pangolp

**Pull request merged**
