### PR TITLE
fix(DB/Creature): Grunda Bronzewing is now mounted

### PR DESCRIPTION
**Pull request by Dr-Arayashiki**
Grunda Bronzewing is now mounted

## Changes Proposed:
-  Grunda Bronzewing is now mounted

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15781

## SOURCE:

https://www.wowhead.com/wotlk/npc=35101/grunda-bronzewing

## Tests Performed:

- in-game test
- just a lack of mount id display

## How to Test the Changes:

1. tele honorhold
2. Walk up to Bronzewing.
3. NPC Grunda Bronzewing is now mounted.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Thanks for the PR

Never delete and insert into creature_template when it isnt necessary. Use update instead

**Comment by heyitsbench** [comment]
What changed between your query and what was there before? I can't see any difference between the two entries.

**Comment by Dr-Arayashiki** [comment]
> O que mudou entre sua consulta e o que havia antes? Não consigo ver nenhuma diferença entre as duas entradas.



> What changed between your query and what was there before? I can't see any difference between the two entries.

UPDATE `creature_template_addon` SET `mount` = 1769 WHERE (`entry` = 35101);

**Comment by heyitsbench** [comment]
> UPDATE `creature_template_addon` SET `mount` = 1769 WHERE (`entry` = 35101);

But that's not what's in the PR.

**Comment by Dr-Arayashiki** [comment]
> 



> > UPDATE `creature_template_addon` SET `mount` = 1769 WHERE (`entry` = 35101);
> 
> But that's not what's in the PR.

oh yes i should have used udate, sorry

**Comment by heyitsbench** [comment]
Might need to rename the file to something like `fix-grunda.sql`, looks like the workflow doesn't like the spaces in the file name.

**Comment by Dr-Arayashiki** [comment]
> Might need to rename the file to something like `fix-grunda.sql`, looks like the workflow doesn't like the spaces in the file name.

I renamed the file :)

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
