### PR TITLE
fix(Core/Player): Allow to swap bags when they are filled

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17084
- closes https://github.com/chromiecraft/chromiecraft/issues/6070

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Need check if bag can hold all items e.g smaller bag and also if it’s appropriate e.g soul bag mining bag etc

**Comment by Kitzunu** [comment]
I tested swapping big filled bag to small filled bag, don't work. So that is good.
I also tested switching normal bag to mining bag. Dont work, so also good

**Comment by heyitsbench** [comment]
Interestingly I've tried switching a felcloth bag with an herb bag in [this situation](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/ba6fc0d0-9e67-49fc-8c4f-6b52f40b2f23), and it gave [this error](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/e2a18308-d430-4bb2-8303-2240c2efdac3), which doesn't sound correct. Still need to check with bank bags.

**Comment by Kitzunu** [comment]
I also tested filled mining bag (20slot), to normal bag (20slot), to mining bag. Works too

**Comment by Kitzunu** [comment]
As for swapping mining bag onto bag with normal items on it, it gives the same error bench got. So that is good I guess

**Comment by heyitsbench** [comment]
Bank-wise, I've swapped bags between existing bags in the bank: the items don't leave the bag they were in before the swap. I've swapped bags between a bag in my backpack and one in the bank, the item in the bank bag stays in the bank bag in the position post-swap. If too many items are in the bank bag to swap into the new bag, it gives the error `These items cannot be swapped.` Seems to yield the same results with specialized bags as in the normal inventory. (e.g. the aforementioned herb bag/felcloth bag swap circumstance) All looks good. 👍

**Comment by elthehablo** [comment]
Don't forget to include CC issue

**Comment by Kitzunu** [comment]
If you see me forget it, please at least link the issue for me so I don't have to go looking for it. I don't work for cc 🤷

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
