### PR TITLE
feat(DB/Item_template): Set Adamantite Shell Machine GCD to zero

### PR DESCRIPTION
**Pull request by Pyromanihack**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17201
- Closes https://github.com/chromiecraft/chromiecraft/issues/5149

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. `.additem 34504` Adamantite Shell Machine
2. `.additem 20475` Adamantite Arrow Maker
3. Now Adamantite Shell Machine has not a GCD (like Arrow Maker)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Just to confirm, you yourself tested this on live servers?

**Comment by Pyromanihack** [comment]
> Just to confirm, you yourself tested this issue on live servers?

First I observed the bug on my local server, and then I applied the changes and re-tested on local

**Comment by heyitsbench** [comment]
> First I observed the bug on my local server, and then I applied the changes and re-tested on local

My concern is no source for the bug in the original issue(s).

**Comment by Pyromanihack** [comment]
> > First I observed the bug on my local server, and then I applied the changes and re-tested on local
> 
> My concern is no source for the bug in the original issue(s).

I'm updating the sources

**Comment by samsam1993** [comment]
This seems to be a core-related issue. The GCD does not go away with this SQL modification.

**Comment by The-GhostRider** [comment]
> This seems to be a core-related issue. The GCD does not go away with this SQL modification.

It works..
Delete Cache..

**Review by The-GhostRider — APPROVED** [review]
it's good.
For me ti can be merged..

**Comment by Kitzunu** [comment]
Did you test this on live servers? (I know the template says so I just want to make sure)

Not saying it should have a GCD, but perhaps it should have an ICD

Because just to throw a wrench in this change

image

**Comment by The-GhostRider** [comment]
> Did you test this on live servers? (I know the template says so I just want to make sure)
> 
> Not saying it should have a GCD, but perhaps it should have an ICD
> 
> The spell has no GCD in DBC data, so there is nothing wrong with the spell. It is the item that has the cooldown so the proof from wowhead about the spell is useless.
> 
> Because just to throw a wrench in this change
> 
> ![image]

"This is strange, though, because there is a senseless discrepancy on Wowhead...
HERE: [Adamantite Shell Machine](https://www.wowhead.com/wotlk/item=34504/adamantite-shell-machine)
We have an ICD (Internal Cooldown) on the item of 1500ms
image

While HERE: [Adamantite Arrow Maker](https://www.wowhead.com/wotlk/item=20475/adamantite-arrow-maker)
There is a discrepancy with its counterpart...
image

Now, these two items/spells essentially do the same thing... except one gives you "Arrows" and the other gives you "Ammo."

Why does one have an ICD and the other doesn't? (I wonder).

- Is it a Blizzard mistake? (an oversight)
- Is it right for both to have an ICD?
- Is it right for both not to have an ICD?

What is the difference?"

Give an explanation to this @Kitzunu

**Comment by Kitzunu** [comment]
I don't know, this is why I ask it to be properly investigated. 

Sometimes I need to play the devil's advocate when things are just presented out of a hunch or from wowhead. I don't want random things being pushed into the core to later just be reverted because it was just wrong.

But this could be a classic case of Blizzard being Blizzard. Sometimes that is the only explanation to their behavior.
It is also the reason as to why we should never trust wowhead. But Bench will check it out on live servers.

**Comment by The-GhostRider** [comment]
> I don't know, this is why I ask it to be properly investigated.
> 
> Sometimes I need to play the devil's advocate when things are just presented out of a hunch or from wowhead. I don't want random things being pushed into the core to later just be reverted because it was just wrong.
> 
> But this could be a classic case of Blizzard being Blizzard. Sometimes that is the only explanation to their behavior. It is also the reason as to why we should never trust wowhead. But Bench will check it out on live servers.

Instead, you know, maybe I've found an explanation for this discrepancy...

Do you know what it might be (in my opinion)?
If you look at the item descriptions, the two items are nearly identical!
They only differ in two things...

The name of the item
and the "Warning" that's present in only one of them...
Is it possible that Blizzard added those 1500ms of ICD as a form of "Role Play" to fit the context of the role-playing game, and since the item "Warns" that it "Contains Explosives" and should be handled with care... they inserted that CD for that reason...

So it's just a nonsensical role-play element... 🤣🤣🤣

**Comment by Pyromanihack** [comment]
Interesting point of view, Ghostrider

At this point, I'd say I can close this PR because it's blizzlike

**Pull request closed without merging**
