### PR TITLE
chore(Core/Cache): Remove an assert breaking 1v1 arena module

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by Kitzunu** [comment]
Add log_error then.
The assert was put there for a reason

**Comment by acidmanifesto** [comment]
> Add log_error then. The assert was put there for a reason

 I am curious about the logical inconsistency being detected with it being a assert. i wonder if this assert was suppose to be a log to begin with from whatever source it was refactor from.

**Comment by acidmanifesto** [comment]
> Add log_error then. The assert was put there for a reason

This is to correct the issue of the 1v1 module breaking. If it was with out the 1v1 module then this will make sense to have that assert. But since the 1v1 module is a catelog module, this assert really has no purpose.

**Comment by Kitzunu** [comment]
Yea. But if you dont use it this might be valuable information

**Comment by Nyeriah** [comment]
Not really, I removed the asserts from everywhere else, I had just forgotten this one. It makes sense for Trinity to have this because they don't have wild settings like we do, but since mods have freedom to do anything, it's pointless to log this while things are operating as expected.

**Review by Winfidonarleyan — APPROVED** [review]

**Pull request merged**
