### PR TITLE
Fix(DB/Script): Phase change for DK starter area Eye of Acherus and npcs.

### PR DESCRIPTION
**Pull request by Rorschach91**
## Changes Proposed:

This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- CLOSES https://github.com/azerothcore/azerothcore-wotlk/issues/20142#issue-2568572596 

## SOURCE:

The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Create a dk and start the chain quest.
2. Use .mod phase 1 and 2 to change your character phase to see the differences.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
If all that's changing here is the phase masks, I'd personally prefer `UPDATE` statements.

**Comment by Rorschach91** [comment]
> If all that's changing here is the phase masks, I'd personally prefer `UPDATE` statements.

On the PR's title?

**Comment by heyitsbench** [comment]
No, instead of the `DELETE`/`INSERT` query pairs you have set in the PR right now, I would prefer seeing `UPDATE` statements.

**Comment by Rorschach91** [comment]
> No, instead of the `DELETE`/`INSERT` query pairs you have set in the PR right now, I would prefer seeing `UPDATE` statements.

Done.

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
not sure if in this case we should add/remove the single phase value to the current phasemaks similarly to the flags
```sql
UPDATE `creature` SET `phaseMask` = `phaseMask`+2 WHERE ...
-- or phaseMask = phaseMask|2
```
to avoid any potential overwrite of other SQL queries, do we?

**Comment by Nyeriah** [comment]
https://www.azerothcore.org/wiki/sql-standards#flags-amp-bits

**Comment by Rorschach91** [comment]
Rewritten

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
Good job, the code looks good to me, if for the other reviewers is ok, I would merge it

**Pull request merged**
