### PR TITLE
fix(Scripts/DB): Improve Demon Portals and convert to SAI

### PR DESCRIPTION
**Pull request by Raelorasz**
## Changes Proposed:
- Convert Demon Portal behaviour from C++ script to SAI
- Demon Portals will now correctly glow purple on use, and will be despawned when their guardians are killed
- Lowered Demon Portal respawn time to 5 minutes (was 15 minutes)
- If the guardians are disengaged and left alone they will despawn two minutes after they have been summoned, along with the portal
- Players will now only be able to interact with the portals if the related quest is not complete
- Adjusted 'Portals of the Legion' quest (ID 5581) POI points to better reflect portal positions

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5798

## SOURCE:

[Footage of the quest from classic](https://www.youtube.com/watch?v=0QQrqOgJRS8)
https://classic.wowhead.com/quest=5581/portals-of-the-legion#comments

## Tests Performed:

- Tested in-game. Windows 10 - enUS client.

https://user-images.githubusercontent.com/82320853/120119340-8aede100-c197-11eb-87b0-7ae890c855e4.mp4

WoWScrnShot_053021_221937

## How to Test the Changes:

1. `.q a 5581`
2. `.go go 30899`
3. Play through the quest

## Known Issues and TODO List:

These Demon Portals have different entries for no apparent reason, maybe they could be grouped up in a single one.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
excellent work @Raelorasz !

**Comment by Sedatyf** [comment]
No test needed @FrancescoBorzi? You want to test it in production?😛

**Comment by FrancescoBorzi** [comment]
@Sedatyf the author tested it and provided evidence + he is already a contributor + it is not a delicate change

that's why :)

**Comment by Sedatyf** [comment]
Haha it was a joke. You're the boss, chief 😄

**Pull request merged**
