### PR TITLE
fix(DB/creature_template): Correct speed_run and speed_walk

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Correct speed_run and speed_walk, taken from vmangos
-  https://github.com/vmangos/core/commit/f0a1fbfc87d97d8a876bf569ca9eb09729714cdd
- https://github.com/vmangos/core/commit/a6919c7e5b86dc94c14ec0c0e9566d2c317b038c
- I have added a lot of co-authors since it wasn't my idea to do this

## Issues Addressed:
- The new speeds should be more accurate

## Tests Performed:
- Applied SQL, checked a few creatures, I don't really know what is correct tbh

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
@Knindzagxg and @T1ti, this one is for you guys - I hope it's useful!

**Comment by Knindzagxg** [comment]
Cheers mate.
Will check once i get a bit more time.

**Comment by Zoidwaffle** [comment]
@Knindzagxg, thanks, no stress :smile:

**Comment by pklloveyou** [comment]
Better than ever

**Comment by Zoidwaffle** [comment]
@pklloveyou : I guess you tested some of these mobs and no obvious errors found?

@Knindzagxg : sorry for poking you, did you find time to have a look at these changes?

I'm trying to see if I can clean up my various PR's and get them merged, so going over all these now :smiley:

**Comment by Knindzagxg** [comment]
Totally forgot to post.

Tested and checked more then 60% and it looks good.

PS ->
Try and check what is diff between PR and current DB.
Lots of them have same speed at the moment, and if we can see what is real difference it would be much easier to check and test every single of them.

**Comment by Zoidwaffle** [comment]
Check, I will try to make a diff later :+1:

**Comment by Zoidwaffle** [comment]
@Knindzagxg : Have a look now. Added the name of the creature and the former walk/run speeds (both values, even if only 1 is changed). Pretty funky that totems have a speed for moving btw...

**Comment by Zoidwaffle** [comment]
I deleted 497 entries, as they had no changes...

**Comment by Knindzagxg** [comment]
Awesome mate, this is perfect now.

I will start checking tonight and hopefully finish on friday.

**Comment by Knindzagxg** [comment]
All seems good mate.

Soz cause waiting this much.

**Review by Knindzagxg — APPROVED** [review]

**Comment by Zoidwaffle** [comment]
@Knindzagxg : it's all good, cheers!

**Pull request merged**
