### PR TITLE
fix(DB): Gorbold Steelhand incorrectly has Cataclysm Gossip Text

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Corrects Gossip text for NPC Gorbold Steelhand (NPC 6301). His current text is from Cataclysm expansion.
- Correct WotLK text was already in DB, so just need to be set correctly.

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Original WotLK leveling video:
https://youtu.be/P8cXHJcb50o?t=2m19s

## Tests Performed:

Capture

## How to Test the Changes:

1. .go creature 37980
2. See gossip text is now correct

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
cata text should be deleted as wel

**Review by acidmanifesto — APPROVED** [review]

**Comment by Lynethris** [comment]
@ZhengPeiRu21 I got this SQL error.

Screenshot 2022-03-29 212442

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21 I got this SQL error.


Sorry, I made the fix in GitHub UI so wasn't notice that it used apostrophe and not backtick. It should now be fixed.

**Comment by Lynethris** [comment]
Tested and work.

**Comment by acidmanifesto** [comment]
Thank you for the PR.

**Pull request merged**
