### PR TITLE
fix(DB/SAI): Port 'Finding the Keymaster' RP from TDB

### PR DESCRIPTION
**Pull request by avarishd**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5017
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14999

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Video and TDB
* GO spawn
-- cherry-pick https://github.com/TrinityCore/TrinityCore/commit/e0ccfefb462e045cfaa07353421c4d4e5b02bc49
-- Co-Authored-By: offl <11556157+offl@users.noreply.github.com>
## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

.q add 10256
.add 28786
.go c 69740
Use the item

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by al3xc1985** [comment]
When devs from azeroth core, will learn to give the credits for all the info they port?
Link ?
Credit to who?

We are having great issues in this community with all data that is taken from other platforms

**Comment by avarishd** [comment]
You can see all my previous prs I've given credit every single time when i could find one.

**Comment by avarishd** [comment]
And to top it off the only thing "taken" from TDB is the GO sniff spawn, but you do you.

**Comment by avarishd** [comment]
This is the sql of the sniff, if you could give me name who had it sniffed I would credit them without a question.
https://github.com/TrinityCore/TrinityCore/blob/3365e6a4b84f59cca5f7ef5fca71fb3979697e52/sql/old/9.x/world/22012_2022_03_06/2022_03_05_30_world_2021_01_04_01_world.sql#L14

**Comment by al3xc1985** [comment]
I suggest add the name and link your description as
-- link
-- name

I've seen many problems cause by ppl not seeing their credit name on other projects.
So it's good to avoid them

**Comment by avarishd** [comment]
Fair enough.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
