### PR TITLE
fix(DB/SAI): Steam Pump Overseer toughen not stacking.

### PR DESCRIPTION
**Pull request by avarishd**
On Just Summoned SAI is used for #13618 (NYI)

## Changes Proposed:
- Add knockdown proc to creature_template_addon
- Make toughen add 1 stack for every 10% missing health.
- Add no_exp extra flag 

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14440
- Closes https://github.com/chromiecraft/chromiecraft/issues/4692

## SOURCE:

https://youtu.be/79XhAIFv9L8?t=244
https://youtu.be/SohyP4uZucY?t=187 - no exp
cmangos
## Tests Performed:

- tested

## How to Test the Changes:

.go c id 18340
confirm knockdown happens
Use gm spells (.learn all gm) - dmg1-3
Push him slowly from 100% hp to 10% hp, confirm that the npc gains 1x stack every 10% missing health, up to 9 stacks at or under 10% health.
Kill it and see that it doesn't give any exp.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Can't it be done in SAI?

image

Also Knockdown is supposed to be triggered by an aura, according to Cmangos

**Comment by Nyeriah** [comment]
Hey @avarishd 

Thanks for the PR. However, we don't script open world creatures in C++ unless there's absolutely no other way to script them and they have complex scripts. At first glance, it doesn't seem to be the case here. What led you to opt for moving it to C++?

Regards.

**Comment by Gultask** [comment]
Here's the Cmangos's script:

```
INSERT INTO `creature_ai_scripts` (`id`, `creature_id`, `event_type`, `event_inverse_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action1_type`, `action1_param1`, `action1_param2`, `action1_param3`, `action2_type`, `action2_param1`, `action2_param2`, `action2_param3`, `action3_type`, `action3_param1`, `action3_param2`, `action3_param3`, `comment`) VALUES
(1834001, 18340, 11, 0, 100, 0, 0, 0, 0, 0, 0, 0, 54, 0, 0, 10045, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Say on Spawn'),
(1834002, 18340, 1, 0, 100, 0, 1000, 1000, 0, 0, 0, 0, 11, 6961, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Knockdown Proc OOC'),
(1834003, 18340, 2, 0, 100, 1024, 90, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen I at 90% HP'),
(1834004, 18340, 2, 0, 100, 1024, 80, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen II at 80% HP'),
(1834005, 18340, 2, 0, 100, 1024, 70, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen III at 70% HP'),
(1834006, 18340, 2, 0, 100, 1024, 60, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen IV at 60% HP'),
(1834007, 18340, 2, 0, 100, 1024, 50, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen V at 50% HP'),
(1834008, 18340, 2, 0, 100, 1024, 40, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen VI at 40% HP'),
(1834009, 18340, 2, 0, 100, 1024, 30, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen VII at 30% HP'),
(1834010, 18340, 2, 0, 100, 1024, 20, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen VIII at 20% HP'),
(1834011, 18340, 2, 0, 100, 1024, 10, 0, 0, 0, 0, 0, 11, 33962, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Steam Pump Overseer - Cast Toughen IX at 10% HP');
```

**Comment by avarishd** [comment]
I guess I thought it would looks weird in SAI, good to know that for world creatures SAI > cpp. (depending on complexity of course)
Also time to get cmangos world db.

**Review by Gultask — APPROVED** [review]

**Pull request merged**
