### PR TITLE
fix(Script/Quest): Moved Shay Leafrunner's script from DB to C++.

### LINKED ISSUE #1535: Quest:Wandering Shay
<Quest:Wandering Shay cannot complete>

##### SMALL DESCRIPTION:
this is an escort quest.
Take the Shay's Bell (https://vanilla-twinhead.twinstar.cz/?item=9189) into "Shay's Chest" on the floor and with it you can call Shay Leafrunner back to you when she goes away;
Escort the NPC to Rockbiter(https://vanilla-twinhead.twinstar.cz/?npc=7765) for complete the quest

##### EXPECTED BLIZZLIKE BEHAVIOUR:
You must escort the npc Shay Leafrunner to the end point of quest, npc Rockbiter (https://vanilla-twinhead.twinstar.cz/?npc=7765) and call her back with Shay's Bell if she goes away during the trip.
Arrived to Rockbiter the quest was completed.

##### CURRENT BEHAVIOUR:
the quest cannot be completed;
the NPC Shay Leafrunner (https://vanilla-twinhead.twinstar.cz/?npc=7774) walks into the mountain and doesen't return back using the Shay's Bell (itemid 9189), so the quest is not completable

##### STEPS TO REPRODUCE THE PROBLEM:
1.find and talk with Shay Leafrunner take the quest 2845;
2. take the quest 2845 and the npc ( Shay Leafrunner) disappear;
3. open the "Shay's Chest" on the floor and take Shay's Bell(id 9189);
4.escort the npc but can't complete the quest.

##### BRANCH(ES):
staging

##### AC HASH/COMMIT:
https://github.com/azerothcore/azerothcore-wotlk/commit/44272f169c49f20c79b78aeea634f3bc7c2dafd1

##### OPERATING SYSTEM:
linux
screenshot 69
screenshot 68

### LINKED ISSUE #6722: Feralas - Quest "Wandering Shay" Not Completing, Missing Scripted Text
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/1083

The escort quest Wandering Shay (https://wowgaming.altervista.org/aowow/?quest=2845) does not complete upon reaching the end destination.

Shay Leafrunner (https://wotlk.evowow.com/?npc=7774) Is also missing her scripted text lines, also her movement speed is too fast judging by classic WoW video.
GUID 50144

Tester: Confirmed the above. Also, she doesn't wander off, which seems to be half the point of the quest. (It's an escort quest, and she gives you a bell to ring when she wanders off to call her back.) When I ran it, she behaved like a pet, just following me constantly and not wandering off at all. While this made the quest rather more pleasant, it was not Blizzlike.

Looking at the DB, Shay does have a number of events set in SmartAI that are supposed to trigger once she gets within 10 yards of Rockbiter (the quest goal NPC), so not sure why they aren't activating. Rockbiter, who is supposed to end the quest, doesn't have any scripts running at all.

Quest handin not possible despite having brought her to the right spot and having the bell:
WoWScrnShot_070421_230720

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Quest should complete upon reaching the end destination.
Shay Leafrunner should be using her scripted text lines during the escort, and should have episodes of wandering randomly until called back by the bell.

##### SOURCE:

https://youtu.be/sb3H2P1yT5U?t=1329
https://classic.wowhead.com/quest=2845/wandering-shay#comments

##### STEPS TO REPRODUCE THE PROBLEM:

1. Teleport to GUID 50144
2. Accept the quest Wandering Shay and loot the bell from the box nea her feet
3. Escort her to Rockbiter camp and see it does not complete
4. Observe no scripted text from her

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99646044-feralas-quest-wandering-shay-not-completing-missing-scripted-text?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #1535
Fixes #6722

## Issues Addressed:

- Closes #1535
- Closes #6722
- Closes https://github.com/chromiecraft/chromiecraft/issues/1083

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Teleport to GUID 50144
2. Accept the quest Wandering Shay and loot the bell from the box nea her feet
3. Escort her to Rockbiter camp and see it does complete the quest
4. Observe the whole script.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
@azerothcore/testers  please have a look here

**Comment by stoudtlr** [comment]
@UltraNix i can test after merge conflict resolved

**Comment by UltraNix** [comment]
@syssneck You can do it now.

**Comment by stoudtlr** [comment]
Everything with the quest works now.  Was able to complete and turn it in.  Did see one small issue.  After you get to Rockbiter, Shay does say her dialogue line, but then also says the same dialogue line from the beginning of the quest about getting her bell from the chest.
image

**Comment by stoudtlr** [comment]
I could only find one video of the quest and that line wasn't repeated.  Video says it's from classic, but I'm not sure either. It's been almost 15 years since I've done these quests. Lol

https://youtu.be/2DXOsO7Lv3I
Can start at 2:45

**Comment by stoudtlr** [comment]
Thanks @syssneck! This PR makes everything work exactly as shown in the video you found except for Shay repeating that line.

**Review by Helias — APPROVED** [review]

**Comment by syssneck** [comment]
@Helias there is still one small issue with Shay repeating one message: https://github.com/azerothcore/azerothcore-wotlk/pull/7801#issuecomment-923879100

**Comment by Helias** [comment]
Oh, sorry

**Pull request merged**
