### PR TITLE
fix(SQL/smart_scripts) target in script 1436800

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/AdonisWOW/bugtracker/issues/11

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. TP to the npc: `.go c 247567`
247567 - (entry: 14368) [Lorekeeper Lydros X:164.335 Y:522.497 Z:-48.3836 MapId:429]
2. Take quest 7482: `.quest add 7482`
3. Interact with the skeleton that is nearby

Having the wrong target, at least in Spanish (I don't know about other languages, the NPC can't recognize the player's gender and the dialogue is displayed incorrectly)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
This will not accomplish what you want. `MaleText` and `FemaleText` operate based off the gender of the creature saying the text whereas `$g` operates based off the gender of the target of the text.

**Comment by pangolp** [comment]
> This will not accomplish what you want. `MaleText` and `FemaleText` operate based off the gender of the creature saying the text whereas `$g` operates based off the gender of the target of the text.

Why then is it currently failing to achieve these results?

image

**Comment by heyitsbench** [comment]
> Why then is it currently failing to achieve these results?

Likely because the creature has no target for its text.

**Comment by pangolp** [comment]
> Likely because the creature has no target for its text.

Could be.

**Comment by pangolp** [comment]
@heyitsbench You are absolutely right.

WoWScrnShot_100624_144528

WoWScrnShot_100624_144533

WoWScrnShot_100624_144539

WoWScrnShot_100624_145209

WoWScrnShot_100624_145213

WoWScrnShot_100624_145220

The error is in the target.

**Comment by pangolp** [comment]
Now it works. Thanks @heyitsbench 

WoWScrnShot_100624_151010

WoWScrnShot_100624_151016

WoWScrnShot_100624_151023

**Review by Nefertumm — APPROVED** [review]

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
