### PR TITLE
fix(DB): Various database cleanups

### PR DESCRIPTION
**Pull request by Endeffect-AT**
With this PR I want to fix some DB bugs that I have tracked in the game. 

Removing "[DEPRECATED]" quest titles
--------------------------
Some quests which are live ingame have a title like "[DEPRECATED]" or "Deprecated:". 
Many of these quests are active and can be completed.  
I just removed the strings that contain "deprecated" and updated the entries.  

Removing Highvale Ranger titles "PH MODEL WIP"
------------------------------------------------------------

Those NPCs are found in Hinterlands .go 324.5412129 -2677.939453 117.246620 0 and now have this title:

image

This title have to be removed as the modoel is already up to date! 

**Source:** https://wow.gamepedia.com/Highvale_Ranger (See former appearance)

The title was also removed on Rising Gods P-Server (Best WotLK server for german language over 10 years now) and is declared as db error:

https://redmine.rising-gods.de/issues/22936

Old Model:
image

Reworked (actual) Model:
image

##### CHANGES PROPOSED:
- removed `Title` LIKE '%deprecated%' in quest_template_locale for deDE which are NOT included in disables table  - See the comments in File: Many of them were completed by myself ingame (34)
- removed `Title` LIKE '%WIP%' in creature_template_locales for all locales (8)

-  Fixed the weapon in offhand

##### ISSUES ADDRESSED:
- Closes

##### TESTS PERFORMED:
- Imported on win 10 pro 64 & HeidiSQL 10.3.0.5771 without errors and checked the changes

##### HOW TO TEST THE CHANGES:

- Just import the sql file with an GUI of your trust and check that no error occurs.

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stoabrogga** [comment]
- Are those quests really obtainable by normal means? I play a lot on my own server (regular player, not GM) and never saw a quest containing "deprecated" in it's title.
- Why are you completely removing the title from some quests? Even "deprecated" would be better than having no title at all in my opinion.

**Comment by Endeffect-AT** [comment]
> * Are those quests really obtainable by normal means? I play a lot on my own server (regular player, not GM) and never saw a quest containing "deprecated" in it's title.
> * Why are you completely removing the title from some quests? Even "deprecated" would be better than having no title at all in my opinion.

Yes, I actually came across it in-game, but concerns more the deDE locales. 
I was aware that some titles are empty. In any case, the title deprecated is wrong, so what can we do:

1. Find the right title for those inactive quests

2. Clearly mark the inactive quests with [Deactivated] or something

3. If we choose point 2 we should do it for more than these quests?

**Comment by Stoabrogga** [comment]
We could also try to identify those quests and ensure that they are not obtainable in the game. The title "deprecated" is a good hint to know that this quest was removed or replaced by another one.

**Comment by Endeffect-AT** [comment]
gladly, is there a simple solution to implement this for all quests?

**Comment by Endeffect-AT** [comment]
Thats okay for me! The reason why I wanted to remove the texts is either there for all or none at all.

**Comment by Stoabrogga** [comment]
I don't see any benefit in removing the "deprecated" strings. They are there for a reason (quest is invalid / disabled / deactivated however you may call it). If a title for a single quest, which is still obtainable in-game, is wrong then please just fix this single quest but don't just randomly remove parts of the quest titles without actually doing some research about those quests.

**Comment by Endeffect-AT** [comment]
And I see no advantage in keeping the titles, whether the quest is active or inactive. In case it is active -> wrong. In the event that it is inactive -> why note in the title and not just make a new column with active / inactive ???

**Comment by Stoabrogga** [comment]
The benefit in leaving the "deprecated" in the title is in seeing at once that this quest is invalid. If such a quest shows during normal gameplay you know that you have found a bug and can fix it (either fix the quest because it was replaced / removed or just fix the quest title). No need to extend the data model for this.

**Comment by Endeffect-AT** [comment]
I totally agree with you, but if there is, then there should be a uniform solution. I don't think the text in the title is good because it is cumbersome to edit separately. If quests are no longer lockable, then the ~ 150 "deprecated" titles won't help us much. If so for all or none at all. My opinion.

**Comment by Stoabrogga** [comment]
They help if you work directly with the DB. Sorry, but in my opinion the titles should stay as they are and only be changed if a quest has _definitely_ a wrong title. But ultimately it's staff decision if a PR is merged, not my own, so let's see what others think on that matter.

**Comment by Endeffect-AT** [comment]
The strings I removed are probably less than 10% of all quests that are inactive. They don't have a "deprecated" title and it doesn't matter ... You are welcome to do the work and correct the individual active ones now or find a good solution for all quests.

**Comment by FrancescoBorzi** [comment]
I appreciate your contribution @Endeffect-AT but I agree with @Stoabrogga 's points.

I've also never experienced seeing such titles as a player, so I guess it would be handier to keep those titles the way they are unless we have a strong reason not to.

**Comment by Stoabrogga** [comment]
> You are welcome to do the work and correct the individual active ones now or find a good solution for all quests.

I don't see the need to do this. In my opinion, if a quest is wrong, solve it on case to case basis. But I'm just repeating myself...

**Comment by Endeffect-AT** [comment]
That is exactly why I would like to discuss it. In addition, I presented a solution that just doesn't fit - that's the way it is.
Thanks for your opinion @FrancescoBorzi . 
As a perfectionist, I just cannot agree with myself why half a solution is better left as it is than changing something and maybe improving it.

**Comment by BarbzYHOOL** [comment]
I agree with Stoabrogga, the name "DEPRECATED" is really useful in my opinion to know what is blizzlike and what is NO MORE blizzlike. How many times it helped me for creatures too ? I mean I could even just get one creature and use it for my custom stuff, knowing it would not interfere

**Comment by Endeffect-AT** [comment]
You convinced me i will take care of it after christmas and only rename the active quests for the deDE locales.  However, I will come up with something how to make the marking uniform and that for all quests.
However, I will come up with something how you can perhaps make the marking uniform and that for all quests.

Just to clarify that, I'm glad if you tell me what makes sense and what a mistake, that's the only way I learn.  I will annoy you with it for a long time 😁

What about the NPCs and the missing weapon?

**Comment by Stoabrogga** [comment]
> What about the NPCs and the missing weapon?

Removal of this strange title is ok (it's also not there for the English version). Concerning the weapons... I don't really care, as this is a very minor issue. If you have the time to fix it, please go ahead.

**Comment by Endeffect-AT** [comment]
Still wip

**Comment by BarbzYHOOL** [comment]
the missing weapon? sorry i quickread it and i don't see what you are talking about xD

**Comment by Endeffect-AT** [comment]
Ready for review & test

- deleted help lines after blizzlike check
- tested script

References confirmed with https://db.rising-gods.de/ & compared entries with disables

**Comment by BarbzYHOOL** [comment]
just to be sure, creature template 2694 is used in NON-DEPRECATED quests, right?

**Comment by Endeffect-AT** [comment]
> just to be sure, creature template 2694 is used in NON-DEPRECATED quests, right?

Richt, they have nothing to do with the quests above. Just a bug in the title...

**Comment by BarbzYHOOL** [comment]
it's the Highvale Ranger, weird that nobody ever talked about it, alright I approve this PR from the look of the sql file

**Comment by Stoabrogga** [comment]
> it's the Highvale Ranger, weird that nobody ever talked about it

The English version of the Highvale Ranger is already correct, only the other languages got the wrong title. I checked the SQL script and compared it with the original values, looks good so far. The weapons are also ok.

**Comment by BarbzYHOOL** [comment]
> > it's the Highvale Ranger, weird that nobody ever talked about it
> 
> The English version of the Highvale Ranger is already correct, only the other languages got the wrong title. I checked the SQL script and compared it with the original values, looks good so far. The weapons are also ok.

ah ok thank you for explanation !!

**Comment by Endeffect-AT** [comment]
Thx for approving guys!

**Pull request merged**
