### PR TITLE
Core/Scripts: NPC Iruk gossip from DB

### PR DESCRIPTION
**Pull request by poszer**
NPC Iruk use gossip from DB [Iruk](https://www.wowhead.com/npc=26219/iruk)
[Quest for it](https://www.wowhead.com/quest=11961)

##### CHANGES PROPOSED:

-  Added already existing DB gossip content.
-  Added correct spell enum from spell_creature_ to spell_create_.
-  Replaced switch case with if statement.

###### ISSUES ADDRESSED:

Closes 

##### TESTS PERFORMED:

========== Build: 3 succeeded, 0 failed, 12 up-to-date, 1 skipped ==========
Builded without errors on Windows. Tested in game, everything work as intended, quest can be done normally, the interaction with the Iruk is also okay, the gossip works.
Picture below, with this commit : 

IrukFix

Infos : 
Wowhead

##### HOW TO TEST THE CHANGES:

1. .quest add 11961
2. .go creature 105531  - Try to speak with Iruk and click on the menu. ( You should be able to finish quest ).
[Quest Video](https://www.youtube.com/watch?v=ty36oy51Rks)

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by wizzymore** [comment]
```cpp
/*######
## npc_iruk
######*/

#define GOSSIP_OPTION_SEARCH_CORPSE  "<Search corpse for Issliruk's Totem.>"

enum Iruk
{
    NPC_TEXT_THIS_YOUNG_TUSKARR             = 12585,

    QUEST_SPIRITS_WATCH_OVER_US             = 11961,

    SPELL_CREATE_TOTEM_OF_ISSLIRUK          = 46816
};

class npc_iruk : public CreatureScript{
public:
    npc_iruk() : CreatureScript("npc_iruk") { }
    bool OnGossipHello(Player* player, Creature* creature)
    {
        if (player->GetQuestStatus(QUEST_SPIRITS_WATCH_OVER_US) == QUEST_STATUS_INCOMPLETE)
            player->ADD_GOSSIP_ITEM(GOSSIP_ICON_CHAT, GOSSIP_OPTION_SEARCH_CORPSE, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF+1);

        player->PlayerTalkClass->SendGossipMenu(NPC_TEXT_THIS_YOUNG_TUSKARR, creature->GetGUID());
        return true;
    }

    bool OnGossipSelect(Player* player, Creature* /*creature*/, uint32 /*sender*/, uint32 action)
    {
        player->PlayerTalkClass->ClearMenus();

        if (action == GOSSIP_ACTION_INFO_DEF + 1)
        {
            player->CastSpell(player, SPELL_CREATE_TOTEM_OF_ISSLIRUK, true);
            player->CLOSE_GOSSIP_MENU();
        }
        return true;
    }
};
```

Try this, should run on windows and travis would have no conflict with it

**Comment by poszer** [comment]
> ```c++
> /*######
> ## npc_iruk
> ######*/
> 
> #define GOSSIP_OPTION_SEARCH_CORPSE  "<Search corpse for Issliruk's Totem.>"
> 
> enum Iruk
> {
>     NPC_TEXT_THIS_YOUNG_TUSKARR             = 12585,
> 
>     QUEST_SPIRITS_WATCH_OVER_US             = 11961,
> 
>     SPELL_CREATE_TOTEM_OF_ISSLIRUK          = 46816
> };
> 
> class npc_iruk : public CreatureScript{
> public:
>     npc_iruk() : CreatureScript("npc_iruk") { }
>     bool OnGossipHello(Player* player, Creature* creature)
>     {
>         if (player->GetQuestStatus(QUEST_SPIRITS_WATCH_OVER_US) == QUEST_STATUS_INCOMPLETE)
>             player->ADD_GOSSIP_ITEM(GOSSIP_ICON_CHAT, GOSSIP_OPTION_SEARCH_CORPSE, GOSSIP_SENDER_MAIN, GOSSIP_ACTION_INFO_DEF+1);
> 
>         player->PlayerTalkClass->SendGossipMenu(NPC_TEXT_THIS_YOUNG_TUSKARR, creature->GetGUID());
>         return true;
>     }
> 
>     bool OnGossipSelect(Player* player, Creature* /*creature*/, uint32 /*sender*/, uint32 action)
>     {
>         player->PlayerTalkClass->ClearMenus();
> 
>         if (action == GOSSIP_ACTION_INFO_DEF + 1)
>         {
>             player->CastSpell(player, SPELL_CREATE_TOTEM_OF_ISSLIRUK, true);
>             player->CLOSE_GOSSIP_MENU();
>         }
>         return true;
>     }
> };
> ```
> 
> Try this, should run on windows and travis would have no conflict with it
> P.S. IDK how to post a commit/PR as a comment

That's old code, used before. Are you on AC discord? @wizzymore

**Comment by poszer** [comment]
**Info** : Closing until i fix it

**Comment by FrancescoBorzi** [comment]
@poszer  you can keep it open as WIP

**Comment by wizzymore** [comment]
This now can be merged

**Pull request closed without merging**
