### PR TITLE
fix(DB/Zone):improved Elwynn Forest

### PR DESCRIPTION
**Pull request by Knindzagxg**
Zone now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

### CODE REVIEW

**Comment by aradep** [comment]
Lot of narrow trigger ranges. 🕵️

**Comment by FrancescoBorzi** [comment]
@Knindzagxg

**Comment by Knindzagxg** [comment]
Same as in Dun Morogh, it have very low chance to "proc" xP

**Comment by FrancescoBorzi** [comment]
shall we mark this as [To be merged] ?

@Knindzagxg @aradep

**Comment by Knindzagxg** [comment]
Yeah, its same Daze proc chance as in Dun M.
Sorting now.

**Review by Si1ker — APPROVED** [review]

**Comment by Si1ker** [comment]
@Kitzunu  labeler wrong, adding core to non-core changes 🐱

**Comment by Kitzunu** [comment]
:( Then both conditions are broken :(

**Pull request merged**
