### PR TITLE
fix(DB/Zone):improved Hellfire Peninsula

### PR DESCRIPTION
**Pull request by Knindzagxg**
## Changes Proposed:
- Missing SAI creature updates.
- Improvements to existing if possible.

## Tests Performed:
- Applied SQL without problems.
- Tested only few that have Aura applied and or removed during combat.

## How to Test:
- Apply SQL(s).
- Restart Server (You can .reload creature_template for each creature as well, but will take time)
- Go to zone (Check PR name) and check creatures around - You can also spawn (.npc add) each by command.

## Source for Changes:
- [Wowhead](https://wowhead.com) Database and or comments.
- [WotlkDB](https://wotlkdb.com/) Multi checking trough Private DB's.
- [WowWiki](https://wowwiki-archive.fandom.com/wiki/Portal:Main) Can be useful for extra informations.
- [WowPedia](https://wow.gamepedia.com/Wowpedia) Cross checking trough comments if possible.
- [Retail](https://worldofwarcraft.com/en-gb/) In-game checking if previous don't have any required informations.

## Target Branch:
- [x] Master

## Operating System:
- Linux (Debian 10)

## How to Test AzerothCore PR's
When a PR is ready to be tested, it will be marked as **[Waiting to be tested]**.
You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:
http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
First of all, it's better to have AI than none.

**Comment by FrancescoBorzi** [comment]
> First of all, it's better to have AI than none.

@Knindzagxg @pklloveyou have you tested this? is it good to be merged?

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Knindzagxg** [comment]
@FrancescoBorzi 

I made PR's for all TBC zones, need others to test it xP

**Comment by pklloveyou** [comment]
I simply tested it on each NPC to see if they would cause errors to the server

**Comment by claudiodfc** [comment]
This test is useless, SAI doesn't crash the server.

**Comment by Knindzagxg** [comment]
Updated as requested.

@claudiodfc SAI can crash server and make big issues with memory.
We had that problem year ago cause some of them missed force_despawn option and once players were in zone NPC would keep spawning new "mobs" indefinitely.

**Comment by claudiodfc** [comment]
Ok, then where's the test case?

> I simply tested it on each NPC to see if they would cause errors to the server
- how long did you test for each creature
- how long was the server running
- Some creatures might have scripted events, are these events correctly started and finished?

I don't think I'm asking too much, if you ask for a pull request there has to be a logical procedure for merging it. We wouldn't want you to crash the server, acidentally.

I will test this myself from Monday on so no one merge any of these PRs until I finish.

**Comment by claudiodfc** [comment]
[Stonescythe Whelp](https://wotlkdb.com/?npc=16927)
- [X] Stonescythe Whelp casts Absolute defense

[Haal'eshi Windwalker](https://wotlkdb.com/?npc=16966)
- [X] Haal'eshi Windwalker casts Hurricane
- [X] Haal'eshi Windwalker casts Lightning Bolt

[Haal'eshi Talonguard](https://wotlkdb.com/?npc=16967)
- [ ] Haal'eshi Talonguard casts Sprint

[Tamed Ravager](https://wotlkdb.com/?npc=19461)
This is the only creature that I wasn't able to find in [wowwiki](https://wowwiki-archive.fandom.com/wiki/Ravager)
and it doesn't even show on the Ravager species list. on WotlkDB it doesn't have any spells
either which is for now the most updated DB for TBC.
- Didn't find proof on them casting Rend. Can you give some feedback on this?


[Razorthorn Flayer](https://wotlkdb.com/?npc=24920)
- [X] Razorthorn Flayer casts Absolute defense
- [X] Razorthorn Flayer casts Pierce armor
- [X] Razorthorn Flayer casts Rend

[Blistering Oozeling](https://wotlkdb.com/?npc=16903)
Wrong spell, after PR this casts Corrosive Ooze but on WotlkDB this is the [spell](https://wotlkdb.com/?spell=33966)
Probably cast after death.
- [ ] Blistering Oozeling casts Summon Blistering Oozeling

[Mo'arg Forgefiend](https://wotlkdb.com/?npc=16946)
- [X] Mo'arg Forgefiend casts Saw Blade
- [X] Mo'arg Forgefiend casts Slime Spray

[Gan'arg Servant](https://wotlkdb.com/?npc=16947)
- [X] Gan'arg Servant casts Power Burn

[Z'kral](https://wotlkdb.com/?npc=18974)
This one casts Drill in game but haven't found any proof of it anywhere
can you give feedback on this one too?
- [X] Z'kral casts Power Burn

[Maiden of Pain](https://wotlkdb.com/?npc=19408)
- [X] Maiden of Pain casts Lash of Pain
- [ ] Maiden of Pain casts Whipped Frenzy

[Starving Helboar](https://wotlkdb.com/?npc=16879)
- [X] Starving Helboar casts Burning Spikes

[Heckling Fel Sprite](https://wotlkdb.com/?npc=18978)
Did not find any proof of them casting any spells on any database.
Can you provide some info about this?

[Infernal Warbringer](https://wotlkdb.com/?npc=19261)
- [X] Infernal Warbringer casts Immolation

[Wrathguard](https://wotlkdb.com/?npc=18975)
- "By 146819 (32,574 – 6·14·316) on 2008/07/30 (Patch 2.4.3)
The only time they put out any real damage is with Flame Wave; THAT, you want to avoid as much as possible."
- [X] Wrathguard casts Flame wave.


[Subjugator Shi'aziv](https://wotlkdb.com/?npc=19282)
- (On gamepedia)[https://wow.gamepedia.com/Subjugator_Shi%27aziv] this Subjugator does cast Mind Sear according to the DB
but the Subjugator Yalqiz below doesn't according to the DB. May be data incoherence.
- [ ] Casts Mind Sear when below 80%
- [X] Casts Pain Spike

[Subjugator Yalqiz](https://wotlkdb.com/?npc=19335)
- After crossing different databases, wotlkdb is the only one saying
that she casts Mind Sear.
- [X] Casts Mind Sear when below 80%
- [X] Casts Pain Spike

**Comment by T1ti** [comment]
WOTLKdb is a private server database, it's not very accurate
image
example : the book doesn't say the talonguard has sprint.

**Comment by Knindzagxg** [comment]
```Blistering Oozeling
Wrong spell, after PR this casts Corrosive Ooze but on WotlkDB this is the spell
Probably cast after death.```

It's summoned by server, dunno how to explain it in other words.
![Ooze](https://user-images.githubusercontent.com/27079035/111916919-8614fe80-8a7d-11eb-90da-23f252524464.png)

Other spell is during combat, and most times they won't even cast cause low health.

**Comment by T1ti** [comment]
image
for blistering oozeling, the book says that blistering rot summons them and blistering oozeling don't have any abilities

**Comment by claudiodfc** [comment]
Interesting, where did you get this book @T1ti ?
@Knindzagxg Maybe the spell isn't scripted server side... I can take a look!

**Comment by Knindzagxg** [comment]
Yeah, Rot is there and adds are up as well there into pool.

Book will miss some options as well btw, cause doesn't have further patch updates.

**Comment by Knindzagxg** [comment]
Updated [Talonguard](https://wotlkdb.com/?npc=16967).

Will allow him to Dual Wield on aggro, instead Sprint.

**Comment by T1ti** [comment]
image
No ability
image
she has mind sear
image
also mind sear

**Comment by T1ti** [comment]
> Updated [Talonguard](https://wotlkdb.com/?npc=16967).
> 
> Will allow him to Dual Wield on aggro, instead Sprint.

Dual Wield is usualy a permanant aura on the creature, not an SAI cast...



> Interesting, where did you get this book @T1ti ?
> @Knindzagxg Maybe the spell isn't scripted server side... I can take a look!

ask on discord for the link



> Yeah, Rot is there and adds are up as well there into pool.
> 
> Book will miss some options as well btw, cause doesn't have further patch updates.

Book is from like patch 2.2 / 2.3, but I doubt they went back and added new abilities to random world creatures ? seems unlikely

**Comment by Knindzagxg** [comment]
Yeah, they always do some changes but never announce about it.
Some of them can be found on wowhead, where you can click on different patch notes.

It's mostly cause system is changed in Wotlk.

And what i found weird, Dual Wield will work trough cast.
Only thing i can't get it to work (Trough flags) is off hand attack.
Think something need to fixed trough cpp in SAI / Flag system.

**Comment by T1ti** [comment]
> It's mostly cause system is changed in Wotlk.

what system change ?

**Comment by claudiodfc** [comment]
@T1ti Does CLS support Off-hand attacks?

**Comment by T1ti** [comment]
> @T1ti Does CLS support Off-hand attacks?

if properly implemented it should, but the fact that an npc doesn't attack at all with his offhand is related to something else, not the damage calculation

@Knindzagxg if you make the creature cast it, on spawn seems better than on aggro ?
btw theer are two versions of dual wield, https://wotlkdb.com/?spell=29651 https://wotlkdb.com/?spell=42459
The one you chose gives +20% hit chance

**Comment by claudiodfc** [comment]
I updated my test case message so after everything is taken care of this should be good to be merged!

**Comment by Knindzagxg** [comment]
I did it yday in rush Titi, gonna sort correctly now.

**Comment by Knindzagxg** [comment]
- Talon Guard updated -> Will have Dual Wield on spawn / respawn.
- Maiden updated -> Different ID for Frenzy tho, cause original one is not scripted in core. This one will give haste and 1 extra attack damage.
- Shi'aziv and Yalqiz updated -> Dual Wield on spawn / respawn. Mind Sear added to Yalqiz.

**Comment by Knindzagxg** [comment]
- Removed Oozeling -> Check on retail they have no spells anymore.
- Removing Raveger as well -> Not able to test due friendly faction -.-'
- Updated Fel Sprite after checking -> They have low level fire shield instead bolt.

**Comment by Knindzagxg** [comment]
@claudiodfc 
Can u check latest updates.
Ill start working on Shadowmoon from tomorrow.

**Comment by claudiodfc** [comment]
## Test results
- [X] Talonguard casts Dual Wield on respawn;
- [X] Maiden of Pain casts Frenzy;
- [X] Yal'qiz and Shi'aziv casting Mind Sear;
---
I believe everything is working correctly 👍🏼

**Comment by Knindzagxg** [comment]
Awesome xD

**Comment by Si1ker** [comment]
@Voxstrasza make sure to adjust the name of the PR and the commit before merging.

**Pull request merged**
