### PR TITLE
fix(DB/gameobject): Adjust spawntimesecs for multiple GOs

### PR DESCRIPTION
**Pull request by Si1ker**
Imported from https://github.com/TrinityCore/TrinityCore/issues/20162

## Changes Proposed:
-  Adjust 'spawntimesecs' in 'gameobject' for:
Cozzle's Footlocker
Captain's Footlocker
Soaked Tome
Rathis Tomber's Supplies
Dented Chest
Worn Chest
Crate of Ingots
Mysteries of the Light
The Saga of Terokk
First Aid Supplies
Night Elf Plans: An'daroth
An'owyn
Scrying on the Sin'dorei
Sealed Box
Dawn Runner Cargo/Warped Crates

## Issues Addressed:
- Improve spawn time on multiple low/mid-level game objects

Close: https://github.com/azerothcore/azerothcore-wotlk/issues/4060

## Tests Performed:
- **Tested in-game**
- **SQL query applied:** /* Affected rows: 17  Found rows: 0  Warnings: 0  Duration for 3 queries: 0.125 sec. */

## How to Test the Changes:

Same as described in https://github.com/TrinityCore/TrinityCore/issues/20162

## Known Issues and TODO List:

- N/A

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Si1ker have you tested each one of them?

Also we should add guid `49828` too, see: https://github.com/azerothcore/azerothcore-wotlk/pull/2288/files

**Comment by Si1ker** [comment]
@FrancescoBorzi Yes, just need quest (+quest item) and .go object [ID of the GO]
Wowhead can be used for looking at which quest the GO belongs to

- Added suggestion !

image

**Review by Yehonal — APPROVED** [review]

**Comment by Kitzunu** [comment]
We really dont need this to be tested, as long as the guids are correct the changes will work

**Comment by Si1ker** [comment]
guids? I'm using IDs 🐱

**Comment by Kitzunu** [comment]
Same same :P

On phone so hard to see all the code at once, but guid/id doesnt matter which

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> We really dont need this to be tested, as long as the guids are correct the changes will work

Sure, but at least checking that the changes are right, not just blindly copied from TC. Which I guess Silker has already done

**Comment by pklloveyou** [comment]
Tested

**Comment by LukasVolgger** [comment]
Thx @pklloveyou and @Si1ker !

**Comment by Yehonal** [comment]
In this PR the object 176189 is missing: the skeletal sea turtle

Why isn't on the list? is there a reason for it? 

http://datenbank.classic-wow.org/?object=176189
http://www.wowhead.com/quest=4681/washed-ashore

**Comment by FrancescoBorzi** [comment]
@Yehonal better open a new PR

**Pull request merged**
