### PR TITLE
fix(DB) Untranslated texts for The Battle for Undercity

### PR DESCRIPTION
**Pull request by MathematicalWTF**
## Changes Proposed:
-  Creates the missing `gossip_menu_option_locale`, `creature_text_locale`, `quest_request_items_locale` and `quest_offer_reward_locale` to spanish.

## Issues Addressed:

- Closes 

## Tests Performed:

- File and statements executed on my database several times to verify failures.
- Changes seen in-game with both alliance and horde.

## How to Test the Changes:

- Inserting the sql in your acore_world database.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by MathematicalWTF** [comment]
I've made a lot of silly mistakes, sorry. In the last commit I correct everything.

**Comment by MathematicalWTF** [comment]
Just in case, it's pango's fault for telling me to remove and combine INSERTS. 😂😂

**Comment by Delcidx** [comment]
Tested, working great.

**Comment by pangolp** [comment]
> Just in case, it's @pangolp 's fault for telling me to remove and combine INSERTS.

hahaha, the things you have to read. I told you, you won't ask me to prove you a commit ever again, because I will dig you to the last mistake.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pangolp** [comment]
Congratulations @MathematicalWTF

**Review by pangolp — APPROVED** [review]

**Pull request merged**
