### PR TITLE
Fix(Core/DB): Hardcoded text - Eastern Kingdoms

### PR DESCRIPTION
**Pull request by Nefertumm**
##### CHANGES PROPOSED:

-  Use db data in order to allow translations with gossips and texts
-  Moved Kharan Mighthammer to DB
-  Added some overrides and some NULL to nullptr

##### TESTS PERFORMED:

Build and tested some of them.

##### HOW TO TEST THE CHANGES:

Check if all the changed gossips are working as before.
Check (if possible with locale != us) if all the changed monster yells are working as before.

##### KNOWN ISSUES AND TODO LIST:

- [ ] There are some other gossips to change.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
Good job

**Comment by wizzymore** [comment]
Add the numbers related to DB from AddGossipItemFor in ENUM ( look at reviews to know what i mean )

**Comment by Nefertumm** [comment]
I didn't do that because i dont have time for that.

**Comment by BarbzYHOOL** [comment]
> Add the numbers related to DB from AddGossipItemFor in ENUM ( look at reviews to know what i mean )

why?

**Comment by disclosurez** [comment]
works well

**Comment by comix1988** [comment]
I'm testing it now

**Comment by comix1988** [comment]
I've been testing:
- khran mighthammer with 4001 and 4342 id quest and he works fine;
- lokthos darkbargainer: with frendly reputation i can buy an items from he, otherwise nothing. The a binding contract mission also works.
- doom'rel: is ok, when I press on the gossip, the fight begins.
- Majordomo: is ok, when I press on the gossip, the fight begins.
- gloom'rel: gossip works but i found on wowpedia a different gossip
gloom'rel

If it can serve, tomorrow I can do more tests @Nefertumm

**Comment by Viste** [comment]
Run on test server, for register: http://server-test.azerothcore.org/ 
for gm access PM me or write on email.

**Pull request merged**
