### PR TITLE
Ice Tomb

### PR DESCRIPTION
**Pull request by Ali-Khazaee**
https://github.com/azerothcore/azerothcore-wotlk/issues/2201

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@andoys can you please test this?

**Comment by andoys** [comment]
I can't do a proper 25 man test for this yet. But @Ali-Khazaee was able to test this himself using 2 accounts: 
ali

**Comment by disclosurez** [comment]
Just implemented on my server with ~50 online, should let you know if this is fixed or not asap.

**Comment by boom8866** [comment]
INSERT INTO `conditions` VALUES (13, 3, 71048, 0, 0, 1, 0, 70157, 1, 0, 1, 0, 0, '', 'Bomb');
INSERT INTO `conditions` VALUES (13, 3, 70123, 0, 0, 1, 0, 70157, 1, 0, 1, 0, 0, '', 'Bomb');
INSERT INTO `conditions` VALUES (13, 3, 71047, 0, 0, 1, 0, 70157, 1, 0, 1, 0, 0, '', 'Bomb');
INSERT INTO `conditions` VALUES (13, 3, 71049, 0, 0, 1, 0, 70157, 1, 0, 1, 0, 0, '', 'Bomb');

The problem is that the player on the ice is hurt, spell = 71049, because it takes a long time. When you wait around 20S on the ice, this problem will occur. I have tested and fixed it.

**Comment by FrancescoBorzi** [comment]
@boom8866 FYI I made your comment more beautiful:

image

**Comment by Knindzagxg** [comment]
Tested as well with 3 accounts, and don't see issue now.
Tho, it's better to confirm while there is more players, just in case.

**Comment by disclosurez** [comment]
works well, tested on my realm in 25 man vs it

**Comment by FrancescoBorzi** [comment]
good job @Ali-Khazaee and thanks a lot @Knindzagxg and @disclosurez for testing this!

**Pull request merged**
