### PR TITLE
fix(DB/Spells): Greater Heal spell from 8P T2 Priest set should scale…

### LINKED ISSUE #11934: Vestments of Transcendence Priest 8/8 set bonus
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

https://wotlkdb.com/?itemset=211

[8/8 set bonus works and gives renew rank 5 equivalent heal on Greater Heal over 15 seconds](https://classic.wowhead.com/spell=22010/greater-heal-renew#comments), but it does not scale with spell power or talents.

[Greater Heal proc with 161 Spell Power](https://streamable.com/53j7ib)
[Greater Heal Renew Proc with 317 Spell Power](https://streamable.com/paosjr)
[
Renew rank 5 spell power scaling heal on 317 spell power](https://streamable.com/bbzuq3)
### Expected Blizzlike Behaviour
Set bonus

Should heal the same as a rank 5 renew. It should also scale with talents/gear according to https://www.wowhead.com/item-set=211/vestments-of-transcendence#comments comments.

### Source
https://classic.wowhead.com/spell=22010/greater-heal-renew#comments

https://www.wowhead.com/item-set=211/vestments-of-transcendence#comments comments.

https://us.forums.blizzard.com/en/wow/t/transcendence-8-piece-set-bonus-improved-renew-and-spiritual-healing-talents/621964

Set bonus

Set scale

### Steps to reproduce the problem

1. Equip 8/8 t2 on a priest.
2. Cast Greater Heal --> see the renew that is cast.
3. Cast renew rank 5 and compare the difference. Notice the extra spell power from your gear and extra talents and see that the 8/8 greater heal renew doesn't seem to change.

### Extra Notes
Originally reported : https://github.com/chromiecraft/chromiecraft/issues/3569

Vestments of Transcendence itemset id: 211
Boots: 16919
Handguards of Transcendence: 16920
Halo of Transcendence: 16921
Leggings of Transcendence: 16922
Robes of Transcendence: 16923
Pauldrons of Transcendence: 16924
Belt of Transcendence: 16925
Bindings of Transcendence: 16926

Greater Heal Rank 5 (level 60) spell ID: 25314

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
… with spell power.

Fixes #11934

## Issues Addressed:

- Closes #11934
- Closes https://github.com/chromiecraft/chromiecraft/issues/3569

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Equip 8/8 t2 on a priest.
Cast Greater Heal --> see the renew that is cast.
Cast renew rank 5 and compare the difference.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Ovahlord** [comment]
the bonus coefficient is wrong. It's suposed to be 0.2. It's literally in the dbc

**Comment by UltraNix** [comment]
@Ovahlord It's the same as for Renew Rank5 in `spell_bonus_data`.

**Comment by Ovahlord** [comment]
No seriously. these spellpower coefficient are literally inside the dbc (spell.dbc) so all you have is to read them from there and drop the obsolete spell_bonus_data entries. TrinityCore does that already so all you gotta do is porting it.

**Comment by UltraNix** [comment]
As long as AzeorthCore does not have it, using `spell_bonus_data` is a good solution. And porting this is not covered by this PR.

**Comment by Ovahlord** [comment]
yes, which is why I tell you to use the data which is exposed in the dbc which is the correct value.
image

**Comment by UltraNix** [comment]
Okay.

**Review by Ovahlord — APPROVED** [review]
value is correct now. can be merged.

**Comment by Gultask** [comment]
Tested.
`.aura 22010` Greater Heal Renew
`.learn 2060` Greater Heal
`.learn 6077` Renew rank 5

Greater Heal Renew with 0 SP: 63 HP
Renew rank 5 with 0 SP: 63 HP

`.aura 32925` 102 bonus SP

Greater Heal Renew with 102 SP: 75 HP
Renew rank 5 with 102 SP: 87 HP

I don't know why I had this difference with the scaling. It should add ~20 HP per tick, no?

Also, [some comments in Wowhead](https://classic.wowhead.com/spell=22010/greater-heal-renew#comments) claimed that it "receives the full bonus of your +healing", so the 0.2 scaling for 5 ticks should be correct, I think.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
