### PR TITLE
fix: Loch Modan multiple ore spawn

### PR DESCRIPTION
**Pull request by nedarion**
## Changes Proposed:
- Adds Tin and Silver ores to the pools, making it so that only one can spawn at the time

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/3661

## SOURCE:
The changes proposed on this PR are just a fix to the current situation, where multiple ores spawn at the same time in Loch Modan. I haven't verified that the resulting behavior after applying this matches anything that can be considered blizzlike, but it does get rid of the multiple ores problem.

## Tests Performed:
This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

1. Run SQL commands
2. Verify that 333 records were inserted
3. Verify in-game that no multiple ores spawn on a single point in Loch Modan

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
@neifion-00000000 Do you have any sniffs on this?

**Comment by nedarion** [comment]
> @neifion-00000000 Do you have any sniffs on this?

Sadly I don't. I'm trying to get one but it might take a while if I'm even able to get it. The changes proposed however are an improvement on the current behavior. If there is any other thing besides the sniffs that I can get to improve this please let me know!

**Comment by pangolp** [comment]
> > @neifion-00000000 Do you have any sniffs on this?
> 
> Sadly I don't. I'm trying to get one but it might take a while if I'm even able to get it. The changes proposed however are an improvement on the current behavior. If there is any other thing besides the sniffs that I can get to improve this please let me know!
> 
> EDIT: And I just know notice you were tagging someone else :man_facepalming: 

For a moment, I thought I had tagged the wrong person.

**Comment by elthehablo** [comment]
We can merge this for now, but Neifion is obviously still working on their big project so those sniffs will come in the future. Can someone test this briefly with a before/after in some places?

**Pull request merged**
