### PR TITLE
fix(Build/CMake): CMake now uses the Windows env vars

### PR DESCRIPTION
**Pull request by Daylien**
## CHANGES PROPOSED:
- CMake wasn't able to find the environment variables which are noted in
the [Wiki](https://www.azerothcore.org/wiki/Installation) e.g. MYSQL_INCLUDE_DIR or MYSQL_LIBRARY
- Further I added another variable for OpenSSL which is OPENSSL_ROOT_DIR
- This change allows .zip installations with a custom PATH

## ISSUES ADDRESSED:
- Download MySQL and or OpenSSL as a .zip archive. Place it anywhere on your filesystem and set the environment variable from the [Wiki](https://www.azerothcore.org/wiki/Installation) to the directory
- Watch CMake complain about not finding MySQL and or OpenSSL

## TESTS PERFORMED:
- Building on Windows 10 64Bit 2004
- Checked different places on the system eg. `D:\`, `E:\`

## HOW TO TEST THE CHANGES:

* Download MySQL and OpenSSL as .zip archives
* Place them anywhere on your filesystem
* Create the following environment variables `MYSQL_INCLUDE_DIR `, `MYSQL_LIBRARY` and `OPENSSL_ROOT_DIR`
* Point them to the corresponding directory
* Build the solution

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Daylien thanks for your contribution!

**Comment by nicoaravena** [comment]
Doubt, this should only be tested on windows env?

**Comment by Helias** [comment]
I think so

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan we need a Windows guy to review this :)

**Comment by Winfidonarleyan** [comment]
I will not remove my libraries to test this :/

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan that's ok but can you review the code ?

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Kitzunu** [comment]
Thanks =)

**Pull request merged**
