### PR TITLE
feat(Tools/Vmapextractor): Improved vmap detail level by extracting w…

### LINKED ISSUE #4782: Ethereal Liquor allows you to phase through BG walls (possibly related to fear bug) [$50]
Ethereal Liquor allows you to phase through BG walls (possibly related to fear bug)

##### CURRENT BEHAVIOUR:

Drink Ethereal Liquor. It turns you into a feared monster. The feared monster will run through walls in BGs.

https://www.wowhead.com/item=38294/ethereal-liqueur

Possibly related;

This might be a fear issue not an ethereal liquor issue, but I don't know.

https://github.com/azerothcore/azerothcore-wotlk/issues/4769

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Not phase through walls.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Warsong Gulch
2. Go inside a hut/building
3. Drink and watch

##### AC HASH/COMMIT:

AzerothCore rev. 6a7155eb7e82 2021-03-07 12:37:07 

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/97032521-ethereal-liquor-allows-you-to-phase-through-bg-walls-possibly-related-to-fear-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…mo doodads (tables, chairs etc).

Port from TC.
Fixed #4782.

New Vmaps and Mmaps ARE REQUIRED.

## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #4782.

## Tests Performed:
-
-

## How to Test the Changes:

1. Enter Warsong Gulch.
2. Test one of these spots: https://user-images.githubusercontent.com/18535853/111451057-fe14b900-874b-11eb-8aed-62345a80b589.png https://user-images.githubusercontent.com/18535853/111451597-90b55800-874c-11eb-9b1d-2f2726040a46.png
3. Cast fear on self and observe results.
4. Additional check: Inside these "rooms" add temporary npc (e..g. `.npc add temp 1747`), move out the room, select the NPC and type `.debug los`, as I did here: https://user-images.githubusercontent.com/80540499/111452903-4499f180-8713-11eb-9432-c27af3223089.jpg. NPC should not be in LoS.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by UltraNix** [comment]
I forgot to add it:
New vmaps and mmaps ARE REQUIRED.

**Comment by FrancescoBorzi** [comment]
@UltraNix can you please fill "How to Test the Changes" so people can test this?

**Comment by pklloveyou** [comment]
It doesn't matter. I know how to test it. I'm building it

**Comment by pklloveyou** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
ok nice, thanks @pklloveyou for testing this.

We will need to prepare v10 for the client data: https://github.com/wowgaming/client-data/releases

can anyone help with it? where I currently am located, my upload is extremely slow

**Comment by UltraNix** [comment]
So only upload blocks this PR?

**Comment by FrancescoBorzi** [comment]
> So only upload blocks this PR?

yes, as I said I have a poor upload where I currently am so I can't help with it. Sorry

**Comment by UltraNix** [comment]
Me either :/

**Comment by Si1ker** [comment]
> Me either :/

@UltraNix , we'll take care of it.

**Comment by 55Honey** [comment]
This happens when i start the mmaps-generator.exe from that PR.
It says "The application could not be started  correctly."
image
Troubleshooting c++redistributables and windows updates/rebuilding did not solve it.

**Comment by UltraNix** [comment]
It says nothing to me.

**Comment by 55Honey** [comment]
If it works on other windows machines, the problem might be on my end. Can't test and help with the upload when it's not working tho, sry :(

**Comment by pklloveyou** [comment]
I'm win10x64

**Comment by Hacki95** [comment]
I get a few weird outputs right before the end with the vmaps4extractor, are these normal?

> ...
> Extracting World\Wmo\Transports\Transport_Zeppelin\Transport_Zeppelin.wmo
> Extracting <Empty>\Kl_Onyxiaslair.wmo
> No such file.
> Couldn't open RootWmo!!!
> Extracting World\Wmo\Transports\Transport_Ship_Ne\Transportship_Ne.wmo
> Extracting World\Wmo\Band\Final_Stage.wmo
> No such file.
> Couldn't open RootWmo!!!
> Extracting World\Wmo\Azeroth\Buildings\Griffonaviary\Griffonaviary.wmo
> ...

**Comment by UltraNix** [comment]
This is normal.

**Comment by pklloveyou** [comment]
yes

**Comment by FrancescoBorzi** [comment]
@Helias can you please take care of this?

**Comment by Helias** [comment]
yes

**Comment by pklloveyou** [comment]
What are we waiting for?

**Comment by Helias** [comment]
new data published https://github.com/wowgaming/client-data/releases/tag/v10 , thanks to @55Honey 
we can merge this I think or fix any compatibility platform issues

**Review by Helias — APPROVED** [review]

**Pull request merged**
