### PR TITLE
fix(Core/GM Commands): Update NPC Info command

### PR DESCRIPTION
**Pull request by ghost**
## Changes Proposed:
-  Update .npc info command to show possible npc entries and chance.
-  Also rearranged layout.

## Issues Addressed:
- Closes 

## Tests Performed:
- English works perfectly.

## How to Test the Changes:
1. select an npc in game ant, in gm mode, type ".npc info"

## Known Issues and TODO List:
- [1] Need someone to do other languages.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]
做得好！

**Review by Kitzunu — APPROVED** [review]

**Comment by WORISX** [comment]
Is it tested on tempspawns?

image

**Comment by Kitzunu** [comment]
@malcrom could you add a null check and just pass 0 if that's the case for all the cData stuff.

**Comment by malcrom** [comment]
> @malcrom could you add a null check and just pass 0 if that's the case for all the cData stuff.

I thought temp spawns were spawned with it set to 0

**Comment by Kitzunu** [comment]
the reason why it you need it is because when you spawn a temp spawn it isn't actually recorded in the creature table which means that when you try to call the cData it will just throw a nullptr

**Comment by malcrom** [comment]
Updated and tested

**Review by Kitzunu — APPROVED** [review]
looks good

**Pull request merged**
