### PR TITLE
(DB/AcoreString) Modifying message entry 474 475 476

### PR DESCRIPTION
**Pull request by pangolp**
### Changes Proposed:
-  The idea of the pull request is to modify the messages that provide information about the status of the missions, by using the `.lookup quest` command. Currently they are displaying some parameters, which do not receive information, so it is better to modify them.

### Issues Addressed:

- Closes

### Tests Performed:

- Inside the game
- Windows 10

### How to Test the Changes:

1. Use the command `.lookup quest $name` and you will see that it has a format, where it should include some parameters, but they are not passed to the message. For example:

```
6001 - [Body and Heart] Quest %s (%u) is already active.
6002 - [Body and Heart]
```

### Screenshot

acore_string

This is the message, after applying the SQL. It is shown in Spanish, because I am using that client, and I took the opportunity to add the translations.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
I dont have a Es or Mx client. Can u show what it was showing before the pr? Just so we can better understand the comparison?

**Comment by Nyeriah** [comment]
This will break the message that shows once you do .quest complete

**Comment by Kitzunu** [comment]
Just fix the script if it is broken.

**Comment by pangolp** [comment]
> I dont have a Es or Mx client. Can u show what it was showing before the pr? Just so we can better understand the comparison?

The message currently displayed, with no change applied, is this:

```
6001 - [Body and Heart] Quest %s (%u) is already active.
6002 - [Body and Heart]
```

A %s and %u appear, but these parameters will never be passed to the message.

**Comment by pangolp** [comment]
> This will break the message that shows once you do .quest complete, .quest add and others

In the `.quest complete` and `.quest add`, the parameters also appear without values.

**Comment by pangolp** [comment]
> Just fix the script if it is broken.

Ok, then I close the PR.

**Pull request closed without merging**
