### PR TITLE
fix(DB/BWL): Blackwing Warlocks

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Corrected Warlock summon portal timers, it was kinda low.
-  Added smart scripts for the portals and Enraged Felguards.
-  Despawn the portals if the warlock evades.
-  Blackwing technicians respawn timer has been lowered again to 30s, but this time their respawn is linked to each warlock near the pack. This allows them to respawn and for the players, farm elementium.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11256

## Tests Performed:

- Tested in-game.

## How to Test the Changes:

1. Go to blackwing lair and check the changes made.

### CODE REVIEW

**Comment by fputs** [comment]
Enraged Felguards are now summoning properly

2022-04-04-213236_2560x1440_scrot

**Comment by Lynethris** [comment]
> 

Have you seen other points ? (If portals despawn and technician respawn when warlock evade ? ...)

**Comment by Lynethris** [comment]
> Enraged Felguards are now summoning properly
> 
> 2022-04-04-213236_2560x1440_scrot

Have you check other points ? (If portals despawn and technician respawn when warlock evade ? ...)

**Comment by fputs** [comment]
Followup testing:

- Portals despawn when warlocks evade
- Enraged Felguards do not despawn when combat ends
- If combat is dropped after felguards have spawned, then combat is started again, the warlocks will open new portals that summon more felguards
- Technicians respawn when the warlocks evade, though it seems to take a longer amount of time than 30 seconds. More like 2 minutes
- Technicians drop Elementium Ore multiple times, allowing for farming
- Technicians do not respawn when their attached warlock is dead (see image below)

2022-04-05-071403_2560x1440_scrot

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
