### PR TITLE
fix(Core/Spells): Entangling Roots -- Nature's Grasp Proc

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry picked from TC

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9475

## Tests Performed:

- None

## How to Test the Changes:

1.cast nature's grasp .cast 53312 with one char
2.get a rogue with 2 fast daggers (1.8 and 1.4 speed)
3.on the rogue, cast hemmorhage (.cast 48660)
4.watch nature's grasp stacks and root duration on rogue

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by laasker** [comment]
doesnt work, there still no ICD

**Comment by Kitzunu** [comment]
I know, thats why it is wip :)

**Comment by laasker** [comment]
ah my bad, didnt see it

**Comment by acidmanifesto** [comment]
What is the Status of this PR?

**Comment by Kitzunu** [comment]
waiting for https://github.com/azerothcore/azerothcore-wotlk/pull/9938

**Pull request closed without merging**
