### PR TITLE
fix(DB/Creature Formation) Scholo: Make Alexei Barov's adds respawn correctly

### LINKED ISSUE #8239: [Scholomance] Adds for Alexei barov don't respawn and are slow to join fight.
### Current Behaviour

The mobs aren't linked to his reset apparently.
image

Triggered by killing one, enabling GM mode (or FD, but was on my mage) and toggling again

### Expected Blizzlike Behaviour

Both adds should respawn on reset

### Source

_No response_

### Steps to reproduce the problem

1. Go to scholo / alexei barov (.go c 48863 )
2. aggro, kill one add, evade fight (FD, GM, invisiblity, vanish), ...
3. mob doesn't respawn.

creature ID: 10504 and 10489. Maybe fixable through formation?

### Extra Notes

_No response_

### AC rev. hash/commit

dcd2bbabb420 (my dev branch but that's latest master and I haven't touched scholo)

### Operating system

win 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by kjack9**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

Adds a creature formation to make Lord Alexei Barov's (10504) Risen Guard (10489) adds respawn if the fight is reset before Alexei dies.

## Issues Addressed:

- Closes #8239 (oldie but a goodie)

## SOURCE:

The changes have been validated through:
- [X] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by avarishd** [comment]
If you kill only 1 of the guards and alexei, the guard will respawn even if alexei is dead.

**Comment by kjack9** [comment]
> If you kill only 1 of the guards and alexei, the guard will respawn even if alexei is dead. (if you evade the alive guard)

I'm...not sure how to prevent that.

https://www.azerothcore.org/wiki/creature_formations

As far as I can tell, setting the flag to 27 is the only way to accomplish this using creature formations. Is there another flag combination or pattern that can be used to ensure that if the leader is dead, the creature won't respawn?

**Comment by kjack9** [comment]
Nevermind - adding this to `linked_respawn` doesn't seem to resolve the issue:

```sql
DELETE FROM `linked_respawn` WHERE `guid` IN (48862, 48864) AND `linkType`=0;
INSERT INTO `linked_respawn` (`guid`, `linkedGuid`, `linkType`) VALUES
(48862, 48863, 0),
(48864, 48863, 0);
```

**Comment by avarishd** [comment]
Converting from SAI to cpp or using SAI logic to respawn them seems like the way.

**Comment by kjack9** [comment]
> Converting from SAI to cpp or using SAI logic to respawn them seems like the way.

I guess that raises another question - should respawns due to `creature_formation` respect the settings in `linked_respawn`? I would think yes, but open to other interpretations.

**Comment by Nyeriah** [comment]
1) linked_respawns
2) conditions

Those two you can do

**Comment by kjack9** [comment]
> 1. linked_respawns
> 
>     2. conditions
> 
> 
> Those two you can do

The respawn mechanic for `creature_formations` doesn't appear to respect the settings in `linked_respawns`, that's the first thing I tried.

```sql
DELETE FROM `linked_respawn` WHERE `guid` IN (48862, 48864) AND `linkType`=0;
INSERT INTO `linked_respawn` (`guid`, `linkedGuid`, `linkType`) VALUES
(48862, 48863, 0),
(48864, 48863, 0);
```

Unless I'm just setting it up wrong, the issue still happens when I add that to the `linked_respawn` table.

Am I doing it wrong, is that working as intended, or do I need to file a bug and PR for the two not playing well together?

**Comment by kjack9** [comment]
Once #17597 is merged, this PR should work correctly and be good to merge.

**Comment by kjack9** [comment]
Updated to keep the group from pulling if the boss' passive aura hits you. This matches classic live.

Still pending #17597 to really work correctly.

**Comment by kjack9** [comment]
#17597 is merged now, this should work correctly. Ready to test and review.

**Comment by sudlud** [comment]
Tested.

.go c 48863
.gm off
engage `Lord Alexei Barov`

kill one or both `Risen Guard` adds
walk away and disengage fight with `.combat` or `.gm on`

before PR
- adds do not respawn

after PR
- both adds instantly respawn after disengaging fight

**Review by sudlud — APPROVED** [review]

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
