### PR TITLE
fix(Core/Spells): Troll Roof Stalker's Stealth and Ashenvale Outrunne…

### LINKED ISSUE #8727: Attacks of Troll Roof Stalker and Ashenvale Outrunner doesn't brake stealth
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/952

 was hanging out in Orgrimar as a couple of human ladies, on my way to the bonfire, and the Troll Roof Stalker killed both my characters, and no attacks were logged in the combat log.
After ghost walking and rezzing, I was again killed and the damage done was still not logged.
shot1

Tester:

The issue is confirmed. [Troll Roof Stalker](https://wowgaming.altervista.org/aowow/?npc=23090)'s attacks doesn't break their [stealth](https://wowgaming.altervista.org/aowow/?spell=32199). [Ashenvale Outrunner](https://wowgaming.altervista.org/aowow/?npc=12856)'s attacks doesn't break [Ashenvale Outrunner Sneak](https://wowgaming.altervista.org/aowow/?spell=20540)

https://user-images.githubusercontent.com/85256266/138675440-056372bc-e3f9-45a9-b86d-95a4b56ea855.mp4

https://user-images.githubusercontent.com/85256266/138675884-b8f0dc15-5a97-4cea-a4d7-c9476cca0de5.mp4

### Expected Blizzlike Behaviour

All damage taken should be recorded in the combat log.

Tester:

I'm thinking the problem not with combat log. Attacks should break stealth. Same as rogue mechanic.

### Source

Wowpedia [Stealth (mechanic)](https://wowpedia.fandom.com/wiki/Stealth_(mechanic)?oldid=2365329)
> Stealth is an ability that allows players or mobs to sneak around undetected. Most notably a rogue's ability.

Wowpedia [Stealth (rogue)](https://wowpedia.fandom.com/wiki/Stealth?oldid=2365328)
> Taking any action such as looting or attacking will remove stealth. There are a few exceptions, such as  [Distract], or Pickpocketing. 

Other ingame [stealth](https://wowgaming.altervista.org/aowow/?search=stealth#spells) or [sneak](https://wowgaming.altervista.org/aowow/?search=sneak#spells) spells are removable via attacks. Tested most of it.

### Steps to reproduce the problem

.go c id 23090
don't deal damage to Troll Roof Stalker and look for results.

.go c id 12856
don't deal damage to Ashenvale Outrunner and look for results.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…r Sneak should break on cast/done melee attack.

Fixes #8727

 

## Issues Addressed:

- Closes #8727
- Closes https://github.com/chromiecraft/chromiecraft/issues/952

## Tests Performed:

- Not tested.

## How to Test the Changes:

.go c id 23090
don't deal damage to Troll Roof Stalker and look for results.

.go c id 12856
don't deal damage to Ashenvale Outrunner and look for results.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by patou01** [comment]
They don't stealth at all when I test it.
image

**Comment by UltraNix** [comment]
@patou01 Try now.

**Comment by patou01** [comment]
Seems to work. Additional question is whether they have the right weapon? Not relevant to this pr, but I'm surprised to see them with a huge axe while being stealthed.

**Comment by UltraNix** [comment]
Comments on wowhead say it;s okay.

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
