### PR TITLE
fix(Scripts/SSC): make The Lurker Below spout rotate faster again

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

Rotation speed lines up with retail sniffs

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/6448

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [x] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

untested

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Both speed and duration now correct, or does the duration still need correction?

**Comment by Nyeriah** [comment]
The duration is correct, as for the speed it needs more research. Spell procs every 200ms in sniffs

**Comment by elthehablo** [comment]
So 0.1f per tick, (2pi/0.1) so we need 63 rotations to do a full circle. 16 s a tick every 200ms so that is 16*5 = 80 ticks, so 80/63 = 126% of a rotation

**Comment by elthehablo** [comment]
250ms would do just shy of a full rotation

**Comment by heyitsbench** [comment]
When you say needs more research, does that refer to the amount of rotation in terms of degrees?

**Comment by elthehablo** [comment]
Maybe. Hard to tell. Rotation looks smooth on retail but they might have a different implementation of rotation in their core

**Comment by elthehablo** [comment]
As expected he does a little over a circle, which lines up to the videos I saw. Should be good to merge

**Review by Nefertumm — APPROVED** [review]

**Comment by balleny** [comment]
turns way to quickly now. takes about 12 seconds for a full circle instead of 16

**Comment by balleny** [comment]
also, he is set to have 3 seconds intro into Spout and 16 seconds rotation.
but, there is also a whirlwind which takes place after 18 seconds (https://github.com/azerothcore/azerothcore-wotlk/blob/d266bf3d15849eb315aab48247035a54a0c51a72/src/server/scripts/Outland/CoilfangReservoir/SerpentShrine/boss_lurker_below.cpp#L138)
so he whirlwinds before finishing Spout.

going by DBM, the overall event should take 22 seconds, hence 19 seconds for the full spout animation (which could equate to 16 or 18 seconds for 360 degree rotation plus the remainer for the additional rotation observed.

**Pull request merged**
