### PR TITLE
fix (DB) : Skeletal Thrash

### PR DESCRIPTION
**Pull request by acidmanifesto**
Currently the smart script has it casted over a few thousand times minimal and to repeat a few thousand times. Obviously is wrong. Seems to be from what i am to experience, it casts on aggro, a single time since it is a aura on itself.

## Changes Proposed:
-  Corrects Attack of NPC Skeletal Flayer 1783

## Issues Addressed:

- Closes 

## Tests Performed:

- Builds
- Performs

## How to Test the Changes:

1. do a .go c 45285
2. piss it off and fight it
3. observe thrash is not being spammed on player.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
This is also wrong, permanent auras go to creature_template_addon. Is this a permanent aura?

**Comment by Kitzunu** [comment]
Not neccessarily if it has been sniffed to cast on reset, as auras i c_t_a is not cast

**Comment by Nyeriah** [comment]
That's precisily why I asked if it's a permanent aura. Those aren't cast. I have yet to see a combat aura being cast on reset though, because that hook is called on respawn as well as on evade.

**Comment by acidmanifesto** [comment]
So how should we proceed? Add it in the creature addon?

**Comment by Nyeriah** [comment]
I could be wrong but it looks like a permanent aura

image

**Comment by acidmanifesto** [comment]
> I could be wrong but it looks like a permanent aura
> 
> image

adding the aura with the following query shows no aura on the npcs at all:
```-- removes smart script for thrash for npc entry 1783
UPDATE `creature_template` SET `AIName`='' WHERE  `entry`=1783;
DELETE FROM `smart_scripts` WHERE `entryorguid`=1783;

-- adds thrash as aura for npc entry 1783
DELETE FROM `creature_addon` WHERE `guid`=1783;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES (1783, 0, 0, 0, 0, 0, 3, '8876');
```

image

**Comment by acidmanifesto** [comment]
Updated to On Aggro, cast thrash on self.
image

**Comment by acidmanifesto** [comment]
I am doing a correction to thrash pr at the moment. this pr will be closed and it will be superseded by the upcoming pr.

**Pull request closed without merging**
