### PR TITLE
fix(DB/Zone):improved Swamp of Sorrows

### PR DESCRIPTION
**Pull request by Knindzagxg**
Zone now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

### CODE REVIEW

**Comment by aradep** [comment]
Tested, all working except for Molt Thorn-14448. He should cast his spell more than once. (https://youtu.be/mRex21CbWS8?t=27)

**Comment by FrancescoBorzi** [comment]
@Knindzagxg

**Comment by Knindzagxg** [comment]
Updated @aradep 
Recheck as well xP

**Comment by aradep** [comment]
Nice and thorny 👍

**Comment by Knindzagxg** [comment]
Perfect xP

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
