### PR TITLE
refactor(SmartAI): Moving quest 2936 to the database

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
-  Move the script to the database

## Issues Addressed:

- Closes 

## Tests Performed:

- Windows 10

## How to Test the Changes:

1. quest add 2936
2. go o 27094
3. Interact with the object and you should complete the mission.

## Screenshot

WoWScrnShot_052721_211708

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — CHANGES_REQUESTED** [review]
You are missing

if (player->GetQuestStatus(QUEST_SPIDER_GOLD) == QUEST_STATUS_INCOMPLETE)

This part from your SQL script, add a condition to only run the SAI for that condition

**Comment by pangolp** [comment]
I was checking the conditions, but I can't really find which one I should use. I was looking for the gossip and the completed missions (with the negation) but I don't know if that's it.

**Comment by Nyeriah** [comment]
CONDITION_QUESTSTATE | 47 
| Quest ID - see quest_template.id 
| state_mask: true if player is in any of the provided quest states for the quest (1 = not taken, 2 = completed, 8 = in progress, 32 = failed, 64 = rewarded)

**Comment by FrancescoBorzi** [comment]
@pangolp what's the status of this PR?

**Comment by pangolp** [comment]
> @pangolp what's the status of this PR?

I have to do the conditional. It is not difficult. But well, time went by and I forgot about it. After doing it, I would have to test the pull request again to see if it meets all the requirements.

**Comment by FrancescoBorzi** [comment]
> > @pangolp what's the status of this PR?
> 
> I have to do the conditional. It is not difficult. But well, time went by and I forgot about it. After doing it, I would have to test the pull request again to see if it meets all the requirements.

ok I'll close it until you want to work on it again. We are trying to not have old stale PRs

**Comment by pangolp** [comment]
> > > @pangolp what's the status of this PR?
> > 
> > 
> > I have to do the conditional. It is not difficult. But well, time went by and I forgot about it. After doing it, I would have to test the pull request again to see if it meets all the requirements.
> 
> ok I'll close it until you want to work on it again. We are trying to not have old stale PRs

All that was left to do was to make the conditional. But well, it's good that you closed it, because it took me a long time to do it, but I couldn't find the right option, then in the comments I was told about it, but I didn't do it until now.

**Comment by acidmanifesto** [comment]
> > > > @pangolp what's the status of this PR?
> > > 
> > > 
> > > I have to do the conditional. It is not difficult. But well, time went by and I forgot about it. After doing it, I would have to test the pull request again to see if it meets all the requirements.
> > 
> > 
> > ok I'll close it until you want to work on it again. We are trying to not have old stale PRs
> 
> All that was left to do was to make the conditional. But well, it's good that you closed it, because it took me a long time to do it, but I couldn't find the right option, then in the comments I was told about it, but I didn't do it until now.

I dont something simular with adjusting player pop based on locale db2 files, and custom start up screens to show different messages on login based on locale of the client. If u are still interested in rethinking select strategies hit me up in the discord room. M'Dic - acidmanifesto in azcore.

**Comment by pangolp** [comment]
> > > > > @pangolp what's the status of this PR?
> > > > 
> > > > 
> > > > I have to do the conditional. It is not difficult. But well, time went by and I forgot about it. After doing it, I would have to test the pull request again to see if it meets all the requirements.
> > > 
> > > 
> > > ok I'll close it until you want to work on it again. We are trying to not have old stale PRs
> > 
> > 
> > All that was left to do was to make the conditional. But well, it's good that you closed it, because it took me a long time to do it, but I couldn't find the right option, then in the comments I was told about it, but I didn't do it until now.
> 
> I dont something simular with adjusting player pop based on locale db2 files, and custom start up screens to show different messages on login based on locale of the client. If u are still interested in rethinking select strategies hit me up in the discord room. M'Dic - acidmanifesto in azcore.

My user is Stevej#5879

**Pull request closed without merging**
