### PR TITLE
Fixes to Illidan encounter.

### LINKED ISSUE #19552: Trigging invulnerability during the Illidan fight phase 2 when soloing him resets the encounter
### Current Behaviour

Casting Divine Shield, or presumably any invulnerability spell, during Phase 2 of the Illidan fight when soloing him causes the encounter to reset, except Akama does not appear to respawn.

### Expected Blizzlike Behaviour

Presumably the fight should still continue regardless.

### Source

_No response_

### Steps to reproduce the problem

1. Engage Illidan solo.
2. Fight him to Phase 2.
3. Cast Divine Shield. Encounter will reset.

### Extra Notes

_No response_

### AC rev. hash/commit

fcdc50306ff8734f6f56d22db54862c173879f10

### Operating system

Windows Server 2022

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by ASBaj**
- If raid wipes during phase 2, raid will be reset correctly and illidan will be selectable for the next attempt.
- Using invulnerability during phase 2 will no longer cause the raid to reset.

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #19552

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Blandyoung** [comment]
There are still issues that have not been considered.
The transition phase will clearall threaten.
it‘s still reset.
﻿Perhaps we should randomly select a target after the transition phase to increase the threat value a bit.

**Comment by Blandyoung** [comment]
void EnterEvadeMode(EvadeReason why) override
        {

            if (Creature* akama = ObjectAccessor::GetCreature(*me, instance->GetGuidData(NPC_AKAMA)))
                akama->AI()->EnterEvadeMode(why);

            if (Player* player = me->SelectNearestPlayer(100.0f))
            {
               if (player->IsInCombat()) //need more test             
                    return;
            }
            BossAI::EnterEvadeMode(why);
            Reset();
        }

**Comment by Gultask** [comment]
Hello, I've spent some time rewriting Illidan and I took this PR into consideration as well. You can see it that I've resolved by using:

- a boolean for when Maiev is spawned, so that when Illidan checks for players and finds they're all immune, he won't evade needlessly.
- a check for while he's flying. Whenever he checks for phase transition, he also checks if there's any players left in combat. If not he evades

image

Also, using ReplaceUnitFlags() in Reset will remove the NOT_SELECTABLE flag.

So thanks for the PR regardless!

**Comment by ASBaj** [comment]
> Hello, I've spent some time rewriting Illidan and I took this PR into consideration as well. You can see it that I've resolved by using:
> 
> * a boolean for when Maiev is spawned, so that when Illidan checks for players and finds they're all immune, he won't evade needlessly.
> * a check for while he's flying. Whenever he checks for phase transition, he also checks if there's any players left in combat. If not he evades
> 
> image
> 
> Also, using ReplaceUnitFlags() in Reset will remove the NOT_SELECTABLE flag.
> 
> So thanks for the PR regardless!

That's great, thanks! I definitely don't have any more time to put into this lol.

**Pull request closed without merging**
