### PR TITLE
Core/Auction: Fix client crashes on lists of bids and own auctions

### PR DESCRIPTION
**Pull request by Viste**
## CHANGES PROPOSED:
-  Previous behavior was dumping too much to data to client and caused crashes. 
- To see more than last 50 auctions and bids, consider using UI addons.  
thx to Warlockbugs and mangos team

## TESTS PERFORMED:
- build only
## HOW TO TEST THE CHANGES:
 - Use AuctionHouse
## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
I tested these and none of them were wrong.
1.Auction items(176).
2.View the list of auctions.
3.List of sellers.
4.List of bids.
5.A normal auction process.6.

**Comment by BarbzYHOOL** [comment]
How do we test this BEFORE the PR to see the crash? I have never heard of this crash before

**Comment by pklloveyou** [comment]
It should be a kind of crash before the repair.

**Comment by Viste** [comment]
> How do we test this BEFORE the PR to see the crash? I have never heard of this crash before

t

> How do we test this BEFORE the PR to see the crash? I have never heard of this crash before

you can overflow client buffer with WPE PRO packets manipulation

**Comment by BarbzYHOOL** [comment]
> It should be a kind of crash before the repair.
> It should have been fixed before the crash.
> Translation software translated content seems to be not very accurate, I changed an expression.

do you use deepl.com for translation? 你用deepl.com做翻译吗？

**Comment by pklloveyou** [comment]
> > It should be a kind of crash before the repair.
> > It should have been fixed before the crash.
> > Translation software translated content seems to be not very accurate, I changed an expression.
> 
> do you use deepl.com for translation? 你用deepl.com做翻译吗？

https://translate.yandex.com/

**Comment by BarbzYHOOL** [comment]
@pklloveyou try this https://www.deepl.com/translator#zh/en/是插件的引起的？没往这方面想。。。好的我去试一下，谢谢你 !!

/end offtopic :P

**Comment by kuramajssken001** [comment]
> > > It should be a kind of crash before the repair.
> > > It should have been fixed before the crash.
> > > Translation software translated content seems to be not very accurate, I changed an expression.
> > 
> > 
> > do you use deepl.com for translation? 你用deepl.com做翻译吗？
> 
> https://translate.yandex.com/

There is a problem with this commit

Can not cancel the auction

**Comment by kuramajssken001** [comment]
> I tested these and none of them were wrong.
> 1.Auction items(176).
> 2.View the list of auctions.
> 3.List of sellers.(176)
> 4.List of bids.
> 5.A normal auction process.

Can not cancel the auction

**Comment by Nefertumm** [comment]
Did you test without the pr too? To confirm if it's the pr or something else.

**Comment by kuramajssken001** [comment]
> Did you test without the pr too? To confirm if it's the pr or something else.

yeah,pr

**Comment by pklloveyou** [comment]
> > Did you test without the pr too? To confirm if it's the pr or something else.
> > @Nefertumm
> > yeah,pr

confirm

**Comment by BarbzYHOOL** [comment]
WITHOUT the PR?? @pklloveyou @kuramajssken001

**Comment by pklloveyou** [comment]
@BarbzYHOOL Without PR, function normally

**Comment by Viste** [comment]
thanks i look

**Comment by BarbzYHOOL** [comment]
hmm i might test it soon, especially the bug kuramassj reported
plz remind me

**Pull request closed without merging**
