### PR TITLE
feat(Core/Achievements): Send guild's name instead of the player's on…

### LINKED ISSUE #5369: Realm First! achievements from raids should announce name of guild to server [$35]
## CURRENT BEHAVIOUR:
When you achieve a Realm First! from raids, the following messages are broadcast to the server:
```
name has earned the achievement [Realm First! xyz]
name2 has earned the achievement [Realm First! xyz]
name3 has earned the achievement [Realm First! xyz]
```
etc (how many are in the raid that get the achievement - up to 25 times)

## EXPECTED BLIZZLIKE BEHAVIOUR:

Essentially, the broadcast should use the guild name for the sake of the server-wide spam.  If you are in the raid and close proximity to the players getting the achievements, it should look like this:

```
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
Player1 has earned the achievement [The Fall of Naxxramas]!
player1 has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
Player2 has earned the achievement [The Fall of Naxxramas]!
player2 has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
Player3 has earned the achievement [The Fall of Naxxramas]!
player3 has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
```

For the rest of the server, it looks like this:

```
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
guild has earned the achievement [Realm First! Conqueror of Naxxramas]!
```

This should be the behavior on only the following achievements:

[Realm First! Obsidian Slayer](https://wotlkdb.com/?achievement=456)
[Realm First! Conqueror of Naxxramas](https://wotlkdb.com/?achievement=1402)
[Realm First! Magic Seeker](https://wotlkdb.com/?achievement=1400)
[Realm First! Celestial Defender](https://wotlkdb.com/?achievement=3259)
[Realm First! Death's Demise](https://wotlkdb.com/?achievement=3117)
[Realm First! Grand Crusader](https://wotlkdb.com/?achievement=4078)
[Realm First! Fall of the Lich King](https://wotlkdb.com/?achievement=4576)

## SOURCE:

https://i.imgur.com/BTtayWL.jpg -- In this screenshot, the guild names are Doesnt look like Amiye and Did it for Whitney - screenshot is from July 2010 and was taken from someone not in the raid

Video, same source as the screenshot above: https://youtu.be/IrEyrMw6IlY - Pause at 8:50 and play at .25% speed, it's hard to catch.  screenshot from video if you miss it: https://i.imgur.com/Bv5k9UU.png

CUTIES ONLY guild downing Algalon for the first time, video from 2009 - pause at 6:32 and play at .25% speed https://www.youtube.com/watch?v=yzZ8LTGcMVI - screenshot: https://i.imgur.com/RTWZis0.png

noxa guild downing Anub'arak w/ 50 attempts remaining, video from 2009 - pause at 9:12 and play at .25% speed https://youtu.be/aN6at_DO_N8 - screenshot: https://i.imgur.com/oc3H5uE.png

Wowhead comments:

https://www.wowhead.com/achievement=3259/realm-first-celestial-defender#comments:id=655280 - "Like all Realm First raid achievements, you will recieve a title for slaying the final boss in the raid. In this case, the title is: "The Celestial Defender". Not only do you get the title, but a nice **server-wide message stating your guild is broadcasted**!"

https://www.wowhead.com/achievement=3259/realm-first-celestial-defender#comments:id=655681 - "the message says "guild name" has earned the achievement [ Realm First: Celestial Defender] x25 not player names."

https://www.wowhead.com/achievement=1400/realm-first-magic-seeker#comments:id=726513

https://www.wowhead.com/achievement=1400/realm-first-magic-seeker#comments:id=676363

## STEPS TO REPRODUCE THE PROBLEM:
1. Create a character and create a guild
2. Create another character, on a separate account to watch the chatbox
3. On your first character, kill a boss that yields these achievements
4. Go to your second character and read the chatbox
5. The broadcast will contain the PLAYER NAME, not the guild name 

## EXTRA NOTES:
No other server has this right - it's really a forgotten mechanic.  I've been meaning to post this issue for a long time, but getting confirmation that it's real is a pain in the ass.

## AC HASH/COMMIT:
9997fa7

## OPERATING SYSTEM:
Win10

<bountysource-plugin>

---
There is a **[$35 open bounty](https://www.bountysource.com/issues/97910266-realm-first-achievements-from-raids-should-announce-name-of-guild-to-server?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…e when achieved realm first kill.

Fixed #5369.

## Changes Proposed:
-  Added condition: if player has guild send its name to the server for realm first kill achievements.

## Issues Addressed:
- Closes #5369.

## Tests Performed:

- Tested ingame with two different chars and different achievements.

## How to Test the Changes:

1. Create char.
2. Create your own guild by command: `.guild create "name_of_guild"`.
3. `.achiev add 4576`.
4. Observe chatt.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by HerrPony** [comment]
A first check of the code looks like that you always broadcast the guild name on first kill achivement. Not only for the given achivements in the issue.

As far as i can see there has to be a check if the achivement is one of the given and if 80% or more of the raid is in the same guild.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Voxstrasza** [comment]
> 
> 
> A first check of the code looks like that you always broadcast the guild name on first kill achivement. Not only for the given achivements in the issue.
> 
> As far as i can see there has to be a check if the achivement is one of the given and if 80% or more of the raid is in the same guild.

It doesn't need to be the same guild.  See this screenshot:  https://i.imgur.com/BTtayWL.jpg

Two different guilds earning the achievement.

**Comment by Voxstrasza** [comment]
BTW, the 80% thing from the issue comments is from **CATACLYSM**

This is completely different.  Please do not get it mixed up and implement the wrong coding:

WOTLK has CHARACTER Realm First achievements - when the raid realm first achievements are earned, the realm gets broadcasted the name of the guild x25 times (can be two or three different guilds, the guild gets broadcasted instead of the character name) (see the issue for how it looks)

Cataclysm has GUILD achievements.  This is very, very different.

**Comment by Voxstrasza** [comment]
I tested this out with 4 characters - one Horde level 1 sitting in the starter zone, and 3 level 80 alliance venturing into a raid to earn an achievement.

When I leveled the alliance characters to 80 on a 5th separate GM character, the following message was broadcast to the realm (viewed from a level 1 horde):

```
[10:53 AM] Uno has earned the achievement [Realm First! Level 80]!
[10:53 AM] Uno has earned the achievement [Realm First! Level 80 Priest]!
[10:53 AM] Uno has earned the achievement [Realm First! Level 80 Dwarf]!
[10:54 AM] Dos has earned the achievement [Realm First! Level 80 Paladin]!
[10:54 AM] Dos has earned the achievement [Realm First! Level 80 Draenei]!
[10:55 AM] Chickenwing has earned the achievement [Realm First! Level 80 Hunter]!
[10:55 AM] Chickenwing has earned the achievement [Realm First! Level 80 Night Elf]!
```

Uno, Dos and Chickenwing are the character names - so it doesn't and it shouldn't broadcast their guild name for level or profession achievements.

Next, I placed them all in the same guild - Animosity - and I killed Sartharion on 25 man (again, 3 toons = 3 broadcasts) - the following message was broadcast to the realm (viewed from a level 1 horde):

```
[11:01 AM] Animosity has earned the achievement [Realm First! Obsidian Slayer]!
[11:01 AM] Animosity has earned the achievement [Realm First! Obsidian Slayer]!
[11:01 AM] Animosity has earned the achievement [Realm First! Obsidian Slayer]!
```

All seems correct so far, but let's add a 4th character to the raid, in the guild Eternal - the following message was broadcast to the realm (viewed from a level 1 horde):


```
[11:11 AM] Eternal has earned the achievement [Realm First! Magic Seeker]!
[11:11 AM] Animosity has earned the achievement [Realm First! Magic Seeker]!
[11:11 AM] Animosity has earned the achievement [Realm First! Magic Seeker]!
[11:11 AM] Animosity has earned the achievement [Realm First! Magic Seeker]!
```

All seems good.  For good measure, I maxed one of the toons professions - this is the broadcast:

```
[11:15 AM] Uno has earned the achievement [Realm First! Grand Master Jewelcrafter]!
```

**Review by Voxstrasza — APPROVED** [review]

**Comment by HerrPony** [comment]
> BTW, the 80% thing from the issue comments is from **CATACLYSM**
> 
> This is completely different. Please do not get it mixed up and implement the wrong coding:
> 
> WOTLK has CHARACTER Realm First achievements - when the raid realm first achievements are earned, the realm gets broadcasted the name of the guild x25 times (can be two or three different guilds, the guild gets broadcasted instead of the character name) (see the issue for how it looks)
> 
> Cataclysm has GUILD achievements. This is very, very different.

Sorry! It wasn't meant to be rude or something like this. In the issue was someone who was sure that you have to be 80% in the same guild and everything so i just thought we have to check for that. Sorry again ....

**Comment by Voxstrasza** [comment]
> 
> 
> > BTW, the 80% thing from the issue comments is from **CATACLYSM**
> > This is completely different. Please do not get it mixed up and implement the wrong coding:
> > WOTLK has CHARACTER Realm First achievements - when the raid realm first achievements are earned, the realm gets broadcasted the name of the guild x25 times (can be two or three different guilds, the guild gets broadcasted instead of the character name) (see the issue for how it looks)
> > Cataclysm has GUILD achievements. This is very, very different.
> 
> Sorry! It wasn't meant to be rude or something like this. In the issue was someone who was sure that you have to be 80% in the same guild and everything so i just thought we have to check for that. Sorry again ....

Don't be sorry - I was just trying to get my point across lol.  The 80% thing is a system implemented in Cataclysm.  In WotLK, it's just character based realm firsts.  I think the idea behind announcing the guild instead of the character for raid realm firsts was to bring credit to the guild as a whole rather than the individual player (which eventually became guild achievements)

**Comment by Voxstrasza** [comment]
@FrancescoBorzi if you're ok with this, I think it's good to merge.  It works correctly and matches all the screenshots/videos and wowhead comments.

Probably won't be seen in full until chromiecraft reaches level 80.

**Comment by Branel** [comment]
My bad for giving that faulty source about 80% - good of you to point out the misstake and sorry Herrpony for the missinformation.

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
