### PR TITLE
fix(DB/Creature): Make Webwood spiders and Githyiss the Vile neutral

### PR DESCRIPTION
**Pull request by Asthalor**
## Changes Proposed:
-  Make Webwood spiders and Githyiss the Vile neutral by adding civilian status and faction creature, that is neutral to players

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7627
- Closes https://github.com/chromiecraft/chromiecraft/issues/1581

## SOURCE:

https://www.wowhead.com/quest=917/webwood-egg#comments

## Tests Performed:

- .gm off (if not they are always yellow)
- .go c id 1986 and check the bar now yellow
- .go c id 1994and check the bar now yellow

Test

spider neutral

githyss neutral

## How to Test the Changes:

1. .gm off ( if not they are always yellow)
2. .go c id 1986 and check the bar now yellow
3. .go c id 1994and check the bar now yellow

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by JamesGent** [comment]
This PR is not needed as the report is invalid. Sorry friend.

https://www.wowhead.com/npc=1986/webwood-spider#comments

By Delvara on 2009/02/22 (Patch 3.0.9) |   |  
Also to be noted, this is usually the first aggressive creature that Night Elves meet.

**Comment by syssneck** [comment]
Tested and it works just fine! 
You have one unnecessary pair of brackets in your SQL, but it also works this way.

**Comment by Si1ker** [comment]
https://github.com/TrinityCore/TrinityCore/blob/f759809d9d4364bc1d988e4390d3d5a33d5469e9/sql/old/4.3.4/TDB0_to_TDB1_updates/world/021_creature_template.sql#L55

https://github.com/TrinityCore/TrinityCore/blob/f759809d9d4364bc1d988e4390d3d5a33d5469e9/sql/old/4.3.4/TDB0_to_TDB1_updates/world/021_creature_template.sql#L62

TC has these as 22

**Comment by Asthalor** [comment]
Faction 22 is Beast - Spider. 

image

Because they have a 8 in ourMask that means that is aggresive to players.
Because they wanted to be neutral that must to change.
Creature is 0 on ourMask, frendlyMask and HostileMask, so its neutral to everyone.

**Comment by Asthalor** [comment]
Look like this change is from 3.3.3, because on the forum there are answers that said they were aggresive and other that they were neutral.

SIPERS INFO

We can try to use another faction that have 0 on ourMask, but i tought creature was fine.

**Comment by Si1ker** [comment]
image

Reference: https://ptr.wowhead.com/npc=1986/webwood-spider#comments

I may think the possibility that the change was on 3.3 and then rolled back.
On newer versions after that (following xpacs to woltk) they were aggressive.

Also, (no good source but still source 'cause paid devs n.n), found this warmane video, showing the spiders aggressive):
https://youtu.be/8VOVgdHKTt4?t=74

**Comment by Asthalor** [comment]
Hmm, then what should we do? Make them neutral or keep them aggresive?

**Comment by Si1ker** [comment]
https://web.archive.org/web/20100207210021/http://www.worldofwarcraft.com/patchnotes/#3.3.0

pending.
At the moment, looking at changes from 3.3 to 3.3.5a , hoping to get any info about changes to initial creatures

**Review by Si1ker — APPROVED** [review]
Go ahead.

Webwood Spider are level 3-4
Githyiss the Vile is Level 5

**Patch 3.3.0 (undocumented changes)**
image
Reference: https://wowwiki-archive.fandom.com/wiki/Patch_3.3.0_(undocumented_changes)

**Comment by Kitzunu** [comment]
They are not civilians. Changing the faction should be enough.

**Comment by Asthalor** [comment]
Thanks Kitzunu, i will update the SQL and do a quick test then.
I took the example of Diseased Timber Wolf (69) and they had it, so i tought it was neccesary hehe

**Comment by JamesGent** [comment]
Tested and works fine on my end too. Simply loaded the SQL into World & they're all yellow now.

**Pull request merged**
