### PR TITLE
fix(DB/Event):  Brewfest - Synthebrew Goggles and Ram Racing Reins

### PR DESCRIPTION
**Pull request by locus313**
## CHANGES PROPOSED:
-  Fix smart_scripts for synthebrew goggles and ram racing reins
-  Fix conditions and gossip_menu_option for synthebrew goggles

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3495
- Credits: @genion18

## TESTS PERFORMED:
- Apply sql and restart server
- Check that glodrak huntsniper and goldark snipehunter now provides the synthebrew goggles
- Check that driz tumblequick provides the ram racing reins

## HOW TO TEST THE CHANGES:

- Apply sql and restart server
- Check that glodrak huntsniper and goldark snipehunter now provides the synthebrew goggles
- Check that driz tumblequick provides the ram racing reins

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Kitzunu** [comment]
In the future, please do not @ the original author.
Use the GitHub Co-authored-by feature to avoid people getting unnecessary pings :)

I know some have complained about it, and I think it is a fair way of doing it ^^

**Comment by genion18** [comment]
Its okay, This way.
Greets: genion18 aka Toxic/ICC/C7 since 1989

**Comment by locus313** [comment]
Thanks, was not aware of that feature in github. Will use that going forward.

**Comment by locus313** [comment]
Can this be merged soon? The other open pr https://github.com/azerothcore/azerothcore-wotlk/pull/3511 is dependent on being able to receive the synthebrew goggles.

**Comment by FrancescoBorzi** [comment]
sure @locus313

**Pull request merged**
