### PR TITLE
fix(DB/Gameobject): Fix Silithyst Geyser click invalid

### PR DESCRIPTION
**Pull request by disgrace2013**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 
- #18034 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Thanks for the PR!

Could this aura also be added via gameobject_template_addon maybe?
Also did you generate the SAI comment with Keira? It feels like the comment is incomplete 

Also what can you please describe the issue that existed before this PR real quick

**Comment by sudlud** [comment]
Also you might want to create a local branch on your AC fork and not use "master" branch to open a PR.

Otherwise this might very likely lead to issues in your AC fork later on if you're not too familiar with Git.

**Comment by disgrace2013** [comment]
> Thanks for the PR!
> 
> Could this aura also be added via gameobject_template_addon maybe? Also did you generate the SAI comment with Keira? It feels like the comment is incomplete
> 
> Also what can you please describe the issue that existed before this PR real quick

Quest [Scouring the Desert] in Silithus cannot be completed because player cannot gain aura [Silithyst] when righ-click a Silithyst Geyser.

**Comment by disgrace2013** [comment]
> Also you might want to create a local branch on your AC fork and not use "master" branch to open a PR.
> 
> Otherwise this might very likely lead to issues in your AC fork later on if you're not too familiar with Git.

I got it,ty.

**Comment by sudlud** [comment]
Thanks for the feedback!

So this PR is closing #18034?

If yes, you can add the issue number after the "Closes" in your PR description.

This will correctly link this PR to the issue and also the issue gets closed when the PR is getting merged.

**Comment by disgrace2013** [comment]
> Thanks for the feedback!
> 
> So this PR is closing #18034?
> 
> If yes, you can add the issue number after the "Closes" in your PR description.
> 
> This will correctly link this PR to the issue and also the issue gets closed when the PR is getting merged.

YES

**Comment by disgrace2013** [comment]
> Thanks for the feedback!
> 
> So this PR is closing #18034?
> 
> If yes, you can add the issue number after the "Closes" in your PR description.
> 
> This will correctly link this PR to the issue and also the issue gets closed when the PR is getting merged.

Yes,I've done that.

**Comment by sudlud** [comment]
> > Thanks for the feedback!
> 
> > 
> 
> > So this PR is closing #18034?
> 
> > 
> 
> > If yes, you can add the issue number after the "Closes" in your PR description.
> 
> > 
> 
> > This will correctly link this PR to the issue and also the issue gets closed when the PR is getting merged.
> 
> 
> 
> Yes,I've done that.

Thanks! - but please ensure the issue number is in the same line as the keyword "Closes":

- Closes #...

**Comment by sudlud** [comment]
> > Also you might want to create a local branch on your AC fork and not use "master" branch to open a PR.
> 
> > 
> 
> > Otherwise this might very likely lead to issues in your AC fork later on if you're not too familiar with Git.
> 
> 
> 
> I got it,ty.

I think this might require opening a new PR based on the local branch

**Comment by disgrace2013** [comment]
> > > Also you might want to create a local branch on your AC fork and not use "master" branch to open a PR.
> > 
> > 
> > > 
> > 
> > 
> > > Otherwise this might very likely lead to issues in your AC fork later on if you're not too familiar with Git.
> > 
> > 
> > I got it,ty.
> 
> I think this might require opening a new PR based on the local branch

OK

**Pull request closed without merging**
