### PR TITLE
fix(CORE/Player): Allow sharing completed in log quests. Send push to…

### PR DESCRIPTION
**Pull request by AbraKabastard**
… party on failed reason seasonal

Quest sharing wasn't allowed when the quest was completed in the log but not handed in.
Quest sharing that would fail because of seasonal quests didn't let the player know why.

## Changes Proposed:
-  Removed code preventing sharing on completed quests
-  Add code to send party response
-  This code is same as TC now

## Issues Addressed:
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/4958
- Closes https://github.com/chromiecraft/chromiecraft/issues/216

## Tests Performed:
- Get a quest into the completed state and attempt to share it
- Attempt to share a quest that is seasonal when not in season
- 

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @AbraKabastard for fixing this!

just a note: next time, can you please first open the issue on the AC side (you can just copy-paste the original report from ChromieCraft), link the two issues together, and change the label on the original issue from [Needs triage] to [Linked (AC)] ?

we do this to keep track of all issues coming from ChromieCraft and organize them in the GitHub projects, so we can do some statistics as well.

For this time it's not needed 👍

**Review by Stifler82 — APPROVED** [review]
👍

**Comment by Stifler82** [comment]
> 👍

@FrancescoBorzi 
Tested and works perfectly!

**Comment by FrancescoBorzi** [comment]
> > 👍
> 
> @FrancescoBorzi
> Tested and works perfectly!

good job @AbraKabastard and @Stifler82 !

**Pull request merged**
