### PR TITLE
fix(DB/quest_template): Beer Basted Boar Ribs (384) shouldn't require Cooking skill

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  Removes Skill requirement
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14033
- Closes https://github.com/chromiecraft/chromiecraft/issues/4524

## SOURCE:

WotLK Classic PTR

## Tests Performed:

- Tested ingame
- 

## How to Test the Changes:

1. Create a dwarf/gnome
2. .level 4
3. .go c id 1267

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Please update the branch, it's complaining about a file that doesn't exist

**Comment by Gultask** [comment]
Thanks, I was wondering what was the issue.
But this seems to be a sniffed value so I'm waiting on WPP for now.

**Comment by heyitsbench** [comment]
```
ServerToClient: SMSG_QUERY_QUEST_INFO_RESPONSE (0x2A96)
Entry: 384
Has Data: True
Quest ID: 384
QuestType: 2 (Normal)
QuestLevel: 7
QuestScalingFactionGroup: 0
QuestMaxScalingLevel: 255
QuestPackageID: 0
QuestMinLevel: 5
QuestSortID: -304
QuestInfoID: 0 (None)
SuggestedGroupNum: 0
RewardNextQuest: 0
RewardXPDifficulty: 5
RewardXPMultiplier: 1
RewardMoney: 175
RewardMoneyDifficulty: 5
RewardMoneyMultiplier: 1
RewardBonusMoney: 390
[0] RewardDisplaySpell: 0
[1] RewardDisplaySpell: 0
[2] RewardDisplaySpell: 0
RewardSpell: 0
RewardHonor: 0
RewardKillHonor: 0
RewardArtifactXPDifficulty: 0
RewardArtifactXPMultiplier: 1
RewardArtifactCategoryID: 0
StartItem: 0
Flags: 262152 (Sharable, DisableCompletionText)
FlagsEx: 0 (None)
FlagsEx2: 0 (None)
[0] RewardItems: 2888
[0] RewardAmount: 5
[0] ItemDrop: 0
[0] ItemDropQuantity: 0
[1] RewardItems: 2889
[1] RewardAmount: 1
[1] ItemDrop: 0
[1] ItemDropQuantity: 0
[2] RewardItems: 0
[2] RewardAmount: 0
[2] ItemDrop: 0
[2] ItemDropQuantity: 0
[3] RewardItems: 0
[3] RewardAmount: 0
[3] ItemDrop: 0
[3] ItemDropQuantity: 0
[0] RewardChoiceItemID: 0
[0] RewardChoiceItemQuantity: 0
[0] RewardChoiceItemDisplayID: 0
[1] RewardChoiceItemID: 0
[1] RewardChoiceItemQuantity: 0
[1] RewardChoiceItemDisplayID: 0
[2] RewardChoiceItemID: 0
[2] RewardChoiceItemQuantity: 0
[2] RewardChoiceItemDisplayID: 0
[3] RewardChoiceItemID: 0
[3] RewardChoiceItemQuantity: 0
[3] RewardChoiceItemDisplayID: 0
[4] RewardChoiceItemID: 0
[4] RewardChoiceItemQuantity: 0
[4] RewardChoiceItemDisplayID: 0
[5] RewardChoiceItemID: 0
[5] RewardChoiceItemQuantity: 0
[5] RewardChoiceItemDisplayID: 0
POIContinent: 0
POIx: 0
POIy: 0
POIPriority: 0
RewardTitle: 0
RewardArenaPoints: 0
RewardSkillLineID: 0
RewardNumSkillUps: 0
PortraitGiver: 0
PortraitGiverMount: 0
PortraitGiverModelSceneID: 0
PortraitTurnIn: 0
[0] RewardFactionID: 47
[0] RewardFactionValue: 5
[0] RewardFactionOverride: 0
[0] RewardFactionCapIn: 7
[1] RewardFactionID: 54
[1] RewardFactionValue: 5
[1] RewardFactionOverride: 0
[1] RewardFactionCapIn: 7
[2] RewardFactionID: 0
[2] RewardFactionValue: 0
[2] RewardFactionOverride: 0
[2] RewardFactionCapIn: 7
[3] RewardFactionID: 0
[3] RewardFactionValue: 0
[3] RewardFactionOverride: 0
[3] RewardFactionCapIn: 7
[4] RewardFactionID: 0
[4] RewardFactionValue: 0
[4] RewardFactionOverride: 0
[4] RewardFactionCapIn: 7
RewardFactionFlags: 3
[0] RewardCurrencyID: 0
[0] RewardCurrencyQty: 0
[1] RewardCurrencyID: 0
[1] RewardCurrencyQty: 0
[2] RewardCurrencyID: 0
[2] RewardCurrencyQty: 0
[3] RewardCurrencyID: 0
[3] RewardCurrencyQty: 0
AcceptedSoundKitID: 890
CompleteSoundKitID: 878
AreaGroupID: 0
TimeAllowed: 0
ObjectiveCount: 2
AllowableRaces: 1791
TreasurePickerID: 0
Expansion: 0
logTitleLen: 21
logDescriptionLen: 81
questDescriptionLen: 442
areaDescriptionLen: 0
questGiverTextWindowLen: 0
questGiverTargetNameLen: 0
questTurnTextWindowLen: 0
questTurnTargetNameLen: 0
questCompletionLogLen: 60
[0] Id: 380295
[0] Quest Requirement Type: 1 (Item)
[0] StorageIndex: 0
[0] ObjectID: 2886
[0] Amount: 6
[0] Flags: 0
[0] Flags2: 0
[0] ProgressBarWeight: 0
[0] VisualEffects: 0
[0] Description: 
[1] Id: 380296
[1] Quest Requirement Type: 1 (Item)
[1] StorageIndex: 1
[1] ObjectID: 2894
[1] Amount: 1
[1] Flags: 0
[1] Flags2: 0
[1] ProgressBarWeight: 0
[1] VisualEffects: 0
[1] Description: 
LogTitle: Beer Basted Boar Ribs
LogDescription: Ragnar Thunderbrew in Kharanos wants 6 Crag Boar Ribs and a mug of Rhapsody Malt.
QuestDescription: Nothing my tavern patrons enjoy more than some Beer Basted Boar Ribs!  Only problem is, the local trapper who used to bring me supplies enlisted in the King's Army to help with the war on the Alliance front. $b$bMaybe you can help me out?  If you bring me six crag boar ribs and a Rhapsody Malt from the tavern here, I'll give you the family recipe for my famous Beer Basted Boar Ribs, not to mention a free sample!  The secret's in the Malt!
AreaDescription: 
PortraitGiverText: 
PortraitGiverName: 
PortraitTurnInText: 
PortraitTurnInName: 
QuestCompletionLog: Return to Ragnar Thunderbrew at Shimmer Ridge in Dun Morogh.
```

**Comment by Gultask** [comment]
Thank you! But then this confirms we have a problem in the core: 
```
Quest 384 has `ZoneOrSort` = -304 but `RequiredSkillId` does not have a corresponding value (185).
```

**Pull request closed without merging**
