### PR TITLE
feat(Core/Command): Deserter rm all time parameter

### PR DESCRIPTION
**Pull request by Gozzim**
## Changes Proposed:
- Add an optional variable for the `.deserter remove bg all` and `.deserter remove instance all` commands
- Not specified defaults to 15min for bg and 30min for instance
- Set to -1 will remove any deserter debuff length

## Issues Addressed:

- Closes 

## Tests Performed:

- Added bg deserter < 15min and removed all with and without  a set time
- Added bg deserter >= 15min and removed all with and without  a set time
- Added bg deserter and removed all with time set to -1

## How to Test the Changes:

1. Use `.deserter bg add 300`
2. Use `.deserter bg remove all` and observe the outcome
3. Use `.deserter bg add 900`
4. Use `.deserter bg remove all` and observe the outcome
5. Use `.deserter bg add 3600`
6. Use `.deserter bg remove all 30m` and observe the outcome
7. Use `.deserter bg remove all 2h` and observe the outcome
8. Use `.deserter bg add 3600`
9. Use `.deserter bg remove all -1` and observe the outcome

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Unfortunatly, it's doesn't work for me. .debuff command doesn't exist. And if I use .deserter bg/instance remove all, it's marked as done but nothing IG (tested online and offline, with worldserver and IG).

Screenshot 2022-06-11 194945

**Comment by Gozzim** [comment]
@Maelthyrr oh yeah I seem to have made a mistake in the description but corrected it now.
Not adding any time on remove will default to 30min for instance and 15min for BG.
-1 will remove any time
And setting a time will remove any deserter debuff of that type with lower or equal the given time left.

It worked in my tests
Let me know if this information helps you out

**Comment by acidmanifesto** [comment]
@azerothcore/testers a retest will be needed on this pr.

**Comment by acidmanifesto** [comment]
Thank you for the test @Maelthyrr 
will merge when the compile testing is complete. it wont give me the option to merge when still running.
image

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
