### PR TITLE
fix(Core/Handlers): Faction Change service properly reset and give ne…

### LINKED ISSUE #7981: Faction change auto-learns all the flight paths in the new faction
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original post: https://github.com/chromiecraft/chromiecraft/issues/1788

Faction change auto-learns all the flight paths in the new faction 

Even the ones the player did not explore at all or even the lvl 70 ones.

### Expected Blizzlike Behaviour

Player should learn only the respective flight paths player has learned in player's previous faction. 

### Source

I only have anecdotal evidence unfortunately 

### Steps to reproduce the problem

Create an account
Learn a few (not all fight-paths)
change faction.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7e2e6f8ee85f82f57a3c6e0f6f645b4c42292e7a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### LINKED ISSUE #8732: Faction change opens inaccessible flypath on isle of Quel'Danas what preventing player to log in.
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2192

Since TBC content is not available, this shouldn't be possible. I misclicked a flight path there instead of Light's Hope (eyesight issues due to medical condition) and any attempt to land causes a D/C. 
This shouldn't be possible due to content gating, and you character essentially gets stuck in a feedback loop if any attempts to log back in are made.
WoWScrnShot_102521_134552

Testrer:

The issue is confirmed. Changing race open all flypaths included Isle of Quel'Danas. Can't reproduce DCs for sure. I guess it's related to content phases.
WoWScrnShot_102621_002419

### Expected Blizzlike Behaviour

A disconnect shouldn't be present when landing on this area. But this is a Chromie Craft issue at present. The FP should not be visible.

### Source

X

### Steps to reproduce the problem

.character factionchange
take fly to Isle

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Windows 10

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…w level-appropriate fly points.

Fixes #7981
Fixes #8732

## Issues Addressed:

- Closes #7981
- Closes #8732
- Closes https://github.com/chromiecraft/chromiecraft/issues/1788
- Closes https://github.com/chromiecraft/chromiecraft/issues/2192

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

change character level to something low, e.g. `char level 45`
`.character factionchange`
Change faction
See that only level-appropriate flight paths are available.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
```
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Handlers/CharacterHandler.cpp: In member function ‘void WorldSession::HandleCharFactionOrRaceChangeCallback(std::shared_ptr<CharacterFactionChangeInfo>, PreparedQueryResult)’:
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Handlers/CharacterHandler.cpp:2242:78: error: ‘sMapMgr’ was not declared in this scope
src/server/game/CMakeFiles/game.dir/build.make:1755: recipe for target 'src/server/game/CMakeFiles/game.dir/Handlers/CharacterHandler.cpp.o' failed
                     AreaTableEntry const* zone = sAreaTableStore.LookupEntry(sMapMgr->GetZoneId(PHASEMASK_NORMAL, pathNode->mapid, pathNode->x, pathNode->y, pathNode->z));
```

**Comment by temperrr** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'TaxiPathBySourceAndDestination': identifier not found (compiling source file H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\LuaFunctions.cpp)	modules	H:\Azerothcore\modules\mod-eluna-lua-engine\src\LuaEngine\GlobalMethods.h	2422	
Error	LNK2001	unresolved external symbol "class std::map<unsigned int,class std::map<unsigned int,struct TaxiPathBySourceAndDestination,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,struct TaxiPathBySourceAndDestination> > >,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,class std::map<unsigned int,struct TaxiPathBySourceAndDestination,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,struct TaxiPathBySourceAndDestination> > > > > > sTaxiPathSetBySource" (?sTaxiPathSetBySource@@3V?$map@IV?$map@IUTaxiPathBySourceAndDestination@@U?$less@I@std@@V?$allocator@U?$pair@$$CBIUTaxiPathBySourceAndDestination@@@std@@@3@@std@@U?$less@I@2@V?$allocator@U?$pair@$$CBIV?$map@IUTaxiPathBySourceAndDestination@@U?$less@I@std@@V?$allocator@U?$pair@$$CBIUTaxiPathBySourceAndDestination@@@std@@@3@@std@@@std@@@2@@std@@A)	worldserver	F:\Build\src\server\worldserver\modules.lib(LuaFunctions.obj)	1	
Error	LNK1120	1 unresolved externals	worldserver	F:\Build\bin\RelWithDebInfo\worldserver.exe	1	



(I run with eluna)

**Comment by temperrr** [comment]
Still have the same error

**Comment by UltraNix** [comment]
Not with Eluna.

**Comment by tkn963** [comment]
Tested, works as it should! 👍

**Comment by temperrr** [comment]
Would be great not to merge before the eluna issue has been resolved :)

**Comment by UltraNix** [comment]
@azerothcore/testers Please, test it.

**Comment by UltraNix** [comment]
What are we waiting here for?

**Comment by Kitzunu** [comment]
I guess @temperrr hasn't finished his test in a month lol.

@temperrr status? Does this work or not?

**Comment by temperrr** [comment]
It works but the eluna one needs to be pred first

**Comment by temperrr** [comment]
Otherwise eluna breaks

**Comment by UltraNix** [comment]
Yes - Eluna fix is ready to be pushed, but I don't know how to do it :(

**Comment by UltraNix** [comment]
As the Eluna is already merged, this one can be merged as well.

**Pull request merged**
