### PR TITLE
fix(DB/creature): King Bangalash

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
- Respawn should be 5m (not 30) aka 10m with (default) decay for elites
- This matches the vmangos timer (weak evidence, I know...)
- Says 5-10 mins: https://www.wowhead.com/npc=731/king-bangalash#comments
- 10m was selected as a "sounds about right to me" number
- He should walk around and not just stay in a fixed position (walking around randomly now)

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/196
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4828

## Tests Performed:
- Applied SQL
- Watched him walk around... Didn't wait for him to respawn.

## How to Test the Changes:

- `.go c id 731`
- watch him move, kill and wait...

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Comment by Zoidwaffle** [comment]
To make it visible: I changed the respawn from 10m to 5m. This is because the default decay is 5m for elites, and in total it makes it a 10m respawn rate (which is what the goal was).

I tested the above and it seems correct on my own server - please correct me if I'm wrong.

**Review by Stifler82 — CHANGES_REQUESTED** [review]
```
UPDATE `creature` SET `spawntimesecs`=300,`MovementType`=1, `wander_distance`=10 WHERE `guid`=2169;
```

60 are too much yrds!

**Comment by Stifler82** [comment]
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4828

**Comment by Zoidwaffle** [comment]
60 yards isn't that much - I have been standing at the respawn point doing `.distance` for a while. He never really gotten that far away.

There are 36 other mobs with a walking distance of 60, that's the reason for the number.

Just 10 as you suggested is really not a lot. I found no videos where I can really see how he moves - but if he's supposed to stay pretty fixed, then 10 is fine.

No matter what, any movement is better than no movement as he had before. So I changed it to 10 as @Stifler82 suggested.

**Comment by Stifler82** [comment]
> 60 yards isn't that much - I have been standing at the respawn point doing `.distance` for a while. He's never really gotten that far away.
> 
> There are 36 other mobs with a walking distance of 60, that's the reason for the number.
> 
> Just 10 as you suggested is really not a lot. I found no videos where I can really see how he moves - but if he's supposed to stay pretty fixed, then 10 is fine.
> 
> No matter what, any movement is better than no movement as he had before. So I changed it to 10 as @Stifler82 suggested.

60 yrds is a lot Dude, I don't know..
I am not saying that you must necessarily do 10yrds, but not more than 15yrds


https://user-images.githubusercontent.com/1884642/111028488-ddb4c980-83ee-11eb-8504-8db5dea9cad7.mp4

**Comment by Zoidwaffle** [comment]
No worries, 10 yards is fine - as already said, this is better than what was.

If anyone has some sort of evidence for what a better value is, it's trivial to update it now or later :+1:

**Review by Stifler82 — APPROVED** [review]
👍

**Comment by Zoidwaffle** [comment]
I believe it's ready to merge, it has been tested and reviewed and all seems fine.

**Comment by Zoidwaffle** [comment]
@FrancescoBorzi : hm, it's registered that Stifler82 already reviewed the code, but it's not marked as reviewed here? So could I ask for a review? Thanks!

**Comment by Stifler82** [comment]
> @FrancescoBorzi : hm, it's registered that Stifler82 already reviewed the code, but it's not marked as reviewed here? So could I ask for a review? Thanks!

@Zoidwaffle 
what do you mean?

**Comment by Zoidwaffle** [comment]
Ah, there's a `Stifler82 approved these changes 3 days ago` notice, but in the upper right corner, under reviewers, there should be a little green icon - but it's grey (the tiny "v" like shape, I don't know the English name for it).

Or maybe I'm wrong and all is fine as it is.

**Review by Stifler82 — APPROVED** [review]
test Approve

**Comment by Stifler82** [comment]
Me also see the gray tick

image

**Comment by LukasVolgger** [comment]
You need an approvement by an member with writing access. Here you go

**Review by LukasVolgger — APPROVED** [review]

**Review by Si1ker — APPROVED** [review]

**Review by Voxstrasza — APPROVED** [review]

**Pull request merged**
