### PR TITLE
DB: Fixes Issue #1439 [QUEST] The Shimmering Frond

### PR DESCRIPTION
**Pull request by CookieMonsterDev**
Quest Fix

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1439

##### TESTS PERFORMED:

Tested on windows with a horde character.

##### HOW TO TEST THE CHANGES:

Login with a horde character and do:
.go 10849 2053 1327 1

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by CookieMonsterDev** [comment]
Fixing issue right now lol

**Comment by FrancescoBorzi** [comment]
Thank you @CookieMonsterDev ! Waiting for tester approval

**Comment by comix1988** [comment]
I tested this PR and now it works correctly.
the quest is now available only from the alliance players. 
Good job @CookieMonsterDev

**Comment by FrancescoBorzi** [comment]
thank you very much @CookieMonsterDev and @comix1988 !

**Pull request merged**
