### PR TITLE
fix(Core/Build): correct macos build

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Fix build for macos

### CODE REVIEW

**Comment by Kitzunu** [comment]
drop mac support when? :P

**Comment by Winfidonarleyan** [comment]
> drop mac support when? :P

I'm curious, too.

**Comment by Kitzunu** [comment]
I wonder if someone actually runs AC on mac, or if they run it in docker

**Comment by iraizo** [comment]
most of them dont even use an Intel cpu and ac does not even support arm64e so why bother

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
