### PR TITLE
Check range of fire totem when casting Fire Nova

### LINKED ISSUE #1530: [PVP/PVE][SPELL] FIRE NOVA
##### SMALL DESCRIPTION:
The Shaman spell Fire Nova have not range limit , not the range of the damage of the spell that is activated on the totem https://wow.gamepedia.com/Magma_Totem , the range of activation of the spell from the totem 
 https://wotlk-twinhead.twinstar.cz/?spell=1535 (spell fire nova ) 

##### EXPECTED BLIZZLIKE BEHAVIOUR:
 The shaman spell Fire Nova should have a range of 30 yard   , 36 if improved with talent , of activation from the totem https://wow.gamepedia.com/Magma_Totem

https://wotlk-twinhead.twinstar.cz/?spell=1535

##### CURRENT BEHAVIOUR:
Infinite Range of Activation from the totem https://wow.gamepedia.com/Magma_Totem

##### STEPS TO REPRODUCE THE PROBLEM:
summon https://wow.gamepedia.com/Magma_Totem , don't waste time the totem will disappear  , go far from the totem , more than 36  yard or more and u will see that the spell Fire Nova can be activated 

##### AC HASH/COMMIT:

44272f1

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70608254-pvp-pve-spell-fire-nova?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Viste**
##### CHANGES PROPOSED:
-  Check range of fire totem when casting Fire Nova
##### Target branch(es): Master
**How to test:** place totem and try to cast fire nova from a distance of over 30/36(if improved with talent)  yards If this doesn't work out, it's okay.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Viste can you please provide instructions for testers ?

**Comment by Viste** [comment]
place totem and try to cast fire nova from a distance of over 30/36 yards If this doesn't work out, it's okay.

**Comment by Viste** [comment]
and btw in issue  has information on how to test

**Comment by Viste** [comment]
```
src/server/scripts/CMakeFiles/scripts.dir/build.make:6159: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/Northrend/VaultOfArchavon/boss_emalon.cpp.o' failed
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Northrend/VaultOfArchavon/boss_emalon.cpp.o] Terminated
CMakeFiles/Makefile2:1199: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Terminated
```
wtf

**Comment by comix1988** [comment]
I tested:
- before the fix the command worked even beyond 40y
- after the fix if the totem is out of range the command doesn't work;
- only one bug: the fire nova also works in LOS. Is it possible to fix it?

tested on Ubuntu 18.04.2 LTS
**on behalf of @maelstromserver**

**Comment by milestorme** [comment]
tested AzerothCore rev. 26ae2ce2d626+ 2019-03-11 21:46:57 +0100 (master branch) (Win64, Release)

can cast fire nova rank 4 from any distance

**Comment by Viste** [comment]
@milestorme I understand the tests were performed without adding a Pull request just on master branch

**Comment by milestorme** [comment]
my bad i'm sorry let me retry this the official way off the wiki

**Comment by milestorme** [comment]
Tested following instruction on wiki fresh pull AzerothCore rev. cc8de64c9631 2019-03-13 18:40:49 +1100 (pr-1566 branch) (Win64, Release) can cast fire totem from any distance

**Comment by Viste** [comment]
plz show your server info to be clear

**Comment by milestorme** [comment]
AzerothCore rev. cc8de64c9631 2019-03-13 18:40:49 +1100 (pr-1566 branch) (Win64, Release)

**Comment by comix1988** [comment]
how many yards have you tested?

**Comment by milestorme** [comment]
100 yards and every cast in between

**Comment by Viste** [comment]
hm its impossible according to code its very simpl and must work in 100% of cases

**Comment by Viste** [comment]
we test this PR with @brussens and fix really don't work and only one thing can make it work and its  #1457
@comix1988 do you have this pr on your server #1457 ?

**Comment by Viste** [comment]
@milestorme can you try use both PRs #1457 and #1566

**Comment by comix1988** [comment]
now i testing the lady's PR at ICC. However I had tested the fire nova on the PR 1566

**Comment by comix1988** [comment]
before fix (master branch):

https://youtu.be/RA8n1oi89FE

after fix (pr-1566 branch):

https://youtu.be/Rh2xB8J55FU

@Viste the fix works but you have to fix the talent of fire nova as shown in the "after fix" video

**Comment by milestorme** [comment]
can confirm on AzerothCore rev. 675dcf78b71f 2019-03-14 14:46:26 +1100 (pr-1566 branch) (Win64, Release) that at 30.02 yards I cannot cast fire nova with searing totem rank 10 down

**Comment by Viste** [comment]
@comix1988 you're just a wizard, thank you very much! i look today on talent

**Pull request merged**
