### PR TITLE
fix(Scripts/Paladin) Infusion of Light proc.

### PR DESCRIPTION
**Pull request by SKingOWN**
## Changes Proposed:
-  Fix infusion of light talent of paladin with sacred shield on does not proc.
-  I only make a PR with change propossed by @PsYchoNauTek in this issue https://github.com/azerothcore/azerothcore-wotlk/issues/11930 

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11930

## Tests Performed:

- Build on Windows 10 and with Visual Studio 2022 
- Run authserver.exe and worldserver.exe OK!
- Test in-game all spells related to the fix and all work propertly.

## How to Test the Changes:

1. Create a Paladin (Levelup to 80) and learn spells.
2. Set talent Infusion of light (53576).
3. Cast Sacred shock (48825) until critic hit.
4. Then cast Sacred Shield (53601).
5. And until Sacred Shield is active cast Beam of light (48785).
6. Then the HoT Beam of light (66922) should be activated.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by PsYchoNauTek** [comment]
thx for making the pr tho! =D

**Comment by SKingOWN** [comment]
@PsYchoNauTek i will build and test it now.

**Comment by SKingOWN** [comment]
I build and tested this and works fine.

**Comment by PsYchoNauTek** [comment]
@SKingOWN, thx for checking it out tho ^.^

**Comment by Meramaf** [comment]
Tested and work correctly. Thanks!

**Comment by Nyeriah** [comment]
Hello,

Firstly, thanks for your PR and thanks @PsYchoNauTek for sharing the fix!
However, please revert the style changes and keep only the new code.

@UltraNix could you review this one? I was looking into this yesterday and this caught my attention: 
image

But there's more to it. I suppose the proc flag may be wrong too

**Comment by SKingOWN** [comment]
The fix works fine, but the best practice would be to fix the original function...
`
void HandleProc(AuraEffect const* aurEff, ProcEventInfo& eventInfo)
`

**Comment by Nyeriah** [comment]
Just trying to understand what the problem was, if it works I have no issues with it 👍

**Comment by PsYchoNauTek** [comment]
> Just trying to understand what the problem was, if it works I have no issues with it 👍

the problem was that the HoT which should apply when u skilled IoL talent with sacred shield + holy shock spell cast did not proc at all.
So I did hire a C++ dev to fix it + share it with the community afterwards =)

**Comment by pklloveyou** [comment]
Wrong pr

**Comment by UltraNix** [comment]
Superseded by #11935

**Pull request closed without merging**
