### PR TITLE
fix(Core/AQ): Rewrite bug trio fight

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Rewrite the whole fight.
-  Add missing spells and mechanics.
-  Fix timers.

## Issues Addressed:

- Closes none?

## SOURCE:

Part of CMangos.
Some guides like [this](https://www.guilded.gg/Hench/groups/Q3mWR6dG/channels/462655b3-5171-4859-9424-f372bd07bb6d/forums/537065352), [this](https://www.icy-veins.com/wow-classic/silithid-royalty-guide-strategy-abilities-loot) or [this](https://us.millenium.gg/guide/7179.html?page=8)
[Wowhead guide](https://classic.wowhead.com/guides/bug-trio-temple-of-ahnqiraj-strategy)

## Tests Performed:

- Tested everything in-game.

## How to Test the Changes:

1. Go to AQ40.
2. Engage Bug Trio.
3. Profit?

## Known Issues and TODO List:

- [ ] There are some things I don't really like how I coded them, but well. I'm open to suggestions.

### CODE REVIEW

**Comment by avarishd** [comment]
merge conflict, https://github.com/azerothcore/azerothcore-wotlk/pull/11596/files#diff-5d8cdf78dfcd1a3f758a87bdec8b5d88f53c8e51d2b8cde9c244526711615b92

Will test tomorrow

**Comment by Nefertumm** [comment]
fixed

**Comment by avarishd** [comment]
.go c 87603 (Vem) 
Tested with 2 characters

- [x] All evade at the corresponding position (couple yards outside of the room)
- [x] Loot is correct for each of the corresponding last boss, tested all 3
- [x] All charge (devour, correctly stop (become passive) any actions while devouring), emotes correctly and heal to full 
- [x] All threat resets work (devour/fear and -80% charge target)
- [x] Princess Yauj spells & (10) adds on death
- [x] Lord Kri spells & cloud on death
- [x] Vem spells & on death, the remaining bosses are enraged (Vengeance) (Also self buffed if he is the last alive)


Extra Stuff:
- [?] They should be marked as "boss phased reset" on evade? - Not sure about this one (I did play classic, but I have no memories of that one), hard to find any VIDEO source of anyone wiping/evading them, can maybe be tested in classic/tbc?

**Comment by Nefertumm** [comment]
@avarishd sure, I know it's pretty hard to find evidence of people wiping to those bosses because I wanted that information too :P So if you can check on TBC or SOM, then go ahead. :)

**Comment by avarishd** [comment]
@Nefertumm I do not play retail/classic anymore so I cannot help further regarding that, but my testing was done with the previous comment, all was good.

**Comment by Nefertumm** [comment]
Oh ok, no worries. Then this is safe to merge, if anything we can investigate further and if we need to, make that change later :)

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
