### PR TITLE
feat(Core/Creature): implement c_t->spell_school_immune_mask

### PR DESCRIPTION
**Pull request by Kitzunu**
* https://github.com/TrinityCore/TrinityCore/commit/ae878e18ef121b7b1960f40f2b0f99debd2155d8

Co-Authored-By: Wyreth <32145860+Wyreth@users.noreply.github.com>

## Changes Proposed:
-  Implement spell_school_immune_mask to allow defining creature spell school immunity in the database
- Port all existing spell_school_immune_mask from Trinitycore

## Issues Addressed:
- Closes 

## Tests Performed:
- Builds
- Tested in-game on all spell schools as shown below
image
image
image
image

## How to Test the Changes:

```cpp
    SPELL_SCHOOL_NORMAL                 = 0, (1 >> 0 = 1)
    SPELL_SCHOOL_HOLY                   = 1, (1 >> 1 = 2)
    SPELL_SCHOOL_FIRE                   = 2, (1 >> 2 = 4)
    SPELL_SCHOOL_NATURE                 = 3, (1 >> 3 = 8)
    SPELL_SCHOOL_FROST                  = 4, (1 >> 4 = 16)
    SPELL_SCHOOL_SHADOW                 = 5, (1 >> 5 = 32)
    SPELL_SCHOOL_ARCANE                 = 6  (1 >> 6 = 64)
```

Easily tested with this:
```sql
-- REMEMBER TO UNDO THIS AFTER TESTING AS THIS MOB SHOULD NOT BE IMMUNE TO THIS
UPDATE `creature_template` SET `spell_school_immune_mask`=`spell_school_immune_mask`|1|2|4|8|16|32|64 WHERE `entry` = 299;
```
1. .go c id 299
2. Test casting spells with the different schools. (HOLY, FIRE, NATURE, FROST, SHADOW, ARCANE | NORMAL is Physical damage)

## Known Issues and TODO List:

- [ ] 
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
just curious, how was it done before this pr?

**Comment by Kitzunu** [comment]
It wasnt

**Comment by 55Honey** [comment]
Tested and proven working for all schools.
Including effects like Thorns, Entangling Roots, Hibernate, Soothen Animal, etc. All abilities result in "immune".

**Review by Helias — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
