### PR TITLE
fix(DB/creature_template): Resistances for creatures level 21-30

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Align creature resistances for levels 21-30 with vmangos

## Issues Addressed:
- Hopefully the vmangos data for these creatures is better

## Tests Performed:
- Looked at numbers to be changed, it could make sense
- Applied SQL
- Not tested in game

## How to Test the Changes:

- `.go c id <any entry id from the SQL>`
- Check combat log, use appropriate spells

## Known Issues and TODO List:

- The SQL looks like it does since I created it using code... Not super pretty, but the intention is showing in a fairly easy to read manner, exactly what will change.
- I prefer to segment these changes, if they are interesting, into ~10 level PR's going forward, not to swamp any reviewers with possibly hundreds of creatures at once

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by T1ti** [comment]
the baron aquanis change looks weird, remove his frost resist and give him 140 arcane resistance ? he's a water elemental.
his resistance is shown in the book
image

image
aku'mai deosn't have any resistance in the book, he's a boss so I assume if he had any, it would be displayed

**Comment by T1ti** [comment]
image
This one was also correct

He's the resistance for the water elementals

**Comment by Si1ker** [comment]
Same here as https://github.com/azerothcore/azerothcore-wotlk/pull/4753#issuecomment-792361937

**Comment by Zoidwaffle** [comment]
@T1ti : yeah, the Aquanis one did seem a bit weird. It was correct the way it was, the new changes have been removed.

Aku'mai updated as well (aka removed).

Updated 2 elementals - going to bed, will check if I missed more from your book tomorrow.

**Comment by Zoidwaffle** [comment]
So are the suggested changes looking fine or not?

**Review by FrancescoBorzi — APPROVED** [review]
codestyle looks good, waiting to be tested

**Comment by Zoidwaffle** [comment]
@T1ti : are you happy with the current version? All your suggestions should have been handled.

Not sure how much testing is needed - I mean, we can test the mobs, but what value do we get from it? The list of changes is rather short and only 2 mobs should have a noticeable change.

The changes should not be game-breaking... The only big chance is 2 elementals getting some fire resistance. In case it turns out to be wrong, it can be tweaked easily.

I would like to change the status to "To be merged" if there are no objections.

**Comment by T1ti** [comment]
looks good to me

**Comment by Helias** [comment]
This PR is outdated, you need to use creature_template_resistence now.
I can't test it in the last azerothcore db

**Comment by Zoidwaffle** [comment]
@helias: My RL is interfering massively with my online presence at the moment. I hope to get more time soon, then I will fix it (without having looked into it, I guess the change to make here is trivial).

**Comment by Eldarix** [comment]
I don't know what may have failed but despite applying the changes the npc's that I have tested still have resistance:

WoWScrnShot_052821_212943
WoWScrnShot_052821_213128
WoWScrnShot_052821_213239

**Comment by FrancescoBorzi** [comment]
@Eldarix thanks for your feedback.

@Zoidwaffle can you please check it again?

**Comment by Kitzunu** [comment]
Will close due to inactivity and creature_template has been reworked enough that these queries won't work

**Pull request closed without merging**
