### PR TITLE
[WIP] move hardcoded eng text and gossips to DB from Core in Ulduar

### LINKED ISSUE #570: Core/Script: Hardcoded gossips & text in Ulduar
**Description**:

we have some hardcode in ulduar texts and gossips

**Current behaviour**:  All in english and its make me sad

**Expected behaviour**:   all text and gossips must be in DB and translateble

**Steps to reproduce the problem**:

1.  go to src\scripts\Northrend\Ulduar\Ulduar
2.  open some files
3.  see hardcoded english test and Upset

**Branch(es)**: 0.x / 1.x / master (Specify the branch(es) affected by this issue) 

master

**AC hash/commit**:  

 0dd68df

**Operating system**:  

Linux (doesn't metter here)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/48446484-core-script-hardcoded-gossips-text-in-ulduar?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Viste**
**Changes proposed:**

-  This PR done for move all hardcoded text and gossips from core to DB

**Target branch(es):** 1.x/2.x etc.

master

**Issues addressed:** Closes #570 

**Tests performed:** (Does it build, tested in-game, etc)

No test now just start this becouse i have free time and need do something for people sometimes

**Known issues and TODO list:**

- [need make SQL, drop anather code many things in to do for now ]

### CODE REVIEW

**Comment by Inifield** [comment]
Why would you remove it ? if you want to translate just translate the text don't need to remove everything

**Comment by Viste** [comment]
@Inifield  WIP status of PR can say you i'm not done, plz w8 and you see why

**Comment by Viste** [comment]
@Inifield now you happy ?

**Comment by Yehonal** [comment]
Is it still in wip? or can be considered completed?

if yes i can pull on staging branch to be tested on demo server

**Comment by Viste** [comment]
@Yehonal you can test  auriaya and portal work for now later i add other bosses and npc so its still wip about whole ulduar instance.

**Comment by Yehonal** [comment]
Would be better to complete it before in this way we can test at one shot. Otherwise open multiple PR if you prefere we merge it gradually

**Comment by HeartWell** [comment]
Ах ты проказник)

**Comment by Viste** [comment]
soon will be update

**Comment by Yehonal** [comment]
Please merge updates from master branch, we need to run a travis build to check about warnings.

**Comment by Viste** [comment]
@Yehonal done

**Comment by Yehonal** [comment]
travis is quite buggy lately, after my commit it has been compiled without errors but the check says that the build failed..

However remember the indendation @Viste

**Comment by Viste** [comment]
@Yehonal sorry i update my notepad and with update broke tab to 4space changing

**Comment by Yehonal** [comment]
will be reopened when finished

**Pull request closed without merging**
