### PR TITLE
fix(scripts/Steamvault): Switch Mekgineer Steamrigger's enrage to Heroic mode only

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
- Change (5min) enrage timer to Heroic only (see source)

(The difficulty increment in heroic for summons is that besides de HP checks, there's an additional summon every 15s-24s)

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5790

## SOURCE:

https://wowwiki-archive.fandom.com/wiki/Mekgineer_Steamrigger
&
image
&
image

## Tests Performed:

- Tested

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Adds are summoned on a timer in Heroic, we saw it in retail

**Comment by Si1ker** [comment]
@Gultask in this timer? (15600ms - 25400ms)

**Comment by Gultask** [comment]
yeah that's what I found. I based it off the timestamps between each cast of the summon spells.
I thought it was weird too, almost fixed it as well shortly before Heroics came out because I had forgotten about it

**Comment by Si1ker** [comment]
> yeah that's what I found. I based it off the timestamps between each cast of the summon spells. I thought it was weird too, almost fixed it as well shortly before Heroics came out because I had forgotten about it

Judging by common sense, all timers in Heroic would be on that timer.
It seems impossible in Heroic it only has 1 summon on that timer, this makes it way easier than normal.
Sounds about right?

**Comment by Si1ker** [comment]
`Gnome Repairers: A few times during the fight at 75%, 50% and 25% health, he will call upon 3-4 gnomes to heal him. These gnomes have 5k hp and deal 200-500 melee damage on hit. These are non-elite mobs and should receive all focus from DPS, to prevent boss from healing. The healing is a channeled spell which break on damage, and after it has been broken the gnome will start it again after a few seconds, so keep the DPS up.`
.
.
Heroic Mode
Steamrigger in heroic mode is almost identical to normal mode, **except that an extra gnome appears** every 7 seconds or so. So DPS need to burn it down in addition to the normal 3 spawn that comes when Steamrigger announces "Tune em' up boys!". The tank can Thunderclap to interrupt heals temporarily, but the gnomes quickly switch back to healing so it only buys 3-4 seconds at most. Druid tanks can use swipe to prevent healing until dps can pick up the gnomes. Priests should Fear gnomes that are beating on clothies when possible.

**Comment by Si1ker** [comment]
When I read "heroic" and "adds" definitely something seems off with that 1 add per timer ..  so the approach proposed here have much more sense.

image

**Comment by Gultask** [comment]
https://youtu.be/n4v6l2oyahQ?t=1772
Check the video, only around 3 mechanics spawn during the fight

**Comment by Si1ker** [comment]
> https://youtu.be/n4v6l2oyahQ?t=1772 Check the video, only around 3 mechanics spawn during the fight

Weird, but undeniable. 🤔
Also confirmed it [in this vid as well](https://youtu.be/4yGmX_YrMck?t=1424)

I don't think there's a video for the enrage timer of 5min happening only in Heroic so we rely on wowheadComments/Guides that mention that's the behavior? changing...

**Comment by balleny** [comment]
from https://wowwiki-archive.fandom.com/wiki/Mekgineer_Steamrigger

> Steamrigger in [heroic mode](https://wowwiki-archive.fandom.com/wiki/Heroic_mode) is almost identical to normal mode, except that an extra gnome appears every 7 seconds or so.

boss should summon adds every 25% AND time based adds on top.

**Comment by Nyeriah** [comment]
Best if we check it on retail to be sure if we haven’t already

**Comment by Si1ker** [comment]
> > https://youtu.be/n4v6l2oyahQ?t=1772 Check the video, only around 3 mechanics spawn during the fight
> 
> Weird, but undeniable. 🤔 Also confirmed it [in this vid as well](https://youtu.be/4yGmX_YrMck?t=1424)
> 
> I don't think there's a video for the enrage timer of 5min happening only in Heroic so we rely on wowheadComments/Guides that mention that's the behavior? changing...

@Gultask  ?

**Comment by Gultask** [comment]
5 minutos
image

**Comment by balleny** [comment]
looking into videos
https://www.youtube.com/watch?v=CS1QdwH1aKE
and similar on youtube, there is indeed only 1 add spawning every now and then. no percentage based spawns

**Pull request closed without merging**
