### PR TITLE
MMAP: Build ADT floor just like WMO floor below liquid

### PR DESCRIPTION
**Pull request by killerwife**
https://github.com/TrinityCore/TrinityCore/pull/27503

I am the author, so any cross posting licensing issues dont apply.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by killerwife** [comment]
Testing: Use recast demo or any other tool to visualize ocean floors for example in stranglethorn before and after. Ingame, try to use pathing in water before and after. Warning, slope extraction might need to be adjusted going forward, but that is not the topic of this PR.

**Comment by FrancescoBorzi** [comment]
Please note that mmaps need to be re-extracted

**Comment by pklloveyou** [comment]
Tested

**Comment by Kitzunu** [comment]
Thank you for your contribution =)

**Comment by FrancescoBorzi** [comment]
> Please note that mmaps need to be re-extracted

@Kitzunu will you take care of re-extracting the data?

**Comment by Kitzunu** [comment]
If we wanted to force an mmap update, the mmap version shouldve been updated.

Anyhow, I will see if I can fire up my extractor

**Comment by r-o-b-o-t-o** [comment]
Extracted data can be downloaded from https://github.com/wowgaming/client-data/releases/tag/v13

**Pull request merged**
