### PR TITLE
fix(Core/Spells): Dungeon and world bosses are always subject to spel…

### LINKED ISSUE #9633: Shaman's Wind Shear doesn't apply "preventing any spell in that school from being cast" aura
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2541

Wind Shear does not lock a NPC out of a school of magic for 2 seconds.  This seems to be widespread on several NPCs I have encountered since leveling in the last few weeks.  I cannot even count the number of times since level 16 that this has happened, everyday I have to re-read the tooltip and never recall the ability working as it does at this moment.

Example.  Instructor Malicia has Renew, Flash Heal, and Heal.  These all share the same school of magic, yet after using a Wind Shear she is capable of instantly switching to one of the other spells from the same school.

Tester:

The issue is confirmed. Shaman's [Wind Shear](https://wowgaming.altervista.org/aowow/?spell=57994) doesn't apply "preventing any spell in that school from being cast" aura

https://user-images.githubusercontent.com/85256266/145583874-529dfb0b-dbdc-4e06-a1d9-cbd5a11b21b6.mp4

### Expected Blizzlike Behaviour

Wind Shear is suppose to preventing any spell in that school from being cast

### Source
Description of the spell
> Instantly blasts the target with a gust of wind, causing no damage but interrupting spellcasting and preventing any spell in that school from being cast for 2 sec. Also lowers your threat, making the enemy less likely to attack you. 

Wowpedia https://wowpedia.fandom.com/wiki/Wind_Shear?oldid=2185096

### Steps to reproduce the problem

idk how to test it with one character
.cast 5176 - 1st character
.cast 57994 on 2nd character while 1st is casting
.cast 5176 - after interrupt on 1st character

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/0300cef119ea1708f26ab1519d46c652410b414f

### Operating system

Windows 11

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…l school lockouts.

Fixes #9633

## Issues Addressed:

- Closes #9633
- Closes https://github.com/chromiecraft/chromiecraft/issues/2541

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/9633)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
Shouldn't title be "Creatures are always subject to spell school lockouts" instead of dungeon and world bosses?

**Comment by claudiodfc** [comment]
Also will this work on players too since the change is on creature class?

**Comment by UltraNix** [comment]
The PR is about bosses in dungeons, because normal creatures were okay. 
The problem was about creatures, not players.

**Comment by claudiodfc** [comment]
I understand, is just that the first issue your closing is not about prevention on creatures, but on a duel.

**Comment by UltraNix** [comment]
That test is not valid. For players, lockout works only for spells from spellbook, not casted by command.

**Comment by claudiodfc** [comment]
#### Test case
- .go c id 10505 (**Instructor Malicia**)
- .damage 30000
- Wind Sheer Heal or Flash heal effectively applies spell lockout.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
