### PR TITLE
add a config file: modules/config.cmake.dist

### PR DESCRIPTION
**Pull request by AyaseCore**
##### CHANGES PROPOSED:
Add a config file: modules/config.cmake.dist
Modules can be simply enabled or disabled.

###### ISSUES ADDRESSED:

Closes  none

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Hehe, thanks, that was fast. I will test it soon

**Comment by BarbzYHOOL** [comment]
Working but there are missing details when using cmake:

```* Build world/auth       : Yes (default)
* Build with scripts     : Yes (default)
* Build map/vmap tools   : No  (default)
* Build core w/PCH       : No
* Build scripts w/PCH    : No
* Show compile-warnings  : No  (default)
* Use coreside debug     : Yes
* Use unix gperftools     : No  (default)
* Use GIT revision hash  : Yes
* Enable extra features    : Yes (default)
* Enable vmap DisableMgr checks    : Yes (default)
* Enable extra logging functions    : Yes
```

See, no "Disable modules" output

**Comment by AyaseCore** [comment]
I didn't realize I needed to add a detail description. I'll add it after work.

**Comment by Winfidonarleyan** [comment]
@AyaseCore Good idea. Good work.
@BarbzYHOOL says about the file
[../showoptions.cmake](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/cmake/showoptions.cmake)

``` cmake
if(DISABLE_MODULES)
  message("* Disable all module      : Yes")
else()
  message("* Disable all module      : No (default)")
endif()
```

**Comment by BarbzYHOOL** [comment]
@Winfidonarleyan I guess you inverted the @ xD but thank you for the file link, ayase can add it now and it saves us time!!

**Comment by Yehonal** [comment]
Why don t use DISABLED_AC_MODULES instead. It supporta regex formula so you could use:
-DDISABLED_AC_MODULES=".*"

It should work. Maybe we have just to document it

**Comment by BarbzYHOOL** [comment]
@Yehonal we used this as a base......................... https://github.com/azerothcore/azerothcore-wotlk/blob/master/conf/config.cmake.dist

**Comment by AyaseCore** [comment]
`DISABLED_AC_MODULES=".*"` is not work.
```
    if (";${DISABLED_AC_MODULES};" MATCHES ";${MODULENAME};")
       continue()
    endif()
```
DISABLED_AC_MODULES is the string to be matched.

@Yehonal

**Comment by Yehonal** [comment]
Ok so it should be inverted :) nice catch

Il Gio 26 Lug 2018, 16:42 ayase <notifications@github.com> ha scritto:

**Comment by BarbzYHOOL** [comment]
Tell us where to document it and how :P

**Comment by AyaseCore** [comment]
I rewrote it.
added a `config.cmake.dist`.
It can simply enable or disable modules.
The work is good at present.
image

Review it if you have time.
@Yehonal 
@BarbzYHOOL

**Comment by talamortis** [comment]
Got to say this looks like a great idea! @AyaseCore well done.

**Comment by Nefertumm** [comment]
Any reason to not merge this?

**Comment by BarbzYHOOL** [comment]
I don't remember how to test and ayase didn't put the steps on how to test :'(

**Comment by FrancescoBorzi** [comment]
any updates on this? can anyone point what needs to be tested?

**Comment by AyaseCore** [comment]
I have been busy recently. I haven't paid attention to it for a long time.
Resolved merge conflict. 

About how to use it:
1.copy and rename  `config.cmake.dist`  to  `config.cmake`.
2.edit it.
3.cmake again.

If use cmake-gui. change `set (DISPLAY_CMAKE_GUI_OPTION 1)`
This makes it easier to enable or disable modules
image

@BarbzYHOOL  @FrancescoBorzi

**Comment by FrancescoBorzi** [comment]
@AyaseCore thanks a lot.

Can anyone test this? Possibly on a different platform (e.g. on Linux)

**Comment by AyaseCore** [comment]
> @AyaseCore thanks a lot.
> 
> Can anyone test this? Possibly on a different platform (e.g. on Linux)

I didn't test it on Linux, but it should be ok.

**Comment by BarbzYHOOL** [comment]
I will test it

**Comment by FrancescoBorzi** [comment]
any news on this?

**Comment by comix1988** [comment]
How can I test this PR?

**Comment by BarbzYHOOL** [comment]
@comix1988 https://github.com/azerothcore/azerothcore-wotlk/pull/985#issuecomment-449583431 note that i will try it as soon as i finished my stuff, it's on my to do list but if you test it before me, it's cool :P

**Comment by comix1988** [comment]
sorry @BarbzYHOOL , I don't know Cmake

**Comment by Winfidonarleyan** [comment]
Very good PR, but it needs to be completed before the end, and I will do it

**Comment by BarbzYHOOL** [comment]
@Winfidonarleyan alright, i wanna test this now (finally), do I need to wait for something to be fixed?

**Comment by BarbzYHOOL** [comment]
ok this is working, i'm gonna update it soon

**Comment by Yehonal** [comment]
Module folder MUST NOT contain any file in its root, it's against our directory structure standard. Configuration files must be placed under /conf/

However, we already have a similar feature: 

https://github.com/azerothcore/azerothcore-wotlk/blob/master/conf/config.sh.dist#L49

its a CMAKE def (CDISABLED_AC_MODULES). Here you are the commit: https://github.com/azerothcore/azerothcore-wotlk/commit/603753dfff93f8eb0560d8f2951cd15139cdd70b

So, maybe you should improve the already existing system and use the correct folder

**Comment by BarbzYHOOL** [comment]
the file you point to is a BASH file, if we don't use your BASH script we miss this option

**Comment by BarbzYHOOL** [comment]
What if I move most of the code in that file to `/conf/config.cmake.dist` ? should be fine no?

**Comment by Yehonal** [comment]
> What if I move most of the code in that file to `/conf/config.cmake.dist` ? should be fine no?

I've already discussed it before (1 year ago?), https://github.com/azerothcore/azerothcore-wotlk/pull/985#issuecomment-408002137 , the issue with DISABLED_AC_MODULES was that the condition must be reverted 

from ";${DISABLED_AC_MODULES};" MATCHES ";${MODULENAME};" to 
";${MODULENAME};" MATCHES ";${DISABLED_AC_MODULES};"

BTW, you have to move your implementation under /conf/ ofc

**Comment by BarbzYHOOL** [comment]
sorry i don't understand but i'll check lol

**Comment by BarbzYHOOL** [comment]
what the fuck happened?? I updated the core and pulled the PR, then I edited it and pushed to AyaseCore's repo

now it lists all changes made during 1 year

I don't really get it, it should only compare to the actual master which is identic apart from 2 files

Anyway it was just a small improvement over the original PR, not the fix Yehonal wanted.
It can be reverted ofc but I wanted to add it before it's being reworked entirely

**Comment by BarbzYHOOL** [comment]
@Yehonal I tried your -DDISABLED_MODULES and it works fine BUT not the regex, I tried with `-DDISABLED_MODULES=*` or `-DDISABLED_MODULES=mod-*` but it loads all the modules and tries to compile them

**Comment by BarbzYHOOL** [comment]
ok i fixed my shit but still we need to take what is good in this PR (the ideas mostly like an option to disable ALL modules at once, and info in cmake on what is getting disabled) and include it in yehonal's solution

**Comment by FrancescoBorzi** [comment]
please solve the conflicts

**Comment by BarbzYHOOL** [comment]
> please solve the conflicts

no, not needed, this pr will be discarded, needs to be redone as we said above

(also last time i tried to add all the newer commits, it completely fucked up, dunno why)

**Comment by Kitzunu** [comment]
> > please solve the conflicts
> 
> no, not needed, this pr will be discarded, needs to be redone as we said above
> 
> (also last time i tried to add all the newer commits, it completely fucked up, dunno why)

Any news on this or is it going to be discarded and can be closed?

**Comment by BarbzYHOOL** [comment]
we only need to add more output to the actual system, in the console, functionality wise it's good enough

**Comment by BarbzYHOOL** [comment]
@yehonal the -DDISABLED_AC_MODULES=".*" doesn't work, when used, then it doesn't compile at all

**Pull request closed without merging**
