### PR TITLE
Fix water blink

### PR DESCRIPTION
**Pull request by jestermaniac**
## Changes Proposed:

aye whas poppin

water problem: TC don't be havin this issue cuz they be using v15 mmaps while AC is still 12. in mmaps v15 seems like the poly extends to water as well? cuz when i wuz debuggin here```PathGenerator::BuildPolyPath``` i had mad low values for ```distToStartPoly``` and ```distToEndPoly``` while AC wuz getting the distance from the terrain under the water (this i proven cuz the futher i went from terrain under water the larger the dist to nearest poly became) hence big ass values.

with mmaps 12 tho which is wut we stuck with rn to fix it i had to treat in water cases (but not necessarily underwater, matter of fact there's no prob underwater blinking) like underwater and not let mmaps fuck me over and get me a nice ass shortcut built for me aye word

this fixes also behaviour that u see in da vid here

https://streamable.com/otm2u1

it would prolly be better to update mmaps to v15 u dig btw.

falling problem: aye lemme start with saying TC got same problem. so in the original issue they be saying that yo ass should always, when u falling, land safely on ground (?) but ppl here say otherwise https://github.com/SunstriderEmu/BugTracker/issues/1443

they basically be saying u should tp to ground if there are only 40yds between start position and the ground (perpendicular distance along the Z axis). idk what to do here tbh.

the problem btw is the fact that you're not getting tp upwards, rather the poly build fails and tp back where u started. this be from the fact that the core builds an invalid poly or that he builds a valid one but the Z can't be calculated correctly cuz of invalid grid height and errythang fails.

what I did to patch up this bitch up a lil is for the spells with implicit target ```TARGET_DEST_CASTER_FRONT_LEAP``` (from dbc there are only 2: blink and netherstep) to set the Z axis on ground level if ```MovePositionToFirstCollision``` failed. 

this doesn't work always tho as it fails to catch all cases. in some places when he tryna get the height of the grid , given x and y for the player, the height returned is invalid. idk gotta get me some time to study more how this shit works tho maybe upgrading mmaps/vmaps etc we get better results

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6427
- Closes https://github.com/chromiecraft/chromiecraft/issues/1550
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7571

## Tests Performed:

- tried locally 

## How to Test the Changes:

1. blink in or under water
2. jump from some high ass place

## Known Issues and TODO List:

- decide wut we finna do bout jumping from high places and find a way to get consistent height from grids given x,y as input

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
Need check instances

**Comment by jestermaniac** [comment]
> 
> 
> Need check instances

no clue wut that meanz

**Comment by FrancescoBorzi** [comment]
> > Need check instances
> 
> no clue wut that meanz

@Winfidonarleyan care to explain? :D

**Comment by Winfidonarleyan** [comment]
> > > Need check instances
> > 
> > no clue wut that meanz
> 
> @Winfidonarleyan care to explain? :D

Need test this pr with players

**Review by UltraNix — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers can anyone please have a look at this? it has been waiting for 20 days....

**Comment by IntelligentQuantum** [comment]
@FrancescoBorzi Can you add this PR to chromiecraft?

**Comment by jamadaha** [comment]
**Tested**

- [X] Floating in water | **Works as expected**
- [ ] Standing on water (I.e. waterwalking) | **Not working**
    - If no ground is close, nothing happens. If ground is nearby you blink onto the ground e.g. if on the coast you blink underwater onto the seafloor
- [ ] Running on water (with waterwalking) | **Not working**
    - Teleports backwards
- [X] Underwater | **Works as expected**
- [ ] Falling over water | **Not working**
     - Teleports down into the water, in a floating position
- [ ] Falling over ground | **Not working**
    - Teleports onto the ground (If you're high enough, it actually initiates a loading screen)

**Doesn't seem to be working correctly**

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi Can you add this PR to chromiecraft?

typically we don't add stuff there which hasn't been merged to AC master first, unless there is a special reason for

why do we need this sooner than merging?

**Comment by jestermaniac** [comment]
imma try and work on waterwarlkin blink soon as i already knew it didnt work. matter of fact this pr was mainly to fix blinking when u floatin and to fix mob chasin u in water. bout falling + blink we gotta first decide wassup imo and maybe someone that knows balls deep bout maps can help us out understand why we can't get Z consistently given arbitrary x and y

**Comment by jestermaniac** [comment]
aye so got some more changes going. waterwalking should be gucci i think. decided that for poly building in water we always fucking with shortcuts as we dont have poly to hold onto and just make everything easier.

bout falling i managed to get consistent Z to go balls deep in the search in the grid to avoid getting invalid heights from holes in the grid. since nobody gave a fuck about what i wrote about falling + blink above i decided to follow what beings told here since there's video proof https://github.com/SunstriderEmu/BugTracker/issues/1443

imo we gucci but we better get this whole shit tested well b4 doin anythang else fr

**Comment by FrancescoBorzi** [comment]
@jestermaniac what's the status of this PR?

**Comment by jestermaniac** [comment]
waitin for someone to review/test.

but i guess someone should check if this pr is obsolete cuz of this

https://github.com/azerothcore/azerothcore-wotlk/pull/9124
https://github.com/azerothcore/azerothcore-wotlk/pull/8775
https://github.com/azerothcore/azerothcore-wotlk/pull/8692

**Comment by acidmanifesto** [comment]
> waitin for someone to review/test.
> 
> but i guess someone should check if this pr is obsolete cuz of this
> 
> #9124 #8775 #8692

i can only speak for my commit of #8775, we need newer vmaps and mmaps which is another pr before we can confirm anything water related with blink on mines.

**Comment by sschepens** [comment]
I can confirm that water blinking seems to works as intended with #9124 so this is probably not necessary

**Comment by FrancescoBorzi** [comment]
> I can confirm that water blinking seems to works as intended with #9124 so this is probably not necessary

ok then closing this, we can reopen if needed

**Comment by CMHWoody** [comment]
The history on this suggests that @sschepens confirmed that water blinking seems to be working, however, I just rolled a mage and when swimming across the surface of the water, blink moves you forward, however it puts you down on the ground at the bottom of the body of water.  Given the dates on all these issues, I would think the fixes would be in place by now, yet this specific issue does not seem to be fixed as of yet.

**Pull request closed without merging**
