### PR TITLE
feat(Core/Network): Add conf to allow/disallow storing IP address

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/68bf7e6d12e1689d688db32c05066b8832922c67)

Co-Authored-By: Giacomo Pozzoni <giacomopoz@gmail.com>

## Changes Proposed:
- Conf to allow/disallow storing IP for those that don't need it, or for GDPR reasons  

## Tests Performed:

- Tested

## How to Test the Changes:

1. Check if it stores IP or 0.0.0.0

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Kitzunu codestyle failing

**Comment by Kitzunu** [comment]
fixed

**Comment by Helias** [comment]
still failing :S

**Comment by Kitzunu** [comment]
Now

**Comment by Shybuia** [comment]
🟥 Tested:

1. Prepared changes using guide [https://www.azerothcore.org/wiki/how-to-test-a-pr](url)
2. Used dashboard to compile ./acore compiler all
3. Updated new authserver.conf and worldserver.conf cp env/dist/etc/authserver.conf.dist env/dist/etc/authserver.conf cp env/dist/etc/worldserver.conf.dist env/dist/etc/worldserver.conf
4. Restarted auth session and world session
5. Relogged
6. Saw IP due to default setting of AllowLoggingIPAddressesInDatabase = 1
7. Changed authserver.conf AllowLoggingIPAddressesInDatabase = 0
8. Restarted auth session and world session
9. Relogged
10. Didn't see any change in DB
11. I was questioning myself if I restarted everything properly, so I just restarted VM to be sure 
12. Relogged
13. Didn't see any change in DB

DB Table acore_auth.account with option: 
AllowLoggingIPAddressesInDatabase = 1
image
DB Table acore_auth.account with option: 
AllowLoggingIPAddressesInDatabase = 0
image

**Comment by Kitzunu** [comment]
Well last attempt is currently wrapped in an if statement, so it doesn't even get checked if you use the config.

If you feel like it should also be 0.0.0.0 then I can change that. It's up to you, for me either is good enough

**Comment by Shybuia** [comment]
Well, I'm not an expert to gdpr/privacy things but I assumed that all ips will be set to 0.0.0.0 since that is also kind of "leftover" about the player connection info. Anyone elses opinion here is welcomed

**Comment by Kitzunu** [comment]
will fix =)

**Comment by Kitzunu** [comment]
Try now

**Comment by Shybuia** [comment]
@Kitzunu since I test under Ubuntu, builds for it need to pass first ... thanks

**Comment by Kitzunu** [comment]
I will fix build either tomorrow or the next day

**Comment by Kitzunu** [comment]
fixed

**Comment by Kitzunu** [comment]
@Shybuia could you test again

**Comment by Shybuia** [comment]
Passed, good job @Kitzunu 

✅ 
AllowLoggingIPAddressesInDatabase = 0
image
✅ 
AllowLoggingIPAddressesInDatabase = 1
image

**Pull request merged**
