### PR TITLE
fix(DB/questpoi): 7321 - Soothing Turtle Bisque - correct POI for Horde

### PR DESCRIPTION
**Pull request by wowquester**
This fixes POI area for 7321 which shares it with the 555 (alliance version) which has the correct ones. Please beware of my MySQL skill, although it fixes the problem, I encourage you to review this code and if necessarry, make it more compact. The basic idea is just to duplicate entries from 555 to 7321 - this results in correct behavior of the quest poi on the world map.
PS:(I am VERY new to the world of fixing things... please be nice and if anything, try to explain it a as would to a small child.)

## Changes Proposed:
-  Corrected POI behavior for Horde side (Q7321)
- 

## Issues Addressed:

- [Closes](https://github.com/azerothcore/azerothcore-wotlk/issues/9550)

## SOURCE:

It's the same cooking quest - shares location, task and creatures, Aliance verions works as expected, see https://github.com/azerothcore/azerothcore-wotlk/issues/9550

## Tests Performed:

Horde
WoWScrnShot_070923_104341
Ali
WoWScrnShot_070923_104346
Horde only
WoWScrnShot_070923_104358
Previous behavior (the misplaced is the original state)
https://user-images.githubusercontent.com/85256266/145011607-dbd5ba12-6555-483c-9562-31a2f2a9d03b.jpg
- 

## How to Test the Changes:

1. .go tax 13
2. .q add 7321 (Horde)
3. .q add 555 (Alliance)
4. Compare them

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
This needs to be sniffed

**Comment by elthehablo** [comment]
Bench already explained to you that this is a "hack-fix", and that goes against the AC principle especially for low priority issues like this. So someone needs to sniff the POIs and then make this PR.

**Comment by wowquester** [comment]
> Bench already explained to you that this is a "hack-fix", and that goes against the AC principle especially for low priority issues like this. So someone needs to sniff the POIs and then make this PR.

Ah, sorry about that. I thought that hack-fix means it's undoable...

**Comment by elthehablo** [comment]
> > Bench already explained to you that this is a "hack-fix", and that goes against the AC principle especially for low priority issues like this. So someone needs to sniff the POIs and then make this PR.
> 
> Ah, sorry about that. I thought that hack-fix means it's undoable... 

Hack-fix means that the fix does relieve the problem somewhat, but it is not the way it should work. The way it should work usually being the way it is implemented on classic servers. The end-goal of AC is to be very close to that. Thanks for the contribution though and keep it up :)

**Comment by Gultask** [comment]
> This needs to be sniffed

Impossible for now. I'm in the mind now that it's ok to guess/approximate as long as there's an issue clearly stating that this needs to be sniffed later. I'll wait for some more opinions, though.

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
