### PR TITLE
fix(Scripts/AqhQiraj): Increased aggro range for Moam.

### LINKED ISSUE #12901: [AQ20] Aggro range issue with some bosses
### Current Behaviour

Low aggro range for Ossirian and Moam

### Expected Blizzlike Behaviour

They should have a big aggro range (around 50y as Kurinaxx)

### Source

Ossirian: https://youtu.be/tu99VfdupMg?t=1238

Moam: https://youtu.be/u1D35z0iHrI?t=12

### Steps to reproduce the problem

1. Engage these bosses

### Extra Notes

_No response_

### AC rev. hash/commit

[27d0086](https://github.com/azerothcore/azerothcore-wotlk/commit/27d0086b8c1f0a844aeb2f733f5699b21717019f)

### Operating system

Windows 11 Pro

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12901

## Issues Addressed:

- Closes #12901

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Engage these bosses from >30y range.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
@UltraNix I tested and doesn't work for ossirian. Before to create the issue, I was apply the same thing but even if I get the yell in the stair the boss is not pull. Maybe the aggro system work only in 2D space ?

**Comment by UltraNix** [comment]
Aggro system works in 2D if mob is not flying.

**Comment by Maelthyrr** [comment]
Yes that what I was thinking. But as we can see on several videos, the boss is aggro when players are in stairs and not on the top of stairs.

**Comment by UltraNix** [comment]
@Maelthyrr Problem here with Ossirian is that he's not in LoS with players. Do we have video from retail that he aggroes on players at the bottom of the stairs?

**Comment by Maelthyrr** [comment]
From classic another: https://www.youtube.com/watch?v=v8KrCk9iujw

From old retail: https://www.youtube.com/watch?v=XVtfW9cNIa0
https://www.youtube.com/watch?v=IJIQ-ohWXEE
https://www.youtube.com/watch?v=8xPDQl9m86E

The system seems have been change a little since classic and retail. But on the behavior, it's maybe not a "pull". But an event where the boss go down to be in LoS of players. I will look with gulthask to check this on woltk classic.

**Comment by UltraNix** [comment]
@Maelthyrr If you can, try cast some spells on him with long range (if any) from different spots on the stairs to see if it is in LoS with you.

**Comment by Maelthyrr** [comment]
Talk with Gultask, during these AQ20 sniff he can pull him only at the top on stair. No areatigger, or other mechanic in the sniffs. So let Ossirian like this and only touch moam. On videos, he is probably pull  by a spell or a weapon as crossbow.

**Comment by UltraNix** [comment]
@Maelthyrr Done.

**Comment by Maelthyrr** [comment]
@UltraNix maybe just update the title to remove ossirian

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
