### PR TITLE
Core/Creature: Localization creatures.

### PR DESCRIPTION
**Pull request by HeartWell**
**Changes proposed:**

-  Adding localization creature_template_locale.

**Target branch(es):** 1.x.

**Issues addressed:** Closes #https://github.com/azerothcore/azerothcore-wotlk/issues/207

**Tests performed:** (Does it build, tested in-game, etc)

- Tested and working

### CODE REVIEW

**Comment by sucofog** [comment]
Testing tomorrow to give feedback, but Im pretty sure it works ;D

**Comment by sucofog** [comment]
========== Compilar: 16 correctos, 0 incorrectos, 0 actualizados, 0 omitidos ==========
Compile perfect

**Comment by sucofog** [comment]
Test done @HeartWell perfect job.

https://files.gitter.im/azerothcore/azerothcore/6odF/blob

**Comment by cooler-SAI** [comment]
agreed! all works good

**Pull request merged**
