### PR TITLE
Fix PR #3001

### PR DESCRIPTION
**Pull request by Mitradis**
Fix PR https://github.com/azerothcore/azerothcore-wotlk/pull/3001

Becouse this option in fact not work.

see https://github.com/azerothcore/azerothcore-wotlk/issues/2830

## CHANGES PROPOSED:
-  
-  

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
-
-

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Mitradis thanks for the PR! Please add the missing information: `TESTS PERFORMED`, `HOW TO TEST THE CHANGES`, etc...

**Comment by Kitzunu** [comment]
I tested this when I made that PR and what I concluded is that what I did worked and this did not work.
So please do as shin asked and fill out the template so I can test this again

**Comment by Mitradis** [comment]
that's why i don't do PRs, i have my corepatch with fixes. I will not prove anything to anyone i hate it.

Kitzunu you PR not work if use Debug.Battleground = 1 and you try go to BGs nothing will come of it. Becouse BattlegroundMgr.cpp will not miss you. Plz, if you have questions just see original post https://github.com/azerothcore/azerothcore-wotlk/issues/2830

**Comment by FrancescoBorzi** [comment]
> I will not prove anything to anyone I hate it.

@Mitradis it's not about proving anything. It's about explaining what your change does and what could (potentially) be affected.

> For heaven's sake JUST SEE CODE.

The issue here is that testers are not necessarily programmers. So not everyone is going to understand your code. If we don't put explanations in PRs, then we are restricting the possibility to test only to programmers. While with descriptions, also non-programmers can help with testing.

This is very important and I hope you will understand it.

**Comment by BarbzYHOOL** [comment]
just by looking at the changed file, it looks like it's good to me

it will depend on the debug config option, seems correct

**Comment by Mitradis** [comment]
as I thought no one needs it

**Comment by FrancescoBorzi** [comment]
@Mitradis you know we don't charge for keeping a PR open. So even if (sadly) no one tested this, you could have just left it open.

**Pull request closed without merging**
