### PR TITLE
feat(Core/Game): Add option to disable trading BoP items among raid members

### LINKED ISSUE #4883: Feature: by worldserver.conf Add a setting to allow the transaction time to loot items [$20]
**Describe your feature request or suggestion in detail**
Blizzard has set a default time of 2 hours for trading items looted by the boss

**Describe a possible solution to your Feature or Suggestion in detail**
Blizzard has set a default time of 2 hours for trading items looted by the boss,I  hope we can add a setting to enable or disable it,Set 0 to disabled. If it is set to be greater than 0, the number of hours allowed to trade is 2. Via `worldserver.conf`

<bountysource-plugin>

---
There is a **[$20 open bounty](https://www.bountysource.com/issues/97181928-feature-by-worldserver-conf-add-a-setting-to-allow-the-transaction-time-to-loot-items?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…ms among raid members.

Fixed #4883

## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #4883.

## Tests Performed:
-
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@mpfans please test this

**Comment by mpfans** [comment]
tested... BOP items dropped from raid and dungeon cannot be traded. Those purchased by NPC can be returned to NPC.

good job!

**Comment by pklloveyou** [comment]
I'm late.

**Comment by UltraNix** [comment]
Updated.

**Pull request merged**
