### PR TITLE
fix(DB/Creature): Razorscale Harpoon Fire State

### PR DESCRIPTION
**Pull request by poszer**
Razorscale Harpoon Fire State

##### CHANGES PROPOSED:

- Adding flags_extra 128	CREATURE_FLAG_EXTRA_TRIGGER creature is trigger-NPC (invisible to players only). 
-  It already have flags_extra set to 2 | CREATURE_FLAG_EXTRA_CIVILIAN | 0x00000002 | creature does not aggro (ignore faction/reputation hostility)
- At the end it's set to flags_extra=130.

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2035

##### TESTS PERFORMED:

Yes, it should be invisible to players. It's trigger

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Naxxramas-Server have you tested this? or your approval is for code review? Just to understand :)

**Comment by Naxxramas-Server** [comment]
I'v tested it and work fine

**Comment by FrancescoBorzi** [comment]
good job @poszer and @Naxxramas-Server

**Comment by spinzaku** [comment]
Thank you for this!!

**Pull request merged**
