### PR TITLE
fix(DB/conditions): Glyph Chasing Conditions

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Glyph Chasing rubbing option only available in correct situations

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3911
- Closes https://github.com/chromiecraft/chromiecraft/issues/3743
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12336

## SOURCE:

See original reports

## Tests Performed:

- Tested in game, can only get rubbing during quest, with rubbing kit, and when rubbing not already collected

## How to Test the Changes:

1. Test option is not available
2. Add quest and quest item, test option is available
3. Collect rubbing, test that option is not available if rubbing already received

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by tkn963** [comment]
Are you supposed to right-click the crystal and choose an option to collect the rubbing? I can't collect any if I don't have the quest and I can't collect any if I have the item but I can't seem to collect any even if I don't have the item. I abandoned the quest and grabbed it again to make sure there weren't some issue with me just deleting the items.
image

**Comment by ZhengPeiRu21** [comment]
> Are you supposed to right-click the crystal and choose an option to collect the rubbing? I can't collect any if I don't have the quest and I can't collect any if I have the item but I can't seem to collect any even if I don't have the item. I abandoned the quest and grabbed it again to make sure there weren't some issue with me just deleting the items. image

You should be able to open gossip menu any time, but option will only appear when three condition are meet: you must have the quest, you must have the quest item, and you must not have already the rubbing for that crystal.

> I can collect the one from the gameobject with id 180454 (Hive'Ashi) but other two with ids 180453 and 180455 doesn't give me any options.

Sorry, this was my mistake! I was lazy and replace all "1" with "2" and "3", which changed some wrong values! I have update it to be correct now.

**Comment by tkn963** [comment]
If I don't have the quest , I can't collect any 👍 
If I do have the quest, I can collect all of them 👍 
If I have the quest and the item already, I can't collect them again 👍

**Comment by Gultask** [comment]
I got the same results as tkn963 👍

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
