### PR TITLE
fix(DB/Spawns): Some improvements to Death Talon Hatcher spawns:

### LINKED ISSUE #10941: [BWL] Death Talon Hatcher - Incorrect position and not patrolling
### Current Behaviour

- Death Talon Hatcher have incorrect positions
- Some Death Talon are missing
- They are not patrolling

### Expected Blizzlike Behaviour

- On many videos, it seems  that there are one Death Talon between two traps line
- Death Talon are patrolling on their line
- It seems to be no Death Talon in the stairs (more visible on the 2nde video)

### Source

https://www.youtube.com/watch?v=U_LKtGzxjTI&t=84s&ab_channel=Arlaeus

https://www.youtube.com/watch?v=D9gD9eBT0NA&t=404s&ab_channel=CholThemAll (start at 5:10min)

### Steps to reproduce the problem

1. .go xyz -7579.5917 -980.4238 442 469
2. Look the situation in the supression room

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 3fc9e914515d

### Operating system

Windows 11

### Custom changes or Modules

_No response_

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/106210519-bwl-death-talon-hatcher-incorrect-position-and-not-patrolling?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Corrected spawn positions
Death Talon Hatcher should patrolling the room.
Fixes #10941

## Issues Addressed:

- Closes #10941

## Tests Performed:

- Not tested.

## How to Test the Changes:

.go xyz -7579.5917 -980.4238 442 469
Look the situation in the supression room

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
Fixed.

**Comment by Lynethris** [comment]
All seems good. Strange pathway but it's seems like this on official.

I just got this warning in worldserver : WaypointMovementGenerator::LoadPath: creature Death Talon Overseer (GUID Full: 0xf1300030ad000079 Type: Creature Entry: 12461  Low: 121) doesn't have waypoint path id: 0

**Comment by UltraNix** [comment]
@Lynethris Not related to this PR.

**Comment by Nefertumm** [comment]
Startup errors
```
LinkedRespawn: Creature (guid) 85788 not found in creature table
LinkedRespawn: Creature (guid) 85793 not found in creature table
LinkedRespawn: Creature (guid) 85797 not found in creature table
LinkedRespawn: Creature (guid) 85798 not found in creature table
LinkedRespawn: Creature (guid) 85799 not found in creature table
LinkedRespawn: Creature (guid) 85802 not found in creature table
LinkedRespawn: Creature (guid) 85805 not found in creature table
```

**Comment by UltraNix** [comment]
@Nefertumm Fixed.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
