### PR TITLE
Fix pet saving on UNIX.

### LINKED ISSUE #57: Hunter pet's not saved. [$10]
**Description**: Hunter pet's not saved.

**Current behaviour**: On the Linux operating system hunter pets are not saved, but windows everything works perfectly.

**Expected behaviour**: When pet leveling level level should save, but it is reset when the log.

**Branch(es)**: 1.x / 2.x (Select the branch(es) affected by this issue) 

**AC hash/commit**:  [c9610ca](https://github.com/azerothcore/azerothcore-wotlk/commit/c9610ca0b5c6bbffcb443e1cc1dd698c53bada16)

**Operating system**:  OC Linux
## 

<bountysource-plugin>
---
There is a **[$10 open bounty](https://www.bountysource.com/issues/36880340-hunter-pet-s-not-saved?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Maczuga**
**Changes proposed:**

-  Fixes saving pets on UNIX systems
-  
-  

**Target branch(es):** master

**Issues addressed:** Closes #57 

**Tests performed:** (Does it build, tested in-game, etc) 

Tested on server with avg pop 2,5k online. Compiles and works fine.

**Known issues and TODO list:**

- [ ] 
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by boom8866** [comment]
Determine

**Comment by ShinDarth** [comment]
@boom8866  what do you mean? does it work for you or not?

**Comment by boom8866** [comment]
@ShinDarth Confirm that the problem has been solved

**Comment by boom8866** [comment]
@ShinDarth There is no question of keeping the 75 level.   I think this problem has been solved

**Comment by ShinDarth** [comment]
thanks @Maczuga for the PR and @boom8866  for the feedback, merged.

**Pull request merged**
