### PR TITLE
fix(DB/Object) Hide mailbox during hallow's end event

### PR DESCRIPTION
**Pull request by locus313**
## CHANGES PROPOSED:
-  Hide mailbox during hallow's end event

Before pr:

image

After pr:

image

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3602

## TESTS PERFORMED:
- Apply sql and restart server
- Start hollow's end event
- Check that mailbox disappears
- Stop Hollow's end event
- Check that mailbox reappears

## HOW TO TEST THE CHANGES:

- Apply sql and restart server
- .event start 12
- Check that mailbox disappears
- .event stop 12
- Check that mailbox reappears

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Meltie2013** [comment]
@locus313 Why would you hide the mailbox during the event? This was never done on retail servers.
It's just better to fix the position of the mailbox instead.

**Comment by Helias** [comment]
agree with @Meltie2013, I suggest to move the NPC to a different location

**Comment by Kitzunu** [comment]
Both solutions are hacky since we dont have the required sniffs or proof.

So the question lands in, what is the least hacky

**Comment by Si1ker** [comment]
"So the question lands in, what is the least hacky"
Move the npc.

**Comment by Kitzunu** [comment]
I'd say remove the mailbox because the only proof we have is that the npc is correct

**Comment by Gierlappen** [comment]
I don't understand why we don't just move the npc as i suggested in my PR and if somebody find a better or blizzlike solution we can just change it...

To move the Mailbox or hide it during the event is just more incorrect. I am the first to want correctness but if there is no source what is the blizzlike behaviour we still can improve things what is good to get people for this project.

As a contributor i wan't to say that i would contribute much more to this project if we go off this "if it's not blizzlike we accept the crap we have before we improve it" line. This is just demotivating.

I love this project and will continue contributing but i hab to say this.

**Comment by Meltie2013** [comment]
@Kitzunu Hiding the mailbox would be pointless and not blizzlike, cause the mailbox is in the right location. Plus you are removing the ability for players to visit the mailbox after auction house action as well by hiding it.
NPC is not in the right location and needs to be moved to the right of it. You guys making a bigger deal out it then it needs to be.

**Comment by locus313** [comment]
I will just close this pr since it sounds like more people are in favor of moving the npc.

**Comment by Kitzunu** [comment]
Improvements yes.
The only reason why I'd prefer this over moving the NPC is that the screenshot from the previous or. but then, it is not my preference that counts

**Comment by FrancescoBorzi** [comment]
> I don't understand why we don't just move the npc as i suggested in my PR and if somebody find a better or blizzlike solution we can just change it...
> 
> To move the Mailbox or hide it during the event is just more incorrect. I am the first to want correctness but if there is no source what is the blizzlike behaviour we still can improve things what is good to get people for this project.
> 
> As a contributor i wan't to say that i would contribute much more to this project if we go off this "if it's not blizzlike we accept the crap we have before we improve it" line. This is just demotivating.
> 
> I love this project and will continue contributing but i had to say this.

I agree. We should be flexible. Also, whatever PR we merge, we can always make it better later.

**Pull request closed without merging**
