### PR TITLE
fix(DB/creature) Rachelle Gothena Position

### LINKED ISSUE #3602: (Event) Hallow's End - Rachelle Gothena/mailbox location
##### CURRENT BEHAVIOUR:

- Rachelle Gothena is spawning in the same location as a mailbox out side the auction house

image

##### EXPECTED BLIZZLIKE BEHAVIOUR:

- Still trying to find the exact information on this, but dont think there should actually be a mailbox right outside of the auction house. From what I could find the spawn location for Rachelle Gothena looks about right:
https://wowgaming.altervista.org/aowow/?npc=15354

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to the auction house in Orgrimmar
2. See that Rachelle Gothena is spawned right in the mailbox that is right outside the auction house

##### AC HASH/COMMIT:

https://github.com/azerothcore/azerothcore-wotlk/commit/32da0eeb9e39b362eae50944a5b16069301403c6

##### OPERATING SYSTEM:

Centos7

##### MODULES:

mod-ah-bot
mod-autobalance
mod-cfbg
mod-custom-login
mod-individual-xp
mod-transmog

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/94005972-event-hallow-s-end-rachelle-gothena-mailbox-location?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Gierlappen**
## CHANGES PROPOSED:
-  Update coordinates for creature guid 86234

No real evidence found for the NPC's actual location. But better than in the mailbox

## Before PR 

image

## After PR

image

## ISSUES ADDRESSED:
- Closes #3602 

## TESTS PERFORMED:
- Imported SQL
- Tested ingame (See Screenshot)

## HOW TO TEST THE CHANGES:

- Import SQL
- .go 1655.067505 -4423.856445 16.487047 1
- See the result

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Si1ker — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Review by Kitzunu — CHANGES_REQUESTED** [review]
No.
image

That is a picture from  2007/09/28 (https://classic.wowhead.com/npc=15354/rachelle-gothena#screenshots:id=57277) which shows she should stand on the other side.

**Comment by Gierlappen** [comment]
That's the old position IN the Mailbox... Please Tage a close look to the Screenshots and compare them.

**Review by grimgravy — APPROVED** [review]

**Comment by locus313** [comment]
I agree with @Kitzunu on this, In the research I did it looks like Rachelle Gothena is in the correct position and the mailbox is ether in the incorrect position or should not even be there. I was trying to find a resource with org mailbox positions during wotlk, but not found a good resource to confirm.

**Comment by Gierlappen** [comment]
In that case i close the PR. Someone can make a new one for the Mailbox if you find a source of the correct behaviour

**Comment by BarbzYHOOL** [comment]
@locus313 @kitzunu so are we satisfied with the mob being inside the mailbox atm? xD

**Comment by BarbzYHOOL** [comment]
can we merge this and open a followup issue instead? we are keeping a bug for reasons like "oh no the mob is 1 meter on the left, it's so not blizzlike"

**Comment by BarbzYHOOL** [comment]
that mailbox is not on current official wow (normal) and wasn't there in classic either, so the only way to know would be to watch 2009 videos of orgrimmar and be lucky

**Comment by locus313** [comment]
@BarbzYHOOL What if we just hide the mailbox during the event? 
```sql
DELETE FROM `game_event_gameobject` WHERE `guid` IN (150747);
INSERT INTO `game_event_gameobject` (`eventEntry`, `guid`) VALUES (-12,150747);
```
I can submit in a pr in a little bit.

**Comment by BarbzYHOOL** [comment]
i also thought about that, it's a solution too, a bit shaky though (players will be confused about the mailbox not being here)

but what if it also happens during other events?

or what about moving the mailbox? dunno, many solutions for such a small but bad looking bug

**Comment by FrancescoBorzi** [comment]
so did anyone provide a better solution for this? otherwise this one should be accepted imho...

**Comment by locus313** [comment]
@FrancescoBorzi from the feedback we had in the other pr, Seems like we should just accept this pr.

**Comment by Si1ker** [comment]
@FrancescoBorzi  I give my +1 / 👍  to this one.
@Gierlappen If you wanna continue it, you have my support. 🐱

**Comment by Gierlappen** [comment]
I will open a new PR 👍

**Comment by FrancescoBorzi** [comment]
thanks everyone for their feedback, and especially thanks @Gierlappen for the PR!

**Pull request closed without merging**
