### PR TITLE
fix(DB/Quest): Remove exclusivegroup from Tome of Divinity quests

### PR DESCRIPTION
**Pull request by Nyeriah**
...and only show next quest if player has completed the book quest

## Changes Proposed:
-  Remove exclusivegroup from Tome of Divinity quests
-  only show next quest if player has completed the book quest

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8746

## SOURCE:

https://user-images.githubusercontent.com/47818697/142729552-e1b01c5a-b103-45f8-99f8-8c4ba8e416ee.mp4

## Tests Performed:

- Tested in-game.
- 

## How to Test the Changes:

1. Create a human paladin (level 12)
2. Teleport to goldshire, pick up breadcrumb quest for the ress spell from trainer
3. Go to stormwind cathedral, turn in quest
4. Pick up the book quest, try to accept quest from book
5. Turn in quest from book, next quest in the chain shows up

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@Shineslippers please test this (it should fix not being able to pick quest from book for both humans and dwarves).

**Comment by Shineslippers** [comment]
Ok, i will but check out conditions as i mentioned

- 2998, 3681 should not close 1641, 1642 and should not open 1643
-  2997, 2999, 3000 should not close 1645, 1646 and should not open 1647
- You have to start quest only from book
- 1641 should be repetable. In case of destroy of book, but not available after 1642 complete.
- 1645 should be repetable. In case of destroy of book, but not available after 1646 complete.

**Comment by Shineslippers** [comment]
Tested:
Complete of any [Tome of Divinity](https://wowgaming.altervista.org/aowow/?search=tome+of+divinity#quests) quests:
- doesn't start any other quests
- doesn't broke accept of The Book of Divinity quests

**Comment by Nyeriah** [comment]
> Tested. Complete of any [Tome of Divinity](https://wowgaming.altervista.org/aowow/?search=tome+of+divinity#quests) quests:
> 
> Condition	Result
> doesn't start any other quests	yes
> doesn't broke accept of The Book of Divinity quests	yes
> only show next quest if player has completed the book quest	yes
> Quests [1641](https://wowgaming.altervista.org/aowow/?quest=1641) and [1645](https://wowgaming.altervista.org/aowow/?quest=1645) isn't repetable. Destroy of [Tome of Divinity](https://wowgaming.altervista.org/aowow/?item=6775) broke chain.

Thanks for testing, I've fixed that part too. You should be able to reaccquire the book if you destroy it now.

**Comment by Shineslippers** [comment]
Seems fine. 1641 and 1645 is repetable, but in video on complete it was `blue mark` type quest
image

**Comment by Nyeriah** [comment]
> Seems fine. 1641 and 1645 is repetable, but in video on complete it was `blue mark` type quest. Right now while you have book NPC doesn't show anything. image

Ahhh... so the quest that offers the book should show even if you already got the book? Okay, maybe I fixed it "too much", alright, I'll remove that condition

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
