### PR TITLE
fix(CORE/Instance): Fixed group spawn UBRS Rend Blackhand

### LINKED ISSUE #1876: UBRS BIG bug event Boss Warchief Rend Blackhand
SMALL DESCRIPTION:
Event Arena Warchief Rend Blackhand Imba

EXPECTED BLIZZLIKE BEHAVIOR:

This encounter is pretty simple, once several waves of enemies are taken out (Either 1 Elite chromatic dragonkin and an orc handler or 2 dragonkin; and 3 chromatic whelps) he will come through the gate to face you. It is important to note throughout this fight that a multitude of orcs spawn at the top of the arena. They will remain there until the event is completed.

https://wow.gamepedia.com/Rend_Blackhand_(tactics) 

Patch changes
Warlords of Draenor Patch 6.0.2 (2014-10-14): Removed. 
WoW Icon update.png Patch 1.3.0 (2005-03-07): Rend Blackhand's treasure table has been modified. 

https://www.youtube.com/watch?v=0KeVyOxlKG4 offi Video

CURRENT BEHAVIOUR:

- [ ] The first group before the start of the event should not be behind the gate.

- [ ] The groups that are spawned are too many (imba.) 

- [X] The texts are okay and correct.

- [X] The boss damage seems to be okay.

- [ ] At the event the spectators should be full of elite npc's who don't interfere. 

- [X] All creatures or corpses created during the event are deleted in a group wipe.

Wow offi https://youtu.be/0KeVyOxlKG4?t=141

AC Video https://youtu.be/_R0TRDXpLvY

STEPS TO REPRODUCE THE PROBLEM:

.go 154.01 -394.17 124.23 229

BRANCH(ES):
AzerothCore rev. b67ea15d1651+ 2019-05-23 15:26:51 +0000 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: NO

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74574932-ubrs-big-bug-event-boss-warchief-rend-blackhand?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by finnmich**
UBRS Rend Blackhand was spawing too many mobs in first phase

Partially fixes issue #1876 now playable

##### ISSUES ADDRESSED:
- Partially Closes #1876 

##### TESTS PERFORMED:
- Go to event: .go 154.01 -394.17 124.23 229
- Verify that the mobs in phase 1 spawns at correct rate
- Tested on docker in win10

##### HOW TO TEST THE CHANGES:
 - .go 154.01 -394.17 124.23 229
- Verify spawnrate

##### KNOWN ISSUES AND TODO LIST:
- [ ] NPC spectators still missing during encounter

##### Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@finnmich 

> NPC spectators still missing during encounter

Are you planning to add this to this PR or is the PR finished?

**Comment by finnmich** [comment]
> @finnmich
> 
> > NPC spectators still missing during encounter
> 
> Are you planning to add this to this PR or is the PR finished?

Hi, I am not planning to add the spectators so this PR finished.
(My goal was to make the encounter playable, which it now is)

**Comment by Stoabrogga** [comment]
Ok, thanks, looks good to me. Just need someone to test this.

**Comment by Stoabrogga** [comment]
As a side note: This bug was introduced with PR #1101, don't know why this did not show up during the tests and reviews at the time. Using "sizeof" to get the number of array elements should **never** be used as it returns the size in **Bytes**. Probably this would work, too:
```cpp
for (uint8 i = 0; i < sizeof(wave) / sizeof(wave[0]); ++i)
```
But I think the solution of this PR is better, because the length of the array is directly specified.

**Comment by pangolp** [comment]
Proven. Although I think those npc should disappear. Because if not in the first output they appear as 8 npc. This was the order in which the groups came out:

1. 8
2. 3
3. 4
4. 4
5. 5
6. 5

<a href="https://subefotos.com/ver/?f10e455fc3504726e18596983a42c0a7o.jpg" target="_blank"></a>

**Comment by Stoabrogga** [comment]
@pangolp 
Thanks for testing this. I'd say we merge this PR to fix this game-breaking bug. We can always fine-tune the event in subsequent PRs.

**Comment by pangolp** [comment]
Can't add one more commit including delete?

**Comment by Stoabrogga** [comment]
@pangolp 
No, please create a separate PR for this as changes to the area or the event itself should be discussed and tested separately.

**Pull request merged**
