### PR TITLE
fix(Core/Spells): Allow barkskin and HOF to be casted while player has disorient.

### PR DESCRIPTION
**Pull request by ErnestoGonzalezC**
gouge tried to do it above with disorient but didn't work.

the powers [bark skin and hand of freedom] should be able to be used
while under the effects of disoriented, for example in gouge.

## Changes Proposed:
-  Allow barkskin and HOF to be casted while player has gouge tried to do it above with disorient but didn't work.

## Issues Addressed:
- Closes 

## Tests Performed:

-  Compiles successfully on Windows.

## How to Test the Changes:

Login with a druid or paladin and 1 rogue, cast gouge to the paladin or druid and try to use the hand of freedom in the case of the paladin and in the case of the druidic bark skin.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
Do these changes affect other spells?

**Comment by pklloveyou** [comment]
PR had no effect

**Comment by pklloveyou** [comment]
test method
.aura 1776
.c 1044 or .c 22812

**Comment by ErnestoGonzalezC** [comment]
@pklloveyou ```m_spellInfo-> Id ! = 22812 && m_spellInfo-> Id ! = 1044``` The change only affects those 2 powers, I saw your comment, I tried it your way and it works.

**Comment by Kitzunu** [comment]
This too I'd honestly prefer if it was a spellscript. This way is kind of hacky

**Comment by pklloveyou** [comment]
You can use spells, but they don't work

**Comment by ErnestoGonzalezC** [comment]
@pklloveyou I think it was my mistake when trying to explain it in the pr, the idea is that these 2 powers can be launched while under the effect of disorientation.

**Comment by GMKyle** [comment]
I didn't test the PR but only reading spell desc any1 can notes that barkskin is usable while stunned, frozen, incapacitated, feared or asleep but can't find that hand of freedom should have the same behavior while incapacitated, i also check the spells using spellwork.

**Comment by ErnestoGonzalezC** [comment]
> I didn't test the PR but only reading spell desc any1 can notes that barkskin is usable while stunned, frozen, incapacitated, feared or asleep but can't find that hand of freedom should have the same behavior while incapacitated, i also check the spells using spellwork.

The truth is that to make arrangements regarding the pvp mechanics I was guided by warmane since it is the most complete current server of this branch.

**Comment by GMKyle** [comment]
Trust only in how this spells works in warmane is a mistake if you ask me. I know is a good server ....... but is not retail. 
I also said that barkskin should be cast while incapacitated but HoF don't bc using Spellwork only has (can be used while stunned) attr (i know, is hard find info). Finally i think you should use a different approach (maybe use a spellscript), like Kitzunu said.

**Comment by ErnestoGonzalezC** [comment]
> Trust only in how this spells works in warmane is a mistake if you ask me. I know is a good server ....... but is not retail.
> I also said that barkskin should be cast while incapacitated but HoF don't bc using Spellwork only has (can be used while stunned) attr (i know, is hard find info). Finally i think you should use a different approach (maybe use a spellscript), like Kitzunu said.

I don't think you have time to take a different approach to this, let me know if the PR should be shut down. And with respect to not being guided only by warmane, I understand it but it is the only way I have to apply rapid changes since in my country the internet is very expensive

**Pull request closed without merging**
