### PR TITLE
refactor(Map): Use std::chrono for SetZoneOverrideLight

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick https://github.com/TrinityCore/TrinityCore/commit/e33c4b8f7f18c89fec3d95531fdccad526c12c10

Co-Authored-By: HelloKitty <5829095+HelloKitty@users.noreply.github.com>

## Changes Proposed:
- Start using std::chrono instead

## Tests Performed:

- Builds

## How to Test the Changes:

1. Check LK or Malygos that they override the light as before

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
we should do the same for eventmap class, loads of timers are in huge ass uints

**Comment by Kitzunu** [comment]
We should do it everywhere =)

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Kitzunu** [comment]
@azerothcore/testers can someone test please...

**Review by Helias — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> @azerothcore/testers can someone test please...

@jamadaha @IntelligentQuantum can you guys please test all PRs that need to be tested and are waiting already for a long time?

**Comment by Nyeriah** [comment]
**Tested, working as intended.**

**Review by Nyeriah — APPROVED** [review]

**Comment by Kitzunu** [comment]
Thank you @Nyeriah

**Pull request merged**
