### PR TITLE
fix(Scripts/ZulFarrak): add Hearthstone mechanic to Blys party when event not started in time

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
- Added hearthstone mechanic after approximately 2 and a half minutes where the party from Bly "hearths" home
-  also found an apparent bug where if you had already talked to Bly once, a boolean would be fire upon getting that gossip menu, which was also used in its condition. So this bugged the event if you closed the window. I fixed this too

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11773
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16316
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16317
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16318
- Closes https://github.com/chromiecraft/chromiecraft/issues/5546

## SOURCE:

See issue above

## Tests Performed:

- tested by myself. should work
- 

## How to Test the Changes:

1. go to ZF
2. start the pyramid event
3.

## Known Issues and TODO List:

- [ ] fix that Weegli and Bly get stuck when you talk to them

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
WIP because gossip is ruining my day. Him staying stuck because of people talking to him does not make anything undoable and should not cause further bugs tho.

**Comment by Kitzunu** [comment]
> fix that Weegli and Bly keep moving even if you talk to them

Check `InteractionPauseTimer in c_t_m

**Comment by elthehablo** [comment]
> 



> > fix that Weegli and Bly keep moving even if you talk to them
> 
> Check `InteractionPauseTimer` in c_t_m

No entry exists for them yet. Will toy around with it a bit. ty. Are they automatically linked or do I need to configure something in another table?

**Comment by Kitzunu** [comment]
It's linked to creature entry

**Comment by elthehablo** [comment]
> It's linked to creature entry https://www.azerothcore.org/wiki/creature_template_movement

Yeah sorry, I meant more that it needs to be "set" like for SmartAI. Anyway, default is NULL so this is probably not it, but testing regardless by setting both to 1ms

**Comment by Kitzunu** [comment]
No. Anything creature_template_* is directly linked to the creature

**Comment by elthehablo** [comment]
> No. Anything creature_template_* is directly linked to the creature

No luck unfortunately :/

**Comment by elthehablo** [comment]
Moreover, I am kind of starting to feel this is why the gossip was removed on npc walking x)

**Comment by Kitzunu** [comment]
Okay then I definetly misunderstood. Because in the todo you say they keep moving, but now they get stuck when you talk to them?

**Comment by elthehablo** [comment]
> Okay then I definetly misunderstood. Because in the todo you say they keep moving, but now they get stuck when you talk to them?

Ah yeah that was me not writing something coherent in my haste. It was supposed to read: fix (make it so) that they keep moving, even if you talk to them

**Comment by Kitzunu** [comment]
Got it

**Comment by elthehablo** [comment]
should be good to merge now

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
