### PR TITLE
Fix improve our docker structure

### PR DESCRIPTION
**Pull request by tony-engineering**
## Changes Proposed:
- use Dockerfile multi-stage feature to avoid having a Dockerfile for "build" and another for "run"
- merge worldserver and authserver images since they use the same codebase. Introduce a flag START_AS_AUTHSERVER to be able to run the image as authserver
- use Docker BuildKit in order to enable layers caching in pipelines
- enable compilation cache when building with Docker
- publish the images of containers on docker hub
- allowing the user to pull and use them without necessarily building them locally

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4006

## Tests Performed:
- `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build` everything seems to be up and running
- change a C++ file, run `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build` and observe that compilation is faster than the first time
- run pipeline, wait the build to finish, then force rerun by pushing an empty commit `git commit -m "Force rerun" --allow-empty` and observe that layers are cached 

## How to Test the Changes:

- `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build`
- change a C++ file, run `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build`

## Known Issues and TODO List:

- add this to documentation: In order to build a testable image and run unit tests, do the following: `DOCKER_BUILDKIT=1 docker build -f docker/server/Dockerfile --target=testable -t azerothcore2/server:test .` then `docker run azerothcore2/server:test ./azerothcore/build/src/test/unit_tests`
- when runnung tests with the method described above there very few tests run. Is it expected ?

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by tony-engineering** [comment]
I was pushing images on an account I created "https://hub.docker.com/r/azerothcore2/server". The best would be that you provide the "azerothcore" DockerHub username/password as environment variables in your repo to push images there.
What do you think ?

**Comment by tony-engineering** [comment]
Env variables to provide for docker login are: DOCKER_HUB_PASSWORD and DOCKER_HUB_USERNAME

**Comment by locus313** [comment]
@tony-engineering we actually already have a different docker restructure in progress here:
https://github.com/azerothcore/azerothcore-wotlk/pull/4488

While adding of docker hub is something we want to do. I am not in favor of combining the auth and worldserver images. There is many times where only the worldserver needs to be restarted and not the authserver. We also need to think of cases where someone might want to run more than one realm. Which the authserver would be used for all realms.

Also not in favor of combining the build and run into a multi-stage docker. This only runs the first time the docker is build. I don't think we should require users to rebuild the docker images every time they want to run a build or just update the core. We also need to think about the cases where users may want to update, but not the server offline while running the new build. 

We also need to keep the ci scripts in place as they get used by the ci on our many module repo's.

**Comment by tony-engineering** [comment]
@locus313 There are some things you didn't see when you executed commands displayed in "How to test the changes" section. Or you didn't see while reading the proposed version of docker-compose.yml file.

I took the time to read your commits https://github.com/azerothcore/azerothcore-wotlk/pull/4488/commits and saw that what you want to do with the devcontainer feature of VSCode is not incompatible with my changes. 

## "combining the auth and worldserver images"
in the Docker world "image" != "container". We had 2 images -> 2 containers. Now we have 1 image -> 2 containers. Dockerfiles for authserver and worldserver were the same. So no need to have two of them. 

##  "worldserver needs to be restarted and not the authserver"
Please execute commands displayed in "How to test the changes" in order to observe that you can restart worldserver without restarting authserver.

## "We also need to think of cases where someone might want to run more than one realm"
You can always choose how many replicas you want for each component of your application.

## "rebuild the docker images every time they want to run a build or just update the core"
Please execute commands displayed in "How to test the changes" in order to observe Docker layers + compilation caching.

## "users may want to update, but not the server offline while running the new build"
I didn't understand this point.

## "keep the ci scripts in place"
I deleted only scripts that were not needed if users use docker-compose to build and run the app.
I am fine with readding them.

**Comment by tony-engineering** [comment]
No review was done

**Comment by FrancescoBorzi** [comment]
> No review was done

so you decided to close this PR and delete the branch, like it cost you something to keep it open?

**Pull request closed without merging**
