### PR TITLE
fix(scripts/MoltenCore): Disable Ragnaros movement

### LINKED ISSUE #11869: Ragnaros moves during combat
[chromiecraft/issues/3539](https://github.com/chromiecraft/chromiecraft/issues/3539)

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

During combat with ragnaros, if the tank enters his hitbox he will take a backstep like most other mobs.
He only backsteps in lava, and will not exit the lava onto the land sections, but he can be pushed around anywhere in the lava pool in Molten Core.

### Expected Blizzlike Behaviour

Ragnaros should not move.

### Source

_No response_

### Steps to reproduce the problem

1. Summon Ragnaros in MC
2. Enter combat with Ragnaros
3. Step into his hitbox with his back to lava

### Extra Notes

2022-05-25 16_13_39-is1 (F5) Luckdemon-ChromieCraft - Luck Goats

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/7b4e1ef7d3d638f4ed182130af286a8f99528f53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Si1ker**
Pull Request by [sílker](https://www.chromiecraft.com/en/armory/?character/ChromieCraft/s%C3%ADlker)

## Changes Proposed:
-  Enable root state

## Issues Addressed:

- Closes #11869
- Closes https://github.com/chromiecraft/chromiecraft/issues/3539

## SOURCE:

Any Ragnaros encounter's video

## Tests Performed:

- Tested -> the change fixes the issue and does not break any encounter's mechanic
image

## How to Test the Changes:

1. Go Molten Core
2. Kill every boss and douse all runes
3. Engage into Ragnaros' encounter
4. Stay within 0-3 yards at all time, you'll notice no movement backwards from Ragnaros

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
I believe we should investigate what caused him to be able to move in the first place. It wasn't like that before, and as I know root is handled by creature_template_movement (or whatever that table was). @acidmanifesto this seems right up your alley.

**Comment by Nyeriah** [comment]
@acidmanifesto this worked fine until about two weeks ago for certain. I'm sure we would have noticed this before the raid was released and all during this time while testing and running the raid every week. Were there any recent changes that could have caused this?

**Comment by temperrr** [comment]
Personally never saw him move even last two weeks so not much use there

**Comment by acidmanifesto** [comment]
> @acidmanifesto this worked fine until about two weeks ago for certain. I'm sure we would have noticed this before the raid was released and all during this time while testing and running the raid every week. Were there any recent changes that could have caused this?
> 
> @temperrr do you happen to know when this started to happen?

Unless something cleared its movement state in the unit.cpp or movement generators. I wouldnt know. Ill check his ctm for his entry. But the only 4 things that will clear its states and make it default can walk is: unit.cpp adjustments, movent generators adjustments, ctm being re-adjusted, or individual creature script.

All four i made no changes to in over 6 months.

**Comment by temperrr** [comment]
There is been a pr with pathfinding and liquid I think

**Comment by acidmanifesto** [comment]
So look back at some old databases. This boss never had the rooted inhabit type. inhabit type was supersceded by the ctm i implemented. Alot, if not all the bosses in azerothcore were scripted previous to the ctm port. There are bosses that have root state in the source. I do not see the issue with this PR, but if there is a issue with this PR, then we need to know how to handle something like this so it is consistent within the source of azerothcore. Do we start moving all source rooted bosses to the ctm? or do we keep add root to the source to keep it all as one single c++ scripted boss? I will approve this PR, and leave the rest up for discussion before any merge consideration is made.

**Review by acidmanifesto — APPROVED** [review]

**Comment by Maelthyrr** [comment]
And why not use root flag in create_template_movement ? Revert the modif will easier than a cpp modif.

**Comment by acidmanifesto** [comment]
> And why not use root flag in create_template_movement ? Revert the modif will easier than a cpp modif.

It can go either way.

**Comment by Nyeriah** [comment]
If the CTM change works, then we probably should use that instead. If it doesn't work, then we should probably see why it doesn't because rooted creatures shouldn't reposition, definitely.

**Comment by acidmanifesto** [comment]
@Si1ker can you try and test if the following sql query will work instead? if it does, are you willing to change your pr to be sql only?
Run on the World DB:
```
DELETE FROM `creature_template_movement` WHERE `CreatureId`=11502;
INSERT INTO `creature_template_movement` (`CreatureId`, `Ground`, `Swim`, `Flight`, `Rooted`, `Chase`, `Random`, `InteractionPauseTimer`) VALUES (11502, 0, 0, 0, 1, 0, 0, NULL);
```

**Comment by Si1ker** [comment]
@acidmanifesto

**Comment by Maelthyrr** [comment]
Tested  and work. No issue encounter.

**Pull request merged**
