### PR TITLE
refactor(Core/Scripts): restyle with astyle

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## CHANGES PROPOSED:
- Restyle `scripts` lib with astyle

### Used arguments:
- `-A1 -xV -S -N -Y -p -xg -k1 -W1 -O -xM -H -xf -xh -xy`

## Target branch(es):
- [x] Master

### About
- http://astyle.sourceforge.net/

### CODE REVIEW

**Comment by Kitzunu** [comment]
Out of curiosity, what is astyle

**Comment by Winfidonarleyan** [comment]
Recheck pr info and look url

**Comment by Mitradis** [comment]
sory)) I could not resist after all restyle prs))
https://sun9-4.userapi.com/_fgrO8Z4cFWLmecsEeI_RAQ4mvknhTJZw28xHQ/B8xzmY-R5hE.jpg
"style bitch,"
"style"

**Comment by Mitradis** [comment]
@Winfidonarleyan need fix merge

**Pull request closed without merging**
