### PR TITLE
fix(Scripts/ICC): gossip in boss Deathbringer Saurfang

### PR DESCRIPTION
**Pull request by pangolp**
### Changes Proposed:
-  The hardcore code is removed from the gossip and replaced with the database code.
-  Some broadcast_text, from the intro, are updated.

### Issues Addressed:

- Closes

### Tests Performed:

- Windows 10
- In-game

### How to Test the Changes:

1. .tele IcecrownCitadelRaid
2. The first broadcast_text, belong to the dialogues at the entrance of the instance, after you kill the first adds of the ladder (in the alliance). In the horde, I had no problems.
3. The `gossip` and the `npc_text`, belong to the npc, which start the 4 boss event.

### Screenshot

WoWScrnShot_071422_155930

WoWScrnShot_071522_022601

The script does not fix the problem currently found in the event. It only adds the functionality of being able to read the gossip from the database and add some missing broadcast_text.

### Known Issues and TODO List:

---

### How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
image
Workflow failure is not a failure. But will need testing or video of the PR since it deals with a none english locale or a individual with the native locale client to test and report back their findings. If all is well I will message shin for a direct merge.

**Review by acidmanifesto — APPROVED** [review]

**Comment by pangolp** [comment]
If you play the audio, in the English client, you will hear the text you modify inside the broadcast_text_locale. I understand that the broadcast_text, should not be modified, because they are supposed to be sniffs, but in the locale, something happened and evidently, that particular text was uploaded wrong.

**Comment by pangolp** [comment]
Ultimately, what we can do, is to remove the broadcast_text for now, even if it is wrong, but to pass the tests. Because I don't know if someone is going to provide a video, then I'll have to see if I can get one. But you could compare it with the text you have in English.

**English:**
> This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people.$B$BRemember, hero, fear is your greatest enemy in these befouled halls. Steel your heart and your soul will shine brighter than a thousand suns. The enemy will falter at the sight of you. They will fall as the light of righteousness envelops them!

**Google translation (not the one I use) - But it is for comparison**
> Esta es nuestra posición final. Lo que ocurra aquí tendrá un eco a través de los tiempos. Independientemente del resultado, sabrán que luchamos con honor. Que luchamos por la libertad y la seguridad de nuestro pueblo.$B$BRecuerda, héroe, el miedo es tu mayor enemigo en estos salones ensuciados. Endurece tu corazón y tu alma brillará más que mil soles. El enemigo vacilará al verte. Caerán cuando la luz de la justicia los envuelva.

**Comment by pangolp** [comment]
Wait, it is also wrong in English. It has more dialogue than it should have, because then that phrase is said in another broadcast. Indeed, there is something wrong here.

**Comment by Maelthyrr** [comment]
Tested with french and US version and work fine. Some issue with the vent but not related to this PR. Already present.

**Comment by pangolp** [comment]
> Tested with french and US version and work fine. Some issue with the vent but not related to this PR (Already present).

Thank you for the proofs, and I'm sorry I couldn't answer sooner, but I was traveling. I understand, that validations are done for the `broadcast_text` case because sometimes people edit them, and most of them are sniff. But in the case of the locale, I don't understand why the INSERT of the data was wrong. That is why I propose to modify it. But when I do it, I get the validator that the table should not be modified.

**Comment by pangolp** [comment]
My idea was to solve the script, but it turned out to be a bit more complex than I thought, so I started by modifying the gossip and text. Then I will see if I can move forward with the script.

**Pull request merged**
