### PR TITLE
fix(DB): Argent Guard Thaelrid

### PR DESCRIPTION
**Pull request by Volgger**
Argent Guard Thaelrid (ID 4787) had wrong faction such as title & name
in locales.

With this PR i adapted the NPC **from patch 4.0.3a to 3.3.5a.** Now the NPC is able to end quest 6561 and start quest 1200 as expected. 

## CHANGES PROPOSED:
-  Changed faction to 35 (Friendly with A/H) 
image

-  Changed Name from "Scout Thaelrid" to "Argent Guard Thaelrid" & added Title "The Argent Dawn" for deDE, esES, esMX & frFR locales

**References taken from https://wowwiki.fandom.com/wiki/Scout_Thaelrid**
**Adapted to the `creature_template from` AC.** 

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Imported SQL file with HeidiSQL on Win 10 pro x64
- Checked NPC and tested with A/H Char
- Checked quests

## HOW TO TEST THE CHANGES:

- Import SQL file 
- .go -528.080139 316.999176 -50.471893 48
- Check if the NPC is friendly with A/H char

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
image

**Comment by pklloveyou** [comment]
NPC works fine, but I can't test the locale

**Comment by Endeffect-AT** [comment]
Thx 4 testing @pklloveyou ! 

I have only translated the locales where I am 100% sure that they are correct.
Therefore it may be that the koKR, ruRU, zhCN, zhTW locales are still wrong. This may be translated by someone who knows the language :)

**Comment by Si1ker** [comment]
Tested 👍 💯 

Before ->
2020-02-19 11_22_40-Window


After ->
2020-02-19 11_29_25-Window

**Comment by Endeffect-AT** [comment]
Thx! Delete Cache folder and the name is also correct :)

**Comment by BarbzYHOOL** [comment]
@Si1ker thank you for testing, join us on discord !

**Comment by BarbzYHOOL** [comment]
@pklloveyou  hey, do you run a public server? (you can tell me on discord if you prefer)

**Comment by pklloveyou** [comment]
The server? I didn't get it. @BarbzYHOOL

**Comment by BarbzYHOOL** [comment]
no, nothing ^^ ignore it

**Comment by BarbzYHOOL** [comment]
thank you @Volgger and thanks the testers :))

**Pull request merged**
