### PR TITLE
fix(Core): Crashfix.

### LINKED ISSUE #11714: [server] world server crash 0511
### Current Behaviour

crash log:

https://gist.github.com/mpfans/9d8789571f9421fac3d8e7a5d7c9488e

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

aeb260c3cc14dfb5bfb0a3cd2540db534c993df3

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
## Issues Addressed:

- Closes #11714

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by eyeofstorm** [comment]
@UltraNix 

This modification may not fix the issue.
According to the crash log, It seems crash at Vehicle.cpp:533.
Which means 'Seats' member of class Vehicle is nullptr.

Addittional information:
In vehicle.dbc, there is no seat defined of entry 337 (referenced by  Salvaged Siege Turret).

**Comment by UltraNix** [comment]
```

**Comment by UltraNix** [comment]
Vehicle::IsVehicleInUse (this=0x0) at /home/polly/azerothcore/src/server/game/Entities/Vehicle/Vehicle.cpp:533
#3  0x00000000007296ea in npc_salvaged_siege_engine::BeforeSpellClick (this=<optimized out>, clicker=0x7fff4dadb280) at /home/polly/azerothcore/src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp:441
```
`Vehicle::IsVehicleInUse (this=0x0)` as you can see, vehicle is null. That crashfix is okay.

**Comment by eyeofstorm** [comment]
Oh, Vehicle::IsVehicleInUse (this=0x0)
You are right, and I am blind.

Salvaged Siege Turret has seat1 defined  at vehicle.dbc.

**Comment by mpfans** [comment]
tested.

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
