### PR TITLE
fix(Core/SpellEffect): increase speed of cat charge

### PR DESCRIPTION
**Pull request by Helias**
I don't know if my changes are really useful or not, it's really hard to get if the speed is increased actually or not.
I don't think that I made some break changes, I did several tests on this.

## Changes Proposed:
-  increase the speed of Feral Charge - Cat

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4791

## Tests Performed:
- tested several times in-game changing a lot of the parameters but apparently, there is a "limit" of the VELOCITY.
- There is a max velocity value that you can't overcome, this maximum is assigned considering the client limit as the comments says in MoveSplineInit.cpp line 123 `// limit the speed in the same way the client does`.

## How to Test the Changes:
.cast 768
.cast 49376 on a target

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
I feel that the speed has not improved

**Comment by laasker** [comment]
Yea, the speed is the same : P

Not sure if it helps but, i found in spell.dbc that Feral Charge - Cat 49376 casts
Charge 61138 https://wotlk-twinhead.twinstar.cz/?spell=61138
and that charge casts another charge https://wotlk-twinhead.twinstar.cz/?spell=61132

I tried to change the id to both of these but the speed is the same : (

**Comment by Helias** [comment]
Understood, the problem is the limit in MoveSplineInit.cpp line 123, should we overcome this limit? In TC is the same.
Are we sure that the youtube video with the increased speed is correct?

**Comment by laasker** [comment]
> Understood, the problem is the limit in MoveSplineInit.cpp line 123, should we overcome this limit? In TC is the same.
> Are we sure that the youtube video with the increased speed is correct?

Yes, Zybak youtube channel videos are all from Retail, so it is how the spell correctly works

**Comment by Mitradis** [comment]
why you replace "else if" on if?

**Comment by laasker** [comment]
i decided to test this again and worked!
im really, really sorry. I dont know what i had done wrong, but this does increases the speed of Feral Charge - Cat.

**Comment by Helias** [comment]
@laasker so the PR fix the issue? it's hard to test this, don't worry

@Mitradis because inside the if there is a return, it is unrelevant if you use else if or if in this case

**Comment by laasker** [comment]
@Helias Yes the PR fix the issue, thank you

**Review by vhiperdev — APPROVED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
