### PR TITLE
fix(Scripts/Temple of AhnQiraj): AhnQiraj critters should enter comba…

### LINKED ISSUE #12909: [AQ40] Being in combat nearby critters should cause them to attack the player.
### Current Behaviour

Qiraji Scarab (15316) and Qiraji Scorpion (15317) do not react to nearby combat.

### Expected Blizzlike Behaviour

They should engage the players that are nearby & in combat. I believe there's a mechanic called combat pulse.

### Source

Retail

### Steps to reproduce the problem

1. `.go c id 15316` or `.go c id 15317`
2. pull a nearby trash mob, see if the critters react.

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/9724c07528ab2746bd8e38fdc9a062f4854d788c

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…t with nearby attacked players.

Fixes #12909

## Issues Addressed:

- Closes #12909

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go c id 15316` or `.go c id 15317`
pull a nearby trash mob, see if the critters react.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
It works but I was going to change their SAI to add missing spells :c 
Could you add those in this PR? Or should I open another issue?

They:

- [ ] Cast 6016 within range 0-5y, repeating every 5000-9000ms.
- [ ] Cast 26050 on victim, initial 5000-9000ms, repeats every 6000-12000ms.
- [ ] Despawn after 5000ms on death.
- [X] Change faction on reset.

```
(15317, 0, 0, 0, 9, 0, 100, 0, 0, 5, 5000, 9000, 0, 11, 6016, 32, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Qiraji Scorpion - Within 0-5 Range - Cast \'Pierce Armor\''),
(15317, 0, 1, 0, 0, 0, 100, 0, 5000, 9000, 6000, 12000, 0, 11, 26050, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 'Qiraji Scorpion - In Combat - Cast \'Acid Spit\''),
(15317, 0, 2, 0, 6, 0, 100, 0, 0, 0, 0, 0, 0, 41, 5000, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Qiraji Scorpion - On Just Died - Despawn In 5000 ms'),
(15317, 0, 3, 0, 25, 0, 100, 0, 0, 0, 0, 0, 0, 2, 311, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Qiraji Scorpion - On Reset - Set Faction 311');
```

I'll update my PR right now to not conflict with this one.

**Comment by UltraNix** [comment]
@Gultask I will add it here.

**Comment by UltraNix** [comment]
@Gultask Done.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Gultask** [comment]
It works 👍 
Thank you ^^

**Comment by Nefertumm** [comment]
Conflicts

**Comment by UltraNix** [comment]
@Nefertumm @acidmanifesto Done.

**Pull request merged**
