### PR TITLE
Fix Ragnaros magma blast

### PR DESCRIPTION
**Pull request by Darkon47**
Currently the Ragnaros fight is bugged pretty badly, he is spamming magma blast in melee, and doing nothing if you stand out of range, this change fixes that so the fight can run as intended.

##### CHANGES PROPOSED:
-  
-  

##### ISSUES ADDRESSED:
- Closes

##### TESTS PERFORMED:
-
-

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by wizzymore** [comment]
**Magma Blast - Massive Ranged Damage**
If no one is engaged in melee with Ragnaros he will throw a ranged attack for _4000–6000_ damage which will kill most non-tank players in 1 hit and quickly wipe the raid. It's advisable to have a MT stand by at the end of Phase 2 to pick him up immediately upon resurfacing.

So yes, this makes it blizzlike.

Thank you for this fix!

**Comment by LichKing255** [comment]
Confirm.

**Comment by Stoabrogga** [comment]
@wizzymore @LichKing255 
Did you test this PR?

**Comment by LichKing255** [comment]
> @wizzymore @LichKing255
> Did you test this PR?

yes, true and working.

**Pull request merged**
