### PR TITLE
Core/Quests: Abandon&Finish quest items 

### PR DESCRIPTION
**Pull request by poszer**
Core/Quests: Abandon&Finish quest items 

Abandoning quests will delete associated quest items.

Closes 
[1094](https://github.com/azerothcore/azerothcore-wotlk/issues/1094)

##### TESTS PERFORMED:
Builded without errors on Win.

**BEFORE :**
before

**AFTER:**
after

**Ps**. Sorry, images are bad.  :rofl: 

HOW TO TEST CHANGES:
1. Accept a quest which requires collecting some item.
2. Collect 1+ of that item.
3. Abandon Quest
4 .Item will not remains in your inventory.

BRANCH(ES):

master

### CODE REVIEW

**Comment by talamortis** [comment]
Nice fix, just need to do a check now for items that grant a quest not to delete them

**Comment by poszer** [comment]
> 
> 
> This will introduce bugs to quests... non-quest specific items such as crafting reagents should remain in inventory, also:
> 
> Currently only the required amount of quest bound items are deleted on reward, fail, or abandon of a quest. However, there are quests like: http://www.wowhead.com/quest=582/headhunting that allow you to collect more than the required amount due to drop rates, this will lead to maybe, having a huge quantity of quest items not being removed.
> 
> You're missing this three commits, hope helps:
> 
> [TrinityCore/TrinityCore@8460285](https://github.com/TrinityCore/TrinityCore/commit/8460285f9442c41615f4bac80e9810a6eab8c252)
> [TrinityCore/TrinityCore@da204ad](https://github.com/TrinityCore/TrinityCore/commit/da204ad78c0a960da9fe3ea009ac91f8f39b6af2)
> [TrinityCore/TrinityCore@3e789bd](https://github.com/TrinityCore/TrinityCore/commit/3e789bd476ff9f10224c47b12c7e1af1483df189)

Good. Thank you ! Will include it

**Comment by BarbzYHOOL** [comment]
Lf dev

**Comment by FrancescoBorzi** [comment]
Looking for @poszer   or someone else to complete the work that has been previously started here.

**Comment by BarbzYHOOL** [comment]
@poszer !!

**Comment by poszer** [comment]
Okay, updated. Will close this and open new PR for it

**Comment by BarbzYHOOL** [comment]
@sucofog new PR here https://github.com/azerothcore/azerothcore-wotlk/pull/1241

**Pull request closed without merging**
