### PR TITLE
feat(Core/Config): rework configs load system

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
PR based @BarbzYHOOL idea in PR (#2560)

## CHANGES PROPOSED:
* Add new function for load modules configs
* Add messages for the modules using config variant (see screenshots)
* Rework loading config method
* Replace type in functions `Get***Default` from `const char* name` to `std::string const& name` (for new logging system)
* Now the loading of configs modules is separated from the configs servers.  See `LoadAppConfigs()` and `LoadModulesConfigs();`

### Before
1. Load `conf..dist` conf
```cpp
if (!sConfigMgr->LoadInitial(cfg_def_file.c_str())) 
{
    printf("ERROR: Invalid or missing default configuration file : %s\n", cfg_def_file.c_str());
    return 1;
}
```
2. Load `.conf` conf
```cpp
if (!sConfigMgr->LoadMore(cfg_file))
{
    printf("WARNING: Invalid or missing configuration file : %s\n", cfg_file);
    printf("Verify that the file exists and has \'[worldserver]' written in the top of the file!\n");
}
```
3. Add list configs in `World` class in `game` library
```cpp
//set module config file list
sWorld->SetConfigFileList(CONFIG_FILE_LIST);
```
4. Load modules configs in fuction `SetInitialWorldSettings`
```cpp
///- Initialize the World
sWorld->SetInitialWorldSettings();
```
### After
1. Add list configs files (server and modules if app == worldserver)
```cpp
sConfigMgr->SetConfigList(std::string(configFile), std::string(CONFIG_FILE_LIST));
```
2. Load apps configs
```cpp
if (!sConfigMgr->LoadAppConfigs())
   return 1;
```
3. Load modules config (in Config class) after loaded db
```cpp
sConfigMgr->LoadModulesConfigs();
```
---

## TESTS PERFORMED:
- Build and run in Win at VS `16.7.0 Preview 3.1`
- Build and run in Linux `Debian10` at `Clang7`

## HOW TO TEST THE CHANGES:
- Build and run auth/worldserver with configs modules
- Check logs in console/file
- See screenshots for example

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### Media
- Screenshots
image
image

```
2020-01-11 20:06:54 Using configuration file worldserver.conf.
2020-01-11 20:06:54 Using SSL version: OpenSSL 1.1.1d  10 Sep 2019 (library: OpenSSL 1.1.1d  10 Sep 2019)
2020-01-11 20:06:54 Using ACE version: 6.3.2
2020-01-11 20:06:54 AzerothCore rev. 97c02b70f922+ 2020-01-11 19:40:31 +0700 (ac-rework-config branch) (Win64, Release) (worldserver-daemon)
2020-01-11 20:06:54 <Ctrl-C> to stop.

2020-01-11 20:06:54    █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
2020-01-11 20:06:54   ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
2020-01-11 20:06:54   ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
2020-01-11 20:06:54   ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
2020-01-11 20:06:54   ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
2020-01-11 20:06:54   ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
2020-01-11 20:06:54                                 ██████╗ ██████╗ ██████╗ ███████╗
2020-01-11 20:06:54                                 ██╔════╝██╔═══██╗██╔══██╗██╔═══╝
2020-01-11 20:06:54                                 ██║     ██║   ██║██████╔╝█████╗
2020-01-11 20:06:54                                 ██║     ██║   ██║██╔══██╗██╔══╝
2020-01-11 20:06:54                                 ╚██████╗╚██████╔╝██║  ██║███████╗
2020-01-11 20:06:54                                  ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

2020-01-11 20:06:54   	  AzerothCore 3.3.5a  -  www.azerothcore.org

2020-01-11 20:06:54 Realm running as realm ID 1
2020-01-11 20:06:54 Using World DB: ACDB 335.3 (dev)
2020-01-11 20:06:54 
2020-01-11 20:06:54 Load config error. Invalid or missing configuration file: worldserver.conf
2020-01-11 20:06:54 Verify that the file exists and has '[worldserver]' written in the top of the file!
2020-01-11 20:06:54 
2020-01-11 20:06:54 ERROR: Load config error. Invalid or missing dist configuration file: ExternalMail.conf.dist
2020-01-11 20:06:54 ERROR: Verify that the file exists and has '[worldserver]' written in the top of the file!
2020-01-11 20:06:54 
2020-01-11 20:06:54 Load config error. Invalid or missing configuration file: worldserver.conf
2020-01-11 20:06:54 Verify that the file exists and has '[worldserver]' written in the top of the file!
2020-01-11 20:06:54 
2020-01-11 20:06:54 Load config error. Invalid or missing configuration file: worldserver.conf
2020-01-11 20:06:54 Verify that the file exists and has '[worldserver]' written in the top of the file!
2020-01-11 20:06:54 
2020-01-11 20:06:54 Load config error. Invalid or missing configuration file: worldserver.conf
2020-01-11 20:06:54 Verify that the file exists and has '[worldserver]' written in the top of the file!
2020-01-11 20:06:54 
2020-01-11 20:06:54 Using configuration for modules:
2020-01-11 20:06:54 > Module (transmog) using (transmog.conf)
2020-01-11 20:06:54 > Module (DungeonBuff) using (DungeonBuff.conf.dist)
2020-01-11 20:06:54 > Module (QuestBuff) using (QuestBuff.conf.dist)
2020-01-11 20:06:54 > Module (ExternalMail) using (default hardcoded settings)
2020-01-11 20:06:54 > Module (CFBG) using (CFBG.conf.dist)
2020-01-11 20:06:54 
2020-01-11 20:06:54 Initializing Scripts...
2020-01-11 20:06:54 Loading C++ scripts
2020-01-11 20:06:54 Will clear `logs` table of entries older than 1209600 seconds every 10 minutes.
2020-01-11 20:06:54 Using DataDir ../data/
2020-01-11 20:06:54 WORLD: VMap support included. LineOfSight:1, getHeight:1, indoorCheck:1 PetLOS:1
2020-01-11 20:06:54 ERROR: -> Not found option 'External.Mail.Enable'. The default value is used (No)
2020-01-11 20:06:54 ERROR: -> Not found option 'External.Mail.Interval'. The default value is used (1)
2020-01-11 20:06:54 
2020-01-11 20:06:54 Loading acore strings...
2020-01-11 20:06:54 >> Loaded 1171 acore strings in 4 ms
...
```

### CODE REVIEW

**Comment by Viste** [comment]
пиздато но ты бесишь ) придется мержится ска )))

**Comment by Winfidonarleyan** [comment]
Ахах, у меня планы чтобы убрать конфиг с World класса

**Comment by BarbzYHOOL** [comment]
> Replace type in functions Get***Default from const char* name to std::string const& name (for new logging system)

which new logging system?

Also what about that "reload feature" you talked to me?

**Comment by Winfidonarleyan** [comment]
> which new logging system?
> 
> Also what about that "reload feature" you talked to me?

Yes, for poco logs

**Comment by Ashland** [comment]
@BarbzYHOOL Wow this will break every module , got to love those breaking changes , Dan h there’s a lot of modules that will no longer work correctly if this is merged without updating the modules at the same time .

**Comment by BarbzYHOOL** [comment]
@Ashland I didn't make that PR so don't tag me, and show more respect towards contributors' work.

You should also explain what is wrong in the PR and if you find too many issues in the core, you can help with them too.

**Comment by Viste** [comment]
та ты заебал, когда ты уже угомонишься и нажмешь на кнопку merge

**Comment by Winfidonarleyan** [comment]
Незя
image

**Comment by Viste** [comment]
пиздец говно ебаное )

**Comment by Winfidonarleyan** [comment]
Хах

**Comment by BarbzYHOOL** [comment]
viste, your jokes in russian (i hope they're jokes) are confusing us :(

**Comment by FrancescoBorzi** [comment]
@Viste have you tested this ?

**Comment by BarbzYHOOL** [comment]
1) So, if this PR is accepted, my own PR is useless, right ?

2) What about the `.reload` thing you told me in private on discord, Winfi ?

3) Does this PR break any module ? Old modules ? new modules ? Can you test, Winfi ?

**Comment by Viste** [comment]
> viste, your jokes in russian (i hope they're jokes) are confusing us :(

its jokes don't worry. no i dont test it yet want do it in few days but i see code is ok. 
and this PR block my ACE pr :)

**Comment by Viste** [comment]
>     3. Does this PR break any module ? Old modules ? new modules ? Can you test, Winfi ?
all modules

**Comment by BarbzYHOOL** [comment]
If it breaks all modules, then that's not really good for us. Can it be possible to keep modules compatible ?

Else, I don't think we can merge this at the moment, too many modules to update.

**Comment by Viste** [comment]
> If it breaks all modules, then that's not really good for us. Can it be possible to keep modules compatible ?

no we cant sry :C need update all modules )) i can help with it

**Comment by Winfidonarleyan** [comment]
Hahaha, lol, so...
Let me explain what's going on and convince you ``otherwise``.

1. All modules that **_do not support_**  the macro `AC_ADD_CONFIG_FILE` - They'll work just like they did, change nothing.
2. All modules that **support** the macro `AC_ADD_CONFIG_FILE` - In these modules, the configuration will be loaded on this system

**Comment by Stoabrogga** [comment]
@Winfidonarleyan 
Sorry to ask, but I still don't understand: Is it necessary to change the modules which use "AC_ADD_CONFIG_FILE"?

**Comment by Winfidonarleyan** [comment]
No

**Comment by Yehonal** [comment]
Few questions:

1) what exactly does it improves in terms of features? 
2) as I understood, it's compatible with the current module system, it's not a breaking change. Is it? I've not against but we've to know.

3) before we was loading the .dist file, and then , if exist, the copied .conf "extending" the already loaded .dist configuration. Now, if I've read well your code, you load the .conf if exists, otherwise the .dist. Is it true?


A good approach imho would be something like this:

**.conf extends** -> **.dist.conf** extends -> hardcoded default value (taking care about keep the .dist.conf with the same values of hardcoded defaults)

Normally a server application should be capable to run even without the .conf files, so the "extend" logic should be better than loading only .conf or .dist.conf

**Comment by Winfidonarleyan** [comment]
1. Separate configurations, replace loading code, see **About loading config method**
2. Yes, it's not a breaking change. Only improve loading default configs (*server.conf / .conf.dist) and modules where there's support CMake macro `AC_ADD_CONFIG_FILE`
3. Loading all configs (`.conf.dist` and `.conf`) always if exist all files. For modules and default

---

> **.conf extends** -> **.dist.conf** extends -> hardcoded default value (taking care about keep the .dist.conf with the same values of hardcoded defaults)

Do you mean how best to get an option from the config?

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan what's the status of this? just needs to be tested/reviewed?

**Comment by Winfidonarleyan** [comment]
@FrancescoBorzi This is a long done PR

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan ok then we have to find testers for this.

@pklloveyou @Kitzunu @furywow @xDevICCI can you please give this a try?

**Comment by Kitzunu** [comment]
I dont use modules and I work 12 hr days this week so time is slim x)

**Comment by xDevICCI** [comment]
i try this ! wait me

**Comment by merdlin** [comment]
Very old PR, it must have been corrected. nobody but complained about it.

**Comment by FrancescoBorzi** [comment]
> Very old PR, it must have been corrected. nobody else complained.

or maybe no one tested it :) can you please test it too @merdlin ?

thanks @xDevICCI please let us know!

**Comment by merdlin** [comment]
Tested, I found no errors.

**Comment by Winfidonarleyan** [comment]
Update:
- `TESTS PERFORMED:`
- `HOW TO TEST THE CHANGES:`

**Comment by furywow** [comment]
Tested, no problems. :thinking: 

ubuntu 20.04

**Comment by FrancescoBorzi** [comment]
thanks all!

**Comment by Yehonal** [comment]
Winfi, are we now forced to create the .conf file next to the dist file? otherwise the server won't start. Is it true?

I'm testing it on a new azerothcore installation and authserver is not able to run without the "authserver.conf"

**Comment by Winfidonarleyan** [comment]
Yes

**Comment by BarbzYHOOL** [comment]
that's bad then

**Pull request merged**
