### PR TITLE
fix(Scripts/ZulGurub): Sacrificed Trolls should not be attackable by …

### LINKED ISSUE #12354: [ZG] Jin'do the Hexxer - Mind Controlled players can target and attack Sacrificed Troll creature.
### Current Behaviour

When a player is mind controlled by Brain Wash Totem, they will sometimes target and attack the Sacrificed Troll creatures.

### Expected Blizzlike Behaviour

Sacrificed Trolls should not be valid targets for mind controlled players.

### Source

https://youtu.be/bWTIVsbrjGo?t=109

### Steps to reproduce the problem

1. `.go c id 11380` with 2+ characters
2. get mind controlled by Brain Wash Totem, see if the Sacrificed Troll creatures are valid targets

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/4d888f94316d15f35b3bae4539ac81b033093c96

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…mind controlled players.

Fixes #12354

## Issues Addressed:

- Closes #12354

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c id 11380` with 2+ characters
get mind controlled by Brain Wash Totem, see if the Sacrificed Troll creatures are valid targets

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
The Sacrificed Troll sniffed faction is 16: https://github.com/azerothcore/azerothcore-wotlk/pull/12337#issuecomment-1179817370
But this PR does work, however.

**Comment by UltraNix** [comment]
If set to 16, then we have problem.

**Comment by UltraNix** [comment]
Do we have sniffed faction of Jindo?

**Comment by Gultask** [comment]
I'll ask Neifion

**Comment by Gultask** [comment]
Yup. FactionTemplate: 28

```
[1] UpdateType: CreateObject1
[1] Object Guid: Full: 0x204CB026A00B1D0000028600003F746C Creature/0 R4908/S646 Map: 309 Entry: 11380 Low: 4158572
[1] Object Type: 5 (Unit)
[1] NoBirthAnim: False
[1] EnablePortals: False
[1] PlayHoverAnim: False
[1] HasMovementUpdate: True
[1] HasMovementTransport: False
[1] Stationary: False
[1] HasCombatVictim: False
[1] HasServerTime: False
[1] HasVehicleCreate: False
[1] HasAnimKitCreate: False
[1] HasRotation: False
[1] HasAreaTrigger: False
[1] HasGameObject: False
[1] HasSmoothPhasing: False
[1] ThisIsYou: False
[1] SceneObjCreate: False
[1] HasPlayerCreateData: False
[1] HasConversation: False
[1] MoverGUID: Full: 0x204CB026A00B1D0000028600003F746C Creature/0 R4908/S646 Map: 309 Entry: 11380 Low: 4158572
[1] Movement Flags: 0 (None)
[1] Movement Flags 2: 0 (None)
[1] Movement Flags 3: 0 (None)
[1] MoveTime: 3152993270
[1] Position: X: -11515.778 Y: -1275.4799 Z: 79.6621
[1] Orientation: 3.159045934677124023
[1] Pitch: 0
[1] StepUpStartElevation: 0
[1] MoveIndex: 0
[1] Has Transport Data: False
[1] Has Fall Data: False
[1] HasSpline: False
[1] HeightChangeFailed: False
[1] RemoteTimeValid: False
[1] Has Inertia: False
[1] WalkSpeed: 2.5
[1] RunSpeed: 15
[1] RunBackSpeed: 4.5
[1] SwimSpeed: 4.72221994400024414
[1] SwimBackSpeed: 2.5
[1] FlightSpeed: 7
[1] FlightBackSpeed: 4.5
[1] TurnRate: 3.141592741012573242
[1] PitchRate: 3.141592741012573242
[1] MovementForceCount: 0
[1] MovementForcesModMagnitude: 1
[1] HasMovementSpline: False
[1] PauseTimesCount: 0
[1] FieldFlags: 0 (None)
[1] EntryID: 11380
[1] DynamicFlags: 0
[1] Scale: 1
[1] Health: 319800
[1] MaxHealth: 319800
[1] DisplayID: 11311
[1] [0] NpcFlags: 0
[1] [1] NpcFlags: 0
[1] StateSpellVisualID: 0
[1] StateAnimID: 1682
[1] StateAnimKitID: 0
[1] Charm: Full: 0x0
[1] Summon: Full: 0x0
[1] CharmedBy: Full: 0x0
[1] SummonedBy: Full: 0x0
[1] CreatedBy: Full: 0x0
[1] DemonCreator: Full: 0x0
[1] LookAtControllerTarget: Full: 0x0
[1] Target: Full: 0x0
[1] BattlePetCompanionGUID: Full: 0x0
[1] BattlePetDBID: 0
[1] (ChannelData) SpellID: 0
[1] (ChannelData) SpellXSpellVisualID: 0
[1] SummonedByHomeRealm: 0
[1] Race: 0
[1] ClassId: 2
[1] PlayerClassId: 0
[1] Sex: 0
[1] DisplayPower: 0
[1] OverrideDisplayPowerID: 0
[1] [0] Power: 26200
[1] [0] MaxPower: 26200
[1] [0] ModPowerRegen: 1065353216
[1] [1] Power: 0
[1] [1] MaxPower: 0
[1] [1] ModPowerRegen: 1065353216
[1] [2] Power: 0
[1] [2] MaxPower: 50
[1] [2] ModPowerRegen: 1065353216
[1] [3] Power: 1000000
[1] [3] MaxPower: 1000000
[1] [3] ModPowerRegen: 1065353216
[1] [4] Power: 0
[1] [4] MaxPower: 0
[1] [4] ModPowerRegen: 1065353216
[1] [5] Power: 0
[1] [5] MaxPower: 0
[1] [5] ModPowerRegen: 1065353216
[1] [6] Power: 0
[1] [6] MaxPower: 0
[1] [6] ModPowerRegen: 1065353216
[1] Level: 63
[1] EffectiveLevel: 0
[1] ContentTuningID: 0
[1] ScalingLevelMin: 0
[1] ScalingLevelMax: 0
[1] ScalingLevelDelta: 0
[1] ScalingFactionGroup: 0
[1] ScalingHealthItemLevelCurveID: 0
[1] ScalingDamageItemLevelCurveID: 0
[1] FactionTemplate: 28
[1] (VirtualItems) [0] ItemID: 13722
[1] (VirtualItems) [0] ItemAppearanceModID: 0
[1] (VirtualItems) [0] ItemVisual: 0
[1] (VirtualItems) [1] ItemID: 0
[1] (VirtualItems) [1] ItemAppearanceModID: 0
[1] (VirtualItems) [1] ItemVisual: 0
[1] (VirtualItems) [2] ItemID: 0
[1] (VirtualItems) [2] ItemAppearanceModID: 0
[1] (VirtualItems) [2] ItemVisual: 0
[1] Flags: 32832
[1] Flags2: 2099200
[1] Flags3: 0
[1] AuraState: 0
[1] [0] AttackRoundBaseTime: 2000
[1] [1] AttackRoundBaseTime: 2000
[1] BoundingRadius: 0.428399980068206787
[1] CombatReach: 2.099999904632568359
[1] DisplayScale: 1
[1] NativeDisplayID: 11311
[1] NativeXDisplayScale: 1
[1] MountDisplayID: 0
[1] StandState: 0
[1] PetTalentPoints: 0
[1] VisFlags: 0
[1] AnimTier: 0
[1] PetNumber: 0
[1] PetNameTimestamp: 0
[1] PetExperience: 0
[1] PetNextLevelExperience: 2147483647
[1] ModCastingSpeed: 1
[1] ModSpellHaste: 1
[1] ModHaste: 1
[1] ModRangedHaste: 1
[1] ModHasteRegen: 1
[1] ModTimeRate: 1
[1] CreatedBySpell: 0
[1] EmoteState: 10
[1] TrainingPointsUsed: 0
[1] TrainingPointsTotal: 0
[1] [0] ResistanceBuffModsPositive: 92
[1] [0] ResistanceBuffModsNegative: 0
[1] [1] ResistanceBuffModsPositive: 0
[1] [1] ResistanceBuffModsNegative: 0
[1] [2] ResistanceBuffModsPositive: 0
[1] [2] ResistanceBuffModsNegative: 0
[1] [3] ResistanceBuffModsPositive: 0
[1] [3] ResistanceBuffModsNegative: 0
[1] [4] ResistanceBuffModsPositive: 0
[1] [4] ResistanceBuffModsNegative: 0
[1] [5] ResistanceBuffModsPositive: 0
[1] [5] ResistanceBuffModsNegative: 0
[1] [6] ResistanceBuffModsPositive: 0
[1] [6] ResistanceBuffModsNegative: 0
[1] BaseMana: 1944
[1] SheatheState: 1
[1] PvpFlags: 0
[1] PetFlags: 0
[1] ShapeshiftForm: 0
[1] HoverHeight: 1
[1] MinItemLevelCutoff: 0
[1] MinItemLevel: 0
[1] MaxItemLevel: 0
[1] WildBattlePetLevel: 0
[1] BattlePetCompanionNameTimestamp: 0
[1] InteractSpellID: 0
[1] ScaleDuration: 100
[1] LooksLikeMountID: 0
[1] LooksLikeCreatureID: 0
[1] LookAtControllerID: -1
[1] GuildGUID: Full: 0x0
[1] SkinningOwnerGUID: Full: 0x0
```

**Comment by UltraNix** [comment]
@Gultask Do we have a sniff from Brain Wash Totem charming players?

**Comment by Gultask** [comment]
I don't think so. That's something we'll need to sniff as well as the Edge of Madness summoning event.

**Comment by Maelthyrr** [comment]
What is the status of this PR?

**Comment by UltraNix** [comment]
@Maelthyrr Missing sniff.

**Comment by Maelthyrr** [comment]
> @Maelthyrr Missing sniff.

I will try to get it.

**Comment by acidmanifesto** [comment]
Conflicts

**Comment by UltraNix** [comment]
@acidmanifesto Done.

**Comment by Nyeriah** [comment]
Is this one abandoned? What's the status on this one? It's been set to be merged later a year ago

**Comment by Gultask** [comment]
Sniff was requested and no one is bothering with it as there's more pressing matters.

On my end I think it's a core issue. For some reason MC'd players often attack neutral critters and creatures. I opened an issue about it quite a while ago.

**Comment by heyitsbench** [comment]
I've sniffed a failed attempt of the fight (includes mechanics such as the MC) and added it to the collective. Uploading a recording as well, but that'll be a bit.

**Comment by Kitzunu** [comment]
PR Abandoned. If you want to continue, reopen it or make a new PR.

**Pull request closed without merging**
