### PR TITLE
fix(Core/SmartScripts): Disallow Gob to use Combat with Zone

### PR DESCRIPTION
**Pull request by Kitzunu**
* Proper  fix for https://github.com/azerothcore/azerothcore-wotlk/issues/3028

## CHANGES PROPOSED:
-  Disallow Gob to use Combat with Zone

## TESTS PERFORMED:
- Builds

## HOW TO TEST THE CHANGES:

1. Make a SAI for a Gob with SMART_ACTION_SET_IN_COMBAT_WITH_ZONE

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
@FrancescoBorzi a proper fix for the crash thing that we merged yesterday :)

**Comment by pklloveyou** [comment]
It can be the same
```c++
- if (!me->GetMap()->IsDungeon())
+ if (mScriptType != SMART_SCRIPT_TYPE_GAMEOBJEC && !me->GetMap()->IsDungeon())
```

**Comment by FrancescoBorzi** [comment]
excellent @Kitzunu

**Comment by P-Kito** [comment]
I did not see this within 1 day, this is not a proper fix for this issue

**Comment by BarbzYHOOL** [comment]
need to make a followup issue then?

**Pull request merged**
