### PR TITLE
Fix:(Core/Gameobjects) Fix so non-consumable goobers don't despawn on use

### LINKED ISSUE #2658: Romantic Picnic Basket disappears ahead of time
##### SMALL DESCRIPTION:

**Romantic Picnic Basket** disappears ahead of time after it was used by owner

##### EXPECTED BLIZZLIKE BEHAVIOUR:

It mustt staying for 3 minutes and everybody can use it too with you for getting an achievenment

##### CURRENT BEHAVIOUR:

After using Romantic Picnic Basket it disappears momentarely

##### STEPS TO REPRODUCE THE PROBLEM:

1. if event "Love is in the Air" not started yet: .event start  8
2. .add 34480
3. use item, then use Basket
4. You can add 34480 to other player, which will use it near you and will use the Bucked. You and him gets love auras, but not achievement.

##### EXTRA NOTES:

изображение

##### BRANCH(ES):

master lastest

##### OPERATING SYSTEM:

Win 7

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/88304009-romantic-picnic-basket-disappears-ahead-of-time?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Kitzunu**
Fixes #2658 

Test performed:

- [x] Builds

- [x] In-game

Branch: Master

How to test:
1. Use any consumable goober without the change and with the change.

**I want to state that this is NOT my doing, it was taken from these commits originally made by Wyrserth on TrinityCore https://github.com/TrinityCore/TrinityCore/commit/50c5d30d13fe12af2a2028baf845fb6eab329a57 & https://github.com/TrinityCore/TrinityCore/commit/2b1e8d135bd3f3a3ddf7f29471cf6116da223175**

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
thanks @Kitzunu for importing this and ofc thanks to the original author @Wyrserth

**Comment by pklloveyou** [comment]
After testing, the object did not disappear. Will this PR affect other objects?

**Comment by FrancescoBorzi** [comment]
@pklloveyou it could as it's a change in the core, so testing also different kind of objects just to make sure nothing is broken would be better

**Comment by Kitzunu** [comment]
Test for example the apples in the INNs when Hallows end is on.

They should not disapear either and this should fix it

**Comment by Kitzunu** [comment]
Updated author, thanks @BarbzYHOOL for teaching me the ways :P

**Comment by Kitzunu** [comment]
BTW this will affect any
GAMEOBJECT_TYPE_GOOBER = 10
&
GAMEOBJECT_TYPE_CHEST = 3

```SQL
SELECT * FROM gameobject_template WHERE `type` IN (3,10)
```
Should get you all affected gobs

**Comment by pklloveyou** [comment]
I will put this PR on the server next Thursday for players to test

**Comment by pklloveyou** [comment]
So far players have not reported such errors

**Comment by BarbzYHOOL** [comment]
thank you @Kitzunu 

and of course, thank you @pklloveyou for testing!!

**Comment by CosmeF** [comment]
Hello. Players and myself have experienced a weird bug with this commit. It appears for some reason the ores on certain spots get instant respawn after mining them. 
imagen

I would like if someone else could go to the location on the image and test it, to see if it is an issue worth reporting. I've tested on 2 different machines (debian 10/ubuntu18.04), both on this commit hash.

**Pull request merged**
