### PR TITLE
Don't use bounding radius for aggro distance checks.

### PR DESCRIPTION
**Pull request by Krejza9**
## Changes Proposed:
-  This change is necessary for the correct calculation functioning of the future patch for aggro range
-  

## SOURCE:
https://github.com/vmangos/core/commit/af745365e9bd7f0963734510452c0ac957fb1424

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ] Some files need to be traced and added

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers can anyone help here please

**Comment by Winfidonarleyan** [comment]
@viste а ну ревью

**Review by Viste — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Ty

**Comment by Viste** [comment]
> Ty

you should say спасибо, because i dont speak this strange language 👯

**Comment by Krejza9** [comment]
@FrancescoBorzi please update Labels , no longer WIP
to Ready to be reviewed,Waiting to be tested
thx

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/developers can anyone please check this?

**Comment by Krejza9** [comment]
I talked to the brotalnia everything is fine , he didn't know about the second PR #6179 which needs to be deployed at the same time as this one.
My mistake , I should have put both PRs in one to avoid wrong conclusions

**Comment by Kitzunu** [comment]
How to test, what did you test? Dont ignore the template

**Comment by Krejza9** [comment]
merged with #6214

**Pull request closed without merging**
