### PR TITLE
Valkyr ShadowGuard  - Phase 2

### PR DESCRIPTION
**Pull request by xDevICCI**
Fix players using HoP to prevent selection from valkyrs

##### CHANGES PROPOSED:

-  
-  

###### ISSUES ADDRESSED:

Closes 

##### HOW TO TEST THE CHANGES:

<----- Start of Phase 1 ----->
Start Boss LK 25 (Normal - Heroic)
Do damage until the earthquake phase arrives
<---- End of Phase 1 ------>

<--- Start of Phase 2 ---->
Stand in the middle of the platform
Wait for the valkyr to come out
Cast HoP to player

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
thanks @xDevICCI waiting for tester feedback

**Comment by BarbzYHOOL** [comment]
How to test at least? Plz fill the "how to test"

**Comment by Nefertumm** [comment]
Go to ICC, reach LK, hit until phase 2, wait for valkyrs, cast Hand of Protection on valkyr's target, see if they grab him.

**Comment by BarbzYHOOL** [comment]
> Go to ICC, reach LK, hit until phase 2

That's why I can't test haha

**Comment by wetbrownsauce** [comment]
Maybe I'm doing something wrong, but I can't test this for the life of me. On 25 heroic (haven't tested other difficulties), lich king does his role play with tirion, then freezes him in ice, but then instantly runs back up to his throne and resets. Sindragosa also insta-kills me on aggro.

**Comment by BarbzYHOOL** [comment]
@xDevICCI @Nefertumm can someone give exact instructions on how to test?
with GM commands in the right order please

**Comment by wetbrownsauce** [comment]
Okay so I got this working. I'm not sure why I was having the problems previously described. I'm trying to replicate them to see if they need their own issue.  

That aside, I was able to properly test this PR. 

- Before PR, putting Hand of Protection on another player would prevent the Valk from picking them up.
- After PR, putting Hand of Protection on another player doesn't matter to the Valk, they can still pick that player up.

Works as intended.

**Comment by BarbzYHOOL** [comment]
ah ok that's what HoP means :rofl:

**Pull request merged**
