### PR TITLE
fix(Core): Fix Achievement Packets

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix Achievement packets to have correct times
-  Fixes display of many achievements such as Average Gold Per Day

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3712

## SOURCE:

Cmangos https://github.com/cmangos/mangos-wotlk/blob/master/src/game/Achievements/AchievementMgr.cpp

## Tests Performed:

- 

## How to Test the Changes:

1. View Statistics tab

## Known Issues and TODO List:

- One more value in the packet should be 1 if it is a failed timed criteria, but I don't think this is ever used and would need some new functions so I didn't fix it. I left a TODO in case we are want to properly fix it later.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by tkn963** [comment]
A little sad that **Critters killed** still doesn't work but the rest seems fine. Did only a limited amount of tests on the statistics since I don't know specifically what needs testing and there were no issues.

**Comment by ZhengPeiRu21** [comment]
> A little sad that **Critters killed** still doesn't work but the rest seems fine. Did only a limited amount of tests on the statistics since I don't know specifically what needs testing but there were no issues.

Critters killed is I think an unrelated issue. I will look at fix that soon too!

**Comment by Maelthyrr** [comment]
Tested too, not check everything, but work fine. So I pass in to be merged. Thanks :)

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Comment by JustVityok** [comment]
Still doesn't work for me sadly, Average gold per day is the same as Total gold, Legendary items is still the same as Epic items. At least average quests is now different from Total quests

**Comment by tkn963** [comment]
> Still doesn't work for me sadly, Average gold per day is the same as Total gold, Legendary items is still the same as Epic items. At least average quests is now different from Total quests

Could you create a bug report for this? I notice the same thing along with several other statistics showing the wrong values. There were quite a few I couldn't test when testing this PR that I'm now noticing after playing for some time.

**Comment by JustVityok** [comment]
> > Still doesn't work for me sadly, Average gold per day is the same as Total gold, Legendary items is still the same as Epic items. At least average quests is now different from Total quests
> 
> Could you create a bug report for this? I notice the same thing along with several other statistics showing the wrong values. There were quite a few I couldn't test when testing this PR that I'm now noticing after playing for some time.

created it before, got linked to this one and closed. should i link it here again?

**Comment by ZhengPeiRu21** [comment]
I am surprising to hear this is not work for you. Average gold per day is the statistic I was check when testing this PR and seems to working for me. Is it not working for you on a local instance or just on ChromieCraft?

**Comment by JustVityok** [comment]
> I am surprising to hear this is not work for you. Average gold per day is the statistic I was check when testing this PR and seems to working for me. Is it not working for you on a local instance or just on ChromieCraft?

never tried local instance, will try later (or ptr). On ChromieCraft gold and rare/legendary items were never fixed, but quests ARE fixed after my bugreport.

**Comment by ZhengPeiRu21** [comment]
Very strange! It is working for me currently on local Windows test server, but not working on ChromieCraft. I wonder if this is a platform specific issue. I suspect it may be working on Windows but not on Linux. Are other Windows users able to verify it is working? Are other Linux users able to verify it is not working?

**Pull request merged**
