### PR TITLE
fix(Core): Implement ACHIEVEMENT_CRITERIA_TYPE_OWN_RANK

### PR DESCRIPTION
**Pull request by sudlud**
## Changes Proposed:
This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Progress #1418

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

Alliance
.title add 1
.title add 2
.title add 3
.title add 4
.title add 5
.title add 6
.title add 7
.title add 8
.title add 9
.title add 10
.title add 11
.title add 12
.title add 13
.title add 14

Horde
.title add 15
.title add 16
.title add 17
.title add 18
.title add 19
.title add 20
.title add 21
.title add 22
.title add 23
.title add 24
.title add 25
.title add 26
.title add 27
.title add 28

The achievement (in the category "Feats of strength") will be granted according to each title.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Makes progress towards #1418, no?

**Comment by sudlud** [comment]
#1418 focus is for 2 other unimplemented criterias which is why I didn't link it - but yes in general it's progress towards implementing unsupported achievement criteria.

**Review by Kitzunu — APPROVED** [review]

**Comment by sudlud** [comment]
Thanks for the review @Kitzunu !
I just added a follow-up commit because of a minor oversight on my side, now the DB gets properly checked for achievement criteria data of the new criteria type on server startup.

**Comment by TimekillerTK** [comment]
Tested. 

> NOTE: Though not in the screenshots, I confirmed that all 14 ranks appear in Feats of Strength for both Alliance and Horde characters.

### Before
* Gaining titles **does not** give you feats of strength

Alliance

image


Horde

image

---

### After

* Gaining titles **does** give you feats of strength


Alliance

image


Horde

image

**Comment by sudlud** [comment]
I just learned about mod-pvp-titles, which should profit from this implementation.

**Comment by Kitzunu** [comment]
Thanks for the PR !

**Pull request merged**
