### PR TITLE
fix(DB/creature_template): Improve Ulduar

### LINKED ISSUE #3552: (Raid-Ulduar) Wrong damage in bosses
##### CURRENT BEHAVIOUR:

The current damage of Ulduar bosses they are very superior to those of blizzard.
Here are some examples.
ignis 25
hodir 25
thorim 25
freya 25
mimiron 25
vezax 25
vezax 10

Almost all bosses have the wrong damage and this happens in mode 10 and 25 but at the moment I could only find this.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The damage inflicted by the bosses is shown in the following videos:
Ignis 10
https://www.youtube.com/watch?v=dXVOTCBbTgM
https://www.youtube.com/watch?v=vVZ-df9kfTk
Ignis 25
https://www.youtube.com/watch?v=Plxi6jaBcJ0
https://www.youtube.com/watch?v=2pNvPmaS3-w
https://www.youtube.com/watch?v=q5hQ6xgBTfc
Hodir 10
https://www.youtube.com/watch?v=wmJz7OkYiFo
hodir 25
https://www.youtube.com/watch?v=e1LRW0YaKyg
https://www.youtube.com/watch?v=auxb6AGzuqM
https://www.youtube.com/watch?v=D-Xg6sALfA8
https://www.youtube.com/watch?v=bvhACGHhdGw
https://www.youtube.com/watch?v=k0lORzSHDp4
Thorim 25  (seems to have the correct damage)
https://www.youtube.com/watch?v=6Lvk8XReW1I  
https://www.youtube.com/watch?v=PNT9tSxFDeg  
https://www.youtube.com/watch?v=JLYZykH8eQs  
https://www.youtube.com/watch?v=qk7naVKc3kU 
Freya 10
https://www.youtube.com/watch?v=qTpDaZWOYeU
https://www.youtube.com/watch?v=S9cBUWnXn9I
https://www.youtube.com/watch?v=1leHv611P5g
Freya 25
https://www.youtube.com/watch?v=7wxv88pA3Ew   (Min 3:05)
https://www.youtube.com/watch?v=RRrnn2W871k
Mimiron 10
https://www.youtube.com/watch?v=VtkouIxacBI
https://www.youtube.com/watch?v=37U7-gBwpFs
https://www.youtube.com/watch?v=Vcqe4JBcQDo
https://www.youtube.com/watch?v=MHqySgIKWTY
Mimiron 25
https://www.youtube.com/watch?v=yePAlisR3Pk
https://www.youtube.com/watch?v=A3lUI3vCzbA
https://www.youtube.com/watch?v=W640JPmABjk
Vezax 10
https://www.youtube.com/watch?v=I_ss8HpM_X4
https://www.youtube.com/watch?v=LKRTgGI4bBI
https://www.youtube.com/watch?v=Gq2LVApE8zM
https://www.youtube.com/watch?v=TckFS3KtLFc
vezax 25
https://www.youtube.com/watch?v=ACDRJuARk2k
https://www.youtube.com/watch?v=lKm4g6pT15U
https://www.youtube.com/watch?v=nBVc6U6YRoM

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a character that can tank
2. .learn 25899  .learn 48470  .learn 16237  .learn 58753  .learn 48942  .modify hp 500000  .learn 62892 (Heal)
3. Get tank gear and reach a minimum of 24k armor without buff
4. Learn tank talents.
5. Go to Ulduar.
6. buff on me and spam ancestral fortitude (16237).
##### EXTRA NOTES:

It is very important to take damage with all the buffs on ... and this is because in raid these buffs are always active.
The buffs mentioned above reduce damage taken.
I recommend doing damage tests with 65% physical damage reduction
Don't forget the paladin's aura.
Spam Ancestral Fortitude.
image

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/93310310-raid-ulduar-wrong-damage-in-bosses?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Knindzagxg**
Changes:

Min, Max & Modifier Damage for whole Raid.

How to test:
Apply SQL
Restart Server and delete your Cache.
Make sure to add basic tanking gear towards Raid ilevel.

Also, you can check #3552 to get more idea what you will need for testing.

Should also close #3552 

Note: You wont be able to survive some mechanics where second tank is required - Use one more account on those fights.

### CODE REVIEW

**Comment by Knindzagxg** [comment]
Will do a bit more checking tomorrow, i wanna be sure about something.

**Comment by aradep** [comment]
instead of 1.01 damagemodifier could it just be 1 and then increase the min/max dmg by 1%?

**Comment by Si1ker** [comment]
@Knindzagxg  Check our closed PRs to get an idea why the suggestion from @aradep would be bad.
#2773 
#2766 

CC @FrancescoBorzi and @BarbzYHOOL 

I fear this is all breaking stuff... I will confirm later 'cause I don't have time now.. D:

**Comment by BarbzYHOOL** [comment]
> instead of 1.01 damagemodifier could it just be 1 and then increase the min/max dmg by 1%?

Yes, I also don't know why we should not use dmgmodifier 1, nobody could enlighten me on this topic

However, we can still change all the dmgmodifier and minmax dmg at once in the future with a smart query, so it's not that big of a deal. What is important is that the mobs have correct/logic dmg

**Comment by Knindzagxg** [comment]
Im fully checking about modifier.
Looks like it have to be there, and need to be even higher (Up to 5x)

Last night i found that spells and some mechanics scales with this, and that can be reason why sometimes we have lower damage then supposed.

Psy damage is not big deal, its very easy to sort - Im more worried about that multiplier when some tanking mechanics will be with % of basic damage and attack power.

But will know more in next few days.
Wait for few more cross db checks and some info.

**Comment by Knindzagxg** [comment]
Ready for full testing.

**Review by Helias — APPROVED** [review]

**Comment by iyasenai** [comment]
Apply the changes and these were the results

Ulduar 25

Damage_Ulduar
Assembly of Iron

Ulduar 10
Damage_Ulduar 10
Assembly of Iron  10

**Comment by Knindzagxg** [comment]
Finally, we are golden now mate.

Thanks again for retesting xD

**Comment by aradep** [comment]
Boss damage seems a bit overtuned. (50k-70k) https://wotlkdb.com/?npc=33190 shows lower values, (32k-45k) not sure how accurate they are though.

**Review by Si1ker — APPROVED** [review]

**Comment by BarbzYHOOL** [comment]
@aradep, your link is just a TC database, it means nothing.

So you reduced damage Knindza? I hope it's not too easy now lol

**Comment by Knindzagxg** [comment]
@aradep 

Nah mate.
45k damage in values on Nax geared tank is something about 12-13k on hit, and that's how it should be on Normal xP
Furnace can hit up to 35k on tanks, depending on strat and Constructors buffs.

**Pull request merged**
