### PR TITLE
Split playerBytes fields in characters table

### PR DESCRIPTION
**Pull request by Nefertumm**
**Changes proposed:**

-  Split playerBytes field in characters table, imported from TrinityCore/TrinityCore@1925778e44a370b26ae8f16b76279f62d20fb5be

**Target branch(es):** master

**Issues addressed:** Updates #236 

**Tests performed:** Tested and working. Will be better if anyone test it too :)

**Known issues and TODO list:** None

### CODE REVIEW

**Comment by ShinDarth** [comment]
good job!

**Comment by Gooyeth** [comment]
It can be applied?

**Comment by BarbzYHOOL** [comment]
Probably but needs someone to test (and know what it is about :D)

**Comment by Viste** [comment]
Add this PR to source for migration TC -> sunwell, post result later when all be done(tested)

**Comment by Viste** [comment]
All works fine! we can merge it!

**Comment by Yehonal** [comment]
I think we should revert it: https://github.com/azerothcore/azerothcore-wotlk/issues/850

**Comment by ShinDarth** [comment]
I think we should just fix the pdump, @Nefertumm can you please have a look at it?

**Comment by BarbzYHOOL** [comment]
@Viste  is looking at it at the moment and will open a PR

**Pull request merged**
