### PR TITLE
fix(Core/Warden): Fixed random kicks caused by warden.

### LINKED ISSUE #5017: Issue with Warden
## CURRENT BEHAVIOUR:

The client gets kicked after a certain amount of time. For me, this appears to occur after 60 to 80 minutes of being in-game. The server does not crash, and the client can log back in again instantly. I can be in the middle of fighting when I'm suddenly kicked out of the game

## EXPECTED BLIZZLIKE BEHAVIOUR:

The client should not get kicked for no real reason

## SOURCE:

N/A

## STEPS TO REPRODUCE THE PROBLEM:

1. Compile the source, import the databases etc
2. Leave all configs as default, make sure warden is enabled, and set LogDebugMask to 75497537 to get some extra info in the console
3. Start the server and log in using the client
4. Run around and do stuff or be semi-idle, just make sure not to let yourself go AFK
5. After a certain amount of time you will be kicked out of the game

## EXTRA NOTES:

I have unfortunately not tested older versions of the core as I only started using it a couple of days ago and was told off on Discord when even mentioning trying older versions
The first break point I get is "_session->KickPlayer("Warden: clientResponseTimer > maxClientResponseDelay (Warden::Update)");" from Warden.cpp
After several days of research and testing, I can finally say that I believe this to be the fault of Warden. Disabling Warden in the worldconfig seems to fix the issue
The "Unable to read memory" I really have no idea what that's about

kickplayer1
kickplayer2

## AC HASH/COMMIT:

7067696f83c6ccb8c4f9ecc316ccf9be70693c03

## OPERATING SYSTEM:

Windows 10, Ubuntu 20.04, Ubuntu 20.10

## MODULES:

None

## CUSTOMIZATIONS:

Nothing

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97451522-issue-with-warden?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Removed any action from false positive warden check.
Fixed #5017

## Changes Proposed:
-  Added to `warden_action` overriden entry.
-  

## Issues Addressed:
- Closes #5017

## Tests Performed:

- 
- 

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
In AC, the core table name is warden_ checks

**Comment by UltraNix** [comment]
It's character database, not world.

**Comment by pklloveyou** [comment]
It doesn't work. The character is offline automatically

**Comment by UltraNix** [comment]
@pklloveyou What? I have no problems with logging.

**Comment by pklloveyou** [comment]
Warden.Enabled = 0
Warden.ClientResponseDelay = 1
The character is automatically offline after a period of time

**Comment by UltraNix** [comment]
Set `Warden.ClientCheckFailAction = 2` and then once you got banned, show me the ban reason.

**Comment by pklloveyou** [comment]
image

**Comment by pklloveyou** [comment]
The reason is not shown

**Comment by UltraNix** [comment]
So it's not a ban, only kick form server?

**Comment by pklloveyou** [comment]
I cleared the "warden_checks" table . He still automatically kicks out players. I found that this error occurred when #4827 was updated.

**Comment by hahalmtdhl** [comment]
I had the same problem. It's not solved yet.

https://github.com/azerothcore/azerothcore-wotlk/issues/5031

**Comment by UltraNix** [comment]
@pklloveyou @hahalmtdhl @disclosurez @mpfans Test again with new changes.

**Comment by FrancescoBorzi** [comment]
cc @Footman

**Comment by pklloveyou** [comment]
Wait for a while to see if it will be offline

**Comment by pklloveyou** [comment]
Or offline

**Comment by pklloveyou** [comment]
image
They're offline here

**Comment by pklloveyou** [comment]
I seem to have found the reason

**Comment by pklloveyou** [comment]
image
I'll try it on

**Comment by pklloveyou** [comment]
I don't know why the client doesn't send WARDEN_CMSG_CHEAT_CHECKS_RESULT packets

**Comment by hahalmtdhl** [comment]
This time, the modification was very successful. I waited for 3 hours, but I didn't force logout before it appeared. @FrancescoBorzi FrancescoBorzi

**Comment by pklloveyou** [comment]
Warden.ClientResponseDelay = 20 You try this

**Comment by UltraNix** [comment]
Why you even changed that to 20?

**Comment by mpfans** [comment]
I'm testing, please wait for my feedback

**Comment by pklloveyou** [comment]
Maybe we should limit the scope of the options

**Comment by mpfans** [comment]
The test lasted about 2 hours. There were no random kicks and no false positives

**Comment by UltraNix** [comment]
So it's okay now?

**Comment by disclosurez** [comment]
confirmed fixed with latest change

**Comment by UltraNix** [comment]
Thanks for your feedback.
@FrancescoBorzi Hit it!

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @UltraNix @mpfans @pklloveyou and @disclosurez

**Pull request merged**
