### PR TITLE
feat (Core/Script): Color coded Item Lookup

### PR DESCRIPTION
**Pull request by pklloveyou**
## Changes Proposed:
```sql
UPDATE `acore_string` SET `content_default`='%d - |c%s|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r' WHERE `entry`=512;
```
image

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Nyeriah thoughts? Color coding item by rarity on the look up.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Does sql need adjustment? If so include sql file.

**Comment by Nyeriah** [comment]
I think it doesn't do harm

**Comment by pklloveyou** [comment]
I don't know how to submit SQL, O.o!

**Comment by pklloveyou** [comment]
oh I have learned it.

**Review by acidmanifesto — APPROVED** [review]
Unless there is another dev with questions or objections, i will be approving thise once someone confirms independent testing.

**Comment by temperrr** [comment]
image

**Comment by IntelligentQuantum** [comment]
@temperrr 

```sql
UPDATE `acore_string` SET `content_default`='%d - |c%s|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r' WHERE `entry`=512;
```

**Comment by temperrr** [comment]
I had the sql applied to my database

**Comment by temperrr** [comment]
nop same error

**Pull request closed without merging**
