### PR TITLE
fix(Core/Arenas): Fixed getting correct battleground status in case o…

### LINKED ISSUE #7278: Last person to leave arena doesn't count as a loss
### Current Behaviour

The last person of an losing arena team that leaves before the match end don't count as a loss.
The team and the players that lost the match does lose rating/MMR, except the last player, if he leaves.

In this video we can see this issue:
https://www.youtube.com/watch?v=XXb96vzzTU8
First player that leaves the match before it ends loses 4 personal rating (988>984), and the second player keeps the 1201 personal rating after leaving.

### Expected Blizzlike Behaviour

All players of the arena team should lose personal rating/mmr if their arena team lost the match.

### Source

_No response_

### Steps to reproduce the problem

1. enter arena 2x2 or 3x3
2. wait for your friend(s) to die or tell him/them to leave
3. (while out of combat) leave arena
4. check your personal score/rating and your arena team score/rating

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…f people leaving arena.

Fixed #7278

## Changes Proposed:
-  Fixed getting correct battleground status in case of people leaving arena

## Issues Addressed:

- Closes #7278

## Tests Performed:

- Not tested

## How to Test the Changes:

1. enter arena 2x2 or 3x3
2. wait for your friend(s) to die or tell him/them to leave
3. (while out of combat) leave arena
4. check your personal score/rating and your arena team score/rating

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by laasker** [comment]
Tested, now players that leaves before the match end now lose rating. 
:-)

**Comment by FrancescoBorzi** [comment]
@laasker thanks a lot for testing this. Have you also checked any potential (undesired) collateral effects? You should generally do it when testing C++ PRs.

> REMEMBER: when testing a PR that changes something generic (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but especially check that the PR does not cause any regression (i.e. introducing new bugs).

> For example: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but we should test Y and Z as well.

**Comment by laasker** [comment]
> @laasker thanks a lot for testing this. Have you also checked any potential (undesired) collateral effects? You should generally do it when testing C++ PRs.
> 
> > REMEMBER: when testing a PR that changes something generic (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but especially check that the PR does not cause any regression (i.e. introducing new bugs).
> 
> > For example: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but we should test Y and Z as well.

Not yet, i plan to open a server which can get ~100 online players, so it will be easier and faster to test and see if there is a collateral effects, but for now i can only test solo on my local server sadly.

**Comment by FrancescoBorzi** [comment]
> > @laasker thanks a lot for testing this. Have you also checked any potential (undesired) collateral effects? You should generally do it when testing C++ PRs.
> > > REMEMBER: when testing a PR that changes something generic (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but especially check that the PR does not cause any regression (i.e. introducing new bugs).
> > 
> > 
> > > For example: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but we should test Y and Z as well.
> 
> Not yet, i plan to open a server which can get ~100 online players, so it will be easier and faster to test and see if there is a collateral effects, but for now i can only test solo on my local server sadly.

it's ok, what I'm just saying is don't try to only test the specific bug but also try to do some quick check on the generic thing that has been worked on (in this case Arenas/BGs)

**Review by Helias — APPROVED** [review]

**Review by Kitzunu — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by cihankaracom** [comment]
> Tested, now players that leaves before the match end now lose rating. :-)

If players leave before the match starts, they should lose ratings, but that doesn't happen. Am I wrong?

**Pull request merged**
