### PR TITLE
refactor(DB/Broadcast_text): Change column names

### PR DESCRIPTION
**Pull request by Kitzunu**
## CHANGES PROPOSED:
* Give unk columns proper names

* Rename EmoteID/Delay 0-2 to 1-3
Why: Because 1-3 makes more sense

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2959

## TESTS PERFORMED:
- Builds
- Worldserver runs

## HOW TO TEST THE CHANGES:

1. Run worldserver

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
yes but what about the code that supposedly make use of these columns?

if they have a name, then they must have a usage

if they have no name, then they have no code related probably

**Comment by Kitzunu** [comment]
image
they are used, names are from TC

**Comment by merdlin** [comment]
tested, it works.

**Comment by BarbzYHOOL** [comment]
they have values but are the values handled by the core? what happens if you put 6, 0, 1 or 15000??

**Comment by Kitzunu** [comment]
Dont ask me, I just rename x)

**Comment by BarbzYHOOL** [comment]
if it does nothing and you see a good name, you don't expect it to do nothing but if you see "unk" you know it's not working, so need to know what it's for

plz someone check and save us from this trouble: what do these do??

**Comment by BarbzYHOOL** [comment]
wait

**Comment by FrancescoBorzi** [comment]
why closing this?

**Comment by Kitzunu** [comment]
Because Barbz don't want the changes because we don't what the columns do (and I don't know where to look)

**Pull request closed without merging**
