### PR TITLE
fix(DB/creature_template): Improve damage

### PR DESCRIPTION
**Pull request by Knindzagxg**
Been checking whole night about Modifier and recent fixes we pushed towards Classic Dungeons.

There were some mistakes and Blackrock Depts were not finished.
Now, we finally have match with average damage on boss fights that is confirmed trough Beastiary and other databases.

In next few days, i will run full check on TBC Dungeons.
@Si1ker already have PR for TBC Raids - Did check last night as well and everything is perfect.
Will only need to change modifier to 1.01 - Reopen your PR mate.

Also, i will finish my Wotlk PR's tomorrow or during week, just wanna be fully sure and do all checks first.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by BarbzYHOOL** [comment]
Well done guys, I'm really happy that nobody's work got wasted!! @knindzagxg @si1ker

so this PR is for blackrock depths?

**Comment by Knindzagxg** [comment]
Yeah, BRD included and few got buffed as well.

**Comment by Si1ker** [comment]
@Knindzagxg  so what? should I reopen both PRs?  they are for instances and raids from TBC

**Comment by Knindzagxg** [comment]
Raids are good and thouth u already reopened for it.

Dungeons need to be updated due new LFG buff / stat.
I will look into it next week.

Open for Raid if u can today, ill do another check if need.

**Comment by Geekena** [comment]
damage and spells are ok
didnt had problems in test
blackrock take lot of time to finish

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
