### PR TITLE
fix(DB/Creature): Commander Felstrom Infinite Loot Farm

### PR DESCRIPTION
**Pull request by avarishd**
Unsure if this is the proper way to do this, but it works.
Additionally, **I don't know how to stop giving EXP through SAI,** without messing with the spell's properties.
## Changes Proposed:
-  Set dynamicflag 128 on spell hit and despawn corpse after 2s

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6129

## SOURCE:

https://www.youtube.com/watch?v=DaMBxAdcslw - Corpse stays for 1-2 seconds
## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. .go c 5126 - and look for the NPC in the rooms around (multiple spawns) /tar Commander
2. Bring him to low HP: 1-120 Hp. / .damage 1050 
3. Let him finish his cast
4. Notice he is unlootable and corpse despawns
5. Kill him without letting the the cast to go off, he is lootable 

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Tested and working 👍

**Comment by mpfans** [comment]
tested and work.
```
I don't know how to stop giving EXP through SAI
```
If the spell is successful, do you not calculate the kill, so you don't need to give experience value?

**Comment by avarishd** [comment]
> If the spell is successful, do you not calculate the kill, so you don't need to give experience value?

Perhaps SPELL_EFFECT_INSTAKILL should reset all damage calculations so it doesn't give any credit, but this is unknown.
Also there is no option in SAI (Unless I'm blind) to disable EXP (maybe can be added?)

**Comment by mpfans** [comment]
> > If the spell is successful, do you not calculate the kill, so you don't need to give experience value?
> 
> Perhaps SPELL_EFFECT_INSTAKILL should reset all damage calculations so it doesn't give any credit, but this is unknown. Also there is no option in SAI (Unless I'm blind) to disable EXP (maybe can be added?)

Is it better to restore health after successful casting?

**Comment by avarishd** [comment]
> Is it better to restore health after successful casting?

No, https://db.rising-gods.de/?spell=3488

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
