### PR TITLE
Fix(Core/Quest): Correct add locale in quest

### LINKED ISSUE #1554: The Quest Completed text will not be translated from english to german
SMALL DESCRIPTION:

The quest is not translated correctly from English to German 
Quest name True translated
Details True Translated
Objectives Votes Oversees
CompletedText Is not translated although available in quest_template_locale

CURRENT BEHAVIOUR:

CompletedText Not translated

STEPS TO REPRODUCE THE PROBLEM:

Create Character
Accept Quest 
Finish Quest 
View CompletedText is not translated

EXTRA NOTES:

BRANCH(ES):
master

AC HASH/COMMIT:
AzerothCore rev. 5348d9cbe590 2019-03-03 16:33:17 +0100 (master branch) (Win64, Release)

OPERATING SYSTEM:
Win10

MODULES:
transmog

I hope I filled everything in correctly.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/70863023-the-quest-completed-text-will-not-be-translated-from-english-to-german?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
-  Correct add locale in quest

###### ISSUES ADDRESSED:
Close #1554

##### TESTS PERFORMED:
- [x] Test build in MSVS 16 2019

##### HOW TO TEST THE CHANGES:
1. Check complete text in a quest
2. Apply pr
3. Check complete text in a quest

##### KNOWN ISSUES AND TODO LIST:
- [x] Build in Travis
- [x] Test in game **not default locale**

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Nefertumm** [comment]
Nice catch.

**Comment by Nefertumm** [comment]
Tested with esES locale and it works as it should. The only thing left is fill the quest_offer_reward_locale, that only has german translations.

**Comment by FrancescoBorzi** [comment]
good job @Winfidonarleyan and @Nefertumm  !

**Comment by Winfidonarleyan** [comment]
Perfect, thanks a lot @Nefertumm.

**Pull request merged**
