### PR TITLE
fix(DB/creatures): Correct BaseAttackTime and RangeAttackTime

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  "normalize" attack speeds using a [TC commit](https://github.com/vmangos/core/blob/4a1083821eecdd77129e053e9c77b966c15f6924)
~~-  copy vmangos values as they are hopefully more accurate~~
- Import 2 [commits](https://github.com/vmangos/core/commit/4a1083821eecdd77129e053e9c77b966c15f6924) from [vmangos](https://github.com/vmangos/core/commit/f0a1fbfc87d97d8a876bf569ca9eb09729714cdd) 

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4524

## Tests Performed:
- Checked a few values, I really don't know if either are true.

## How to Test the Changes:

- Check out the before/after values for your favorite changed creature

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by T1ti** [comment]
seems good to me

**Comment by Zoidwaffle** [comment]
True, so are their guesses better than our guesses? Let me check my random number generator fast! :smile:

**Comment by T1ti** [comment]
There are some tricks to verify if a creature attack speed is correct, if it's a normal non unique creature, chances are he will probably have a default 1x attack value

you can divide the default CLS attack dmg value to the speed to verify if it matches, I used this trick here

**Comment by T1ti** [comment]
`UPDATE `creature_template` SET `BaseAttackTime`=1258 WHERE `entry`=2641; -- 'Vilebranch Headhunter' BaseAttackTime was 2000
`
I have a doubt about this one, value seems weird.
maths time : 
confirmed dmg from the book : 77-105
image
With 2.0 speed (in trinity core DB)
the CLS returns the correct damages
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=2641 (aowow is the Trinity core database, it calculates dmg from the CLS with attack speed)

So 2000 was correct, and vmangos is wrong here.

So I suggest only using the confirmed and sniffed data

**Comment by Zoidwaffle** [comment]
Check, I hear what you are saying - and I will make an update to the PR.

**Comment by FrancescoBorzi** [comment]
cc @Knindzagxg

**Comment by Zoidwaffle** [comment]
@T1ti : OK, so I totally skipped the DB comparisons and simple carried over 3 patches (1 TC, 2 vmangos) as one commit.

After this is done, if needed, I can always compare data again and see how many places we still differ... If needed.

**Comment by Knindzagxg** [comment]
@Zoidwaffle 

Can you remove everything that will modify speed and make new PR?
For damage everything seems fine, and that part is ok.

```UPDATE `creature_template` SET `speed_run`=4.28571 WHERE `entry`=11583;```

This is one that kinda worry me again -> It's about Nefarian and he shouldnt be that fast.
Sniffs sometime gonna calculate movement as higher speed cause of blinks and other effects.
There are few more with higher or regular, but need more time to test it properly.

We will need to check deeply, cause there was a lot of issues that some NPC had higher speed then supposed and players were not able to kite (Even on some boss fights where Boss fixate on them)

**Comment by T1ti** [comment]
> @Zoidwaffle
> 
> Can you remove everything that will modify speed and make new PR?
> For damage everything seems fine, and that part is ok.
> 
> `` UPDATE `creature_template` SET `speed_run`=4.28571 WHERE `entry`=11583; ``
> 
> This is one that kinda worry me again -> It's about Nefarian and he shouldnt be that fast.
> Sniffs sometime gonna calculate movement as higher speed cause of blinks and other effects.
> There are few more with higher or regular, but need more time to test it properly.
> 
> We will need to check deeply, cause there was a lot of issues that some NPC had higher speed then supposed and players were not able to kite (Even on some boss fights where Boss fixate on them)

there's a single fix commit for nefarian that needs to be ported

**Comment by Zoidwaffle** [comment]
@Knindzagxg : speed_run adjustments have been removed now.

@T1ti : Yeah, I guess a speed PR should include that.

**Comment by Knindzagxg** [comment]
Much better now.
Ill check speed as well, just need more time.

**Review by Knindzagxg — APPROVED** [review]

**Comment by pklloveyou** [comment]
It feels better than before

**Comment by T1ti** [comment]
https://github.com/TrinityCore/TrinityCore/commit/b7b1c2df790f1eb9203f084045e90ee5f9e1ebb5

TC decided to change ALL ranged attack times to default (2000)

**Comment by Zoidwaffle** [comment]
@T1ti  - yep, but that belongs in a PR outside of here. I can make it later unless you do it :smiley:

**Pull request merged**
