### PR TITLE
fix(DB/Creature): FixCreature Sporebat+Greater Sporebat+Young Sporebat+Sporewing

### PR DESCRIPTION
**Pull request by Selyria**
The creatures Sporebat+Greater Sporebat+Young Sporebat+Sporewing should occupy the player with the spell Energizing Spores at death

Creatur ID 18128,18129,18280,20387

https://db.rising-gods.de/?spell=35336#used-by-npc

https://de.wowhead.com/spell=35336/energiereiche-sporen

Closes nothing

TESTS PERFORMED:
I tested it myself and it worked.

HOW TO TEST THE CHANGES:
.go c 64455
.go c 64559
.go c 72265
.go c 65571
Kill the creature and see if you got the buff.

Target branch(es):
Master

### CODE REVIEW

**Comment by Knindzagxg** [comment]
Aye, all good.

This reminds me to keep checking OL for more missing AI.

**Comment by Stoabrogga** [comment]
This could have been accomplished much easier using this simple update statement:
```sql
UPDATE `smart_scripts` SET `target_type` = 1 WHERE `entryorguid` IN (18128,18129,20387,18280) AND `source_type` = 0 AND `action_type` = 11 AND `action_param1` = 35336;
```
But the outcome is the same, so I think this is good to merge.

**Comment by BarbzYHOOL** [comment]
Wait, if this can be done in one line then why delete and reinsert??

**Comment by BarbzYHOOL** [comment]
wtf @poszer

**Comment by BarbzYHOOL** [comment]
next time i'll put a request changes

**Comment by poszer** [comment]
> wtf @poszer

What? It's approved, it's marked as To Be Merged o.O

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL just remove the `To be merged` label if you want to prevent a PR to be merged

**Comment by BarbzYHOOL** [comment]
true, i should have changed the labels, didn't thin kabout it (just asked a question and forgot)

**Comment by Selyria** [comment]
> true, i should have changed the labels, didn't think about it (just asked a question and forgot)

Another question: Where is the problem with sending SQL files for such a long time, is there any problem or is it just because of optics?

Am just a newbie in the sql area

**Comment by BarbzYHOOL** [comment]
What?

**Comment by Selyria** [comment]
you could have written it that way

UPDATE  ` smart_scripts `  SET  ` TARGET_TYPE `  =  1  WHERE  ` entryorguid `  IN ( 18128 , 18129 , 20387 , 18280 ) AND  ` source_type `  =  0  AND  ` action_type `  =  11  AND  ` action_param1 `  =  35336 ;

I just wrote it completely and uploaded it as PR 

Just want to know if that's a problem if you don't cut it short.

**Comment by BarbzYHOOL** [comment]
yes, it's much better to use the small version, it's easier to read, easier to debug, the repository is smaller and teaches you better practice :)

**Comment by Selyria** [comment]
> yes, it's much better to use the small version, it's easier to read, easier to debug, the repository is smaller and teaches you better practice :)

Okay, I'll try to take it over.

**Comment by FrancescoBorzi** [comment]
@Selyria FYI: I've updated your comment for better readability, by wrapping the SQL code using triple apex (`)

**Comment by BarbzYHOOL** [comment]
But once it's in the core, it's in the repository forever :P so no need to change this PR's code now @Selyria

**Pull request merged**
