### PR TITLE
CORE/Spell: fix Spell reflected doesn't create DR on reflecting spell target.

### PR DESCRIPTION
**Pull request by a4501150**
##### CHANGES PROPOSED:

-  fix Spell reflected doesn't create DR on reflecting spell target

###### ISSUES ADDRESSED:

Closes [650](https://github.com/azerothcore/azerothcore-wotlk/issues/650)

##### TESTS PERFORMED:

Tested in the game in the way the video shows

see [650](https://github.com/azerothcore/azerothcore-wotlk/issues/650)

##### KNOWN ISSUES AND TODO LIST:

- [x] whether the reflection spell caster should apply Diminishing?
for example, mage cast poly on a warrior. After warrior reflect 3 times, should the warrior be immune for poly?

##### Target branch(es):

Master

### CODE REVIEW

**Comment by a4501150** [comment]
It needs to be improve. The current behavior is that warrior would immune to poly if he reflect 3 times.

**Comment by santahashi** [comment]
So I've been testing this PR since it is published, many thanks to a4501150. 
It is working like intended, the server could also run fine without any errors.

**Comment by Knindzagxg** [comment]
Can confirm - Working perfect.

**Comment by BarbzYHOOL** [comment]
@a4501150 thank you very much!

@santahashi @Knindzagxg thank you guys for testing!!

**Pull request merged**
