### PR TITLE
fix(DB/Zone):improved Strangethorn Vale II

### PR DESCRIPTION
**Pull request by Knindzagxg**
Zone now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

### CODE REVIEW

**Comment by aradep** [comment]
All working except for Lesser Water Elemental(691) has no mana to cast Frost Nova.

**Comment by FrancescoBorzi** [comment]
@aradep

**Comment by Knindzagxg** [comment]
Updated @aradep 

Please, re-test as well xP

**Comment by aradep** [comment]
All good ⛄

**Comment by Knindzagxg** [comment]
Awesome xP

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
