### PR TITLE
[Raid] Ulduar

### PR DESCRIPTION
**Pull request by Knindzagxg**
Fix for Faceless Horror in Ulduar Heroic mode.

It was missing SAI that was using in Normal.

Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/3182

To check, apply SQL, reload creature_template and smart_scripts (Or server restart) and do Ulduar run.

### CODE REVIEW

**Comment by Kitzunu** [comment]
2020-08-06 15:54:30 Creature (Entry: 33772) lists difficulty 1 mode entry 33773 with `AIName` filled in. `AIName` of difficulty 0 mode creature is always used instead.

**Comment by pklloveyou** [comment]
image
image

**Comment by Knindzagxg** [comment]
> 
> 
> 2020-08-06 15:54:30 Creature (Entry: 33772) lists difficulty 1 mode entry 33773 with `AIName` filled in. `AIName` of difficulty 0 mode creature is always used instead.

Weird it's not working fully.
Mhm, ill look into more into it, just wanted to copy just incase.

**Comment by Knindzagxg** [comment]
Edit: I'm total idiot i linked same AI without adding new, that was missing from report.
Ignore for now, i will sort in a day or two.

**Comment by felwyn** [comment]
I was in Ulduar. We must change some movement and position patterns of some NPCs.

**Comment by Helias** [comment]
@felwyn thank you for testing, but this issue has been fixed with this PR?
https://github.com/azerothcore/azerothcore-wotlk/issues/3182

**Comment by felwyn** [comment]
Sadly when I encountered that Faceless Horror he only charged "Void Wave".

**Comment by FrancescoBorzi** [comment]
@Knindzagxg the build is failing, still need to fix the following error:

```
 Creature (Entry: 33772) lists difficulty 1 mode entry 33773 with `AIName` filled in. `AIName` of difficulty 0 mode creature is always used instead.
```

**Comment by Knindzagxg** [comment]
I still havent worked on this mate.
Atm, it using same AI as on normal, need to find what we need to sort via cpp for MC

**Comment by Knindzagxg** [comment]
Finally sorted @FrancescoBorzi.

Shield and add will now appear as supposed.
On death, shield will be removed from Void.

**Comment by Geekena** [comment]
need some time to reach for test
damage and spells are ok
no problems found

**Comment by Geekena** [comment]
also can we summon npc to test outside or need always to go in raid?

**Comment by Knindzagxg** [comment]
Some of them you can summon, but not all.
Depends on SAI, some of them are locked and will cast spells only inside instance.

Thanks for tests btw xD

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
