### PR TITLE
fix(Script/Spell): Gryphon/Wyvern Pet - Mounting Check Aura

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/5f71c40b969c07f950e3dceb99037c7685512e71)

## Changes Proposed:
-  Implement spell Gryphon/Wyvern Pet - Mounting Check Aura

## Tests Performed:

- Tested in-game, works

## How to Test the Changes:

2. .add 49662
3. Learn the pet
4. Summon the pet
5. See that if you are not mounted, it will run with you
6. see that when you are mounted, it will start to fly

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Now everything works as it should

**Comment by FrancescoBorzi** [comment]
> Now everything works as it should

except the build

```
Script named 'spell_gen_gryphon_wyvern_mount_check' is assigned in the database, but has no code!
```

**Comment by FrancescoBorzi** [comment]
@Kitzunu any news?

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers please check this

**Comment by claudiodfc** [comment]
Tested.
- When the player is on foot, the pet follows him/her around.
- When mounted on a ground mount, the pet switches to flight mode but stays on the ground.
- When mounted and flying, the pet switches to flight mode with the player.

image

**Pull request merged**
