### PR TITLE
chore(Common/Misc): Replace old macros with modern C++ attributes

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/5ae2a0f47d323fadcfebf44c7b6ec11a3f91c75a)

Co-Authored-By: Giacomo Pozzoni <giacomopoz@gmail.com>

## Changes Proposed:
-  Replace DECLSPEC_NORETURN to [[noreturn]]
-  Remove unused DECLSPEC_DEPRECATED

## Tests Performed:

- None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
`ATTR_NORETURN` delete

**Comment by Kitzunu** [comment]
Forgot x) Fixed

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
nice

**Comment by Kitzunu** [comment]
I was waiting for a comment from you haha. Was thinking of you when I cherry-picked XDDD

**Comment by FrancescoBorzi** [comment]
> I was waiting for a comment from you haha. Was thinking of you when I cherry-picked XDDD

I can't help it, I love replacing old crap with modern standards

**Comment by Winfidonarleyan** [comment]
> > I was waiting for a comment from you haha. Was thinking of you when I cherry-picked XDDD
> 
> I can't help it, I love replacing old crap with modern standards

Hmmmmm, I'll surprise you in early July

**Pull request merged**
