### PR TITLE
Core/Text: Implemented BroadcastText.

### PR DESCRIPTION
**Pull request by HeartWell**
**Changes proposed:**

-  Implemented broadcast_text and add localization locales_broadcast_text.

**Target branch(es):** 1.x.

**Issues addressed:** Closes #https://github.com/azerothcore/azerothcore-wotlk/issues/207

**Tests performed:** (Does it build, tested in-game, etc)

- Tested and working

### CODE REVIEW

**Comment by cooler-SAI** [comment]
will test it soon

**Comment by sucofog** [comment]
https://files.gitter.im/azerothcore/azerothcore/hzb3/blob

https://files.gitter.im/azerothcore/azerothcore/2Tvf/blob

Working as intended, waiting for locales :P

**Comment by pak3935** [comment]
Full
https://bitbucket.org/pak3935/sunwellcore3/commits/bc88636a061db17f0003eeced506780057dc4c05

**Comment by sucofog** [comment]
https://bitbucket.org/pak3935/sunwellcore3/commits/bc88636a061db17f0003eeced506780057dc4c05

Its working perfect, we should add the rest of the commit

**Comment by ShinDarth** [comment]
@sucofog feel free to open PR

**Pull request merged**
