### PR TITLE
DB: Fix Sen'jin Fetish model

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
The vanity pet "Sen'jin Fetish" has an invisible model assigned for modelid2. Through this PR this model is removed.

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
Tested in-game

##### HOW TO TEST THE CHANGES:
- ```.additem 45606```
- Use the item and summon the vanity pet; there's a 50% chance that you won't see a model
- Apply the SQL script
- ```.reload creature_template 33810```
- Resummon the pet

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by wetbrownsauce** [comment]
Tested. 30 summons in a row, all visible lol. As far as this PR is concerned, this works properly. 



However, the pet is supposed to have three possible models, not one. See: 
[Warcraft Pets Page](https://www.warcraftpets.com/wow-pets/undead/voodoo-companions/senjin-fetish/)
>When summoned, this pet will randomly appear using one of three different models, shown above at right.

[Youtube Video](https://www.youtube.com/watch?v=cDVyQxWHD7k)

It should also be floating off the ground, and might be too big in-game currently.

**Comment by FrancescoBorzi** [comment]
@wetbrownsauce @Stoabrogga is this incomplete or we can merge it ?

**Comment by FrancescoBorzi** [comment]
@wetbrownsauce generally speaking, if a PR only improves things without breaking anything I would always merge it and open a new issue for what's missing.

Feel free to merge it.

**Comment by wetbrownsauce** [comment]
Yeah, I was just thinking since it already alters model id it might as well put in the correct ones, but unfortunately I don't know what the correct ones are. I'll open an issue for it though

**Comment by Stoabrogga** [comment]
Sadly, it's not that easy. I tried to find appropriate models, but there are only passive doodads for this which cannot be used directly for modelid1-3. Also, in order to work correctly, there should be a drum sound when summoning the pet, so it all boils down to write a new custom AI for this. I just wanted to fix the invisible model with this PR, as a custom AI will take much more time to get it all right.

**Comment by wetbrownsauce** [comment]
Yeah I know, I spent a while trying to figure out if the displays were anywhere in the game files. The drum sound is already there though, but idk if it is the right sound file.

**Pull request merged**
