### PR TITLE
fix(DB/GO): move herbs outside of buildings

### LINKED ISSUE #6312: Alterac Mountains - Bruiseweed Growing Indoors in Strahnbrad
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [X] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/832

A Bruiseweed with Node ID 3564 seems to be spawning on the staircase inside the abandoned inn in Strahnbrad. My observed coordinates are at 61, 43. 

Wow_fi0VEe6rov

Tester: confirmed: 
WoWScrnShot_061121_205720

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Pretty sure plants aren't supposed to spawn inside buildings. My Gathermate data also suggests there should be no spawn here.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Either observe the node at coordinates 61, 43 in Alterac Mountains, or use ".go object 3564".

##### EXTRA NOTES:

First bug report, let me know if something is incomplete or missing. Thanks.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99123695-alterac-mountains-bruiseweed-growing-indoors-in-strahnbrad?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6314: Redridge Mountains - Bruiseweed Spawning Underneath Steps at Stonewatch
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/834

Noticed there was a Bruiseweed node at Stonewatch in Redridge Mountains that I couldn't reach. The Node ID is 85462 and it is located at 67, 56 in Redridge.

WoWScrnShot_061021_200957

Fired up my own local server to discover that using ".go object 85462" put me at the coordinates of 67, 56. This is underneath the stairs / inside the tower.

image

Tester: confirmed. It's unreachable through normal means.

WoWScrnShot_061121_212237
WoWScrnShot_061121_212242

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Nodes shouldn't be unreachable or clipped inside objects.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Observe Bruiseweed node being unreachable, either by using 'Find Herbs' or ".gobject near" at coordinates 67, 56 in Redridge Mountains. OTHERWISE just use ".go object 85462".

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cb1aaec4af13341816b65fea5ccbb4b44ef7a585

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99123693-redridge-mountains-bruiseweed-spawning-underneath-steps-at-stonewatch?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jamadaha**
## Changes Proposed:
-  Moves the herbs (GUID 3564 and 85462) to the nearest spot outside

## Issues Addressed:

- Closes #6312 
- Closes #6314

## SOURCE:

Before - 3564:
image

After - 3564:
image

Before - 85462:
image

After - 85462:
image

## Tests Performed:

- .go o 3564, 85462
- Observe

## How to Test the Changes:

1. .go o 3564, 85462
2. Observe

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]

**Comment by Asthalor** [comment]
Tested with server version  AzerothCore rev. 6e082e351393

Went to the first node and it spawned properly outside the building.

Inside the builing
noNode1

Outside the building 

noNode1FIX


Went to the second node, and i couldnt find it.
The command .go o 85462 spawned me on the place of the second one, but i couldnt find it.

newnode2

**Comment by jamadaha** [comment]
Thanks for testing!
The reason it didn't spawn in the second place is likely that it is in a pool.
Checked the DB, should have 25% chance of spawning (In pool of 207 with a spawn limit of 55)

**Comment by LukasVolgger** [comment]
So is it ready to be merged?

**Comment by jamadaha** [comment]
@LukasVolgger I think so? I don't know the requirements for a pull request to be merged.

**Comment by LukasVolgger** [comment]
> @Asthalor Thanks for testing!
> The reason it didn't spawn in the second place is likely that it is in a pool.
> Checked the DB, should have 25% chance of spawning (In pool of 207 with a spawn limit of 55)

Because of that

**Comment by jamadaha** [comment]
Ah. That's the intended behavior.

**Comment by LukasVolgger** [comment]
Thx @jamadaha and @Asthalor for this work!

**Pull request merged**
