### PR TITLE
fix(Scripts/Vehicles): The next player entering Salvaged Siege Engine…

### LINKED ISSUE #1317: [Ulduar] Salvaged Siege Engine
##### SMALL DESCRIPTION:

When a second player gets on, he doesn't occupy the empty space.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

When a player is on the vehicle, the second player should automatically move to the free place. However, this does not happen. 

##### CURRENT BEHAVIOUR:

https://www.wowhead.com/npc=33060/salvaged-siege-engine

Currently, if a player climbs when a partner is already there, he gets buggy and the only way to get back to normal is to disconnect. Since he doesn't have the button to get out of the vehicle.

<a href="http://subefotos.com/ver/?8cb967dd9e1b5f970beeb1c6aba72d8ao.jpg" target="_blank"></a>

##### STEPS TO REPRODUCE THE PROBLEM:

1. Assemble a raid of at least 2 players.
2. Get in the vehicle and ask a partner to do it.
3. It is important that we are in the part where the vehicle is driven. If we are in the back, the problem does not reproduce.

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

62b05683

##### OPERATING SYSTEM:

- Debian 9
- Windows 7

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/68894637-ulduar-salvaged-siege-engine?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
… should control turret if it's not occupied.

Fixes #1317

## Issues Addressed:

- Closes #1317

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Get 2 players
`.npc add temp 33060`
Both players enter the vehicle

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by mpfans** [comment]
tested,work now.

**Comment by mpfans** [comment]
sry.... There is still a bug
When the tank driver and co pilot are occupied, the third person still has an icon to board the tank
In the icon on the right, only the main driver can see his own icon. When the co pilot sees that the main driver has no players, he can also click the switch icon, but he can't switch to the main driving position
The third man boarded the tank and couldn't get down without any skills. He had to logout

https://youtu.be/aA4JDZSsXlw

**Comment by UltraNix** [comment]
About the 3rd person - this is not a bug. There are 4 seats there - main driver, turret and 2 doing nothing.
```
By Trinsick on 2009/05/04 (Patch 3.1.1)
Carries four people, but only two can do anything (the driver and the gunner). The other two are just passengers, so I would recommend only having two per vehicle. 
```

**Comment by mpfans** [comment]
> About the 3rd person - this is not a bug. There are 4 seats there - main driver, turret and 2 doing nothing.
> 
> ```
> By Trinsick on 2009/05/04 (Patch 3.1.1)
> Carries four people, but only two can do anything (the driver and the gunner). The other two are just passengers, so I would recommend only having two per vehicle. 
> ```

ok,However, when there are players in the driver's seat, the co driver sees that there are no players in the driver's seat. This is a bug.

and then third player should also have a jump down icon, or they can only log out
image

**Comment by UltraNix** [comment]
No, if the seat is not ejectable.

**Comment by mpfans** [comment]
> No, if the seat is not ejectable.

If the seat cannot be ejected, these players can only log out and will be ejected by the system, which is a bad experience Because these people never know whose tank has two passengers

**Comment by UltraNix** [comment]
There is nothing I can do about it. That icon is clientside and depends on vehicleid , which is correct. The main problem is resolved.

**Comment by mpfans** [comment]
> There is nothing I can do about it. That icon is clientside and depends on vehicleid , which is correct. The main problem is resolved.

ok

**Comment by mpfans** [comment]
Please merge as soon as possible, thank you!

**Comment by IntelligentQuantum** [comment]
@UltraNix 

```
 /home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/Northrend/Ulduar/Ulduar/ulduar.cpp:427:43: fatal error: unknown class name 'VehicleAI'; did you mean 'Vehicle'?
struct npc_salvaged_siege_engine : public VehicleAI
```

**Comment by UltraNix** [comment]
@IntelligentQuantum Fixed.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by skelUA** [comment]
Salvaged Siege Engine not work  :(

**Pull request merged**
