### PR TITLE
fix(Core): Crash

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Use the parameter to initialize a value...

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13291
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13275

## Tests Performed:

- Tested in-game.

## How to Test the Changes:

1. Read steps from https://github.com/azerothcore/azerothcore-wotlk/issues/13291
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
@kissingers @zranger1 @tweiser could you some of you guys test it, please?

**Comment by kissingers** [comment]
I test the two spell, before will and  now will not case the server crash. I will test more tales spell.


but the log still have when Druid change to big bar mode.
AuraEffect::HandleProcTriggerSpellAuraProc: Could not trigger spell 0 from aura 24932 proc, because the spell does not have an entry in Spell.dbc.

**Comment by Nefertumm** [comment]
Yes, this pr only fixes the crash. The log should be fixed on another pr.

**Comment by kissingers** [comment]
Already test 7 class, no crash anymore. It seems fixed.

**Comment by Nefertumm** [comment]
Thank you for testing

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
