### PR TITLE
fix(core/QuestHandler) question marks not shown

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10553
- Closes https://github.com/chromiecraft/chromiecraft/issues/2915
- Closes https://github.com/chromiecraft/chromiecraft/issues/7392

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. To reproduce the error, just take a mission, whose npc contains a gossip. After taking the mission and interacting with the NPC, to see the menu, you move far enough away from it until it disappears from your sight. When you approach him again, you will see that the sign above his head disappears, thus avoiding showing you the status of the mission (whether complete or incomplete). The only way to see the sign again is to exit the game and re-enter it. At that moment, the sign appears again.
2. After applying the pull request, perform the same action, and you will see that no matter how far you go, the sign will always remain above the npc's head, thus showing not only who to give the mission to, but also that also, its status (complete or incomplete)

WoWScrnShot_093024_130254

WoWScrnShot_093024_130130

WoWScrnShot_093024_130132

WoWScrnShot_093024_130144

WoWScrnShot_093024_131006

WoWScrnShot_093024_131019

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
I don't know if they are also related to these topics, that's why I didn't include them in the closes.
- https://github.com/azerothcore/azerothcore-wotlk/issues/8840
- https://github.com/azerothcore/azerothcore-wotlk/issues/7897
- https://github.com/azerothcore/azerothcore-wotlk/issues/18435
- https://github.com/azerothcore/azerothcore-wotlk/issues/13537

**Comment by pangolp** [comment]
I don't really understand why this change was made.
https://github.com/azerothcore/azerothcore-wotlk/pull/9962
Maybe it's incomplete and we should look for another solution.
Otherwise, the people who approved this, I don't know what result they were looking for.

**Comment by pangolp** [comment]
Now that I'm looking at it, it's not the same code, someone modified it later.
The original code might work, but the current one might not.
```c++
GossipMenu& gossipMenu = _player->PlayerTalkClass->GetGossipMenu();
// Did we already get get a gossip menu? if so no need to status query
if (!gossipMenu.Empty())
    return;
```

**Comment by heyitsbench** [comment]
Likely resolves https://github.com/chromiecraft/chromiecraft/issues/7392 as well.

**Comment by pangolp** [comment]
> Likely resolves https://github.com/chromiecraft/chromiecraft/issues/7392 as well.

I can try it.

**Comment by pangolp** [comment]
@heyitsbench That issue should be resolved, given that it is the same problem. Now I add it inside the classes, thank you.

**Review by Nefertumm — APPROVED** [review]
It seems like it doesn't regress any of the previous PRs that changed this piece of code before, although further testing is needed.

**Comment by TheSCREWEDSoftware** [comment]
In AzerothCore rev. e58c9cba422d 2024-09-23 10:31:03 +0000 (master branch) (Win64, RelWithDebInfo, Static) I'm having a hard time testing this issue was I've not been able to achive what's reported. 

In AzerothCore rev. e687c57eb6bd 2024-10-07 03:09:35 -0300 (pr/20099 branch) (Win64, RelWithDebInfo, Static) (yours) I can't achieve any of the issues above, which i pressume is good. But i can't test the issues on the build above. I'm aware that build is a month old.

Can someone give some feedback on this?

**Comment by pangolp** [comment]
> In AzerothCore rev. e58c9cba422d 2024-09-23 10:31:03 +0000 (master branch) (Win64, RelWithDebInfo, Static) I'm having a hard time testing this issue was I've not been able to achive what's reported. 
> 
> In AzerothCore rev. e687c57eb6bd 2024-10-07 03:09:35 -0300 (pr/20099 branch) (Win64, RelWithDebInfo, Static) (yours) I can't achieve any of the issues above, which i pressume is good. But i can't test the issues on the build above. I'm aware that build is a month old.
> 
> Can someone give some feedback on this?

I tried it when I did the pull request and then I didn't try it again. I could update the branch and test it again, but the problem is easy to try. You take a quest, you interact with the NPC that gave it to you (it has to have a menu), you get away enough (until you see it) and you get closer again. In doing so, the symbol on the head disappears. You can also add some logs or prints within the handle, and you'll see that the quest and the state don't load, they're ignored, because the menu has already been loaded. Then, if you disconnect and re-enter, having not interacted with the NPC, the symbol above your head, appears normally.

**Comment by pangolp** [comment]
This failure did not originate in the last month. ChromieCraft reports that talk about the situation indicate that it's a pretty old topic and I remember having reports of this last year, but then I really forget. I thought it was something in the player's pothole, but then I saw this, I tried it and it worked.

**Comment by TheSCREWEDSoftware** [comment]
Oky I see my issue there, was i didn't walk far enough, i did walk once or twice out of the render range but that didn't do anything had to walk more than that.

Can confirm the issue on any build previous to this commit and the fix on this commit.

Thanks for the clarification Pango

**Comment by TheSCREWEDSoftware** [comment]
[Youtube Video](https://www.youtube.com/watch?v=ftgU8RcUVJ8&ab_channel=TheSCREWEDSoftware) of my testing.

Has timestamp for Current and PR.

Tests shown:

1 - Getting the quest and going far
2 - Completing the quest (before going far)
3 - Completing the quest (after going far)

**Comment by pangolp** [comment]
Thank you for the test and the video.

**Comment by Nefertumm** [comment]
@TheSCREWEDSoftware could you take a look if you could reproduce the issue mentioned in [this pr](https://github.com/azerothcore/azerothcore-wotlk/pull/9962) to see if this pr causes no regressions?

**Comment by TheSCREWEDSoftware** [comment]
Yeah I can test it. Using PR of this pull and see if that PR is breaking currently?

**Comment by pangolp** [comment]
I can update the branch later if necessary.

**Comment by Nefertumm** [comment]
> Yeah I can test it. Using PR of this pull and see if that PR is breaking currently?

Exactly, thank you.

**Comment by TheSCREWEDSoftware** [comment]
I tried what both issues were mentioned in that PR. 

I never got the issue of having an interaction and nothing happening nor having the interaction skip the gossip.

Always gave me the gossip to browse her goodies and tha option opened the vendor panel. 

Also no errors on worldserver.exe

**Comment by Nefertumm** [comment]
Thank you @TheSCREWEDSoftware

**Pull request merged**
