### PR TITLE
fix(Scripts/ZulGurub): Fixed never-ending Thousand Blades during Rena…

### LINKED ISSUE #12078: [ZG] Edge of Madness - Renataki is casting Thousand Blades non-stop.
### Current Behaviour

After the first Thousand Blades cast, Renataki won't stop casting it until a Vanish, and when he returns he'll start casting Thousand Blades non-stop again.

### Expected Blizzlike Behaviour

Renataki casts Thousand Blades 2-5 times in succession, switching targets for every cast if possible.

### Source

Thousand Blades being used 5 times in a row: https://youtu.be/urX62TDf1gM?t=125
ditto: https://youtu.be/XgwrVqh76Us?t=25

### Steps to reproduce the problem

If the Summoning Event is implemented:
`.event stop 27`
`.event stop 28`
`.event stop 30`
`.event start 29`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Renataki

else:
`.go xyz -11905 -1911 66 309`
`.npc add temp 15084`

### Extra Notes

Reported in: https://github.com/chromiecraft/chromiecraft/issues/3629

Tested in https://github.com/azerothcore/azerothcore-wotlk/commit/4bc99f8070cf8f38452e18585a0ff668478a8510 as well

From fendwe

image

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36f0a7757bde9573262f298aa1eaf6765af8295e

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…taki encounter.

Fixes #12078

## Issues Addressed:

- Closes #12078
- Closes https://github.com/chromiecraft/chromiecraft/issues/3629

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.event stop 27`
`.event stop 28`
`.event stop 30`
`.event start 29`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Renataki

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Renataki only casts Thousand Blades once per event now.

**Review by IntelligentQuantum — APPROVED** [review]

**Review by acidmanifesto — DISMISSED** [review]
per CC Tester:
```
The thing is that he's supposed to cast Thousand Blades 2-5 times in sequence. 
When I tested he was only doing it once and not 2-5 times.
```

**Comment by UltraNix** [comment]
@Gultask Have you tested it with at least 4 people?

**Comment by Gultask** [comment]
Right. I should've thought of that :c 

It's working perfectly.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
