### PR TITLE
fix(Scripts/BlackwingLair): Chromaggus Affliction debuf should target…

### LINKED ISSUE #11125: [BWL] Chromaggus debuff should stagger over the raid.
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [X] 60

### Current Behaviour

The debuffs will be casted on all raid members at the same time

### Expected Blizzlike Behaviour

The debuffs should  be applied to 10-15 players only.

### Source

watch the raid frames top left.
https://youtu.be/MyH-OWhjxW4?t=1705

### Steps to reproduce the problem

Go to chromaggus with a raid group.

### AC rev. hash/commit

77f13636b75f

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
… max 15 players.

Fixes #11125

## Issues Addressed:

- Closes #11125

## Tests Performed:

- Not tested.

## How to Test the Changes:

Go to chromaggus with a raid group.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
Tested and work (you can see this on decursive panel, 15 people affected)


WoWScrnShot_032722_212318

**Comment by Lynethris** [comment]
@UltraNix I remove "to be merged" and pass it in "testing in progress" again. @temperrr think to have seenn an undesirable issue during my guild test on CC PTR. But he isn't sure that is related to this PR.

**Comment by temperrr** [comment]
I watched some videos, the maximum should be 12 on each ability:

green  8 - 1 - 2 - 7 
black  1 - 10 - 11 - 7 
blue  12 - 4 - 8
bronze 1 - 6 - 2 - 8
red 12 - 12 

https://www.youtube.com/watch?v=NjabDdTydlU

green - (1) 9 (2) 7 (5) 12 (12) 11
black (4) 10 (6) 11 (13) 12
blue  (7) 11 (11) 12
bronze (3) 11 (9) 8 (10) 8
red  (8) 5 (14) 7 (15) 10
(1 -> the order which it applied)
https://youtu.be/MyH-OWhjxW4?t=1695

**Comment by UltraNix** [comment]
@temperrr Done.

**Comment by temperrr** [comment]
Cheers, can you update the mod-progression-module one with this change, too? :)

**Comment by UltraNix** [comment]
Okay.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
