### PR TITLE
fix(DB/quest): quest should can see NPC

### PR DESCRIPTION
**Pull request by mpfans**
## Changes Proposed:
after update 2391f454c74d0cfb51235ee3ef288ad36d2c4e1b,`Forging an Alliance`(quest id 12924 ) can't see quest target NPC

## Tests Performed:

- tested ingame

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by avarishd** [comment]
After deleting `2022_05_07_00.sql` (the sql from the pr) and rebuilding world db `Njormeld` was not there either, so it is not related to the previously mentioned pr.

Additionally Njormeld (30127, guid 207219) has creature_template_addon [56768](https://db.rising-gods.de/?spell=56768) that could be a part of the problem

**Comment by avarishd** [comment]
Need to take https://db.rising-gods.de/?quest=12966 from King Jokkum (intended) in 12966 & 12967 in order for him to show.

**Comment by avarishd** [comment]
I just went back and tested without the mentioned PR (`2022_05_07_00`) and all worked properly, so _**it might be that the entire bug report was wrong, as such bug did not exist**._ 

[Video of me going trough the quests before the PR (clean world db, that sql was not imported)](https://www.youtube.com/watch?v=2GN5krOrlxM) [MY WORLD DB, before the pr](https://i.gyazo.com/fe423f48a380f2ee732fca3e85e54d84.png)
I start Forging An Alliance up at [1:35](https://youtu.be/2GN5krOrlxM?t=95) before that was to show that there was nothing wrong with the phasing for the quests mentioned in the pr.
[With the PR, we are stuck here](https://i.gyazo.com/f909bc7df907f8b46e1001ff36a753df.jpg)
[SOURCE Forging An Alliance up -> You Can't Miss Him -> Battling the Elements](https://www.youtube.com/watch?v=6syJYv163GE)

**Comment by mpfans** [comment]
> I just went back and tested without the mentioned PR (`2022_05_07_00`) and all worked properly, so _**it might be that the entire bug report was wrong, as such bug did not exist**._
> 
> [Video of me going trough the quests before the PR (clean world db, that sql was not imported)](https://www.youtube.com/watch?v=2GN5krOrlxM) [MY WORLD DB, before the pr](https://i.gyazo.com/fe423f48a380f2ee732fca3e85e54d84.png) I start Forging An Alliance up at [1:35](https://youtu.be/2GN5krOrlxM?t=95) before that was to show that there was nothing wrong with the phasing for the quests mentioned in the pr. [With the PR, we are stuck here](https://i.gyazo.com/f909bc7df907f8b46e1001ff36a753df.jpg) [SOURCE Forging An Alliance up -> You Can't Miss Him -> Battling the Elements](https://www.youtube.com/watch?v=6syJYv163GE)
> 
> Solution, revert to quest_start 12956
> 
> > UPDATE` `spell_area`SET`quest_start`=12956 WHERE `spell`=55858;

Please create a new character and complete the quests successively from quest 13064

https://github.com/azerothcore/azerothcore-wotlk/issues/11634

**Comment by avarishd** [comment]
@mpfans https://youtu.be/2GN5krOrlxM?t=56 it's in the previous comment, this is before 11634
It all worked fine

**Comment by mpfans** [comment]
> @mpfans https://youtu.be/2GN5krOrlxM?t=56 it's in the previous comment, this is before 11634's pr It all worked fine

OH! you have a error... 


1. `.quest a 12915`
2.`.quest a 12922`
3.`.quest c 12922`
4.`.go xyz 7217.320312 -3636.736084 824.563965 571`
5.`Return the quest`
6. You will not be able to complete the quest 12915

Please follow my steps strictly,only copy 1 - 4...

**Comment by avarishd** [comment]
Cannot reproduce ( PRE 11634 fix )

https://user-images.githubusercontent.com/46330494/167592771-bd4ff0fc-75c6-4e63-8876-fefdc0168bc2.mp4

**Comment by mpfans** [comment]
> @mpfans https://youtu.be/2GN5krOrlxM?t=56 it's in the previous comment, this is before 11634's pr It all worked fine

 before 11662's pr hava a bug ....  

> 

complete quest 12922 ,leave this area... re enter this area..

**Comment by mpfans** [comment]
> Cannot reproduce ( PRE 11634 fix )
> 
>  632716db592e35734cf78b59c32b2d68.mp4



> Cannot reproduce ( PRE 11634 fix )
> 
>  632716db592e35734cf78b59c32b2d68.mp4

If you restore PR 11662, the database will not be restored So you're still testing the repaired database

**Comment by avarishd** [comment]
I'm testing on the world db pre 11662
fe423f48a380f2ee732fca3e85e54d84

https://user-images.githubusercontent.com/46330494/167594796-bbb7598a-6804-42b3-a2d6-e61696144035.mp4

**Comment by mpfans** [comment]
image

**Comment by avarishd** [comment]
@mpfans **Oh I see, confirmed ( on pre 11662 )**

https://www.wowhead.com/quest=12924/forging-an-alliance#comments
[Mending Fences](https://www.wowhead.com/quest=12915/mending-fences) + [A Spark of Hope](https://www.wowhead.com/quest=12956/a-spark-of-hope) => [Forging an Alliance](https://www.wowhead.com/quest=12924/forging-an-alliance#comments)

PR Should be changed to
```sql
-- (Quests) Forging an Alliance require A Spark of Hope + Mending Fences
DELETE FROM `conditions` WHERE `SourceEntry`=12924;

INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES 
(19, 0, 12924, 0, 0, 8, 0, 12956, 0, 0, 0, 0, 0, '', 'Forging an Alliance - Requires quest rewarded'),
(19, 0, 12924, 0, 0, 8, 0, 12915, 0, 0, 0, 0, 0, '', 'Forging an Alliance - Requires quest rewarded');

-- Reverts changes made in 11662
UPDATE `spell_area` SET `quest_start`=12956 WHERE `spell`=55858;

```

Works disregarding which quest your turn in first

https://user-images.githubusercontent.com/46330494/167781940-273a8fd7-fad9-49a8-a105-8a38f02e9bac.mp4

**Comment by mpfans** [comment]
> 

ok,but players have obtained quest 12924 will not be able to complete quest 12915 now,only future players can be fixed

**Comment by avarishd** [comment]
> > 
> 
> ok,but players have obtained quest 12924 will not be able to complete quest 12915 now,only future players can be fixed

Technically 11662 was not wrong as it "fixed" the phase changing after [Spark of Hope](https://www.wowhead.com/quest=12956/a-spark-of-hope) and not [Forging an Alliance](https://www.wowhead.com/quest=12924/), but it broke too many things, maybe someone else can figure out a way to do this properly.

Also you can parse character_queststatus_rewarded and edit accordingly, can maybe(?) just award it to players that have completed 12924? Or something along those lines.

- [x] **This is tested now and can be merged**

**Comment by mpfans** [comment]
> > > 
> > 
> > 
> > ok,but players have obtained quest 12924 will not be able to complete quest 12915 now,only future players can be fixed
> 
> Technically 11662 was not wrong as it "fixed" the phase changing after [Spark of Hope](https://www.wowhead.com/quest=12956/a-spark-of-hope) and not [Forging an Alliance](https://www.wowhead.com/quest=12924/), but it broke too many things, maybe someone else can figure out a way to do this properly. (probably from the condition table?)
> 
> Also you can parse character_queststatus_rewarded and edit accordingly, can maybe(not sure if this would be the proper way though) just award it to players that have completed 12924? Or something along those lines.
> 
> * [x]  **This is tested now and can be merged**

After accepting this PR,if  players get 12915 and 12924 at the same time will manually complete 12915 with GM command

**Comment by mpfans** [comment]
@UltraNix   please check this.. tyvm

**Review by UltraNix — APPROVED** [review]

**Comment by mpfans** [comment]
@Nyeriah @Kittnz  Please merge this PR as soon as possible. Many PR to be tested later are based on this pr

**Comment by Kittnz** [comment]
I can't merge anything on azerothcore ;) @mpfans

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Run source ./apps/ci/ci-pending.sh
Pending SQL check script:

> PROCEDURE check - OK
Missing Semicolon (;) or multiple newlines at the end of the file.
Error: Process completed with exit code 1.

can't merge

**Comment by mpfans** [comment]
> Run source ./apps/ci/ci-pending.sh Pending SQL check script:
> 
> > PROCEDURE check - OK
> > Missing Semicolon (;) or multiple newlines at the end of the file.
> > Error: Process completed with exit code 1.
> 
> can't merge

I didn't find any errors in this SQL statement

**Comment by mpfans** [comment]
> I can't merge anything on azerothcore ;) @mpfans

sry. I'm @ wrong

**Comment by avarishd** [comment]
Maybe it's the space after VALUE?

**Comment by mpfans** [comment]
> Maybe it's the space after VALUES?

only 1 line .... fail too...

**Comment by mpfans** [comment]
I tried to modify various SQL statements, but I always failed!

**Comment by Nyeriah** [comment]
It might have to do with line endings

**Pull request closed without merging**
