### PR TITLE
fix(DB/Gameobject): Ores/Herbs should be visible in visible in all phases

### PR DESCRIPTION
**Pull request by avarishd**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

<details>
<summary> List of IDs and Names of objects that are being changed</summary>

ID / Name
---
| id | name | 
| ---: | --- | 
| 1617 | Silverleaf | 
| 1618 | Peacebloom | 
| 1619 | Earthroot | 
| 1620 | Mageroyal | 
| 1621 | Briarthorn | 
| 1622 | Bruiseweed | 
| 1623 | Wild Steelbloom | 
| 1624 | Kingsblood | 
| 1628 | Grave Moss | 
| 1731 | Copper Vein | 
| 1732 | Tin Vein | 
| 1733 | Silver Vein | 
| 1734 | Gold Vein | 
| 1735 | Iron Deposit | 
| 2040 | Mithril Deposit | 
| 2041 | Liferoot | 
| 2043 | Khadgar's Whisker | 
| 2044 | Wintersbite | 
| 2045 | Stranglekelp | 
| 2046 | Goldthorn | 
| 2047 | Truesilver Deposit | 
| 2054 | Tin Vein | 
| 2055 | Copper Vein | 
| 3724 | Peacebloom | 
| 3725 | Silverleaf | 
| 3726 | Earthroot | 
| 3727 | Mageroyal | 
| 3729 | Briarthorn | 
| 3730 | Bruiseweed | 
| 3763 | Copper Vein | 
| 3764 | Tin Vein | 
| 103711 | Tin Vein | 
| 103713 | Copper Vein | 
| 123309 | Ooze Covered Truesilver Deposit | 
| 123310 | Ooze Covered Mithril Deposit | 
| 123848 | Ooze Covered Thorium Vein | 
| 142140 | Purple Lotus | 
| 142141 | Arthas' Tears | 
| 142142 | Sungrass | 
| 142143 | Blindweed | 
| 142144 | Ghost Mushroom | 
| 142145 | Gromsblood | 
| 150079 | Mithril Deposit | 
| 150080 | Gold Vein | 
| 150081 | Truesilver Deposit | 
| 150082 | Small Thorium Vein | 
| 175404 | Rich Thorium Vein | 
| 176583 | Golden Sansam | 
| 176584 | Dreamfoil | 
| 176586 | Mountain Silversage | 
| 176587 | Plaguebloom | 
| 176588 | Icecap | 
| 176589 | Black Lotus | 
| 176636 | Sungrass | 
| 176637 | Gromsblood | 
| 176638 | Golden Sansam | 
| 176639 | Dreamfoil | 
| 176640 | Mountain Silversage | 
| 176641 | Plaguebloom | 
| 176642 | Arthas' Tears | 
| 176643 | Small Thorium Vein | 
| 176645 | Mithril Deposit | 
| 181108 | Truesilver Deposit | 
| 181248 | Copper Vein | 
| 181249 | Tin Vein | 
| 181270 | Felweed | 
| 181271 | Dreaming Glory | 
| 181276 | Flame Cap | 
| 181277 | Terocone | 
| 181279 | Netherbloom | 
| 181281 | Mana Thistle | 
| 181555 | Fel Iron Deposit | 
| 181556 | Adamantite Deposit | 
| 181557 | Khorium Vein | 
| 181569 | Rich Adamantite Deposit | 
| 183043 | Ragveil | 
| 183044 | Felweed | 
| 183045 | Dreaming Glory | 
| 183046 | Blindweed | 
| 189973 | Goldclover | 
| 189978 | Cobalt Deposit | 
| 189979 | Rich Cobalt Deposit | 
| 189980 | Saronite Deposit | 
| 189981 | Rich Saronite Deposit | 
| 190169 | Tiger Lily | 
| 190170 | Talandra's Rose | 
| 190171 | Lichbloom | 
| 190172 | Icethorn | 
| 190173 | Frozen Herb | 
| 190175 | Frozen Herb | 
| 190176 | Frost Lotus | 
| 191019 | Adder's Tongue | 
| 191133 | Titanium Vein | 

</details>

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6931

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

Only source that I can think of are the "disappearing" herbs/ores in classic (when someone mines it in a phase that you're not in), but that's going off memory,

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

Run before and after the PR
```sql
SELECT distinct gameobject.id, gameobject_template.name, gameobject.phaseMask FROM gameobject JOIN gameobject_template ON gameobject.id=gameobject_template.entry WHERE gameobject.id IN(1617,1618,1619,3724,3725,3726,1620,1621,3727,3729,1622,1623,1624,2045,3730,2041,2046,1628,2044,2041,2043,176636,176642,142140,142141,142142,142143,142144,180165,183046,180164,176641,176640,176639,176638,176637,142145,176583,176584,176586,176587,176588,176589,180166,180167, 180168,183043,183044,183045,181270,181271,181275,181276,181277,181278,183385,181279,181282,181281,189973,190169,190173,190175,190174,190170,190172,191019,190171,190176,1731,181248,103713,2055,3763,1732,3764,103711,181249,2054,1733,1735,105569,73939,1734,2040,123310,150079,150080,176645,181109,2047,123309,150081,150082,181108,176643,123848,175404,181555,181556,181557,181569,181570,189978,189979,189980,189981,191133) AND gameobject.map IN(0,1,530,571);
```

.go ga 120721
Then step back 10 yards
Then go 10 yards

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by avarishd** [comment]
This should probably be reran once in a while.

**Comment by Nyeriah** [comment]
No, we will need to be mindful and always use that phasemask when spawning nodes

**Comment by avarishd** [comment]
Fair, but it's so easy to forget.

**Comment by Nyeriah** [comment]
Reviewers can’t forget about it, it’s not really feasible for us to be recommitting the same SQL over and over just in case. Doesn’t sound like a good solution

**Comment by Kitzunu** [comment]
But phase is a sniffed value, no?

**Comment by neifion-00000000** [comment]
this is definitely not always the case, we already know of one situation in Borean Tundra where this case is not true

**Pull request merged**
