### PR TITLE
fix(Scripts/ShadowLabirynth): Fixed Blackheart's Incite Chaos.

### LINKED ISSUE #13024: [Instance] ShadowLabyrinth Mind Control targeting issues
### Current Behaviour

The two players affected by the spell will not attack each other
https://www.wowhead.com/wotlk/spell=33676/incite-chaos

### Expected Blizzlike Behaviour

Controlled players attack each other

### Source

_No response_

### Steps to reproduce the problem

1.two player
2.modify hp
3.go cr 66937
4.wait

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/e5efa47f7fc6640e1d03fcd4f261400e99221728

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #13024

## Issues Addressed:

- Closes #13024

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

two player
modify hp
`.go cr 66937`
wait

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
```
[3] UpdateType: CreateObject2
[3] Object Guid: Full: 0x2056B4456012D900005EA2000005D466 Creature/0 R5549/S24226 Map: 555 Entry: 19300 Low: 382054
[3] FactionTemplate: 1761

[4] UpdateType: CreateObject2
[4] Object Guid: Full: 0x2056B4456012D940005EA2000005D466 Creature/0 R5549/S24226 Map: 555 Entry: 19301 Low: 382054
[4] FactionTemplate: 1761

[5] UpdateType: CreateObject2
[5] Object Guid: Full: 0x2056B4456012D980005EA2000005D466 Creature/0 R5549/S24226 Map: 555 Entry: 19302 Low: 382054
[5] FactionTemplate: 1761

[6] UpdateType: CreateObject2
[6] Object Guid: Full: 0x2056B4456012D9C0005EA2000005D466 Creature/0 R5549/S24226 Map: 555 Entry: 19303 Low: 382054
[6] FactionTemplate: 1761

[7] UpdateType: CreateObject2
[7] Object Guid: Full: 0x2056B4456012DA00005EA2000005D466 Creature/0 R5549/S24226 Map: 555 Entry: 19304 Low: 382054
[7] FactionTemplate: 1761
```

**Review by Gultask — DISMISSED** [review]

**Comment by murinotania** [comment]
degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates

**Comment by Si1ker** [comment]
Closes #1956

**Comment by heyitsbench** [comment]
> Closes #1956

Are you sure? That issue contains a bunch of separate issues, I doubt this PR would resolve all of those.

**Comment by Si1ker** [comment]
> 

"Jun 9, 2019" just this pvp thing was really missing.

**Comment by Si1ker** [comment]
> > Closes #1956
> 
> Are you sure? That issue contains a bunch of separate issues, I doubt this PR would resolve all of those.

"Jun 9, 2019" just this pvp thing was really missing.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
