### PR TITLE
feat(Core/SmartAI): Add new event parameter, event_param6

### PR DESCRIPTION
**Pull request by Gultask**
Blizz always has 4 timers for each creature spell, initial min, max, repeat min, max. Adding these to SAI leaves only one parameter for other uses, which sometimes it's not enough.
This approach was chosen because it maintains compatibility with TC. In the future we might keep timers in separate columns entirely.

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Gultask** [comment]
Surpringsingly, it seems to work.

**Comment by The-GhostRider** [comment]
@Gultask 
I just updated and compiled the CORE and I get this error:

image

**Comment by Gultask** [comment]
Did you run the file before? It can only be ran once, unfortunately.
Either delete your acore_world and rebuild or delete the column and try again.

It's better to delete acore_world though, as otherwise the smart_script rows that were modified in the file will break too.

**Comment by The-GhostRider** [comment]
I deleted the file From: Azerothcore\azerothcore-wotlk\data\sql\updates\db_world

image

and now it works:

image

**Comment by The-GhostRider** [comment]
> Did you run the file before? It can only be ran once, unfortunately. Either delete your acore_world and rebuild or delete the column and try again.
> 
> It's better to delete acore_world though, as otherwise the smart_script rows that were modified in the file will break too.


@Gultask 
I would like to suggest you this solution:
I just edited the file like this, the CORE loaded the SQL file without problems and this way the code is **ALWAYS re-executable.**


image




-- Adds the column only if it doesn't already exist
ALTER TABLE `smart_scripts`
    ADD COLUMN IF NOT EXISTS `event_param6` INT UNSIGNED NOT NULL DEFAULT '0' AFTER `event_param5`;

-- Update values only if the column exists
UPDATE `smart_scripts` SET `event_param6` = `event_param5` WHERE `event_type` = 106 AND `source_type` = 0 AND `event_param6` = 0;
UPDATE `smart_scripts` SET `event_param5` = 0 WHERE `event_type` = 106 AND `source_type` = 0 AND `event_param6` = 0;

UPDATE `smart_scripts` SET `event_param6` = `event_param5` WHERE `event_type` = 105 AND `source_type` = 0 AND `event_param6` = 0;
UPDATE `smart_scripts` SET `event_param5` = 0 WHERE `event_type` = 105 AND `source_type` = 0 AND `event_param6` = 0;

**Comment by heyitsbench** [comment]
Why update values only if the column exists if you make sure the column exists with the alter table?

**Comment by The-GhostRider** [comment]
> Why update values only if the column exists if you make sure the column exists with the alter table?

Because that other way, the CORE fails (IF) someone accidentally loads the SQL file manually.
**(Look at the Screenshots I uploaded a few previous posts**)

**Comment by Kitzunu** [comment]
well they shouldnt load it manually lol. But IF NOT EXISTS is a valid addition for it though

**Comment by The-GhostRider** [comment]
> well they shouldnt load it manually lol. But IF NOT EXISTS is a valid addition for it though

If you remember, I was doing Fix here in 2021, and in 2021, the 'Automatic File Update' feature hadn't been implemented in the CORE. As a result, not being aware of this Fix, I continued using a batch macro I had created to perform file updates.

So, I couldn't have known about this new "Innovation". (LOL)

Therefore, I followed the procedure I had always followed...

Furthermore, (theoretically) the syntax procedure for Queries should ALWAYS be reloadable within the DB (by convention). At least, that's what I was told here on AC in 2021 by @FrancescoBorzi e @Helias

**Comment by Helias** [comment]
Adding that "IF NOT EXISTS" condition can be a good approach for next time, we could keep in mind it for the next similar query about altering a table.

Or update this in another small PR.

**Comment by Kitzunu** [comment]
> But IF NOT EXISTS is a valid addition for it though

I literally said that, but okay. But pick fights, you good at that

**Comment by Kitzunu** [comment]
anyway that dont work I realized
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `event_param6` INT UNSIGNED NOT NULL DEFAULT '0' AFTER `event_para'
```

**Comment by The-GhostRider** [comment]
> > But IF NOT EXISTS is a valid addition for it though
> 
> I literally said that, but okay. But pick fights, you good at that

"
I'm not sure if you are referring to me, but if that's the case, I'm not attacking you, I'm just "explaining" why I uploaded it manually. It wasn't an attack, it was an explanation.

**Comment by Kitzunu** [comment]
I apologize then. I interpreted your message as hostile. All good 👍

**Comment by The-GhostRider** [comment]
> I apologize then. I interpreted your message as hostile. All good 👍

Sorry for that, It wasn't my intention, through chat it's hard to understand the "tones," and this is how I express myself. I'm sorry if it's being misinterpreted.

**Comment by Kitzunu** [comment]
All good all good

**Comment by The-GhostRider** [comment]
> anyway that dont work I realized
> 
> ```
> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `event_param6` INT UNSIGNED NOT NULL DEFAULT '0' AFTER `event_para'
> ```

Which one?

**Comment by Kitzunu** [comment]
IF NOT EXISTS

**Comment by Kitzunu** [comment]
Well I ran your whole query

**Comment by The-GhostRider** [comment]
> IF NOT EXISTS

IDK.. for me it works..

image

**Comment by Kitzunu** [comment]
I guess you use Maria. MySQL does not support IF NOT EXISTS for ALTER TABLE

**Comment by The-GhostRider** [comment]
> I guess you use Maria. MySQL does not support IF NOT EXISTS for ALTER TABLE

Yes I use MariaDB

**Pull request merged**
