### PR TITLE
fix(Scripts/Ulduar): Fixed spawning Hodir chests.

### LINKED ISSUE #10811: [Ulduar] Hodir loot erro
### Current Behaviour

When the player wins in 10 mans mode, it takes more than 3 minutes! The Chets obtained are actually 25mans mode and hero 2 Chets

When the player wins in 25 mans mode, it takes more than 3 minutes! The Chets obtained are actually10 mans mode and hero 2 Chets
### Expected Blizzlike Behaviour

10 mans mode...more than 3 minutes! only 1 chest ..
25 mans mode...more than 3 minutes! only 1 chest ..

### Source

_No response_

### Steps to reproduce the problem

1.set 10 mans mode (OR 25 mans mode)
2.go c id 32845
3..gm off
4. killed Hodir 
5. look loot

### Extra Notes

_No response_

### AC rev. hash/commit

4509a36e9180f83a420b552c785fe53f743c7ae3

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #10811

## Issues Addressed:

- Closes #10811

## Tests Performed:

- Not tested. 

## How to Test the Changes:

1.set 10 mans mode (OR 25 mans mode)
2.go c id 32845
3..gm off
4. killed Hodir
5. look loot

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Test it please.

**Comment by pklloveyou** [comment]
```
            case NPC_HODIR:
                m_uiHodirGUID = creature->GetGUID();
+              if (GetData(TYPE_HODIR) != DONE)
+              {
+                   SetData(TYPE_HODIR, NOT_STARTED);
+                   SetData(TYPE_SPAWN_HODIR_CACHE, 0);
+              }
                break;
```
Solved this problem

**Comment by mpfans** [comment]
It's right to loot boxes now, but there will still be 2 boxes if the battle time exceeds 3 minutes

**Comment by mpfans** [comment]
The following warnings will be prompted at compile 

```/home/polly/azerothcore/src/server/scripts/Northrend/Ulduar/Ulduar/instance_ulduar.cpp:221:25: warning: enumeration values 'DUNGEON_DIFFICULTY_EPIC' and 'RAID_DIFFICULTY_25MAN_HEROIC' not handled in switch [-Wswitch]
                switch (diff)
                        ^```

**Comment by UltraNix** [comment]
@mpfans Try now, without your code.

**Comment by mpfans** [comment]
Now more than 3 minutes, it shows that houdil has broken the precious treasure chest, but the box has not disappeared. You can still pick up additional boxes after more than 3 minutes

**Comment by UltraNix** [comment]
@mpfans One more time, please.

**Comment by mpfans** [comment]
tested,10 and 25 chets looted right now. but If you kill it in three minutes, you can't achieve `I Could Say That This Cache Was Rare (10 player)` and `I Could Say That This Cache Was Rare (25 player)`

**Comment by mpfans** [comment]
@FrancescoBorzi @claudiodfc @Nefertumm  Please merge it as soon as possible. I have other tests based on this PR to complete

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
