### PR TITLE
fix(DB/Spell): Giant Softshell drops

### PR DESCRIPTION
**Pull request by iraizo**
Giant Softshell Clam's should only be lootable with a certain quest (6142)

## Changes Proposed:
-  data_8 (questid) has been changed on the [Giant Softshell Clam](https://wotlk-twinhead.twinstar.cz/?object=177784) to [Clam Bait](https://wotlk-twinhead.twinstar.cz/?quest=6142)

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5585

## SOURCE:

 [Soft-shelled Clam](https://wotlk-twinhead.twinstar.cz/?item=15874) is a Quest item required for [Clam Bait](https://wotlk-twinhead.twinstar.cz/?quest=6142) 

## Tests Performed:

- I tested both test cases below on my local machine/server and they work as intended.

### Test case 1
1. `.quest add 6142`
2. `.go o 31973`
3. Open the clam.
4. Check if you got a Soft-shelled Clam.

### Test case 2
1. Do step 2 and 3 of test case 1 and see if its not interactable.

## Known Issues and TODO List:

Nothing.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
Nice test cases, keep it up 👍🏼

**Comment by Kitzunu** [comment]
Are you sure? According to the wiki this should be the quest id of a completed quest

**Comment by iraizo** [comment]
> Are you sure? According to the wiki this should be the quest id of a completed quest

How would that make sense

**Comment by iraizo** [comment]
> 
> 
> I just asked as I saw something else on the wiki 🤷

Well im asking what "completed quest" is supposed to mean

**Comment by Kitzunu** [comment]
```cpp
enum QuestStatus : uint8
{
    QUEST_STATUS_NONE           = 0,
    QUEST_STATUS_COMPLETE       = 1,
    //QUEST_STATUS_UNAVAILABLE    = 2,
    QUEST_STATUS_INCOMPLETE     = 3,
    //QUEST_STATUS_AVAILABLE      = 4,
    QUEST_STATUS_FAILED         = 5,
    QUEST_STATUS_REWARDED       = 6,        // Not used in DB
    MAX_QUEST_STATUS
};
```
There are currently 5 states a quest can have, if it has the status "Complete" it would mean you have fulfilled all the requirements of the quest but you have not handed it in. But I do not know the one who made the wiki thought of "Complete" or "Rewarded". And I also don't know what the expected outcome of that field should be. Just wanted to know if it contradicts with the wiki or not =)

**Comment by iraizo** [comment]
> 
> 
> ```c++
> enum QuestStatus : uint8
> {
>     QUEST_STATUS_NONE           = 0,
>     QUEST_STATUS_COMPLETE       = 1,
>     //QUEST_STATUS_UNAVAILABLE    = 2,
>     QUEST_STATUS_INCOMPLETE     = 3,
>     //QUEST_STATUS_AVAILABLE      = 4,
>     QUEST_STATUS_FAILED         = 5,
>     QUEST_STATUS_REWARDED       = 6,        // Not used in DB
>     MAX_QUEST_STATUS
> };
> ```
> 
> There are currently 5 states a quest can have, if it has the status "Complete" it would mean you have fulfilled all the requirements of the quest but you have not handed it in. But I do not know the one who made the wiki thought of "Complete" or "Rewarded". And I also don't know what the expected outcome of that field should be. Just wanted to know if it contradicts with the wiki or not =)

Well im not even sure where you found that nor what i am supposed to get out of this since the wiki just states the quest id

**Comment by Kitzunu** [comment]
if it works it works :)

**Comment by iraizo** [comment]
> 
> 
> if it works it works :)

Well i havent actually tried turning in the quest but it does seem to function correctly

**Comment by FrancescoBorzi** [comment]
@iraizo @Kitzunu  what's the status of this? can it be merged?

**Comment by iraizo** [comment]
> 
> 
> @iraizo @Kitzunu what's the status of this? can it be merged?

Id say that much that it functions

**Comment by FrancescoBorzi** [comment]
> Id say that much that it functions

what does it mean?

**Comment by iraizo** [comment]
> 
> 
> > Id say that much that it functions
> 
> what does it mean?

I mean.. it works so i guess it can be merged

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
