### PR TITLE
fix(DB/Conditions): Collect Rookery Egg should require nearby Rookery…

### PR DESCRIPTION
**Pull request by Nyeriah**
… Egg

## Changes Proposed:
-  Add conditions for spell cast
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9039

## Tests Performed:

- Tested in-game.
- 

## How to Test the Changes:

.go ga 87903 - teleport to The Rookery
.q a 4735
use Collectronic Module

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@Shineslippers Please test this and let me know if there's any issues remaining.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Shineslippers** [comment]
@Nyeriah I'm sorry not able to do tests. Never did it before. Ii think `consume` mean egg destroy. When you using item on video it's already pop up.

**Comment by Nyeriah** [comment]
> @Nyeriah I'm sorry not able to do tests. Never did it before. I think `consume` mean egg destroy. When you using item on video it's already pop up.

Okay, I'll look into that to see what can be done, but as far as I know gameobject spell targeting doesn't work

**Comment by Shineslippers** [comment]
[Eggscilloscope](https://wowgaming.altervista.org/aowow/?item=12144) item wehat you getting before this quest and you ahve to use it before collection eggs to reduce pop radius. I feel like it also dooesn't work, but maybe it can help.

**Pull request merged**
