### PR TITLE
fix(Core/Items): Armor type requirement for needing items in LFG grou…

### LINKED ISSUE #7467: [Dungeon Finder] Roll Rules for classic dungeons
### What client do you play on?

ruRU

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Now classes can only roll their own type of armor in classic dungeons. For example, druid healers can only roll leather, but cannot roll cloth.

### Expected Blizzlike Behaviour

Items that do not exceed level 70 should not have class restrictions on the type of armor. For example 35 ilvl cloth can roll paladins, shamans, druids.

### Source

Blue post:
https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

> The player’s class must be able to equip the item, either at the time of the roll or at a later level. For example: A level 38 shaman would able to roll "Need" on a level 42 mail item; however, he or she would not be able to roll "Need" on a plate item.
The armor proficiency of the player’s class must not be higher than the item being rolled on. If it is, the player will unable to roll “Need.” For example: A level 75 warrior would unable to roll "Need" on certain mail items. **(This restriction will only come into play for items with an iLevel above 70.)**
If a player’s class is pure melee, he or she will be unable to roll "Need" on spell power items. Pure melee classes include rogues and warriors. Druids, paladins, death knights, and shaman may still roll "Need" on spell power items, provided that the above two conditions are met.

Video:
3:09 - paladin can roll leather
https://youtu.be/tTwgdv53FrU?t=190 

upd
2:50 - Shaman press "Need" Cloth Hands
https://youtu.be/546hZW_ohzg?t=170

6:02-6:04 - Shaman press "Need" Cloth Head
https://youtu.be/G2lbPy6VN_M?t=360

upd
8:50 - Shaman Greenar press "Need" Cloth Wrist
https://youtu.be/-3Sr-0pcZkg?t=531

7:10 - 7:37 - Druids Saine and Romane press "Need" Cloth Head
https://youtu.be/86CqyD7NfeU?t=430

upd

2:26 - Resto Shaman can press "Need" Cloth Chest and do it. This is cross server party consists of prot war, **resto shaman, mage**, hunter and rogue.
https://youtu.be/s2VokcGf3M8?t=146

### Steps to reproduce the problem

Queue for a dungeon finder.

### Extra Notes

Original Report: https://github.com/chromiecraft/chromiecraft/issues/1460

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2d77fe9274005a99f8445b8dac9dd0fcd3faf3c5

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…p comes into play only for items above 70 ilvl.

Fixed #7467

## Issues Addressed:

- Closes #7467
- Closes https://github.com/chromiecraft/chromiecraft/issues/190
- Closes https://github.com/chromiecraft/chromiecraft/issues/1460

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Queue for a dungeon finder for some classic low level dungeon.
2. Loot some items with armor type not fit to your class/level (e.g. cloth item for warrior or mail item for 42 lvl shaman)
3. See you can need on that item.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Mitradis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/4858
https://github.com/chromiecraft/chromiecraft/issues/470
https://github.com/chromiecraft/chromiecraft/issues/535
fix that too?

**Comment by UltraNix** [comment]
No.

**Comment by syssneck** [comment]
> Loot some items with armor type not fit to your class/level (e.g. cloth item for warrior or mail item for 42 lvl shaman)
Shamans can wear mail with lvl 40+

**Comment by UltraNix** [comment]
I mean - mail item for 42 lvl shaman, being a 38 lvl shaman :P

**Review by syssneck — CHANGES_REQUESTED** [review]

**Comment by FrancescoBorzi** [comment]
@pklloveyou have you been running this with players?

**Comment by pklloveyou** [comment]
It's working on my server

**Comment by temperrr** [comment]
Tested.

Not working as it should. I can now roll on mail as a leather wearer (rogue, druid etc) when I am never able to equip such item. ( only shaman and hunter should be able to roll on mail and leather and cloth in low level dungeons). Also a priest can need on mail and leather.

Havent tested it further, but this are the requirements;

https://www.bluetracker.gg/wow/topic/eu-en/11824414332-the-dungeon-finder-what-to-know/

1`If a player’s class is pure melee, he or she will be unable to roll "Need" on spell power items. Pure melee classes include rogues and warriors. Druids, paladins, death knights, and shaman may still roll "Need" on spell power items, provided that the above two conditions are met.`
2`The player’s class must be able to equip the item, either at the time of the roll or at a later level. For example: A level 38 shaman would able to roll "Need" on a level 42 mail item; however, he or she would not be able to roll "Need" on a plate item.`

Above ilvl 70 these rules apply on top of 1 and 2.:
3` The armor proficiency of the player’s class must not be higher than the item being rolled on. If it is, the player will unable to roll “Need.” For example: A level 75 warrior would unable to roll "Need" on certain mail items. (This restriction will only come into play for items with an iLevel above 70.)`

**Comment by UltraNix** [comment]
@temperrr The loot mode was Need Before Greed?

**Comment by UltraNix** [comment]
@temperrr Please - retest it.

**Comment by temperrr** [comment]
> @temperrr Please - retest it.

on it!

**Comment by temperrr** [comment]
> @temperrr The loot mode was Need Before Greed?
> @pklloveyou Can you confirm that problem?

loot mode is need before greed

**Comment by temperrr** [comment]
I broke my docker setup, again, no time to fix it atm, hope someone else can take over the testing.

**Comment by syssneck** [comment]
This looks a lot better now, but from looking at the code, I'm certain, that this rule is not in place yet:

> 1) If a player’s class is pure melee, he or she will be unable to roll "Need" on spell power items. Pure melee classes include rogues and warriors.

If this is not planned with this PR, then I can test it later the way it is now.
I don't see a reason, why Rogues or Warriors should ever roll need on something below their armor proficiency, spellpower or not. So maybe you could add another check for Rogues and Warriors, so that they can't roll on cloth for Rogue and cloth + leather for Warriors. What do you think?

**Comment by UltraNix** [comment]
I can try to add this rule to that PR.

**Comment by UltraNix** [comment]
@syssneck And what about items with base stats, like intellect for warriors and rogue? It is useless stat for these classes as well as str/agi for priests or warlocks.

**Comment by Efymer** [comment]
Something I found testing this PR:

- As a Paladin I can roll need on dagger I cannot use 🔴 

WoWScrnShot_090121_130205

**Comment by syssneck** [comment]
@UltraNix yeah true, but how to implement this? Add more checks for all base stats? This is getting to complicated and is afaik not blizzlike.
Sometimes a warrior tank wants to roll on a mail chest with int for example, just because of the armor value on it, not for the stats.
A priest might want to roll on cloth shoulders with agi, but the other stat on it is spirit, and he wants that.
And so on ... too many possible exceptions.

It will be good, if we can just add the rule, that melee classes (warriors & rogues) can't roll on spellpower items.

@Efymer I think this PR is for armor type only, but I wonder about the second example. Did you already test with the changes, that Ultranix added ~2 h ago? A warlock should not be able to roll on leather with these changes.

**Comment by Efymer** [comment]
Hey @syssneck,
Answering your questions:
- Yes I was testing it with the latest changes. 
- I went to the instance with the `.go c id` command and Group Loot.

**Comment by UltraNix** [comment]
Okay, I get it. You are right.

**Comment by UltraNix** [comment]
@syssneck You can retest it.

**Comment by syssneck** [comment]
@UltraNix Warriors and Rogues can need on all cloth items:
grafik

**Comment by UltraNix** [comment]
@syssneck 
```
The armor proficiency of the player’s class must not be higher than the item being rolled on. If it is, the player will unable to roll “Need.” For example: A level 75 warrior would unable to roll "Need" on certain mail items. (This restriction will only come into play for items with an iLevel above 70.)
```

**Comment by UltraNix** [comment]
Yes - they can need on cloth, because item level < 70 as stated above somewhere.

**Comment by syssneck** [comment]
Yes, correct, but for Warriors and Rogues there is this extra rule, as stated above: 

> If a player’s class is pure melee, he or she will be unable to roll "Need" on spell power items. Pure melee classes include rogues and warriors.

**Comment by UltraNix** [comment]
Yes, I see. It's not a stat, but a spell. Need some work here :)

**Comment by UltraNix** [comment]
@syssneck Another update. Please test.

**Comment by syssneck** [comment]
I have no idea what's going on, the first boss I want to loot, I'm stuck in the looting animation and I don't see the group loot window. After that, the server does not react to any input (no error in the server window). It is probably on my end, but I will wait and see, what @Efymer reports.

**Comment by Efymer** [comment]
@UltraNix , I'm having the same issue as @syssneck 

https://streamable.com/a3lwtn

**Comment by UltraNix** [comment]
Did your server crash?

**Comment by Efymer** [comment]
> Did your server crash?

It didnt crash, i's just stuck

**Comment by UltraNix** [comment]
@syssneck @Efymer Fixed. Check now.

**Comment by Efymer** [comment]
PR looks good to me now ✔️ All the condition stated in the ticket are met.

Checks I did:

**Cloth**

- Cannot need on leather mail and plate.
- Can need cloth.
- Can need on cloth even if the character is too low to equip it.

**Leather**

- Cannot need on mail and plate.
- Can need on cloth and leather.

**Mail**

- Cannot need on plate.
- Can need on cloth, leather and mail.

**Plate**

- Can need on cloth, leather, mail and plate.
- **EXCEPTION**: Warriors, cannot need on cloth with spell power.


Good job!

**Comment by syssneck** [comment]
Thank you @Efymer. I will just add a few things:
- Warriors and Palas can roll on plate before lvl 40 ✔️ 
- Shamans and Hunter can roll on mail before lvl 40 ✔️ 
- Warriors and Rogues can not roll on items with spellpower ✔️(I would still probably just prevent warriors and rogues from rolling on cloth altogether, but well it is blizzlike) 
- After ilvl 70 you may only need on items of your armor proficiency (pala=plate, shaman=mail, priest=cloth and so on)✔️

As far as I can tell, this works like the blue post now. There are still some bugs with need on weapons & shields, but that is a different matter. 
Good job, we can merge this from my side!

**Pull request merged**
