### PR TITLE
fix(SAI): Disciple of Naralex

### LINKED ISSUE #5927: Final event in Wailing Caverns not splitted in waves
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [X] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/664

##### CURRENT BEHAVIOUR:

During the final event (where you try to save Naralex) 3 waves of mobs should appears. The second one should come in once you defeated the first one and so on. At the moment they are "timed": even if you didn't finish clearing the previous wave after a certain amount of time the next one appears (the same goes for the final boss, [Mutanus](https://wowgaming.altervista.org/aowow/?npc=3654))

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Once you cleared a wave of mobs the next one should appear

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Defeat the 4 druid bosses of Wailing Caverns
2. Talk with the [Disciple of Naralex](https://wowgaming.altervista.org/aowow/?npc=3678) at the entrance of the instance
3.  Escort him to the Naralex area
4.  As soon as the first wave appears do nothing, after a while the second wave will appear 

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/0d699222de92185681f9a78822a0e5d9898294f4

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: b2ab5db):

WoWScrnShot_051821_054319
WoWScrnShot_051821_054721
WoWScrnShot_051821_054903
WoWScrnShot_051821_054922
WoWScrnShot_051821_054929

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98539888-final-event-in-wailing-caverns-not-splitted-in-waves?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6644: [Wailing Caverns] Last boss doesn't spawn correctly [$30]
### CURRENT BEHAVIOUR:

When waves has been defeated, Naralex doesn't appear. The disciple keep casting forever

### EXPECTED BLIZZLIKE BEHAVIOUR:

When waves has been defeated, Naralex should wake up as the disciple finished to cast his ritual

### STEPS TO REPRODUCE THE PROBLEM:

1. Go to wailing cavern
2. Kill everyboss
3. Go to the disciple at dungeon's entrance and trigger his event

### AC HASH/COMMIT:
 
https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

### OPERATING SYSTEM:

Ubuntu 20.04

### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

**CUSTOMIZATIONS:**

<bountysource-plugin>

---
There is a **[$30 open bounty](https://www.bountysource.com/issues/99543852-wailing-caverns-last-boss-doesn-t-spawn-correctly?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Fixes Disciple of Naralex script in order to complete Wailing Caverns
- Cleansing spell is not interrupted on the fire circle

## Issues Addressed:

- Closes #6644 
- Closes #5927 

## Tests Performed:

- Tested on Windows 10

## How to Test the Changes:

1. .go c id 3678
2. .go c id 3671 (kill)
3. .go c id 3669 (kill)
4. .go c id 3670 (kill)
5. .go c id 3673 (kill)
6. .go c id 3678 (Start the event)
7. Finish the dungeon

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Sedatyf** [comment]
Good job on that one @claudiodfc and thank you for taking care of this high priority issue
I tested it on my local core and: 
- ✔️ I could finish Wailing Caverns without any problem (please look at the first video)
- ✔️ mobs are spawning in wave and not all in the same time (please look at the second video)


https://user-images.githubusercontent.com/59012307/124022436-118f1b80-d9ed-11eb-868a-889429a09279.mp4


https://user-images.githubusercontent.com/59012307/124022439-12c04880-d9ed-11eb-9c63-6223b76bf9a7.mp4

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by gabryatfendor** [comment]
It's basically perfect, good job! I don't know if it's doable, but as per my original report a little time should be added between the waves, to allow people to drink/eat. Still, great job!

**Comment by claudiodfc** [comment]
It's doable, I just need to get the hand of Actionlists :)

**Comment by Sedatyf** [comment]
It's doable, okay, but which behavior is blizzlike? Don't forget that we try to stick the closest we can to a blizzlike server

**Comment by gabryatfendor** [comment]
I can link here the video I made for the issue on chromiecraft, you can see the pause beteween the waves. I counted 20/25 seconds. The video was recorded on Wow Classic

https://www.youtube.com/watch?v=zScO80lIfBM

**Comment by claudiodfc** [comment]
He's right, I was just in a rush to get Wailing Caverns open as soon as possible for Chromiecraft.

**Pull request merged**
