### PR TITLE
Fix(DB/Creature): set proper faction for Deepmoss Hatlings

### LINKED ISSUE #9432: Deepmoss Hatlings spawned by Deepmoss Eggs are not hostile
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2443

When you interact with the gameobjects to loot the eggs, there's a chance for Hatchlings to spawn. Currently, they do but with the wrong faction, not being aggressive to the player. Also on the video bellow, they seem to have a random waypoint movement.

Tester:

The issue is confirmed. After using [Deepmoss Eggs](https://wowgaming.altervista.org/aowow/?object=19541) spawned creatures is neutral.

WoWScrnShot_120121_043855

### Expected Blizzlike Behaviour

Spiders should attack the players when spawned

### Source

Wowhead [Deepmoss Spider Eggs](https://www.wowhead.com/quest=1069/deprecated-deepmoss-spider-eggs)
https://youtu.be/UWHhc6ZJeOQ?t=7
https://youtu.be/keSBXBKF0Vg?t=254

### Steps to reproduce the problem

.go ga 44640
loot the egg

### Extra Notes

X

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc16abc30ea2e9412627ddd9d15868eac8aabb53

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Set proper faction (22)

## Issues Addressed:

- Closes #9432 

## Tests Performed:

Tested in-game

## How to Test the Changes:

.go ga 44640, open the gob and see if the creature attacks you

### CODE REVIEW

**Comment by Kitzunu** [comment]
Sniffed?

**Comment by Nefertumm** [comment]
No.

**Comment by pangolp** [comment]
The day we get a sniff great. But as long as we don't have it, let's not stop fixing things. We have to give solutions to the problems. If later, the code can be improved, great. But in the meantime, let's not stop making changes.

**Review by pangolp — APPROVED** [review]

**Comment by T1ti** [comment]
image
here's a sniff, faction is 312 on classic vanilla

**Comment by Nefertumm** [comment]
image

Faction 312 doesn't exist on core 👀

**Comment by T1ti** [comment]
> image
> 
> Faction 312 doesn't exist on core 👀

creature_tempalte points to faction_template, not faction.
Factino_tempalte's second column then points to faction

**Comment by Nefertumm** [comment]
Ahh, I understand, thank you! I see now.

**Comment by Nefertumm** [comment]
Tested again, working. Ty for the info @T1ti <3

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by malcrom** [comment]
Sniffed. 312 is correct.

**Pull request merged**
