### PR TITLE
feat(License): delete address to license file

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
- Delete address to the license file (like TC)

I just don't want to get confused, because we have two licenses

### CODE REVIEW

**Comment by Helias** [comment]
I'm not sure about this PR, I think that we could leave the license mention in the source file.

**Comment by BarbzYHOOL** [comment]
Yehonal and Shin know more about licensing, let's see what they say

But why would it be better to remove them ?

**Comment by Yehonal** [comment]
We use GPL2 only for old TC files, but all our new features are under AGPL2 that "fixes" various GPL2 lacks (such license has been created before the internet era).

PS Modules can use any kind of license they want, even not open-source.

**Comment by FrancescoBorzi** [comment]
that's the point, we release new files under AGPL v3 but we can't change the license to the existing files (GPL v2). That's why we need to specify in each file which of the two licenses is used

**Comment by BarbzYHOOL** [comment]
> that's the point, we release new files under AGPL v3 but we can't change the license to the existing files (GPL v2). That's why we need to specify in each file which of the two licenses is used

Yes, old licenses can never be removed unless we rewrite everything from scratch

**Comment by Helias** [comment]
I think we can update and merge this PR.
Probably we don't need to add the URL of the license in the source code.

**Comment by BarbzYHOOL** [comment]
@Yehonal

**Comment by FrancescoBorzi** [comment]
there is no need for this change, as I said: we have different files having different licenses (old files GPL v2, new files AGPLv3) that's why IMHO we should keep it

**Comment by BarbzYHOOL** [comment]
ok (sorry winfi :D)

**Pull request closed without merging**
