### PR TITLE
fix(DB/Raid):improved Eye of Eternity

### PR DESCRIPTION
**Pull request by Knindzagxg**
Changes:

Min, Max & Modifier Damage for whole Raid.

How to test:
Apply SQL
Restart Server and delete your Cache.
Make sure to add basic tanking gear towards Raid ilevel.

Before you start checking damage:
.mod hp 500000
.learn 1908 (Uber heal over time)

If there is any issue with damage and if you get instantly killed, lemme know.

Note: You wont be able to survive some mechanics where second tank is required - Use one more account on those fights.

### CODE REVIEW

**Comment by iyasenai** [comment]
Where did you get those values from?
Any video on youtube?
Official post?

**Review by Helias — APPROVED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by iyasenai** [comment]
I tested the damage and these were the results.
These were the Buffs and the gear I used.
image

Nexus Lord 25  Entry: 31750
image
Nexus Lord 10  Entry: 30245
image

Malygos 25  Entry: 31734
image
Malygos 10  Entry: 28859
image

**Comment by Knindzagxg** [comment]
@iyasenai - Can u re-test again mate.

**Comment by iyasenai** [comment]
New Test.

Malygos 25 Entry: 31734
image

Malygos 10 Entry: 28859
image

**Comment by Knindzagxg** [comment]
Cheers mate, ill do more checking tomorrow once im back.
25m seems ok now tho.

**Comment by Knindzagxg** [comment]
Yet again cheers for tests mate.
Malygos is now sorted.

Thanks to tankspot and logs i was able to find even better values.
He's just little stronger then Sartharion (Which is already good xD) and added that extra now.

**Comment by Voxstrasza** [comment]
the important thing to keep in mind is that this is an entry level raid, so you'd be doing it with ilvl 200 blues, maybe a few ilvl 200 epics from badge vendor, maybe a few pieces of naxx25 gear because you have to do naxx25 before malygos.  the difficulty of the boss should be aimed at players with that gear.  so here's a gearset I used that I think would be the most realistic, blue gear, ilvl 200 tier 7 shoulders, 1 naxx25 piece

[image]https://i.imgur.com/2Dg1z8k.jpg[/image]

I set my health to 29500 (which is what a tank would be raid buffed in this gear, give or take a few 100s) and let the boss hit me.  malygos hit me between 9500-11000 consistently, which is ok.  it's a dragon boss, so you shouldn't have to worry about the melee swings - it's always the breath that raids have to worry about.  all good in my book

**Review by Si1ker — APPROVED** [review]

**Comment by Knindzagxg** [comment]
Not gonna merge yet @Si1ker 

We need to see are we gonna use Modifier or not.
Waiting for @BarbzYHOOL PR.

**Pull request merged**
