### PR TITLE
fix(DB/ShadowmoonValley): add immunities to Uvuros

### PR DESCRIPTION
**Pull request by alaxandir**
## Changes Proposed:
- Add immunities to Uvuros
- Immune to Fear, Root, Slow, Spell Interrupt, Silence, Snare, Freeze, Horror

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16296

## SOURCE:
- According to user comments on WowHead from original Wrath, this mob has certain immunities which have been added. https://www.wowhead.com/wotlk/npc=21102/uvuros
- In addition the PR requested these immunities be added for Bliz-like expectation

## Tests Performed:
- Tested Mage and Warrior in game
- Immune to appropriate abilities such as frost nova root, fear, counter spell, the slow effect of frost bolt.

## How to Test the Changes:
`go c id 21102`
Cast any spell with the listed mechanics.
Observe his susceptibility.

## Known Issues and TODO List:
- [ ] Noticed that Fel-Reaver also has no immunities except for Bleed, unsure if this is blizzard like. I admittedly don't know how to test this to observe expected behaviours short of playing on the official classic wrath server, which I don't have.

Discord #AiurJordan9442

### CODE REVIEW

**Comment by heyitsbench** [comment]
On Wrath Classic, he is susceptible to Cone of Cold's slow effect.

**Comment by heyitsbench** [comment]
You need to add `.sql` to the end of the filename by the way.

**Comment by alaxandir** [comment]
Sorry, my first PR learning git. Thanks for the help.

**Comment by heyitsbench** [comment]
> Sorry, my first PR learning git. Thanks for the help.

No problem, thanks for the PR! ❤️

**Comment by elthehablo** [comment]
might want to change your title. for db fixes we generally would do something as follows in this case:

`fix(DB/ShadowmoonValley): add immunities to Uvuros`

for future reference, immunities are always really hard to prove. sometimes it's possible to crossreference with other dbs (TC for instance) to see what they are doing and take values from there, but those are also not always correct

**Comment by elthehablo** [comment]
aditionally for sql the convention is to make them look like this:
```sql
01 --
02 MY SQL STATEMENT WHERE `id` = 0;
03 
```

**Comment by heyitsbench** [comment]
> aditionally for sql the convention is to make them look like this:

It's fine how it is. 🙂

**Comment by Nyeriah** [comment]
The bitwise operator should be used when updating bitmask fields

```sql 
UPDATE `creature_template` SET `mechanic_immune_mask` = `mechanic_immune_mask` |XXX|YYY WHERE `entry` = XXXX;
```

**Comment by elthehablo** [comment]
> > aditionally for sql the convention is to make them look like this:
> 
> It's fine how it is. 🙂

it is fine is that it will work the same. it is less readable tho

**Comment by heyitsbench** [comment]
> it is fine is that it will work the same. it is less readable tho

Adding a line of just dashes has no impact on readability IMO. If you mean the bitmask operator, I do agree.

**Comment by elthehablo** [comment]
> > it is fine is that it will work the same. it is less readable tho
> 
> Adding a line of just dashes has no impact on readability IMO. If you mean the bitmask operator, I do agree.

the latter :)

**Comment by heyitsbench** [comment]
> btw is he poly immune?

He is on Classic.

**Comment by alaxandir** [comment]
requested changes made, added polymorph immunity

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Thanks for the PR 👍

**Comment by elthehablo** [comment]
Good work on first PR!

**Pull request merged**
