### PR TITLE
fix(Core/Spells): Sleep aura from Magic Dust should be removed if tar…

### LINKED ISSUE #11947: Magic Dust (2091) and its Sleep spell (1090) debuff can be applied to some immune mobs to no effect.
### Current Behaviour

Using item Magic Dust on creatures such as Chromatic Elite Guard causes the Sleep aura to be applied but they will still move and attack without any animations being played.

### Expected Blizzlike Behaviour

Magic Dust and the Sleep aura should respect creature immunities.

### Source

_No response_

### Steps to reproduce the problem

1. `.additem 2091 10` `.learn 1090`
2. `.go c 10814`

or 

3. `.tele Plaguewood` and test on the creatures there

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/3575

Magic Dust (ID: 2091)
Magic Dust's Sleep (ID: 1090)

[https://youtu.be/YJMTzyz7Ux4](https://github.com/chromiecraft/chromiecraft/issues/url)

https://user-images.githubusercontent.com/100873791/171932238-e169ff7e-feeb-453d-8206-fb0a0bed6d99.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/2de12c79374bdb77396e60b2c44975ed69d8acec

### Operating system

Windows 10.

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
…get is too high level.

Fixes #11947

## Issues Addressed:

- Closes #11947
- Closes https://github.com/chromiecraft/chromiecraft/issues/3575

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.additem 2091 10` `.learn 1090`
`.go c 10814`
or
`.tele Plaguewood` and test on the creatures there

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by temperrr** [comment]
```>> ASSERTION FAILED

# Location '/mnt/data/azerothcore/src/server/game/Spells/Auras/SpellAuras.cpp:518'
# Function '_UnapplyForTarget'
# Condition 'auraApp->GetRemoveMode()'
 
#----------------------------------------------------------------------#
zsh: segmentation fault (core dumped)  ./worldserver
``` 
when 
.additem 2091
.go c id 10814
use the item on the chromatic guard

when using sleep no crash

**Comment by UltraNix** [comment]
@temperrr Should be okay now.

**Comment by acidmanifesto** [comment]
@azerothcore/testers this needs to be tested again.

**Comment by Gultask** [comment]
Works!

I got more interested in this a few days ago, so I went ahead and checked Wowhead. It seems that it was bugged at late-WotLK, as in it used to fail way more than it should, even against low-level enemies.
Furthermore, a failed cast shouldn't trigger the cooldown and also shouldn't consume a dust.

I had assumed that this bug was due to missing flags or something in the Sleep spell so I did not go to research it further, so I'm sorry to be dumping all of this in the PR.

All comments from: https://web.archive.org/web/20110904104113/http://www.wowhead.com:80/item=2091

>Very disappointed. This stuff is officially worthless now, at level 80 i tried to use this on a 78 non-elite in crystalsong forest and it fizzeled something like 100 times in a row, I decided it just wasnt going to work and proceeding to one shot the stupid satyr. I got it to work against a lvl 6 defias cutpurse though... oh and also a rat by the auction house... and after only 5 fizzles! (3.3.5)

>As a 39, I was able to get the dust to work once out of every 8 or 9 times on a level 7 mob in Dun Morogh. Each time the dust fizzled, it did not get consumed. When the dust finally worked, it did get consumed. (3.3.5)

>This dust has been nerfed further and now has a 100% chance to Fizzle (not work) as a level 80 character using this against another level 80 player. (3.2.0) (I think that's hyperbole)

>I just tried using this on a lvl 18 elite in Wailing Caverns, and it kept fizzling forever, making it officially useless. (3.2.0)

>Opened a petition and asked a GM about it. He said it is now 'Working as intended'. (3.2.0)

>Upon opening my own GM petition, i received a form letter indicating the item is known to bugged at this point in time, and should NOT be fizzling against mobs. (3.3.2)

**Comment by UltraNix** [comment]
@Gultask Test now.

**Comment by Gultask** [comment]
It's giving me the "Invalid Target" error and cancelling the cast most of the time. If I spam it I can get it to cast all the way but it fails with "Invalid Target" again at the very end.
But it works sometimes, casting all the way and without any errors and putting the target to sleep.

**Comment by UltraNix** [comment]
But this is what you linked:
`Each time the dust fizzled, it did not get consumed. When the dust finally worked, it did get consumed. (3.3.5)`

**Comment by Gultask** [comment]
I just thought it was weird that most of the time the cast never went off, and when it did it sometimes did not work, it was a bit inconsistent. The 'invalid target' might give people the wrong idea too, but idk...

It was nerfed only in 3.1.0 so Classic footage won't give us much. And I haven't found any WotLK videos that show it 'fizzling'. Sorry...

**Comment by UltraNix** [comment]
I will revert it and leave it as it was.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
