### PR TITLE
fix(Core/Clang): make it work with clang 10

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## CHANGES PROPOSED:
-  Fix error `fatal error: cannot assign to non-static data member within const member function 'SetGridId'
-  This will allow clang 10 compilation

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3066
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2927

## TESTS PERFORMED:

- Build

## HOW TO TEST THE CHANGES:

- Try to compile AC using clang 10 and run it, do a quick check in game

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by iThorgrim-Hub** [comment]
Not works for me ^^
```
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/BoundingIntervalHierarchy.h:10:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/BoundingIntervalHierarchy.cpp:7:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/BoundingIntervalHierarchy.h:10:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Collision/Maps/MapTree.cpp.o
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Management/VMapManager2.cpp:23:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Maps/MapTree.h:11:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/BoundingIntervalHierarchy.h:10:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Collision/Maps/TileAssembler.cpp.o
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Management/MMapManager.cpp:7:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/server/game/Maps/MapManager.h:13:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/server/game/Maps/Map.h:27:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Models/GameObjectModel.h:10:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Matrix3.h:18:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
[ 16%] Building CXX object src/common/CMakeFiles/common.dir/Collision/Models/GameObjectModel.cpp.o
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:106: src/common/CMakeFiles/common.dir/Collision/BoundingIntervalHierarchy.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Maps/MapTree.cpp:7:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Maps/MapTree.h:11:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/BoundingIntervalHierarchy.h:10:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:120: src/common/CMakeFiles/common.dir/Collision/DynamicTree.cpp.o] Error 1
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Maps/TileAssembler.cpp:7:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Maps/TileAssembler.h:10:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Models/GameObjectModel.cpp:10:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Models/WorldModel.h:11:/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Management/MMapFactory.cpp:7:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Management/MMapFactory.h:14:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/server/game/Maps/Map.h:27:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/src/common/Collision/Models/GameObjectModel.h:10:
In file included from /home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Matrix3.h:18:
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:118:25: fatal error: definition of implicit copy constructor for 'Vector3' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
    Vector3& __fastcall operator= (const Vector3& rkVector);
                        ^
/home/ithorgrim/World of Warcraft/_Source/AzerothCore/deps/g3dlite/include/G3D/Vector3.h:213:20: note: in implicit copy constructor for 'G3D::Vector3' first required here
            return Vector3::zero();
                   ^
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:190: src/common/CMakeFiles/common.dir/Collision/Maps/MapTree.cpp.o] Error 1
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:134: src/common/CMakeFiles/common.dir/Collision/Management/MMapFactory.cpp.o] Error 1
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:204: src/common/CMakeFiles/common.dir/Collision/Maps/TileAssembler.cpp.o] Error 1
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:148: src/common/CMakeFiles/common.dir/Collision/Management/MMapManager.cpp.o] Error 1
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:176: src/common/CMakeFiles/common.dir/Collision/Management/VMapManager2.cpp.o] Error 1
1 error generated.
make[2]: *** [src/common/CMakeFiles/common.dir/build.make:218: src/common/CMakeFiles/common.dir/Collision/Models/GameObjectModel.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1258: src/common/CMakeFiles/common.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by FrancescoBorzi** [comment]
@iThorgrim-Hub how can I reproduce it? I don't get those errors. For me it just works fine after this

**Comment by Viste** [comment]
@iThorgrim-Hub just use
```
cmake ../ -DCMAKE_INSTALL_PREFIX=/your/path -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=1(or 0) -DSCRIPTS=1```
and send this fucking ```-DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"``` from wiki to the genius who add this :)

**Comment by Viste** [comment]
https://paste2.org/dgwUEKDI

**Comment by FrancescoBorzi** [comment]
@Viste @iThorgrim-Hub https://github.com/azerothcore/wiki/pull/237

I also use just:

```
cmake ../ -DCMAKE_INSTALL_PREFIX=/my/path -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DTOOLS=1 -DSCRIPTS=1
```

and it works for me

**Comment by iThorgrim-Hub** [comment]
With @Viste cmake command it's work's 👍

**Pull request merged**
