### PR TITLE
fix(Core/Unit): Flight Form riding crop, vehicle speed auras

### PR DESCRIPTION
**Pull request by sogladev**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

Fixes interactions of flight form and riding crop.

Changes to vehicle speed auras handling and renames to match mounted speed increases

Take a look at 32223 Crusader Aura for example (spellwork ss below). `SPELL_AURA_MOD_VEHICLE_SPEED_ALWAYS` is poorly named, so it is renamed

```
206 SPELL_AURA_MOD_INCREASE_VEHICLE_FLIGHT_SPEED -> SPELL_AURA_MOD_INCREASE_FLIGHT_SPEED
208 SPELL_AURA_MOD_INCREASE_FLIGHT_SPEED -> SPELL_AURA_MOD_FLIGHT_SPEED_ALWAYS
210 SPELL_AURA_MOD_VEHICLE_SPEED_ALWAYS -> SPELL_AURA_MOD_FLIGHT_SPEED_NOT_STACKING
```

- Related PR https://github.com/azerothcore/azerothcore-wotlk/pull/16761

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16235

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

spellwork_crusader_aura

renames from https://github.com/cmangos/mangos-wotlk/commit/adb928a130cf2179afdf9b072b509886a6a673c2#diff-a3a435b3bd695cc249d08b981cdb8d6149373d04fa7f559e7591fbbcfc3aea28R256

also see handling in

https://github.com/cmangos/mangos-wotlk/blob/1b653c1b5bafbfab7d595feab963d438935e440a/src/game/Entities/Unit.cpp#L9427

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

only tested flight form

druid 70
.tele outland
.add 25653

print speed
```
/script print(string.format("speed%% %d", (GetUnitSpeed("Player") / 7) * 100))
/script print(string.format("speed %d",GetUnitSpeed("Player")))

```

280% mount
.learn 32297

note that having a 310% learned will give flying form 310% speed without updating tooltip

I did not check vehicles

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [x] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

Vehicle speed are affected, should be tested

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Can you please also prepare a PR for the module that fails the build

**Comment by sudlud** [comment]
please also merge master here for codecheck CI to pass

**Comment by sudlud** [comment]
just tested this on a lvl 70 druid according to https://github.com/azerothcore/azerothcore-wotlk/pull/16761#issuecomment-2002599612

- with `Riding Crop` equipped, druid flight and travel form do not get an increase in speed (as expected)

but on normal mounts the increase seems to be too much, still have to check with a version prior PR

`Riding Crop` should give 10% increase

what I observed is:
`Golden Gyrphon`
- flying 150% -> 175%
- walking 60% -> 76%

`Acherus Deathcharger`
- walking 100% -> 120%

this looks more like a 20% increase than 10%.

but this has also already not been correct in the other PR linked above. probably this also is not an issue (maybe)
also this is probably unrelated to this PR and could be a separate issue

**Review by sudlud — APPROVED** [review]

**Comment by manstfu** [comment]
```
/root/azerothcore/modules/mod-anticheat/src/AnticheatMgr.cpp:634:92: fatal error: use of undeclared identifier 'SPELL_AURA_MOD_INCREASE_VEHICLE_FLIGHT_SPEED'; did you mean 'SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED'?
    const bool no_fly_auras = !(player->HasAuraType(SPELL_AURA_FLY) || player->HasAuraType(SPELL_AURA_MOD_INCREASE_VEHICLE_FLIGHT_SPEED)
                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                           SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED


/root/azerothcore/src/server/game/Spells/Auras/SpellAuraDefines.h:270:5: note: 'SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED' declared here
    SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED            = 207,
    ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:258: modules/CMakeFiles/modules.dir/mod-anticheat/src/AnticheatMgr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1365: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by sogladev** [comment]
> Have you tested the Headless Horseman's mount? After the update, the Headless Horseman's mount animation has problems, and the horse's legs become very fast.

Is this a visual issue? Can you check with script below and see if the output is:
200% ground
380% fly

with trinket 220% ground
with trinket 417% fly 

```
/script print(string.format("speed%% %d", (GetUnitSpeed("Player") / 7) * 100))
/script print(string.format("speed %d",GetUnitSpeed("Player")))
```

**Comment by sogladev** [comment]
> Watch the video, other mounts are fine https://youtu.be/vf8VL3KXrnw

I checked with a commit before this PR a774bbd42514 and I am able to reproduce it after some attempts; This PR is not the cause, but you can open a new issue and reference the video

**Pull request merged**
