### PR TITLE
fix:(Scripts\ZulGurub): Razzashi Cobra's will act as Venoxis minions (trigg…

### PR DESCRIPTION
**Pull request by Ragelezz**
…er combat at once, reset, etc)

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/834

## Tests Performed:

- Engage Venoxis, he will not trigger combat on Razzashi or reset them if they are dead meanwhile (and also razzashi won't trigger combat to venoxis)
- 

## How to Test the Changes:

1. Engage Venoxis and now see those Cobras will get combat aswell (or engage cobra and venoxis will get combat aswell) also they will respawn if you wipe at Venoxis
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
why the issue has been already closed? it is already fixed on master? if not, we should keep open it until this PR will be merged

**Comment by Nyeriah** [comment]
Hello,

The changes proprosed in this PR could be done with `creature_formations` without requiring his minion to be scripted. Likewise, if his minions are supposed to respawn on wipes, you could use instance's minion data to handle their respawn.

The second's a suggestion, but I think formations would be a better answer to this, we don't need to add another script to them that way.

Regards

**Comment by Ragelezz** [comment]
All minions from bosses should have a C++ script inside boss script not a SAI or database work.

**Comment by Ragelezz** [comment]
@azerothcore/testers

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
