### PR TITLE
fix(Core/LFG): requirements, level ... ?

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by dualcorex** [comment]
What exactly should we test here? Is this just to verify the minimum levels for each dungeon when using LFG? This pull seems a bit vague, but I assuming from the title that it's start at level 15 and see if the dungeons that show up at each level in LFG match the minimum dungeon entry levels set by Blizzard. Am I on the right track or is it something else?

**Comment by IntelligentQuantum** [comment]
> What exactly should we test here? Is this just to verify the minimum levels for each dungeon when using LFG? This pull seems a bit vague, but I assuming from the title that it's start at level 15 and see if the dungeons that show up at each level in LFG match the minimum dungeon entry levels set by Blizzard. Am I on the right track or is it something else?

1. worldserver.conf Set JoinBGAndLFG.Enable = 0
2. .deserter bg add 20000 and join bg you should get error
3. Join heroic rdf with gs 0 you should get error

**Review by Nefertumm — APPROVED** [review]

**Comment by temperrr** [comment]
- [x] worldserver.conf Set JoinBGAndLFG.Enable = 0
- [x] .deserter bg add 20000 and join bg you should get error
- [x] Join heroic rdf with gs 0 you should get error
- [x] Join bg withou deserter and no error
- [ ] Join Normal rdf with gs 0 and you should not get error.  
image

**Comment by IntelligentQuantum** [comment]
> * [x]  worldserver.conf Set JoinBGAndLFG.Enable = 0
> 
>     * [x]  .deserter bg add 20000 and join bg you should get error
> 
>     * [x]  Join heroic rdf with gs 0 you should get error
> 
>     * [x]  Join bg withou deserter and no error
> 
>     * [ ]  Join Normal rdf with gs 0 and you should not get error.
>       image

tnx for test

**Comment by IntelligentQuantum** [comment]
@temperrr test please

**Comment by temperrr** [comment]
Can still not join normal dungeons?
image

**Comment by IntelligentQuantum** [comment]
@temperrr 

Screenshot_20220215_150245

**Comment by temperrr** [comment]
For me it shows I am locked on all my chars.

**Comment by IntelligentQuantum** [comment]
@temperrr please check this pr i close this https://github.com/azerothcore/azerothcore-wotlk/pull/10740

**Pull request closed without merging**
