### PR TITLE
DB/Creature: Spirit of Olum and Spirit of Udalo

### PR DESCRIPTION
**Pull request by grimgravy**
##### CHANGES PROPOSED:
- Fix conditions for the teleportation
- Add the missing teleportation to the Chamber of Command
- Fix gossip text
- Spirit of Udalo also has the teleport to the Command Chamber.
  
Closes [1639#](https://github.com/azerothcore/azerothcore-wotlk/issues/1639)

##### TESTS PERFORMED:

Window 7

##### HOW TO TEST THE CHANGES:
the correction was made by trinitycore a few years ago. I just updated

##### Target branch(es):

Test

### CODE REVIEW

**Comment by comix1988** [comment]
I tested this sql file, and it's okay with me.
tested first without sql file:
- the gossip for the teleport was still visible before killing any bosses;
- the gossip for the teleport didn't work even after killing the council;
tested with sql files:
- Gossip is unlocked when the council is killed and now works.

@grimgravy good job

**Comment by gtao725** [comment]
@grimgravy thx, does this also fix Spirit of Udalo?

**Comment by grimgravy** [comment]
@gtao725 not yet, being checked

**Comment by gtao725** [comment]
awesome, thank you!

**Pull request merged**
