### PR TITLE
fix(Scripts/BlackwingLair): Chromaggus should not attack units afflic…

### LINKED ISSUE #11182: [BWL] Chromaggus should not hit target that is timelapsed
### Current Behaviour

Chromaggus uses timelapses then continues to hit his target.

### Expected Blizzlike Behaviour

Like any stun, it should focus on the next target that is not stunned.

### Source

image
https://wowpedia.fandom.com/wiki/Chromaggus

### Steps to reproduce the problem

1. go to chromaggus
2. hide 1 char
3. aggro other char
4. get stunned on 1 char that has threat
5. notice other char that you put in hiding didnt get attacked

### Extra Notes

_No response_

### AC rev. hash/commit

9e7d1e2a3af7

### Operating system

Manjaro x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…ted by Time Lapse: Bronze.

Fixes #11182

## Issues Addressed:

- Closes #11182

## Tests Performed:

- Not tested.

## How to Test the Changes:

go to chromaggus
hide 1 char
aggro other char
get stunned on 1 char that has threat
notice other char that you put in hiding is now the victim

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
Doesn't work

**Comment by UltraNix** [comment]
@Lynethris You are testing this with progession_mode?

**Comment by Lynethris** [comment]
> @Lynethris You are testing this with progession_mode?

No

**Comment by UltraNix** [comment]
Just tested with one player - boss evaded when the stun buff applied.
With 2 players - boss ignores the one with stun and started attacking the 2nd player.
Please, test it again.

**Comment by Lynethris** [comment]
I start to compile again. But I see on the code and changes seems to impact the situation where players is stun by bronze affliction. But @temperrr issue is about the Time Lapse spell (https://classic.wowhead.com/spell=23310/time-lapse). Yes the spell and the aura have the same name.

Am I wrong?

**Comment by temperrr** [comment]
Yep this issue is about the one lynnethris linked.

**Comment by UltraNix** [comment]
Oh okay. My mistake.

**Comment by UltraNix** [comment]
@Lynethris Should be okay now.

**Comment by Lynethris** [comment]
It's work :)

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
