### PR TITLE
fix(DB): Lazy peons 'Work Work' sound removal in Valley of Trials

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Removed ACTION_PLAY_RANDOM_SOUND
- Added Sounds played to the creature_text instead

## Issues Addressed:

- Closes not reported issue

## Tests Performed:

- Tested on Windows 10

## How to Test the Changes:

1. Roam around Valley of Trials and check for Lazy peon's sounds.

## Known Issues and TODO List:

None.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Cinnamohn** [comment]
The play sound ids are 8 and 17, not 2, 12, and 21.

**Comment by savowe** [comment]
Yes. The delete statement target a lot of different stuff
grafik

**Comment by Cinnamohn** [comment]
The xxxx00 entries should target 8 and 17, the xxxx01 entries are correct as 2, 12, and 21 though.

**Comment by claudiodfc** [comment]
Thanks, I'll tend to it soon.

**Comment by savowe** [comment]
> And from what I can tell with the correction, they no longer blast you with "WORK WORK" at full volume while you're 100+ yards away.

And thanks for the clarification. From the PR description I could not be sure what differences I should look for.

@claudiodfc can you confirm this?

**Comment by claudiodfc** [comment]
Exactly @savowe

**Comment by savowe** [comment]
@claudiodfc 
a lot of them were very quite, but I still found some that were making random sounds.
Please delete them as well :)

grafik

**Comment by claudiodfc** [comment]
That should be everyone!

**Comment by savowe** [comment]
tested and works as described.

there has been another pr opened here https://github.com/azerothcore/azerothcore-wotlk/pull/9525

**Comment by Kitzunu** [comment]
Superseeded by https://github.com/azerothcore/azerothcore-wotlk/pull/9525 as it is sniffed

**Pull request closed without merging**
