### PR TITLE
fix(Scripts/ZulGurub): Improvements to Hazzarah encounter

### LINKED ISSUE #11612: [ZG] Edge of Madness - Hazza'rah - Missing/Wrong Spells
### Current Behaviour

Earth Shock (ID: 24685) is missing.
Chain Burn (ID: 24684) is missing and boss is using Mana Burn (25779 or 26046) instead, which he should not have.
The boss is using Summon Nightmare Illusions (ID: 24729) instead of the correct (ID: 24728)

### Expected Blizzlike Behaviour

Hazza'rah should have the following spells:
Earth Shock (ID: 24685), which he casts on primary target.
Chain Burn (ID: 24684), which he casts at a mana user, if none are found he does not cast chain burn.
Summon Nightmare Illusion (ID: 24728)

### Source

Chain Burn: https://youtu.be/4z6rJLuhWfM?t=29
Summon Nightmare Illusions (note the visual effects): https://youtu.be/4z6rJLuhWfM?t=18
Earth Shock: https://youtu.be/nN4-ecE0FnE?t=25

### Steps to reproduce the problem

If the Summoning Event is implemented:
`.event stop 27`
`.event stop 29`
`.event stop 30`
`.event start 28`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Hazza'rah

else:
`.go xyz -11905 -1911 66 309`
`.npc add temp 15083`

### Extra Notes

Hazza'rah NPC (ID: 15083)

Some sources such as Wowpedia claim that he does not use Chain Burn if he has no mana, which is odd because it costs no mana to use. Regardless, I've not seen a single video where draining his mana was used as a strategy.

The Summon Nightmare Illusion spell is a headscratcher. I don't know if it's used once, spawning 3 adds, or if it's used 3 times, summoning one add each cast. I do know that the adds spawn in a triangle formation around the caster, facing towards them, as seen in the video above. However, since the boss doesn't use that spell, I'm not sure how it'll work well enough to make a report.

Edit: From looking at the sources, the timers, *to me*, looks like:
Illusions: 16-24s, but with an average of 18s, since only a few times it went beyond 20s
Earth Shock: Minimum is 8s but I've seen it take as long as 30s for a cast to go off. Average of 13,4s, so maybe 8-18s?
Chain Burn: 12-28s, high variance, minimum of 12s, average of 20s
Sleep: ~15s after pull. 24-32s after that, average of 28s

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/d1b690e3fa89897b6eada5fc8ec11354227cf2d5

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Corrected timers of events.
Added missing/Removed invalid spells.
Fixes https://github.com/azerothcore/azerothcore-wotlk/issues/11612

## Issues Addressed:

- Closes #11612

## Tests Performed:

- Not tested.

## How to Test the Changes:

If the Summoning Event is implemented:
`.event stop 27`
`.event stop 29`
`.event stop 30`
`.event start 28`
`.additem 19931`
`.go xyz -11905 -1911 66 309`
use the brazier and engage Hazza'rah

else:
`.go xyz -11905 -1911 66 309`
`.npc add temp 15083`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
- [ ] Boss is casting Chain Burn even when there are no mana-users alive. He also casts it on the main target, even if it is a warrior.
 - [ ] Nightmare Illusion (ID: 15163) does not disappear when killed, leading to massive bodies piling up on the arena.
 - [ ] The Nightmare Illusions start attacking immediately, there should be a pause between spawning and attacking.
 - [ ] When Summon Nightmare Illusions is cast, the adds spawn immediately. They fade in correctly but there should be a delay between the visuals and the summon.
 - [ ] Boss is only using the 'walk' animation (like when you press '/') and not the normal one. But I think the speed is correct.
 
 - [ ] Also, sorry that I didn't include this in the issue, in vanilla footage he seems to ignore the tank after Sleep is cast. But there are also comments claiming that the first one to leave sleep is the tank because of the boss's attacks. I'll add some sources below.

https://user-images.githubusercontent.com/100873791/172028525-11c8e4cc-546b-42b5-b807-d4306e2c3053.mp4

https://youtu.be/4z6rJLuhWfM?t=40 He doesn't cast Chain Burn on the tank.

Sleep: 

[In Classic all threat is wiped](https://youtu.be/LusUKtJGG7U?t=2883) but Classic isn't 100% vanilla. Unfortunately this may be the best source I found since it has a threat meter.

 - At [0:33](https://youtu.be/4z6rJLuhWfM?t=33) he continues attacking the tank
 - At [0:58](https://youtu.be/4z6rJLuhWfM?t=58) he switches target and the tank has to taunt the boss off the new target.
 - At [1:38](https://youtu.be/4z6rJLuhWfM?t=98) he switches target but when the debuff runs out he then targets the tank again, however I did not see the taunt visual effect.
 - At [2:10](https://youtu.be/4z6rJLuhWfM?t=130) again it seems that the tank has to taunt the boss.
 - In this WotLK footage [here](https://youtu.be/nN4-ecE0FnE?t=30) and [here](https://youtu.be/nN4-ecE0FnE?t=56), the boss targets one of the DK's summons after the sleep.

In the WotLK footage it looks like there's a threat percentage counter on the boss' portrait, but I'm unsure how much that helps. When summons are present the percentage fluctuates a lot.

**Comment by UltraNix** [comment]
@Gultask Updates - please test it.
```
Nightmare Illusion (ID: 15163) does not disappear when killed, leading to massive bodies piling up on the arena.
```
Looks okay to me.

```
Boss is only using the 'walk' animation (like when you press '/') and not the normal one. But I think the speed is correct.
```
Boss is using running - this is how it looks with its current speed and its model.

**Comment by Gultask** [comment]
Weird, the bodies are still there when I kill them by auto-attacks, .damage and .die
I'll re-create the DB and check if that helps, because I clearly remember that they were disappearing when I wrote the issues.

Sleep is ending combat now.

And the summons may be spawning a bit too close to the boss, and not on the markers. It's not an issue in cramped environments but if there's open space they should be more spaced out. See video.

https://user-images.githubusercontent.com/100873791/172056976-2b7da6da-0c7b-4b50-a479-29b15907f3bc.mp4

**Comment by UltraNix** [comment]
@Gultask 
```
Sleep is ending combat and resetting the boss.
```
If you are the only one, then yes - it will reset. I beliee it's bliiz, as it's been reported that boss should not attack targets with Sleep.

**Comment by UltraNix** [comment]
Corpse delay/spawns position corrected.

**Comment by Gultask** [comment]
> If you are the only one, then yes - it will reset. I beliee it's bliiz, as it's been reported that boss should not attack targets with Sleep.

That would make soloing the boss impossible, and since the range is so large it affects the entire raid.
https://youtu.be/nN4-ecE0FnE?t=30 has a WotLK solo.

**Comment by UltraNix** [comment]
```
Also, sorry that I didn't include this in the issue, in vanilla footage he seems to ignore the tank after Sleep is cast
```

**Comment by Gultask** [comment]
Ah I see how that may be misleading. I'm sorry I'll try to word stuff better in the future.

By ignore I meant more as in he prefers to target other players instead of the tank, although that wasn't 100% the case.

[In Classic all threat is wiped](https://youtu.be/LusUKtJGG7U?t=2883) but Classic isn't 100% vanilla. Unfortunately this may be the best source I found since it has a threat meter.

Vanilla footage:

 - At [0:33](https://youtu.be/4z6rJLuhWfM?t=33) he continues attacking the tank
 - At [0:58](https://youtu.be/4z6rJLuhWfM?t=58) he switches target and the tank has to taunt the boss off the new target.
 - At [1:38](https://youtu.be/4z6rJLuhWfM?t=98) he switches target but when the debuff runs out he then targets the tank again, however I did not see the taunt visual effect.
 - At [2:10](https://youtu.be/4z6rJLuhWfM?t=130) again it seems that the tank has to taunt the boss.

In this WotLK footage [here](https://youtu.be/nN4-ecE0FnE?t=30) and [here](https://youtu.be/nN4-ecE0FnE?t=56), the boss targets one of the DK's summons after the sleep.

**Comment by UltraNix** [comment]
Looks weird. Sometimes ignores tank, sometimes attack other target with sleep, sometimes...

**Comment by UltraNix** [comment]
@Gultask Please, test it again.

**Comment by Gultask** [comment]
Looking very good! No issues from what I can see 👍 
Thanks for your work, Nix!

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
