### PR TITLE
fix(Core/ZG): Multiple improvements to High Priestess Mar'li

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Modernize her script.
-  Unhack spider spawning.
-  Fixed a lot of timers.
-  Added missing mechanics.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11531
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11529
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11617
- Partly closes https://github.com/azerothcore/azerothcore-wotlk/issues/11532 (spiders are not spawned anymore on spider phase)

## SOURCE:

Timers from CMangos/Provided source.

## Tests Performed:

- Tested in-game.

## How to Test the Changes:

1. Engage Mar'li and check she casts all the correct spells.
2. Wait for the spawns of Mar'li and check their growth.
3. With more players, check charge spell (this was not tested but the code was improved).

## Known Issues and TODO List:

- [ ] For some reason, gobjects don't despawn on activation.
- [ ] Gobjects casts... The spider spawn spells don't work as they should because of this, in consequence the spiders are spawning on Mar'li instead on the eggs.
- [x] Melee damage from Mar'li seems to be too high ?

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
This is the first time I'm testing like a boss like this so tell me if I'm being too nit-picky 😄 
Mar'li was the first boss I researched too so my issues may not be the better ones I did, sorry. I got better with time, I promise 😬 .

So here's what I've noticed:

- [ ] After Mar'li goes to Phase 2 (Spider Form) she keeps the dagger in her spider hands.
- [ ] Missing the yell "The brood shall not fall!" when transforming back
- [ ] Drain Life and Enlarge only happens once during fight, in the very first phase. After she transforms back into troll form, she won't cast Drain Life or Enlarge again.

Some things I totally to put in my reports (sorry!):
- [ ] She should ignore targets that have the Enveloping Web debuff, removing them from the threat table temporarily ([video source](https://youtu.be/G3hipBd_hfI?t=106))([video source 2](https://www.youtube.com/watch?v=YKIWvzNHIIg))
- [ ] Charge is... interesting. I'll do some research then report back here if I find anything.

Since Hatch Eggs is broken for now, I placed the adds through `.npc add temp 15041` and Growth/Full Grown work fine!

Now to nit-pick:
- [ ] Transformation is not blizz-like, as she currently transforms fully grown and does not get larger over the course of 2 seconds. And there should be a small delay between the SAY_TRANSFORM and the actual transformation.

Oh! and yes, the physical damage is way too high from all the bosses I saw so far. We need to talk with M'Dic at some point to address that. I think the damage is from sniffs?

WoWScrnShot_052022_170006

**Comment by Nefertumm** [comment]
Thank you, I'll address the issues soon. I don't get the missing yell though, since it was added on the code and sql. Did you ran the sql correctly right? 🤔

**Comment by Gultask** [comment]
omg 🤦 I did forget to run the SQL. I'll re-test everything ASAP.

**Comment by Nefertumm** [comment]
@Gultask do you mind checking it again ? :)

**Comment by Nefertumm** [comment]
I didn't change the weapon thingy on transform and the transform is not blizzlike yet, but soon

**Comment by Gultask** [comment]
Tested with 2 characters and solo.

 - [ ] If Enveloping Webs hits all targets, the boss resets. Also happens if you solo her.

And that's all I've found, looks good so far! 👍

**Comment by Gultask** [comment]
Ugh, I'm sorry Nef, I didn't know [this video](https://youtu.be/-Tj_U5YDM4E?t=62) existed. It's WotLK footage with very good quality and clearly shows that Enveloping Web **does** remove threat. [This one](https://youtu.be/Lm4gm2zEcBM?t=62) also shows the threat wipe and the Charge hitting the player and dealing a bit of damage comparable to a melee hit.

**Comment by Nefertumm** [comment]
Now Charge should work, I didn't change the timer though since I think it's okay to cast charge only after enveloping webs (it's stated on wiki as she would charge after webs if she can).
I changed the transformation, she should not have her dagger on her hand anymore after transforming, and I restored the code from the threat drop.
Test it whenever you can, please. :)

**Comment by Gultask** [comment]
It looks great!

I think everything that's left now is cosmetic/visual, but it's functioning really well. Nice work, Nefertum 👍

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
