### PR TITLE
[Core / Script] Mr Smite Event Update

### LINKED ISSUE #1337: Deadmines: Mr Smite not resetting events on wipe
##### SMALL DESCRIPTION:
After wiping on Mr Smite the second time you fight him he will do all his emotes twice.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
Events reset and he'll only do each emote once.

##### CURRENT BEHAVIOUR:
Each time Mr Smite resets he's scheduling his stomp/emote/run to the chest events for 66% and 33% health. However these aren't being reset between attempts, so if you die 4 times at the start of the fight he'd do each emote 5 times the next time.

##### STEPS TO REPRODUCE THE PROBLEM:
1. Go to Mr Smite ".tele creature id 636" will take you to his adds
2. Die, target self .die
3. Fight him again properly, he'll do each emote twice at 66% and 33% health.

##### EXTRA NOTES:
This might be due to patrols not pathing (being worked on here https://github.com/azerothcore/azerothcore-wotlk/pull/876) but also when you pull Mr Smite you always get a pirate, squalshaper and goblin add, these shouldn't be adding. Similarly it's impossible to pull any NPC from the top deck of the ship without pulling VanCleef.

BRANCH(ES):
master

AC HASH/COMMIT:
a8621e4

OPERATING SYSTEM:
Windows 10

MODULES:
VAS Autobalance, Individual XP

OTHER CUSTOMIZATIONS:
None

### PR DESCRIPTION
**Pull request by talamortis**
Fixed an issue where Mr Smite would do his stomp event more than once.

##### CHANGES PROPOSED:

-  Fixed an issue where Mr smite would do event more than once.
-  

###### ISSUES ADDRESSED:

Closes #1337 

##### KNOWN ISSUES AND TODO LIST:

- [ ] Needs testing due to edited code at work :+1: 
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Trystanosaurus** [comment]
I've tried this update, killing him both first time and dying a few times first and it seems to work perfectly now. Thanks for the fix.

**Comment by poszer** [comment]
The fix is good. Tested in game, the event resseting after wipes. Thanks @talamortis

**Comment by talamortis** [comment]
Thanks for testing, will merge

**Comment by BarbzYHOOL** [comment]
ty guys

**Pull request merged**
