### PR TITLE
fix(DB/object): Pool copper veins on Bloodmyst Isle

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Pool all copper veins (there are only 3 of them, so the direct value of this PR is limited... but it makes sense if more spawn points are added later)

## Issues Addressed:
- This is a nicer way to control mining nodes
- Relevant for AzerothCore issue #4518 (but it does not close it)

## Tests Performed:
- Teleport around

## How to Test the Changes:

```
.go xyz -2411.3 -11965 13.399 530 -- 120324 Bloodmyst Isle, Copper Vein, spawn 1
.go xyz -2614.69 -12192.1 28.0703 530 -- 120325 Bloodmyst Isle, Copper Vein, spawn 2
.go xyz -2623.13 -11772.2 9.2479 530 -- 120363 Bloodmyst Isle, Copper Vein, spawn 
```

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Stifler82 — COMMENTED** [review]
you have to put more spawn points here, they are too few ..
at least another 7 - 8 at least..

WoWScrnShot_022321_190107

**Comment by Zoidwaffle** [comment]
@Stifler82 - I'm already working on a follow up... This is just making a pool.

I have 180 spawn locations mapped out, just need to sort out some logic before making a PR.

**Review by Helias — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> @Stifler82 - I'm already working on a follow up... This is just making a pool.
> 
> I have 180 spawn locations mapped out, just need to sort out some logic before making a PR.

are you planning to do it in this PR or will open a new one for that? just wondering, both options are fine.

**Comment by Zoidwaffle** [comment]
I would actually prefer this one to get merged in first - and then make a "generic pool upgrade for a zone" PR afterwards, since it could be relevant to do something similar for... well... all zones. It's a lot of work, but focusing on the lower levels zones first, could be a nice improvement for ChromieCraft.

I'm cross-posting from issue #4518, but here's what I wrote (with a few edits):

---

I spend a bit of time on it - and it's kinda fun to try and make this stuff work automatically... But besides that, there are a few things to consider.

There are 180 spawn points for Bloodmyst divided into something like ~100 copper, 50 tin and 30 silver.

One way would be to simply make a giant pool with all of these... and if only 20 spawn, relatively speaking, it's most likely to be copper etc., making the "rare" veins rare.

Another solution, as I can see they went for in the Ghostland zone, would be making ~100 nodes (all the copper locations) and then make them spawn where there's 70% for copper, 20% for tin and 10% for silver...

The "make all 180 spawns" would bring the map into pretty much exactly matching the "Gathermate" addon (I literally took the coordinates from there). The "make spawns able to be 3 things" would perhaps be more elegant, at the cost of a slightly more advanced db-structure.

Personally I might prefer to just use all 180 spawns and call it a day. Then if weird spawns are found, they can just be removed or relocated a bit...

Either way, both options are superior as compared to now IMHO... And I assume something similar could/should be be done for more zones, so I'm trying to see if I can make this "the AC way of handling nodes for herbs/minerals".

Anyone with strong preferences regarding this?

**Pull request merged**
