### PR TITLE
fix(DB/creature): Move Ashenvale Elder Bear spawn

### PR DESCRIPTION
**Pull request by Azcobu**
## Changes Proposed:
- Moves an Ashenvale Elder Bear (ID 3810) spawn slightly so it isn't wedged into a cliff face and can move freely instead of being stuck.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7746
- Closes https://github.com/chromiecraft/chromiecraft/issues/1639

## SOURCE:

NPCs should not be wedged into geometry.

## Tests Performed:

- Ran SQL, no errors/warnings, 1 row changed as expected.
- Checked in-game, bear is now roaming freely and not stuck:

WoWScrnShot_090621_214104

## How to Test the Changes:

1. .go c 34360 and observe.

## Known Issues and TODO List:

N/A.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Si1ker** [comment]
@Helias @Azcobu 

Without applying the fix, I have no issues with this NPC, I have vmap support enable in worldserver config to help the z calculation

image

**Comment by Si1ker** [comment]
I have read your issue, no point here. Please, don't change game data by personal preference/opinion without any base.

image

**Comment by gurveleg** [comment]
teste don my local AC, AzerothCore rev. 728839b84952 2021-09-05 10:02:31

https://user-images.githubusercontent.com/80769357/132481269-7b0f86af-b9ab-4832-a5dc-f3422cd42df8.mp4

Say what you will, but this is clipping and preventing roaming.

**Comment by Azcobu** [comment]
> game data by personal preference/opinion without any base.

This change is closer to known game data than AC is. The bear's current coords are 61.1, 63.5. If you look at the spawn map for the bear [here](https://tbc.wowhead.com/npc=3810/elder-ashenvale-bear#map) you will find no spawns further west than 61.4, and none in its current location. The two closest spawns are 61.4, 63.4, and 61.4, 63.8. I've split the difference and put the new spot at 61.4, 63.6. I can't imagine how or why the bear being wedged motionless in placed would be considered acceptable or Blizz-like behaviour, but its current position is demonstrably neither accurate or Blizz-like whether it's wedged in place or not. Of course, TBC WH data isn't particularly reliable and normally this level of detail would be somewhat pointless, but if you want a foundation for the change, that's the data we have. 

Also, this insistence on the purity of the AC database is very odd given the number of other NPCs we've found spawning in rocks, trees, buried in the landscape, floating through treetops, etc. NPCs are routinely out of position by tens of yards.

**Comment by Si1ker** [comment]
> > game data by personal preference/opinion without any base.
> 
> This change is closer to known game data than AC is. The bear's current coords are 61.1, 63.5. If you look at the spawn map for the bear [here](https://tbc.wowhead.com/npc=3810/elder-ashenvale-bear#map) you will find no spawns further west than 61.4, and none in its current location. The two closest spawns are 61.4, 63.4, and 61.4, 63.8. I've split the difference and put the new spot at 61.4, 63.6. I can't imagine how or why the bear being wedged motionless in placed would be considered acceptable or Blizz-like behaviour, but its current position is demonstrably neither accurate or Blizz-like whether it's wedged in place or not. Of course, TBC WH data isn't particularly reliable and normally this level of detail would be somewhat pointless, but if you want a foundation for the change, that's the data we have.
> 
> Also, this insistence on the purity of the AC database is very odd given the number of other NPCs we've found spawning in rocks, trees, buried in the landscape, floating through treetops, etc. NPCs are routinely out of position by tens of yards.

"Also, this insistence on the purity of the AC database is very odd given the number of other NPCs we've found spawning in rocks, trees, buried in the landscape, floating through treetops, etc. NPCs are routinely out of position by tens of yards."

All of those issues were fixed in a single PR by UltraNix when we got problems with the Height Z calculation
With vmap support enabled on the worldserver config and vmaps v11 , all of those issues are gone, you can find another bunch of people against personal opinions to change game data just because

**Comment by Azcobu** [comment]
Not sure what you're trying to say there. I was thinking of issues like https://github.com/azerothcore/azerothcore-wotlk/issues/7342, https://github.com/azerothcore/azerothcore-wotlk/issues/6545 or https://github.com/azerothcore/azerothcore-wotlk/issues/6116.

Anyway, as I haven't seen any arguments or data suggesting that the bear's new position is inaccurate or not Blizz-like, resuming PR as per usual.

**Pull request merged**
