### PR TITLE
Core/Spells: fix deterrence melee hits

### PR DESCRIPTION
**Pull request by GitVerge**
##### CHANGES PROPOSED:

-  Deterrence will make you parry melee auto attacks, if possible.

Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/1522

##### TESTS PERFORMED:
None

##### HOW TO TEST THE CHANGES:
- Cast deterrence when npcs auto attack you

##### KNOWN ISSUES AND TODO LIST:
 
- Check if we also have issues with melee spells or any spell

##### Target branch(es):

Master

### CODE REVIEW

**Comment by TheHighlord** [comment]
I think SPELL_AURA_MOD_PARRY_PERCENT spell aura effect should be fixed in the core, not for a specific spell.

**Comment by GitVerge** [comment]
It could be done that way, this aura mod is already implemented but probably something in the parry cap formula is breaking the %. If someone has a screenshot of parry chance after using deterrence ingame it could be useful to know.

**Comment by TheHighlord** [comment]
@GitVerge 
kar

Hmm... it shows 0.00%

**Comment by GitVerge** [comment]
Could you try with my last commit?

**Comment by TheHighlord** [comment]
> Could you try with my last commit? @TheHighlord

Still 0 %

**Comment by GitVerge** [comment]
Is your defense skill at max level?

**Comment by TheHighlord** [comment]
> Is your defense skill at max level?

Yep.

kar

**Comment by GitVerge** [comment]
Ok I will test it when I have time and fix it

**Comment by Viste** [comment]
these aren't the droids you're looking for...

**Comment by GitVerge** [comment]
> these aren't the droids you're looking for...

hi, any ideas? ^^

**Comment by Viste** [comment]
yes you see it soon in my PR

**Comment by BarbzYHOOL** [comment]
> Ok I will test it when I have time and fix it

Did you test it @GitVerge ?

**Pull request closed without merging**
