### PR TITLE
Fix NPC 28611 (Scarlet Captain) in the DK area

### PR DESCRIPTION
**Pull request by Stoabrogga**
He now shoots from a distance and says the correct text lines on aggro.

**Changes proposed:**
smart_scripts:
- Set min and max distance for shoot and corrected the comment for ID 0
- Added ID 4 to say the correct text lines on aggro

creature_text:
- Delete wrong text line "Light bless you, my child.", which is not contained in the quotes (see https://wowgaming.altervista.org/aowow/?npc=28611)

**Target branch(es):** master

**Issues addressed:** Closes #

**Tests performed:** tested in-game:
1. .npc add 28611 (NPC does not attack from a distance, just stands there)
2. apply SQL script
3. .reload smart_scripts
4. .reload creature_text
5. .npc add 28611 (NPC says correct text lines on aggro and shoots from a distance)

**Known issues and TODO list:** none

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Motorheadx** [comment]
tested and works but it is better to do 2 and 30 distance from the shot.When 5 and 30 there is a gap where he does not attack auto attack and shoot

**Comment by Stoabrogga** [comment]
You're right. Reduced the min distance from 5 to 2.

**Comment by Motorheadx** [comment]
=))

**Comment by Deku** [comment]
@Stoabrogga is this ready to merge?

**Comment by Stoabrogga** [comment]
Yes, I think this can be merged, it is working good now.

**Comment by Deku** [comment]
@Stoabrogga thanks for your work!

**Pull request merged**
