### PR TITLE
chore(bash/docker): Docker installation support for ARM64 machines

### LINKED ISSUE #10851: ./acore.sh docker client-data failed on macbook m1
### Current Behaviour

Running: docker-compose run --rm ac-build bash acore.sh client-data
[+] Running 0/1
 ⠋ ac-database Pulling                                                     4.9s
no matching manifest for linux/arm64/v8 in the manifest list entries
error: Uncaught (in promise) Error: Failed with error: 18, however,
            it's not related to this Deno script directly. An error occurred within
            the script called by the command itself
          throw new Error(`Failed with error: ${status.code}, however,
                ^
    at Command.<anonymous> (file:///Users/chenyang/azerothcore-wotlk/apps/docker/docker-cmd.ts:290:17)
    at async Promise.all (index 0)
    at async file:///Users/chenyang/azerothcore-wotlk/apps/docker/docker-cmd.ts:240:5

### Expected Blizzlike Behaviour

apps/docker/docker-cmd.ts should be modified to work on macbook m1

### Source

_No response_

### Steps to reproduce the problem

1. git clone https://github.com/azerothcore/azerothcore-wotlk.git
2. cp conf/dist/config.sh conf/config.sh
3. ./acore.sh docker client-data

### Extra Notes

_No response_

### AC rev. hash/commit

743c028e31740afebe73afa15ee0ed2e1b4926da

### Operating system

mac os 12.2.1 macbook air m1 

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by podmepodme**
Before this change, ./acore.sh docker build failed on ARM MacBook.
With url updated, i was able to run AzerothCore from docker and successfully logged in to game.

This is repo from which url was taken: https://github.com/LukeChannings/deno-arm64

## Changes Proposed:
-  replaced deno_install.sh link for one which also include arm version

## Issues Addressed:

- Already closed but not implemented
- Closes  #10851

## Tests Performed:

- Running  ./acore.sh docker build will result in following error: 

image

Sorry for screenshot, i don't know how to format output properly.
Test was performed on MacBook Pro 14 M1 running Ventura 13.4.1 (c) 

## How to Test the Changes:

1. in repo: ./acore.sh docker build

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
As there is no active docker developer I will leave this open in hopes someone wants to test it.

Worst case I will just merge it and if it were to break something we can just revert it.

**Comment by walkline** [comment]
I wouldn't recommend using someone's personal gist as a default dependency option. Perhaps consider using this gist as a fallback option for only arm64 platform instead?

But in general JS runtime dependency to build a C++ project looks weird to me 😁

**Comment by michaeldelago** [comment]
Whats the licensing on the gist link? We should vendor it in the repo if we intend to use it, rather than referring to it like that.

**Comment by podmepodme** [comment]
I like the idea of including script in the repo. however i I couldn't find license in deno-arm64 repo. I will contact the author about this. 

Maybe we could get rid of deno altogether, but for now it will be easier just to include the script.

**Comment by podmepodme** [comment]
Author specified license in the script (MIT).

Can i include this script (and edit apps/bash_shared/deno.sh accordingly ) in next commit for this PR? Sorry for asking trivial questions, this is my first PR in open-source project.

**Comment by podmepodme** [comment]
@michaeldelago did a great job in PR https://github.com/azerothcore/azerothcore-wotlk/pull/16898, which removes deno as a dependency from the docker build. As far as I know, this dependency is the only reason why AzerothCore did not build on the arm machines from Docker. Because of that, I am closing this PR.

**Pull request closed without merging**
