### PR TITLE
fix(DB/creature_template): Disciple of Naralax walking speed

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  He should walk much slower (from 1.4 to 0.8)
- The number 0.8 was selected as a "seems about right" number. Anything from 0.7-0.9 is probably fine.

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5011
- Closes https://github.com/chromiecraft/chromiecraft/issues/297

## SOURCE:

- https://youtu.be/xeW3Nl9akYA?t=1721 - from Classic, but he's slow as molasses going uphill on a cold day

## Tests Performed:

- Applied SQL
- Did the quest. He walks slowly... but when testing, I found out there's more wrong... The issue is here:  https://github.com/azerothcore/azerothcore-wotlk/issues/4953. This does not invalidate this PR, but there's more to fix afterwards...

## How to Test the Changes:

In order to start the event which makes Disciple of Naralex start walking, you must kill the 4 Leaders of the Fang
They can be found here:
.go creature 27380
.go creature 27366
.go creature 87107
.go creature 38148

Once they are dead go to the Disciple of Naralex:
.go creature 18675

Talk to him and select the gossip option "Let the event begin!"
He will begin to walk away.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Hacki95** [comment]
This might be out of the scope for this PR, but if you have an idea how we can get him to help with fighting the adds and slow down the spawning of the mobs at the end it would be nice if we can add those fixes here aswell.

**Comment by Zoidwaffle** [comment]
Well, I guess it involves some SAI. I have done some simple stuff earlier so perhaps I can fix it... But I'm not super good at it. And it's a different issue, found it when testing this one... Perhaps some inspiration can be found here https://github.com/azerothcore/azerothcore-wotlk/pull/4324 at least for the aggro part.

**Comment by Hacki95** [comment]
> 
> 
> Well, I guess it involves some SAI. I have done some simple stuff earlier so perhaps I can fix it... But I'm not super good at it. And it's a different issue, found it when testing this one... Perhaps some inspiration can be found here #4324 at least for the aggro part.

All good! I just found out how this encounter works and I will submit a PR for it.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
good job

**Pull request merged**
