### PR TITLE
fix(DB/Characters): enum missing type of module

### PR DESCRIPTION
**Pull request by Meramaf**
## Changes Proposed:
-  Correct Worldserver Startup

## Issues Addressed:

- Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/9257

### CODE REVIEW

**Comment by Kitzunu** [comment]
Yo,
there is nothing wrong with worldserver startup. Why are you making these changes?

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/updates/db_characters/2021_11_06_00.sql

**Comment by Meramaf** [comment]
Hey, these changes correct the addressed issues https://github.com/azerothcore/azerothcore-wotlk/issues/9257

**Comment by Winfidonarleyan** [comment]
> Hey, these changes correct the addressed issues #9257

Try make clean DB

**Comment by Meramaf** [comment]
> > Hey, these changes correct the addressed issues #9257
> 
> Try make clean DB

Here with a clean database, it's because of the transmog module

image

image

**Pull request closed without merging**
