### PR TITLE
fix(Core/Cooldowns): SPELLMOD_COOLDOWN should not affect category coo…

### LINKED ISSUE #6391: [Warrior] Talent "Improved Disciplines", and the "12 seconds cooldown on the 3 spells"
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/826

##### CURRENT BEHAVIOUR:

It seems like having specced "Improved Disciplines" (I have 2/2, maybe 1/2 also does it?) makes that using one of the three spells "Retaliation", "Shield Wall" or "Recklessness" does not trigger the "display" of the 12 seconds cooldown so that you can't have two or more of those spells active on you at the same time.
Nonetheless, you still can't stack these spells.
Here is a video, also showing that you can't stack the spells: https://youtu.be/0ZawfOiAV30

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The "12 seconds cooldown" should start on the other spells and be displayed in tooltip.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Spec Improved Disciplines 2/2
2. Use Retaliation
3. Hover over "Shield Wall" ability to see tooltip without the 12 seconds cooldown

##### EXTRA NOTES:

Maybe it is a client side issue, so can't be fixed? I'm not sure so I felt like I should still report it.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/617a935ee469641f3689061bb390158040b5d8d7

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 466cdb6 ) :

WoWScrnShot_061721_133255
WoWScrnShot_061721_133302

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99325164-warrior-talent-improved-disciplines-and-the-12-seconds-cooldown-on-the-3-spells?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…ldowns.

Fixed #6391.

## Changes Proposed:
-  Category cooldowns shouldn't be affected by `SPELLMOD_COOLDOWN`.

## Issues Addressed:

- Closes #6391
- Closes https://github.com/chromiecraft/chromiecraft/issues/826

## Tests Performed:

- Tested ingame

## How to Test the Changes:

1. Spec Improved Disciplines 2/2
2. Use Retaliation
3. Hover over "Shield Wall" ability to see tooltip

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by pklloveyou** [comment]
The Chinese client does not have this error O.o

**Comment by pklloveyou** [comment]
Tested

**Comment by pklloveyou** [comment]
Errors found

**Comment by pklloveyou** [comment]
Druid's star falling spell. After using the glyph of star falling, the spell can't be released after the spell cools down

**Comment by UltraNix** [comment]
What is Star Falling?

**Comment by pklloveyou** [comment]
image
image

**Comment by pklloveyou** [comment]
```.ad 40921```
use 40921
```.c 48505```

**Comment by UltraNix** [comment]
@pklloveyou Try now.

**Comment by pklloveyou** [comment]
It works normally this time, but it still needs to be tested by others. The original repair needs to be tested

**Comment by FrancescoBorzi** [comment]
> It works normally this time, but it still needs to be tested by others. The original repair needs to be tested

@azerothcore/testers please check this

**Comment by FrancescoBorzi** [comment]
> I think it can be merged.

ok for me

**Pull request merged**
