### PR TITLE
fix(Core/Spells): Implemented spell proc phases.

### LINKED ISSUE #9634: Mage's Fingers of Frost talent is proc on hit
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2537

FoF right now is both proccing and consuming on-hit rather than on-cast. This might not mean a lot at first glance but it should allow mages to react and plan quicker when a proc occurs, specially in pve where travel distances can be huge, resulting in the loss of the FoF "Ghost Charge" uses since you can't really predict when the consumes happen.

Tester:

The issue is confirmed. Mage's [Fingers of Frost](https://wowgaming.altervista.org/aowow/?spell=44543) talent is proc and consume on hit

https://user-images.githubusercontent.com/85256266/145609471-a2384f37-a377-4b3c-9d31-2a80f8f123b7.mp4

### Expected Blizzlike Behaviour

**_Both the trigger and the consume should be consumed on cast_**. Just a reminder that the cast that procs FoF should not consume nor benefit from it (unless the cast that procs the talent isn't casted during a previous FoF I'd assume). 

Keep in mind that the famous Ghost charge should still be possible even wit this change, meaning a 3rd instant spell should benefit from FoF if this spell is casted right after the spell that consumes the last stack of the talent. Getting the ghost charge to work seems like the tricky part because from what I read it happened either due to latency or maybe the spell queue system that prob snapshotted the buff (wich doesn't seem to be implemented here at all).

**Retail video of the Proc happening on cast can be seen [here](https://youtu.be/8ET2Ct9_Ma8?t=24), it happens @ 26 seconds just slow down the video to 0.25 secs.** If you go further along the video there's plenty of examples of the talent being triggered and consumed on cast.

 Example of ghost charge use: frostbolt (procs fingers) > frostbolt (consumes 1/2 FoF) > frostbolt + ice lance/deep freeze/brain freeze (consumes last stack while both benefitting from the crit increase).

### Source

https://web.archive.org/web/20101204052143/http://www.worldofwarcraft.com/patchnotes/patch3p3.html
Patch 3.3 "Fingers of Frost: This talent now triggers immediately on casting a spell rather than being delayed until the spell strikes the target."

https://www.mmo-champion.com/threads/677129-Fingers-of-Frost-Change
"Also, it wont affect the ghost charge because this is already how the removal of the buff works. The buff fades on spell cast, not hit. Ghost charge is all latency."

### Steps to reproduce the problem

.go c 48335
.aura 44545
.cast 116

### Extra Notes

https://wowgaming.altervista.org/aowow/?spell=44545

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #9634

## Changes Proposed:
-  Set proper proc phase to some spells (ported from TrinityCore)

## Issues Addressed:

- Closes #9634
- Closes https://github.com/chromiecraft/chromiecraft/issues/2537

## Tests Performed:

- Not tested

## How to Test the Changes:

.go c 48335
.aura 44545
.cast 116

For Druid's Nature's Grace:
Pickup Nature's Grace: talent
Set spell critical chance to 100
Cast Wrath at some target - Nature's Grace should proc off on spell cast.
Cast another Wrath immediately - Nature's Grace should affect that cast and be consumed before the 1st Wrath hits the target.

For Shaman's Elemental Mastery:
Pickup Elemental Mastery talent
Cast Elemental Mastery 
Cast Lightning Bolt at some target - you should get spell haste buff on cast.
Cast another Lightning Bolt - spell haste buff should affect that cast  before the 1st Lightning Bolt hits the target.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@azerothcore/testers Please, test it.

**Comment by temperrr** [comment]
tested

works as described.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Why do we have two seperate sqls?
Why can we not consolidate it to one?

**Comment by UltraNix** [comment]
Because one of them is a modification in table.

**Review by acidmanifesto — APPROVED** [review]
just got a second opinion from a staffer and they stated that two sqls is fine in the pr. Originally i was lead to believe this would of caused issues but i am happy that is not the case.

**Comment by Kitzunu** [comment]
Update wiki please

**Comment by FrancescoBorzi** [comment]
> Update wiki please

@UltraNix has this been addressed?

**Comment by UltraNix** [comment]
@FrancescoBorzi I will do it before merge.

**Pull request merged**
