### PR TITLE
Implement blink v4.5 for AzerothCore

### PR DESCRIPTION
**Pull request by kvipka**
http://forum.deadmines.org/threads/blink.7/

**Changes proposed:**

[ ]blink in abyss
[ ]blink by path ( rechecking each step )
[ ]where player can walk - blink will available there
[ ]implemented check on dynamic objects (locked doors and etc)
[ ]implemented total path of blink.

**Target branch(es):** 1.x/2.x etc.
3.3.5a
**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc)

**Known issues and TODO list:**
https://github.com/azerothcore/azerothcore-wotlk/issues/381#issuecomment-283071406
**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/pull/15796

**Comment by talamortis** [comment]
Has anyone tested this?

**Comment by Rushor** [comment]
yes. i works great.

**Comment by talamortis** [comment]
Thank you :) will merge

**Comment by Rushor** [comment]
@talamortis don't forget to apply this change in spelleffects too https://github.com/TrinityCore/TrinityCore/pull/15796/files#diff-b3ff7e4adf5326d9790d99d1dee0da2dL4611

**Comment by talamortis** [comment]
could you please do PR for it @Rushor?

**Comment by Rushor** [comment]
@kvipka finish it pls. kthx

**Comment by kvipka** [comment]
For AC in effectleap no corrections in spelleffects:
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/game/Spells/SpellEffects.cpp#L4698

**Pull request merged**
