### PR TITLE
fix(DB/EversongWoods): Fix sit position of benches

### PR DESCRIPTION
**Pull request by SoglaHash**
Character sits at the wrong Z-position.

## Changes Proposed:
Fix Data1(height) of these 2 benches. Similar to nearby benches like id: 184706

## Issues Addressed:
https://github.com/azerothcore/azerothcore-wotlk/issues/10566

## Tests Performed:

```
.go gameobject 25520
.go gameobject 25518
```
chair_fixed2

## How to Test the Changes:

```
.go gameobject 25520
.go gameobject 25518
```
Sit on the benches

## Known Issues and TODO List:

- [ ] Blood elf males glitch their legs through the bench, but I think that's blizzlike 

chair_fixed

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Globaly better, but I got also an issue with human and gnome. Think depend to the modele. I will try to look on Woltk classic PTR.

**Comment by Maelthyrr** [comment]
Check and it's not relly better on classic.

**Review by Kitzunu — CHANGES_REQUESTED** [review]
This should be sniffed.

**Review by Helias — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@heyitsbench or @neifion-00000000 are you guys able to sniff out the benches for this PR to be adjusted or consider valid?

**Comment by heyitsbench** [comment]
> heyitsbench or neifion-00000000 are you guys able to sniff out the benches for this PR to be adjusted or consider valid?

I can get it done in a bit (if they do show up in sniffs), it's only fitting.

**Comment by heyitsbench** [comment]
Can't get any parsed sniffs from Wrath Classic at the moment (waiting on WPP), but here's one from 2.5.2.

```
ServerToClient: SMSG_QUERY_GAME_OBJECT_RESPONSE
Entry: 184705
Allow: True
Type: 7 (Chair)
Display ID: 6979
[0] Name: Bench
[0] Data: 1
[1] Data: 1
Size: 1

ServerToClient: SMSG_QUERY_GAME_OBJECT_RESPONSE
Entry: 184707
Allow: True
Type: 7 (Chair)
Display ID: 6979
[0] Name: Bench
[0] Data: 1
[1] Data: 1
Size: 1
```

**Comment by Maelthyrr** [comment]
@SoglaHash did you look with the sniffs from 2.5.2 or is it abandoned?

**Comment by SoglaHash** [comment]
> @SoglaHash did you look with the sniffs from 2.5.2 or is it abandoned?

Hi, thank you for the reminder. 

The sniffs to indicate that the original data is correct and `Data1` should remain at 1. 

I discovered there are similar benches with displaymodel 6979 that don't suffer from the "graphical bug" reported in the issue with `Data1=2`. However there are others that do with `Data1=1`. 

I list 2 examples:
```
Data1=2 gameobject_template 187217; entry 47556;  `.go gameobject 47556`  
Data1=1 gameobject_template 185888; entry 20522; `.go gameobject 20522` 
```

I believe the "graphical bug" is blizzlike for the benches mentioned in the issue and others with the same displaymodel

**Comment by Maelthyrr** [comment]
Ok, as the actual values in the DB are correct, I will close this PR. It's maybe a blizz bugs or related to coordinate issues with the gob system. Need more investigation.

**Comment by heyitsbench** [comment]
If I remember correctly the seating positions on Classic were the same as AC, so I'd say it's a blizzlike bug.

**Comment by Maelthyrr** [comment]
The values are the same, but as you can see below the coordinate system got few issues. So I prefer that we check on classic if it's the same case before closing the issue.  (https://github.com/azerothcore/azerothcore-wotlk/pull/13083)

**Pull request closed without merging**
