### PR TITLE
fix(DB/Creatures): Snow Mound stalker should be invisible.

### LINKED ISSUE #11021: [ulduar] can see the invisible hellfire
### Current Behaviour

`the halls of winter`  can see the invisible hellfire,no gm on
`.go gameobject 35529`
`.go gameobject 41918`
`.go gameobject 40659`
`.go gameobject 40655`
`.go gameobject 40657`
`.go gameobject 35548`
image

Then there are some snowdrifts that have no invisible hellfire and need to be increased
image
`.go gameobject 35533`
`.go gameobject 35543`
`.go gameobject 35555`
image

### Expected Blizzlike Behaviour

Each snowbank will refresh some monsters if it steps on it,players can't see the invisible Hellfire (trigger)

### Source

_No response_

### Steps to reproduce the problem

1.   `.gm on`
2. `.go gameobject 35529`
3. Stay away from the snowdrift and enter `.gm off`
4. You'll see invisible hellfire

### Extra Notes

_No response_

### AC rev. hash/commit

1f90a18a5888a12a9b3bc32a0d4804baf81d51fe

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/106210512-ulduar-can-see-the-invisible-hellfire?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11021

## Issues Addressed:

- Closes #11021

## Tests Performed:

- Not tested. 

## How to Test the Changes:

`.go gameobject 40659`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by pklloveyou** [comment]
Tested

**Comment by mpfans** [comment]
work now. but `.go gameobject 39951`  near to it can not trigger, there will be no monsters

image

**Comment by UltraNix** [comment]
@mpfans Try now.

**Comment by Lynethris** [comment]
> .go gameobject 40659

Tested and work.

**Comment by mpfans** [comment]
tested,work now.tyvm

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
