### PR TITLE
fix(Scripts/BlackwingLair): Fixed starting Razorgore the Untamed fight.

### LINKED ISSUE #7729: Dragon Orb (spellid 19869) Has no effect on Razorgore the Untamed
### Current Behaviour

Using the spell Dragon Orb/Clicking on the Orb of Domination in Blackwing Lair has no effect. Instance cannot be finished because of current behavior.

### Expected Blizzlike Behaviour

Using the spell Dragon Orb/Clicking on the Orb of Domination in Blackwing Lair should cast Mind Control on Razorgore the Untamed.

### Source

https://www.youtube.com/watch?v=Iir2J0YtYlY

### Steps to reproduce the problem

1.Enter Blackwing Lair
2.Right Click on Orb of Domination
3.???
4.Profit

### Extra Notes

There is a missing visual effect on the orb of domination but that should be of no consequence. Restoration of basic functionality is more essential.

### AC rev. hash/commit

AzerothCore rev. 728839b84952+ 2021-09-05 10:02:31 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 1. Characters in world: 1.
Connection peak: 2.
Server uptime: 1 day(s) 9 hour(s) 37 minute(s) 45 second(s).
Update time diff: 10ms, average: 10ms.
ACDB 335.4-dev
World DB Revision: 2021_09_04_02
Character DB Revision: 2021_07_21_00
Auth DB Revision: 2021_06_17_00

### Operating system

Debian 10.10

### Custom changes or Modules

Initial modules enabled were:
mod-ah-bot
mod-autobalance
mod-solo-lfg
mod-transmog
mod-weapon-visual-master
mod-ARAC

However, I removed all the modules and patches, emptied the world database, and rebuild server. Issue persisted.

EDIT: While looking at how this is done on trinitycore, I noticed that instead of spellid 19869, they use spellid 42013 (QAE Charm) which when used with .cast does indeed lead to the correct behavior of possessing Razorgore.

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #7729

## Issues Addressed:

- Closes #7729

## Tests Performed:

- Not tested

## How to Test the Changes:

1.Enter Blackwing Lair
2.Right Click on Orb of Domination
3.Encounter should start

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers

**Comment by stoudtlr** [comment]
clicking on the orb gives a "target not in line of sight" error.
image

**Comment by mpfans** [comment]
@Barborica-Alexandru

**Comment by stoudtlr** [comment]
just finished retesting it.  multiboxed a raid group to get here legit instead of gm commands to tp in and everything worked as intended.  Razorgore now moved around as he's supposed to and i was able to click on the orb to control him.
control

Was able to destroy the eggs and then fight him.
image

Gate to next area opened on his death.

**Pull request merged**
