### PR TITLE
fix(DB/Smart Scripts) - Door Lever - On Game Object State Changed.

### PR DESCRIPTION
**Pull request by devovh**
**Changes Proposed:**

-  Fix all door's lever, Now Opening and Close all Door's - working.

**Issues Addressed:**

- Closes : Solving the problem with all doors regarding opening and closing.

**Tests Performed:**

- Inside the game
- Windows Server 2022 Datacenter

**How to Test the Changes:**
- .tele deadmines, kill first boss and test lever (door open and close)

**How to Test AzerothCore PRs:**

When a PR is ready to be tested, it will be marked as [WAITING TO BE TESTED].

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

REMEMBER: when testing a PR that changes something generic (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but especially check that the PR does not cause any regression (i.e. introducing new bugs).

For example: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but we should test Y and Z as well.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Please don't delete the PR template and include the necessary information.

**Comment by devovh** [comment]
I understand, I quickly added this amendment that it is a serious bug related to opening and closing doors, for example through levers. At the beginning, in the old azerothcore revie based on sunwell core there was a similar problem, then there was a different solution to this problem, because it was enough to uncomment a certain entry in the source code regarding the ready object. Later, after updating this solution in the source code based on trinitycore, someone probably missed adding a smart script to the database, and therefore this problem still remained like it used to be with this uncommenting.

**Comment by Maelthyrr** [comment]
Closes:
- https://github.com/azerothcore/azerothcore-wotlk/issues/10340
- https://github.com/azerothcore/azerothcore-wotlk/issues/11485

**Comment by acidmanifesto** [comment]
Can you do a fetch upstream so we can see if that failure is already taken care of?

**Pull request closed without merging**
