### PR TITLE
fix(DB/creature_template): Adjust speed movement for creatures [PART 1]

### PR DESCRIPTION
**Pull request by Efymer**
## Changes Proposed:
Thanks to the vMaNGOS sniffs, I made a small app to compare our speed movement values to the values from the sniffs and that's the output of it. 
If some creature had different values, an UPDATE query is generated for it.
**This first batch, only includes creatures from ID 0 to 3000.**

## Issues Addressed:

Closes https://github.com/chromiecraft/chromiecraft/issues/960

## SOURCE:

- vMaNGOS sniffs.

## Tests Performed:

-  Checked some of the values ingame to see if they made sense.

## How to Test the Changes:

1. Test as many creatures as you can.
2. Check that the values make sense.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Efymer** [comment]
Also worth to keep in mind that not all the creatures are included on the sniffs, so some creatures could still have wrong values out there, but that's an improvement already!

**Comment by T1ti** [comment]
Didn't we already do that a few months ago??

**Comment by claudiodfc** [comment]
We're the few months ago sniffs the same as these?

**Comment by T1ti** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/4644

What we did was add only their commits

**Comment by T1ti** [comment]
Where did you get some of those values from ?

Like I compared a few, and for me entry = 1754 has speed_run 1.14286 in the sniffs, your new value is 0.571429

**Comment by Efymer** [comment]
@T1ti I just checked and this specific case is weird, in the sniffs database there are multiple rows for the entry 1754, while the first one has the value 0.571429, the rest they have the value you mention.

**Comment by T1ti** [comment]
fyi sometimes creatures have auras that modify their speed, you can check that in the "auras" column

I only have 1 entry for 1754 though, are you using the mass release?

**Comment by Efymer** [comment]
I imported a SQL file named `classic_combined_sniff_db_31727_to_36935_kittnz_mantislord_brotalnia`, which I believe is the one you provided through mediafire 🤔

**Comment by T1ti** [comment]
I use this one but I only have 1 entry

creature_template are unique primary keys, how can you have multiple ?

**Comment by T1ti** [comment]
oh you did it with the "creature" table I see

**Comment by T1ti** [comment]
image
As you can see this entry has 3 auras
2974 is wing clip
https://classic.wowhead.com/spell=2974/wing-clip

**Comment by T1ti** [comment]
somethnig that you can do is check for entries that have a different value than the "common" ones

i compiled a list of common values : 

**### speed_run:**
**1.14286**	= 8.0/7.0, most common value

**1.48571** = 10.4/7

**1.19048** = 8.3333/7

**1.28571** = 9/7

**0.857143**  = 6/7

**1.42857** = 10/7

**0.992063** 

ps : I found another worng one : 
UPDATE `creature_template` SET `speed_run` = 0.685714 WHERE (`entry` = 1225); -- It was 1.14286

**Comment by Efymer** [comment]
@T1ti I updated the PR following this steps:
1) A clean run comparing only with fields that didn't have any aura to be 100% sure that the speed was the correct
2) I checked the diff: https://www.diffchecker.com/llrLX2jr and I went back to adding creatures that had auras that didn't affect movement.

**Comment by Efymer** [comment]
Closing PR since seems that it will be better to check creatures individually.

**Comment by T1ti** [comment]
Disagree, I think it's better to mass update it and then fix the few possible leftovers, so we don't get swarmed with thousands of issues

**Comment by Efymer** [comment]
@T1ti 
> Closing PR since seems that it will be better to check creatures individually.

Well, the PR was opened for a bit more than a month with no activity, I understand that nobody wants to go and validate all the edited creatures and check them one by one, that's why I'm closing it.

If anybody wants to continue with this task, it can easily be continued with the app I did to compare the values:
https://azerothcore-speedchecker.web.app/

**Comment by T1ti** [comment]
can someone else reopen this then ?

**Comment by Kitzunu** [comment]
Nope, branch has been deleted.

Need to cherry-pick

**Comment by T1ti** [comment]
it's just an SQL file

**Pull request closed without merging**
