### PR TITLE
fix(Core): solve issue with MariaDB

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3083
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3080

## TESTS PERFORMED:

- Not tested

## HOW TO TEST THE CHANGES:

Install AC using MariaDB

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by CosmeF** [comment]
It works. I've tested this changes on Debian 10, and the error is gone.

**Comment by Winfidonarleyan** [comment]
Tested with `MariaDB 10.4` in Win at compile `VS 16.6.0 Preview 4.0`
Successful build

**Comment by hlainin** [comment]
With this fix, the bug is gone. Thanks!

**Comment by Kitzunu** [comment]
Works with MySQL 8 ;)

```
========== Build: 7 succeeded, 0 failed, 9 up-to-date, 0 skipped ==========

AzerothCore rev. 850c25b5d820+ 2020-05-21 00:25:07 +0200 (Kitzunu-own branch) (Win64, RelWithDebInfo) (worldserver-daemon) ready...
```

**Comment by FrancescoBorzi** [comment]
thanks all for the test feedback! really appreciated.

let's merge this next please

**Comment by Kitzunu** [comment]
Ty for the PR!

**Pull request merged**
