### PR TITLE
Core/Fixes: Added Command cs_deserter

### PR DESCRIPTION
**Pull request by Bodeguero**
**Changes proposed:**
-  Added Command .desert
-   "deserter  instance add"
-   "deserter instance remove"
-   "deserter bg add"
-   "deserter bg remove"

**Target branch(es):** Master

**Tests performed:** (Does it build, tested in-game, etc)
Tested in game and working.
**Known issues and TODO list:**
Nothing

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by ShinDarth** [comment]
@Bodeguero  thanks, I've left some comments to improve it.

It would be appreciated if someone can also test this and leave a feedback comment.

**Comment by ShinDarth** [comment]
@Bodeguero  can you complete this one?

**Comment by Bodeguero** [comment]
@ShinDarth yes tested in game and working.

**Comment by ShinDarth** [comment]
@Bodeguero yes but can you please check my review comments?

**Comment by Bodeguero** [comment]
@ShinDarth I've tested it in game and is working perfectly a shame I have already deleted the repack that compiled - my internet is bad to download it again and test it take a 03 days! Anything you can not test? I guarantee it's working perfectly and worked!

**Comment by ShinDarth** [comment]
@Bodeguero yes I understand, but my review was about the codestyle. Can you please check it and edit the code accordingly?

**Comment by Bodeguero** [comment]
@ShinDarth I do not understand what you mean if the code is wrong can close this PR! One thing I know is working perfectly!

**Comment by Blumfield** [comment]
He is not saying your code is wrong, he is saying the codestyle is not good, for example this https://github.com/azerothcore/azerothcore-wotlk/pull/175/commits/9870fc79251c4ebdcc74db4ce28960e693da6f78#diff-b3fece75f30e5164d64e025a8e2a973eR604 you see there's too much space compared to others

**Comment by Bodeguero** [comment]
@Blumfield  and @ShinDarth They are talking and complaining about a single space? What is the difference of having a small space and not have? The code will be better - the function will be different? Could you answer me? I am newbie in this area of programming for World Of Warcraft!

**Comment by ShinDarth** [comment]
@Bodeguero  sure:  the code-style does not impact the performance or the functionality of the functions, but keeping a good code-style is important to have a clean, easy to understand code:

https://en.wikipedia.org/wiki/Coding_conventions

**Comment by Bodeguero** [comment]
@ShinDarth The space remaining in the code is making it difficult to understand? I am newbie in that I'm still not understanding forgive me for this - more for me this perfect! **If you can close this PR**! I will continue working on my corrections with code **dirty and no one understands**!

Grateful!

**Comment by ShinDarth** [comment]
@Bodeguero you don't need to close it! Feel free to work on it while it is still a work in progress. Having an open PR is useful for you to receive feedback while you work on it.

We usually just add a tag [WIP] on PRs that are not ready to be merged yet.

**Pull request closed without merging**
