### PR TITLE
fix(Core/Spells): Beacon of Light should not cause combat.

### LINKED ISSUE #7276: Beacon of Light weird PvP combat behavior
### Current Behaviour

Players with Beacon of Light buff are getting in PvP combat when the Paladin that casted Beacon gets in combat with another player (maybe creatures too)

i recorded a video:
https://www.youtube.com/watch?v=3DWPFsQ0iAo 
Here we can see that i get in combat when i have the Beacon of Light buff and the paladin cast Judgement of Wisdom on a enemy player.

### Expected Blizzlike Behaviour

Players shouldn't get in combat because they have a Beacon of Light buff of a paladin that is combat. 
Should only get in combat if they attack/get attacked by another player/creature.

### Source

_No response_

### Steps to reproduce the problem

1. Log on a paladin and 2 more classes (doesnt matter which) and go to a PvP zone (.tele arena)
2. Set the paladin in a party with another char/class
3. Cast Beacon of Light on your friend in party
4. On the paladin, use any spell on enemy player that puts you in combat. 
Now the friend with Beacon of Light got combat aswell

### Extra Notes

If, while in combat, you(as a Paladin) keep healing yourself and having a friend with Beacon of Light buff, you and your friend wont leave combat till you stop healing. 
This bug can be abused to not get sapped against rogues in PvP, or accidentaly keeping your friend in combat, making him to not be able to go stealth, drink or use mount.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3067662b70bf

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #7276

## Changes Proposed:
-  Added `SPELL_ATTR1_NO_THREAT` att to Beacon of Light triggered spell.

## Issues Addressed:

- Closes #7276

## Tests Performed:

- Tested ingame

## How to Test the Changes:

1. Log on a paladin and 2 more classes (doesnt matter which) and go to a PvP zone (.tele arena)
2. Set the paladin in a party with another char/class
3. Cast Beacon of Light on your friend in party
4. On the paladin, use any spell on enemy player that puts you in combat.
5. Now the friend with Beacon of Light got no combat anymore.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by laasker** [comment]
Sadly it didnt work for me, not sure if my local server is missing a commit/PR, but players with the buff still get combat

**Comment by UltraNix** [comment]
I tested that. Put a beacon on my party mate, then attacked the mob. The party member did not get combat.

**Comment by laasker** [comment]
I tested against a mob and indeed it doesnt give combat to party member, but against players it did give combat

**Comment by UltraNix** [comment]
@laasker Test it now

**Comment by laasker** [comment]
Tested again, now it doesn't give combat to party players anymore, : DD

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
