### PR TITLE
fix (DB/Item) Import stats of S1 and S2 Waist/Wrist/Feet from wowhead/wotlk

### PR DESCRIPTION
**Pull request by Tereneckla**
## Changes Proposed:
-  Set Stats, Armor, Class Restriction of season 1 and 2 wrist, waist, feet to wowhead.com/wotlk values
(I filtered by epics between iLvL 113 and 136 with resilience on them)
- 

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5710

## SOURCE:

Values are from the wowhead API

## Tests Performed:

- Ran SQL
- added items specifically mentioned by reporter 32982 and 32976

## How to Test the Changes:

add any of these items
28644,28383,32791,32794,28991,28987,28986,32795,32998,28404,28410,28993,32789,32806,28446,32786,28643,28445,32997,28978,32982,28984,31596,32792,28444,28385,28994,32819,32994,29002,32813,29005,32801,28998,32974,32793,28424,28988,28447,28974,28641,32978,28645,28981,28443,32975,28448,32788,32986,28983,32983,28402,32985,32811,32990,29004,32812,32808,28975,28646,28605,32992,28995,32979,32977,28985,32817,28640,32799,29003,28982,28422,32980,28638,32973,32800,28989,29000,28976,32807,28992,32803,32984,32988,32814,32787,32804,28999,32797,32816,32790,28411,31597,32818,28642,32987,32805,32981,28381,32798,28423,30491,32809,32989,29006,28973,31598,32810,32999,28977,28629,28997,28449,32785,28996,28630,32821,31599,32991,28409,32802,28990,29001,32796,32976,28451,31595,32993,31594,28980,32995,32820,28405,28639,32996,28450

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Would it be possible to find a source for these stats other than current Classic Wowhead?

**Comment by Tereneckla** [comment]
One could query classic wotlk directly, but this is the best I can do

**Comment by heyitsbench** [comment]
> One could query classic wotlk directly, but this is the best I can do

Well my point is moreso asking is this possibly a Classic change?

**Comment by Tereneckla** [comment]
The S2 items have the same stats as listed on the 2009 version of wowwiki https://wowwiki-archive.fandom.com/wiki/Veteran%27s_PvP_rewards

I also think it's extremely unlikely that they changed those items for classic

**Comment by FrancescoBorzi** [comment]
has this PR been forgotten?

**Comment by Nyeriah** [comment]
Looks like we’re lacking information to wrap this one up.

**Comment by Tereneckla** [comment]
Don't know why this needs more information

The chances of it being an undocumented wotlk classic change that also has the same values as some guys wrote into wowwiki in 2009 are null

**Comment by Gultask** [comment]
Ok, so I'm pretty sure stats in particular aren't dbc data. I still wonder why they were wrong in the first place, though.

**Comment by Kitzunu** [comment]
Status?

**Comment by Tereneckla** [comment]
Still done from my side. Just needs a stamp of approval

**Comment by heyitsbench** [comment]
Matches Classic and WowWiki of the era, but not TC.

**Comment by Gultask** [comment]
I took a further look. The items that were severely mismatched were from a later parse and had anomalous fields, such as BuyPrice and SellPrice different from 0, and missing flags.

I modified your PR to only contain the mismatched items, and also remove VerifiedBuild, the Flag, etc

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
