### PR TITLE
fix(DB/Creatures): Living & Mature lasher

### PR DESCRIPTION
**Pull request by poszer**
Living lasher, Mature lasher movement

##### CHANGES PROPOSED:

- New SAI script
- Fixed issue with movements for these creatures (Living lasher, Mature lasher).

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2005

##### TESTS PERFORMED:

Yes. Query imported without errors. Tested in game, the creatures are standing now, and correctly move to the player in combat.

##### HOW TO TEST THE CHANGES:

1. .go c 88233, .go c 131438
2. Enter in combat with them (Check without this commit first)

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Knindzagxg** [comment]
All good mate.

Tested in-game.

**Comment by poszer** [comment]
> All good mate.
> 
> Tested in-game.

Thanks @Knindzagxg

**Comment by FrancescoBorzi** [comment]
@Stoabrogga don't forget to remove the `To be merged` to avoid the risk that someone accidentally merges something after such a comment

**Comment by poszer** [comment]
> Sorry, but this is wrong. I remember this area well from retail, the lashers should always be submerged and come out of the ground on aggro. See also this screenshot from 2009, where all lashers are submerged:
> https://wowwiki.fandom.com/wiki/Steppe_of_Life
> 
> Please use this script instead, it just fixes casting the "Stand" spell (which doesn't work) and replaces it with the removal of the submerged flag. Tested it successfully already:
> 
> ```sql
> DELETE FROM `smart_scripts` WHERE `entryorguid` IN (30845,34300) AND `source_type` = 0 AND `id` = 3;
> INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`)
> VALUES
> (30845,0,3,0,4,0,100,0,0,0,0,0,0,91,9,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'Living Lasher - On Aggro - Remove Flag Standstate Submerged'),
> (34300,0,3,0,4,0,100,0,0,0,0,0,0,91,9,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'Mature Lasher - On Aggro - Remove Flag Standstate Submerged');
> ```

I saw that screen, but also i saw others where they stand. Let's wait for knindza to test on Blizz. After he's confirmation, if needed i'll change

**Comment by Stoabrogga** [comment]
@poszer 
If you mean the video you posted on the issue #2005, it's from Warmane, not from retail, so has no credibility.

**Comment by poszer** [comment]
> @poszer
> If you mean the video you posted on the issue #2005, it's from Warmane, not from retail, so has no credibility.

Nope, the video is from Wmane i know. It was only video where clearly can see these mobs (Just in case added to show how it looks)

**Comment by Stoabrogga** [comment]
There's also a comment on wowhead (patch 3.0.9) mentioning that they are buried in the ground:
https://www.wowhead.com/npc=30845/living-lasher#comments:id=610619

**Comment by Knindzagxg** [comment]
Just saw, ill check on Blizz in next few minutes.

**Comment by Knindzagxg** [comment]
Yeah, they are buried underground always.
Checked whole zone just be sure.

https://i.imgur.com/pG80o2q.jpg

**Comment by poszer** [comment]
> Yeah, they are buried underground always.
> Checked whole zone just be sure.
> 
> https://i.imgur.com/pG80o2q.jpg

Ok good. Will update soon

**Comment by poszer** [comment]
Thanks @Stoabrogga & @Knindzagxg for infos

**Pull request merged**
