### PR TITLE
Add Black Bear Pack northwest of the Ironforge Airfield.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:
-  Adds Black Bear and two Young Black Bears in a small area northwest of the Ironforge airfield.

## Issues Addressed:

- Makes progress towards #6994 

## SOURCE:

TBCC Sniffs (Partially)

## Tests Performed:

- Observed that the creatures correctly spawned in the area.

## How to Test the Changes:

1. Run the query
2. Use the in-game command .go xyz -4322 -1464 415
3. Observe the three bears spawned

## Known Issues and TODO List:

- [x] Still have to find the wander_distance of the two young black bears and their actual spawn position

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Got a more comprehensive sniff, waiting on WPP.

**Comment by heyitsbench** [comment]
Ready for review.

**Comment by SoglaHash** [comment]
tested this PR
## Before patch
No bears
No bears
## After patch
3 Bears spawned
Bears

**Comment by heyitsbench** [comment]
So the two Young Black Bears are supposed to be wandering, which it looks like they're doing correctly in your screenshot, but the adult Black Bear is supposed to be emote sitting, which they're not doing in your screenshot but they did when I tested.

**Comment by SoglaHash** [comment]
I've uploaded the screenshot to confirm they spawned. I do also have a recording where you can see the 2 cubs patrolling but the big bear does not sit down

https://user-images.githubusercontent.com/74299960/181815176-998217e4-5e3c-458e-a150-0beb8346d147.mp4

I can try again later and if I see a difference I'll update this.

**Comment by heyitsbench** [comment]
I looked at how some other creatures were set up to sit in the DB and found that they used the `bytes1` column to achieve the same thing, so that's what I used. Upon running the query on my own clean world DB, the bear does sit, so I'm not sure what's going on.
image

**Comment by SoglaHash** [comment]
Apologies, I must've did something wrong earlier today. The cubs are wandering and the adult bear is sitting down! 

12544_after_patch2

**Comment by heyitsbench** [comment]
Thank you for testing! <3

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Thank you for your pr!

**Pull request merged**
