### PR TITLE
fix(Core/Spell): Impelement SPELL_ATTR7_NO_ATTACK_DODGE & SPELL_ATTR7…

### PR DESCRIPTION
**Pull request by Kitzunu**
…_NO_ATTACK_PARRY & SPELL_ATTR7_NO_ATTACK_MISS

cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/bd6de8eb6104e5e3e08149dfd44008ef0fb4c74a)

Co-Authored-By: Ovah <18347559+Ovahlord@users.noreply.github.com>
Co-Authored-By: Gildor <521036+Jildor@users.noreply.github.com>

## Changes Proposed:
-  implement SPELL_ATTR7_NO_ATTACK_DODGE & SPELL_ATTR7_NO_ATTACK_PARRY & SPELL_ATTR7_NO_ATTACK_MISS
-  change some "spell" to "spellInfo"
- Spells with SPELL_ATTR7_NO_ATTACK_DODGE cannot be dodged
- Spells with SPELL_ATTR7_NO_ATTACK_PARRY cannot be parried
- Spells with SPELL_ATTR7_NO_ATTACK_MISS cannot miss

## Tests Performed:

- Builds 

## How to Test the Changes:

1. Test a spell with one of the attributes

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
I put this PR on the server

**Review by Helias — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> I put this PR on the server

thanks @pklloveyou , let us know

**Comment by pklloveyou** [comment]
So far, there are no player feedback errors

**Comment by pklloveyou** [comment]
So far, there are no player feedback errors

**Comment by Kitzunu** [comment]
Maybe this is Good to go. You can also read code, the logic adds up

**Comment by pklloveyou** [comment]
So far, there are no player feedback errors.

**Pull request merged**
