### PR TITLE
feat. Add script to update modules from console

### PR DESCRIPTION
**Pull request by pangolp**
Co-authored-by: Revision <tkn963@gmail.com>
Co-authored-by: michaeldelago <michaeldelago98@gmail.com>
Co-authored-by: Kitzunu <24550914+Kitzunu@users.noreply.github.com>

## Changes Proposed:
This PR proposes changes to:
-  [x] General scripts

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes 

## SOURCE:

- [x] Other

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue

1. You access the modules folder.
2. You run the script
3. You will see that all modules are updated
4. I clarify, that you must have git. Many download the .zip, and that will not work for them.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by noisiver** [comment]
Why do you need to specify the branch to pull? What if a module doesn't use master or the user needs to use a branch other than master?

**Comment by pangolp** [comment]
> Why do you need to specify the branch to pull? What if a module doesn't use master or the user needs to use a branch other than master?

Good question. Maybe that can be changed. But at one point, he asked me, and he leaves it that way, but it's likely that you're right and you need to remove that part or modify it.

**Comment by pangolp** [comment]
> use main for exampe

I'll check, thanks.

**Comment by pangolp** [comment]
@noisiver The branch thing, I think it was because of this.

```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>
```

**Comment by noisiver** [comment]
> 

My bash scripts only use `git pull` and it works as intended.

**Comment by pangolp** [comment]
> My bash scripts only use `git pull` and it works as intended.

But surely, in the git config --global or somewhere, you will have specified so that it can be that way. Here remember, that it will be finished by a person who perhaps does not have those configurations. Anyway, I'll check.

**Comment by noisiver** [comment]
I never have to add any variables to git. A clean installation of Linux with a fresh installation of git and that command works fine. There may be reasons as to why it would fail but the same could be said by specifying the branch and it being wrong. One alternative would be this: `git pull origin $(git rev-parse --abbrev-ref HEAD)`. It gets the currently checked out branch and supplies it to the pull.

**Comment by pangolp** [comment]
> I never have to add any variables to git. A clean installation of Linux with a fresh installation of git and that command works fine. There may be reasons as to why it would fail but the same could be said by specifying the branch and it being wrong. One alternative would be this: `git pull origin $(git rev-parse --abbrev-ref HEAD)`. It gets the currently checked out branch and uses it to when pulling any changes.

I'll try it, thanks.

**Comment by pangolp** [comment]
I just need to solve this issue. Now I will see what I can investigate, the truth is that the example that CodeFactor gives me does not work for me.

image

**Comment by pangolp** [comment]
> https://github.com/azerothcore/mod-progression-system use main for exampe

I can't find any shell files in that directory, which iterates through a list, steps in, and executes a command. Either I don't see it, or I don't understand what he wants to tell me with the message he sent me.

**Comment by pangolp** [comment]
It seems that now if he likes how I look.

**Comment by pangolp** [comment]
Now that I realize it, you're right @noisiver.
I forgot that many times people don't use `master`, they use main, for example, as the `main` branch.

**Comment by noisiver** [comment]
That's exactly what Kitzunu meant. Also, sometimes the user might want to use a branch other than master and don't want it to forcibly reset to master when they update using this script.

**Comment by pangolp** [comment]
> That's exactly what Kitzunu meant. Also, sometimes the user might want to use a branch other than master and don't want it to forcibly reset to master when they update using this script.

Yes, I understand. The logic is fine.

**Comment by pangolp** [comment]
> https://github.com/azerothcore/mod-progression-system use main for exampe

I read very quickly, I did not see the word `main`

**Comment by noisiver** [comment]
image

**Comment by pangolp** [comment]
> image

Now that you mentioned it, I went to the repository and reread the message I left and found the word.
But I read in a hurry, and I didn't see it.

**Comment by pangolp** [comment]
Does anyone need me to make changes or can it be merged? If they have any recommendations, we change it. Although it can also be done in the future.

**Review by michaeldelago — COMMENTED** [review]
A few change suggestions to help ensure the script is safer. Bash has a lot of footguns. 

Not that this contribution is bad or anything, but I'm trying to think of things that could go wrong with this

- What happens if the user doesn't have their modules pulled through git?

- What happens if the git remotes for the modules isn't called `origin`?

- Does this work on Windows? 

- Would minor documentation on using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and the command to update those (`git pull --recurse-submodules`) be a suitable replacement to this?

**Comment by pangolp** [comment]
@michaeldelago Incredible report, I will review it in detail, and I will make the proposed changes. As to whether the script works on windows, it should, in case git bash is installed. In fact, I work on Windows 10 and on Debian 11 / 12 and Ubuntu. Anyway, I make the changes, and test it. Thank you.

**Comment by pangolp** [comment]
This doesn't work, with the last changes we made to it.

https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/9b89c7f3-dcf3-4230-8a02-bc3e3680505b

**Comment by pangolp** [comment]
This way it works for me.

https://github.com/azerothcore/azerothcore-wotlk/assets/2810187/15a01d03-7721-4d42-8250-ddf8b7642eba

**Review by michaeldelago — COMMENTED** [review]
Having the `set -euo pipefail` is good enough for most issues, works for me. 

I defer to other reviewers, however.

**Comment by pangolp** [comment]
@Nyeriah Can we merge it?

**Comment by Nyeriah** [comment]
I didn’t participate in this discussion so will leave it to one of the other developers who have.

**Comment by pangolp** [comment]
2 weeks, to add a script, which basically updates the modules. It doesn't even modify anything in the emulator. I made all the changes and tests that they asked me to do. Really, I don't know what else they want me to do.

**Comment by michaeldelago** [comment]
@pangolp I'm sorry to say but I don't think this should be merged. I'd recommended someone either use [git submodules](https://github.blog/2016-02-01-working-with-submodules/) or the `./acore.sh` dashboard, which includes a [subcommand to update modules](https://github.com/azerothcore/azerothcore-wotlk/blob/master/apps/installer/main.sh#L16). 

The code in the script might be simple to port to the dashboard if there's slight differences in functionality.

I do appreciate the functionality of the script and I think it may be useful to add into documentation, but I don't think it needs to be included in the repo.

**Comment by pangolp** [comment]
Then what do we do? Shall we close the pull request?

**Pull request closed without merging**
