### PR TITLE
refactor(Naxxramas): code cleaning

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- [x] **DEPENDS ON https://github.com/azerothcore/azerothcore-wotlk/pull/1657 AND CANNOT BE REVIEWED UNTIL THAT ONE IS MERGED**

---------------------------

##### CHANGES PROPOSED:

- Minor code refactoring
- Fix clang-tidy & coverity issues

image

##### HOW TO TEST THE CHANGES:

- Test Naxxramas

##### KNOWN ISSUES AND TODO LIST:

It's just a bunch of minor code refactoring, nothing should change.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
Ready for review

**Comment by Knindzagxg** [comment]
Looks good, haven't found any issues except i mentioned in my previous post (Other PR about NPC and gobject).

Tho, while testing last time i saw something weird and i can confirm it now:

Trash before Patchwerk reset after 1 hour, which should be changed as well.
Should be easy fix trough DB.

**Comment by FrancescoBorzi** [comment]
@Knindzagxg thanks a lot for testing. All bugs that are not introduced by this PR should be reported separately, otherwise it becomes confusing. In the PR discussions let's focus on spot bugs introduced by the PR.

**Comment by Stoabrogga** [comment]
@Knindzagxg 
Thanks for testing this. Could you please open an issue concerning the bugs you found? It has to be addressed in a new PR and I think this information gets lost if it is only mentioned in a comment for a PR.

**Pull request merged**
