### PR TITLE
fix(DB/Creature): Fixing reports related to DB, SAI, Text

### PR DESCRIPTION
**Pull request by poszer**
- Fixing several issues

Co-Authored-By: Stoabrogga <stoabrogga@users.noreply.github.com>

Fixing reports related to DB, SAI, Text

##### CHANGES PROPOSED:

-  Update, Added SAI
-  

###### ISSUES ADDRESSED:

Closes Part of this https://github.com/azerothcore/azerothcore-wotlk/issues/1015 And this https://github.com/azerothcore/azerothcore-wotlk/issues/1062

Some of reported issues are already fixed in previous PR, Example: 

- [x]  Reprogrammed Defendo-tank 66D fixed in

https://github.com/azerothcore/azerothcore-wotlk/commit/55ef766b19f1d65f1073615b8da390605989ff83

- [x]  Bone Warrior fixed in 

https://github.com/azerothcore/azerothcore-wotlk/commit/31ee4b14f2a5ba8e18d11b28c55c2b127bfafe7b

##### TESTS PERFORMED:

Yeah, everything fine

##### KNOWN ISSUES AND TODO LIST:

- [x] Could not find TextGroup 1 for Creature(Havenshire Colt)
- [x] Caverndeep Burrower SAI
- [x] Caverndeep Reaver SAI
- [x] Scarlet Abbot creature text
- [x] Blackwood Ursa SAI

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Sadly it is not possible to fix errors like
```
Could not find Text for Creature(Spirit Wolf) Entry 29264
```
because there's not enough information available. The Spirit Wolf is summoned by a player and the error is caused by a SAI script with wrong target type for the talk action, but you have no chance identifying the correct SAI script causing this. I created PR #2023 in order to improve logging for these cases and propose merging it before continuing with fixing the creature text issues.

**Comment by poszer** [comment]
> Sadly it is not possible to fix errors like
> 
> ```
> Could not find Text for Creature(Spirit Wolf) Entry 29264
> ```
> 
> because there's not enough information available. The Spirit Wolf is summoned by a player and the error is caused by a SAI script with wrong target type for the talk action, but you have no chance identifying the correct SAI script causing this. I created PR #2023 in order to improve logging for these cases and propose merging it before continuing with fixing the creature text issues.

Interesting, there must be way for this. For example this one : 
Could not find Text for Creature(Ebon Blade Prisoner) Entry 30194
When the player opens the cage, the prisoner despawns and the spell http://wotlk.openwow.com/spell=38078 is cast by the gob and trigger one of this 4 spells (force cast by the player) : 56214, 56212, 56209, 56207.

**Comment by Knindzagxg** [comment]
@Stoabrogga 

I used some easy fixes for wolfs or etc, just to avoid DB errors.
Like adding ... in text and 0 in chance.

I know it's not real fix, just towards error until i check them somewhere if there is info.

Most of them have emotes, like enaged in combat or things like.

**Comment by Stoabrogga** [comment]
@poszer 
As discussed on discord I think it would be better to split this PR into multiple PRs which are isolated from each other. It would be easier to test and merge them step by step.

**Comment by Stoabrogga** [comment]
I added the "Scarlet Medic" (28608), concerns this error message:
```Could not find TextGroup 1 for Creature(Havenshire Colt)```

**Comment by poszer** [comment]
> I added an update for the "Scarlet Medic" (28608), concerns this error message:
> `Could not find TextGroup 1 for Creature(Havenshire Colt)`

Ok, good. It's ready now

**Comment by Stoabrogga** [comment]
The changes for "Caverndeep Burrower" and "Caverndeep Reaver" were wrong, I corrected them. The talk action has to stay in there because it points out that they got irradiated. It just used the wrong text group id.

**Comment by Stoabrogga** [comment]
Ok, now everything works well:
- "Caverndeep Burrower" and "Caverndeep Reaver"
 Fought against "Irradiated Pillager" and killed it near a "Caverndeep Burrower" and a "Caverndeep Reaver": No more errors in the log and the creatures now correctly use the emote "is splashed by the blood and becomes irradiated!"
- "Scarlet Abbot"
 Fought until enraged; no errors in the log anymore and the creature correctly uses the emote "becomes enraged!"
- "Blackwood Ursa"
 Now casts "Rejuvenation" if an ally drops under 200 health
- Quest "Grand Theft Palomino": No more creature text errors in the log while escaping with the horse

**Comment by poszer** [comment]
> Ok, now everything works well:
> 
> * "Caverndeep Burrower" and "Caverndeep Reaver"
>   Fought against "Irradiated Pillager" and killed it near a "Caverndeep Burrower" and a "Caverndeep Reaver": No more errors in the log and the creatures now correctly use the emote "is splashed by the blood and becomes irradiated!"
> * "Scarlet Abbot"
>   Fought until enraged; no errors in the log anymore and the creature correctly uses the emote "becomes enraged!"
> * "Blackwood Ursa"
>   Now casts "Rejuvenation" if an ally drops under 200 health
> * Quest "Grand Theft Palomino": No more creature text errors in the log while escaping with the horse

Perfect, thank you

**Pull request merged**
