### PR TITLE
fix(Core/SpellAuras): prevent crash in Aura::GetType()

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/6892
- Prevent crash https://gist.github.com/mpfans/ff6eafa1fc655d1f1f88b92dee5bc4a2 reported by @mpfans

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
not sure if @UltraNix has a better idea to fix this crash

**Comment by UltraNix** [comment]
Seems valid.

**Comment by Viste** [comment]
if i remember right:
https://github.com/WarheadCore/WarheadCore_AC_Arhive/commit/d7f2af413f4fd9e0e708798eb29cb8146de0698e#diff-1921596918c2026118ef02eba3eb6fa8ab14a9a09b4370145facef1cc5c02ebdR31

**Comment by FrancescoBorzi** [comment]
sure @Viste , but also the null check doesn't hurt so we can merge both

**Pull request merged**
