### PR TITLE
fix(DB/Conditions): Sha'ni Proudtusk infinite spawning. 

### PR DESCRIPTION
**Pull request by avarishd**
## Changes Proposed:
- (AND) Add condition to not spawn NPC if there is already an NPC within 10 yards.
- (AND) Add QUEST_STATE (Rewarded and Complete) condition that allows to spawn NPC after completing 3821

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10827
- Closes https://github.com/chromiecraft/chromiecraft/issues/3106

## Tests Performed:

- tested

## How to Test the Changes:

.q a 3821
.go gameobject id 160445
Spam click it while having the quest in your log AND after turning it in.
Notice that there will always be 1 NPC, and no more.
## Known Issues and TODO List:

- [x] Unknown if you should be able to summon her AFTER you complete 3821. In case you don't accept the quest that she starts and she despawns, resulting in you having to wait for another person to summon her.
- [x] If you talk with the npc, someone can potentially spam click to summon/despawn to disrupt you.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Instead of despawning you can set up a condition to only summon Sha'ni if there isn't one already nearby since the gob uses SmartAI

Here's an example and where I learned that from: https://github.com/azerothcore/azerothcore-wotlk/pull/15074/files#diff-85c028f95a71a196147203afc49222f96e2f09a877d87707e4b80798428d111dR115

It'd solve your issue in the TODO

**Comment by Nyeriah** [comment]
Could also use this to make the condition simpler 
image

**Comment by avarishd** [comment]
This PR is actually "old" and in these couple of days I've learned quite a bunch about conditions.

**Comment by avarishd** [comment]
@Gultask

**Review by Gultask — APPROVED** [review]

**Comment by Maelthyrr** [comment]
Hi, thanks for the PR. Tested with two char:

- [X] Spam clic will spawn only one npc
- [X] If another player use the gob, it doesn't spawn a new npc
- [X] When the npc despawn, the player can respawn her by clicking again on the gob
- [X] If a player doesn't have the quest, he can't summon the npc

**Pull request merged**
