### PR TITLE
fix(DB/Creature Loot) - Update Bloodkelp (22094) drop tables

### PR DESCRIPTION
**Pull request by kjack9**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

Updates the drop rates for the various creatures that drop Bloodkelp (22094). This was discussed a while back in #9785, but it doesn't appear any changes were implemented before the issue was closed.

## Issues Addressed:

- Addresses #9785 (which is already closed, but this isn't fixed?)

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

[WoWHead Reference Link](https://www.wowhead.com/wotlk/item=22094/bloodkelp)

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. `.quest add 8970`
2. `.tel alcazisland`
3. Kill affected creatures and observe updated drop.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
Why are you deleting the whole creature loot and inserting it back again? Just delete or update the chance from the entries and the item

**Comment by kjack9** [comment]
> Why are you deleting the whole creature loot and inserting it back again? Just delete or update the chance from the entries and the item

I was under the impression that the standard is to DELETE and INSERT rather than update. It has at least been that way for SAI in the past.

https://www.azerothcore.org/wiki/sql-standards#insert-amp-delete

Do I misunderstand the project standards?

**Comment by Nefertumm** [comment]
Not at all, but you could just only delete that specific item. That's what I meant

**Comment by kjack9** [comment]
> Not at all, but you could just only delete that specific item. That's what I meant. Also, we are not against the UPDATE clausule if it's used correctly.
> 
> Edit: Sorry wrong button :p

Okay. I'll roll back and figure out what the specific updates are and then push a new commit. Standby.

**Comment by kjack9** [comment]
Okay, see if that works for ya.

**Review by Nefertumm — APPROVED** [review]

**Comment by elthehablo** [comment]
The reason it was originally scrapped from the Myrmidon was explained here: https://github.com/azerothcore/azerothcore-wotlk/pull/9873 . I am not trying to say this is wrong, but wowhead has been proven to not be an accurate source on loot in the past, as most of the time it is diluted. This can happen, for instance, when another mob drops something near the mob that was killed, then it might get registered on the other mob as well. So yeah I'll have to look into this. I will compare with VMangos tonight and come back to this

**Comment by kjack9** [comment]
> The reason it was originally scrapped from the Myrmidon was explained here: #9873 . I am not trying to say this is wrong, but wowhead has been proven to not be an accurate source on loot in the past, as most of the time it is diluted. This can happen, for instance, when another mob drops something near the mob that was killed, then it might get registered on the other mob as well. So yeah I'll have to look into this. I will compare with VMangos tonight and come back to this

Is this PR worth keeping open or has other testing shown that the current drop rates are correct?

**Comment by elthehablo** [comment]
> > The reason it was originally scrapped from the Myrmidon was explained here: #9873 . I am not trying to say this is wrong, but wowhead has been proven to not be an accurate source on loot in the past, as most of the time it is diluted. This can happen, for instance, when another mob drops something near the mob that was killed, then it might get registered on the other mob as well. So yeah I'll have to look into this. I will compare with VMangos tonight and come back to this
> 
> Is this PR worth keeping open or has other testing shown that the current drop rates are correct?

worth keeping open. I just need to restore access to my db lol

**Comment by elthehablo** [comment]
CManGOS has the following:
image

interestingly enough they think myrmidon should drop the kelp

**Comment by Kitzunu** [comment]
what's up with this one?

**Comment by elthehablo** [comment]
Debate on whether cmangos has this correct. M'dic claimed otherwise

**Comment by elthehablo** [comment]
> go classic and test it x)

I might do a bit of SoD actually

**Comment by Kitzunu** [comment]
@heyitsbench

**Comment by sudlud** [comment]
Closing this for now as it has been abandoned for quite some time.

Please feel free to re-open and update the PR again.

**Pull request closed without merging**
