### PR TITLE
fix(DB): positioning of the control console on the zeppelin "Cloudkisser"

### LINKED ISSUE #1394: Zeppelin "The Cloudkisser" losing control console
##### SMALL DESCRIPTION:
The zeppelin "The Cloudkisser", which moves between Tirisfal Glades and Vengeance Landing, loses it's control console.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The control console should stay on the zeppelin.

##### CURRENT BEHAVIOUR:
The control consol falls down and then floats through the air while the zeppelin moves.

##### STEPS TO REPRODUCE THE PROBLEM:
- ```.go 1988.7 -6086.86 13.3416 571```
- sometimes the console is visible in the grass while the zeppelin is docked:
 
- it is missing on the zeppelin:
  
- when the zeppelin is moving, it floats through the air:
 

##### EXTRA NOTES:
None

##### BRANCH(ES):
Master

##### AC HASH/COMMIT:
fc1fad4e32fedd486a8fe8ca30d2f8c3040b6d55

##### OPERATING SYSTEM:
Ubuntu 16.04

##### MODULES:
https://github.com/azerothcore/mod-vas-autobalance
https://github.com/azerothcore/mod-transmog
https://github.com/azerothcore/mod-npcbeastmaster

##### OTHER CUSTOMIZATIONS:
None

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Fix the positioning of the control console on the zeppelin "Cloudkisser". Otherwise it falls to the ground and floats through the air while the zeppelin is moving.

###### ISSUES ADDRESSED:
Closes #1394

##### TESTS PERFORMED:
tested in-game

##### HOW TO TEST THE CHANGES:
see #1394

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Tested by @pklloveyou too

**Comment by pklloveyou** [comment]
correct！~passed

**Comment by FrancescoBorzi** [comment]
@pklloveyou thanks a lot for testing this

**Comment by BarbzYHOOL** [comment]
@Stoabrogga thank you! @pklloveyou thank you!

**Pull request merged**
