### PR TITLE
Change encoding in banner

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
**Changes proposed:**
-  Correct encoding in banner (UTF-8 no BOM)
-  Correct line in banner

**Target branch(es):** master.

**Issues addressed:** Close (https://github.com/azerothcore/azerothcore-wotlk/issues/910)

**Tests performed:** Test build and test run.

**Tests platform:**  Windows 10. Visual Studio 2017 (15.7.3) x64

**How to test the changes:**
1. Apply my commit
2. Rebuild project
3. Run authserver and worldserver

**Known issues and TODO list:** No

### CODE REVIEW

**Comment by ShinDarth** [comment]
@Winfidonarleyan good job!

@Trystanosaurus can you please test this PR and check if it solves your issue?

**Comment by Trystanosaurus** [comment]
Yes, I've tested this PR just now and it looks to be working, no warnings when compiling and the logo's showing correctly.

**Comment by Winfidonarleyan** [comment]
Perfectly

**Comment by ShinDarth** [comment]
thanks @Winfidonarleyan  and @Trystanosaurus

**Pull request merged**
