### PR TITLE
fix(DB/SAI): Grimclaw

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
- Prevent the Grimclaw event for How Big a Threat (part 2) from taking several minutes longer than intended
-  Delete useless Grimclaw spawn
-  Rebuild Waypoints, use correct entry numbering (entry*100)
- Update SAI to conform to new waypoints and remove unused rows

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11374
- Closes https://github.com/chromiecraft/chromiecraft/issues/3188
- Closes https://github.com/chromiecraft/chromiecraft/issues/3313
- Closes https://github.com/chromiecraft/chromiecraft/issues/3216
- Closes https://github.com/chromiecraft/chromiecraft/issues/3296

## Tests Performed:

- Tested ingame
- 

## How to Test the Changes:

1. .quest add 985
2. .quest complete 985
3. .go quest ender 985

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
It was an annoying bug ok!? 😭

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Originally when he started he was seen going thru the air before the parse waypoints were added. How does it look now from start to finish?

**Comment by Gultask** [comment]
That was because the WPs were the other way around, so Grimclaw would spawn, fly to the other side of the map (to go to point 1) then path all the way back.
Looks fine now, imo. I didn't see any flying, at least.

**Comment by acidmanifesto** [comment]
> That was because the WPs were the other way around, so Grimclaw would spawn, fly to the other side of the map (to go to point 1) then path all the way back.
> Looks fine now, imo. I didn't see any flying, at least.

Noice. Ill take your word for it.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
