### PR TITLE
minor quest fixes 3

### PR DESCRIPTION
**Pull request by PolarCookie**
**Bael'Gar's Fiery Essence**: updated so that it now needs Bael'Gar's corpse to work.

**Crimson Crystal Shard**: Should be guaranteed over 5 kills, setting it to 100%

**Kurenai, Mag'Har**: Rep from quests for these was increased in some patch.

**Sporeggar**: rep from quests was to low.

**Diaphanous wing droprate**: made uniform over all insects.

**Greater and Young Sporebat**: now drop eyes, was added in some patch.

**Vengeful Draenei**: There were 3 of these, added more based on TC.

**Escaping the Tomb**: was missing its goal

**Slain Sha'tar Vindicator**: Redone to be more and faster respawn.
**Slain Auchenai Warrior**: Redone to be more and faster respawn.

**Howling wind**: uniform droprate.

**Tests performed:** tested on my own build
**Target branch(es):** master

### CODE REVIEW

**Comment by Ladrek1989** [comment]
i'll give this ago when i get home tonight

**Comment by Ladrek1989** [comment]
Bael'Gar's Fiery Essence Works testing others

**Comment by Ladrek1989** [comment]
Crimson Crystal Shard drops 100%

**Comment by Yehonal** [comment]
PR imported on staging-branch, ready to be tested on public demo server

**Comment by Jagermaister95** [comment]
The reports have all been tested and confirmed.
Tested on azerothcore demo server.

**Comment by ShinDarth** [comment]
@Yehonal @Jagermaister95 very good

**Pull request merged**
