### PR TITLE
refactor(Core/Misc): acore to Acore

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  In most cases right now we use Lower::Upper::Upper
-  With PR most cases will use Upper::Upper::Upper which makes more sense imho

## Tests Performed:

- Wait for CI

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Need fixing modules

**Comment by Kitzunu** [comment]
https://github.com/ElunaLuaEngine/Eluna/pull/364

**Comment by Winfidonarleyan** [comment]
Conflicts

**Comment by Winfidonarleyan** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/385d8ff00671e1c325e35465af49f58b51375441/apps/EnumUtils/enumutils_describe.py

**Comment by FrancescoBorzi** [comment]
```
WorldObjectMethods.h:191:9: fatal error: use of undeclared identifier 'acore'; did you mean 'Acore'?
        acore::UnitLastSearcher<ElunaUtil::WorldObjectInRangeCheck> searcher(obj, target, checker);
```

**Comment by Kitzunu** [comment]
> [ElunaLuaEngine/Eluna#364](https://github.com/ElunaLuaEngine/Eluna/pull/364)

**Pull request merged**
