### PR TITLE
refactor(Core/Trainer): Import TC handling of Trainers

### PR DESCRIPTION
**Pull request by Kitzunu**
* Cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/bf3ab6d9c4366dae1d34957813e3fbf40ac8532b)

Co-Authored-By: Shauren shauren.trinity@gmail.com
Co-Authored-By: Ghaster 11392454+Ghaster@users.noreply.github.com

old https://github.com/azerothcore/azerothcore-wotlk/pull/5428

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5420

TODO:

- [x] Implement acore::Containers::MapGetValuePtr https://github.com/azerothcore/azerothcore-wotlk/pull/6111
- [x] Implement Cell::VisitWorldObjects https://github.com/azerothcore/azerothcore-wotlk/pull/6113
- [x] Implement sSpellMgr->AssertSpellInfo https://github.com/azerothcore/azerothcore-wotlk/pull/6115
- [x] Implement AsUnderlyingType https://github.com/azerothcore/azerothcore-wotlk/pull/6117
- [x] Implement SkillLineAbility.dbc to determine player initial spells https://github.com/azerothcore/azerothcore-wotlk/pull/6015

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
> Co-Authored-By: Shauren [shauren.trinity@gmail.com](mailto:shauren.trinity@gmail.com)
> Co-Authored-By: Ghaster [11392454+Ghaster@users.noreply.github.com](mailto:11392454+Ghaster@users.noreply.github.com)

image

**Comment by Kitzunu** [comment]
LMAO

**Comment by Sedatyf** [comment]
Sorry about the mention thing, wrong copy paste 😓

**Comment by Helias** [comment]
This PR will improve the AoWoW compatibility :rocket:

**Comment by Kitzunu** [comment]
too much conflicts

**Pull request closed without merging**
