### PR TITLE
fix(DB/SAI): Various fixes for Mogor (Ring of Blood)

### LINKED ISSUE #1907: Nagrand Arena Mogor the Ogre doesn't revive himself
SMALL DESCRIPTION:

Mogor doesn't revive after he's been killed for the first time.

EXPECTED BLIZZLIKE BEHAVIOR:

https://www.youtube.com/watch?v=i-atkvdLsNA Quotes look chat

Video Bossfight https://youtu.be/wCjLu8Q1pM0?t=241

https://wowwiki.fandom.com/wiki/Mogor_the_Ogre

In the Burning Crusade expansion, Mogor leads the Warmaul Ogres in the Laughing Skull Ruins in northern Nagrand in Outland. He watches, while shouting insults at you, during the series of battles in the Ring of Blood. After you finish pummeling (or getting pummeled by) the 5 elites, Mogor himself comes down to fight you personally. He has a slight heal, (but has a ton of health, making it a very annoying ability) When he is first killed he will resurrect himself (He will have less health this time around) and will enrage, hitting for over 1000 damage on plate armor.

CURRENT BEHAVIOUR:

Man goes to do the arena quest in Nagrand after killing the 5 bosses before comes Mogor.

Mogor doesn't do much except go into the ring and say 1 sentence and then start the fight he heals himself a little and castet follow spells.

Spells that work

Mogor - In Combat - Cast 'Chain Lightning' (No Repeat) ID 16033
Mogor - In Combat - Cast 'Flame Shock' (No Repeat) ID 39529
Mogor - Between 0-60% Health - Cast 'Healing Wave' (No Repeat) 15982
Mogor - Between 0-30% Health - Cast 'Frenzy' (No Repeat) ID 28747

When he dies, he completes the quest.

AC Video https://youtu.be/hBb-2u2fmrw

Offi Video Bossfight https://youtu.be/wCjLu8Q1pM0?t=241

STEPS TO REPRODUCE THE PROBLEM:

.quest remove 9962
.quest remove 9967
.quest remove 9970
.quest remove 9972
.quest remove 9973
.quest remove 9977

.go -727.81 7929.77 58.001 530 

Start the quest series and defeat the 5 bosses and then start the quest with mogor name of quest The Ring of Blood: The Final Challenge.

BRANCH(ES):

AzerothCore rev. 0e08350b69fe+ 2019-05-28 14:29:31 +0200 (master branch) (Win64, Release)

OPERATING SYSTEM:
Windows 10

MODULES: 
Transmog
Worldchat

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74814278-nagrand-arena-mogor-the-ogre-doesn-t-revive-himself?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Mogor is the final challenge in the "Ring of Blood" quest chain. The following fixes will be applied:

- Mogor resurrects himself after being defeated for the first time
- he will only cast "Frenzy" after resurrection
- he now uses also Ice Totem
- Ice Totem has been fixed to periodically cast "Frost"
- he now casts "Chain Lightning" only every 10 seconds
- he uses "Healing Wave" only once at 60% health during the first part of the fight
- he uses "Healing Wave" every 15 seconds when below 50% health during the second part of the fight
- if combat is cancelled he resets himself and returns to his home position

###### ISSUES ADDRESSED:
Closes #1907 

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- preparation:
```
.quest remove 9962
.quest remove 9967
.quest remove 9970
.quest remove 9972
.quest remove 9973
.quest remove 9977
.go -727.81 7929.77 58.001 530
```
- play through the quest chain
- finally fight and defeat Mogor; after being killed he should resurrect himself before being defeated once and for all

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@Selyria 
Ok, thanks for testing this. I updated the script:
- Mogor will now use Ice Totem
- he will cast Frenzy only after resurrection

**Comment by Selyria** [comment]
> @Selyria
> Ok, thanks for testing this. I updated the script:
> 
> * Mogor will now use Ice Totem
> * he will cast Frenzy only after resurrection



- [ ] The boss shouldn't go enrage in the first phase of life. He should not do that until the second phase after resuscitation. 

- [ ] The totem is missing in the first phase of life as well as in the second phase of life.

- [ ] The boss casts Chain Lightning way too often. He should hit too. He should do Chain Lightning only about every 10-12 seconds according to the video. 

- [ ] The boss should heal himself in the second phase of life from about 50%.
Healing every 14-16 seconds according to video

- [ ] When the group dies the boss should resetten and not just stand in the ring and be aggro

I think after that he's blizzlike.

**Comment by Stoabrogga** [comment]
@Selyria 
Ok, I updated the SQL script once more, should have now addressed all points additionally to the ones I already mentioned:
- Chain Lightning only every 10 seconds
- Healing Wave when below 50% health and then every 15 seconds (he uses it also in the first phase, as can be seen in the video)
- if he is out of combat he will despawn after 10 seconds

Could you please test once more?

**Comment by Selyria** [comment]
> @Selyria
> Ok, ich habe das SQL-Skript noch einmal aktualisiert, hätte jetzt alle Punkte zusätzlich zu den bereits erwähnten ansprechen sollen:
> 
> * Kettenblitz nur alle 10 Sekunden
> * Heilwelle bei weniger als 50% Gesundheit und dann alle 15 Sekunden (er benutzt sie auch in der ersten Phase, wie im Video zu sehen ist)
> * Wenn er sich außerhalb des Kampfes befindet, wird er nach 10 Sekunden verschwinden
> 
> Könnten Sie bitte noch einmal testen?



> @Selyria
> Ok, I updated the SQL script once more, should have now addressed all points additionally to the ones I already mentioned:
> 
> * Chain Lightning only every 10 seconds
> * Healing Wave when below 50% health and then every 15 seconds (he uses it also in the first phase, as can be seen in the video)
> * if he is out of combat he will despawn after 10 seconds
> 
> Could you please test once more?

- [X] The boss shouldn't go enrage in the first phase of life. He should not do that until the second phase after resuscitation. 

- [X] The totem is missing in the first phase of life as well as in the second phase of life.

- [ ] Totem spell has to be fixed think core

- [X] The boss casts Chain Lightning way too often. He should hit too. He should do Chain Lightning only about every 10-12 seconds according to the video. 

- [ ] Phase One
In the first phase of life he should be allowed to heal himself from 60% 1 times
Phase 2
The boss should heal himself in the second phase of life of about 50%.
Healing every 14-16 seconds according to the video

- [ ] If the group dies he should better respawn and not despawn then you have to wait for respawn.

Which doesn't make any sense as he hasn't been defeated.

I think after that he's blizzlike.


The totem is defective. It castet 1 time the spell Frost ID 18977 but this should recall it every 3 seconds.

**Comment by Stoabrogga** [comment]
@Selyria 
Ok, I think I managed to solve the remaining issues. Could you please test the updated script?

**Comment by Selyria** [comment]
> @Selyria
> Ok, I think I managed to solve the remaining issues. Could you please test the updated script?

Well, I gotta say, super work. 

Last minor error

- [ ] The boss can't be stunned or silenced.

**Comment by Stoabrogga** [comment]
@Selyria
So, Mogor should be interruptible or not interruptible? Sorry, but I don't quite understand.

**Comment by Stoabrogga** [comment]
I pushed another commit setting the appropriate mechanic immune flags for Mogor. He should now be unstoppable for the players. Hope it is better this way.

**Comment by Selyria** [comment]
> I pushed another commit setting the appropriate mechanic immune flags for Mogor. He should now be unstoppable for the players. Hope it is better this way.

One Word Perfect

**Comment by Stoabrogga** [comment]
Great, thanks for all your help and feedback :+1:

**Pull request merged**
