### PR TITLE
feat(Core/Database): add support set arguments for PrepareStatment

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- partical cherrypick https://github.com/WarheadCore/WarheadBand/commit/0b3f073ca2419576eb1a24464cef1485f8b75e02

## Example usage:

- `SetArguments`
```cpp
LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_IP_INFO);
stmt->SetArguments(ip_address);
LoginDatabase.Execute(stmt);

LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_SEL_LOGONCHALLENGE);
stmt->SetArguments(GetRemoteIpAddress().to_string(), login);
LoginDatabase.Execute(stmt);
```

- `SetData`
```cpp
LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_UPD_LOGON);
stmt->SetData(0, salt);
stmt->SetData(1, verifier);
stmt->SetData(2, accountId);
LoginDatabase.Execute(stmt);

LoginDatabasePreparedStatement* stmt = LoginDatabase.GetPreparedStatement(LOGIN_ADD_VIP);
stmt->SetData(0, accID);
stmt->SetData(1, 30min);
stmt->SetData(2, vipLevel);
LoginDatabase.Execute(stmt);
```

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@Kitzunu just look this :D

**Review by acidmanifesto — APPROVED** [review]

**Comment by claudiodfc** [comment]
I see, more random changes for no reason

**Comment by 55Honey** [comment]
> I see, more random changes for no reason

Do you have anything useful to say? If not, feel free to refrain from commenting.

**Comment by Winfidonarleyan** [comment]
> I see, more random changes for no reason

Do you have a problem with something?

**Pull request merged**
