### PR TITLE
fix(Core/Combat): Rooted creatures should attack targets in melee reach.

### LINKED ISSUE #12108: Rooted npcs should ignore out of reach targets for current highest threat melee target selection #3634
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Melee NPCs stand while rooted and wait until the root is over to reach the highest threat target if out of range.

[1. Druid rooted nearest melee threat target ignored ](https://streamable.com/avmuot)
[2. Mage Frost Nova Root highest threat target ignored ](https://streamable.com/jaikdm)
### Expected Blizzlike Behaviour

n = rooted npc
h = current threat holder
p = lower on threatlist

n ------------ h
p

n should attack p, because it can't reach h
after the root ends it should go and attack h again (unless someone overthreated by the regular 130% 110% rules relative to h)

### Source
Rooted target
Another WoWWiki guide source.

image
https://www.wowhead.com/spell=122/frost-nova#comments:id=36313

image
https://wowwiki-archive.fandom.com/wiki/Root

### Steps to reproduce the problem

Assemble 2 controllable units (2 players, player and pet, whatever) and an npc
build some threat on the npc
root the npcs
move the unit highest in threat away from the npc

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3634

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36f0a7757bde9573262f298aa1eaf6765af8295e

### Operating system
Windows 10.

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12108

## Issues Addressed:

- Closes #12108
- Closes https://github.com/chromiecraft/chromiecraft/issues/3634

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Assemble 2 controllable units (2 players, player and pet, whatever) and an npc
build some threat on the npc
root the npcs
move the unit highest in threat away from the npc

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@Tereneckla Please - test it.

**Comment by Tereneckla** [comment]
They now prioritize a target in melee range over the threattable even when not rooted

**Comment by UltraNix** [comment]
@Tereneckla @BeefSteaker Should be okay now.

**Comment by Tereneckla** [comment]
Works as expected with pure melee NPCs now

One thing I thought of while testing is the behavior of mainly ranged NPCs. With this pull request they switch to melee when rooted even if the melee target is not highest in threat. I assume that to be wrong but am not sure on that
Gully is investigating on blizz servers

**Comment by Tereneckla** [comment]
@UltraNix 
Gully tested it,
Ranged mobs should prioritize ranged targeting over melee (maybe it's obvious in hindsight)

a ranged mob for your convencience:
.go c 202648

**Comment by UltraNix** [comment]
@Tereneckla I have no idea to define ranged mob in core.

**Comment by Gultask** [comment]
CastFlags 64 in SAI, combat movement, CMC

**Comment by UltraNix** [comment]
Yeah - that's in script, not in core.

**Comment by Nyeriah** [comment]
We need to create AI behavior patterns. So a ranged creature behaves properly e.g moves away from rooted players, prioritizes targets, etc.

**Comment by GastonCK** [comment]
Is there something to test here? I see no changes since the last test performed by Tereneckla.

**Comment by Nyeriah** [comment]
Yes, sorry, unfortunately this has been abandoned. If the author would like to continue this we can reopen it later.

**Comment by elthehablo** [comment]
> We need to create AI behavior patterns. So a ranged creature behaves properly e.g moves away from rooted players, prioritizes targets, etc.

So this is also the root problem of the casters not moving after being silenced bug

**Pull request closed without merging**
