### PR TITLE
Core/ICC: Lord marrowgar, bone storm target selection

### PR DESCRIPTION
**Pull request by GitVerge**
###### CHANGES PROPOSED:
-  Lord marrowgar will select top 2 or 4, depending on raid mode, farthest raid members during bone storm.

###### ISSUES ADDRESSED:
#786

##### TESTS PERFORMED:
None

##### HOW TO TEST THE CHANGES:
Fight this boss with more than 2 or 3 players

##### TODO
I am not sure about the numbers, had several retail videos as reference.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by GitVerge** [comment]
A lot of commits, sorry. It should be good to test.

**Comment by BarbzYHOOL** [comment]
no problem for the commit count

**Comment by comix1988** [comment]
I tried to test this PR but as seen from the video lord marrowgar now remains stationary on the tank when cast bonestorm.
https://www.youtube.com/watch?v=5_2V01UzJ3A&feature=youtu.be
am I wrong?

**Comment by wetbrownsauce** [comment]
Tested. Unsure if this is blizzlike. Marrowgar definitely bonestorms to random targets, seemingly preferring the further ones initially, but subsequent charges seem... off.  

Referring to this post: [here](https://www.wowhead.com/forums&topic=157432&p=2085401#p2077262)

With the set up described in the post (I tested with six players, 1 at X, 1 at Y, 1 at Z, and then 3 remaining stacked at the center) it would seem that the blizzlike behavior would be "You will find that Marrowgar will bounce around from one tank to the other". Meaning in this test, he should bounce between the people at positions X, Y, & Z. However, in testing he often swirls into the middle DPS group and hangs out for a while.

**Comment by comix1988** [comment]
i found this on wowpedia:

wowpedia
wowpedia2

write "random target",  not the farthest ones

**Comment by GitVerge** [comment]
Hmmm I am not sure about retail being 100% random, it was just the feel I got from the video. Maybe because in the videos everyone moves away from the storm it seems like it is targeting the furthest targets so it confused me.

Anyway there are a lot of things to do in ICC, included Marrowgar, and easier to confirm than this change.

You can close this PR without problems ^^

**Comment by FrancescoBorzi** [comment]
so shall this be closed? @wetbrownsauce @GitVerge @comix1988

**Comment by GitVerge** [comment]
it cannot be confirmed if it is retail-like behaviour,  so I close it.

**Pull request closed without merging**
