### PR TITLE
chore: Rename TRINITY_DEBUG to CORE_DEBUG

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
##### CHANGES PROPOSED:
- Give proper name to that debug option

##### TESTS PERFORMED:
- NO TESTS DONE (but i had to make the PR while I had it in mind else it would be forgotten forever :P)
-

##### HOW TO TEST THE CHANGES:

Compile and enable core debug with the cmake option `WITH_COREDEBUG`, then check if the debug messages work.

##### KNOWN ISSUES AND TODO LIST:

- Maybe we should rename the cmake option to a simpler `COREDEBUG` no? the `WITH_` seems superfluous but many other options also use this weird syntax

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
And what about changing this too:

```cmake
src/server/worldserver/CMakeLists.txt:49:    COMPILE_DEFINITIONS _TRINITY_CORE_CONFIG="${CONF_DIR}/worldserver.conf")
src/server/authserver/CMakeLists.txt:53:    COMPILE_DEFINITIONS _TRINITY_REALM_CONFIG="${CONF_DIR}/authserver.conf")
```

**Comment by Viste** [comment]
#2436

**Comment by Viste** [comment]
https://github.com/azerothcore/azerothcore-wotlk/commit/e22d78ecd6997bc11f8620b759364f119dac431a renamed to ACORE_DEBUG

**Comment by BarbzYHOOL** [comment]
acore is confusing

**Comment by Viste** [comment]
why?
ACORE_DEBUG - azerothcore_debug all is ok on my view

**Comment by Stoabrogga** [comment]
I don't think we need this PR anymore, ACORE_DEBUG is good enough.

**Comment by BarbzYHOOL** [comment]
you chose acore cause that's what yehonal put long ago, but nobody says acore for azerothcore we either say "AC" or "AzerothCore" or maybe "AzCore"

it's confusing as fuck because we don't know what it is, nowhere is written "acore" but in some files

also sad i have done that for nothing while we now have a worse name

**Comment by Stoabrogga** [comment]
To be honest, I like "ACORE" better than "AC", "AZCORE", "CORE" or something like that.

**Comment by BarbzYHOOL** [comment]
we never see acore anywhere, i thought it was a dependency from another project, you know like the directories called "drassil" or whatever but in fact it's just "azerothcore"

ofc i will remember that acore = azerothcore, it's not for me
and it's not for you either, it's for people who never touched AC, they might be confused in my opinion (as I was) 

maybe create a lexicon with all the terms in the wiki then lol but imo names should be obvious

**Comment by Viste** [comment]
@BarbzYHOOL acore now is main namespace and in db we now use acore_string you can't get confused

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL you can blame @Yehonal for the "drassil" naming :D

**Pull request closed without merging**
