### PR TITLE
feat(Tools/Mapextractor): Implemented liquid object detection 

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/e6bfa71e4d43c49a95e2ddca5522c68322be8117
https://github.com/TrinityCore/TrinityCore/commit/fd30618f12b3414e92acd0ffc8b196bfd295ce00
https://github.com/TrinityCore/TrinityCore/commit/8d1bb258fc4a777b2bd145efd9cadb22d4ec84a2
https://github.com/TrinityCore/TrinityCore/commit/2924283f072459c0c324c8e8d6f7e78ca718dbad

## Tests Performed:

- NOT-TESTED
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
@pklloveyou Can you test this pr please

**Comment by UltraNix** [comment]
MMaps should be updated as well (version).

**Comment by pklloveyou** [comment]
Can you merge it #10922?

**Comment by Lynethris** [comment]
I got this error during the extraction:

Screenshot 2022-04-18 122248

**Comment by IntelligentQuantum** [comment]
> @IntelligentQuantum I got this error during the extraction:
> 
> Screenshot 2022-04-18 122248

Ok Tnx

**Comment by IntelligentQuantum** [comment]
@Lynethris Again pease

**Comment by Lynethris** [comment]
Test done in: ZulGurub, Westfall, Stormwind, Orgrimmar, Montelcore/BRD, Naxxrammas.

- [X] No issue with map extraction
- [X] No issue/crash in worldserver
- [X] No glicht find with area liquid
- [X] Lava damage is always applied to player (test in MC/BRD)

- [ ] For Naxxrammas, player receive no dammage/debuff from liquids. I'm not totally sure but normally, this should be the case. (same mechanic as lava).

**Comment by IntelligentQuantum** [comment]
>     * [ ]  For Naxxrammas, players receive no dammage/debuff from liquids. I'm not totally sure but, normally this should be the case. (same mechanic as lava).

Does it work properly without these edits? @Lynethris

**Comment by Nefertumm** [comment]
It does, I already checked it.

**Comment by Nefertumm** [comment]
Conflicts again :P

**Comment by IntelligentQuantum** [comment]
@Lynethris Can you test again

**Comment by Lynethris** [comment]
Work now for Nax. Any others issues find. 

Just for information, no damage from slime liquid in undercity. But for this case, I don't know if it's like this on retail.

**Comment by Nefertumm** [comment]
I'll check in a bit the issue commented by Lynethris. I'll let you know

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
I'll merge after Wednesday

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
