### PR TITLE
fix(Core/Spell): Make use of SPELL_ATTR6_NOT_RESET_SWING_IF_INSTANT

### PR DESCRIPTION
**Pull request by Kitzunu**
ported from tc

## Changes Proposed:
-  Make use of SPELL_ATTR6_NOT_RESET_SWING_IF_INSTANT

this affects these spells

```sql
SELECT `id`, `name_lang_1`, `attributesEx6`
FROM `dbc_spell` 
WHERE `attributesEx6` & @flag = @flag
```
| id | name_lang_1 | attributesEx6 | 
| ---: | --- | ---: | 
| 879 | Exorcism | 33554432 | 
| 5614 | Exorcism | 33554432 | 
| 5615 | Exorcism | 33554432 | 
| 10312 | Exorcism | 33554432 | 
| 10313 | Exorcism | 33554432 | 
| 10314 | Exorcism | 33554432 | 
| 19750 | Flash of Light | 33554432 | 
| 19939 | Flash of Light | 33554432 | 
| 19940 | Flash of Light | 33554432 | 
| 19941 | Flash of Light | 33554432 | 
| 19942 | Flash of Light | 33554432 | 
| 19943 | Flash of Light | 33554432 | 
| 27137 | Flash of Light | 33554432 | 
| 27138 | Exorcism | 33554432 | 
| 48784 | Flash of Light | 33554432 | 
| 48785 | Flash of Light | 33554432 | 
| 48800 | Exorcism | 33554432 | 
| 48801 | Exorcism | 33554432 | 
| 66113 | Flash of Light | 33554432 | 
| 68008 | Flash of Light | 33554432 | 
| 68009 | Flash of Light | 33554432 | 
| 68010 | Flash of Light | 33554432 | 

## Tests Performed:
- None

## How to Test the Changes:

Make sure none of those spells trigger bool Spell::IsAutoActionResetSpell() const

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/4306

**Comment by claudiodfc** [comment]
Paladins are actually broken for needing this flag

**Comment by Kitzunu** [comment]
Explain pls

**Comment by claudiodfc** [comment]
From the sound of it, it's a check flag in order to avoid instant spells reseting auto attacks?

**Comment by Kitzunu** [comment]
Yea, autoattack should not reset if the casttime is instant and the spell has this attribute (Which the ones above have by default in DBC)

**Comment by claudiodfc** [comment]
What i meant in the message before was, the fact that so many Paladin spells need this flag is silly, makes them unnecessarily strong hehe

**Comment by Kitzunu** [comment]
Ah :P

**Comment by pklloveyou** [comment]
I didn't understand the effect of it

**Comment by Kitzunu** [comment]
If the spell is an instant cast and has that attribute (Only the spells above have this attribute) that will do so your auto-attack will not reset after that spell

**Comment by pklloveyou** [comment]
image

**Comment by pklloveyou** [comment]
I still don't understand. :(

**Comment by Kitzunu** [comment]
Okay, so:

1. Auto attack a target
2. Use one of the spells, if it has casttime nothing changes
3. If the spell is instant cast, then you should continue to autoattack the same as before and not cast an autoattack right after the spell

**Comment by pklloveyou** [comment]
OK, I'll try,

**Comment by Voxstrasza** [comment]
Download the Quartz addon for 3.3.5.  It has a built in swing timer and it will help with testing this.

**Comment by pklloveyou** [comment]
Tested

**Comment by pklloveyou** [comment]
48825->48785  prompt It doesn't interrupt melee attacks

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
