### PR TITLE
fix(Core/Spell): Glyph apply bonus

### PR DESCRIPTION
**Pull request by r0m1ntik**
Thank @lineagedr for fix.

## Changes Proposed:
-  Fixed glyph bonus after reload

## Issues Addressed:
- Closes [3387](https://github.com/azerothcore/azerothcore-wotlk/issues/3387)
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3388

## Tests Performed:
-
-

## How to Test the Changes:

1) create paladin
2) apply glyph [Glyph of Seal of Vengeance](https://wowroad.info/?item=43869)
3) use Seal of Vengeance
4) reload
5) bonus do not reset

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by mnclaras — APPROVED** [review]
Tested and working.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Kitzunu** [comment]
Will this fix https://github.com/azerothcore/azerothcore-wotlk/issues/3772 ?

**Comment by lineagedr** [comment]
@Kitzunu Out of those two issues only https://github.com/azerothcore/azerothcore-wotlk/issues/3388 the other issue I did a PR that was closed.

**Comment by Kitzunu** [comment]
Would it fix https://github.com/azerothcore/azerothcore-wotlk/issues/488 ?

**Comment by Kitzunu** [comment]
thanks =)

**Pull request merged**
