### PR TITLE
fix(DB/pathing): Badlands Missing Pathing

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Add missing pathing to many NPC and creatures in Badlands
-  All values from VMangos

## Issues Addressed:

- Closes unreported issues

## SOURCE:

VMangos

## Tests Performed:

- Manually checked each path, all seem correct

## How to Test the Changes:

1. .tele badlands
2. Check new creature paths

## Known Issues and TODO List:

- [x] This PR currently has an issue that needs to be resolved! Paths are added to several flying creatures (buzzard), but this cause them to fly on the ground as if walking. If I set a delay time on a waypoint, they will wait at the correct flight height, but will move to ground again when moving between waypoints. The waypoint locations are from VMangos sniffs so I do not think it is correct to just move them up higher. Does anyone know how to resolve this?

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kosiak** [comment]
Im on mobile at the moment so i cant check. Mby try `creature_template_movement` table?

**Comment by ZhengPeiRu21** [comment]
> Im on mobile at the moment so i cant check. Mby try `creature_template_movement` table?

Thank you for the ideas. I thought the same thing, but the creature_template_movement for these creature seems correct:
image

move_type for the waypoint_data is also set to 2, so I am very confusing why it does not work!

**Comment by Kosiak** [comment]
> > Im on mobile at the moment so i cant check. Mby try `creature_template_movement` table?
> 
> Thank you for the ideas. I thought the same thing, but the creature_template_movement for these creature seems correct: image
> 
> move_type for the waypoint_data is also set to 2, so I am very confusing why it does not work!

If that picture is for the creature u need try to set flight to 2. Or if ut should be 1 then u need to specify hover height in `creature_template`.

**Comment by ZhengPeiRu21** [comment]
Thank you, I did not think of set Flight to 2. With that change, it is better, but still fly very close to the ground and have sudden movement to the ground when it reaches a waypoint. I did try to just move waypoints up higher, and doing this it looks right, but the creature still "pops up" every time it is not moving between waypoints, so I think this is not the correct fix (and also modifies the sniffed data, which should not be right.) It does look correct on Vmangos but it could be the core handling things differently.

**Comment by Kosiak** [comment]
Try `flight` = 1 and try to play with hover height in `creature_template`. That way u wont modify any axis.

**Comment by ZhengPeiRu21** [comment]
> Try `flight` = 1 and try to play with hover height in `creature_template`. That way u wont modify any axis.

Apology for the slow response. This did not seem to work for me - I set the hover height to a very high value but the creature still was move on the ground. Thank you for the idea. Sorry that this is still not working! I am not sure what else to try.

**Comment by Maelthyrr** [comment]
@ZhengPeiRu21 help wanted ? or is it abandon ?

**Comment by ZhengPeiRu21** [comment]
> @ZhengPeiRu21 help wanted ? or is it abandon ?

Help would be very appreciate. Everything is work except for the flying creature movement issue. We could just remove their pathing if we are needing, but it seems like a good path and should work - I wonder if there is core difference that needs to change.

**Comment by hanabi5** [comment]
You have to add creature template movement to them

**Comment by ZhengPeiRu21** [comment]
> You have to add creature template movement to them

Thank you for the suggesting. However, these creature already have Flight set to 1 in creature_template_movement.

**Comment by hanabi5** [comment]
How about their ground flag? I remember have some creatures not alternating between flying and walking

**Comment by ZhengPeiRu21** [comment]
> How about their ground flag? I remember have some creatures not alternating between flying and walking

Ground flag is set to 0. I think this correct; these model do not have any ground animation.

**Comment by ZhengPeiRu21** [comment]
> ~https://www.azerothcore.org/wiki/creature_template_movement#flight check the flight table, it's set to disable gravity~
> 
> Try ground flag 2

That fixed it! Thank you! It looks great now. This is ready to be tested again.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
