### PR TITLE
fix(Core/Creatures): Implemented `CREATURE_FLAG_EXTRA_DONT_CALL_ASSISTANCE` extra flag.

### LINKED ISSUE #12745: [AQ20] General Rajaxx - Waves 6 chain pull waves 7
### Current Behaviour

Wave 6 chain pulls Wave 7 because some mobs of the wave path around the center object to the wrong side

### Expected Blizzlike Behaviour

the waves shouldnt pull others wavrs

### Source

_No response_

### Steps to reproduce the problem

- .tele aq20
- Do Rajaxx waves until the waves 6

### Extra Notes

https://github.com/chromiecraft/chromiecraft/issues/3920

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #12745

## Issues Addressed:

- Closes #12745

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.tele aq20
Do Rajaxx waves until the waves 6

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
@UltraNix doesn't work. Parkkon don't follow this adds and pass by the right side pulling the waves 7.

https://youtu.be/CtZsoh6KNGQ

**Comment by UltraNix** [comment]
@Maelthyrr Please, test it again.

**Comment by Maelthyrr** [comment]
Tested again, and I got the same result :/

**Comment by UltraNix** [comment]
@Maelthyrr Just tested and works okay.

**Comment by UltraNix** [comment]
https://imgur.com/a/gzAROGz

**Comment by Maelthyrr** [comment]
Sorry, I'm stupid. I forgot to apply the sql ><. So work fine thank you :) (I will look to apply this in ZG and BWL where we got the same issue)

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
