### PR TITLE
feat(Core/Network): Add Proxy Protocol v2 support.

### PR DESCRIPTION
**Pull request by walkline**
In some cases, you may want to place the authserver or worldserver behind a proxy or load balancer. However, if you do this, you would lose the client's address (IP). To address this issue, most proxies and load balancers support Proxy Protocol (v1 & v2). To utilize it, we also need Proxy Protocol support on both the authserver and worldserver.

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18100

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

I used HAProxy to test this change.
1. I changed authserver and worldserver configs by changing ports (3777 & 8026) and by enabling Proxy Protocol.
2. Run HAProxy with the next config:
```
global
    log /dev/log    local0
    log /dev/log    local1 notice
    stats timeout 30s

defaults
    log global
    mode tcp
    option tcplog
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend tcp_front
    bind 0.0.0.0:3724
    default_backend tcp_back

frontend tcp_world
    bind 0.0.0.0:8085
    default_backend tcp_world_back

backend tcp_back
    server backend_server 127.0.0.1:3777 send-proxy-v2

backend tcp_world_back
    server backend_server 127.0.0.1:8026 send-proxy-v2
```
3. Login to the game using regular ports.
4. You can use `.lookup ip` command to verify players IP.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Voidx** [comment]
Can someone explain to me exactly how to configure this? I’ve tried different ways and I can’t get it to work

**Comment by walkline** [comment]
@Voidx what proxy are you using, and could you share the configuration on both the proxy and AC sides?

**Comment by Voidx** [comment]
@walkline Good morning, thank you for the help,
I am using HAProxy, I assume that the following configuration will be on the frontend:
```

global
log /dev/log local0
log /dev/log local1 notice
stats timeout 30s

defaults
log global
mode tcp
option tcplog
timeout connect 5000ms
timeout client 50000ms
timeout server 50000ms

frontend tcp_front
bind 0.0.0.0:3724
default_backend tcp_back

frontend tcp_world
bind 0.0.0.0:8085
default_backend tcp_world_back

backend tcp_back
server backend_server 217.182.194.32:3777 send-proxy-v2

backend tcp_world_back
server backend_server 217.182.194.32:8026 send-proxy-v2

```

on backend server:
worldconfig bind to 0.0.0.0:8026
auth 0.0.0.0:3777
Network.EnableProxyProtocol = 1 on auth and world config

on realmdlist table:
id name address localAddress localSubnetMask port icon flag timezone allowedSecurityLevel population gamebuild
1 Azerothcore 217.182.194.32 127.0.0.1 255.255.255.0 8026 0 2 1 0 0 12340

HAProxy version 2.8.5-1ubuntu3.4

HAProxy is only on the frontend, right?
Do I need to set any blocking rule or something similar?

Very grateful for the response, really!

**Comment by walkline** [comment]
I see the issue - you’re pointing to the real worldserver in the realmlist table, but it should point to the proxy.

What exactly is the problem for you? Can you log in and see the list of realms, or are you unable to log in at all?

**Comment by Voidx** [comment]
I understand the idea of pointing to the proxy, but what if you want to use 2 proxies?
I cannot log in directly — it reaches “get realms”, the auth does communicate, but the worldserver sends the response back using the backend’s real IP instead of the proxy.

**Comment by walkline** [comment]
As for the issue - it looks like the problem is in the realmlist table that I already mentioned.

As for 2 proxies. You mean 2 proxies for the same realm? Unfortunately, you can’t have multiple records in the realmlist table for a single realm. I’d try to solve this at the DNS level, for example by using round-robin DNS or GeoDNS to return different proxy IPs (and specify this dns in realmlist table).

**Comment by Voidx** [comment]
Oh, what a pity. What I really wanted to do is have 2 different connection points to the backend: the first one from the actual backend machine, and the second one from the proxy (to improve the connection for certain countries).

**Comment by Voidx** [comment]
Now I have done the following test and it still gets stuck on “authenticating”:

```
global
    log /dev/log    local0
    log /dev/log    local1 notice
    stats timeout 30s

defaults
    log global
    mode tcp
    option tcplog
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend tcp_front
    bind 0.0.0.0:3724
    default_backend tcp_back

frontend tcp_world
    bind 0.0.0.0:8085
    default_backend tcp_world_back

backend tcp_back
    server backend_server 217.182.194.32:3777 send-proxy-v2

backend tcp_world_back
    server backend_server 217.182.194.32:8026 send-proxy-v2
```

realmlist table:
id name address localAddress localSubnetMask port icon flag timezone allowedSecurityLevel population gamebuild
1 Azerothcore 74.208.227.146 127.0.0.1 255.255.255.0 8026 0 2 1 0 0 12340

WorldServerPort = 8026
RealmServerPort = 3777

**Comment by walkline** [comment]
I think you are specifying a wrong port in realmlist table, it should be 8085 as specified in frontend, right?

**Comment by Voidx** [comment]
@walkline  I’ve tried with 8085 and with 8026, neither of them works.

**Comment by walkline** [comment]
@Voidx we can continue discussion in discord if required.

**Pull request merged**
