### PR TITLE
refactor(Core/BG/AB): code cleanup

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
##### CHANGES PROPOSED:

- Fixed some clang-tidy warnings

##### TESTS PERFORMED:

Builds, runs, tried a quick AB game with 1 player only and everything looks fine.

Tip: don't see the flags of AB? Close your WoW client and delete its `Cache` folder. Then try again.

##### HOW TO TEST THE CHANGES:

- Make sure that the Battlground **Arathi Basin** is not broken and there is not regression

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Endeffect-AT** [comment]
Can't test, build fails on commit 4103801f3ba808d307e70bdb6e73ecb310c81f09

[comp_err.txt](https://github.com/azerothcore/azerothcore-wotlk/files/4022935/comp_err.txt)

**Comment by FrancescoBorzi** [comment]
@Endeffect-AT thanks a lot, I will update this.

**Comment by FrancescoBorzi** [comment]
Same here. @Endeffect-AT done, can you please test this?

**Comment by Endeffect-AT** [comment]
- [ ] Gate gameobject exists during countdown
- [ ] Start timer works ( 2 min, 1 min, 30 sec (Get ready!) - Gate opens
- [ ] Assault/defend/capture announced
- [ ] Can only assault bases controlled by opposing faction
- [ ] Stats in scoreboard track correctly
- [ ] Player is dismounted when indoors
- [ ] Buffs are working correctly 
- [ ] Buffs are respawning after exactly 3 min
- [ ] Controlling no base gains 0 resources
- [ ] Gaining resources stacks as more bases are captured
- [ ] Controlling all bases gains ~ 30 resources per sec and you win fast
- [ ] After win closing timer works and player got kicked (2 min, 1 min, 45 sec, 30 sec, 15 sec)

**Comment by Helias** [comment]
Thank you for your awesome job!

**Comment by Endeffect-AT** [comment]
Would even test more, but unfortunately I don't have the time. Can't even complete my own planned PRs anymore :(

**Comment by Helias** [comment]
We need more testers, we can base our testing on only 1 person.
Personally, I am busy too, and when I have free-time I spend it on NEW apps/improvements/bugfix etc.

**Pull request merged**
