### PR TITLE
Remove useless item (Brew of the month) from Blix Fixwidget

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7998
- Closes https://github.com/chromiecraft/chromiecraft/issues/1801

## Tests Performed:

- Tested
- Arch Linux

## How to Test the Changes:

1..go c 152120
2.Talk to NPC
3.He is selling 1 Brew of the month (Entry = 37599)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by jamadaha** [comment]
Why does this have the 'To Be Merged' tag? Should someone else not test/review it first?

**Comment by jamadaha** [comment]
Tested:
Ran SQL query - Removed 2 rows, as expected? I think.
Found only one form for sale, as seen below
image

**Review by Hacki95 — APPROVED** [review]

**Review by Hacki95 — CHANGES_REQUESTED** [review]
How did you know which one of the both IDs to remove? 

According to wowhead tbc classic he is selling the 37737 version not the other one: https://tbc.wowhead.com/npc=24495/blix-fixwidget

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum please check @Hacki95 's comment

**Comment by IntelligentQuantum** [comment]
> How did you know which one of the both IDs to remove?
> 
> According to wowhead tbc classic he is selling the 37737 version not the other one: https://tbc.wowhead.com/npc=24495/blix-fixwidget

Check Azcobu description https://github.com/azerothcore/azerothcore-wotlk/issues/7998

And i checked warmane and wowcircle server both of them used 37599

**Review by Hacki95 — APPROVED** [review]

**Comment by Hacki95** [comment]
Thanks for the clarification!

It would greatly help if you would add sources to your PRs. It's often times hard to tell if something is guessed or if it has any research behind it.

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum what's the status of this PR?

**Comment by IntelligentQuantum** [comment]
> @IntelligentQuantum what's the status of this PR?

I dont have source for this.
I deleted this item because warmane and wowcircle doesnt have it.

**Comment by Yehonal** [comment]
> > @IntelligentQuantum what's the status of this PR?
> 
> I dont have source for this. I deleted this item because warmane and wowcircle doesnt have it.

According to this news: https://www.wowhead.com/news/brewfest-2009-sep-20-oct-5-quest-guide-information-120322#news-post-120322, The item has been added to that vendor during WotLK (2009). Hence, those two pserver you mentioned are possibly bugged

**Comment by IntelligentQuantum** [comment]
> > > @IntelligentQuantum what's the status of this PR?
> > 
> > 
> > I dont have source for this. I deleted this item because warmane and wowcircle doesnt have it.
> 
> According to this news: https://www.wowhead.com/news/brewfest-2009-sep-20-oct-5-quest-guide-information-120322#news-post-120322, The item has been added to that vendor during WotLK (2009). Hence, those two pserver you mentioned are possibly bugged

So we can close this pr.

**Pull request closed without merging**
