### PR TITLE
fix(DB): The Barrens minerals and pooling

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Removed current Azerothcore minerals for The Barrens
- Added gameobjects with sniffed data for Tin and Silver

## Issues Addressed:

- Closes part of #9431 

## SOURCE:

Classic Sniffs
## Tests Performed:

- Tested on Windows 10

## How to Test the Changes:

Roam around The Barrens and check for Silver (rare) and Tin.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by temperrr** [comment]
image
image
image

There seem to be silver & tin doubler spawning

(didnt check whole map)

**Comment by temperrr** [comment]
image

Silver one wasnt there... (other two were on top of eachother)

**Comment by temperrr** [comment]
image
image
image
image
image

**Comment by temperrr** [comment]
On a sidenote, looks good, apart from quite a few veins at the boars & dwarves in the south.

**Comment by claudiodfc** [comment]
I have to delete these Guids manually because they don't have a zoneId and I don't want to delete gobjects on a range of positions

**Comment by temperrr** [comment]
The ones I have missed we probably receive reports for eventually. Looks good!

**Pull request closed without merging**
