### PR TITLE
fix(DB/object): Pool copper veins in Eversong Forest

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  Pool copper veins in Eversong Forest
- Maybe ~~20~~ 30 spawns at once is a wrong number, but it's easy to modify afterwards

## Issues Addressed:
- This is a nicer way to control mining nodes

## Tests Performed:
- Teleported to locations

## How to Test the Changes:

```
.go xyz 8978.16 -7247.94 111.609 530 -- 74930 Eversong Woods, Copper Vein, spawn 1
.go xyz 9156.25 -5893.79 4.91682 530 -- 74931 Eversong Woods, Copper Vein, spawn 2
.go xyz 8851.35 -6392.48 32.4433 530 -- 74932 Eversong Woods, Copper Vein, spawn 3
.go xyz 8957.36 -6504.22 18.1698 530 -- 74933 Eversong Woods, Copper Vein, spawn 4
.go xyz 9061.54 -7157.18 79.3397 530 -- 74934 Eversong Woods, Copper Vein, spawn 5
.go xyz 9074.31 -6966.63 18.7819 530 -- 74935 Eversong Woods, Copper Vein, spawn 6
.go xyz 8772 -6848.48 61.0593 530 -- 74936 Eversong Woods, Copper Vein, spawn 7
.go xyz 8620.28 -7021.36 69.6507 530 -- 74937 Eversong Woods, Copper Vein, spawn 8
.go xyz 8296.24 -7134.22 126.994 530 -- 74938 Eversong Woods, Copper Vein, spawn 9
.go xyz 8304.13 -6966.73 93.4246 530 -- 74939 Eversong Woods, Copper Vein, spawn 10
.go xyz 8255.45 -6933.31 88.8827 530 -- 74940 Eversong Woods, Copper Vein, spawn 11
.go xyz 8141.18 -7891.01 201.926 530 -- 74941 Eversong Woods, Copper Vein, spawn 12
.go xyz 8758.19 -6855.44 65.6054 530 -- 74942 Eversong Woods, Copper Vein, spawn 13
.go xyz 9352.82 -7918.88 15.0909 530 -- 74943 Eversong Woods, Copper Vein, spawn 14
.go xyz 9153.6 -6066.24 91.2698 530 -- 74944 Eversong Woods, Copper Vein, spawn 15
.go xyz 8576.77 -7342.3 150.207 530 -- 74945 Eversong Woods, Copper Vein, spawn 16
.go xyz 9113.07 -6119.59 40.2528 530 -- 74946 Eversong Woods, Copper Vein, spawn 17
.go xyz 8840.84 -6578.18 53.5975 530 -- 74947 Eversong Woods, Copper Vein, spawn 18
.go xyz 9045.76 -6455.03 2.36801 530 -- 74948 Eversong Woods, Copper Vein, spawn 19
.go xyz 8113.18 -6211.63 41.5512 530 -- 74949 Eversong Woods, Copper Vein, spawn 20
.go xyz 8632.77 -6182.24 55.188 530 -- 74950 Eversong Woods, Copper Vein, spawn 21
.go xyz 8671.68 -6909.58 110.265 530 -- 74951 Eversong Woods, Copper Vein, spawn 22
.go xyz 8479.97 -6171.22 77.417 530 -- 74952 Eversong Woods, Copper Vein, spawn 23
.go xyz 8842.07 -7222.16 66.3173 530 -- 74953 Eversong Woods, Copper Vein, spawn 24
.go xyz 8744.72 -7365.18 95.5962 530 -- 74954 Eversong Woods, Copper Vein, spawn 25
.go xyz 8707.96 -5766.97 10.0575 530 -- 74955 Eversong Woods, Copper Vein, spawn 26
.go xyz 8924 -7719.83 198.6 530 -- 74956 Eversong Woods, Copper Vein, spawn 27
.go xyz 8620.07 -5806.49 37.7047 530 -- 74957 Eversong Woods, Copper Vein, spawn 28
.go xyz 8133.32 -6785.23 71.3577 530 -- 74958 Eversong Woods, Copper Vein, spawn 29
.go xyz 8199.71 -6835.06 79.741 530 -- 74959 Eversong Woods, Copper Vein, spawn 30
.go xyz 8852.93 -6967.63 30.9926 530 -- 74960 Eversong Woods, Copper Vein, spawn 31
.go xyz 8570.85 -7471.04 139.781 530 -- 74961 Eversong Woods, Copper Vein, spawn 32
.go xyz 8522.32 -7738.49 123.011 530 -- 74962 Eversong Woods, Copper Vein, spawn 33
.go xyz 8864.79 -7776.76 172.942 530 -- 74963 Eversong Woods, Copper Vein, spawn 34
.go xyz 9709.15 -7925.85 9.3747 530 -- 74964 Eversong Woods, Copper Vein, spawn 35
.go xyz 9595.45 -7797.68 41.8183 530 -- 74965 Eversong Woods, Copper Vein, spawn 36
.go xyz 9258.71 -6442.46 18.3215 530 -- 74966 Eversong Woods, Copper Vein, spawn 37
.go xyz 9270.79 -6399.6 9.563 530 -- 74967 Eversong Woods, Copper Vein, spawn 38
.go xyz 9227.42 -6113.97 45.0611 530 -- 74968 Eversong Woods, Copper Vein, spawn 39
.go xyz 8915.39 -6179.36 7.73462 530 -- 74969 Eversong Woods, Copper Vein, spawn 40
.go xyz 9018.65 -5971.72 12.7394 530 -- 74970 Eversong Woods, Copper Vein, spawn 41
.go xyz 8999.2 -5967.17 13.0295 530 -- 74971 Eversong Woods, Copper Vein, spawn 42
.go xyz 8933.25 -6974.55 21.7225 530 -- 74972 Eversong Woods, Copper Vein, spawn 43
.go xyz 8923.4 -6822.55 54.7797 530 -- 74973 Eversong Woods, Copper Vein, spawn 44
.go xyz 8796.62 -6693.31 56.7484 530 -- 74974 Eversong Woods, Copper Vein, spawn 45
.go xyz 8265.85 -7446.72 175.822 530 -- 74975 Eversong Woods, Copper Vein, spawn 46
.go xyz 8338.62 -7384.13 210.359 530 -- 74976 Eversong Woods, Copper Vein, spawn 47
.go xyz 8640.4 -7137.19 86.2068 530 -- 74977 Eversong Woods, Copper Vein, spawn 48
.go xyz 8757.04 -7205.74 56.7255 530 -- 74978 Eversong Woods, Copper Vein, spawn 49
.go xyz 8350.22 -6638.37 114.945 530 -- 74979 Eversong Woods, Copper Vein, spawn 50
.go xyz 8391.14 -6303.74 128.429 530 -- 74980 Eversong Woods, Copper Vein, spawn 51
.go xyz 8697.75 -6217.64 35.9229 530 -- 74981 Eversong Woods, Copper Vein, spawn 52
.go xyz 8616.06 -6041.67 57.8267 530 -- 74982 Eversong Woods, Copper Vein, spawn 53
.go xyz 8698.23 -6041.53 19.0908 530 -- 74983 Eversong Woods, Copper Vein, spawn 54
.go xyz 8435.37 -5754.15 26.823 530 -- 74984 Eversong Woods, Copper Vein, spawn 55
.go xyz 8757.86 -6306.09 57.1405 530 -- 74985 Eversong Woods, Copper Vein, spawn 56
.go xyz 8923.64 -6579.72 40.4971 530 -- 74986 Eversong Woods, Copper Vein, spawn 57
.go xyz 9157.8 -6194.33 28.8475 530 -- 74987 Eversong Woods, Copper Vein, spawn 58
.go xyz 8764.94 -7016 40.6887 530 -- 120618 Eversong Woods, Copper Vein, spawn 59
```

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Stifler82 — CHANGES_REQUESTED** [review]
@Zoidwaffle
Tested, works perfect, excellent spawn points.
But you have only to change this:
```
INSERT INTO `pool_template` (`entry`,`max_limit`,`description`) VALUES
(11644,20,"Copper Vein - Eversong Woods");
```
to this:
```
INSERT INTO `pool_template` (`entry`,`max_limit`,`description`) VALUES
(11644,30,"Copper Vein - Eversong Woods");
```
**this screen is with the change set to 30 instead of 20**

WoWScrnShot_022321_200606

**Comment by Zoidwaffle** [comment]
@Stifler82 - I changed from 20->30.

**Review by Stifler82 — APPROVED** [review]
Perfect!

**Comment by Stifler82** [comment]
@FrancescoBorzi 
@Helias

**Review by Helias — APPROVED** [review]

**Pull request merged**
