### PR TITLE
fix(Scripts/AhnQiraj): Spawn 3 crystals at start.

### LINKED ISSUE #12762: [AQ20] Ossirian - Number of crystals that can be up simultaneously is too low.
### Current Behaviour

Only 1 crystal can be up at a time, excluding the initial crystal.

### Expected Blizzlike Behaviour

A matter of debate:
 - Retail has 6.
 - Comments from Wowhead claim at least 5 in 4.0.3
 - WotLK footage shows at least 3

### Source

https://youtu.be/4ekKACUEMAE?t=141 shows 3.

there are few of them in the area (5+) ([source](https://www.wowhead.com/object=180619/ossirian-crystal#comments:id=1374817) Patch 4.0.3)

This is the scouting mechanic, that by using the crystals along the sides of the arena it forces them to spawn using the 3 spawn points in the center
>this will almost guarantee all three crystals being ready constantly in the center of the map. ([source](https://wowwiki-archive.fandom.com/wiki/Ossirian_the_Unscarred))

### Steps to reproduce the problem

1. `.go xyz -9397 1947 87 509 2.5`
2. Engage Ossirian.
3. Count the crystals that spawned. Ignore the crystal that was already present there.
4. See if using one respawns another somewhere else so that the number of crystal up simultaneously is always constant.

### Extra Notes

Keep in mind that:

1. One crystal in particular (the one that is already present before the boss is engaged) **is completely separate from this issue** and is supposed to have a different behaviour from the rest of them.
2. There are 11 spawn points that they can spawn from. Several of them are obscured by pillars so they cannot be seen if the player does not move.
3. Mechanics change in-between expansions. For example: Cataclysm decreased Razorgore MC debuff from 60s to 10s.

More info here: https://github.com/azerothcore/azerothcore-wotlk/issues/12472

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/b2e449fd15e38b4778a42650f388b8213cf62a6a

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12762

## Issues Addressed:

- Closes #12762

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go xyz -9397 1947 87 509 2.5`
Engage Ossirian.
Count the crystals that spawned. Ignore the crystal that was already present there.
See if using one respawns another somewhere else so that the number of crystal up simultaneously is always constant.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Only one of the three crystals can spawn another one when used. All of them should spawn another on use, so that there's always 3 available at all times.

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Maelthyrr** [comment]
Now, 3 crystal spawn at start. But I'm not sure, after this only one crystal should spawn ? Because if I activate quickly 3 crystal after pulling the boss, I got sometime 2 or 3 new crystals. As if we got a respawn for each crystal activate.

**Comment by UltraNix** [comment]
@Gultask ??

**Comment by Gultask** [comment]
That is the intended effect. Every activation should spawn another crystal, so that there is always a certain number of them up at all times.
Sorry my internet is down and I can't test it myself for now.

**Comment by UltraNix** [comment]
So it's okay.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
