### PR TITLE
fix(Core/Movement): Rewritten follow movement generator for pets.

### LINKED ISSUE #7296: Pets Not Aligning With Owner
### What client do you play on?

enUS

### Faction

- [x] Alliance
- [X] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1376

Pets is behind owner if stop moving.
WoWScrnShot_081121_080207

Tester: confirmed. This is an issue that's been around for a while - see discussion at https://github.com/TrinityCore/TrinityCore/issues/21237, where there is extended discussion on this issue, though with the codebases diverging over time, not sure how much is still relevant now. However, one comment (https://github.com/TrinityCore/TrinityCore/issues/21237#issuecomment-555791434) does give links to yet another emulator project where this issue has apparently been fixed. 

### Expected Blizzlike Behaviour

on one line with owner

### Source
Some clips of normal hunter/pet movement, showing that the pet should be abreast of its owner/
https://youtu.be/WabuFT3N2IE?t=8m17s
https://www.youtube.com/watch?v=NOnbH6I7sSQ&t=3710s

### Steps to reproduce the problem

have pet

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/36a1777b99c400484537c358af8fa6b3a42b13c7

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #7296

## Changes Proposed:
-  Properly synchronize pet's position with its owner.

## Issues Addressed:

- Closes #7296
- Closes https://github.com/chromiecraft/chromiecraft/issues/1376

## Tests Performed:

- Tested ingame

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/7296)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by lineagedr** [comment]
I just tested and the pet does not allign with owner.

AzerothCore Ultranix:PetFollow Test:
https://www.youtube.com/watch?v=nhWjIbGftYg

This is how it should look:

AzerothCore Blizzlike pet movement:
https://www.youtube.com/watch?v=xaXbaWYRIcU

Pet should calculate few steps ahead of owner and when owner stops the pet should return to owners pos.

**Comment by UltraNix** [comment]
Bug was about pets not allign on owner when stopped - that has been fixed altough.

**Comment by UltraNix** [comment]
@lineagedr Can you test it again?

**Comment by lineagedr** [comment]
@UltraNix It's the same.

**Comment by UltraNix** [comment]
So it's about something more.

**Comment by lineagedr** [comment]
@UltraNix But honestly if the bug was only for pet not aligning after owner has stopped there's no point in adding more.

**Comment by UltraNix** [comment]
@lineagedr Should be okay now.

**Comment by lineagedr** [comment]
@UltraNix It's going in the right direction. Few things to note:

1. After pet finishes movement pet should move to owner pos: https://www.youtube.com/watch?v=yeBKycc3lEg
Should be like: https://www.youtube.com/watch?v=xaXbaWYRIcU&t=5s

2. If you move to the side the pet doesn't align with owner: https://www.youtube.com/watch?v=FsJnPSNXqOU
Should be like: https://youtu.be/xaXbaWYRIcU?t=22
2.1 Even if you don't move to the side just keep moving and the owner will eventually outpace the pet.

3. The pet seems to be twitching: https://www.youtube.com/watch?v=pLpxZSe-mEM
Should be smooth like: https://youtu.be/xaXbaWYRIcU?t=9

4. This should be tested by someone who has latest mmaps / vmaps. Since pet is calculating few steps ahead of owner if a player keeps walking into a wall will the pet go into the wall? In my tests it went but I think it might be related to me not having vmaps/mmaps.

**Comment by FrancescoBorzi** [comment]
the build is failing

**Comment by UltraNix** [comment]
@lineagedr Please, retest it.

**Comment by lineagedr** [comment]
@UltraNix It's much better but there's weird movement glitches

https://user-images.githubusercontent.com/12139798/129795340-ae242889-25ad-4448-96ef-24a813bea963.mp4


https://user-images.githubusercontent.com/12139798/129795511-7f7812cb-9e49-4341-b40c-2789fed92959.mp4

If owner is slowed it shouldn't affect the pet movement speed

https://user-images.githubusercontent.com/12139798/129795816-405667f6-518b-4242-87d4-655624d5953b.mp4


Should be something like this:

https://user-images.githubusercontent.com/12139798/129796412-f5772934-9566-4e9d-937a-277ed0a74229.mp4

**Comment by lineagedr** [comment]
A - D are binded strafe left,right

W+A

https://user-images.githubusercontent.com/12139798/129797458-1320e0dd-875d-4b71-a333-ffbe6a17d986.mp4

How it should be:

W+A

https://user-images.githubusercontent.com/12139798/129797538-f9fe9991-ae8c-44d5-96e4-d5b010de3041.mp4

**Comment by lineagedr** [comment]
Same thing goes for temporary pets.

https://user-images.githubusercontent.com/12139798/129798319-945583f5-5cf2-4c57-9024-226d5527dce6.mp4

How it should be:

https://user-images.githubusercontent.com/12139798/129798036-ad91b1b1-3673-4fae-bd1e-84af2fe96fbe.mp4

**Comment by UltraNix** [comment]
@lineagedr Test it.
```
It's much better but there's weird movement glitches
```
It's because desynchro between pet's speed and spline length which is hard to calculate proeprly at that point - I will leave it as it is.

```
If owner is slowed it shouldn't affect the pet movement speed
```
If I recall correctly, if not in combat, pet should always inherit owner's speed.

**Comment by UltraNix** [comment]
@lineagedr Test it again.

```
It's much better but there's weird movement glitches
```
Yep - it's hard to calculate proper speed. I think I will leave as it is, unless I'll find better formula.

**Comment by lineagedr** [comment]
@UltraNix Pets still glitch out but I guess it's minor. Merge?

**Comment by UltraNix** [comment]
But it's better now?

**Comment by pklloveyou** [comment]
Pets give people a strange feeling. Sometimes they are stuck,

**Comment by UltraNix** [comment]
@pklloveyou Can you provide any video about this?

**Comment by pklloveyou** [comment]
Fortunately, it can be merged

**Comment by UltraNix** [comment]
Okay.

**Comment by pklloveyou** [comment]
When moving, the pet is "stuck" on the transport ship
It's difficult to translate the description. Can you try it
```
.go c 279
```
Summon pets and try to move after the transport starts

**Comment by UltraNix** [comment]
@pklloveyou I believe it's not related to that PR, but to transport system.

**Comment by Kitzunu** [comment]
closes https://github.com/azerothcore/azerothcore-wotlk/issues/2941 or no?

**Comment by UltraNix** [comment]
@Kitzunu Yes.

**Pull request merged**
