### PR TITLE
fix(DB/SAI): Theradrim Guardian

### PR DESCRIPTION
**Pull request by grimgravy**
## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/13372
- Closes https://github.com/chromiecraft/chromiecraft/issues/3904

## Tests Performed:

- Tested in game

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Thanks for your contribution but this can`t be accepted. There`s a SAI event for death

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
add in the scripted death scene that is done thru sai and the PR can be re-reviewed

**Comment by grimgravy** [comment]
> add in the scripted death scene that is done thru sai and the PR can be re-reviewed

it doesn't work, I already did that

**Comment by Gultask** [comment]
Try adding a cast flag for the spell to be triggered.

**Comment by acidmanifesto** [comment]
will need to be tested. Removing WIP tag i applied.

**Comment by Maelthyrr** [comment]
Tested and work fine. Thanks

**Review by Gultask — APPROVED** [review]

**Pull request merged**
