### PR TITLE
Core/Misc: Change how Position struct is retrieved

### PR DESCRIPTION
**Pull request by sschepens**
## Changes Proposed:
-  Porting TC https://github.com/TrinityCore/TrinityCore/commit/2585e799f95f259dd4b422daf15ef7963173c408
-  Simpler use of functions and more in line with TC, can help port more things later
- Depends on https://github.com/azerothcore/azerothcore-wotlk/pull/9016 being merged

## Issues Addressed:

- Closes 

## Tests Performed:

- Only buildng should be OK, code isn't changed
- 

## How to Test the Changes:

1. Only buildng should be OK, code isn't changed
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@sschepens please resolve conflicts

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by sschepens** [comment]
@Winfidonarleyan needs for https://github.com/azerothcore/azerothcore-wotlk/pull/9016 to be merged first

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan needs for #9016 to be merged first

I understand.

**Comment by Winfidonarleyan** [comment]
Need fix build

**Comment by sschepens** [comment]
@Winfidonarleyan yup I screwed up while rebasing, fixed.

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan yup I screwed up while rebasing, fixed.

okay, need wait build anyway

**Pull request merged**
