### PR TITLE
fix(Core\Spells):Commander Felstrom's rebirth spell should not trigger kill-effect because it can be looted endlessly

### PR DESCRIPTION
**Pull request by Ragelezz**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6129
- Closes https://github.com/chromiecraft/chromiecraft/issues/735

## Tests Performed:

- .go c id 771, bring him to low hp and let him cast Felstorm Ressurection, notice he can be looted
- 

## How to Test the Changes:

1. .go c id 771, bring him to low hp and let him cast Felstorm Ressurection, notice he cannot be looted anymore and his corpse will despawn
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Ragelezz please fix the merge conflicts. Let us know if you need help with it ;)

**Comment by Ragelezz** [comment]
@Nyeriah Any news on SPELL_EFFECT_INSTAKILL research for killcredit?

**Comment by Ragelezz** [comment]
Merge conflicts were fixed days ago, shall we merge it ? Already tested.

**Comment by Nyeriah** [comment]
The Feign Death hack is not acceptable. I have other suggestions to this:

1) Remove his loot table if the spell is cast (if he gets "revived")
2) Make him untargetable if he gets revived (still a hack, but better than hacking the spell dbc)

We could reset the "PlayerDamageRequired" value (or whatever was the name of that function) when he's hit by that spell, so when he kills himself the player will not get any credit (loot or XP). I think this is the closest to blizzlike we can get, and with this we achieve option 1)

**Pull request closed without merging**
