### PR TITLE
Added Hook for modules

### PR DESCRIPTION
**Pull request by talamortis**
**Changes proposed:**

-  Added hook
-  
-  

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc)
tested hook and is working

**Known issues and TODO list:**

- [  ]
- [ ] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Yehonal** [comment]
Please use "new standard" way to naming hook that is composed in this way:

On[Before/After][ActionName]

You should use "before" when it's placed Before that action, and After when it's placed  after the action itself.

In your case should be something like:

OnAfterScriptsLoading

also, what does it means: 

sLog->outString("Loading Modules..."); 

it doesn't load any module

**Comment by talamortis** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/754

**Comment by Yehonal** [comment]
Ok but please update hook name and can be merged

Il 30 Gen 2018 00:51, "Lee" <notifications@github.com> ha scritto:

**Comment by BarbzYHOOL** [comment]
@talamortis this never got merged?

**Pull request closed without merging**
