### PR TITLE
BREAKING CHANGE(Deps/Boost): Set 1.74 as minimum version

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
- Update minimum version to 1.74 to be able to proceed with C++20 build

## Tests Performed:

- Tested on windows, build can proceed and does not break on Boost being broken

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
we probably want to wait until the next Debian stable version is released, which will have 1.74 in the default Boost package version, as well as waiting until it is available on Ubuntu 20.04. Currently, in GitHub Actions there is 1.74 but not on a clean, standard Ubuntu 20.04.

**Comment by Kitzunu** [comment]
Status?

**Comment by FrancescoBorzi** [comment]
> Status?

still not available in ubuntu 20.04: https://packages.ubuntu.com/search?keywords=libboost&searchon=names

not sure if there are plans to port it

**Comment by Winfidonarleyan** [comment]
Can use this for `Ubuntu 20.04`
https://github.com/WarheadCore/WarheadBand/blob/42b2ee3d3dd241889b6ea3c4e44ce75c759d13e8/apps/installer/includes/os_configs/ubuntu.sh#L11

**Comment by Kitzunu** [comment]
@FrancescoBorzi @locus313

**Comment by locus313** [comment]
> Can use this for `Ubuntu 20.04` https://github.com/WarheadCore/WarheadBand/blob/42b2ee3d3dd241889b6ea3c4e44ce75c759d13e8/apps/installer/includes/os_configs/ubuntu.sh#L11

That requires adding a 3rd party repo, which I don't think we should do. If I remember correctly the `add-apt-repository` command is not installed by default with ubuntu minimal installs that most vps/cloud providers use. So I don't really think we should up the min version yet.

**Comment by FrancescoBorzi** [comment]
exactly, currently it's only available in ubuntu 21.04 or higher:

https://packages.ubuntu.com/search?keywords=libboost1.74-dev

we need to wait for a backport to 20.04, if there will even be there one

**Comment by LordArcanine** [comment]
this will be a problem for debian 10 users like me...

**Comment by FrancescoBorzi** [comment]
I'd say let's reopen this when it's time, no need to keep it hanging as it's a small change.

**Pull request closed without merging**
