### PR TITLE
fix(DB): Add sharks

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Adds the missing sharks in the oceans and their pathing
-  All values from Vmangos
-  There previously was one shark in the world but it had no pathing. This updates it with correct position and pathing as well.

## Issues Addressed:

- Closes unreported issue

## Tests Performed:

- Sharks are present

## How to Test the Changes:

1. .go to sharks, see they are present and moving looks okay

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]
Baby Shark Do do do do do.

**Comment by Gultask** [comment]
`Duplicate entry '19769500-1' for key 'waypoint_data.PRIMARY'`

**Comment by ZhengPeiRu21** [comment]
> `Duplicate entry '19769500-1' for key 'waypoint_data.PRIMARY'`
> 
> Other than that it's all good :)
> 
> Movement is a bit weird but it's a map issue, making them 'stick' to the ocean floor instead of swimming.

Thank you for your testing! I've fixed the SQL mistake that should resolve the error when re-run it.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
