### PR TITLE
fix(DB/scripts): Freya - Sun beam

### PR DESCRIPTION
**Pull request by Si1ker**
Fix for my original PR #3587 

==========
These changes will fix the Sun beam event on 25-man raid and place the correct models into the dummies which are triggering the spell.

In the current Freya event at AC, Freya is summoning just 1 sun beam for 10 and 25 mode, which is wrong, this needs to be 1 for 10-man mode and 3 for 25-man mode.

Reference: https://www.youtube.com/watch?v=7wxv88pA3Ew  (3:08)

## CHANGES PROPOSED:
-  Fix models on dummies which are triggering the spell
-  Add to more summons on 25-man raid

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Tested in-game
image

## HOW TO TEST THE CHANGES:

Change raid mode to 25-man
.go c Freya
Engage combat and wait for the three Sun Beams positions

## KNOWN ISSUES AND TODO LIST:

- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by iyasenai** [comment]
Works correctly, watch the video :)
https://www.youtube.com/watch?v=drlGJksIb4E

**Comment by FrancescoBorzi** [comment]
good job @Si1ker and thanks @iyasenai for testing!

**Comment by FrancescoBorzi** [comment]
@Si1ker build broken on master after this merge :(

**Comment by FrancescoBorzi** [comment]
Fix: https://github.com/azerothcore/azerothcore-wotlk/pull/3746

**Pull request merged**
