### PR TITLE
fix(DB/Quest): Suntara Stones escort quest

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6735
- Closes https://github.com/chromiecraft/chromiecraft/issues/1090

## Tests Performed:

- Tested
- Arch Linux

## How to Test the Changes:

1. Teleport to GUID 6823 and accept the quest
2. Escort Dorius and observe him

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by syssneck** [comment]
Good script!
I noticed two small things:
- He is not pointing at the Cauldron. He is kneeling and pointing in the wrong direction, when he says: "This is the place, ..."
- he started running the last bit (as he should) but we fought a spider and when he went back to his route, he had the running speed, but his walking animation

**Comment by IntelligentQuantum** [comment]
> Good script!
> I noticed two small things:
> 
>     * He is not pointing at the Cauldron. He is kneeling and pointing in the wrong direction, when he says: "This is the place, ..."
> 
>     * he started running the last bit (as he should) but we fought a spider and when he went back to his route, he had the running speed, but his walking animation

I will test it again tomorrow.
tnx for test

**Comment by Helias** [comment]
build fails for
`SmartAIMgr: EntryOrGuid 14751700 using event(0) has an action type that is not yet supported on AzerothCore (118), skipped.`

**Comment by IntelligentQuantum** [comment]
>     * He is not pointing at the Cauldron. He is kneeling and pointing in the wrong direction, when he says: "This is the place, ..."

@syssneck  Can you take a screenshot or video ? I tried it was right.

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
