### PR TITLE
Core/Scripts: Fixed Mimiron's Spinning Up + proper timers (wowwiki)

### LINKED ISSUE #1611: [Ulduar] Spinning Up Mimiron P4  [$90]
[Ulduar] Spinning Up Mimiron P4 

##### SMALL DESCRIPTION:
Mimiron Spinning up spell in P4 doesn't work

##### EXPECTED BLIZZLIKE BEHAVIOUR:
When Mimiron arrive in P4 , the VX-001 have to use the spell Spinning-Up like in the P2

##### CURRENT BEHAVIOUR:
Actually , VX-001 use the Spinning up only on P2 and not on P4 , and if we uncomment this line : https://github.com/azerothcore/azerothcore-wotlk/blob/03bfbf4f7e43f6b8064e6846e0bf2503958c17bc/src/server/scripts/Northrend/Ulduar/Ulduar/boss_mimiron.cpp#L1376 , VX-001 use the spell , but visual is not correct with damage done by the spell ...

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Enter Ulduar 10 or 25 players
2. Travel to Mimiron and engage him
3. See the VX-001 P2 is correct but not in P4

##### BRANCH(ES):

master

##### OPERATING SYSTEM: Debian 9

<bountysource-plugin>

---
There is a **[$90 open bounty](https://www.bountysource.com/issues/71801325-ulduar-spinning-up-mimiron-p4?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by FALL1N1**
## CHANGES PROPOSED:
-  Blizzlike timers (as of wowwiki) for the spinning up event.
-  Proper check for the spinning up position so there's no delay.

## ISSUES ADDRESSED:
- Closes #1611

## TESTS PERFORMED:
- Take him in P2 - check if the position of the laser beam is accurate
- Take him in P4 - check if the position of the laser beam is accurate

## HOW TO TEST THE CHANGES:

- Take him in P2 - check if the position of the laser beam is accurate
- Take him in P4 - check if the position of the laser beam is accurate

## KNOWN ISSUES AND TODO LIST:

- None

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Helias** [comment]
We need testers for this, this is an important PR, very good job :+1:

**Comment by aradep** [comment]
Encountering some bugs. In phase 2 he snaps toward the same orientation every time, and in phase 4 the orientation doesnt really change
[phase 2 ](https://www.youtube.com/watch?v=8AN_zUSR3v8)
[phase 4](https://www.youtube.com/watch?v=TipOUH6CnAc)

**Comment by FALL1N1** [comment]
@aradep thank you for the test, I will re-check it.

**Review by Si1ker — APPROVED** [review]
It's the way to go, still need to address bugs based on aradep's feedback. 👍

**Comment by FALL1N1** [comment]
There will be a new PR with a complete overhaul for Mimiron hence I am closing this one.

There are more issues with him so it's for the better.

**Pull request closed without merging**
