### PR TITLE
fix(Build/Windows): For OS locales like CJK

### PR DESCRIPTION
**Pull request by vconcat**
Fix compile error under Windows with locale CJK(like codepage cp936).

Because `authserver/Main.cpp` and `worldserver/Master.cpp` contains non-ASCII(Unicode?) characters.

## Changes Proposed:
-  
-  

## Issues Addressed:
- related to #3370 

### Before:
**Success to build by re-saving `authserver/Main.cpp` and `worldserver/Master.cpp` with BOM as Visual Studio recommended.**
```
AzerothCore rev. 60f02f86d6c9+ 2021-03-18 22:24:58 +0000 (master branch) (Win64, Release) (authserver)
<Ctrl-C> to stop.

An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
An error occurred converting string from UTF-8 to WStr
     AzerothCore 3.3.5a  -  www.azerothcore.org

Using configuration file configs/authserver.conf.
Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.5.5
MySQL server ver: 10.5.9-MariaDB
MySQL client library: 10.5.5
MySQL server ver: 10.5.9-MariaDB
DatabasePool 'acore_auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Updating Realm List...
Added realm "AzerothCore" at 127.0.0.1:8085.
Authserver listening to 0.0.0.0:3724
```

### After
**Without any changes to source codes**
```
AzerothCore rev. 60f02f86d6c9+ 2021-03-18 22:24:58 +0000 (master branch) (Win64, Release) (authserver)
<Ctrl-C> to stop.

   █████╗ ███████╗███████╗██████╗  ██████╗ ████████╗██╗  ██╗
  ██╔══██╗╚══███╔╝██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝██║  ██║
  ███████║  ███╔╝ █████╗  ██████╔╝██║   ██║   ██║   ███████║
  ██╔══██║ ███╔╝  ██╔══╝  ██╔══██╗██║   ██║   ██║   ██╔══██║
  ██║  ██║███████╗███████╗██║  ██║╚██████╔╝   ██║   ██║  ██║
  ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
                                ██████╗ ██████╗ ██████╗ ███████╗
                                ██╔════╝██╔═══██╗██╔══██╗██╔═══╝
                                ██║     ██║   ██║██████╔╝█████╗
                                ██║     ██║   ██║██╔══██╗██╔══╝
                                ╚██████╗╚██████╔╝██║  ██║███████╗
                                 ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

     AzerothCore 3.3.5a  -  www.azerothcore.org

Using configuration file configs/authserver.conf.
Opening DatabasePool 'acore_auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.5.5
MySQL server ver: 10.5.9-MariaDB
MySQL client library: 10.5.5
MySQL server ver: 10.5.9-MariaDB
DatabasePool 'acore_auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Updating Realm List...
Added realm "AzerothCore" at 127.0.0.1:8085.
Authserver listening to 0.0.0.0:3724
```

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
https://github.com/TrinityCore/TrinityCore/pull/24572

**Comment by vconcat** [comment]
OH, I did not known this before.
But this works for me, and the logo show in console also looks correct.

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan can this be accepted or requires changes?

**Comment by Winfidonarleyan** [comment]
I think yes

**Review by Winfidonarleyan — APPROVED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
