### PR TITLE
Fix Lady Deathwhisper intro

### PR DESCRIPTION
**Pull request by Nefertumm**
When you are at Lord Marrowgar entrance and he starts his intro, Lady
starts her intro too. With this fix, that is fixed.

**Changes proposed:**

-  Use DoAction + AreaTriggerScript instead MoveInLOS for intro.

**Target branch(es):** master

**Issues addressed:** -

**Tests performed:** Build and tested in game.

**Known issues and TODO list:** -

### CODE REVIEW

**Comment by Motorheadx** [comment]
it does not work has been checked, event speech does not start now at all

**Comment by Nefertumm** [comment]
Make sure that you are not testing with gm on.

**Comment by Motorheadx** [comment]
I'm sorry, my mistake

**Comment by Kaev** [comment]
@Motorheadx Did it work properly?

**Comment by Motorheadx** [comment]
like normally works

**Comment by BarbzYHOOL** [comment]
Ok, thank you motorheadx and of course, thank you @Nefertumm

**Comment by BarbzYHOOL** [comment]
? @pklloveyou

**Pull request merged**
