### PR TITLE
fix(Scripts/BlackTemple): Flames of Azzinoth - Fix the charge logic

### PR DESCRIPTION
**Pull request by Grimdhex**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

* fix the distance logic (negative usage imply "at least")
* remove also a old duplicate check in a spell script

## Issues Addressed:

- Closes totally https://github.com/azerothcore/azerothcore-wotlk/issues/19954 and https://github.com/chromiecraft/chromiecraft/issues/7351#issue-2513928203

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Pull boss
2. Get to phase 2

## Known Issues and TODO List:

- [ ] I've not enough informations about the delay between two charges on differents players. So the behavior could be not fully blizzlike.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by PkllonG** [comment]
Tested

**Comment by Grimdhex** [comment]
I was thinking about it, and I don't know if it's a way out or not. It's possible for a player to be charged if he's close to a flame of azzinoth but more than 40y away from the other. As during their spawn, we use SetInCombatZone.

**Comment by Helias** [comment]
if you are not sure you could ask more feedback in the issues
@Rorschach91 ?

**Comment by Rorschach91** [comment]
Mmmh.... I think that It could be possible. One thing that I noted watching boss fight videos is that tanks never move a Flame of Azzinoth too far away from the other. Probably because they don't want that the other Flame jump on a melee that it is doing damage to the other flame at that moment.

So, yes. One of them can charge a player that It's fighting the other Flame of Azzinoth if that player is more than 40 yard away.
Rember that who has a Flame of Azzinoth in aggro could never be charged.

**Comment by Grimdhex** [comment]
>  Rember that who has a Flame of Azzinoth in aggro could never be charged.

Even by the other Flame ? Because SelectTarget method can exclude the current target but the target/tank from the other flame it doesn't do the difference with another player as threat lists are individuals.

**Comment by Rorschach91** [comment]
> > Rember that who has a Flame of Azzinoth in aggro could never be charged.
> 
> Even by the other Flame ? Because SelectTarget method can exclude the current target but the target/tank from the other flame it doesn't do the difference with another player as threat lists are individuals.

I may have misinterpreted what I saw. For that part I forgot to say that I'm not 100% sure about this thing, sorry.

**Comment by Grimdhex** [comment]
> > > Rember that who has a Flame of Azzinoth in aggro could never be charged.
> > 
> > 
> > Even by the other Flame ? Because SelectTarget method can exclude the current target but the target/tank from the other flame it doesn't do the difference with another player as threat lists are individuals.
> 
> I may have misinterpreted what I saw. For that part I forgot to say that I'm not 100% sure about this thing, sorry.

It's fine. I know you can't know everything. I think that we can let like this, and if there a new report about it, I will try to find another way.

**Pull request merged**
