### PR TITLE
feat(Core/DB): Add Creature ExperienceModifier 

### LINKED ISSUE #5469: Add Creature_template Experience Modifier column [$10]
## CURRENT BEHAVIOUR:

This column and setting is currently missing from AC.
All creatures use predefined hardcoded xp in core.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Each creature should have its own experience multiplier defined in the database.

## SOURCE:

Blizzard's creature tool from 2009.
image

Also it can be seen on classic, bosses have higher XP rates than elites 
Example : In this video, trash elites give about 220xp per player
At the end, Archaedas gives 739xp.
https://www.youtube.com/watch?v=GHsytWhHKNA

Currently even TC has an experience modifier column

## STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

## AC HASH/COMMIT:
512fe7df0ab89ce553a00a6cfacee632f0b76926

## CUSTOMIZATIONS:

<bountysource-plugin>

---
There is a **[$10 open bounty](https://www.bountysource.com/issues/98101604-add-creature_template-experience-modifier-column?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Krejza9**
## Changes Proposed:
-  Add support for ExperienceModifier for specific creatures

## Issues Addressed:

- Closes #5469 

## SOURCE:

TC

## Tests Performed:

- test in-game

## How to Test the Changes:

1. Kill the creature
2. Write down the XP you get for it.
3. Change the ExperienceModifier value in the creature_template table for the same creature.
4. The result will be multiplied by the given value

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Krejza9** [comment]
Some pictures from the PR test

base XP from killing creatures
WoWScrnShot_072421_101542

after  ExperienceModifier set to 10
WoWScrnShot_072421_101309

**Comment by Kitzunu** [comment]
Good job, I will review tonight 😊

**Comment by pklloveyou** [comment]
Tested

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
@Kitzunu for me it's to be merged

**Review by Kitzunu — APPROVED** [review]

**Comment by T1ti** [comment]
Good job, should this PR also include data for it ? 
Port all the columns that aren't *1 from TC

**Comment by Kitzunu** [comment]
creature_template
---
```sql
SELECT * FROM creature_template WHERE ExperienceModifier <> 1
```
| entry | difficulty_entry_1 | difficulty_entry_2 | difficulty_entry_3 | KillCredit1 | KillCredit2 | modelid1 | modelid2 | modelid3 | modelid4 | name | subname | IconName | gossip_menu_id | minlevel | maxlevel | exp | faction | npcflag | speed_walk | speed_run | scale | rank | dmgschool | BaseAttackTime | RangeAttackTime | BaseVariance | RangeVariance | unit_class | unit_flags | unit_flags2 | dynamicflags | family | type | type_flags | lootid | pickpocketloot | skinloot | PetSpellDataId | VehicleId | mingold | maxgold | AIName | MovementType | HoverHeight | HealthModifier | ManaModifier | ArmorModifier | DamageModifier | ExperienceModifier | RacialLeader | movementId | RegenHealth | mechanic_immune_mask | spell_school_immune_mask | flags_extra | ScriptName | VerifiedBuild | 
| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: | 
| 10925 | 0 | 0 | 0 | 0 | 0 | 11009 | 0 | 0 | 0 | Rotting Worm | \0 | \0 | 0 | 50 | 50 | 0 | 21 | 0 | 1 | 1,14286 | 0,4 | 0 | 0 | 2000 | 2000 | 1 | 1 | 1 | 32768 | 2048 | 0 | 42 | 10 | 65537 | 0 | 0 | 0 | 0 | 0 | 71 | 98 |  | 1 | 1 | 0,001 | 1 | 1 | 0,5 | 0,005 | 0 | 0 | 1 | 0 | 0 | 64 |  | 12340 | 

Only one, so it can definitely be included

**Comment by T1ti** [comment]
Lol. I'll check if vmangos/cmangos have better data

**Comment by Krejza9** [comment]
On vmangos there is 372 record I can use them

**Comment by Krejza9** [comment]
@Kitzunu btw value 0.005 on TC doesn't make sense

**Comment by Kitzunu** [comment]
It does if you want the creature to give less XP :D

**Comment by Krejza9** [comment]
Yea but on 500xp it is 2.5XP :-D :-D

**Comment by Kitzunu** [comment]
Probably some small add that shouldnt give lots of xp

**Comment by Krejza9** [comment]
I looked on vmangos and it says pure 0 , so now who is right :(

**Comment by T1ti** [comment]
> I looked on vmangos and it says pure 0 , so now who is right :(

on AC 0 xp is usualy done through a flag

**Comment by Kitzunu** [comment]
Yes, no XP should use CREATURE_FLAG_EXTRA_NO_XP_AT_KILL

**Comment by Krejza9** [comment]
Ok , then I remove ExperienceModifier = 0 from SQL query and upload it.

**Comment by T1ti** [comment]
So from what i've seen in vmangos all dungeon bosses have x2 XP

From the footage I've seen on classic, normal bosses seem to have x2 XP but end bosses seem to have signficantly higher XP, like x3 ?

with player lvl 43:

lvl 40 boss gives 237xp
lvl 44 elite trash gives 200xp
lvl 45 boss gives 339 xp
Archaedas(end boss) is lvl 47 and gives 739 xp

**Comment by Krejza9** [comment]
Looks like they got it on Vmangos.
You also need to pay attention to the rest XP modifier when examining it is 200% at maximum rest.

**Comment by Kitzunu** [comment]
Isnt boss xp multiplier set in Core too?

**Comment by Krejza9** [comment]
@Kitzunu depending on whether the boss counts as Elite
then it's
`            if (creature->isElite())
            {
                // Elites in instances have a 2.75x XP bonus instead of the regular 2x world bonus.
                if (unit->GetMap() && unit->GetMap()->IsDungeon())
                    xpMod *= 2.75f;
                else
                    xpMod *= 2.0f;
            }`
If it doesn't count as elite , it follows the standard calculation like a normal creep

**Comment by T1ti** [comment]
> Isnt boss xp multiplier set in Core too?

the calculations is hardcoded in core yes, elite XP is also auto calculated

Those bosses have obviously higher XP than regular elite xp

**Comment by T1ti** [comment]
I have done additional research, I can confirm based on soloing videos that normal dungeon bosses have x2 xp multiplier so vmangos is correct for that

BUT I have found out that final dungeon bosses have x2.8 xp !

**Comment by FrancescoBorzi** [comment]
I think we can separate the contents from the feature itself. The feature can be merged already and we can open more PRs later to make it better and better.

**Pull request merged**
