### PR TITLE
Fixed annoying client crash with some stealth auras.

### PR DESCRIPTION
**Pull request by FALL1N1**
For example go to STV(Stranglethorn Vale) and pull the stealth panthers, after couple seconds your game will crash.

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
I tried the panthers two days ago and found 0 bug, I could kill them all. I had read the bug about Sunwell but couldn't reproduce on AC

**Comment by Dreaxxx** [comment]
SAame like Barbz , haven't got any problem with the panther in STV with my client

**Comment by Stoabrogga** [comment]
Is this the NPC? https://wowgaming.altervista.org/aowow/?npc=684
If so I had no issues while killing them for quest https://wowgaming.altervista.org/aowow/?quest=192.

**Comment by Stoabrogga** [comment]
Sorry, but I cannot reproduce the issue. Tested with a level 37 character and killed 5 of the panthers without crashing.

**Comment by FALL1N1** [comment]
basically it's a TC merge so everything should be good

**Comment by BarbzYHOOL** [comment]
> it's a TC merge so everything should be good

blasphemy

northcraft applied this to the letter

**Comment by poszer** [comment]
I cannot reproduce this issue. Tried everything mentioned for test purpose, but without crash.

**Comment by BarbzYHOOL** [comment]
Ok, we will reopen this PR if needed. Thank you @FALL1N1 (I let it open so we had enough tests to avoid wasting your work, but it's not relevant to our core apparently)

Thank you @poszer @Dreaxxx @Viste @Stoabrogga for testing original issue

**Pull request closed without merging**
