### PR TITLE
Fix typo in `wp show` command description.

### PR DESCRIPTION
**Pull request by Irishsmurf**
`s/$slected_waypoint/$selected_waypoint`

## Changes Proposed:
-  Fix a typo in a command description/example.

## Issues Addressed:

- N/A

## Tests Performed:

- It builds.
- It changes a string.

## How to Test the Changes:

1. Run the .wp show command, and observe that the help text no longer contains a typo.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by heyitsbench — APPROVED** [review]

**Comment by heyitsbench** [comment]
While I do approve of the intended change, the actual [change to DB entries is done through updates, not by modifying the base queries](https://www.azerothcore.org/wiki/how-to-create-a-db-pr).

**Comment by Irishsmurf** [comment]
Thanks for the pointer!
I've added a SQL command which updates the string.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Nyeriah** [comment]
SQL codestyle needs to be fixed

**Review by Nyeriah — CHANGES_REQUESTED** [review]
SQL codestyle

**Comment by FrancescoBorzi** [comment]
@Irishsmurf thanks for your contributions

@IntelligentQuantum @heyitsbench thanks for reviewing this PR but please don't forget updating the workflow labels so the PR is not forgotten

**Comment by heyitsbench** [comment]
> heyitsbench thanks for reviewing this PR but please don't forget updating the workflow labels so the PR is not forgotten

I am not a maintainer, my PR reviews mean nothing.

**Comment by FrancescoBorzi** [comment]
> I am not a maintainer, my PR reviews mean nothing.

everyone is welcome to review PRs and properly updating labels is part of it ;)

**Comment by Irishsmurf** [comment]
@Nyeriah is there anything else required here to close this out?

**Pull request merged**
