### PR TITLE
[Database] Floating Corpse DK Starting/Scarlet Infantryman missing weapons

### PR DESCRIPTION
**Pull request by Kizarr**
**Changes proposed:**

-  Fix Scarlet Infantryman missing weapons
-  Fix floating corpse event.  

**Credits**

@Aokromes and @Rushor

**Target branch(es):** 1.x/2.x etc.
Master

**Issues addressed:** Closes #
Closes  https://github.com/TrinityCore/TrinityCore/issues/6631 on trinitycore

**Tests performed:** (Does it build, tested in-game, etc)
Builds and tested.

**Known issues and TODO list:**
- [ None]

### CODE REVIEW

**Comment by ShinDarth** [comment]
Thanks for submitting the PR!

However the SQL files need to be versioned, please read this page and update your PR:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files

**Comment by Kizarr** [comment]
@ShinDarth I will update this later today thank you.

**Comment by falzard** [comment]
why closed

**Comment by Yehonal** [comment]
Even if need improvements and some fixes are already presents
there are a lot of queries that are still valid

So i've reopened it

**Comment by Yehonal** [comment]
Available in staging-branch and demo server

**Pull request merged**
