### PR TITLE
refactor(Core/Spell): remove spell_cooldown_overrides and move it to …

### PR DESCRIPTION
**Pull request by Kitzunu**
…SpellInfoCorrections

* Remove spell_cooldown_overrides and move to SpellInfoCorrections to keep it all in one place.

* cherry-pick https://github.com/azerothcore/azerothcore-wotlk/pull/19153 into this

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
If approved, at merge add this to the commit message
```
Co-authored-by: avarishd <46330494+avarishd@users.noreply.github.com>
```
because I forgot in commit

**Comment by Nyeriah** [comment]
If anyone has more information on this it would be greatly appreciated. 

What we have here is that charmed creature spells have no cooldowns, so the table previously added cooldowns to the spells when they were charmed by players only.

It is unclear to me if those spells should have cooldowns when cast by creatures and/or players, outside being charmed/controlled.

The DBC has no data on cooldown/recovery time for those spells, as with most creature spells.

With this PR cooldown will be applied indiscriminately wether cast by a creature or player, despite the charmed status. 
If creatures use AI with repeat timers lower than the cooldown, those scripts will have issues.

**Comment by heyitsbench** [comment]
To my understanding, the way cooldowns work for creatures and their spells follows like this:
A creature has a spell list (can be seen [here](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/cb003512-d596-4576-a18e-412c02b35aeb) and [here](https://github.com/azerothcore/azerothcore-wotlk/assets/38561765/568cdba2-269b-4894-8b74-b8a3a049f566)). That is used for its general combat AI, and when charmed, the cooldown is determined by this spell list.

For example, an uncharmed [Defias Pillager](https://www.wowhead.com/wotlk/npc=589) casts [Fireball](https://www.wowhead.com/wotlk/spell=20793/fireball). Upon casting, it then gets a cooldown for when it will cast next, say min is 10s, max is 20s, and it rolls a 14s cooldown. It then can't use that spell for 14s (not necessarily that it will cast in 14s, just that it is a cooldown). It works pretty much the same way when the creature is charmed, so the pillager while charmed is commanded to cast fireball, and it rolls a 16s cooldown, that means the creature cannot be commanded to cast fireball again for 16s.

As for what these cooldowns would be if the player character itself cast these spells with no cooldown, that we cannot know unless something goes quite wrong on Blizzard's end.

**Comment by Nyeriah** [comment]
Is there any source of this dynamic handling?

**Comment by avarishd** [comment]
[Scarshield Spellbinder](https://www.wowhead.com/classic/npc=9098/scarshield-spellbinder) with [Resist Fire](https://www.wowhead.com/classic/spell=15123/resist-fire)
22 -> 34
https://youtu.be/vzgXkmBkTsc?t=60

**Comment by heyitsbench** [comment]
> Is there any source of this dynamic handling?

It is behavior I've seen myself across various mobs on Wrath Classic, the belief that it's directly tied to the uncharmed combat AI stems from a discussion I had in the VMaNGOS Discord.

**Comment by Nyeriah** [comment]
Okay, well, then, in that case it would be better to keep the table and add the spell timers mirroring the ones used in the AI. Then you can fix this issue properly

**Comment by avarishd** [comment]
Another column of "TimerStepUp" Perhaps?

**Comment by Kitzunu** [comment]
I agree with Nyeriah. But I propse to change the table name to properly say it is about npc ai spells ish

**Comment by Kitzunu** [comment]
I will close this @avarishd or @heyitsbench could one of you open an issue suggesting changes to this table to allow the dynamic shit?

**Pull request closed without merging**
