### PR TITLE
fix(DB/Creature): Correct Rep for Heroic Nexus Terror

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Fix rep value for Nexus Terror on Heroic

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15799
- Closes https://github.com/chromiecraft/chromiecraft/issues/5328

## SOURCE:

See original issue

## Tests Performed:

- SQL runs successfully

## How to Test the Changes:

1. Kill Nexus Terror in Heroic difficulty, confirm correct rep

## Known Issues and TODO List:

- We may want to double-check retail values to confirm this is correct rep value.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
my man is fast. looks good!

**Comment by elthehablo** [comment]
tested. works!

**Comment by Gultask** [comment]
This is wrong. The actual value is 22.5 It alternates (perfectly in my experience) between 22 and 23.

I had assumed this was supported by AC, but now that I checked it seems that all reputation are int values.

**Comment by ZhengPeiRu21** [comment]
> This is wrong. The actual value is 22.5 It alternates (perfectly in my experience) between 22 and 23.
> 
> I had assumed this was supported by AC, but now that I checked it seems that all reputation are int values.

Thank you for checking. If I have time in the next few days, I will try adding float support to the core for reputation values.

**Comment by ZhengPeiRu21** [comment]
This can be merged once https://github.com/azerothcore/azerothcore-wotlk/pull/15818 is merged.

**Review by Gultask — APPROVED** [review]

**Pull request merged**
