### PR TITLE
Fix(Core/Ulduar): Fixed the Stone Nova stacking issue in 25man mode

### LINKED ISSUE #3564: (Raid-Ulduar) Stone Nova does not stack.
##### CURRENT BEHAVIOUR:

In the combat against Kologarn in its 25 player mode, when one of his arms is destroyed, the npc Rubble ID: 33768 appears.
The problem is when these NPCs cast their Stone Nova ID: 63978 ability the debuff is not stacking if another Rubble applies the debuff.
WoWScrnShot_101020_184359

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Stone Nova has to stack despite another Rubble casting the ability.
https://www.youtube.com/watch?v=9bFX0kIarM0  (Min 1:55 -- 2:07) 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Ulduar 25.
2. .npc add 33768 (create at least 2)
3. Start combat and observe.

##### EXTRA NOTES:

In 10-player mode, Rubble NPCs do not cast this ability.
https://www.youtube.com/watch?v=RytKo-x9xNU

https://wotlkdb.com/?spell=63978
https://www.wowhead.com/spell=63978/stone-nova
https://www.wowhead.com/npc=33768/rubble
https://wotlkdb.com/?npc=33768

##### AC HASH/COMMIT:

91f4671

##### OPERATING SYSTEM:

Windows 10

##### MODULES:

--

##### OTHER CUSTOMIZATIONS:

No.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/93380134-raid-ulduar-stone-nova-does-not-stack?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kubeeek**
## CHANGES PROPOSED:
-  Added spellID 63978 to the spells that should stack 

## ISSUES ADDRESSED:
- Closes #3564 

## TESTS PERFORMED:
- Tested at Linux. 
- Spawned two rubbles in the Ulduar 25man mode 
- Debuff were stacking properly from both Rubbles

## HOW TO TEST THE CHANGES:
As the author of #3564 wrote:
- Go to Ulduar 25.
- npc add 33768 (create at least 2)
- Start combat and observe.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by aradep** [comment]
Tested, works!  (Can you do the same to #3565?)
image

**Comment by kubeeek** [comment]
@aradep thank you for the testing. Yeah, I can. Though should I make another PR or include it here?

**Comment by aradep** [comment]
I think for clarity it'd be best to make another PR.

**Review by Si1ker — APPROVED** [review]

**Review by Si1ker — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Si1ker just be careful with naming please, this should not be `Core/Ulduar` but `Scripts/Ulduar` as scripts are not part of the core

**Comment by Si1ker** [comment]
@FrancescoBorzi  The change is in the spell manager, see the file changed for further reference.

**Comment by FrancescoBorzi** [comment]
oh, my bad then. Core is correct.

**Pull request merged**
