### PR TITLE
Fix config loading for ac-dev-server container

### PR DESCRIPTION
**Pull request by michaeldelago**
## Changes Proposed:
-  This properly moves things from `DOCKER_ETC_FOLDER` to `confDir`
-  originally broken with https://github.com/azerothcore/azerothcore-wotlk/commit/888a718cf349f47b2230fdac0484df3a570bb898

## Issues Addressed:
- Should hopefully close https://github.com/azerothcore/acore-docker/issues/12

## Tests Performed:
- I'm not exactly aware of the testing procedure for this, as I don't use acore-docker
- That said, the previous behavior has been replicated:
https://github.com/azerothcore/azerothcore-wotlk/blob/2420d19e54eef2df6e9d997f0582d5d485920ecd/apps/compiler/includes/functions.sh#L148-L150
- Open to suggestions

## How to Test the Changes:
1. Open to Suggestions

## Known Issues and TODO List:

- Test properly

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by michaeldelago** [comment]
@Yehonal, fingers crossed

**Comment by Yehonal** [comment]
Thanks! I'm going to test it right now. I just need to comment out this line in our docker-compose file:

```
     - ${DOCKER_VOL_ETC:-./env/docker/etc}:/azerothcore/env/dist/etc
``` 

To resemble the same situation we have in the acore-docker (where the configs, by default, are not injected from the host)

**Comment by Yehonal** [comment]
I'm having this error:

```
Generating confs...
grep: env/dist/etc/*.dockerdist: No such file or directory
Layered env/dist/etc/*.dockerdist onto env/dist/etc/*.dist
cp: cannot stat 'env/dist/etc/*.dist': No such file or directory
```

I think the problem is on the $base_conf. This should fix it:

```diff
index 16c515e33..3a6f4aad6 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -123,11 +123,11 @@ services:
       - ${DOCKER_WORLD_EXTERNAL_PORT:-8085}:8085
       - ${DOCKER_SOAP_EXTERNAL_PORT:-7878}:7878
     volumes:
-      - ${DOCKER_VOL_ROOT:-.}:/azerothcore:cached
+      # - ${DOCKER_VOL_ROOT:-.}:/azerothcore:cached
       # expose some dist folder outside allowing the host to use them
       - ${DOCKER_VOL_CONF:-./conf}:/azerothcore/conf
+          # the dist files should be always find inside the $confDir folder, that can be different by the DOCKER_ETC_FOLDER
+          distPath="$confDir/$base_conf.dist"
+          # if the dist file doesn't exists, it means we are not compiling that app
+          if [ ! -f "$distPath" ]; then
+            continue
+          fi
+
           # replace params in foo.conf.dist with params in foo.conf.dockerdist
-          conf_layer "$dockerdist" "$base_conf.dist" " # Copied from dockerdist"
+          conf_layer "$dockerdist" "$distPath" " # Copied from dockerdist"
 
           # Copy modified dist file to $confDir/$filename
           # Don't overwrite foo.conf if it already exists.
-          cp --no-clobber --verbose "$base_conf.dist" "$confDir/$filename"
+          cp --no-clobber --verbose "$distPath" "$confDir/$filename"
         done
       fi
```

**Comment by michaeldelago** [comment]
Applied your patch, and made a few consistency/clarity changes. Removing the volumes and running the indicated command worked for me, but you're more knowledgeable about testing this than I am.

**Comment by michaeldelago** [comment]
from your previous output, I'd be interested in seeing why 
```
grep: env/dist/etc/*.dockerdist: No such file or directory
```

didnt glob properly

**Comment by Yehonal** [comment]
> from your previous output, I'd be interested in seeing why
> 
> ```
> grep: env/dist/etc/*.dockerdist: No such file or directory
> ```
> 
> didnt glob properly

Ok so with your patch I have this result:

```
Generating confs...
Layered env/dist/etc/dbimport.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/dbimport.conf.dist
'/azerothcore/env/dist/bin/../etc/dbimport.conf.dist' -> '/azerothcore/env/dist/bin/../etc/dbimport.conf'
Done
```

And this is because I'm only compiling the dbimport only.

With all the apps enabled I get this instead:

```
Generating confs...
Layered env/dist/etc/authserver.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/authserver.conf.dist
'/azerothcore/env/dist/bin/../etc/authserver.conf.dist' -> '/azerothcore/env/dist/bin/../etc/authserver.conf'
Layered env/dist/etc/dbimport.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/dbimport.conf.dist
'/azerothcore/env/dist/bin/../etc/dbimport.conf.dist' -> '/azerothcore/env/dist/bin/../etc/dbimport.conf'
Layered env/dist/etc/worldserver.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/worldserver.conf.dist
'/azerothcore/env/dist/bin/../etc/worldserver.conf.dist' -> '/azerothcore/env/dist/bin/../etc/worldserver.conf'
Done
```

However, this works because now we do a copy of those files into the env/dist/etc while building the image: https://github.com/azerothcore/azerothcore-wotlk/commit/3202158af1e2875162eaeb828a5fd78e7702b091


By changing the DOCKER_ETC_FOLDER to the original source of those files (env/docker/etc) it still works:

```
Generating confs...
Layered env/docker/etc/authserver.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/authserver.conf.dist
'/azerothcore/env/dist/bin/../etc/authserver.conf.dist' -> '/azerothcore/env/dist/bin/../etc/authserver.conf'
Layered env/docker/etc/dbimport.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/dbimport.conf.dist
'/azerothcore/env/dist/bin/../etc/dbimport.conf.dist' -> '/azerothcore/env/dist/bin/../etc/dbimport.conf'
Layered env/docker/etc/worldserver.conf.dockerdist onto /azerothcore/env/dist/bin/../etc/worldserver.conf.dist
'/azerothcore/env/dist/bin/../etc/worldserver.conf.dist' -> '/azerothcore/env/dist/bin/../etc/worldserver.conf'
Done
```

So the code is solid enough now.

The DOCKER_ETC_FOLDER was used by the acore-docker to instruct where to get the files (https://github.com/Yehonal/acore-api/blob/bc799784283e846ebc1b77ba5147309b3b569298/docker-compose.yml#L155) , but now that we have are copying them under the `env/dist/etc` we can assume that the variable is deprecated. I wouldn't remove it yet though.

**Comment by Yehonal** [comment]
The acore-docker pipeline is working again 🥳

**Pull request merged**
