### PR TITLE
fix(Scripts/AhnQiraj): Obsidian Destroyer - Drain Mana.

### LINKED ISSUE #12637: [AQ20] Obsidian Destroyer (15338) Drain Mana only targets one player and missing visual spell
### Current Behaviour

- Only casts Drain Mana (25755) once
- Missing visual spell for Drain Mana (26639)

### Expected Blizzlike Behaviour

Casts Drain Mana 6 times, once for each different mana user. If there's only one mana user, it will only cast one. If there are no mana users, it will not cast it at all.
Casts the visual spell (26639) 200ms after the first Drain Mana spell

### Source

Sniffs from retail and https://youtu.be/o5fhWnI9Lk8?t=2096

### Steps to reproduce the problem

1. `.go c id 15338` with 2 or more characters
2. see if more than one Drain Mana spell is being cast
3. see if the visual spell is being cast

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/a4c809f13c818d1d7e078ed49cd67afbebebd900

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12637

## Issues Addressed:

- Closes #12637

## Tests Performed:

- Not tested.

## How to Test the Changes:

`.go c id 15338` with 2 or more characters
see if more than one Drain Mana spell is being cast
see if the visual spell is being cast

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Never cast mana drain.

**Comment by UltraNix** [comment]
@Maelthyrr Should be okay now.

**Comment by Gultask** [comment]
Casts Drain Mana but it's casting Purge way too much, it should only cast Purge when it reaches full mana.

**Comment by UltraNix** [comment]
@Gultask Try now.

**Comment by Maelthyrr** [comment]
@UltraNix tested with 3 char, he cast mana drain on 3.

**Comment by UltraNix** [comment]
@Maelthyrr And?

**Comment by Maelthyrr** [comment]
> @Maelthyrr And?

My bad, I thought only mana drain should be cat. Sorry, everything is fine.

**Comment by Nefertumm** [comment]
Fixed build and merge conflicts

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
