### PR TITLE
fix(Core/Spells): Area or assembly zone restriction

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:
-  fix: Area or zone restriction in quests
-  fix: quests [Flight of the Wintergarde Defender](https://www.wowhead.com/quest=12237/flight-of-the-wintergarde-defender), [Into The Wild Green Yonder](https://www.wowhead.com/quest=13045/into-the-wild-green-yonder), [You'll Need a Gryphon](https://www.wowhead.com/quest=12814/youll-need-a-gryphon), [No Fly Zone](https://www.wowhead.com/quest=12815/no-fly-zone), [Cold Hearted](https://www.wowhead.com/quest=12856/cold-hearted), [Defending Wyrmrest Temple](https://www.wowhead.com/quest=12372/defending-wyrmrest-temple), [The Thane of Voldrune (horde)](https://www.wowhead.com/quest=12259/the-thane-of-voldrune), [The Thane of Voldrune (alliance)](https://www.wowhead.com/quest=12255/the-thane-of-voldrune)
- **remembering that there are a few quests added to the restriction. So there are more of them to be implemented**   

## Issues Addressed:

- Closes 

## Tests Performed:

- was performed windows 7 64bits. Not a single error was found and it is Functional

## How to Test the Changes:

1. add the quests with command:
2. .quest add 12237, .quest add 13045, .quest add 12814, .quest add 12815, .quest add 12856, .quest add 12372, .quest add 12259 (horde), .quest add 12255 (alliance)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
@azerothcore/testers this will need to be tested

**Comment by Maelthyrr** [comment]
@grimgravy Thanks you for this PR ! Tested and it's work globaly. I just find one issue:

- "Flight of the Wintergarde Defender". The gryphon doesn't despawn. So you can take him again after the dismount and repeat this again to bypass the restriction.

**Comment by grimgravy** [comment]
@Maelthyrr, i have a code I wrote from that assignment, the improvement of which. Not opening a PR (fix) because it is not complete (the way I want it). However, solve this problem as well as from the same mission. My PC gave a problem with the video input, I placed an order for a video card on Aliexpress, I cannot make change at this time. Now I have to wait.

**Comment by benjymansy123** [comment]
> Not opening a PR (fix) because it is not complete (the way I want it).

Is opening a draft PR out of the question?

**Comment by acidmanifesto** [comment]
What is the status of this PR?

**Comment by Nyeriah** [comment]
Thanks for the PR, but same issue as the other one: spelldbc corrections need to go to the CPP file, we don't override clientside spells by adding into that table

**Comment by acidmanifesto** [comment]
@grimgravy merge conflicts.

**Comment by acidmanifesto** [comment]
@grimgravy merge conflicts
@Nefertumm we are pending a review request from you, yes or no to merge?

**Pull request closed without merging**
