### PR TITLE
fix(DB/NPC): Zenn Foulhoof

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12512

## SOURCE:

Wotlk Classic: https://www.youtube.com/watch?v=ZerX5j4xgDY
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Are these waypoints sniffed? Last I knew about Zenn is that he has a random pattern but it's **very** slow. Like, he does some movement, stops for 30-40s then starts again. I think he was the first creature I sniffed in TBCC, but I lost the packet.

Also, in Acore we use GUIDx10 for waypoints instead of GUIDx100 :)

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
source of way points?

**Comment by grimgravy** [comment]
is a few seconds link here: https://www.youtube.com/watch?v=ZerX5j4xgDY

**Comment by acidmanifesto** [comment]
With no sniff and being told to reference a few seconds of a video with blur spots on it, we are unable to confirm if this is a retail video or not. If the npc is a random wandering distance it needs to be observed for a good while while being sniffed. Please provide verifiable retail video or a sniff, or reference and link to other verifiable database such as TC or mangos.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
https://github.com/azerothcore/azerothcore-wotlk/pull/13216#issuecomment-1406535835

**Comment by Gultask** [comment]
I believe that it is a scripted random movement, set to wander every once in a while and then stop. I can't prove it because I never bothered to sniff it again and I lost the packet I had cause I forgot to rename it :p

**Comment by Maelthyrr** [comment]
If it's not a path, why not use "wander_distance"?

**Comment by grimgravy** [comment]
> If it's not a path, why not use "wander_distance"?

not used for this type of movement

**Comment by Gultask** [comment]
It's not waypoints either, I can prove it.

This is a special case of very delayed random WPs. I can't get the values for now because I deleted the sniff packet, though :P

**Comment by grimgravy** [comment]
> @grimgravy what's the status of this?

I will try to come up with a better movement for the npc. I need time to build

**Comment by Gultask** [comment]
This is legitimately an oddity. I've never really seen one of these before.

This NPC has a really slow wander. But it IS a wander

**Comment by Nyeriah** [comment]
Hello,

This PR has not received any updates in an extended amount of time, therefore we are closing it for the time being as it seems to have been abandoned. If you wish to continue developing this, please leave a message and we will reopen it. Thanks for your contributions.

Regards

**Pull request closed without merging**
