### PR TITLE
DB/Quest: Quest 11223 moved from core to DB

### PR DESCRIPTION
**Pull request by pangolp**
##### CHANGES PROPOSED:
- Add smart_script
- Remove c++ script
- Added locale in this gossip

##### TESTS PERFORMED:
- [x] Test on Windows.

##### HOW TO TEST THE CHANGES:
To test the changes, it is enough to take the mission.
.quest add 11223

##### KNOWN ISSUES AND TODO LIST:
None in particular, just change the c++ script to an SQL script

##### Target branch(es):
Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
looks good @pangolp good job!

**Comment by Winfidonarleyan** [comment]
I tested this quest before and after pr. Identical work. Now there is localization gossip.

**Comment by FrancescoBorzi** [comment]
great job @pangolp and @Winfidonarleyan !

**Comment by BarbzYHOOL** [comment]
we need to keep only one type of commit naming convention though

**Pull request merged**
