### PR TITLE
fix(Core/Config): MaxWhoList config

### PR DESCRIPTION
**Pull request by poszer**
MaxWhoList config

##### CHANGES PROPOSED:

-  Adding missing config for the MaxWhoListReturns which exist in world.conf.dist
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2026

##### TESTS PERFORMED:

Yep, fine everything.

##### HOW TO TEST THE CHANGES:

1. Change configuration

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by poszer** [comment]
@w5860363 Can you try now?

**Comment by Winfidonarleyan** [comment]
Need rework who list

**Comment by poszer** [comment]
> Need rework who list

Ok, thanks. Will check it

**Comment by Winfidonarleyan** [comment]
Please check who list in game, at player level 100+

**Comment by w5860363** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Handlers/MiscHandler.cpp#L393
Relevant content commented out is still invalid configuration

**Comment by Viste** [comment]
don't understand this config option  >_< this value hardcoded in client and he always show only 49 players, yes he write 49 of 10000 but shows only 49, but its one of idiotic things done by blizzard >_<

**Comment by poszer** [comment]
> https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Handlers/MiscHandler.cpp#L393
> Relevant content commented out is still invalid configuration

Yea, need fully rework

**Pull request closed without merging**
