### PR TITLE
fix(Core/TempleOfAhnQiraj): Rewrite Fankriss

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Use spells for entangle and worm summon.
-  Moved from ScriptedAI to BossAI (this needs to be done with almost every boss in the instance).
-  Added formation with Vekniss Drones around the boss.
-  Fixed SAI for Fankriss spawns, now they cast berserk after 10-20s iic.

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3812

## SOURCE:

Positions and timers from CMangos, mechanics from classic videos/guides.

## Tests Performed:

-  Tested in-game.

## How to Test the Changes:

1. .go c id 15510
2. Engage Fankriss

## Known Issues and TODO List:

- [ ] Not an issue but there were a lot of lacking information about bug waves (worms/vekniss hatchlings), if something needs to be corrected, let me know.
- [ ] For the love of God, clean up the header file, it's a mess.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Tested:
https://youtu.be/bCOoXMak8JY?t=22
- [X] Boss don't have big issue
- [X] Reset work
- [X] [Mortal Wound](https://classic.wowhead.com/spell=25646/mortal-wound) present
- [ ] [Entangle](https://classic.wowhead.com/spell=720/entangle) don't work (i'm sure but it's seems never cast)
- [X] [Vekniss Drone](https://classic.wowhead.com/npc=15300/vekniss-drone) spawn
- [X] [Spawn of Fankriss](https://classic.wowhead.com/npc=15630/spawn-of-fankriss) spawn and will enrage

**Comment by Nefertumm** [comment]
Entangle is not casted on tanks, to be able to see it you should go with 2 chars

**Comment by Maelthyrr** [comment]
> Entangle is not casted on tanks, to be able to see it you should go with 2 chars

Will check later

**Comment by Gultask** [comment]
I'm seeing the Entangle, and saw no other issues so far 👍

**Comment by Gultask** [comment]
Actually, Vekniss Drones are respawning after the boss is dead. Is that ok?

Also I didn't check research either the boss or much of the instance yet but there were 2 reports about it in the CC repo:
https://github.com/chromiecraft/chromiecraft/issues/3812
https://github.com/chromiecraft/chromiecraft/issues/3811

**Comment by Nefertumm** [comment]
Ty, about the vekniss drones, wowwiki shows this 
image

So it's highly possible the ptr doesn't reflect those changes. About them spawning while the boss is dead, I'll address that in a bit

**Comment by Nefertumm** [comment]
This is a video from cataclysm, but it shows the bugs around the boss 
https://youtu.be/Ypbi9vF15uM?t=641

**Comment by Gultask** [comment]
Ahh. Patch 2.0.1.
Kerric reports are mainly based around WoW Classic so that'd explain it. Ty for the source :)

**Comment by Nefertumm** [comment]
I linked Kerric's issue with the pr so it closes automatically, the only thing missing is the aggro radius.

**Comment by Gultask** [comment]
Is there a way to sniff the aggro radius? I'd imagine that'd be hard in retail, because of the level squish. If there's one I can go around finding them out since we'll have to probably adjust the aggro radius for all bosses.

**Comment by Nefertumm** [comment]
I don't think so, but you can use an addon called RangeDisplay to see how far the boss is on pulling (hard on retail because it diminishes detection I think)

**Comment by Gultask** [comment]
I'll try that. I'll see if I have a level 30 character somewhere.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
