### PR TITLE
Fix DB import issues

### LINKED ISSUE #1278: Apply 2019_01_12_01.sql fail
##### SMALL DESCRIPTION:

Friends, I want to raise the problem of apply last DB updates, because it appears due to the restriction of the mysql `max_allowed_packet` directive.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Execute multiple files in HeidiSQL

##### EXTRA NOTES:

It is worth adding a note to the wiki that the size of the `max_allowed_packet` directive should be changed (for me, a change in the value of 128 * 1024 * 1024 * 3 worked) or split `data/sql/updates/db_world/2019_01_12_01.sql` file.
```mysql
/* Use in mysql console */
set global max_allowed_packet = 128 * 1024 * 1024 * 3;
```

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

latest

##### OPERATING SYSTEM:

WIN10 X64 with MariaDB 10.3

##### MODULES:

None.

##### OTHER CUSTOMIZATIONS:

None.

### LINKED ISSUE #1281: world_update.sql typo
##### SMALL DESCRIPTION:
`-- DB update 2019_01_13_00 -> 2019_01_14_00`
```
DELETE FROM `creature_text` WHERE `entry` IN (14392);
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextId`) VALUES 
(14392, 0, 0, 'NEFARIAN IS SLAIN! people of Orgrimmar, bow down before the might of $N and his allies for they have laid a blow against the Black Dragonflight that is sure to stir the Aspects from their malaise! This defeat shall surely be felt by the father of the Black Flight: Deathwing reels in pain and anguish this day!', 14, 0, 100, 0, 0, 0, 'Overlord Runthak', 9867),
(14392, 1, 0, 'Be lifted by $N accomplishment! Revel in his rallying cry!', 14, 0, 100, 0, 0, 0, 'Overlord Runthak', 9868);
```
`creature_text` does not have an `entry` column. The now merged PR #1160 changed the column name from `entry` to `CreatureID`.

See:
```
ALTER TABLE `creature_text` CHANGE `entry` `CreatureID` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0';
```

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
c90afdd9e2b6604bb126b4e37821bc5b596957ad

##### OPERATING SYSTEM:
Windows 10

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
##### CHANGES PROPOSED:

-  Fix all DB imports issues after https://github.com/azerothcore/azerothcore-wotlk/pull/1160

###### ISSUES ADDRESSED:

- Closes #1278
- Closes #1281

##### TESTS PERFORMED:

Reproduced and then fixed the db import issue using both:
- the db_assembler on main host on Linux
- the dockerized AC DB

##### HOW TO TEST THE CHANGES:

- Delete your world database (or rename it)
- Run the db assembler with option "import-all"

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
In file `2019_01_14_00.sql` need delete 44-47 lines. 

In file `2019_01_12_01.sql` line 12246 and 12248
```sql
UPDATE `creature_text` SET `Text` = 'NEFARIAN IS SLAIN! people of Orgrimmar, bow down before the might of $N and his allies for they have laid a blow against the Black Dragonflight that is sure to stir the Aspects from their malaise! This defeat shall surely be felt by the father of the Black Flight: Deathwing reels in pain and anguish this day!', `Type` = 14, `Language` = 0, `Probability` = 100, `Emote` = 0, `Duration` = 0, `Sound` = 0, `BroadcastTextId` = 9867, `TextRange` = 0, `comment` = 'Overlord Runthak' WHERE `CreatureID` = 14392 AND `GroupID` = 0 AND `ID` = 0;
UPDATE `creature_text` SET `Text` = 'Be lifted by $N accomplishment! Revel in his rallying cry!', `Type` = 14, `Language` = 0, `Probability` = 100, `Emote` = 0, `Duration` = 0, `Sound` = 0, `BroadcastTextId` = 9868, `TextRange` = 0, `comment` = 'Overlord Runthak' WHERE `CreatureID` = 14392 AND `GroupID` = 1 AND `ID` = 0;
```

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan what do you mean? why removing those lines? can it be done in a separate PR? I would merge this one asap

**Comment by Winfidonarleyan** [comment]
This data is already in the database

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan I know, but I'm just changing the way we import those files. Not their contents.

If we want to add/remove data from the database we need to add new sql update files. This is just an exception because we must fix the existing ones. Thanks anyway for the review :)

**Comment by Winfidonarleyan** [comment]
Okay, go merge

**Pull request merged**
