### PR TITLE
feat(Core/Misc): remove ACE Auto_Ptr

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## CHANGES PROPOSED:
- Full remove `AutoPtr`
- Switch `QueryResult` to `std::shared_ptr`
- Switch `PreparedQueryResult` to `std::shared_ptr`
- Switch `Weather` to `std::unique_ptr`

## ISSUES ADDRESSED:
- Part #3451

## TESTS PERFORMED:
- Build only

## HOW TO TEST THE CHANGES:
- Run all applications `*server.exe` 
- Try the `Weather` system in-game
- Try to perform actions to interact with the DB `Items, characters and other`

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Mitradis** [comment]
cant merge, conflicts, need update for test.

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan

**Comment by Winfidonarleyan** [comment]
@Mitradis pr ready

**Comment by Mitradis** [comment]
@FrancescoBorzi @Winfidonarleyan build and work fine.
ctrl+c crash remained((

**Comment by FrancescoBorzi** [comment]
@Mitradis have you tested this in game?

> ## HOW TO TEST THE CHANGES:
> - Run all applications `*server.exe` 
> - Try the `Weather` system in-game
> - Try to perform actions to interact with the DB `Items, characters and other`

can you please have a look at it?

**Comment by Mitradis** [comment]
@FrancescoBorzi of course i started the server and playing (checking instances\locations\items\transmog\ahbot\autobalance etc.). Additional now i test weather system (.wchange 1 1 and .wchange 2 1 work fine).

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Mitradis** [comment]
@FrancescoBorzi can we force merge for fix https://github.com/azerothcore/azerothcore-wotlk/pull/3707 for this PR?

**Comment by FrancescoBorzi** [comment]
@Mitradis sure we can prioritise this, however the build is failing. @Winfidonarleyan can you please fix it?

**Comment by FrancescoBorzi** [comment]
Eluna's failure is fixed here: https://github.com/ElunaLuaEngine/Eluna/pull/339

We can merge this, this PR was not the cause of the Eluna's failure.

**Comment by Kitzunu** [comment]
Thank you 👍

**Pull request merged**
