### PR TITLE
feat(Core/Logging): rework logging to POCO::Logging

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
TODO
- [ ] #2566 
- [ ] auth
- [ ] common
- [ ] debug

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
this PR must be done first before the config one, no ? so we can use the logging in it

**Comment by Winfidonarleyan** [comment]
No, after config only

**Comment by BarbzYHOOL** [comment]
> Replace type in functions Get**Default from const char name to std::string const& name (for new logging system)

this from https://github.com/azerothcore/azerothcore-wotlk/pull/2566 requires Pocco logging ??

**Comment by Winfidonarleyan** [comment]
For this pr need pr #2566

**Pull request closed without merging**
