### PR TITLE
[Fix/core] fix pit of saron 

### LINKED ISSUE #10123: Boss in Pit of Saron Can not kill
### Current Behaviour

Boss tyrannus at last position is unattackable ,can not enter combat, so can not be killed

### Expected Blizzlike Behaviour

boss should enter combat

### Source

_No response_

### Steps to reproduce the problem

1. enter instance pit of saron
2. kill boss garfrost and boss  krickandick
3. wait in front of boss tyrannus 
4. watch , no trigger to enter combat, and boss was unattackable

### Extra Notes

_No response_

### AC rev. hash/commit

da7f4da51639+

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by betayi**
## Changes Proposed:
-  fix #10123 
-  

## Issues Addressed:

- Closes #10123 

## Tests Performed:

- 
- tested

## How to Test the Changes:

1.kill boss 1 and 2 
2. go throught cave 
3.stand in front of boss 3, to watch if  trigger the combat start event

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by opcode02** [comment]
i tried this patch, and ran through the pit of sauron in both normal and heroic, seems to have the same behavior as before, no trigger at the top of the hill after killing krick and ick and killing those groups of 5 undead things going up the hill.

**Comment by betayi** [comment]
look this, i have finish the whole instance without any mistake

**Comment by Krath** [comment]
> look this, i have finish the whole instance without any mistake

I don't think this is a proper fix. The encounter always worked as intended and the instance code hasn't been touched in months. Something else broke the trigger before the cave.

**Comment by betayi** [comment]
> > look this, i have finish the whole instance without any mistake
> 
> I don't think this is a proper fix. The encounter always worked as intended and the instance code hasn't been touched in months. Something else broke the trigger before the cave.

it's only fix this instance trigger at current branch commits, and won't effect others, why not properly? does the commit cause  new problem a proper fix? we can correct it properly sometimes in future , at least，it works fine, without cause new problem.

**Comment by opcode02** [comment]
Ok, I tested the newer patch and it definitely triggers correctly now, now you can finish the pit of saron's zones bosses to the end and everything triggers correctly.

**Comment by adink1** [comment]
Triggers correctly, but the last NPC that appears won't take part in the battle

**Comment by fullofstarschen** [comment]
This Patch works fine.

> Triggers correctly, but the last NPC that appears won't take part in the battle

**Comment by claudiodfc** [comment]
This PR doesn't make any sense. Why are you commenting these lines? If they do nothing here, just re-write this.

**Comment by adink1** [comment]
The latest version still can't trigger, only this patch can be used

**Comment by Rosencrant** [comment]
This patch Don't Work.

**Comment by nestormourino** [comment]
Working fine,

**Comment by Lynethris** [comment]
I confirmed that the fix work. If you test the PR, care with events that broke when you go fast (like .die command).

**Comment by Lynethris** [comment]
PR Close. A proper fix do the same thing (#10819 ).

**Pull request closed without merging**
