### PR TITLE
feat(Core/SmartAI): Add support for usage of waypoint_data in SAI

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

waypoint_data is more well-maintained and more robust than waypoints. Ideally we should start using these new actions and events and deprecate the old ones.

In the sql file there are examples of its usage

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/18430
- Closes https://github.com/chromiecraft/chromiecraft/issues/6361

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [X] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [x] Creature comments
- [ ] Replace hand guids with @CGUID stuff (please don't make me do this it's so annoying

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Likely resolves https://github.com/azerothcore/azerothcore-wotlk/issues/18430 and its linked issue.

**Comment by Gultask** [comment]
ya

**Review by elthehablo — DISMISSED** [review]

**Comment by elthehablo** [comment]
builds all dead? nice

**Comment by sudlud** [comment]
> builds all dead? nice

#18697

**Comment by Gultask** [comment]
I'll expand on this, so don't merge yet

**Comment by Gultask** [comment]
Apparently the Pause() and Resume() MovementGenerator methods aren't fully implemented yet and ignores(?) the timer parameter. TC's MotionMaster reimplementation I think would fix it.

Anyway, I'm done with this one. Will make the wiki and Keira PRs shortly, but hopefully with all these we can move on from the waypoints table

**Review by elthehablo — APPROVED** [review]

**Pull request merged**
