### PR TITLE
fix(DB/AQ20): Ossirian Loot

### LINKED ISSUE #12699: Ossirian Loot wrong
https://github.com/chromiecraft/chromiecraft/issues/3914

### What client do you play on?

ruRU

### Faction

Both

### Content Phase:

60

### Current Behaviour

Drops only head, hilt and ring tokens and very small % to drop other stuff

### Expected Blizzlike Behaviour

Should also drop 2 non-set pieces from his loot table. And im not sure but I think only one random token should drop(hilt or ring)

### Source

https://youtu.be/Sg_BlR_F2hk?t=2286

### Steps to reproduce the problem

Kill Ossirian

### Extra Notes

image
is reference table % for other loot
image

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/e6dd5d3e22d92dddc841079f9108275fd0359be1

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by SoglaHash**
Corrected Ossirian boss loot

## Changes Proposed:
I made Ossirian drop:
3 books
1 hilt or ring. More likely to drop epic
2 epic non-set
1 head
1 enchanting recipe with 7% chance

I put them in seperate ref tables so there's no duplicate non-set or book drops.

## Issues Addressed:

- Closes #12699
- https://github.com/chromiecraft/chromiecraft/issues/3914

## Tests Performed:

- 
1269_ossirian_loot

## How to Test the Changes:

Go to Ossirian
```
.go c 144601
```
Reset Instance
```
.instance u all 
```
1. TP to Ossirrian
2. Kill
3. Check loot
4. Reset 

Also check the loot table in SQL with Keira3. Ossirian (id: 15339) to see if I missed a skill book or item.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
Hey, what is your source for these drops / reference tables?

**Comment by SoglaHash** [comment]
I looked at how Acore DB was structured and then referenced it with
1. classic wowhead https://classic.wowhead.com/npc=15339/ossirian-the-unscarred
2. https://github.com/brotalnia/database
3. my own experience raiding aq20 multiple times per week on classic + reference vids like posted in your issue 

It's not an exact copy of any but seems the most sensible.

For instance,
The ref table with the hilt/ring was guesswork. Epic should drop most, but not always, but never with the ring. So I choose 40/40/10/10 chance split

Non-set loot and books are always unique, so I put them in different ref tables.

The drop chance of ench recipes are low but could be 5-15%. So I put 7.

**Comment by Nefertumm** [comment]
We don't take wowhead as a valid source for loot sadly. We usually take a look at CMangos DB values more than anything else, since they are pretty accurate (in certain situations not, but I think that's not the case here), take a look there if you want.

**Comment by SoglaHash** [comment]
I've updated the query to match CMangos DB, however I'm not able to get it to import properly and linked it as a gist below. I get a 
```
SQL Error [1062] [23000]: Duplicate entry '34024-20727' for key 'reference_loot_template.PRIMARY'
```
which refers to `20727:'Formula: Enchant Gloves - Shadow Power'),` It is in both ref table 34022 and 34030, is that not allowed? 

https://gist.github.com/SoglaHash/6b2c4fd72e83ad246ad0a2855d450439

**Pull request closed without merging**
