### PR TITLE
fix(Core/Spell): Omen of clarity

### PR DESCRIPTION
**Pull request by Ali-Khazaee**
https://github.com/azerothcore/azerothcore-wotlk/issues/2133

### CODE REVIEW

**Comment by poszer** [comment]
Just if someone didn't read infos, this isn't Blizzlike. Anyway, thanks for PR @Ali-Khazaee

**Comment by Knindzagxg** [comment]
It fix Omen now, tested without problems.

**Comment by poszer** [comment]
Not Blizzlike :)

**Comment by Stoabrogga** [comment]
@poszer
I read the comments and it is ok for me. If it should not be merged, why did you not just close the PR?

**Comment by poszer** [comment]
I practice writing a comment more, and directing people that this PR is wrong, actually not the blizz behaviour.

**Comment by Stoabrogga** [comment]
Well, feel free to close it if you think this should not be merged.

**Comment by talamortis** [comment]
Closing PR due to not Blizzlike.

**Comment by BarbzYHOOL** [comment]
It procced like that in classic and TBC.

But on wowpedia they say this ` Now a passive spell. Now also procs on damage and healing spells, yet no longer procs on feral abilities(only auto-attacks proc it). Proc rate is roughly 6% with a 10 second internal cooldown. `

Damnit what a nerf

**Pull request closed without merging**
