### PR TITLE
fix(Core): Build

### PR DESCRIPTION
**Pull request by PkllonG**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
cc @Nefertumm

**Comment by pklloveyou** [comment]
```
40851	spell_gen_select_target_count_7_1
45680	spell_gen_select_target_count_7_1
45976	spell_gen_select_target_count_7_1
48425	spell_gen_select_target_count_7_1
52438	spell_gen_select_target_count_7_1
52449	spell_gen_select_target_count_7_1
```
Don't we need these?

**Comment by elthehablo** [comment]
Nope

**Comment by elthehablo** [comment]
Or well we will find out after you delete them :p

**Comment by pklloveyou** [comment]
I am very certain that we should not delete it

**Comment by Nyeriah** [comment]
I don’t know why the registry was deleted but Nefertum should be able to check this soon and clarify why it was removed

**Comment by pklloveyou** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/7dbb65cafac063e857e71f7b232616e84f75b645/src/server/scripts/Spells/spell_generic.cpp#L661

**Comment by Nefertumm** [comment]
My bad, it was too late for me. It shouldn't be deleted

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
