### PR TITLE
fix(Scripts/AlteracValley): Crashfix.

### LINKED ISSUE #10794: [AV] Taunting Vanndar Stormpike does not pull Marshals
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/3116

When you pull Vanndar Stormpike on Alterac Valley, it doesn't generate aggro on the rest of the adds.

Tester:

The issue is confirmed.

WoWScrnShot_022322_101812

### Expected Blizzlike Behaviour

When you taunt the boss, it should pull all the adds too, that happens with the horde boss.

### Source

_No response_

### Steps to reproduce the problem

1. Taunt Vanndar Stormpike

### Extra Notes

https://wowgaming.altervista.org/aowow?npc=11948

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/f82c60526b9955c697b1ee804a8e7613f62c1568

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
## Issues Addressed:

- Closes #10794

## Tests Performed:

- Not tested.

## How to Test the Changes:

Need more people for this, can't reproduce it solo on local AC prob
Pull one of adds
Get out of range carefully, use spells like vanish, FD when you have aggro on boss
Boss resets and his adds continues to get killed by group

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nefertumm** [comment]
You would need to add the previous changes to it again since it was reverted!

**Comment by UltraNix** [comment]
Done.

**Comment by temperrr** [comment]
/mnt/data/azerothcore/src/server/scripts/EasternKingdoms/AlteracValley/alterac_valley.cpp:116:85: fatal error: use of undeclared identifier 'FACTION_AV_ALLIANCE'
                    if (Creature* mainBoss = bg->GetBGCreature((me->GetFaction() == FACTION_AV_ALLIANCE ? AV_CPLACE_A_BOSS : AV_CPLACE_H_BOSS)))
                                                                                    ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:1245: src/server/scripts/CMakeFiles/scripts.dir/EasternKingdoms/AlteracValley/alterac_valley.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1043: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by UltraNix** [comment]
@temperrr Done.

**Comment by temperrr** [comment]
Tested all kinds of situations, it works and didnt crash for me.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
