### PR TITLE
feat(Core/SAI): SetData now has invoker

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/cfc77fd84355d28737f3f85f2ba318be5caacdea)

* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/beb333738db0d493bf95994eb5557e174e5dd3a6)

* Move IsSmart function from headerfile

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19195

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
for you @avarishd

**Review by Nyeriah — APPROVED** [review]

**Comment by Gultask** [comment]
!!!

**Comment by avarishd** [comment]
Seems to work, tested move_to_pos when data is set by a creature.
<details>

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/6b93838e-4c9d-4047-b01c-f3de467fb51e

</details>

**Comment by avarishd** [comment]
This is causing areatriggers to spit out error that the target is not sai (which is correct), when targeting a creature/object(untested of object) with a cpp script.
(Action does NOT get skipped, you can see that he still yells in the first picture.)

Should either be using scripted areatrigger or doaction, thoughts?

image
image

**Comment by avarishd** [comment]
After a bit more testing during the last few days it seems that gameobjects are not being handled as invokers.

<details>

**(The ale sets data 1 1)**
Tested with a bunch of different actions that require target, same results.

image

https://github.com/azerothcore/azerothcore-wotlk/assets/46330494/e380563b-5dae-4455-a7d9-29f94fc63d17

</details>

**Pull request merged**
