### PR TITLE
fix(DB/gameobject): Double stacked veins in Stranglethorn Vale

### PR DESCRIPTION
**Pull request by OMGhixD-OG**
## Changes Proposed:
-  Remove Double stacked veins in Stranglethorn Vale next to Booty Bay

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4424

## Tests Performed:

Followed the "how to reproduce problem" field from the Bugreport. 
When importing this fix. Should get rid of Duplicated Veins in the lower part of STV. (including veins that look out of place, Like nearly floating etc.)

## How to Test the Changes:

STEPS TO REPRODUCE THE PROBLEM:
Use Detect Minerals
Exit the Booty Bay tunnel and go up the hill (where I am on the map)
Find the double stacked silver/iron veins.

This was how i reproduced the problem.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by OMGhixD-OG** [comment]
If i did something incorrectly. Please do let me know.

**Comment by locus313** [comment]
First off, want to thank you for your contribution!
Can you add a new line at the end of the file? (no spaces, just a new line) Can you also fill out the rest of the template with tests you performed and how others can test the change?

**Comment by OMGhixD-OG** [comment]
> First off, want to thank you for your contribution!
> Can you add a new line at the end of the file? (no spaces, just a new line) Can you also fill out the rest of the pr template with tests you performed and how others can test the change?

Better?

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@OMGhixD-OG looks fine now, thanks for your contribution!

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
