### PR TITLE
fix(Scripts/BlackwingLair) Razorgore should not reset with only one raid member alive that is conflagrated

### PR DESCRIPTION
**Pull request by SaxxonPike**
## Changes Proposed:
- Make it so that Razorgore's conflagrate functions like Drakkisath's conflagrate (which does this mechanic properly): threat is only temporarily reduced to zero
- Allow Razorgore to still attack conflagrated players if they are the only players left alive (as they will have 0 threat but still be eligible)

## Issues Addressed:
- This is a regression introduced with #11183 (although that partially addressed the issue, it was not entirely the correct fix)

## SOURCE:
- This shows what is supposed to happen when a solo player (only one on the threat table) is conflagrated: https://youtu.be/5FxU1dLJUs4?t=293 (starts 4:53)
- Notice how Razorgore continues attacking the conflagrated player because there's no one else on the threat table.

## Tests Performed:
- We built and ran AC, and entered BWL with 2 players to verify that targets switched appropriately during Conflagrate.
- We also ran it with 1 player to make sure the encounter did not reset due to Razorgore lacking eligible targets.

## How to Test the Changes:
Testing solo:
1. `.tele blackwinglair` and enter, alone, with no pets
2. Begin the encounter by killing the weak mobs on the left- but leave Razorgore loose
3. Observe that the fight does not reset when Razorgore conflags the player.
Testing intended:
1. `.tele blackwinglair` and enter with any number of friends
2. Begin the encounter by killing the weak mobs on the left- leave Razorgore loose
3. Observe that Razorgore's target changes when the tank is conflagrated.

## Known Issues and TODO List:

- Not at this time.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by SaxxonPike** [comment]
I think this is as a result of the Threatmgr changes since our last merge, I will repair.

**Comment by Gultask** [comment]
Sorry for the late reply. There is a lack of testers at the moment. Build is still failing for me.

**Comment by Gultask** [comment]
Generally this is a safety measure to make it possible to solo. In WotLK videos I've never seen a boss with this mechanic that actually resets when using it. So I'd say this PR would indeed correct an issue.

**Comment by Nefertumm** [comment]
Superseded by https://github.com/azerothcore/azerothcore-wotlk/pull/13782 as it fixes other bosses too. Thank you for your PR!

**Pull request closed without merging**
