### PR TITLE
fix(DB): Air Invasion improvement

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Improved Air Elemental Rift's SmartAI to summon 3 Invaders per rift
Maximum.
- Invaders don't despawn until killed, even after The Windreaver dies.
- Improved Whirling Invader's SmartAI to make the Rifts work and their
in-combat AI with VMangos spells and timers.

## Issues Addressed:

- Closes not reported issue

## SOURCE:

Vmangos and classic

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Check how many maximum Whirling Invaders spawn per rift (3)
2. After Killing an invader another should spawn about 30s later
3. After killing The Windreaver the Rifts should despawn but not the Whirling Invaders.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by dualcorex** [comment]
I tried to test this in-game, however I was unable to get the event to start. Currently in Silithus, north west corner. I looked up the event using `.lookup event Invasions` Elemental Invasions is event ID 13. I tried to start the event using `.event start 13` but the event doesn't start. trying to start a second time says the event is alreay active. I see no rifts, or no spawns. Is that the correct way to start this event? Has anyone else been able to manually start the event using the commands?

**Comment by claudiodfc** [comment]
The command is supposed to spawn the NPCs for the event. If it doesn't spawn then the command is probably broken. I'll see what's up later

**Comment by claudiodfc** [comment]
Turns out the issue was between the chair and the keyboard, as usual. I've updated the PR. Could you please re-test @dualcorex ? 🙏🏼

**Comment by temperrr** [comment]
Too many are spawning:
image

**Pull request closed without merging**
