### PR TITLE
Molten Core - Core Hounds

### LINKED ISSUE #592: [RAID] MC Magmadar's core hound groups do not revive if the pack is not killed.
**Description**: The core hound packs that must be killed before reaching Magmadar do not revive themselves as they should if the pack is not killed in the proper manner.

**Expected behavior:** 
Core Hounds that have been dead for a short while should respawn if the entire pack of hounds has not been killed. The correct mechanic requires all hounds in the pack to be taken to low health and killed off with an AOE attack. If the pack is not killed entirely, dead hounds will respawn and rejoin the battle.

**Branch:**
Master

**Commit Hash:** 
c15f15ebb0a113a5cf20fc11afb89b2bcff9ec6d

### PR DESCRIPTION
**Pull request by Gargarensis**
**Changes proposed:**

-  Now they work properly

**Issues addressed:** Closes #592

**Tests performed:** (Does it build, tested in-game, etc) It build and I tested it, further test might be good.

**Known issues and TODO list:**

- [ The core hound are still attackable while dead. I did it like this because of a video I saw where they behaved this way. If it is wrong, correct me.
ref: https://www.youtube.com/watch?v=DCKVG75yCGw ]

### CODE REVIEW

**Comment by Yehonal** [comment]
It does not compile

image

**Comment by Yehonal** [comment]
It's a warning but must be fixed, you have just to put brackets in this way:

```
                    if (me->HasUnitState(UNIT_STATE_DIED)) {
                        if (killer)
                            me->Kill(killer, me);
                        else
                            me->Kill(me, me);
                    }
```

**Comment by ShinDarth** [comment]
to avoid confusion, I would say to always add brackets (even when the if/else block has only one statements)

**Comment by Yehonal** [comment]
It's on staging branch and on our dev server ready to be tested

**Comment by ShinDarth** [comment]
@mygithome002  please give your feedback about your tests

**Pull request merged**
