### PR TITLE
fix(DB/Creature): Manually apply 'automated z correction' to DB spawns

### PR DESCRIPTION
**Pull request by sudlud**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

the core hackfix which has been doing this "on the run" was removed already in #18200 (and modified before in #18153).

this "restores" the state of all DB spawns in non-instancable maps that triggered the hackfix as if the hackfix would still be active, but not touching any sniffed spawns.

so for these spawns the in-game behaviour should be exactly the same as before #18200 and #18153.

the list was generated by following these steps:
- revert #18200 and #18153
- clear table `pool_creature` to force-spawn all creatures ignoring any pools
- `worldserver.conf` -> `PreloadAllNonInstancedMapGrids = 1` to actually spawn all creatures in all non-instanced maps on sever start
- generate an appropriate LOG-message within the hackfix-code (if it was triggered) for the output file
- remove any entries with `VerifiedBuild != 0` from the output file

## Issues Addressed:

- Progress #18684

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
didn't check all 22k lines, but I think that we need some in-game tests than code reviews here

**Comment by Gultask** [comment]
just some questions:

1. what about caves? I've seen a lot of creatures and gobs on top of caves possibly due to z-fidgeting done ages ago
2. what about flying creatures, if any? with DisableGravity for example?

**Comment by sudlud** [comment]
The file is ordered by map, then by creature ID.

All lines also have the creature name as comment at the end.

The hackfix checked if there is a surface above the spawn point within a range of up to z+1.0f.
if there is a surface, the spawn gets moved up onto that surface.

I could imagine that it's not wanted to change spawns like:
- debug targets
- * targets
- bunnies
Etc.

Maybe someone can please take a look through the file

**Comment by PkllonG** [comment]
guid
1976960
1976954

**Comment by PkllonG** [comment]
After I searched for more than 100 pieces of data, I recommended merging PRs, and I didn't expect that there were so many underground

**Comment by pvp100com** [comment]
I tested 50 items one by one, including comparing differences in the game, and the issues should have been resolved.

Before:


After:

**Comment by sudlud** [comment]
How about merging this PR 🌋

**Comment by PkllonG** [comment]
> How about merging this PR 🌋

I've been using it in my server for a long time

**Comment by Helias** [comment]
good job! thanks for the PR and for testing it!

**Comment by Gultask** [comment]
Thank you both Pk and pvp for looking into it!

**Pull request merged**
