### PR TITLE
refactor(Scripts/AhnKahet): new script system

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Update to new model

## Tests Performed:

- builds

## How to Test the Changes:

1. Test that scripts work like before. Eg. Uses spells, talks. tl:dr make sure the bosses don't just stand still

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by FlamePrince** [comment]
I was excited to test this out, but I'm encountering some conflicts:

https://i.imgur.com/Nz50tJb.png

**Comment by Kitzunu** [comment]
fixed

**Comment by savowe** [comment]
builds now.

Tested non-heroic:

- [x] Elder Nadox: spawns adds and the guardian which makes him immune. Looks good.
- [x] Prince Talderam needs the two crystalls activated to engage in fight. He casts Flame Spheres, Bloodthirst. I did not see him vanish and attack me. But this might be because I was alone. Looks good.
- [ ] Jedoga Shadowseeker spawns acolytes that try to sacrifice themselves and becomes immune. But if they reach the middle nothing happens. See video below
- [x] Herold casts insanity and shadowbolts. Looks good 

https://user-images.githubusercontent.com/38558793/143689727-23d4ddac-dc33-4842-991d-c47930817489.mp4

**Comment by Kitzunu** [comment]
All you need to test if it works the same way as before. Aka the scripts are loading which they are.

**Pull request merged**
