### PR TITLE
fix(Scripts/ZulAman): Nalorakk sometimes not move when player close

### PR DESCRIPTION
**Pull request by kissingers**
Initialize a parameter that is used without initialization to avoid uncertainty in the script's execution logic, fixing the boss sometimes can not work.

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 
https://github.com/azerothcore/azerothcore-wotlk/pull/19010
## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by kissingers** [comment]
Tested about 50 times and all ok.

**Comment by Nyeriah** [comment]
Please initialize it in Reset()

**Comment by kissingers** [comment]
> Please initialize it in Reset()
But this boss has 3 extra walking stages, if reset this parameter in other stages, it may lead to incorrect, other stages this parameter seems to need to be retained in the reset(), so it may be better to set to 0 during initialization.

**Comment by PkllonG** [comment]
```_phase = PHASE_SEND_GUARDS_1;```

**Comment by kissingers** [comment]
Thanks, I add it just like order of definitions

private:
    uint8 _phase;
    bool _ranIntro;
    bool _active;

**Comment by kissingers** [comment]
Also there no script when died , so there no summon creature to give box. but the script not so same as before , I dont where add this right.

        void JustDied(Unit* /*killer*/) override
        {
            Talk(SAY_DEATH);
            _JustDied();
            if (instance)
                instance->SetData(DATA_NALORAKKEVENT, DONE);
        }

**Comment by kissingers** [comment]
It seem ok, will do as a new fix.

    void JustDied(Unit* killer) override
    {
        BossAI::JustDied(killer);
        Talk(SAY_DEATH);
        if (instance)
            instance->SetData(DATA_NALORAKKEVENT, DONE);
    }

**Review by elthehablo — APPROVED** [review]

**Comment by elthehablo** [comment]
Idd shouldn't be in reset as we don't want this behaviour to happen when you wipe.

Could ofc do some conditions in there but this is fine imo to have it in the constructor.

Anyway, will look at ZA more in the coming months so we can work on improving this further

**Pull request merged**
