### PR TITLE
fix(Core/crash): prevent the crash of the core limiting the mails to load

### PR DESCRIPTION
**Pull request by Helias**
Add a limit to load the mails

## CHANGES PROPOSED:
-  improve the query SQL to load the mails

## TESTS PERFORMED:
- I didn't test it, but I am aware of this critical bug

## HOW TO TEST THE CHANGES:
- send 30k (or maybe more) mails  to a player and with that player open the mailbox, the core will wait for the SQL query to finish the loading but it will not in low time, this will cause a crash of the server.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
Will this prevent several players from viewing any mail?

**Comment by peti446** [comment]
After 70K mails I still did not crash it somehow before the pr, however I can confirm after applying the PR mail still works like intended even with 70K mails (NB: I did not open all of them but at least 120 to see if they refresh correctly :))

**Comment by Shadofiend** [comment]
Worked.

**Comment by Helias** [comment]
thanks for testing, but I need to add more checks, with @peti446 I tested different cases and figure out that I need to improve this PR

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Helias** [comment]
@peti446  is working on this, so I am closing this PR

**Pull request closed without merging**
