### PR TITLE
fix(Scripts/UBRS): Drakkisath's conflagrate should drop threat tempor…

### PR DESCRIPTION
**Pull request by Nyeriah**
…arily

also adjust it's timer slightly

## Changes Proposed:
-  Reset threat temporarily for Conflag. targets
-  Adjust timer according to feedback

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/9003

## Tests Performed:

- Tested in-game.
- 

## How to Test the Changes:

1. engage drakkisath with 2 characters
2. notice threat drops when he casts conflag and he goes to the next target
3. notice that threat is readded once conflag expires (according to feedback it should be temporary)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Tested and working as expected.

**Comment by T1ti** [comment]
Isn't target switching when applying a CC breakable by dmg global mob AI rather than ahrdcoded threat drop ?

**Comment by Nyeriah** [comment]
> Isn't target switching when applying a CC breakable by dmg global mob AI rather than hardcoded threat drop ?
> 
> The same behavior should happen when any mob applies a polymorph or whatever, they ignore the cc'd player and switch to secondary

This isn't a breakable CC.

**Comment by T1ti** [comment]
Confuse should be the same as disorient afaik, it's just the aura effect that is different  and it does break on DMG.

Confusion was renamed to disorient in patch 1.9 https://wowpedia.fandom.com/wiki/Disorient 

Dragon's breath also uses spell aura Confuse.

**Comment by T1ti** [comment]
Also Blizz would have 100% included the threat drop in a spell effect, unless there's a dummy/script effect, in this case it could be coded

**Comment by Nyeriah** [comment]
Conflagrate:
Skärmbild 2021-11-25 053338

Dragon's breath:
Skärmbild 2021-11-25 053454

Right now, you can take as many hits and Conflagrate never breaks. So as I see it, it's the MECHANIC_DISORIENT that breaks on damage and not the spell itself, it has nothing to do with the aura but the mechanic that it applies. It could be that the core is doing it wrong, but that's how it is right now.

**Comment by T1ti** [comment]
Yeah drakkisath's conflag doesn't seem to apply any mechanic effect 
I'll look into it more, maybe there's an hidden server side spell that drops threat

**Comment by Plasmashield** [comment]
Threat shouldn't reset temporarily. You shouldn't get back your threat after conflagration over

**Comment by Nyeriah** [comment]
> Threat shouldn't reset temporarily. You shouldn't get back your threat after conflagration over

Please open an issue with the sources for your claim and I'll look into it

**Comment by Plasmashield** [comment]
> > Threat shouldn't reset temporarily. You shouldn't get back your threat after conflagration over
> 
> Please open an issue with the sources for your claim and I'll look into it

Oky. But i don't understand why it was implemented like this without any sources

**Comment by Nyeriah** [comment]
> > > Threat shouldn't reset temporarily. You shouldn't get back your threat after conflagration over
> > 
> > 
> > Please open an issue with the sources for your claim and I'll look into it
> 
> Oky. But i don't understand why it was implemented like this without any sources

I was told by a retail player this is how it should work, and this is how this kind of mechanic usually works. If you think it's wrong you're free to make your claim, not a problem to me at all.

**Comment by Plasmashield** [comment]
So... Just someone told it to you? The same as it was with Elemental Focus? Is it enough that someone just said it to you to change it? By the fact that in 5 minutes of searching for a video, you can find how it actually works on a classic for now.

**Comment by Nyeriah** [comment]
> So... Just someone told it to you? The same as it was with Elemental Focus? Is it enough that someone just said it to you to change it? By the fact that in 5 minutes of searching for a video, you can find how it actually works on a classic for now.

Please find such evidence and post it as already suggested. As I said, I have no issues reworking this if it's not how it should work, but there's no room for drama in projects like this, you were already told what needs to be done.

**Pull request merged**
