### PR TITLE
fix(DB): Removing Thrash from Creatures

### LINKED ISSUE #6118: Remove "Thrash" ability from creatures that aren't supposed to have it
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

Original report: https://github.com/chromiecraft/chromiecraft/issues/718

##### CURRENT BEHAVIOUR:

*Please consider reading extra notes first, there is the foundation of this report.*
1. In Darkshore, the whole Foreststrider family, including [Foreststrider Fledgling](https://wowgaming.altervista.org/aowow?npc=2321), [Foreststrider](https://wowgaming.altervista.org/aowow?npc=2322) and [Giant Foreststrider](https://wowgaming.altervista.org/aowow?npc=2323) possess ability [Thrash trigger(spell=12787)](https://wowgaming.altervista.org/aowow?spell=12787).WoWScrnShot_052721_201002
2. [Blackwood Pathfinders](https://wowgaming.altervista.org/aowow/?npc=2167#abilities) have incorrect version of Thrash trigger, please note that this is only my speculation of comparing AoWoW DB and [ref DB](https://wotlkdb.com/), not in-game testing.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

1. None of them should be able to cast any kind of Thrash.
2. Blackwood Pathfinder should have [Proc chance: 25% version](https://wotlkdb.com/?spell=54913#used-by-npc), not the 35% version.

##### SOURCE:

ref DB: https://wotlkdb.com/

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to darkshore (preferably around level 14 as a cloth-type class)
2. Challenge any previously mentioned mobs
3. !?
4. Check the combat log

##### EXTRA NOTES:

1. A confusing detail of AoWoW DB, although Thrash(spell=12787) is mentioned on the [Foreststrider's page](https://wowgaming.altervista.org/aowow/?npc=2322), Foreststrider isn't listed on the "Used by" of [Thrash(spell=12787)](https://wowgaming.altervista.org/aowow/?spell=12787#used-by-npc).

2. It's difficult to find a good source of knowledge for wotlk, as classic wotlk hasn't arrived yet and wayback machine is incomplete for reference in general, so for the purpose of this report I use https://wotlkdb.com/ as my reference, but it isn't much better to be honest, for example: [Blackwood Tracker](https://wotlkdb.com/?npc=11713#abilities) is described to have [Thrash(spell=3391)](https://wotlkdb.com/?spell=3391#triggered-by), but that spell is only an action(hit two extra times), not a percentage trigger, It's not clear to me how that's supposed to work.

3. I also tried to check the classic wowhead page, but it's even more confusing there, as [Blackwood Tracker](https://classic.wowhead.com/npc=11713/blackwood-tracker#abilities) is listed to have multiple versions of thrash-triggers, which one(10%, 15%, 35%) is supposed to be used?

4. *Update*, I found a video of a player fighting striders in classic wow, if it would be of any help: https://youtu.be/vhKiSTZnjLI?t=180

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: ea76481):

WoWScrnShot_052921_192347
WoWScrnShot_052921_192501
WoWScrnShot_052921_192608
WoWScrnShot_052921_192744

I saw some of you commenting on the databases and their reflection in these NPCs, and I was not sure if I should link the problem in AzerothCore or not, but since it seems that the mismatch exists, I did it, sorry if it wasn't the right thing to do!!

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98815937-remove-thrash-ability-from-creatures-that-aren-t-supposed-to-have-it?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Deleted SmartAI events for creatures that cast Thrash spells in Vanilla.
- Removing AI name from creatures without SAI.
- Modified each creature that should cast thrash based on brotalnia's sniffs. Most of these are creatures with the following keywords on their names: **Mauler** or **Thrasher** and specific types of creatures like Gnolls, Ogres, Raptors, Centipaar, Hydras and some dungeon creatures like the ones in Scarlet Monastery, Goblins in Deadmines or Hydras in Maraudon.
- **Stonevault Brawler**: Was missing Enrage - Say Link on event
- **Stonevault Mauler**: Missing Enrage Text linked event.
- **Shade of Eranikus**: Fixed ID order for events and removed Linked event 0 to 1, maybe fixing on pull Say Text.

## Issues Addressed:

- Closes #6118 
- Closes https://github.com/chromiecraft/chromiecraft/issues/718
##### Sniffs from Brotalnia (Classic)
All these creatures cast the ability 3391 which is the non trigger thrash spell, which means, directly getting the thrash auto-attacks.

``` mysql
-- Creatures that casted 3391 'Thrash' from Issue
SELECT * FROM `spell_unique_caster`
WHERE `caster_id` IN (232, 449, 478, 519, 669, 757, 862, 880, 1039, 1142, 1202, 1224, 1353, 1520, 1654, 1655, 1656, 1658, 1662, 1693, 1783, 1791, 1843, 1847, 1871, 2167, 2186, 2236, 2321, 2322, 2323, 2535, 2536, 2560, 2681, 2717, 2728, 2749, 2773, 2944, 3256, 3284, 3285, 3378, 3456, 3476, 3722, 3746, 3812, 3814, 3988, 3999, 4023, 4202, 4348, 4374, 4388, 4389, 4390, 4479, 4493, 4540, 4634, 4656, 4687, 4855, 5234, 5260, 5267, 5287, 5435, 5455, 5456, 5457, 5458, 5459, 5460, 5477, 5622, 5683, 5709, 5976, 5977, 6005, 6020, 6068, 6093, 6140, 6348, 6352, 6506, 7039, 7067, 7101, 7234, 7287, 7307, 7320, 7369, 7446, 7669, 7671, 8138, 8205, 8216, 8299, 8911, 8961, 8981, 9096, 9164, 9167, 9176, 9267, 9777, 10407, 10414, 10416, 10488, 10639, 10946, 10991, 11043, 11357, 11372, 11486, 11677, 11724, 11725, 11737, 11782, 11789, 11791, 11858, 11918, 11921, 12138, 12201, 12207, 12940, 13088, 13159, 14275, 14276, 14282, 14283, 14426, 14750, 14821, 14882, 15591, 16216, 16593, 17397, 18631, 23680, 24552, 24713, 25027, 25028, 25611, 25625, 28101, 29033, 29392, 30147, 6210) AND `spell_id` = 3391;
```

## Tests Performed:

- Not tested

## How to Test the Changes:

1. .go c id 100 (Shouldn't cast Thrash)
2. .go c id 478  (Should cast Thrash)
3. If it works for a positive and negative test case, all other IDs are also working.

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
Running the Recommended query from your post results in a error with nothing displayed.
```-- Creatures that casted 3391 'Thrash' from Issue
SELECT * FROM `spell_unique_caster`
WHERE `caster_id` IN (232, 449, 478, 519, 669, 757, 862, 880, 1039, 1142, 1202, 1224, 1353, 1520, 1654, 1655, 1656, 1658, 1662, 1693, 1783, 1791, 1843, 1847, 1871, 2167, 2186, 2236, 2321, 2322, 2323, 2535, 2536, 2560, 2681, 2717, 2728, 2749, 2773, 2944, 3256, 3284, 3285, 3378, 3456, 3476, 3722, 3746, 3812, 3814, 3988, 3999, 4023, 4202, 4348, 4374, 4388, 4389, 4390, 4479, 4493, 4540, 4634, 4656, 4687, 4855, 5234, 5260, 5267, 5287, 5435, 5455, 5456, 5457, 5458, 5459, 5460, 5477, 5622, 5683, 5709, 5976, 5977, 6005, 6020, 6068, 6093, 6140, 6348, 6352, 6506, 7039, 7067, 7101, 7234, 7287, 7307, 7320, 7369, 7446, 7669, 7671, 8138, 8205, 8216, 8299, 8911, 8961, 8981, 9096, 9164, 9167, 9176, 9267, 9777, 10407, 10414, 10416, 10488, 10639, 10946, 10991, 11043, 11357, 11372, 11486, 11677, 11724, 11725, 11737, 11782, 11789, 11791, 11858, 11918, 11921, 12138, 12201, 12207, 12940, 13088, 13159, 14275, 14276, 14282, 14283, 14426, 14750, 14821, 14882, 15591, 16216, 16593, 17397, 18631, 23680, 24552, 24713, 25027, 25028, 25611, 25625, 28101, 29033, 29392, 30147, 6210) AND `spell_id` = 3391;
```
image

**Comment by claudiodfc** [comment]
> Running the Recommended query from your post results in a error with nothing displayed.
> 
> ```
> SELECT * FROM `spell_unique_caster`
> WHERE `caster_id` IN (232, 449, 478, 519, 669, 757, 862, 880, 1039, 1142, 1202, 1224, 1353, 1520, 1654, 1655, 1656, 1658, 1662, 1693, 1783, 1791, 1843, 1847, 1871, 2167, 2186, 2236, 2321, 2322, 2323, 2535, 2536, 2560, 2681, 2717, 2728, 2749, 2773, 2944, 3256, 3284, 3285, 3378, 3456, 3476, 3722, 3746, 3812, 3814, 3988, 3999, 4023, 4202, 4348, 4374, 4388, 4389, 4390, 4479, 4493, 4540, 4634, 4656, 4687, 4855, 5234, 5260, 5267, 5287, 5435, 5455, 5456, 5457, 5458, 5459, 5460, 5477, 5622, 5683, 5709, 5976, 5977, 6005, 6020, 6068, 6093, 6140, 6348, 6352, 6506, 7039, 7067, 7101, 7234, 7287, 7307, 7320, 7369, 7446, 7669, 7671, 8138, 8205, 8216, 8299, 8911, 8961, 8981, 9096, 9164, 9167, 9176, 9267, 9777, 10407, 10414, 10416, 10488, 10639, 10946, 10991, 11043, 11357, 11372, 11486, 11677, 11724, 11725, 11737, 11782, 11789, 11791, 11858, 11918, 11921, 12138, 12201, 12207, 12940, 13088, 13159, 14275, 14276, 14282, 14283, 14426, 14750, 14821, 14882, 15591, 16216, 16593, 17397, 18631, 23680, 24552, 24713, 25027, 25028, 25611, 25625, 28101, 29033, 29392, 30147, 6210) AND `spell_id` = 3391;
> ```
> 
> image

That query is for the Sniffs database from Brotalnia's repository:

https://github.com/claudiodfc/database

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
So doing a Audit of our Smart AI table I find the following entries with the trash ability being in use. I feel like you are on the right track, but may of been looking at the wrong spell ids as 3391 did not give me a hit on any of the npcs you have in your sql pr. Here is a list of all smart ai Thrash Seplls in used via creature entry and their name for quicker search. Also one is a GUID which i clearly label in the list. Also ensure no Smart AI chains are being broken in the process which is another thing your query would of done, so we need a way to idenitfy and correct each of the ones listed if applicable in the thrash removal.

**Casting 3391:**
18858 Wrathbringer
18214 Fenclaw Thrasher
22244 Unbound Ethereal
22174 Trigul
21040 Outraged Raven's Wood Sapling
22286 Fel Rager
21636 Vengeful Draenei
18660 Subjugator Vaz\'shir
19201  Mountain Gronn
18207 Murkblood Scavenger  

**Cast 8876 (Another spell dealing with thrash:**
Via GUID 52144 Crimson Monk 
100 Gruff Swiftbite
449 Defias Knuckleduster
478 Riverpaw Outrunner
519 Slark
1202 Tunnel Rat Kobold
1353 Sarltooth
1783 Skeletal Flayer
1791 Slavering Ghoul
2186 Carnivous the Breaker
2560 Highland Thrasher
2717 Dustbelcher Mauler
2728 Feral Crag Coyote
3256 Sunscale Scytheclaw
3378 Bael\'dun Officer
3456 Razormane Pathfinder
3722 Mystlash Flayer
3746 Foulweald Den Watcher
4023 Bloodfury Roguefeather
4493 Scarlet Avenger
5234 Gordunni Mauler
5267 Unliving Atal\'ai 
5435 Sand Shark
5455 Centipaar Wasp
5456 Centipaar Stinger
5457 Centipaar Swarmer
5458 Centipaar Worker
5459 Centipaar Tunneler
5460 Centipaar Sandreaver
5709 Shade of Eranikus 
6005 Shadowsworn Thug
7039 War Reaver
7234 Ferocitas the Dream Eater
7369 Deadwind Brute
7446 Rabid Shardtooth
8138 Sul'lithuz Broodling
8299 Spiteflayer
8981 Malfunctioning Reaver
9096 Rage Talon Dragonspawn
9176 Gor'tesh
9267 Smolderthorn Axe Thrower
9777 Flamekin Sprite
10407 Fleshflayer Ghoul 
10416 Bile Spewer 
10639 Rorgish Jowl
10991 Wildpaw Gnoll
11043 Crimson Monk 
11357 Son of Hakkar
11372 Razzashi Adder
11677 Taskmaster Snivvle
11782 Ambershard Destroyer
11791 Putridus Trickster 
12138 Lunaclaw
12201 Princess Theradras 
12207 Thessala Hydra 
12940 Vorsha the Lasher
13088 Masha Swiftcut
14282 Frostwolf Bloodhound
14283 Stormpike Owl
14750 Gurubashi Bat Rider
14821 Razzashi Raptor
14882 Atal\'ai Mistress
16593 Shattered Hand Brawler
17397 Shadowmoon Adept
18631 Cabal Cultist
23680 Plagued Proto-Dragon
29033 Spirit of Atha
6210 Caverndeep Pillager
	  

**Cast 3417 (Another spell dealing with thrash:**
4540 Scarlet Monk 
4855 Stonevault Brawler
7320 Stonevault Mauler 
8911 Fireguard Destroyer 
9164 Elder Diemetradon 
9167 Frenzied Pterrordax 
10414 Patchwork Horror 
10488 Risen Construct
11486 Prince Tortheldrin 
15207 The Duke of Fathoms
15305 Lord Skwol

**Cast 12787 (Another spell of thrash)**
232, Farmer Ray
669, Skullsplitter Hunter
757, Lost One Fisherman
862, Stonard Explorer
880, Erlan Drudgemoor
1039 Fen Dweller
1224 Young Threshadon
1520 Rattlecage Soldier 
1654 Gregor Agamand
1655 Nissa Agamand
1656 Thurman Agamand
1658 Captain Dargol
1662 Captain Perrine 
1693 Loch Crocolisk
1843 Foreman Jerris
1847 Foulmane
1871 Eliza\'s Guard
2167 Blackwood Pathfinder
2236 Raging Reef Crawler
2321 Foreststrider Fledgling
2322 Foreststrider
2323 Giant Foreststrider
2535 Maury "Club Foot" Wilkins
2536 Jon-Jon the Crow
2681 Vilebranch Raiding Wolf 
2749 Siege Golem
2773 Or'Kalar
2944 Boss Tho'grun
3285 Venture Co. Peon 
3476 Isha Awak
3812  Clattering Crawler
3814  Spined Crawler
3988  Venture Co. Operator
3999  Windshear Digger
4202  Gerenzo Wrenchwhistle
4348  Noxious Shredder
4374 Strashaz Hydra
4388  Young Murk Thresher
4389  Murk Thresher
4390  Elder Murk Thresher
4634  Kolkar Mauler
4656  Maraudine Mauler
4687  Deepstrider Searcher
5260  Groddoc Ape
5287  Longtooth Howler
5477  Noboru the Cudgel
5622  Ongeku
5683  Comar Villard
5976  Dreadmaul Brute
5977  Dreadmaul Mauler
6020  Slimeshell Makrura
6068  Warug\'s Bodyguard
6093  Dead-Tooth Jack
6140  Hetaera
6348  Wavethrasher
6352  Coralshell Lurker
6506  Ravasaur Runner
7067  Venture Co. Drone
7101  Warpwood Shredder
7287  Foreman Silixiz
7307  Venture Co. Lookout
8205  Haarka the Ravenous
8216  Retherokk the Berserker
8961  Felpaw Ravager
10946 Horgus the Ravager
11724 Hive'Ashi Swarmer
11725 Hive'Zora Waywatcher
11737 Stonelash Flayer
11789 Deep Borer
11858 Grundig Darkcloud
11918 Gogger Stonepounder
11921 Besseleth
13159 James Clark
14276 Scargil
14426 Harb Foulmountain
15591 Minion of Weavil
16216 Unholy Swords
24552 Sliver
25027 Frenzied Ghoul
25028 Skeletal Ravager
29392 Ravenous Jaws

**Comment by acidmanifesto** [comment]
> > Running the Recommended query from your post results in a error with nothing displayed.
> > ```
> > SELECT * FROM `spell_unique_caster`
> > WHERE `caster_id` IN (232, 449, 478, 519, 669, 757, 862, 880, 1039, 1142, 1202, 1224, 1353, 1520, 1654, 1655, 1656, 1658, 1662, 1693, 1783, 1791, 1843, 1847, 1871, 2167, 2186, 2236, 2321, 2322, 2323, 2535, 2536, 2560, 2681, 2717, 2728, 2749, 2773, 2944, 3256, 3284, 3285, 3378, 3456, 3476, 3722, 3746, 3812, 3814, 3988, 3999, 4023, 4202, 4348, 4374, 4388, 4389, 4390, 4479, 4493, 4540, 4634, 4656, 4687, 4855, 5234, 5260, 5267, 5287, 5435, 5455, 5456, 5457, 5458, 5459, 5460, 5477, 5622, 5683, 5709, 5976, 5977, 6005, 6020, 6068, 6093, 6140, 6348, 6352, 6506, 7039, 7067, 7101, 7234, 7287, 7307, 7320, 7369, 7446, 7669, 7671, 8138, 8205, 8216, 8299, 8911, 8961, 8981, 9096, 9164, 9167, 9176, 9267, 9777, 10407, 10414, 10416, 10488, 10639, 10946, 10991, 11043, 11357, 11372, 11486, 11677, 11724, 11725, 11737, 11782, 11789, 11791, 11858, 11918, 11921, 12138, 12201, 12207, 12940, 13088, 13159, 14275, 14276, 14282, 14283, 14426, 14750, 14821, 14882, 15591, 16216, 16593, 17397, 18631, 23680, 24552, 24713, 25027, 25028, 25611, 25625, 28101, 29033, 29392, 30147, 6210) AND `spell_id` = 3391;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > image
> 
> That query is for the Sniffs database from Brotalnia's repository:
> 
> https://github.com/claudiodfc/database

I apologzie for the misunderstanding on my part. I left a detail list review, Hopefully it will assist you in correcting your pr.
There are a few thrash spell ids in use. So i included the npc id and name to help.

**Comment by claudiodfc** [comment]
Thanks acid for the feedback. I wanted to clarify something though.

1. Other than the creatures I used in the query, no creature should cast thrash directly.
2. On the sniffs from Brotalnia, no creature casts the spells you just told which means that this spell is probably procced off another spell.
3. There's a lot of creatures you posted here that are from other expansions that the sniffs don't cover due to being vanilla/classic exclusive.

I suggest that creatures casting spell **Thrash** (12787, 3417 and 8876) from their SmartAI should be removed aswell.

**Comment by acidmanifesto** [comment]
> Thanks acid for the feedback. I wanted to clarify something though.
> 
> 1. Other than the creatures I used in the query, no creature should cast thrash directly.
> 2. On the sniffs from Brotalnia, no creature casts the spells you just told which means that this spell is probably procced off another spell.
> 3. There's a lot of creatures you posted here that are from other expansions that the sniffs don't cover due to being vanilla/classic exclusive.
> 
> I suggest that creatures casting spell **Thrash** (12787, 3417 and 8876) from their SmartAI should be removed aswell.

Feel free to rewrite the sql to handle whatever approach you feel like it should be taken. Just keep in mind azerothcore was originally a pserver source before it went open so at times alot of stuff can and has been determined to be wrong. I just want to ensure all information is provided to you so you can make any adjustment you will need done to ensure it goes thru as I do strongly support this PR. It doesnt have to correct everything as the sniff did not cover all expansions but look it over and see what adjustments you can make for what you do have the information on that was provided to you.

**Comment by claudiodfc** [comment]
I'll check later when I got more time the Vanilla NPCs and remove their Thrash spell accordingly. The other TBC/WOTLK can probably wait until more sniffs about those expansions exist.

**Comment by temperrr** [comment]
This appears to be WIP then? Ill mark it as such?

**Comment by claudiodfc** [comment]
After checking the database, these are the creatures above level 60 casting thrash currently with the other spell IDs. Since I don't have sniffs on them, I'll add them to the not to remove thrash from their list until Chromie progresses into the Outland, which should be enough time to have more sniffs on TBC wow.

| entry | minlevel |
| --- | --- |
| 1843 | 62 |
| 16216 | 81 |
| 24552 | 70 |
| 25027 | 69 |
| 25028 | 69 |
| 29392 | 79 |
| 11486 | 61 |
| 15207 | 62 |
| 15305 | 63 |
| 16593 | 70 |
| 17397 | 61 |
| 18631 | 69 |
| 23680 | 70 |
| 29033 | 80 |
| 18858 | 68 |
| 18214 | 62 |
| 22244 | 70 |
| 22174 | 71 |
| 21040 | 66 |
| 22286 | 70 |
| 21636 | 65 |
| 18660 | 68 |
| 19201 | 66 |
| 18207 | 64 |

**Review by acidmanifesto — APPROVED** [review]

**Comment by dualcorex** [comment]
I tested this in-game for about five minutes following the "How to test..." instructions and found the following...

[x] Using `.go c id 100` (Shouldn't cast Thrash). These mobs did NOT cast Thrash.
[ ] Using `.go c id 478` (Should cast Thrash). These mobs did NOT cast Thrash either.
[ ] If it works for a positive and negative test case, all other IDs are also working. None of these two mobs (100, 478) are casting Thrash that I could see.

cap2

**Comment by claudiodfc** [comment]
@dualcorex I've updated the SQL, could you please repeat the test? Thank-you very much 🙏🏼

**Comment by dualcorex** [comment]
> @dualcorex I've updated the SQL, could you please repeat the test? Thank-you very much 🙏🏼

Hi, I tested it again using your updates. This time I see Thrash from both `.go c id 100` and `.go c id 478`.

ID 100
c-100

ID 478
c-478

**Comment by claudiodfc** [comment]
Hello thanks for testing! As far as I can see only the Outrunner is casting Thrash which is the 478 I'd. So the test is correct

**Comment by dualcorex** [comment]
@claudiodfc Hi yes I will amend my test. You are correct. Since ID 100 and 478 ported me to different locations guess I thought it was differ mobs. Haha. Sorry for the miss understanding.

**Pull request merged**
