### PR TITLE
fix(DB/Creatures): Death Talon Wyrmguard should gain extra auras.

### LINKED ISSUE #10425: [BWL] Death Talon Wyrmguard issues
### Current Behaviour

Death talon wyrmguards only use stun

### Expected Blizzlike Behaviour
They should come in a random variety (all can be different)
Green - Single target sleep on the main tank. An offtank must be ready to pick up the loose wyrmguard until the effect wears off. Should be killed first as they take up tanking resources.
Red - Heavy fire damage. Extra healing required but otherwise not dangerous. Usually the second to go down if a green wyrmguard is present.
Black - 800 to 1200 Fire Damage applied directly to the tank. Does not apply a debuff and you'll need to check the Battle Log to notice it. Treat the same way as Red brood powers are.
Blue - Reduced attack speed and reduced movement speed. They do the least overall damage but are harder to establish aggro on due to the slowing effects. Blue wyrmguards should be killed last, unless a bronze is present.
Bronze - Main tank is constantly sent spinning, making it hard for them to build aggro. In addition, nearby players will take cleave damage. It is possible for melee DPS to continue attacking if they stand on the far side of the wyrmguard. Bronze Wyrmguards should be killed last.

Each wyrmguard will have a 100% weakness[citation needed] to a certain element (Frost, Fire, Shadow, Arcane, or Nature). All other magic damage is reduced by 75%.[citation needed] Because DPS is extremely lopsided in these pulls, it is very easy for casters to pull aggro through overnuking. Lower rank offensive spells must be used for these pulls, regulating damage to about 1000 per 3 seconds.

### Source
https://wowwiki-archive.fandom.com/wiki/Wyrmguard_Pack
https://youtu.be/oQUFxe47CKw?t=1641
### Steps to reproduce the problem

.go c id 12460

### AC rev. hash/commit
fb8a38c7b3067414a8aaa4450756cc9f9143239a

### Operating system

Linux

### Custom changes or Modules

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #10425

## Issues Addressed:

- Closes #10425

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go c id 12460`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@UltraNix the build is failing

**Comment by UltraNix** [comment]
Done.

**Comment by Kitzunu** [comment]
codestyle

**Comment by UltraNix** [comment]
@Kitzunu Done.

**Pull request merged**
