### PR TITLE
fix(Core/BWL): Nefarian spawns

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Nefarian spawns from third phase should now spawn on their death's position.
-  Removed Shadowbolt Volley changes from a previous PR of mine, it seems its behavior was correct after all.
-  Rogue class call should not be removed by using Vanish.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11299

## Tests Performed:

- Tested in-game.

## How to Test the Changes:

1. Go to BWL and engage Nefarian with a Rogue.
2. Check skeletons position and Nefarius volley.
3. Try to vanish rogue call.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by fputs** [comment]
[x] Skeletons spawn on top of the Drakonid body they came from

[ ] Nefarius casts shadow bolts, not Shadowbolt Volley during phase 1. This may be because there were only 2 characters in the raid during my test, I'm not sure. Need developer feedback on how to test this properly.

[x] Rogue class call is not removed by Vanish, Rogue is still immobilized

Not sure if this is intended, but Skeletons do not despawn when Nefarian dies.

**Comment by fputs** [comment]
Shadowbolt Volley properly activates when Nefarian tps within 30 yards of 2 characters

**Comment by Nefertumm** [comment]
@fputs 
```
Not sure if this is intended, but Skeletons do not despawn when Nefarian dies.
```
Updated.

**Comment by fputs** [comment]
Skeletons now despawn when Nefarian dies

**Pull request merged**
