### PR TITLE
Fix(Scripts/TrialOfTheCrusader):  solved issue #19834

### PR DESCRIPTION
**Pull request by zhouqingzq**
fix(Scripts/TrialOfTheCrusader): Touch of light/Touch of darkness should not deal damage to players with same color

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19834

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.Go to a fight with Twin Val'kyr
2.first player tanks 2 of them with dark/light debuff
3.wait second player to get debuff
4.second player should not get debuff "touch of light" with Light Essence or "touch of dark" with Dark Essence.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
Hi, I see that you replace the magic numbers 0,1,2,3 with the enum values, which is good, but how this changes can fix the issue?

**Comment by Helias** [comment]
is this PR ready to be tested/reviewed?

**Comment by zhouqingzq** [comment]
yes，I have tested it locally

**Comment by zhouqingzq** [comment]
> is this PR ready to be tested/reviewed?

yes，I have tested it locally

**Comment by zhouqingzq** [comment]
> Hi, I see that you replace the magic number 0,1,2,3 with the enum values, which is good, but how these changes can fix the issue?

sorry, I have modified the pr. I missed a line of modifications, the touch damage should be taken by the player who has touch debuff, not all the party member.

**Comment by TheSCREWEDSoftware** [comment]
@zhouqingzq It's the expected result?

image

**Comment by zhouqingzq** [comment]
> @zhouqingzq It's the expected result?
> 
> image

Player A obtained the Dark Essence and was affected by Light's Touch. Under normal circumstances, Player B should not take any damage. In this screenshot, Player A shows an absorb effect, which could be due to cheat god mode. The screenshot does not indicate whether Player B took any damage. If Player B did not take damage, that would be the expected outcome.

**Comment by Grimdhex** [comment]
Why do you have revert some recent commits as SpellQueue ?

**Pull request closed without merging**
