### PR TITLE
fix(Core/Spells): Lowered Magmadar Panic's effect radius to 30 yards.

### LINKED ISSUE #9115: [Molten Core] Magmadar Panic range possibly too high
### Current Behaviour

Magmadar Panic fears casters on max range

### Expected Blizzlike Behaviour

Magmadar Panic should fear up to 30 yards.

### Source

https://classic.wowhead.com/guides/magmadar-molten-core-strategy

### Steps to reproduce the problem

Go to MC
Magmadar
Be >30 yards
Get feared.

### Extra Notes

Should be checked what the range is at the moment, it appears to be to high.

### AC rev. hash/commit

009a52d1f13c

### Operating system

Win64

### Custom changes or Modules

Eluna

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #9115

## Issues Addressed:

- Closes #9115

## Tests Performed:

- Not tested

## How to Test the Changes:

Go to MC
Magmadar
Be >30 yards

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by T1ti** [comment]
Has this one been tested ? Need to make sure it hits players from **their** 30 yards range, I assume there's something going on with the caster radius

**Comment by T1ti** [comment]
Tested : Panic range is too short now, it seems to hit players in about 20 yards radius **around him**
image

**Comment by T1ti** [comment]
so revert/fix this

**Comment by T1ti** [comment]
additional testing done with the original value : (45 yards), it hits the players within rougly 33 yards, so about 3 extra yards

Note that when magmadar casts enrage, he grows by rougly 3 yards too ( my previous calculation was done aknowledging that)

**Comment by Nyeriah** [comment]
@UltraNix please check the feedback above once you've got some spare time

**Comment by UltraNix** [comment]
> Has this one been tested ? Need to make sure it hits players from **their** 30 yards range(which is 30yds from bounding box of the boss, not from midle point of the boss), I assume there's something going on with the caster radius

Not really true. When you are casting spell (in that ase it's an AoE source spell), the center is you (your position) and not your bounds. You can check that with some creatures with big bounding sizes e.g. Brutallus on SWP. So the spell is coming from your position to target bounds (because it's enough to be hit by spell. So in that case, Magmadar's size does not affect  this.

**Comment by UltraNix** [comment]
> additional testing done with the original value : (45 yards), it hits the players within rougly 33 yards, so about 3 extra yards
> 
> Note that when magmadar casts enrage, he grows by rougly 3 yards too ( my previous calculation was done aknowledging that)

Yep - Combat reach for this model is 12y in every repo. Changing to 15y should resolve problem, but not sure about it ;)

**Comment by T1ti** [comment]
Yep so something might be off with AC's calculations, don't know what.

**Comment by UltraNix** [comment]
Hmm, not really.
When he is enraged, then the calculations are okay: 12y bounding + 3y from enrage + 30y spell range = 45y total.
Maybe Blizz just simplified that?

**Comment by T1ti** [comment]
I was calculating 33 player range from magmadar, regardless of enrage or not, if he's enraged I just move 3 yards back, it's still the same.
.distance properly update the distance if he enrages

**Comment by T1ti** [comment]
magmadar's model collision(in creaturemodeldata.dbc) is different between 3.3.5 and 1.12
3.3.5 : 
image

1.12 : 
image

No idea if that matters or if it's only client side. But blizz clearly modified it, even in 1.13 (classic), it's the same as vanilla, but on retail (same client as classic), it's the updated values, same as Wotlk.

**Comment by T1ti** [comment]
Anyways it's not a big deal, players can still outrange it with range increase talents which give rougly +6 yards(36), they just have less room and have to stand at the max (33+ instead of 30+)

**Comment by UltraNix** [comment]
@T1ti Remember about player's size - 1.5y. 
I think I will leave it as it is.

**Pull request merged**
