### PR TITLE
feat(Core/Config): Naxxramas - Ability to change Sapphiron encounter requirement

### PR DESCRIPTION
**Pull request by avarishd**
## Changes Proposed:
-  Add worldserver config that enables/disables Sapphiron's requirement of having to defeat all end quater bosses in order to start the encounter **(disabled by default, as per patch 3.3.0**)

## Issues Addressed:

- Improve on #15048

## Tests Performed:

- tested in-game

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Objection - changes of this nature should go to a module as the source files should strictly contain 3.3.5 code. There's the mod-proression-system for this purpose.

**Comment by avarishd** [comment]
I have nothing against the progression mod, but the file does contain 3.3.5 code, with the simple addition of having the ability to be changed previous state (when/if needed) with a simple line. Icecrown buffs config are in the basket.

**Comment by Nyeriah** [comment]
It is a progression change and we do not intend to emulate every progression change in our script files, as such, **this should not be merged.**

Further discussion can be found here on how to implement this using the progression module: https://github.com/azerothcore/mod-progression-system/issues/308#issuecomment-1431055698 

It's cumbersome but we can always work towards an easier and better way to achieve those changes, without, however, bloating the core script files with progression changes (like MaNGOS has done over the years)

**Comment by avarishd** [comment]
Fair enough.

**Comment by 55Honey** [comment]
Still thanks for trying to help. It's the thought which counts 👍

**Pull request closed without merging**
