### PR TITLE
DB/Misc: Borean Tundra SAI

### PR DESCRIPTION
**Pull request by poszer**
Co-Authored-By: William Starrheld <starrheld@users.noreply.github.com>

Borean Tundra some NPC fixes

##### CHANGES PROPOSED:

-  Added SAI for Rocknar, Bloodspore Harvester, Bloodspore Roaster, Bloodspore Firestarter
-  Updated inhabittype for some creatures.
- Updated creature_texts
- Added Waypoint for bird

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/686

##### TESTS PERFORMED:

Yes, tested in game. Everything is fine. Thanks @STARRHELD 

##### HOW TO TEST THE CHANGES:

- Read the closing issue

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Pondaveia** [comment]
I know it hurts, but remember to update your SAI from " to '

**Comment by Nefertumm** [comment]
I'll do it for him, a lot of prs lately, he deserves it <3

**Comment by comix1988** [comment]
I tested this sql file and:
- Rocknar now casts his 2 spells and speaks at the beginning of the fight
- the bird at field D.E.T.H.A. now it flies in a circle;
- the various NPC Bloodspore now cast their respective spells;
- I don't know what InhabitType is;

good job @poszer

**Comment by Helias** [comment]
@comix1988 

immagine

Reference: www.azerothcore.org/wiki/creature_template#creature_template-InhabitType

**Pull request merged**
