### PR TITLE
DB: solve startup errors + disable faulty error

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/679

### HOW TO TEST

Make sure the removed:

- `mail_loot_template` (90, 119, 124, 140, 180, 183, 216, 217, 218, 270) 
-  `achievement_criteria_data` (4989, 4988, 5620, 5632, 5619, 4987) https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2129964/achievement+criteria+data

 don't break anything

### CODE REVIEW

**Comment by wetbrownsauce** [comment]
Tested. This PR breaks a few quests. 

The deleted `mail_loot_template` data in this PR results in the following:
- Quest [7735](https://wowgaming.altervista.org/aowow/?quest=7735) No longer includes a Rugged Armor Kit in the mail sent to the player after handing in. 
- Quest [9671](https://wowgaming.altervista.org/aowow/?quest=9671) No longer includes A Letter from the Admiral in the mail sent to the player after handing in. (which is important since it begins the next quest in the chain).
- Quest [10588](https://wowgaming.altervista.org/aowow/?quest=10588) No longer includes a Letter from Shattrath in the mail sent to the player after handing in. 
- Quest [13960](https://wowgaming.altervista.org/aowow/?quest=13960) & possibly also [13959](https://wowgaming.altervista.org/aowow/?quest=13959) No longer include the pet in the mail sent to the player after handing in. 

There are also some lunar festival mail rewards (lucky red envelopes should be mailed to players after handing in to certain elders) that I can't confirm due to the mail taking 6 hours to arrive, but based on the above I'm assuming these also are broken in this PR.  


**I have tested all of the above WITHOUT the PR, and they all send the correct items in the mail. Applying this PR directly breaks them.**

As for the achievement_criteria changes, most of the affected achievements are actually statistics for number of 5 player, 10 player, and 25 player instances entered. These don't appear to work before or after the PR, so the changes in their db table make no difference aside from removing start up warnings/errors.

**Comment by FrancescoBorzi** [comment]
@wetbrownsauce thanks a lot.

then there should be some issue with this error reporting: it says that it's "useless" but it's clear that it is not

**Comment by BarbzYHOOL** [comment]
Also travis broke the SQL, because travis comes in when we add branches directly to AC @FrancescoBorzi

**Comment by BarbzYHOOL** [comment]
@wetbrownsauce also you can change the mail delivery time for your dev server to 0 in the worldserver.conf

**Comment by wetbrownsauce** [comment]
@BarbzYHOOL I thought the worldserver.conf setting was for player-to-player mail delay, not quest mail?

**Comment by BarbzYHOOL** [comment]
It also affects auction house, so my guess is it affects everything

**Pull request closed without merging**
