### PR TITLE
feat(Core/Maps): Use a fixed offset instead of full collision height …

### LINKED ISSUE #4666: Razorfen Kraul Archers like to climb to the ceiling (possibly Wailing Caverns related too) Mob Pathing [$50]
Razorfen Kraul Archers like to climb to the ceiling (possibly Wailing Caverns related too) Mob Pathing

##### CURRENT BEHAVIOUR:

If you taunt a razorfen archer, he will try to reposition to hit you, this can involve climbing to the ceiling and becoming unreachable for melee.

WoWScrnShot_030121_141905

WoWScrnShot_030121_141823

This is not RFK specific. Sometimes the snakes in Wailing Caverns will climb higher and higher until they hit the roof.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Mobs should reposition on ground only, not float.

##### STEPS TO REPRODUCE THE PROBLEM:

RFK:
1. GO to Razorfen Krauk
2. Find ranged unit like Hunter or Animal Tamer
3. Taunt it and break line of sight, see how it behaves.

Wailing Caverns:
An easy reproduction step is to enter Wailing Caverns, and go the "left way" towards Lord Cobrahn. The non-elite snakes love to climb low walls, pillars, and low ceilings if you break LOS or make them move.

Tag a couple of snakes and start running in circles around pillars, or towards the lower ceilings.

##### AC HASH/COMMIT:

AzerothCore rev. c2f274e06dcf 2021-02-28 13:31:49 +0000 (master branch) (Unix, RelWithDebInfo)

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
There is a **[$50 open bounty](https://www.bountysource.com/issues/96852771-razorfen-kraul-archers-like-to-climb-to-the-ceiling-possibly-wailing-caverns-related-too-mob-pathing?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…when retrieving floor Z.

Port from TC.
Fixed #4666

## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #4666.

## Tests Performed:
- Tested with snakes in Wailing Caverns.
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Yehonal** [comment]
Not sure why we need that rename, but using that constant instead of the collision height is the right approach to find a proper floor coord. Indeed. Gonna approve it

**Review by Yehonal — APPROVED** [review]

**Comment by UltraNix** [comment]
@Yehonal Just same value, but the name more fit to current implementation.

**Comment by FrancescoBorzi** [comment]
good job @UltraNix

**Comment by pklloveyou** [comment]
good job

**Comment by UltraNix** [comment]
Updated.

**Pull request merged**
