### PR TITLE
fix(Core): Pet being slowed when owner is slowed

### PR DESCRIPTION
**Pull request by Hacki95**
## Changes Proposed:
- FollowMovementGenerator updates the Pets Movement speed to match their owners, lets add a check to see if the owner currently suffers from an Aura that slows him down, if yes then don't slow down the pet aswell.

## Issues Addressed:
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/4975
- Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/4772
- Closes: https://github.com/chromiecraft/chromiecraft/issues/279

## Tests Performed:

- Create Hunter/Warlock
- Summon Pet
- Get dazed or otherwise slowed by a spell
- Pet won't be slowed anymore

## How to Test the Changes:

- Apply patch.
- Create Hunter/Warlock.
- Get into a fight so a creature hits you until you are dazed.
- Let your pet attack another creature.
- Your pet should not be slowed anymore.

**Edit by Shin**: also test pets in general and make sure there is no regression

## Known Issues and TODO List:

- There seem to be certain edge cases where "owner->GetOwner()->GetAuraEffectsByType(SPELL_AURA_MOD_DECREASE_SPEED).empty()" returns true even when you have a slowing effect on you. This seems to happen to me when you had a certain combination of slow down effects once (even if they aren't active anymore).
- I have no idea why that happens and it seems to be a problem with the way we handle our lists, this problem persists until you restart the server. Is there a better way to check if the player is slowed?

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Hacki95** [comment]
@FrancescoBorzi Could you maybe take a look at the "Known Issues / TODO List" portion? Maybe you have an idea who might have an answer to my problem.

**Comment by Hacki95** [comment]
> 
> 
> > @FrancescoBorzi Could you maybe take a look at the "Known Issues / TODO List" portion? Maybe you have an idea who might have an answer to my problem.
> 
> checked, not sure why it happens. However, if I understood correctly, with this change would still be better than nothing.
> 
> But this should be **properly** tested before merging.
> 
> > REMEMBER: when testing a PR that changes something generic (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but especially check that the PR does not cause any regression (i.e. introducing new bugs).
> 
> > For example: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but we should test Y and Z as well.

Agreed. I plan on doing a few more tests to find out why .empty() doesn't work in some cases. 

@UltraNix since you seem very knowledgable about all corners of wow emulation, do you have by chance any idea if there is a better way to check if a player is slowed by an effect? Thanks in advance.

**Comment by UltraNix** [comment]
Becausee not all the snare/slow effects are SPELL_AURA_MOD_DECREASE_SPEED.
```
// Xinef: update speed of pet also
            if (!IsInCombat())
            {
                Unit* pet = ToPlayer()->GetPet();
                if (!pet)
                    pet = GetCharm();

                // xinef: do not affect vehicles and possesed pets
                if (pet && (pet->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED) || pet->IsVehicle()))
                    pet = nullptr;

                if (pet && pet->GetTypeId() == TYPEID_UNIT && !pet->IsInCombat() && pet->GetMotionMaster()->GetCurrentMovementGeneratorType() == FOLLOW_MOTION_TYPE)
                    pet->UpdateSpeed(mtype, forced);
                if (Unit* critter = ObjectAccessor::GetUnit(*this, GetCritterGUID()))
                    critter->UpdateSpeed(mtype, forced);
            }
```
  This is where pet's speedis synchornized with owner, but only out of combat.

**Comment by Hacki95** [comment]
> 
> 
> Becausee not all the snare/slow effects are SPELL_AURA_MOD_DECREASE_SPEED.
> 
> ```
> // Xinef: update speed of pet also
>             if (!IsInCombat())
>             {
>                 Unit* pet = ToPlayer()->GetPet();
>                 if (!pet)
>                     pet = GetCharm();
> 
>                 // xinef: do not affect vehicles and possesed pets
>                 if (pet && (pet->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED) || pet->IsVehicle()))
>                     pet = nullptr;
> 
>                 if (pet && pet->GetTypeId() == TYPEID_UNIT && !pet->IsInCombat() && pet->GetMotionMaster()->GetCurrentMovementGeneratorType() == FOLLOW_MOTION_TYPE)
>                     pet->UpdateSpeed(mtype, forced);
>                 if (Unit* critter = ObjectAccessor::GetUnit(*this, GetCritterGUID()))
>                     critter->UpdateSpeed(mtype, forced);
>             }
> ```
> 
> This is where pet's speedis synchornized with owner, but only out of combat.

Thanks a lot, I will take a look into this.

**Comment by mnclaras** [comment]
> // Xinef: update speed of pet also
>             if (!IsInCombat())
>             {
>                 Unit* pet = ToPlayer()->GetPet();
>                 if (!pet)
>                     pet = GetCharm();
> 
>                 // xinef: do not affect vehicles and possesed pets
>                 if (pet && (pet->HasFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_PLAYER_CONTROLLED) || pet->IsVehicle()))
>                     pet = nullptr;
> 
>                 if (pet && pet->GetTypeId() == TYPEID_UNIT && !pet->IsInCombat() && pet->GetMotionMaster()->GetCurrentMovementGeneratorType() == FOLLOW_MOTION_TYPE)
>                     pet->UpdateSpeed(mtype, forced);
>                 if (Unit* critter = ObjectAccessor::GetUnit(*this, GetCritterGUID()))
>                     critter->UpdateSpeed(mtype, forced);
>             }

Can it be related to this bug? [Issue 5250](https://github.com/azerothcore/azerothcore-wotlk/issues/5250)

**Comment by Hacki95** [comment]
I will give this one more try in a few days else I will close it for someone else to look at.

**Comment by FrancescoBorzi** [comment]
what's the status of this? needs more testing or changes?

**Comment by Hacki95** [comment]
> 
> 
> what's the status of this? needs more testing or changes?

It sometimes works and sometimes it doesnt. It seems to be like Ultranix said, its not always SPELL_AURA_MOD_DECREASE_SPEED. Weird thing is the spells I am testing are indeed this aura. It works once and then its bugging out. Do you know anyone I could ask about this?

**Comment by UltraNix** [comment]
Fixed by https://github.com/azerothcore/azerothcore-wotlk/commit/1becd73f09764e9e6ae27f35efdb514e860b12bf

**Pull request closed without merging**
