### PR TITLE
fix(DB/Creature): Use sniffed speeds for Heroic versions of TBC creatures

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  Speed was heavily polluted in heroics
-  Most creatures don't change speeds between difficulties
- Most sniffs are from heroics, so if they do change speeds it won't negatively impact heroics

## Issues Addressed:

- Closes 

## SOURCE:

Neifion's Classic sniffs

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Shouldn't this have already been handled with #14495? Is it just that more data is available for these creatures?

**Comment by Gultask** [comment]
If you go to the heroic maps ingame all entries that are sniffed will be of the normal versions. So the heroic versions never got fixed in the first place.

In all the instances where we compared speeds NormalxHeroic they were always the same. I think there might be some exceptions (Raging Flames from Netherbinder Sepethrea, for example)

**Comment by elthehablo** [comment]
How about the voidwalkers from Vorpil? Or were those correct? I'm too lazy to check the ids in here

**Comment by Gultask** [comment]
Without this PR the Heroic versions travel at 1.14 speed, the same as the majority of creature run speeds, which is slightly faster than the player

**Comment by elthehablo** [comment]
Really? They moved at blazing speeds when I was testing Vorpil on heroic. Might be patched now tho. This was before I made my PR, like a week before official SL release

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
