### PR TITLE
fix(GossipMenu) Dalaran guide guards

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. Download the branch with the changes
2. Test translations with different clients

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by M4th3m4tic4l** [comment]
works👍

**Review by M4th3m4tic4l — APPROVED** [review]

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Grimdhex** [comment]
What does this PR ?

**Comment by IntelligentQuantum** [comment]
> What does this PR ?

image

**Comment by pangolp** [comment]
> What does this PR ?

This pull request adds 3 broadcast text to a Dalaran guard gossip. It's those broadcast text, the texts always show you in English. With this change, and if there is the translation within the premises (which at least the Spanish is because I test it), it should change, based on the game client that is used.

**Comment by pangolp** [comment]
Thanks.

**Pull request merged**
