### PR TITLE
fix(Core/Command): Can comment closed tickets

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Before this PR, we couldn't comment a closed ticket.
Now we can.

I'd like to know if some server owner find this inconvenient (maybe because they don't trust their GMs etc)? I personally need this option but maybe we could improve the feature to be configurable.

@icenet @disclosurez @Si1ker what do you guys think about this?

### CODE REVIEW

**Comment by IceNet** [comment]
+Rep

**Comment by Si1ker** [comment]
@BarbzYHOOL Totally useful, let's go for it! 🌟 🐱

**Comment by BarbzYHOOL** [comment]
alright thanks guys

**Comment by FrancescoBorzi** [comment]
@Si1ker why are you removing labels from PRs? o_O

**Pull request merged**
