### PR TITLE
refactor(Core/Player): extract KillRewarder, TradeData and PlayerTaxi

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Moved 556 lines of code out of `Player.cpp`
- Updates https://github.com/azerothcore/azerothcore-wotlk/issues/6698

### CODE REVIEW

**Comment by Kitzunu** [comment]
Rename file from KillerRewarder to KillRewarder. Sounds better and it is what you use within the file. So it should match

**Comment by FrancescoBorzi** [comment]
> Rename file from KillerRewarder to KillRewarder. Sounds better and it is what you use within the file. So it should match

ah yes, good point, thanks

**Review by Kitzunu — CHANGES_REQUESTED** [review]
above

**Comment by Kitzunu** [comment]
no. Why did you merge it without making the changes?

**Pull request merged**
