### PR TITLE
fix(DB/SAI): fix quest Kaw the Mammoth Destroyer.

### PR DESCRIPTION
**Pull request by MarioJvPz98**
Modified SQL code for AC standards.

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 
[https://github.com/azerothcore/azerothcore-wotlk/issues/18181](https://github.com/azerothcore/azerothcore-wotlk/issues/18181)
## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

-- Raistlin
-- [NexXuZ_R](https://www.github.com/MarioJvPz98)
-- [CodigoWoW](https://www.github.com/Codigottv)

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [x] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
Okay with my tests I found some issues:

- AT works even when you're not on a mammoth (need a condition for that likely)
- he doesn't really jump on the mammoth on some occasions
- I couldn't loot the halberd after killing him

Overall this needs some work before it can be merged

**Comment by elthehablo** [comment]
In the meantime, it would be nice if someone else could test this as well

**Comment by elthehablo** [comment]
Also. I think the old script was pretty good https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+is%3Aclosed+mammoth perhaps instead of reconstructing the whole script we can just change some things that broke. Tbh looking at the script I can't quickly see what part broke because of combat movement (because that is the most likely culprit imo)

**Comment by MarioJvPz98** [comment]
It is a fix, although it needs to be fully polished, it could be done from there, right?

**Comment by elthehablo** [comment]
Ideally we want to fix the things from the old PR instead of re-inventing the wheel

**Comment by sudlud** [comment]
Can this be closed as the quest got fixed with #18501 now?

**Comment by pangolp** [comment]
> Can this be closed as the quest got fixed with #18501 now?

@MarioJvPz98 Is the problem solved?

**Comment by sudlud** [comment]
closing this for now, please feel free to repoen and update the PR if any issues with the quest should arise in the future!

**Pull request closed without merging**
