### PR TITLE
fix(DB/creature): Rabid Brown Bear Position

### PR DESCRIPTION
**Pull request by LukasVolgger**
## CHANGES PROPOSED:

- Update coordinates for creature 101032

## Before PR 

image

## After PR

image

## ISSUES ADDRESSED:
- None

## TESTS PERFORMED:
- Imported SQL
- Tested ingame

## HOW TO TEST THE CHANGES:

- Import SQL
- Clear WoW Cache
- .go c 101032

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Racknar0** [comment]
Test

image

**Comment by Gierlappen** [comment]
@Racknar0 Thx 4 testing!

**Comment by BarbzYHOOL** [comment]
gierlapen, do not forget the ":" in the commit titles!!!

**Comment by Gierlappen** [comment]
> gierlapen, do not forget the ":" in the commit titles!!!

👌

**Pull request merged**
