### PR TITLE
Create rev_1500226875532818300.sql

### PR DESCRIPTION
**Pull request by grimgravy**
**Changes proposed:**

-  Fixed Brewfest Building is Darkmoon Faire Building

**Target branch(es):** 1.x

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by talamortis** [comment]
what is this PR for?

**Comment by grimgravy** [comment]
To fix event error

**Comment by Yehonal** [comment]
Which event error? could you paste it?

**Comment by Yehonal** [comment]
Which event error? could you paste it? @grimgravy

**Comment by grimgravy** [comment]
Sorry for the delay my pc gave bad problem is already solved
error 
[error[1].txt](https://github.com/azerothcore/azerothcore-wotlk/files/1194111/error.1.txt)
game_event_creature` game event id (71) is out of range compared to max event id in `game_event`

**Comment by Yehonal** [comment]
in your sql you've added game event 70 to game_event table, but in game_event_creature you're inserting id 71. 

Maybe you have to change that value (?)

**Comment by Yehonal** [comment]
@grimgravy

**Comment by Ercules76** [comment]
There is event 71 too
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `description`, `world_event`) VALUES (71, '2013-01-06 01:01:00', '2020-12-31 06:00:00', 131040, 8639, 0, 'Darkmoon Faire Building (Mulgore)', 0);

**Comment by Yehonal** [comment]
Tested and it works

**Pull request merged**
