### PR TITLE
Fix XP disable NPC script

### PR DESCRIPTION
**Pull request by Foereaper**
## Changes Proposed:
- Fixes the script to use the xp toggle cost config option properly.

## Issues Addressed:

- Previously this config variable did not work, as the cost defined in the db would override this config option.

## Tests Performed:

- It builds, logic should be fine. Feel free to test ingame.

## How to Test the Changes:

- Set the config option to something else than 10g, it should now reflect properly ingame.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by avarishd** [comment]
The amount of gold is now properly shown in the box, but you've removed the logic for handling the gold.

**Comment by Foereaper** [comment]
Does the core not handle this automatically when a gossip option has moneyBox defined? It definitely does in PlayerGossip, so I assumed it was handled the same throughout the core.

**Comment by avarishd** [comment]
Afaik, there is no logic at all for [ScriptedGossip](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/AI/ScriptedAI/ScriptedGossip.cpp), thus usage of action(s), however there is for [PlayerGossip](https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/game/Entities/Player/PlayerGossip.cpp#L287).

**Comment by Foereaper** [comment]
I restored the money logic, although a little differently to prevent the amount of nesting in the original function.

**Comment by avarishd** [comment]
All works now, although I'm unsure about using auto to assign data type. Have to wait for the actual reviewers feedback on that.

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
