### PR TITLE
fix(Core/AI): more AI factories checks

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Follow up for https://github.com/azerothcore/azerothcore-wotlk/pull/11779
-  https://github.com/TrinityCore/TrinityCore/commit/d56a28afee19741c582ed8e16dbf8e30311f68ea
-  https://github.com/TrinityCore/TrinityCore/commit/9c24ec5c966da1a78ddd3df6023c6cab43111ebc
-  https://github.com/TrinityCore/TrinityCore/commit/d02f481d9ac8e1d1a7716368f609d53a5add0960
-  https://github.com/TrinityCore/TrinityCore/commit/877749cf3ffd479a87f7b3a7ac1b3703389c6cb3

## Issues Addressed:

- Closes -

## Tests Performed:

- Compiled, played a little bit in-game.

## How to Test the Changes:

Check some creatures with smart script, gobs, etc. Try mind-controlling moving creatures as well.

### CODE REVIEW

**Comment by Nefertumm** [comment]
@pklloveyou

**Comment by pklloveyou** [comment]
I just woke up

**Comment by pklloveyou** [comment]
It's good for me now, and pet mistakes are also solved

**Comment by pklloveyou** [comment]
```sql
UPDATE `creature_template` SET `AIName` = 'AggressorAI' WHERE `AIName` = 'AggresorAI';
```

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Nefertumm** [comment]
> ```sql
> AggresorAI
> ```

There are no entries with that kind of mistake, I've only put the ones who are mistaken.

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
