### PR TITLE
fix(DB/Spawning/Pathing) Eversong Woods cleanup and pathing #1

### PR DESCRIPTION
**Pull request by malcrom**
## Changes Proposed:
-  Remove some over spawning and add some missing spawns. Also added some missing pathing.

## SOURCE:
Official video and Sniff

## Tests Performed:
- No errors. Tested pathing in game and checked spawning.

## How to Test the Changes:
1. Install sql

### CODE REVIEW

**Comment by acidmanifesto** [comment]
To test
1. .go c 56027 and observe pathing
2. .go c 56028 and observe pathing
3. .go c 56029 and observe pathing

**Comment by claudiodfc** [comment]
## Strange Waypoint
image

## Issue 1
After they aggro and kill a lynx on the side of the road, one of them went to the waypoint destination while another one resumed his last position. This happened due to one aggroing first and another one following up. Maybe because they're linked? However one of them waits for the other guard to come back to the waypoint and they sync once again. It's very trivial and probably not related to this PR anyways.

image
image
image

**Comment by claudiodfc** [comment]
## Issue 2
Probably not related to this PR specifically but to the SmartAI, When waypoints are interrupted they don't resume, having NPCs stuck in places until the script triggers movement again, such as these cases:

image

**Comment by claudiodfc** [comment]
## Issue 3
Also probably not related to this PR, but looks like these murlocs pathing are missing inhabit type for swim?
image

**Comment by claudiodfc** [comment]
Tested all the changes. Overall looks very good, other than the things I've mentioned. 👍🏽

**Comment by malcrom** [comment]
Core handling of pathing is a separate thing. There is no inhabit type for swim in waypoint_data.

**Comment by acidmanifesto** [comment]
> Core handling of pathing is a separate thing. There is no inhabit type for swim in waypoint_data.

My inhabit removal pr that is pending will allow the creatures to path in water when given the swim ctm.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
