### PR TITLE
Staging [1]

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
This PR contains all the additions that `staging` branch has.

It will be merged after they have been tested.

In this package we have:

- ~Minor spell code refactoring~
- ~CMake changes to support MariaDB (thanks @Viste)~
- ~Improvement to the LOS system (thanks @Viste)~
- ~Time handling improvements  (thanks @Viste)~
- Fix distance calculation for spells (thanks @Viste)

# DO NOT MERGE DIRECTLY INTO MASTER

### CODE REVIEW

**Comment by Asherdoom** [comment]
checked instances collision paths and other various instance/raid enviromental fixes and bugs
checked world pathing and classes spells / abilities and gear stacking.

**Comment by BarbzYHOOL** [comment]
Very glad that you try the staging branch, are you on the discord? What are your names on the discord?

**Comment by comix1988** [comment]
sorry, I'm not on your discord

**Comment by FrancescoBorzi** [comment]
sadly, no one is using this branch, closing....

**Pull request closed without merging**
