### PR TITLE
Dep/Jemalloc: update to Jemalloc 5.2.1

### PR DESCRIPTION
**Pull request by Viste**
##### CHANGES PROPOSED:
-  update to Jemalloc 5.2.1 we have to old >_< (maybe partially reduce memory consumption)
##### HOW TO TEST THE CHANGES:
build 
run
watch
write
##### Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Viste** [comment]
@LichKing255 thanks

**Comment by FrancescoBorzi** [comment]
@Viste is there anything specific that should be checked or we can just merge it?

**Comment by Viste** [comment]
@FrancescoBorzi we can merge i think.
But It would be cool to see how to use memory with and without PR. Especially on windows.
As there was a lot of things fixed concerning leaks in windows

**Comment by LichKing255** [comment]
> @FrancescoBorzi we can merge i think.
> But It would be cool to see how to use memory with and without PR. Especially on windows.
> As there was a lot of things fixed concerning leaks in windows

I didn't see much of an impact on the Memory Leak I reported earlier.
And my problem continues.
https://github.com/azerothcore/azerothcore-wotlk/issues/2280
issue closed but there is a problem with some windows.
I don't know this is memory leak or vmaps problem, but i know there is a problem.
There have been many reports but the reason is not clear.
Even after my report someone else reported it and it has not closed yet
https://github.com/azerothcore/azerothcore-wotlk/issues/2233
I've reviewed Trinity Commit and there is no solution to test it. You probably just have to merge it

**Comment by Viste** [comment]
and?

**Comment by Mitradis** [comment]
after this "update" (which gives nothing!) i stop build AC. Ty Viste.

**Comment by Viste** [comment]
it's hard to live with mental illness

**Pull request merged**
