### PR TITLE
fix(Core/Spells): On autoshot interrupt send proper packet to cancel …

### LINKED ISSUE #5734: Hunter's auto attack does not stop for bandaging [$30]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Hunter's auto-shot will continue to tick and interrupt bandaging 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Bandage should stop all actions when activated. It is considered a channeled spell.
[https://wowwiki-archive.fandom.com/wiki/Channeling](https://wowwiki-archive.fandom.com/wiki/Channeling)
Testing with wand's auto-shoot works properly

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a hunter
2. Proceed to a training dummy
3. Range attack, and try to bandage
4.

##### EXTRA NOTES:

Original issue from Chiromicraft 
[https://github.com/chromiecraft/chromiecraft/issues/454](https://github.com/chromiecraft/chromiecraft/issues/454)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Did you fix this issue? Go claim the **[$30 bounty](https://www.bountysource.com/issues/98356231-hunter-s-auto-attack-does-not-stop-for-bandaging?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…autoshot clientside.

Fixed #5734.

## Changes Proposed:
-  Added `SendAttackSwingCancelAttack` to be sent on autoshot interrupt.

## Issues Addressed:

- Closes #5734
- Closes chromiecraft/chromiecraft#454

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1.Create a hunter
2. Proceed to a training dummy
3. Make sure you have option `Auto Attack / Auto Shot` enabled in `Options -> Combat` interface menu.
4. Range attack, and try to bandage

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by necropola** [comment]
Also
- Closes https://github.com/chromiecraft/chromiecraft/issues/454

**Comment by FrancescoBorzi** [comment]
> Also
> 
> * Closes [chromiecraft/chromiecraft#454](https://github.com/chromiecraft/chromiecraft/issues/454)

thanks @necropola , please @UltraNix don't forget about that

**Comment by UltraNix** [comment]
It's the same issue.

**Comment by necropola** [comment]
@UltraNix It is, but in another (ChroimieCraft not AzerothCore) repository. I don't think that it will automatically be marked as solved when this PR is merged, unless it's mentioned (Closes https://github.com/chromiecraft/chromiecraft/issues/454) in this PR, too.

But maybe I'm wrong and the automation is much smarter than I expected.

**Comment by FrancescoBorzi** [comment]
@necropola is right, unfortunately we need to mention both

**Pull request merged**
