### PR TITLE
feat(Core/Scripts): split the huge scriptloader into smaller pieces

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- WarheadCore/Warhead@85e4608
- WarheadCore/Warhead@8660f90
- WarheadCore/Warhead@96bc31924a5a418d37bd961ef2880f9072126348
- WarheadCore/Warhead@9e43365b3d7817b128ecfc6bfd74f4b2b6fc7c69

```sh
* Script configuration (static):
  |
  +- worldserver
  |   +- Commands
  |   +- Custom
  |   +- EasternKingdoms
  |   +- Events
  |   +- Kalimdor
  |   +- Northrend
  |   +- OutdoorPvP
  |   +- Outland
  |   +- Pet
  |   +- Spells
  |   +- World
  |

* Modules configuration (static):
  |
  +- worldserver
  |   +- mod-ah-bot
  |   +- mod-cfbg
  |   +- mod-eluna-lua-engine
  |   +- mod-server-auto-shutdown
  |   +- mod-transmog
  |

> Module (mod-ah-bot) using deprecated loader api
> Module (mod-cfbg) using deprecated loader api
> Module (mod-server-auto-shutdown) using deprecated loader api
> Module (mod-transmog) using deprecated loader api
```

## Issues Addressed:
- Part #4302
- Part #5721

## Tests Performed:
image

## How to Test the Changes:
- Test in game any script or module

## Known Issues and TODO List:
- [x] Merge #5333 in `master`
- [ ] Add new template for modules

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
build failing

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan merge conflicts

**Comment by Winfidonarleyan** [comment]
Can test this? Just build and check any script in the core

**Comment by FrancescoBorzi** [comment]
> Can test this? Just build and check any script in the core

@azerothcore/testers

**Comment by Sedatyf** [comment]
Hmmm that's weird. I pulled this PR and tried to CMake it, and I have an error.
Here is the error:
```
-- CMake version: 3.20.1
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
CMake Error at conf/dist/config.cmake:28 (message):
  The value (1) of your SCRIPTS variable is invalid! Allowed values are:
  none;static;dynamic;minimal-static;minimal-dynamic.  Set static
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


-- Configuring incomplete, errors occurred!
See also "D:/Documents/Universite_Boulot/PROJETS_DEV/azerothcore/build/CMakeFiles/CMakeOutput.log".
See also "D:/Documents/Universite_Boulot/PROJETS_DEV/azerothcore/build/CMakeFiles/CMakeError.log".
```

**Comment by Winfidonarleyan** [comment]
Use clean build dir

**Comment by Winfidonarleyan** [comment]
Any news?

**Comment by Sedatyf** [comment]
Sorry didn't find time to test it yet. I'm a bit busy this week

**Comment by Winfidonarleyan** [comment]
> Sorry didn't find time to test it yet. I'm a bit busy this week

Okay, no problem

**Comment by Sedatyf** [comment]
Yup, sorry, it's my fault! When conflicts will be merged, I'll definitely test it asap

**Comment by Kitzunu** [comment]
fixed

**Comment by Sedatyf** [comment]
> fixed

Damn you're fast. I'm testing it then

**Comment by Sedatyf** [comment]
I can't build in Visual and I can't CMake either
Here is issues raised by Visual
image

**Comment by Kitzunu** [comment]
Try delete cache in CMake

**Comment by Sedatyf** [comment]
My build folder was empty before launching the CMake command

image

**Comment by Kitzunu** [comment]
Do "Delete Cache" anyways, if that still fails after, search from CMake var SCRIPTS and change it to Static

**Comment by Sedatyf** [comment]
> Do "Delete Cache" anyways, if that still fails after, search from CMake var SCRIPTS and change it to Static

The static does the trick!

**Comment by Sedatyf** [comment]
CMake worked, Visual build worked, but worldserver crashed. I'm on Windows 10
Do you want the crash logs?

**Comment by Kitzunu** [comment]
I am compiling now to see if I also get the crash

**Comment by Kitzunu** [comment]
Did you build with any modules? did you do anything or did the worldserver just crash on startup?

I just compiled without modules and the worldserver starts without crashing

**Comment by Kitzunu** [comment]
- 🟢 CMake -> Works
- 🟢 Compiling -> Works
- 🟢 CreatureScript -> Works (Tested c id 16808 which yells when engaging in combat)

I have not tested Modules as I do not use them

**Comment by Sedatyf** [comment]
No modules, and the worldserver didn't fully loaded correctly, it crashed before the end

**Comment by Kitzunu** [comment]
Wild guess, have you updated the Database?

I got no crash or errors

**Comment by Sedatyf** [comment]
Hmmm I guess. I'll take a look at it

**Comment by Sedatyf** [comment]
> Wild guess, have you updated the Database as we are using latest master in the PR?
> 
> I got no crash or errors

You're definitely to good. The problem was the database

**Comment by Kitzunu** [comment]
I just merged a PR that changed DB structure beforebI updated this PR, so I knew it probably was that 👯

**Comment by Sedatyf** [comment]
I did a dungeon, auctioned an item, learnt and took a fly, learned some spells, wandered in the world, and nothing weird happened. No errors in the worldserver, no crash, nothing.
Do you want me to test a module @Winfidonarleyan @FrancescoBorzi @Helias?

**Comment by FrancescoBorzi** [comment]
@Sedatyf  thank you very much!

the modules appear to be correctly loaded from what I can see from the CI, so there shouldn't be need for additional testing:

```
Using modules configuration:
> AutoBalance.conf.dist
> duelreset.conf.dist
Unable to open 'GameObjectModels.dtree' file.
> mod_LuaEngine.conf.dist
> npc_beastmaster.conf.dist
> premium.conf.dist
> transmog.conf.dist
```

https://github.com/azerothcore/azerothcore-wotlk/runs/2878534053#step:9:51

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Very good, thanks for testing @Kitzunu and @Sedatyf!

**Comment by eTzmNcbkrng** [comment]
Getting this error when I try to install with Docker, same error when I try to manually configure with CMake.
```
-- CMake version: 3.16.3
CMake Error at conf/dist/config.cmake:28 (message):
  The value (ON) of your SCRIPTS variable is invalid! Allowed values are:
  none;static;dynamic;minimal-static;minimal-dynamic.  Set static
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)
```

**Comment by Kitzunu** [comment]
Delete cache, seg SCRIPT to Static

**Comment by Kitzunu** [comment]
Its due to CMake keeping the old SCRIPT variable which was a bool

**Comment by FrancescoBorzi** [comment]
> Its due to CMake keeping the old SCRIPT variable which was a bool

we should then update that value in all wiki pages and scripts such as docker, dashboard, etc...

cc @Winfidonarleyan

**Comment by Kitzunu** [comment]
there is no wiki about that. Winfi is already making a changelog for it. or maybe the Linux and mac has the variables in installation stuff from wiki. I don't know.

Nothing needs to be changed in wiki for windows at least

**Pull request merged**
