### PR TITLE
feat(Core/SmartScripts): SMART_ACTION_DISABLE_EVADE

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

[TC](https://github.com/TrinityCore/TrinityCore/commit/b18b05ee4af3b8ca64448f0c68c126ed711a579d)
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Please add the source when your cherry-pick things from TrinityCore, it not only speeds up the reviewing process but also keeps things fair with the original authors

**Review by Nyeriah — APPROVED** [review]

**Comment by IntelligentQuantum** [comment]
> Please add the source to the PR/commit when your cherry-pick things from TrinityCore, it not only speeds up the reviewing process but also keeps things fair with the original authors

I downloaded the source, I do not know who added these
If I find it, I will definitely do it

**Comment by Nyeriah** [comment]
You can search on TrinityCore's github repository

https://github.com/TrinityCore/TrinityCore/commit/b18b05ee4af3b8ca64448f0c68c126ed711a579d

**Comment by IntelligentQuantum** [comment]
> You can search on TrinityCore's github repository
> 
> [TrinityCore/TrinityCore@b18b05e](https://github.com/TrinityCore/TrinityCore/commit/b18b05ee4af3b8ca64448f0c68c126ed711a579d)

tnx

**Comment by Kitzunu** [comment]
Two things you can do to find:

1. Gitblame the code to hopefully find it. (Sometimes it isnt as easy if they made a lot of codestyle changes etc.)
2. Try and use Github search option at the top left in a repo to try and locate it. Usually their commit names have something to do with what got changed. And it can also find issues/prs

**Comment by Kitzunu** [comment]
Also pls fix codestyle

**Pull request merged**
