### PR TITLE
fix(DB\GameObject):Blood of Heroes respawn time, position and data corrections

### PR DESCRIPTION
**Pull request by Ragelezz**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8507
- Closes https://github.com/chromiecraft/chromiecraft/issues/2089

## Tests Performed:

- SELECT * FROM gameobject WHERE id IN (176213,176214); and see that there are duplicate spawns
- same query, respawn time is not the same to all objects
- guids 5281 and 5276 are underground

## How to Test the Changes:

1. SELECT * FROM gameobject WHERE id IN (176213,176214); no more duplicates
2. same query, respawn time is the same and adjusted gameobject_template data to match the original
3. guids 5281 and 5276 are above ground

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
? thart liknk gthisx PR

**Comment by Nyeriah** [comment]
There are two gameobjects related to this, a chest and a trap. The trap is supposed to spawn on top of the chest but our core doesn't handle that yet (https://github.com/azerothcore/azerothcore-wotlk/pull/8572 will address it).

The trap gameobject shouldn't be spawned @ database, it gets spawned together with the chest it is linked to (linked through gameobject_template).

I appreciate the time you've taken to look into this, but those changes are incorrect and they will end up breaking it in the future

The coords and spawn time need to be adjusted for the chest object, and it seems you're changing it for the trap, but the trap is going away soon enough so that part needs correction too

**Comment by Ragelezz** [comment]
So just delete the trap object?

**Comment by Nyeriah** [comment]
Hello,

Gameobject 176214 is not spawned anymore, the query in this PR returns no results. Please check if any changes are still necessary after the latest updates.

Thank you for your time

**Comment by Ragelezz** [comment]
I just replaced trap object with the proper lootable object as needed, no need to do other things now.

**Comment by Nyeriah** [comment]
Okay, so if nothing else is required, is it safe to close this PR? The SQL query here doesn't change any rows anymore.

**Comment by Ragelezz** [comment]
Yes.

**Pull request closed without merging**
