### PR TITLE
refactor(Core/ScalingStatValue): Allow use larger statistics on items

### PR DESCRIPTION
**Pull request by Illunix**
I think players should be able to use items with larger statistics without core edits.

## HOW TO TEST THE CHANGES:

1. Recompile, clear client cache and log in game : Blizzlike items stats shouldn't had changed.
2. Recompile, clear client cache, create a custom item with stats > 32767 : new stats items shoudln't be limited to 32767.

### CODE REVIEW

**Comment by Illunix** [comment]
Moved to https://github.com/azerothcore/azerothcore-wotlk/pull/3154

**Comment by Shard-MW** [comment]
Good for me, I'm using this for years and working fine :)
Thanks for your PR @Illunix

**Comment by Kitzunu** [comment]
Isnt it better to ALTER and CHANGE instead of updating the base SQL?
If you do this people who already use the core wont get the changes, right?

**Comment by Illunix** [comment]
> Isnt it better to ALTER and CHANGE instead of updating the base SQL?
> If you do this people who already use the core wont get the changes, right?
Done @Kitzunu

**Comment by Illunix** [comment]
I tested it and everything works

**Comment by Kitzunu** [comment]
Why close?

**Comment by Illunix** [comment]
I'll open new in a moment, I fucked up one thing @Kitzunu

**Comment by Kitzunu** [comment]
You can always revert any commits you make to a pr :P

**Comment by Illunix** [comment]
Moved to https://github.com/azerothcore/azerothcore-wotlk/pull/3156 Please merge @Kitzunu

**Pull request closed without merging**
