### PR TITLE
Fixxing the gunship battle cannons in icecrown

### PR DESCRIPTION
**Pull request by qwe900**
Getting energy on cast not on hit

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

[https://youtu.be/nSDn2m0ThsI?t=33](https://youtu.be/nSDn2m0ThsI?t=33)
## Tests Performed:

- 
- 

## How to Test the Changes:

1. go to gunship battle
2. enter gun
3. shot

## Known Issues and TODO List:

may theres is a cleaner way to do it
- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Ragelezz** [comment]
Works.

**Review by Ragelezz — CHANGES_REQUESTED** [review]
break not return at line 1955

**Comment by Kitzunu** [comment]
Hacks... Try making a generic spellscript instead please

**Comment by Ragelezz** [comment]
Or a spellscript inside gunship file but I doubt none of the bosses require more attention.

**Comment by Kitzunu** [comment]
I'd prefer it to ve generic incase we find more cases like this

**Comment by qwe900** [comment]
> 
> 
> break not return at line 1955

if we break we just leave the switchcase and generate power on cast and hit so we get double energy.

A Generic spellscript will also not work i think because the spelleffect is handled before and will automaticly generate the power.

**Comment by qwe900** [comment]
> 
> 
> Or a spellscript inside gunship file but I doubt none of the bosses require more attention.

There are few more bugs in IceCrownCitadel.
Gunship artillery does not work , the target selection is wrong and the spell is wrong i think. 
There is also no knockback on artilly hit.

Professor debuff on tank does not stack in last phase. 

And as Healer you dont have a chance to win the fight against the mob where u will be teleported to. Because the NPC u heal dont get the dmg buff.

**Comment by Ragelezz** [comment]
As said, ICC might need a rework later.
To this PR, you can remove the Energize effect from spell via SpellMgr and make a spellscript to handle properly on cast in gunship file. Generic spellscripts SHOULD NOT be involved in instance scripts at all.

**Comment by Kitzunu** [comment]
Fair point.

Cc @Nyeriah do you know of a better way of doing it without hardcoding stuff?

**Comment by Nyeriah** [comment]
@Kitzunu this may have to do with that issue with spelleffects being executed in the wrong order, eff1 should execute independently of the result from eff0

**Comment by Kitzunu** [comment]
Oh another one of those. Then we shouldnt touch it until a generic fix is made imo

**Comment by qwe900** [comment]
theres not spelleffectapplyfix on azerothcore so how to overite this.

**Comment by Kitzunu** [comment]
It is a general bug in the core, that covers more spells. eg. https://github.com/azerothcore/azerothcore-wotlk/issues/8484 

So it needs a general fix in the core, to make the execution order work as it should. Per Nyeriah's comment

**Comment by qwe900** [comment]
so editing 
boss_icecrown_gunship_battle.cpp

`class spell_igb_cannon_blast : public SpellScriptLoader
{
public:
    spell_igb_cannon_blast() : SpellScriptLoader("spell_igb_cannon_blast") { }

    class spell_igb_cannon_blast_SpellScript : public SpellScript
    {
        PrepareSpellScript(spell_igb_cannon_blast_SpellScript);

        bool Load() override
        {
            return GetCaster()->GetTypeId() == TYPEID_UNIT;
        }

        void CheckEnergy()
        {
            if (GetCaster()->GetPower(POWER_ENERGY) >= 100)
            {
                GetCaster()->CastSpell(GetCaster(), SPELL_OVERHEAT, true);
                if (Vehicle* vehicle = GetCaster()->GetVehicleKit())
                    if (Unit* passenger = vehicle->GetPassenger(0))
                        sCreatureTextMgr->SendChat(GetCaster()->ToCreature(), SAY_OVERHEAT, passenger);
            }
        }
        void PowerGain()
        {
            if (GetCaster()->GetPower(POWER_ENERGY) < 100)
            {
                GetCaster()->SetPower(POWER_ENERGY, GetCaster()->GetPower(POWER_ENERGY) + urand(6, 10));
               
            }
        }

        void Register() override
        {
            OnCast += SpellCastFn(spell_igb_cannon_blast_SpellScript::PowerGain);
            AfterHit += SpellHitFn(spell_igb_cannon_blast_SpellScript::CheckEnergy);
        }
    };

    SpellScript* GetSpellScript() const override
    {
        return new spell_igb_cannon_blast_SpellScript();
    }
};`

and 
SpellMgr.cpp
`    //canon fix icc
    ApplySpellFix({69399, 70172}, [](SpellEntry* spellInfo)
    {
        spellInfo->Effect[EFFECT_1] = 0;
    });`

is better yes ?

**Comment by Nyeriah** [comment]
> so editing boss_icecrown_gunship_battle.cpp
> 
> `class spell_igb_cannon_blast : public SpellScriptLoader { public: spell_igb_cannon_blast() : SpellScriptLoader("spell_igb_cannon_blast") { }
> 
> ```
> class spell_igb_cannon_blast_SpellScript : public SpellScript
> {
>     PrepareSpellScript(spell_igb_cannon_blast_SpellScript);
> 
>     bool Load() override
>     {
>         return GetCaster()->GetTypeId() == TYPEID_UNIT;
>     }
> 
>     void PowerGain()
>     {
>         GetCaster()->SetPower(POWER_ENERGY, GetCaster()->GetPower(POWER_ENERGY) + urand(6, 10));
>         if (GetCaster()->GetPower(POWER_ENERGY) >= 100)
>         {
>             GetCaster()->CastSpell(GetCaster(), SPELL_OVERHEAT, true);
>             if (Vehicle* vehicle = GetCaster()->GetVehicleKit())
>                 if (Unit* passenger = vehicle->GetPassenger(0))
>                     sCreatureTextMgr->SendChat(GetCaster()->ToCreature(), SAY_OVERHEAT, passenger);
>         }
>   
> 
>     }
> 
>     void Register() override
>     {
>         OnCast += SpellCastFn(spell_igb_cannon_blast_SpellScript::PowerGain);
>        
>     }
> };
> 
> SpellScript* GetSpellScript() const override
> {
>     return new spell_igb_cannon_blast_SpellScript();
> }
> ```
> 
> };`
> 
> and SpellMgr.cpp ` //canon fix icc ApplySpellFix({69399, 70172}, [](SpellEntry* spellInfo) { spellInfo->Effect[EFFECT_1] = 0; });`
> 
> is better yes ?

I don't understand why the spellmgr part is necessary. But changing that spell script from AfterHit to OnCast will probably solve it, yes? I didn't know those spells already had a spell script, but it's likely the issue here, yeah (perhaps the only issue).

**Comment by qwe900** [comment]
> 
> 
> > so editing boss_icecrown_gunship_battle.cpp
> > `class spell_igb_cannon_blast : public SpellScriptLoader { public: spell_igb_cannon_blast() : SpellScriptLoader("spell_igb_cannon_blast") { }
> > ```
> > class spell_igb_cannon_blast_SpellScript : public SpellScript
> > {
> >     PrepareSpellScript(spell_igb_cannon_blast_SpellScript);
> > 
> >     bool Load() override
> >     {
> >         return GetCaster()->GetTypeId() == TYPEID_UNIT;
> >     }
> > 
> >     void PowerGain()
> >     {
> >         GetCaster()->SetPower(POWER_ENERGY, GetCaster()->GetPower(POWER_ENERGY) + urand(6, 10));
> >         if (GetCaster()->GetPower(POWER_ENERGY) >= 100)
> >         {
> >             GetCaster()->CastSpell(GetCaster(), SPELL_OVERHEAT, true);
> >             if (Vehicle* vehicle = GetCaster()->GetVehicleKit())
> >                 if (Unit* passenger = vehicle->GetPassenger(0))
> >                     sCreatureTextMgr->SendChat(GetCaster()->ToCreature(), SAY_OVERHEAT, passenger);
> >         }
> >   
> > 
> >     }
> > 
> >     void Register() override
> >     {
> >         OnCast += SpellCastFn(spell_igb_cannon_blast_SpellScript::PowerGain);
> >        
> >     }
> > };
> > 
> > SpellScript* GetSpellScript() const override
> > {
> >     return new spell_igb_cannon_blast_SpellScript();
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > };`
> > and SpellMgr.cpp ` //canon fix icc ApplySpellFix({69399, 70172}, [](SpellEntry* spellInfo) { spellInfo->Effect[EFFECT_1] = 0; });`
> > is better yes ?
> 
> I don't understand why the spellmgr part is necessary. But changing that spell script from AfterHit to OnCast will probably solve it, yes? I didn't know those spells already had a spell script, but it's likely the issue here, yeah (perhaps the only issue?).

Because the effect1 will gain the power after hit which is wrong. So this override it and let handle the spellscript(which oldway just checks the power for overheating ) also gains power now.

**Pull request closed without merging**
