### PR TITLE
fix(Core/Loot): Fixed processing duplicated loot item within different groups.

### LINKED ISSUE #10498: [LootMgr] Lootable items are incorrectly processing item-reference tables causing unexpected loot
### Current Behaviour

LootGroup rolls between items for each Reference separately which causing each possible loot to rolled on different order

### Expected Blizzlike Behaviour

It ruins the RNG between items with 100% chance.
Should first fetch each lootable items from the item-references then check if player is allowed to loot (and soon), then _roll_ which item should be added (and how many) to the loot.

### Source

_No response_

### Steps to reproduce the problem

Let's take a look at item `52001`, should loot a shoulder or a ring (both with 100% chance according to the database)

1. Create a plate character
2. Add 4x Foror's Crate `.additem 23162 4`
2. Add 161 satchel `.additem 52001 161`
3. Open them all `/use Satchel of Helpful Goods`
4. See the ring has around ~6-7% drop chance for plate
5. Repeat with different type of armor, because the shoulder is then rolled at different times

### Extra Notes

See how the order of the roll based on how early the LootGroup rolls for the item, it's visually very visible when a cloth user rolls, the cloth shoulder is rolled with the ring very early which gives the illusion of normal behaviour.
The ring is rolled early on, but then it gets rerolled each time a shoulder gets rolled from each reference, therefore the chance to get the ring for plate users are very low, because the ring might be already replaced by other armor type of shoulder.

alt text
alt text
alt text
alt text

### AC rev. hash/commit

AzerothCore rev. dfa28e4f7dfe 2022-02-01 18:01:42 -0300 (master branch) (Win64, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1m  14 Dec 2021 (library: OpenSSL 1.1.1m  14 Dec 2021)
Using Boost version: 1.78.0
Using MySQL version: 80028
Using CMake version: 3.22.2
Compiled on: Windows 10.0.19042
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in C:/AzerothCore/build/bin/RelWithDebInfo/Data/maps. Total size: 252191207 bytes
vmaps directory located in C:/AzerothCore/build/bin/RelWithDebInfo/Data/vmaps. Total size: 658130721 bytes
mmaps directory located in C:/AzerothCore/build/bin/RelWithDebInfo/Data/mmaps. Total size: 2199390740 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.6-dev
Using World DB Revision: 2022_02_01_01
Using Character DB Revision: 2022_01_29_00
Using Auth DB Revision: 2021_11_06_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #10498

## Issues Addressed:

- Closes #10498
- Closes https://github.com/chromiecraft/chromiecraft/issues/3412

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.additem 23162 4`
`.additem 52001 100`
Open all satchels
See the ring has around ~50% drop rate.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by malcrom** [comment]
Will this affect the updated loot for level 1-5 where duplicate items are dropped?

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
There are loots for level 1 to 5 players that are duped dropped in retail in starter zones which is blizzlike and still present even in current expansions of retail. Are we able to make a exception for that? or are we changing that up?

**Comment by UltraNix** [comment]
@malcrom @acidmanifesto Need some examples of such entries.

**Comment by acidmanifesto** [comment]
> @malcrom @acidmanifesto Need some examples of such entries.

pretty much all the starter zones for example do drop dupe grey trash items, up to level 10 to 15 of the character.

**Comment by UltraNix** [comment]
@acidmanifesto I need exact entry of mob.

**Comment by acidmanifesto** [comment]
Human Start zone for example:

https://www.wowhead.com/wotlk/npc=69/diseased-timber-wolf
https://www.wowhead.com/wotlk/npc=299/diseased-young-wolf
https://www.wowhead.com/wotlk/npc=6/kobold-vermin
https://www.wowhead.com/wotlk/npc=38/defias-thug

**Comment by UltraNix** [comment]
@Nefertumm @acidmanifesto I see that max 3 duplicated items can be dropped from one group. So I see no regression here.

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
