### PR TITLE
fix(Core/Handlers): Adjust start swing handler.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:

This PR proposes changes to:
-  [X] Core (handlers).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11719
- Closes https://github.com/chromiecraft/chromiecraft/issues/3495
- Likely closes https://github.com/chromiecraft/chromiecraft/issues/7070
- Might close https://github.com/chromiecraft/chromiecraft/issues/7001

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [X] This pull request requires further testing.
So this fix is weird. From what I understand, it's trying to avoid a null pointer being floated along the way, but the issue is that when it gets to the removed function and stops the attack, it breaks the client and the client can no longer auto attack anything ever again. The behavior can easily be seen (iirc) by doing something like casting the aether ray wrangling rope but removing the target before the cast finishes, or by using the macro in the Noggenfogger issue. I don't know if the proposed change is necessarily correct, but I do know that it fixes the issues seen. I also know I would like thorough testing to be done on this PR if at all possible.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Need to check if the remaining code doesn’t crash or cause issues after it’s removed (the variable is used below and will be dereferenced/null if there’s no enemy)

**Comment by heyitsbench** [comment]
I did test it a bit and I could not get it to crash trying everything I observed causing the auto attack issue, nor did I find anything not working as (I believe) it should, but yea, if anyone else can give this a solid test, that'd be swell.

**Comment by heyitsbench** [comment]
Tested once again, still could not find any issues and had no crashes.

**Comment by PkllonG** [comment]
I'm using the Currently no players have found the bug

**Pull request merged**
