### PR TITLE
fix(Core/Spells): Fix wintergrasp spells yards

### PR DESCRIPTION
**Pull request by Pondaveia**
##### CHANGES PROPOSED:

Changed the radius spell effect of following spells:

- http://wotlk.cavernoftime.com//spell=51422
- http://wotlk.cavernoftime.com//spell=57610
- http://wotlk.cavernoftime.com//spell=50999
- http://wotlk.cavernoftime.com//spell=50990

###### ISSUES ADDRESSED:

Closes #1327 

##### TESTS PERFORMED:

Didn't test.

##### HOW TO TEST THE CHANGES:

1. Go to Wintergrasp and use cannon, machines
2. Cast spells mentioned and see damage radius index.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Knindzagxg** [comment]
Tested all goodie.

**Comment by FrancescoBorzi** [comment]
good job @Pondaveia and @Knindzagxg

**Comment by xDevICCI** [comment]
good

**Comment by BarbzYHOOL** [comment]
good if the values are right

**Comment by poszer** [comment]
> good if the values are right

They re not

**Comment by solidmaxtor** [comment]
The Spell 50989 is actual default in wintergasp catapults

**Pull request merged**
