### PR TITLE
fix(DB/Creature): [Loot] Unyielding mobs low drop of Runecloth

### PR DESCRIPTION
**Pull request by Carriola-wotlk**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19904
- Closes chromiecraft/chromiecraft#5784

I also changed drop rate of Netherweave Cloth (it was too high, it was 60%). Here are the changes:

Unyielding Footman
- Runecloth chance 50 (chance was 20)
- Netherweave Cloth chance 25 (chance was 60)
- GroupId 1

Unyielding Sorcerer
- Runecloth chance 50 (chance was 20)
- Netherweave Cloth chance 25 (chance was 60)
- GroupId 1

Unyielding Knight
- Runecloth chance 50 (chance was 20)
- Netherweave Cloth chance 25 (chance was 60)
- GroupId 1

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
What are the sources on this?

**Comment by elthehablo** [comment]
I see. Wowhead. Unfortunately not a reliable source. It's best to get some second source to check these numbers with. We can either check cmangos databases or using the law of big numbers by killing these on a TBC/wotlk/cataclysm live server

**Comment by alecsci** [comment]
@elthehablo, isn't wotlk wowhead good enough ?

**Comment by elthehablo** [comment]
It depends on the issue. The problem is that you just cannot trust those numbers.

Items that shouldn't even drop off of those creatures sometimes show up there.

**Comment by Gultask** [comment]
My take on this is that cloth at these numbers we can find the intuit the chances by looking at Wowhead's numbers. In this case:
50% for Runecloth
25% for Netherweave

My only question is: Can they drop both cloth at the same time?
Because if they can, then the current method is fine.
If they **cannot** there are 2 possibilities:
1. Only one cloth can drop at a time, at the same percentages, so they'd only need the same GroupID
2. Level 59 creatures drop Runecloth while level 60 creatures drop Netherweave. We don't have a clean system for that so we normally just go with the solution to the first possibility :P

I'm trying to recall if Hellfire Peninsula creatures can drop both cloths at the same time, but as a rule of thumb creatures normally can't so what I'd do is set all Runecloth to 50, all Netherweave to 25, and set both to the same GroupId, so only one cloth can drop at any one point.

**Comment by Carriola-wotlk** [comment]
> I'm trying to recall if Hellfire Peninsula creatures can drop both cloths at the same time, but as a rule of thumb creatures normally can't so what I'd do is set all Runecloth to 50, all Netherweave to 25, and set both to the same GroupId, so only one cloth can drop at any one point.

ok, so I edit chances (Runecloth to 50% and Netherweave to 25%) and set GroupId 1 for both

**Review by sudlud — APPROVED** [review]

**Pull request merged**
