### PR TITLE
fix(Core): Crashfix.

### LINKED ISSUE #13145: [server] world server crash 0926
### Current Behaviour

crash log :

https://gist.github.com/mpfans/476f4fe9491916ff3b2db28bdf9b4d2d

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

1f472bddd395073bf2a2d146ecb66489b36015fb

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### LINKED ISSUE #13329: [server] world server crash 1006
### Current Behaviour

crash log :

https://gist.github.com/mpfans/d7cca4566bbf4610c2a7f87346fccdca

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

6c3fc2603b46c84cd4334030f4bf7b57857e0241

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #13329
Fixes #13145

Supersedes #13154

## Issues Addressed:

- Closes #13329
- Closes #13145

## Tests Performed:

- Not tested.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by mpfans** [comment]
> @mpfans Please, test it.

I don't know how to reproduce it. I can only use it and see if it will crash again

**Comment by UltraNix** [comment]
Okay.

**Comment by Gultask** [comment]
https://user-images.githubusercontent.com/100873791/197331640-1dc27099-e68c-4218-b599-ef4ab5ff95ae.mp4

I haven't tested yet but this is how Master of Elements works in WotLK Classic with periodic spells and AoE:
 - Living Bomb periodic crits **do not** trigger Master of Elements
 - Living Bomb's explosion can only trigger Master of Elements once, regardless of how many crits there were.
 - With Blizzard, there can only be a maximum of one proc per tick, regardless of how many crits there were
 - With Flamestrike the same applies, only one proc, regardless of how many crits
 - Arcane Explosion the same, only one proc maximum per cast

Mana regained:
 - Living Bomb: 148 (Mana cost of 493)
 - Blizzard: 62 (Mana cost of 1658)
 - Flamestrike: 202 (Mana cost of 672)
 - Arcane Explosion: 148 (Mana cost of 493)

**Comment by UltraNix** [comment]
@Gultask This PR is only about crashfix. If there are some bugs on our core, please open a new ticket.

**Comment by mpfans** [comment]
After 4 days of testing, no crash was found. It is recommended to merge

**Comment by mpfans** [comment]
Please merge it first

**Review by IntelligentQuantum — APPROVED** [review]

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
