### PR TITLE
Simplify quest_template table to match trinitycore's table

### LINKED ISSUE #1119: Simplify quest_template table
This task is part of https://github.com/azerothcore/azerothcore-wotlk/issues/1118 and aims to simplify the structure of the `quest_template` table by moving several fields into new separate tables.

The following tasks can be done sequentially so one can re-use the commits from tc:

1) Move some fields from `quest_template` into the new table `quest_template_addons`

https://github.com/TrinityCore/TrinityCore/commit/5178395a4f973fdb0b9657e54f06e62a6e2d5111

2) Move some fields from `quest_template` into the new tables `quest_details`, `quest_request_items` and `quest_offer_reward`

https://github.com/TrinityCore/TrinityCore/commit/f7c7b92ef3c7f600276495f6d28061716fba0c23

3)  Some refactoring/corrections
https://github.com/TrinityCore/TrinityCore/commit/bc67016e7bfe8ffcd7220897c44e4d49d1392834
https://github.com/TrinityCore/TrinityCore/commit/b41e0156dbc084ec35603cb30492e0410eb697dd
https://github.com/TrinityCore/TrinityCore/commit/b1d773f3d50a45051066281f2e1c5f3407fd424c
https://github.com/TrinityCore/TrinityCore/commit/4a532a71b655945f394fecfe4a2177b2618a6d59

### PR DESCRIPTION
**Pull request by Nefertumm**
##### CHANGES PROPOSED:

-  Changed a lot of variable names.
-  Added quest_details, quest_request_items, quest_offer_reward and sort some columns.
-  Delete some useless iterations.

###### ISSUES ADDRESSED:

Closes #1119 

##### TESTS PERFORMED:

Windows: It compiles, the server starts without errors and everything seems fine when you take a quest.

##### HOW TO TEST THE CHANGES:

Just pick some quest and complete them.

##### KNOWN ISSUES AND TODO LIST:
 -

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Nefertumm thanks a lot for working on this!

What about the table `quest_template_addon´ ? I couldn't find it in your diff

**Comment by wetbrownsauce** [comment]
The changes so far don't seem to cause any issues. I did some quests in valley of trials and thousand needles, everything was correct and worked properly.

**Comment by Nefertumm** [comment]
> 
> 
> @Nefertumm thanks a lot for working on this!
> 
> What about the table `quest_template_addon´ ? I couldn't find it in your diff

It's already in the core, it was done by Helias (f549a25501a12291af77f5d7f59ba69a4fc4a956)

**Comment by BarbzYHOOL** [comment]
Awesome

**Comment by wetbrownsauce** [comment]
Did a bit more thorough test, after around 50 quests in outland, still no issues - everything seems to be good!

**Comment by FrancescoBorzi** [comment]
@Nefertumm good job!
@wetbrownsauce thanks a lot for testing this :+1:

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL maybe it would be faster to complete the loot_template too, copy the entire wiki from trinitycore and adjust the small differences like rbac

**Comment by BarbzYHOOL** [comment]
>copy the entire wiki from trinitycore

how

**Pull request merged**
