### PR TITLE
fix(Core/Pets): Improved Revive Pet should affect dead despawned pet.

### LINKED ISSUE #9589: Hunter's talent Improved Revive Pet doesn't apply additional HP if pet corpse is despawned
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2504

Talent Improved Revive Pet (2/2) doesn't give your pet 45% health when you ress him. It only gives the health when your pet dies and you immediately ress him. If your pet disappear and then you ress him, it won't ress him with 45% health, but only 15% like untalented.

Tester:

The issue is confirmed. [Improved Revive Pet](https://wowgaming.altervista.org/aowow/?spell=19575) doesn't apply `the aditional health your pet returns with` if corpse was despawned for some ocasion.

https://user-images.githubusercontent.com/85256266/145203054-75d7f776-cd47-4ee1-b5dc-6356f4e44bd7.mp4

### Expected Blizzlike Behaviour

Improved Revive Pet talent (2/2) should always give your pet 45% health when ressed

### Source

_No response_

### Steps to reproduce the problem

.npc add 3939
.pet create
.aura 19575
.damage 5000 - to pet
.tele mulgore - to not wait corpse despawn
.cast 982

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/fc4b5a93a0318610e14af3a3bb50a1719f5ee765

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #9589

## Issues Addressed:

- Closes #9589
- Closes https://github.com/chromiecraft/chromiecraft/issues/2504

## Tests Performed:

- Not tested

## How to Test the Changes:

.npc add 3939
.pet create
.aura 19575
.damage 5000 - to pet
.tele mulgore - to not wait corpse despawn
.cast 982

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
```
/SpellEffects.cpp:5407:17: fatal error: using the result of an assignment as a condition without parentheses [-Wparentheses]
        if (pet = player->GetPet())
```

**Comment by UltraNix** [comment]
Done.

**Comment by Voxstrasza** [comment]
Does not seem to be working.  [Video](https://youtu.be/SyUJOhptZnE)

**Comment by UltraNix** [comment]
@Voxstrasza Should be okay now.

**Comment by Voxstrasza** [comment]
> @Voxstrasza Should be okay now.

No changes - still doesn't work.

**Comment by UltraNix** [comment]
Hmm, tested on my local and it was okay :/

**Comment by Voxstrasza** [comment]
@UltraNix you're right, I made a mistake when importing your fix files.  it is working [Video](https://youtu.be/oTfjc49aFUg)

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
