### PR TITLE
fix(DB/Creature): Rework Avatar of the Martyred

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  Previously ungrouped
-  Changes the SAI to only despawn when out-of-combat. Also takes timers and Phase In spell from Mangos

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5779

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
```
Table 'creature_loot_template' Entry 20303 Item 277[9](https://github.com/azerothcore/azerothcore-wotlk/pull/16523/checks#step:10:10)7: equal-chanced grouped entry, but group not defined - skipped
Table 'creature_loot_template' Entry 20303 Item 27876: equal-chanced grouped entry, but group not defined - skipped
Table 'creature_loot_template' Entry 20303 Item 27877: equal-chanced grouped entry, but group not defined - skipped
Table 'creature_loot_template' Entry 20303 Item 27878: equal-chanced grouped entry, but group not defined - skipped
Table 'creature_loot_template' Entry 20303 Item 27937: equal-chanced grouped entry, but group not defined - skipped
Table 'creature_loot_template' Entry 20303 Item 28268: equal-chanced grouped entry, but group not defined - skipped
Table 'creature_loot_template' Entry 20303 does not exist but it is used by Creature 20303
```

Why does this appear?

**Comment by Gultask** [comment]
Forgot to push an update and the file contained a typo

**Comment by pangolp** [comment]
> Forgot to push an update and the file contained a typo

Excellent!

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Gultask does it need further testing? if you tested it already, feel free to merge it

**Pull request merged**
