### PR TITLE
fix(DB/Creature): Looking to the Leadership quest mob respawn times

### PR DESCRIPTION
**Pull request by BeefSteaker**
## Changes Proposed:
-  set respawn time of Lieutenant Commander Thalvos and  Arch Mage Xintor to 1 minute

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4834
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14709

## SOURCE:

both are exactly one minute from being looted

https://user-images.githubusercontent.com/11332559/213287265-981206be-a1ca-4bd8-84db-64b2390d49d9.mp4

https://user-images.githubusercontent.com/11332559/213287503-2df78c25-8b88-4ff1-abaf-135f96f6e359.mp4
## Tests Performed:

- ran quesry on local 
- killed on local

## How to Test the Changes:

1. .go c id 16978 & .go c id 16977
2. kill npc's and wait to respawn (no quest needed)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
That's part of Dynamic Respawns which we don't have implemented yet. With this they'll despawn after 5mins then respawn in 1min after that.
How does it look ingame?

**Comment by BeefSteaker** [comment]
i need to update my local, but testing it yesterday it seemed about right. nowhere near 5 mins

**Comment by Gultask** [comment]
> i need to update my local, but testing it yesterday it seemed about right. nowhere near 5 mins

I meant after the corpse despawns.
The thing is that in our current method we can't have the behaviour seen above where the creature respawns without the corpse despawning as well. In AC it must occur sequentially, while it's not mutually exclusive in Retail.

**Comment by Gultask** [comment]
image
Ahh so this is interesting. I couldn't find why they don't use the default timer.

**Review by Gultask — APPROVED** [review]

**Pull request merged**
