### PR TITLE
Fix(DB/Smart_scripts) Ambassador Sunsorrow

### LINKED ISSUE #5352: Book has incorrectly formatted HTML text
Originally reported https://github.com/chromiecraft/chromiecraft/issues/302

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39

##### CURRENT BEHAVIOUR:

When reading the book Lament of the Highborne, the text is displayed as HTML and not human readable.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Book should be legible by a human.

##### STEPS TO REPRODUCE THE PROBLEM:

~~`.additem 30632`~~ Edit: False report, my bad :(

Be at least Level 15
Go to [Sylvanas](https://wotlkdb.com/?npc=10181): `.go cr 32039`
Accept the first [quest](https://wotlkdb.com/?quest=9175) from the [item](https://wotlkdb.com/?item=22597) that starts the chain: `.additem 22597`
Turnin the quest: `.quest reward 9175`
Add the followup [quest](https://wotlkdb.com/?quest=9180): `.quest add 9180`
Turnin the quest at Sylvanas
Talk to [Ambassador Sunsorrow](https://wotlkdb.com/?npc=16287) (standing to Sylvanas' Right) to get the book.

Here is a video of me reproducing the bug on a local install showing that book obtained from GM command is fine, but the book from the quest is broken.
https://www.youtube.com/watch?v=XyUjCNjXFMY

##### EXTRA NOTES:

Looks like it might have been a straight copy-pasta from Wowhead without checking how it displayed in game.
Might be worth checking the database for other books that have HTML tags in them, I have no idea what the SQL for that might be though.

image
image
image

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/8bacb39d53349f63066e84bcddb5a7f9300acb0d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97909891-book-has-incorrectly-formatted-html-text?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Branel**
## Changes Proposed:
-  Changes the smartscript from casting a spell to instead creating the item inside of the players inventory

## Issues Addressed:
- Closes #5352

## SOURCE:

Original bugpost.

## Tests Performed:

- Windows 10, tested ingame on Orc and Blood Elf

## How to Test the Changes:

1. Create a Blood Elf
2. `.go cr 32039`
3. `.quest add 9180`
4. Turn the quest in
5.  Talk to Ambassdor Sunsorrow, click on the 'What is it that you have for me, ambassodor?' gossip.

## Known Issues and TODO List:

- [x] Book no longers has HTML errors
I am unsure if this quest is supposed to be available to any other race than Blood Elf, if that is the case there is a issue of the NPC not giving the book to other races. Any confirmation would be appreciated.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Branel** [comment]
For some reason if the NPC casts a spell to create the book it ends up making the book having the player as author and that messes up with the HTML which is the reason I had to take this approach.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @Branel for this contribution! can you please provide some feedback of your testing results? i.e. a screenshot or a video

**Comment by Eldarix** [comment]
hi ! this is what i get:
WoWScrnShot_042121_074102
WoWScrnShot_042121_074111
WoWScrnShot_042121_074121
WoWScrnShot_042121_074129

**Comment by Branel** [comment]
Are you sure that you updated your database correctly? The book says that it is created by you, and the changes I made to the SmartAI should prevent the player from being the author.

**Comment by Eldarix** [comment]
Good morning :) I thought so but it seems not, excuse my ignorance, it is my first attempt at testing and I still have a lot to learn, if you could tell me how to make sure I have updated concretely what is needed, I would appreciate it, I am using the latest version of docker.

Thanks in advance and have a nice day.

**Comment by Eldarix** [comment]
WoWScrnShot_042121_101817
 
now yes, was obviously my fault :)

**Comment by FrancescoBorzi** [comment]
good job @Branel and @Eldarix !

**Comment by pklloveyou** [comment]
Tested

**Comment by Kitzunu** [comment]
Could you write the spell that is supposed to handle it somewhere? Perhaps in a new issue... Because although this works, it is a hack as it is supposed to be handled by a spell.

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
Nah, this is good enough. Perhaps the same issue exists with more spell created items or books, but that is an issue for another day

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
