### PR TITLE
fix(DB/creature): Expedition base camp - NPC locations

### PR DESCRIPTION
**Pull request by Si1ker**
This change will fix the spawn locations for the three npcs around the Dalaran portal at the expedition base camp in Ulduar
image

## CHANGES PROPOSED:
-  Change the spawn location of the following creatures with GUID: 136552, 136523 and 136553

## ISSUES ADDRESSED:
- The current locations are way too high in the air, when you enter into the instance for the first time, you will see them falling/crashing to the ground

## TESTS PERFORMED:
- Applied SQL changes with no errors found
- Tested in-game

## HOW TO TEST THE CHANGES:

**Before applying the changes:**
- .go xyz -805.978 -201.806 429.841 603 3.076
- Select any of those three npcs
- .die
- .respawn
- See how it respawn in the air and will crash to the ground
(When you enter into the instance for the first time, these three npcs will spawn at that high point in the air with no reason)

**After applying the changes:**
- .go xyz -805.978 -201.806 429.841 603 3.076
- Select any of those three npcs
- .die
- .respawn
- See how it will spawn as planned in the same point
(When you enter into the instance, they will not be falling as before)

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by aradep** [comment]
Tested, works like a charm.

**Comment by wizzymore** [comment]
@Si1ker i am very sorry to let you know this but you must close this PR. This will be invalidated because of my Base Camp rework so i don't think it is needed.

**Comment by Si1ker** [comment]
@wizzymore  Have you scripted them or change the way they spawn?  I don't care closing the PR if they just does not spawn in the air and crash into the ground.. haha  😹

**Comment by wizzymore** [comment]
image
image

Changed their spawn and script

**Comment by Si1ker** [comment]
### This issue will be addressed on #3558

**Pull request closed without merging**
