### PR TITLE
fix(DB/SAI) Fix Quest: The Stone Watcher

### PR DESCRIPTION
**Pull request by Kosiak**
## Changes Proposed:
-  Update missing gossip flag for npc

## Issues Addressed:

- Closes [Quest: The Stone Watcher - bugged! #2899](https://github.com/chromiecraft/chromiecraft/issues/2899)

## SOURCE:

https://www.youtube.com/watch?v=bONxXSBNSAo
https://www.youtube.com/watch?v=3XVRWi2SJkA

## Tests Performed:

- Added quest [Seeing What Happens](https://classic.wowhead.com/quest=2946/seeing-what-happens) (.q add 2946). 
- Submitted quest and NPC spawns and gives u another quest [The Stone Watcher](https://classic.wowhead.com/quest=2954/the-stone-watcher)
-  Accepted quest and clicked trough gossips and finished quest after that.

## How to Test the Changes:

1. Add quest (.q add 2946)
2. Submit and wait for NPC to spawn. Accept next quest [The Stone Watcher](https://classic.wowhead.com/quest=2954/the-stone-watcher) from NPC.
3. Click trough NPCs gossips and complete quest.

## Known Issues and TODO List:

Peoples who already spawned NPC and couldn't complete quest and NPC de-spawned will have problems as NPC only spawns after you complete quest [Seeing What Happens](https://classic.wowhead.com/quest=2946/seeing-what-happens). 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Lynethris** [comment]
Tested and work.

**Comment by Nefertumm** [comment]
Uhm, I forgot to understand, is https://github.com/azerothcore/azerothcore-wotlk/issues/9508 fixed by this PR too, I didn't have time to check?

**Comment by Kosiak** [comment]
> Uhm, I forgot to understand, is #9508 fixed by this PR too? I didn't have time to check

No they still mixed up. I got the fix. Gonna do another pr right?

**Comment by Nefertumm** [comment]
Excellent, thank you!

**Pull request merged**
