### PR TITLE
Minor Fixes SQL patch

### LINKED ISSUE #342: [NPC][WOTLK] Brittle Revenant - Missing Random MovementType + Low Droprate
**Description**: Wrong MovementType

**Current behaviour**: Standing still 

**Expected behaviour**: MovementType 1 like Seething Revenant

**Steps to reproduce the problem**:

1. Go to Frostfield Lake
2. Check them out and check out Seething Revenant
3. Can be seen here that they should move 

https://www.youtube.com/watch?v=Kgf0tslmPWM

**Branch(es)**: Master

**AC hash/commit**:  b2c3330095bf

**Operating system**:  Windows 7

**Modules**:  None

**Other Customizations**: None

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

### PR DESCRIPTION
**Pull request by starrheld**
Thanks to @Rushor!
----------------------

**Changes proposed:**

Heldgarr Steelbeard - Unable To Shoot at Target

[Quest][WotlK] The Last of Her Kind

Adding Textevent of Civilian Recruit inside building and updating model

DB/Creature: Bellinger and Bailey

DB/Creature: Snowblind Devotee

DB/Creature: Torseg the Exiled

Janks's missing mine event - DB: Janks's mine event

Initiate Park - Pathing and Emotescript

Initiate Vernon + Initiate Greer - Textevent and Pathing

Apprentice Trotter - Pathing + Emotescript

Librarian Hamilton - Add pathing and Emotescript

Karen I Don't Caribou the Culler - Better Pathing Added and Correct SpellID 46147

Armorer Orkuruk - Missing Hate Texts

Wind Master To'bor & Warsong Wind Rider Script

Warden Nork Bloodfrenzy & Son - Conversation

Mogg and Pooka added their Storyscript

[NPC][Wotlk] Jimmy the Stable Boy - Missing Pathingscript

[NPC][Classic] Misc - Pathing and Emotestateupdates for Hammerfall Guardian, Horde Guard, Peon and Westfall Woodworker

[NPC][Classic] Wretched Ghoul + Zoombie - Attackevent + Pathing

[NPC][WotlK] Ironwool Mammoth

Patrolling Event + Mini Event

[NPC][Classic] Lumberjack - Added Emotes and Pathing

[NPC][Classic] Defias Thug - Emotes + Pathing + Randommovement

[NPC][Classic] Zalduun <Priest Trainer> - Heal + Pathing + Text

[NPC][Classic] Scarlet Deserter Event with Gothik the Harvester

[NPC][Classic] Gothik the Harvester - Implement resurrection Event for Scourge Gryphon and Scarlet Ghoul

[NPC][Classic] Lord Thorval - Link Texts to Movement

[NPC][WotlK] Ore Cart - Questevent for "Fruits of Our Labor"

[NPC][TBC] Mordenai - Add Movement and Attackscript

[NPC][TBC] Chancellor Bloodleaf - Textevent with Corok the Mighty

[NPC][TBC] Painmistress Gabrissa - Pathing and Castscript

[NPC][TBC] Eye of the Citadel - Revengetext On Death of Morkh

[NPC][TBC] Levixus - Missing Announce of Blizzard Crew Member(s)

[NPC][TBC] Experimental Pilot - Conversation with Engineering Crewmember(s)

[NPC][TBC] Consortium Nether Runner - Text and Pathscript

[NPC][TBC] Nurse Judith - Pathing + Emotescript

[NPC][Classic] Eye of Naxxramas - Spawn + Pathing

[NPC][WotlK] Durkot Wolfbrother - Added Pathing and Emoteevent

[Quest][Northrend][Icecrown]"Battle Before The Citadel" - Phasing Issue

[Quest][NorthRend][Icecrown]At The Enemy's Gates - Phasing Issue

[Item] Plans: Ragesteel Helm Should Only Drop From Anger Guards

[Instance] Deadmines - Rework (Formation and Waypoint(s).

[Instance] Caverns of Time: Old Hillsbrad Foothills - Full Rework

**Target branch(es):** Master

**Issues addressed:** Closes #342 #343 #345 #346 #348 #349 #350 #356 

**Tests performed:** Tested and Confirmed

### CODE REVIEW

**Comment by Rushor** [comment]
you can change the autor of the commit here to give credits, since most of this are my fixes 

GitHub Logo

simply copypaste: 

Rushor <Rushor@users.noreply.github.com>

in that empty field and push it after it

thank you!

**Comment by starrheld** [comment]
@Rushor I want you to get credit, I'm just making sure it's getting fixed over here as well.
I'm not after any credit, I'm commiting directly from my UNIX (ubuntu) not sure how I change the Author

**Comment by ShinDarth** [comment]
please squash the commits and set the author

**Comment by ShinDarth** [comment]
http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by falzard** [comment]
How did he get your commits? @Rushor

**Comment by sucofog** [comment]
Are this commits gonna apply?

**Comment by talamortis** [comment]
have these been tested?

**Comment by talamortis** [comment]
does this also close #356?

**Comment by starrheld** [comment]
@talamortis Nope it doesn't I want feedback and possibly check the text that appears on the screen, I think that is scripted in the code. 1000 Mana should trigger that text.

**Comment by talamortis** [comment]
Tested and working welldone @starrheld  @Rushor  :) 👍

**Pull request merged**
