### PR TITLE
fix(Core/Creature): Fix an issue with incorrect corpse decay calculation.

### LINKED ISSUE #11710: Default Corpse Decay Times Inaccurate
### Current Behaviour

Currently the corpse decay time for a creature that hasn't been looted/skinned is set to 60 seconds.

### Expected Blizzlike Behaviour

After testing on TBC Classic with a few mobs ([Adder](https://classic.wowhead.com/npc=3300/adder), [Sickly Gazelle](https://tbc.wowhead.com/npc=12296/sickly-gazelle), and [Greater Plainstrider](https://tbc.wowhead.com/npc=3244/greater-plainstrider)) I have found that all three of these mobs had their corpse decay after approximately five minutes.

### Source

Burning Crusade Classic.

### Steps to reproduce the problem

1. Go to the Barrens
2. Kill Adder, Sickly Gazelle, or Greater Plainstrider
3. Observe much quicker corpse decay time

### Extra Notes

The adder and the sickly gazelle had no loot and did not have the skinnable tag. The plainstrider however did have the skinnable tag, but the character I was on did not have skinning. I did kill two plainstriders, one I looted the other I didn't, and both had their corpse decay in five minutes.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/32b7531295f7e3d776d3c39ec215c200aa1da312

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### LINKED ISSUE #14325: Corpse decay timers broken within the last three days
### Current Behaviour

I updated and deployed three days ago, on December 18th, and things were evidently fine. I just did so again today, AC> AzerothCore rev. 7f6788ce86a3 2022-12-20 16:09:17 +0000 (master branch) (Unix, RelWithDebInfo, Static), only plugin being transmog, and now corpses despawn immediately after being looted. I've only noted the issue with normal corpses, and haven't sought out other sorts to compare.

Relevant config, unchanged recently:

Corpse.Decay.NORMAL    = 300
Corpse.Decay.RARE      = 300
Corpse.Decay.ELITE     = 300
Corpse.Decay.RAREELITE = 300
Corpse.Decay.WORLDBOSS = 3600
Rate.Corpse.Decay.Looted = 1

I don't see any recent changes in src/server/game/Entities/Creature/Creature.cpp which makes me curious how it's behaving differently.

### Expected Blizzlike Behaviour

Obey Corpse.Decay.NORMAL * Rate.Corpse.Decay.Looted config

### Source

_No response_

### Steps to reproduce the problem

Find and kill a normal mob. Loot it.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 7f6788ce86a3 2022-12-20 16:09:17 +0000 (master branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using MySQL version: 100518
Using CMake version: 3.18.4
Compiled on: Linux 5.10.0-20-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/acore/data/maps. Total size: 291014951 bytes
vmaps directory located in /opt/acore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/acore/data/mmaps. Total size: 2320900676 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS 
Using World DB: ACDB 335.8-dev
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-transmog

### Operating system

Debian 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by heyitsbench**
Co-authored by: UltraNix <80540499+UltraNix@users.noreply.github.com>

## Changes Proposed:
- Changes a calculation from removing a corpse immediately after it's looted with certain configs to more correct calculation.
- Changes default corpse decay configs to blizzlike values.

## Issues Addressed:

- Closes #11710
- Closes #14325

## SOURCE:

TBC Classic.

## Tests Performed:

- Tested in-game with `Corpse.Decay.NORMAL` set to 300 and `Rate.Corpse.Decay.Looted` set to 1.

## How to Test the Changes:

1. Change the `Corpse.Decay.*` and `Rate.Corpse.Decay.Looted` config options to whatever values you like.
2. Make sure the creature's corpse is removed at the correct times according to the configs you set.

## Known Issues and TODO List:

- There is an issue with creature respawn times as well, but that's not something I care to deal with right now.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by UltraNix — APPROVED** [review]

**Comment by Gultask** [comment]
Wouldn't it be best to wait until dynamic respawn is implemented?

With this PR every single normal mob would have its respawn timer increased by at least 4 minutes. Which would be a problem in highly populated zones, as we've seen in the TBC release for ChromieCraft.

**Comment by heyitsbench** [comment]
> Wouldn't it be best to wait until dynamic respawn is implemented?

In my opinion, this whole corpse removal and respawn stuff might as well be ripped out entirely if/when dynamic spawns are implemented, but I don't see why improvements shouldn't be made while waiting for a system that may very well never come.

> With this PR every single normal mob would have its respawn timer increased by at least 4 minutes, no?

Depends. If the killer loots the mob immediately, the mob respawns pretty much as soon as the corpse is removed (the respawn issue I mentioned in the known issues segment.) This also applies if the mob gets looted later on (e.g. if looted a minute after being killed, the mob will respawn when the corpse is removed, thus five minutes after being looted.) If the mob *doesn't* get looted, the corpse decays in five minutes as expected, and the mob respawns five minutes after that, as they should. Like I said in the description, I'm not fixing that discrepancy between looted/unlooted mobs. But I will fix the issue with the corpse decay time being appended rather than recalculated.

**Comment by heyitsbench** [comment]
Okay, both of those issues are "fixed". Adjusting `Rate.Corpse.Decay.Looted` does nothing currently, but it's more blizzlike than it was before. Now to get that working properly.

**Comment by heyitsbench** [comment]
There's an issue outside of this function. I've updated the relevant portion with what (to me) logically makes sense when I try to do the math myself, but it is *highly* inconsistent in-game. Sometimes it works as it should, and others the corpse decays instantly. I'm not good enough at debugging and I've been staring at this one function for far too long to want to fix the actual issue anymore. It *might* be related to the fact that I was testing with skinnable creatures, but I kinda doubt it. Either way, I'm giving up, since I'm sure it won't get merged if it breaks the rate config, which it would.

**Pull request closed without merging**
