### PR TITLE
FIx startup error

### PR DESCRIPTION
**Pull request by milestorme**
Fix startup error (thanks @poszer )
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2228

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Logging this message as error is intended:
https://github.com/azerothcore/azerothcore-wotlk/issues/2228#issuecomment-524428675

**Comment by milestorme** [comment]
Please explain , as to why we are initialising world server as an error

**Comment by Stoabrogga** [comment]
Just read the comment, @BarbzYHOOL explained this pretty well. A _real_ fix has to provide a better logging system.

**Comment by BarbzYHOOL** [comment]
yeah, it's just cosmetic, like sometimes there are outstring empty just to add new empty lines

not very clean but it works

**Pull request closed without merging**
