### PR TITLE
fix(DB/Creature): Civilian Recruit improvements

### PR DESCRIPTION
**Pull request by wizzymore**
## Changes Proposed:
- Fix first in line position
image
Old position was on red dot, and this made the npc go over the table.
- Add the correct path for the civilians that need to go to the barracks ( taken from retail )

## Issues Addressed:
- Closes none

## Tests Performed:
- Windows

## How to Test the Changes:

`.go c 108029`
Wait for the to go in line and watch them move and despawn.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Yehonal** [comment]
Finally! GJ

**Comment by nicoaravena** [comment]
Works good. Just a doubt, the line should start so far back (at the end of the other)? Or the line should populate from the beginning to the end?
imagen
imagen

**Comment by wizzymore** [comment]
@nicoaravena because of scripting limitations, from the back, the NPC's are set as Activate, so they continue with the line even when no player is near them.
This means that only at a server restart if a player was in that exact place the line will be empty

**Comment by nicoaravena** [comment]
Ok, I can understand that now, it works perfectly.

**Comment by pklloveyou** [comment]
Tested

**Comment by Kitzunu** [comment]
Thanks!

**Pull request merged**
