### PR TITLE
fix(Core/BattlefieldWG): Workshops/Graveyard not changing to neutral

### PR DESCRIPTION
**Pull request by Valdifer**
## Changes Proposed:
-  When you were capturing a workshop, when the bar was at gray (neutral), the workshops weren't updating to neutral team and the team who was owning the workshop still had more vehicles while it was neutral
-  Change workshop/GY to neutral

## Issues Addressed:

- Closes 

## Tests Performed:

- Build without error
- 
WoWScrnShot_113022_130125

## How to Test the Changes:

1. .tele wintergrasp
2. start wintergrasp
3. go to some graveyard/workshop and cap it

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
image
Whether the flag should be removed when neutral？

**Comment by Valdifer** [comment]
> image Whether the flag should be removed when neutral？

hmm, i will take a look into that

**Comment by Valdifer** [comment]
I'm new to AC code but it seems like those banners are from DB? i mean i saw somewhere the data but i dont remember it, seeing the DB it is
Horde Phasemask = 16
Alliance Phasemask = 32
Neutral Phasemask = ?
So it seems that should be there with the neutral phasemask? thats the info i got

**Comment by pklloveyou** [comment]
I'm not familiar with the battlefield code

**Comment by Valdifer** [comment]
> I'm not familiar with the battlefield code

I found it :D
image
image
image

Now lets see how i do this

**Comment by Valdifer** [comment]
image
image

Done

**Review by acidmanifesto — APPROVED** [review]

**Comment by avarishd** [comment]
On all 3 states of control. (Alliance/Neutral/Horde):
- [x] Vehicle counter updates.
- [x] Workshops update. (And the phasing, no overlapping A/H banners.)
- [x] Graveyards update.
<details>

https://user-images.githubusercontent.com/46330494/222147774-346c87bd-6cc0-4a89-bbae-36545233bf4d.mp4

</details>

**Review by Maelthyrr — APPROVED** [review]

**Pull request merged**
