### PR TITLE
fix(Docker): Persistent volumes for ac-database

### PR DESCRIPTION
**Pull request by h0lysp4nk**
(Docker) Persistent volume for ac-database

## CHANGES PROPOSED:
-  Added persistent volume for container `ac-database`

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2946

## TESTS PERFORMED:
- Ran `docker-compose config` to ensure syntax is right
- Started the containers
- Do some changes in the DB
- Stopped the containers with `docker-compose down`  which deletes the container
- Started the container and the data persisted

## HOW TO TEST THE CHANGES:

- Build AzerothCore in docker
- Start the containers
- Type `docker-compose down` which will remove the containers
- Start the containers again with `docker-compose up -d` and check database to see if data persisted.

## KNOWN ISSUES AND TODO LIST:

- None

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@h0lysp4nk interesting, I didn't know about this (I'm not a Docker expert).

However, what if I **do want** to destroy the DB and start from a clean one?

Currently destroying/recreating it's useful for development purposes. Do we have a way to let the user persist it?

**Comment by h0lysp4nk** [comment]
@FrancescoBorzi Yes, adding the volume in my PR will make the container persist. When that container is added if you want to destroy the database you'll need to remove the volume. As docker-compose prefixes it's containers etc with the folder name you would need to run `docker volume rm azerothcore-wotlk_ac-database`

**Comment by FrancescoBorzi** [comment]
@h0lysp4nk good to know, can you please add this somewhere in our Docker wiki? for example in the FAQ?

http://www.azerothcore.org/wiki/Install-with-Docker

**Comment by h0lysp4nk** [comment]
@FrancescoBorzi Sure :)

**Comment by h0lysp4nk** [comment]
@FrancescoBorzi https://github.com/azerothcore/wiki/commit/9dbddca2dbda87f34d712408880fce60cd812177

**Comment by Kitzunu** [comment]
Create a PR on the Wiki Repository, please :)

**Comment by h0lysp4nk** [comment]
@Kitzunu Okay done :)
https://github.com/azerothcore/wiki/pull/215

**Comment by th3lolipop** [comment]
Thanks, It works smoothly !! @h0lysp4nk  
Tested with `docker-compose down` and `docker-compose up` again. SQL data still remains in the volume after all and also tested with deleted the volume and `docker-compose up` again. 
 
Screenshot from 2020-04-28 18-28-23

**Comment by FrancescoBorzi** [comment]
thanks @th3lolipop for testing this!

good job @h0lysp4nk

**Comment by Kitzunu** [comment]
Ty for the PR!

**Pull request merged**
