### PR TITLE
fix(Core/CreatureScript): Fix dk quest 12701 #2557

### LINKED ISSUE #2557: [Quest] DK ID: 12701 (Massacre At Light's Point) Bug
[Quest] DK ID: 12701 (Massacre At Light's Point) Bug

##### SMALL DESCRIPTION:

In this quest you must enter a mining trailer and a miner drags you through the enemy lines to one of the two ships on the beach. When he takes you to the ship on the left, everything is fine; but when it takes you to the ship on the right, the mining trailer stays in the air.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The miner should take you to the ship.

##### CURRENT BEHAVIOUR:

Quest: [Massacre At Light's Point] https://wowgaming.altervista.org/aowow/?quest=12701
Class: Death Knight.
Details: When the miner arbitrarily takes you to the ship on the right, the cart stays in the air and does not reach the ship.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a Death Knight.
2. Command: .q a 12701
3. Command: .go xyz 2396.51 -5895.32 110.473
4. Enter in mining cart.
5. Wait for it to arrive on the ship (The error is only when it leaves you on the ship on the right, otherwise: leave the mission (.q r 12701) and repeat from step 2).

Screenshot:

WoWScrnShot_010820_151900

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

cf33698040e62ebe2c49d785ea526c114c9d271c

##### OPERATING SYSTEM:

Debian 10

##### MODULES:

mod-anticheat
mod-bossannouncer
mod-cfbg
mod-transmog
mod-duelreset

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/86647237-quest-dk-id-12701-massacre-at-light-s-point-bug?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by skxawng-cu**
Fix dk quest 12701 issue https://github.com/azerothcore/azerothcore-wotlk/issues/2557#issue-547091473

## CHANGES PROPOSED:
-  Add two WayPoints in AI Script of the minner for fix the bug.
-  More info about the bug in the issue.

## ISSUES ADDRESSED:
- Closes #2557

## TESTS PERFORMED:
- Testing the quest after the change many times and everything is ok.
- Testing for the two chips.

## HOW TO TEST THE CHANGES:

1. Create a Death Knight
2. Add quest - Command: .q a 12701
3. Command: .go xyz 2396.51 -5895.32 110.473
4. Enter in mining cart.
5. Wait for it to arrive on the ship (The error was only when it leaves you on the ship on the right but you can repeat the process until he leaves you at both ships).

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Looks good, thanks. Will test this later.

**Comment by Stoabrogga** [comment]
Tested successfully, thanks. I pushed another commit in order to smooth out the waypoint movement (the miner is bunny-hopping while running down the hill) and drive around the other mine car which stands in the way above the hill. Can be merged in my opinion.

**Comment by skxawng-cu** [comment]
Perfect, I had already noticed the jumps of the miner and the mining car that was in the middle. Thanks for fix that.

**Comment by FrancescoBorzi** [comment]
good job @skxawng-cu  and @Stoabrogga !

**Comment by BarbzYHOOL** [comment]
Thank you @skxawng-cu for the fix and @Stoabrogga for testing/improving

**Pull request merged**
