### PR TITLE
feat(DB/Translations) Imported german translations from GTDB

### LINKED ISSUE #2346: Missing deDE Quest Locales (Offer Reward & Request Items)
##### SMALL DESCRIPTION:

Nearly all quest texts of the request items and the offer rewards are not translated in german.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Wow deDE Client should be able to use all german quest texts. 

##### CURRENT BEHAVIOUR:

Missing deDE Locales in the following db tables:

- quest_request_items_locale
- quest_offer_reward_locale. 

##### STEPS TO REPRODUCE THE PROBLEM:

1. Add any quest
2. get the required stuff (Requested items)
3. End the quest (Offer rewards)

##### EXTRA NOTES:

Using Azerothcore Solo Repack from Brookstech

##### BRANCH(ES):
master

##### AC HASH/COMMIT:
d2b409e77ed0+ 2019-06-15 11:51:37 -0500

##### OPERATING SYSTEM:
Windows 10 Home Premium

##### MODULES:

- Auctionhouse Bot
- npc_beastmaster
- npc_enchanter
- BuffMaster
- VASAutoBalance 
- Transmogrifier

##### OTHER CUSTOMIZATIONS:

- AutoRevive on death
- NPC Instance, LFG, Dungeon cooldowns reset
- Individual-XP

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/81883352-missing-dede-quest-locales-offer-reward-request-items?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Helias**
##### CHANGES PROPOSED:
I imported from [GTDB](https://github.com/gpn39f/GTDB) ~and [GCMDB](https://github.com/Xadras/GCMDB/)~ several string translated into german for deDE client as @Endeffect-AT suggested.

I imported the followings table and related data, I removed the duplicates data:

- creature_text_locale (452)
- creature_template_locale (only 40, the others 22k are already imported)
- gossip_menu_option_locale (2924)
- item_template_locale (165)
- npc_text_locale (5395)
- page_text_locale(28)
- points_of_interest_locale (0) -> AC has already all data
- trinity_string (904)
- quest_template_locale (1), these quests are already translated for deDE client.
- ~quest_request_items_locale (3082)~,  ~quest_request_items_locale (648) **(GCMDB)**~
- ~quest_offer_reward_locale (5680)~, ~quest_offer_reward_locale (2936) **(GCMDB)**~

##### ISSUES ADDRESSED:
- Closes #2346 

##### HOW TO TEST THE CHANGES:
 - Import the SQL file and check the translations
 - Check that the others locales are untouched after the importing

##### Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Endeffect-AT** [comment]
Need more detailed checks?

**Comment by Helias** [comment]
@Endeffect-AT just check around like one row per table, I made several converters per table, if in one row there is a error, it will be in any table row, hence, just check the code, only one row per table :wink: 

Import all the SQL file into the database and check if it returns error (should not).

**Comment by Endeffect-AT** [comment]
Imported the update several times, also from a fresh db. No errors occured, and also checked more translations  👍

**Comment by Helias** [comment]
The only problem now is the Travis build that fail, I don't know why, if this will be solved the status of the PR will be "To Be Merged"

**Comment by Endeffect-AT** [comment]
2019-10-26 10:02:40 Table `achievement_reward_locale` (Entry: 4400) has locale strings for non-existing achievement reward.

This is the causal Error.

Also i discovered a small text error in the npx_text_locale:

The string 'Seid gegrüßt, $' in a bunch of entries is not correct. It should be 'Seid gegrüßt, $N' so that the player name is written, so it just says '$'.

**Comment by Helias** [comment]
@Endeffect-AT, ok, I will check the original GTDB and compare it with that text

**Comment by Helias** [comment]
Fixed the strings and removed the achievement.

**Comment by Helias** [comment]
@Endeffect-AT, thank you

**Comment by Endeffect-AT** [comment]
Ty too @Helias ✌🏻

**Comment by Stoabrogga** [comment]
Pushed a new commit. There were a few locales "deDe" which are now replaced with the correct form "deDE" and a few umlaut errors.

**Comment by Endeffect-AT** [comment]
Further checks required or why no one approves it? Or is it not needed if you label it? Sry im just learning Git....

**Comment by Helias** [comment]
In the azerothcore github workflow, yes, is needed the approve of one developer, hope someone will approve it asap and merge, anyway, don't worry, it will be merged.

**Comment by Endeffect-AT** [comment]
@Helias alright, thx 4 your help!

**Comment by Endeffect-AT** [comment]
I noticed that many texts are missing some punctuation at the end.  Is it possible to fix the errors?

**Comment by Endeffect-AT** [comment]
@Helias 
I have found another German database, this time from ManGOS where the errors of punctuation do not appear. 
Can you just change the Files in PR?

https://github.com/Xadras/GCMDB

**Comment by Helias** [comment]
it's a bit hard for me in this period, but I'll try

**Comment by Endeffect-AT** [comment]
Thx man, you guys do an awesome job here 👍 
To recognise this error i finished ~100+ quests to recognise that a lot of the entries are not correct. It's a lot more work to edit every single line as to import the correct ones. 
All the other tables except the quest locales working fine  so they can stay 👍

**Comment by Helias** [comment]
Ok, nice ;-)
Anyway my job would not be complete without a tester that report me bugs, so thanks you ;-)
I try to do my best, I will remove/ignore the old locales table `quest_request_items_locale` and `quest_offer_reward-locale` importing them from the new DB that you linked to me.

**Comment by Endeffect-AT** [comment]
Thanks, I'm just starting and learning about the AzerothCore but i've been playing for years with the wow server emulation and just have one goal:  WotLK with all features and german locales :)

When you are ready I will test the locales. Also if i have more experience then i will also start testing PR's 👍

**Comment by Helias** [comment]
Imported:
- checked quest_template_locale, everything were already in AC
- quest_request_items_locale (648)
- quest_offer_reward_locale (2936)

**Comment by Endeffect-AT** [comment]
Thank you for your hard work! I will now check the texts more intensively on the known errors, which may take a while 😄 

However, I believe that ultimately the quests will  will not be imported at all. I think I have to get either from a public server or even translate each quest individually ... Last one i don't hope so 😄 

Just give me a few days to review 👍

**Comment by Helias** [comment]
@Endeffect-AT, I appreciate your goals and your intentions, but I want to finish this PR, after that if you want to finish "ALL" locales I can make you a tool that extract texts from WoWHead or other websites, where maybe you can find the locales already translated :P.

**Comment by Endeffect-AT** [comment]
@Helias 
Okay, so it's better we import all the locales except the quests. It also seems these translations are not 100% correct, better than the GTDB but they would do more work than improve ...

Approving merging the other locales 👍 

- creature_text_locale (452)
- creature_template_locale (only 40, the others 22k are already imported)
- gossip_menu_option_locale (2924)
- item_template_locale (165)
- npc_text_locale (5395)
- page_text_locale(28)
- points_of_interest_locale (0) -> AC has already all data
- trinity_string (904)
- quest_template_locale (1), these quests are already translated for deDE client.

**Comment by Helias** [comment]
What about these tables from GCMDB?
- quest_request_items_locale (648)
- quest_offer_reward_locale (2936)

**Comment by Endeffect-AT** [comment]
The GCMD Translations are much better than the GTDB in terms of punctuation, but I had to read yesterday after several hours reading texts that not everything is translated correctly.  So it is better that until further notice, we import only what is correct.  The quest texts I will look at intensively, as such a tool would of course be very helpful :)

**Comment by Helias** [comment]
ok, so I'm removing the related quest tables data of GCMDB and changing the status of this PR in "To Be Merged".
Anyway, @Endeffect-AT you could test the translations of GCMDB before asking me to convert them into AC :sweat_smile: 

Be careful next time ;-)

**Comment by Endeffect-AT** [comment]
@Helias
I did not notice because the errors sometimes occur in the middle of the text. Although I could fix it because not all lines are affected, but if you want to close the PR it is so much better. 
It was not in vain, however, to convert the tables as I will continue to process them and later merge them all - All you have is good :-) 
Of course I will pay more attention next time, sorry for the inconvenience! 
As far as the tool for extracting from the webistes I would be very grateful. PM me in Discord if you want :)

**Comment by Helias** [comment]
@Endeffect-AT, is a pleasure work with you, don't worry for the inconvenience ;-)
Yeah, we can arrange something in chat about a possible extracting tool.
Anyway now I'm working on security issues about AC that has priority, so I want to merge this PR asap and maybe work into another PR the others translations texts.

The web scraping tool will help to get multi-lang texts, not only the german ones, indeed I would make it in future :P

**Pull request merged**
