### PR TITLE
Core/ChatHandler: Update Addon message read fix

### PR DESCRIPTION
**Pull request by ladiszlai**
Update Addon message read fix (my last commit)

### CODE REVIEW

**Comment by pondaveia** [comment]
@talamortis can you check this?

**Comment by FrancescoBorzi** [comment]
We need to resolve the merge conflicts & test this.

**Comment by Nefertumm** [comment]
@ladiszlai can you resolve the conflicts with this pr?

**Comment by Rochet2** [comment]
Fixed the conflicts. Now just need testing.

**Comment by FrancescoBorzi** [comment]
how can this be tested? what does it change? the PR description is not much descriptive :P

**Comment by Rochet2** [comment]
According to https://github.com/azerothcore/azerothcore-wotlk/pull/796#issuecomment-367990042
it seems that the following chat messaging was possibly broken:
- CHAT_MSG_PARTY
- CHAT_MSG_RAID
- CHAT_MSG_GUILD
- CHAT_MSG_BATTLEGROUND

So testing should include probably trying to chat in those chats before and after the change and see if before was broken and after works or that both work.

**Comment by comix1988** [comment]
I tested:
- whisper chat
- party chat
- raid chat
- bg chat
 Guild chat I could not test it.

I didn't find any problems before and after the fix

**Pull request merged**
