### PR TITLE
fix(Core/Accounts): GM Rank 1 hostile to players

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2806

## Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Si1ker** [comment]
V3nomAnc3r and me already tested in issue #2806 .
Approval and go 🚀  !

@FrancescoBorzi

**Comment by Si1ker** [comment]
@Helias or @BarbzYHOOL can you link this PR to the issue so once the PR gets merged the issue is closed? Ty 🐱

**Comment by Helias** [comment]
@Si1ker, done :rocket:

**Comment by BarbzYHOOL** [comment]
@Helias don't put it in title else it will be in our git history (though it can be added in description)

Instead, write "Closes xxx" in the PR description and it should work fine (even with "Close" typo, should work)

`Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2806`

**Comment by Helias** [comment]
@BarbzYHOOL oh, ok, for me it's the same :sweat_smile:

**Comment by FrancescoBorzi** [comment]
I thought about this a bit, and I realised there could be cases when you want to have a player who is also some kind of moderator but not a GM.

This PR is still good as probably the majority of people expect a `SEC_MODERATOR` to be considered a GM.

However, I think it would be nice to make this configurable (that can be done in a separate PR).

@IntelligentQuantum you are the king of configurations, would you like to take this?

**Comment by BarbzYHOOL** [comment]
It only works if you have gm mode on

**Comment by IntelligentQuantum** [comment]
@FrancescoBorzi Yes sure :smile: .

**Comment by Kitzunu** [comment]
Thanks for the PR!

**Pull request merged**
