### PR TITLE
Infinite spawns! Fix Civilian Recruit not despawning.

### PR DESCRIPTION
**Pull request by AGandrup**
I stumbled upon a cosmetic event in Northrend which has an NPC (Civilian Recruit) continuously spawning but they never despawn again leading to an infinite amount of Civilian Recruit's piling up. This obviously affects performance and increases CPU usage exponentially, especially because these NPC's happens to be set as active in their script aswell. An active object keeps itself and everything around it updated, and also keeps the grid active. These NPCs shouldn't even be set to active in the first place as they serve no purpose but being cosmetic, but thats a story for another time, right now the issue is that they never despawn 😛 

WoWScrnShot_101723_190750

## Changes Proposed:

- Make Civilian Recruit despawn once they reach the end of their path.

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — CHANGES_REQUESTED** [review]
Please condense this into one INSERT and I guess three DELETE's thank you

**Comment by Cinnamohn** [comment]
Not seeing this issue as of 23606bc

https://github.com/azerothcore/azerothcore-wotlk/assets/51275113/47a1614a-67e4-4ee9-99db-33f02fa95957

**Comment by AGandrup** [comment]
Hmm. Its been some time since I applied this fix to my database, perhaps it was fixed in some other way in the meantime. Or do you already happen to have this fixed in your db somehow?
Could try run this query:
SELECT * FROM smart_scripts WHERE entryorguid = 2522000;

or entryorguid = 2522001

**Comment by AGandrup** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/4278

I guess this explains it. I wonder why this wasnt working for me in the past, perhaps it was broken at somepoint and fixed again? Idk, oh well.

Closing this.

**Pull request closed without merging**
