### PR TITLE
fix(DB/gameobject): Peacebloom spawn location

### LINKED ISSUE #5836: Redridge Mountains - Peacebloom node in the middle of the road
**CURRENT BEHAVIOUR:**
Original report: chromiecraft/chromiecraft#638

Peacebloom node (id: 1396) spawn in the middle of the road in Redridge Mountains.
Confirmed on local AC server:

WoWScrnShot_051421_093045

Herb is currently not spawned in but I'm standing right on top of the node.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
The herb should not spawn in the middle of the road.

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. `.go o 1396`
2. Observe

**EXTRA NOTES:**

**AC HASH/COMMIT:**
5a950f0

**OPERATING SYSTEM:**
Arch Linux

**MODULES:**

**CUSTOMIZATIONS:**

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98542812-redridge-mountains-peacebloom-node-in-the-middle-of-the-road?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anguaive**
## Changes Proposed:
Peacebloom node (id: 1396) was positioned on a road. It has been moved
to a nearby location next to the road, where there are no other herb
nodes close by.

## Issues Addressed:

- Closes #5836 
- Closes https://github.com/chromiecraft/chromiecraft/issues/638

## Tests Performed:

- Tested new location
- Made sure there are no other herb nodes right next to the new location

WoWScrnShot_051421_094407

White: new location
Red: old location
Blue: nearby herb nodes (none visible)

## How to Test the Changes:

1. `go o 1396`
2. Make sure new node location is acceptable

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by anguaive** [comment]
Removing the node would also be a solution. Peaceblooms shouldn't spawn in Redridge as IcemanHHW points out. I don't think it's a big deal since it's right next to Elywnn and resource nodes locations need an overhaul anyway from what I can tell.

**Comment by Branel** [comment]
I am for deletion as it would be the only node in the entire zone which wouldn't make a whole lot of sense.

**Comment by anguaive** [comment]
I just did a cursory search in the zone and found 2 more (1686 and 1374), one of them nowhere near Elwynn, so it's not a one-off thing. I'll keep looking for a bit and remove them if you prefer that (I don't mind either way).

**Comment by anguaive** [comment]
Peacebloom nodes 1396, 1374, 1686 and 1740 have been removed. Prior locations marked with red dots:

rr_peaceblooms

**Review by Branel — APPROVED** [review]

**Comment by Branel** [comment]
Tested.

**Comment by Hacki95** [comment]
Did you move the node by hand or did you use some kind of source for the new coordinates? (Eg. vmangos, trinitycore, sniffs)

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Si1ker** [comment]
@anguaive why are you deleting in-game content? what's your reason/source for that?

**Comment by Branel** [comment]
@anguaive Si1lker's critical eye prevented us from making a misstake :D
https://tbcdb.com/?object=1618 see Redrige mountains and please create peaceblooms there as they seem to be some that are missing or need to be moved, I should have been more certain before making such a claim.

**Comment by anguaive** [comment]
@Hacki95 As far as I'm aware we don't know the exact blizz node locations so I hand picked the new location. Original bug report was about the plant being on the middle of the road so I thought moving it off the road would be sufficient (I ended up removing it afterwards)

@Si1ker IcemanHHW (person who submitted the bug) as well as sources like https://tbc.wowhead.com/object=1618/peacebloom and https://www.wowhead.com/object=1618/peacebloom say there are no Peaceblooms in Redrigde Mountains at all, so we agreed on removing them. Apparently https://tbcdb.com/?object=1618 claims the opposite. I can't check on live servers myself so I don't know who/what to believe at this point. If we come to a conclusion together I'd be happy to perform the DB updates.

**Comment by Branel** [comment]
Live servers wont make a better judgement. The tbc source supports that there is supposed to be a peacebloom at the original position just maybe moved to a better position, so I think the better choice is to use that as a source.

**Comment by FrancescoBorzi** [comment]
@anguaive there are errors, please check:

```
`pool_gameobject` has a non existing gameobject spawn (GUID: 1374) defined for pool id (950), skipped.
`pool_gameobject` has a non existing gameobject spawn (GUID: 1396) defined for pool id (950), skipped.
`pool_gameobject` has a non existing gameobject spawn (GUID: 1686) defined for pool id (950), skipped.
`pool_gameobject` has a non existing gameobject spawn (GUID: 1740) defined for pool id (950), skipped.
```

**Comment by syssneck** [comment]
Hi, I can confirm, that there should be no Peaceblooms in Redridge (WoW Vanilla Master Guide):
No Peacebloom in Redridge
Can this be merged? :)

**Pull request merged**
