### PR TITLE
Fix(DB): Shutting Down Manaforge Coruu

### PR DESCRIPTION
**Pull request by The-GhostRider**
## Changes Proposed:

[Anteprima](https://www.youtube.com/embed/YfKansM4gb0)
So..
I was unable to reproduce the problem (as show my video up)..
In fact I went to check the NPC trigger flags: [Coruu Control Console](https://wowgaming.altervista.org/aowow/?npc=20417)
And I must say that he has all the correct flags and should not attack Players..
But there is the remote possibility that due to strange dynamics that escape me now, these flags are sometimes ineffective, so I inserted an additional flag (for safety) making the NPC peaceful.

Screenshot_2

This way it is 100% sure that the NPC does not attack any player.

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4948
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17943

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Does not line up with a 45942 sniff.
```
Object Guid: Full: [Redacted] Creature/0 Map: 530 Entry: 20417
[...]
Flags: 33554688
Flags2: 2048
Flags3: 0
```

**Comment by Helias** [comment]
> Does not line up with a 45942 sniff.
> 
> ```
> Object Guid: Full: [Redacted] Creature/0 Map: 530 Entry: 20417
> [...]
> Flags: 33554688
> Flags2: 2048
> Flags3: 0
> ```

so this can be considered more a hackfix considering the official data from sniff?
do we have any other solutions?

I think that if we have no other solutions that can avoid this, we could even use this

**Comment by heyitsbench** [comment]
> so this can be considered more a hackfix considering the official data from sniff?

Going against sniff data is almost definitely a hackfix in my opinion.

> do we have any other solutions?

Passive react state would be my proposition, but that's just me.

**Comment by Nyeriah** [comment]
There’s absolutely no reason to use data that contradicts sniffed data, specifically when there are alternatives

**Comment by The-GhostRider** [comment]
https://github.com/azerothcore/azerothcore-wotlk/assets/1884642/b53da587-85b4-411f-99bf-2de8dd5b51e5

**Pull request closed without merging**
