### PR TITLE
fix(DB/Creature): Kargath Grunt equipment

### PR DESCRIPTION
**Pull request by poszer**
- Kargath Grunt are orcs that guard Kargath in Badlands. He should have axe equiped:
https://wowwiki.fandom.com/wiki/Kargath_Grunt
https://wow.gamepedia.com/Kargath_Grunt

##### CHANGES PROPOSED:

-  Equip axe
-  

###### ISSUES ADDRESSED:

Closes 

##### TESTS PERFORMED:

Yes, everything fine

##### HOW TO TEST THE CHANGES:

1. .go c6898

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
successfully tested

**Comment by solidmaxtor** [comment]
check nice axe but he is she?
image

**Comment by poszer** [comment]
> check nice axe but he is she? :-P
> 
> image

It has two models in DB :P

**Comment by Stoabrogga** [comment]
There's also a difference between grammatical gender and natural gender. The name for this NPC is "Kargath Grunt", no matter if it's female or male. Same for various city guards etc.

**Pull request merged**
