### PR TITLE
fix(Core/Pets): fixed crash happening when current pet is forcibly removed

### LINKED ISSUE #9995: Server Crash
### Current Behaviour

warlock summon a imp, then mount,and unmount ,the imp won't apear and summon another pet such as voidwalker
then crash 

### Expected Blizzlike Behaviour

won't crash

### Source

_No response_

### Steps to reproduce the problem

1.warlock cast summon imp
2.mount
3.unmount 
4.summon void walker

### Extra Notes

_No response_

### AC rev. hash/commit

235fea9ce569+

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Cheerypick https://github.com/Winfidonarleyan/TrinityCore/commit/d163735abdf37c8840dbb7e3151d91bc898473ef

## Issues Addressed:

- Closes #9995 

## Tests Performed:
-

## How to Test the Changes:
1.
2.
3.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@temperrr what is the results of the test?

**Comment by temperrr** [comment]
Needs more testing. Couldn't replicate the issue locally

**Comment by anzz1** [comment]
I can crash server with .pet create command, by first having any pet , then dismissing it (not abandoning) , and trying to use .pet create on another creature (not .npc tame which is a duplicate function but seems fixed somehow). Maybe related to this?

**Comment by Nyeriah** [comment]
> I can crash server with ".pet create" command like this: By first having any pet , then dismissing it (not abandoning). Then trying to use ".pet create" on a creature , server crashes.
> 
> Noteworthy is that ".npc tame" which is almost a duplicate function of ".pet create" (btw that should be fixed too) does not crash the server, instead it returns "creature not tameable" in this scenario. Even though the creature is indeed tameable but that error msg prevents a crash). What is should return as error msg is that you already have a pet, but it does not if you have a pet but it's currently dismissed.
> 
> Maybe related to this?
> 
> Also the current version of https://github.com/azerothcore/mod-npc-beastmaster also crashes the server when selecting a pet. [azerothcore/mod-npc-beastmaster#55](https://github.com/azerothcore/mod-npc-beastmaster/issues/55)
> 
> The mod-npc-beastmaster still works fine in [e5d650c](https://github.com/azerothcore/azerothcore-wotlk/commit/e5d650c5f3e35973b8b9acfbab31857c9a1c4134) . Something has been changed in the pet code since then and causing a crash. This should be investigated.
> 
> EDIT: Add more info

Does the crash you describe happen **with** this PR applied?

**Comment by anzz1** [comment]
Yup, still crashes.

Compiled this https://github.com/Winfidonarleyan/azerothcore-wotlk/commit/1320c60acaa6e02396745f934b5b90a7d69a36f9 with only one module: mod-npc-beastmaster at this commit https://github.com/azerothcore/mod-npc-beastmaster/commits/92ad11eae49c49e70003aed6c4237eff872cf35d

Made a orc hunter, set his level to 11, added the beastmaster .npc add 601026 , restarted server, chose a pet, same crash assert in SavePetToDB https://github.com/azerothcore/mod-npc-beastmaster/issues/55#issue-1094654960

.pet create after dismissing pet, same crash, except no assertion message and plain old access violation crash.

I think currently the pet system is broken and it would be better for users to revert to an older patch.

**Comment by Winfidonarleyan** [comment]
> Yup, still crashes.
> 
> Compiled this [Winfidonarleyan@1320c60](https://github.com/Winfidonarleyan/azerothcore-wotlk/commit/1320c60acaa6e02396745f934b5b90a7d69a36f9) with only one module: mod-npc-beastmaster at this commit [azerothcore/mod-npc-beastmaster@92ad11e](https://github.com/azerothcore/mod-npc-beastmaster/commit/92ad11eae49c49e70003aed6c4237eff872cf35d)
> 
> Made a orc hunter, set his level to 11, added the beastmaster .npc add 601026 , restarted server, chose a pet, same crash assert in SavePetToDB [azerothcore/mod-npc-beastmaster#55 (comment)](https://github.com/azerothcore/mod-npc-beastmaster/issues/55#issue-1094654960)
> 
> .pet create after dismissing pet, same crash, except no assertion message and plain old access violation crash.
> 
> I think currently the pet system is broken and it would be better for users to revert to an older patch.

can test without [azerothcore/mod-npc-beastmaster ?](https://github.com/azerothcore/mod-npc-beastmaster) ?

**Comment by Winfidonarleyan** [comment]
@mpfans, @betayi can retest with this changes?

**Comment by mpfans** [comment]
I need the day after tomorrow to test because I'm on vacation

**Comment by betayi** [comment]
> @mpfans, @betayi, @anzz1, can retest with this changes?

Is this change of unit.cpp a isolate patch or just a attachment of player.cpp and spelleffect.cpp edition patch ?

**Comment by anzz1** [comment]
Yep, still crashing. I didn't use the mod-npc-beastmaster at all, just .pet create.
Steps to reproduce:
1. I pulled this commit https://github.com/Winfidonarleyan/azerothcore-wotlk/commit/d748890d4cad8a73a8a4538002b4e3d5094c60f1 and built it.
2. I created a new Tauren Hunter character, used .character level 11 to bring it up to lvl 11.
3. I used .learn 2641 to learn [Dismiss Pet](https://wotlk.evowow.com/?spell=2641)
4. I walked to a npc next to spawn, a Plainstrider bird mob, targeted it and used .pet create. Plainstrider is now your pet.
5. I used Dismiss Pet spell to dismiss the plainstrider.
6. I targeted a new Plainstrider mob, and typed in .pet create -> Server crash, exactly the same as before.

**Comment by Nyeriah** [comment]
Does it still crash without the command? Just trying to isolate the problem here, if the server only crashes using the command then the command needs to be fixed and we can merge this meanwhile as it is rather critical

**Comment by Winfidonarleyan** [comment]
> Yep, still crashing. I didn't use the mod-npc-beastmaster at all this time, just .pet create. Steps to reproduce:
> 
> 1. I pulled this commit [Winfidonarleyan@d748890](https://github.com/Winfidonarleyan/azerothcore-wotlk/commit/d748890d4cad8a73a8a4538002b4e3d5094c60f1) and built it completely fresh.
> 2. I created a new Tauren Hunter character, used .character level 11 to bring it up to lvl 11.
> 3. I used .learn 2641 to learn [Dismiss Pet](https://wotlk.evowow.com/?spell=2641)
> 4. I walked to a npc next to spawn, a Plainstrider bird mob, targeted it and used .pet create. Plainstrider is now your pet.
> 5. I used Dismiss Pet spell to dismiss the plainstrider.
> 6. I targeted a new Plainstrider mob, and typed in .pet create -> Server crash, exactly the same as before.
> 
> EDIT: I tried now a build with [azerothcore/mod-npc-beastmaster@ed0ad17](https://github.com/azerothcore/mod-npc-beastmaster/commit/ed0ad17ebd5755d76e608f295ea4eef128745ab0) too. Now you cannot make the server crash anymore by talking to the beastmaster npc while having a dismissed pet. When you talk to the Beastmaster NPC and try to purchase a pet while having your pet out, he says "you must abandon or stable your current pet" like he should. If you dismiss and have a dismissed(unsummoned but active) pet and try to purchase a pet, he doesn't say anything but also a new pet won't come and the server doesn't crash.
> 
> But you can still crash the server by having no pet at all and purchasing a pet from him, or having a stabled pet and purchasing from him.
> 
>  
> 
> Build environment

fix command

**Comment by mpfans** [comment]
test now..

**Comment by anzz1** [comment]
Tested, it does not crash anymore with .pet create ! Good job. 
One more thing though: there are duplicate (but a bit different) commands at  

.pet create (HandlePetCreateCommand) : https://github.com/Winfidonarleyan/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_pet.cpp#L53
.npc tame (HandleNpcTameCommand) : https://github.com/Winfidonarleyan/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_npc.cpp#L1138

They are mostly same but with little differences so which is the right way now? also one of them should be either completely removed or just move the chat command to call the other handler. there shouldn't be a duplicate function (for example make .npc tame to call the HandlePetCreateCommand handler or just remove .npc tame func completely)

mod-npc-beastmaster still crashes but if this don't cause any other crashes then I guess it could be merged to core and just fix the module itself.

**Comment by Nyeriah** [comment]
Still crashing @Winfidonarleyan 

```Thread 27 "worldserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x14fdb2bfd700 (LWP 4010972)]
0x0000000000d8a787 in Pet::GetLoadPetInfo (stable=..., petEntry=0, petnumber=0, current=false)
#0  0x0000000000d8a787 in Pet::GetLoadPetInfo (stable=..., petEntry=0, petnumber=0, current=false)
#1  0x00000000012baab0 in Spell::CheckCast (this=0x14fa8b683800, strict=false) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:5939
#2  0x00000000012b86c1 in Spell::prepare (this=0x14fa8b683800, targets=<optimized out>, triggeredByAura=0x0) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3323
#3  0x00000000010ae872 in WorldSession::HandleCastSpellOpcode (this=0x14fa84226c00, recvPacket=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/SpellHandler.cpp:470
#4  0x00000000011d474b in WorldSession::Update (this=0x14fa84226c00, diff=10, updater=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:348
#5  0x00000000010e9bf4 in Map::Update (this=0x14fdd58ff140, t_diff=108, s_diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/Map.cpp:746
#6  0x00000000011061bd in MapUpdateRequest::call (this=0x14fada4d6380) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:44
#7  0x0000000001105b78 in MapUpdater::WorkerThread (this=0x1dea7d8 <MapMgr::instance()::instance+216>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:155
#8  0x000014fe1588ade4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x000014fe159a5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#10 0x000014fe1557a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
#0  0x0000000000d8a787 in Pet::GetLoadPetInfo (stable=..., petEntry=0, petnumber=0, current=false)
No locals.
```

**Comment by Winfidonarleyan** [comment]
> Still crashing @Winfidonarleyan 
> 
> ```Thread 27 "worldserver" received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x14fdb2bfd700 (LWP 4010972)]
> 0x0000000000d8a787 in Pet::GetLoadPetInfo (stable=..., petEntry=0, petnumber=0, current=false)
> #0  0x0000000000d8a787 in Pet::GetLoadPetInfo (stable=..., petEntry=0, petnumber=0, current=false)
> #1  0x00000000012baab0 in Spell::CheckCast (this=0x14fa8b683800, strict=false) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:5939
> #2  0x00000000012b86c1 in Spell::prepare (this=0x14fa8b683800, targets=<optimized out>, triggeredByAura=0x0) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Spells/Spell.cpp:3323
> #3  0x00000000010ae872 in WorldSession::HandleCastSpellOpcode (this=0x14fa84226c00, recvPacket=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Handlers/SpellHandler.cpp:470
> #4  0x00000000011d474b in WorldSession::Update (this=0x14fa84226c00, diff=10, updater=...) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Server/WorldSession.cpp:348
> #5  0x00000000010e9bf4 in Map::Update (this=0x14fdd58ff140, t_diff=108, s_diff=10) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/Map.cpp:746
> #6  0x00000000011061bd in MapUpdateRequest::call (this=0x14fada4d6380) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:44
> #7  0x0000000001105b78 in MapUpdater::WorkerThread (this=0x1dea7d8 <MapMgr::instance()::instance+216>) at /root/env/chromiecraft/azerothcore-wotlk/src/server/game/Maps/MapUpdater.cpp:155
> #8  0x000014fe1588ade4 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> #9  0x000014fe159a5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
> #10 0x000014fe1557a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
> #0  0x0000000000d8a787 in Pet::GetLoadPetInfo (stable=..., petEntry=0, petnumber=0, current=false)
> No locals.
> ```

Okay

**Comment by Winfidonarleyan** [comment]
> Tested, it does not crash anymore with .pet create ! Good job. One more thing though: there are duplicate (but a bit different) commands at
> 
> .pet create (HandlePetCreateCommand) : https://github.com/Winfidonarleyan/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_pet.cpp#L53 .npc tame (HandleNpcTameCommand) : https://github.com/Winfidonarleyan/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_npc.cpp#L1138
> 
> They are mostly same but with little differences so which is the right way now? also one of them should be either completely removed or just move the chat command to call the other handler. there shouldn't be a duplicate function (for example make .npc tame to call the HandlePetCreateCommand handler or just remove .npc tame func completely)
> 
> mod-npc-beastmaster still crashes but if this don't cause any other crashes then I guess it could be merged to core and just fix the module itself.

I rework this module, can test? - https://github.com/azerothcore/mod-npc-beastmaster/pull/56

**Pull request merged**
