### PR TITLE
fix(Core/SmartScripts): Added option to override current running time…

### LINKED ISSUE #12227: [quest]  `Hard to Swallow` bug
### Current Behaviour

use `Potent Explosive Charges`  unable to obtain quest items

https://youtu.be/8_cqaAWr-7g

### Expected Blizzlike Behaviour

use `Potent Explosive Charges`  , monster will be killed, and then there will be quest items on the ground

https://www.youtube.com/watch?v=mAMzC4zUXiM

### Source

_No response_

### Steps to reproduce the problem

1.  .q a 12049
2.  .go c id 26293
3.  Attack it and use `Potent Explosive Charges`  when he is weak

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…d actionlist.

Fixes #12227

## Issues Addressed:

- Closes #12227

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.q a 12049`
`.go c id 26293`
Attack it and use Potent Explosive Charges when he is weak

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
tested and work

**Comment by acidmanifesto** [comment]
at the moment we would need to know if any other smart scripts or quests are going to be effected with this pr since it is a core wide change of this nature. Are there any other examples of exsisting smart actions we can compare with as a control test to ensure nothing is regressing or breaking?

**Comment by UltraNix** [comment]
It's nothing breaking. It's just an extra option on default "0". Only one script just uses different value.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
> It's nothing breaking. It's just an extra option on default "0". Only one script just uses different value.

Thank you for the follow up and the PR.

**Pull request merged**
