### PR TITLE
fix(Core/Spells): Implemented PROC_EX_ONLY_FIRST_TICK.

### LINKED ISSUE #7677: Mage's Arcane Concentration Procs From Blizzard Far Too Frequently
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [x] Horde

### Content Phase:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour
Original report: https://github.com/chromiecraft/chromiecraft/issues/1502

Clearcasting

The mage talent Arcane Concentration procs Clearcasting all the time when you cast Blizzard spell. My mage can aoe casting Blizzard without wasting any mana. My mage in dungeons has no mana problems by casting Blizzard and Arcane Missiles

Tester: confirmed that Arcane Concentration is proccing off any damage done by Blizzard throughout the entire channel. At 10% per spell hit, this results in ridiculous numbers of Clearcasting procs. Here's an example, 5 CC procs in 8 seconds from one Blizzard cast - turn the sound on to hear them:

https://user-images.githubusercontent.com/81782124/131685212-cdb792be-4b19-47b2-b889-a0e6cecab77c.mp4

### Expected Blizzlike Behaviour

Correct behaviour is a flat 10% chance to proc if the spell does damage, not 10% per hit.

Clearcasting procs less (I think)
See the first video and notice when you hear the sound. Everytime you hear it the Clearcasting procs. In the retail the Clearcasting was proced when you started the spell and not when you channel it. This is the reason it procs that often.

Tester: from a related emulator project: 
> Talent Arcane Concentration works incorrectly when combined with Blizzard, repeatedly proc. during one Blizzard cast (the frequency depends on the number of mobs under the blizzard).
How it should work:
Chance of proc. Arcane Concentration must be calculated on the activation of the Blizzard. ([Source](https://github.com/SunwellWoW/Sunwell-TBC-Bugtracker/issues/572))

From a Mage FAQ: 
> How does Clearcasting work?											
> - This talent has a fixed 10% chance to proc as long as one mob is hit by one of your spells.												
> - Hitting multiple enemies will NOT increase your chance to get a proc.		
> - Yes, Clearcasting was """"""""""buffed"""""""""" on your private server.  ([Source](https://docs.google.com/spreadsheets/d/1uCXQni8Ndf0RuKfgNUlQ_jzfKIYmsCVuYXS_P3OaKUY/edit#gid=1879540205 ))

However, this quote comes from vanilla Classic, although I haven't found patch notes recording any changes between then and Wrath either.

Even from Reddit of all places has a discussion on the mechanics here: https://www.reddit.com/r/classicwow/comments/b478j2/arcane_concentration/
- "I think for channeled and AoE spells, only the initial cast is what procs Concentration."
- "One chance per spell cast (hitting the button) always."
- "All spell based procs are on a per-cast basis unless something specifically states otherwise."
- "Some private servers erroneously (MaNGOS core mainly) allow Clearcasting to proc per tick, not per cast and it's hilariously overpowered. With sufficient targets Mages have dramatically increased uptime on these servers, far beyond what was ever possible on retail."

There's also more discussion at https://tbc.wowhead.com/spell=12577/arcane-concentration#comments with the usual varying claims, some saying it's a flat 10% chance on a hit, and thus Blizzard shouldn't proc it any more than any other spell, and others disagreeing.

To be fair, I should also note a Wowwiki article that seems to provide evidence against this being incorrect:
"Further, Blizzards often proc clearcasting when allowed to run to their full duration, due to the large number of times Blizzard strikes and thus has a chance at proc'ing, which can sometimes mean that you can chain two, three, or even four Blizzards for no mana cost that all" ([source](https://wowwiki-archive.fandom.com/wiki/Arcane_Concentration))

As always for sources that disagree, it's a judgement call. Wowwiki/Wowpedia is typically a good source, so I'm reluctant to dismiss it, but should note that it's a player-edited site like any other, so can contain errors too. In this case, it's the only source I've found that says Blizzard + Arcane Concentration behaved like this. Every other source says it doesn't.

### Source

Example Video 1: https://youtu.be/-JRGW4P9g0c
Example Video 2: https://youtu.be/fpmenPU332k
Other sources as per above.

### Steps to reproduce the problem

Gather some mobs and cast Blizzard. Its better to have a tank because you cast without been hit

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #7677

## Issues Addressed:

- Closes #7677
- Closes https://github.com/chromiecraft/chromiecraft/issues/1502

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Be a mage.
2. Get `Arcane Concentration` talent (5 points)
3. Cast Blizzard/Arcane Missiles 
4. See if Clearcasting proc rate is bigger than 10%.
More info [here](#7677)

Omen of Clarity (druid) and Elemental Focus (Shaman) should be tested as well. 
These spells should be tested with some AOE spells (Hurricane/Tranquility for druids / Chain Heal/Chain Lighting for shamans) as well as some channeled or single spells to ensure there are no new bugs.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by stoudtlr** [comment]
Mage testing with PR:
Blizzard 50 times.  Clear Casting procced on cast #'s: 9, 19, 21, 23, 28, 32, 38, 43, 46, 50 - Averages to 20%
Tried Firebolt 50 times.  Clear Casting procced on cast #'s: 7, 29, 34, 41, - 8%
Flamestrike 50 times.  Clear Casting procced on #'s: 5, 6, 8, 10, 11, 13, 30, 37, 44 - 18%
Frostbolt 50 times. Clear Casting on #'s: 8, 25, 26, 33, 37 - 10%

Blizzard and Flamestrike testing above was done with two test dummies so each cast hit two targets.
Testing both again with only 1 target.
Blizzard: 2, 9, 11, 18, 21, 22, 32, 47, 48 - 18%
Flamestrike: 1, 5, 21,  38, 42, 49, - 12%

will test more later with other spells

**Comment by stoudtlr** [comment]
@UltraNix testing finished.  Here's results for Druid and Shaman.

Druid
Moonfire - 1,5,6,9,19,24,38,45 - 16%
Starfire - 5,12,13,16,24,29,33,40,45 - 18%
tranquility - 0% - tested this one 50 times solo and an additional 50 in a group. Clear casting never procced
wrath - 12,18,22,25,27,31,49 - 14%
hurricane - none, 0%

Shaman
Lightning bolt - 9,21,33 - 6%
chain lightning 3,4,13,15,16,31,33,36 - 16%
Earth Shock - 5,8,17,31,43,46 - 12%
Lava Burst - 14,21,38,42 - 8%
Chain Heal - none, 0%

all aoe and chain damage spells were testing on a group of two training dummies.  aoe and chain heals were done with two character group.

**Comment by UltraNix** [comment]
@stoudtlr Remember that Shaman's Elemental Focus works only with critical strikes.

**Comment by stoudtlr** [comment]
> @stoudtlr Remember that Shaman's Elemental Focus works only with critical strikes.

You're right. Other two classes can proc on any cast while Shamans can only proc from a crit.  That means it should have been 0% for all of my Shaman tests since they were done on an ungeared character with base 0% crit chance, right?

**Comment by UltraNix** [comment]
I must say that there is something wrong with the RNG system. 5 tests and 5 different numbers. This is not covered by that PR
The main problem has been resolved with that PR - `Arcane Concentraction` is proccing only on first tick of Blizzard/Arcane Missiles.

**Comment by stoudtlr** [comment]
Agreed. With all the multi hit spells I tested it was  only the first hit that triggered the buff. None of the subsequent hits did.

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
