### PR TITLE
refactor(Core/Game): restyle game lib with astyle

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## CHANGES PROPOSED:
- Restyle `game` lib with astyle

### Used arguments:
- `-A1 -xV -S -N -K -Y -p -xg -k1 -W1 -O -xM`

## Target branch(es):
- [x] Master

### About
- http://astyle.sourceforge.net/

### CODE REVIEW

**Comment by Helias** [comment]
Is needed to solve conflicts

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan there are conflicts here

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan conflicts

**Comment by Winfidonarleyan** [comment]
Done

**Comment by Winfidonarleyan** [comment]
Very nice, Welcome normal codestyle in all core :D

**Pull request merged**
