### PR TITLE
feat(Core/Time): Implement saparated manager for game time

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Created `GameTime` namespace and `UpdateTime` class and moved their code out of `World` class
- Delete diff tracker
- Correct calculate average diff
- Calculate time with `std::chrono` lib https://en.cppreference.com/w/cpp/chrono/time_point/time_since_epoch

## Issues Addressed:
- General part #6490 

## SOURCE:
- https://github.com/TrinityCore/TrinityCore/commit/7567cafec84080d26ea513242a1f540a823b8f9d
- https://github.com/TrinityCore/TrinityCore/commit/12701cb0c6c45eb105ad449eb9a56e76d84d691e

## Tests Performed:
image
image
image

- Tested spells cooldown
- Tested BG
- Tested uptime
- Tested shutdown/restart core

## How to Test the Changes:
- Just test functions which are time-dependent
- Need test BF Wintergrasp
- Need test reset daily/weekly/mountly quests

## Known Issues and TODO List:
- [x] Doc changes
- [ ] https://github.com/azerothcore/mod-cfbg/pull/80
- [ ] https://github.com/azerothcore/mod-ah-bot/pull/47
- [ ] https://github.com/azerothcore/Eluna/pull/16
- [x] Wait merge #8663

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
Need review

**Comment by Kitzunu** [comment]
conflict

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by FrancescoBorzi** [comment]
that's a conflict

**Comment by Winfidonarleyan** [comment]
Ready review

**Review by Kitzunu — APPROVED** [review]
looks good as far as I can tell

**Comment by Winfidonarleyan** [comment]
Wait - https://github.com/azerothcore/azerothcore-wotlk/pull/10207

**Review by Nyeriah — APPROVED** [review]

**Comment by coolzoom** [comment]
the core is ruined after this commit

**Pull request merged**
