### PR TITLE
Removed cooking requirement for Beer Basted Boar Ribs quest

### PR DESCRIPTION
**Pull request by sh3rp**
## Changes Proposed:
Remove Cooking requirement for quest

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14033
- Closes https://github.com/chromiecraft/chromiecraft/issues/4524

## SOURCE:
see issue

## Tests Performed:
- Created dwarf character, went to quest giver, verified quest giver is available without the cooking skill trained

## How to Test the Changes:
1. Create dwarf char
2. .levelup 4
3. .go c id 1267
4. Verify quest is available for pick up
5. Pick up quest from quest giver

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
In the `Issues Addressed:` section, please place `Closes` in front of the issue link, and if it's tied to a ChromieCraft issue, please try to include that one as well. For example:
```
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14033
- Closes https://github.com/chromiecraft/chromiecraft/issues/4524
```

**Comment by Gultask** [comment]
We can't merge this, unfortunately.
QuestSortID are sniffed values. See: https://github.com/azerothcore/azerothcore-wotlk/pull/14034

It's probably an issue with the core.

**Comment by sh3rp** [comment]
> We can't merge this, unfortunately. QuestSortID are sniffed values. See: #14034
> 
> It's probably an issue with the core.

I'm new here, so pardon my ignorance.

In the referenced PR, there is a single update to the `quest_template_addon` table which removes the skill requirement.  In this PR, I also removed the reference to the QuestSortID (which I believe is related to the quest DBC?) that references the cooking skill requirement.

Why can't that second part be executed?  What about "sniffed values" stops us from fixing them?  And I thought the quest_template modification was a Core modification?

**Comment by heyitsbench** [comment]
> And I thought the quest_template modification was a Core modification?

Anything done in a SQL query is a change to the database.

> What about "sniffed values" stops us from fixing them?

Sniffed values are values taken *directly* from packets sent from Blizzard to the client (in this case, Wrath Classic iirc) so they are thus (for the vast, vast, vast majority) inherently correct.

**Comment by Gultask** [comment]
Sniffed values are confirmed to be the true values used by Blizzard themselves. They are sent from the server directly to the client.

In this case:
`QuestSortID: -304` This is sniffed. We aren't supposed to change it since it's the value Blizzard themselves use and can be confirmed.

What I mean by "Core" is the cpp core of AzerothCore, not the DB itself.

**Comment by sh3rp** [comment]
> Sniffed values are confirmed to be the true values used by Blizzard themselves. They are sent from the server directly to the client.
> 
> In this case: `QuestSortID: -304` This is sniffed. We aren't supposed to change it since it's the value Blizzard themselves use and can be confirmed.
> 
> What I mean by "Core" is the cpp core of AzerothCore, not the DB itself.
> 
> Edit: Almost got here before Bench😔

Got it.  I'll close this PR then and start digging around the Core.  This is a great opportunity to get familiar with the code base, I think.

Really appreciate your help @Gultask @heyitsbench.

**Comment by Gultask** [comment]
Don't worry about it. And thanks for the contribution. It means a lot!❤️‍🔥

**Pull request closed without merging**
