### PR TITLE
[Core/Scrips]: Kologarn focused eyebeam should target only 1 target.

### PR DESCRIPTION
**Pull request by lineagedr**
## Changes Proposed:
-  Change eyebeam trigger MaxAffectedTargets to 1

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7351

## Tests Performed:

- Tested with the method below

## How to Test the Changes:

1. Login on more than 1 character
2. Make your way through ulduar to Kologarn
3. Engage the boss and wait 10 seconds for him to cast focused eyebeam
4. Observe if the beam now only targets one character

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by blacknightt1** [comment]
https://github.com/TrinityCore/TrinityCore/blob/c37da124c3609b636a769175c793ac7ab58120c1/src/server/game/Spells/SpellMgr.cpp#L3868

In the version
trinitycore
I checked in the game and this was a fixed case but
In azerothcore

No

**Comment by FrancescoBorzi** [comment]
@lineagedr please check last comment and also merge conflicts

**Comment by lineagedr** [comment]
@FrancescoBorzi There's nothing to address. I've tested it multiple times the boss casts the beam to one person.


https://user-images.githubusercontent.com/12139798/130304245-a99ddf86-184b-49e0-831d-283c927df41b.mp4

**Comment by blacknightt1** [comment]
> 
> 
> @FrancescoBorzi There's nothing to address. I've tested it multiple times the boss casts the beam to one person.
> 2021-08-21.02-39-05.mp4


We tested this several times and it was a bug But you say there is no problem!

https://youtu.be/uVmrSJEJWck

**Comment by lineagedr** [comment]
@blacknightt1 By the looks of the video you are running on https://github.com/azerothcore/azerothcore-wotlk/commit/7b343d0088a74a051640faee9b2a0926f9d023e0  and you haven't even applied this PR to your core. Not sure how you expect it to be working if you haven't added the fix to your core.

**Pull request merged**
