### PR TITLE
Core/Fixes: Update Source AzerothCore

### PR DESCRIPTION
**Pull request by Bodeguero**
Update Source AzerothCore

AuthServer:
logo

WorldServer:
logo

I compile on Linux and Windows - the mistakes that I've had I fixed.

I hope the community like! :facepunch: 

PS: Forgive me for the mistakes in English - I use the Google translator :innocent:

### CODE REVIEW

**Comment by Yehonal** [comment]
This README is quite ambiguos: https://github.com/AzerothCore/azerothcore-wotlk/blob/4e116ccca66988cffa3a4cf74e7d1b43ccfeed33/README.md

**Comment by Bodeguero** [comment]
@Yehonal  I did not understand what I meant? Because quite ambiguous - did something wrong? I did not understand anything!

**Comment by Yehonal** [comment]
You are taking about paying services in this readme

Il 20/Lug/2016 13:45, "Bodeguero" <notifications@github.com> ha scritto:

**Comment by Bodeguero** [comment]
@Yehonal well fixed error in [README.md](https://github.com/AzerothCore/azerothcore-wotlk/pull/18/commits/997bdb2e2f1fecb497bce67af88b67668d3f148d)!

I thought it was something serious just a simple error that can be corrected! It was my fault not correctly read the information because I have my private sources! Anyway, I think now this without problems!

**Comment by ShinDarth** [comment]
@Bodeguero thanks for this PR, may you squash those commits?

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by ShinDarth** [comment]
also, I see almost "5k file changed"... what's happening?

**Comment by ShinDarth** [comment]
@Bodeguero 

first of all thanks for your PR.

However, I see that there are almost 5k file changed, could you please split your work into modular PRs so it is easier for the developers to review and accept them?

For instance, one PR to edit the initial welcome message in the console, etc...

**Comment by Bodeguero** [comment]
@ShinDarth can let so I will now forward!If they are not using my PR can shut it!

**Comment by ShinDarth** [comment]
ok, just open new separated PRs

**Comment by Bodeguero** [comment]
@ShinDarth ok man!

**Comment by ShinDarth** [comment]
@Bodeguero can you open a separated PR to change the welcome message?

image

**Comment by Bodeguero** [comment]
@ShinDarth see changes:
[authserver](https://github.com/Bodeguero/AzerothCore_/blob/3.3.5_OS_LINUX/src/server/authserver/Main.cpp#L114-L132)

[worldserver](https://github.com/Bodeguero/AzerothCore_/blob/3.3.5_OS_LINUX/src/server/worldserver/Master.cpp#L129-L147)!

:facepunch:

**Comment by ShinDarth** [comment]
Can you open a PR? I can tell you how if you want

**Comment by Bodeguero** [comment]
@ShinDarth 

[Pull Requests 23](https://github.com/AzerothCore/azerothcore-wotlk/pull/23)
[Pull Requests 24](https://github.com/AzerothCore/azerothcore-wotlk/pull/24)

**Comment by ShinDarth** [comment]
@Bodeguero 

thanks a lot for your help!

just some tips:  

- you can open one single PR for one feature (you don't need to open one for each file, just wrapping each feature into a PR)
- fix the code indentation

:+1:

**Pull request closed without merging**
