### PR TITLE
Header include optimization SpellAura.h SpellAuraEffects.h

### PR DESCRIPTION
**Pull request by niaro-kitty**
Header include optimization for files: SpellAura.h SpellAuraEffects.h

## CHANGES PROPOSED:
Header include optimization for files: SpellAura.h SpellAuraEffects.h
Remove include "SpellInfo.h"

## TESTS PERFORMED:
Only compile

## HOW TO TEST THE CHANGES:
Only compile

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
Only compile

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Thank you for this PR!

Please, can you run this file in your root Azerothcore `bash apps/git_tools/setup_git_commit_template.sh` ? it's just an help for better commit names

**Comment by FrancescoBorzi** [comment]
> HOW TO TEST THE CHANGES:
> Only compile

o_O

**Comment by niaro-kitty** [comment]
Yes. Never used

**Comment by Rochet2** [comment]
looks fine. I wonder if its possible to remove the spellinfo include in spell.h in an easy way as well. cant see it used there.

**Comment by FrancescoBorzi** [comment]
@Rochet2 you can approve the PR if you think it's fine ;)

**Comment by FrancescoBorzi** [comment]
has anyone tested this in game?

**Comment by BarbzYHOOL** [comment]
test what and how?

**Comment by FrancescoBorzi** [comment]
if I understood correctly, just logging in game a try a few spells should be enough

**Comment by FrancescoBorzi** [comment]
@niaro-kitty why closing this?

**Comment by BarbzYHOOL** [comment]
@Rochet2 what the hell did this PR do tho?

**Comment by Rochet2** [comment]
It removes unnecessary including of files.
That will speed up compilation for example.

**Comment by niaro-kitty** [comment]
i don't like tag ragequit :(

**Comment by FrancescoBorzi** [comment]
@niaro-kitty 

image

**Comment by niaro-kitty** [comment]
I was in a bad mood that day  ._.

**Comment by FrancescoBorzi** [comment]
maybe next time I'm in a bad mood I'll close the entire AzerothCore project :)

joking apart, thanks for your contribution

**Comment by BarbzYHOOL** [comment]
I removed the tag yesterday, weird it didn't display. Anyway it fit exactly what happened and we use this tag to find old PRs that can be reopened.

**Comment by BarbzYHOOL** [comment]
@niaro-kitty it was merged, thank you!

**Pull request merged**
