### PR TITLE
fix(DB/HallsOfStone): Triggers in Tribunal of Ages

### PR DESCRIPTION
**Pull request by Si1ker**
Tested in live server with ~130 players
No negative script/side-effects found.

## Issues Addressed:

* Trigger attacking players - Fix trigger aggro (updates flags)
image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Don't change modelid fields, those are sniffed. AC is missing probabilities fields. Until implemented create an SAI to change modelid on_respawn.
You can disable combat by adding `unit_flags`|768 as well.

**Comment by Si1ker** [comment]
@Gultask check now.

**Comment by Gultask** [comment]
Without any script the creature will definitely use the bad modelid every once in a while :S

**Comment by Si1ker** [comment]
> Without any script the creature will definitely use the bad modelid every once in a while :S

@Gultask , what's the matter? addition of flag_extra 130 makes the trigger:
<html>
<body>


2 | CREATURE_FLAG_EXTRA_CIVILIAN | 0x00000002 | creature does not aggro (ignore faction/reputation hostility)
-- | -- | -- | --



</body>
</html>

<html>
<body>


128 | CREATURE_FLAG_EXTRA_TRIGGER | 0x00000080 | creature is trigger-NPC (invisible to players only)
-- | -- | -- | --



</body>
</html>

Previously field was set to 0 which caused the problem.

**Comment by Gultask** [comment]
Ahh I see, sorry I'm not used to that flag.

**Review by Gultask — APPROVED** [review]

**Pull request merged**
