### PR TITLE
fix(DB/Quest) : Venomhide Eggs quest not bound to prerequisites

### PR DESCRIPTION
**Pull request by razers211**
## Scope:
      Fix(DB/Quest) : Venomhide Eggs quest not bound to prerequisites

## Description :
         The quest "Venomhide Eggs" is acceptable without completing "Toxic To>
         

## Issues Addressed:

- issue #6962

## Changes Proposed:
-  add the missing  quest requirements in quest_template_addon for quest "Venomhide Eggs"
-

### CODE REVIEW

**Comment by Kitzunu** [comment]
Dont ignore the pr template

**Comment by razers211** [comment]
> Dont ignore the pr template

should i redo the PR ?

**Comment by Kitzunu** [comment]
no, you just need to update your comment =)

**Comment by FrancescoBorzi** [comment]
hello @razers211 and thanks for your contribution, welcome to AzerothCore!

a small tip from me (for next time): you don't need 2 separate pending files, you can place all your SQL code in once (unless it's really big but this is not the case)

**Review by LukasVolgger — CHANGES_REQUESTED** [review]
Oh, although the code looks good please solve the conflicts as

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Review by LukasVolgger — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by LukasVolgger** [comment]
Tjx @razers211 and @pklloveyou !

**Pull request merged**
