### PR TITLE
fix(DB/creature_template): Remove bleed immunity from Escape from Durnholde bosses.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:
- Removes the bleed immunity mask from [Lieutenant Drake](https://www.wowhead.com/wotlk/npc=17848), [Captain Skarloc](https://www.wowhead.com/wotlk/npc=17862), and [Epoch Hunter](https://www.wowhead.com/wotlk/npc=18096), including their heroic variants.

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4944.

## SOURCE:

Original issue, as well as Wrath Classic.

## Tests Performed:

- Tested in-game, works as observed on Wrath Classic.

## How to Test the Changes:

1. `.tele oldhillsbrad`
2. `.quest add 10277`
3. `.quest reward 10277`
4. Enter the dungeon.
5. Try to cast a bleeding spell (such as [Rend](https://www.wowhead.com/wotlk/spell=47465)) on the three bosses.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Won't we need heroic versions as well?

**Review by Gultask — APPROVED** [review]

**Comment by heyitsbench** [comment]
> Won't we need heroic versions as well?

If we want to lump those in to this PR as well, that's fine by me. Testing them on Classic will probably be a bit, but it's unlikely the immunities are different, at least IMO.

**Comment by Gultask** [comment]
Getting info for Heroic versions in Classic as well is too much trouble, don't worry about that 😂
It's just so that we don't run into the same exact issue a few months from now.

**Comment by Nyeriah** [comment]
@heyitsbench Please don't specify the table, specifying what it is about in the title is around enough (TrinityCore commit message style)

**Comment by heyitsbench** [comment]
> Please don't specify the table, specifying what it is about in the title is already enough (TrinityCore commit message style) e.g "fix(DB/Creature)"

Feel free to submit a PR to the wiki to clarify that convention.

**Comment by Nyeriah** [comment]
@heyitsbench If you need further clarification on how to write commit messages following the convention we use you're free to write me a message on Discord @ Nyeriah#8793

**Comment by heyitsbench** [comment]
No one should have to go through Discord DMs to understand the convention.

**Comment by Nyeriah** [comment]
I appreciate your cooperation 👍

**Comment by heyitsbench** [comment]
> I appreciate your cooperation 👍

Give me a clear and concise standard to abide by and I'll gladly do it. I am not of the opinion that "subscope" is clear nor concise. I can only write so many standards for the wiki myself.

**Comment by Kitzunu** [comment]
Just look at all the past 8k commit

**Comment by heyitsbench** [comment]
> Just look at all the past 8k commit

https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+%28DB%2Fcreature_template%29+

**Comment by Nyeriah** [comment]
> > Just look at all the past 8k commit
> 
> https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+%28DB%2Fcreature_template%29+

Those are pull requests, if you look into the actual commits we've been correcting them every single time... sometimes they slip, but we try our very best. The very first item in your list: 

https://github.com/azerothcore/azerothcore-wotlk/pull/14495

image

was merged as:

image

**Pull request merged**
