### PR TITLE
fix(DB): Fix Some Gnomeregan Issues - Missing Animations, Spells and Texts

### PR DESCRIPTION
**Pull request by LannyE**
## Changes Proposed:
- Fix the animation on the Sparklematic 5200
- Fix Techbots missing texts, spell conditions and dupe bug management
- Remove non-summoned dupe bugs from the creature table
- Fix the Irradiation Aura on irradiated creatures
- Fix duplicted text on creature ID 6223 and 6224 (Leper Gnomes)
- Fix irradiation splash damage SAIs and texts for nearby creature   

## Issues Addressed:
Techbot (id: 6231) is missing some texts, spell conditions, and dupe bug managment
Sparklematic 5200 (id: various) Missing animation on quest completion
Irradiated Mobs missing irradiation auras
Leprous Mobs have texts duplicated in DB
Various Mobs missing irradiation splash texts and spellhit SAI

Reference:
https://github.com/TrinityCore/TrinityCore/issues/18825
https://github.com/TrinityCore/TrinityCore/issues/18737
https://github.com/TrinityCore/TrinityCore/issues/21560

## Tests Performed:
- Test Sparklematic 5200
- Tested Techbot
- Tested Leper Gnomes
- Tested Irradiated Creatures splashing other nearby creatures
- 

Tested in-game on Windows

## How to Test the Changes:
 
- To go Gnomeregan
- Engage Leper gnomes and see if they speak on aggro.
- Look at irradiated mobs and see if they have the green aura shown below.
WoWScrnShot_022021_131719
- Go to Techbot 
- fight him and look for new text dialogue during fight
- Check for summoned dupe bugs
- Check for dupe bugs despawning after battle
- Check for battle net spell to only affect players
- Check for patch spell to only kill Dupe bugs
- Go into the Gnomeregan instance
- Get a grime-encrusted object 
- Go to the holdout area
- Complete a Sparklematic 5200 quest using the Sparkelmatic 5200 and observe if the Spraklematic has an animation. 
- Check for emote dialogue of nearby creatures getting splashed by irradiation after killing you kill an irradiated creature.   

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @LannyE !

**Comment by LannyE** [comment]
I think I found a minor bug in the Caverndeep Ambusher and the Dark Iron Agent text.  Do you want me to make a new PR or do another commit to fix it?

**Comment by LannyE** [comment]
Sorry, I needed to add these fixes due to fixing the things I did revealed DB errors already present in the core DB.  I found them as I was running through Gnomeregan again while testing another PR I am working on.  I also noticed I deleted the already present Dark Iron Agent text so I felt it was necessary to correct this before moving it to production.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @LannyE for the update

**Pull request merged**
