### PR TITLE
fix(DB/quest_template_locale): Add some ruRU localization to multiple quests.

### LINKED ISSUE #14145: (DB/Locale): The Prophecy of Akida
### Current Behaviour

https://www.wowhead.com/tbc/quest=9544/the-prophecy-of-akida

Not translated into Russian progress and a brief description of the task

### Expected Blizzlike Behaviour

Should be multi-language support

### Source

_No response_

### Steps to reproduce the problem

Just take this quest

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+ 

### Operating system

Debian 11

### LINKED ISSUE #14146: (DB/Locale): Therylune's Escape
### Current Behaviour

https://www.wowhead.com/quest=945/therylunes-escape

No localization ruRU quest objectives 

### Expected Blizzlike Behaviour

Should be multi-language support

### Source

_No response_

### Steps to reproduce the problem

Just take this quest,

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+ 

### Operating system

Debian 11

### LINKED ISSUE #14148: (DB/Locale): An Aggressive Defense
### Current Behaviour

https://www.wowhead.com/wotlk/quest=1025/an-aggressive-defense

After killing the necessary opponents
a task appears (return to npc)
which is not translated into Russian

### Expected Blizzlike Behaviour

Should be multi-language support

### Source

_No response_

### Steps to reproduce the problem

Take this quest, complete it, and when you turn it in, you will find that there is no ruRU localization.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+ 

### Operating system

Debian 11

### Custom changes or Modules

image_2022-12-12_07-58-33

### LINKED ISSUE #14159: (DB/Locale): Pridewings of Stonetalon
### Current Behaviour

https://www.wowhead.com/wotlk/quest=1134/pridewings-of-stonetalon

Quest objectives, after the conditions are met (Return to NPC) not translated into Russian

### Expected Blizzlike Behaviour

Should be multi-language support

### Source

_No response_

### Steps to reproduce the problem

Take this quest, complete it, and when you turn it in, you will find that there is no ruRU localization.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 20da358afbd5+ 

### Operating system

Debian 11

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:
- Adds ruRU localization for CompletedText to quests 945, 1011, 1022, 1025, 1034, 1035, 1134, and 9517 and ObjectiveText to quest 9544.

## Issues Addressed:

- Closes #14145
- Closes #14146
- Closes #14159
- Makes progress towards #14147
- Makes progress towards #14148
- Makes progress towards #14174
- Makes progress towards #14183
- Makes progress towards #14184
- Makes progress towards #14185

## SOURCE:

Wrath Classic live sniffs.

## Tests Performed:

- Untested.

## How to Test the Changes:

1. Run the query.
2. Start the game with ruRU localization.
3. `.quest add` the related quests.
4. Observe Russian objective texts.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by PivanDepolo** [comment]
After applying your SQL queries are not translated quest objectives for https://github.com/azerothcore/azerothcore-wotlk/issues/14145 anyway

**Comment by heyitsbench** [comment]
> After applying your SQL queries are not translated quest objectives for #14145 anyway

Please clear your client cache. 
image

**Comment by PivanDepolo** [comment]
> > After applying your SQL queries are not translated quest objectives for #14145 anyway
> 
> Please clear your client cache. image

Deleted the entire WTF folder. Restarted the server. 
Still not translated for me

**Comment by PivanDepolo** [comment]
Ah, it works now. Thank you sir!

**Comment by heyitsbench** [comment]
> Ah, it works now. Thank you sir!

Thank you for testing! ❤️

**Comment by PivanDepolo** [comment]
But anyway for https://github.com/azerothcore/azerothcore-wotlk/issues/14185 quest objectives are not translated.

**Comment by heyitsbench** [comment]
> But anyway for #14185 quest objectives are not translated.

Is [this text mentioned in the related issue](https://user-images.githubusercontent.com/38561765/207239107-1e38e201-d77e-4c10-904d-9e19c7bed962.png) translated?

**Comment by PivanDepolo** [comment]
> > But anyway for #14185 quest objectives are not translated.
> 
> I'll try to get that fixed as well tomorrow. Is [this text mentioned in the related issue](https://user-images.githubusercontent.com/38561765/207239107-1e38e201-d77e-4c10-904d-9e19c7bed962.png) translated?

Yes sir.

**Comment by PivanDepolo** [comment]
When passing this [quest ](https://github.com/azerothcore/azerothcore-wotlk/issues/14148) phrases are not translated too(

**Comment by PivanDepolo** [comment]
I don't know what happened to AС. There was no such problem in 2019. Now almost every second quest is not translated.

**Comment by heyitsbench** [comment]
> When passing this [quest ](https://github.com/azerothcore/azerothcore-wotlk/issues/14148) phrases are not translated too

Yes, unfortunately the method I'm using to get the texts in this PR does not grab text in that window. If you could add that text to the [issue](https://github.com/azerothcore/azerothcore-wotlk/issues/14148), I would appreciate it. I'll also update this PR description accordingly.

> There was no such problem in 2019. Now almost every second quest is not translated.

I unfortunately was not around in 2019, couldn't tell you what could have happened. 😦

**Comment by PivanDepolo** [comment]
> > When passing this [quest ](https://github.com/azerothcore/azerothcore-wotlk/issues/14148) phrases are not translated too
> 
> Yes, unfortunately the method I'm using to get the texts in this PR does not grab text in that window. If you could add that text to the [issue](https://github.com/azerothcore/azerothcore-wotlk/issues/14148), I would appreciate it. I'll also update this PR description accordingly.

If I knew where to get the correct ones already translated, I would have fixed it myself. But I do not know(

**Comment by heyitsbench** [comment]
> If I knew where to get the correct ones already translated, I would have fixed it myself. But I do not know(

For things that my sniffs can't grab, using the [Russian version of Wowhead](https://www.wowhead.com/wotlk/ru) is likely a good enough source if you'd like to throw them on the issues or submit the PRs yourself. 😀

**Comment by PivanDepolo** [comment]
> When passing this [quest ](https://github.com/azerothcore/azerothcore-wotlk/issues/14148) phrases are not translated too( 

I fixed it by this query => 
`INSERT INTO `quest_offer_reward_locale` (`ID`, `locale`, `RewardText`, `VerifiedBuild`) VALUES (1025, 'ruRU', 'Славная работа, $N. Спасибо тебе.', 18019);`

I take translation from wowhead

**Pull request merged**
