### PR TITLE
feat(Core/Logging): rework logging

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Base (start) commit https://github.com/TrinityCore/TrinityCore/commit/55ce180f2867700b28921d99f9a0cb9c83330c91

## Issues Addressed:
- Part #3719
- Part #4669

## Tests Performed:
- Windows (me and @Kitzunu)
- Linux `Ubuntu 20.04` (me)

## How to Test the Changes:
- Check console and files
- Check doc

## Target Branch(es):
- [x] Master
 
## How to Test AzerothCore PRs

When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

---

## About new logging system
- Logging documentation - https://github.com/azerothcore/azerothcore-wotlk/blob/a071ab46b77d4b09b244c2e193e6a63d46197bf7/doc/Logging.md

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
Ready to test

**Comment by Winfidonarleyan** [comment]
Add documentation

**Comment by claudiodfc** [comment]
Can't build due to errors

**Comment by Winfidonarleyan** [comment]
@claudiodfc corrected build

**Comment by claudiodfc** [comment]
Hey Winfi, trying to pull the PR, however, when pulling there's conflicts on merge:

```
both modified:   src/server/game/Globals/ObjectMgr.cpp
both modified:   src/server/scripts/Commands/cs_reload.cpp
```

**Comment by Winfidonarleyan** [comment]
Okay, need time for solve

**Comment by Winfidonarleyan** [comment]
@claudiodfc try test

**Comment by Kitzunu** [comment]
I followed all steps Winfi gave me in Discord and it works

**Review by Kitzunu — APPROVED** [review]
Approving as the testing worked, not going to review 246 files D:

**Comment by FrancescoBorzi** [comment]
> Approving as the testing worked, not going to review 246 files D:

fair enough, but the build is still failing

**Comment by Winfidonarleyan** [comment]
Fix today

**Comment by Winfidonarleyan** [comment]
Ready

**Comment by Kitzunu** [comment]
When I tested it works so for me its good to go as build is passing

**Comment by Kitzunu** [comment]
Merge Conflicts

**Comment by Kitzunu** [comment]
Thanks!

**Pull request merged**
