### PR TITLE
feat(Core/Player): PartyLevelReq invite settings

### PR DESCRIPTION
**Pull request by poszer**
New world setting

##### CHANGES PROPOSED:

-  Minimum level at which players can invite to group setting
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1918

##### TESTS PERFORMED:

Yes, builded on win without problems. Tested in game with two characters created (Level 1) using the setting to 10, it doesn't allow invite to party sending the msg to character who trying to invite '' Trial accounts are not allowed to invite in group '' . This is old setting, which already exist on some cores, i ported it from StormCore. Since we have already implemented configurations in the world for chat restrictions, this is ideal so the new players who come on server to advertise won't be able to do it until they have required level for invite (Bcoz this is abused by checking /who -> Creating party -> And sending msg advertisements in party)  :smile:  

##### HOW TO TEST THE CHANGES:

1. Create 2 characters, level 1 and level 10 example
2. Set configuration in worldserver.conf to PartyLevelReq = 5 or 10
3. Try to invite character from character who is level 1 

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Hir0shi** [comment]
@poszer 

i will to tested but, So what's Guild!

ChatLevelReq.Guild = ?

**Comment by poszer** [comment]
> @poszer
> 
> i will to tested but, So what's Guild!
> 
> ChatLevelReq.Guild = ?

Nothing, test this and write comment :smile: Abt Guild, When i have time, i'll look in that setting also :D 
P.S Do not be aggresive, and do not use exclamation, i don't like to see it and also It can be understood incorrectly  -.- Be grateful for this because you opened the issue a few hours ago, and already it's fixed. Enjoy

**Comment by Mindustry** [comment]
Tested on a Windows 10 64-bit build. 
Took some screenshots for this one to show what the issue was and how @poszer fixed it successfully. Sorry if it's a little image heavy. 
All tested successfully, config was added to .dist file properly, it's a needed feature. Thanks again, poszner. 

Right now it's possible to block anyone under a certain level to chat, whisper, trade, make auctions, make tickets, and even send/receive mail. The one thing they can do is spam party invites and then advertisements to anyone who accidentally or unexpectedly accepts. 
WoWScrnShot_053119_112654
WoWScrnShot_053119_112704


#1919 Successfully adds a config option that allows you to block players from inviting under a certain level.   
config
WoWScrnShot_053119_114331


It's also successful in allowing friends to invite each other despite level difference. 
WoWScrnShot_053119_114448
WoWScrnShot_053119_114449

**Comment by Hir0shi** [comment]
Thankyou for test @Mindustr

. PartyLevelReq fixed.

1.create guild
2.try to invite character level "1" from guild
3.character can chat on the guild level "1"

. GuildLevelReq ?

**Comment by Mindustry** [comment]
@Hir0shi 
I'm pretty certain allowing players to speak in guild chat no matter what level is the intention. I'm not sure there is a reason to put a  level requirement on it.

**Comment by poszer** [comment]
> Tested on a Windows 10 64-bit build.
> Took some screenshots for this one to show what the issue was and how @poszer fixed it successfully. Sorry if it's a little image heavy.
> All tested successfully, config was added to .dist file properly, it's a needed feature. Thanks again, poszner.
> 
> Right now it's possible to block anyone under a certain level to chat, whisper, trade, make auctions, make tickets, and even send/receive mail. The one thing they can do is spam party invites and then advertisements to anyone who accidentally or unexpectedly accepts.
> WoWScrnShot_053119_112654
> WoWScrnShot_053119_112704
> 
> #1919 Successfully adds a config option that allows you to block players from inviting under a certain level.
> config
> WoWScrnShot_053119_114331
> 
> It's also successful in allowing friends to invite each other despite level difference.
> WoWScrnShot_053119_114448
> WoWScrnShot_053119_114449

Nice, thank you for testing :+1:

**Comment by Hir0shi** [comment]
@Mindustr

yes, but maybe somebody needs

ChatLevelReq.Guild = ?

**Comment by Mindustry** [comment]
@Hir0shi 
Maybe, but it would be in a different pull request regardless.

**Comment by Hir0shi** [comment]
I know ! But this is a need, on the worldserver.cfg you can use or no !

ChatLevelReq.Guild

**Comment by poszer** [comment]
> I know ! But this is a need, on the worldserver.cfg you can use or no !
> 
> ChatLevelReq.Guild
> 
> OMG.

It's not needed, as the Guild leader you can manage what ranks can speak in /guild chat like @Mindustry explained you. Locking this conversation to prevent spam

**Pull request merged**
