### PR TITLE
fix(Core/Spell): Make use of SPELL_ATTR4_DONT_REMOVE_IN_ARENA

### PR DESCRIPTION
**Pull request by Kitzunu**
Ported from tc

## Changes Proposed:
-  Make use of SPELL_ATTR4_DONT_REMOVE_IN_ARENA
-  Move for loop into functions

<details>
<summary>These spells are affected by the flag</summary>

dbc_spell
---
```sql
SELECT `id`, `name_lang_1`, `attributesEx5`
FROM `dbc_spell` 
WHERE `attributesEx5` & @flag = @flag
```
| id | name_lang_1 | attributesEx5 | 
| ---: | --- | ---: | 
| 498 | Divine Protection | 4 | 
| 642 | Divine Shield | 4 | 
| 1022 | Hand of Protection | 4 | 
| 1490 | Curse of the Elements | 4 | 
| 5599 | Hand of Protection | 4 | 
| 7367 | Infected Bite | 4 | 
| 8733 | Blessing of Blackfathom | 4 | 
| 10278 | Hand of Protection | 4 | 
| 11721 | Curse of the Elements | 4 | 
| 11722 | Curse of the Elements | 4 | 
| 16128 | Infected Bite | 4 | 
| 21848 | Snowman | 4 | 
| 23444 | Transporter Malfunction | 4 | 
| 23456 | Transporter Malfunction | 4 | 
| 23457 | Transporter Malfunction | 4 | 
| 24339 | Infected Bite | 4 | 
| 25771 | Forbearance | 4 | 
| 27228 | Curse of the Elements | 4 | 
| 36893 | Transporter Malfunction | 4 | 
| 36895 | Transporter Malfunction | 4 | 
| 36897 | Transporter Malfunction | 4 | 
| 36899 | Transporter Malfunction | 4 | 
| 42134 | Lesser Rune of Warding | 4 | 
| 42135 | Lesser Rune of Warding | 4 | 
| 42136 | Greater Rune of Warding | 4 | 
| 42137 | Greater Rune of Warding | 4 | 
| 43869 | You're a Zombie! | 1028 | 
| 43958 | You're Infected! | 4 | 
| 47865 | Curse of the Elements | 4 | 
| 48018 | Demonic Circle: Summon | 516 | 
| 53094 | Infected Worgen Bite | 4 | 
| 53174 | Infected Worgen Bite | 4 | 
| 54088 | Corpse Blight | 4 | 
| 54223 | Shadow of Death | 4 | 
| 55711 | Weakened Heart | 4 | 
| 57723 | Exhaustion | 4 | 
| 57724 | Sated | 4 | 
| 59645 | Underbelly Elixir | 4 | 
| 59831 | Underbelly Elixir | 4 | 
| 59843 | Underbelly Elixir | 4 | 
| 66009 | Hand of Protection | 4 | 
| 66010 | Divine Shield | 4 | 
| 66233 | Ardent Defender | 4 | 
| 71550 | Divine Shield | 4 | 

</details>

## Issues Addressed:
- ref #4306

## Tests Performed:

- Builds
- Tested in-game

## How to Test the Changes:

1. Before entering arena:
2. .aura 57723
3. .aura 41912 (SPELL_ATTR4_DONT_REMOVE_IN_ARENA)
4. Enter arena see that both are removed
5. Before arena end:
6. .aura 48672
7. See that it is removed when arena is over

No change in functionality, except correct use of SPELL_ATTR4_DONT_REMOVE_IN_ARENA <3

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Comment by r0m1ntik** [comment]
Done 👍

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Stifler82** [comment]
@Kitzunu 

Pls. can you explain to me with (Exactly) what this fix you did does?
Because I don't see what the correlation is with this issue https://github.com/azerothcore/azerothcore-wotlk/issues/5157

I'm not so familiar with C++, I can understand what that code does (more or less), but not totally..

**Comment by Kitzunu** [comment]
It wont fix that issue, it was a 2 am thought I had.

Dont worry about it

**Pull request merged**
