### PR TITLE
fix(Core): Crashfix.

### PR DESCRIPTION
**Pull request by UltraNix**
## Tests Performed:

- Not tested.

## How to Test the Changes:

Go to AV
Attack main boss with mini bosses stil alive.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
Tested

**Comment by temperrr** [comment]
image
@UltraNix 

```
Battleground::GetBGCreature: creature (type: 445, GUID Full: 0x00c3695c01d4afa7 Type: <unknown> Entry: 6904833  Low: 13938599) not found for BG (map: 30, instance id: 3)!
```

**Comment by UltraNix** [comment]
@temperrr Even without this PR?

**Comment by UltraNix** [comment]
@temperrr Should be okay now.

**Comment by temperrr** [comment]
Yep, spam is gone. 

Checked for crash once more, no crash.

All good as far as I can tell... (again).

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
