### PR TITLE
fix(Core/Raid):Putricide mutated abomination being energized by players

### PR DESCRIPTION
**Pull request by GMKyle**
##### CHANGES PROPOSED:
-  Make a condition (db) for druid spell Revitalize talent (http://wotlk.cavernoftime.com/spell=48539) procs
-  Introduce a validation (core) for disc priest Rapture talent (http://wotlk.cavernoftime.com/spell=47535) 

##### ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2380

##### TESTS PERFORMED:
- Build without errors and tested in-game. (Win10 server)

##### HOW TO TEST THE CHANGES:
 - Read the issue description.

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Pass the test and work as expected
.learn 48539
.learn 47535
.c 48441
.c 48438
.c 17
NORP：To produce energy.
RP：It doesn't produce energy.
image

**Comment by Stoabrogga** [comment]
@pklloveyou 
Could you please explain what NORP / RP means? Without / with PR (Pull Request)?

**Comment by pklloveyou** [comment]
I modified it.

**Comment by Stoabrogga** [comment]
Ok, so when you write RP you actually mean PR, got it :smile: 
Thanks for testing this :+1:

**Comment by OcelotGear** [comment]
This is wrong. The old behavior is blizzlike https://www.wowhead.com/forums&topic=158065.

https://es.lmgtfy.com/?q=abomination+rejuvenation

**Comment by Stoabrogga** [comment]
@OcelotGear 
This PR has already been merged. If you think the behaviour is wrong please create an issue for further discussion, as this is the wrong place for this.

**Pull request merged**
