### PR TITLE
fix(Core/Creatures): Fixed unitialized varibale implemented in 728d018.

### LINKED ISSUE #5030: Lichking resets after dialogue when he can't find player (LoS?)
## CURRENT BEHAVIOUR:
the Lich King resets when the player is not in LoS. 

## EXPECTED BLIZZLIKE BEHAVIOUR:
the Lich King should run to the player and attack him

## STEPS TO REPRODUCE THE PROBLEM:

1. go to lichking (ICC last boss)
2. start dialogue 
3. hide (like in video)

## EXTRA NOTES:
video issue: https://vid.dragonwrath.net/v/J98Sxd
maybe related to:
https://github.com/azerothcore/azerothcore-wotlk/issues/5022
https://github.com/azerothcore/azerothcore-wotlk/issues/5021
https://github.com/azerothcore/azerothcore-wotlk/issues/5014

## AC HASH/COMMIT:
3e29ce2e50e969d7d4ca1cd8a86745e74301f3b7

## OPERATING SYSTEM:
debian 10

## MODULES:
mod-cfbg
mod-transmog
mod-pvp-titles
mod-1v1

## CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97451513-lichking-resets-after-dialogue-when-he-can-t-find-player-los?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #5030

## Changes Proposed:
-  Fixed unitialized variable.
-  

## Issues Addressed:
- Closes #5030

## Tests Performed:

- 
- 

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/5040 not needed.
@disclosurez @Err0r1 test #5030 again.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Err0r1** [comment]
Still same issue

https://i.imgur.com/WFz1I5I.jpg

**Comment by Err0r1** [comment]
Issue fixed
Video: https://vid.dragonwrath.net/v/lHEchV

**Comment by FrancescoBorzi** [comment]
thanks @UltraNix and @Err0r1

**Pull request merged**
