### PR TITLE
fix(DB/Gameobject): Delete unused hack objects

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  ref https://github.com/azerothcore/azerothcore-wotlk/issues/9998

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
image
You need to remove them from the gameobject_addon as well

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
gameobject_template_addon needs adjustments as well

**Comment by Kitzunu** [comment]
Will do

**Review by acidmanifesto — APPROVED** [review]

**Comment by Bogir** [comment]
If those items are present in DBC - you must not delete them!
Just fix they stats or set to 0 and leave them in base for future useю Some of them ALLREADY in use in modules or other customisations and this commit will break the server

**Comment by Kitzunu** [comment]
Hello Bogir!

I appreciate that you are trying to help but in this case you are entirely wrong. These were **custom gameobject used to hackfix stuff left over from the sunwell period**. None of these that I have deleted are used anywhere within the core or database. And are most certainly not blizzlike in any way

As for gobs in modules, that's what they are. Gobs in modules.
I don't touch modules, I touch the core repository which is made to be blizzlike.

Have a great evening :)

**Comment by Bogir** [comment]
once again:
Iа momething is present in Game Client DBC - don't delete it!

And no matter if you know does those things are used by somebody or not. If they are present in dbs - let them stay. 
If you want - you may fix eath item. But not delete them.

**Comment by Kitzunu** [comment]
Item != GameObject

**Comment by acidmanifesto** [comment]
> once again:
> If something is present in Game Client DBC - don't delete it!
> 
> And no matter if you know does those things are used by somebody or not. If they are present in dbs - let them stay. 
> If you want - you may fix each item. But not delete them.
> 

If there is any problem following a pr be sure to open up a issue ticket on the github. If there is a issue with a module that isnt related to a hook be sure to open up a issue with that module's project page. 
Be sure to include what was effected and what quest/area/npc/gameobject was broken from the pr. We hope to hear about it more in detail. Thank you for your concern and may the guiding light of cthulhu reflect on us all.

**Comment by Nyeriah** [comment]
@Bogir Those were **custom** gameobjects, we don't keep **custom** gameobjects in our world database. If they're used by modules then they belong to their module repository. We will **never** keep any custom item/gameobject in our database. There's a difference between **unused** and **custom**, we cannot keep **custom**.

**Pull request merged**
