### PR TITLE
feat(Apps): Add a tool to remove trailing whitespaces

### PR DESCRIPTION
**Pull request by Kitzunu**
Remove trailing whitespace from .cpp & .h files in src/server & src/common directories using this script
```bash
find -name '*.cpp' -print0 | xargs -r0 sed -e 's/[[:blank:]]\+$//' -i
find -name '*.h' -print0 | xargs -r0 sed -e 's/[[:blank:]]\+$//' -i
```

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Where were you before? Very very good script and PR, Very!

**Comment by Kitzunu** [comment]
I googled the script xD

**Comment by Kitzunu** [comment]
I know we have CI to fail if there are trailing any whitespace, but it can be cool to add this tool anyway.

Easy on-hand for anyone that might want to use it in a module or for another project

**Comment by Winfidonarleyan** [comment]
I use my cpp script with POCO lib and PRCE - https://pocoproject.org/docs/Poco.RegularExpression.html
```
(^\\s+$)|( +$)
```

**Pull request merged**
