### PR TITLE
fix(DB/Reputation):Brood of Nozdormu reputation

### PR DESCRIPTION
**Pull request by zxcnxc**
## Changes Proposed:
-  Changes the Brood of Nozdormu reputation gain from killing Anubisath Defender, Anubisath Sentinel, Obsidian Eradicator, Qiraji Lasher, Vekniss Hive Crawler, Vekniss Soldier, Vekniss Stinger, Vekniss Warrior, Vekniss Wasp from 500  to 100 and stop giving rep up to neutral.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7621
- Closes https://github.com/chromiecraft/chromiecraft/issues/1577

## SOURCE:

https://classic.wowhead.com/faction=910/brood-of-nozdormu#npcs

## Tests Performed:

- Ran SQL, 10 Affected rows, 0 error
image

 Check via in-game

1. Kill mob in Friendly Reputation

image

2. Kill mob in Neutral Reputation 

image

3. Kill mob in Unfriendly Reputation

image

4. Kill mob in Hostile Reputation
 
image

5. Kill mob in Hated Reputation

image

Tested on local server / Win 10 64 Bit

## How to Test the Changes:

1. .go c 88015 / Anubisath Defender
2. .modify rep 910 (Brood of Nozdormu) Hostile / Neutral / Friendly
3. Kill mob
4. Check chat general

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — CHANGES_REQUESTED** [review]
Hello, please check this table first: https://www.azerothcore.org/wiki/reputation_reward_rate

If the rates are set to normal values you can go ahead with this changes.

**Comment by zxcnxc** [comment]
> 
> 
> Hello, please check this table first: https://www.azerothcore.org/wiki/reputation_reward_rate
> 
> If the rates are set to normal values you can go ahead with this changes.

I'm sorry but I don't understand, do i need to rework my SQL or i need to add faction on **reputation_reward_table** since faction 910 is not there ? Can you point me ? I'm sorry if i sound rude

image

**Comment by LukasVolgger** [comment]
> > 
> > 
> > Hello, please check this table first: https://www.azerothcore.org/wiki/reputation_reward_rate
> > 
> > If the rates are set to normal values you can go ahead with this changes.
> 
> I'm sorry but I don't understand, do i need to rework my SQL or i need to add faction on **reputation_reward_table** since faction 910 is not there ? Can you point me ? I'm sorry if i sound rude
> 
> image

No worries, you did everything right. I wanted you to check this table first because this was the reason why mobs for other factions gave too much rep. If the faction you mentioned is not there everything is good!

**Review by LukasVolgger — APPROVED** [review]

**Comment by syssneck** [comment]
Tested, they give now 100 rep per kill and stop giving rep after you reach friendly with the Brood of Nozdormu.

**Pull request merged**
