### PR TITLE
fix(DB/quest): Gathering Leather requires skinning

### PR DESCRIPTION
**Pull request by Zoidwaffle**
## Changes Proposed:
-  You need to be a skinner for the quest Gathering Leather
-  https://classic.wowhead.com/quest=768/gathering-leather

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4766
- Closes chromiecraft/chromiecraft#173

## Tests Performed:
- Applied SQL
- Tried to pick up the quest as a skinner and not

## How to Test the Changes:

- `.go c id 3050`
- `.learn 8613` (skinning)
- Talk to Veren Tallstrider

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Zoidwaffle** [comment]
Some mess in the commits there... Please ignore that crap... The end result in the SQL file should be fine and valid.

**Comment by Si1ker** [comment]
### Verified
image
source: https://classic.wowhead.com/quest=768/gathering-leather

### SQL query tested
```sql
UPDATE `quest_template_addon` SET `RequiredSkillID`=393, `RequiredSkillPoints`=1 WHERE `ID`=768;
/* Affected rows: 1  Found rows: 0  Warnings: 0  Duration for 1 query: 0.000 sec. */
```

### Tested

**Without skinning**
image


**After learning skinning**
image

**Review by Si1ker — APPROVED** [review]

**Comment by Zoidwaffle** [comment]
Fancy testing with screenshots :heart:

**Comment by Si1ker** [comment]
> Fancy testing with screenshots ❤️

As every single testing should be. #QualityControl 🐱

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
