### PR TITLE
fix(Core/Maps): Fixed displaying instance warning when entering binde…

### PR DESCRIPTION
**Pull request by UltraNix**
…d dungeon.

## Changes Proposed:
-  Fixed displaying instance warning when entering binded dungeon.

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Enter the raid and kill one boss
2. Invite to your group another person
3. The second guy enters the dungeon and should see warning about pending instance id.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers please check this

**Comment by pklloveyou** [comment]
image
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pklloveyou** [comment]
Wait a minute, there seems to be an error here. I found that no binding window pops up during the test https://github.com/azerothcore/azerothcore-wotlk/pull/7452 process

**Comment by UltraNix** [comment]
Because it's different PR?

**Comment by pklloveyou** [comment]
I merged together

**Comment by UltraNix** [comment]
No idea.

**Comment by pklloveyou** [comment]
I'll try 7425 first

**Comment by pklloveyou** [comment]
```c++
if (!playerBind->perm && !mapSave->CanReset() && group && !group->isLFGGroup() && !group->IsLfgRandomInstance())
```
Should this be done?

**Comment by FrancescoBorzi** [comment]
@pklloveyou so, is this buggy for you? have you tested this PR without other changes?

**Comment by UltraNix** [comment]
@pklloveyou You just restored the old, now working code.

**Comment by pklloveyou** [comment]
I just tried again after merging. The instance binding window is not displayed

**Comment by UltraNix** [comment]
Just tested and everythings works like a charm. Remove all other PRs, recompile it and follow the steps.

**Pull request merged**
