### PR TITLE
fix(db): 4 NPCS in sw shadowglen with "wait" movetype location fixed

### PR DESCRIPTION
**Pull request by neifion-00000000**
2 Grell and 2 Grellkin were incorrectly placed.

Uploaded sniff that was taken while working/exploring to submissions.

## Changes Proposed:
-  Place mobs in the correct location-  

## SOURCE:
Packets for area 04 have been submitted prior to this PR
image

## Tests Performed:
- Mobs checked against source.
- SQL tested 

## How to Test the Changes:

1.  .go c 47286 (47284 is nearby)
     .go c 47334 (47344 is nearby)
2.  Compare to classic servers  (read below if they do not match exactly)

## Known Issues and TODO List:
Some interesting behavior was discovered, a "scare" mechanic.  It can make the mobs move to new locations as they run away from any active combat.  Both Grell and Grellkin have this mechanic.  If you go to check these mobs against classic and do not see them in the correct location, be sure to clear the camp (or at least kill the ones with the behavior we emulate as "stay" movement), its likely they had the scare mechanic go off and were never killed afterward.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Dont replace into.
Use delete + insert

**Comment by neifion-00000000** [comment]
> I agree. We need to do a delete and then insert or a update. With replace we may end up with undesire outcomes.

fixed it up :)

**Comment by Kitzunu** [comment]
You can make these into one query.

Check https://www.azerothcore.org/wiki/sql-standards to learn more about SQL stuff

**Comment by neifion-00000000** [comment]
I am including this in a different upcoming PR as part of a larger spawn point revision

**Pull request closed without merging**
