### PR TITLE
fix(Scripts/AQ20): Ossirian movement speed

### PR DESCRIPTION
**Pull request by SoglaHash**
On pull Ossirian movies too slow and is kiteable. He should speed up and
become no longer kitable.

## Changes Proposed:
Add event that repeats 10 times to speed up Ossirian from 1.0f to 2.0f in steps of 0.1f

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3912

## How to Test the Changes:

1. Go to Ossirian
```
.go c 144601
```
2. Set Speed
```
.mod speed 1.3
.mod speed 1.08
```
3. Ranged pull and attempt to kite

In both cases he should catch up to the player

## Known Issues and TODO List:

- Ossirian aggro range is too small. He does not body pull accurately

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I took a look in retail. The movement speed increase is still there but it isn't detected by a sniffer.

The change in speed is also instant and happens only once.
Vmangos has it scripted in their core: https://github.com/vmangos/core/blob/development/src/scripts/kalimdor/silithus/ruins_of_ahnqiraj/boss_ossirian.cpp

**Comment by Maelthyrr** [comment]
Tested and work fine.

**Comment by Gultask** [comment]
@SoglaHash 
Actually. I found it now. I was looking for an aura before but it's a SMSG_MOVE_SPLINE_SET_RUN_SPEED
It happens exactly 10s after the encounter starts
The movement speed increase is exactly x2.2 times the original speed. From 6 in the sniff to 13.2

**Comment by Gultask** [comment]
Works fine. Resetting the encounter also resets the boss' speed.

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
