### PR TITLE
Core: Crashfix.

### LINKED ISSUE #8099: server crash 20210926
### Current Behaviour

logs
https://gist.github.com/mpfans/cb54cecdae5aae6aefd2952a6fe707b6

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

792b99cbc9a6eac43c564993e80e02ac8333cc9f

### Operating system

ubuntu 20.04

### Custom changes or Modules

none

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #8099

## Issues Addressed:

- Closes #8099

## Tests Performed:

- Tested ingame, but even without that fix crash did not happen

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans @bgcfb @SKingOWN Please, test it.

**Comment by SKingOWN** [comment]
I am building the PR in Ubuntu 20.04 right now. I will send the results soon.

**Review by Helias — APPROVED** [review]

**Comment by SKingOWN** [comment]
Connection peak: 932.
Server uptime: 7 hour(s) 6 minute(s) 35 second(s).
Update time diff: 10ms, average: 15ms.

Seven hours uptime and no crash with more than 900 users online.

**Comment by mpfans** [comment]
Already testing. Please wait for feedback

**Comment by bgcfb** [comment]
I am already testing this pr and some problem seems relate to this pr.
#8167

**Comment by UltraNix** [comment]
It's not related to it.

**Comment by bgcfb** [comment]
24 hours uptime and no crash with more than 300 users online.

**Comment by UltraNix** [comment]
@mpfans How's it going?

**Comment by SKingOWN** [comment]
In my case it crashes again 11 hours ago but may be by other problem.

Connected players: 496. Characters in world: 486.
Connection peak: 862.
Server uptime: 11 hour(s) 32 minute(s) 16 second(s).
Update time diff: 10ms, average: 12ms.

**Comment by SKingOWN** [comment]
I look around the code an is full of ASSERT(). I believe that is better to replace that by LOG_ERROR and not dump the server.

**Comment by UltraNix** [comment]
@SKingOWN Just post a crashlog.

**Comment by SKingOWN** [comment]
> @SKingOWN Just post a crashlog.

@UltraNix I am testing in my production server and I build in Release mode because if I build in Debug mode the uptime diff is to hight (about 500ms or more) (To many users online to build in debug mode).

In release mode the core don't save crash logs (I am not sure).

**Comment by bgcfb** [comment]
> > @SKingOWN Just post a crashlog.
> 
> @UltraNix I am testing in my production server and I build in Release mode because if I build in Debug mode the uptime diff is to hight (about 500ms or more) (To many users online to build in debug mode).
> 
> In release mode the core don't save crash logs (I am not sure).


I am using RelWithDebInfo mode for 300 users@10ms diff , crash log saved but this crash

**Comment by SKingOWN** [comment]
> > > @SKingOWN Just post a crashlog.
> > 
> > 
> > @UltraNix I am testing in my production server and I build in Release mode because if I build in Debug mode the uptime diff is to hight (about 500ms or more) (To many users online to build in debug mode).
> > In release mode the core don't save crash logs (I am not sure).
> 
> I am using RelWithDebInfo mode for 300 users@10ms diff , crash log saved but this crash

In my server I have more than 1000 users online every day, I try few months ago to build in debug and was imposible to play.

**Comment by SKingOWN** [comment]
Connected players: 1203. Characters in world: 1193.
Connection peak: 1245.
Server uptime: 22 hour(s) 59 minute(s) 32 second(s).
Update time diff: 72ms, average: 36ms.

**Comment by UltraNix** [comment]
@SKingOWN Build in RelWithDebInfo.

**Comment by mpfans** [comment]
running 278281sec no crash..

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
@mpfans status? Is this ready to be merged?

**Comment by SKingOWN** [comment]
I tested for few days and no problems.

**Comment by Nefertumm** [comment]
I need someone to fix Eluna's build, without that I can't merge anything.

**Comment by SanLorenzo59** [comment]
I had reported this crash to @UltraNix this morning on Discord. I have applied this fix to my local server, this crash has not happened any more.

**Comment by mpfans** [comment]
Since accepting this PR on September 30, it has not crashed again. I think it can be merged!

**Review by bgcfb — APPROVED** [review]

**Comment by Nefertumm** [comment]
Yes, I'm waiting the checks so it can be merged :)

**Comment by mpfans** [comment]
> Yes, I'm waiting the checks so it can be merged :)

I've been on vacation until October 8

**Comment by Nefertumm** [comment]
Ty all for testing <3

**Pull request merged**
