### PR TITLE
fix(DB/Quest): Fixed quest Bitter Rivals

### PR DESCRIPTION
**Pull request by Asthalor**
## Changes Proposed:
-  Used some code from https://github.com/TrinityCore/TrinityCore/issues/17267
-  Using the base commit i fixed the barrels not spawning after picking quest and the orientation of the dude after doing the route

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6984

## SOURCE:

https://www.youtube.com/watch?v=uN-Va90gL70

## Tests Performed:

- .go c 1373 and pick the quest
- .add 2686 10 for the beer needed to distract the guy
- Start the distraction and see when the guarded barrel turns into unguarded
- Without turning the quest check the route and text of the guy
- After that check the unguarded barrel transforms into the guarded one
- After doing the route you could distract him again, this time do the quest and check that after doing all of that the distraction quest dissapears.

Video

https://streamable.com/5rmwp3

## How to Test the Changes:

1. .go c 1373 and pick the quest
2. .add 2686 10 for the beer needed to distract the guy
3. Start the distraction and see when the guarded barrel turns into unguarded
4. Without turning the quest check the route and text of the guy
5. After that check the unguarded barrel transforms into the guarded one
6. After doing the route you could distract him again, this time do the quest and check that after doing all of that the distraction quest dissapears.

## Known Issues and TODO List:

- Just some minor things. I could not make the quest Guarded barrel to pop the quest distracting the guy, so when the qquest bitter rivals is picked both quests pop up.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Asthalor** [comment]
Finally done. This quest seemed to be very easy to fix, but in the end i had a lot of trouble with the spawning and despawning of the barrels.
Using the target GAMEOBJECT_RANGE fixed the problems, but that took more time that i am willing to admit.

I hope its all good after the testing!

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by banehammer** [comment]
Okay this commit is like 97% done. It still needs a bit minor stuff. Will do!

**Comment by banehammer** [comment]
Quest is bugged again.
Now it is complete chaos than before
Capture

**Comment by Kitzunu** [comment]
Open an issue

**Pull request merged**
