### PR TITLE
fix(Core/Dungeon): Elder Nadox hardcore texts + Ahn'kahar Spell Flinger spells.

### PR DESCRIPTION
**Pull request by GMKyle**
##### CHANGES PROPOSED:

- Replace Elder Nadox hardcore texts
-  Fix Ahn'kahar Spell Flinger (30278) spells (shadow-blast,shadow-sickle)

Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/2219

##### TESTS PERFORMED:
- Build without errors and tested in-game. (Win10 server)

##### HOW TO TEST THE CHANGES:
- Enter in Ahn'kahet: The Old Kingdom
- Engage some Ahn'kahar Spell Flinger
- Engage Elder Nadox. Alternatively change client language 

##### Target branch(es):

Master

 
 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
SPELLL 56698 and 56702 Failure，Boss talk NICE

**Comment by GMKyle** [comment]
@pklloveyou thx for testing but could you be more specific
spell 56698: Should do damage equal to 50% of the target's maximum health.
https://wotlk.cavernoftime.com/spell=56698
spell 56702:  When i test instance in normal this spell miss a lot due to lvl diference
NPC 30283:I don't modify nothing about this dude however it's has SmartIA in db (i don't checked)

**Comment by pklloveyou** [comment]
@GMKyle 56702 No display Attack damage

**Comment by pklloveyou** [comment]
```sql
INSERT INTO`smart_scripts`(`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(30283,0,0,0,0,0,100,2,0,0,0,0,0,11,56709,1,0,0,0,0,1,0,0,0,0,0,0,0,0,'PlagueWalker-Combat-Cast\'AuraofLostHope\'(Phase1)(NoRepeat)(Dungeon)'),
(30283,0,1,0,0,0,100,4,0,0,0,0,0,11,61459,1,0,0,0,0,1,0,0,0,0,0,0,0,0,'PlagueWalker-OnRespawn-Cast\'AuraofLostHope\'(Phase1)(NoRepeat)(Dungeon)'),
(30283,0,2,0,0,0,100,6,???,???,???,???,0,11,56698,0,0,0,0,0,2,0,0,0,0,0,0,0,0,'');
(30283,0,2,0,0,0,100,6,???,???,???,???,0,11,56702,0,0,0,0,0,2,0,0,0,0,0,0,0,0,'');
(30283,0,2,0,0,0,100,6,7000,11000,120000,130000,0,11,56707,0,0,0,0,0,2,0,0,0,0,0,0,0,0,'PlagueWalker-InCombat-Cast\'ContagionofRot\'(Phase1)(NoRepeat)(Dungeon)');
```
It is a template

**Comment by pklloveyou** [comment]
Work as expected should be merged

**Comment by Stoabrogga** [comment]
Is there still something missing or wrong concerning creature 30283 (Plague Walker)? There's also a Travis error which has to be fixed.

**Comment by pklloveyou** [comment]
Without this PR, the creature is wrong to release this spell, and the spell will not harm the player.Use this PR to generate damage value after spell

**Pull request merged**
