### PR TITLE
fix(DB/World):improved Classic Rares II

### PR DESCRIPTION
**Pull request by Knindzagxg**
Missing Classic rares now fully updated.

With this PR, every "Classic / Vanilla" zone have been checked in last 6 months and fixed.
In next few weeks i will start checking and working on TBC and WOTLK content.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele to zone and run / test around.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
build fails

**Comment by Knindzagxg** [comment]
why its failing oO ?

**Comment by FrancescoBorzi** [comment]
@Knindzagxg to see why it's failing, you can just check the build log. Click on "Details" of a failing build, it will open the CI window:

image

So you'll see the errors:

```
2020-10-25 18:52:05 SmartAIMgr: EntryOrGuid 1844 using event(1) has an invalid action type (0), skipped.
2020-10-25 18:52:05 SmartAIMgr: EntryOrGuid 10359 using event(0) has an invalid action type (0), skipped.
```

**Comment by BarbzYHOOL** [comment]
give better names to commits plz so we can more easily test and navigate the work

here it should be `fix(DB/Creature): Added SAI for vanilla rare mobs` (creature or NPC) because you added the SAI for these mobs right? before that they had none

**Comment by aradep** [comment]
Tested, all working except...
The Husk(1851) has a weird spell https://wotlkdb.com/?spell=17320
Scarlet Executioner(1841) Execute range needs to be lowered to 20% to match spell. If he tries to execute at 30% it doesn't work.
Scarlet Interrogator(1838) No mana to cast Immolate.
Fellicent's Shade(10358) has "0%-0%" range for one entry.
🦖

**Comment by FrancescoBorzi** [comment]
@Knindzagxg

**Comment by Knindzagxg** [comment]
Updated @aradep 
Can u check those again mate.

**Comment by aradep** [comment]
Scarlet Executioner still not casting Execute (I think because he tries at 21%) Lowering chance to 19% made it work for me. Everything else is good. 👍

**Comment by Knindzagxg** [comment]
Updated, check now xP

**Comment by aradep** [comment]
Working good now

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
