### PR TITLE
fix(DB/creature_template_locale): Spanish totem translation

### LINKED ISSUE #11371: [creature_template_locale] Missing Spanish totem translation
Originally reported by **Silkarx** at https://github.com/chromiecraft/chromiecraft/issues/3333

### Current Behaviour

Missing translation for Totem of Wrath on esES/esMX

image

### Expected Blizzlike Behaviour

[Tótem de cólera II] for Totem of Wrath II
[Tótem de cólera III] for Totem of Wrath III

### Source

esES/esMX language pack

### Steps to reproduce the problem

Use esES/esMX WoW client
Create Shaman
Summon Totem of Wrath ll and Totem of Wrathlll, those will be displayed as...
"ZzOLDTotem of Wrath ll" and "ZzOLDTotem of Wrath lll"

### Extra Notes

image

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/48fccc851d8491c9019a585c74417641376795de

### Operating system

Ubuntu 20.04

### Custom changes or Modules

HD texture pack (char only)

### PR DESCRIPTION
**Pull request by Si1ker**
## Changes Proposed:
-  Add esES translation
-  Add esMX translation

## Issues Addressed:

- Closes #11371
- Closes https://github.com/chromiecraft/chromiecraft/issues/3333

## SOURCE:

esES/esMX language pack

## Tests Performed:

- Tested

## How to Test the Changes:

- Apply changes, run server, Use esES/esMX WoW client, create Shaman
- Summon Totem of Wrath ll and Totem of Wrathlll, those will be displayed as they should

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by Tony931023** [comment]
This PR, it cannot be merged now, until what I mentioned above is fixed

**Comment by Kitzunu** [comment]
You have not mentioned anything?

**Comment by Kitzunu** [comment]
It's pending meaning you never hit review button lol so nobody can see it

**Review by Tony931023 — CHANGES_REQUESTED** [review]

**Comment by Si1ker** [comment]
@Lynethris add the label back again.

**Pull request merged**
