### PR TITLE
fix(Core): Crashfix.

### LINKED ISSUE #11650: [server]world crash 0506
### Current Behaviour

crash log :

https://gist.github.com/mpfans/645d2cbee73913e46f132c12e2b4bf72

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/283ce18bb7b961264eae983a401aaacb89725273 + PR https://github.com/azerothcore/azerothcore-wotlk/pull/11616

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11650

## Issues Addressed:

- Closes #11650

## Tests Performed:

- Not tested.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@mpfans Please, test it.

**Comment by mpfans** [comment]
crash again:
https://gist.github.com/mpfans/5a67e81ea756484210cfdabdf0645ec4

**Comment by mpfans** [comment]
Player feedback: after entering the black hole, there is only 1 HP, and then the server crashes

**Comment by SKingOWN** [comment]
How can I build and configure on linux to get crashlogs without high latency. I've tried RelWithDebInfo but it doesn't save crashlogs or I can't find them.

**Comment by SKingOWN** [comment]
I think the problem could be related to this... Player.cpp:1027
`
void Player::setDeathState(DeathState s, bool /*despawn = false*/)
{
// (......)
//FIXME: is pet dismissed at dying or releasing spirit? if second, add setDeathState(DEAD) to HandleRepopRequestOpcode and define pet unsummon here with (s == DEAD)
        RemovePet(nullptr, PET_SAVE_NOT_IN_SLOT, true);
// (.......)
`

**Comment by SKingOWN** [comment]
I check some files related to the crash and found this closed issue https://github.com/azerothcore/azerothcore-wotlk/issues/11331 by this PR https://github.com/azerothcore/azerothcore-wotlk/pull/11464 ...

Analyzing the PR in detail, I think that it doesn't make much sense since it only adds an 'else' to an 'if' that always returns. So this problem is much older.

**Comment by UltraNix** [comment]
I can't reproduce it as well.

**Comment by UltraNix** [comment]
@mpfans Please, test it again.

**Comment by UltraNix** [comment]
@mpfans

**Comment by acidmanifesto** [comment]
i'm currently re-runing the single failed as it's reason for failure is not related to this pr.

**Comment by mpfans** [comment]
@UltraNix Under test, I want to test for 2 weeks

**Comment by UltraNix** [comment]
@mpfans Okay.

**Comment by mpfans** [comment]
tested,work!tyvm

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
