### PR TITLE
fix(DB): Missing Deadmines Pathing and Linking

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Adds several missing pathing and mob linking to Deadmines mobs
-  Values imported from Vmangos

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Vmangos

## Tests Performed:

- Checked in game, looks correct

## How to Test the Changes:

1. .go creature to affected GUIDs, confirm pathing
2. Confirm linked mobs now pull together

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ZhengPeiRu21** [comment]
Sorry, please wait to merge this one. I think there may be one duplicated patrol.

**Comment by Nefertumm** [comment]
Status?

**Comment by acidmanifesto** [comment]
Status?

**Comment by Maelthyrr** [comment]
I will mark it as abandoned. Feel free to reopen this PR if you get more time.

**Pull request closed without merging**
