### PR TITLE
DB: Minor Fixes

### PR DESCRIPTION
**Pull request by STARRHELD**
**Changes proposed:**

-  Added missing event for creature **R-3D0**
-  Added missing out of combat text for creature **Hargin Mundar**
-  Added missing event after handing in the quest **The Prodigal Lich Returns** in **Undercity**
- Added missing event for **Dame Auriferous**, **High Executor Mavren**, **Advisor Valwyn** and **Deathstalker Maltendis**
- Added missing NPC(S) in **Caer Darrow**
- Players name will appear instead of "MAC" on the quest **Grimtotem Spying**
- Fixed spell range of Flush Pipe knockback in (**Dalaran Sewers**) / **Dalaran Arena**
- **Stonescythe Whelps** should be hostile to both Horde and Alliance
- Currently the quest **Challange Overlord Mok'Morokk** is not working properly, due to missing smart script
- The creature **Verifonix <The Surveyor>** had the wrong faction and gave no reputation with **Booty Bay**
- Added missing text and smart script for creature **Doctor Razorgrin**

**Target branch(es):** Master

**Issues addressed:** Closes #

**Tests performed:** Tested everything, but feedback is appreciated like always

### CODE REVIEW

**Comment by talamortis** [comment]
Will test tomorrow 🖒

**Comment by sucofog** [comment]
Done tests, all fixes are good and right to merge.

**Comment by ShinDarth** [comment]
@TW1NKLET @sucofog @talamortis is still there a reason for not merging this one?

**Comment by Kizarr** [comment]
@ShinDarth I think there inactive for the last two months. Feel free to merge for them.

> Done tests, all fixes are good and right to merge.

**Comment by ShinDarth** [comment]
@Kizarr can you test this please?

**Comment by talamortis** [comment]
Tested, all works but gain an error on some creatures

**Comment by ShinDarth** [comment]
what errors?

**Comment by StygianTheBest** [comment]
>Tested, all works but gain an error on some creatures
>what errors?

Bump?

**Comment by ShinDarth** [comment]
@StygianTheBest have you tested this? please leave your feedback

**Comment by Yehonal** [comment]
PR imported on staging-branch, ready to be tested on public demo server

**Comment by Yehonal** [comment]
@STARRHELD could you check those errors please?

**Comment by Jagermaister95** [comment]
I've tried all the fixes made in the report and work perfectly

**Pull request merged**
