### PR TITLE
fix(Scripts/BlackTemple): fatal attraction - incorrect tick logic

### PR DESCRIPTION
**Pull request by Grimdhex**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes a part of: https://github.com/azerothcore/azerothcore-wotlk/issues/19940#issue-2520007860 and https://github.com/chromiecraft/chromiecraft/issues/7348#issue-2513144012

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Engage Mother Shahraz with more than 4 people.
2. Wait for Fatal Attraction to be cast on 3 of them.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Nyeriah** [comment]
This is wrong, the first two ticks should deal less damage, but with this the first two ticks will deal 3k damage and every other will multiply by the number of ticks afterwards

**Comment by TheSCREWEDSoftware** [comment]
I didn't knew how to proper test this.

I had 5 accounts and all in .cheat god and with tier 6 raid gear. Does the Absorbed Damage tell you if it's properly ticked?

image

image

**Review by Nyeriah — CHANGES_REQUESTED** [review]
block merge

**Comment by Grimdhex** [comment]
I close this PR. For the moment, I've no idea how fix this, but I can confirm with debug that the spell cast can be call few times on the same tick. I wasn't able to find the source, but probably not related to the script.

**Pull request closed without merging**
