### PR TITLE
Bloodlord Mandokir Fix

### LINKED ISSUE #195: [boss] zul gurub
Description: After a wipe, Bloodlord Mandokir (ID:11382) is supposed to position himself where the Vilebranch Speaker (ID:11391) was prior to killing him to trigger the encounter. The boss has to reset and place himself below the stairs.
Also, a minor bug with him yelling "I'm keeping my eye on you, player!" when casting Threatening Gaze (ID:24314) but he is supposed to yell "player! I'm watching you!".

Current behaviour: When a wipe occur, Bloodlord Mandokir starts to run away from his platform and goes outside his "room" and starts running around the next zone only to come back again to despawn.
He is also yelling the wrong thing when casting Threatening Gaze.

Expected behaviour: Upon a wipe he should reset the encounter and run to the bottom of the stairs. Meaning he should reset his health back to full and respawn his mount, Ohgan (ID:14988), which he then mounts and the fight can start again when attacked.

Steps to reproduce the problem:

Kill the Vilebranch Speaker at the bottom of the stairs.
Attack Bloodlord Mandokir.
Die.
Wait to see him run around and eventually despawn or release and run back inside and he has despawned.
##

### PR DESCRIPTION
**Pull request by talamortis**
**Changes proposed:**
Bloodlord Mandokir will now have correct text when casting gaze

**Target branch(es):** Master

**Issues addressed:** Closes #195

**Tests performed:** (Does it build, tested in-game, etc)
Tested and working
**Known issues and TODO list:**
- [Fix .cpp file for boss as he does a lap around the area] 

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by ShinDarth** [comment]
@talamortis are you sure that this closes the #195 ? I see only the text modification

**Comment by talamortis** [comment]
@ShinDarth No it doesnt close the issue, but i will be fushing the other fixes to this branch for the issue

**Comment by ShinDarth** [comment]
ok that is fine, but please edit:

> Issues addressed: Closes #195 

in something like:

> Issues addressed: Improves #195 

just to be clear that this fix does not completely solve the issue

**Comment by talamortis** [comment]
no it does not its 1 fix out of 2

**Comment by ShinDarth** [comment]
@talamortis  yes that is what I meant :D

**Comment by talamortis** [comment]
Will test this PR tomorrow since i have new HDD, and had to start fresh :)

**Comment by ShinDarth** [comment]
@talamortis any news about this?

**Comment by talamortis** [comment]
tested and working but would like someone else to test to be 100% sure

**Pull request merged**
