### PR TITLE
fix(DB): Creature random movement without distance

### PR DESCRIPTION
**Pull request by Eronox**
## Changes Proposed:
-  Set wanderer distance to 2 for "Patches"

patches has only random movement set by smart scripts but was missing wanderer distance, worldserver had a log in error level warning us about this behavior 

## Issues Addressed:

N/A

fixes worldserver error

## SOURCE:

N/A 
## Tests Performed:

- start worldserver
-  visit npc
- query applies

## How to Test the Changes:

1. start worldserver

## Known Issues and TODO List:

N/A

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Eronox** [comment]
regression caused by https://github.com/azerothcore/azerothcore-wotlk/pull/9925

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Eronox Currently Failure here:
image

**Comment by Eronox** [comment]
> @Eronox Currently Failure here Please adjust movement type for the guid: image

Yes, that's why this PR is labeled as WIP as my original fix was wrong.

**Comment by Kitzunu** [comment]
status?

**Pull request closed without merging**
