### PR TITLE
(Scripts/AI) AQ20: Modernize Kurinnaxx

### PR DESCRIPTION
**Pull request by kjack9**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [X] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

Updates AQ20/Kurinnaxx to modern standards.

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

All abilities appear to fire normally. Ossirian yells on boss death. Andorov spawns on boss death.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## Known Issues and TODO List:

None.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Hey thanks for the PR. Just one thing: comments are redundant when its pretty obvious stuff like this

**Comment by kjack9** [comment]
> Hey thanks for the PR. Just one thing: comments are redundant when its pretty obvious stuff like this

I appreciate that you guys that have been working on this code for years know exactly what I'm doing based on the code alone, but man that's hard on newcomers. I'm removing all my comments on this PR as you requested, but I would implore you to consider allowing SOME documentation on this codebase so that it's not such a guess-and-hope process to learn how to use it. I sure would have appreciated someone leaving breadcrumbs for me in the last month or so I've been learning.

My 2c.

**Comment by kjack9** [comment]
> Hey thanks for the PR. Just one thing: comments are redundant when its pretty obvious stuff like this

> Hey thanks for the PR. Just one thing: comments are redundant when its pretty obvious stuff like this

I appreciate that you guys that have been working on this code for years know exactly what I'm doing based on the code alone, but man that's hard on newcomers. I'm removing all my comments on this PR as you requested, but I would implore you to consider allowing SOME documentation on this codebase so that it's not such a guess-and-hope process to learn how to use it. I sure would have appreciated someone leaving breadcrumbs for me in the last month or so I've been learning.

My 2c.

**Comment by Nyeriah** [comment]
Documentation on complex things is fine, but I don't see how this f.e helps

image

It's quite clear that abilities are being scheduled, the name of the function called is scheduler, spells are being cast inside the function etc. so it~s pretty redudant.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
