### PR TITLE
fix(DB/Creature): Force the correct modelid on spawn of Enchanted Tiki Warriors

### PR DESCRIPTION
**Pull request by Asthalor**
## Changes Proposed:
-  Added the script on SAI to morph the creatures to the model id 25749.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12094

## SOURCE:

https://wowwiki-archive.fandom.com/wiki/Enchanted_Tiki_Warrior
Youtube videos

## Tests Performed:

- .go c id 28882
- Check no infernals are around

## How to Test the Changes:

1. .go c id 28882
2. Check no infernals are around

Tests

tiki1

tiki2

tiki3

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Ovahlord** [comment]
changing template models is a hack. you can override the modelID for each spawn in the creature table. Do that instead.

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/10071

**Comment by Ovahlord** [comment]
well that was a dumb move. because if you did not implement the model selection systems from trinity's master branch with its probability settings, you effectively broke all creatures which use a secondary modelId for invisibility without being a trigger npc. so there are two solutions here:  stick with trinity's 335 system and bring the column back or port trinity's master branch model selection system. Either of these two handlings is better than further ruining the sniffed template data of creatures.

**Comment by acidmanifesto** [comment]
> well that was a dumb move. because if you did not implement the model selection systems from trinity's master branch with its probability settings, you effectively broke all creatures which use a secondary modelId for invisibility without being a trigger npc. so there are two solutions here: stick with trinity's 335 system and bring the column back or port trinity's master branch model selection system. Either of these two handlings is better than further ruining the sniffed template data of creatures.

If i recall. it was a pt 1 of 3 prs. There was a issue with Gender not being swapped out at all on respawn, only random gender selected on startup originally. However the secondary modelId for invisibility has been working fine. In this case we would just need to see what is stroking out for this particular issue with azerothcore. We will take your view into consideration.

**Comment by Gultask** [comment]
@Asthalor You can add a line in their SAI to morph them into the correct modelid on spawn/respawn.

**Comment by Asthalor** [comment]
I will try to do some tests to see if the Not repeat flag is needed or not. I updated the visual studio and im trying to get it fixed today.

**Comment by Asthalor** [comment]
This issue is ready for testing @Gultask. The WIP can be removed :)

**Comment by Sneften** [comment]
Tested ✔️ 
No infernals around!

**Review by Gultask — APPROVED** [review]

**Comment by Gultask** [comment]
Thanks for the PR!

**Pull request merged**
