### PR TITLE
refactor(Core): apply clang-tidy modernize-loop-convert

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-loop-convert`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-loop-convert.html

### How to test the changes

This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:

- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game and play around a bit
- All good so far? Then this should be good to go

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-use-nullptr`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html

### How to test the changes

This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:

- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game and play around a bit
- All good so far? Then this should be good to go

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by JamesGent** [comment]
james@Grasswalker MINGW64 /c/azerothcore-wotlk (pr-3822)
$ git pull origin pull/3822/head
From https://github.com/azerothcore/azerothcore-wotlk
 * branch              refs/pull/3822/head -> FETCH_HEAD
error: Your local changes to the following files would be overwritten by merge:
  src/common/Collision/BoundingIntervalHierarchy.h src/common/Collision/Management/IVMapManager.h src/common/Collision/Management/VMapManager2.h src/common/Collision/Maps/MapTree.h src/common/Collision/Maps/TileAssembler.h src/common/Collision/Models/GameObjectModel.h src/common/Collision/Models/ModelInstance.h src/common/Collision/Models/WorldModel.h src/common/Database/Transaction.h src/common/Dynamic/LinkedList.h src/common/Packets/ByteBuffer.h src/common/Packets/WorldPacket.h src/common/Threading/LockedQueue.h src/common/Utilities/Timer.h src/common/Utilities/Util.h src/server/game/Achievements/AchievementMgr.h src/server/game/Battlegrounds/Battleground.h src/server/game/Combat/ThreatManager.h src/server/game/Entities/Creature/Creature.h src/server/game/Entities/GameObject/GameObject.h src/server/game/Entities/Object/Object.h src/server/game/Entities/Object/Updates/UpdateMask.h src/server/game/Entities/Player/Player.h src/server/game/Entities/Unit/Unit.h src/server/game/Events/GameEventMgr.h src/server/game/Globals/ObjectMgr.h src/server/game/Groups/GroupReference.h src/server/game/Instances/InstanceSaveMgr.h src/server/game/Loot/LootMgr.h src/server/game/Maps/Map.h src/server/game/Miscellaneous/SharedDefines.h src/server/game/Movement/Spline/MoveSpline.h src/server/game/Movement/Spline/MoveSplineInitArgs.h src/server/game/Movement/Spline/Spline.h src/server/game/Quests/QuestDef.h src/server/game/Server/WorldSession.h src/server/game/Spells/SpellMgr.h src/server/shared/DataStores/DBCStorageIterator.h src/server/shared/DataStores/DBCStructure.h src/server/shared/Network/RealmSocket.cpp src/server/shared/Network/RealmSocket.h src/server/shared/Realms/RealmList.cpp src/server/shared/Realms/RealmList.h src/tools/mmaps_generator/IntermediateValues.h src/tools/mmaps_generator/MapBuilder.cpp src/tools/mmaps_generator/MapBuilder.h src/tools/vmap4_extractor/model.h

**Comment by FrancescoBorzi** [comment]
@JamesGent the problem here (and maybe in the other PR too) is that you have to start from a **clean** state before checking out a specific PR. Which means:

- being on `master` branch (`git checkout master`)
- having no pending changes (you can remove all by doing `git reset --hard`)

then follow again the instructions to checkout the PR's code and rebuild

**Comment by JamesGent** [comment]
Success after clean compile.

Desktop 05-12-2020 18-50-34-591

ac-worldserver_1  | AzerothCore rev. 18a4ecfe7225+ 2020-12-05 18:39:24 +0000 (pr-3822test branch) (Unix, Release) (worldserver-daemon)

**Comment by LukasVolgger** [comment]
Thx @JamesGent for testing!

**Review by Helias — APPROVED** [review]

**Pull request merged**
