### PR TITLE
feat(Core/Creatures): Extended mob leash mechanic to assisting in com…

### LINKED ISSUE #4660: Very important missing mob leash behavior [$20]
##### CURRENT BEHAVIOUR:
You can aggro multiple creatures with a ranged attack or spell and they will reset separatly if you don't hit them.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
In official Classic, creatures pulled at the same time will stay linked and won't reset separately. This is a big difference for the leveling and general world, it makes clearing groups of creatures a lot harder and makes mistakes less forgiving
This only happens with the "call for help" mechanic, when you aggro ONE mob and he calls for helps around him.
If you face pull multiple mobs, the mechanic will not trigger, because they haven't aggroed from the call for help "aoe aggro", they aggroed from the facepull.

This the the detailed description of the issue for the vanilla Vmangos core and the fix
vmangos/core#793
Commits : 
1. https://github.com/vmangos/core/commit/7d2f1e2923734ea1b983eeaa0208cfd158d4af02
2. https://github.com/vmangos/core/commit/c8510cbbd4dccbdac9900cc507910ef3ae0e6c43
3. https://github.com/vmangos/core/commit/3666b1d85bfdd6de8dec23726119485dde566d04 (?)
4. https://github.com/vmangos/core/commit/183203611d796a4958bbd64a394728f325257cbd (I think this one is a bug fix from moving to that system)

##### EXTRA NOTES:
I'm not 100% sure if this mechanic was still in Wrath, but I don't see a reason it wouldn't be. Some people even said it's still on retail

##### AC HASH/COMMIT:
3d0a4288e0ce9579d90b86437a49c648eee16e87

<bountysource-plugin>

---
There is a **[$20 open bounty](https://www.bountysource.com/issues/96796145-very-important-missing-mob-leash-behavior?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…bat creatures.

Fixed #4660.

## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #4660.

## Tests Performed:
- Tested in game with different amount of mobs.
-

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
How to test, after translation, I didn't understand the mistakes in the question

**Comment by FrancescoBorzi** [comment]
@UltraNix please provide details about how to test this, including what can be potentially affected by the change so our testers can check it. Thank you

**Comment by UltraNix** [comment]
@pklloveyou Steps to test it:
1. Find some group of mobs (5-6 mobs)
2. Pull out ONLY one mob (e.g. taunt)
3. The rest of mobs should aggro on you
4. Start damaging ONLY the mob that you aggroed (from 2.)
5. Move with the aggroed mobs 40 yards, but remember attacking ONLY the first mob continously.
6.  Observe that the rest of the mobs will not evade, even if you were not attacking them.

Without this fix, the rest of mobs would evade.

**Comment by T1ti** [comment]
About point 4.
I think it should be any of those mobs will extend the leash, not just the original, they all become linked.

I cat test PRs right now my.installs and git are a mess

**Comment by UltraNix** [comment]
@T1ti And that's how it works now - any mob within the group extends the shared leash timer.

**Comment by T1ti** [comment]
https://github.com/vmangos/core/issues/793#issuecomment-756274983

For further testing, look at each of those points

**Comment by pklloveyou** [comment]
Can anyone give it a try? I failed the test
.go 7452 2800  413 571
.c 51775
Then move back and attack only the mocked NPC

**Comment by UltraNix** [comment]
Updated.

**Comment by UltraNix** [comment]
What are we waiting for?

**Review by Si1ker — APPROVED** [review]

**Comment by Si1ker** [comment]
> What are we waiting for?

To be tested.

**Comment by UltraNix** [comment]
Alright. I tested that ingame, but I understand you don't have to trust me as this is my code :) I'll be waiting.

**Comment by Si1ker** [comment]
> Alright. I tested that ingame, but I understand you don't have to trust me as this is my code :) I'll be waiting.

Just project's procedures, as done for everyone, thanks!

**Comment by FrancescoBorzi** [comment]
@UltraNix generally, we trust the author if it's already a known contributor like you are, however for delicate Core changes we typically require more users to check. Sometimes is hard to draw the line, but we try to do our best :)

thanks for your contribution!

@pklloveyou can you give this another try please?

**Comment by pklloveyou** [comment]
After testing, I found that there was no change, and there was no error described in the problem. I pulled NPC more than 190 yards away from the refresh point, and NPC would be out of combat
Within 190 yards, it's the same, not out of combat
I hope a second person can test it

**Comment by UltraNix** [comment]
@pklloveyou Test it again, please.

**Comment by UltraNix** [comment]
https://imgur.com/a/mbzRiXQ
This is how it looks right now. @T1ti what do you think?

**Comment by T1ti** [comment]
Yep, also test by damaging a different creature than the original one
I'm not sure about the blue creature reseting yet, I asked someone

**Comment by pklloveyou** [comment]
I'm building, please wait

**Comment by UltraNix** [comment]
> Yep, also test by damaging a different creature than the original one

I already did it when the original one died.

**Comment by T1ti** [comment]
well for a few secs only and you didn't really move them

**Comment by UltraNix** [comment]
> well for a few secs only and you didn't really move them

I move them 30 yards away, but imgur only accepts videos < 1min :(
But I assure you that none of the mobs evaded after the original one died.

**Comment by T1ti** [comment]
I believe you. Let's wait for some people that have played and tried this update tho it could have a lot of unintended bugs.

-some bugs to test is what happens when player got crowd controled (before a fix mbos would evade on vmang)s
-if creature's pets have the same leash timer and don't reset separately

**Comment by pklloveyou** [comment]
Tested I've moved so far, so long as I keep attacking all creatures, I won't be out of combat
image

**Comment by pklloveyou** [comment]
The second time I moved 270 yards

**Comment by T1ti** [comment]
So after talking a bit about it with one of the oriignal guys who researched this mechanic, here are some other tests : 
-Face pull multiple mobs at the same time, their leash shouldn't be linked
-pull multiple mob with an AOE(the aoe should hit them at the same time):leash shouldn't be linked

There is another mechanic : If a mob stays 5 second in melee range of the player, his leash while reset as if the player hit him. I need more info about how it works for casters/ranged hits
I'm also not sure if that 5 sec timer resets all the linked creatures or not

**Comment by T1ti** [comment]
-The leash deosn't only extend on taking damage, but on being hit by any negative spell(except triggered spells)
So a non damaging debuff should extend the leash

**Comment by UltraNix** [comment]
> -The leash deosn't only extend on taking damage, but on being hit by any negative spell(except triggered spells)
> So a non damaging debuff should extend the leash

Source info? I've never heard about that.

**Comment by T1ti** [comment]
Correction about the 5sec in range mechanic : 
It's not specifically related to the mob being in melee range, but to the **Chase movement generator**. 
The leash(12sec timer) will reset if the creature chases (move) for 5seconds

From Brotalnia : 
_there is a timer in chase movement generator
and it starts counting when mob stops moving
when it reaches 5 seconds, it resets the leash timer
which is 12 seconds_

**Comment by T1ti** [comment]
> > -The leash deosn't only extend on taking damage, but on being hit by any negative spell(except triggered spells)
> > So a non damaging debuff should extend the leash
> 
> Source info? I've never heard about that.

They tested it on classic, spaming a non damaging debuff will reset extend the leash forever

**Comment by UltraNix** [comment]
Remember that is Classic, not the Wotlk - mechanic might be changed.

**Comment by UltraNix** [comment]
https://github.com/TrinityCore/TrinityCore/issues/830
`On retail servers, both WotLK and Cataclysm, mobs will continue to follow you out of their spawn area if you continuously attack them and keep aggro on them. As soon as you stop actively attacking them for about 6 seconds, they will also evade and run back to their spawn location`
`Especially the paragraph called "Escaping Combat" is interesting as it says: "Note that if someone else pulls aggro from you or you continue to attack it, the traveling distance to leash the mob will reset."`
I remember videos from retail, kitting e.g. Fel Reaver to Shatrath City by attacking continously.

**Comment by T1ti** [comment]
> [TrinityCore/TrinityCore#830](https://github.com/TrinityCore/TrinityCore/issues/830)
> `On retail servers, both WotLK and Cataclysm, mobs will continue to follow you out of their spawn area if you continuously attack them and keep aggro on them. As soon as you stop actively attacking them for about 6 seconds, they will also evade and run back to their spawn location`
> `Especially the paragraph called "Escaping Combat" is interesting as it says: "Note that if someone else pulls aggro from you or you continue to attack it, the traveling distance to leash the mob will reset."`
> I remember videos from retail, kitting e.g. Fel Reaver to Shatrath City by attacking continously.

that's exactly what I said ? Just that it's either attacks or any spell cast on the creature, it deosn't ahve to doa ctual damages

**Comment by UltraNix** [comment]
In every single kitting video I saw that people must attacked mob by melee or damage spell.

**Comment by T1ti** [comment]
> In every single kitting video I saw that people must attacked mob by melee or damage spell.

because it's the obvious way to do it, but it's been proven non damaging debuffs also work

I just did it on classic and I kited a creature accross the map by spaming curse of weakness

**Comment by UltraNix** [comment]
Sorry, but I don't believe proofs from classic :)

**Comment by T1ti** [comment]
NP even though I beleive there is no reason for subtle global mechanics like this to have changed before cataclysm.
It's unrelated to this issue anyways, which is about the shared leash

**Comment by T1ti** [comment]
Lol I just tested it on retail, and ti's still how it works.
It didn't change from vanilal to shadowlands

**Comment by UltraNix** [comment]
> -some bugs to test is what happens when player got crowd controled (before a fix mbos would evade on vmang)s
> -if creature's pets have the same leash timer and don't reset separately

So what must be done? How it should work?

**Comment by UltraNix** [comment]
> -some bugs to test is what happens when player got crowd controled (before a fix mbos would evade on vmang)s
> -if creature's pets have the same leash timer and don't reset separately

@T1ti  So what must be done? How it should work?

**Comment by T1ti** [comment]
> > -some bugs to test is what happens when player got crowd controled (before a fix mbos would evade on vmang)s
> > -if creature's pets have the same leash timer and don't reset separately
> 
> @T1ti So what must be done? How it should work?

-just test if there is no bug when player gets crowd controlled
-pull a mob that has a pet, verify that the pets don't reset before the creature

**Comment by pklloveyou** [comment]
Conflict with #5065?

**Comment by T1ti** [comment]
We'll have to make sure that creatures aggroed by the new call for help tick don't share leash

Shared leash shoul only happen with the initial player pull

**Comment by UltraNix** [comment]
We are sure - there is check if mob is already called for help.

**Comment by FrancescoBorzi** [comment]
@pklloveyou @T1ti what's the status of this? can it be merged?

**Comment by pklloveyou** [comment]
@FrancescoBorzi Can be merged

**Pull request merged**
