### PR TITLE
fix(Script/Ulduar): Freya spawning multiple chests

### PR DESCRIPTION
**Pull request by avarishd**
It happens due the fact that you can still melee swing ~~and hold channel spells~~ on a target that has turned from hostile to friendly
Now I know why it was there in first place . . . 🐒 
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11793

## Tests Performed:

- Tested
- 

## How to Test the Changes:

1. .go c 136554
2. "Kill" freya and spam damage while she is roleplaying ( can use .damage 30000 or melee attacks)
3. Should spawn only 1 chest

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by avarishd** [comment]
@mpfans Try to overkill her multiple times while she is doing the dead roleplay. 
`.damage 3000000`

**Comment by Nyeriah** [comment]
Thanks for the PR, but this isn't a good solution. It's better if we check if the encounter is done in the first IF.

**Comment by avarishd** [comment]
@Nyeriah Something like this? Had to check Thorim to see how it's properly done. Also are the 4 keepers not supposed to bind you to the instance?

**Comment by Nyeriah** [comment]
Actually, I just meant

```cpp
            if (damage >= me->GetHealth() && _instance->GetData(TYPE_FREYA) == DONE)
```

I don't have information about the keepers, because, as you mentioned, you're already saved at that point 🤷‍♂️ so can't really check it, sadly.

**Comment by avarishd** [comment]
> ```c++
>             if (damage >= me->GetHealth() && _instance->GetData(TYPE_FREYA) != DONE)
> ```
Oh, wow... 🤦‍♂️  Will change it to that later. Thanks!

**Review by avarishd — COMMENTED** [review]
Implement Nyeriah's suggestion

**Comment by mpfans** [comment]
tested,work now

**Comment by mpfans** [comment]
@UltraNix  please check it,tyvm

**Review by UltraNix — APPROVED** [review]

**Comment by Nyeriah** [comment]
Did it not work? You still left the max health line

**Comment by avarishd** [comment]
It works, but I don't see a reason to remove it, keeping it as a "precaution" changes nothing.

**Comment by avarishd** [comment]
> Well, blizzlike scripts are our goal so unless it has been verified on retail that her health jumps to full instantly once she leaves combat it shouldn't be there. It's something you can verify in the packets received

That does make sense and I don't really need to packet sniff (I don't play retail/recycled), there is more than enough video source that her hp DOES NOT go to full. (Had to put damage = 0 on top, otherwise she would die)

**Comment by mpfans** [comment]
@UltraNix @Nyeriah  please check it,tyvm

**Review by UltraNix — APPROVED** [review]

**Pull request merged**
