### PR TITLE
Fix Scholomance Hall of secrets issues

### PR DESCRIPTION
**Pull request by vtihomirov**
#### Unstable Corpse:
* Adjusted Unstable Corpse (10480) SAI so it can now trigger Disease Burst on self-death.
#### Lorekeeper Polkelt:
* Replaced Corrosive Acid Breath(16359) ability with Corrosive Acid(8245).
* Replaced Volatile Infection(3584) ability with Volatile Infection(18149)
#### Unstable Corpse:
https://github.com/azerothcore/azerothcore-wotlk/issues/4520
> 2. Unstable corses don't explode on death

#### Lorekeeper Polkelt:
There isn't and issue present for Lorekeeper Polkelt but since I was testing the unstable corpses issue I decided to test him as well.
Currently Lorekeeper Polkelt casts Corrosive Acid Breath which applies a stackable debuff that deals damage.
Corrosive Acid Breath(16359):
```
160 armor reduction with 62 nature damage caused per application
```
But he should cast Corrosive Acid instead source https://youtu.be/ej5Y4tAQ0zI?t=3799 which has cast time and doesn't deal damage.

Corrosive Acid(8245):
```
960 armor reduction on all affected targets.
```

##### Unstable Corpse:
- Unstable corpses don't explode on death
- Tested in game on linux/docker setup from windows client.
- With the changes they now explode and deal 750 damage
##### Lorekeeper Polkelt:
- Currently Lorekeeper Polkelt casts Corrosive Acid Breath which applies a stackable debuff that deals damage.
- Tested in game on linux/docker setup from windows client.
- With the changes he now casts Corrosive Acid(8245)
```
960 armor reduction on all affected targets.
```

## Known Issues and TODO List:

- [ ]
- [ ]

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@vtihomirov thanks for your contribution! can you provide some evidence of testing, such as a video and/or some screenshots?

thank you!

**Comment by vtihomirov** [comment]
Screenshots of tests before the changes:
No disease burst:
without_changes-Screenshot_20210411_134245
Corrosive Acid Breath:
without_changes-Screenshot_20210411_134321

**Comment by vtihomirov** [comment]
Screenshots of tests after the changes:
Disease burst triggers and deals damage:
Screenshot_20210411_131448
Corrosive Acid has cast time:
Screenshot_20210411_132133
Corrosive Acid info:
Screenshot_20210411_132304

**Comment by pklloveyou** [comment]
Tested

**Comment by T1ti** [comment]
Lorekeeper : Volatile infectino's spell id was also incorrect

He should use https://classic.wowhead.com/spell=18149/volatile-infection instead of 3584

**Comment by vtihomirov** [comment]
Test after correction of volatile infection:
Screenshot_20210412_171012

**Comment by pklloveyou** [comment]
@T1ti

**Comment by Eldarix** [comment]
I think the fix works as intended, that's my results after the applying:

WoWScrnShot_060921_190620
WoWScrnShot_060921_190649
WoWScrnShot_060921_190657
WoWScrnShot_060921_190714

**Pull request merged**
