### PR TITLE
feat(Core/Command): Deserter Command send feedback

### LINKED ISSUE #11936: Feedback: .deserter command
### Describe your feature request or suggestion in detail

Following on this PR : https://github.com/azerothcore/azerothcore-wotlk/pull/11921
Currently, the .deserter command does not give any feedback after usage, it'd be useful for it to give back a message reporting results (whether it was successful or not, name of the character, duration, account name, account ID, character GUID).

### Describe a possible solution to your feature or suggestion in detail

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Gozzim**
## Changes Proposed:
-  Using the `.deserter` command will now always give feedback
    - Player or amount of players effected
    - Time factor if relevant
    - The kind of deserter processed

## Issues Addressed:

- Closes #11936

## Tests Performed:

- Added and removed BG Deserter from PlayerChar/Console to/from an online player
- Added BG Deserter from PlayerChar/Console to multiple online players and removed BG Deserter from all players 
- Added and removed BG Deserter from PlayerChar/Console to/from an offline player
- Added BG Deserter from PlayerChar/Console to multiple offline players and removed BG Deserter from all players 
- Added BG Deserter from PlayerChar/Console to a mix of online and offline players and removed BG Deserter from all players 

## How to Test the Changes:

1. Add a Deserter debuff to an offline player and remove it (before and after logging out)
2. Add a Deserter debuff to an online player and remove it (before and after logging in)
3. Add a Deserter debuff to a mix of online and offline players and remove it from all players

## Known Issues and TODO List:

- [ ] Removing deserter from all players will not display the correct value of the amount of players if a player hasn't been saved to the DB after gaining the Debuff
- [x] #11955

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Gozzim** [comment]
> I think we have yet to ponder if displaying how may deserter debuffs were removed is worth adding a blocking query in the command script. Those can be costy specially if used against the characters* tables.

Yeah, sadly that's very true. I was hoping that the `DELETE `would also return a result on how many lines were removed. But neither with `Execute` nor with `Query `it does. That's why I had to add that query. Maybe we could add this(?) I haven't looked that deep into the implementation yet.

**Comment by acidmanifesto** [comment]
> I think we have yet to ponder if displaying how may deserter debuffs were removed is worth adding a blocking query in the command script. Those can be costy specially if used against the characters* tables.

Do you have any objection to this PR?

**Comment by Gozzim** [comment]
> > I think we have yet to ponder if displaying how may deserter debuffs were removed is worth adding a blocking query in the command script. Those can be costy specially if used against the characters* tables.
> 
> Do you have any objection to this PR?

I opened a PR that would give a solution to this problem #12002

If this is merged we have a much more efficient way to get the number of deleted lines.

So waiting for that might be worth it. Of course we can also change it after or with that PR if this one is merged

**Comment by Maelthyrr** [comment]
@Gozzim can't test with conflicts.

**Comment by Gozzim** [comment]
Fixed @Maelthyrr

**Comment by acidmanifesto** [comment]
@azerothcore/testers

**Comment by acidmanifesto** [comment]
I'm rerunning a failed work flow that has nothing to do with this pr. Once it goes green we will merge it. Thank you @Maelthyrr for the test confirmation.

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
