### PR TITLE
fix(Docker): allow to use modules

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
##### CHANGES PROPOSED:

-  Include modules in Docker build

##### TESTS PERFORMED:

Not yet tested.

##### HOW TO TEST THE CHANGES:

Include a module in your sources as you would normally do in a traditional setup. Then run the docker setup and see if the module is correctly included.

##### Target branch(es):

Master

### CODE REVIEW

**Comment by sirbao** [comment]
Just finished docker build, still no modules activ/working, the only difference so far, was during the docker build process the modules folder seems to be included see screenshot
finished docker build

**Comment by FrancescoBorzi** [comment]
@sirbao thanks. Did you clean the build cache before compiling?

**Comment by sirbao** [comment]
@FrancescoBorzi Yes i did clean the cache before compiling.

**Comment by koffeine** [comment]
Adding `ADD modules /azerothcore/modules` line to `docker/build/Dockerfile` was not enough for me, I also had to remove `modules/*` line from `.dockerignore` file.

After building with these two changes modules were working in Docker.

**Comment by FrancescoBorzi** [comment]
many thanks @koffeine !

**Pull request merged**
