### PR TITLE
fix(Core/Formations): Implemented new creature formation flag: GROUP_AI_FLAG_ACQUIRE_NEW_TARGET_ON_EVADE.

### LINKED ISSUE #13394: [BWL] Death Talon Wrymguards respawn regression
original report https://github.com/chromiecraft/chromiecraft/issues/4172
### What client do you play on?

enUS

### Faction

Both

### Content Phase:

60

### Current Behaviour

Death Talon Wrymguards in BWL have a custom / far from blizzlike respawn behavior.
If they reset with less than 2 alive, the remaining one will respawn.
This allows for the group of 3 mobs to be split into a pull of one followed by a pull of the remaining two with usage of feign death.

### Expected Blizzlike Behaviour

The 3 guards shouldnt be separatable / splitable.
And if they not all 3 are killed, the full pack should respawn.

### Source

https://github.com/chromiecraft/chromiecraft/issues/3321
regression of https://github.com/azerothcore/azerothcore-wotlk/pull/11512

### Steps to reproduce the problem

2 chars required.
pull one with hunter, attack one with 2nd char, FD with hunter. only one mob stays infight due to inproper linking.

### Extra Notes

so far these mobs have not being fixed fully. Luckily, the Anubisath Sentinals at the entrance of AQ40 have the correct behavior regarding: getting in combat, staying linked, respawning on reset.
Please, use the Anubisath Sentinals as a template for the behavior of the Wrymguards to fix them.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/77faa1d84d85199170ef540a43b5ed824de43702

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Improved GROUP_AI_FLAG_ASSIST* flags implementation.
Fixes #13394

## Issues Addressed:

- Closes #13394
- Closes https://github.com/chromiecraft/chromiecraft/issues/4172

## Tests Performed:

- Not tested.

## How to Test the Changes:

2 chars required.
pull one with hunter
attack the rest with 2nd char
FD with hunter
The hunter mob should switch the 2nd char

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Are you sure this is always the case?

**Comment by Gultask** [comment]
For example: I found these while I was searching for something else:

>That's not how it is now either. I have jumped down in UBRS without dismissing my pet and only noticed when I saw him taking damage but not standing near me... I put him on stay and he died, then I feigned death and all the stuff the pet pulled reset. This was because I wasn't close to my party at the time and nobody healed/buffed me to chain them into the threat table, so when I feigned death I was the only one on their threat table.
>
>I've had this same sorta thing work when I accidentally face pulled, but I've also seen it fail if I was close enough to my party that when they aggroed me it instantly put my party in combat with them as well. ([source](https://www.reddit.com/r/classicwow/comments/ezwr2y/comment/fgql2dm/))

> just last night doin Strat UD I pulled a pack and FD'd and it reset just fine without going to the group - I was far enough away and didn't have any HoTs or heals going to me. (same source)

**Comment by UltraNix** [comment]
@Gultask I will improve it.

**Comment by UltraNix** [comment]
@Gultask Please, test it again.

**Comment by Maelthyrr** [comment]
Tested and seems to work fine:

- [X] When hunter FD, creatures switch to the other char
- [X] If players die with at least one creature alive, all the group respawn

**Comment by FrancescoBorzi** [comment]
what's the status of this PR? can anyone please review it? @azerothcore/developers

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@UltraNix have you updated the documentation (wiki) about this change?

**Pull request merged**
