### PR TITLE
fix(Core/Spells) T9 2p Hunter bonus vs Mortal Shots.

### LINKED ISSUE #8859: [Hunter] T9 2 piece Serpent Sting Crit dmg wrong scaling
### Current Behaviour

https://github.com/dalaranwow/dalaran-wow/issues/3017

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

see https://github.com/dalaranwow/dalaran-wow/issues/3017

### Extra Notes

_No response_

### AC rev. hash/commit

a25eae3

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed getting bonus damage from critical strikes for melee/ranged DoT spells.
Fixes #8859

## Changes Proposed:
-  More to read: https://github.com/TrinityCore/TrinityCore/issues/1807 https://github.com/TrinityCore/TrinityCore/issues/6647

## Issues Addressed:

- Closes #8859

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info [here](https://github.com/dalaranwow/dalaran-wow/issues/3017)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by claudiodfc** [comment]
## Test Result: ❌
- Using the Tier 9 4/5 Hunter set.
- Crit damage before Mortal Shots: 750
- Crit damage after learning Mortal Shots(5/5): 750

**Comment by UltraNix** [comment]
@claudiodfc Try again.

**Comment by claudiodfc** [comment]
Unchanged results. Still the same crit damage.

**Comment by UltraNix** [comment]
Non-crit:
WoWScrnShot_112221_171707

Crit w/o Mortal Shots:
WoWScrnShot_112221_171652

Crit with Mortal Shots:
WoWScrnShot_112221_171552

308 + (308 * 1.3) ~ 709
Everything works okay.

**Comment by Nyeriah** [comment]
@UltraNix it seems there are merge conflicts

**Comment by UltraNix** [comment]
Done.

**Pull request merged**
