### PR TITLE
fix(Core/Character):fix worldserver with autobalance mod crash when character creation fails

### PR DESCRIPTION
**Pull request by Vitumoc**
## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/17577
- Closes https://github.com/azerothcore/mod-autobalance/issues/166

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by kjack9** [comment]
I don't think I love this solution to the problem - doesn't this try to make a new map with ID 0 (Eastern Kingdoms, I believe)?

Instead, might I recommend touching the GetMap() function directly?

https://github.com/azerothcore/azerothcore-wotlk/blob/52d37a927dc921785fcac35bd8830221299495c7/src/server/game/Entities/Object/Object.h#L526C41-L526C47

Or it might be better to have the `OnPlayerLeaveCombat` hook not be called at all for a player who was never actually created?

**Comment by kjack9** [comment]
I will see if I can find a good way to test, but I like your latest solution a lot better. 👍

**Comment by Vitumoc** [comment]
When a player was not actually created, no cleanup is required. player is just a `Player*`.

https://github.com/Vitumoc/azerothcore-wotlk/blob/747aa8efbe93a8949f4d908e90024174290ee3f7/src/server/game/Handlers/CharacterHandler.cpp#L538-L559

`MotionMaster` will be automatically deleted.No need to use clean function.
when the player is created successfully, the AT_LOGIN_FIRST flag must be set. On the contrary, when the player creation fails, m_atLoginFlags will be AT_LOGIN_NONE.

I will do some testing on this change later.

**Review by kjack9 — APPROVED** [review]
This solution makes a lot of sense to me and prevents the firing of hooks/functions on characters that never actually entered the world.

**Comment by Nyeriah** [comment]
Please fix code style (no php style braces, braces go to new line)

**Comment by Nyeriah** [comment]
Also AtLoginFlags is a bitmask, so it needs bitwise evaluation (the check will fail if for some reason they have any other flag during their first login in addition to the first login flag)

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
