### PR TITLE
Add GitRevision

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
**Changes proposed:**
- Add GitRevision as in TrinityCore
- Delete SystemConfig.h

#### When you change the revision, some files (described below) will not be compiled again
* src/common/Debugging/WheatyExceptionReport.cpp
* src/server/authserver/Main.cpp
* src/server/game/Handlers/CharacterHandler.cpp
* src/server/game/World/World.cpp
* src/server/scripts/Commands/cs_server.cpp
* src/server/worldserver/Master.cpp

**Target branch(es):** master.

**Issues addressed:** No issue

**Tests performed:** Tested build (Windows 10 and Linux 14.04)

**How to test the changes:**
- Apply commit (https://github.com/Winfidonarleyan/azerothcore-wotlk/commit/a851f4496842cf2a2c6263a400641f19cc151308)
- Rebuild core
- Add new test commit
- Rebuild core
- You can see how only 1 file is compiled (GitRevision.cpp)

**Known issues and TODO list:** No

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
What kind of tests are needed?

**Comment by BarbzYHOOL** [comment]
The tests you mentioned :P

**Comment by Winfidonarleyan** [comment]
I tested everything. Windows and Linux + Travis. All test ok.

**Comment by BarbzYHOOL** [comment]
Just need someone else to confirm, don't worry!

**Comment by Viste** [comment]
use it more then one year on sunwell, all is ok.
but! test tonight on AZ and write result

**Comment by Winfidonarleyan** [comment]
@BarbzYHOOL, Ok ok 👍

**Comment by kraftmatic** [comment]
Tested fine on *nix.

**Comment by ShinDarth** [comment]
@kraftmatic you can then merge it

**Comment by BarbzYHOOL** [comment]
Thank you @kraftmatic and @Viste  for testing

Thank you @Winfidonarleyan for fix!!

**Pull request merged**
