### PR TITLE
fix(DB/Quest): Going Bearback SAI

### PR DESCRIPTION
**Pull request by poszer**
Fix Going Bearback quest issue

##### CHANGES PROPOSED:

-  React state, will fix issue with creatures that are friendly instead of enemy.
-  

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1853 https://github.com/azerothcore/azerothcore-wotlk/issues/695

##### TESTS PERFORMED:

Yes, quest can be done now without problem.

##### HOW TO TEST THE CHANGES:

1. Read closing issue or .quest add 12851 // .tele stormpeaks (on the quest location)
2. Also be sure to complete all previous chain quests :
going

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
good job @poszer and @Selyria

**Comment by Meltie2013** [comment]
@poszer 
Just to let you know, there is a server side spell that goes with Icefang.

```
ID - 54788 Icefang Begin Pathing
=================================================
Category = 0, SpellIconID = 1, activeIconID = 0, SpellVisual = (0,0), SpellPriority = 0
Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x00000180 (SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
=================================================
Spell Level = 0, base 0, max 0, maxTarget 0

Category = 0
DispelType = 0 (DISPEL_NONE)
Mechanic = 0 (MECHANIC_NONE)
SpellRange: (Id 1) "Self Only":
    MinRange = 0, MinRangeFriendly = 0
    MaxRange = 0, MaxRangeFriendly = 0

CastingTime (Id 1) = 0.00
Duration: ID (35)  4000, 0, 4000
Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
Chance = 101, charges - 0
=================================================
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0

Effect 1:  NO EFFECT

Effect 2:  NO EFFECT
```

Missing spell for column `spell3`. 
```
+-------+---------+--------+--------+--------+
| entry | name    | spell1 | spell2 | spell3 |
+-------+---------+--------+--------+--------+
| 29602 | Icefang |  54897 |  54907 |      0 |
+-------+---------+--------+--------+--------+
```

Reference Commit:
https://github.com/TrinityCore/TrinityCore/commit/589fed54d15c9c769ef22c0b98dcaed68d8383b

**Comment by poszer** [comment]
> @poszer
> Just to let you know, there is a server side spell that goes with Icefang.
> 
> ```
> ID - 54788 Icefang Begin Pathing
> =================================================
> Category = 0, SpellIconID = 1, activeIconID = 0, SpellVisual = (0,0), SpellPriority = 0
> Family SPELLFAMILY_GENERIC, flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000
> 
> SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
> DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
> PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
> =================================================
> Attributes: 0x00000180 (SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_HIDE_IN_COMBAT_LOG)
> =================================================
> Spell Level = 0, base 0, max 0, maxTarget 0
> 
> Category = 0
> DispelType = 0 (DISPEL_NONE)
> Mechanic = 0 (MECHANIC_NONE)
> SpellRange: (Id 1) "Self Only":
>     MinRange = 0, MinRangeFriendly = 0
>     MaxRange = 0, MaxRangeFriendly = 0
> 
> CastingTime (Id 1) = 0.00
> Duration: ID (35)  4000, 0, 4000
> Interrupt Flags: 0x00000000, AuraIF 0x00000000, ChannelIF 0x00000000
> Chance = 101, charges - 0
> =================================================
> Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
> BasePoints = 0
> Targets (25, 0) (TARGET_UNIT_TARGET_ANY, NO_TARGET)
> Aura Id 4 (SPELL_AURA_DUMMY), value = 1, misc = 0 (0), miscB = 0, periodic = 0
> 
> Effect 1:  NO EFFECT
> 
> Effect 2:  NO EFFECT
> ```
> 
> Missing spell for column `spell3`.
> 
> ```
> +-------+---------+--------+--------+--------+
> | entry | name    | spell1 | spell2 | spell3 |
> +-------+---------+--------+--------+--------+
> | 29602 | Icefang |  54897 |  54907 |      0 |
> +-------+---------+--------+--------+--------+
> ```
> 
> Reference Commit:
> [TrinityCore/TrinityCore@589fed5](https://github.com/TrinityCore/TrinityCore/commit/589fed54d15c9c769ef22c0b98dcaed68d8383b)

I know, that's just random added on trinity. It's not blizzlike.
I remember very well that there was just 2 options while driving this bear farming rep with Hodir factions. 
Also, you can see here video, it's very old video, 10 years ago posted :
https://www.youtube.com/watch?v=uA7YubiAHGA
There are also just 2 spells

**Comment by BarbzYHOOL** [comment]
Are you sure @poszer ?? it says " Last spell (spell3) shouldn't be show to the client," so it's normal that u can't see it in the video lol

**Comment by Meltie2013** [comment]
The spell should be in (spell7). Plus server side spell will never display at the client anyways.

**Comment by BarbzYHOOL** [comment]
yes however what does that spell do? and why spell7 and not 3? lol so mysterious

In top of that, the spell 54788 is not in spell_dbc table so it's only in the DBC??

I checked the DBC and there is no description for that spell, only a name and then need to analyze the values (it's very tedious). Name is "Icefang Begin Pathing"

**Comment by Meltie2013** [comment]
Majority of server side spells won't have descriptions on them.

The table `spell_dbc` is mainly used for custom spell entries or modifications. Its used for spells that are available to players.

Going back to spell `54788`, its an aura. It states in the the spell data I posted. It starts the pathing of the creature.

**Comment by BarbzYHOOL** [comment]
spells in spell_dbc have no buff displayed (and not even a name) so I supposed it would be there

well I think it's something @poszer should add or at least try with that mob

ty for info meltie

**Pull request merged**
