### PR TITLE
fix(DB/gameobject): Out of place Bruiseweed nodes

### LINKED ISSUE #5884: Silverpine Forest - Herb nodes spawning inside buildings
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [x] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Bruiseweed nodes 2944 and 3069 are located inside buildings. (Bug found on Chromie, screenshots from local server)
WoWScrnShot_050921_174843
WoWScrnShot_050921_174807

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Resource nodes shouldn't spawn inside buildings like this.

##### STEPS TO REPRODUCE THE PROBLEM:

1. `.go o 3069` 
2. `.go o 2944`
3. `.gobject near` if they're not spawned and you want to be sure

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/6947789622de45479d2311fd5d1635af3a957b5d

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98542802-silverpine-forest-herb-nodes-spawning-inside-buildings?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anguaive**
Bruiseweed nodes (id: 2944, 3069) are located inside buildings.
This is wrong. I chose to remove the nodes instead of relocating them
nearby, because the Bruiseweed density in this area already way higher
than on live classic.

17 Bruiseweeds in a 100 radius from a point midway between the two affected buildings:
WoWScrnShot_051621_105123
(everything except Bruiseweeds are filtered out)

Only 11 Bruiseweeds in the vicinity according to wowhead classic:

## Changes Proposed:
-  Remove Bruiseweed nodes (id: 2944, 3069)

## Issues Addressed:

- Closes #5884 
- Closes https://github.com/chromiecraft/chromiecraft/issues/589

## SOURCE:
https://classic.wowhead.com/object=1622/bruiseweed

## Tests Performed:

- Tested on 8168f9a

## How to Test the Changes:

1. `.go o 2944` shouldn't work
2. `.go o 3069` shouldn't work

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Hacki95** [comment]
The problem with these nodes is not necessarily that they are too many or wrong, they are just not pooled and thats why too many of them spawn at the same time.

Wowhead classic is not necessarily accurate for things like this.

**Comment by claudiodfc** [comment]
Even though our nodes are not pooled, this can be merged since he's deleting Herbs that grow inside buildings

**Comment by claudiodfc** [comment]
@Kitzunu would you be so kind to review this 🙏🏼

**Review by Si1ker — COMMENTED** [review]
deleting content is not a fix until proof of it.

**Comment by claudiodfc** [comment]
> deleting content is not a fix until proof of it.

Where do plants grow? Outside on earth or on the building's floor?

**Comment by Si1ker** [comment]
> > deleting content is not a fix until proof of it.
> 
> Where do plants grow? Outside on earth or on the building's floor?

If a gob is into the DB, is for a reason, no one was intentionally planning to deploy gobs into buildings just because the water is liquid, deleting is not the right fix, gobs into buildings should be relocated with source.
You know, some stuff you find out when you start thinking, you can do it too, just try.

**Comment by claudiodfc** [comment]
Lmao, that's all I have to say. Just lmao.

**Comment by Helias** [comment]
What should we do with this PR?

- Merge it deleting the gobs closing the issues? :green_circle: 
- Merge it deleting the gobs without closing the issues? :green_apple: 
- Do not merge, put in WIP until the author of the PR move the gobs instead of delete? :green_square:

**Comment by LukasVolgger** [comment]
WIP and move the GOBs imo

**Pull request closed without merging**
