### PR TITLE
fix(Core): reputation gain rate when nearby party members are dead

### PR DESCRIPTION
**Pull request by r-o-b-o-t-o**
## Changes Proposed:
-  Fix reputation gains when a nearby party member is dead.

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5398

## Tests Performed:

- Applied C++ changes
- Tested in-game on Windows 10 clients and server

## How to Test the Changes:

- Get two characters in a party
- `.go c 52242` with both characters
- Kill the Skeletal Acolyte
- Both characters should get around +5 rep with Argent Dawn
- Target one of the two characters and do `.die`
- `.respawn 52242`
- With the character that is still alive, kill the Skeletal Acolyte
- Verify that both characters get the same amount of reputation as before

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by r-o-b-o-t-o** [comment]
Since there are now two variables (`xpRate` and `reputationRate`) instead of `rate` in `KillRewarder::_RewardPlayer`, I'm wondering if I should change `ScriptMgr::OnRewardKillRewarder(player, isDungeon, rate);` to `ScriptMgr::OnRewardKillRewarder(player, isDungeon, xpRate, reputationRate);`?

**Comment by Sedatyf** [comment]
Hey there.
I don't know if @r-o-b-o-t-o questions will change something in PR's behavior, but I tested it anyway. (I'll test it again if necessary after the possible changings in code)
So, both characters gained +5 rep by killing creature when they are both alive ✔️ 

https://user-images.githubusercontent.com/59012307/116855996-a1396900-abfa-11eb-8e5d-05e6a621e7bb.mp4

And both characters gained +5 rep as well when of them is dead ✔️ 

https://user-images.githubusercontent.com/59012307/116856052-b8785680-abfa-11eb-9445-64a6bfc5eccb.mp4

Feel free to @me if you want me to test it again

**Comment by r-o-b-o-t-o** [comment]
> I don't know if @r-o-b-o-t-o's question will change something in the PR's behavior, but I tested it anyway. (I'll test it again if necessary after the possible changes in code)

The question I asked is about the scripting engine, so it could break existing modules, but it wouldn't change anything in a server without modules

**Comment by Sedatyf** [comment]
>The question I asked is about the scripting engine, so it could break existing modules, but it wouldn't change anything in a server without modules

Ah I see. It can be the subject of another test though.

**Comment by FrancescoBorzi** [comment]
what's the status of this? further test needed ?

> > The question I asked is about the scripting engine, so it could break existing modules, but it wouldn't change anything in a server without modules
> 
> Ah I see. It can be the subject of another test though.

**Comment by Sedatyf** [comment]
> Since there are now two variables (`xpRate` and `reputationRate`) instead of `rate` in `KillRewarder::_RewardPlayer`, I'm wondering if I should change `ScriptMgr::OnRewardKillRewarder(player, isDungeon, rate);` to `ScriptMgr::OnRewardKillRewarder(player, isDungeon, xpRate, reputationRate);`?

@r-o-b-o-t-o asked this but currently, it can be merged if you don't have any further informations to give him

**Comment by FrancescoBorzi** [comment]
ah I see your point, I'm giving some time for a second opinion @azerothcore/modules @Yehonal otherwise I'd merge it later

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
