### PR TITLE
feat(Core/Spell): revert "feat(Core/Spells): improve SpellCheckRange(), spell cast when dismounting, falling or levitating spells (#3384)"

### PR DESCRIPTION
**Pull request by Helias**
This reverts commit b4242735749ca6ff4d7e370cc0d41105f5856f60.

## Changes Proposed:
-  revert https://github.com/azerothcore/azerothcore-wotlk/pull/3384

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5021

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Helias** [comment]
@markvetx @zqgmzq make a quick test pls

**Comment by markvetx** [comment]
@Helias Works okay.

**Comment by pklloveyou** [comment]
This also fixed the hunter's explosion trap

**Review by icecatbing — APPROVED** [review]
Works okay.

**Pull request merged**
