### PR TITLE
feat(Core/Thread): move Processpriority to separated files

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Move Processpriority to separated files

## Tests Performed:
- Startup

## How to Test the Changes:
- Just startup all applications

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @mpfans can you please have a look at this?

**Comment by Sedatyf** [comment]
What do you mean by ``Just startup all applications`` @Winfidonarleyan?
Do I just have to build this PR and then run my server?

**Comment by Winfidonarleyan** [comment]
> What do you mean by `Just startup all applications` @Winfidonarleyan?
> Do I just have to build this PR and then run my server?

Yes

**Comment by Sedatyf** [comment]
Hey @Winfidonarleyan 
So I built this PR, started worldserver and authserver. Nothing odds happened. I played a bit, like I did a dungeon, created a character, deleted it, nothing weird. I don't know if you need me to do more thant that. If so, let me know

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
I think it's enough, as it's just about moving code from one file to others, thanks @Sedatyf <3

**Comment by Winfidonarleyan** [comment]
> Hey @Winfidonarleyan
> So I built this PR, started worldserver and authserver. Nothing odds happened. I played a bit, like I did a dungeon, created a character, deleted it, nothing weird. I don't know if you need me to do more thant that. If so, let me know

Thanks for test

**Pull request merged**
