### PR TITLE
fix(DB/CreaturesSAI): Silithid Invader and Silithid Hive Drone

### PR DESCRIPTION
**Pull request by Stifler82**
## Changes Proposed:
-  Fixed SAI NPC: [Silithid Hive Drone](https://classic.wowhead.com/npc=4133/silithid-hive-drone) and [Silithid Invader](https://classic.wowhead.com/npc=4131/silithid-invader)

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/207
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4862

## Tests Performed:

- Tested in game and working
- Tested on Windows 10 (64)
- **Video Test:** [Silithid Invader and Silithid Hive Drone](https://youtu.be/-HBY2wByGUU)

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
image
fail

**Comment by Stifler82** [comment]
> image
> fail

look better, give a look to my video test, pls..

**Comment by FrancescoBorzi** [comment]
> image
> fail

thanks for testing this but can you please be a bit more descriptive? where is the failure and how can we reproduce it?

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
