### PR TITLE
fix(DB/Script): Violet Hold Door not opening

### PR DESCRIPTION
**Pull request by Valdifer**
## Changes Proposed:
-  Violet Hold door wasn't opening when you were pressing the lever, so i moved The Violet Hold door to Smart_script

## Issues Addressed:

- Closes 

## Tests Performed:

- Build without errors
- https://www.youtube.com/watch?v=jOSdSKqGntM

## How to Test the Changes:

1. .tele dalaran
2. go to violet hold
3. .additem 42482 and open the door
4. press the lever

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Hi, unfortunately, this PR doesn't work. But it's a global issue with all levers. Look https://github.com/azerothcore/azerothcore-wotlk/issues/10340 and https://github.com/azerothcore/azerothcore-wotlk/issues/10340.

If I did any mistake this work but the author had never updated with the review: https://github.com/azerothcore/azerothcore-wotlk/pull/11739

**Comment by Valdifer** [comment]
> Hi, unfortunately, this PR doesn't work. But it's a global issue with all levers. Look #10340 and #10340.
> 
> If I did any mistake this work but the author had never updated with the review: #11739

It is strange, i tested it and for me it is working. The video i added is after testing the SAI, gonna test it again

**Comment by Valdifer** [comment]
image
Tested now

**Comment by Maelthyrr** [comment]
I will recheck this night. Maybe an error.

**Comment by Maelthyrr** [comment]
You're right. I made a mistake. So work as intended. Thanks :)

**Comment by Valdifer** [comment]
> You're right. I made a mistake. So work as intended. Thanks :)

No worries! thx :D

**Review by acidmanifesto — APPROVED** [review]

**Pull request merged**
