### PR TITLE
fix(db): Missing creature_queststarter entry NPC Duke Hydraxis

### LINKED ISSUE #2447: [Fix included] Missing creature_queststarter entry 'Duke Hydraxis'
##### SMALL DESCRIPTION:

Duke Hydraxis should start the quest 6804 - he didn't.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

NPC 'Duke Hydraxis' should give the quest 6804. 

##### CURRENT BEHAVIOUR:

Source: 
https://classic.wowhead.com/quest=6804/poisoned-water
https://classic.wowhead.com/npc=13278/duke-hydraxis#starts

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### EXTRA NOTES:

FIX: 

`DELETE FROM `creature_queststarter` WHERE `id` = 13278 AND `quest` = 6804;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (13278, 6804);`

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

c294dd3+ 2019-11-06 09:34:24 +0100 (master branch)

##### OPERATING SYSTEM:

Windows 10 pro 64 Bit

##### MODULES:

- Auctionhouse Bot
- Autobalance

##### OTHER CUSTOMIZATIONS:

-  Max Skill on levelup

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/83884773-fix-included-missing-creature_queststarter-entry-duke-hydraxis?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Endeffect-AT**
NPC Duke Hydraxis 13278 was not starting the quest 6804

Closes AzerothCore issue #2447

##### CHANGES PROPOSED:
-  Added entry in world table creature_queststarter  id 13278 and quest 6804

##### ISSUES ADDRESSED:
- Closes #2447 

##### TESTS PERFORMED:
- Tested successfully ingame

##### HOW TO TEST THE CHANGES:

- Import the sql file
- Go to NPC 13278 and check if he starts the quest 6804 'Poisoned Water'

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):
- [x] Master

 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Helias** [comment]
Tested, it works.  

immagine

**Comment by Endeffect-AT** [comment]
@Helias 
Thx 4 testing, also added the questender entry. Pls test it too after finishing the quest

**Comment by Helias** [comment]
I tested also the questender fix.

**Comment by Endeffect-AT** [comment]
Perfect 👍🏻

**Comment by Stoabrogga** [comment]
Sorry, but this should not be merged. As pointed out correctly in this comment the quest was removed with patch 3.0.8:
https://github.com/azerothcore/azerothcore-wotlk/issues/2447#issuecomment-554770582

See also:
https://wow.gamepedia.com/Duke_Hydraxis#Patch_changes

Please be careful, WoW Classic is **not** WotLK.

**Comment by Endeffect-AT** [comment]
I got my approvement that the quest should be there in the EveryQuest DB from WotLK Addon. Here it is required with the quest 'Stormers and Rumblers' to unlock the quest 'Eye of the Emberseer'. 

Alright, close this 👍 
Sry for the inconveniences 🙏

**Comment by Helias** [comment]
I'm sorry too.

I checked online wowhead several times, this was also my mistake, sorry :pensive:

**Comment by Stoabrogga** [comment]
What's also really annoying: If you open this URL you get to the classic version and have to manually switch to retail:
https://wowhead.com/quest=6804
Only on the retail version you get the complete list of comments concerning the other patches.

**Comment by Endeffect-AT** [comment]
@Stoabrogga 

As i told you, the final confirmation for me to add the quest was the EveryQuest DB.
Now i know i have to spend more time to research, it never happens again. My only motive is to help to improve the AC.

It was my fault, sry.

**Comment by FrancescoBorzi** [comment]
@Endeffect-AT no worries and thanks for your contribution anyway! If you need any assistance while contributing, just poke us on discord ;)

**Pull request closed without merging**
