### PR TITLE
fix(Core/Spells): Next melee swing spells are supposed to be queued u…

### LINKED ISSUE #6588: "On next attack" spells are not queued when out of range
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [ ] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Queuing up "on next attack" spells such as Raptor Strike or Heroic Strike while out of range (may it be from afar, kiting too far away using Wing Clip) causes the "Out of range" error to pop up and unqueues the "on next attack" spell.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

On Next Attacks are supposed to "Queue up" when out of range and get used once you get within range of your target.. So you don't need to spam the ability in order to make it so your next melee swing.

##### SOURCE:

In both Classic and Classic TBC you are able to queue these abilities up when you are outside of range
Video from retail Classic WoW where Raptor Strike get queued when out of range: https://youtu.be/8-CAayVkpEc?t=90

##### STEPS TO REPRODUCE THE PROBLEM:

1. Create a hunter
2. While out of melee range, use Raptor Strike
3. Get the "Too far away" error 
4. Raptor Strike gets canceled.

##### EXTRA NOTES:

Originally reported https://github.com/chromiecraft/chromiecraft/issues/1006

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99494654-on-next-attack-spells-are-not-queued-when-out-of-range?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…p even when out of range.

Fixed #6588

## Changes Proposed:
-  On Next Swing Attacks are supposed to "Queue up" when out of range and get used once you get within range of your target

## Issues Addressed:

- Closes #6588
- Closes https://github.com/chromiecraft/chromiecraft/issues/1006

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. Create a hunter
2. While out of melee range, use Raptor Strike
3.  No "Out of range" error. If you reach your target, the spell is casted.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
It now appears to be interrupted and will not cast automatically near the target

**Comment by UltraNix** [comment]
Can you test it again? Can try with warrior's Heroic Strike?

**Comment by pklloveyou** [comment]
ok

**Comment by pklloveyou** [comment]
Heroic Strike after PR is in the skill queue and works normally

**Comment by UltraNix** [comment]
Raptor Strike works okay if you have disabled AutoShot (Autoshot interrupt all spells - it's okay).

**Comment by pklloveyou** [comment]
Tested
I removed the character's auto fire spell and it works normally

**Review by Helias — APPROVED** [review]

**Pull request merged**
