### PR TITLE
fix(Scripts/AhnQiraj): Hive'Zara Stinger.

### LINKED ISSUE #12532: [AQ20] Hive'Zara Stinger do not use any abilities
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

60

### Current Behaviour

NPC: https://wowgaming.altervista.org/aowow/?npc=15327
Hive'Zara Stinger do not use any abilities.

### Expected Blizzlike Behaviour

Hive'Zara stingers hit for 3000 damage against someone afflicted with Hive'Zara Catalyst from Hive'Zara Wasps. Charges random targets for about 500 (against tank).

The mob will charge if you are within 5-25 yards. Either be right on top of the mob, or at max casting range. Anywhere in between and you will be charged.

The charge does not deaggro, the mob returns immediately to the tank. Melee group should not move if this happens. 

### Source

https://wowwiki-archive.fandom.com/wiki/Hive%27Zara_Stinger

### Steps to reproduce the problem

1. Go to PTR.
2. Go to AQ20.
3. Engage Hive'Zara Stinger.
4. See result.

### Extra Notes

Originally reported: https://github.com/chromiecraft/chromiecraft/issues/3825

See comments for more information

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/35dfcf588f62339c44ff99a3e7e85f0b983ed923

### Operating system

Windows 10 Pro

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft PTR - AzerothCore rev. cc52712ac12e 2022-07-15 16:11:49 +0200 (master branch) (Unix, Debug, Static)

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12532

## Issues Addressed:

- Closes #12532

## Tests Performed:

- Not tested.

## How to Test the Changes:

Go to PTR.
Go to AQ20.
Engage Hive'Zara Stinger.
See result.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
Didn't work for me. Still isn't casting anything.

And sorry I forgot to add additional info in the issue linked.
It always prefers to target players afflicted by Hive'Zara Catalyst over others.
It casts a Charge immediately on pull and every 4850 - 6100ms after

**Comment by UltraNix** [comment]
@Gultask Have you been in 5-20y range?

**Comment by UltraNix** [comment]
Also, there is a new file, so you must re-run cmake.

**Comment by Gultask** [comment]
I did re-run cmake. But I got to see it once now although only on pull. I have 2 characters, each one engaged with a different Hive'Zara Stinger, standing 15y from each other and in both of the Stinger's threat lists, but I'm not seeing a Charge.

image

The 5y minimum range limitation doesn't exist in WotLK: https://youtu.be/qczUg9kUIV4?t=105
I believe it's another case of a mob *prefers* targets that are over 5y in range, but does not exclude those that are within 5y if there are no better alternatives.

**Comment by UltraNix** [comment]
@Gultask 
obraz_2022-08-07_210134121

Please, test it again with some updates.

**Comment by Gultask** [comment]
It's much better now but it isn't prioritizing players with aura 25187 (Hive'Zara Catalyst).
Also I still think the timers need to be adjusted. You can see it in the video how fast it is (I believe it's every 3s and the video plays in 2x speed) and the timer I gathered was also very fast at 4850 - 6100ms

**Comment by UltraNix** [comment]
`It's much better now but it isn't prioritizing players with aura 25187 (Hive'Zara Catalyst).` Works okay to me (remember it won't charge to tank anymore).
Timers corrected.

**Comment by Gultask** [comment]
Strange. I used 3 characters, one as the tank, one with the aura and one without. It still charged randomly between the latter two.

**Comment by Maelthyrr** [comment]
Tested and UN have right. Everything work, even charge.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
