### PR TITLE
feat(Core/SmartScripts): Add a warning when a boolean value is outside of [0,1] range

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

https://github.com/TrinityCore/TrinityCore/commit/84c8d21ad38ade64444e2394f090b49d2ffb5c51

@Nyeriah Can you check these db errors and make sure they are correct  or not Please! 
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@IntelligentQuantum Conflicts here

**Comment by Kitzunu** [comment]
This is good

**Comment by IntelligentQuantum** [comment]
@Nyeriah Done

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Well, those start up errors need to be fixed now x)

**Comment by IntelligentQuantum** [comment]
> Well, those start up errors need to be fixed now x)

Yeah and i need your help xD

**Comment by Kitzunu** [comment]
Just set all of them to 1, it can't get worse than it already is, rithgt?

**Comment by Kitzunu** [comment]
modules failing

**Comment by Kitzunu** [comment]
not due to this, my bad

**Pull request merged**
