### PR TITLE
fix(Core/AI): Fix target selectors logic when accounting for tanks

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  Fix the logic so it skips tanks when it is supposed to
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- Tested ingame
- 

## How to Test the Changes:

1..go creature id 9018
2. notice she casts shadoword pain on tanks again
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@Maelthyrr Please take a look at this when you have the time, to see if this is intended or we should rename the variable.

Currently target selectors are broken and tanks are excluded by default, because despite **withTank** being set to true, tanks are never selected. So it seems to be like the logic was reversed. Have a look yourself.

**Review by 55Honey — APPROVED** [review]

**Comment by pklloveyou** [comment]
tc 
```

DefaultTargetSelector::DefaultTargetSelector(Unit const* unit, float dist, bool playerOnly, bool withTank, int32 aura)
    : _me(unit), _dist(dist), _playerOnly(playerOnly), _exception(!withTank ? unit->GetThreatManager().GetLastVictim() : nullptr), _aura(aura)
{
}

```

**Comment by Nyeriah** [comment]
Not really concerned about how it looks like at TC when it's not working as intended.

**Comment by pklloveyou** [comment]
I mean, TC is consistent with your PR
In addition, after using your PR, I tested two bosses and now they work normally

**Pull request merged**
