### PR TITLE
fix(DB/GameObject): fix Malchezaar door being selectable

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
- change the door to be not selectable
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16272
- Closes https://github.com/chromiecraft/chromiecraft/issues/5611

## SOURCE:

see sources linked in issues

## Tests Performed:

- tested ingame -> works
- 

## How to Test the Changes:

1. go to kara
2. fly up to the top 
3. go near the door and see it is unclickable

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Afaik you can select the door but it’s locked on retail, same as Aran

**Comment by elthehablo** [comment]
> Afaik you can select the door but it’s locked on retail, same as Aran

Source might be incorrect then. It does appear in the video that the door is unclickable. Preferably someone needs to go and check on retail/PTR

**Comment by Gultask** [comment]
Could be several things. Flags and state can change on script. Sometimes it depends on the faction in the addon

**Comment by elthehablo** [comment]
All the doors do seem to have the same dynamicflag in scripts: `[28] DynamicFlags: 4294901760`. Can these flags be deciphered?

**Comment by FrancescoBorzi** [comment]
status of this?

**Comment by FrancescoBorzi** [comment]
alright... so shall we close this? @elthehablo

**Comment by elthehablo** [comment]
> alright... so shall we close this? @elthehablo 

Yes better to

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
