### PR TITLE
Core/DB: Fix quest "Roll the Bones"

### LINKED ISSUE #185: [Quest] Roll the bones id 3882
**Description**: You can receive this quest from Spark Nilminer in Un'goro Crater. During this quest, you need to loot 8 Dinosaur bones from Diametradon, Elder diametradon Or Stegodon. You can loot these bones even from some skeletons on the ground.

**Current behaviour**: Diametradon, Elder Diametradon, Stegodon, Thunderstomp Stegodons seems to have low drop rate on this item. I killed 50 of them with no one of this items dropped.

**Expected behaviour**: The drop rate should be near 30% as shown here. This is the only source I could find: http://www.wowhead.com/item=11114/dinosaur-bone

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Branch(es)**: master

**AC hash/commit**:  https://github.com/azerothcore/azerothcore-wotlk/commit/8eb135e5456acebf44108f01bbee67fb07a4a317

**Operating system**:  Windows 8, 8.1, 10

**Modules**: Duel reset

**Other Customizations**: Crossfaction

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)
[//]: # (For fixes containing c++ create a Pull Request)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38593457-quest-roll-the-bones-id-3882?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Blumfield**
**Changes proposed:**

-  Fix loot chance of  Dinosaur Bone for the quest Roll the Bones

**Target branch(es):** 1.x/2.x etc.
master

**Issues addressed:** Closes #
This closes #185 

**Tests performed:** (Does it build, tested in-game, etc)
Tested in-game, works without problem

**Known issues and TODO list:**

- [ ] None

Intendation fixed by @talamortis and made a PR per @ShinDarth request

### CODE REVIEW

**Comment by HeartWell** [comment]
http://merlin.org.ua/wowhead2/?item=11114

**Comment by ShinDarth** [comment]
@HeartWell I don't speak russian. What do you mean with that link?

**Comment by Blumfield** [comment]
I don't speak russian either, he means the loot chance should 100% instead of 30% but is your link trustable @HeartWell ? could you provide english source too thanks

**Comment by HeartWell** [comment]
To change the language to English, I mean that the chance written 100%.

**Comment by Blumfield** [comment]
Okay so the only information i've got about it is that : 
Quest was first introduced in vanilla and has been modified 3 times, one in vanilla, one in tbc and finally one in cataclysm. see http://wowwiki.wikia.com/wiki/Quest:Roll_the_Bones_(original) and http://www.thottbot.com/quest=3882/roll-the-bones#comments:id=188274 this is where I got confused, blizzard removed the quest and re-added it back in cataclysm under a different quest id

anyway here is a pre-video of a guy doing this quest in vanilla https://youtu.be/1T7DXg88SgQ?list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&t=4586 you can see he didin't loot the bones so it can't be 100% chance ( if you keep watching you'll see he kill 2 - 3 mobs and still don't loot it ) and finally here's a video filmed on mop(not sure) https://youtu.be/VFPrhKjLw90?t=107 he kills 3 mobs and only loot one, I doubt blizzard changed the drop chance to 100% only in wotlk

**Comment by ShinDarth** [comment]
@HeartWell it looks like 30% is the best choice, but thanks anyway for your feedback
@Blumfield thanks for fix and explaination
@talamortis thanks for helping 
@thurin93 thanks for reporting the issue

MERGED

**Pull request merged**
