### PR TITLE
fix(Scripts/Temple of AhnQiraj): Aggro Drones.

### LINKED ISSUE #12716: [AQ40] Vekniss Soldier - Agro Drones (25152) has no effect
### Current Behaviour

Agro Drones (25152) has no effect

### Expected Blizzlike Behaviour

It should aggro all Vekniss Drones within a certain distance

### Source

_No response_

### Steps to reproduce the problem

`.go xyz -8199.47 1678 -31.4 531 6`
pull a Vekniss Soldier, see if a large amount of Vekniss Drones are pulled as well (larger than the standard call_for_help range)

### Extra Notes

Exact distance TBD, perhaps other cores have it scripted. If not I can try to figure it out in retail.

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/3771a7120d962bbe7cca70a1c1440b4acba440a5

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12716

## Issues Addressed:

- Closes #12716

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go xyz -8199.47 1678 -31.4 531 6`
pull a Vekniss Soldier, see if a large amount of Vekniss Drones are pulled as well (30y range)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
It works 👍

**Comment by Si1ker** [comment]
Is it possible to just add the code from the new file "temple_of_ahnqiraj.cpp" into the existing "instance_temple_of_ahnqiraj.cpp" ?

**Comment by Nefertumm** [comment]
instance_xxxx.cpp should only have instance related stuff and not scripts from creatures

**Comment by UltraNix** [comment]
@Nyeriah @IntelligentQuantum Please, merge it.

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
