### PR TITLE
fix(DB/Conditions): Grub should sell its items only to players who co…

### LINKED ISSUE #13613: Grub sells you things before he should.
https://github.com/chromiecraft/chromiecraft/issues/4338
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

Currently, [Grub](https://www.wowhead.com/wotlk/npc=3443) is willing to sell you Dig Rats and the recipe for Dig Rat Stew as a brand new character.

### Expected Blizzlike Behaviour

Grub should give you a [quest](https://www.wowhead.com/wotlk/quest=862) once you've learned Journeyman Cooking. Once you turn in the quest, then he will begin to sell you the things.

### Source

image

[Wowhead comments](https://www.wowhead.com/wotlk/quest=862/dig-rat-stew#comments) and Wrath Classic.

### Steps to reproduce the problem

.level 30
.go c id 3443

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b427e8e18cb6baa80124ce8e3a7e79aa670bcc74

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…mpleted "Dig Rat Stew" quest.

Fixes #13613

 

## Issues Addressed:

- Closes #13613
- Closes https://github.com/chromiecraft/chromiecraft/issues/4338

## Tests Performed:

- Not tested.

## How to Test the Changes:

Clear cache folder.
`.level 30`
`.go c id 3443`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Tested, [vendor menu](https://user-images.githubusercontent.com/38561765/201532238-b8ec5028-fbfa-4e34-a07e-9cf98e7868e6.png) appears with no items inside of it if cooking not known by player. If cooking is learned, a [gossip menu](https://user-images.githubusercontent.com/38561765/201532216-edc177ec-387c-4c14-9f91-9ed110e7935e.png) offering the quest and vendor menu appears. Once the quest is completed, the [vendor menu](https://user-images.githubusercontent.com/38561765/201532275-ee72503f-744a-4892-975f-45370e29f20a.png) is all that's available, now with items inside of it.

I do believe that blizzlike behavior is Grub not being interactable until the player knows cooking, in which case he'll offer the quest but no (empty) vendor menu. Otherwise, all seems working as expected.

**Comment by UltraNix** [comment]
@heyitsbench What cooking level is required?

**Comment by heyitsbench** [comment]
> @heyitsbench What cooking level is required?

Wowhead comments say 15, all I did was learn cooking and the aforementioned options became available to me.

**Comment by UltraNix** [comment]
@heyitsbench Clear cache folder and test it again.

**Comment by heyitsbench** [comment]
Not knowing cooking but being of level brings up his [text](https://user-images.githubusercontent.com/38561765/201536984-2383536b-aed2-4b64-93d7-f50840a88169.png), learning cooking (skill level 1) allows me to[pick up the Dig Rat Stew quest](https://user-images.githubusercontent.com/38561765/201537022-fd9fde0b-6f04-471c-96d9-1b85a86d66e5.png), completing this quest [allows the vendor menu to be pulled up](https://user-images.githubusercontent.com/38561765/201537059-870dfa07-ac17-4ed1-8d74-aef86c1e8301.png), where he will then [offer the dig rats and dig rat stew](https://user-images.githubusercontent.com/38561765/201537094-60054bfa-e11e-469d-a2d8-66c26d52449e.png).

Expected behavior is that he will not be interactable whatsoever without 15 cooking skill, where he will then offer the quest through that gossip menu.

**Comment by UltraNix** [comment]
@heyitsbench As a NPC he must be interactable

**Comment by heyitsbench** [comment]
> @heyitsbench As a NPC he must be interactable

https://user-images.githubusercontent.com/38561765/201537905-00a56533-6222-41ff-88a4-595f196a3776.mp4

This character does not know cooking. I cannot get the text menu from this NPC.

**Comment by UltraNix** [comment]
Ah okay.

**Comment by UltraNix** [comment]
@heyitsbench Try now.

**Comment by heyitsbench** [comment]
Giving this warning during worldserver startup: `Creature (Entry: 3443) has assigned gossip menu 10311, but npcflag does not include UNIT_NPC_FLAG_GOSSIP (1).` NPC is non-interactable without knowing cooking, as expected.
Quest shows up upon learning cooking, still doesn't need level 15 cooking. Upon completing the quest, nothing happened and he gave no vendor menu. A game client restart (likely a cache wipe too) is required for him to have his vendor menu available to me, with no gossip required.

**Comment by UltraNix** [comment]
@heyitsbench Should be okay now.

**Comment by heyitsbench** [comment]
Tested, works exactly as it should. 👍

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
