### PR TITLE
fix(Core/Warden): Fix buffer not being handled during interrupt.

### PR DESCRIPTION
**Pull request by AnchyDev**
## Changes Proposed:
I don't think the ByteBuffer is being correctly handled when you interrupt Warden with custom payloads.
Please test this change somebody!

## Issues Addressed:

- [Possible Related to this Issue](https://github.com/AnchyDev/BreakingNewsOverride/issues/7)

## Tests Performed:

[Same as here](https://github.com/azerothcore/azerothcore-wotlk/pull/14723)

## How to Test the Changes:

[Same as here](https://github.com/azerothcore/azerothcore-wotlk/pull/14723)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by AnchyDev** [comment]
I'd like to note this only affects server that use a module that sends custom Warden payloads. Server without these modules are unaffected.

**Comment by acidmanifesto** [comment]
Fix white space

**Review by acidmanifesto — APPROVED** [review]
Code review wise looks good. Would recommend someone testing if someone is able to replicate.

**Comment by AnchyDev** [comment]
I've exposed the _initialized bool in Warden.cpp to allow for modules to check Warden to ensure it has received the hash result successfully. This may also be an important fix for my module because it doesn't wait and malforms the payload.

**Pull request merged**
