### PR TITLE
fix(DB/Darkshore): allow Delmanis the Hated to engage in combat

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

~~Delmanis was being moved using SmartAI and corresponding waypoints in `waypoints`. I set the movement of Delmanis to passive wp movement with `waypoint_data`. This is because when Delmanis is ordered to move via SAI, he will not be able to be deterred from moving along his path. This makes it so that he does not attack any attacking player.~~ Delmanis now engages in combat

See old PR: https://github.com/azerothcore/azerothcore-wotlk/pull/10804

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16555
- Closes https://github.com/chromiecraft/chromiecraft/issues/5698

## SOURCE:

The changes have been validated through:

none needed

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. `.list creature 3662`
2. `.go creature <delmanisguid>`
3. observe him walking and being able to be pulled

## Known Issues and TODO List:

- [ ] wps might not be sniffed? (they seem to be sourced from TC)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
what about this script? 😢 
image

Also I had this problem as well many times. All you have to do is change ReactState to 2 (Agressive) here:
image

So uh... sorry you spent all this time doing this :P

**Comment by elthehablo** [comment]
> what about this script? 😢 
> image
> 
> Also I had this problem as well many times. All you have to do is change ReactState to 2 (Agressive) here:
> image
> 
> So uh... sorry you spent all this time doing this :P 

It wasn't a lot of time fortunately. I discarded the script because it didn't make a lot of sense to me and didn't seem sniffed looking at the PR (might have missed something). In general, I don't see the benefit of doing waypoints in SAI when it comes to general creature movement

**Comment by Gultask** [comment]
In general waypoints_data handles nothing more than patrols. Many creatures not only move, but also at some points do random movement, or scripts, randomized lines, etc. The number of which increases greatly in TBC and Wrath. SAI just allows us to have near complete control over movement in DB.

**Comment by Gultask** [comment]
In fact Nyeriah made it so that creatures can have separate combat and movement scripts, mainly on my request for this exact reason, this is why movement and RP in TBC dungeons are near perfect :p

**Comment by elthehablo** [comment]
> In fact Nyeriah made it so that creatures can have separate combat and movement scripts, mainly on my request for this exact reason, this is why movement and RP in TBC dungeons are near perfect :p 

Okay I wasn't aware of this. Then I am on-board. I will update the react state instead

**Review by Gultask — APPROVED** [review]

**Pull request merged**
