### PR TITLE
fix(Core/Gossip): Fix gossip menu for locale clients

### PR DESCRIPTION
**Pull request by patou01**
## Review questions:
- Is this the way we want to go? 
- What can this possibly break, I have no knowledge of the gossip and databases, I merely traced down where it seemed to not choose correctly.

## Changes Proposed:
-  If the string found in broadcast_text is empty, we look into the gossip_menu table instead. This should only be a fallback solution.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7209

## Tests Performed:

- Built on my pc, win10 x64. Seems to work.
- Tested on frFR, worked. Tested on enUS, didn't break. 

## How to Test the Changes:

1. Go to any npc which add this issue of text stacking, probably most if not all guards and talk to them.
2.
3.

## Known Issues and TODO List:

- [ ] Update broadcast_text_locale if possible/necessary so that the gossip_menu_option_locale is ignored. 
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by LukasVolgger** [comment]
Thx for the fix!

**Comment by patou01** [comment]
This is more of a fallback solution though. If we do indeed want to go for the "broadcast_text holds everything you ever need", then we need to come up with a way to complete that table.

If you're good with SQL, maybe you can try to have a look for something like "every entry in broadcast_text that doesn't have a match in broadcast_text_locale for language xX", as my understanding is that the IDs are shared, then we can estimate how much work it would be to update the db too.

**Comment by LukasVolgger** [comment]
The locales are still a big wip although I and others have already done a lot of work.  The locales will be implemented step by step in further PRs.  Unfortunately, there are also a lot of texts to translate myself, which makes the work difficult and I don't have time for it at the moment

**Comment by patou01** [comment]
Can you check if the texts are present in the gossip_menu_locale gossip? Else I'll look tonight, but I don't remember having seen ruRU locale anywhere 🤔

**Comment by LukasVolgger** [comment]
The locales are there @patou01

**Comment by SergeyBliznec** [comment]
> For ruRU locale don't work image

https://github.com/SergeyBliznec/azerothcore-rudb
My port ruRU texts from YTDB project. Everything works well for me.

**Comment by patou01** [comment]
@SergeyBliznec , I'm not sure I understand what you said.
Did you have the issue of text not appearing with the DB fix you linked, and then it got fixed once you applied this PR that changes the core to display the data?
Or does your DB fix fix it by itself?

**Comment by SergeyBliznec** [comment]
> @SergeyBliznec , I'm not sure I understand what you said. Did you have the issue of text not appearing with the DB fix you linked, and then it got fixed once you applied this PR that changes the core to display the data? Or does your DB fix fix it by itself?

If I use this PR on a standard world db, I get this:
woLocale
After apply my YTDB port locle:
woLocale
The decision from this PR helped me. If you do not apply it, the menu will have empty values.
PS, I'm sorry for my English) I don't speak well

**Comment by LukasVolgger** [comment]
Thx @patou01 for this PR and @SergeyBliznec for Testing!

**Comment by 0356738481** [comment]
8396

**Pull request merged**
