### PR TITLE
fix(Core/Creatures): Critters should start fleeing upon entering comb…

### LINKED ISSUE #14218: Demoralizing/Challenging Roar does not affect critters.
Original report: https://github.com/chromiecraft/chromiecraft/issues/4543
**Current Behaviour**
Currently critters (such as [sheep](https://www.wowhead.com/wotlk/npc=1933), [rabbit](https://www.wowhead.com/wotlk/npc=721), or [deer](https://www.wowhead.com/wotlk/npc=883)) will have the aura applied from [demoralizing](https://www.wowhead.com/wotlk/npc=99)/[challenging](https://www.wowhead.com/wotlk/npc=5209) roar.

**Expected Blizzlike Behaviour**
These critters (perhaps all critters, might be some exceptions, not sure) should have the aura applied from the roar, but also run away from the caster.

**Source**
Wrath Classic Live/PTR.

**Steps to reproduce the proble**m
`.learn 5487`,` .learn 99`/`.learn 5209`, `.learn 5229`
`.tele stormwind`
Leave Stormwind through the southeast gates and go to the critters in the area surrounding area.
Either cast enrage or use .modify rage (sufficiently high number)
Cast roar of your choice while in range of critters.
Observe the issue.

**AC rev. hash/commit**
https://github.com/chromiecraft/azerothcore-wotlk/commit/c29927b8e9aaf03429e04c7a751be8337b56879d

### PR DESCRIPTION
**Pull request by UltraNix**
…at rather than taking damage.

Cleaned up fleeing code.
Original source: TrinityCore.
Fixes #14218

## Issues Addressed:

- Closes #14218
- Closes https://github.com/chromiecraft/chromiecraft/issues/4543

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.learn 5487`, `.learn 99`/`.learn 5209`, `.learn 5229`
`.tele stormwind`
Leave Stormwind through the southeast gates and go to the critters in the area surrounding area.
Either cast enrage or use .modify rage (sufficiently high number)
Cast roar of your choice while in range of critters.
Observe the issue.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Tested with the creatures and spells mentioned in the original report as well as taunt. The critters do not have their movement path interrupted if they are in the process of moving to a point when they enter combat, which I don't believe is accurate. Otherwise, works very well.

Also, if the source is coming from another core (i.e. TC) would this not be a co-author/cherrypick situation?

**Comment by UltraNix** [comment]
@heyitsbench I'm not sure I understand what are you talking anout.

**Comment by heyitsbench** [comment]
> I'm not sure I understand what are you talking anout.

Forgive the crude drawing, but [this is the behavior I'm observing](https://user-images.githubusercontent.com/38561765/208307101-f44afe31-06d1-4cbc-bac7-39ac1de7dbf8.png). On Classic the movement path gets cut off right when the creature enters combat and they flee, whereas with this PR the creature continues its movement and then flees.

If you meant about the TC source, from what I've seen of other AC PRs that use a TC commit (like [this one](https://github.com/azerothcore/azerothcore-wotlk/pull/13638)), they mention a co-author or a cherrypicked commit or something like that.

**Comment by UltraNix** [comment]
`Forgive the crude drawing, but [this is the behavior I'm observing](https://user-images.githubusercontent.com/38561765/208307101-f44afe31-06d1-4cbc-bac7-39ac1de7dbf8.png). On Classic the movement path gets cut off right when the creature enters combat and they flee, whereas with this PR the creature continues its movement and then flees.`
Fixed

`If you meant about the TC source, from what I've seen of other AC PRs that use a TC commit (like https://github.com/azerothcore/azerothcore-wotlk/pull/13638), they mention a co-author or a cherrypicked commit or something like that.`
Their code is modified as it was not working.

**Comment by heyitsbench** [comment]
Tested. Working as it should. 👍

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
