### PR TITLE
fix(Scripts/ZulFarrak): Moved Sergeant Bly's script from DB to C++. S…

### LINKED ISSUE #6423: Zul'Farrak Stairs Event Phased Poorly
**CURRENT BEHAVIOUR:**

WoWScrnShot_061821_203813

The first wave spawns and stands still until you pull them. Then after they die, an amount of time is waited, and the second wave spawns and stands still until you pull them. We stood around for like 45 seconds between phase 1 and 2 with nothing to do. 

**EXPECTED BLIZZLIKE BEHAVIOUR:**

https://www.youtube.com/watch?v=mtBuWdd2EHk

They should charged the stairs/pyramid and it should be super cool. No delays, no phasing issues, no weird standing still.

https://classic.wowhead.com/guides/zulfarrak-classic-dungeon-strategy

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Play the Zul'farrak Stairs Event
2. Compare to videos
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**

AzerothCore rev. 34da0cda5195 2021-06-15 12:02:03 

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99328308-zul-farrak-stairs-event-phased-poorly?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6696: [Dungeon] Zul Farrak - Sometimes Seargent Bly gets reset after first wave/or doesnt leave the cage at all [$25]
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Sergeant Bly  (https://wotlk.evowow.com/?npc=7604) is sometimes refusing to leave the cage, or "gets reset" qand runs back tot the cage after 1st wave of mobs dies.
Seems something is breaking the script, doesnt happen every time tho, sometimes it works fine.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Seargent Bly should leave the cage when cages are unlocked and stay out of the cage so players can interact with him to progress the dungeon.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Do Zul Farrak dungeon up to the Cages part.
2. Unlock the cages and see if the script works correctly

##### EXTRA NOTES:

https://github.com/chromiecraft/chromiecraft/issues/1066

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
There is a **[$25 open bounty](https://www.bountysource.com/issues/99646237-dungeon-zul-farrak-sometimes-seargent-bly-gets-reset-after-first-wave-or-doesnt-leave-the-cage-at-all?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6700: Sergent Bly in Zul Farrak has double chat options
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1069

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After rescuing Sergeant Bly from and clearing the mobs, when talking to Sergeant Bly to start his encounter he has two options.
SeargeantBly

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should only be 1 option when talking to him

##### SOURCE:

https://blizzardwatch.com/gallery/zulfarrak?slide_pos=9

##### STEPS TO REPRODUCE THE PROBLEM:

1. GO to Zul Farrak and do the dungeons up to the point where you have to fight Sergeant Bly
2. Talk to him and notice he has two conversation options

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99646234-sergent-bly-in-zul-farrak-has-double-chat-options?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…ource: TrinityCore

Fixes #6696

## Issues Addressed:

- Closes #6423
- Closes #6696
- Closes #6700
- Closes https://github.com/chromiecraft/chromiecraft/issues/1066
- Closes https://github.com/chromiecraft/chromiecraft/issues/1069
- Supersedes #5952
- Supersedes #6723

## Tests Performed:

- Tested ingame, but only mechanics.

## How to Test the Changes:

1. Do Zul Farrak dungeon up to the Cages part.
2. Unlock the cages and see if the script works correctly

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by syssneck** [comment]
Is this ready to be tested now?

**Comment by UltraNix** [comment]
Yes.

**Comment by syssneck** [comment]
Ok, tested:

- [X] Sergeant Bly and his crew now reliably move down the steps, no matter how fast I kill the adds
- [X] They always leave the cages (but I also didn't have this problem before)
- [ ] Downstairs, I can aggro Sergeant Bly without the others helping him (here only Raven helped him, but only because I walked too close to her):
grafik
- [ ] I can aggro Sergeant Bly, before asking the goblin, to open the door (I'm not 100% sure, but I think it should only be possible, to engage Sergeant Bly in a fight, after I talked to the goblin)
- [ ] Engaging Sergeant Bly, before talking to the goblin, breaks the event. After that, the goblin only says this:
grafik
I cleared all the trolls in Zul'Farrak, but I can't get him to open the door.

**Comment by syssneck** [comment]
- [ ] Engaging Sergeant Bly, before talking to the goblin, breaks the event. After that, the goblin only says this:
grafik

I cleared all the trolls in Zul'Farrak, but I can't get him to open the door.

**Comment by UltraNix** [comment]
@syssneck Test it again please.

**Comment by syssneck** [comment]
Okay, I tested it again:
- I still got stuck with the goblin (sometimes) not offering to open the door on my second try (first one went well). In this second try, I let the NPCs engage on the bosses and I let them fight for a while, before I helped them
- Nekrum Gutchewer and Shadowpriest Sezz'ziz shouldn't roam, they should just stand still in this position here:
https://youtu.be/HAq1RPVWfLk?t=478
- They should also spawn the adds, when they are attacked, but here the adds are already there (see that they spawn the adds in the video).
- Sergeant Bly and the others are sometimes facing the wrong direction (downstairs):
grafik

- They are facing the wrong direction (upstairs):
grafik

**Comment by UltraNix** [comment]
```
They should also spawn the adds, when they are attacked, but here the adds are already there (see that they spawn the adds in the video).
```
Looks like they've changed something in that encounter.
https://youtu.be/EYxKVVt8Fy4?t=1451 - no adds

**Comment by syssneck** [comment]
@UltraNix They also spawn adds in this video. There is only one add standing in front of Nekrum Gutchewer and Shadowpriest Sezz'ziz when they engage them (probably still standing from the second wave).

At 24:24: Two adds appear on the right side and attack (one melee, one caster)
At 24:34 another two adds spawn on the left side (this time two casters)
At 24:46 another three adds spawn (one melee on the right, two casters on the left)

**Comment by UltraNix** [comment]
@syssneck Please test. These adds NYI.

**Comment by syssneck** [comment]
Okay, tested three times, worked each time. I didn't manage to break the event, but there are still some things off (not counting the add spawn):
- I can still talk to the goblin & Sergeant Bly when they are moving, making them stop instantly, without continuing afterwards:

https://user-images.githubusercontent.com/68868567/133745340-af074347-1bf2-48c3-b22d-14aa5f87482b.mp4

This is probably the biggest remaining issue, as Sergeant Bly will not help in the fight.
Same thing after the second wave, when they move down. I can stop him again by speaking to him (so that he remains upstairs):

https://user-images.githubusercontent.com/68868567/133745976-3a0a90e9-1064-4f0f-82cf-48a45639f137.mp4

**Comment by syssneck** [comment]
Small remaining issues with the goblin:
- he bugs out before despawning, spamming his: "I'm out of here!" message repeatedly
- Minor thing: He runs over the heap of skulls

https://user-images.githubusercontent.com/68868567/133746345-dbe3a4cd-e8df-4b3a-bb94-41677f5010a2.mp4

**Comment by syssneck** [comment]
Nekrum Gutchewer and Shadowpriest Sezz'ziz  position a bit off and facing the wrong direction:
grafik

**Comment by UltraNix** [comment]
@syssneck Need another test.

**Comment by syssneck** [comment]
Okay, tested:
- some repercussion I guess, but I can't talk to Sergeant Bly anymore after the goblin blew up the door:
grafik

(I believe the dialog option was available, when the goblin was still on his way, but disappeared, after the goblin despawned)

- Sergeant Bly and his crew are not engaging the troll bosses on their own (they're just standing and waiting downstairs). They are also not helping the player(s), when the player(s) decide to engage them out of their aggro range:
grafik

**Comment by UltraNix** [comment]
```
Sergeant Bly and his crew are not engaging the troll bosses on their own (they're just standing and waiting downstairs). They are also not helping the player(s), when the player(s) decide to engage them out of their aggro range:
```
Because you are too far away.

**Comment by syssneck** [comment]
Yes, but they should go on the trolls themselves, watch here: https://youtu.be/HAq1RPVWfLk?t=475

**Comment by UltraNix** [comment]
Another test please :)

**Comment by syssneck** [comment]
Okay, they engage the troll bosses now on their own and I can talk to Bly after the goblin blew up the door, but the option is spammable now:

https://user-images.githubusercontent.com/68868567/133894289-be863a05-5492-40d7-af21-00f5d4c0b79a.mp4

- One little thing I noticed, I don't see Bly saying: "Let's move forward!" and the goblin say: "I'm out of here!", if I'm not relatively close to them (I don't see it in the chat). I guess there is nothing we can do about it, is there?

- I'm not sure if this is important, but I get this warning in the world console:
SMART_ACTION_SET_COUNTER

- Do you want to implement the add spawn or merge it this way? 

We are almost there! Thank you for your patience! :D

**Comment by UltraNix** [comment]
Add spawn? I already implemented that add spawning by boss.

**Comment by syssneck** [comment]
Yes, the adds spawn with the boss, but they should spawn during the boss fight. I guess it's okay the way it is now.
Should I test one last time with this change?

**Comment by UltraNix** [comment]
Yes.

**Comment by syssneck** [comment]
Alright, thank you! We are good to go from my side.

**Comment by Si1ker** [comment]
```txt
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp: In member function ‘virtual void npc_shadowpriest_sezziz::npc_shadowpriest_sezzizAI::UpdateAI(uint32)’:
src/server/scripts/CMakeFiles/scripts.dir/build.make:3687: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/ZulFarrak/zulfarrak.cpp.o' failed
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/scripts/Kalimdor/ZulFarrak/zulfarrak.cpp:595:24: error: ‘MostHPMissingInRange’ is not a member of ‘Acore’
                 Acore::MostHPMissingInRange u_check(me, 40.f, 1500);
                        ^~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/Kalimdor/ZulFarrak/zulfarrak.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
CMakeFiles/Makefile2:1398: recipe for target 'src/server/scripts/CMakeFiles/scripts.dir/all' failed
make: *** [all] Error 2
Makefile:145: recipe for target 'all' failed
```

**Comment by UltraNix** [comment]
@Si1ker I always build before pushing.

**Comment by Si1ker** [comment]
@UltraNix & @syssneck all ready?

**Comment by UltraNix** [comment]
Yep.

**Comment by syssneck** [comment]
Yes, ty!

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
