### PR TITLE
fix (Core/Quest) Correct link quest and fix command lookup quest for …

### LINKED ISSUE #3247: You cannot link the quest to the chat
##### CURRENT BEHAVIOUR:

You cannot link the quest to any chat, there is a Russian client and there are 2 DBC languages on the server (English basic and Russian) have you worth 3 in this place: ChatStrictLinkChecking.Severity = 3
Used to work.
If you put 1 then it works.

#3002 most likely this is after this commit

##### STEPS TO REPRODUCE THE PROBLEM:

1. put in the config ChatStrictLinkChecking.Severity = 3
2. link any quest in the game if you have DBC English basis and Russian client
##### AC HASH/COMMIT:

[4e76485](https://github.com/azerothcore/azerothcore-wotlk/commit/4e7648503795e9bb9a4945f8a7a454fd2326d6f1)

##### OPERATING SYSTEM:

Ubuntu 18
##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/92225120-you-cannot-link-the-quest-to-the-chat?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by r0m1ntik94**
## CHANGES PROPOSED:
- Fix issues #3247 

## ISSUES ADDRESSED:
- Closes #3247 

## TESTS PERFORMED:
- Tested on ubuntu 18.04

## HOW TO TEST THE CHANGES:
Update source code and (link quest in game or use command .lookup quest)

 **[WAITING TO BE TESTED]**

### CODE REVIEW

**Comment by Tyrelis** [comment]
I have tested this using enUS client and I was not able to link the quest through chat using .lookup quest after enabling ChatStrictLinkChecking.Severity = 3 in the config. After I have applied the fix from the PR it did not fix the issue I got quest not found error. If were to click quest in chat though it works fine even before pr.

**Comment by r0m1ntik94** [comment]
@Tyrelis 
Capture d’écran 2020-08-10 à 13 12 38
Capture d’écran 2020-08-10 à 13 13 03

**Comment by Tyrelis** [comment]
> @Tyrelis
> Capture d’écran 2020-08-10 à 13 12 38
> Capture d’écran 2020-08-10 à 13 13 03
This confirms the fix works for russian client but no english.

**Comment by Tyrelis** [comment]
> @Tyrelis
> Capture d’écran 2020-08-10 à 13 12 38
> Capture d’écran 2020-08-10 à 13 13 03

If you manually type it. It works but if shift left click on it then it doesn't perhaps I misunderstood what you wanted tested sorry.

**Comment by r0m1ntik94** [comment]
@Tyrelis Please write a video, but I don't really understand what does not work for you.
Does your server have a multi-language DBC? if so, what languages do you have there and what is the client's language?

**Comment by Tyrelis** [comment]
> @Tyrelis Please write a video, but I don't really understand what does not work for you.
> Does your server have a multi-language DBC? if so, what languages do you have there and what is the client's language?

I am saying the pr works it your typing the

> @Tyrelis Please write a video, but I don't really understand what does not work for you.
> Does your server have a multi-language DBC? if so, what languages do you have there and what is the client's language?

Please read above..

**Comment by Helias** [comment]
@felwyn from your side this PR works, but apparently it doesn't in the environment of @Tyrelis, right?

We need to be sure that this PR works before put it as `To Be Merge`

**Comment by Tyrelis** [comment]
> @felwyn from your side this PR works, but apparently it doesn't in the environment of @Tyrelis, right?
> 
> We need to be sure that this PR works before put it as `To Be Merge`

It works I just tested it wrong.

**Review by Helias — APPROVED** [review]

**Pull request merged**
