### PR TITLE
fix(DB/translation): some Chinese translation

### PR DESCRIPTION
**Pull request by mpfans**
## Changes Proposed:
* update Wintergrasp battle announce
* object
* item

## Tests Performed:

- tested ingame

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — CHANGES_REQUESTED** [review]
Remove quotes around ints

**Review by Nefertumm — APPROVED** [review]

**Comment by Kitzunu** [comment]
Verifiedbuild is int, remove quotes

**Comment by mpfans** [comment]
image
I don't see quotation marks

**Comment by benjymansy123** [comment]
image
Here as well.

**Comment by mpfans** [comment]
> image Here as well.

ty

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
