### PR TITLE
fix(Creature/Model) Model probability change

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

This pull request aims to modify the probability that the NPC adopts model 20570 over the other model that it has defined. For some reason, the NPC has 2 models within the table. And the probability is the same in both cases, so sometimes it chooses one form or the other. However, that specific model is usually present in NPCs that are dummy, to which some effect or script is usually applied, which the player does not usually perceive.

## Issues Addressed:

- Closes 

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. After applying this change, the NPCs involved, although they have 2 models in the table, should take as priority the other one they have defined and not this one.
2. Currently, what is happening is that they are taking either of the two, and while that information can be obtained by consulting the sources, it should not take the form of the devil.

WoWScrnShot_092724_160143

WoWScrnShot_092724_153539

WoWScrnShot_092724_153828

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
Ok, then I'll review that topic and this one too.
```
Creature (Entry: 23046) has zero total chance for all models in creature_template_model.
Creature (Entry: 23058) has zero total chance for all models in creature_template_model.
Creature (Entry: 23322) has zero total chance for all models in creature_template_model.
Creature (Entry: 23327) has zero total chance for all models in creature_template_model.
Creature (Entry: 37094) has zero total chance for all models in creature_template_model.
Creature (Entry: 37158) has zero total chance for all models in creature_template_model.
Creature (Entry: 37704) has zero total chance for all models in creature_template_model.
Creature (Entry: 37746) has zero total chance for all models in creature_template_model.
Creature (Entry: 38340) has zero total chance for all models in creature_template_model.
Creature (Entry: 38341) has zero total chance for all models in creature_template_model.
Creature (Entry: 38342) has zero total chance for all models in creature_template_model.
```

**Comment by heyitsbench** [comment]
These are the official probabilities bruteforced from 51831: https://gist.github.com/heyitsbench/40f7d6fb8f3a355acc0643d7dadf3cb3

**Comment by pangolp** [comment]
> These are the official probabilities bruteforced from 51831: https://gist.github.com/heyitsbench/40f7d6fb8f3a355acc0643d7dadf3cb3

Does that mean they have to be visible? I've been playing on private servers since 2014, and I've never seen those NPCs in the world, except when the GM activates me, and because they usually have some script or effect assigned to them. But that way, I never saw them, now, if I changed something, I don't know.

**Comment by heyitsbench** [comment]
I know from my own research that the creatures on the Isle of Quel'Danas do not have their models assigned from that table but rather by a transform spell. I see a *lot* of changed creature model data in this PR and I don't know what all is being touched, thus I only provided the official data on what has been bruteforced that this PR aims to correct so that it can be changed accordingly.

**Comment by pangolp** [comment]
> I know from my own research that the creatures on the Isle of Quel'Danas do not have their models assigned from that table but rather by a transform spell. I see a _lot_ of changed creature model data in this PR and I don't know what all is being touched, thus I only provided the official data on what has been bruteforced that this PR aims to correct so that it can be changed accordingly.

I'm modifying the probability of that model being chosen over the other. That's all. Each creature, for some reason, has 2 models. And what I'm doing is preventing the 20570 from being chosen over the other model. That's why the emulator gave me an error a moment ago, because there were creatures that only had 1 model, and if the probability is zero, then that means that it wasn't going to choose any. That's what this pull request is trying to achieve. To choose the other model, instead of choosing 20570.

**Comment by heyitsbench** [comment]
To clarify, the current data AC has is almost certainly incorrect, I'm not disagreeing with that, but I am saying that what this PR aims to replace it with likely also isn't fully correct. I'm suggesting you take the values from the bruteforce that I've linked and include them in your PR (and replace the VerifiedBuild column to match).

**Comment by pangolp** [comment]
> To clarify, the current data AC has is almost certainly incorrect, I'm not disagreeing with that, but I am saying that what this PR aims to replace it with likely also isn't fully correct. I'm suggesting you take the values from the bruteforce that I've linked and include them in your PR (and replace the VerifiedBuild column to match).

But you gave me 173 models, and I am modifying more than 500. As for changing the `VerifiedBuild`, there is no problem, in fact, I don't even know what that attribute is specifically used for. It must be the version from which the data is obtained, I put it at 12340, because it is the build that we are supposed to be using for the 3.3.5a client, but if it needs to be changed, it is changed. However, I am missing data.

**Comment by heyitsbench** [comment]
> But you gave me 173 records, and I am modifying more than 500.

Most of the creatures you are modifying don't exist in the bruteforce nor in a stock AC DB. Some of them *may* be difficulty entries, in which case you can just reuse the data from the base creature.

> It must be the version from which the data is obtained, I put it at 12340, because it is the build that we are supposed to be using for the 3.3.5a client

Yes, but the specific numbers you provided did not come from a 12340 client or any other client, so you should be using a value of 0 for VerifiedBuild.

> but if it needs to be changed, it is changed. However, I am missing data.

That's why I provided the bruteforced data from Wrath Classic.

**Comment by pangolp** [comment]
> > But you gave me 173 records, and I am modifying more than 500.
> 
> Most of the creatures you are modifying don't exist in the bruteforce nor in a stock AC DB. Some of them _may_ be difficulty entries, in which case you can just reuse the data from the base creature.
> 
> > It must be the version from which the data is obtained, I put it at 12340, because it is the build that we are supposed to be using for the 3.3.5a client
> 
> Yes, but the specific numbers you provided did not come from a 12340 client or any other client, so you should be using a value of 0 for VerifiedBuild.
> 
> > but if it needs to be changed, it is changed. However, I am missing data.
> 
> That's why I provided the bruteforced data from Wrath Classic.

Let's see if I understand. What you suggest to me is that instead of doing an update, what we do is insert those values ​​that you gave me? What I don't quite understand is that in that case, I would be missing records. It may be that within AC, there are records that are wrong, however, I would apply this solution and then review each of the missing npc in more detail. Because I am applying an update to more than 500 records, and in your code, I only have 173, which if I divide it by 2, because the majority are 2 models per npc, I only get 86 modified npc.

**Comment by heyitsbench** [comment]
> Because I am applying an update to more than 500 records

But you aren't. Doing a SELECT query for every single record in that table with a CreatureID being touched at all in your PR yields only 159 rows on my local database, less even than the bruteforced records. E.g. every CreatureID greater than 40363 in your query simply does not exist in a stock AC database.

**Comment by heyitsbench** [comment]
https://gist.github.com/heyitsbench/7423e231531dbbb41bbcf83af082dd31

Here's a DELETE/INSERT replacement of the existing data with officially sourced values with none of the nonexistent creature IDs.

**Comment by pangolp** [comment]
```
2 queries executed, 2 success, 0 errors, 0 warnings

Query: DELETE FROM `creature_template_model` WHERE `CreatureID` IN (21876, 22986, 23040, 23046, 23058, 23322, 23327, 23583, 23751, 2375...

172 row(s) affected

Execution Time : 0.003 sec
Transfer Time  : 0.003 sec
Total Time     : 0.007 sec
-----------------------------------------------------------

Query: INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)...

172 row(s) affected

Execution Time : 0.003 sec
Transfer Time  : 0 sec
Total Time     : 0.003 sec
```

**Review by heyitsbench — APPROVED** [review]

**Comment by heyitsbench** [comment]
Sorry for all the headache. 😛

**Comment by pangolp** [comment]
> Sorry for all the headache. 😛

The important thing is that the problem is solved. The method, you can change. I work publicly, to learn from others, I have no problem making changes.

**Comment by heyitsbench** [comment]
For the record, a PR that affects only the `creature_template_model` table really doesn't need testing, just needs no errors to occur in the CI, especially since I will probably be double checking every one of them to ensure they match sniffed data or at least don't mess up existing data (if I don't fix most of it myself eventually anyway).

**Review by Nyeriah — APPROVED** [review]

**Comment by pangolp** [comment]
@heyitsbench @Nyeriah @sudlud @Helias Thanks.

**Pull request merged**
