### PR TITLE
fix(DB/Assembler): Remove file that fails the updater

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Delete a file that is making the assembler fail
- @Helias could you look over it and see why this file is failing? Perhaps too big? https://github.com/azerothcore/azerothcore-wotlk/pull/4088

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Helias** [comment]
Everything works in my machine
Anyone is encountering any errors updating the db?

**Comment by Kitzunu** [comment]
It is very weird the build is failing on ERROR: [1146] Table 'acore_world.cinematiccamera_dbc' doesn't exist

**Comment by yuanf225** [comment]
5F542EFB-831D-48CF-AD43-6B6ECF834EE0 The assembled world update sql application reports an error

**Comment by FrancescoBorzi** [comment]
maybe the DB squash will solve the issue WITHOUT being forced to remove this file.

@Kitzunu let me do it as soon as I have some time and let's see if it solves the problem

**Pull request closed without merging**
