### PR TITLE
fix(DB/Creature): Mr. Smite Aggro

### PR DESCRIPTION
**Pull request by wizzymore**
## Changes Proposed:
-  Fix Mr. Smite aggro additional mobs by moving the near creatures further away. The distance is about 1-2 yards adjustment

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/1444
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7381

## Tests Performed:

- Aggroed Mr. Smite by attacking the rogues at the start of the bridge and also reset the boss with those mobs killed and aggroed by attacking him first, he didn't aggro in both cases.

## How to Test the Changes:

1. .tele deadmines
2. .go xyz 3.472 -755.362 9.175
3. Aggro smite by aggroing one hidden rogue near the bridge

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by syssneck** [comment]
Tested, works just fine! And the position change is minimal.

**Comment by FrancescoBorzi** [comment]
good job @wizzymore and @syssneck but I have the same remark as: 

https://github.com/azerothcore/azerothcore-wotlk/pull/7373#issuecomment-899566023

it's ok for this too, but for future PRs please follow the workflow so we don't make this place too messy ;)

**Comment by syssneck** [comment]
I created an AC issue for easier future reference: https://github.com/azerothcore/azerothcore-wotlk/issues/7381
Please close this one as well, when this will be merged, ty!

**Comment by FrancescoBorzi** [comment]
> I still created an AC issue for easier future reference: #7381

ok then there is no need to keep the project for this PR

**Pull request merged**
