### PR TITLE
fix(Scripts/Misc): Fix bosses not reseting after the despawn update

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
@Tony931023 please test halion and lk reset with this

**Review by Gultask — APPROVED** [review]

**Comment by Tony931023** [comment]
@Nyeriah 

Halion: No longer shows the 3rd phase corporatability in the 1st, this and it **works fine**

LK: only resets columns 3 of 4, Tirion is still frozen does not reset, if you die with ice spheres from the intermediate phases, when you re-enter they are present
WoWScrnShot_032023_215331

**Comment by Tony931023** [comment]
LK: when it casts Reap Soul after channeling he does not transfer his soul into Frostmourne.

**Comment by Nyeriah** [comment]
I've fixed tirion getting stuck, I am not getting the sphres not reseting anymore... odd

**Comment by Tony931023** [comment]
> I've fixed tirion getting stuck, I am not getting the sphres not reseting anymore... odd

I tried now and the spheres no longer get stuck, the columns come out fine now, only Reap Soul remains,

https://user-images.githubusercontent.com/4868094/226514530-7e12f36d-036e-4bc9-bb7b-919678f02c3b.mp4

**Comment by Nyeriah** [comment]
Ty for testing 👍

**Comment by Nyeriah** [comment]
Thanks for the headsup 👍

**Pull request merged**
