### PR TITLE
fix(Core/Spell): Make use of SPELL_ATTR2_NO_SCHOOL_IMMUNITIES

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  SPELL_ATTR2_UNAFFECTED_BY_AURA_SCHOOL_IMMUNE  was not used before
-  Looked at where TC use it
- Add some null checks to prevent possible crashes

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4306

## Tests Performed:

- none 

## How to Test the Changes:

1. Check that these spells pass through mobs that are usually immune to the school

<details><summary>Affected Spells</summary> 

dbc_spell
---
```sql
SELECT `ID`, `name_lang_1`, `AttributesEx2`
FROM `dbc_spell` 
WHERE `AttributesEx2` & @flag = @flag
```
| ID | name_lang_1 | AttributesEx2 | 
| ---: | --- | ---: | 
| 5 | Death Touch | 67108868 | 
| 265 | Area Death (TEST) | 336084997 | 
| 355 | Taunt | 67108864 | 
| 781 | Disengage | 67108864 | 
| 1161 | Challenging Shout | 67108864 | 
| 1515 | Tame Beast | 67175424 | 
| 1742 | Cower | 67108864 | 
| 1753 | Cower | 67108864 | 
| 1754 | Cower | 67108864 | 
| 1755 | Cower | 67108864 | 
| 1756 | Cower | 67108864 | 
| 2400 | Transfer Power | 67108868 | 
| 2649 | Growl | 67108864 | 
| 3716 | Torment | 67108864 | 
| 4020 | Safirdrang's Chill | 67108868 | 
| 4293 | MOTI, Redux: Hourglass of Eternity Dies - Quest Fails | 67125249 | 
| 4294 | The Life-Binding | 67108868 | 
| 4330 | MOTI, Redux: Hourglass of Eternity Dies | 67108869 | 
| 4342 | Explodo-Rockets | 67108864 | 
| 5209 | Challenging Roar | 67108864 | 
| 5432 | Mind Trick: Chains - Torso Blood Back | 67108868 | 
| 5509 | Bringing Down Heb'Jin: Beating on Heb'Jin's Drum - Object | 67108868 | 
| 5513 | Orb of Illusion | 67108928 | 
| 5545 | The Life-Binding | 67108868 | 
| 5729 | Stoneclaw Totem Effect | 335544320 | 
| 6360 | Soothing Kiss | 67108864 | 
| 6393 | Stoneclaw Totem Effect | 335544320 | 
| 6394 | Stoneclaw Totem Effect | 335544320 | 
| 6395 | Stoneclaw Totem Effect | 335544320 | 
| 6509 | Gore Bladder | 67108933 | 
| 6795 | Growl | 67108864 | 
| 6967 | Sky Terror: Dummy to Gargoyle Target 01 | 67108868 | 
| 7439 | The Art of Being a Water Terror: Water Terror Aura | 67108868 | 
| 7769 | Strafe Jotunheim Building | 67108864 | 
| 7809 | Torment | 67108864 | 
| 7810 | Torment | 67108864 | 
| 7811 | Torment | 67108864 | 
| 7813 | Soothing Kiss | 67108864 | 
| 7853 | The Art of Being a Water Terror: Force Cast on Player | 67108868 | 
| 8998 | Cower | 67108864 | 
| 9000 | Cower | 67108864 | 
| 9892 | Cower | 67108864 | 
| 10423 | Stoneclaw Totem Effect | 335544320 | 
| 10424 | Stoneclaw Totem Effect | 335544320 | 
| 10727 | Uzo's Ritual of Blood | 67108868 | 
| 11774 | Torment | 67108864 | 
| 11775 | Torment | 67108864 | 
| 11784 | Soothing Kiss | 67108864 | 
| 11785 | Soothing Kiss | 67108864 | 
| 13481 | Tame Beast | 67108864 | 
| 14916 | Growl | 67108864 | 
| 14917 | Growl | 67108864 | 
| 14918 | Growl | 67108864 | 
| 14919 | Growl | 67108864 | 
| 14920 | Growl | 67108864 | 
| 14921 | Growl | 67108864 | 
| 16697 | Cower | 67108864 | 
| 17735 | Suffering | 67108864 | 
| 17750 | Suffering | 67108864 | 
| 17751 | Suffering | 67108864 | 
| 17752 | Suffering | 67108864 | 
| 18761 | Swallow Soul | 67108868 | 
| 18826 | Savior's Sacrifice | 67108864 | 
| 19548 | Tame Ice Claw Bear | 67175424 | 
| 19674 | Tame Large Crag Boar | 67175424 | 
| 19687 | Tame Snow Leopard | 67175424 | 
| 19688 | Tame Adult Plainstrider | 67175424 | 
| 19689 | Tame Prairie Stalker | 67175424 | 
| 19692 | Tame Swoop | 67175424 | 
| 19693 | Tame Webwood Lurker | 67175424 | 
| 19694 | Tame Dire Mottled Boar | 67175424 | 
| 19696 | Tame Surf Crawler | 67175424 | 
| 19697 | Tame Armored Scorpid | 67175424 | 
| 19699 | Tame Nightsaber Stalker | 67175424 | 
| 19700 | Tame Strigid Screecher | 67175424 | 
| 19901 | dmg7 | 603979776 | 
| 20211 | Lord-Commander's Nullifier | 67108928 | 
| 21855 | Challenge Flag | 67108864 | 
| 22966 | Soul Coax | 67108869 | 
| 23356 | Taming Lesson | 67175424 | 
| 25512 | Stoneclaw Totem Effect | 335544320 | 
| 25729 | Find the Ancient Hero: Kill Credit | 67108869 | 
| 25732 | Through the Eye: Eye of the Lich King | 67108868 | 
| 25745 | Possession | 67108868 | 
| 25781 | Righteous Fury | 603979780 | 
| 26281 | Taunt | 67108864 | 
| 26385 | You'll Need a Gryphon: Uzo's Ritual of Blood Triggered Transform | 67108868 | 
| 26560 | Summon Arete's Gate | 67108869 | 
| 27004 | Cower | 67108864 | 
| 27047 | Growl | 67108864 | 
| 27048 | Cower | 67108864 | 
| 27254 | dmg8 | 603979776 | 
| 27255 | dmg9 | 603979776 | 
| 27258 | dmg10 | 603979776 | 
| 27261 | dmg11 | 603979776 | 
| 27270 | Torment | 67108864 | 
| 27271 | Suffering | 67108864 | 
| 27275 | Soothing Kiss | 67108864 | 
| 27765 | Soul Wrack | 67108868 | 
| 27769 | Whisper Gulch: Yogg-Saron Whisper | 335560704 | 
| 29060 | Taunt | 67108864 | 
| 29070 | Sovereign Rod | 67108865 | 
| 29071 | Sovereign Rod | 67108865 | 
| 29072 | Whisper Gulch: Yogg-Saron Whisper Dummy | 335560708 | 
| 29142 | Eyesore Blaster | 603979780 | 
| 29880 | Mana Shield | 67108864 | 
| 29963 | Mass Polymorph | 67108928 | 
| 29972 | Darkmender's Ghoul: Chains | 67108868 | 
| 30099 | Tame Crazed Dragonhawk | 67175424 | 
| 30102 | Tame Elder Springpaw | 67175424 | 
| 30105 | Tame Mistbat | 67175424 | 
| 30181 | The Shadow Vault: Phase Shift I | 67125249 | 
| 30646 | Tame Barbed Crawler | 67175424 | 
| 30653 | Tame Greater Timberstrider | 67175424 | 
| 30654 | Tame Nightstalker | 67175424 | 
| 30719 | Teleport to Dalaran | 67108868 | 
| 30740 | Eyesore Blaster | 71303172 | 
| 30879 | Permanent Area Damage 50k | 603979776 | 
| 31008 | Hammer of Vindication | 67108868 | 
| 31334 | Growl | 67108864 | 
| 31474 | Sky Terror: Dummy to Gargoyle Target 02 | 67108868 | 
| 31694 | Strange Feeling | 67125248 | 
| 31699 | The Admiral Revealed: Lord-Commander's Nullifier Effect | 67108864 | 
| 31709 | Cower | 67108864 | 
| 31932 | Freezing Trap Effect | 71303168 | 
| 32067 | The Sum is Greater than the Parts: Dr. Terrible's Death Signal | 67108868 | 
| 32889 | Grasp of Death | 67108868 | 
| 33329 | Murmur's Wrath | 67108868 | 
| 33331 | Murmur's Wrath | 67108868 | 
| 33332 | Suppression Blast | 67108868 | 
| 33479 | Adamantine Shell | 67108864 | 
| 33698 | Anguish | 67108864 | 
| 33699 | Anguish | 67108864 | 
| 33700 | Anguish | 67108864 | 
| 33701 | Suffering | 67108864 | 
| 34105 | Taunt Visual | 67108864 | 
| 35958 | Mana Bomb Explosion | 67108868 | 
| 36213 | Angered Earth | 67108864 | 
| 36461 | Purify Elemental | 67108868 | 
| 36642 | Banished from Shattrath City | 67108864 | 
| 36671 | Banished from Shattrath City | 67108864 | 
| 36851 | Bethod's Sword Challenge | 67108868 | 
| 36935 | QA -5000 Attack Power | 71303168 | 
| 37448 | Chain Lightning | 67108864 | 
| 37486 | Taunt | 336084997 | 
| 37548 | Taunt | 67108864 | 
| 37833 | Banish | 67108864 | 
| 37834 | Unbanish Azaloth | 67108864 | 
| 37848 | Cosmetic - Chain Lightning Special02 (single) | 67108868 | 
| 37906 | Book of Fel Names | 67108864 | 
| 38078 | Ebon Blade Prisoners: Force Cast from Cage | 67108868 | 
| 38328 | Threat Reduction | 67108864 | 
| 38329 | Threat Reduction | 67108864 | 
| 38376 | Banish | 67108864 | 
| 38637 | Nether Exhaustion | 67108864 | 
| 38638 | Nether Exhaustion | 67108864 | 
| 38639 | Nether Exhaustion | 67108864 | 
| 39222 | Anti-Demon Flame Thrower | 67108864 | 
| 39270 | Growl | 67108864 | 
| 39377 | [DND]Taunt Visual | 67108864 | 
| 39384 | Burning Flames | 603979776 | 
| 39985 | Legion Ring - Charm - North 01 (Possess) | 67108864 | 
| 40357 | Legion Ring - Character Invis and Immune | 67108868 | 
| 40382 | Legion Ring - Charm - North 02 (Possess) | 67108864 | 
| 40383 | Legion Ring - Player Force-Cast North 02 | 67108869 | 
| 40404 | Legion Ring - Enter Stage N02 | 67108864 | 
| 40415 | Fixated | 67108868 | 
| 40498 | Legion Ring - Cancel Character Invis and Immune | 67108868 | 
| 40509 | Cancel Grasp of the Emerald Dream | 67108868 | 
| 40521 | Legion Ring - Player Force-Cast North 03 | 67108869 | 
| 40522 | Legion Ring - Enter Stage N03 | 67108864 | 
| 40523 | Legion Ring - Charm - North 03 (Possess) | 67108864 | 
| 40646 | Cosmetic - Legion Ring Eredar Lightning | 67125252 | 
| 40825 | Banishment | 67108868 | 
| 40856 | Wrangling Rope | 67108928 | 
| 40893 | Fixated | 67108868 | 
| 40969 | Malister's Frost Wand | 67108868 | 
| 41341 | Balance of Power | 67108864 | 
| 41909 | Hell Hath a Fury: Hex of Air Knockback | 67108864 | 
| 42632 | Mission: Eternal Flame: Bunny 01 Kill Credit | 67108868 | 
| 42633 | Mission: Eternal Flame: Bunny 02 Kill Credit | 67108868 | 
| 42634 | Mission: Eternal Flame: Bunny 03 Kill Credit | 67108868 | 
| 42635 | Mission: Eternal Flame: Bunny 04 Kill Credit | 67108868 | 
| 42953 | Teleport to Violet Stand | 67108864 | 
| 43067 | Towers of Certain Doom: NW Kill Credit | 67108868 | 
| 43077 | Towers of Certain Doom: E Kill Credit | 67108868 | 
| 43086 | Towers of Certain Doom: SW Kill Credit | 67108868 | 
| 43087 | Towers of Certain Doom: SE Kill Credit | 67108868 | 
| 43263 | Ghoul Taunt | 71303168 | 
| 43307 | Scare the Guano Out of Them!: Summon Darkclaw Guano | 67108868 | 
| 43351 | Cleansing Soul | 67108864 | 
| 43504 | BG Reinforcements - OnDeath Proc Aura | 336084993 | 
| 44375 | Whelpling Influence | 67108864 | 
| 44836 | Banish | 67108864 | 
| 44934 | Sunwell Portal Quests Flag | 67108868 | 
| 45106 | Showdown: Goc Kill Credit | 67108869 | 
| 45110 | Greengill Slave Freed | 67108868 | 
| 45611 | Arcane Chains | 67108932 | 
| 45808 | Har'koa's Chains | 67125252 | 
| 46167 | Planning for the Future: Create Snowfall Glade Pup Cover | 67108868 | 
| 46276 | Ravager Taunt | 67108864 | 
| 46331 | Trainer: Untrain Talents | 67108868 | 
| 46424 | Power of the Storm | 67108869 | 
| 46432 | Power of the Storm | 67108928 | 
| 47096 | Rifle the Bodies: Create Mage Hunter Personal Effects | 67108868 | 
| 47984 | Torment | 67108864 | 
| 47989 | Suffering | 67108864 | 
| 47990 | Suffering | 67108864 | 
| 47993 | Anguish | 67108864 | 
| 48293 | Flamebringer's Chain | 67108868 | 
| 48575 | Cower | 67108864 | 
| 48753 | A Fall from Grace: Bell Rung Dummy Aura | 67125252 | 
| 49029 | Fixated | 67108868 | 
| 49613 | Taunt | 67108864 | 
| 50867 | Hourglass of Eternity Nearby | 67108868 | 
| 50918 | Gluttonous Lurkers: Create Basilisk Crystals Cover | 67108868 | 
| 50926 | Gluttonous Lurkers: Create Zul'Drak Rat Cover | 67108868 | 
| 51013 | Exsanguinate | 67108864 | 
| 51671 | Ghostly | 67125248 | 
| 52154 | Taunt | 67108864 | 
| 52222 | Soul Font Void | 67108868 | 
| 52242 | Foundation for Revenge: Soul Font Void Channel | 67108868 | 
| 52249 | Quetz'lun's Hex of Air | 67108864 | 
| 52250 | Quetz'lun's Hex | 67108928 | 
| 52251 | Quetz'lun's Hexxing Stick | 67108928 | 
| 52278 | Quetz'lun's Hex of Fire | 67108864 | 
| 52340 | Har'koa's Spirit | 67125252 | 
| 52351 | Quetz'lun's Protection | 67108864 | 
| 52353 | Script Effect - Creature Capture GUID to Dot Variable | 67125253 | 
| 52381 | Reclaim Power | 67108868 | 
| 52486 | You Reap What You Sow: Quest Complete Force Cast | 67125252 | 
| 52596 | Medallion of Mam'toth | 67108864 | 
| 52603 | Trample | 67108928 | 
| 52607 | Enraged Mammoth: Trample Aura for On Death Kill Credit | 67108864 | 
| 52644 | Hexed Caches: Hex Master | 67108868 | 
| 52687 | Bombard the Ballistae: Knockback | 67108868 | 
| 52741 | Darkmender's Tincture | 67108929 | 
| 52859 | Submission | 67108868 | 
| 52860 | Rampage: Drain Power Effect | 67108868 | 
| 52884 | Drain Power | 67108868 | 
| 52989 | Akali's Stun | 67108868 | 
| 53010 | Convocation at Zol'Heb: Removef Akali's Stun | 67108868 | 
| 53096 | Quetz'lun's Judgment | 67108868 | 
| 53360 | Teleport to Dalaran | 67108864 | 
| 53477 | Taunt | 67108864 | 
| 54090 | Area Despawn | 67108868 | 
| 54112 | Get the Key: Vaelen's Chains - Left Hand | 67125252 | 
| 54190 | Lifeblood Dummy | 67108869 | 
| 54191 | Lifeblood Siphon | 67108865 | 
| 54224 | Death | 67649537 | 
| 54620 | Teleport Crystal: Teleport to Dalaran AICast Script | 67108868 | 
| 54723 | Soul Wrack | 67108868 | 
| 54794 | Taunt | 67108864 | 
| 54837 | Shartuul Kill Credit | 67125249 | 
| 55063 | Arbiter's Judgment | 67108869 | 
| 55278 | Stoneclaw Totem | 335544324 | 
| 55284 | Siege Ram | 67108864 | 
| 55328 | Stoneclaw Totem | 335544324 | 
| 55329 | Stoneclaw Totem | 335544324 | 
| 55330 | Stoneclaw Totem | 335544324 | 
| 55332 | Stoneclaw Totem | 335544324 | 
| 55333 | Stoneclaw Totem | 335544324 | 
| 55335 | Stoneclaw Totem | 335544324 | 
| 55409 | The Shadow Vault: Phase Shift II | 67125249 | 
| 55773 | Horde Control Phase Shift | 336084993 | 
| 55774 | Alliance Control Phase Shift | 336084993 | 
| 55796 | Get the Key: Vaelen's Chains - Right Hand | 67125252 | 
| 55974 | Blood Boil | 67108864 | 
| 55981 | Mammoth Trumpet | 67108864 | 
| 56222 | Dark Command | 67108864 | 
| 56559 | Distracting Shot | 67108868 | 
| 56578 | Rapid-Fire Harpoon | 67108868 | 
| 56617 | Alliance Controls Factory Phase Shift | 336084993 | 
| 56618 | Horde Controls Factory Phase Shift | 336084993 | 
| 56699 | Controlling Nergeld | 67108868 | 
| 56902 | Wintergrasp Victory | 336084997 | 
| 57405 | Flush | 67108868 | 
| 57461 | To Icecrown Airship - Player - Aura - Teleport to Dalaran Trigger | 67108864 | 
| 57635 | Disengage | 67108864 | 
| 57884 | Through the Eye: Kill Credit to Master | 67108869 | 
| 57980 | Left Hand Chains | 67108868 | 
| 57983 | Right Hand Chains | 67108868 | 
| 58108 | Patches Chain | 67108868 | 
| 58494 | Wintergrasp Defeat | 336084997 | 
| 58586 | Stoneclaw Totem Effect | 335544320 | 
| 58587 | Stoneclaw Totem Effect | 335544320 | 
| 58588 | Stoneclaw Totem Effect | 335544320 | 
| 58589 | Stoneclaw Totem | 335544324 | 
| 58590 | Stoneclaw Totem | 335544324 | 
| 58591 | Stoneclaw Totem | 335544324 | 
| 58622 | Teleport to Lake Wintergrasp | 67108868 | 
| 58632 | Teleport to Lake Wintergrasp | 67108868 | 
| 58633 | Teleport to Lake Wintergrasp | 67108868 | 
| 58639 | Stoneclaw Totem Effect | 335544320 | 
| 58681 | Teleport to Lake Wintergrasp | 67108868 | 
| 58855 | Growl | 67108864 | 
| 58857 | Twin Howl | 67108864 | 
| 59096 | Teleport to Lake Wintergrasp | 67108868 | 
| 59506 | Heroic Vanguard | 71303168 | 
| 59671 | Challenging Howl | 67108864 | 
| 59702 | Explodo-Rockets | 67108864 | 
| 59760 | Teleport: Fortress Graveyard. | 67108869 | 
| 59762 | Teleport: Sunken Ring | 67108869 | 
| 59763 | Teleport: Broken Temple | 67108869 | 
| 59765 | Teleport: Horde Landing Zone | 67108869 | 
| 59766 | Teleport: Westspark Factory Graveyard | 67108869 | 
| 59767 | Teleport: Eastspark Factory Graveyard | 67108869 | 
| 59769 | Teleport: Alliance Landing Zone | 67108869 | 
| 59951 | Mind Trick: Chains - Left Hand | 67108868 | 
| 59952 | Mind Trick: Chains - Right Hand | 67108868 | 
| 60027 | Alliance Control Phase Shift | 336084993 | 
| 60028 | Horde Control Phase Shift | 336084993 | 
| 60532 | Heart Explosion Effects | 67108864 | 
| 60839 | Mystery of the Infinite: Hourglass of Eternity Dies | 67108869 | 
| 60840 | Mystery of the Infinite: Hourglass of Eternity Dies - Quest Fails | 67125249 | 
| 60932 | Disengage | 67108864 | 
| 60966 | Heroic Vanguard | 71303168 | 
| 61507 | Disengage | 67108864 | 
| 61676 | Growl | 67108864 | 
| 61832 | Rifle the Bodies: Create Magehunter Personal Effects Cover | 67108869 | 
| 62068 | Scare the Guano Out of Them!: Cast Spell 1 On Target's Master | 67108868 | 
| 62105 | To'kini's Blowgun | 67108928 | 
| 62108 | Tails Up: Summon Female Frost Leopard | 67108868 | 
| 62116 | Tails Up: Summon Female Icepaw Bear | 67108868 | 
| 62124 | Hand of Reckoning | 67108864 | 
| 62392 | Lightning Destruction | 67108868 | 
| 63463 | Alliance Tournament Eligibility Flag | 67108868 | 
| 63464 | Horde Tournament Eligibility Flag | 67108868 | 
| 63465 | Alliance Tournament Eligibility Release | 67108868 | 
| 63466 | Horde Tournament Eligibility Release | 67108868 | 
| 63518 | Place Alliance Champion Flag | 67108868 | 
| 63519 | Place Horde Champion Flag | 67108868 | 
| 63624 | Learn a Second Talent Specialization | 67649541 | 
| 64193 | Heartbreak | 336084997 | 
| 64380 | Shattering Throw | 67108864 | 
| 64576 | Court of Bones Phase Shift | 335560709 | 
| 65737 | Heartbreak | 336084997 | 
| 65869 | Disengage | 67108864 | 
| 65940 | Shattering Throw | 67108864 | 
| 65941 | Shattering Throw | 67108864 | 
| 68340 | Disengage | 67108864 | 
| 69235 | Camera Shake - Tremor | 67125252 | 
| 69623 | Player Voluntarily Ejects From Craft | 67125252 | 
| 70013 | Quel'Delar's Compulsion | 67125248 | 
| 70193 | Quel'Delar Phase Shift | 335560709 | 
| 70428 | Taunt | 67108864 | 
| 70996 | Exhaustion Removal (TEST) | 336084997 | 
| 73075 | Taunt Morbidus | 67108864 | 
| 73906 | Quest Credit | 67108864 | 
| 75100 | Attack | 67125253 | 

</details>

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by pklloveyou** [comment]
How to test it

**Comment by Kitzunu** [comment]
Check that these spells pass through mobs that are usually immune to the school

**Comment by pklloveyou** [comment]
image
Mocking hostile creatures?

**Comment by pklloveyou** [comment]
image
10H ICC 
immune
It's working

**Comment by pklloveyou** [comment]
Organisms that are not immune also work

**Comment by pklloveyou** [comment]
so? tested?

**Comment by pklloveyou** [comment]
It has been working on my server for nine days and no player has reported an error

**Comment by FrancescoBorzi** [comment]
thanks @pklloveyou for your feedback <3

**Comment by FrancescoBorzi** [comment]
@Kitzunu codestyle fails

**Comment by Helias** [comment]
codestyle issue

**Comment by Kitzunu** [comment]
😠 will fix when I am not at work the whole day. Probs weekend

**Comment by pklloveyou** [comment]
So far, there are no player feedback errors

**Comment by Kitzunu** [comment]
Fixed

**Comment by pklloveyou** [comment]
nice

**Pull request merged**
