### PR TITLE
fix(DB/GameObject-Spawn): Copper veins spawns in Mulgore

### PR DESCRIPTION
**Pull request by r-o-b-o-t-o**
## Changes Proposed:
-  Fixed two copper veins that were incorrectly placed in southern Mulgore

## Issues Addressed:
image

## SOURCE:

On the classic wowhead db, only one vein exists here, and another is placed a bit further away:
image

## Tests Performed:

- Applied SQL fix on local DB
- Tested in-game
- Checked on minimap that nodes correspond to the ones imported from the Wowhead db plugin in Gatherer:
image

## How to Test the Changes:

- `.go object 4696`
- `.go object 20650`

## Known Issues and TODO List:
None

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @r-o-b-o-t-o ! was there an issue report for this bug?

**Comment by r-o-b-o-t-o** [comment]
Hello @FrancescoBorzi, no, there is no report for this, I just encountered these veins while playing on ChromieCraft and thought I'd fix them :)

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
ty

**Pull request merged**
