### PR TITLE
fix(DB/quest_template_locale): esES and esMX

### LINKED ISSUE #11421: (esES - esMX) Update quest_template_locale to 100%
### Current Behaviour

Update of the quest_template_locale table to 100% in: esES and esMX

### esES and esMX 
* These quests have been marked as obsolete by Blizzard and cannot be obtained or completed.
- [9754](https://es.classic.wowhead.com/quest=9754)
- [10215](https://es.classic.wowhead.com/quest=10215)
- [12445](https://es.classic.wowhead.com/quest=12445)
- [12731](https://es.classic.wowhead.com/quest=12731)
- [12923](https://es.classic.wowhead.com/quest=12923)
- [13541](https://es.classic.wowhead.com/quest=13541)

### Source

_No response_

### Steps to reproduce the problem

*

### Extra Notes

Update some translations that contain error

### AC rev. hash/commit

AzerothCore rev. 4ac565699fcb 2022-04-13 11:57:04 +0000 (master branch) (Unix, RelWithDebInfo, Static)

### Operating system

Ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by Tony931023**
Update some translations that contain errors in the quest_template_locale table in esES and esMX

- Close #11421 

- https://wotlkdb.com/?quest=147

### CODE REVIEW

**Comment by acidmanifesto** [comment]
Can you Fetch the Upstream and see if the codefactor issue is resolved?

**Comment by acidmanifesto** [comment]
What is the status of this PR? Is it abandon?

**Comment by Maelthyrr** [comment]
Without news, I will close this PR. Please ping me or another member to reopen it.

**Comment by Tony931023** [comment]
@Maelthyrr This pr is not abandoned, I only have personal problems and I have not been able to continue it, please reopen it, to continue working on it

**Comment by Maelthyrr** [comment]
@Tony931023 you marked this PR as ready to be reviewed. Are any new changes coming?

**Comment by Tony931023** [comment]
Yes, in the next PR I will be adding the other translations, this is ready to be reviewed now

**Comment by Kitzunu** [comment]
update it

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Tony931023 fetch a upstream on this so we can get newer workflow results please

**Comment by acidmanifesto** [comment]
April of 2022 was the last movement on this pr. Author may of followed up in december but not further pr movement has occured, will mark as abandon and closed. Feel Free to reopen when you are able to follow up.

**Pull request closed without merging**
