### PR TITLE
fix(DB/Loot): remove blackened gloves loot

### PR DESCRIPTION
**Pull request by Helias**
## Changes Proposed:
-  remove [Blackened Defias Gloves](https://wowgaming.altervista.org/aowow/?item=10401), [Boots](https://wowgaming.altervista.org/aowow/?item=10402) and [Leggings](https://wowgaming.altervista.org/aowow/?item=10400) from the reference_loot_template because the item should be dropped only from  Defias Overseers and Defias Taskmasters. The loot of this item in these NPCs is already handled in creature_loot_template.

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4671
- Closes https://github.com/chromiecraft/chromiecraft/issues/108

## Tests Performed:
- executed the SQL script

## How to Test the Changes:
- the chance to loot this item is very low actually, so it's hard to loot it from the other NPCs like https://wowgaming.altervista.org/aowow/?npc=3255
- I don't think is necessary a test for this small change

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
\` \`

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> Tests Performed:
> executed the SQL script

@Helias haven't you tried this in game?

**Comment by Helias** [comment]
I tried before the PR and it's hard to loot the items, so it's not immediate to verify the loot.

**Comment by pklloveyou** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
@pklloveyou thank you very much for testing. When you have time can you please test some of:

https://github.com/azerothcore/azerothcore-wotlk/pulls?q=is%3Apr+is%3Aopen+label%3A%22Waiting+to+be+tested%22

**Pull request merged**
