### PR TITLE
fix(Script/Instance): Ulduar - Fix Keeper's missing gossips and remove hardcode

### PR DESCRIPTION
**Pull request by avarishd**
Finally learned how to do gossips (At least I like to think that....)
## Changes Proposed:
- Added the missing text that explains what each keeper does 
- Added the 2nd part of the gossip, where you confirm you want the keeper's assistance
- Removed the hardcode

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11702

## SOURCE:

In the issue

## Tests Performed:

- Tested in-game (and tested with yogg, to make sure I didn't screw the keeper activation, all good)

## How to Test the Changes:

.gm on
.go c 1975234
Speak with him or any other keeper
Notice the proper npc_text & 2nd gossip page
Make sure the keepers actually activate when spoken to (have to clear to yogg)

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Comment by mpfans** [comment]
tested, no work.

image

image

**Comment by avarishd** [comment]
@mpfans Can you try again, but delete cache? (Unless you already have)

**Comment by mpfans** [comment]
> @mpfans Can you try again, but delete cache? (Unless you already have)

I re clone the code, recompile it, delete the game cache, and test , work.

**Comment by mpfans** [comment]
Please merge it

**Comment by mpfans** [comment]
@Nyeriah

**Pull request merged**
