### PR TITLE
fix(DB): Blackrock Drake's pathing

### PR DESCRIPTION
**Pull request by hanabi5**
## Changes Proposed:
- Unsniffed waypoint data to fix temporarily them clipping through
  textures in the middle of the Blackrock Mountain
- Added template movement, adjusted speeds acording to sniffed data and
  increased visibilitydistance to avoid them not loading if too far
  away, altering their synced flight.

## Issues Addressed:

- Closes a not reported issue

## SOURCE:

Brotalnia's sniffs

## Tests Performed:

- Tested in-game

## How to Test the Changes:

1. Go to Blackrock Mountain and staying in the middle, the drakes will lap around the area.

image

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
The Drakes do some little jolts when changing directions but otherwise are fine.

https://user-images.githubusercontent.com/100873791/168888955-7553ea56-85fa-4e7f-b94a-e0d1ee8648a3.mp4

**Comment by hanabi5** [comment]
We could have smooth waypoints to avoid this

**Comment by hanabi5** [comment]
why is this wip?

**Comment by Maelthyrr** [comment]
> why is this wip?

Do you shouldn't add some waypoint to get a smooth pathway ?

**Comment by hanabi5** [comment]
Smooth waypoints are a core modification for every waypoint. It's basically an implementation of the Flight master experience. Besides this change is supposed to be temp until we get real sniffs

**Comment by hanabi5** [comment]
I'll see if I can put in more waypoints to make it look better

**Pull request closed without merging**
