### PR TITLE
fix(Core/SAI): Do not reset HP with SMART_ACTION_UPDATE_ENTRY

### PR DESCRIPTION
**Pull request by Kitzunu**
* https://github.com/TrinityCore/TrinityCore/commit/8967cc96df4c1c5c7465e9fd1fa66400f3e992b3

Co-Authored-By: Wyrserth <43747507+Wyrserth@users.noreply.github.com>

## Changes Proposed:
-  Creature HP should not reset when changing Entry

## Tests Performed:
- Builds
- Tested in-game

## How to Test the Changes:

1. .go c id 30422
2. .mod phase 4
3. Deal damage on the creature
4. .cast 56727
5. See that the creature keeps it's HP even when Entry has been changed

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by pklloveyou** [comment]
Have you tested it? It doesn't work for me

**Comment by Kitzunu** [comment]
Yes I did

Follow the steps I said and it will work

**Comment by Kitzunu** [comment]
https://user-images.githubusercontent.com/24550914/107236360-ee57d580-6a25-11eb-8d72-86a3e28f0435.mp4

As you see here, when I cast the spell he changes entry and the HP remains the same

**Comment by pklloveyou** [comment]
OK, I thought it was maximum health ，Tested

**Comment by FrancescoBorzi** [comment]
thanks guys @Kitzunu @pklloveyou

**Pull request merged**
