### PR TITLE
fix(Core/Item): Fixed incorrect damage mod for Heirloom 2H weapons

### PR DESCRIPTION
**Pull request by Kitzunu**
* cherry-pick commit (https://github.com/TrinityCore/TrinityCore/commit/13fa60ab86c6338f034823fbd49a90baedd3ab58)

## Changes Proposed:
-  Heirloom weapons use a wrong calculation server side resulting in higher max and lower min damage

-  From 3.3.5 0x61A830:
https://gist.github.com/robinsch/06cdafc4d011500362c3c5cdf7ed1d39

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kofmy** [comment]
degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates

**Comment by Kitzunu** [comment]
Which isnt possible as the calculation literslly changed 😅

**Review by Nyeriah — APPROVED** [review]

**Comment by saisi1983** [comment]
Heirloom weapons damage still higher than normal weapons
eg:[Battleworn Thrash Blade]entry=44096;[Warglaive of Azzinoth]entry=32837;when you equiped the weapon,you will see the damage value.

**Comment by baogejin** [comment]
try this？
微信图片_20230621154442

**Pull request merged**
