### PR TITLE
fix(Core/Spell): Make use of SPELL_ATTR6_DONT_CONSUME_PROC_CHARGES

### PR DESCRIPTION
**Pull request by Kitzunu**
cp from tc

## Changes Proposed:
-  Don't remove proc charges from spells with SPELL_ATTR6_DONT_CONSUME_PROC_CHARGES

<details>
<summary>Spells with the attribute</summary>

dbc_spell
---
```sql
SELECT `id`, `name_lang_1`, `attributesEx6`
FROM `dbc_spell` 
WHERE `attributesEx6` & @flag = @flag
```
| id | name_lang_1 | attributesEx6 | 
| ---: | --- | ---: | 
| 698 | Ritual of Summoning | 32 | 
| 1464 | Slam | 32 | 
| 8820 | Slam | 32 | 
| 11604 | Slam | 32 | 
| 11605 | Slam | 32 | 
| 25241 | Slam | 32 | 
| 25242 | Slam | 32 | 
| 46584 | Raise Dead | 32 | 
| 47474 | Slam | 32 | 
| 47475 | Slam | 32 | 
| 47632 | Death Coil | 32 | 
| 47633 | Death Coil | 32 | 
| 53352 | Explosive Shot | 32 | 
| 53353 | Chimera Shot - Serpent | 33 | 
| 53769 | Death Coil | 32 | 
| 60856 | TF-Xplosive Rocket Turret | 32 | 
| 61999 | Raise Ally | 32 | 
| 62735 | Ritual of Summoning Test | 32 | 

</details>

## Issues Addressed:
- ref https://github.com/azerothcore/azerothcore-wotlk/issues/4306

## Tests Performed:

- None

## How to Test the Changes:

The logic is here... but
1. Use the spells above, they shouldn't consume proc charges

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
I don't understand how to test here

**Comment by Kitzunu** [comment]
I'll have to get back to you in some time and I can detail it more. Atm I got no time

**Comment by pklloveyou** [comment]
Translation software, translation of certain words, their meaning changed. sorry

**Comment by Kitzunu** [comment]
You can .learn 47475
.aura 46916
and use 47475 and see that for these spells nothing has changed

**Comment by Kitzunu** [comment]
I found the commit on TC https://github.com/TrinityCore/TrinityCore/commit/23823f5147e808928e1d8cd31b6cdf31753ef14d apparently xinef fixed it there but not on Sunwell x)

**Comment by pklloveyou** [comment]
> You can .learn 47475
> .aura 46916
> and use 47475 and see that for these spells nothing has changed

It's normal for him to work . Tested?

**Comment by pklloveyou** [comment]
Put on the server for a week, the player did not report the error

**Review by FrancescoBorzi — APPROVED** [review]

**Pull request merged**
