### PR TITLE
feat(DB/Worldstates): added worldstates entry 20004 in characters DB

### LINKED ISSUE #2382: DB/Worldstates: Add a world state for daily quest reset time to `characters`
I saw the `characters.worldstates` table in our DB, compared to TC it seems that we are missing some worldstates, like the "WorldState Daily Rest Quest Time".

Related code: https://github.com/TrinityCore/TrinityCore/commit/1277c542638522b210addd22966c32db89cb29b6#diff-69f0ea4bf362615d6993f2a38027d31a

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/82631925-db-worldstates-add-a-world-state-for-daily-quest-reset-time-to-characters?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Helias**
In `CharacterDatabaseCleaner.cpp` there are some piece of code that UPDATE the world state 20004  (`WS_CLEANING_FLAGS`) that currently does not exist.
In characters.worldstates there is 20005 named as `cleaning_flags` but it's wrong, I renamed it into `NextDailyQuestResetTime` and added the correct `cleaning_flags` entry.

##### CHANGES PROPOSED:
- added worldstate 20004 cleaning_flags
- renamed world state 20005 into `NextDailyQuestResetTime`

##### ISSUES ADDRESSED:
- Closes #2382

##### HOW TO TEST THE CHANGES:
- Add this PR to your core and import the sql query.
- Set `worldserver.conf` parameters correctly:
`CleanCharacterDB = 1`
`PersistentCharacterCleanFlags = 14`
- Set `worldstates` sql table value with the same value of `PersistentCharacterCleanFlags`, to make this execute the following query:
```sql
UPDATE `worldstates` SET `value`='14' WHERE `entry`='20004';
```
- log in in game and add dual talent specialization, learn some talents and spells
- check `character_talent` it will be full of data
- restart the worldserver, now `character_talent` will be empty, log in game and you will see your talents resetted
- change che worldserver.conf `PersistentCharacterCleanFlags=0`  and restart the server
- you will see that in `worldstates` **cleaning_flags** (20004) will be 0.

##### Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Could you please tell me if I understood this correctly?

- In order to use the cleaner you have to enable "CleanCharacterDB" in the worldserver configuration and specify a value >0 for entry 20004 in worldstates.
- The value has to be a combination of these flags:
  https://github.com/azerothcore/azerothcore-wotlk/blob/832bccd9fa8ae5f3dd20eaeed244e74cd700f2de/src/server/game/Tools/CharacterDatabaseCleaner.h#L14-L18
- The cleaner runs once at server start.

**Comment by Helias** [comment]
Correct, I've just made a PR in the wiki.

https://github.com/azerothcore/wiki/pull/140

**Comment by Helias** [comment]
I added a better description in worldserver.conf.dist, hope someone can test this PR soon.

**Comment by pangolp** [comment]
The PR is very complete, but I still don't understand what would be the change I would have to visualize in order to try it.

**Comment by FrancescoBorzi** [comment]
@Helias can you help @pangolp to test this?

**Comment by pangolp** [comment]
He's been explaining to me, but no matter how hard I try, I can't understand the change that takes place. It would be good for someone else to try, because I explain everything in detail, but even so I can not see the change. Evidently I am doing something wrong.

**Comment by pangolp** [comment]
<a href="https://subefotos.com/ver/?de71ced5989d9fd9b04d9d0aadc25d4ao.png" target="_blank"></a>
<a href="https://subefotos.com/ver/?91e00cb9dcf4157991eb90f52419bc42o.png" target="_blank"></a>
<a href="https://subefotos.com/ver/?b3a6be948025d6a8442e378c7bd9abf2o.png" target="_blank"></a>

**Comment by Helias** [comment]
Guide to test this PR updated, thx @pangolp

**Comment by Endeffect-AT** [comment]
Tested with your instrucions @Helias:

1. Added PR to core

2. Set the worldserver.conf as suggested: 

2020-01-02 17_08_50-D__World of Warcraft_3 3 5 WotLK__AzerothCore Test_bin_Release_worldserver conf
2020-01-02 17_09_05-D__World of Warcraft_3 3 5 WotLK__AzerothCore Test_bin_Release_worldserver conf

3. Executed the sql script in acore_characters db: `UPDATE`worldstates` SET `value`='14' WHERE `entry`='20004';`

2020-01-02 17_08_28-Local MySQL_acore_characters_worldstates_ - HeidiSQL 10 2 0 5599

4.  Logged in, added dual talent specialization and learned all spells such as two specs 
Result in character_talent table: 

2020-01-02 17_18_17-Local MySQL_acore_characters_character_talent_ - HeidiSQL 10 2 0 5599

5. After a server restart:

2020-01-02 17_19_46-Local MySQL_acore_characters_character_talent_ - HeidiSQL 10 2 0 5599

6. Changed the worldserver.conf to PersistentCharacterCleanFlags=0 and restartet again:

2020-01-02 17_21_58-Local MySQL_acore_characters_worldstates_ - HeidiSQL 10 2 0 5599

**Conclusion:** Working as expected :)

**Comment by Helias** [comment]
Ty man for all of your work @Endeffect-AT :heartbeat:

**Comment by Endeffect-AT** [comment]
No big deal mate ☺️

**Pull request merged**
