### PR TITLE
fix(Core/LFG): Fixed showing dungeon access requirements only for lea…

### LINKED ISSUE #14070: [dungeon_access_requirements] leader_only does not work for LFG
### Current Behaviour

When an access requirement is set to leader_only, it is not enforced through LFG and the group must enter the instance manually

### Expected Blizzlike Behaviour

.

### Source

_No response_

### Steps to reproduce the problem

`.quest add 10285` `.quest reward 10285` on one character
rest of the group does not complete quest
attempt to enter Opening the Dark Portal using LFD

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/721711d70f31ad46b615b630c379d61837d263f6

### Operating system

Windows 10

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…ders in LFG.

Fixes #14070

  

## Issues Addressed:

- Closes #14070

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.quest add 10285` `.quest reward 10285` on one character
rest of the group does not complete quest
attempt to enter Opening the Dark Portal using LFD

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
I don't understand what the desired behavior is here. Party leader has completed quest 10285, partied with a character who has not completed that quest (character 2), and dungeon finder shows "The Black Morass" as locked, with the reasoning that character 2 hasn't completed the prerequisite quest, though looking at the original issue that looks to be unchanged.

**Comment by Gultask** [comment]
In a group, entering the instance through the portal works fine if it has leader_only set to 1, but that field has no effect on RDF or LFG, the idea is to allow leader_only to affect RDF as well.

You can use https://github.com/azerothcore/mod-progression-system/blob/main/src/Bracket_61_64/sql/world/progression_61_64_dungeon_access_requirements_attunements.sql to test it. As it'll add more dungeons that use leader_only

**Comment by heyitsbench** [comment]
So does the Black Morass not have this leader_only flag by default? If so, why was it given as a testing/repro step?

**Comment by Gultask** [comment]
Black Morass is the only dungeon that has leader_only set to 1 by default.

**Comment by heyitsbench** [comment]
> Black Morass is the only dungeon that has leader_only set to 1 by default afaik.

So then if this PR works as expected, both players should be able to queue as a party for Black Morass with only the leader having completed the quest, correct?

**Comment by Gultask** [comment]
The Heroic version of Black Morass*

image

> So then if this PR works as expected, both players should be able to queue as a party for Black Morass with only the leader having completed the quest, correct?
Yes

**Comment by heyitsbench** [comment]
> The Heroic version of Black Morass

Then in that case, RDF has an issue with both players lacking the Key of Time. Adding this key to the leader's inventory does not unlock the dungeon for both players to queue. Having the key in both players' inventories allows the players to queue if the leader has completed the quest, but not if the leader has not.

**Comment by Gultask** [comment]
I think that's fine, if I'm understanding correctly. The item requirement in this case is not leader_only, only the quest is. Everyone needs to have the key to enter, while only the leader is required to complete the quest.

Which is obviously bizarre and I think the leader_only flag there is misplaced 😛

**Comment by heyitsbench** [comment]
> I think that's fine, if I'm understanding correctly. The item requirement in this case is not leader_only, only the quest is. Everyone needs to have the key to enter, while only the leader is required to complete the quest.

Then in that case I'd say this PR is working as it should. Thanks ❤️

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
