### PR TITLE
fix(DB/Core): Fix some issues concerning "Thorim's Charm of Earth" (Mending Fences)

### LINKED ISSUE #1897: (quest) Mending Fences
(quest) Mending Fences 

##### SMALL DESCRIPTION:

Can't target Fjorn with rock

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Can target Fjorn with rock just like other giants

##### CURRENT BEHAVIOUR:

Can't target Fjorn with rock

##### STEPS TO REPRODUCE THE PROBLEM:

1. Get Mending Quest Npc
2. Try to use rock on fjorn

##### BRANCH(ES):

master

##### AC HASH/COMMIT:

Azerothcore rev. ded199d+

##### OPERATING SYSTEM:

Ubuntu 16/18

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/74699603-quest-mending-fences?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Apply the following fixes to "Thorim's Charm of Earth" (ID 41050, provided for quest "Mending Fences"):
- allow Fjorn to be targeted by the spell "Hurl Boulder"
- summon exactly 5 dwarves at the target of "Hurl Boulder"
- the dwarves will attack Stormforged Iron Giants and Fjorn
- remove the cpp spell script and all references for "Hurl Boulder" as they are not needed anymore

###### ISSUES ADDRESSED:
Closes #1897 

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- preparation:
```
.quest remove 12915
.quest add 12915
.go 7209.15 -3363.71 845.991 571
```
- pick up granite boulders
- use the item "Thorim's Charm of Earth" against Stormforged Iron Giants and Fjorn, it should now work on both NPCs

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master

### CODE REVIEW

**Comment by Stoabrogga** [comment]
@Selyria 
I pushed a new commit, please test once more.

**Comment by Stoabrogga** [comment]
One issue is still open in my opinion: If I remember correctly it was nearly impossible to get aggro from the giants, as the dwarves had some kind of taunt. As it is now you have to be very carefully not to cause too much damage. But I don't know how to properly add threat for the dwarves.

**Comment by Stoabrogga** [comment]
Ok, found a solution and pushed a new commit. The Earthen Ironbane now build up more threat so the giants are less likely to attack the player.

**Comment by Selyria** [comment]
> Ok, found a solution and pushed a new commit. The Earthen Ironbane now build up more threat so the giants are less likely to attack the player.

Yep, it looks a lot better that way.

High equip chars pull aggro but then so.

low Level and low equip players don't pull aggro.

And the helpers spawn on the mob well so.

Nice job

**Comment by Stoabrogga** [comment]
> What would be even better if the helpers despawned after 10 seconds without a fight.
> 
> at the moment they stand around for a very long time

I think they should stay for 1 minute, see the spell description:
https://wotlk.evowow.com/?spell=55528
They will also despawn if you take too long for the fight.

Anyway, thanks for testing this :+1:

**Comment by Selyria** [comment]
> > What would be even better if the helpers despawned after 10 seconds without a fight.
> > at the moment they stand around for a very long time
> 
> I think they should stay for 1 minute, see the spell description:
> https://wotlk.evowow.com/?spell=55528
> They will also despawn if you take too long for the fight.
> 
> Anyway, thanks for testing this 👍

Ah, okay, I thought after the fight, they were always gone fast.

At the moment they're about 5 minutes in the opposite direction.

(29927, 0, 2, 0, 1, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 41, 10000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Earthen Ironbane - Out of Combat - Despawn In 10000 ms');

**Comment by Stoabrogga** [comment]
Ok, thanks for the hint. It is much better that they despawn after 10 seconds when out of combat. I pushed another commit including this SAI entry.

**Pull request merged**
