### PR TITLE
Mass Update deprecated and monster items.

### PR DESCRIPTION
**Pull request by T1ti**
## Changes Proposed:
-  In AC currently all server side "secret" items like creature items and deprecated/test/dev items all have a generic name and wrong/missing data, they have no data except class, display id and (a wrong)name
image

How did I proceed : 

I searched in AC's database : items `WHERE name LIKE '%NPC Equip%'`.
 I copied all of the entries of returned items, and then I copied all the data for those items from vmangos database, I checked them on wowhead classic and they look accurate. This change also includes giving them the proper "deprecated" flags
This only affects items from the vanilla era as vmangos is a vanilla server.
No "normal" item should be affected by this
Somee examples : 
Before : 
image

image

After : 
image
image
On wowhead : 
https://classic.wowhead.com/item=2178/monster-sword-long-ornate
https://classic.wowhead.com/item=23795/permanent-spirit-of-zanza

There are about 2600 items affected, a lot of fun dev/test items like some legendaries/artifacts

## Issues Addressed:
- Closes 

## Tests Performed:

- ran querry and tested a few items in game
- 

## How to Test the Changes:

- Run the query.
- Look at the ID of affected items in the querry ("where ID = ...") and test those in game

## Known Issues and TODO List:

- [ ] I didn't port resistances because some of them have negative resistances, this is currently not supported by the table which has unisgned int.
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by T1ti** [comment]
obviously they throw a lot of errors for non existing spell ids...
A solution could be to ignore those error messages for deprecated items ? I thnk that's what vmangos does
otherwise I could just remove all spells from them but that's a bit sad.

**Comment by claudiodfc** [comment]
Can these items be deleted or are they equiped by NPCs?

**Comment by T1ti** [comment]
> Can these items be deleted or are they equiped by NPCs?

There are two types : developement/test/gm items are not used
Monster items are sued, and it's the majority of those

BTW I found out what those errors emssages are, Wotlk is just missing a lot of spell data that vanilla had, so the solution is either porting those spells to 3.3.5 to entirely fix them, or removing spell efects for those items

**Comment by FrancescoBorzi** [comment]
@T1ti what's the status of this PR?

**Comment by T1ti** [comment]
it's sad but i'm just gonna redo the PR without any spell related stuff....

**Comment by T1ti** [comment]
PR updated, no more loading error.

**Comment by T1ti** [comment]
image
To compare with the original without spells, here's the permanent spirit of zanza without its new spell effect. Note that I now include item descriptions updates

**Comment by FrancescoBorzi** [comment]
@T1ti build code style check failing with:

> Missing Semicolon (;) or multiple newlines at the end of the file.

**Comment by T1ti** [comment]
How many newlines should there be ?

**Comment by FrancescoBorzi** [comment]
> How many newlines should there be ?

only one, also check for missing semicolumns `;`

**Comment by T1ti** [comment]
Any trick for that ? I can't manually check 3000 lines 

I did a ctrlf+f search of ; and it returns as many results as the number of lines

**Comment by Nyeriah** [comment]
It's definitely not a semicolumn issue, so something with line endings

Skärmbild 2021-11-04 095225

**Comment by FrancescoBorzi** [comment]
> Worst scenario, could you break down the file in parts so we could try to make it work?

@T1ti

**Comment by T1ti** [comment]
can't get it to work

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers @claudiodfc can anyone please help to get this PR merged?

**Comment by claudiodfc** [comment]
It might be a missing new line on ending which I didn't check, or the job is trying to copy the whole SQL but because It's too long the clipboard gets full and it doesn't check its entirety?
I would say split the file into half and try again honestly.
I ran the query and everything is fine, no warnings or errors 👍🏼

**Comment by Kitzunu** [comment]
looks good to me. I say we merge even though that ci is failing. Probably because it is too big of a file :shrug:

Anyhow it runs fine when I import it into my database, so I see no reason not to merge it.

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Running the ci script on local machine everything pass too. so dno why github cant handle it

**Pull request merged**
