### PR TITLE
fix(DB/Creature): npc positions

### LINKED ISSUE #3374: NPCs standing intogether
NPCs standing intogether

##### CURRENT BEHAVIOUR:

There are 2x2 NPCs standing intogether
GUIDs of them all
5849 and 5231

5237 and 5848
https://i.imgur.com/WcEb15J.jpg

and another one right here
5747 and 5324

3756 and 5746
https://i.imgur.com/W0e5vEW.jpg

5750 and 4566

##### STEPS TO REPRODUCE THE PROBLEM:

1. 
2. 
3. 

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/92530984-npcs-standing-intogether?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Helias**
## CHANGES PROPOSED:
-  positions of some NPCs

## ISSUES ADDRESSED:
- Closes #3374  

## TESTS PERFORMED:
- just see in-game the positions and orientation of the related NPCs

## HOW TO TEST THE CHANGES:
`.go creature 5231`
`.go creature 3756`

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by felwyn** [comment]
We could leave this open for any other NPC positions missing or bugging out. So we dont have to do a new bug issue every single time we see something like this

**Comment by craftorix** [comment]
.go creature 117207

All Riflemen are positioning themselves on the defend wall sometimes.

**Comment by craftorix** [comment]
.go creature 117434 

Medic Hawthron is not directly looking at the Valiance Footman which makes it look weird.

**Comment by craftorix** [comment]
.go creature 116919

I can sit on the chair while it is already being used.
WoWScrnShot_090520_180031

**Comment by craftorix** [comment]
.go creature 109652

NPC is colliding with this block here making him walking over this higher thing
WoWScrnShot_090520_180031

**Comment by Helias** [comment]
@craftorix open a proper issue, this is not related to this PR

**Pull request merged**
