### PR TITLE
fix(Core/Config): Added new config to make pet's health be modified b…

### LINKED ISSUE #11480: Stats of (summoned) pets not affected by global modfiers
### Current Behaviour

Health and Mana of enemy pets are currently not affected by global modifiers from worldserver_config.

Ex.: With Rate.Creature.Normal.HP = 0,5,, a Crawler (pet of Murloc Hunters in Westfall) should about 170-180 instead of the normal 350 hp.

### Expected Blizzlike Behaviour

Modifiers from worldserver.conf should affect enemy pets in the same way as any other mobs.

### Source

_No response_

### Steps to reproduce the problem

1. Change global modifiers in worldserver.conf.
2. Target pet mob

### Extra Notes

Probably has the same root cause as https://github.com/azerothcore/azerothcore-wotlk/issues/9291
Health and mana formulas contain creature_template modifiers as floating values:

> float factorHealth = owner->GetTypeId() == TYPEID_PLAYER ? std::min(1.0f, cinfo->ModHealth) : cinfo->ModHealth;
        float factorMana = owner->GetTypeId() == TYPEID_PLAYER ? std::min(1.0f, cinfo->ModMana) : cinfo->ModMana;
 SetCreateHealth(std::max<uint32>(1, stats->BaseHealth[cinfo->expansion]*factorHealth));
        SetModifierValue(UNIT_MOD_HEALTH, BASE_VALUE, GetCreateHealth());
        SetCreateMana(stats->BaseMana * factorMana);
        SetModifierValue(UNIT_MOD_MANA, BASE_VALUE, GetCreateMana());

So it should probably work, or do we need an extra hook for worldserver.conf in Pet.cpp?

### AC rev. hash/commit

f13723097400d04cc9169dba1403255600bc575a

### Operating system

Windows 7 x64

### Custom changes or Modules

mod-learnspells
mod-autobalance
mod-transmog
mod-arac

### PR DESCRIPTION
**Pull request by UltraNix**
…y rank health rates.

Closes #11480

## Issues Addressed:

- Closes #11480

## Tests Performed:

- Not tested.

## How to Test the Changes:

More info [here](#11480)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
applying run-label as some tests are showing as cancelled

**Comment by Maelthyrr** [comment]
need to update, error compile (line 1290)

**Comment by Maelthyrr** [comment]
After fixing the errors on my side, I tested the PR and it works fine.

**Comment by Nyeriah** [comment]
image

**Pull request merged**
