### PR TITLE
fix(Core/Creature): Reduce z offset for automated spawn correction

### LINKED ISSUE #16839: Pets in Magical Menagerie (Dalaran) are shifted up, out of their cages and displays
### Current Behaviour

Pets in Magical Menagerie (Dalaran) are shifted up, out of their cages and displays. Examples of some of them:

https://0x0.st/H2Xf.png

### Expected Blizzlike Behaviour

Pets are in their cages and displays, not above them.

### Source

_No response_

### Steps to reproduce the problem

1. Enter Magical Menagerie
2. Observe.

### Extra Notes

_No response_

### AC rev. hash/commit

AzerothCore rev. 5c132654cd2f 2023-07-27 23:44:47 -0300 (master branch) (Unix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 2.
Server uptime: 29 minute(s) 32 second(s)
Update time diff: 1ms, average: 1ms.
Using SSL version: OpenSSL 1.1.1n  15 Mar 2022 (library: OpenSSL 1.1.1n  15 Mar 2022)
Using Boost version: 1.74.0
Using CMake version: 3.18.4
Using MySQL version: 100519
Found MySQL Executable: /bin/mysql
Compiled on: Linux 5.10.0-23-amd64
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /opt/acore/data/maps. Total size: 291014951 bytes
vmaps directory located in /opt/acore/data/vmaps. Total size: 658130721 bytes
mmaps directory located in /opt/acore/data/mmaps. Total size: 2192910844 bytes
Default DBC locale: enUS.
All available DBC locales: enUS 
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: 2023_05_23_00.sql
Latest WorldDatabase update: 2023_07_27_05.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-transmog

### Operating system

Debian 11 amd64

### Custom changes or Modules

mod-transmog

### PR DESCRIPTION
**Pull request by sudlud**
- this is necessary to correctly spawn creatures within small confines
- 0.42f is as good as 1.0f to detect and correct reasonable z errors in DB spawn data

## Changes Proposed:

This PR proposes changes to:
-  [x] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes #16839

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
I’d have removed it completely, but haven’t investigated what the z change was meant to address, so this is fine for the time being

**Comment by sudlud** [comment]
> I’d have removed it completely, but haven’t investigated what the z change was meant to address, so this is fine for the time being 

It adds 1.0f or now 0.42f to the spawn's z value and then tries to find the closest surface underneath.

If the spawn was already above that surface - nothing is being changed.

If the spawn was below that surface - it uses the surface z value + 0.1f as new z value.

Might help with spawns slightly sitting in the ground maybe.

**Comment by Meramaf** [comment]
image

This doesn't fix the toys on the shelves in Dalaran.

**Comment by Kitzunu** [comment]
This has nothing to do with that. They are a part of the world models.

**Comment by Kitzunu** [comment]
Oh now I see what you mean... Be more specific next time.

Also make a bug report and dont comment on random prs
Screenshot_20240116_132216_Chrome

**Pull request merged**
