### PR TITLE
fix (core): Null check the helpers

### PR DESCRIPTION
**Pull request by acidmanifesto**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
I'm not sure if this helps at all, you're still converting not checking object type, so if a creature casts a charge spell ToPlayer() will return null and it will lead to a crash.

```
if (ToPlayer())
   ToPlayer()->SetCanTeleport();
```
or
```
if (Player* player = ToPlayer())
   player->SetCanTeleport();
```

Should help

**Comment by Nyeriah** [comment]
Yes, sure, it should be ```m_caster->ToPlayer()```

It was just an example

**Comment by acidmanifesto** [comment]
> Yes, sure, it should be `m_caster->ToPlayer()`
> 
> It was just an example. Probably the same needs to be checked in the other PRs

im looking over the other, should still be fine already. I am still a bit curious how that crash was triggered.

**Comment by acidmanifesto** [comment]
@Nyeriah besides my sleep depervation you were right. good catch.

**Comment by RS-Degen** [comment]
This one too?

https://github.com/azerothcore/azerothcore-wotlk/blob/14eb63c2715a665be972aa771bd99cf48c816a0f/src/server/game/Entities/Unit/Unit.cpp#L13829

**Comment by acidmanifesto** [comment]
> This one too?
> 
> https://github.com/azerothcore/azerothcore-wotlk/blob/14eb63c2715a665be972aa771bd99cf48c816a0f/src/server/game/Entities/Unit/Unit.cpp#L13829

Nope.

**Review by Kitzunu — APPROVED** [review]

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
