### PR TITLE
feat(Core/Trainer): Implement ReqSpell

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Implement ReqSpell

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5399

## Tests Performed:

- Buillds
-  Tested in-game

## How to Test the Changes:

Use the field and see if you can learn a spell if you do not own the reqspell.

also check so that there is no difference in spells showing, before and after PR

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Okay, I know this is not ideal and not pretty, but it is a temporary fix for anyone that want to fix the other specialization professions.

What we need to do in the future, which I do not have time for in the next few weeks is to port https://github.com/TrinityCore/TrinityCore/commit/bf3ab6d9c4366dae1d34957813e3fbf40ac8532b for a better handling of trainer

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/5420

**Comment by pklloveyou** [comment]
The drawing before PR is green. After PR, you need to complete the assigned task before you can learn   
Tested

**Comment by Kitzunu** [comment]
I have started the work to import TC handling here https://github.com/azerothcore/azerothcore-wotlk/pull/5428 but will only work on it when I get spare time over...

So now we need to decide, either we wait until my new PR is completed. (Don't know when)
Or we use this PR until I am completed with the other one.

**Comment by pklloveyou** [comment]
All right, I've merged

**Pull request closed without merging**
