### PR TITLE
fix(apps/scripts): Add quotes for paths containing empty spaces

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
## CHANGES PROPOSED:
-  This PR tries to fix empty spaces in pathes but it's still not working correctly, but it's a start lol

## HOW TO TEST THE CHANGES:

- Use the db_assembler.sh inside a path containing empty spaces

## KNOWN ISSUES AND TODO LIST:

- [ ] Fix this for all cases @Yehonal 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
ok then i merge, can't hurt

**Comment by Kitzunu** [comment]
any update?

**Comment by BarbzYHOOL** [comment]
@Yehonal check

**Comment by locus313** [comment]
@BarbzYHOOL I been doing some testing of the db_assembler.sh with a space in the directory path and got it working now :) Here is the branch that has the changes:
https://github.com/locus313/azerothcore-wotlk/tree/db-assembler-path-spaces 

In my testing  I did find that we are going to have to update the modules include.sh and conf/conf.sh.dist. For the include.sh we currently have:
```bash
source $MOD_PATH_ROOT"/conf/conf.sh.dist"

if [ -f $MOD_PATH_ROOT"/conf/conf.sh" ]; then
    source $MOD_PATH_ROOT"/conf/conf.sh"
fi
```
will need to change it to:
```bash
source "$MOD_PATH_ROOT/conf/conf.sh.dist"

if [ -f "$MOD_PATH_ROOT/conf/conf.sh" ]; then
    source "$MOD_PATH_ROOT/conf/conf.sh"
fi
```
For the conf/conf.sh.dist we currently have:
```bash
DB_WORLD_CUSTOM_PATHS+=(
	$MOD_PATH_ROOT"/sql/world/"
)
```
will need to change it to:
```bash
DB_WORLD_CUSTOM_PATHS+=(
	"$MOD_PATH_ROOT/sql/world/"
)
```

Let me know if you want to merge the changes into this pr or if you want me to just open a new pr.

**Comment by Zoidwaffle** [comment]
@FrancescoBorzi : I believe this PR is obsolete as it was handled in PR #3716.

**Comment by Helias** [comment]
nice catch, I think too, I am closing this

**Comment by BarbzYHOOL** [comment]
yes i think so

**Pull request closed without merging**
