### PR TITLE
feat(DB/game_tele): Added Emerald Dream game_tele

### PR DESCRIPTION
**Pull request by Helias**
Added Emerald Dream game_tele and the instance Emerald Dream ID:169

### How to test this PR

Apply the sql code in this PR.

Use the following commands:
```
.tele EmeraldDream
.tele EmeraldStatue
.tele VerdantFields
.tele EmeraldForest
```

See the different zones ;-)

To see the Emerald Dream zone with textures use [this patch](https://mega.nz/#!59gywQBZ!mH3-7pTW_MSDIi-Eayc-aXVnBC__NtHDEJwYgtVbqiE).

Source: https://github.com/TrinityCore/TrinityCore/issues/16131

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Tested successfully.

**Comment by wowtbconline** [comment]
WoWScrnShot_060419_115030
WoWScrnShot_060419_115247
WoWScrnShot_060419_115655
WoWScrnShot_060419_120224
WoWScrnShot_060419_120444
WoWScrnShot_060419_120633
WoWScrnShot_060419_120716
WoWScrnShot_060419_121232
WoWScrnShot_060419_121241
WoWScrnShot_060419_121725
WoWScrnShot_060419_122019
WoWScrnShot_060419_122937
WoWScrnShot_060419_123001
WoWScrnShot_060419_123356
To contemplate the emerald Dream can be infinite...

**Comment by wowtbconline** [comment]
If you need my emerald dream patch, you can talk about it

**Comment by Helias** [comment]
awesome, it is released somewhere?

**Comment by FrancescoBorzi** [comment]
@wowtbconline awesome! it would be great if you could share it

**Comment by wowtbconline** [comment]
> Круто, это выпущено где-нибудь?

We made this patch ourselves.

**Comment by wowtbconline** [comment]
> awesome, is it released somewhere?

We made this patch ourselves.

**Comment by wowtbconline** [comment]
> @wowtbconline awesome! it would be great if you could share it

 I can give you the emerald dream patch in return mod-bg-slaveryvalley

**Pull request merged**
