### PR TITLE
Set molten core exit teleport location to in front of Lothos Riftwalker

### PR DESCRIPTION
**Pull request by ChrisCGalbraith**
## Changes Proposed:
-  Set MC exit teleport location to in front of Lothos Riftwalker

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10028

## Tests Performed:

- Tested in-game
- OS: Win10

## How to Test the Changes:

1. Teleport inside Molten Core
2. Run through raid instance teleporter inside Molten Core to exit the instance

## Known Issues and TODO List:

- None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Tested and work.

**Comment by Kitzunu** [comment]
Where are these values taken from?

**Comment by Nyeriah** [comment]
I've been meaning to sniff this but I never found the time + forgot :\

**Comment by ChrisCGalbraith** [comment]
> Where are these values taken from?

They aren't taken from anywhere specific. I placed myself in a reasonable position. If these can be sniffed then I can easily amend.

**Review by Kitzunu — APPROVED** [review]
Fine for now I guess....

**Pull request merged**
