### PR TITLE
feat(DB): skilltiers_dbc

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Create skilltiers_dbc table

## Tests Performed:

- None 

## How to Test the Changes:

1. 🤷 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by r-o-b-o-t-o — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
To test this I think that we need to run AzerothCore without DBC, we could use the DBCs only for the initial setup or for the first start

**Comment by Yehonal** [comment]
> To test this I think that we need to run AzerothCore without DBC, we could use the DBCs only for the initial setup or for the first start
> 
> Moreover, is needed to update this https://github.com/wowgaming/client-data/releases/tag/dbc_sql_v1 ? @Yehonal

This is deprecated and also contains fields that have been changed so it's not gonna work. The new way to export DBC to SQL is by using the node-dbc-reader: https://github.com/wowgaming/node-dbc-reader

You can easily export all the dbc with the entire dataset in sql by using that tool (with updated field names)

**Review by Yehonal — APPROVED** [review]

**Comment by Kitzunu** [comment]
Needs to be tested or no?

**Comment by Helias** [comment]
if you already tested it, for me we can merge

**Comment by Kitzunu** [comment]
I havent

**Comment by Helias** [comment]
I would prefer to merge it with one test at least :sweat_smile:

**Comment by Kitzunu** [comment]
Well assuming that loading DBC override was properly implemented in the first place, there is no reason for it not to work.

**Comment by FrancescoBorzi** [comment]
> Well assuming that loading DBC override was properly implemented in the first place, there is no reason for it not to work.

still why don't you just test it ? ^^

**Comment by Kitzunu** [comment]
because I dont know what the dbc does lol. Yehonal wanted me to add this, so I did

**Comment by Yehonal** [comment]
> because I dont know what the dbc does lol. Yehonal wanted me to add this, so I did

You just forgot to add the table in your PR causing bugs because of this missing table and we applied an hotfix for it, as far as I remember. it's not me wanted you adding this but it's just mandatory to do it when you add support to new DBCs. The test should have been done together with that PR (which apparently has not be tested properly though). For me you can merge it anyway

**Comment by Yehonal** [comment]
> > because I dont know what the dbc does lol. Yehonal wanted me to add this, so I did
> 
> You just forgot to add the table in your PR causing bugs because of this missing table and we applied an hotfix for it, as far as I remember. it's not me wanted you adding this but it's just mandatory to do it when you add support to new DBCs. The test should have been done together with that PR (which apparently has not be tested properly though). For me you can merge it anyway

Considering we're having some issues with some _dbc tables here: https://github.com/azerothcore/azerothcore-wotlk/issues/4312 @Kitzunu it'd be nice if you can generate at least some SQL to test this.

Here there's the guide on how to generate SQL for our DBC tables: https://www.azerothcore.org/wiki/how-to-import-dbc-data-in-db

**Comment by FrancescoBorzi** [comment]
what's the status of this PR?

**Comment by claudiodfc** [comment]
You should populate the Database with the DBC data:

````
INSERT IGNORE INTO skilltiers_dbc (`ID`,`Cost_1`,`Cost_2`,`Cost_3`,`Cost_4`,`Cost_5`,`Cost_6`,`Cost_7`,`Cost_8`,`Cost_9`,`Cost_10`,`Cost_11`,`Cost_12`,`Cost_13`,`Cost_14`,`Cost_15`,`Cost_16`,`Value_1`,`Value_2`,`Value_3`,`Value_4`,`Value_5`,`Value_6`,`Value_7`,`Value_8`,`Value_9`,`Value_10`,`Value_11`,`Value_12`,`Value_13`,`Value_14`,`Value_15`,`Value_16`)
 VALUES (2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (22,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (24,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (41,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (62,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (81,100,400,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (121,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (122,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (123,75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (124,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (125,200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (126,60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (127,25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (141,120,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (142,180,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (143,60,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (161,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,375,450,0,0,0,0,0,0,0,0,0,0),
 (181,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (182,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (221,30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (222,50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0),
 (223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,150,225,300,0,0,0,0,0,0,0,0,0,0,0,0);
```

**Comment by claudiodfc** [comment]
A note, we are loading `SkillRaceClassInfo` from the database but it's empty. This table only makes sence if we also populate it with data for the column `SkillRaceClassInfo.SkillTierID` to make sence for this PR, which is about SkillTiers.

**Comment by claudiodfc** [comment]
Should be tested with #9287

**Comment by claudiodfc** [comment]
I have no idea how to test this.
#### Test case
- Skillraceclassinfo with `SkillID` 98 is for `Language: Common`
- `SkillTierID` 21, which is the ID for `skilltiers_dbc` table with value 300.
- Edited the 300 to 69
- Checked in-game and nothing changed, not in the skills tab at least.

This might not be used by the core yet?

**Comment by Yehonal** [comment]
> 

There are 3 cases of DBCs:

1. those ones never used by the server 
2. those ones used by the server and that changes can be seen also client side 
3. those one used by the server but that require client changes to also have them displayed inside the client


the 1st case is untestable, while the other 2 can be just tested by checking if the server acts properly (despite of visible/not visible client changes).

Practical example: you can change the damage amount of a spell even though in the client you will still see the original value. That spell will just do the damage you have specified.

In this case I suppose you can just check if the cost changes accordingly to your value, once you practically consume the skill. 
Also we need confirmation that the original behaviour (with the empty table, so DBC only) is working as intended. 
In past we added table support for some DBCs and we had bugs because of column conflicts etc.
It should not be the case though

**Comment by claudiodfc** [comment]
That seems to be the cases @Yehonal . I changed the Skill from Holy to Holy shit and I could only check the skill name by using the GM command `.lookup skill holy`. So at least the DBCs were working for SkillLine before. That proves your point already by nothing changing client side.
I'll try to see if there's a skill that I can test by changing costs then.

**Comment by claudiodfc** [comment]
#### Progress
- Changed the `SkillRaceClassInfo.ID` 40 to have `SkillTierId` 21 which is by default 300 and used as a condition for Horde. Also changed it to 69.
- When creating a new character they can't speak. `You can't speak that language.` message is displayed.

**Comment by claudiodfc** [comment]
Can't have a real test for this, tried changing `SkillRaceClassInfo` to have several different SkillTiers but changing the SkillTiers values never change anything. Either setting a different max value for professions like Engineering or lowering the cost which should be their initial value, instead of 1 being 0.
Running the command for lookup skill also doesn't show any changes server side. I don't see any problem with merging this PR but it also won't change anything. First because the DBC table is empty and second because even if it wasn't empty, nothing would change.

**Comment by Yehonal** [comment]
> Can't have a real test for this, tried changing `SkillRaceClassInfo` to have several different SkillTiers but changing the SkillTiers values never change anything. Either setting a different max value for professions like Engineering or lowering the cost which should be their initial value, instead of 1 being 0. Running the command for lookup skill also doesn't show any changes server side. I don't see any problem with merging this PR but it also won't change anything. First because the DBC table is empty and second because even if it wasn't empty, nothing would change.

I can see that this DBC is only used here (ObjectMgr.cpp):

image

That return value apparently is never used by the core for conditions etc (but maybe I'm wrong), however, AC is an extensible framework, hence it can be used by some modules etc.

For now, I would consider this PR tested because the original behaviour is not touched and can be merged

**Comment by Kitzunu** [comment]
Ty

**Pull request merged**
