### PR TITLE
feat(DB): Import german quest_offer_reward texts from GTDB (Part 1/4)

### PR DESCRIPTION
**Pull request by Volgger**
I decided to split my translations and fixes into several tranches so that they can be checked more easily.

A total of ~ 9,000 German translations are missing from the quests which I would like to import over time. Any help is very welcome, just write me on Discord!

## CHANGES PROPOSED:
-  Import the first ~ 750 of a total of ~ 3000 German quest texts for table `quest_request_items_locale` from GTDB 

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
Since around 80% of the punctuation marks were missing from the GTDB and I compared them manually with the `quest_request_items`table and adjusted them from AC, I can confirm that they are the correct 3.3.5a strings.

- Imported on win 10 pro x64 with HeidiSQL without errors

## HOW TO TEST THE CHANGES:

Just import sql file and check some strings at your own. 

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Thank you for that. Have you tested ingame? Before that it was just in english?

What is GTDB?

**Comment by Endeffect-AT** [comment]
Of course I also checked some texts in-game. GTDB was a German database project for 3.3.5a TC. There were some projects, also for MaNGOS, none of them were completely finished.

**Comment by Stoabrogga** [comment]
This can be merged in my opinion. I checked the IDs and they don't exist yet for the locale "deDE", so the translations are better than no translations at all.

**Comment by Endeffect-AT** [comment]
Thx @Stoabrogga! The next part is almost ready!

**Comment by Endeffect-AT** [comment]
I had the smart idea to check the texts with a spell check. Small grammatical and spelling mistakes fixed, now everything is perfect :)

**Comment by Volgger** [comment]
It works in both versions. I just overlooked changing it from GTDB, otherwise I always prefer `'`

**Comment by BarbzYHOOL** [comment]
@Volgger thank you!

**Pull request merged**
