### PR TITLE
fix(Core/Spells): Forbid using charge if already charging to someone.

### LINKED ISSUE #6453: Warrior - Intercept/Charge Issues
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/917

If you use charge on target A then intercept target B while still charging to target A, target B will just take damage/get stunned, but your character will remain in the position of your first target.

Demo here: https://youtu.be/KqYU27mvCCA

Tester: confirmed, going both ways. First, charge then intercept:

https://user-images.githubusercontent.com/81782124/122675233-ab99db80-d217-11eb-8505-d3203ff6597f.mp4

Then using the second macro, intercept then charge. Sorry for the horrible crash zoom, but charge doesn't produce a nice visible damage number, only a swirly stun animation, and needed to make sure that was visible.

https://user-images.githubusercontent.com/81782124/122675340-177c4400-d218-11eb-83db-e78c4b02eb81.mp4

Note there has been some work done on Charge/Intercept recently in https://github.com/azerothcore/azerothcore-wotlk/pull/6421, but that doesn't seem to be related, it was about making them impossible to dodge/parry/block.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

This should not happen.
Every time you charge/intercept a target, your character must start charging towards that target.

##### SOURCE: 

don't think I need a source for this, it's pretty obvious it's not working as intended.

##### STEPS TO REPRODUCE THE PROBLEM:

1. You need 2 dummies in a straight line Dummy A and Dummy B
2. Set Dummy A as your focus target (target it and type /focus)
3. Target Dummy B, be in Battle Stance and spam this macro, it should be really easy to reproduce the bug 

/cast [@focus] Charge
/cast berserker stance
/cast intercept

##### EXTRA NOTES:

Can't test if the same happens if you reverse the spell order because I don't have the Juggernaut talent to be able to charge in combat, so please make sure you test that too.
To do that, learn bloodrage ability and use this macro

/cast [@focus] intercept
/cast battle stance
/cast charge

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99363481-warrior-intercept-charge-issues?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Fixed #6453

## Changes Proposed:
-  Cannot use another charge/intercept if already charging.

**Requires #7152**

## Issues Addressed:

- Closes #6453
- Closes https://github.com/chromiecraft/chromiecraft/issues/917

## Tests Performed:

- No tested

## How to Test the Changes:

1. You need 2 dummies in a straight line Dummy A and Dummy B
2. Set Dummy A as your focus target (target it and type /focus)
3. Target Dummy B, be in Battle Stance and spam this macro, it should be really easy to reproduce the bug

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]
Looks legit

**Review by Helias — APPROVED** [review]

**Comment by pklloveyou** [comment]
I hope someone can test it as soon as possible

**Comment by robbie018** [comment]
<h1>Before fix</h1>
I can indeed confirm the bug.
https://user-images.githubusercontent.com/65018032/127754720-f36b43ca-a3f4-4511-83e8-b8c31f4f9a56.mp4

<h1>After fix</h1>
Unfortunately the bug isn't fixed. If I'm correct I've pulled your code and compiled it. I also see the line of code you've added. But I can't see any fixes.
https://user-images.githubusercontent.com/65018032/127754745-add7e337-df1b-493a-a99a-d0874a716912.mp4

image

**Comment by pklloveyou** [comment]
It's right,

**Pull request merged**
