### PR TITLE
Fixed warning at server start related to transports

### PR DESCRIPTION
**Pull request by Kaev**
**Changes proposed:**
Fixed the following warning related to transports during server server start:
Warning: GetUInt32() on non-(medium)int field. Using type: SHORT.

MapEntryId is uint32 in DBC and code - Changed smallint to int

**Target branch(es):** master

**Issues addressed:** Part of #679

### CODE REVIEW

**Comment by ShinDarth** [comment]
please read:

https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files

also always leave an empty line at the end of source files, especially for SQLs

**Comment by Kaev** [comment]
Like this?
(Somehow GitHub doesn't show the empty line here, if you check the file in the repo it is there :s)

**Comment by ShinDarth** [comment]
Yes, that should be fine. Waiting for some tester feedback

**Comment by Rochet2** [comment]
This should be revertedAnyone remember what this fixed exactly?
Most of the code in core assumes uint16 for mapid.

So either all core types need to be changed for handling the map or just the one that caused the error attempted to fix in this PR.

**Comment by BarbzYHOOL** [comment]
The bug was ignored by everybody because you need to use "-DWITH_COREDEBUG=1" in cmake to notice a change ingame and in the console

So with that flag, it was really horrible bug.

**Pull request merged**
