### PR TITLE
Move area trigger storage from DBC to database

### PR DESCRIPTION
**Pull request by Kaev**
**Changes proposed:**
-  Moved area trigger storage from DBC to database
-  Renamed AreaTrigger to AreaTriggerTeleport (it was named wrong in the core)

**Target branch(es):** master

**Issues addressed:** Part of #584

### CODE REVIEW

**Comment by ShinDarth** [comment]
good job, waiting for tester feedback

**Comment by Kaev** [comment]
I tested it in the following ways:

Test 1
- .debug areatriggers
- go to Pit of Sauron
- enter and leave the instance to test AreaTriggerTeleport
- kill forgemaster and ikk
- on the path to the ice cave are multiple areatriggers that are triggered (see chat messages bcs of .debug areatriggers)

Test 2
- .debug areatriggers
- .tele area52
- walk out of Area 52 and an areatrigger will activate (see chat again)

**Comment by Yehonal** [comment]
Please could you merge latest updates from master and resolve conflicts?

**Comment by Kaev** [comment]
Will resolve the conflicts this weekend

**Pull request merged**
