### PR TITLE
Fix adduser/addgroup commands in dockerfile

### PR DESCRIPTION
**Pull request by michaeldelago**
## Changes Proposed:
-  adduser and addgroup commands in Dockerfile have `acore` hardcoded

## Issues Addressed:

- No issue found, but this was discussed in discord 

## Tests Performed:

- I haven't performed any tests

## How to Test the Changes:

1. Run command that should fail in previous setup
    ```bash
    $ docker compose --profile app build --build-arg DOCKER_USER=foobar
    ```

## Known Issues and TODO List:

- I need to test this change. I can't because I'm working right now. 

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
> I haven't performed any tests

@michaeldelago thanks for your contribution, however it would be nice if you can test it so we are sure that it works fine and we can merge it

**Comment by Kitzunu** [comment]
bump

**Comment by michaeldelago** [comment]
Should be able to get tests done this weekend.

**Comment by michaeldelago** [comment]
This has been tested and is confirmed working.

Testing methodology is standard:

1. `./acore.sh docker build`
2. `./acore.sh docker start:app`
3. AzerothCore should come up without anything interesting happening

**Comment by Kitzunu** [comment]
thanks for the pr

**Pull request merged**
