### PR TITLE
fix(DB/gameobject): Import Vmangos herbs for Old World starter zones.

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  Populates starter zones with herb nodes from Vmangos
- Excludes Teldrassil since it was done at https://github.com/azerothcore/azerothcore-wotlk/pull/10170
- **temporary** fix until a thorough reconstruction can be made

## Issues Addressed:

- Closes 

## SOURCE:

Vmangos and
https://github.com/vmangos/core/pull/1500

## Tests Performed:

- Tested ingame. Starter zones are more populated. Cleaned out Durotar, nodes respawned after 15min in different locations.

## How to Test the Changes:

1. `.tele Elwynn` `.tele durotar` `.tele mulgore` `.tele dunmoro` `.tele tirisfal`
2. `.aura 2383`

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I also made a revert file. I don't know where I should upload it to so feel free to ask me if you want it.

**Comment by ZhengPeiRu21** [comment]
This is a great PR! This has been needing a fix for a long time. Thank you for do this work.

**Comment by Gultask** [comment]
Neifion's method using Areas within zones is more correct. AC generally uses 'master' pools for entire zones, while Vmangos uses 3-4 pools per zone, one for Peacebloom, another for Silverleaf, for example.

Also, thanks, Zheng! <3
I made another .sql file prior to this one containing every node in the Old World but:
1. If made through this method, it'd leave a massive gap in the `gameobject` table as I'd move all spawns way higher.
2. It'd take forever to test & be approved
3. It was a bit messy overall :p 

If this one is successful I might come back and finish other zones.

**Comment by Gultask** [comment]
Done 5 complete runs of Elwynn forest now, finding between 60-70 nodes each run, every time it respawns.

Although I have noticed a possible problem with pooling: It seems that a lot of nodes are respawning only *after* I start gathering others. For example. I waited the 15 min respawn timer, by then every node that should've spawned has respawned, right? But not exactly. I started my run in Heroes' Vigil, the island in Stone Cairn Lake, and there were no spawns there. After returning there following a 5-min gathering run, I saw that some nodes spawned in the island.
So either I don't know how pooling works or there might be *something* fishy?

Either way I don't know what else to test at this point. I also have the full Old World query ready.

**Comment by temperrr** [comment]
tested

looks good, not 100% blizzlike but better then what we have (tested dun morogh)

**Review by temperrr — APPROVED** [review]

**Pull request merged**
