### PR TITLE
feat(DB/game_tele): Hidden Places

### PR DESCRIPTION
**Pull request by LukasVolgger**
## CHANGES PROPOSED:
- Few minor improvements to existing teleports
- Add secrets places, unfinished regions and other to ```game_tele``` table

**Source: TrinityAdmin GM Addon**

## ISSUES ADDRESSED:
- None

## TESTS PERFORMED:
- Applied SQL Script
- Tested all teleports

## HOW TO TEST THE CHANGES:

**1. Apply SQL script**
**2. To test you need to have an GM Account (account set gmlevel "accname" 3 1)**
**3. Test all the following teleports with .tele ID / tele Name and enjoy:**

- 233 (KarazhanCrypts)
- 241 (DalaranCrater)
- 703 (Orgrimmar)
- 1263 (Undercity)
- 1426 (EmeraldDreamStatue)
- 1428 (EmeraldDreamForest)
- 1451 (AzsharaAllianceEntrance)
- 1452 (AzsharaHordeEntrance)
- 1453 (JailAlliance)
- 1454 (JailHorde)
- 1455 (AhnQirajBacklands)
- 1456 (BlackcharCaveInside)
- 1457 (BlackwingLairOutside)
- 1458 (DeadminesStrangePlace)
- 1459 (DeeprunTramDeeprunDivers)
- 1460 (DeeprunTramNessy)
- 1461 (DeeprunTramUnderwaterLocation)
- 1462 (GillijimsIsle)
- 1463 (NaxxramasOutside)
- 1464 (NewmansLanding)
- 1465 (OrtellsHideoutDunMorogh)
- 1466 (SilverpineForestShadowfangKeep)
- 1467 (StratholmeOutside)
- 1468 (TopOfBlackrockMountain)
- 1469 (WetlandsHiddenSpot)
- 1470 (ZulGurubAlterOfStorms)
- 1471 (ZulGurubStranglethornVale)
- 1472 (ArathiDwarvenFarm)
- 1473 (Gilneas)
- 1474 (EasternPlaguelandsUnfinishedRegion)
- 1475 (GrimBatolWatchPost)
- 1476 (QuelThalas)
- 1477 (QuelThalasTower)
- 1478 (SilithusSouthernFarm)
- 1479 (SilithusUnfinishedRegion)
- 1480 (StranglethornValeUnfinishedRegion)
- 1481 (TheForbiddingSeaIslands)
- 1482 (TirisfalGladesUnfinishedRegion)
- 1483 (WetlandsDwarvenVillage)
- 1484 (BadlandsUnfinishedRegion)
- 1485 (HyjalBlizzardConstructionCo)
- 1486 (HyjalCrater)
- 1487 (HyjalCaveInside)
- 1488 (HyjalCaveOutside)
- 1489 (HyjalTheWorldTree)

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
nice addition @LukasVolgger ! well done

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Review by Hacaw — APPROVED** [review]
I successfully tested this with all the locations provided by author.
The code looks fine from my point of view.

TESTING
---
Applied sql-script file to my database-container.
Start using .tele [ID] and all the locations match with their description.

Off-Topic-1: @LukasVolgger , while testing this I was amazed that I wasn't aware of some of the location, nice, good job. But from productivity perspective for some-of them which are only gm-related or scraped blizz work, I guess there are going to be used for custom events ? 

Off-Topic-2: @FrancescoBorzi, @LukasVolgger until now I used lookup taxi nodes / go taxinode (but it seems there are related to dbc files), I guess it would be better to start using lookup tele / tele from now on ? Are there more waypoints available for tele commands? 

CONFIG
---
COMMIT: f62693021fa83b270eb82ce624a611ab6337917e
OPERATING SYSTEM: Win10 + Docker for Desktop
MODULES / CUSTOMIZATION: None

**Comment by LukasVolgger** [comment]
Tanks for your review and tests! Good job! 

The purpose of these hidden teleports is exactly as you were allowed to experience.  Hardly anyone knows these places and if they are not noted down somewhere, it will stay that way.  I e.g.  I'm working on a teleport mod for AC which uses all these teleports as a premium item for players so that they can explore the world more than many others.

**Comment by Zoidwaffle** [comment]
I just want to add that it's a great idea to make access to all these places easier - I have only seen a few of these myself and I look forward to checking out them all :muscle:

**Pull request merged**
