### PR TITLE
fix(Scrpits/Quest): Improve Recharging the Batteries

### PR DESCRIPTION
**Pull request by grimgravy**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15802
- Closes https://github.com/chromiecraft/chromiecraft/issues/5327

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers @azerothcore/testers can anyone please check this?

**Review by Nefertumm — APPROVED** [review]

**Comment by GastonCK** [comment]
Tested, working good
The item is usable when the phase hunter is low hp and the text "Phase hunter is very weak" appears in chat.
Killed it in different ways: last hit with dot, with direct damage, with recharge battery debuff and without it aswell. 
Nothing wierd happened, all good. also tested creature reset behaviour and it reseted well.
WoWScrnShot_070123_123623

**Comment by Gultask** [comment]
@grimgravy usually we handle quests through SAI, what's the reason you needed to use cpp? I'm just curious about what was needed

**Comment by grimgravy** [comment]
> @grimgravy usually we handle quests through SAI, what's the reason you needed to use cpp? I'm just curious about what was needed

is necessary

**Comment by elthehablo** [comment]
> > @grimgravy usually we handle quests through SAI, what's the reason you needed to use cpp? I'm just curious about what was needed
> 
> is necessary

can you explain why it is necessary? I am trying to do the same for another quest and going from this as an example

**Comment by elthehablo** [comment]
also fix title pls x)

**Comment by Nefertumm** [comment]
> Why are you using old spellscripts?

He is using the old spellscript because the spell has an aurascript and a spellscript

**Comment by Kitzunu** [comment]
RegisterSpellWithAuraScript

**Comment by grimgravy** [comment]
> > > @grimgravygeralmente lidamos com missões através da SAI, qual é o motivo pelo qual você precisava usar o cpp? Só estou curioso sobre o que era necessário
> > 
> > 
> > é necessário
> 
> você pode explicar por que é necessário? Estou tentando fazer o mesmo para outra missão e saindo disso como exemplo



> > > @grimgravygeralmente lidamos com missões através da SAI, qual é o motivo pelo qual você precisava usar o cpp? Só estou curioso sobre o que era necessário
> > 
> > 
> > é necessário
> 
> você pode explicar por que é necessário? Estou tentando fazer o mesmo para outra missão e saindo disso como exemplo



> > > @grimgravy usually we handle quests through SAI, what's the reason you needed to use cpp? I'm just curious about what was needed
> > 
> > 
> > is necessary
> 
> can you explain why it is necessary? I am trying to do the same for another quest and going from this as an example

SAI has its limit, although it is great option to use, but remember that it has its limit, not everything is used by it

**Comment by grimgravy** [comment]
@elthehablo, SAI has its limit, although it is great option to use, but remember that it has its limit, not everything is used by it

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
