### PR TITLE
Move the Ashbringer event AI of the Bloody Monastery mob to Smartai

### PR DESCRIPTION
**Pull request by fangshun2004**
Move the Ashbringer event AI of the Bloody Monastery mob to Smatai
Modify the distance of the "Scarlet Wizard" Cast Arcane Explosion
The Bloody Guards in the church, like Blizzard, trigger the event and face the player, stand up, kneel, and Talk
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [x] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

If your pull request promotes complex changes that require a detailed explanation, please describe them in detail specifying what your solution is and what is it meant to address.

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**
＃15218
## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by fangshun2004** [comment]
Keira3 doesn't seem to be editing properly `(4300, 0, 1, 0, 0, 106, 0, 100, 0, 2000, 6000, 7000, 11000, 0, 10, 11, 8439, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Scarlet Wizard - In Combat - Cast Arcane Explosion'), `
I don't know if this is right

**Comment by fangshun2004** [comment]
The script content triggered by the timing trigger is the same, I don't know if I can use the same script ID. If  can, how to write a comment

**Review by Kitzunu — DISMISSED** [review]

**Comment by Kitzunu** [comment]
Where is this script taken from?

**Comment by fangshun2004** [comment]
> Where is this script taken from?

Script from the pull request from #15218。. I moved values from his script into smartai. Added standing motion. I don't think there should be miscellaneous control code in the script

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
