### PR TITLE
Fix Quest 11879 Kaw the Mammoth Destroyer. - CodigoWoW.

### PR DESCRIPTION
**Pull request by MarioJvPz98**
Referenced commit(s): c513da85c892cc68a0ac424d8914a5531ffc8786

## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [x] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes 
[(Quest\11879) kaw the mammoth destroyer not work again #18181](https://github.com/azerothcore/azerothcore-wotlk/issues/18181)
## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [x] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [x] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

-- [NexXuZ_R](https://github.com/MarioJvPz98)
-- [CodigoWoW](https://github.com/Codigottv)
## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [x] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
Hello. Looks like the last commit on master joined your PR so we need that file removed.

Also you have a part commented out at the bottom.

Thanks for the PR

**Comment by MarioJvPz98** [comment]
Hello Dan. It is always good to help and give back a little of everything you do for all of us who play and love this great game. Now, a question, why do you mark it with X and not with the check? (I didn't use github to contribute, so for the moment I'm taking the shot)

**Comment by elthehablo** [comment]
> Hello Dan. It is always good to help and give back a little of everything you do for all of us who play and love this great game. Now, a question, why do you mark it with X and not with the check? (I didn't use github to contribute, so for the moment I'm taking the shot)

Hi mate. I didn't mark anything. These are our automatic workflow jobs that check whether your code was up to standard. we check, among others, codestyle, worldserver start up with sql statement applied, etc.

**Comment by MarioJvPz98** [comment]
No, I was not referring to the fact that you directly marked it for me, but rather that the page or the bot marked it that way, but I also assumed that it was due to a previous review and things like that, in the same way, thank you very much to everyone who You work to make every day better. Thank you so much! :)

**Comment by elthehablo** [comment]
So for this to work you can do things:

1. Close this PR, start off from a clean updated branch and open a new PR (just copy paste all sql lines in a new file)

2. Rebase the branch such that the first commit is not included

Idk how familiar you are with git, but no offense, judging by this mistake, which I have made myself a few times, I think the first option is the easiest

**Comment by elthehablo** [comment]
> OK it's good. I don't use Git much, I would think the basics, but I will open another PR to see how it goes, although I followed all the steps in the contribution guide and was able to do them without any problem. But the first PR was really bad, I'll try again from a clean branch. In any case,
> If we could talk via PM for any questions about the process that I may be missing and if you could help me, I would appreciate it!

Yeah sure you can hmu on Discord if you want ElDiablo on AzerothCore disc

**Pull request closed without merging**
