### PR TITLE
fix(DB/Installation):  key duplicate during import of SQL

### PR DESCRIPTION
**Pull request by franc01s**
## Changes Proposed:
- multiple duplicate entry found during DB update 
 

## Issues Addressed:

- #12097

## Tests Performed:

- Installation ran fine now 

## How to Test the Changes:

1. Install application from scratch

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by lord-spirit** [comment]
Awesome. Was able to finally get the docker installation to work using these updates. ty @franc01s

**Review by lord-spirit — COMMENTED** [review]
lgtm

**Review by marcelhas — APPROVED** [review]
I tested this commit by commit and each commit solved a SQL problem I encountered during the docker setup when running `./acore.sh docker start:app`.

With these changes I can finally run the server! Thanks @franc01s!

**Comment by Kapel** [comment]
I've also been able to run the server without any errors thanks to this one. The database migration went smooth.

**Comment by dustxdustx** [comment]
Approve please. I waiting for this bug fix...

**Comment by Kitzunu** [comment]
superseded by https://github.com/azerothcore/azerothcore-wotlk/commit/3daa8e2146b97346c61b08f5d23751e27f8692f2

**Pull request closed without merging**
