### PR TITLE
fix(DB/Spell): Correct Effect of all Summon dbc spells

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## SOURCE:

TC

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Fun one to test, I'm sure.

**Comment by Gultask** [comment]
What's that word mean?

**Comment by Gultask** [comment]
But for real, if I'm correct then all of these are unused. Since they all used the wrong effect, 41 (JUMP) instead of 28 (SUMMON/SPAWN)

**Comment by heyitsbench** [comment]
A TC commit would help with reasoning. 😛

**Comment by Gultask** [comment]
It's all taken from the most recent DB snapshot. May not be 1:1 actually.
Essentially up until now we either: hacked SummonCreature or just fixed it like this in the dbc

**Comment by Gultask** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/6124

omg... see?
```
30954, -- Free Webbed Creature
30955, -- Free Webbed Creature
30956, -- Free Webbed Creature
30957, -- Free Webbed Creature
30958, -- Free Webbed Creature
30959, -- Free Webbed Creature
30960, -- Free Webbed Creature
30961, -- Free Webbed Creature
30962, -- Free Webbed Creature
30963, -- Free Webbed Creature
31010, -- Free Webbed Creature
```

**Comment by heyitsbench** [comment]
> omg... see?

Legacy scripts? :')

**Comment by Kofmy** [comment]
degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates degenerates

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
