### PR TITLE
fix(Core/Config): add support '#' for password and etc

### LINKED ISSUE #4781: Cannot connect to Database if password uses special character
##### CURRENT BEHAVIOUR:
You can no longer use `#` in Passwords since pull #4704

##### EXPECTED BEHAVIOUR:
Being able to use `#` (and anything else) for safer passwords ofc. :)

##### STEPS TO REPRODUCE THE PROBLEM:
1. Use a strong password and include a `#`
2. Fail to start server because it cannot open the database pool. :C
3. :3

##### EXTRA NOTES:
It's no big deal to change a password and remove the "#" if needed but it should work as before so people can actually use very stronk passwords. :D

Also related Issue (closed with pull): https://github.com/azerothcore/azerothcore-wotlk/issues/4748

##### AC HASH/COMMIT:
60d684282b602addfcb666cc970f01f700732b37

##### OPERATING SYSTEM:
Ubuntu 18.04

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97032522-server-fails-connecting-to-database-with-in-password-string?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #4781

## Tests Performed:
image

## Target Branch(es):
- [x] Master

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
@D3thw0lf try this

**Comment by D3thw0lf** [comment]
Sadly it's still not working. Just use one ``#`` in your password for your database e.g. ```thisismy#secret``` and no other ```#``` in the same line. If I add another comment ```#``` behind the password stuff it starts.

Example (not working):
```WorldDatabaseInfo     = "localhost;3306;root;supersecret#password;world"```

Example (working since change):
```WorldDatabaseInfo     = "localhost;3306;root;supersecret#password;world" #```

**Comment by Mitradis** [comment]
remove all this block:
size_t found = line.find_last_of('#');
if (found != std::string::npos)
line = line.substr(0, found);
why this needed? if # used in inside string this is error whoever allowed it

**Comment by Winfidonarleyan** [comment]
> remove all this block:
> size_t found = line.find_last_of('#');
> if (found != std::string::npos)
> line = line.substr(0, found);
> why this needed? who will use # in end of string for commenting??? just stuped.

#4781

**Pull request closed without merging**
