### PR TITLE
Fix overlapping mailbox in undercity (Trade Quarter, south)

### PR DESCRIPTION
**Pull request by Stoabrogga**
**Changes proposed:**
There are two overlapping mailboxes in Undercity, south Trade Quarter. Delete one of them.

**Target branch(es):** master

**Tests performed:** tested build incl. DB update, tested in-game

**Known issues and TODO list:** none

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
In GM mode only no? I've seen some of them in Dk zone too

**Comment by Stoabrogga** [comment]
I normally don't use GM mode. The "double-mailbox" is always there, just looks awful.

**Comment by kraftmatic** [comment]
Verified that this fixes the double mailbox in Undercity.
6adlv4r

**Comment by BarbzYHOOL** [comment]
Thank you both :)

**Pull request merged**
