### PR TITLE
Fix(scripts/paladin) infusion of light proc

### PR DESCRIPTION
**Pull request by pklloveyou**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/11931

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
@Nyeriah @UltraNix

**Comment by pklloveyou** [comment]
I used it on my project and server on April 7, 2022

**Comment by pklloveyou** [comment]
Nobody needs it? Then I'll turn it off

**Comment by Nyeriah** [comment]
@pklloveyou our availability during the weekdays may vary a lot due to college/work/real life responsibilities. I apprecite your willingness to help and urge you to please be patient until one of us has the time to look into it.

This PR is closer to what I had in mind to address this issue

Tagging you here too so you can check it @UltraNix

**Review by UltraNix — APPROVED** [review]

**Comment by UltraNix** [comment]
This PR is the correct one.

**Comment by Meramaf** [comment]
Tested and work to ;)

**Pull request merged**
