### PR TITLE
fix(DB/Gameobject): add chest pooling to solid chests in Duskwood

### LINKED ISSUE #6457: Duskwood - Missing Chest Pooling
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [ ] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/913

Multiple chests are active at the same time in the same area.

Around Raven Hill Cementary

85666 (Entry: 2850) - [Solid Chest X:-10205.700195 Y:170.328995 Z:27.242100 MapId:0] 
18572 (Entry: 2850) - [Solid Chest X:-10300.400391 Y:-18.723301 Z:44.225201 MapId:0] 
85665 (Entry: 2850) - [Solid Chest X:-10431.599609 Y:-22.177299 Z:47.503300 MapId:0] 
85667 (Entry: 2850) - [Solid Chest X:-10577.000000 Y:-53.329201 Z:36.798302 MapId:0]
85808 (Entry: 2850) - [Solid Chest X:-10698.000000 Y:-104.122002 Z:37.992298 MapId:0] 

Random chests in the woods
33475 (Entry: 2850) - [Solid Chest X:-10835.700195 Y:-568.281006 Z:36.557400 MapId:0]  
85807 (Entry: 2850) - [Solid Chest X:-10759.299805 Y:-587.221008 Z:36.881401 MapId:0] 

Near the Ghost Mary
17033 (Entry: 2850) - [Solid Chest X:-10773.900391 Y:-1378.969971 Z:38.946800 MapId:0] 
85809 (Entry: 2850) - [Solid Chest X:-10792.299805 Y:-1377.219971 Z:39.027000 MapId:0]
85810 (Entry: 2850) - [Solid Chest X:-10819.799805 Y:-1384.349976 Z:44.255199 MapId:0]  

In the woods north of Darkshire
85663 (Entry: 2850) - [Solid Chest X:-10178.599609 Y:-1023.049988 Z:27.637800 MapId:0]
85839 (Entry: 2850) - [Solid Chest X:-10173.099609 Y:-831.416992 Z:41.919300 MapId:0]  
18577 (Entry: 2850) - [Solid Chest X:-10170.799805 Y:-763.898010 Z:41.646400 MapId:0] 

Tester: confirmed, ran around and the zone was practically knee deep in Solid Chests. Apart from those above, I also found 85765, 18562, 85844, 18547, 85675, and 63361.

Not as bad as it looks, as one of these dots was a melon juice barrel, but 3 chests so close is still bad.
WoWScrnShot_062021_232252

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Usually only 1 chest should be active at a time in a sub zone. 

##### STEPS TO REPRODUCE THE PROBLEM:

1.  Go to any of the locations listed above, and you can see all the chests.

##### EXTRA NOTES:

There are several locations I haven't checked in Duskwood, since my level is too low. so there could be more locations having issues.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99363478-duskwood-missing-chest-pooling?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by jamadaha**
## Changes Proposed:
-  Add chest pooling to solid chests in Duskwood
-  Set spawn time to 7200s (As most of them were before, but some had different spawn times)

## Issues Addressed:

- Closes #6457 

## Tests Performed:

- Performed the tests as described in how to test the changes

## How to Test the Changes:

1. Apply SQL
2. There should be no deleted pool templates
3. Check that the pool templates are added correctly 
    - There should be pool templates with entry 11671, 11672, 11673, 11674 and 11675
    - They should all have a limit of 1
    - Entry 11671, 11672, 11673, 11674 and 11675 should have descriptions mentioning Raven Hill Cementary, Duskwood, Ghost Mary, Darkshire and VulGol respectively.
4. There should be no deleted pool gameobjects
5. Each pool should contain the GUIDs as specified in step 3 and proposed changes, each with a distinct description matching their corresponding zone.
6. These GUIDs should be in no other pools.
7. Check in game for each zone that only one chest has spawned

## Known Issues and TODO List:

- The solid chest described in the issue closed, with GUID 63361 is a herb beside a solid chest.
- The solid chest with GUID 85765 described in the issue closed isn't added to a pool, it sits in a sub zone by itself.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — CHANGES_REQUESTED** [review]
Please add a new line at the end

**Comment by jamadaha** [comment]
@LukasVolgger There was already an empty line at the end of the file, how many should there be?

**Comment by LukasVolgger** [comment]
> @LukasVolgger There was already an empty line at the end of the file, how many should there be?

Only one. I checked Github on web and mobile and until your last commit there was no empty line. See my screens:

**Comment by jamadaha** [comment]
If there were no newline wouldn't it look like this?
image

**Comment by LukasVolgger** [comment]
I always check the changed file on web because the mobile app lied to me so many times. 

Coincidentally I still have your first commit open and it looked like this:

**Comment by jamadaha** [comment]
In that first commit, there was still a newline at the end of the source file
image
So should there be a single newline at the end of the source file as displayed above. Or in GitHub, where that would mean two newlines in the source file, as seen in the latest commit:
image

**Comment by LukasVolgger** [comment]
Summoning @FrancescoBorzi !

What's the right path?

**Comment by FrancescoBorzi** [comment]
@LukasVolgger I was thinking the same as:

> > > @LukasVolgger There was already an empty line at the end of the file, how many should there be?
> > 
> > 
> > Only one. I checked Github on web and mobile and until your last commit there was no empty line. See my screens:
> 
> If there were no newline wouldn't it look like this?
> image
> 
> While with a newline it looks like
> image
> 
> In the latter there is an empty line at the end of the source file

**Comment by LukasVolgger** [comment]
> @LukasVolgger I was thinking the same as:
> 
> > If there were no newline wouldn't it look like this?
> > image
> > 
> > While with a newline it looks like
> > image
> > 
> > In the latter there is an empty line at the end of the source file
> 
>  

You check this on mobile?

**Comment by FrancescoBorzi** [comment]
> > @LukasVolgger I was thinking the same as:
> > > If there were no newline wouldn't it look like this?
> > > image
> > > While with a newline it looks like
> > > image
> > > In the latter there is an empty line at the end of the source file
> 
> You check this on mobile?

no, I mostly use desktop

**Review by LukasVolgger — APPROVED** [review]

**Pull request merged**
