### PR TITLE
fix(Core/Maps): GetCollisionHeight and Z_OFFSET_FIND_HEIGHT

### PR DESCRIPTION
**Pull request by locus313**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Si1ker** [comment]
This PR fixes:

image

image

**Comment by Yehonal** [comment]
The reason why this is working is because most of the creatures have a collisionheight of ~2:

https://wow.tools/dbc/?dbc=creaturemodeldata&build=3.3.5.12340#page=1&colFilter[0]=49

In this link you can see the human male display info that has a collision height of 2.031

I don't think this is the way to go tbh

**Comment by Yehonal** [comment]
Also hacki did the same change here: https://github.com/azerothcore/azerothcore-wotlk/pull/5775

**Comment by morpheux** [comment]
Just applied the code, things are better. Blood Queen still on the ground.

**Comment by FrancescoBorzi** [comment]
@Yehonal @Locus313 wouldn't be better to merge this while we wait for a better solution?

**Comment by Si1ker** [comment]
> @Yehonal @locus313 wouldn't be better to merge this while we wait for a better solution?

@FrancescoBorzi I support the idea.

**Comment by locus313** [comment]
> @Yehonal @Locus313 wouldn't be better to merge this while we wait for a better solution?

Yeah i agree, it may not address all cases but does address some of the new bug reports we been seeing.

**Comment by Yehonal** [comment]
I'd say: would be better to work on a concrete/final solution now than to apply a workaround that will only make it more difficult to spot the bug later.

Instead, you could just suggest people that are having this issue to apply this PR by pulling it

**Comment by speedrunz** [comment]
i'm not sure if this is related but some of the mobs in LK encounter (10man normal) such as Raging Spirits sometimes goes below the ground.

**Comment by morpheux** [comment]
> i'm not sure if this is related but some of the mobs in LK encounter (10man normal) such as Raging Spirits sometimes goes below the ground.

its related. This PR Fixes it but brings other problems with it.

**Comment by FrancescoBorzi** [comment]
> I'd say: it would be better to work on a concrete/final solution now instead of applying a workaround that will only make it more difficult to spot the bug later.
> Instead, you could just suggest people that are having this issue to apply this PR by pulling it

@Yehonal I'd prefer to instead merge this now and keep the master as stable and playable as possible.

I agree we should also fix it properly, but it looks like no one is going to work on this anytime soon (correct me if I'm wrong).

So better merge this now and open a new issue describing the problem that still needs to be fixed. Can you please take care of this? I'll apply a bounty on it so we can surely not forget about it ;)

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by speedrunz** [comment]
@morpheux I tried this PR but the Raging Spirits still falls.

**Comment by Yehonal** [comment]
> @morpheux I tried this PR but the Raging Spirits still falls.

could you provide more details? the entry of the creature, the position etc.

**Comment by speedrunz** [comment]
here's the db info of the creature.

INSERT INTO `creature_template`(`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `modelid1`, `modelid2`, `modelid3`, `modelid4`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `scale`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `spell_school_immune_mask`, `flags_extra`, `ScriptName`, `VerifiedBuild`) VALUES (36701, 39302, 39303, 39304, 0, 0, 16946, 0, 0, 0, 'Raging Spirit', '', '', 0, 83, 83, 2, 14, 0, 2, 1.42857, 1, 3, 0, 66.4, 2000, 2000, 1, 1, 1, 0, 2048, 0, 0, 0, 0, 0, 0, 6, 40, 0, 0, 0, 0, 0, 0, 0, '', 0, 3, 1, 53.968, 1, 1, 0, 151, 1, 650854271, 0, 1073741824, 'npc_raging_spirit', 11159);


i'll add more info when I re-do the test again.

**Comment by speedrunz** [comment]
Blood Queen Lanathel on 10man mode is also below the ground.
-> https://imgur.com/a/Dp1DsJw

**Comment by speedrunz** [comment]
Additional Info on ICC 10man normal mode:
- When LK reaches below 40%, he goes to the mid and casts Remorseless Winter (probably he changes the platform? not sure). This is where the Raging Spirits and other mobs e.g. ghouls fall.
- This is also where the upcoming anti-cheat falsely detects us as FlyHackers and kicks us
--> more info on the upcoming anticheat overhaul --> https://github.com/azerothcore/mod-anticheat/pull/32

**Comment by FrancescoBorzi** [comment]
@Yehonal @speedrunz please open a new issue with all the remaining problems after this PR.

**Pull request merged**
