### PR TITLE
fix(Core/Spells): Improvements to Far Sight spell:

### LINKED ISSUE #6368: Shaman "Far Sight" camera not working properly on multiple casts
Original report(s) combined from Chromiecraft https://github.com/chromiecraft/chromiecraft/issues/870 

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [x] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

There seems to be several issues with Far Sight. When double casting it to jump to far away or out of direct line of sight locations. First during the second cast the camera jumps back to your character before going to the desired location. 

Second, if you don't interrupt the channeling and let it run out, your camera stays to where you previously used Far Sight- you're first cast point- and you're stuck there unless you cast it again and interrupt to reset the camera https://youtu.be/jj3B8W1mW5o

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Far Sight should cast and recast without jumping back to the player. https://youtu.be/CTnTtXcqTHU
Once the channeling run out it should reset your camera back to the player's character.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Use Far Sight
2. Use Far Sight again while the current one is still being channeled
3. Notice the camera
4. Let the second cast run out
5. Notice the camera
6. Cast again and interrupt to reset the camera

##### EXTRA NOTES:

N/A.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/34da0cda5195dede48cb0406b23248330d6249cb

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99276195-shaman-far-sight-camera-not-working-properly-on-multiple-casts?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
Far Sight should not interrupt while casting another spell.
Corrected setting Far Sight as an active object.
Fixed grid activation range for active dynamic objects.
When Far Sight is over, the camera should be reset to player.
Enable swapping camera between Far Sight and Sentry Totem.
Fixes #6368

## Issues Addressed:

- Closes #6368
- Closes https://github.com/chromiecraft/chromiecraft/issues/870
- Closes https://github.com/chromiecraft/chromiecraft/issues/1019

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

Use Far Sight
Use Far Sight again while the current one is still being channeled
Notice the camera
Let the second cast run out
Notice the camera
Cast again and interrupt to reset the camera

Put down a sentry totem
Cast far sight
See that the camera does move to far sight spot.
Cancel far sight
Camera is again on sentry totem

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by avarishd** [comment]
- [x] Camera resets upon letting the channel end/canceling it
- [x] Camera can be swapped between Far Sight and Sentry Totem (Odd interaction, look below)
- [ ] Camera flickers back to player upon chain casting Far Sight [Video](https://gyazo.com/71874a9848c8ed82bb3ea0ffc6bbd748)
---
 Unknown/Odd: 
- [ ] If there is a Sentry Totem out and then you let Far Sight end/cancel it OR cast any other spell, the camera will be reset to the totem, regardless of which POV (Character or Totem) you casted Far Sight from. [Video](https://i.gyazo.com/b4518391b1695ead8eae3897ec4c42e3.mp4)
- [ ] When switching between Far Sight and Sentry Totem, the camera is placed on the player, not the totem [Video](https://gyazo.com/38df45edcafe198e17061174d0c96981)
----
Odd behaviour that may or may not be a part of the pr
- Far sight despawns totems when casted "too far" [2009 Video](https://youtu.be/X1RcSHnPs2Q)

**Comment by UltraNix** [comment]
@avarishd 
`Camera flickers back to player upon chain casting Far Sight ` 
Fixed

`When switching between Far Sight and Sentry Totem, the camera is placed on the player, not the totem
`If there is a Sentry Totem out and then you let Far Sight end/cancel it OR cast any other spell, the camera will be reset to the totem, regardless of which POV (Character or Totem) you casted Far Sight from.`
Not fixable due to how client handle far sight viepoints

`Far Sight sometimes (1 in 10~) fails to place camera at the desired location and returns back to the player` 
Cannot reproduce it (but I see on retail it happened too)

`Far sight despawns totems when casted "too far" `
This despawn is done by client - nothing I can do with it.

**Comment by avarishd** [comment]
With this new information and another test there are 2 new outcomes:
1) When casting Far Sight with the character being relatively close (within ~100 yards), the camera still flickers for a split second

<details>
 <summary>1) Video Spoiler</summary>

https://user-images.githubusercontent.com/46330494/168440983-f8c58d9b-9693-4ace-a133-a8973889df17.mp4
</details>


2) When the character is far away (more than the previously mentioned, ~100 yards), it functions properly

<details>
 <summary>2) Video Spoiler</summary>

https://user-images.githubusercontent.com/46330494/168440879-74e347ae-dd70-49c3-9107-ef362ba3cad7.mp4

</details>

---
Misc info:

I also found what caused the worldserver error (was happening prior to the PR).
When you have a Sentry Totem out (even if not being used), Far Sight-ing, far enough to despawn your totems causes it.

<details>
 <summary>Video Spoiler</summary>

https://user-images.githubusercontent.com/46330494/168441393-5d62a636-fee6-4c4d-aae6-767fc023c8ab.mp4

</details>

**Comment by UltraNix** [comment]
`When casting Far Sight with the character being relatively close (within ~100 yards), the camera still flickers for a split second`
It's because how visibility system works and I can't fix it. I see some kind of this flickering even on retail videos (e.g. here https://www.youtube.com/watch?v=bp1I5DQ2GJI - it's the same mechanic)

**Comment by UltraNix** [comment]
`I also found what caused the worldserver error (was happening prior to the PR).` Also not something bad.

**Comment by avarishd** [comment]
@UltraNix Interesting information, with that my testing is done then, all works as intended now.

**Comment by UltraNix** [comment]
@avarishd 3 more fixes:
`When switching between Far Sight and Sentry Totem, the camera is placed on the player, not the totem`
`Far sight despawns totems when casted "too far"` But up to 533yards - this is the maximum visibility distance
`Player::CreateViewpoint: Player Shamun cannot remove current viewpoint! pops "randomly"`

**Comment by avarishd** [comment]
- [ ] When switching between Far Sight and Sentry Totem, the camera is placed on the player, not the totem 
Camera still goes to the totem
- [ ] Far sight despawns totems when casted "too far" But up to 533yards - this is the maximum visibility distance
No change, they despawn at roughly the same distance 
- [x] Player::CreateViewpoint: Player Shamun cannot remove current viewpoint! pops "randomly"

**Comment by mpfans** [comment]
> 

So can this be merged?

**Comment by UltraNix** [comment]
Yes.

**Comment by mpfans** [comment]
@Nefertumm please merge it,tyvm

**Pull request merged**
