### PR TITLE
Remove temporary fix and document possible null in hook

### PR DESCRIPTION
**Pull request by Rochet2**
**Changes proposed:**

-  Remove temporary crash fix (not a real solution)
-  Document possible null in hook which caused the crash to occur

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:** Closes #

**Tests performed:** (Does it build, tested in-game, etc)

**Known issues and TODO list:**

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Yehonal** [comment]
Has been tested on linux?

Il 03 Mar 2018 20:50, "Rochet2" <notifications@github.com> ha scritto:

**Comment by Rochet2** [comment]
@Yehonal No it is not tested on linux.

**Comment by BarbzYHOOL** [comment]
How to test this?

**Comment by Rochet2** [comment]
I think the problem fixed originally was that using attacker->CustomData.GetDefault<Something>(); was crashing the core. However the reason for it crashing was that attacker was NULL and not that CustomData was somehow faulty.
This commit comments that attacker is null and removes the custom data temporary fix.

The test should basically be calling CustomData.GetDefault for a creature and a player with some custom data class that contains something. This could be done in ModifyPeriodicDamageAurasTick as that is where the original issue was found - except that you should check that attacker is not NULL, but I dont think its mandatory to test it there.

**Pull request merged**
