### PR TITLE
fix(Scripts/ZulGurub): Fixed Hakkar's Blood Siphon.

### LINKED ISSUE #12189: [ZG] Hakkar - Blood Siphon
### Current Behaviour

Blood Siphon not stun the raid.

### Expected Blizzlike Behaviour

When siphon blood is cast, Hakkar should stun the entire raid for 8sec, and drain the life of players. But if a player get debuff[ Poisonous Blood](https://classic.wowhead.com/spell=24321/poisonous-blood), the drain will instead damage Hakkar.

### Source

https://classic.wowhead.com/guides/hakkar-the-soulflayer-zul-gurub-strategy

### Steps to reproduce the problem

1. Engage Hakkar
2. Wait that he cast blood siphon

### Extra Notes

_No response_

### AC rev. hash/commit

[76e9e19](https://github.com/azerothcore/azerothcore-wotlk/commit/76e9e19f0cd8c4f552f547532581884c1af3028c)

### Operating system

Windows 11

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12189

## Issues Addressed:

- Closes #12189

## Tests Performed:

- Not tested.

## How to Test the Changes:
Engage Hakkar
Wait that he cast blood siphon

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I had merge conflicts.

image

**Comment by UltraNix** [comment]
@Gultask Try now.

**Comment by Gultask** [comment]
Jumping or moving can break the channel.

https://user-images.githubusercontent.com/100873791/175827822-c72a63be-326b-435f-af59-77ea3a238bb9.mp4

**Comment by Nefertumm** [comment]
The only thing that didn't work before was blood siphon not stunning. The rest of the things worked before with my last pr. Restore the validate method as well.

**Comment by UltraNix** [comment]
@Gultask Please, test it again.
@Nefertumm Validation restored.

**Comment by Gultask** [comment]
- [ ] If I'm already moving before Blood Siphon (like auto-running), it will immediately be cancelled.


https://user-images.githubusercontent.com/100873791/177006651-defa6d81-edac-4c92-951d-cb39cd07758b.mp4


 - [ ] Every Man for Himself and the PvP Insignias can break Blood Siphon, but I don't know if that's blizzlike or not.

**Comment by UltraNix** [comment]
@Gultask Please, test it again.

**Comment by Gultask** [comment]
The channeling is still cancelling if I'm moving before the cast.

**Comment by UltraNix** [comment]
@Gultask Should be okay now.

**Comment by Gultask** [comment]
Everything works as far as I can see 👍

**Comment by acidmanifesto** [comment]
@Nefertumm need your assessment on this since this was something related to what you are working on.

**Pull request merged**
