### PR TITLE
feat(Core/ScriptMgr): replace macro and cleanup

### LINKED ISSUE #9575: Custom modules are not executing
### Current Behaviour

It appears custom modules are not being executed when I use my custom item as seen in https://youtu.be/2UVxelGeQZc.

### Expected Blizzlike Behaviour

Before the latest merge of AzerothCore into my server's branch the item would execute its `OnUse` behaviour distributing the items it contains (it is not a container) and then deleting one instance of the item.

### Source

_No response_

### Steps to reproduce the problem

Create a custom module such as an `ItemScript` which can be reproduced as follows:
1. Create an item with a corresponding `ItemScript`.
2. Link that `ItemScript` to the `item_template` using the `ScriptName` field.
3. On use the item's script doesn't run.

### Extra Notes

_No response_

### AC rev. hash/commit
Last commit merged: 846487acaa9f4b604af0628bca5685be6815f9ba

```
AzerothCore rev. 94b93cd94c8e 2021-12-05 08:50:44 +1100 (wobgob branch) (Unix, Release, Static)
Using SSL version: OpenSSL 1.1.1f  31 Mar 2020 (library: OpenSSL 1.1.1f  31 Mar 2020)
Using Boost version: 1.71.0
Using MySQL version: 80027
Using CMake version: 3.16.3
Compiled on: Linux 5.4.0-81-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ./maps. Total size: 252191207 bytes
vmaps directory located in ./vmaps. Total size: 658130721 bytes
mmaps directory located in ./mmaps. Total size: 2196365032 bytes
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: ACDB 335.5-dev
Using World DB Revision: 2021_12_04_03
Using Character DB Revision: 2021_09_25_00
Using Auth DB Revision: 2021_06_17_00
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-colonist
- mod-hardcore
- mod-level-up
- mod-loot-box
- mod-player-settings
```

### Operating system

Ubuntu 20.04

### Custom changes or Modules

Modules are listed in the AC rev. hash/commit section. All modules have been made in-house. Custom changes is allowing multiple resource tracking.

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
- Replace macros with new inline functions
- Correct logic for few hooks
- Separate each scripts into separate files

## Issues Addressed:
- Closes #9575
- Closes https://github.com/azerothcore/mod-eluna-lua-engine/issues/73

## Tests Performed:
- In game
- [x] https://github.com/azerothcore/azerothcore-wotlk/pull/9598#issuecomment-991039007

## How to Test the Changes:
1. Just check scripts with any modules

## Linked PR's:
- https://github.com/azerothcore/mod-autobalance/pull/98

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by yuanf225** [comment]
#9598 Can it also solve the problem of https://github.com/azerothcore/mod-eluna-lua-engine/issues/74?

**Comment by Winfidonarleyan** [comment]
> #9598 Can it also solve the problem of [azerothcore/mod-eluna-lua-engine#74](https://github.com/azerothcore/mod-eluna-lua-engine/issues/74)?

maybe, need test

**Comment by yuanf225** [comment]
I will test in an hour

**Comment by yuanf225** [comment]
`[Eluna]: Executed 28 Lua scripts in 149 ms
 
WORLD: World initialized in 0 minutes 14 seconds
 
AzerothCore rev. 8acf0bf4d07e+ 2021-12-10 10:35:51 +0700 (pr/9598 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
Starting up Auction House Listing thread...
Calendar deletion of old events.
Guild Daily Cap reset.
AC> Calendar deletion of old events.

AC> 
`

I tested it, but AIO is still unavailable. I don’t know how to test the others. Can anyone tell me?

**Comment by 55Honey** [comment]
Tested with: https://github.com/55Honey/acore_ElunaTest
Output:
```
CreatureOnEnterCombat fired (1)
event: 1  creature: Diseased Young Wolf
PLAYER_EVENT_ON_ENTER_COMBAT has fired:
event: 33  playername: Heinz
CreatureOnLeaveCombat fired (2)
event: 2  creature: Diseased Young Wolf
PLAYER_EVENT_ON_LEAVE_COMBAT has fired:
event: 34  playername: Heinz
CreatureOnEnterCombat fired (1)
event: 1  creature: Diseased Young Wolf
PLAYER_EVENT_ON_ENTER_COMBAT has fired:
event: 33  playername: Heinz
CreatureOnDied fired (4)
event: 4  creature: Diseased Young Wolf
PLAYER_EVENT_ON_KILL_CREATURE has fired:
event: 7  killer: Heinz  killed: Diseased Young Wolf
PLAYER_EVENT_ON_LEAVE_COMBAT has fired:
event: 34  playername: Heinz
```
Creature hooks `CreatureOnEnterCombat`, `CreatureOnLeaveCombat` and `CreatureOnDied` work confirmed.

**Comment by Winfidonarleyan** [comment]
> ```
> [Eluna]: Executed 28 Lua scripts in 149 ms
>  
> WORLD: World initialized in 0 minutes 14 seconds
>  
> AzerothCore rev. 8acf0bf4d07e+ 2021-12-10 10:35:51 +0700 (pr/9598 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon) ready...
> Starting up Auction House Listing thread...
> Calendar deletion of old events.
> Guild Daily Cap reset.
> AC> Calendar deletion of old events.
> 
> AC> 
> ```
> 
> I tested it, but AIO is still unavailable. I don’t know how to test the others. Can anyone tell me?

how to test AIO ?

**Comment by Winfidonarleyan** [comment]
> Tested with: https://github.com/55Honey/acore_ElunaTest Output:
> 
> ```
> CreatureOnEnterCombat fired (1)
> event: 1  creature: Diseased Young Wolf
> PLAYER_EVENT_ON_ENTER_COMBAT has fired:
> event: 33  playername: Heinz
> CreatureOnLeaveCombat fired (2)
> event: 2  creature: Diseased Young Wolf
> PLAYER_EVENT_ON_LEAVE_COMBAT has fired:
> event: 34  playername: Heinz
> CreatureOnEnterCombat fired (1)
> event: 1  creature: Diseased Young Wolf
> PLAYER_EVENT_ON_ENTER_COMBAT has fired:
> event: 33  playername: Heinz
> CreatureOnDied fired (4)
> event: 4  creature: Diseased Young Wolf
> PLAYER_EVENT_ON_KILL_CREATURE has fired:
> event: 7  killer: Heinz  killed: Diseased Young Wolf
> PLAYER_EVENT_ON_LEAVE_COMBAT has fired:
> event: 34  playername: Heinz
> ```
> 
> Creature hooks `CreatureOnEnterCombat`, `CreatureOnLeaveCombat` and `CreatureOnDied` work confirmed.

thanks for test

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-autobalance/src/AutoBalance.cpp:60:21: fatal error: 'ABModuleScript' does not refer to a value
    FOR_SCRIPTS_RET(ABModuleScript, itr, end, ret) // return true by default if not scripts
                    ^
/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/modules/mod-autobalance/src/AutoBalance.h:29:7: note: declared here
class ABModuleScript : public ModuleScript
      ^
1 error generated.

**Comment by hahalmtdhl** [comment]
> 

[https://github.com/Rochet2/AIO/issues/13](url)
There are examples that can be used for testing.
AIO really still can't be used

Use this example to test:
https://github.com/Rochet2/AIO/tree/master/Examples/TestWindow

**Pull request merged**
