### PR TITLE
fix(DB/creature_template): Improved Obsidian Sanctum

### PR DESCRIPTION
**Pull request by Knindzagxg**
Changes:

Min, Max & Modifier Damage for whole Raid.

How to test:
Apply SQL
Restart Server and delete your Cache.
Make sure to add basic tanking gear towards Raid ilevel.

Before you start checking damage:
.mod hp 500000
.learn 1908 (Uber heal over time)

If there is any issue with damage and if you get instantly killed, lemme know.

Note: You wont be able to survive some mechanics where second tank is required - Use one more account on those fights.

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by iyasenai** [comment]
I tested the damage and these were the results.
These were the Buffs and the gear I used.
image

Onyx Flight Captain 25   Entry: 31000
image
Onyx Flight Captain 10  Entry: 30682
image
Onyx Blaze Mistress 25 Entry: 30998
image
Onyx Blaze Mistress 10 Entry: 30681
image
Onyx Brood General 25 Entry: 30999
image
Onyx Brood General 10 Entry: 30680
image
Onyx Sanctum Guardian 25 Entry: 31001
image
Onyx Sanctum Guardian 10 Entry:  30453
image

Bosses

Sartharion 25  Entry: 31311
image
Sartharion 10  Entry: 28860
image

Vesperon 25   Entry: 31535
image
Vesperon 10   Entry: 30449
image
Shadron 25    Entry: 31520
image
Shadron 10   Entry: 30451
image
Tenebron 25 Entry: 31534
image
Tenebron 10 Entry: 30452
image

**Comment by Knindzagxg** [comment]
@iyasenai - Can u re-test again mate, just Sartharion.

**Comment by iyasenai** [comment]
New test

Sartharion 25  Entry: 31311
image
Sartharion 10  Entry:  28860
image

**Comment by Knindzagxg** [comment]
Cheers mate, ill do more checking tomorrow once im back.
25m seems ok now tho.

**Comment by Knindzagxg** [comment]
Nothing to change here.

New tests are equal to Tankspot videos and original logs.
Thanks once again mate.

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
