### PR TITLE
feat(Core/Chat): exclude flood by GM-commands from locallhost

### PR DESCRIPTION
**Pull request by Bogir**
Cancel flood to console if GM-commands are sends from localhost

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
This affect SOAP doesn't it? If it does, then we can't accept those changes

**Comment by Kitzunu** [comment]
make it configurable. I'd still like the logs

**Comment by Bogir** [comment]
> This affects SOAP doesn't it? If it does, then we can't accept those changes unfortunatelly

I have not found any evidence that SOAP is dependent on this log and vice versa

**Review by Nyeriah — APPROVED** [review]

**Comment by acidmanifesto** [comment]
@Bogir we have merge conflict on the worldserver.conf.dist that for some reason i can not edit something as superficial on my end.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Merge Conflicts.

**Comment by acidmanifesto** [comment]
@Bogir status of the PR?

**Pull request closed without merging**
