### PR TITLE
DB/Creature Vile Fin & Ragged Scavenger fix

### PR DESCRIPTION
**Pull request by poszer**
Vile Fin & Ragged Scavenger creatures fix

Thanks @Maurowin & @grimgravy 

##### CHANGES PROPOSED:

-  Updated SAI : The creature Vile Fin Minor Oracle now casting spells, also doing melee attacks(While out of mana).
-  Updated flags for Ragged Scavenger creature (They will not attack until aggro'ed).

###### ISSUES ADDRESSED:

Closes 
https://github.com/azerothcore/azerothcore-wotlk/issues/1215
https://github.com/azerothcore/azerothcore-wotlk/issues/1223

##### TESTS PERFORMED:

Builded without problem. Tested in game, everything is working fine.
The Vile fin casting spells and also doing melee attacks while out of mana.
The creature Ragged Scavenger won't attack players while near them anymore ( Just attacking if aggro'ed ).
raggedscavenger

vilefinminororacle

##### HOW TO TEST THE CHANGES:

1. .go creature 41776  ( Walk near Ragged Scavenger ) --> Check will attack
2. .go creature 29923 ( Attack Vile fin Minor Oracle ) --> Check will he creature Cast and do melee attacks

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by poszer** [comment]
> 
> 
> The wolf in your screenshot doesn't look like it's the right wolf but yes, it's probably the right fix anyway because it was the same fix in elwynn forest
> 
> also next time add backticks to the table and column names (in fact grimgravy put them in his message but he forgot the triple backticks, so I edited his message and copied it back)
> 
> And I separated the queries with an empty line

Wrong image :laughing:  Updated

**Comment by BarbzYHOOL** [comment]
Wow nice it worked "co-authored" o_0 last time I tried it didn't work

**Comment by Nefertumm** [comment]
Didn't work because i had a typo, i wrote that in the commit......

**Comment by BarbzYHOOL** [comment]
@Nefertumm ?? didn't speak of your commit, don't worry, I tried this myself on a fork and it wasn't showing up on github

**Pull request merged**
