### PR TITLE
fix(DB/UBRS): change rep on kill for Pyroguard Emberseer from 50 to 20

### PR DESCRIPTION
**Pull request by elthehablo**
## Changes Proposed:
-  change rep from 50 to 20
-  

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Most Credible source 2023 (Bench):
image

## Tests Performed:

- not tested
- 

## How to Test the Changes:

1. kill pyroguard
2.
3.

## Known Issues and TODO List:

none afaik

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by heyitsbench** [comment]
Rep with the waterlords when the screenshot was taken was neutral.

**Comment by elthehablo** [comment]
yeah the standing might be an issue as well... no clue at all and a pain to check lol

**Comment by Vanheden** [comment]
I'm revered with Waterlords on my 80 warrior from Vanilla. I can go check.

**Comment by elthehablo** [comment]
> I'm revered with Waterlords on my 80 warrior from Vanilla. I can go check.

Lovely

**Comment by Vanheden** [comment]
> > I'm revered with Waterlords on my 80 warrior from Vanilla. I can go check.
> 
> Lovely

Crap it gave me nothing :(

**Comment by Tereneckla** [comment]
Only Ragnaros and Magmadar give rep from revered to exalted

**Comment by elthehablo** [comment]
Yeah I would need someone at honored to check this lol

**Comment by heyitsbench** [comment]
> Yeah I would need someone at honored to check this lol

I don't think it's out of the question to believe Wowhead's data on it, being that it stops giving rep at honored.

**Review by Maria-sequel — APPROVED** [review]

**Pull request merged**
