### PR TITLE
fix(DB/Creature) Ebon Blade Commander Equipment

### PR DESCRIPTION
**Pull request by jorge990125**
## Changes Proposed:

This PR proposes changes to:
-  [x] Database (SAI, creatures, etc).

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

- import the sql to the database
- start the server
- enter icc

example of the solution
https://www.wowhead.com/wotlk/npc=37967/ebon-blade-commander
363520890-a1222331-78d8-4183-944f-e8548c68eb03

### CODE REVIEW

**Comment by elthehablo** [comment]
I'm unsure exactly what you're doing here, but if you're only updating equipment, it's best to do an update instead of an insert

**Comment by jorge990125** [comment]
I only added the equipment to the npc that did not have it on, if you want go to icc and see for yourself

**Comment by avarishd** [comment]
He meant to use UPDATE, just for `equipment_id`.
https://www.azerothcore.org/wiki/sql-standards#update

**Comment by elthehablo** [comment]
> I only added the equipment to the npc that did not have it on, if you want go to icc and see for yourself

Okay that is great. Then it's better to do an update statement. I will show you why. This is current guid 88752 on live:

(88752, 37967, 0, 0, 571, 0, 0, 1, 1, 0, 5606.21, 2012.55, 798.125, 0.994737, 120, 0, 0, 1, 0, 0, 0, 0, 0, '', 0)

Your change is:

(88752, 37967, 0, 0, 571, 0, 0, 1, 1, 1, 5606.21, 2012.55, 798.125, 0.994838, 120, 0, 0, 1, 0, 0, 0, 0, 0, '', 0)

So it looks like you are slightly changing the position. What is that based on? It does not show from the PR. But if you're not changing the position you can just do an UPDATE on the equipment_id for the valid creatures

**Comment by jorge990125** [comment]
> > Solo agregué el equipo al npc que no lo tenía puesto, si quieres ve a icc y compruébalo por ti mismo.
> 
> Está bien, eso es genial. Entonces es mejor hacer una declaración de actualización. Te mostraré por qué. Esta es la guid 88752 actual en vivo:
> 
> (88752, 37967, 0, 0, 571, 0, 0, 1, 1, 0, 5606.21, 2012.55, 798.125, 0.994737, 120, 0, 0, 1, 0, 0, 0, 0, 0, '', 0)
> 
> Tu cambio es:
> 
> (88752, 37967, 0, 0, 571, 0, 0, 1, 1, 1, 5606.21, 2012.55, 798.125, 0.994838, 120, 0, 0, 1, 0, 0, 0, 0, 0, '', 0)
> 
> Entonces parece que estás cambiando ligeramente la posición. ¿En qué se basa eso? No se nota desde el PR. Pero si no estás cambiando la posición, puedes simplemente hacer una ACTUALIZACIÓN en el id_equipo para las criaturas válidas.

**Comment by jorge990125** [comment]
ahh I understand, I will make the change again only for equipment_id

**Review by sudlud — APPROVED** [review]

**Pull request merged**
