### PR TITLE
fix(DB/NPC): Eridan Bluewind

### PR DESCRIPTION
**Pull request by Kitzunu**
This PR fixes these issues:

- Currently, Eridan's gossip option is shown even if you have not completed the quest "Purified!".

- Currently, Eridan has no SAI which means the gossip option is useless.

Tests:
SAI Works.
The condition works

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
There are startup errors in your SQL code:

```
addToGossipMenuItems: GossipMenuId 1 Item 3142 not found
Not handled grouped condition, SourceGroup 1
```

https://travis-ci.org/github/azerothcore/azerothcore-wotlk/jobs/662280827?utm_medium=notification&utm_source=github_status

**Comment by Kitzunu** [comment]
fixed... Was I being dumb

**Comment by Si1ker** [comment]
Hi 😸 

HOW TO TEST THE CHANGES:
=====================================-
.go c 9116
Check you're getting the gossip without completing the quest
Introduce SQL changes -> restart
Talk to Eridan Bluewind, you should only have the option to accept the quest now, take it.
Talk to Eridad Bluewind once again and complete the quest.
Now you should be getting the gossip correctly.
=====================================-


= - = - = - = - = - =
Some additional info 🐱 
Quest name: Purified!
Quest ID: 4442
= - = - = - = - = - =




### Before PR

(without completing the quest, still getting gossip)
2020-03-22 22_37_23-Window



### After PR: 

* (without completing the quest)
2020-03-22 22_34_32-Window


* (after completing the quest)
2020-03-22 22_34_53-Window



🚀 Ready to be merged 🚀  @FrancescoBorzi @Kitzunu

**Comment by BarbzYHOOL** [comment]
@FrancescoBorzi @Yehonal @Rochet2 almost every PR can only be merged by admins (now?), I don't know why. Big issue

**Comment by BarbzYHOOL** [comment]
@Kitzunu thank you mate!

@Si1ker thank you mate for testing!

**Pull request merged**
