### PR TITLE
fix(Core/BattlegroundQueue): Replace std::erase() with .remove() ...

### PR DESCRIPTION
**Pull request by maluramichael**
... because std::erase cannot be compiled under linux without using any experimental features

## Changes Proposed:
- Removed std::erase and replaced it with Container.remove(element)

## Issues Addressed:

- Fix build issues under linux introduced in https://github.com/azerothcore/azerothcore-wotlk/pull/12731

## Tests Performed:

- Builds again on my machine with `c++ (Debian 8.3.0-6) 8.3.0`
```
[100%] Linking CXX executable worldserver
cd /tank/development/projects/azerothcore/build/src/server/apps && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/worldserver.dir/link.txt --verbose=1
/usr/bin/c++ -O2 -g -DNDEBUG -pthread -lncurses  CMakeFiles/worldserver.dir/worldserver/Main.cpp.o CMakeFiles/worldserver.dir/worldserver/ACSoap/ACSoap.cpp.o CMakeFiles/worldserver.dir/worldserver/CommandLine/CliRunnable.cpp.o CMakeFiles/worldserver.dir/worldserver/RemoteAccess/RASession.cpp.o -o worldserver  -Wl,-rpath,::::::::::::::::::::::::::::::::: ../../../modules/libmodules.a ../scripts/libscripts.a ../game/libgame.a ../../../deps/gsoap/libgsoap.a /usr/lib/x86_64-linux-gnu/libreadline.so ../shared/libshared.a ../database/libdatabase.a /usr/lib/x86_64-linux-gnu/libmariadb.so ../../common/libcommon.a /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.74.0 /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0 ../../../deps/argon2/libargon2.a ../../../deps/SFMT/libsfmt.a /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so ../../../deps/jemalloc/libjemalloc.a -ldl -lstdc++fs ../../../deps/fmt/libfmt.a ../../../deps/g3dlite/libg3dlib.a -lpthread ../../../deps/recastnavigation/Detour/libDetour.a /usr/lib/x86_64-linux-gnu/libz.so
make[2]: Leaving directory '/tank/development/projects/azerothcore/build'
[100%] Built target worldserver
make[1]: Leaving directory '/tank/development/projects/azerothcore/build'
/usr/local/bin/cmake -E cmake_progress_start /tank/development/projects/azerothcore/build/CMakeFiles 0
```

## How to Test the Changes:

1. Run `cmake -S. -Bbuild -DTOOLS_BUILD=all -DCMAKE_INSTALL_PREFIX=/tank/game_server/azerothcore/ -DWITH_WARNINGS=1 -DSCRIPTS=static -DMODULES=static -DCMAKE_VERBOSE_MAKEFILE=ON` and `(cd build; make)`

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
> ... because std::erase cannot be compiled under linux without using any experimental features

`std::erase` is part c++20, which we support. I don't see the point of this PR

**Comment by maluramichael** [comment]
Oh ok. Yeah i thought that too but clang 16 and gcc 8 did not work. Do i have to enable some flags for it to work?

**Comment by Winfidonarleyan** [comment]
There is currently no version of Clang higher than 14.0.6
https://releases.llvm.org/download.html

**Comment by maluramichael** [comment]
> There is currently no version of Clang higher than 14.0.6
> https://releases.llvm.org/download.html

ok will have to check it again. maybe ill get it to work with std::erase

**Comment by maluramichael** [comment]
> > ... because std::erase cannot be compiled under linux without using any experimental features
> 
> `std::erase` is part c++20, which we support. I don't see the point of this PR. You just don't need to use old compilers. And, last commit build without errors - https://github.com/azerothcore/azerothcore-wotlk/runs/8167815256?check_suite_focus=true

So my problem is that i cannot use clang with `-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++` because than i will get the following compiler errors.

```
/root/.cache/JetBrains/RemoteDev/dist/71861dbc5a9e2_CLion-2022.2.1/bin/cmake/linux/bin/cmake --build /tank/development/projects/azerothcore/cmake-build-debug --target worldserver -j 3
[93/1142] Building CXX object src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch
FAILED: src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch 
/usr/bin/clang++ -DAC_HAS_BROKEN_WSTRING_REGEX -DBOOST_ALL_NO_LIB -DBOOST_ASIO_NO_DEPRECATED -DBOOST_BIND_NO_PLACEHOLDERS -DBOOST_CHRONO_NO_LIB -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SERIALIZATION_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_USE_UTF8 -DENABLE_VMAP_CHECKS -DFMT_CONSTEVAL="" -DHAVE_SSE2 -DNO_BUFFERPOOL -DNO_CORE_FUNCS -DSFMT_MEXP=19937 -D_BUILD_DIRECTIVE=\"Debug\" -D_CONF_DIR=\"/tank/game_server/azerothcore/etc\" -I/tank/development/projects/azerothcore/src/server/database -I/tank/development/projects/azerothcore/src/server/database/Database -I/tank/development/projects/azerothcore/src/server/database/Database/Implementation -I/tank/development/projects/azerothcore/src/server/database/Logging -I/tank/development/projects/azerothcore/src/server/database/Updater -I/tank/development/projects/azerothcore/cmake-build-debug/src/server/database -I/tank/development/projects/azerothcore/cmake-build-debug -I/tank/development/projects/azerothcore/src/common -I/tank/development/projects/azerothcore/src/common/Asio -I/tank/development/projects/azerothcore/src/common/Collision -I/tank/development/projects/azerothcore/src/common/Collision/Management -I/tank/development/projects/azerothcore/src/common/Collision/Maps -I/tank/development/projects/azerothcore/src/common/Collision/Models -I/tank/development/projects/azerothcore/src/common/Configuration -I/tank/development/projects/azerothcore/src/common/Cryptography -I/tank/development/projects/azerothcore/src/common/Cryptography/Authentication -I/tank/development/projects/azerothcore/src/common/DataStores -I/tank/development/projects/azerothcore/src/common/Debugging -I/tank/development/projects/azerothcore/src/common/Dynamic -I/tank/development/projects/azerothcore/src/common/Dynamic/LinkedReference -I/tank/development/projects/azerothcore/src/common/Encoding -I/tank/development/projects/azerothcore/src/common/IPLocation -I/tank/development/projects/azerothcore/src/common/Logging -I/tank/development/projects/azerothcore/src/common/Metric -I/tank/development/projects/azerothcore/src/common/Navigation -I/tank/development/projects/azerothcore/src/common/Platform -I/tank/development/projects/azerothcore/src/common/Threading -I/tank/development/projects/azerothcore/src/common/Utilities -I/tank/development/projects/azerothcore/deps/argon2 -I/tank/development/projects/azerothcore/deps/SFMT -I/tank/development/projects/azerothcore/deps/utf8cpp -I/tank/development/projects/azerothcore/deps/fmt/include -I/tank/development/projects/azerothcore/deps/g3dlite/include -I/tank/development/projects/azerothcore/deps/recastnavigation/Detour/Include -isystem /usr/include/mariadb -g -Wno-narrowing -Wno-deprecated-register -W -Wall -Wextra -Winit-self -Wfatal-errors -Wno-mismatched-tags -Woverloaded-virtual -std=gnu++20 -Winvalid-pch -fpch-instantiate-templates -Xclang -emit-pch -Xclang -include -Xclang /tank/development/projects/azerothcore/cmake-build-debug/src/server/database/CMakeFiles/database.dir/cmake_pch.hxx -x c++-header -MD -MT src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch -MF src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch.d -o src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch -c /tank/development/projects/azerothcore/cmake-build-debug/src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.cxx
In file included from <built-in>:1:
In file included from /tank/development/projects/azerothcore/cmake-build-debug/src/server/database/CMakeFiles/database.dir/cmake_pch.hxx:5:
In file included from /tank/development/projects/azerothcore/src/server/database/PrecompiledHeaders/databasePCH.h:21:
In file included from /tank/development/projects/azerothcore/src/server/database/Database/Field.h:23:
/tank/development/projects/azerothcore/src/common/Utilities/Duration.h:55:27: fatal error: no type named 'days' in namespace 'std::chrono'
using Days = std::chrono::days;
             ~~~~~~~~~~~~~^
1 error generated.
[95/1142] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourCommon.cpp.o
ninja: build stopped: subcommand failed.
```

```
/usr/bin/clang++ --version
Debian clang version 16.0.0-++20220902115253+5073499b693d-1~exp1~20220902115355.717
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Should i close this pr and create/search an issue for the chrono error?

**Comment by Maelthyrr** [comment]
> > > ... because std::erase cannot be compiled under linux without using any experimental features
> > 
> > 
> > `std::erase` is part c++20, which we support. I don't see the point of this PR. You just don't need to use old compilers. And, last commit build without errors - https://github.com/azerothcore/azerothcore-wotlk/runs/8167815256?check_suite_focus=true
> 
> So my problem is that i cannot use clang with `-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++` because than i will get the following compiler errors.
> 
> ```
> /root/.cache/JetBrains/RemoteDev/dist/71861dbc5a9e2_CLion-2022.2.1/bin/cmake/linux/bin/cmake --build /tank/development/projects/azerothcore/cmake-build-debug --target worldserver -j 3
> [93/1142] Building CXX object src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch
> FAILED: src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch 
> /usr/bin/clang++ -DAC_HAS_BROKEN_WSTRING_REGEX -DBOOST_ALL_NO_LIB -DBOOST_ASIO_NO_DEPRECATED -DBOOST_BIND_NO_PLACEHOLDERS -DBOOST_CHRONO_NO_LIB -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_REGEX_NO_LIB -DBOOST_SERIALIZATION_NO_LIB -DBOOST_SYSTEM_DYN_LINK -DBOOST_SYSTEM_USE_UTF8 -DENABLE_VMAP_CHECKS -DFMT_CONSTEVAL="" -DHAVE_SSE2 -DNO_BUFFERPOOL -DNO_CORE_FUNCS -DSFMT_MEXP=19937 -D_BUILD_DIRECTIVE=\"Debug\" -D_CONF_DIR=\"/tank/game_server/azerothcore/etc\" -I/tank/development/projects/azerothcore/src/server/database -I/tank/development/projects/azerothcore/src/server/database/Database -I/tank/development/projects/azerothcore/src/server/database/Database/Implementation -I/tank/development/projects/azerothcore/src/server/database/Logging -I/tank/development/projects/azerothcore/src/server/database/Updater -I/tank/development/projects/azerothcore/cmake-build-debug/src/server/database -I/tank/development/projects/azerothcore/cmake-build-debug -I/tank/development/projects/azerothcore/src/common -I/tank/development/projects/azerothcore/src/common/Asio -I/tank/development/projects/azerothcore/src/common/Collision -I/tank/development/projects/azerothcore/src/common/Collision/Management -I/tank/development/projects/azerothcore/src/common/Collision/Maps -I/tank/development/projects/azerothcore/src/common/Collision/Models -I/tank/development/projects/azerothcore/src/common/Configuration -I/tank/development/projects/azerothcore/src/common/Cryptography -I/tank/development/projects/azerothcore/src/common/Cryptography/Authentication -I/tank/development/projects/azerothcore/src/common/DataStores -I/tank/development/projects/azerothcore/src/common/Debugging -I/tank/development/projects/azerothcore/src/common/Dynamic -I/tank/development/projects/azerothcore/src/common/Dynamic/LinkedReference -I/tank/development/projects/azerothcore/src/common/Encoding -I/tank/development/projects/azerothcore/src/common/IPLocation -I/tank/development/projects/azerothcore/src/common/Logging -I/tank/development/projects/azerothcore/src/common/Metric -I/tank/development/projects/azerothcore/src/common/Navigation -I/tank/development/projects/azerothcore/src/common/Platform -I/tank/development/projects/azerothcore/src/common/Threading -I/tank/development/projects/azerothcore/src/common/Utilities -I/tank/development/projects/azerothcore/deps/argon2 -I/tank/development/projects/azerothcore/deps/SFMT -I/tank/development/projects/azerothcore/deps/utf8cpp -I/tank/development/projects/azerothcore/deps/fmt/include -I/tank/development/projects/azerothcore/deps/g3dlite/include -I/tank/development/projects/azerothcore/deps/recastnavigation/Detour/Include -isystem /usr/include/mariadb -g -Wno-narrowing -Wno-deprecated-register -W -Wall -Wextra -Winit-self -Wfatal-errors -Wno-mismatched-tags -Woverloaded-virtual -std=gnu++20 -Winvalid-pch -fpch-instantiate-templates -Xclang -emit-pch -Xclang -include -Xclang /tank/development/projects/azerothcore/cmake-build-debug/src/server/database/CMakeFiles/database.dir/cmake_pch.hxx -x c++-header -MD -MT src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch -MF src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch.d -o src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.pch -c /tank/development/projects/azerothcore/cmake-build-debug/src/server/database/CMakeFiles/database.dir/cmake_pch.hxx.cxx
> In file included from <built-in>:1:
> In file included from /tank/development/projects/azerothcore/cmake-build-debug/src/server/database/CMakeFiles/database.dir/cmake_pch.hxx:5:
> In file included from /tank/development/projects/azerothcore/src/server/database/PrecompiledHeaders/databasePCH.h:21:
> In file included from /tank/development/projects/azerothcore/src/server/database/Database/Field.h:23:
> /tank/development/projects/azerothcore/src/common/Utilities/Duration.h:55:27: fatal error: no type named 'days' in namespace 'std::chrono'
> using Days = std::chrono::days;
>              ~~~~~~~~~~~~~^
> 1 error generated.
> [95/1142] Building CXX object deps/recastnavigation/Detour/CMakeFiles/Detour.dir/Source/DetourCommon.cpp.o
> ninja: build stopped: subcommand failed.
> ```
> 
> ```
> /usr/bin/clang++ --version
> Debian clang version 16.0.0-++20220902115253+5073499b693d-1~exp1~20220902115355.717
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> ```
> 
> Should i close this pr and create/search an issue for the chrono error?

Yes, open an issue related to the chrono with clang 16. But if you don't want to wait, I suggest for the moment to use clang11. As you can see with git action, there are no build issue with this version.

**Comment by maluramichael** [comment]
@Maelthyrr alright will do that. Thank you

**Comment by ltlqx2022** [comment]
@maluramichael I solved the problem with debian 11.1

**Comment by maluramichael** [comment]
> @maluramichael I solved the problem with debian 11.1

can you tell me what compiler version you used?

**Comment by ltlqx2022** [comment]
@maluramichael gcc version 10.2.1 20210110 (Debian 10.2.1-6)

**Pull request closed without merging**
