### PR TITLE
fix(Scripts/VOA): Some code-style improvements and perhaps some bandwidth consumption issue

### LINKED ISSUE #2260: Bandwidth consumption ( Instance Vault of Archavon )
Hi, sorry native language spanish, so i will try to explain
In the instance Vault of Archavon
with 25 players the servers go from 1mb of upload bandwidth to more than 10mb, so the server lags.
It happen in the moment the boss has agro and go to attack

all the server get lag
cpu remain in 10% and memory is ok

Branch installed: Commits on Aug 31, 2019
I can't say in what commit it start i think 2 o 3 commits before i thought it was only an internet issue at first. but i tested it, and the server in that moments go from 1mb of upload to more than 10mb

Also take note upload price in my country is expensive, i will understand if it is a normal behavior but i don't think so becouse the server only had at this moment 30 players. and it only happen with the instance.

In case im wrong please excuse me.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/79863202-bandwidth-consumption-instance-vault-of-archavon?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Goatform**
## CHANGES PROPOSED:
-  Some code style improvements
-  Removed magic numbers
-  Attempt to fix one of the reported issues

**DEV:** Use `?w=1` with the commit link so that the GitHub shows you specific changes that I've done.

## ISSUES ADDRESSED:
- Maybe closes #2260
NOTE: I do not know if it'll fix it still but perhaps some of the people who confirmed this as an issue can check it out.
So I'll link @Nemepy , @boom8866 and @pklloveyou 

## TESTS PERFORMED:
- Compile
- Tested the boss (Archavon the Stone Watcher)

## HOW TO TEST THE CHANGES:

- Go to VOA raid
- Fight Archavon the Stone Watcher

## KNOWN ISSUES AND TODO LIST:

- None at the moment.

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by aradep** [comment]
Running into a couple bugs

- Impale visual (being picked up and held in Archavon's hand) ends too soon, making it seem like the tank is stuck in place while the stun wears off.
- Sometimes Archavon casts Stomp, Impale, Crushing Leap, and Rock Shards all simultaneously.

**Comment by Goatform** [comment]
1st is possibly related to my adjustments.
2nd is unlikely related to this commit and I won't be working on it.

**Comment by FrancescoBorzi** [comment]
> 2nd is unlikely related to this commit and I won't be working on it.

@Goatform @aradep just check if the bug is already on master ;)

**Comment by aradep** [comment]
> just check if the bug is already on master ;)

True, mb 😄 

1st bug (Impale visual too short) is present on master. 2nd bug (casting other spells during Crushing Leap) also on master but to a lesser extent.

before PR: casts Crushing Leap, Rock Shards at the same time. 
after PR: casts Crushing Leap, Rock Shards, Stomp, Impale at the same time.

**Comment by Goatform** [comment]
So then none of these bugs are caused by my PR which means I will most likely not correct it here in this PR but I may if I get some time.

**Comment by FrancescoBorzi** [comment]
thanks @aradep , marking this as To Be Merged. Good job @Goatform !

**Review by Si1ker — APPROVED** [review]

**Comment by Si1ker** [comment]
Thanks for this PR @Goatform 
cc @FrancescoBorzi to merge

**Pull request merged**
