### PR TITLE
chore(CI): Improve error message of check_pending_sql

### PR DESCRIPTION
**Pull request by Kitzunu**

### CODE REVIEW

**Review by locus313 — APPROVED** [review]

**Review by locus313 — APPROVED** [review]

**Comment by locus313** [comment]
Just thought of something else. We probably should change the name of the workflow now too. 
https://github.com/azerothcore/azerothcore-wotlk/blob/master/.github/workflows/check_pending_sql.yml#L1
Maybe just change it to "check-pending-sql"

**Comment by Kitzunu** [comment]
Done

**Review by locus313 — APPROVED** [review]

**Comment by Kitzunu** [comment]
Weird stuff that https://github.com/azerothcore/azerothcore-wotlk/pull/4075 does not fail on multiple newlines @locus313 O.o

**Comment by locus313** [comment]
I had forgotten that the `tr -d '\n'` part of the if filters out the new line characters. if we dont do this then we have to change the `tail -c 1` part of the if to include more characters (most likely just change it to 2), but this brings more possibilities of false negatives on the check.

**Comment by Kitzunu** [comment]
F that

**Pull request merged**
