### PR TITLE
Update travis build ubuntu to 16.04

### LINKED ISSUE #1132: Update Ubuntu version in Travis to Xenial (16.04)
Since last month, [travis supports Ubuntu 16.04](https://blog.travis-ci.com/2018-11-08-xenial-release). We should update our travis build to use 16.04 instead of 14.04.

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
Closes #1132

### CODE REVIEW

**Comment by Rochet2** [comment]
`ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
`
We probably need mysql..
https://docs.travis-ci.com/user/database-setup/#mysql

**Comment by FrancescoBorzi** [comment]
@Rochet2 specifying that we need mysql in the travis config file indeed solved the issue, thanks (I wonder why it wasn't necessary before).

However now there is another issue, I struggled a lot trying to solve it without success. I documented it here: https://stackoverflow.com/questions/53877869/cant-find-any-matching-row-in-the-user-table-after-upgrading-mysql-from-5-6-t

Something wrong happens in [this line](https://github.com/azerothcore/azerothcore-wotlk/blob/ecb5ae325e635d5f9ac0aba5489da2964f202a05/apps/db_assembler/includes/functions.sh#L110) of one bash script and I can't really understand it.

**Comment by FrancescoBorzi** [comment]
Solve that isse, now getting another one:

> ERROR 1067 (42000) at line 234: Invalid default value for 'last_login'

**Comment by FrancescoBorzi** [comment]
Solved all issues related with mysql, now getting:

> /home/travis/build/azerothcore/azerothcore-wotlk/src/server/scripts/World/npcs_special.cpp:773:10: fatal error: 'OnQuestComplete' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]

**Pull request merged**
