### PR TITLE
fix(Core/Events): Prevent seasonal quests from resetting at server re…

### LINKED ISSUE #6973: [Stranglethorn Fishing Extravaganza] Master Angler quest resets if server restart during the event, allowing for multiple winners on the same day
Original report: https://github.com/chromiecraft/chromiecraft/issues/1028

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

If server restart happens during the Stranglethorn Fishing Extravaganza, after the winner has been selected, another player can deliver 40 Speckled Tastyfish required for Quest:Master Angler and be another winner on the same day, obtaining one of the rewards and achievement.

Despite the rare environment, this may open a window for easy achievement and quest rewards from the Quest:Master Angler. Quest also resets for the previous winner so the same person can get two rewards on the same day if they are 'lucky'.

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Server restart should not affect the Quest:Master Angler and reset its completion once the winner is selected for the day.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Wait till the Stranglethorn Fishing Extravaganza event is up
2. Collect 40 Speckled Tastyfish https://wowgaming.altervista.org/aowow/?item=19807
3. Approach Riggle Bassbait <Fishmaster> https://wowgaming.altervista.org/aowow/?npc=15077 in Booty Bay
4. Wait until someone completes Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
5. Trigger/Wait for server restart while the Stranglethorn Fishing Extravaganza event is still up
6. Log in as fast as possible
7. Try to complete Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
8. Inspect your achievements for Master Angler of Azeroth https://wowgaming.altervista.org/aowow/?achievement=306

##### EXTRA NOTES:
The same issue may be also affecting Kalu'ak Fishing Derby https://wowgaming.altervista.org/aowow/?quest=24803 in Northrend where rewards from the event are even more lucrative.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/091b072be10ecbe75d9aa38c19e2262e0cbc7690

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

Confirmed and reproduced on a local AC server (AC HASH/COMMIT: 42f27af) 

Effectively lets 2 characters get the achievement on the same day after a server reset;

WoWScrnShot_071621_073401
WoWScrnShot_071621_073721

The player who made the report has explained it very well, but just in case, looking for info in old forums, they all confirm that being a competition, it makes no sense that more than one player wins it, I consider this extract the most clarifying:

ruwubww

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99970987-stranglethorn-fishing-extravaganza-master-angler-quest-resets-if-server-restart-during-the-event-allowing-for-multiple-winners-on-the-same-day?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…start. Source: TrinityCore.

Fixes #6973

## Issues Addressed:

- Closes #6973
- Closes https://github.com/chromiecraft/chromiecraft/issues/1028

## Tests Performed:

- Not tested.

## How to Test the Changes:

Wait till the Stranglethorn Fishing Extravaganza event is up
Collect 40 Speckled Tastyfish https://wowgaming.altervista.org/aowow/?item=19807
Approach Riggle Bassbait https://wowgaming.altervista.org/aowow/?npc=15077 in Booty Bay
Wait until someone completes Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
Trigger/Wait for server restart while the Stranglethorn Fishing Extravaganza event is still up
Log in as fast as possible
Try to complete Quest:Master Angler https://wowgaming.altervista.org/aowow/?quest=8193
Inspect your achievements for Master Angler of Azeroth https://wowgaming.altervista.org/aowow/?achievement=306

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
@azerothcore/testers Please test it.

**Comment by temperrr** [comment]
I can still hand in the quest after a server reboot when somebody else already did it.

**Comment by UltraNix** [comment]
@temperrr Try now.

**Comment by temperrr** [comment]
It now always says somebody already completed the event. Even the next week.

**Comment by UltraNix** [comment]
@temperrr Please, once again.

**Comment by temperrr** [comment]
Now its back to when server restarts its available again.

**Comment by UltraNix** [comment]
:/

**Comment by UltraNix** [comment]
@temperrr Once gain. It must work now :)

**Comment by temperrr** [comment]
Ok it works. 
Start worldserver with runasdate.exe
set on a sunday 2pm
complete event
nobody else can complete it

START wordserver again with runasdate.exe
on a date that ISNT A SUNDAY
let server load
shut it down

start worldserver again with runasdate.exe
set a week ahead on a sunday 2pm compared to first
you can complete the event again

If you miss the middle step it never unloads the event it seems ;)

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
macOS build broken here @UltraNix 

In file included from /Users/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Events/GameEventMgr.cpp:18:
/Users/runner/work/azerothcore-wotlk/azerothcore-wotlk/src/server/game/Events/GameEventMgr.h:164:18: fatal error: no template named 'unordered_map' in namespace 'std'; did you mean 'unordered_set'?
    typedef std::unordered_map<uint32, std::vector<uint32>> GameEventSeasonalQuestsMap;

**Pull request merged**
