### PR TITLE
fix(DB/Creature): The Ancient Hero SmartAI fix

### PR DESCRIPTION
**Pull request by Meramaf**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes  #https://github.com/azerothcore/azerothcore-wotlk/issues/12153

## Tests Performed:

- 
- 

## How to Test the Changes:

.q a 13133
.go c id 30718
talk it
when he becomes iskalder, then use The Bone Witch's Amulet for iskalder
bring 'iskalder' back to 'The Bone Witch'

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Not work for me. With gm off, mobs are hostile. I can't talk to them. In gm, I click on gossip do nothing.

**Comment by Meramaf** [comment]
> Not work for me. With gm off, mobs are hostile. I can't talk to them. In gm, when I talk to them, it's do nothing.

This Hero spawn in random npc, you need check more npcs to summon a hero. I testet this and this work for me

**Comment by mpfans** [comment]
tested and work. thank you PR @Meramaf

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
