### PR TITLE
fix(Core): fix chests not despawning when opened in group

### PR DESCRIPTION
**Pull request by r-o-b-o-t-o**
## Changes Proposed:
-  Deactivate chests when their last item has been rolled by a group

## Issues Addressed:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5362
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/5128

Video displaying the current (bugged) behaviour:

https://user-images.githubusercontent.com/24357633/115364584-d211ab00-a1c3-11eb-936a-499f5ec0bc12.mp4

## Tests Performed:

- Tested in-game on Windows 10

## How to Test the Changes:

- Log in on two separate accounts
- With one account, invite the character from the other account in a group
- Go to a chest with both characters (example: `.go o 30950`)
- Make sure that the loot rule is not Free For All
- Open the chest, take all gray/white items, close the chest
- With both characters, roll on the green/blue items
- Verify that the chest is despawning when all items have been rolled for

See example video:

https://user-images.githubusercontent.com/24357633/115364603-d6d65f00-a1c3-11eb-9dd6-565126c5ab38.mp4

## Known Issues and TODO List:
**NOTE**: this is my first C++ PR here, so please review this carefully 😁 if you think it could be fixed in a better way, write a comment and I'll edit the changes.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Stifler82** [comment]
Great Job! @r-o-b-o-t-o 🚀🚀🚀

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
Nice PR, good job

**Comment by Sedatyf** [comment]
I'll test it today as @r-o-b-o-t-o  already told me about this PR. I'll keep you updated

**Comment by Sedatyf** [comment]
Hey there.
So I tested this with different scenarios:

- Everyone pass on green stuff. Chest doesn't disappear as there is still those green stuffs in it. Then it disappears when we loot those stuffs directly in the chest ✔️ 

https://user-images.githubusercontent.com/59012307/115458409-f4d4ab80-a225-11eb-9373-5bb0ba0f99a7.mp4

- Nobody roll on items, so time runs out. Chest doesn't disappear as there is still those green stuffs (like first scenario) ✔️ 

https://user-images.githubusercontent.com/59012307/115458498-12097a00-a226-11eb-8538-f7693d6acdd7.mp4

- Everyone roll on green stuff but the character who opened the chest didn't grab white/gray stuffs. Chest doesn't disappear as there is those white stuffs in it. It then disappears if someone loots it ✔️ 

https://user-images.githubusercontent.com/59012307/115458712-5dbc2380-a226-11eb-8660-12d56fee4167.mp4

- Finally, someone takes all white/gray stuffs in chest, then roll for green stuffs. The chest disappears when roll is over ✔️ 

https://user-images.githubusercontent.com/59012307/115458891-a4aa1900-a226-11eb-9342-7c2d28992d2a.mp4

Everything looks good!

**Comment by r-o-b-o-t-o** [comment]
Hi there @FrancescoBorzi, did you have a chance to take a look at the changes?
I think a second review wouldn't hurt 😛

**Comment by Stifler82** [comment]
> Hi there @FrancescoBorzi, did you have a chance to take a look at the changes?
> I think a second review wouldn't hurt 😛

You already got it, form me, but it was "Hidden" 😉

**Comment by Footman** [comment]
this produces tons of crashes on live server

**Comment by r-o-b-o-t-o** [comment]
Hello @Footman, really sorry about that, and thanks for reporting!

**Comment by FrancescoBorzi** [comment]
my bad, I've merged this too quickly. I reverted it for now so we don't have crashes.

@r-o-b-o-t-o can you please open a new PR with the changes? so we can review it

**Pull request merged**
