### PR TITLE
The repair creature indicates that there are acceptable tasks, but the dialogue has no acceptable tasks.

### PR DESCRIPTION
**Pull request by pklloveyou**
The repair creature indicates that there are acceptable tasks, but the dialogue has no acceptable tasks.

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:
- 1.image

- 2.Find this creature, talk to the visible task, and talk to observe the creature.

- 3.After using the patch:
image
Accept all visible tasks
image
Before using the patch:
image

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
I'm sorry, but i'm totally unable to find this npc. I get "target map or coordinates is invalid". (command use : .go c id 29795 and .go c 142849)

**Comment by pklloveyou** [comment]
> I'm sorry, but i'm unable to find this npc. I get "target map or coordinates is invalid". (command use : .go c id 29795 and .go c 142849)

image
image

**Comment by Lynethris** [comment]
I see any difference with and without the fix. I'm unable to reproduce the bug on the master branch. Can you give me the process for reproduce this ?

WoWScrnShot_031822_210438

**Comment by pklloveyou** [comment]
ok

**Pull request closed without merging**
