### PR TITLE
Fix(DB/Gameobject) Mining nodes inside of eachother

### LINKED ISSUE #5310: Copper veins too close to each other in Durotar
## CURRENT BEHAVIOUR:

Copper veins 12487 and 5474 are too close to each other in Durotar

image

## EXPECTED BLIZZLIKE BEHAVIOUR:

Mining nodes should not spawn too close to each other.

## STEPS TO REPRODUCE THE PROBLEM:

1. .go o 12487

## AC HASH/COMMIT:

rev 33aeadf8

## OPERATING SYSTEM:

Ubuntu 20:04

## CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97910153-copper-veins-too-close-to-each-other-in-durotar?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #5338: Double Mithril Spawn in Tanaris
## CURRENT BEHAVIOUR:

Two mithril veins are spawning too closely together in Tanaris:
Node 7327 -> Node 17491, distance 1.13 units.

Note there was another issue raised about doubled mithril in Tanaris (https://github.com/azerothcore/azerothcore-wotlk/issues/5234); this is not the same pair of nodes.

## EXPECTED BLIZZLIKE BEHAVIOUR:

Ore should be spaced more evenly, and not overlapping.

## SOURCE:

WoWScrnShot_041821_154616

## STEPS TO REPRODUCE THE PROBLEM:

1. .go o 7327
2. Observe.

## AC HASH/COMMIT:

Rev. 3a5d6fd001bb+ 2021-04-18 02:26:38 +0200 (master branch) (Unix, Release)

## OPERATING SYSTEM:

Ubuntu 20.10

## CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97910143-double-mithril-spawn-in-tanaris?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Branel**
## Changes Proposed:
Moves the node that is inside of another to a more appriopiate location.

## Issues Addressed:
- Closes #5338
- Closes #5310

## SOURCE:

Source is original bug report.

## Tests Performed:

Works on Windows 10 

## How to Test the Changes:

Please follow the wiki to update your database, when done use `.go o 7327` &  `.go o 12487` and see the change.

## Known Issues and TODO List:

N/A

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ErnestoGonzalezC** [comment]
Why is it pointing to the database named acore_world? in my case it is called az_world, I don't think everyone uses the name acore_world (wouldn't it be better to point directly to the gameobject?)

**Comment by Branel** [comment]
It is the name generated by the [setup](https://github.com/azerothcore/azerothcore-wotlk/blob/master/data/sql/create/create_mysql.sql).

Thank you for your feedback, I will update the commit with a more universal approach. :D

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks for your contribution @Branel and @ErnestoGonzalezC for reviewing this

**Comment by pklloveyou** [comment]
Tested

**Pull request merged**
