### PR TITLE
fix(scripts/npc) Experience Eliminator only asks pertinent questions

### PR DESCRIPTION
**Pull request by kjack9**
## Changes Proposed:
-  Fixes the Experience Eliminator NPCs to only ask the right question based on your current XP gain flag.

## Issues Addressed:
None

## SOURCE:
Personal finding.

## Tests Performed:

- builds with latest AzerothCore
- tested with Behsten and Slahtz on appropriate faction characters

## How to Test the Changes:

1. Visit Behsten in Stormwind or Slahtz in Orgrimmar
2. Note that the NPC only asks you the right question
3. Stop/start your experience with the NPC
4. Note that the other question shows now

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
[this](https://www.youtube.com/watch?v=nJJdPAc0mpw&ab_channel=DrustvarGaming) also shows that it should be the way it now is with your fix. At least in retail. And [this](https://www.youtube.com/watch?v=hb63OEysQFQ&ab_channel=ewew43) from what looks like wotlk retail

**Comment by kjack9** [comment]
Any questions or concerns on this? Pretty simple change with no real chance of breaking something else. Anything else needed from me before it can be merged?

**Comment by Nyeriah** [comment]
Yes, could you add brackets?

https://www.azerothcore.org/wiki/cpp-code-standards

**Comment by kjack9** [comment]
> Yes, could you add brackets?

Yep, done!

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
