### PR TITLE
fix(DB/Locale): Add several entries for frFR

### PR DESCRIPTION
**Pull request by PolluxTroy0**
##### CHANGES PROPOSED:
Added frFR translation for : 
- broadcast_text_locale
- creature_text_locale
- gossip_menu_option_locale
- npc_text_locale
- quest_offer_reward_locale
- quest_request_items_local

All from TC latest known DB and from some other DB i found. All IDs are normally added.
Lots of translations stay in english and need to be translated.

###### ISSUES ADDRESSED:
Missing french translations for tables above.

##### TESTS PERFORMED:
Tried it on my builded core (16/01/2019 @ 20h00). It seems to work, can't try for all localized data :)

##### HOW TO TEST THE CHANGES:
Update SQL DB (Make backup before)

##### KNOWN ISSUES AND TODO LIST:
Missing lots of frFR localizations, for locales tables not implemented yet next to TC sql restructuration.

- [ ] Translate missing frFR data (huge work, can't do it solo)

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
Another big file incoming... good work!

@BarbzYHOOL can you have a look at this?

**Comment by PolluxTroy0** [comment]
I'll split my file into one for each table, too much lines to work with ^^

**Comment by FrancescoBorzi** [comment]
@PolluxTroy0 that would actually be much better :)

**Comment by PolluxTroy0** [comment]
Didn't see those 500 000+ lines in broadcast_text_locale and duplicated some of them ;)

**Comment by poszer** [comment]
Will be updated on new PR

**Comment by PolluxTroy0** [comment]
Reworked sql file ;)

**Comment by FrancescoBorzi** [comment]
@PolluxTroy0 can you split it into several files? for example one file per table?

**Comment by PolluxTroy0** [comment]
> @PolluxTroy0 can you split it into several files? for example one file per table?

Yup, i can. Do i need to create an update rev_***.sql for each ?

**Comment by FrancescoBorzi** [comment]
@PolluxTroy0 yes please :)

**Comment by BarbzYHOOL** [comment]
is it ready to be tested?

@Maurowin à tester :P

**Comment by PolluxTroy0** [comment]
Je split les fichiers, je re -pull et ce sera bon

**Comment by PolluxTroy0** [comment]
I have all other locales for frFR, waiting for needed tables to be supported to add them to the db.

**Comment by PolluxTroy0** [comment]
Please, do not add this PR to master branch while i'm not done adding french translation.
But you can try actual files to test them.

**Comment by PolluxTroy0** [comment]
@FrancescoBorzi Ready to test ;)

**Comment by PolluxTroy0** [comment]
Je partage ce lien si certains veulent aider à traduire ce qui ne l'est pas encore : https://docs.google.com/spreadsheets/d/1Q1F49oN3du3d872V5FC71821WdRboTjMX45cImRiM30/edit?usp=sharing

**Comment by Maurowin** [comment]
J'en ai traduit pas mal (des récurrentes)

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL

**Comment by Maurowin** [comment]
Quand vous participez à la traduction relisez vous et n'oubliez pas les / aves les '
Je suis en train de corriger se que je vois mais je pense qu'il va falloir que tu te fasses un outils pour check les / @PolluxTroy0

**Comment by PolluxTroy0** [comment]
@Maurowin Je ferais ça en effet. Merci pour ton aide ;)

**Comment by PolluxTroy0** [comment]
Je pense faire une update ce week-end avec les achievments ;)

**Comment by poszer** [comment]
What is status of this ? Is this finished, tested by anyone? Cmon #French people, easy to test :smiley:

**Comment by BarbzYHOOL** [comment]
As soon as I put my hands back into a core, I will test this and the PRs I said I must test etc so if nobody does, I will.

**Comment by poszer** [comment]
> As soon as I put my hands back into a core, I will test this and the PRs I said I must test etc so if nobody does, I will.

I believe in you @BarbzYHOOL  :blush: :stuck_out_tongue:

**Comment by PolluxTroy0** [comment]
Can i continue to work on this or start again if changes has been made on the db tables ?

**Comment by FrancescoBorzi** [comment]
@PolluxTroy0 I suggest to merge master into your branch and check if the build passes

**Comment by Maurowin** [comment]
Look up this link, i think it will be usefull to translate the server in French 
https://www.mediafire.com/folder/8b3sv65pwibr0/TraductionFR-3.3.5a#8b3sv65pwibr0

**Comment by Maurowin** [comment]
@BarbzYHOOL peut être le transformer en WIP non? et le merger.

**Comment by Kitzunu** [comment]
Please always have DELETE before INSERT

**Comment by Kitzunu** [comment]
Do we want to push this just to get the translations that have been made?

I am pretty sure the PR is abandoned

**Comment by Helias** [comment]
I totally agree with you @Kitzunu, I think that we can also merge this, it should not break anything.

**Pull request merged**
