### PR TITLE
Core/Spells: fix spell range check

### LINKED ISSUE #2673: RangeHack
More info, With Fix >> https://github.com/TrinityCore/TrinityCore/issues/17060

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/88722709-rangehack?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Viste**
## CHANGES PROPOSED:
- port of https://github.com/TrinityCore/TrinityCore/commit/e6a52d4aae9e8facc46c3b05e0560d540a928d73
## ISSUES ADDRESSED:
- Closes #2673 #310

## Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@Viste first of all, thank you for your PR.

Unfortunately, contributors can't properly test your PR unless it is clear how to test it.
I understand that sometimes PRs are generic and there can't be a clear testing procedure explained, however, you could **at least** explain what your changes can **potentially** affect.

**Comment by Viste** [comment]
@FrancescoBorzi all info in issue

**Comment by Stoabrogga** [comment]
>
> this may be unexpected, but... range calculation ;))

Exactly, it affects every spell. Will be interesting how to test this thoroughly in order to prevent any side effects. I honestly have no idea...

**Comment by Viste** [comment]
> > this may be unexpected, but... range calculation ;))
> 
> Exactly, it affects every spell. Will be interesting how to test this thoroughly in order to prevent any side effects. I honestly have no idea...

You will never be able to test everything and make sure that nothing is broken, too many details and subtle things that sometimes do not even remember.

This strategy(tests) applies only to correcting a particular quest/spell, etc.

**Comment by Stoabrogga** [comment]
If we are not able to test it thoroughly it should not be merged in my opinion. We also should not just take over code fragments from TC without exactly knowing what it can affect and how the changes work in-game (I presume you did not test this in-game). AC has a different code base than TC, as both projects follow different ways of development for years now. Fixes working for TC may not work for AC.

**Comment by BarbzYHOOL** [comment]
Helias said it was not a bug here https://github.com/azerothcore/azerothcore-wotlk/issues/310

**Comment by V3nomAnc3r** [comment]
I will check tomorrow

**Comment by Viste** [comment]
> AC has a different code base than TC

it's not even funny. MaNGOS and TC did develop in different ways. SunwellCore(AzerothCore) just a fork of 2012 TC and bunch of hackfixes and with pseudo-optimization from pussywizard (cutting out all logs and etc.)  the code base is almost the same. And you can block me back it would be nice not to have contact with you.

**Comment by retrydev** [comment]
че за идиоты вообще, не знают даже как проверить данный баг, https://github.com/TrinityCore/TrinityCore/issues/17060  у тринити кор все же там описанно что и как проверить, данный баг работает и я его лично исправил у себя, а криворукие тупые идиоты пусть идут лесом, им бля покажи баг дай фикс на него, нет все равно будут как геи хуйню расспрашивать всякую

**Comment by Stoabrogga** [comment]
Viste, I blocked you for a few days because you don't stop to randomly insult people who don't have the same opinion as you. I honestly don't know why you are still allowed to work on this project, but I personally will block you again. And if AC is just a bunch of hackfixes, then why are you still here? Why not help out TC instead?

@retrydev 
Please stop with your insulting comments.

**Comment by Viste** [comment]
> And if AC is just a bunch of hackfixes, then why are you still here? Why not help out TC instead?

in short, the last 15 years, it just so happens. And don't worry, someday you'll fix all the quests.

> @retrydev
> Please stop with your insulting comments.

That's his opinion and he has the right to express it. 
anyway all who need this fix can apply it by hands. Closing, since Stoabrogga's code lord is against it.

**Comment by Stoabrogga** [comment]
>
> And don't worry, someday you'll fix all the quests.

At least I test my stuff thoroughly in-game on a clean system before creating a PR and provide detailed instructions on how to test (which is also not 100% failsafe, but better than just taking over code without actually knowing what it does). And I don't provide PRs where I don't exactly know what I'm doing.

>
> That's his opinion and he has the right to express it.

It's not, it's an insult.

**Comment by Viste** [comment]
я могу объяснить тебе что делает этот код. каждую строчку. только толку? ты будешь тестировать каждый спел доступный игрокам с ренжом каста? бой с бссами в инстах? спелы нпц/боссов? Знаешь все существующие баги?

**Comment by Stoabrogga** [comment]
I don't speak Russian, but I think I understood what you're saying using translation tools:

If you could explain the changes in your PR this would've been great, I'm always eager to learn. But the original TC Issue explains nearly nothing, there's only a big patch file in one of the comments and later just the TC commits. I also don't know if you checked the current state of the TC implementation as the commit you mentioned is very old.
Also to test this you could have thought of a few different types of spells or abilities using different ranges (including melee range) or a few specific boss encounters which depend on range checks and then include instructions on how to test those (in addition to the actual range hack issue). I'm now working for many years as software developer and testing was always the most important part of software development.

**Comment by Viste** [comment]
wait you say we must test stuff and then say 

> few different types of spells or abilities using different ranges (including melee range) or a few specific boss encounters which depend on range checks

its not a test is to calm the nerves in the spirit of...
"Well, nothing seems to have broken." 

I'm sorry, but it doesn't work like that.
Either it's being tested thoroughly and accurately. Or what's all this for, then?
what you're suggesting is to do the job mediocrely.
in which case it's better not to do it at all.

**Comment by Viste** [comment]
and about 

> But the original TC Issue explains nearly nothing

REALLY? 
Снимок экрана от 2020-02-19 23-24-04

**Comment by BarbzYHOOL** [comment]
This PR might be useful, it would require someone to run it long enough though.

Retrydev has been banned, thanks for everything you did for us (= nothing).

**Comment by BarbzYHOOL** [comment]
> in which case it's better not to do it at all.

No, it's not better to not test at all, that's stupid. You're just too lazy to explain how to test and you don't want to follow our very small set of rules (correct usage of git, correct usage of github mostly), but you're not lazy to write all these illogical arguments, that's pathetic.

One of the reason people use AC is because it's very stable. All the concerns from Stoabrogga/Shin are logic, valid and these two staff members are both professional **software** developers. 

Now that you closed the PR, stop arguing, nobody agrees with you but your friends. I could even test it myself if there were some instructions but you prefer us to blindly believe in you. I'm sure you would not agree if other people pushed PRs and we would blindly merge everything all the time.


The PR can be reopened with more instructions.

Last warning: respect the people managing this repository, without them everything stops and there is no more AzerothCore, no more pull request, nothing.


@V3nomAnc3r I hope you can tell us how the fix goes and if you can run it long enough, it would be nice.

**Comment by Stoabrogga** [comment]
> and this is just a start of issue ))

Yes, this was the part I understood. But they did not explain why they fixed it the way they did, and that's what I'm interested in. I want to understand the logic behind the changes.

And concerning testing: If the software change affects more or less the whole product, and the product is too complex to be tested thoroughly, you have to identify a few representative test cases in order to reduce the risk of regression. It never can be perfect (risk = 0), but it is much better than not testing at all.
The other method would be introducing some kind of test system where many players can play and report bugs (Blizz PTR), but this is not possible for such a small project.

**Comment by Viste** [comment]
@BarbzYHOOL I've already said that often the code is enough to know what changes you'll see in the game.
The language barrier prevents you from grasping the essence of what I'm saying.
Your test rules only work if there are minor changes that are easy to check. When the change is global, all these tests can be divided by 0.
Half of your stuff, can not understand by the code +- what changes it carries... 
I'm sorry, but it's okay to communicate about any changes in the kernel only with Yehonal/Winfi/Kaev/Rochet2. 

I've got an example of how thats true tested works... PR was tested, merged, than someone saw an unusual/new behavior, got scared and all work reverted )))) nice nice 

вот почему я говорюч то надо тестировать все полностью и до конца. Ну или не тестировать вообще. Результат все равно будет один. Либо все будет хорошо и классно. Либо вы откатите коммит назад.

**Comment by BarbzYHOOL** [comment]
We merged a big PR from Winfi (taken from TC) and it reverted several of our fixes. And sometimes testing is not enough. Better test a little than nothing.


Anyway I said stop arguing else I close the discussion here  (because everyone is repeating itself). I understand your point of view and there is no language barrier because I had understood this before your last post.

And Yehonal would agree with us. You can ask him if you want.

**Comment by FrancescoBorzi** [comment]
> I've already said that often the code is enough to know what changes you'll see in the game.

And I've already said many times that not all testers are programmers so they CANNOT simply read the code and figure out what needs to be tested. But you keep ignoring this and expecting everyone to just "look at the code" in order to understand how to test it.

> I've got an example of how thats true tested works... PR was tested, merged, than someone saw an unusual/new behavior, got scared and all work reverted )))) nice nice

it's not about being "scared". It is about: if a PR introduces a new bug, and NO ONE is able to fix that bug (including the PR's author), the only thing we can do is to revert that PR. It is sad, of course, but there is no alternative.

**Comment by Yehonal** [comment]
@Viste , there are people who have the awareness of the entire system to read the code, there are people that have the half-awareness of it, and there are people who don't have it but can still understand when someone explains things in detail.

I always love to read the entire code of the PR and check every single bit that has been changed because, even the TC changes, sometimes are brainfart products.
That's why I always suggest describing in the best way what you did, it's also because sometimes people try to port things from TC without being aware of the entire system and we don't have a complete testing layer that ensures us your code fix 2 things and breaks everything else.

Given that, it's just a behavior suggestion for you, to contribute, to let me know that you know what you do, to help people to understand how things work reading your description etc.
I love this kind of contribution. At least, try to do it when requested and do not rage-quit or stuff like that please. 

About the code, it's a very old range hack and this issue is related to test what happens: https://github.com/TrinityCore/TrinityCore/issues/17060

maybe starting from it we can see if on AC we're having the same issue and what happens with this patch instead. And maybe it can be related: https://github.com/azerothcore/azerothcore-wotlk/issues/2440

But please, stop to waste time and comments for these useless discussions. There is no professional project in the world that can accept a big PR like that without having more detail and tests. If you don't want to collaborate in this way @Viste I don't have anything against, but we've to close "malformed" or untestable PRs and, in that case, you can just smile like us, without anyone going crazy  :)

**Comment by FrancescoBorzi** [comment]
> we don't have a complete testing layer 

actually we don't have an (automated) testing layer at all, that's the biggest issue of WoW emulation imho

**Comment by Stoabrogga** [comment]
Closing this as there's another solution: #2686 
Also AC uses a different code base than TC, it evolved in it's own way since the projects did part ways 2012, so in order to not risk destabilization of the core no TC commits should be taken over blindly, they should only taken into consideration as "inspiration" for our own fixes (we actually have to analyze and fix such stuff on our own). AC is an independent project, it is **not** just another TC fork.

Btw, the commit which this PR was based on is very old and caused months of bugs, just follow the linked discussions of the original TC issue (and subsequent discussions).

**Comment by Yehonal** [comment]
Thanks @Stoabrogga for your analysis on this PR

I totally agree with you

**Pull request closed without merging**
