### PR TITLE
fix(DB): Reverting past node changes

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
- Until pooling and/or dynamic spawn is introduced, nothing should
  change related to pooling because once the objects are consumed, they
  won't respawn.

## Issues Addressed:

- Closes pooling of mineral nodes recent changes not respawning

## Tests Performed:

- Tested on Windows 10

## How to Test the Changes:

1. Roam around Elwyn Forest and Duskwood and make sure nodes respawn. Don't pay attention to quantity or spawning of them.

## Known Issues and TODO List:

None.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
There's a few entries on the logs that I didn't notice so I'm fixing them quickly.

**Comment by Kitzunu** [comment]
Yikes

**Comment by Nyeriah** [comment]
@azerothcore/testers please test this

**Comment by Hacki95** [comment]
"Until pooling and/or dynamic spawn is introduced, nothing should
change related to pooling because once the objects are consumed, they
won't respawn." 

That makes no sense in my eyes if the changes are still better right now while we wait for those system.

So if you want to revert past node changes it should be done at the same time when a new system is also ready to be tested.

Imagine this getting merged and then nobody ever tackles dynamic spawn or the pool issues.

**Comment by claudiodfc** [comment]
I can't promise anything, but this is mostly to resolve the problems chromiecraft and other servers are probably having, where copper doesn't spawn for anyone and makes mining, blacksmithing and other professions blocked. I'm gonna start working on pooling and spawning my next task, so this is pretty much a needed temporary change as to make the game at least playable.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
