### PR TITLE
Gathering Quest While in Party bug

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
Correct the problem that the bag when obtaining the item, by one of the group members, currently does not disappear, and remains so, until the body disappears. In this way, it is prevented the immediate stripping of the creature being in a group for example.

## Issues Addressed:
- Closes 

https://github.com/azerothcore/azerothcore-wotlk/issues/4399
https://github.com/chromiecraft/chromiecraft/issues/20

## Tests Performed:
- Windows

## How to Test the Changes:

Create a group, and perform a quest with an item that must be obtained by killing a creature. If the item does not have the flag that everyone can obtain it, only 1 should be able to obtain it.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pangolp** [comment]
While the pull request solves part of the problem. We have to check another related problem. In the database, there are items that have to have a flag, the number 2048, which allows everyone to get the item. The problem is that it is not in all, then, we will have to detect them later and add the corresponding flag.

```sql
-- https://www.wowhead.com/item=22889/vial-of-moth-blood
UPDATE `item_template` SET `Flags`=`Flags`|2048 WHERE `entry`=22889;
```

loot

```
| Flag | Hex    | Comments                                    |
|------|--------|---------------------------------------------|
| 2048 | 0x0800 | Item is party loot and can be looted by all |
```
```sql
SELECT `entry`, `name`, `flags` FROM `item_template` WHERE `entry`=22889;
```
```
| entry | name               | flags |
|-------|--------------------|-------|
| 22889 | Vial of Moth Blood | 0     |
```

**Comment by Kitzunu** [comment]
A lot of quests shouldnt have it.

For example the majority of quests where you have to gather more than one item should not have that flag

**Comment by pangolp** [comment]
> A lot of quests shouldnt have it.
> 
> For example the majority of quests where you have to gather more than one item should not have that flag

It is that most of them do not have it, however, some do. That is why I do not propose to add them all. Rather, we will have to detect which are the ones that should be modified. But that is the subject of another issue or pull request. This fix helps to remove the bag, in case it does not have the flag, which is also necessary. Because if it does not have the flag, and on top of that, this modification is not done, the bag will always remain in the npc once it is dead. For which, the usual behavior is that once someone gets the item, if he does not have the flag, it is no longer available, for example, to be skinned, in the case of a beast.

**Comment by pangolp** [comment]
The pull request does not assign the flag, it removes the bag.
The comment I made above should actually go in another issue.

**Comment by pangolp** [comment]
This item is a case of one that should have the flag, but I agree that they are not all.

**Comment by pangolp** [comment]
Another example of an item that should be obtained by everyone is this: https://www.wowhead.com/item=22934/lasher-sample and only let one person in the group actually obtain it. That is why I mentioned that although they are 2 different topics, they are related. That is why I may have generated confusion. But we have another pull request, that I also have to try, because maybe it will solve the problem.

https://www.wowhead.com/items?filter=166:98;3:1;0:0
That could be a possible list. But I must continue my research.

**Comment by 55Honey** [comment]
> A lot of quests shouldnt have it.
> 
> For example the majority of quests where you have to gather more than one item should not have that flag

From my leveling experience on a Master core from last years June, i can confirm that especcially in Northrend lots of questitems were only lootable by a single character. Especcially those obtained from objects.

**Comment by pangolp** [comment]
> > A lot of quests shouldnt have it.
> > For example the majority of quests where you have to gather more than one item should not have that flag
> 
> From my leveling experience on a Master core from last years June, i can confirm that especcially in Northrend lots of questitems were only lootable by a single character. Especcially those obtained from objects.

Thanks @55Honey. Correct. The pull request partially solves the problem. Because what it does, is that at least, one gets it and then it is no longer available. The complement to this is to check the loot party items and add the flag to them. Not all items have this condition, but there are several.

**Comment by pangolp** [comment]
Here is an example of an item that has the flag.
Maybe not many are missing, but evidently that is the arrangement.
```sql
SELECT `entry`, `name`, `flags` FROM `item_template` WHERE `entry`=36746;
```
```
| entry | name                      | flags |
|-------|---------------------------|-------|
| 36746 | Goramosh's Strange Device | 2048  |
```
I think this fix should be applied, and at the same time, add the flag to the items. Now I am going to make another pull request, with the items that I have detected and that I know are loot part items.

**Comment by pangolp** [comment]
Here we have information about items from level 1 to 19.
https://wowgaming.altervista.org/aowow/?items&filter=cr=98:5;crs=1:1;crv=0:0;minle=1;maxle=19#0+2

**Comment by pklloveyou** [comment]
It works, but I don't know if it will affect other actions

**Comment by pklloveyou** [comment]
I'll put it on the server on Monday for players to test

**Comment by pangolp** [comment]
I tried it, with several missions and that's what happened. The loot would appear, someone would get it, and the second one you couldn't get it anymore, but at least, the bag disappears and allows you to skin it for example, in case it's a beast. Now, however, if you were in a party, you could not get the hides. Thanks for your interest @pklloveyou

**Comment by pklloveyou** [comment]
So far, no player has reported an error

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by pangolp** [comment]
Thank you @pklloveyou

**Pull request merged**
