### PR TITLE
fix(Core/Pets) Pet scaling only being applied to pets with DB Entry

### PR DESCRIPTION
**Pull request by alaxandir**
Original script was only applying the config option `CONFIG_ALLOWS_RANK_MOD_FOR_PET_HEALTH` (Pet.RankMod.Health)
to pets who did *not* have a DB entry. It was part of the else statement.

This PR creates a new if statement above the else statement where the scaling value will be applied appropriately if this bool is true.

## Changes Proposed:
-  Apply this change to core core to allow all pets to be scaled appropriately to config options if they have a DB entry and also without a DB entry.

## Issues Addressed:
- Further improves https://github.com/azerothcore/azerothcore-wotlk/issues/11480

## SOURCE:
- After testing noticed that pets without a DB entry would not scale regardless of the config option `Pet.RankMod.Health` being set to true or false.

## Tests Performed:
- Rebuilt without errors. 
- Tested locally on entity 8996 (Voidwalker Minion)
- Tested locally on entity 416 (Imp)

## How to Test the Changes:
1. go to orgrimmar burning blade cave
2. observe caster minion (voidwalker) hp with `Pet.RankMod.Health` = 0 and `Pet.RankMod.Health = 1`

## Known Issues and TODO List:
- There may be some outlier summons I have not thought about for this change, but it should not be a breaking change, it will merely scale the HP values to the global modifiers in the `worldconf` if they are changed and if the `Pet.RankMod.Health` is true.

### CODE REVIEW

**Comment by alaxandir** [comment]
Okay I need help with the styling, I don't know why it keeps finding whitespace on lines I didn't change.

**Comment by heyitsbench** [comment]
> I don't know why it keeps finding whitespace on lines I didn't change.

Styling

**Comment by FrancescoBorzi** [comment]
what's the status of this?

**Comment by alaxandir** [comment]
It works, i resolved the styling changes requested.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
