### PR TITLE
fix(Scripts/ICC): Intro Event Timers and Text

### PR DESCRIPTION
**Pull request by Voxstrasza**
## CHANGES PROPOSED:
-  Change the first line of Tirion Fordring's text in ICC to correlate to the sound being heard (it had the first two lines of dialogue in one line)
-  Delay EVENT_BOLVAR_INTRO_1 so it doesn't overlap with EVENT_LK_INTRO_4
-  EVENT_TIRION_INTRO_6 now happens sooner, so there isn't an awkward pause after EVENT_LK_INTRO_1, and a healthy pause before EVENT_LK_INTRO_2.

## ISSUES ADDRESSED:
- Tirion Fordring had two lines of text into one.
- Bolvar Fordragon's sound overlapped with The Lich King's sound
- Awkward pauses between voice lines

Current AC, Tirion says this in one big line of text:
Highlord Tirion Fordring yells: This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people!  Remember, hero, fear is your greatest enemy in these befouled halls. Steel your heart and your soul will shine brighter than a thousand suns. The enemy will falter at the sight of you. They will fall as the light of righteousness envelops them!

Current AC, sound for the bolded text overlapped.:
The Lich King yells: The breaking of this one has been taxing. The atrocities I have committed upon his soul. He has resisted for so long, **but he will bow down before his king soon**.
Highlord Bolvar Fordragon yells: **NEVER! I... I will never... serve... you...**

## TESTS PERFORMED:
1. Applied SQL
2. Changed timer (icecrown_citadel.cpp)
3. Build successful
4. Startup, zone into ICC and initiated intro roleplay event

## HOW TO TEST THE CHANGES:
1. Apply SQL, build, launch server
2. Create character
3. .tele icecrowncitadel, .gm on and zone into ICC on any difficulty, either faction
4. Kill the first two "The Damned" to initiate roleplay
5. Pay close attention to Tirion's text in the beginning, it is now split properly between sound files
6. Wait towards the end, and listen for Lich King to finish saying "bow down before his king soon" - Bolvar no longer starts speaking before the Lich King finishes.

## Target branch(es):
- [x] Master

Huge thanks to Barbz for walking me through my first PR :)

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Comment by Krath** [comment]
This timer needs to be changed aswell: _events.ScheduleEvent(EVENT_LK_INTRO_2, 58000);
Changing it to 60000 will fix another overlap

**Comment by Krath** [comment]
image
I applied the SQL, but the text is still showing me the two lines. Did I do something wrong?

**Comment by Voxstrasza** [comment]
> 
> 
> image
> I applied the SQL, but the text is still showing me the two lines. Did I do something wrong?

hmm, the SQL makes the changes but doesn't push it to reflect in-game.. can someone take a look at this?

`UPDATE `creature_text` SET `Text`='This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people!' WHERE  `CreatureID`=37119 AND `GroupID`=0 AND `ID`=0;`

**Comment by Voxstrasza** [comment]
@Krath try this

```
UPDATE `broadcast_text` SET `MaleText`='This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people!' WHERE  `ID`=36923;
```

**Comment by Krath** [comment]
> @Krath try this
> 
> ```
> UPDATE `broadcast_text` SET `MaleText`='This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people!' WHERE  `ID`=36923;
> ```

This fixed the issue! Roleplay event is fine now (after applying this SQL and the two timers changes).

**Comment by Voxstrasza** [comment]
> 
> 
> > @Krath try this
> > ```
> > UPDATE `broadcast_text` SET `MaleText`='This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people!' WHERE  `ID`=36923;
> > ```
> 
> This fixed the issue! Roleplay event is fine now (after applying this SQL and the two timers changes).

I have added the new sql and some more modifications to the timer in the script - please test the script when you can

**Comment by Krath** [comment]
> > > @Krath try this
> > > ```
> > > UPDATE `broadcast_text` SET `MaleText`='This is our final stand. What happens here will echo through the ages. Regardless of outcome, they will know that we fought with honor. That we fought for the freedom and safety of our people!' WHERE  `ID`=36923;
> > > ```
> > 
> > 
> > This fixed the issue! Roleplay event is fine now (after applying this SQL and the two timers changes).
> 
> @Krath I have added the new sql and some more modifications to the timer in the script - please test the script when you can

Tested it, looks good to me!

**Comment by BarbzYHOOL** [comment]
so @krath to be merged?

**Comment by Krath** [comment]
> so @Krath to be merged?

Yeah, it's fine for me

**Review by Si1ker — APPROVED** [review]
Thanks for this PR @Voxstrasza 
cc @FrancescoBorzi to merge

**Comment by FrancescoBorzi** [comment]
merged, just a note: this is "Scripts", not "Core" :)

**Pull request merged**
