### PR TITLE
feat(CI): Configured Coverity in Travis

### PR DESCRIPTION
**Pull request by Yehonal**
## CHANGES PROPOSED:

Testing coverity with travis

## HOW TO TEST THE CHANGES:

we just have to wait for travis

## Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Yehonal** [comment]
@Stoabrogga could you help me to understand what failed here? maybe I've missed one of your script for CI

**Comment by Kitzunu** [comment]
I will close this since we moved to Github Actions

**Comment by Yehonal** [comment]
> _Yehonal slams @Kitzunu with a Github Action version of the coverity CI_

https://github.com/azerothcore/azerothcore-wotlk/pull/3004

**Comment by Kitzunu** [comment]
Hahahaha, great work :P

**Pull request closed without merging**
