### PR TITLE
fix(DB/NPC): remove wrong unit_flags to Knight of the Ebon Blade

### PR DESCRIPTION
**Pull request by Helias**
## CHANGES PROPOSED:
-  remove these unit_flags value
image

I used [Keira3](https://www.azerothcore.org/Keira3/) to do this.

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/644

## TESTS PERFORMED:
- Tested in-game

## HOW TO TEST THE CHANGES:
```
.go creature id 31084
.gm off
.mod phase 488 (use this even if you do .gm on and .gm off in a second time)
.quest add 13166
```
Well, use the purple platform to teleport yourself downstairs and fight with some NPCs like the video shows.
https://www.youtube.com/watch?v=QHWpZexZODY

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pangolp** [comment]
Although, it makes the npc's start to fight with the other npc's. Only the ones on top were attracted and the other 2 did not move. When I activated the GM, one of the abominations began to fight with one of the center, but I think that the npc, would be missing something else. Perhaps to modify them the script.

WoWScrnShot_112820_112902
WoWScrnShot_112820_112920

**Comment by pangolp** [comment]
According to the video, npc's look like they have some skills, but I checked and currently have no script assigned to them. It should be seen if you can get information about these skills.

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Si1ker** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/3797   🐱

**Comment by Helias** [comment]
closed for https://github.com/azerothcore/azerothcore-wotlk/pull/3797

**Pull request closed without merging**
