### PR TITLE
fix(DB/gameobject): Update Z pos for gob guid 45150

### LINKED ISSUE #12615: Gloom Weed node unreachable
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

Gloom Weed node is unreachable. Z axis value is too high.

object:
https://wowgaming.altervista.org/aowow/?object=175566

related quest:
https://wowgaming.altervista.org/aowow/?quest=5481

.gobject near:
45150 (Entry: 175566) - [Gloom Weed X:2267.100098 Y:972.916992 Z:57.582500 MapId:0]

.gobject info:
Entry: 175566
Type: 3
Lootid: 13364
DisplayID: 4111
Name: Gloom Weed

image

### Expected Blizzlike Behaviour

A plant should be mounted on a surface and not be flying mid air.
A gathering node should be reachable by a player character.

Proposed new values for the node:
X: 2267.100098 Y: 972.916992 Z: 44.418785

### Source

No reports of unreachable nodes in wowhead entries for both the object and related quest.

https://www.wowhead.com/object=175566/gloom-weed#comments
https://www.wowhead.com/quest=25038/gordos-task#comments

### Steps to reproduce the problem
.go gameobject 45150 

### Extra Notes
Original Report:
https://github.com/chromiecraft/chromiecraft/issues/3872

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/d580ca4f316c66893ec76282c8dd3e0762d3f662

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Si1ker**
## Issues Addressed:

- Closes #12615
- Closes https://github.com/chromiecraft/chromiecraft/issues/3872

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — APPROVED** [review]
But the weed wants to fly and be free :(

**Comment by Si1ker** [comment]
no need for additional testing, I forgot to add a proof of i, here's it:

image

**Comment by acidmanifesto** [comment]
> no need for additional testing, I forgot to add a proof, here's it:
> 
> image
> 

I rather stick to procedure and have it independently tested or let someone else merge it.

**Comment by Si1ker** [comment]
> > no need for additional testing, I forgot to add a proof, here's it:
> > image
> 
>  let someone else merge it.

ok.

**Comment by heyitsbench** [comment]
Position_Z should be set to whatever shortened version of 44.485706 according to TBCC sniff.

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Please adjust per sniff information provided.

**Comment by heyitsbench** [comment]
Tested, working as described. 👍

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
