### PR TITLE
feat(Core/Scripts): implement cs_bg command script

### LINKED ISSUE #10686: Feature: better commands to debug BGs
### Describe your feature request or suggestion in detail

Commands such as:

- `.bg start`  once inside a BG which is not started yet, start the BG immediately
- `.bg win` once inside a BG, close and win the current BG
- `.bg lose` once inside a BG, close and lose the current BG

### Describe a possible solution to your feature or suggestion in detail

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
-  
-  

## Issues Addressed:
- Closes #10686

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by DepTypes** [comment]
https://user-images.githubusercontent.com/99797316/154404003-cf519451-53aa-406a-8849-26a9793a725b.mp4

We were implementing this at the same time. So we went a bit different ways. But I have a few more useful features implemented. Should I try to shoehorn in to this PR when I have the time or open a new one?

**Comment by Winfidonarleyan** [comment]
@DepTypes, I can add your code to my PR

**Comment by acidmanifesto** [comment]
What is the current status of this? Is it abandoned?

**Comment by Winfidonarleyan** [comment]
> What is the current status of this? Is it abandoned?

Yes

**Pull request closed without merging**
