### PR TITLE
feat(CI/Codestyle): added codestyle check

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## CHANGES PROPOSED:
- Added code style check

## Target branch(es):
- [x] Master

### TODO
- [x] tabs with 4 spaces
- [x] delete whitespace

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
...

**Comment by Winfidonarleyan** [comment]
Done

**Comment by Winfidonarleyan** [comment]
Ref #4074

**Comment by FrancescoBorzi** [comment]
@Winfidonarleyan where is the check actually added? which file?

**Comment by Winfidonarleyan** [comment]
apps/ci/ci-codestyle.sh

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
good job @Winfidonarleyan !

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
@Winfidonarleyan merge conflicts

**Pull request merged**
