### PR TITLE
feat(Cmake): set policy CMP005 to NEW

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
Based TC commit https://github.com/TrinityCore/TrinityCore/commit/18cc36bc67023dc9ca58e77733c2b8c74655cf86

##### CHANGES PROPOSED:
- Set policy CMP005 to NEW

##### TESTS PERFORMED:
- Configure in Linux

##### HOW TO TEST THE CHANGES:
- Build this

##### KNOWN ISSUES AND TODO LIST:
-

##### Target branch(es):
- [x] Master

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
Build success

**Comment by pklloveyou** [comment]
Build success

**Comment by Winfidonarleyan** [comment]
Thanks for test

**Comment by Winfidonarleyan** [comment]
Need time for solve conflict

**Comment by pklloveyou** [comment]
I can build successfully!!!!!

**Comment by FrancescoBorzi** [comment]
done

**Pull request merged**
