### PR TITLE
Spell/Death Knight: Death Coil.

### PR DESCRIPTION
**Pull request by DevRival**
Changes proposed: Fix formula damage/heal.
- (443 + (AP* 0.15 * impurity)) = damage.
- (665+ (AP* 0.15 * impurity)) = heal.

Target branch(es): 1.x

Tests performed: (Does it build, tested in-game, etc)
Tested in-game , works as intended.

Known issues and TODO list: No issue.

### CODE REVIEW

**Comment by ShinDarth** [comment]
@DevRival why did you delete this?

**Comment by DevRival** [comment]
I forgot about the Impurity of the talent.

**Comment by DevRival** [comment]
Need help, I decided talent impurity problem , but a problem of the work of the talent calculation of damage is too small. If talent should add 4 % is, in reality there is not even 2% .

**Comment by ShinDarth** [comment]
can you resolve conflicts?

**Comment by DevRival** [comment]
What's the conflict?

**Comment by ShinDarth** [comment]
@DevRival  rebase your branch and you will see all conflicts

**Comment by DevRival** [comment]
@ShinDarth  [Done](https://github.com/azerothcore/azerothcore-wotlk/pull/109)

**Comment by ShinDarth** [comment]
that is not what I meant, you didn't need to open a new PR

but it's ok 👍

**Pull request closed without merging**
