### PR TITLE
LANG_COMMAND_KICKMESSAGE_WORLD

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## HOW TO TEST THE CHANGES:
1. ShowKickInWorld = 1 (worldserver.conf)
2. .kick PlayerName Reason

## Target branch(es):
- [x] Master

### CODE REVIEW

**Comment by pklloveyou** [comment]
Tested, it worked perfectly

**Comment by FrancescoBorzi** [comment]
good job @IntelligentQuantum and thanks a lot @pklloveyou !

**Comment by BarbzYHOOL** [comment]
So it displays the kick reason now, right? @IntelligentQuantum

**Comment by IntelligentQuantum** [comment]
Yeah
Server: %s has kicked %s, reason: %s

**Comment by BarbzYHOOL** [comment]
ok merged, thank you!!!!!!

**Pull request merged**
