### PR TITLE
chore. Remove core module validations

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:

This PR proposes changes to:
- [x] Ci

image

## Issues Addressed:

- Closes 

## SOURCE:

The changes have been validated through:

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.

## How to Test the Changes:

1. Currently, every time the tests are run, this list of modules, which have nothing to do with the emulator tests, is checked. Each module has its own validations, which must be passed before merging it. Checking it again, here in the core, does not really make sense. Because every time one of the modules fails, the validations will not be passed, and that can generate confusion in the people who make contributions.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pangolp** [comment]
If you do not want to delete the files, I can restore them, and we can leave the list empty in any case, but I think that leaving the list empty does not make sense.

**Comment by sudlud** [comment]
One benefit is that it compiles with all these module at the same time, which a module CI will not do.

I could imagine that this CI was created to ensure that everything will compile with the modules e.g. beeing used on CC.

But from the view of AC alone, which has the main focus on the core itself, it's correct that it should not really "care" about any collection of modules compiling together nicely.

**Comment by pangolp** [comment]
> One benefit is that it compiles with all these module at the same time, which a module CI will not do.
> 
> I could imagine that this CI was created to ensure that everything will compile with the modules e.g. beeing used on CC.
> 
> But from the view of AC alone, which has the main focus on the core itself, it's correct that it should not really "care" about any collection of modules compiling together nicely.

This is not the complete list either. There are more than 150 modules, plus those that people create and that the community has not made a fork of them. It would be unnecessary to check them all. The modules already have validations.

**Comment by 55Honey** [comment]
These are mandatory checks for a basic set of modules. Many of them being used on CC. 
I am not sure about all of them, but there's no way we can just remove the whole check.

**Comment by pangolp** [comment]
> These are mandatory checks for a basic set of modules. Many of them being used on CC. I am not sure about all of them, but there's no way we can just remove the whole check.

I left you my answer privately, to avoid misunderstandings. Unfortunately, I do not agree.

**Comment by pangolp** [comment]
@azerothcore/developers Please, if you can express your opinion about this change, it would help me a lot. My argument, in case it is not clear, is that the modules already have validations. I don't see why, the emulator also has to validate that this list of modules (which are not all), have to pass the tests every time a person makes a change within the emulator. His thoughts or any type of change that can be made in this regard is appreciated.

**Comment by 55Honey** [comment]
It is mandatory for us to notice common modules not compiling before the build fails. This PR can not be accepted.

**Comment by 55Honey** [comment]
It is mandatory for us to notice common modules not compiling before the build fails. This PR can not be accepted.

**Comment by FrancescoBorzi** [comment]
> My argument, in case it is not clear, is that the modules already have validations.

The modules already have validations indeed, but this is testing the INTEGRATION between AC and modules so this is another kind of check.

I'm against removing it.

**Pull request closed without merging**
