### PR TITLE
fix(DB/Creature): faction of ravenoak

### LINKED ISSUE #4226: Brother Ravenoak (NPC 5915) Wrong Faction
Brother Ravenoak (NPC 5915) Wrong Faction 

##### CURRENT BEHAVIOUR:

Currently hostile to alliance. Wasn't made hostile to alliance until 4.0.3

https://classic.wowhead.com/npc=5915/brother-ravenoak

https://vanilla-wow.fandom.com/wiki/Brother_Ravenoak

https://www.wowhead.com/npc=5915/brother-ravenoak#comments

image

##### EXPECTED BLIZZLIKE BEHAVIOUR:

Friendly to alliance.

##### STEPS TO REPRODUCE THE PROBLEM:

1. Appear at NPC 5915 or go to Stonetalen/Ashenvale tunnel as Alliance
2. Observe hostile behaviour
3. 

##### EXTRA NOTES:

Chromiecraft 07-01-2021.
79aa5606547d

##### AC HASH/COMMIT:

Chromiecraft 07-01-2021.

##### OTHER CUSTOMIZATIONS:

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95766398-brother-ravenoak-npc-5915-wrong-faction?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Helias**
Fix created by [Keira3](https://www.azerothcore.org/Keira3/)

## Changes Proposed:
-  change faction from 14 to 124, like the other NPCs near him (the faction 124 is the same on TC too)

## Issues Addressed:
- Closes #4226

## Tests Performed:
- tested in-game

## How to Test the Changes:
- `.go c id 5915`
- use horde and alliance character and check the faction, it should be enemy as horde and friendly as an alliance

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by JamesGent** [comment]
Tested and checked. I did not recompile as it is SQL only, but this fixed it on my end.

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
could you say which faction is now, incase it's needed in the future?

**Comment by r0m1ntik** [comment]
> could you say which faction is now, incase it's needed in the future?

14 (Monster)

**Comment by pklloveyou** [comment]
Tested 
image

**Pull request merged**
