### PR TITLE
Adding information to the ip2nation table and ip2nationCountries

### PR DESCRIPTION
**Pull request by pangolp**
## Changes Proposed:
-  Through the information provided by the web [ip2nation.com](http://www.ip2nation.com/ip2nation/Download), the idea is to add the information within the table.

## Issues Addressed:
- Closes 

## Tests Performed:
- If you use the `.player info` command you should be able to get the player's country.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Kitzunu** [comment]
The question is if we really should populate these tables. A lot of data for those who do not want or need it. and can be easily imported from the website by anyone

@FrancescoBorzi @Helias @Yehonal

**Comment by pangolp** [comment]
> The question is if we really should populate these tables. A lot of data for those who do not want or need it. and can be easily imported from the website by anyone like https://www.azerothcore.org/wiki/ip2nation suggests
> 
> @FrancescoBorzi @Helias @Yehonal

It can be an alternative, I don't really know. I thought it might be a good idea to import the data and know where the people are from.

**Comment by Yehonal** [comment]
Instead of adding it within the core, we could open/create a repo for it and link that repo to our catalogue. Would it be a good solution?

**Comment by Kitzunu** [comment]
Well it is linked on the wiki already :shrug: But I suppose that works too

**Comment by pangolp** [comment]
This could be an option. Anyway, in the wiki, the file you download is all together and it has an INSERT for each record. Here I left only 1 INSERT. I think it would be interesting, to leave it somewhere, for whoever wants to add it.

**Comment by FrancescoBorzi** [comment]
@pangolp thanks a lot for this contribution, however I agree with @Kitzunu and @Yehonal . I don't think this should be part of the core as it's a lot of data and not everyone needs it, an optional feature is enough :)

**Comment by pangolp** [comment]
Yes, I think it's a good idea.

**Comment by pangolp** [comment]
I also think it's a good idea to have it as an optional resource.

**Comment by den13501** [comment]
tested, it work

**Comment by pangolp** [comment]
> tested, it work

Thanks for the test, but in the end, will not be incorporated into the emulator, will be available for those who want to apply it, but as something optional.

**Comment by Kitzunu** [comment]
I have made a module, will port later

**Pull request closed without merging**
