### PR TITLE
fix(DB/SmartAI): Stinky's Escape Combat and Talk

### PR DESCRIPTION
**Pull request by Ella36**
"Stinky" Ignatz does not attack NPCs and his IC dialogue targets the player instead of his target 

## Changes Proposed:
-  Remove setting react state 2. Set react state when waypoint starts to 1
- Update talk target to victim for line 10
- Disable assist player flag in template

## Issues Addressed:

Closes: https://github.com/azerothcore/azerothcore-wotlk/issues/7624

## How to Test the Changes:

.go c 68946                                                                     
start quest
As described in the issue

1. Player attacks mob - Escortee does not react 
2. When Escortee gets attacked by a mob it should react

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Hi, tested but he react always when a hostile creature is near him. Even if the creature was engage by the player.

**Comment by SoglaHash** [comment]
> Hi, tested but he react always when a hostile creature is near him. Even if the creature was engage by the player.

Dragging a mob over the NPC does make it react.

Currently the script sets his state to 2 (aggressive) and is then overwritten to 0 (passive) which is why he did not attack at all.
When updating his state to 2 (aggressive) he went goes off running to attack any mob. So changing to 1 (defensive) should be correct?

I've tried changing his faction from 250 to 133 but did not notice a difference in behavior
```
FACTION_ESCORTEE_N_NEUTRAL_ACTIVE 250 (current)
FACTION_ESCORTEE_N_NEUTRAL_PASSIVE 113 
```

Played with `unitflags` did not get intended behavior
```
UNK_16 - No Attack 2
PACIFIED - Creature will not attack
NON_ATTACKABLE
NOT_ATTACKABLE_1
```

I'm not sure how to make him ignore unless attacked as you describe. Maybe I'm missing something

**Comment by Maelthyrr** [comment]
It's a strange behavior to not react when a hostile enemies is near, but I don't think that you can do something with this PR. It's more a EscortIA features. I will pass this PR in "to be merged", but can you open another issue about this? This need more investigation.

**Comment by acidmanifesto** [comment]
changing label to need feed back.

**Comment by acidmanifesto** [comment]
We need this tested and we will need the previous review request to follow up.

**Comment by Kitzunu** [comment]
PR abandoned. If you want to continue to work on this, reopen it or make a new one.

**Pull request closed without merging**
