### PR TITLE
fix(Core/Tools): Revert "Handle different slopes in  mmaps and Add so…

### LINKED ISSUE #11811: Various creatures can enter evade mode if attacked while they're swimming
https://github.com/chromiecraft/chromiecraft/issues/3510

### Current Behaviour

If some swimming creatures are targeted from ranged attacks, they'll not be pulled and will instead instantly start evading.

https://user-images.githubusercontent.com/100873791/169362938-b30954ed-b951-43f3-bb8a-1786abf045cb.mp4

https://user-images.githubusercontent.com/100873791/169363036-cbbfcf5a-c90c-4ec0-b04f-8e23e7969658.mp4

https://youtu.be/3H7Tfjm6fLY

### Expected Blizzlike Behaviour

They should be able to reach the player.

### Source

_No response_

### Steps to reproduce the problem

Very inconsistent and hard to reproduce, but I've found that this spot is easier:
1. `.go xyz 6118 647 -1.5 1`
2. attack several different creatures with ranged attacks.

Also, try avoiding the surface and the "floor", as being in the middle of those 2 will cause the issue more often.
Moving around (especially vertically) while the creature is aggroed to you may also cause the issue.

### Extra Notes

Both the Pygmy Tide Crawler (ID: 2231) and the Darkshore Thresher (ID: 2185) have CTM, while the Greymist Coastrunner (ID: 2202) **does not**, and all three can have the same/similar evade issue.

The Thresher that has its head above the water I think it's part of another issue: https://github.com/azerothcore/azerothcore-wotlk/issues/10383

evade

The original poster also had auto-attack issues following their encounter with another bugged creature: a Surf Crawler (ID: 3107) in Echo Isles. They also have a CTM row.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c7f74e563758241e29721e95b86aed0093a8856a

### Operating system

Windows 10

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### LINKED ISSUE #12079: Fear movement can cause player to clip out-of-bounds
https://github.com/chromiecraft/chromiecraft/issues/3606

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

Victims of fear effects sometimes glitch out of bounds. I noticed this happening in Arathi Basin in Lumber Mill where victims of Fear effects glitch under the map. In Warsong Gultch, in Alliance base on the path to roof, feared players sometimes run through the wall behind the table.

### Expected Blizzlike Behaviour

Fear should not make you glitch out of bounds.

### Source

_No response_

### Steps to reproduce the problem

1. Queue Arathi Basin
2. Go to Lumber Mill
3. Fear enemy player
4. Enemy player sometimes falls through the map

Triager:
This spot seemed to reproduce this problem fairly often: `.go xyz 805.342651 -4412.438477 40.045872 1 4.757246`

### Extra Notes

Player glitched behind wall after having warlock [Fear] used on them. Screenshot taken from live server.

WoWScrnShot_061222_131243

Thanks to minthes and Syn for providing video evidence!

On the PTR realm with commit https://github.com/azerothcore/azerothcore-wotlk/commit/6ffb8aae6eaf

https://user-images.githubusercontent.com/22718174/174215893-040b0641-9183-4ea0-b894-8c070d4f55f3.mp4

https://user-images.githubusercontent.com/22718174/174216261-e84580be-7f6d-445d-a83b-e6d1407de416.mp4

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/c0ab2ab08e001ffce3c688eaf54301608af109a8

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…me more input parameters to improve"

This reverts commit b544eb420ed54ba98fb0522f8814ce6b7e089094.
**NEW MMAPS ARE REQUIRED**
Fixes #12079

## Changes Proposed:
-  @IntelligentQuantum I'm reverting your commit b544eb420ed54ba98fb0522f8814ce6b7e089094 as it is the cause of problems with too high walkable slopes. You can bring it back and try to fix it whenever you like. 

## Issues Addressed:

- Closes #12079
- Closes #11811
- Closes https://github.com/chromiecraft/chromiecraft/issues/3606
- Closes https://github.com/chromiecraft/chromiecraft/issues/3510

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go xyz 805.342651 -4412.438477 40.045872 1 4.757246`
`.aura 5782`

`.go xyz 6118 647 -1.5 1`
attack several different creatures with ranged attacks.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by UltraNix** [comment]
ONLY NEW MMAPS ARE REQUIRED.

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by Gultask** [comment]
I gave it a try. Pathing issues with water mobs were solved from what I could see. But I couldn't get fear to work properly, although I'm *pretty sure* I messed up somewhere in the mmap generation. :p
I did get the `MMAP:loadMap: 0005530.mmtile was built with generator v14, expected v15` errors, if that changes anything.

Another good spot to test fear is `.go xyz -9757.979492 -2095.850830 90.512932 0 2.7202217` in Redridge Mountains, if you're looking for a Eastern Kingdoms example, but I did try with the Kalimdor spot as well.

**Comment by UltraNix** [comment]
@Gultask Yep - you are using old mmaps.

**Comment by temperrr** [comment]
tested
[x] swimming creatures dont evade on ranged attack
[x] Gahzranka no longer evades
[x] seems to have fixed the fear issue, tried to get myself under the floor but couldnt get it to work.
[ ] breaks blink in water again (follow terrain instead of the water)

**Comment by guason9721** [comment]
the maps have a problem that in orgrimmar where tharll is there are 3 thralls and there are 3 portals one of them to go to stormwind, the portals are right near thrall.

**Comment by UltraNix** [comment]
@guason9721 Just open a new report.

**Comment by vurtne** [comment]
who is passwd?

**Comment by acidmanifesto** [comment]
> who is passwd? 

passwd is a command on Unix, Plan 9, Inferno, and most Unix-like operating systems used to change a user's password. The password entered by the user is run through a key derivation function to create a hashed version of the new password, which is saved. Which has nothing to do with this PR.

**Pull request merged**
