### PR TITLE
fix(DB/creature_formations): Thal'trak Proudtusk pathing

### PR DESCRIPTION
**Pull request by LukasVolgger**
Use creature_formations instead of pathing for each npc. This avoids that they get out of sync after a while or get stuck.

Without the PR:
----------

image

With the PR:
----------

image

## CHANGES PROPOSED:
-  Delete own waypoints for creatures 6886, 6883, 6880, 6877
-  Create creature formation for creature 6885

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:

- Imported SQL with HeidiSQL on Win 10 Pro x64
- Tested successfully ingame

## HOW TO TEST THE CHANGES:

- .go c 6885 and wait ~ 2 minutes till the caravan starts
- Follow the NPC's and check that everything looks good
- Trty to interact with one NPC - A few seconds later the whole formation should stop and continue after ~ 2 minutes

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Maurowin** [comment]
nice work !

**Comment by Volgger** [comment]
Thx! So you tested it? @Maurowin

**Comment by Maurowin** [comment]
I couldn't test to the end last night, I'll test again tonight and confirm it with a video.

**Comment by Stoabrogga** [comment]
Could you please reduce the formation distance a bit? I tried this and it looks much better:
```sql
-- Create formation
DELETE FROM `creature_formations` WHERE `leaderGUID` = 6885;
INSERT INTO `creature_formations` (`leaderGUID`, `memberGUID`, `dist`, `angle`, `groupAI`, `point_1`, `point_2`) VALUES
(6885, 6885, 0, 0, 515, 0, 0),
(6885, 6886, 3, 0, 515, 0, 0),
(6885, 6883, 6, 0, 515, 0, 0),
(6885, 6880, 9, 0, 515, 0, 0),
(6885, 6877, 12, 0, 515, 0, 0);
```
- The movement is much smoother
- Poor Amakkar doesn't get lost in the hills

**Comment by Maurowin** [comment]
https://youtu.be/DObDRtXGb-g
That's better but not yet that, towards the end of the video, the leader finds himself at the end of the line. I don't know if at the time, it seems to me that it is, but now I think it's the CORE that we'll have to touch, but no matter which NPC we talk to everyone stops. With the WPs, the concern is that they stop at the next point and not instantly.

**Comment by Volgger** [comment]
Thx @Maurowin for that great testing! Keep it up! 

I tested it again and it's the same behaviour like the pathing of PR #2711 where Stoabrogga tested it here: https://github.com/azerothcore/azerothcore-wotlk/pull/2711#issuecomment-592429114

It should be merged as the creation of the formation will be the better way, any improvement of the stop-time can be added in future to core. 

Without the PR and interacting with the NPC's: 
----------

After the interact the npc stops and will continue on his own waypoint without the rest of the caravan.

WoWScrnShot_022920_152509


With the PR and interacting with the leader NPC: 
----------

He stops - after a few yards the rest of the formation also stops. 

WoWScrnShot_022920_152843

The leader will continue walking on the first position after a few minutes:

WoWScrnShot_022920_153038

With the PR and interacting with the member NPC: 
----------

The member will stop and automatically abort the interacting after a few yards: 

WoWScrnShot_022920_153107

He is speeding up and run back to its old position in the formation:

WoWScrnShot_022920_153124

**Comment by FrancescoBorzi** [comment]
Thanks @Maurowin for your feedback, that's very useful.

I think it's good to merge as it's already an improvement, and we can further improve it later.

**Comment by Maurowin** [comment]
np :D i seen in Warmane server patrol who stop when we clic on one of them. i think its core modification

**Comment by BarbzYHOOL** [comment]
@LukasVolgger thank you for that well done PR (loving the screenshots)

@Maurowin thanks for testing + feedback

and thanks ghost :'(

**Pull request merged**
