### PR TITLE
fix(DB/Quest): Healthy Dragon Scale

### PR DESCRIPTION
**Pull request by poszer**
Healthy Dragon Scale should drop just after Quest ID: 5529 is completed

##### CHANGES PROPOSED:

-  Added conditions. Item will be drop, just if the quest 5529 is completed.
-  Loot updated to 6 drop chance.

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1805

##### TESTS PERFORMED:

Yes, tested in game. The item is dropped just when the player have finished quest ID 5529

##### HOW TO TEST THE CHANGES:

Read here : https://github.com/azerothcore/azerothcore-wotlk/issues/1805

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by Seebaby** [comment]
Looks great I'm just not quite sure with the droppchance some say 6% droppchance

**Comment by poszer** [comment]
> eat I'm just not quite sure with the drop

Yeah, on some Db's it's showing 6%, on some 100% . So i'm not sure about this also. If someone know, it's easy to edit. Thanks for testings @Seebaby

**Comment by Seebaby** [comment]
Jepp it's easy to edit no prob thanks for the fix I'm for 6% all the others would be too imba for classic^^

**Comment by poszer** [comment]
> Jepp it's easy to edit no prob thanks for the fix I'm for 6% all the others would be too imba for classic^^
> 
> http://us.battle.net/wow/en/item/13920 Low dropp

Updated to low drop "6". Thank you

**Pull request merged**
