### PR TITLE
fix(Scripts/Activation Crystals): Instance The Violet Hold

### PR DESCRIPTION
**Pull request by grimgravy**
Based on TrinityCore with improved.
reference: [df21162](https://github.com/TrinityCore/TrinityCore/commit/df21162fe44d2ff29c201a9004586f560789c38b)

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1450

## Tests Performed:

- was performed windows 7 64bits. Not a single error was found and it is Functional

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
what exactly is improved upon? very little details in your message about this.

**Comment by grimgravy** [comment]
added two spells: https://www.wowhead.com/wotlk/spell=57804/control-crystal-activation and https://www.wowhead.com/wotlk/spell=57886/defense-system-spawn-effect

**Comment by acidmanifesto** [comment]
would this not be a issue with the enum's sharing the same int? 
image

**Comment by grimgravy** [comment]
> would this not be a issue with the enum's sharing the same int? image

duplicate values

**Comment by acidmanifesto** [comment]
We will be needing testers on this, and a better description and reference for what exactly is "Based on TrinityCore with improved."
Actually, we will need to know what the testers will be testing to even understand what is being done. If this is a TC cherry pick we will need the commit link and author info as well.

**Comment by Maelthyrr** [comment]
Tested and everything work fine. Commit source here: https://github.com/TrinityCore/TrinityCore/commit/df21162fe44d2ff29c201a9004586f560789c38b Please add credits

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
