### PR TITLE
fix(Core/Battleground): Warsong flags can be picked up while mounted

### PR DESCRIPTION
**Pull request by ArashGorge**
Description : https://github.com/azerothcore/azerothcore-wotlk/issues/2065  (Warsong flags can be picked up while mounted...)

##### CHANGES PROPOSED:

-  DisMount Player while Pickedup Flag
-  

###### ISSUES ADDRESSED:

Closes  https://github.com/azerothcore/azerothcore-wotlk/issues/2065

##### TESTS PERFORMED:

Tested in Game
win 10 vs 2017

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@ArashGorge thanks for your contribution, waiting for testers feedback

**Comment by wowmane** [comment]
don't work use this:

if (!m_goInfo->IsUsableMounted())
playerUser->RemoveAurasByType(SPELL_AURA_MOUNTED);


@ArashGorge 

if u have time: please check this commit, just need to fixed builds!
https://github.com/azerothcore/azerothcore-wotlk/pull/2014

**Comment by ArashGorge** [comment]
> don't work use this:
> 
> if (!m_goInfo->IsUsableMounted())
> playerUser->RemoveAurasByType(SPELL_AURA_MOUNTED);
> 
> @ArashGorge
> 
> if u have time: please check this commit, just need to fixed builds!
> #2014

its working fine, tested in game
and this lines, you told me to test not working, cause "playerUser" and "m_goInfo" is Unknown variable but my writes is not different with this Codes , just test it

**Comment by wowmane** [comment]
@ArashGorge 

https://github.com/azerothcore/azerothcore-wotlk/pull/2014
can you help us fix the errors?

**Comment by FrancescoBorzi** [comment]
good job @ArashGorge and thanks a lot @heyaapl and @wowmane for testing this!

**Comment by poszer** [comment]
Thank you for PR @ArashGorge, @heyaapl, @wowmane for testing

**Pull request merged**
