### PR TITLE
fix(DB/GameTables): correct links to data from gt* DB tables

### LINKED ISSUE #3198: [BUG] Core/Class: Agility no added critical chance in char info
##### CURRENT BEHAVIOUR:
- A warrior's agility(1) does not add a chance of a critical strike(3)

In the pictures the character has items with agility, when you hover the cursor, we see in the hint (6.81% white arrow number 1) (7.48% red arrow number 1) the chance to make a critical blow due to agility. 
But in general, the chance of a critical strike does not add up (arrow number 3 is red and white).

<details>
<summary>Show screenshots</summary>

</details>
<summary>Show screenshots</summary>

the problem was confirmed in the collection of statistics the estimate should be 50% and we have a lot less critical hits.

<details>
<summary>Show screenshots</summary>

WoWScrnShot_071720_222557
WoWScrnShot_071720_222601
WoWScrnShot_071720_222606

</details>

I can't tell you the exact time the problem occurred.
tried on the server updated a week ago (red arrows) and another server a month ago was updated (white arrows). Estimated time the problem appeared 1-2 months ago.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
- The values of chance must add up to a chance of agility.

##### STEPS TO REPRODUCE THE PROBLEM:
1. create a warrior of level 80
2. put objects on it with dexterity, but no chance of a critical strike, for example. item id 47314
3. Move your cursor over the agility and look at the percentage of chance of a critical strike (blue arrow №4).

<details>
<summary>Show screenshots</summary>

</details>

4. look at the chance of a critical strike (blue arrow №5).

<details>
<summary>Show screenshots</summary>

</details>

##### OPERATING SYSTEM: Debian 10

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/92074168-bug-core-class-agility-no-added-critical-chance-in-char-info?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #3237: Mana does not regenerate
I am on commit: https://github.com/azerothcore/azerothcore-wotlk/commit/91bbbf08eb73837f50469ad5dac7a106cecadb8f and I found that mana is not regenerating. My Setup is Debian 10 x86_64 with MySQL 5.7.  I tested with a human mage and ran my mana down to near 0. I waited about 5 min and my mana is still only 5 (it never increased). I confirmed that Rate.Mana in worldserver.conf is 1.

I also tested with an Undead Mage also and the mana failed to regenerate.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/92170709-mana-does-not-regenerate?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## CHANGES PROPOSED:
- Support long values for description and etc.
- Support signed values in `spelldifficulty_dbc`
- Correct links to data in `gt*_dbc` DB tables

## ISSUES ADDRESSED:
- Closes #3242
- Closes #3237
- Closes #3198
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/3268

## TESTS PERFORMED:
- Apply default dbc data from https://github.com/Winfidonarleyan/dbc_sql

## HOW TO TEST THE CHANGES:
- Apply default dbc data from https://github.com/Winfidonarleyan/dbc_sql
- #3198

## Target branch(es):
- [x] Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by TheSkorpiox** [comment]
Tested, it works.

I see that gtregenmpperspt_dcb ID now starts at 0, it's a different approach that mine but i don't like it. I'll accept it anyway.

**Comment by Viste** [comment]
they always start from 0, that they started with 1 — mistake

**Comment by Wowkasu** [comment]
> I see that gtregenmpperspt_dcb ID now starts at 0, it's a different approach that mine but i don't like it. I'll accept it anyway.

This is not an approach, this is to eliminate the cause of the fault. It's the only right solution.

**Comment by TheSkorpiox** [comment]
I'm not saying you guys are wrong, i'm just saying that starting tables with an index at 0 is non-conventionnal, and if not stated somewhere in the documentation it should because it confuses newcomers like me

**Comment by Winfidonarleyan** [comment]
> I'm not saying you guys are wrong, i'm just saying that starting tables with an index at 0 is non-conventionnal for me, and if not stated somewhere in the documentation it should because it confuses newcomers like me

All arrays start with index 0.

But when I opened dbc gtChanceToMeleeCrit.dbc I saw the following.
image

There's no index column in this dbc. Therefore, for convenience, the program has made it automatically and started counting from 1

**Comment by Yehonal** [comment]
I'm going to test this one

**Comment by Yehonal** [comment]
Mana regen has been fixed

I can't confirm this issue: https://github.com/azerothcore/azerothcore-wotlk/issues/3247

My evidence of test: https://www.youtube.com/watch?v=T4Cfb7F-4no

**Comment by Yehonal** [comment]
About the ID field, have you considered creating a table without that field? It's not mandatory to create a PK for a table.

Which is the problem with doing it? We could think a solution for it to include in this PR

**Comment by BarbzYHOOL** [comment]
But primary keys = faster, right?

**Comment by TheSkorpiox** [comment]
You are talking about indexes. A PK automatically creates an index, but you can create them manually

**Pull request merged**
