### PR TITLE
fix(Core/Creatures): Creatures' guardian should not despawn on summon…

### LINKED ISSUE #6211: Various NPC Pets Despawn on Master's Death
#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [x] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

Original report: https://github.com/chromiecraft/chromiecraft/issues/767

Currently, killing Razormane Hunter while his Razormane Wolf is still alive makes the Wolf disappear out of thin air.
Video recorded on ChromieCraft: https://youtu.be/vh3VBQRHpCM
Razormane Hunter: https://wowgaming.altervista.org/aowow/?npc=3265
Razormane Wolf: https://wowgaming.altervista.org/aowow/?npc=3939

Tester's notes: Also checked some other pet NPCs, the Skullsplitter Hunters in STV, and the Sons of Cenarius in Stonetalon, and both their pets despawn when the master is killed too. Probably this is just scratching the surfaces and lots of others are affected. Still looking for more evidence that this isn't Blizzlike though.

Razormane Hunters from Wow Classic: https://youtu.be/DFJUFwg524s?t=284 and https://youtu.be/-r_Ots0t77c?t=536
Son of Cenarius:- https://youtu.be/K9kV7eLGrdE?t=121
Skullsplitter Hunter: https://youtu.be/o61USvLPDUY?t=238

Also a comment from TBC about Skullsplitter Hunters:
Don't kill the pet first or else it'll be resummoned in a few seconds. Also, **kiling the hunter doesn't not mean his pet despawns, it will keep eating you.** Enjoy. (https://www.wowhead.com/npc=669/skullsplitter-hunter#comments:id=201589)

##### EXPECTED BLIZZLIKE BEHAVIOUR:

The Wolf should not disappear, it should stay in the open world.

##### SOURCE:

This is from Classic Wow (the retail one that released late August 2019): https://youtu.be/p_mlzteluTE?t=2854
At 47:34 the player engages a Razormane Hunter and kills the hunter, the Wolf stays alive and then dies. The Wolf does not disappear when the Razormane Hunter dies.
Sorry for the very bad quality, I'll try to find another better quality source.
It is not WotLK but there should be no reason why this kind of behaviour would be changed ?

##### STEPS TO REPRODUCE THE PROBLEM:

1. Go to Barrens, near 55 ; 26, and find a Razormane Hunter.
2. Kill the Razormane Hunter while not killing the Wolf.
3. See the Razormane Wolf disappear as the Hunter dies.

##### EXTRA NOTES:

As stated, evidence is from Classic Wow. I do not think that this behaviour would have been changed when retail went to WotLK but I could be wrong.

Tester: It seems fairly clear pets did not despawn on their master's death in Classic and TBC-era Wow, but some more evidence for Wrath would certainly be nice. 

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/3716ddf3e4e1ef138df334d01980fea019272001

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98907564-various-npc-pets-despawn-on-master-s-death?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…er's death.

Fixes #6211

## Issues Addressed:

- Closes #6211
- Closes https://github.com/chromiecraft/chromiecraft/issues/767

## Tests Performed:

- Not tested

## How to Test the Changes:

1. Go to Barrens, near 55 ; 26, and find a Razormane Hunter.
2. Kill the Razormane Hunter while not killing the Wolf.
3. See the Razormane Wolf is alive as the Hunter dies.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers @azerothcore/developers please check this

**Comment by stoudtlr** [comment]
tested without PR and after killing Razormane Hunter his wolf despawns.  After pulling PR and recompiling I tested again and same behavior still exists.  Wolf pet despawns after Razormane Hunter is killed. Verified PR with Server Info after not seeing a change.
image

**Comment by UltraNix** [comment]
@stoudtlr Fixed. Please, test it.

**Comment by stoudtlr** [comment]
Wolves stay instead of despawning after razormane hunter is killed.
wolves remain

However, there are now a bunch of errors in the server after hunter is killed.  Are these normal and can be ignored?
image

**Comment by UltraNix** [comment]
@stoudtlr Errors should be gone.

**Comment by stoudtlr** [comment]
same results.  pet does not disappear, but two error lines displayed in server console each time a master is killed
image

**Comment by UltraNix** [comment]
Are you sure you updated code?

**Comment by UltraNix** [comment]
Should be okay now.

**Comment by stoudtlr** [comment]
@UltraNix it's better! Error for releasing pet is gone, but error for releasing minion still exists.
image

**Comment by UltraNix** [comment]
Grr...

**Comment by stoudtlr** [comment]
cleaning and rebuilding...

**Comment by stoudtlr** [comment]
@UltraNix "undeclared identifier" error during build
image

**Comment by UltraNix** [comment]
Try now.

**Comment by stoudtlr** [comment]
@UltraNix fixed! pet remains and all server errors are gone
image

**Review by Si1ker — APPROVED** [review]
Tested by stoudtlr
Approved by some weird cat

**Pull request merged**
