### PR TITLE
fix(DB/creature_template): sniff walk/run values

### PR DESCRIPTION
**Pull request by neifion-00000000**
## Changes Proposed:
- Updates over 16k creatures, about 1/3 (Affected rows: 6,143) needing fixed values for walk and/or run speeds: 

## SOURCE:

Made possible by sniff tools including:
ymir, WPP, malcrom's tool
and sniffs provided to the Sniff-Collective
almost 1000 sniffs were scraped for this PR

for reference purposes if anyone continues this other than me, we are currently up to date on these values using sniffs collected up to 2023-1-03

## Tests Performed:

- Largely untested other than a quick glance, if issues are found they should not be related to values here as barring some anomaly with the parser the values here should be 100% correct

## Known Issues and TODO List:

- I suspect my SQL is not up to standards, I am open to suggestions.
- Yes I'm aware 10,000 lines are extra, such is the price to getting 6,143 good lines so fast  

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
@neifion-00000000 try this: https://gist.github.com/Gultask/e5dd2fc1ec5e767fc5eb0b7a44495f3a

Also the build is failing because the first 2 creatures don't exist ([Boss Dummy](https://www.wowhead.com/classic/npc=177469/boss-dummy) and [Cap'n Placeholder](https://www.wowhead.com/classic/npc=184320/capn-placeholder))

**Comment by Gultask** [comment]
It's passing the checks 
image

**Comment by heyitsbench** [comment]
RIP The Cap'n. 😔

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
Why merge later, why not now?

**Comment by Gultask** [comment]
> Why merge later, why not now?

Because it took me a long time to run the query

**Comment by heyitsbench** [comment]
> Because it took me a long time to run the query

Takes a long time to run `broadcast_text.sql`

**Comment by Gultask** [comment]
True and the locale .sql even longer but I don't see why we'd need to merge right **now** with a squash on the way, and add several minutes to DB build time.

**Comment by Kitzunu** [comment]
Doesnt matter, squash or not, everyone will need to sit through it at one point or another

**Comment by Gultask** [comment]
I rebuild my DB at least 3 times a week. More if I'm working on big stuff so it'll definitely affect me, at least. 😛

**Comment by heyitsbench** [comment]
I rebuild multiple times a day. I don't care one way or another. 🤷

**Pull request merged**
