### PR TITLE
Core/Packet: LFG

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  Move Join & Leave LFG to new packet
-  

## Issues Addressed:

- Closes 

## SOURCE:

TC
## Tests Performed:

- Tested
- 

## How to Test the Changes:

1. join & leave lfg
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by claudiodfc** [comment]
## Test result 🦗

Tried to turn off Debug more for LFG and it did work. However, when queuing up for Random Heroic I got the message `You do not meet the requirements`. When trying to queue for individual ones, I was locked for every single one of the available dungeons.

After a few seconds, the worldserver had frozen/crashed displaying this on the console:

```
Command: debug lfg [Player: Flak (GUID Full: 0x0000000000000009 Type: Player Low: 9) (Account: 12) X: 1117.9326 Y: -2525.7415 Z: 59.675873 Map: 0 (Eastern Kingdoms) Area: 2298 (Caer Darrow) Zone: 28 (Western Plaguelands) Selected:  (GUID Full: 0x0000000000000000 Type: None Low: 0)]
d:\a01\_work\3\s\src\vctools\crt\github\stl\src\mutex.cpp(64): mutex destroyed while busy
abort() has been calledCaught signal 22
(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.
```

### Crash log here:
[cac59ad67f8c_worldserver.exe_[9-12_12-2-34].txt](https://github.com/azerothcore/azerothcore-wotlk/files/7684886/cac59ad67f8c_worldserver.exe_.9-12_12-2-34.txt)

**Comment by IntelligentQuantum** [comment]
> ## Test result cricket
> 
> Tried to turn off Debug more for LFG and it did work. However, when queuing up for Random Heroic I got the message `You do not meet the requirements`. When trying to queue for individual ones, I was locked for every single one of the available dungeons.
> 
> After a few seconds, the worldserver had frozen/crashed displaying this on the console:
> 
> ```
> Command: debug lfg [Player: Flak (GUID Full: 0x0000000000000009 Type: Player Low: 9) (Account: 12) X: 1117.9326 Y: -2525.7415 Z: 59.675873 Map: 0 (Eastern Kingdoms) Area: 2298 (Caer Darrow) Zone: 28 (Western Plaguelands) Selected:  (GUID Full: 0x0000000000000000 Type: None Low: 0)]
> d:\a01\_work\3\s\src\vctools\crt\github\stl\src\mutex.cpp(64): mutex destroyed while busy
> abort() has been calledCaught signal 22
> (0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.(0) : Run-Time Check Failure #2 - Stack around the variable 'buffer' was corrupted.
> ```
> 
> ### Crash log here:
> 
> [cac59ad67f8c_worldserver.exe_[9-12_12-2-34].txt](https://github.com/azerothcore/azerothcore-wotlk/files/7684886/cac59ad67f8c_worldserver.exe_.9-12_12-2-34.txt)

For hc mode you need i think 4k gs

**Comment by claudiodfc** [comment]
But is the server gonna crash if a player without 4k GS tries to queue random hc? AFAIK This only existed in Warmane, or was this also in retail wow?

**Comment by IntelligentQuantum** [comment]
@claudiodfc 

I do not know, but without this editing, you will still get this error (You do not meet the requirements)
Can you test this pr again please, Try it without these edits first.

**Comment by claudiodfc** [comment]
Sure thing bro, what do you mean with 

> Try it without these edits first.

**Comment by IntelligentQuantum** [comment]
> Sure thing bro, what do you mean with
> 
> > Try it without these edits first.

i mean without this pr

**Comment by claudiodfc** [comment]
## Test result:

- Joined LFG on normal queue as a level 80 and got teleported to the instance.
- Tried to join Heroic but it said I don't meet the requirements. (Not enough average iLvl)
- Queue still popped after for normal dungeons and no freezes were detected.
- As a fresh Death knight character and everytime I relog on the level 55, the LFG menu looks like the image 1. I can still select dungeons single or queue for any as displayed on the image 2, but I have to manually select the drop down box, there's not an avaliable option right off the hook. If I hit confirm, it tells me _You do not meet the requirements for the chosen dungeons_.
- The same happened when creating a level 1 character and leveling up to 15 using command `.level 14`. The image 3 displays the same issue on the image 1. Relogging doesn't fix the problem either, there's still no default menu and the player has to manually select it.

## Extras

##### (Img.1 - Menu doesn't have a default option selected for a level 55 fresh death knight)
image

##### (Img.2 - There's still a drop down option for the LFG)
image

##### (Img.3 - There's no default option for a character that hits level 15.
image

**Comment by IntelligentQuantum** [comment]
> ## Test result:
> 
>     * Joined LFG on normal queue as a level 80 and got teleported to the instance.
> 
>     * Tried to join Heroic but it said I don't meet the requirements. (Not enough average iLvl)
> 
>     * Queue still popped after for normal dungeons and no freezes were detected.
> 
>     * As a fresh Death knight character and everytime I relog on the level 55, the LFG menu looks like the image 1. I can still select dungeons single or queue for any as displayed on the image 2, but I have to manually select the drop down box, there's not an avaliable option right off the hook. If I hit confirm, it tells me _You do not meet the requirements for the chosen dungeons_.
> 
>     * The same happened when creating a level 1 character and leveling up to 15 using command `.level 14`. The image 3 displays the same issue on the image 1. Relogging doesn't fix the problem either, there's still no default menu and the player has to manually select it.
> 
>     * The menu displays correctly for level 80s and all the options as well, shown or image 4.
> 
> 
> ## Extras
> ##### (Img.1 - Menu doesn't have a default option selected for a level 55 fresh death knight)
> 
> image
> ##### (Img.2 - There's still a drop down option for the LFG)
> 
> image
> ##### (Img.3 - There's no default option for a character that hits level 15.)
> 
> image
> ##### (Img.4 - Correct menu for level 80s)
> 
> image

tnx

**Comment by IntelligentQuantum** [comment]
@claudiodfc i dont have this problem with dk and level 15 ...

**Comment by IntelligentQuantum** [comment]
@claudiodfc 

On Login without select anything
Screenshot_20211217_163800

With select option
Screenshot_20211217_163846

level 80
Screenshot_20211217_163902

**Comment by acidmanifesto** [comment]
Conflicts and also what is the status of this?

**Comment by IntelligentQuantum** [comment]
> Conflicts and also what is the status of this?
Need Test

**Comment by temperrr** [comment]
image

**Comment by temperrr** [comment]
Joining and leaving bgs seems to work.
Rewards (xp and bag) for random seem to work too

**Comment by FrancescoBorzi** [comment]
@azerothcore/developers please review

**Review by Winfidonarleyan — APPROVED** [review]

**Pull request merged**
