### PR TITLE
fix(DB/ZulGurub): Hoodoo Piles should not melee atack their targets.

### LINKED ISSUE #12186: ZG Hoodoo Piles not working correctly
### Current Behaviour

Hoodoo Piles are mind controlling everyone walking near them

### Expected Blizzlike Behaviour

They should have a % chance to mind control the user interacting with it after a short amount of time after looting

### Source

TBC PTR

### Steps to reproduce the problem

1. go to zg
2. loot hoodoo pile
3. get random chacne to be mind controlled

### Extra Notes

_No response_

### AC rev. hash/commit

76e9e19f0cd8c4f552f547532581884c1af3028c

### Operating system

Manjaro x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Will of Hakkar is casted on pile looter.
Fixes #12186

## Issues Addressed:

- Closes #12186

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go gameobject id 180229`
Loot it and see result.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by chobi-wow** [comment]
The Hoodoo piles should:
- trigger;  on being looted the first time (not sequential loots),
- action: have a chance to cast mind control 
- target: on a player in range of the pile. (does not target only the looter)
- resisting: players have a chance resist the mind control.

it should **not**:
- cast multiple instances of mind control
- repeatedly cast mind control
- cast every time it is looted
- cast on multiple players

**Comment by Maelthyrr** [comment]
PR work but it's actually impossible to loot because each time that someone click on it, he is mind control. I don't able to confirm every points of @chobi-wow, but one thing is sure : Pile have a chance to cast mind control (after 4/5 videos, it's seems to be max 20%)

**Comment by acidmanifesto** [comment]
> Tested. Mind control one player but not the spell is always cast when activate. So you can't loot piles.

so this pr is not working as intended?

**Comment by Gultask** [comment]
Can confirm what Maelthyrr said. Object 180229 may be unlootable since it never runs out of "charges" for its trap.

I haven't found any problems besides that.

**Comment by UltraNix** [comment]
@Gultask @Maelthyrr There are two types of this trap. One is just looting gameobject and the second is looting + mind control. This is blizzlike, so not every pile casts MD.

**Comment by temperrr** [comment]
Correct

**Review by Nefertumm — APPROVED** [review]

**Comment by acidmanifesto** [comment]
*Loud Merge Noises* 👍

**Pull request merged**
