### PR TITLE
Clean table acore_auth.uptime and fix acore_world.npc_text_locale

### PR DESCRIPTION
**Pull request by skxawng-cu**
Cleaning table acore_auth.uptime and fix acore_world.npc_text_locale

## CHANGES PROPOSED:
-  Clean table acore_auth.uptime in a clean installation of the core.
-  Fix a import bug in acore_world.npc_text_locale.

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Assemble full database with out errors.
- After a clean build and assemble database the table uptime is empty.

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Stoabrogga** [comment]
I don't know what this is about, but you can close PR #2554 because the change is already included in this PR.

**Comment by skxawng-cu** [comment]
In npc_text_locale.sql.MySQL wouldn't let me import the database either manually or with the assembler. I researched about the problem and that was the best solution I found.
In uptime.sql is only cleaning.

**Comment by Stoabrogga** [comment]
> In npc_text_locale.sql.MySQL wouldn't let me import the database either manually or with the assembler.

Could you please elaborate on this? Which errors did occur?

**Comment by skxawng-cu** [comment]
# mysql --version
mysql  Ver 15.1 Distrib 10.3.18-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

# bash apps/db_assembler/db_assembler.sh
1) all: Assemble all                                6) import-bases: Assemble & Import only bases
2) bases: Assemble only bases                       7) import-updates: Assemble & Import only updates
3) updates: Assemble only updates                   8) import-customs:  Assemble & Import only customs
4) customs: Assemble only customs                   9) quit: Exit from this menu
5) import-all: Assemble & Import all
[Please enter your choice]: 5
=====     DB ASSEMBLER MENU     =====
===== STARTING ASSEMBLY PROCESS =====
Generating /opt/azerothcore-src/env/dist/sql/auth_base ...
Searching on /opt/azerothcore-src/data/sql/base/db_auth/ ...
Generating /opt/azerothcore-src/env/dist/sql/auth_updates ...
Searching on /opt/azerothcore-src/data/sql/updates/db_auth/ ...
Searching on /opt/azerothcore-src/data/sql/updates/pending_db_auth/ ...
Generating /opt/azerothcore-src/env/dist/sql/auth_custom ...
Searching on /opt/azerothcore-src/data/sql/custom/db_auth/ ...
Generating /opt/azerothcore-src/env/dist/sql/characters_base ...
Searching on /opt/azerothcore-src/data/sql/base/db_characters ...
Generating /opt/azerothcore-src/env/dist/sql/characters_updates ...
Searching on /opt/azerothcore-src/data/sql/updates/db_characters/ ...
Searching on /opt/azerothcore-src/data/sql/updates/pending_db_characters/ ...
Generating /opt/azerothcore-src/env/dist/sql/characters_custom ...
Searching on /opt/azerothcore-src/data/sql/custom/db_characters/ ...
Searching on /opt/azerothcore-src/modules/mod-anticheatbot/data/sql/db_characters/ ...
Searching on /opt/azerothcore-src/modules/mod-npc-talent-template/sql/characters/ ...
Searching on /opt/azerothcore-src/modules/mod-transmog/data/sql/db-characters/ ...
Generating /opt/azerothcore-src/env/dist/sql/world_base ...
Searching on /opt/azerothcore-src/data/sql/base/db_world/ ...
Generating /opt/azerothcore-src/env/dist/sql/world_updates ...
Searching on /opt/azerothcore-src/data/sql/updates/db_world/ ...
Searching on /opt/azerothcore-src/data/sql/updates/pending_db_world/ ...
Generating /opt/azerothcore-src/env/dist/sql/world_custom ...
Searching on /opt/azerothcore-src/data/sql/custom/db_world/ ...
Searching on /opt/azerothcore-src/modules/mod-npc-enchanter/sql/world/ ...
Searching on /opt/azerothcore-src/modules/mod-npc-free-professions/sql/world/ ...
Searching on /opt/azerothcore-src/modules/mod-npc-talent-template/sql/world/ ...
Searching on /opt/azerothcore-src/modules/mod-transmog/data/sql/db-world/ ...
=====           DONE            =====
=====       CHECKING DBs        =====
auth database exists
characters database exists
world database exists
=====           DONE            =====
===== STARTING IMPORTING PROCESS =====
auth seems empty
importing AUTH - base ...
characters seems empty
importing CHARACTERS - base ...
world seems empty
importing WORLD - base ...
**ERROR 1118 (42000) at line 2293216: Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.**

**Comment by Viste** [comment]
Row size too large (> 8126).!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11111111111111111111111111111111

**Comment by Stoabrogga** [comment]
Is this related to what is described in the FAQ?
http://www.azerothcore.org/wiki/FAQ#1---mysql-has-gone-away

**Comment by Viste** [comment]
@Stoabrogga no its another but similar

**Comment by skxawng-cu** [comment]
I try ser global to dynamic n works

**Pull request closed without merging**
