### PR TITLE
fix(Core/Spells): Do not send doubled learning packet if spell is lea…

### LINKED ISSUE #7415: Profession spells are learnt twice
**CURRENT BEHAVIOUR:**
Profession spells are learnt twice.

**EXPECTED BLIZZLIKE BEHAVIOUR:**
Only one instance of a spell should be learnt.

**STEPS TO REPRODUCE THE PROBLEM:**
1. Learn a profession such as First Aid
2. You will learn two instances of every spell such as Linen Bandage
3. This can be confirmed by checking your spellbook

**AC HASH/COMMIT:**
c7ee70ea75ff4d6729d8cfc0cbb4ac4d01ac67ee

**OPERATING SYSTEM:**
Ubuntu 20.04 LTS

**MODULES:**
`mod-autobalance`

**CUSTOMIZATIONS:**
Max player level is 19.

### LINKED ISSUE #7764: [Find Herbs] and [Lifeblood] (Rank 4) remained in SpellBook after removing Herbalism
### What client do you play on?

ruRU

### Faction

- [ ] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Find Herbs] and [Lifeblood] (Rank 4) remaine in SpellBook after removing Herbalism.

### Expected Blizzlike Behaviour

[Find Herbs] and [Lifeblood] (Rank 4) must be removed along with Herbalism

### Source

You can check my character. Nickname: Santaria
I use ruRu client, sorry for the screenshot.
<details>
<summary>Screenshot</summary>

</details>

### Steps to reproduce the problem

1. Learn Herbalism and upgrade 300/300
2. Remove Herbalism
3. Learn any other profession. In my case tailoring.
4. Check [Find Herbs] and [Lifeblood] in SpellBook

### Extra Notes

Triager: Does not appear to stay when relogging, but it does stay in book after unlearning (and useable). (but user claims they still have it, I cant test that or replicate it) Possibly also other professions.  Does not happen 100% of the time, about 50% of the time. Maybe has to do something with https://github.com/azerothcore/azerothcore-wotlk/issues/7415
Also, happened before:
https://github.com/azerothcore/azerothcore-wotlk/pull/7290

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/595bb6adccbabc714469f3935541978283b8bdfb

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…rned from skill.

Fixes #7764

## Issues Addressed:

- Closes #7764
- Closes #7415
- Closes https://github.com/chromiecraft/chromiecraft/issues/1507
- Closes https://github.com/chromiecraft/chromiecraft/issues/1624
- 

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

1. .go c 98866
2. Learn herb
3. .setskill 182 300 300
4. Unlearn herb
5. No  [Find Herbs] and  [Lifeblood] in spellbook.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Kitzunu — APPROVED** [review]

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by IntelligentQuantum** [comment]
Tested it works fine for me, and we can close this https://github.com/azerothcore/azerothcore-wotlk/issues/7415

**Comment by Eureka26** [comment]
does anyone know if this fix also https://github.com/azerothcore/azerothcore-wotlk/issues/4882

**Comment by UltraNix** [comment]
@Eureka26 It should.

**Comment by IntelligentQuantum** [comment]
Yeah but unlearn part dosent work

**Pull request merged**
