### PR TITLE
fix(DB): Fixed Southsea Freebooter shoots while running away in fear and while polymorphed

### PR DESCRIPTION
**Pull request by Asthalor**
Fixed some flags on the smartAI of the creature so they cant shoot while fleeing or polymorphed, LOS.. etc

Closes AzerothCore issue#7013

## Changes Proposed:
-  Changed the flag of the shoot skill from 62 to 64 so they cant shoot it while fleeing, LOS, on fear etc
-  Changed the target of the fleeing skill so they only flee, they cant shoot now while fleeing.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/7013
- Closes https://github.com/chromiecraft/chromiecraft/issues/1227

## SOURCE:

I dont know how to record video. This is a bucaneer polymorphed for more than 10 seconds without shooting.

image

## Tests Performed:

- Use .go c id 7856
- Hit them to low their HP and see them fleeing. They should not shoot until they go to another friendly unit.
- MAGES --> Hit them to aggro and polymorph. They should not attack

## How to Test the Changes:

1. Use .go c id 7856
2. Hit them to low their HP and see them fleeing. They should not shoot until they go to another friendly unit.
3. MAGES --> Hit them to aggro and polymorph. They should not attack

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by LukasVolgger — APPROVED** [review]

**Comment by syssneck** [comment]
Hi, I tested it multiple times. Southsea Freebooter now don't shoot while running away or polymorphed.
However, the running speed of the sheep seems a bit too high for me, but I'm not a mage player myself:

https://user-images.githubusercontent.com/68868567/126113736-425c0e2d-5b50-46ab-973f-282d11f8784b.mp4

**Comment by iraizo** [comment]
> Hi, I tested it multiple times. Southsea Freebooter now don't shoot while running away or polymorphed.
> However, the running speed of the sheep seems a bit too high for me, but I'm not a mage player myself:
> fast.sheep.mp4

I am also pretty sure that speed is too high

**Comment by LukasVolgger** [comment]
So i also think it's better to slow down this little guy before he get's a heartattack

**Comment by Asthalor** [comment]
> So i also think it's better to slow down this little guy before he get's a heartattack
> 
> @Asthalor can you check this pls?

Sure!
Im going to take a look at that, i dont know what change could have made them run like that, but it should not be very hard.

**Comment by temperrr** [comment]
Does this also fix them shooting whilst sapped? 
Screenshot from 2021-07-25 09-31-26

**Comment by Asthalor** [comment]
Good find @temperrr 
I changed the code so its much easier to understand the changes.
Ive updated the flags of the spell 'shoot' and done some test to check if they could attack while sapped and i think i fixed those.
**Video test**

https://streamable.com/ya87m3

**Comment by Asthalor** [comment]
Hello @LukasVolgger !
Could it be possible to change the Fix label to the Ready to be tested/ reviewed?
As far as i know there is no work 'yet' to do here :P

**Review by LukasVolgger — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
marking as [To Be Merged] unless someone has still something to add here

**Pull request merged**
