### PR TITLE
fix(DB/Quest): Assign proper quest starters for Brewfest souvenir quests.

### PR DESCRIPTION
**Pull request by TheSCREWEDSoftware**
## Changes Proposed:

This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- closes https://github.com/chromiecraft/chromiecraft/issues/7386

 (Not a exclusive ChormieCraft Issue as this tested on AzerothCore rev. https://github.com/azerothcore/azerothcore-wotlk/commit/bb0d292e1c2bb5619fbc3105e7cd919b45268748 2024-09-22 07:38:46 +0000 (master branch) (Win64, RelWithDebInfo, Static)

## SOURCE:

The changes have been validated through:
- [x] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [x] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [x] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

**Horde**: 
1. `.go creature id 24510`
2. Talk to "Ram Master Ray" and accept "Now This is Ram Racing... Almost"
3. `.quest complete 11409` and deliver the quest (you can press the buff to get out of the ram)
4. You will see that the quest "Another Year, Another Souvenir" shows up on Driz Tumblequick. (as it has a Quester Starter now)

**Alliance**:
1. `.go creature id 24468`
2. Talk to "Neil Ramstein" and accept "Now This is Ram Racing... Almost"
3. `.quest complete 11318` and deliver the quest (you can press the buff to get out of the ram)
4. You will see that the quest "Another Year, Another Souvenir" shows up on Pol Amberstill. (as it has a Quester Starter now)

## Known Issues and TODO List:
Not to my knowledge

Please give feedback if that's how i should export the SQL (From Keira3) or should be something else.

### CODE REVIEW

**Comment by pangolp** [comment]
I wanted to help you solve the build problem, but I have not been able to commit to your branch within this pull request. So I leave you the solution, in case you want to change it, what I did was delete the 2 files that you generated, and using the script that is in the folder, generate one (although that is secondary) and inside it, place the following code.
```sql
--
DELETE FROM `creature_queststarter` WHERE `quest`=13932 AND `id`=24468;
DELETE FROM `creature_queststarter` WHERE `quest`=13931 AND `id`=24510;
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES
(24468, 13932),
(24510, 13931);
```
- data\sql\updates\pending_db_world\rev_1727706143128594500.sql
- data\sql\updates\pending_db_world\create_sql.sh (This is the script for creating the file, it is an old practice that we used to have to do, but for some time now, I think it is no longer necessary, however, I have kept the habit of using that script to generate the file.)

**Comment by TheSCREWEDSoftware** [comment]
I think i did it right this time (i also learnt from what you said how those random name sql gets generated)

**Comment by pangolp** [comment]
You may get an error because you forgot to leave a line break at the end of the document.
image
I create a suggestion for you, and you can create the commit differently from here

**Comment by pangolp** [comment]
I'm really bad at creating titles for pull requests and commits. But in your case, it could be something like this.
> fix(DB/creature_queststarter) Add quest 13931 and 13932

**Comment by heyitsbench** [comment]
Is this PR necessary? Stock AC on 804769400bcb4191d07fc21c2c2d27c37831ca24 I completed the `Now This is Ram Racing... Almost` quest and had the `Another Year, Another Souvenir` quest available from `Belbi Quikswitch`.

**Comment by heyitsbench** [comment]
Disregard, I understand the issue now. Tested, the quest is still available from Quikswitch (and likely the Horde equivalent) when it should only be available from Amberstill presumably.

**Comment by heyitsbench** [comment]
```sql
DELETE FROM `game_event_creature_quest` WHERE `quest` IN (13931, 13932);
```
This query fixes the issue I mentioned above.

**Comment by TheSCREWEDSoftware** [comment]
> ```sql
> DELETE FROM `game_event_creature_quest` WHERE `quest` IN (13931, 13932);
> ```
> 
> This query fixes the issue I mentioned above.

Does removing the quest IDs will make new one and correct them?

**Review by pangolp — APPROVED** [review]
Good job.

**Comment by heyitsbench** [comment]
> Does removing the quest IDs will make new one and correct them?

IMO for creatures like this that are only active during the event, I don't think we should be using `game_event_creature_quest` to assign their quests, but instead `creature_queststarter` like you're using. Just deleting the existing entries seems to work fine.

**Comment by TheSCREWEDSoftware** [comment]
> > Does removing the quest IDs will make new one and correct them?
> 
> IMO for creatures like this that are only active during the event, I don't think we should be using `game_event_creature_quest` to assign their quests, but instead `creature_queststarter` like you're using. Just deleting the existing entries seems to work fine.

So aside from the normal quest creation for the NPCs that used exlucisve for an event, the `game_event_creature_quest` become redudant? or just bad design that shouldnt be used?

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Is this already tested right?

**Comment by TheSCREWEDSoftware** [comment]
From my part yes. Anyone else testing is always welcomed.

**Comment by heyitsbench** [comment]
>  or just bad design that shouldnt be used?

IMO it depends on the quest in question. In this case, where the quest exists only as long as the questgiver exists (which is tied to a game event), then the typical `creature_queststarter` table works fine. For a quest that should only exist during a game event but its questgiver exists all the time, then it should use the game event table. Either way, from my testing, there are two creatures offering this quesst after this PR when there should only be one, so the `DELETE` statement I proposed earlier should still be added, as it fixes the issue without interfering with any other part of the PR.

P.S. Sorry I took so long to respond, I'm forgetful. 😛

**Comment by TheSCREWEDSoftware** [comment]
I'm confused. Should a remove my changes and add ```DELETE FROM `game_event_creature_quest` WHERE `quest` IN (13931, 13932);``` ?

**Comment by pangolp** [comment]
> I'm confused. Should a remove my changes and add ```DELETE FROM `game_event_creature_quest` WHERE `quest` IN (13931, 13932);``` ?

If they're missions, assigned to an NPC, during an event and they shouldn't always be available, I think they're in that table that you mention. But I would have to do tests.

**Comment by TheSCREWEDSoftware** [comment]
Bench said this on the discord, I will update it when i can

**Comment by TheSCREWEDSoftware** [comment]
@heyitsbench confirm me that's this what you meant, already commited

https://github.com/azerothcore/azerothcore-wotlk/pull/20105/commits/4e38bd115b9e7b7a4bd99a1fd755b3eac3064b17

**Comment by heyitsbench** [comment]
Exactly what I meant. 👍 Sorry for the confusion.

**Comment by TheSCREWEDSoftware** [comment]
It's alright, I have still my own issues with certain aspects of Github (learning process).

**Comment by pangolp** [comment]
I can't see well, because I'm from my cell phone. But I think you have one line left over at the end of the document. You just have to leave one, and it gives me the feeling that there are 2, but I can be wrong, given that I'm not on the PC.

**Comment by TheSCREWEDSoftware** [comment]
You're probably correct because I did 1 space nothing showed in the commits, I added another and it a appeared, I will fix it tomorrow during the day

**Comment by Helias** [comment]
I don't think it matters if you have more then one empty line at the end, so I merged the PR, thanks everyone for the support and thanks @TheSCREWEDSoftware for the PR 🚀

**Pull request merged**
