### PR TITLE
fix(DB/loot): Adjust AQ40 loot

### PR DESCRIPTION
**Pull request by Gultask**
## Changes Proposed:
- Adjusts boss and trash loot

## Issues Addressed:

- Closes unreported issue

## SOURCE:

Cmangos, Vmangos. Other Classic data.

## Tests Performed:

- Query ran, checked Keira
- Tested ingame

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by Gultask** [comment]
Done.

**Comment by Nefertumm** [comment]
Duplicate entry '15263-34045-34045-0' for key 'creature_loot_template.PRIMARY

**Comment by Gultask** [comment]
Sorry. I thought I fixed that.

**Comment by Gultask** [comment]
Should be ok now.

**Comment by Nefertumm** [comment]
Hold up, you should update your branch, the other file is from another pr

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
