### PR TITLE
feat(Core/Modules): add separated lib for modules

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
## Changes Proposed:
1. General
- Make sepated library `modules`
- Make new manager `ModuleMgr` for check enable modules and other
- Enable loading modules configs if module enable. (Previously, all configurations were always loaded regardless of whether the module was disabled or not)
2. Eluna
- Move all `ELUNA` code to module
- Added new hooks for support `mod-eluna`
- Fix using double core hooks

## Issues Addressed:
- Part dynamic linking

## Tests Performed:
- In game

## How to Test the Changes:
1. Startup core with/without modules
2. Check any scripts
3. Check any modules
4. Check eluna scripts with https://github.com/azerothcore/mod-eluna-lua-engine/pull/71

## Linked PR's:
- [ ] https://github.com/azerothcore/mod-eluna-lua-engine/pull/71

## Media:
- Add new info in command `.ser debug`
image

- New structure for modules
image

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
@Winfidonarleyan https://github.com/azerothcore/mod-eluna-lua-engine/pull/71 build error

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan [azerothcore/mod-eluna-lua-engine#71](https://github.com/azerothcore/mod-eluna-lua-engine/pull/71) build error

need build with this PR. I build now with this `cmake ../ -DCMAKE_INSTALL_PREFIX=/home/acore -DWITH_WARNINGS=1 -DUSE_COREPCH=0 -DUSE_SCRIPTPCH=0 -DCMAKE_C_FLAGS="-Werror" -DCMAKE_CXX_FLAGS="-Werror"`

**Comment by Winfidonarleyan** [comment]
image

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by IntelligentQuantum** [comment]
- [X] Startup core with/without modules
- [X]  Check any scripts
- [X]  Check any modules
- [X] command server debug
- []  Check eluna scripts with https://github.com/azerothcore/mod-eluna-lua-engine/pull/71 NEED SOMEONE TO TEST

**Comment by Winfidonarleyan** [comment]
> * [x]  Startup core with/without modules
> * [x]   Check any scripts
> * [x]   Check any modules
> * [x]  command server debug
> * [ ]   Check eluna scripts with [feat(Misc): add support new modules loading api mod-eluna-lua-engine#71](https://github.com/azerothcore/mod-eluna-lua-engine/pull/71) NEED SOMEONE TO TEST

I tested most of the hooks

**Comment by Winfidonarleyan** [comment]
Tested some lua scripts
- [x] [lua-event-scripts](https://github.com/55Honey/Acore_CustomWorldboss)
- [x] [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [x] [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)

**Comment by temperrr** [comment]
Tested with
mod-progression-system

and
afbeelding

All working as expected.

✅

**Comment by Winfidonarleyan** [comment]
> Tested with mod-progression-system

Thanks for testing

**Pull request merged**
