### PR TITLE
fix(Core/AI): validate stored targets

### PR DESCRIPTION
**Pull request by Nefertumm**
Co-authored-by: Meji <meji46@users.noreply.github.com>
Co-authored-by: Ariel Silva <ariel-@users.noreply.github.com>
Co-authored-by: Shauren <shauren.trinity@gmail.com>

## Changes Proposed:
-  https://github.com/TrinityCore/TrinityCore/commit/866074b6899d87df6c835b936524d9f76ba78949
-  https://github.com/TrinityCore/TrinityCore/commit/198d18bef5d3480cb30c80e4a4946327f401a6d4

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12485

## Tests Performed:

- Built, not tested.

## How to Test the Changes:

1. Check SAI

### CODE REVIEW

**Comment by Nefertumm** [comment]
@mpfans test it, please

**Review by acidmanifesto — APPROVED** [review]
oh boy. this is going to be fun. Approved

**Comment by mpfans** [comment]
After testing for a day, no crash was found. It is recommended to merge first

**Comment by mpfans** [comment]
Why has no one merged this PR so far? If not merged, it will cause the server to crash and fail to operate normally, and will also affect many other PR being fixed

**Pull request merged**
