### PR TITLE
fix(SQL): dungeon_access_template min_level

### PR DESCRIPTION
**Pull request by locus313**
## Changes Proposed:
- update min level for each dungeon in dungeon_access_template to use the values from the dbc files

## Issues Addressed:
- Closes 

## SOURCE:

https://wow.tools/dbc/?dbc=lfgdungeons&build=3.3.5.12340#page=1

## Tests Performed:

- apply sql

## How to Test the Changes:

- apply sql
- set `DungeonAccessRequirements.LFGLevelDBCOverride = 1` in your worldserver.conf
- run `.reload dungeon_access_template` & `.reload conf`
- use rdf at different level's, make sure your not placed into dungeons too far above your level.

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mdawx** [comment]
Closes https://github.com/chromiecraft/chromiecraft/issues/420

**Comment by Kitzunu** [comment]
?

**Comment by locus313** [comment]
Ended up finding out why max_level was keep at 0. :) When i actually tested, it locks players out that are a higher level. Which isn't desired i think :) The min_levels could probably still be updated though (they seemed a little off when i checked them). I just closed it for now, not removing the branch though.

**Comment by FrancescoBorzi** [comment]
@locus313 what's the status of this PR?

**Comment by locus313** [comment]
This pr should be good to go. This should get the min values for each dungeon in line with the dbc values.

**Comment by FrancescoBorzi** [comment]
@azerothcore/testers please review

**Comment by Nefertumm** [comment]
Tested. Seems to be ok, but I found something odd, I was level 23 and still got into Ragefire Chasm, and that dungeon should pop until lvl 18. So idk if that's good or not.

**Comment by claudiodfc** [comment]
### Test Result ✔
## Test case 1
At level 16 got into the 4 available maps: WC, RFC, SFK and DMines.

### Test case 2

At level 19 got into the 5 available maps: WC, RFC, SFK, DMines and Blackfathom Deeps.

### Test Case 3
At level 50 got placed into The Stockades the first queue.

### Notes:
You have not updated the Database with a Maximum level on `dungeon_access_template.max_level` column, inducing the behaviour that @Nefertumm specified. Is the core already using the mention column too?

image

**Comment by locus313** [comment]
> ### Notes:
> 1. You have not updated the Database with a Maximum level on `dungeon_access_template.max_level` column, inducing the behaviour that @Nefertumm specified. Is the core already using the mention column too?

This pr is only meant to update the min level's to be closer to the dbc values. if we set the max_level column it will prevent higher level players from being able to enter the lower level dungeons (even without using RDF). Hence that's why its currently set to 0 for everything. The behavior you mentioned already happens without this pr if you enable 
 `DungeonAccessRequirements.LFGLevelDBCOverride` .


> image

if you go back and look at the tool there is a MinLevel column, in most cases this was higher than the currently set min_level values in the database. So i used the value from this column.

**Comment by claudiodfc** [comment]
> This pr is only meant to update the min level's to be closer to the dbc values. if we set the max_level column it will prevent higher level players from being able to enter the lower level dungeons (even without using RDF). Hence that's why its currently set to 0 for everything. The behavior you mentioned already happens without this pr if you enable

Well, but if we can fix the Max level at the same time then even better no? Why restrict this PR only for Min level, just add the max level and you kill 2 birds with 1 stone.

**Comment by locus313** [comment]
> > This pr is only meant to update the min level's to be closer to the dbc values. if we set the max_level column it will prevent higher level players from being able to enter the lower level dungeons (even without using RDF). Hence that's why its currently set to 0 for everything. The behavior you mentioned already happens without this pr if you enable
> 
> Well, but if we can fix the Max level at the same time then even better no? Why restrict this PR only for Min level, just add the max level and you kill 2 birds with 1 stone.

Because i don't think its a desired effect to lock out higher-level characters from doing lower-level dungeons.

**Comment by claudiodfc** [comment]
Yes, It is.
Otherwise you're gonna have level 80 players queued for Wailing Caverns, and this isn't a desired effect.

**Comment by locus313** [comment]
> Yes, It is. Otherwise you're gonna have level 80 players queued for Wailing Caverns, and this isn't a desired effect.
> 
> Even worse, for people that level solely on RDF, they could be level 40 and still be placed on lower level instances, and this makes it impossible to level up as. That's why there's a threshold for the levels able to queue for those instances.

But like I mentioned it also prevents higher-level characters from just walking into the dungeon as well. (which is the part I think is not desired) I do agree that we dont want this to happen in RDF. But think some other changes are required to address that part.

**Comment by claudiodfc** [comment]
That might be why there's more columns about this. Needs more investigation.

**Comment by acidmanifesto** [comment]
@locus313 what is the current status of this PR?

**Comment by acidmanifesto** [comment]
@locus313 please let us know if this pr is still being worked on or not. If not I will have to Mark it as abandon.

**Comment by locus313** [comment]
As I mentioned before this pr is only targeted at updating the min levels. I do not really have the time right now to investigate the other items brought up.

**Pull request closed without merging**
