### PR TITLE
feat(Apps): Automatic extractor for windows

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
- Add a program to run all extraction tools from.
- https://github.com/TrinityCore/TrinityCore/blob/3.3.5/contrib/extractor.bat

## Tests Performed:

- Tested with base files

## How to Test the Changes:

1. Copy all extractor .exe's into the folder with wow.exe
2. Copy extractor.bat into the same folder
3. run extractor.bat

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
This is what I've been using. Laugh
mapextractor.cmd
```
@echo off
cls

extract_maps
echo.
echo Extracting DBCs and Maps...
mapextractor.exe

extract_vmaps
echo.
echo Extracting VMAPs
vmap4extractor.exe

build_vmaps
echo.
echo Building VMAPs
md vmaps
vmap4assembler.exe Buildings vmaps

echo.
echo Building MMAPs
md mmaps
mmaps_generator.exe --threads 8

echo.
echo Press any key to exit
pause NUL
```

**Comment by Kitzunu** [comment]
Is that in the core?

**Comment by pklloveyou** [comment]
The same function as PR

**Comment by pklloveyou** [comment]
#2538

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by cjl3230** [comment]
when I choose "4 - Extract all (may take hours)"

**Pull request merged**
