### PR TITLE
fix(Core/Spells): wrong distance calculations in AoE spells

### PR DESCRIPTION
**Pull request by Viste**
AoE = Area of Effect

##### CHANGES PROPOSED:
* the calculation doesn't take into account the size of the dynamic object (the object at the center of the aoe) anymore
* the calculation doesn't take into account the size of the player anymore
 * the distance calculation is done now in 2D.
##### Target branch(es): Master

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
This PR has been tested on test servers with `staging` branch for 2 weeks.

@comix1988 @Asherdoom @zato90 @Azzaleo @RaistlinAstragon

can you please confirm that there is nothing wrong regarding the changes of this PR?

**Comment by comix1988** [comment]
@Viste I have tested a AoE spell and a single target spell of the mage and the distance has a small bug, look at the screens

singletarget
aoe

**Comment by Nefertumm** [comment]
https://github.com/TrinityCore/TrinityCore/commit/95456ab5d8bd623481d315ae55dfbb44b45ba9f5 this will fix the misscalculation. @Viste @comix1988

**Comment by FrancescoBorzi** [comment]
I've solved the merge conflicts. Notes:

- @Viste please have a look, just to double check I haven't done mistakes when solving the conflicts
- It's important to know if the bug reported by @comix1988 here has been introduced by this PR or was already on `master`.

**Comment by comix1988** [comment]
question: is the calculation made on the distance "2D" or "exact 2D"?

**Comment by Viste** [comment]
2D

**Comment by Viste** [comment]
@comix1988 update PR can you test it now again

**Pull request closed without merging**
