### PR TITLE
Removing Goblin Rocket Pack Fix in ICC Gunship Battle

### PR DESCRIPTION
**Pull request by brussens**
##### CHANGES PROPOSED:

The item is removed immediately after the death of the enemy ship, which prevents players from returning to their ship. Therefore, you should remove the backpack later, for example, when one of the commanders begins to leave the ship.

P.S.: This implementation is not quite correct from the architectural point of view, but since we have classes of commanders do not have a common class, we have to finish with the following crutch.

##### Target branch(es):

Master

 
 

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by talamortis** [comment]
can i ask, why have you put the fix into a new class instead of just creating another function and call it that way?

**Comment by FrancescoBorzi** [comment]
@talamortis because of modularity, we should avoid having big classes/methods imho

**Comment by brussens** [comment]
> Isnt that fixed some days ago?
> [9ea1b0e](https://github.com/azerothcore/azerothcore-wotlk/commit/9ea1b0e6be843955d135ed801f29d93eb1cb1d9e)

Your fix removes the object after the ship's murder, when the players can still be on it.

**Comment by brussens** [comment]
> @talamortis because of modularity, we should avoid having big classes/methods imho

Because this method needs to be called from two NPCs (Muradin and Saurfang), so a helper class with the static method was created.

**Comment by talamortis** [comment]
> > @talamortis because of modularity, we should avoid having big classes/methods imho
> 
> Because this method needs to be called from two NPCs (Muradin and Saurfang), so a helper class with the static method was created.

So couldnt this be done in the instance file and @FrancescoBorzi  what does this change had to do with a modular structure??

**Comment by brussens** [comment]
> @talamortis because of modularity, we should avoid having big classes/methods imho

The use of assistant classes is a common practice, I don't understand what I've seen wrong with @talamortis

**Comment by brussens** [comment]
> So couldnt this be done in the instance file and @FrancescoBorzi what does this change had to do with a modular structure??

Why make a copyaster in two classes when you can put it in a separate helper class and use it several times?

**Comment by talamortis** [comment]
> > So couldnt this be done in the instance file and @FrancescoBorzi what does this change had to do with a modular structure??
> 
> Why make a copyaster in two classes when you can put it in a separate helper class and use it several times?

I totally agree, but why not call it in the instance data to remove once the event is complete?

**Comment by poszer** [comment]
> > > So couldnt this be done in the instance file and @FrancescoBorzi what does this change had to do with a modular structure??
> > 
> > 
> > Why make a copyaster in two classes when you can put it in a separate helper class and use it several times?
> 
> I totally agree, but why not call it in the instance data to remove once the event is complete?

Exactly

**Comment by brussens** [comment]
> I totally agree, but why not call it in the instance data to remove once the event is complete?

That's exactly how it's called for. This is a regular helper, which is called when it is necessary. Why bother with this logic in every NPC class?

**Comment by NixAJ** [comment]
Unnecessary helper class, but perhaps I should also start making a helper class for everything that needs just a single function. Thank you, I'll take this lesson with me.

**Comment by brussens** [comment]
> Unnecessary helper class, but perhaps I should also start making a helper class for everything that needs just a single function. Thank you, I'll take this lesson with me.

As a matter of fact, you can put everything that is written somewhere several times into this auxiliary class, there are such places in this script. Besides, the class is static.

**Comment by NixAJ** [comment]
Is this how you always write code in PHP, this make a new class whenever an existing one already exists because you don't like how it is?

Heres the facts, they're very simple and not very complicated to understand.

1. Instance Scripts allow you to store data / have functions for an ENTIRE instance.
2. Making new classes where classes already exists are bad practice, this is called BLOATING. Helper classes such as StringUtils, MathUtils are common practices because they solve GLOBAL issues when wanting to do a certain type of function in a multitude of places.

I don't understand why your have to be so persistent, just move the function to the instance script.

**Comment by talamortis** [comment]
image
 just thought id leave this here :)

**Comment by brussens** [comment]
@talamortis ok

**Comment by talamortis** [comment]
@Winfidonarleyan  please look at the code before "Approving" commits.

**Comment by talamortis** [comment]
@brussens  do you see what i have done with the fix?

- Soon as the event mode is set to done it will then just go though that one statement and remove the item from the player as it sets the loot for the chess this will save bloating of scripts ect.

**Comment by brussens** [comment]
@talamortis Your advice is wrong. The backpack is removed immediately after the ship is killed, and should be removed when the commander begins to leave the ship

**Comment by brussens** [comment]
@talamortis Why don't you read PR?

**Comment by brussens** [comment]
> Unnecessary helper class, but perhaps I should also start making a helper class for everything that needs just a single function. Thank you, I'll take this lesson with me.

And, yes, it's a pity that you're making fun of helper classes without realizing that in the first case the helper class is never global, and in the second case global functions are evil, regardless of programming languages. And yes. I develop most of the time in PHP, but I still understand how the architecture of applications is built, and I don't do that as long as it works. If PHP programming is something bad for you, don't make fun of the language here.

**Comment by talamortis** [comment]
In what way have i made fun of "php" language? im just saying the helper class is not necessary here to be called, also if you knew how the architecture works then you would know that i still had to correct your PR as you put the fix in the Game object part for setting the loot for the players.

**Comment by brussens** [comment]
@talamortis Actually, this comment wasn't about you. And yes. What architecture are we talking about? There is no architecture in AC, there is no one here who has a lot of things to do. And yes, your PR fix did not fix the problem described in the header in any way. The backpack is removed in the same way as it was before. Let it stay as it is.

**Comment by talamortis** [comment]
> @talamortis Actually, this comment wasn't about you. And yes. What architecture are we talking about? There is no architecture in AC, there is no one here who has a lot of things to do. And yes, your PR fix did not fix the problem described in the header in any way. The backpack is removed in the same way as it was before. Let it stay as it is.

Ok give me 5 mins ill submit something else to fix your issue.

**Comment by talamortis** [comment]
Please test the current fix @brussens

**Comment by brussens** [comment]
@talamortis I'm sorry, but after all the reading there is no desire to be engaged in the test of the given PR. Let the testers do it.

**Comment by NixAJ** [comment]
Very mature of you

**Comment by FrancescoBorzi** [comment]
@NixAJ if you want to give your technical opinion, that is always appreciated. However do it without making fun of other people, otherwise don't do it at all.

**Comment by Viste** [comment]
image

**Comment by Viste** [comment]
Smells like some kind of nepotism where you all be with you all good ideas where merge #2095 .
Ah i see you kissed each other's asses in private.
Why did you stop now?
And decided to attack a guy who decided to make the code better?
Yeah, the class is really redundant in this case.
But why not tell a guy about saving data in the dungeons, but attack him immediately by a gang.
Good luck with your endless quest corrections.

**Comment by talamortis** [comment]
@Viste  In what way was i attacking him i asked a simple question about why do we need it in a differnt class when it could of been called in the instance script file?

**Comment by Viste** [comment]
Look at the situation, abstracted from self.
Everything looks like the three of you landed in the commentary to destroy the guy.
Why is that? (Laughs)
Because it was only after you were apparently released from hatred that the NixAJ wrote something intelligible.
Instead of useless questions, to which the guy gave quite constructive answers.

`So couldnt this be done in the instance file and @FrancescoBorzi what does this change had to do with a modular structure??` 
On this answer you could explain the standard logic of dungeon scripts and stop this madness by you keep on ask bullshit insted of explain.

**Comment by talamortis** [comment]
Tested myself and appears to be working as intended

**Comment by FrancescoBorzi** [comment]
@talamortis ok, thank you. Will be merged.

**Comment by NixAJ** [comment]
> Look at the situation, abstracted from self.
> Everything looks like the three of you landed in the commentary to destroy the guy.
> Why is that? (Laughs)
> Because it was only after you were apparently released from hatred that the NixAJ wrote something intelligible.
> Instead of useless questions, to which the guy gave quite constructive answers.
> 
> `So couldnt this be done in the instance file and @FrancescoBorzi what does this change had to do with a modular structure??`
> On this answer you could explain the standard logic of dungeon scripts and stop this madness bгut you keep on ask bullshit insted of explain.

Considering your past record, I don't think you should be the one lecturing on being toxic ;)

**Comment by Viste** [comment]
@NixAJ 
image

**Comment by talamortis** [comment]
so mature @Viste … this is one of the reasons why AC has got a bad name

**Comment by Viste** [comment]
@talamortis i dont start this ))) you and you 2 friends do it

**Comment by talamortis** [comment]
I didn't start anything @Viste  I was just pointing @brussens in the right direction of the fix, but if we get slandered for it then maybe next time I wont mention anything next time. You would of done the same. and to be honest no one asked for your input :)

**Comment by FrancescoBorzi** [comment]
Please solve your personal disputes in private, let's keep it professional here and focus on the code.

Thanks

**Comment by wowmane** [comment]
good job!

Thanks All

**Comment by disclosurez** [comment]
Just implemented on my server with ~50 online, should let you know if this is fixed or not asap.

**Comment by FrancescoBorzi** [comment]
@disclosurez thanks a lot, please let us know

**Comment by BarbzYHOOL** [comment]
@disclosurez What can you tell us?

And thank you very much Brussens for making that PR

**Comment by disclosurez** [comment]
Works well, please merge

**Comment by BarbzYHOOL** [comment]
ty disclosurez

**Comment by talamortis** [comment]
And thanks @talamortis? Maybe??

**Pull request merged**
