### PR TITLE
fix(Core/Movement): Disabled invalid code about getting area info fro…

### LINKED ISSUE #7335: Unmount\Mount when traveling by ship or zeppelin
### Current Behaviour

Unmount\Mount when traveling by ship or zeppelin. When you traveling by ship or zeppelin you can hear or even see how you character unmount and mount again after loading screen. Sometimes **mounting doesn't happen** and after loading screen you unmount. And **Pet sometimes is gone** after traveling.

on screen i was mounted. After traveling dismounted.
WoWScrnShot_081521_090657

I think it's a some hack for someting, i dont know.

### Expected Blizzlike Behaviour

No unmount\mount when traveling by ship or zeppelin. No sound. No visible effects. The same on warname.

### Source

_No response_

### Steps to reproduce the problem

traveling by ship or zeppelin

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/azerothcore/azerothcore-wotlk/commit/6ff9b21b736c5bbf506a1ffa439caadb42c5dbdf

### Operating system

Windows 10 x64

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
…m gameobjects.

Fixes #7335

## Issues Addressed:

- Closes #7335

## Tests Performed:

- Tested ingame on boat from BB to Rachet.

## How to Test the Changes:

More info [here](https://github.com/chromiecraft/chromiecraft/issues/1615)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
build fails

**Comment by FrancescoBorzi** [comment]
still failing

**Comment by FrancescoBorzi** [comment]
@Yehonal @Footman can you please review this PR?

also does it need more testing ? (the author tested it)

**Comment by Yehonal** [comment]
Can you explain a little bit those changes?

However, if this is a proper fix, maybe we should not keep the comments.

Also, can you try to test the case that the code was meant for? 

```
    // NOTE: Objects will not detect a case when a wmo providing area/liquid despawns from under them
    // but this is fine as these kind of objects are not meant to be spawned and despawned a lot
    // example: Lich King platform
```

Without that code can we assume that the lich king platform will still work?

**Comment by UltraNix** [comment]
The code was about getting area/locations data directly from gameobjects (if present) instead of maps/vmaps.
Eg. is you spawn LichKing platform in ShadowmoonValey, just like [@SHauren did](https://github.com/TrinityCore/TrinityCore/commit/0468c70dfe91794ad272594323dd7feb611d0a93#commitcomment-40210913), you would be recognized as being in ICC. But in some places that data is not precise and causes some problems, such as the linked one.
The code was ported from TC and the same bug is on TC. Just comment that out, because maybe someone will fix it.
Ofc, the original platform in ICC works okay.

**Comment by Yehonal** [comment]
> The code was about getting area/locations data directly from gameobjects (if present) instead of maps/vmaps. Eg. is you spawn LichKing platform in ShadowmoonValey, just like [@Shauren did](https://github.com/TrinityCore/TrinityCore/commit/0468c70dfe91794ad272594323dd7feb611d0a93#commitcomment-40210913), you would be recognized as being in ICC. But in some places that data is not precise and causes some problems, such as the linked one. The code was ported from TC and the same bug is on TC. Just comment that out, because maybe someone will fix it. Ofc, the original platform in ICC works okay.

I see, thanks!

**Review by Yehonal — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum can you please test this PR?

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
