### PR TITLE
[DB] Scholomance torch fix

### LINKED ISSUE #751: [DB] Scholomance torch
**Description**:
Door problem. 

**Current behaviour**: Tell us what happens
The Door(Go entry id =175610) must open when worked a torch at Jandice Barov's room

**Expected behaviour**: Tell us what should happen instead
Active secret torch -> Open door -> get items from a chest, behind of the door. 

**Steps to reproduce the problem**:

```SQL
REPLACE INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES (177385,1,0,1,70,0,100,0,2,0,0,0,9,0,0,0,0,0,0,14,43178,175610,0,0,0,0,0,'Torch - On Gossip Hello - Set Gameobject State'),(177385,1,1,0,61,0,100,0,0,0,0,0,106,16,0,0,0,0,0,20,176944,200,0,0,0,0,0,'Torch - On Gossip Hello - Remove Gameobject Flag');
```

**AC hash/commit**:  
https://github.com/azerothcore/azerothcore-wotlk/commit/b669d24a1f6c622737d68be3069a2cfbca5bbfc2

**Operating system**:  
win10 64bit

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/53419275-db-scholomance-torch?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pondaveia**
**Changes proposed:**

-  Copied the fix from tea91 that has been tested by @Knindza

**Target branch(es):**

1.x/2.x etc.

**Issues addressed:** #751 

Closes #751

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Thank you for turning it into a PR

Thanks @tea91 too

**Comment by BarbzYHOOL** [comment]
Hmm was going to merge it but I think it's not the proper way to update SQL on AzerothCore. Need to use an update query or insert if it was missing

**Comment by Deku** [comment]
@BarbzYHOOL corrected the sql formatting 😃

**Comment by BarbzYHOOL** [comment]
I'm not sure. Was the row existing or not?

> https://github.com/azerothcore/azerothcore-wotlk/wiki/Dealing-with-SQL-files
> always use UPDATE in order to change the value of fields of existing rows

Verification: yes the row existed

Here are the old rows:

```
(177385,1,0,1,64,0,100,0,1,0,0,0,131,1,0,0,0,0,0,20,175610,200,0,0,0,0,0,'Torch - On Gossip Hello - Set Gameobject State'),
(177385,1,1,0,61,0,100,0,0,0,0,0,106,16,0,0,0,0,0,20,176944,200,0,0,0,0,0,'Torch - On Gossip Hello - Remove Gameobject Flag');
```

Here are the new rows:

```
(177385,1,0,1,70,0,100,0,2,0,0,0,9,0,0,0,0,0,0,14,43178,175610,0,0,0,0,0,'Torch - On Gossip Hello - Set Gameobject State'),
(177385,1,1,0,61,0,100,0,0,0,0,0,106,16,0,0,0,0,0,20,176944,200,0,0,0,0,0,'Torch - On Gossip Hello - Remove Gameobject Flag');
```

So only the first row is edited and can be updated.

**Comment by Deku** [comment]
@BarbzYHOOL well, there it is 🤣

**Comment by Nefertumm** [comment]
Please set the proper author in the commit (@tea91 in this case):

https://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by pondaveia** [comment]
I have already quoted him here and we are not using his fix but Deku's. Also why would i do that. Also I followed the instructions and couldn't.

**Comment by Deku** [comment]
I hope that pleases the boys

**Pull request merged**
