### PR TITLE
fix(DB): Remove duplicates Cenarion Stormcrow

### PR DESCRIPTION
**Pull request by LukasVolgger**
The creatures with guid 84366, 84368 are wrong and will be removed with this PR.

These 2 creatures are the once who have a guid in `creature` table: 

image

image

All the other Storm Crows have no guid in DB (example): 

image

**Behaviour without the PR:** 
---------------------------

image

image

**Behaviour with the PR:** 
---------------------------

image

image

## CHANGES PROPOSED:
-  Remove the guid 84366 & 84368 as not needed in creature table

## ISSUES ADDRESSED:
- Closes 

## TESTS PERFORMED:
- Imported SQL with HeidiSQL on Win 10 pro x64
- Tested succesfully ingame

## HOW TO TEST THE CHANGES:

- .go -177.734650 5522.484375 42.142647 530
- .go -221.055984 5597.661133 62.601299 530
- Check that there is only one crow like the screenshots above

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Endeffect-AT** [comment]
Need feedback if this is an acceptable solution @staff & why have the other crows no guid? Scripted?

**Comment by Stoabrogga** [comment]
Yes, they are summoned using a script and therefore have no DB GUID. The script is called "npc_air_force_bots":
https://github.com/azerothcore/azerothcore-wotlk/blob/b6cb9247ba96a862ee274c0765004e6d2e66e9e4/src/server/scripts/World/npcs_special.cpp#L489-L492

**Comment by Endeffect-AT** [comment]
Thx for the quick answer! Didn't know where to look for it in the src. I noticed it's not simply searching by name...

What do you think about this fix in relation to Blizzlike? I did not really find a confirmation of the retail variant, but as it is now it is also not correct.

**Comment by Stoabrogga** [comment]
I think in this case they can be deleted, as the script handles the spawn.

**Comment by Stoabrogga** [comment]
Tested successfully. The only crows left are the ones spawned by the script.

**Comment by BarbzYHOOL** [comment]
@LukasVolgger thank you :)

**Pull request merged**
