### PR TITLE
fix(DB/Zones):improved Tirisfal Glades

### PR DESCRIPTION
**Pull request by Knindzagxg**
Glades are now fully updated, since some creatures in zone was missing SmartAI.

Working on every zone at the moment, and will post updates once i'm done with each.

To test it:
Apply SQL
Restart your server

You can manually spawn NPC by ID to check SmartAI or you can go to zone and check like that as well.

.npc add ID
or
.tele TirisfalGlades and run / test around.

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by aradep** [comment]
All working except for Scarlet Missionary (1536). NPC has no mana to cast Fireball with.

**Comment by Kitzunu** [comment]
I believe there is a flag for that @Knindzagxg

**Comment by Si1ker** [comment]
@Kitzunu  again.....???

image

**Comment by Kitzunu** [comment]
Never read that lol.

Can look later, busy until Sundag

**Comment by Knindzagxg** [comment]
Sorted @aradep 

Sadly, masks for full SAI don't work.
Added class to have mana and SAI will be ok with that one as well.

**Comment by Knindzagxg** [comment]
Sadly flags don't work @Kitzunu 

Think SmartAI in general need some updates soon enough xP

**Comment by Si1ker** [comment]
A flag for "Im gonna throw this thing and you can't do anything to stop me"  would be pretty cool.. 🐱

**Comment by Knindzagxg** [comment]
Yeah Sil, that flag would help a lot xP

**Review by Si1ker — APPROVED** [review]

**Review by Helias — APPROVED** [review]

**Pull request merged**
