### PR TITLE
fix(Scripts/UtgardePinnacle): Svalna Sorrowgrave's sacrifice should o…

### PR DESCRIPTION
**Pull request by Nyeriah**
…nly target players

## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- Not tested
- 

## How to Test the Changes:

Create a warlock and set its level to 80 and create another character of any class
Summon any pet as the warlock
Teleport to Utgarde Pinnacle (.tele utgardepinnacle)
Go through the instance until you reach Svala Sorrowgrave
With both characters nearby, engage the boss
Fight her until she uses performs her sacrifice player event with the sword coming down from above
Repeat the boss until she teleports the warlock pet as the player sacrifice

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by tkn963** [comment]
Tested 10 times and works as it should 👍

**Comment by tkn963** [comment]
I just ran the dungeon with my usual group that has two shamans in it and she selected one of the totems to sacrifice. She doesn't seem to select the warlock pet anymore but she does select totems. I need to do more tests with a warlock to make sure she never selects its pet.

**Comment by tkn963** [comment]
Could you potentially use this PR to also modify her position? She's in the ground before triggering her event and after being transformed. It's fine when you start the fight.
image
image

**Review by acidmanifesto — APPROVED** [review]

**Comment by Nyeriah** [comment]
I thought about looking into the visual issue but she needs a rework, won't have time to look deeper into this right now so fixing this one issue

**Pull request merged**
