### PR TITLE
fix(Scripts/GruulLair): Fix Maulgar not casting intimidating shout

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  fix target type as its not an aoe spell
-  

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/5347
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/15867

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Nefertumm — APPROVED** [review]

**Comment by balleny** [comment]
assuming this fix is on the PTR, it does not work.
looking at the code, it seems that the issue is more related to the nesting of the ability, which prevents it from triggering at all.
(assuming that it is supposed to trigger at 50%?!)

**Comment by Nyeriah** [comment]
> assuming this fix is on the PTR, it does not work.

It's not.

**Comment by elthehablo** [comment]
> assuming this fix is on the PTR, it does not work.
> looking at the code, it seems that the issue is more related to the nesting of the ability, which prevents it from triggering at all.
> (assuming that it is supposed to trigger at 50%?!)

ScheduleHealthCheck event and everything that is inside the event that you see after the `[&]` fires at the health values shown in the first parameter. It works.

**Comment by elthehablo** [comment]
> > assuming this fix is on the PTR, it does not work.
> > looking at the code, it seems that the issue is more related to the nesting of the ability, which prevents it from triggering at all.
> > (assuming that it is supposed to trigger at 50%?!)
> 
> ScheduleHealthCheckEvent and everything that is inside the event that you see after the `[&]` fires at the health values shown in the first parameter. It works.

**Pull request merged**
