### PR TITLE
fix(Core/Movement): Do not remove/set UNIT_FLAG_SWIMMING when unit st…

### LINKED ISSUE #8896: Water/underwater incorrect pathing
### What client do you play on?

other

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: https://github.com/chromiecraft/chromiecraft/issues/2244

So this npc i ve pulled it from the boat in the quest in strangle near booty bay mall and he wasnt able to attack me as you can see in this video 
https://youtu.be/VZbno0GxtCo

Tester:

The issue is confirmed. In some uncertain circumstances NPCs choosing ground paths.

https://user-images.githubusercontent.com/85256266/139852235-79365d38-709b-4875-a8e7-6cce3559ea40.mp4

https://user-images.githubusercontent.com/85256266/139852262-1b4a8815-1cd0-450d-b978-b35aae8a5e63.mp4

### Expected Blizzlike Behaviour

NPCs should always choose swimming if player in water.

### Source

X

### Steps to reproduce the problem

.go c 2607 - teleport to blood sail pirate on the boat
agro some NPCs and jump to water

### Extra Notes

https://classic.wowhead.com/npc=4505/bloodsail-deckhand

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…arts swimming.

Fixes #8896

## Issues Addressed:

- Closes #8896
- Closes https://github.com/chromiecraft/chromiecraft/issues/2244

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.go c 2607 - teleport to blood sail pirate on the boat
agro some NPCs and jump to water

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by tkn963** [comment]
Test I performed:
- Teleported to and aggro'd the creature.
- Jumped into the water and watched them run around and down into the water to attack me (as intended)
- Activated GM fly mode and flew up and watched them glitch up with me
- With GM fly mode on I hovered to the side of the ship, a bit above the water, and watched them run around to get to me. 
- When they reached the point where they stopped just under me I flew back to the ship and they ran around the ship again and up as they should to get to me.

I aggro'd a total of 2 pirates for the test, but when I tried it with more (I think like 8) it worked better. Not great, just much better. I noticed that they will also sometimes glitch upwards into the bottom part of the ship and then run up to get me.

They also like to glitch through the very bottom part of the ship, just appearing out of nowhere when you're wondering where they went.

After a few tests of jumping down and flying up, most of them seem to get even more confused and stay near the bottom of the ocean and not actually come up to me when I'm floating near the surface. As soon as I move though, this is me just jumping down and sitting where I landed, they seem to swim back up to me.

It's really hard to explain all the strange things I noticed. Jumping into the water I watched them run around to get to me, I moved just a tad and they seemed to update their movement paths, teleported into the bottom of the ship and again run back out to get to me.

I hope I could at least explain somewhat decently so you understand what I'm saying.

**Comment by tkn963** [comment]
I know most of what I said isn't common occurrence for normal players, the biggest issue for regular players is the fact that you can aggro the pirates and jump into the water and if you don't move, they'll stay near the bottom of the ocean  and you can just sit there, killing them without them getting near you.

**Comment by UltraNix** [comment]
It has nothing to do with that PR. Problems with pathfinding are not covered by this PR - it's about swimming animation.

**Comment by tkn963** [comment]
> It has nothing to do with that PR. Problems with pathfinding are not covered by this PR - it's about swimming animation.

Oh, okay! I'm sorry for the long comment then. Haha.

In that case, it works just as it should! 👍

**Comment by acidmanifesto** [comment]
Not needed with upcoming PR: https://github.com/azerothcore/azerothcore-wotlk/pull/9272/commits/25eba04ef3fd0dc64ad832bbd350a12cbaa2946c
image

**Comment by Nyeriah** [comment]
Thanks for the PR, but the upcoming inhabit type changes will address this issue it seems. I'm closing it for now.

**Pull request closed without merging**
