### PR TITLE
fix(Core): Crashfix.

### LINKED ISSUE #12075: [server]world server crash 0617
### Current Behaviour

crash log :

https://gist.github.com/mpfans/c2ab325969fa650e0744e188efcaf0dd

### Expected Blizzlike Behaviour

none

### Source

_No response_

### Steps to reproduce the problem

none

### Extra Notes

_No response_

### AC rev. hash/commit

8151fcda22c6167211d1c08788791fe1ad9e2c44 + PR #11903 (updated)

### Operating system

ubuntu 20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
## Issues Addressed:

- Closes #12075

## Tests Performed:

- Not tested.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by acidmanifesto** [comment]
@mpfans are you able to test?

**Comment by mpfans** [comment]
I don't know how to reproduce

**Comment by acidmanifesto** [comment]
> I don't know how to reproduce

well since it is essentially a null check, there will be no harm in adding it in.

**Review by acidmanifesto — APPROVED** [review]

**Comment by acidmanifesto** [comment]
Thank you for the PR.

**Pull request merged**
