### PR TITLE
refactor(Core/Query): escape some MySQL 8.0 keywords

### PR DESCRIPTION
**Pull request by Kitzunu**
DISCLAIMER: This will not allow MySQL 8.0 support, but it is 1 step closer to freedom :D

## CHANGES PROPOSED:
-  Add grave accent to some MySQL 8.0 keywords (group & rank)

## ISSUES ADDRESSED:
- Closes my promise to make this PR for @FrancescoBorzi :P

## TESTS PERFORMED:
- Nada since I already run MySQL 8.0 locally.

## HOW TO TEST THE CHANGES:

Run WorldServer(.exe)

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Helias** [comment]
Did you add accent to `ranks` and `groups` because they are private keywords on Mysql 8.0?
You could add the accents also in the other columns if you want.

Anyway, thanks for this PR, refactoring and supporting modern technologies is really a good improvement.

**Comment by Kitzunu** [comment]
I added it to just those two because they are the only ones that cause issues in build/startup of worldserver on Mysql 8.0.

I didn't dig too deep into why.

**Comment by FrancescoBorzi** [comment]
@Kitzunu let's merge this tomorrow?

**Comment by Kitzunu** [comment]
Sure

**Pull request merged**
