### PR TITLE
Implement missing GridUnload setting

### PR DESCRIPTION
**Pull request by AGandrup**
The show goes on...
## Changes Proposed:

This PR proposes changes to:
- Implement missing `GridUnload` setting, which turns on/off unloading of grids (default on) and also act as a guard to make sure that `PreloadAllNonInstancedMapGrids` setting cannot be enabled while `GridUnload` is enabled.
- Added missing check for instances in LoadMap()
## Issues Addressed:

- Should help performance issue discussed in https://github.com/azerothcore/azerothcore-wotlk/issues/17439

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [ ] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/17571 this crash after the latest grid pr

**Comment by heyitsbench** [comment]
> 17571 this crash after the latest grid pr

At least it seems to be an actual crash instead of a hang. Progress, I suppose.

**Comment by AGandrup** [comment]
Will look into it asap.

**Comment by AGandrup** [comment]
> > 17571 this crash after the latest grid pr
> 
> At least it seems to be an actual crash instead of a hang. Progress, I suppose.

Taking one small step at a time :harold_pain:

**Comment by Day36512** [comment]
I've cherry picked both of your commits. Glad progress is being made. I'm still getting crashes pointing to Object.cpp 342. Should I open an issue and submit logs there or do you want them here?

**Comment by AGandrup** [comment]
> I've cherry picked these and the other fix commits of yours. Glad progress is being made. I'm still getting crashes pointing to Object.cpp 342 roughly once every 30mins to an hour. Should I open an issue and submit logs there or do you want them here?

Feel free to post them here with as many details as possible 🙏

**Comment by Day36512** [comment]
> > I've cherry picked these and the other fix commits of yours. Glad progress is being made. I'm still getting crashes pointing to Object.cpp 342 roughly once every 30mins to an hour. Should I open an issue and submit logs there or do you want them here?
> 
> Feel free to post them here with as many details as possible 🙏

So I've been doing a couple different tests, removing modules, lua scripts, cusom scripts etc. I think unfortunately it's actually going to end up being related to trickerer's fork directly (NPC Bots) so I'm testing disabling wandering bots currently. So far no crashes but I would definitely keep in mind with my Callstacks that this is indeed the Trickerer fork even though I've cherry picked your changes (ie, might be indirectly related to the grid system and NPC Bot wandering interactions so really the only thing to be done is for trickerer to fix his build and make exceptions).

Out of curiosity though, how closely do the changes you've made mirror TC's system? 

[Crashes.zip](https://github.com/azerothcore/azerothcore-wotlk/files/13180086/Crashes.zip)

**Comment by AGandrup** [comment]
@Day36512 I just comitted a possible crash fix here, please test it and see if it does anything for you. That said, I have no idea how the changes I've done behave in the project that you are using as I am not familiar with it.

> Out of curiosity though, how closely do the changes you've made mirror TC's system?

Most of it is 1:1, but I spend a lot of time comparing the two and going back and forth in commit history to check why something has been implemented or removed and the motivation behind it.

**Comment by Day36512** [comment]
Awesome, that helps a lot. Much appreciated for all your hard work

**Comment by AGandrup** [comment]
> Awesome, that helps a lot. Much appreciated for all your hard work

No more crashes? 😬

**Comment by Day36512** [comment]
No, just helps me figure out where i might be able to see where npcbots might be failing

**Comment by Nyeriah** [comment]
If this fixes the crash we need to merge it right away, its our top priority as the core unusuable atm with the crash

**Comment by Day36512** [comment]
So far with bots disabled there's no crashes but that's not testing it extensively. Probably would prefer a higher pop realm to test.

**Comment by AGandrup** [comment]
> If this fixes the crash we need to merge it right away, its our top priority as the core unusable atm with the crash

It does fix it. I managed to reproduce the crash without the changes

**Review by Nyeriah — APPROVED** [review]

**Comment by AGandrup** [comment]
You know how we got this "CONFIG_PRELOAD_ALL_NON_INSTANCED_MAP_GRIDS" configuration. The name do state to load ALL non-instanced maps but what is really meant by that is all the base maps / continents i.e. Kalimdor, Eastern Kingdom, Outland and Northrend. Well, turns out that not only did it load those maps, it also loaded ALL sorts of test maps, transport maps (which are not actual maps, but are used to spawn npcs and gobs on transports) and custom maps and then ontop of that it called CreateBaseMap method on all of these maps.

With the last commit we only load the continents as intended which is 4 maps in total instead of, idk 30 maps. So not only does this reduce CPU usage a lot, it also reduces startup as well as shut down time of the worldserver.

**Comment by Nyeriah** [comment]
https://github.com/chromiecraft/chromiecraft/issues/6299#issuecomment-1792275391

Grid searchers seem to have changed and no longer work reliably.

There seems to be far too many issues arising from this implementation unfortunately.

**Comment by AGandrup** [comment]
> [chromiecraft/chromiecraft#6299 (comment)](https://github.com/chromiecraft/chromiecraft/issues/6299#issuecomment-1792275391)
> 
> Grid searchers seem to have changed and no longer work reliably.
> 
> There seems to be far too many issues arising from this implementation unfortunately.

As discussed a couple of times now, the best option right now would be to revert the implementation for now, and make a new PR where it can be properly tested. I kinda want to go over the whole thing again as I have found that some of the changes done (might) not have been necessary or irrelevant, and also that other things should (perhaps) be taking into consideration. Ontop of that, I also got Grafana up and running, so I can track performance and catch bugs much better now.
Unfortunately I haven't had much time this past week so haven't been able to do much with it yet.

I also want to add that @mpfans told me, that he would be willing to help me test and troubleshoot.

So ye, I wouldnt mind rolling back, as it is honestly also a bit frustrating for me to see there keep being issues, and I dont have all time in the world to sit down and fix it.

**Comment by skelUA** [comment]
Crashes is still exist on last rev

**Comment by AGandrup** [comment]
> Crashes is still exist on last rev

Crash log?

**Comment by AGandrup** [comment]
@skelUA if you think the crash is related to this PR, please share crash log so it can be fixed. If you have more information, for example how to reproduce it, please share that as well.

**Pull request merged**
