### PR TITLE
feat(DB): release ACDB 7.0.0

### PR DESCRIPTION
**Pull request by Kitzunu**
```
WORLD: World initialized in 0 minutes 10 seconds

AzerothCore rev. 5d6dfca80cf1 2022-08-21 09:48:09 +0200 (new-squash-POGGIES branch) (Win64, RelWithDebInfo, Static) (worldserver-daemon) ready...
```

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
```
Duplicate filename "/home/runner/work/azerothcore-wotlk/azerothcore-wotlk/data/sql/archive/db_world/7.x/2022_08_21_00.sql" occurred. Because updates are ordered by their filenames, every name needs to be unique!
```
Huh? There are no duplicates o.o

@Winfidonarleyan ?

**Comment by Kitzunu** [comment]
My sourcery works, case closed =)

**Review by Nyeriah — APPROVED** [review]

**Comment by hahalmtdhl** [comment]
Inform error: Unknown collation: 'utf8mb4_0900_ai_ci'
The current MySQL version needs > 8.0 ??

**Comment by Kitzunu** [comment]
No, we do not specify any collation anywhere

**Pull request merged**
