### PR TITLE
fix(Scripts/HyjalSummit): Adjust Air Burst cast targetting.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:

This PR proposes changes to:
-  [X] Scripts (bosses, spell scripts).

## Issues Addressed:

- Closes unreported issue.

## SOURCE:

The changes have been validated through:
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.

## How to Test the Changes:

- [X] This pull request requires further testing.
1. Engage Archimonde in Hyjal Summit, both with one character and multiple.
2. Make sure Air Burst does not target the main threat target.
3. Make sure Air Burst does not get cast when engaged solo.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Tereneckla** [comment]
I am pretty sure the tank should not be targeted by air burst (but still be affected by the knockup)

**Comment by heyitsbench** [comment]
> I am pretty sure the tank should not be targeted by air burst (but still be affected by the knockup)

Yes, that is what this PR aims to do. Currently, the main threat target cannot be affected by Air Burst's effect, but does get targeted by it.

**Comment by Tereneckla** [comment]
Minor brain fart on my side, didn't see the 1

**Comment by Nyeriah** [comment]
Ehm i am pretty sure this is how it was set up before but then someone said it shouldn't work that way, I'll let diablo decide this one as he was working on it previously

**Comment by heyitsbench** [comment]
I know there was an issue where it was still targeting top threat targets, but I heard nothing about it being supposed to work the way it currently does, but I'm in no rush.

**Comment by Tereneckla** [comment]
It only was DoCastAOE for a moment

tank never was excluded from the initial targeting

https://github.com/azerothcore/azerothcore-wotlk/commit/f78820e9d58e9cd8a8f7b6234d94bce5d8a0c1d5
https://github.com/azerothcore/azerothcore-wotlk/commit/bbb0cb43eb0d0574c9a019a0b01cfe71e04ef80b
https://github.com/azerothcore/azerothcore-wotlk/commit/8a988fd10a1adba402cb6db45d7385c81ff606f9

**Comment by amed80** [comment]
It was fixed before with "DoCastRandomTarget(SPELL_AIR_BURST, 0, 0.0f, true, false, false);" https://github.com/azerothcore/azerothcore-wotlk/commit/f78820e9d58e9cd8a8f7b6234d94bce5d8a0c1d5 , i mistakenly reported that the issue still exist which lead to the other change 😥

**Comment by Tereneckla** [comment]
> It was fixed before with "DoCastRandomTarget(SPELL_AIR_BURST, 0, 0.0f, true, false, false);" [f78820e](https://github.com/azerothcore/azerothcore-wotlk/commit/f78820e9d58e9cd8a8f7b6234d94bce5d8a0c1d5) , i mistakenly reported that the issue still exist which lead to the other change 😥

probably, yours excludes the tank
the proposed solution here excludes the highest in threat

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
