### PR TITLE
fix(Core\Scripts):Venomhide Hatchling multiple fixes

### PR DESCRIPTION
**Pull request by Ragelezz**
## Changes Proposed:
- Venomhide Hatchling should offer quests only to summoner
- Venomhide Hatchling should emote when you throw food at him
- Venomhide Hatchling should have his model based on how many baby tooths you have

## Issues Addressed:

- 1.1 Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8779
- 1.2 Closes https://github.com/chromiecraft/chromiecraft/issues/1802
- 2.1 Closes https://github.com/chromiecraft/chromiecraft/issues/1965
- 2.2 Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8409
- 2.3 Closes https://github.com/azerothcore/azerothcore-wotlk/pull/8556
- 3.1 Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8107
- 3.2 Closes https://github.com/chromiecraft/chromiecraft/issues/1871
- 3.3 Closes https://github.com/azerothcore/azerothcore-wotlk/pull/8557
- 
## Tests Performed:

- 1.1 and 1.2 > get 2 chars, one with quest (13906) and other without, summon npc hatchling and notice you can take quests from him without having the main quest or being the owner; also you cannot take quests from another character's hatchling even if you have the main quest 
- 2.1 and 2.2 > .quest add 13906 and summon the pet, regarding how many Baby Tooths you have, he will have the same model
- 3.1 and 3.2 Throw some food at him, for example Silithid Meat, no emote at all

## How to Test the Changes:

1. 1.1 and 1.2 > get 2 chars, one with quest (13906) and one without, summon hatchling and notice only the summoner can take quests from him, even if the 2nd char has the main quest or not
2. 2.1. and 2.2 .quest add 13906 and summon pet, he has various models based on how many Baby Tooths you have in the bag, the more Tooths, the bigger the pet is, ex:
( X < 6 ) = Baby
( X >= 6 and X < 11 ) = Bigger baby with reptile eyes
( X >= 11 and X < 16 ) = Adolescent raptor
( x >= 16 ) = Full-grown raptor
3. 3.1 and 3.2 Throw some food at him, he will emote that he is eating.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Hey @Ragelezz 

Sorry for all the bother, I'm going through the PRs from the oldest to newest and I just found this one, please ignore my other comments asking about the merging of those related PRs as I saw that you merged all of the others into this.

Technically we could merge them one-by-one but that would be a rather preventable bother to you, because merge conflicts eventually will happen. Could you close the other ones that were included into this? 

Thanks for your contributions and for taking the time to look into this :)

**Comment by tkn963** [comment]
I tested it, added the quest to one character and summoned the hatchling. The second character couldn't speak to the hatchling no matter what. There is still a "?" icon when hovering over the hatchling, is that intended or should it just be a hand like when hovering over it as Alliance?

It should be noted in the PR info though that only Horde can access this, as Alliance only gets a "You can never use that item" warning.

**Comment by Ragelezz** [comment]
@Nyeriah So.. what should I do exactly ?

@tkn963 only horde can take that .. tought some players would know that tho, that's fine.

**Comment by Nyeriah** [comment]
@Ragelezz **if** this PR contains all of the changes from the other 3 PRs then you can close the other 3 and only maintain this one, updating it accordingly to reflect the changes (edit the description, so it reflects all of the changes contained in this PR)

**Comment by tkn963** [comment]
> 
> 
> @Nyeriah So.. what should I do exactly ?
> 
> @tkn963 only horde can take that .. tought some players would know that tho, that's fine.

I tend to alternate between Alliance and Horde when testing PRs to make sure it works on both sides. I've never done the quest so I had no idea until I noticed the error message on screen. It's fine either way, good job.

**Comment by Ragelezz** [comment]
@Nyeriah after irl work today will close the rest and leave only this one so we can merge it

**Review by Nyeriah — APPROVED** [review]

**Comment by Nyeriah** [comment]
Thank you for your PR!

**Pull request merged**
