### PR TITLE
fix(DB/Loot): Rot Hide Mongrel has incomplete loot table

### LINKED ISSUE #12808: [Tirisfal Glades] Rot Hide Mongrel has incomplete loot table. Missing quest item, greens.
https://github.com/chromiecraft/chromiecraft/issues/3854

### What client do you play on?

ruRU

### Faction

Horde

### Content Phase:

1-19

### Current Behaviour

Missing quest drop from Rot Hide Mongrel. 

On the site they generally have a very strange loot table - only bags, although they should drop various low-level trash, cloth, and so on.
https://wowgaming.altervista.org/aowow/?npc=1675

### Expected Blizzlike Behaviour

Should drop quest items and various low-level trash

https://www.wowhead.com/wotlk/quest=358
>От cj628 27.02.2007 (Обновление 2.0.8)		
The Embalming Ichor drop off all three varieties of Rot Hides (Gnolls, Graverobbers and Mongrels).
If you see another person at the farm with the Mongrels, group up for "Wanted: Maggot Eye" https://www.wowhead.com/wotlk/?quest=398

https://www.wowhead.com/wotlk/npc=1675

### Source

https://www.wowhead.com/wotlk/quest=358
https://www.wowhead.com/wotlk/npc=1675

### Steps to reproduce the problem

Kill a lot of Rot Hide Mongrels and see nothing but a few copper coins

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/757375f982429c60b17e9b1f559ed86cb22abbc4

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna](https://github.com/azerothcore/mod-eluna)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Zenslash**
## Changes Proposed:
-  Rot Hide Mongrel loot table changed

## Issues Addressed:

- Closes #12808 

## SOURCE:

- https://www.wowhead.com/wotlk/quest=358
- https://www.wowhead.com/wotlk/npc=1675

## Tests Performed:

- Tested on local AC windows server

## How to Test the Changes:

1. Add quest  `.quest add 358`
2. Teleport to NPC `.go creature 44663`
3. Kill Rot Hide Mongrel's and check drop

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by ZhengPeiRu21** [comment]
I do not know if your changes are correct. For example, Duskbat Wing does not seem like it should drop from this mob. What is the source of this data? Vmangos might be a better source.

**Comment by Zenslash** [comment]
> I do not know if your changes are correct. For example, Duskbat Wing does not seem like it should drop from this mob. What is the source of this data? Vmangos might be a better source.

On Wowhead Duskbat Wing listed in the drop list
https://www.wowhead.com/wotlk/npc=1675

**Comment by ZhengPeiRu21** [comment]
> > I do not know if your changes are correct. For example, Duskbat Wing does not seem like it should drop from this mob. What is the source of this data? Vmangos might be a better source.
> 
> On Wowhead Duskbat Wing listed in the drop list https://www.wowhead.com/wotlk/npc=1675

This is a good example of Wowhead is not reliable. This is probably a case of a player on an incorrect private server using the Wowhead data collection addon - notice that there is only 7 drops of Duskbat Wing, much less of the other items dropping. Wowhead often has this type of mistake, so we prefer not to use it as a source.

**Comment by Zenslash** [comment]
> > > I do not know if your changes are correct. For example, Duskbat Wing does not seem like it should drop from this mob. What is the source of this data? Vmangos might be a better source.
> > 
> > 
> > On Wowhead Duskbat Wing listed in the drop list https://www.wowhead.com/wotlk/npc=1675
> 
> This is a good example of Wowhead is not reliable. This is probably a case of a player on an incorrect private server using the Wowhead data collection addon - notice that there is only 7 drops of Duskbat Wing, much less of the other items dropping. Wowhead often has this type of mistake, so we prefer not to use it as a source.

It looks like you're right. Duskbat Wing isn't listed there: https://classicdb.ch/?npc=1675
So I remove it from loot table

**Comment by ZhengPeiRu21** [comment]
I think what you have submit is definitely better than what is existing. But it also I think is still not completely correct. For example, Rabbit's Foot also doesn't seem like it belong on this mob. If possible, I think we should have a correct source for everything and not just guessed.

**Comment by Gultask** [comment]
If you're curious, here's the Cmangos DB's approach to this creature:

image

In the vast majority of cases it's better to port values from other cores, as Wowhead can be notoriously incorrect in the values presented, as you have seen :)

You can find the DB for cmangos wotlk DB here: https://github.com/cmangos/wotlk-db/blob/master/Full_DB/WoTLKDB_1_6_14060.sql.gz
Vmangos can also be excellent: https://github.com/vmangos/core/releases/tag/db_latest

**Comment by Zenslash** [comment]
> If you're curious, here's the Cmangos DB's approach to this creature:
> 
> image
> 
> In the vast majority of cases it's better to port values from other cores, as Wowhead can be notoriously incorrect in the values presented, as you have seen :)
> 
> You can find the DB for cmangos wotlk DB here: https://github.com/cmangos/wotlk-db/blob/master/Full_DB/WoTLKDB_1_6_14060.sql.gz Vmangos can also be excellent: https://github.com/vmangos/core/releases/tag/db_latest

Thanks for the links to the sources)
Cmangos DB's approach looks similar to the current loot table so I think we can stop at the current loot table

**Comment by Gultask** [comment]
Works. Even got a bag :)
image

**Review by Nefertumm — APPROVED** [review]

**Comment by Nefertumm** [comment]
Thank you for the PR!

**Pull request merged**
