### PR TITLE
fix(Core/Commands): Fix removing item from player account

### PR DESCRIPTION
**Pull request by SilentCLD**
## Changes Proposed:
- Removed the else on the SEC_PLAYER check, this shouldn't be there and silently stops the removal of items on player accounts

## Tests Performed:

- Removed an item from an account with SEC_PLAYER (0) security
- Removed an item from an account with SEC_ADMINISTRATOR (3) security

## How to Test the Changes:

1. Create two accounts, one with GM permissions and one without.
2. Add an item to both characters eg. `.addit 17 1`
3. Remove the item from both characters eg. `.addit 17 -1`
4. The item should be successfully removed from both characters

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Bogir** [comment]
Just update your fork

**Comment by SilentCLD** [comment]
> Just update your fork

What do you mean? This issue is present on master.

**Comment by Bogir** [comment]
> > Just update your fork
> 
> What do you mean? This issue is present on master.

I mean just update your fork before make new commit and open PR :)
Youк fork is outdated
`void OnAddGroup(BattlegroundQueue* queue, GroupQueueInfo* ginfo, uint32& index, Player* /*leader*/, Group* /*grp*/, PvPDifficultyEntry const* /*bracketEntry*/, bool /*isPremade*/)`

**Comment by fputs** [comment]
Using a GM character with ` SEC_ADMINISTRATOR (3)` on the account I was able to:
- Add an item to a ` SEC_ADMINISTRATOR (3)` account's character
- Remove an item from a ` SEC_ADMINISTRATOR (3)` account's character
- Add an item to a `SEC_PLAYER (0)` account's character
- Remove an item to a `SEC_PLAYER (0)` account's character

The account with `SEC_PLAYER (0)` is unable to add or remove items

**Review by IntelligentQuantum — APPROVED** [review]

**Pull request merged**
