### PR TITLE
fix(DB/quest_poi): Wrong map marker position - The Princial Source (A)

### LINKED ISSUE #4867: Wrong map marker position - The Principal Source (Alliance)
Original report: https://github.com/chromiecraft/chromiecraft/issues/212 by @necropola
Suggested change:
```
UPDATE `quest_poi_points` SET `X`=6882, `Y`=-653 WHERE `QuestID`=6122 AND `Idx1`=1 AND `Idx2`=0;
```

##### ISSUE: FACTION SIDE:
Alliance

##### CONTENT PHASE:
1-19

##### SMALL DESCRIPTION:
The Alliance Druid quest [The Principal Source](https://wotlkdb.com/?quest=6122) marks the wrong location on the map to draw the sample of water.
image

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The correct location should be marked on the map.
image

##### CURRENT BEHAVIOUR:
See **Small Decsription**.
The World DB has the wrong coordinates (7218, -386) which should be changed to (6882, -653).
```
SELECT * FROM `quest_poi` WHERE `QuestID`=6122;
+---------+----+----------------+-------+----------------+-------+----------+-------+---------------+
| QuestID | id | ObjectiveIndex | MapID | WorldMapAreaId | Floor | Priority | Flags | VerifiedBuild |
+---------+----+----------------+-------+----------------+-------+----------+-------+---------------+
|    6122 |  0 |             -1 |     1 |             42 |     0 |        0 |     1 |             0 |
|    6122 |  1 |              4 |     1 |             42 |     0 |        0 |     1 |             0 |
+---------+----+----------------+-------+----------------+-------+----------+-------+---------------+

SELECT * FROM `quest_poi_points` WHERE `QuestID`=6122;
+---------+------+------+------+------+---------------+
| QuestID | Idx1 | Idx2 | X    | Y    | VerifiedBuild |
+---------+------+------+------+------+---------------+
|    6122 |    0 |    0 | 6558 |  473 |             0 |
|    6122 |    1 |    0 | 7218 | -386 |             0 |
+---------+------+------+------+------+---------------+
```
**Suggested change:**
```
UPDATE `quest_poi_points` SET `X`=6882, `Y`=-653 WHERE `QuestID`=6122 AND `Idx1`=1 AND `Idx2`=0;
```

##### STEPS TO REPRODUCE THE PROBLEM:
- Roll an Alliance Druid
- `.quest add 6122`
- `.tele Auberdine`
- `.go xyz 7218 -386`
- Try to draw the sample (fails)
- `.go xyz 6882 -653`
- Draw the sample (success)

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/a32310772487a7a547b1a239dfaf0967b19f7493

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97181936-wrong-map-marker-position-the-principal-source-alliance?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by necropola**
## Changes Proposed:
-  Change map marker coordinates for quest [The Principal Source](https://wotlkdb.com/?quest=6122) from (7218, -386) to (6882, -653). 

## Issues Addressed:
- Closes #4867
- Closes https://github.com/chromiecraft/chromiecraft/issues/212

## Tests Performed:
- cmake, make on Linux without errors
- db_assembler.sh without errors
- checked DB using mysql command prompt
-  checked in game

## How to Test the Changes:
- Roll an Alliance Druid
- `.quest add 6122`
- `.tele Auberdine`
- `.go xyz 6882 -653`
- Draw the sample (success)

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Stifler82 — APPROVED** [review]
👍

**Comment by pklloveyou** [comment]
Tested

**Comment by Zoidwaffle** [comment]
@necropola : you don't need to recompile when just modifying the database. Then you just need to restart the worldserver.

But really nice you started making PR's! <3

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by necropola** [comment]
> @necropola : you don't need to recompile when just modifying the database. Then you just need to restart the worldserver.

I know, but usually I do a `git fetch+rebase` before making the PR to base it on latest master so I have to compile anyway. Also I enjoy seeing how fast it builds on my Ryzen 2700x with 8 cores. 😸

And thanks, I'm very happy to be here and enjoy working with you guys!

**Comment by FrancescoBorzi** [comment]
> Wait ... I do not need to run `db_assembler.sh`? I know TC's worldserver automaticyally imports the updates but I somehow remember I have to run the import manually on AC. Am I wrong?

TC worldserver does the update automatically, while on AC we handle this part using our bash scripts. The final result is the same

**Comment by necropola** [comment]
> TC worldserver does the update automatically, while on AC we handle this part using our bash scripts. The final result is the same

OK, then I'm doing it correctly. I got a bit confused when @Zoidwaffle said, I just needed to restart the worldserver executable when making/testing a PR with DB changes only.

**Comment by FrancescoBorzi** [comment]
> > TC worldserver does the update automatically, while on AC we handle this part using our bash scripts. The final result is the same
> 
> OK, then I'm doing it correctly. I got a bit confused when @Zoidwaffle said, I just needed to restart the worldserver executable when making/testing a PR with DB changes only.

he meant of course you need to import the DB changes **and** just restart the server, no need to recompile the core if only testing DB changes

**Comment by Zoidwaffle** [comment]
@necropola : could you modify the line with:

`- Closes AzerothCore https://github.com/azerothcore/azerothcore-wotlk/issues/4867`

to this:

`- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4867`

?

It should link this PR with the issue correctly so you can see it from the overview. Similar for the Chromie-link.

**Comment by necropola** [comment]
> @necropola : could you modify the line with:
> 
> `- Closes AzerothCore https://github.com/azerothcore/azerothcore-wotlk/issues/4867`
> 
> to this:
> 
> `- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4867`
> 
> ?
> 
> It should link this PR with the issue correctly so you can see it from the overview. Similar for the Chromie-link.

Interesting. It now automatically links the PR to the issues it closes. We should change the PR template to reflect this.

**Comment by necropola** [comment]
@Zoidwaffle I've edited my other PR, too. Now the github magic works. Thanks for the tip!

**Comment by Zoidwaffle** [comment]
It's already like that - not in the commit template, but in the PR template is should say:

`<!-- If the issue doesn't exist, describe it and how to reproduce it, please. If the issue already exists, just paste the link to the issue you close, like this: Closes https://github.com/azerothcore/azerothcore-wotlk/issues/967 -->`

So it's not super consistent and I also did it the "wrong" way until I noticed the difference.

@necropola : you're welcome!

**Pull request merged**
