### PR TITLE
fix(Scripts/Karazhan): Rework Attumen & Midnight

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  
-  

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/4858
- Closes https://github.com/chromiecraft/chromiecraft/issues/4857

## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
At long last, ready to be tested

**Comment by Nyeriah** [comment]
Considering this is the same script TC still uses up to this day, could someone give this a quick run to check if there are no issues? So we can merge it and get a move on with it

**Comment by Maelthyrr** [comment]
Everything work until the phase 3. If it's Attumen first, the encounter reset. If it's Midnight, the two boss become static static and doesn't fight.

**Comment by Nyeriah** [comment]
Had to rework it to function before treeston's combat rewrite, everything should be fine now

**Comment by Maelthyrr** [comment]
Doesn't work. Attumen or midnigh't doesn't pass in P3. And now, if the encounter is reset the boss disappears.

**Comment by Nyeriah** [comment]
> Doesn't work. Attumen or midnigh't doesn't pass in P3. And now, if the encounter is reset the boss disappears.

Something must be wrong with  your compile because it works for me...

image

**Comment by Maelthyrr** [comment]
Yes, sorry. Some things seem to have gone wrong with the git pull. Everything is fine.

**Review by Kitzunu — APPROVED** [review]

**Pull request merged**
