### PR TITLE
feat(build): initial development nix flake

### PR DESCRIPTION
**Pull request by mbwk**
## Changes Proposed:
This adds a nix flake to the project. This makes it easier for users of the nix package manager to build the project.

## Tests Performed:
I compiled successfully on x86_64-linux with:
```
mkdir build && cd build
cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
make -j $NIX_BUILD_CORES
```

## How to Test the Changes:
1. Have the nix package manager installed with flakes enabled.
2. Run `nix develop` in the project root containing flake.nix and wait for the devshell to appear.
3. From within the devshell, proceed with a CMake build (such as the example under "Tests Performed")

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
Very interesting, I hadn't heard of Nix before this.
I'll give it a try later today 🙃

**Comment by mbwk** [comment]
> Very interesting, I hadn't heard of Nix before this. I'll give it a try later today 🙃

Thank you @sudlud ! By the way, I recommend using https://github.com/DeterminateSystems/nix-installer as it will get you set up with flakes from the start.

**Comment by sudlud** [comment]
Thanks again for the PR!

I've finally found time to give this a test.

I've setup a fresh Debian install on WSL2 on Windows10.
I've followed the install steps in https://github.com/DeterminateSystems/nix-installer to get `nix` installed within debian.
(I've also assured that it's running with `systemd` so that `nix` is actaully available)
I've checked out this PR with Github Desktop (on Windows) and then switched to Debian working in the checked out directory.

```
user@ALIEN-LUDO:/mnt/c/Azerothcore$ git olog -1
* f9b991e52 (HEAD -> pr/18296, github-desktop-mbwk/feat/development-flake) feat(nix): initial development flake

user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore$ nix develop
[...]
(nix:nix-shell-env) user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore$ mkdir build && cd build
(nix:nix-shell-env) user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore/build$ cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/azeroth-server/ -DWITH_WARNINGS=1 -DTOOLS_BUILD=all -DSCRIPTS=static -DMODULES=static
[...]
(nix:nix-shell-env) user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore/build$ make -j $NIX_BUILD_CORES
```

running the worldserver
```
(nix:nix-shell-env) user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore/build$ mkdir -p /home/user/azeroth-server/etc
(nix:nix-shell-env) user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore/build$ cp ../src/server/apps/worldserver/worldserver.conf.dist /home/user/azeroth-server/etc/worldserver.conf
(nix:nix-shell-env) user@ALIEN-LUDO-wsl:/mnt/c/Azerothcore/build$ ./src/server/apps/worldserver

AzerothCore rev. f9b991e5260a 2024-02-09 22:36:30 +0000 (pr/18296 branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.
[...]
```

It tries to start but of course there's additional configuration steps required (?)

All in all I must say this is a pretty straight-forward way to get the server compiled.

But e.g. why is the path $HOME/azeroth-server/ chosen?

---

But right now this PR is alright, it works and provides the flake to get the servers compiled usingnix.

---

A next step after merging this PR would be to ask you to please add some initial documentation maybe to the wiki for this?
So that it's not "just there" but also known how to use it

**Review by sudlud — APPROVED** [review]

**Comment by sudlud** [comment]
Also i would appreciate steps to get everything up & running based on this build, but this could also go into the wiki maybe :)

**Comment by mbwk** [comment]
> Thanks again for the PR!
> 
> I've finally found time to give this a test.

Thank you so much! I know it was a big ask so I appreciate it you making the effort to test it (on WSL2 no less!!).

> It tries to start but of course there's additional configuration steps required (?)
> 
> All in all I must say this is a pretty straight-forward way to get the server compiled.

> But e.g. why is the path $HOME/azeroth-server/ chosen?

I lifted that example directly from the azerothcore Wiki page on building the servers. I intended for this to be a quick, minimally-working development environment for building the server, but in reality it's not yet suitable as a complete Nix derivation for end-users.

For that, build outputs need to be move to a specific `$out` directory during the build phase. I'm happy to pick this back up and make those changes first, and then ask for re-approval before this PR is merged.

> But right now this PR is alright, it works and provides the flake to get the servers compiled using nix.
> 
> A next step after merging this PR would be to ask you to please add some initial documentation maybe to the wiki for this? So that it's not "just there" but also known how to use it

Of course.

**Comment by sudlud** [comment]
Thanks for the feedback!

In my opinion, this could be merged to get a starting point and future PRs get it into an end-user-ready state maybe?

But it's actually not my call as I'm no maintainer - @Nyeriah / @Kitzunu maybe?

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
