### PR TITLE
Core refactor: Clean-up after FD

### PR DESCRIPTION
**Pull request by patou01**
## Changes Proposed:
-  remove _CanDetectFeignDeathOf(Unit) and adapt necessary code.
-  Added a check for FD in CanCreatureAttack() as these were basically always paired.
- that function was not doing what the name suggests, or at least not in a clear way. It's also supposed to not be used and should have been removed when https://github.com/azerothcore/azerothcore-wotlk/pull/5360 was introduced.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/8564

## Tests Performed:

- Built and tested the shaman elementals. Mobs still seem to aggro normally.
- 

## How to Test the Changes:

1. Test if behaviour of pets, shaman elementals or mobs overal changed. There should be no change.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by patou01** [comment]
@Nyeriah any input on how to test this? Is it a matter of eh... "it doesn't seem to do anything gamebreaking and the mobs still attack" ?

**Comment by FrancescoBorzi** [comment]
> @Nyeriah any input on how to test this? Is it a matter of eh... "it doesn't seem to do anything gamebreaking and the mobs still attack" ?

@patou01 well, you wrote this PR so you know better what can be potentially affected. Can you write a summary so people can double-check things in game?

**Comment by patou01** [comment]
> 
> @patou01 well, you wrote this PR so you know better what can be potentially affected. Can you write a summary so people can double-check things in game?

That's a bit the issue here... this is a left-over cleanup from others. In theory, all mobs and FD are affected. For some reason, some bosses were using `_canDetectFDOf()`, so I guess we want to check they still behave as they should (but bosses should never ignore FD afaik).

I assume running a test of FD should do the trick? So checking that pets disengage when the target FDs, checking that bosses and mobs disengage, checking that city guards **don't** disengage, and I think that should do the trick?

**Comment by Nyeriah** [comment]
As far as I know, the easiest example of creatures that ignores FD is indeed city guards, I'm not sure what else. Perhaps truesight auras do something about it too?

**Comment by patou01** [comment]
Note that we're in theory not changing anything, just unifying. So if anyone is detecting FD based on the removed function but not on CanIgnoreFD, then the issue is a missing db flag for that entry (though it would be nice to catch such cases before they go live)

**Comment by FrancescoBorzi** [comment]
what's the status of this PR?

**Comment by patou01** [comment]
Fixed merge conflicts.

What should be tested:
- pets stop chasing when target FDs
- pets don't start attacking someone that was in combat with them after they FD. So: hunter + pet engage on 2 targets (let's say another hunter, hunter B). If both hunter and pet B has attacked pet A, if hunter B FDs and pet B dies, pet A shouldn't engage on hunter B by himself.
- Fire and Earth elementals of shamans should work as before (engaging on spawn is where the difference might have happened)
- mobs shouldn't engage targets that are in FD. FD should still work normally.
- guards should still ignore FD
- Twin emperors should still reset on FD. Same for Hadronox, Lady Deathwhisper

**Comment by claudiodfc** [comment]
Tested.
- Player X has pet in defensive mode. Player Y has pet on passive mode. When Player Y hits player X, player x's pet starts attacking player Y. On Feign Death, pet resets combat.
- Pets don't start attacking someone that was in combat with them after they FD.
- Orc Hunter teleports into Stormwind and aggros a Guard. On Feign Death the guard resets. If close enough to the guard when they reset, they start attacking the player. They probably shouldn't even reset?
- Teleported to Icecrown near packs of adds while in gm mode and casted Feign Death. When gm mode was off, adds never aggroed while wandering around the player.
- Using Feign Death after aggroing Lady Deathwhisper makes her reset after 20s approximately. Hadronox and Emperors reset immediately.
- Elementals look fine. Started attacking while in combat.

The only possible problems are in how Lady Deathwhisper resets and maybe guards ignoring FD altogether. Overall, It's good to go 👍🏼

**Pull request merged**
