### PR TITLE
fix(DB/Fix Faction): Quest: Freedom to Ruul

### PR DESCRIPTION
**Pull request by Stifler82**
## Changes Proposed:
-  Accommodation of a fix I had made.
    Probably, I got confused and filled the whole `factiontemplate_dbc` table,
    **(but without the faction's modification that I had made before).**
    So this fix is used to fix the previous fix.

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/210
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4865
- Closes https://github.com/chromiecraft/chromiecraft/issues/159
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/4783
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/4786

## Tests Performed:
- Tested in game and working
- Tested on Windows 10 (64)
- **Video Test:** [Ruul Snowhoof](https://youtu.be/9S8eg9G6SkA)

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Mitradis** [comment]
@Stifler82 its PR, not issue

**Comment by Stifler82** [comment]
> @Stifler82 its PR, not issue (labels)

@Mitradis 
what do you mean?
explain yourself better, pls..

**Comment by Mitradis** [comment]
this lables not for RPs

**Comment by Stifler82** [comment]
> all this labels not for RPs (20-29 Confirmed Fix included Priority - High)

ok?

**Comment by Mitradis** [comment]
yes

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
- for PRs we use only content labels such as [20-29] and priority (if needed)
- for issues we use content labels AND projects together

**Comment by T1ti** [comment]
Sorry but I think editing Blizzard's DBCs is an absolutely terrible idea, you're also modifying all creatures that used this faction. (horde generic) And there is no reason for Blizzard's fiels to be wrong.

In myopinion the error is that he simply.. used the wrong faction.

I have a classic sniff and there he uses faction 33  which is "escortee" 
image

Tho I don't know if his faction gets changed when you accept the quest or if it's his permanant faction, but think twice before making such changes

**Comment by Stifler82** [comment]
> Sorry but I think editing Blizzard's DBCs(or overriding them in database) is an absolutely terrible idea, you're also modifying all creatures that used this faction. (_"horde generic"_) And there is no reason for Blizzard's files to be wrong.
> 
> In myopinion the error is that he simply.. used the wrong faction.
> 
> I have a classic sniff and there he uses faction 33 which is **"escortee"**
> image
> 
> Tho I don't know if his faction gets changed when you accept the quest or if it's his permanant faction, but think twice before making such changes

Are you serious?
Because if you're kidding, ok, "ahahahah you are fun".

**Comment by T1ti** [comment]
Just found out there was a previous commit and not just this, still hostile mask(enemy group) of the faction got changed to 10 from 0 compared to the DBC, I haven't dived deep into this issue but I wanna be sure we aren't making random changes to the blizzlike settings

**Comment by Stifler82** [comment]
> Just found out there was a previous commit and not just this, still hostile mask(enemy group) of the faction got changed to 10 from 0 compared to the DBC, I haven't dived deep into this issue but I wanna be sure we aren't making random changes to the blizzlike settings. Just explain if I'm saying some bullshit

Does the Blizz-Like Setting stipulate that that faction must be hostile to that other faction?
(The answer is: yes, because if this were not the case, the quest would not work).

The fix I made, put that faction hostile towards the faction of mobs related to the quest?
(The answer is always: yes. Because I have brought evidence with a video that it does it with my fix).

So, yes.. it, works.. it's, Blizz-Like..

**Comment by T1ti** [comment]
But this will make ALL NPCs that use this faction hostile to monsters etc, many civilians and neutral NPCs use this faction
I haven't dug into this issue too much but I really don't thing modifying a global blizzlike faction setting is good.
What you did is adding monsters and alliance as hostile to all NPCs that use the "horde generic" faction.

I'm not saying I am right, just trying to find possible flaws 
There is probably a better solution like changing his faction to an existing faction with the proper settings during the escort rather than editing blizzard's settings.

**Comment by Stifler82** [comment]
> But this will make ALL NPCs that use this faction hostile to monsters etc, many civilians and neutral NPCs use this faction
> I haven't dug into this issue too much but I really don't thing modifying a global blizzlike faction setting is good.
> What you did is adding monsters and alliance as hostile to all NPCs that use the "horde generic" faction.
> 
> I'm not saying I am right, just trying to find possible flaws and this could have a lot of consequences
> There is probably a better solution like changing his faction to an existing faction with the proper settings during the escort rather than editing blizzard's settings.
> Also a sniff from Classic found that this NPC uses the faction 66 (escortee) so there is probably something with this

@T1ti 
Horde Generic is always hostile to "creatures", so what would my fix change?
**Anything!** (except for the buggy quest which would be fixed).

**Comment by T1ti** [comment]
image
Why not just make him use factiontemplate ID 106 which is exactly the same but with enemygroup = 10, exactly what you just changed ?

**Comment by eTzmNcbkrng** [comment]
Can you slow his movement speed? Your video is sped up so it's hard to tell but it looks like he is running at the same (or nearly the same) speed as characters do.  
This is **much** faster than the Classic baseline we have available - https://www.youtube.com/watch?v=3Yp1Rax1ptA

**Comment by ratkosrb** [comment]
I see Ruul Snowhoof in 2 sniffs. Here is some data for him.

Position: 3347.35 -694.701 159.926 3.05433
Faction: 714
Level: 26
NPC Flags: 2
Unit Flags: 256
Walk Speed: 1.2
Run Speed: 1.14286
Bounding Radius: 0.9165
Combat Reach: 2.25
Attack Speed: 2000
Auras: 20514

It's possible his faction changes during the escort, I haven't done the quest.

**Comment by FrancescoBorzi** [comment]
> image
> Why not just make him use factiontemplate ID 106 which is exactly the same but with enemygroup = 10, exactly what you just changed ?
> I haven't experimented enough with factions to know what the difference makes in using enemy group if it's supposedly already hostile vs monsters, but if it changes something for him it might have consequences for other creatures that use this faction (99 mobs)

this is a valid point and a specific-solution should be preferred over changing the faction dbc.

I also agree about being careful when changing the dbc as it could, potentially, break other things. We can always revert if such things happen.

@Stifler82 would you please try the solution suggested by @T1ti ? if it works, it should be preferred to your current solution.

**Comment by FrancescoBorzi** [comment]
ok so I had a chat with @Stifler82 and he explained to me the issue a bit deeper, so if I understood correctly this could potentially fix more issues related to this faction.

still @T1ti had a good point about:

> And there is no reason for Blizzard's files to be wrong.

let's say this is 99% of the times true, but not necessarily always. Also, @Stifler82 confirmed that he has tested several other NPCs having this faction and they seem to keep working fine. I'd say this is good to go then, but we can of course revert the change if anything wrong is found later.

**Pull request merged**
