### PR TITLE
fix(sql): added end RP for Harlan Needs a Resupply Quest

### PR DESCRIPTION
**Pull request by brankkoo**
## Changes Proposed:

This PR proposes changes to:

-Before this commit, you turned in Harlan Needs a resupply quest and there was no RP at the end 

## Issues Addressed:

-Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16299 

## SOURCE:

The changes have been validated through:
-Ported fix from https://github.com/TrinityCore/TrinityCore/commit/02d22d04c1dcf7a90c127e4996c9b13f7ebc3f44

## How to Test the Changes:

1. .go c id 1428, .quest add 333
2.Turn in the quest.

### CO-AUTHOR(S)
-author of the original commit  on Trinity core is https://github.com/SnapperRy

### CODE REVIEW

**Comment by sudlud** [comment]
Thanks for the PR!

There's a new line missing at the end of the sql file (it shows a red circle), can you please add this?

**Comment by brankkoo** [comment]
Added new line

**Comment by Kitzunu** [comment]
If you are cherry-picking things from other projects or other authors you always need to credit the author appropriately. Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors

**Comment by brankkoo** [comment]
Credited the original author of the commit in the co-authors section of the commit template

**Comment by sudlud** [comment]
can you please add a commit / update one of the existing commits to include the original author of the cherry-pick as kitzunu requested?
github should then show you and the original author as authors of this PR.

**Comment by alecsci** [comment]
# Tested  :white_check_mark:

Commit-ID: 337135bf9e409d97628f6f8778d32433991058fc
Win11 + Docker-Setup
No modules

## Before the fix:
- After you complete the quest, no role-play event happens.

## After the fix
- NPC walks and emote as in this video https://www.youtube.com/watch?v=kxY3NrKMy7I

- Added some proof
WoWScrnShot_082024_004158
WoWScrnShot_082024_004243
WoWScrnShot_082024_004738

**Comment by sudlud** [comment]
Thanks for the update and thanks a lot for testing!

**Review by sudlud — APPROVED** [review]

**Pull request merged**
