### PR TITLE
fix(Scripts/BlackwingLair): Razorgore improvements

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  Script his evade modes after retail research and some other improvements
-  

## Issues Addressed:

- Closes 

## Tests Performed:

- Tested ingame
- 

## How to Test the Changes:

1. Pull razorgore
2. .damage him
3. notice he kills all mobs if he dies during p1

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Lynethris** [comment]
I got two issues : 

- First, the event start when the player use the orb and Grethok respawn.
- After, when you kill Razorgore during the P1 and P2, if the player is far from him, he don't die

**Comment by temperrr** [comment]
Getting lots of warnings when compiling:

/root/env/azerothcore-wotlk/src/server/game/AI/CoreAI/UnitAI.h:338:49: warning: unused parameter 'creature' [-Wunused-parameter]
    virtual void SummonMovementInform(Creature* creature, uint32 motionType, uint32 point) { }
                                                ^
/root/env/azerothcore-wotlk/src/server/game/AI/CoreAI/UnitAI.h:338:66: warning: unused parameter 'motionType' [-Wunused-parameter]
    virtual void SummonMovementInform(Creature* creature, uint32 motionType, uint32 point) { }
                                                                 ^
/root/env/azerothcore-wotlk/src/server/game/AI/CoreAI/UnitAI.h:338:85: warning: unused parameter 'point' [-Wunused-parameter]
    virtual void SummonMovementInform(Creature* creature, uint32 motionType, uint32 point) { }
                                                                                    ^

**Comment by Lynethris** [comment]
Strange I don't have this. But with hard test (not easy in solo), I have two issues :

- New issue: adds ignore the player on the orb, and target the nearest player (same thing for the boss if the control is lost/cancel/finish). Normally, they should target him.
- Same issue that the last time:  When you kill Razorgore during the P1 or P2, if a player is far from him, he don't die

**Comment by Nyeriah** [comment]
Please test and let me know if any issues are introduced. Other bugs will be fixed in another PR seeing how this one got quite bloated already

**Comment by Lynethris** [comment]
Okay, I've been testing this PR back and forth as much as I can. I will try to redone some tests  this night. @temperrr It should really be tested again with some players on the PTR because alone it's complicated to test this in solo. 

- [X] Boss reset correctly

- [ ] For explosion: It just seems that if the players stick to one of the two doors, they are spared from the explosion (see picture).  I'm not dev but I don't think that it's a issue with the PR. 
- [ ] Sometime time, some adds are not kill by the explosion but they despawn during the reset (so minor bug)
- [ ] Always problems with threat but maybe fix this in another PR

Images :

WoWScrnShot_032222_151950

WoWScrnShot_032222_152126

**Comment by Lynethris** [comment]
@Nyeriah I have find the problem with explosion. If a player is hide by a object, he is not hit by the explosion. It's the same mechanic as fireball during the P3.

**Comment by Nyeriah** [comment]
Thanks for testing @Lynethris , from what you described, yes, I suspected that was the case

**Review by acidmanifesto — APPROVED** [review]

**Comment by temperrr** [comment]
https://github.com/chromiecraft/chromiecraft/issues/3208

**Comment by temperrr** [comment]
https://github.com/azerothcore/azerothcore-wotlk/issues/10964

**Pull request merged**
