### PR TITLE
fix(DB): Override Spell Bonus Coefficients (Workaround)

### PR DESCRIPTION
**Pull request by ZhengPeiRu21**
## Changes Proposed:
-  Restore spell_bonus_data prior to https://github.com/azerothcore/azerothcore-wotlk/pull/12562
-  Keeps the code changes so that we are able to continue to work on fix individual spells, but allows them to scale properly until proper fixes are implemented
- Also fixes lower rank spells by applying the correct coefficients extracted from the DBC where possible

## Issues Addressed:

- Does not properly solve any issues, but is workaround for https://github.com/azerothcore/azerothcore-wotlk/issues/13102
- And https://github.com/azerothcore/azerothcore-wotlk/issues/13056

## Tests Performed:

- SQL runs without errors
- Not tested in game, but should have same behavior as before

## How to Test the Changes:

1. Run SQL update
2. Test spells from linked issues (like Warlock Immolate) to see if spell power scaling is working

## Known Issues and TODO List:

- We will still want to implement proper workarounds for each spell affected by this and remove them from the DB as we can

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
This'll fix Immolate, along with Conflagrate.
Frostbolt rank 1 still does 22 damage with 121 SP, which seems correct.

**Comment by Gultask** [comment]
Will also fix Judgement dealing only 1 damage.

**Review by Nefertumm — APPROVED** [review]

**Comment by Ovahlord** [comment]
I'm dying a little bit on the inside right now. Like did you really just undo everything because none of you were able to write a simple proc spell script to handle the DoT effect properly? Same applies for Judgement. The formulas are in the tooltip for that spell.

**Comment by heyitsbench** [comment]
> Like did you really just undo everything because none of you were able to write a simple proc spell script to handle the DoT effect properly?

This is, as stated in the title of the PR, an interim workaround while that legitimate fix remains to be made. Gutting it and not touching it until the proper solution could have been done, but a temporary workaround is almost definitely preferable when considering something like ChromieCraft relying on things working close enough for now.

**Comment by 55Honey** [comment]
> I'm dying a little bit on the inside right now. Like did you really just undo everything because none of you were able to write a simple proc spell script to handle the DoT effect properly? Same applies for Judgement. The formulas are in the tooltip for that spell.

@Ovahlord 
If you don't have any productive input and/or prefer to act passive-aggressive / subtle insult anyone around AC, feel free to leave and do not come back.

Consider this a final warning related to multiple such comments in former PRs/issues. I'm pointing to our [Code of Conduct](https://github.com/azerothcore/azerothcore-wotlk/discussions/4022) here. And everyone who wishes to participate in the Azerothcore organization and its associates is expected to follow it.

**Comment by heyitsbench** [comment]
> If you don't have any productive input and/or prefer to act passive-aggressive / subtle insult anyone around AC, feel free to leave and do not come back.

While I disagree with Ovahlord's wording here, they have tried to provide productive input related to this issue in the past. I also see the only possibly insulting thing in the comment as being due to a misunderstanding of the issue this PR was addressing.

**Comment by Nyeriah** [comment]
Nothing justifies insults, misunderstandings or not. The previous offenses weren't misunderstandings either I suppose

**Comment by heyitsbench** [comment]
I see laughing at someone's genuine criticism more insulting than anything Ovahlord said.

**Comment by Nyeriah** [comment]
> I see laughing at someone's genuine criticism more insulting than anything Ovahlord said.

I beg your pardon? What exactly are you referring to?

**Comment by heyitsbench** [comment]
> I beg your pardon? What exactly are you referring to?

image

**Comment by Nyeriah** [comment]
You're of course entitled to your opinion but barging in here and telling someone to stop "hacking shit" is not what I consider "genuine criticism" and it's not the kind of treatment I wish our contributors to have. We aren't in need of this kind of help.

I can't see how my reaction to it is in any way more insulting than what the person posting it said. It just strikes me as odd that yet again the same person walks in here and comments something in the same rude manner as previously.

**Comment by malcrom** [comment]
It is genuine criticism if you are hacking stuff.

**Comment by malcrom** [comment]
Oh and Honey can go fuck herself

**Comment by Nefertumm** [comment]
We won't tolerate this kind of behavior, learn how to communicate with human beings.
Malcrom is now banned from AC.

**Pull request merged**
