### PR TITLE
fix(Core): cs_modify crash fix

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Added a check and used atoi and atof

## Issues Addressed:

- Closes a crash not reported

## Tests Performed:

- tested on windows 10

## How to Test the Changes:

1. .modify mount a b c e de t e
2. .modify mount 3 4

## Known Issues and TODO List:

None

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Winfidonarleyan** [comment]
I think need convert this to new system `ChatCommand`

**Comment by claudiodfc** [comment]
Something worth looking into in the future, this is a patch fix to prevent it to blow up the PTR.

**Comment by temperrr** [comment]
It no longer crashes, but I can't seem to mount anything with the command anymore.

**Comment by temperrr** [comment]
All good

**Comment by Nyeriah** [comment]
@Winfidonarleyan I'll merge this to fix the crash as a temporary solution until we find the time to convert this file to the new model

**Review by Nyeriah — APPROVED** [review]

**Comment by Winfidonarleyan** [comment]
> @Winfidonarleyan I'll merge this to fix the crash as a temporary solution until we find the time to convert this file to the new model

okay

**Pull request merged**
