### PR TITLE
refactor(Core): Rename ...Manager to ...Mgr

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
- title  

## Issues Addressed:

- Closes 

## Tests Performed:

- build

## How to Test the Changes:

1. Build

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
but... why? :D

**Comment by Kitzunu** [comment]
Because all other "Managers" in the source are called Mgr

**Comment by FrancescoBorzi** [comment]
> Because all other "Managers" in the source are called Mgr

aaah **consistency**, I like it! You gotta fix the modules too though :D

**Comment by Kitzunu** [comment]
fuck modules, I hate them with all of my heart ❤️

**Comment by Kitzunu** [comment]
I will fix them soon(tm)

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/mod-anticheat/pull/38
https://github.com/azerothcore/mod-autobalance/pull/90

**Comment by FrancescoBorzi** [comment]
@Kitzunu conflicts

**Comment by Kitzunu** [comment]
review pls

**Review by Helias — APPROVED** [review]

**Comment by Kitzunu** [comment]
https://github.com/ElunaLuaEngine/Eluna/pull/384

**Pull request merged**
