### PR TITLE
fix(Scripts/Spells): Convert some Druid spells to SpellScript

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Convert some spells to SpellScripts

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/16403

## Tests Performed:

- Tested in-game

## How to Test the Changes:

Druid

1. .learn 33763
2. .add 27886
3. .add 40711
4. Test Lifebloom with the Idols

DK

1. Learn Impurity talent in Unholy
2. Use ability, see the damge increases with more impurity learned

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by elthehablo** [comment]
Will test this tonight

**Comment by elthehablo** [comment]
- with rank 1 lifebloom I get an increase from 32 to 38 with the 68 trinket and to 49 with the 80 one
- nourish also works

DK with starter gear starter damage from death coil on random 63 beast mob:
- 0/0: 391
- 1/5: 398
- 2/5: 404
- 3/5: 411
- 4/5: 417
- 5/5: 424

**Comment by Kitzunu** [comment]
Noticed an issue with the dk script

**Comment by elthehablo** [comment]
> Noticed an issue with the dk script

what did you notice?

**Comment by Kitzunu** [comment]
That it doesnt even load x))

**Comment by Kitzunu** [comment]
Removing DK stuff until I figure it out, so we can merge this to fix the issue

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
