### PR TITLE
feat(Core/Scripting): Implement `OnBeforeCreatureSelectLevel()` hook

### PR DESCRIPTION
**Pull request by kjack9**
## Changes Proposed:
This PR proposes changes to:
-  [X] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [ ] Database (SAI, creatures, etc).

Adds the `OnBeforeCreatureSelectLevel()` hook into the `Creature::SelectLevel` function. This hook allows a module to examine and potentially change the level of a creature just before it has its level set and stats generated.

This hook allows me to avoid the "Level Up" animation that happens when entering an instance with AutoBalance or summoning a new creature that is scaled, since the level decision is made before the creature exists in the world.

This PR is in support of new features coming Very Soon™ to the [AutoBalance module](https://github.com/azerothcore/mod-autobalance).

## SOURCE:

The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [ ] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [ ] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [ ] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. Create a simple module that implements the hook
2. Change the "level" variable to any level value
3. Observe that all creatures have that value

Here is example logging output from an unreleased build of AutoBalance that illustrates the general flow:

```
AutoBalance_AllCreatureScript::OnBeforeCreatureSelectLevel: Bazzalan (16) | GUID Full: 0xf130002cff000008 Type: Creature Entry: 11519  Low: 8
AutoBalance_AllCreatureScript::OnBeforeCreatureSelectLevel: Bazzalan (16) is in map Ragefire Chasm (389-3, 5-player Normal)
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Config time for Bazzalan (16) updated to (1696060065241351).
AutoBalance_AllCreatureScript::ModifyCreatureAttributes: Creature Bazzalan (16) scaled to level (61) via dynamic scaling.
AutoBalance_AllCreatureScript::OnBeforeCreatureSelectLevel: Bazzalan (16) is set to level 61.
AutoBalance_AllCreatureScript::OnCreatureAddWorld: Bazzalan (61) added to map Ragefire Chasm (389-3, 5-player Normal)
```

## Known Issues and TODO List:

None.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by kjack9** [comment]
I am doing some testing to see if this is really needed. Please hold.

**Comment by kjack9** [comment]
Yes, it allows me to change the level of an incoming creature before it gets added to the world. Also lets me rely on the Creature.cpp stat generation instead of having to do it myself. I think still needed.

**Comment by Nyeriah** [comment]
The submodules being added in this PR dont look correct

**Comment by kjack9** [comment]
> The submodules being added in this PR dont look correct
GARGH, I was sure I kept that out this time. I will fix it.

**Review by Nyeriah — APPROVED** [review]

**Comment by kjack9** [comment]
Fixed! Something I'm doing in VSCode is staging files I don't intend to. I will figure out what's happening.

**Pull request merged**
