### PR TITLE
fix(DB/SAI): Fix Andorgos teleports in AQ40

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  Implement Andorogos gossip
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/12910

## Tests Performed:

- tested ingame
- 

## How to Test the Changes:

1. .instance setbossstate 7 3
2. instance setbossstate 8 3
3. check if gossips work/teleports
4.
5.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
- [ ] Killing the Twin Emperors manually didn't work. But I suspect that could be a problem with the boss script and the rewrite could fix that :?
- [ ] Using `.instance setbossstate 7 3` resulted in no text other than the standard "Greetings, player" and the gossip option didn't teleport me.

image

The Final Chamber teleport worked perfectly.

**Comment by Nyeriah** [comment]
Yeah, sorry, I forgot a query.
Yes, manually killing them won't work before Nefertum's rewrite, because they don't use boss states atm.

**Comment by Gultask** [comment]
Gossip text shows now 👍 
But I still can't teleport to Twins Chamber. Worldserver gives error: 
`SmartScript::ProcessAction: Entry 15502 SourceType 0, Event 0, Link Event 1 not found or invalid, skipped.`
Removing the '6644' from the SAI id 1 worked for me.

**Comment by Nyeriah** [comment]
Oh yeah I also forgot to push this... sorry :)

**Comment by Gultask** [comment]
Works great now ❤️

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
