### PR TITLE
fix(DB/Item): Change races for Fluorescent Green Mechanostrider

### PR DESCRIPTION
**Pull request by Alethrion**
## Changes Proposed:
This PR proposes changes to:
-  [ ] Core (units, players, creatures, game systems).
-  [ ] Scripts (bosses, spell scripts, creature scripts).
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:
- Closes https://github.com/chromiecraft/chromiecraft/issues/6390

## SOURCE:
The changes have been validated through:
- [ ] Live research (checked on live servers, e.g Classic WotLK, Retail, etc.)
- [ ] Sniffs (remember to share them with the open source community!)
- [X] Video evidence, knowledge databases or other public sources (e.g forums, Wowhead, etc.)
[Wowpedia patch 3.0.8 page](https://wowpedia.fandom.com/wiki/Patch_3.0.8), [Wowpedia version history for the mount adding new races March 16th, 2009](https://wowpedia.fandom.com/wiki/Fluorescent_Green_Mechanostrider?oldid=1808234)
- [ ] The changes promoted by this pull request come partially or entirely from another project (cherry-pick). **Cherry-picks must be committed using the proper --author tag in order to be accepted, thus crediting the original authors, unless otherwise unable to be found**

## Tests Performed:
This PR has been:
- [ ] Tested in-game by the author.
- [ ] Tested in-game by other community members/someone else other than the author/has been live on production servers.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:
- [X] This pull request can be tested by following the reproduction steps provided in the linked issue
- [X] This pull request requires further testing. Provide steps to test your changes. If it requires any specific setup e.g multiple players please specify it as well.

1. .additem (playername) 13325
2. inspect item for alliance races

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by sudlud** [comment]
https://www.azerothcore.org/wiki/sql-standards

Please update the PR accordingly, SQL changes should be in a seperatr SQL file e.g. with an UPDATE query to change the desired column value only.

**Comment by Kitzunu** [comment]
Also item_template is sniffed.

**Comment by heyitsbench** [comment]
> Also item_template is sniffed.

Changes have been made to it in the past.

**Comment by Kitzunu** [comment]
So invalid?

**Comment by heyitsbench** [comment]
> So invalid?

I don't think so, I am the one that opened the linked issue after all.

**Comment by Alethrion** [comment]
PR adjusted to fit accepted format. It's very possible Fluorescent Green Mechanostrider was missed during sniffing as it is an unimplemented mount.

**Review by elthehablo — APPROVED** [review]

**Pull request merged**
