### PR TITLE
Fix(Script/SmartAI): Sergeant Bly

### LINKED ISSUE #6423: Zul'Farrak Stairs Event Phased Poorly
**CURRENT BEHAVIOUR:**

WoWScrnShot_061821_203813

The first wave spawns and stands still until you pull them. Then after they die, an amount of time is waited, and the second wave spawns and stands still until you pull them. We stood around for like 45 seconds between phase 1 and 2 with nothing to do. 

**EXPECTED BLIZZLIKE BEHAVIOUR:**

https://www.youtube.com/watch?v=mtBuWdd2EHk

They should charged the stairs/pyramid and it should be super cool. No delays, no phasing issues, no weird standing still.

https://classic.wowhead.com/guides/zulfarrak-classic-dungeon-strategy

**SOURCE:**

**STEPS TO REPRODUCE THE PROBLEM:**

1. Play the Zul'farrak Stairs Event
2. Compare to videos
3. 

**EXTRA NOTES:**

**AC HASH/COMMIT:**

AzerothCore rev. 34da0cda5195 2021-06-15 12:02:03 

**OPERATING SYSTEM:**

**MODULES:**

**CUSTOMIZATIONS:**

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99328308-zul-farrak-stairs-event-phased-poorly?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #6699: Zul Farrak Stairs event bugs frequently
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1071

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [X] enUS
- [ ] other (specify)

##### FACTION

- [X] Alliance
- [X] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [X] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

It's not every time, but on occasion the NPC group will get to the bottom of the stairs and stop. 

##### EXPECTED BLIZZLIKE BEHAVIOUR:

They should walk over to the dried up fountain and have chat options -The goblin being asked to blow up the door, and starting gruop combat by talking to Bly.

##### STEPS TO REPRODUCE THE PROBLEM:

1. .tele Zulfarrak
2. Do the stairs event, Some people say pulling the boss before the NPC's at completely at the bottom triggers it
3. Repeat if necessary 

##### EXTRA NOTES:

https://youtu.be/ZmnmUIoe9f0

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

### LINKED ISSUE #6700: Sergent Bly in Zul Farrak has double chat options
Original Chromiecraft report https://github.com/chromiecraft/chromiecraft/issues/1069

#### WHAT CLIENT DO YOU PLAY ON?

- [ ] enGB
- [x] enUS
- [ ] other (specify)

##### FACTION

- [x] Alliance
- [x] Horde

##### CONTENT PHASE:

- [ ] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [x] 40-49
- [ ] 50-59

##### CURRENT BEHAVIOUR:

After rescuing Sergeant Bly from and clearing the mobs, when talking to Sergeant Bly to start his encounter he has two options.
SeargeantBly

##### EXPECTED BLIZZLIKE BEHAVIOUR:

There should only be 1 option when talking to him

##### SOURCE:

https://blizzardwatch.com/gallery/zulfarrak?slide_pos=9

##### STEPS TO REPRODUCE THE PROBLEM:

1. GO to Zul Farrak and do the dungeons up to the point where you have to fight Sergeant Bly
2. Talk to him and notice he has two conversation options

##### EXTRA NOTES:

Type here.

##### AC HASH/COMMIT:

https://github.com/chromiecraft/azerothcore-wotlk/commit/cecbd604d3f57312165cc53f8ed40feae51ee45f

##### OPERATING SYSTEM:

Ubuntu 20.04

##### MODULES:

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

##### OTHER CUSTOMIZATIONS:

None.

##### SERVER:

ChromieCraft

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/99646234-sergent-bly-in-zul-farrak-has-double-chat-options?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by claudiodfc**
## Changes Proposed:
-  Removed Sergeant's double dialog and conditions for gossip and gossip options.
- Created a new condition for data set
- Changed Sergeant's script to mimic the vanilla event with more accuracy.
- Altered table for Waypoints to support waypoint grouping, created new action called Random Waypoint Group. This allows to force the Trolls up the pyramid randomising the two available paths from the sides, instead of attacking the Sergeant. Otherwise, they would be running up the pyramid from 9s to 90s based on a random update timer, which can prove quite difficult to clear.

## Issues Addressed:

- Closes #6699 
- Closes #6423 
- Closes #6700 

## Tests Performed:

- Tested on Windows 10

### Test case 1
1. `.cheat god`
2. `.go c id 7274`
3. `.dmg 10000`
4. Loot key
5. Open any cage
6. Watch the event take place. (Use `.dmg 10000` to kill units that climb the pyramid)
7. The _Sandury Trolls_ must take a path from the sides of the pyramid. It's a randomized path either left or right.
8. _Sanfury Slaves and others_ spawn at the near top of the pyramid constantly to fight the Sergeant's group.
9. When the bosses spawn at the bottom, the group starts to climb down the stairs.
10. When the fight is over, Sergeant Bly and his group stay at the bottom in front of the fireplace and his gossip option becomes available, triggering the Sergeant's Bly fight.

## Known Issues and TODO List:

- [x] Waypoints were not being loaded fully for each creature
- [ ] Write test cases
- [ ] Guarantee that no waypoints were broken during this change

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
I just want to point out that in the end I'd prefer to have changes that affect how SmartAI works from the core in a separate PR from one that is fixing another issue with SmartAI in DB.

That way it is easier to document what changes has been done to the overall behavior of SAI. But feel free to test them together and get the build going =)

**Comment by claudiodfc** [comment]
Are you sure? You won't be able to test these changes without the SQL file because the script revolves around the core changes, so you're gonna merge something you're not certain that works 😄

**Comment by Kitzunu** [comment]
Switching out core script to sai script is okay in the same PR, but not changing how for example an Action works and also applying another creature fix in the same pr.

In that case I want the PR of changing SmartAI core mechanics to be merged first

**Comment by LukasVolgger** [comment]
So what's the status of this?

**Comment by FrancescoBorzi** [comment]
> So what's the status of this?

@claudiodfc is not answering for a while, I hope he will be back soon

**Comment by UltraNix** [comment]
Superseded by #7855

**Pull request closed without merging**
