### PR TITLE
fix(Core/Spell): Detect Undead

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
-  Change the spell to cost nothing

It is due to the spell having
```
Power POWER_HAPPINESS, Cost 11460 + 8 Per Second
```
and this power no class has.

## Tests Performed:
- Builds
- Tested in-game

## How to Test the Changes:

1. .add 9154
2. use elixir and see that the aura stays

## Known Issues and TODO List:

- [ ]
- [ ] 

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
missing `How to Test the Changes` instructions

**Comment by Kitzunu** [comment]
This is what happens when you get stressed out by friends to play League xD

**Comment by pklloveyou** [comment]
Tested The aura did not disappear

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by BarbzYHOOL** [comment]
i confirm bug before the PR, and you guys confirmed it works after PR

**Pull request merged**
