### PR TITLE
Fix(Core/Achievement): Throw food

### LINKED ISSUE #8835: Achievement "FOOD FIGHT!" gets wrong player
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Throw of food incorrectly add achievement ["FOOD FIGHT!"](https://wowgaming.altervista.org/aowow/?achievement=3579) to target.

### Expected Blizzlike Behaviour

Achievement should get players who is throwing food.

### Source

Wowwiki ["FOOD FIGHT!"](https://wowwiki-archive.fandom.com/wiki/%22FOOD_FIGHT!%22)
>Sit at a Bountiful Table, target another player (in another chair at the table), and use the "pass food" option until the food bounces of the target's head.

Wowhead ["FOOD FIGHT!"](https://wowwiki-archive.fandom.com/wiki/%22FOOD_FIGHT!%22)
> By 130901 on 2009/11/22 (Patch 3.2.2) 
Not random, when you pass the food the person (or rather the chair, since they count as vehicles) get a buff with a count of 5, allowing that person (or the one after them) to eat that dish 5 times. If you pass food to someone who already have a full stack of 5, the food will bounce. This is noticable if you have an addon that shows the buffs that your vehicle has. In short, pass the food twice, as long as the person in the seat didn't eat any of that dish between the first and second click you will get the 

[Youtube1](https://youtu.be/OHg2DpL5Up0?t=18)
[Youtube2](https://youtu.be/mDi33abkHtw?t=54)

### Steps to reproduce the problem

.event start 26
.go c 240526 - NPC in durotar
sit to a chair
pass food to chair

### Extra Notes

Also you have to able throwing food to Players, but i guess there is need more investigation and different report.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/420ca2e2b57216b90f93e2deb870946b420a72df

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Change the condition for the achievement, and also give the achievement to the caster and not the target.
-  According to Wowhead comments, you can get the achievement if the chair has 5 stacks of the food you're throwing. So you'll get the achievement once you throw enough food hehe

## Issues Addressed:

- Closes #8835 

## Tests Performed:

- Built and tested in-game.

## How to Test the Changes:

1. Check the issue for details.

## Known Issues and TODO List:

- [ ]  It is unclear if we should take a player or the player's chair to do the stack calculations, and also, if we can throw food to a player.

### CODE REVIEW

**Comment by Nefertumm** [comment]
@Shineslippers can you test this? ty

**Review by Nyeriah — APPROVED** [review]

**Comment by Shineslippers** [comment]
Tested: Change the condition for the achievement, and also give the achievement to the caster and not the target.

Right now **_noone_** gets achivement:

https://user-images.githubusercontent.com/85256266/141064999-f5b10d07-e8db-4f2f-a339-c12c81a1ad1f.mp4

**Comment by Nefertumm** [comment]
I changed the code, so it only gives you the achievement if the chair has 5 stack of the food you're throwing, according with the comments of wowhead on how it was supposed to work.

**Comment by Shineslippers** [comment]
MB, i'm sorry. Working.

image

**Pull request merged**
