### PR TITLE
Update AuthHandler.cpp

### PR DESCRIPTION
**Pull request by talefish**
## Changes Proposed:
-  Remove the hint box in the top left corner of the role selection interface.
-  

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
测试有效，老乡啊，太原哪里的。

**Comment by Nyeriah** [comment]
> 测试有效，老乡啊，太原哪里的。

cc @acidmanifesto

**Comment by acidmanifesto** [comment]
> > 测试有效，老乡啊，太原哪里的。
> 
> cc @acidmanifesto 

The test is valid, in the hometown, where in Taiyuan.

**Comment by pklloveyou** [comment]
Tested,
image

**Comment by Kitzunu** [comment]
Send a screen shot before the pr

**Comment by talefish** [comment]
> 在 pr 之前发送屏幕截图

WoWScrnShot_022323_154436

**Comment by acidmanifesto** [comment]
This appears to be chinese client specific. For those not aware of whats going on. There is premium sub expiration warning that shows on the clients with chinese locales. At the character select screen.

This actually breaks it by using a nonexsistent bit in this place, and therefore removes the message.

**Review by bgcfb — APPROVED** [review]

**Comment by pklloveyou** [comment]
Tested

**Comment by TimekillerTK** [comment]
Tested with the `3.3.5a.12340 zhCN` client.

Before:
image

After:
image

**Comment by TimekillerTK** [comment]
By request, also tested with the `3.3.5a.12340 zhTW` client.

Before:
image

After:
image

**Comment by Kitzunu** [comment]
Will close this. I dont think we want to manipulate opcodes to nonexisting bits

**Comment by Aiaiioi** [comment]
测试有效，之前记得飘过一眼，每太注意，事后先更改的时候咋也找不见了。还是discord好心人帮忙找到的，感谢！

**Pull request closed without merging**
