### PR TITLE
refactor(Core): apply clang-tidy modernize-pass-by-value

### PR DESCRIPTION
**Pull request by FrancescoBorzi**
- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-pass-by-value`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html

### How to test the changes

This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:

- (Not mandatory but would be nice to build with `-DTOOLS=1` [extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data) and use the newly extracted data to run the server)
- Run the server
- Access the game and play around a bit
- All good so far? Then this should be good to go

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR- Part of https://github.com/azerothcore/azerothcore-wotlk/issues/3820
- Apply `clang-tidy` with `modernize-use-nullptr`
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html

### How to test the changes

This PR is only about refactoring, it is then not meant to change anything of the program behaviour.
To test this, it is sufficient to:

- Build with `-DTOOLS=1`
- [Extract the client files](https://www.azerothcore.org/wiki/Extract-Client-Data)
- Run the server
- Access the game
- All good so far? Then this should be good to go

## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by nicoaravena** [comment]
Hey! I have the following conflict when pulling this pr to latest master commit.
On file `src/common/Database/Transaction.h`:
imagen

What I see that the lines `~TransactionTask() override = default;` and `~TransactionTask() override { };` have a day of difference in the commit history. Being the first one the newest change.

Which of both should I use to test this PR? (The other 2 lines I asume tht the newest is the one)

**Comment by FrancescoBorzi** [comment]
@nicoaravena fixed, thank you! ready to be tested

**Comment by nicoaravena** [comment]
Core compilation ok.
Server running without issues
imagen

Game running awesome.
imagen

**Comment by FrancescoBorzi** [comment]
thanks @nicoaravena !

**Review by Si1ker — APPROVED** [review]

**Pull request merged**
