### PR TITLE
[WIP] Implementing core build with github actions

### PR DESCRIPTION
**Pull request by Yehonal**
This implements the CI using github actions instead of travis

work in progress

### CODE REVIEW

**Comment by Rochet2** [comment]
Are there some benefits expected from the change?

**Comment by Yehonal** [comment]
> Are there some benefits expected from the change?

* no timeouts
* faster
* no 3rd party dependency
* more configuration options

that's it for now, however, I'm still experimenting

**Comment by BarbzYHOOL** [comment]
will that mean updating all modules' .travis too? :'(

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL it's not mandatory

**Comment by Rochet2** [comment]
Other CI services get speed benefits from cache and prebuilt containers (preinstalled dependencies), but not sure you can use those on github actions. So the build would inevitably be slower on average, no? Atm latest build seems to take 17 min on travis and 32 min on github actions.

btw. a comment about clone depth.
On travis I have had some problems in situations where depth was 1 and multiple commits were pushed in short time. The CI jobs sit in queue and when started the clone would get only latest commit I assume. Then when the job is trying to checkout the actual commit to build it would fail.
Just something to think about.

**Comment by Yehonal** [comment]
It's an edge case but it's possibile. However, the last commit should be
always the one to compile, isn't it?

About speed, I'm sure there's something in github action too. It's taking
30 minutes because I'm compiling without PCH

**Comment by Helias** [comment]
Can we delete the branch **Yehonal-patch-2**, @Yehonal ?

**Comment by BarbzYHOOL** [comment]
means yes

**Pull request closed without merging**
