### PR TITLE
DB/Misc: Update some VoA scripts SAI, add waypoints

### PR DESCRIPTION
**Pull request by HoustonCore**
## CHANGES PROPOSED:
-  Updated the SAI of creatures and the timers "sniffs"
- Add waypoints from sniffs
- Fix amount of gold from Flame Warder in heroic

## TESTS PERFORMED:
- Build and test in game

## HOW TO TEST THE CHANGES:

- .tele VaO
- Go to instant 
- See move wayponts Mobs and go fight him and look cast spell. 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by FrancescoBorzi** [comment]
@HoustonCore same here, can you please add which creatures have been impacted by this change so testers can test it?

**Comment by HoustonCore** [comment]
> @HoustonCore same here, can you please add which creatures have been impacted by this change so testers can test it?

I get it, I'll add a description for testing a little later, I'm at work)

**Comment by HoustonCore** [comment]
@FrancescoBorzi done.

**Comment by Si1ker** [comment]
@HoustonCore What this does fix? What is the issue?
Or is this just an improvement without any previous issue around?

**Comment by HoustonCore** [comment]
@Si1ker This is an improvement and proper operation of mobs.

**Comment by Si1ker** [comment]
@HoustonCore  Even if its an improvement... could I get a more clear description of what it improve?

Like...

"Currenlty the NPC is crashin to a wall so I am adding this way point in order to avoid it..."
"The NPC X currently casts X which is wrong, it should be X"
"Happens this...  and I suggest that should happen this... "

If I want to improve something, I will give a comparison to answer the "why the pr?"
Yeah.. an improvement.. but for what? current paths are wrong? spell timers/type are wrong?

Its really difficult to make "improvements" on stuff like this.. because either is wrong or its blizzlike..

I have run VoA so many times... and I have not noticed something wrong.. adds are casting spells.. doing their way points.. etc

If you can give what I said above, I will be ready to test the PR and make some progress on it.
@Kitzunu  our quality control can check if is needed 🐱  !

**Comment by HoustonCore** [comment]
@Si1ker 
Do you know what sniff is? If Yes, please give me an answer to this.

You are a developer and even more so you open a PR in this core you can't see what is happening in the code?

What is not clear in the word update timers for using mobs spells? Right now, spell timers are close to Blizzard.

Or you can't figure out what gives you points of movement? This is difficult to understand and check whether mobs are moving before or after PR?

Or do you not trust sniff the only system the data taken from the current version of the Blizzard.

**Comment by Viste** [comment]
sorry but sniffs stronger then your 

> I have run VoA so many times... and I have not noticed something wrong.. adds are casting spells.. doing their way points.. etc

**Comment by FrancescoBorzi** [comment]
everyone is trying to help here, so let's not fight but collaborate instead

please less arguing, more coding/testing :)

@HoustonCore Silker was just asking for more details, nothing wrong with it.

@Si1ker can you please give this a try and let us know what your feedback is?

**Comment by HoustonCore** [comment]
@FrancescoBorzi What is more detailed?  And so everything is written and understandable, even links to YouTube are in the sql file.

**Comment by BarbzYHOOL** [comment]
First of all, thanks for this PR!  Really

Secondly, put the links in the description, not in the SQL please

Silker is right, the more explanation the better. And yes, theoretically, sniffs are better, unless of course blizzard changed stuff and then it might or might not be worse. Silker asks for more, probably because he wants things to be as blizzlike as possible.

Now please, don't start to flame another contributor, and even more so, a Staff member because he asked for more information. He is in the staff and that's for a good reason, without him and people like him nobody would be here, so let's be a little more respectful, thanks. And in top of that, anyone can make a mistake, even experienced contributors.

Silker, more info here I think https://github.com/TrinityCore/TrinityCore/pull/25419/files :D

**Review by Si1ker — APPROVED** [review]

**Comment by Delcidx** [comment]
Tested in game. 
- SAI and timers  working as suggested
- Amount of gold of [Flame Warder](https://www.wowhead.com/npc=35143/flame-warder#abilities;mode:n10) in hc mode working, based on changes applied
Gold tested

**Comment by Si1ker** [comment]
@Delcidx Thanks for testing! 🎉

**Pull request merged**
