### PR TITLE
DB/Creature: Shadowlord Deathwall

### PR DESCRIPTION
**Pull request by poszer**
Shadowlord Deathwall fix

##### CHANGES PROPOSED:

-  Added waypoint data
-  Updated to use Waypoint movement.
- Updated  InhabitType Controls where the creature can move and attack.:  4+1 (The creature walk on ground and fly).

###### ISSUES ADDRESSED:

Closes https://github.com/azerothcore/azerothcore-wotlk/issues/1392

##### TESTS PERFORMED:

The query is imported in DB without any errors. Tested in game without this Fix, The creature  is always on the ground ( Which is incorrect ).
Tested, including this fix : The creature is flying and using waypoint ( Correctly attacking targets, While flying, while on the ground. The quest for this creature [The Ata'mal Terrace](https://www.wowhead.com/quest=10707) can be done without problem - The creature drops required item . Here is video preview:  [Shadowlord Deathwall NPC - Video with this Fix](https://youtu.be/L6DxXT0u9_0)

##### HOW TO TEST THE CHANGES:

1. Simply  .go creature 77282 and check around, is the Shadowlord Deathwail flying or he's on the ground. (**PS. The correct is to fly around Ata'mal Terrace**)

##### KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

##### Target branch(es):

Master

### CODE REVIEW

**Comment by comix1988** [comment]
i tested this pr and the npc Shadowlord Deathwall flying in circle over the ata'mal terrace.
I also checked if the quest  "Ata'mal Terrace" work but i found an error, the event don't start.
i try to report some bug in this area:
1-to start the event you have to kill the 3 elite mobs ( https://wowgaming.altervista.org/aowow /?npc=22061 )that cast a spell as seen from the image

cast

(now they doesn't cast anything)

When you kill one of these mobs, waves of other mobs ( shadowmoon retainer https://wow.gamepedia.com/Shadowmoon_Retainer )- start to appear. I have spawned one of these mobs and only do melee attacks rather than ranged attacks.
Only at this point the npc Shadowlord Deathwail drops to the ground.

https://www.youtube.com/watch?v=8QAvDrW89iY link video at 1:34 minutes.



2- npc Shadowlord Deathwail only uses melee attacks instead of casting shadow attacks ( https://www.wowhead.com/npc=22006/shadowlord-deathwail#abilities)

3- npc shadowmoon darkweaver is looped standing - kneel  instead of just standing
https://youtu.be/eww-lHJrEZ4  link video
https://wowgaming.altervista.org/aowow/?npc=22081

sorry for my bad english
@poszer

**Comment by poszer** [comment]
> i tested this pr and the npc Shadowlord Deathwall flying in circle over the ata'mal terrace.
> I also checked if the quest "Ata'mal Terrace" work but i found an error, the event don't start.
> i try to report some bug in this area:
> 1-to start the event you have to kill the 3 elite mobs ( https://wowgaming.altervista.org/aowow /?npc=22061 )that cast a spell as seen from the image
> 
> cast
> 
> (now they doesn't cast anything)
> 
> When you kill one of these mobs, waves of other mobs ( shadowmoon retainer https://wow.gamepedia.com/Shadowmoon_Retainer )- start to appear. I have spawned one of these mobs and only do melee attacks rather than ranged attacks.
> Only at this point the npc Shadowlord Deathwail drops to the ground.
> 
> https://www.youtube.com/watch?v=8QAvDrW89iY link video at 1:34 minutes.
> 
> 
> 
> 2- npc Shadowlord Deathwail only uses melee attacks instead of casting shadow attacks ( https://www.wowhead.com/npc=22006/shadowlord-deathwail#abilities)
> 
> 3- npc shadowmoon darkweaver is looped standing - kneel instead of just standing
> https://youtu.be/eww-lHJrEZ4 link video
> https://wowgaming.altervista.org/aowow/?npc=22081
> 
> sorry for my bad english
> @poszer

This PR is to solve Flying of this creature, and waypoint, since it's mentioned in Issue. 

> ##### EXPECTED BLIZZLIKE BEHAVIOUR:
> Flying on top the part of karabor temple patrolling the area

Btw, Are you sure that  Shadowlord Deathwail only uses melee attacks instead of casting shadow attacks ? Bcoz i have tested this and Shadowlord casting these shadow spells as you can see in this video:
https://youtu.be/L6DxXT0u9_0

For other Issues, related to quest/ creatures in this area / event - I'll see what i can do

**Comment by comix1988** [comment]
@poszer 
if you want I can create a new issue for these bugs.I'll link you a npc movie that does not use spell shadow:
https://youtu.be/m07L4oLJQ8Y

**Comment by poszer** [comment]
> that does not use spell shadow:

Okay, join on our discord channel https://discord.gg/BVvVCB

**Comment by comix1988** [comment]
@poszer i'm Elbarto on your discord but i can't reply
cattura

**Comment by comix1988** [comment]
I tested the fix passed by poszer and:
1-  the mob in loops now work perfectly (you have also put the graphics of the cast .... spectacular .... you're so great!)
2- the waves of mobs are fine. (if this mob survive the event, after a short time they disappear)
3- it would be better if we increase the cast number of the green spell of the flying mob (if it is possible)
4 - last bug to fix: when the dragon descends he must remain on the ground. Now it takes the heart and returns to the air, and it is no longer possible to attack it

**Comment by FrancescoBorzi** [comment]
@comix1988 excellent feedback, thank you

**Comment by poszer** [comment]
**Info : Still working on this**

**Comment by poszer** [comment]
Closing this, will open complete fix in the new PR

**Pull request closed without merging**
