### PR TITLE
fix(DB/Spell): Link triggered Shattrath flask effects to flask aura and proper area.

### PR DESCRIPTION
**Pull request by heyitsbench**
## Changes Proposed:

This PR proposes changes to:
-  [X] Database (SAI, creatures, etc).

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/19786
- Likely closes https://github.com/azerothcore/azerothcore-wotlk/issues/16360
- Closes https://github.com/chromiecraft/chromiecraft/issues/7381
- Closes https://github.com/chromiecraft/chromiecraft/issues/6482

## Tests Performed:

This PR has been:
- [X] Tested in-game by the author.
- [X] This pull request requires further testing and may have edge cases to be tested.

## How to Test the Changes:

- [X] This pull request can be tested by following the reproduction steps provided in the linked issue.

## Known Issues and TODO List:

- [X] ~~This fix further breaks https://github.com/azerothcore/azerothcore-wotlk/issues/19786 as the effects will no longer be kept outside nor inside the instances.~~ This has mostly been resolved, but unfortunately when first consuming the flask in the open world, the flask's effects are maintained until your area is updated.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Rorschach91** [comment]
I've found this problem, but I don't know if it only is a graphic bug.

Bug 1: [Youtube](https://youtu.be/Qg16xDH6GeU)
Bug 2: [Youtube](https://youtu.be/Q5K7qtOHuPc)

**Comment by Rorschach91** [comment]
> Should be resolved, please test again when you are able.

Tested and no, it doesn't resolve the issue.

**Comment by heyitsbench** [comment]
> Tested and no, it doesn't resolve the issue.

Did you start from a clean world database on the second test?

**Comment by Rorschach91** [comment]
> Did you start from a clean world database on the second test?

Oh.....my bad, it works. It can be reviewed.

**Review by Helias — APPROVED** [review]

**Comment by kissingers** [comment]
A minor bug has been observed: after the server restarts, if you are inside the corresponding instance and use Shattrath for the first time, it does not take effect immediately. However, if you leave and re-enter the instance, or if you remove the buff and use another one, it will then work. Subsequently, no matter whether you login or out server, or consume it inside or outside the instance, everything works as expected.

Conclusion: After the server restarts, the first time inside the corresponding instance use this does not take effect.

**Comment by heyitsbench** [comment]
> if you are inside the corresponding instance and use Shattrath for the first time, it does not take effect immediately.

Should be resolved by https://github.com/azerothcore/azerothcore-wotlk/pull/20299 if you'd like to test. ❤️

**Pull request merged**
