### PR TITLE
Fix Realm Selection menu showing number of characters

### PR DESCRIPTION
**Pull request by r0m1ntik**
## Changes Proposed:
-  When deleting a character, removes 1 from the realmcharacters table.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/11990
- Closes https://github.com/chromiecraft/chromiecraft/issues/3566

## Tests Performed:

- Tested and work

Снимок экрана 2022-06-23 в 3 17 22
Снимок экрана 2022-06-23 в 3 17 37

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by r0m1ntik** [comment]
@Luckdemon can u test this ?

**Comment by acidmanifesto** [comment]
@azerothcore/testers

**Review by acidmanifesto — CHANGES_REQUESTED** [review]
Reports state does not work on cc ptr.

**Comment by Nyeriah** [comment]
A quick glance through the code leads me to think this query is being executed on the hard delete and not the soft delete, so the number only updates once the character is completely wiped from the database (can no longer be recovered through .char delete restore)

**Comment by acidmanifesto** [comment]
What is the status of this PR? Is it abandoned?

**Comment by r0m1ntik** [comment]
Do you need to clean with any removal ?

**Comment by acidmanifesto** [comment]
> Do you need to clean with any removal ?

At this time we are informed by testers this PR does not work at all. Is there any plan of action in following up with this PR?

**Comment by Kitzunu** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/14685

**Pull request closed without merging**
