### PR TITLE
fix(DB/Quest): A Dire Situation

### PR DESCRIPTION
**Pull request by Kitzunu**
## CHANGES PROPOSED:
-  Fix SAI
-  Remove useless dummy npc

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/2968

## TESTS PERFORMED:
- Works

## HOW TO TEST THE CHANGES:

Read the issue

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by TheWatchingI** [comment]
I imported the changes in acore_world via heidisql and this guide http://www.azerothcore.org/wiki/How-to-test-DB-only-changes

The result was that all quest mobs were gone. Apparently the wolfs don't spawn anymore.

**Comment by Kitzunu** [comment]
yea because I fucked up and deleted the wrong creature. Go me Q.Q

I will fix it and send you the SQL to get them back

**Comment by Kitzunu** [comment]
@TheWatchingI okay the SQL below will get you the wolfs back, sorry for that :D
Please re-test with the new PR Update
```sql
DELETE FROM `creature` WHERE `guid`=71502;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71502, 20058, 530, 0, 0, 1, 1, 0, 0, 1474.39, 6582.66, -10.0903, 5.21853, 300, 0, 0, 5914, 0, 0, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71503;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71503, 20058, 530, 0, 0, 1, 1, 0, 0, 1488.61, 6573.6, -10.2139, 0.092632, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71504;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71504, 20058, 530, 0, 0, 1, 1, 0, 0, 1413.18, 6552.67, 3.15884, 1.69983, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71505;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71505, 20058, 530, 0, 0, 1, 1, 0, 0, 1446.2, 6472.6, -10.2462, 0.855211, 300, 0, 0, 5914, 0, 0, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71506;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71506, 20058, 530, 0, 0, 1, 1, 0, 0, 1553.61, 6349.34, 3.256, 4.98197, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71507;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71507, 20058, 530, 0, 0, 1, 1, 0, 0, 1524.38, 6345.23, 2.11131, 0.602852, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71508;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71508, 20058, 530, 0, 0, 1, 1, 0, 0, 1629.32, 6346.95, -2.89058, 1.13948, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71509;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71509, 20058, 530, 0, 0, 1, 1, 0, 0, 1686.32, 6301.91, 0.65629, 2.63888, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71510;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71510, 20058, 530, 0, 0, 1, 1, 0, 0, 1733.34, 6270.93, 2.15996, 1.8675, 300, 0, 0, 5914, 0, 0, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71511;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71511, 20058, 530, 0, 0, 1, 1, 0, 0, 1645.34, 6466.5, -0.365726, 0.245413, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71512;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71512, 20058, 530, 0, 0, 1, 1, 0, 0, 1708.77, 6497.15, 1.80648, 4.43451, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71513;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71513, 20058, 530, 0, 0, 1, 1, 0, 0, 1812.23, 6481.29, 2.08525, 1.6769, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71514;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71514, 20058, 530, 0, 0, 1, 1, 0, 0, 1840.46, 6409.48, -10.2139, 0.361519, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature` WHERE `guid`=71515;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`) VALUES (71515, 20058, 530, 0, 0, 1, 1, 0, 0, 1981.4, 6379.49, -10.2139, 3.2634, 300, 5, 0, 5914, 0, 1, 0, 0, 0, '', 0);
DELETE FROM `creature_addon` WHERE `guid`=71502;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `isLarge`, `auras`) VALUES (71502, 0, 0, 3, 4097, 0, 0, NULL);
DELETE FROM `creature_addon` WHERE `guid`=71505;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `isLarge`, `auras`) VALUES (71505, 0, 0, 3, 4097, 0, 0, NULL);
DELETE FROM `creature_addon` WHERE `guid`=71510;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `isLarge`, `auras`) VALUES (71510, 0, 0, 3, 4097, 0, 0, NULL);
DELETE FROM `creature_addon` WHERE `guid`=71512;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `isLarge`, `auras`) VALUES (71512, 0, 0, 0, 4097, 0, 0, NULL);
DELETE FROM `creature_addon` WHERE `guid`=71513;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `isLarge`, `auras`) VALUES (71513, 0, 0, 0, 4097, 0, 0, NULL);

```

**Comment by TheWatchingI** [comment]
Happens to the best. Now everything works fine :)

The wolfs are back, shrunken wolfs stop attacking, one can't use the powder on the same mob multiple times and every usage only brings one point for the quest.

**Comment by Kitzunu** [comment]
Amazing, thank you!!

**Pull request merged**
