### PR TITLE
fix(Core/Spells): Reset melee swing timer on  cast rather than on fin…

### LINKED ISSUE #7216: [Westfall] Defias Pillager's melee swings come instantly after his fireball cast
### What client do you play on?

enGB

### Faction

- [X] Alliance
- [ ] Horde

### Content Phase:

- [ ] Generic
- [X] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

Original report: [Chromie issue#1320](https://github.com/chromiecraft/chromiecraft/issues/1320)

When the Defias Pillager finishes its cast it does a auto attack straight after.

### Expected Blizzlike Behaviour

there should be a delay before auto attack happens.

### Source

_No response_

### Steps to reproduce the problem

Just get in a fight with the Defias Pillager

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/3d4befd7043fbbceb32f7c2a6e0a4f9f638f8b0a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-CustomWorldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

Confirmed on local AC(15013d2).
The melee swing after his cast should take the attackspeed of his staff into account.

https://user-images.githubusercontent.com/68868567/127992742-034f236a-9c25-4760-86fb-2dd34e0382c5.mp4

### PR DESCRIPTION
**Pull request by UltraNix**
…ish.

Fixes #7216

 

## Issues Addressed:

- Closes #7216
- Closes https://github.com/chromiecraft/chromiecraft/issues/1320

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.go creature 44293`
After Fireball mob should delay the melee attack.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by T1ti** [comment]
you mean on cast finish ? I think the melee timer is supposed to be reset on cast finish.

**Review by acidmanifesto — APPROVED** [review]

**Comment by UltraNix** [comment]
Yes - I mean when the spell is casted.
In core - spell finish is when the spell already hit the target and is going to be deleted.
The problem here is with the "flying" spells - spells with speed, like Fireballs, frostbolt, etc. Meleee swing timer was reset when the spell hit the target, not when the spell has been casted.

**Comment by T1ti** [comment]
Good fix then, I can't believe it worked like that

**Comment by temperrr** [comment]
Tested, works as descriped.

Also notices that the issue with players and insta melee  after cast got resolved with this.

**Comment by pklloveyou** [comment]
tested

**Pull request merged**
