### PR TITLE
feat(DB/game_tele): Improve GM Teleports

### PR DESCRIPTION
**Pull request by LukasVolgger**
## CHANGES PROPOSED:
**This PR will add some important teleports which were missing and makes Gamemaster's life easier.**

From Classic - TBC you are able to teleport instantly to every Dungeons entrance - Example: 

- .tele 726 (RagefireChasm)
- .tele 106 (BlackTemple)

For WotLK you have to walk far... - Example:

- .tele 1393 (TheNexus) It's the only teleport for The Nexus, Oculus and The Eye

same here 

- .tele 1419 (TheFrozenHalls) only one teleport for The Forge of Souls, Pit of Saron and Halls of Reflection.

## ISSUES ADDRESSED:
- None

## TESTS PERFORMED:
- Applied SQL Script
- Tested every teleport ingame

## HOW TO TEST THE CHANGES:

**1. Apply SQL script**
**2. To test you need to have an GM Account (account set gmlevel "accname" 3 1)**
**3. Test all the following teleports with .tele ID / tele Name and enjoy:**

- 455 (AzjolNerub) (Updated location)
- 1435 (TheStockade)
- 1436 (AhnKahet)
- 1437 (TheCullingOfStratholme)
- 1438 (GundrakDungeon)
- 1439 (HallsOfLightning)
- 1440 (HallsOfStone)
- 1441 (HallsOfReflection)
- 1442 (PitOfSaron)
- 1443 (RubySanctum)
- 1444 (EyeOfEternity)
- 1445 (ForgeOfSouls)
- 1446 (TheNexusDungeon)
- 1447 (ObsidianSanctum)
- 1448 (Oculus)
- 1449 (TrialOfTheCrusader)
- 1450 (UlduarRaid)
- 1490 (CrystalsongForest)

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by Helias** [comment]
Good job, anyways, you could group everything in two simple sql query:
```SQL
DELETE FROM `game_tele` WHERE `id` IN (1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450);
INSERT INTO `game_tele` (`id`, `position_x`, `position_y`, `position_z`, `orientation`, `map`, `name`) VALUES
(1435, -8779.900391, 834.348816, 94.680130, 0.653013, 0, 'TheStockade'),
(1436, 3643.309082, 2036.508545, 1.787417, 4.339186, 571, 'AhnKahet'),
(1437, -8750.759766, -4442.196777, -199.259674, 4.376938, 1, 'TheCullingOfStratholme'),
(1438, 6952.303711, -4419.976074, 450.077667, 0.807518, 571, 'GundrakDungeon'),
(1439, 9182.918945, -1384.819336, 1110.209961, 5.577789, 571, 'HallsOfLightning'),
(1440, 8921.905273, -993.503479, 1039.410278, 1.552629, 571, 'HallsOfStone'),
(1441, 5630.444824, 1994.013184, 798.058777, 4.587561, 571, 'HallsOfReflection'),
(1442, 5598.744629, 2015.848999, 798.041748, 3.810007, 571, 'PitOfSaron'),
(1443, 3600.503174, 197.339737, -113.760269, 5.299053, 571, 'RubySanctum'),
(1444, 3859.444580, 6989.848145, 152.040604, 5.796354, 571, 'EyeOfEternity'),
(1445, 5666.252930, 2009.196899, 798.041443, 5.431836, 571, 'ForgeOfSouls'),
(1446, 3893.507568, 6985.326172, 69.487663, 6.278975, 571, 'TheNexusDungeon'),
(1447, 3457.111816, 262.394165, -113.819344, 3.282578, 571, 'ObsidianSanctum'),
(1448, 3879.958740, 6984.616211, 106.3120190, 3.196693, 571, 'Oculus'),
(1449, 8515.682617, 716.982239, 558.247864, 1.573150, 571, 'TrialOfTheCrusader'),
(1450, 9327.247070, -1114.638550, 1245.147095, 0.002312, 571, 'UlduarRaid');
```

plus the `UPDATE` one.

**Comment by LukasVolgger** [comment]
Thx @Helias ! Totally forgot about that because i did line by line >_<

**Review by Helias — APPROVED** [review]

**Comment by nicoaravena** [comment]
I just tested this PR.

Starting from AzjolNerub
imagen

And finishing with CrystalsongForest
imagen

**Comment by LukasVolgger** [comment]
Thx 4 testing it @nicoaravena ! Good work!

**Comment by FrancescoBorzi** [comment]
thanks @LukasVolgger and @nicoaravena for this!

**Pull request merged**
