### PR TITLE
Fix(core/script): UBRS Solakar / father flame 

### PR DESCRIPTION
**Pull request by patou01**
**Latest commit should be kind of okay, but still very "private server obvious".** 

## Changes Proposed:
-  Add script for solakar and Hatchers (too hard to make in SAI)
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/611

## Tests Performed:

- basic run through event
- 

## How to Test the Changes:

1. Pick up father flame from object in UBRS, verify event runs properly and resets correctly when needed.
2.
3.

## Known Issues and TODO List:

- [ ] Spawn times
- [ ] Spells for Hatchers? I believe they're supposed to cast stuff other than just slap around.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by patou01** [comment]
The eggs seem to be a bit of a mess. The database has this
image

It seems that deleting the bottom one doesn't influence the behaviour in game...

**Comment by temperrr** [comment]
Tested,

emotes work
resetting works
After killing drake, rend nowhere to be found
event doesnt reset anymore.
image

@Nyeriah

**Comment by patou01** [comment]
@temperrr I was very confused. My response was about to be "thanks for testing this WIP test, I'm unsure how I affected the Rend event, but good to know I'll look into it". Guess I will still make sure I won't break rend :D

**Comment by patou01** [comment]
Help needed:

- Number of waves and what kind of waves, should they be random, 1 of each mob, can they be the same?
- spell timers for the boss

**Comment by patou01** [comment]
@ultranix, remaining questions/remarks based on your review from a while ago:

- `me->GetMotionMaster()->MovePoint(0, me->GetVictim()->GetPosition());`, to me it makes no sense to define ZERO = 0 here, so just leaving it as is. Ideally I'd want to not use MovePoint() at all, but it seems the mob doesn't want to start moving if I just use some attack function after having called `StopMovingOnCurrentPos`.  Do you have an alternative?
- I replaced `SelectNearestTarget` with doZoneInCombat. We'll see how that goes once the other PR goes in.
- I believe the positions are *not* "magic numbers", they're just constants that I cannot define as constant. They're defined at the top like anybody would expect, I think they're okay.

Other than that, conflicts removed now, the CI build should be okay.

**Comment by Nefertumm** [comment]
It's looking good now! Sorry for the no-response, I didn't get the github notification :(

**Review by Nefertumm — APPROVED** [review]

**Comment by temperrr** [comment]
Tested;

works as expected and close enough to blizzlike as we can from videos.

**Pull request merged**
