### PR TITLE
Fix(Core/Spells): Shadowflame should not be interruptable

### PR DESCRIPTION
**Pull request by Nefertumm**
## Changes Proposed:
-  Remove interrupt flag.

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/10423

## SOURCE:

See issue

## Tests Performed:

- Tested in-game with rogue kick.

## How to Test the Changes:

.go c id 11983
.go c id 14601
.go c id 11981

Engage and wait until Shadowflame is casted, try to interrupt it.

### CODE REVIEW

**Comment by IntelligentQuantum** [comment]
@Nefertumm It does not work for me :cry: tested with rogue kick

**Comment by Nefertumm** [comment]
@IntelligentQuantum hmm strange, I tested with firemaw. Did you test it with that one too? I will try to test all of them tho

**Comment by temperrr** [comment]
Tested

- [x] You cannot interrupt the shadowflame
- [ ] It does not show the "protected" cast bar, which I think you would expect. (not sure if this is fixable)
image

**Comment by IntelligentQuantum** [comment]
> @IntelligentQuantum hmm strange, I tested with firemaw. Did you test it with that one too? I will try to test all of them tho

My bad, it works fine, I forgot to type this command make install...

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Nefertumm conflicts

**Comment by Nefertumm** [comment]
I'll fix them soon :)

**Comment by Nefertumm** [comment]
Fixed

**Pull request merged**
