### PR TITLE
DB - Death Knights area rework

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
Imported from TrinityCore. Fixes some issues but requires testing before and after considering the differences between AC and TC in WOTLK content

https://github.com/TrinityCore/TrinityCore/commit/d606ee57e2dcda7d7809d2e67a0fdfde1a3882a2
https://github.com/TrinityCore/TrinityCore/commit/3e74ef1528db315c22196822d545b4638c1ca46c

Original work done by @Grz3s on Cmangos (I don't know link)

**Changes proposed:**

-  Fixes scarlet mobs constantly killing players
-  Fixes tons of other things :P

**Target branch(es):** 1.x/2.x etc.

**Issues addressed:**
I don't know if some issues are related to this, feel free to tell me

**Known issues and TODO list:**

- **Requires testing before and after considering the differences between AC and TC in WOTLK content**. We don't know if it removes good fixes from AC or not. It should be tested BEFORE and AFTER if possible

**NOTE** You no longer need to squash your commits, on merge we will squash it for you. (GitHub added a new feature)

### CODE REVIEW

**Comment by Stoabrogga** [comment]
Loaded the SQL script into the DB without errors. I'm currently trying the DK start area and there's one thing which does not feel right: There are 6 Death Knight Initiates outside of Death's Breach standing nearby enemies without fighting. I think these NPCs have the wrong phase mask (1: always visible) and should be corrected:
`UPDATE creature SET phaseMask = 4 WHERE guid IN (129516, 129517, 129518, 129544, 129545, 129555);`
They will then be visible after the Scarlet Crusade is pushed back (after quest "Victory At Death's Breach!").

**Comment by Stoabrogga** [comment]
They are removing game objects and creatures from the old world in order to add new creatures to the DK area. I don't think this is the right way to do it. We should instead reuse the already deleted IDs in the script. I'll rework the SQL script, add a few more fixes (like the one mentioned above) and post it here later.

**Comment by Stoabrogga** [comment]
Here's the reworked SQL script:
[DB_-_Death_knights_area_rework_updated.txt](https://github.com/azerothcore/azerothcore-wotlk/files/2011054/DB_-_Death_knights_area_rework_updated.txt)

Tested it by checking the IDs with a GM account and playing a fresh DK with a normal player account. Changes:
- move delete statements of the original script to the top in order to reuse the deleted IDs (the original script deleted creatures and game objects from the old world)
- use only deleted IDs within the script
- set Death Knight Initiates to correct phase (otherwise they're wandering between the enemies without fighting)
- set correct aura for one of the dead Scarlet Peasants ("Permanent Feign Death" instead of "Devour Humanoid")
- removed additional duplicates of runeforges, anvils and forges (fixes the flickering when pointing with the mouse on it)

**Comment by BarbzYHOOL** [comment]
Ok awesome, I updated and will merge this soon

**Comment by Motorheadx** [comment]
Add code when the death knight came out of the starting area in Orgrimmar or in Stormwind, the guard begins to spit at him to throw bannans

**Comment by Stoabrogga** [comment]
The issue you mentioned is related to the quests "Warchief's Blessing" (13189) and "Where Kings Walk" (13188). I think it would be better to solve this in a separate PR. This one is already complex enough and concentrates on game objects and creatures in the DK area.

**Comment by Middel** [comment]
@Motorheadx here is the fix for that it's included in here: https://github.com/azerothcore/azerothcore-wotlk/issues/642

**Comment by Motorheadx** [comment]
Not works quest 12641.The eye flies very slowly to its destination.As it arrived it can not take control of something to complete a quest

**Comment by Stoabrogga** [comment]
Quest 12641 works fine, finished it 5 times without problems. The same for quest 12701. Analyzing and fixing the other issues will take some time, though.

**Comment by Motorheadx** [comment]
This quest 12641 perhaps on my reason not works.But this 12701 he is done but there are problems with some mobs are impossible to hit!

**Comment by Stoabrogga** [comment]
This is strange, never had this issue, don't remember any enemies evading. Are only the enemy cannons evading or also the Scarlet Defenders?

**Comment by Motorheadx** [comment]
Only Scarlet Defenders

**Comment by Stoabrogga** [comment]
Hmm, I mostly killed those who are running towards my cannon, so cannot reproduce it. It would be better to handle all this issues separately, perhaps someone can help track down the errors.

**Comment by Motorheadx** [comment]
what is there to running  it just shoot and all is not always wait until they come to you

**Comment by BarbzYHOOL** [comment]
Motorheadx, calm down, he tested this SQL in details, and improved it. Please, open another issue for the bugged quests.

This PR will be merged, it's completed.

**Comment by Motorheadx** [comment]
I understand you well =)

**Comment by Stoabrogga** [comment]
Opened PR https://github.com/azerothcore/azerothcore-wotlk/pull/884 for fixing NPC 28611.

**Pull request merged**
