### PR TITLE
fix(DB/Gameobjects): Spirit Candle should properly give buff to nearb…

### LINKED ISSUE #8815: "Spirit Candle" doesn't give buff
### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59

### Current Behaviour

[Spirit Candle](https://wowgaming.altervista.org/aowow/?item=46711) doesn't give buff similar to [Basic Campfire](https://wowgaming.altervista.org/aowow/?spell=818).

WoWScrnShot_102921_130437

### Expected Blizzlike Behaviour

Should have same buff as Basic Campfire

### Source

Description of spell 
> Places a spirit candle that increases the spirits of those nearby by 4.

Wowhead [Spirit Candle](https://www.wowhead.com/item=46711/spirit-candle#comments:id=881694)
>By Ronny on 2009/11/03 (Patch 3.2.2)
Spirit Candle is sold at any major city graveyard during the Day of the Dead. You can place one on the ground for decoration, it lasts for 5 minutes, its cooldown is also 5 minutes, so you can't place two at once. It buffs you similarly to Basic Campfire, but you can use it only during the Day of the Dead

### Steps to reproduce the problem

.additem 46711
use it

### Extra Notes

_No response_

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/b0d4f1917ec82d978121859b2ea45cdc178bb478

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
…y players.

Fixes #8815

## Issues Addressed:

- Closes #8815

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

.event start 51
.additem 46711
Use the Spirit Candle

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by yuanf225** [comment]
I can take the test after I get home from get off work

**Comment by Nyeriah** [comment]
Tested, working as intended, I wonder if the faction thing wouldn't also fix bonfires?

**Comment by acidmanifesto** [comment]
@Nyeriah i can test independently on the campfire. give me a few minutes.

**Comment by acidmanifesto** [comment]
not working for the campfire but that could be a differ issue entirely.

**Pull request merged**
