### PR TITLE
fix(DB/SAI): Thrym

### PR DESCRIPTION
**Pull request by Stoabrogga**
##### CHANGES PROPOSED:
Set Thrym active in order to allow him to continue on his path even if no player is near. This creature like the other giant wandering outdoor creatures (Fel Reavers, Storm Giants etc.) should pose a threat to the player if he stands in their way.

##### ISSUES ADDRESSED:
none

##### TESTS PERFORMED:
tested successfully in-game

##### HOW TO TEST THE CHANGES:
- ```.go creature id 28243```
- just follow the creature around; without being active it won't resume on it's path if the player gets too far away

##### KNOWN ISSUES AND TODO LIST:
none

##### Target branch(es):
Master
 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by pklloveyou** [comment]
RP passed the test, works perfectly

**Comment by pklloveyou** [comment]
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `entry` = 19400;
DELETE FROM `smart_scripts` WHERE `entryorguid` = 19400;
INSERT INTO `smart_scripts` VALUES (19400, 0, 0, 0, 11, 0, 100, 0, 0, 0, 0, 0, 0, 48, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'Fel Reaver - On Respawn - Set Active On');

**Comment by Stoabrogga** [comment]
@pklloveyou 
Thanks for mentioning the Fel Reaver Sentries, but I don't think they need to be active. The whole area "Abyssal Shelf" was designed only for the bombing run "Mission: The Abyssal Shelf" and it's daily counterpart, "Return to the Abyssal Shelf".
It is also important to only set creatures active which absolutely need to move around independently in order to fulfill their role as they will keep their grid active after they were triggered (spawned) by a player for the first time. An active grid costs a little bit of the servers resources.

**Comment by pklloveyou** [comment]
Thanks for the explanation.

**Pull request merged**
