### PR TITLE
fix(CORE/Commands): .Pinfo

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
##### TESTS PERFORMED:
Yes, imported without errors. Checked and tested in game, everything looks fine.

##### HOW TO TEST THE CHANGES:
1: .guild create "Guild Name"
2: .Pinfo
3: Now you can see Guild Name Guild Rank Note Office Note And Xp - Total Xp

##### Target branch(es):
Master

### CODE REVIEW

**Comment by poszer** [comment]
Tested, everything looks fine :+1: 
guildPINFO

**Comment by BarbzYHOOL** [comment]
it looks off on your screen

btw we didn't have an issue with the characters shown?

**Comment by poszer** [comment]
> it looks off on your screen
> 
> btw we didn't have an issue with the characters shown?

Yes. That's how is should be:
Here is my old image:
tcbefore

**Comment by poszer** [comment]
Yes. That's how is looks @BarbzYHOOL 

Old image:
Screenshot_2

**Comment by BarbzYHOOL** [comment]
@poszer the old image is the same as the above, same output shown

**Comment by Sdyess** [comment]
result5, stmt2, etc...

Please use names that are more meaningful. result and stmt can make sense for one result and statement because they are unique to the scope generally, but now you're making it difficult to keep up with the names.

**Comment by IntelligentQuantum** [comment]
https://github.com/azerothcore/azerothcore-wotlk/blob/master/src/server/scripts/Commands/cs_misc.cpp#L1899

**Comment by BarbzYHOOL** [comment]
No, but you can change them in another PR

**Comment by BarbzYHOOL** [comment]
Thank you

**Pull request merged**
