### PR TITLE
Cmake: Enable include file ScriptPCH.h in lib game-interface

### PR DESCRIPTION
**Pull request by Winfidonarleyan**
##### CHANGES PROPOSED:
-  Enable include file ScriptPCH.h in lib game-interface

##### ISSUES ADDRESSED: 
Close https://github.com/azerothcore/mod-learn-spells/issues/5

##### TESTS PERFORMED:
- [x] Build in VS 16 2019

##### HOW TO TEST THE CHANGES:
- Apply PR
- Rebuild modules which used this file

##### KNOWN ISSUES AND TODO LIST:
- [x] Build in Travis

##### Target branch(es): Master

### CODE REVIEW

**Comment by brussens** [comment]
Tested Win10x64. Comliped success.

**Comment by Winfidonarleyan** [comment]
Thanks for test @brussens

**Comment by gbmv33** [comment]
Works only in VS 16 2019?

**Comment by gbmv33** [comment]
tested on ubuntu 18.04.2 LTS and works

**Comment by Deku** [comment]
As far as I can remember, after PR#1423 no script should be using ScriptPCH, so maybe this is a module's fault, not a core one.

**Comment by Winfidonarleyan** [comment]
@Decu, yes, in core no errors, only in old modules

**Comment by Winfidonarleyan** [comment]
Then this PR can be considered useless

**Comment by milestorme** [comment]
Tested with Ahbot, Eluna , buffmaster, npc Services , loremaster . All working again.

**Pull request closed without merging**
