### PR TITLE
fix(Core/Spell): Handle 5,000 Gold with SpellScript

### PR DESCRIPTION
**Pull request by Kitzunu**
## Changes Proposed:
- Properly handle the spell in SpellScripts

## Tests Performed:

- Builds, tested in-game

## How to Test the Changes:

1. .cast 46642

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Asthalor** [comment]
Tested

Server info 6e0082e351393 with changed applied.

When i use the spell with .cast 46642 nothing happens, but the spell exists because i dont get the message *There is no such command*. So its added properly.

Checked in the database and its all good.

Dont know if i should get 5000 gold when used, the test case dont say.

If more test are needed please report them. Until knowing what should happen when using it i dont know if the test is passed or not.

**Comment by Kitzunu** [comment]
Target yourself and do it, you should get 5k gold

**Comment by Asthalor** [comment]
Tested

After focusing on my character(woops) and using  .cast 46642 5000 gold appeared on my inventory.

image

All OK

**Review by FrancescoBorzi — APPROVED** [review]
less core, more scripts/DB. Good!

**Comment by FrancescoBorzi** [comment]
@Kitzunu there are merge conflicts

**Pull request merged**
