### PR TITLE
fix(DB/Quest): Journey to Undercity outro

### PR DESCRIPTION
**Pull request by Kitzunu**
* https://github.com/TrinityCore/TrinityCore/commit/a9d493c4564cdaa7efe400408f3582f1cdbb8cde

Co-Authored-By: Trond B. Krokli <38162891+illfated@users.noreply.github.com>

## Changes Proposed:
-  Fix outro text of Lady Sylvanas
- Proof https://youtu.be/yOgx6GC1Ap8?t=207 && it exist in Broadcast text

## Tests Performed:
- Tested in-game

## How to Test the Changes:

Not needed, but here is the way:

1. .q add 9180
2. .tele RoyalQuarter
3. Hand in the quest and wait on the outro

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
thanks @Killyana and @illfated

**Comment by pklloveyou** [comment]
Mark

**Comment by illfated** [comment]
> Mark

Mark who?

**Comment by Kitzunu** [comment]
We all wonder the same thing lol

**Comment by illfated** [comment]
Oh well, probably spam.

**Comment by FrancescoBorzi** [comment]
> Oh well, probably spam.

no he is one of our testers

**Comment by illfated** [comment]
OK, very well. Should have been @mentioned to make it useful. (Feel free to "hide" the comments above as Resolved.)

**Comment by pklloveyou** [comment]
I use it to mark what I've merged to test

**Comment by pklloveyou** [comment]
Tested

**Comment by FrancescoBorzi** [comment]
> I use it to mark what I've merged to test

thank you very much!

**Pull request merged**
