### PR TITLE
fix(DB/Creature): Infernal hound Type & Tameability

### PR DESCRIPTION
**Pull request by BeefSteaker**
## Changes Proposed:
-  Set Infernal hound to type Demon
-  Remove Tameability

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/14616

## SOURCE:

Retail (blurry)
image
https://youtu.be/WslqTn2ljj0?t=3

Classic
image
https://youtu.be/WslqTn2ljj0?t=3 (set speed slow)

## Tests Performed:

- .npc add temp 19207 with Exotic pets skill learnt

## How to Test the Changes:

.learn 1515
.learn 53270
.npc add temp 19207
attempt to tame

## Known Issues and TODO List:

- [ ] Its unused content, but someone might want to run the dark portal event in the future.
- [ ] at the time the event happened exotic taming didn't exist, so it's hard to determine if it should be tamable. Best guess it shouldn't as tooltips show it as demon

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Nyeriah** [comment]
Wowhead lists them as beasts https://www.wowhead.com/wotlk/npc=19207/infernal-hound#comments

**Comment by heyitsbench** [comment]
> Wowhead lists them as beasts

Not [TBC Wowhead](https://www.wowhead.com/tbc/npc=19207/infernal-hound), wonder what changed it for them.

**Comment by Nyeriah** [comment]
Classic changes well likely

**Comment by BeefSteaker** [comment]
Yeah it's a weird one. It was a quick one to write, and it caused issues on chromie so I thought I'd put it out there

**Comment by Kitzunu** [comment]
Make it a beast. Wrath classic prio tbc

**Comment by Kitzunu** [comment]
Also, WoWHead lists them as Tamable, but turn Core Hound.

**Comment by Kitzunu** [comment]
Imo close the PR, I dont see an issue.

**Comment by Nyeriah** [comment]
They're using https://www.wowhead.com/classic/spell=19483/immolation#used-by-npc which apparently they shouldn't use when tamed, seeing as its a molten core mob spell. I am to guess it was a typo as I don't think this data was acquired through sniffs or any kind of research

As for the PR itself, we don't have enough information on it/sniffs plus it's inaccessible content so I wouldn't do anything about it, as I mentioned when asked about this by @Samsequel

**Comment by BeefSteaker** [comment]
Ok I'll close it. 
Thought the vids I found might be enough to change it in case anyone runs the event in the future.

**Pull request closed without merging**
