### PR TITLE
DB/Quest Escape Through Force&Stealth

### PR DESCRIPTION
**Pull request by poszer**
Quest Escape Through Force & Escape Through Stealth

**CHANGES PROPOSED:**

-  All changes has done in DB ( Updates, SAI Edit) 
-  Sai was set to cast spell 6928 on NPC ( And spell with that id doesn't exist). 
- It's changed to use AURA 6928 (It's Form of the Moonstalker **Invisibility**) 
- Also, the Bear creature has update to correct position

**Closes** 
#189 
#905 
#904
#190 

**TESTS PERFORMED:**
Builded without errors. Tested in game, looks like it's working fine now.
[Test Video](https://youtu.be/KtVx5tB-0zg)
Also have tested this second quest ( Escape Through Stealth ) how it should working.
Since the Npc will use invisibility aura, there is no chance that he can be attacked by mobs.
The quest will be done after NPC leave that cave
I'll include video from other Emu's how the quest is done.
[Video show: How it should be](https://www.youtube.com/watch?v=y5AMXINUv3Q)

**HOW TO TEST THE CHANGES:**
.go xyz 4601.410645 -4.852083 69.678398
.quest add 993
Complete it by handing quest to NPC near you '' Volcor ''
After that try to do these two quests from Volcor :

1. Escape Through Force
2. Escape Through Stealth

**Target branch(es):**

Master

### CODE REVIEW

**Comment by wetbrownsauce** [comment]
Tested.  

-Both Escape through Force and Stealth complete successfully.
-In Escape Through Stealth, Volcor correctly stealths and is not attacked by mobs.
-In Escape Through Force, Volcor paths all the way to the proper road, fighting things along the way.

I cannot confirm if the mobs were correct during Escape Through Force, I fought the already spawned enemies at the entrance of the cave during the escort, whereas videos such as [this](https://youtu.be/wDJ4Un0EuJQ?t=1616) show 2 extra groups of enemies which spawn later during the escort.

**Comment by Nefertumm** [comment]
Should we merge this? @wetbrownsauce

**Comment by wetbrownsauce** [comment]
I would merge it since it does correct the issues that currently prevent the quest from being completed. I'm not sure if the mob spawns during the escort are correct but I suppose that is a separate issue from this.

**Comment by poszer** [comment]
> 
> 
> Should we merge this? @wetbrownsauce

Since the quest was fcked totally before, i don't see any reason why not? It's fixed almost at all, just some npcs aren't spawned outside, but all other things works perfectly

**Comment by Nefertumm** [comment]
I'll merge then :) Thanks @poszer and @wetbrownsauce.

**Pull request merged**
