### PR TITLE
feat(DB): Test accounts using various GM levels

### PR DESCRIPTION
**Pull request by BarbzYHOOL**
## CHANGES PROPOSED:
- Differentiate 5 different type of test accounts for quick testing. People should rename/remove/change password from them though
- Add new column `comment` to "account_access"

Read some stuff from here for the default value https://dba.stackexchange.com/questions/28086/empty-longtext-or-null and other links, so I decided to make the comment empty instead of null 

## ISSUES ADDRESSED:
- Closes https://github.com/azerothcore/azerothcore-wotlk/pull/1417 (old PR of mine)

## TESTS PERFORMED:
- None yet, if someone can test, it'd be cool or just remind me
-

## HOW TO TEST THE CHANGES:

Just run the SQL and see if any error (for the UPDATE statements)

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
if wanted, i can remove the lock, I don't know I put it just in case

it should work now

**Comment by Meltie2013** [comment]
@BarbzYHOOL Suggestion for you, instead of directly adding this to the auth database. You should have it as a option to install. Don't get me wrong, its nice to have; but some can be forgetful about the test accounts.

:+1:

**Comment by BarbzYHOOL** [comment]
it will only update if the test accounts match the name and hash_pass, so if they have not been modified only (I asked francesoc borzi for that)

**Comment by FrancescoBorzi** [comment]
@Meltie2013 this is not affecting existing servers where those accounts have been deleted/modified

**Comment by FrancescoBorzi** [comment]
what's the status of this? has it been tested?

**Comment by BarbzYHOOL** [comment]
you tested it francesco if i recall :P

**Comment by FrancescoBorzi** [comment]
@BarbzYHOOL I only tested the 2 types of queries one by one, not the full thing

**Comment by Kaev** [comment]
- You only change account_access.comment instead of account_access.gmlevel
- You shouldn't have the password hashes in the query since it's possible that people have changed the passwords for their test accounts (let's hope people did this for their public servers atlest...)

**Comment by FrancescoBorzi** [comment]
> You shouldn't have the password hashes in the query since it's possible that people have changed the passwords for their test accounts (let's hope people did this for their public servers atleast...)

@Kaev that's on purpose: so we only change for those accounts which still have the default values

**Comment by gengarshadowball** [comment]
Everything looks good:

image

**Comment by BarbzYHOOL** [comment]
ty gengar

**Comment by gengarshadowball** [comment]
I found an issue that I didn't find when testing:
```/* SQL Error (1314): LOCK is not allowed in stored procedures */```

Maybe revert merge, remove the lock and merge again?

**Pull request merged**
