### PR TITLE
fix(Core/GameObjects): Creating gameobject's model requires set go st…

### LINKED ISSUE #5180: Vmap issues: Invisible collision + creature spawn
## CURRENT BEHAVIOUR:

After integration of pull request #4922 by @UltraNix there are some new issue. In the client there are some invisible collisions like the one on the screenshot. This collision is there to prevent players to cover NPC on this place.
The problem is that those NPCs cant spawn at this place anymore and fall throw the floor.

image

## EXPECTED BLIZZLIKE BEHAVIOUR:

- Need to remove invisible collision from vmap / mmap
- Or make it possible NPC spawns to ignore it

## STEPS TO REPRODUCE THE PROBLEM:

1. .go xyz 4938 2389 327 631
2.  See that NPCs are not there (they are under the floor)

## AC HASH/COMMIT:

a298803

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/97693775-vmap-issues-invisible-collision-creature-spawn?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UltraNix**
…ate.

Fixed #5180.

## Issues Addressed:
- Closes #5180.

## Tests Performed:

- Not tested ingame.

## Target Branch(es):
- [x] Master

 
## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by pklloveyou** [comment]
image

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by FrancescoBorzi** [comment]
@Footman please have a look at this

**Comment by pklloveyou** [comment]
There are still mistakes

**Comment by UltraNix** [comment]
@pklloveyou Try again.

**Comment by pklloveyou** [comment]
Tested 
image

**Comment by UltraNix** [comment]
Can be merged?

**Comment by pklloveyou** [comment]
merged

**Comment by Stifler82** [comment]
@UltraNix is it possible that this PR has broken this mechanism?
**(it's not something that happens all the time)**

**Video Test:** [GameObjects](https://youtu.be/zY6wZ7NbxKg)

This is the issue:
`https://github.com/chromiecraft/chromiecraft/issues/415`
**P.S.**
**(I'm posting it like this because I don't want to link the Issue to this PR if the PR has nothing to do with the problem)..**

**Comment by UltraNix** [comment]
You mean taht weird dissappearing? Than no.

**Comment by Stifler82** [comment]
> You mean that weird dissappearing? Than no.

@UltraNix 
It is not only that, but the GameObject appears while it is despawned, So this creates that the Player sees the GameObject but actually the GameObject has yet to respawn.
Do you understand what I mean?

**Comment by UltraNix** [comment]
I understand. You can just test if this bug occurs with this PR or not.

**Comment by FrancescoBorzi** [comment]
> I understand. You can just revert that commit and test if it still bugged.

so the commit is this one: https://github.com/azerothcore/azerothcore-wotlk/commit/c860b4422c9f64d41405a024c55ae2e1b87650a1

now **How to revert it and test**:

1) go back to master branch first: `git checkout master`
2) create a new branch: `git checkout -b test-revert-commit-ultranix`
3) revert the commit: `git revert c860b4422c9f64d41405a024c55ae2e1b87650a1`
4) recompile your core
5) do your test ....
6) when you are done, you can go back to master branch and keep working `git checkout master`

**Pull request merged**
