### PR TITLE
fix(DB/Smartscript): [AQ20] Shrieker/Spitting Scarab smartscript improvement

### PR DESCRIPTION
**Pull request by temperrr**
## Changes Proposed:
-  set initial min/max based on sniffed values from @Gultask 
- set random target based on video in liked issue

## Issues Addressed:

- Closes https://github.com/chromiecraft/chromiecraft/issues/3932

## Tests Performed:

- not tested

## How to Test the Changes:

1. Engage shrieker scarab with multiple players in aq20
2. see that they wont charge at the same time and go to a random target

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Gultask** [comment]
I have some packets ready for repeat timers and ymir updated overnight so now I can take initial timers too. Give me 1 hour or so and I'll get back to you :)

**Comment by temperrr** [comment]
Even better

**Comment by Gultask** [comment]
Btw, it's both scarabs that should be changed, they both currently charge on pull 😛 

Shrieker Scarab (Initial):
Charge 7200-20600
Shriek 7200-14500

Spitting Scarab (Initial):
Charge 15700-18200
Spit 7200-16900

Shrieker Scarab (Repeat):
Charge 10900-19400
Shriek 12100-20600

Spitting Scarab (Repeat):
Charge 14600-20600
Spit 9700-19400

**Comment by temperrr** [comment]
@Gultask 

I updated the PR with your values.

**Comment by Gultask** [comment]
Looks good to me! Just remove the interrupt flag from the Spitting Scarab so it doesn't interrupt Acid Spit ^^

**Review by Nefertumm — APPROVED** [review]

**Pull request merged**
