### PR TITLE
Populate Ironforge Airfield and Wetlands Farm

### PR DESCRIPTION
**Pull request by banehammer**
## Changes Proposed:
-  Populates Ironforge Airfield and Wetlands Farm
-  

## Issues Addressed:

- Closes https://github.com/azerothcore/azerothcore-wotlk/issues/6994

## Tests Performed:

- Walked around to confirm that no bugs or weird movement is appearing.
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by jamadaha** [comment]
Does this close https://github.com/azerothcore/azerothcore-wotlk/issues/6994?

**Comment by banehammer** [comment]
@jamadaha Yes it does plus the unpopulated Wetlands Farm.
Though this is only a blueprint. I will update it accordingly throughout the evening.

**Comment by FrancescoBorzi** [comment]
@banehammer the build is broken

**Comment by banehammer** [comment]
There is something wrong with this PR. Will reopen one.

**Pull request closed without merging**
