### PR TITLE
fix(DB-Core/Ulduar): Expedition base camp - Beam

### LINKED ISSUE #3528: Ulduar Base Camp - Mage channel beam
##### CURRENT BEHAVIOUR:
In the Expedition Base Camp in Ulduar, the two Kirin Tor Battle-Mages nearest the shield are not channeling any spells.

##### EXPECTED BLIZZLIKE BEHAVIOUR:
The Kirin Tor Battle-Mages nearest the shield should be channeling a purple energy beam at the shield while it is up, connecting to the two spots visible above. 
https://www.youtube.com/watch?v=_79ba-tIGF8 Video shows blizzlike behavior

##### STEPS TO REPRODUCE THE PROBLEM:
Enter a fresh lockout of Ulduar and look at the shield.

##### EXTRA NOTES:
The channel target NPCs appear to be present, but they are on the ground instead of hovering in place.

##### AC HASH/COMMIT:
e9bce8a

##### OPERATING SYSTEM:
Win 10

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/93265784-ulduar-base-camp-mage-channel-beam?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F40032087&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Si1ker**
This change will fix the current non-functional beam effect at the expedition base camp.
The visual path-lightning effect of the spell is not 100% accurate but will work for this intention. The visual may have been modified in other expansions so if someone wants to spend hours-days-weeks looking for the exact 100.0% accurate spell.. feel free to do it 😹   at the moment is looking pretty cool with this change and.. is working ! 😼 

Reference: https://www.youtube.com/watch?v=_79ba-tIGF8
(0:45)

## CHANGES PROPOSED:
- Include the NPC ID of 'Ulduar shield bunny' into the leviathan script
- Kill both 'Ulduar shield bunny' when the dialog reaches the order for the mages to release the shield
- Fix the position of both flying 'Ulduar shield bunny' that are located at the visual effect zones on the shield bubble
- Place the third 'Ulduar shield bunny' to phase 2 since I do not find a use for it but it's better to have it as backup
- Create a SAI for the Kirin Tor Battle-Mage so these can cast the beam to the 'Ulduar shield bunny'

## ISSUES ADDRESSED:
- Closes #3528 

## TESTS PERFORMED:
- Applied SQL and C++ changes with no problem found
- Tested in-game activating the event as normal mode (speaking with Brann) and hard mode (speaking with Norgannon) for Leviathan

## HOW TO TEST THE CHANGES:

**Before applying the changes**
- Go to the Ulduar instance
- Go to the entrance of the expedition base camp, notice the shield is up but nobody is casting it in order to keep it up

**After applying the changes**
- Go to Ulduar
- Go to the entrance of the expedition base camp, notice that both Kirin Tor Battle-Mages are keeping the shield up
image

- Speak either with Brann (normal mode) or Norgannon (hard mode) to start the event for Leviathan
image

- At the time the Kirin Tor Battle-Mages receive the order to release the shield, they will stop casting
image

## KNOWN ISSUES AND TODO LIST:

- [ ]
- [ ] 

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by aradep** [comment]
(Not 100% on testing PRs. After checkout the revision showed correctly but I had to manually apply the changes to get them to work.) 

Fix works perfectly except for 1 thing: If the server restarts before the bunny NPCs have respawned, the beam effect doesn't work.  https://wotlkdb.com/?spell=48310 looks like the correct spell.

**Comment by Si1ker** [comment]
@aradep Thanks for testing, I've updated the spell into the SAI, I don't have an idea regarding the server restart thing.

@wizzymore I think you've done it with the oculus right, if possible, do you have any suggestions in this scenario?

The Object and bunnies should be saved into the instance I think, but I haven't done anything like that.
The object should be deleted as the script suggested it does.. but it will still appear after the sv reset, also both bunnies should remain dead, is an "only one-time" thing.

@Kitzunu  cc 🐱

**Comment by Kitzunu** [comment]
Cant we spawn them in db and just despawn them with a sai or core script?

**Comment by wizzymore** [comment]
@Si1ker sure i will handle this.

@Kitzunu the problem is that with the current script, the barrier, mages casting and the vehicles will get restored as if you just entered the instance, this is not correct, you should atleast have the vehicles up again and the barrier down, without having to do the RP again.

**Comment by wizzymore** [comment]
Current bugs before boss leviathan:
- NPC's only have the texts scripted, they don't have any waypoints
- The barrier and the beams are removed way to soon
- If the server restarts the following reset:
- - Brann NPC
- - Barrier gets added back
- - Beams are again on
- - Vehicles are not spawned

**Comment by wizzymore** [comment]
Hi,

The base camp is now blizzlike (timing more or less in seconds but it's a huge improvement)
You can find my changes here tell me how we should proceed.
https://github.com/wizzymore/azerothcore-wotlk/tree/ulduar_mages
If you want me to PR to your branch, please update your branch.

**Comment by Si1ker** [comment]
Hi @wizzymore , yeah that's the way to go, in another PR..
I made little changes just to address the issue and just that, not as much as you did, which involves a range of different issues into just one PR, for that reason it's better to close this one and keep it closed for informational purposes.

### This issue will be addressed on #3558

**Pull request closed without merging**
