### PR TITLE
fix(DB/Quest): A Portabale Power Source

### PR DESCRIPTION
**Pull request by Kitzunu**
## CHANGES PROPOSED:
-  Change location of the POI

## TESTS PERFORMED:
- Builds
- tested in-game

## HOW TO TEST THE CHANGES:

Current 
image

How it should be (Since the item drops from Magma Lord Bokk that is in Burning Steppes
image

1. .q add 8925
2. Open map and see that the Quest POI is in the wrong zone

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by aradep** [comment]
POI works, but if you click the (1) marker before the quest is complete, it shows Tanaris (questgiver location). Not sure if this is intended

image

**Comment by Racknar0** [comment]
The point should show where the mission is completed when the map is opened 
Tested

image

**Comment by Gierlappen** [comment]
Thx @Racknar0 ! Can you confirm what @aradep meant when you click the (1)?

**Review by FrancescoBorzi — APPROVED** [review]

**Comment by Racknar0** [comment]
> Thx @Racknar0 ! Can you confirm what @aradep meant when you click the (1)?

When one takes quest and follows them up they appear on the right side 

image

And they are listed according to how they are marked as follow-up

image

But it should not be mandatory to give the number so that the mission appears in the correct POI

**Review by Si1ker — APPROVED** [review]

**Comment by Si1ker** [comment]
@Kitzunu core-build / ubuntu-20.04-clang-without-modules (pull_request)
failing  ;c

**Comment by FrancescoBorzi** [comment]
looks like not caused by the PR itself, restarting the build

**Pull request merged**
