### PR TITLE
fix(DB/pool_template): improve spawn quantity of herbs in northrend

### PR DESCRIPTION
**Pull request by Helias**
improve spawn quantity of herbs in Northrend

## CHANGES PROPOSED:
-  improve the quantity of spawned herbs in Northrend  

## ISSUES ADDRESSED:
- related to https://github.com/azerothcore/azerothcore-wotlk/issues/1857

## TESTS PERFORMED:
- Only executed the SQL query, but in the issue two users already tested it

## HOW TO TEST THE CHANGES:
Check the spawned herbs in Storm Peaks (read the issue comments for more details).

## Target branch(es):
- [x] Master

 
## How to test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here in the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

### CODE REVIEW

**Comment by felwyn** [comment]
Fix approved! More herbs are now spawning in this zone! More than enough 👍

**Review by FrancescoBorzi — APPROVED** [review]

**Review by Knindzagxg — APPROVED** [review]

**Comment by Mamaro89** [comment]
> Fix approved! More herbs are now spawning in this zone! More than enough 👍

What fix?

**Comment by Helias** [comment]
No, it affects only herbs

**Comment by BarbzYHOOL** [comment]
Mamaro is right, I post a new issue about ores

**Pull request merged**
