### PR TITLE
fix(DB/SAI): Heb'Jin should not evade on attack. Source: TrinityCore.

### LINKED ISSUE #12209: [quest] `Bringing Down Heb'Jin`  bug
### Current Behaviour

Right click on `Heb'Jin's Drum` (object id 190695),When `Heb'Jin` came, he immediately left the battle and went back

https://youtu.be/bY2IqW9TUj8

### Expected Blizzlike Behaviour

Right click on `Heb'Jin's Drum` (object id 190695),When `Heb'Jin` came, He will fight the players

From 1 minute 06 seconds
https://www.youtube.com/watch?v=Qun6VBqNUWU

### Source

_No response_

### Steps to reproduce the problem

1. .q a 12662
2. .go xyz 5924.003418 -3803.821777 363.599518 571
3. Right click on `Heb'Jin's Drum` 

### Extra Notes

from 8151fcda22c6167211d1c08788791fe1ad9e2c44 to 38889324b2bd4a77b47bf4774753198e280723ec, Then it will not work

8151fcda22c6167211d1c08788791fe1ad9e2c44  work..

38889324b2bd4a77b47bf4774753198e280723ec  not work

### AC rev. hash/commit

38889324b2bd4a77b47bf4774753198e280723ec

### Operating system

Ubuntu20.04

### Custom changes or Modules

_No response_

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #12209

## Issues Addressed:

- Closes #12209

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

`.q a 12662`
`.go xyz 5924.003418 -3803.821777 363.599518 571`
Right click on Heb'Jin's Drum

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by mpfans** [comment]
There is still a bug After killing Heb'Jin, the bat will go back by itself, give up the quest, and then get the quest again. When Heb'Jin refreshes, he will play the drum again When Heb'Jin comes down, he will ride back with a bat Then you can't kill again

**Comment by UltraNix** [comment]
@mpfans I don't understand at all. Please, record video of this.

**Comment by mpfans** [comment]
https://discord.com/channels/@me/843005002199990282/992758413568262154

When `Heb'Jin` came down, I used `bat net` for bats

**Comment by UltraNix** [comment]
@mpfans Try again.

**Comment by mpfans** [comment]
> @mpfans Try again.

Retest: after using `bat net`, they will separate and run back out of the battle

**Comment by UltraNix** [comment]
@mpfans Try again.

**Comment by mpfans** [comment]
```
2 queries executed, 1 success, 1 errors, 0 warnings

查询：DELETE FROM `smart_scripts` WHERE `entryorguid`=28639 AND `source_type`=0 AND `id` IN (8,9)

共 0 行受到影响

执行耗时   : 0.001 sec
传送时间   : 0.001 sec
总耗时      : 0.002 sec
--------------------------------------------------

查询：INSERT INTO `smart_scripts` VALUES (28636,0,8,5,61,0,100,0,0,0,0,0,0,19,256,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'On Update - Remove Immu...

错误代码： 1062
Duplicate entry '28636-0-8-5' for key 'smart_scripts.PRIMARY'

执行耗时   : 0 sec
传送时间   : 0 sec
总耗时      : 0.001 sec
```

**Comment by mpfans** [comment]
Retest: work, but always feel that something is wrong

**Comment by mpfans** [comment]
https://youtu.be/10NMSMUsMJk

**Comment by UltraNix** [comment]
Time to rewrite that sh*t :)

**Comment by UltraNix** [comment]
@mpfans Should be okay now

**Review by IntelligentQuantum — APPROVED** [review]

**Comment by mpfans** [comment]
nice!good job!!!!

**Comment by acidmanifesto** [comment]
Thank you for the PR

**Pull request merged**
