### PR TITLE
fix(Scripts/MoltenCore): Ragnaros should change its main target to so…

### LINKED ISSUE #10363: Ragnaros thrash mechanic not working properly
Original CC Issue: https://github.com/chromiecraft/chromiecraft/issues/2857

### Current Behaviour

Ragnaros attacks at ridiculous speed doing far over 10k dps to players in melee range when someone outside of range takes or has aggro, and there is still another player in melee range.

### Expected Blizzlike Behaviour

Ragnaros should always attack a player in melee range if there is a player in melee range. He should be attacking at a standard speed with the occasional thrash granting an extra attack.
When a tank gets knocked back out of range, he should turn and continue normally attacking other players in melee range.

### Source

_No response_

### Steps to reproduce the problem

1. Have tank and other melee player in combat with Ragnaros.
2. Have the tank step out of range of Ragnaros.

Alternatively.
1. Have tank fighting Ragnaros with threat.
2. Have any other player not in melee range pull threat.

In both scenarios, the player without threat in melee range gets hit so fast that that they die instantly.

### Extra Notes

This issue can be seen for small timeframes causing wipes on Ragnaros in these common scenarios:

The Main tank gets knocked back by Wrath of Ragnaros, and still has threat when the Offtank goes in. Offtank gets melted.

The Main tank comes back in with charge or other ability, while the Offtank taunts before moving in fully. Main tank gets melted.

The Main tank comes back in with charge or other ability, the Offtank has moved in and taunted, but moves out before the Main tank regains aggro. Main tank gets melted.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/259b9133f68ef0d740fc871d59fab3d2791f33b4

### Operating system

Windows 10

### Custom changes or Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-save-inventory](https://github.com/Nyeriah/mod-save-inventory)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### PR DESCRIPTION
**Pull request by UltraNix**
…meone in melee range if main tank is too far away.

Fixes #10363

## Issues Addressed:

- Closes #10363
- Closes https://github.com/chromiecraft/chromiecraft/issues/2857

## Tests Performed:

- Not tested.

## How to Test the Changes:

Have tank and other melee player in combat with Ragnaros.
Have the tank step out of range of Ragnaros.

Alternatively.

Have tank fighting Ragnaros with threat.
Have any other player not in melee range pull threat.

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by temperrr** [comment]
Tested;

not working.

ragnaros still goes haywire on previous tank when you taunt when not in melee range.
as in 1 attack every 0.5 sec orso.

**Comment by UltraNix** [comment]
@temperrr More info how to reproduce it?

**Comment by UltraNix** [comment]
@temperrr Test it again.

**Comment by temperrr** [comment]
```/mnt/data/azerothcore/src/server/scripts/EasternKingdoms/BlackrockMountain/MoltenCore/boss_ragnaros.cpp:481:36: fatal error: use of undeclared identifier 'EVENT_MAGMA_BLAST_MELEE_CHECK'
            events.RescheduleEvent(EVENT_MAGMA_BLAST_MELEE_CHECK, 10000, PHASE_EMERGED, PHASE_EMERGED);```

**Comment by UltraNix** [comment]
@temperrr Done.

**Comment by temperrr** [comment]
sadly not working :/

image

**Comment by UltraNix** [comment]
@temperrr ?? It's debuff, not melee. And I don't see any timestamps here.

**Comment by temperrr** [comment]
That's what is getting refreshed if you do the instructions. Like every second or half

**Comment by UltraNix** [comment]
Just tested and works okay. Please, retest on the newest update..

**Comment by acidmanifesto** [comment]
We need confirmation before we can consider merging this pr.

**Comment by temperrr** [comment]
Yep it was dumdum move on my part

**Comment by UltraNix** [comment]
@LukasVolgger Why you added the "Ready to be reviewed" label? It's not needed here. The code is okay.

**Comment by LukasVolgger** [comment]
My bad!

**Pull request merged**
