### PR TITLE
fix(Scripts/Spells): Sweeping Strikes - improvements.

### LINKED ISSUE #11594: [Warrior] Issues with Sweeping Strikes.
https://github.com/chromiecraft/chromiecraft/issues/3444

### What client do you play on?

enUS

### Faction

- [X] Alliance
- [X] Horde

### Content Phase:

- [X] Generic
- [ ] 1-19
- [ ] 20-29
- [ ] 30-39
- [ ] 40-49
- [ ] 50-59
- [ ] 60

### Current Behaviour

1. Sweeping Strikes will not trigger from auto-attacks
2. Whirlwind triggers and consumes too many charges from Sweeping Strikes and does too many additional attacks
3. Cleave consumes just one charge of Sweeping Strikes and making just one additional attack

Edit: 
4. Thunder Clap is also using too many charges, but I'm unsure what is the blizz-like behaviour

https://user-images.githubusercontent.com/100873791/166152297-1ac44bcc-cdea-47b8-98e9-757beebfe7a9.mp4

### Expected Blizzlike Behaviour

1. Auto-attacks should consume a charge of Sweeping Strikes and make one additional attack.
2. Whirlwind should only consume one charge of Sweeping Strikes and make just one additional attack.
3. Cleave should consume two charges of Sweeping Strikes and make 2 additional attacks.

### Source

From @Cooties-cc:
>[Here is a PvP video from 8/1/2010](https://www.warcraftmovies.com/movieview.php?id=159107) which should be during the 3.3.5 patch (june 22, 2010), but before the cata prepatch (oct 12, 2010). 
At the 1:19 mark, he intercepts a warlock with a pet out. He then casts sweeping strikes, and follows with a heroic strike that procs sword specialization (extra normal melee swing). The game registers 2 uses of sweeping strikes, bringing the buff down to 3 charges. The MSBT addon also shows 2 procs of sweeping strike damage (1002, 1154) on his pet. Here is an image from the video to get a clearer view. 
<a href="https://imgur.com/UbwL6ec"></a>
This also in part shows that SS can be consumed from extra swings. It also shows that it's a normal extra attack against a 2nd nearby mob, and not based on damage done from main attack (as I saw another closed ticket about SS damage). 
Also at 1:27 mark, he does an auto+MS, which registers 2 sweeping charges used. So normal whites (assuming you may think sword specialization was considered a special attack) should be procing SS. 
<a href="https://imgur.com/bxt1B1l"></a>

[From Wowhead (archived)](https://web.archive.org/web/20110612030818/http://www.wowhead.com:80/spell=12328):
>Using cleave while under the effect of Sweeping Strikes will consume two charges, and make two additional attacks. So if you're fighting two ennemies, Sweeping Strikes + Cleave = 2 hits on each.
That being said, Whirlwind (or one second of bladestorming) will only consume ONE charge per spin, not 4 (maximum number of targets of whilrwind = 4), hitting an additional target per whrilwind, not per ennemy hit by the whirlwind.

>Useful for PVP when fighting against a player with a pet.
You can use this and cleave, it will damage the player, and then sweeping strikes will proc off your cleave attack on his pet, thus making him take another hit.

>I would prefer if this procs of special attacks and not white attacks

>Using Whirlwind with Sweeping Strikes will only generate one additional attack.

### Steps to reproduce the problem

Activate Sweeping Strikes when you have two targets nearby.
Use auto-attack and see no additional attacks or charges consumed
Use cleave and see only 1 additional attack and charge consumed
Use whirlwind and see it consuming more than 1 charge and making more than 1 attack

### Extra Notes

I thought that since this is all concerning consuming charges, that maybe it'd be good to group all 3 issues together. Please let me know if I should keep it separate and I'll create 2 more issues.
Bladestorm works fine, only one charge consumed per tick. Maybe that'll help with fixing Whirlwind?.
Seems like the ability to proc twice off of Cleave was added late in WotLK, given the comments in the Wowhead page.

### AC rev. hash/commit

https://github.com/chromiecraft/azerothcore-wotlk/commit/59e45c251eb53abb0ed4b37a57254cbdf415e69a

### Operating system

Ubuntu 20.04

### Modules

- [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
- [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
- [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
- [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
- [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
- [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
- [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
- [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
- [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
- [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
- [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
- [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
- [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
- [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
- [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
- [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
- [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
- [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
- [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
- [mod-transmog](https://github.com/azerothcore/mod-transmog)
- [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
- [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
- [lua-exchange-npc](https://github.com/55Honey/Acore_ExchangeNpc)
- [lua-custom-worldboss](https://github.com/55Honey/Acore_CustomWorldboss)
- [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
- [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
- [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
- [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
- [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
- [lua-zone-debuff](https://github.com/55Honey/Acore_ZoneDebuff)

### Customizations

None

### Server

ChromieCraft

### PR DESCRIPTION
**Pull request by UltraNix**
Fixes #11594

 

## Issues Addressed:

- Closes #11594
- Closes https://github.com/chromiecraft/chromiecraft/issues/3444

## Tests Performed:

- Tested ingame.

## How to Test the Changes:

More info [here](https://github.com/azerothcore/azerothcore-wotlk/issues/11594)

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Maelthyrr** [comment]
Some issues:

- [ ] When auto-attack, additionnal attack proc beefore the auto-attack
- [ ] Cleave consume only stack and do only one additionnal attack (The repport say 2 charge consume for 2 additionnal attacks)
- [ ] Whirwind consume more than one charge and do more than one additionnal attack (The repport say only one charge and one additionnal attack)

**Comment by UltraNix** [comment]
@Maelthyrr 
` When auto-attack, additionnal attack proc before the auto-attack`
WoWScrnShot_050822_101539
I see no bug here.

`Cleave consume only charge and do only one additionnal attack (The repport say 2 charges consume for 2 additionnal attacks)`
WoWScrnShot_050822_102036
Again, see no bug here. 2 cleave hits - 2 SS hits

`Whirwind consume more than one charge and do more than one additionnal attack (The repport say only one charge and one additionnal attack)`
WW is an AoE spell and it works as Cleave.
With one weapon:
WoWScrnShot_050822_102246
3 WW hits - 2 SS hits.

With two weapons:
WoWScrnShot_050822_102617
6 WW hits (2 per target) and only 3 SS hits.

I see everything works okay to me.

**Comment by Maelthyrr** [comment]
@UltraNix you have right. It's only to visual bugs, but I think that it's come from the client ?

https://youtu.be/FxHrKjdvyQM

**Comment by UltraNix** [comment]
@Maelthyrr Just look at your combat log.

**Comment by mpfans** [comment]
Please merge as soon

**Comment by Nefertumm** [comment]
Build failing

**Comment by UltraNix** [comment]
@Nefertumm Done.

**Review by Nyeriah — APPROVED** [review]

**Pull request merged**
