### PR TITLE
feat(Core/Unit): Implement DoCastRandomTarget() helper

### PR DESCRIPTION
**Pull request by Nyeriah**
## Changes Proposed:
-  Implement DoCastRandomVictim() helper

```cpp
if (Unit* target = SelectTarget(SELECT_TARGET_RANDOM, 0, 100, true))
{
    DoCast(target, SPELL_IMMOLATE);
}
```
Becomes:
```cpp
DoCastRandomVictim(SPELL_IMMOLATE, 0, 100.0f);
```

Or simply:
```cpp
DoCastRandomVictim(SPELL_IMMOLATE);
```

## Issues Addressed:

- Closes 

## Tests Performed:

- Tested in-game.
- 

## How to Test the Changes:

1. Check if The Beast @ UBRS still casts immolate on a random target
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Comment by Kitzunu** [comment]
Isn't "victim" always referred to as the current target with the highest threat? Could be confusing. Perhaps rename it to DoCastRandomTarget?

Also what about adding a parameter like "bool allowVictim" or similar, to allow or disallow throwing the spell on the target with the highest/second-highest threat. Usually the one or two tanks. Or perhaps uint32 threatTablePosition does that?
But I do believe that there are some mechanics where a boss should send a random spell to any character that isn't the tank

**Comment by Nyeriah** [comment]
> Isn't "victim" always referred to as the current target with the highest threat? Could be confusing. Perhaps rename it to DoCastRandomTarget?
> 
> Also what about adding a parameter like "bool allowVictim" or similar, to allow or disallow throwing the spell on the target with the highest/second-highest threat. Usually the one or two tanks. Or perhaps uint32 threatTablePosition does that? But I do believe that there are some mechanics where a boss should send a random spell to any character that isn't the tank

Yes, threatTablePositon does that, it follows the same logic as the previous method. By default it selects any random target (tanks included), but you can change that as you wish like before

```cpp
DoCastRandomVictim(SPELL_IMMOLATE, 1, 100.0f);
```

will skip the tank

I'll change it to RandomTarget

**Comment by Kitzunu** [comment]
>Yes, threatTablePositon does that, it follows the same logic as the previous method. By default it selects any random target (tanks included), but you can change that as you wish like before
>
>DoCastRandomVictim(SPELL_IMMOLATE, 1, 100.0f);
will skip the tank

nice I did not know this =)

**Review by Kitzunu — APPROVED** [review]

**Comment by Kitzunu** [comment]
looks good

**Review by Nefertumm — APPROVED** [review]
Excellent, this is nice. In the future, maybe we can accept a predicate as parameter too. :)
Also, I think this is a really good method since we can skip checking if the target is valid within the creature script.

**Pull request merged**
