### PR TITLE
Core/Packet: Pet

### PR DESCRIPTION
**Pull request by IntelligentQuantum**
## Changes Proposed:
-  Class base packet
-  cleanup

## Issues Addressed:

- Closes 

## SOURCE:

TC
## Tests Performed:

- 
- 

## How to Test the Changes:

1.
2.
3.

## Known Issues and TODO List:

- [ ]
- [ ]

## How to Test AzerothCore PRs
 
When a PR is ready to be tested, it will be marked as **[WAITING TO BE TESTED]**.

You can help by testing PRs and writing your feedback here on the PR's page on GitHub. Follow the instructions here:

http://www.azerothcore.org/wiki/How-to-test-a-PR

**REMEMBER**: when testing a PR that changes something **generic** (i.e. a part of code that handles more than one specific thing), the tester should not only check that the PR does its job (e.g. fixing spell XXX) but **especially** check that the PR does not cause any regression (i.e. introducing new bugs).

**For example**: if a PR fixes spell X by changing a part of code that handles spells X, Y, and Z, we should not only test X, but **we should test Y and Z as well**.

### CODE REVIEW

**Review by Winfidonarleyan — APPROVED** [review]

**Comment by claudiodfc** [comment]
Can you merge conflicts? @Nefertumm

**Comment by IntelligentQuantum** [comment]
> Can you merge conflicts @IntelligentQuantum

Done

**Comment by claudiodfc** [comment]
Let me know if there's anything else that needs a test.
##### Test case
- Taming pet and using pet create command working
- Stable pets also works
- Abandoning pet and learning also works
- Attacking NPCs with pet also works

**Comment by acidmanifesto** [comment]
@IntelligentQuantum we have merge conflicts.

**Comment by FrancescoBorzi** [comment]
@IntelligentQuantum please fix the merge conflicts and the failing build

**Comment by temperrr** [comment]
[ 17%] Building CXX object src/server/game/CMakeFiles/game.dir/Handlers/PetHandler.cpp.o
/mnt/data/azerothcore/src/server/game/Handlers/PetHandler.cpp:948:10: fatal error: use of undeclared identifier 'pet'
    if (!pet)
         ^
1 error generated.

**Pull request merged**
